### ISSUE TITLE
mat-select is empty if selected option has value 0

### ISSUE THREAD

**Issue by Etchelon** [ngx-formly/ngx-formly#1029]
I have this problem:
![image](https://user-images.githubusercontent.com/4141889/42557128-eefd638a-84ed-11e8-9a28-3e6a49352361.png)
The mat-select's selected option is "Active", and its value is 0 (NOT "0").
The placeholder (status) doesn't float. I used Augury to check the component's state and I noticed this:
![image](https://user-images.githubusercontent.com/4141889/42557189-1b1e28d2-84ee-11e8-9599-61675238be71.png)

I checked why the FormlyWrapperFormField is empty and found the following line of code:
https://github.com/formly-js/ngx-formly/blob/b56c8aa9381215103b194c042e008134da617bd6/src/material/form-field/src/field.type.ts#L63

this.formControl.value in this case is 0 so the expression returns true. Should you check against null or undefined?

**Comment by Etchelon** [comment]
I'm now using you default implementation and it doesn't happen anymore. I was using a custom select component (more or less copied from an older version of your implementation).

**Comment by Etchelon** [comment]
I have reproduced this issue in the demo app:
- in demo/src/app/ui/common/input/app.component.ts add type: 'number' to the input field.
- open the demo app and go to http://localhost:4100/ui/material and type 0 in the first input, now of type number.
- the label of the field won't float upon losing the focus.
I've made a fix, will submit a PR in a few minutes.

**Comment by aitboudad** [comment]
fixed in `5.0.4`
