### ISSUE TITLE
Add schematics for upgrading existing ngx-formly projects from v4 => v5 => ...

### ISSUE THREAD

**Issue by juristr** [ngx-formly/ngx-formly#1156]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

This is a **discussion issue** for planning the work on creating "ng update" like schematics (just as Nrwl/NX has) for allowing people to seamlessly upgrade between breaking versions.

Some initial work on schematics has already been done here https://github.com/formly-js/ngx-formly/tree/master/src/schematics which are however mainly for providing "ng add" functionality.

//cc @aitboudad

**Comment by aitboudad** [comment]
seems promising, all relevant changes are mentioned in [UPGRADE-5.0](https://github.com/formly-js/ngx-formly/blob/master/UPGRADE-5.0.md)

I'd prefer to wait until we reach RC phase but it not blocking if anyone interested to work on it

**Comment by aitboudad** [comment]
close in favor of #1366

**Comment by aitboudad** [comment]
I'm going to release V5 this weekend without this feature due to the lack of time, we'll focus on schematics and docs in `V7`.
sorry about that :pray:
