### ISSUE TITLE
model value for select options and async loading

### ISSUE THREAD

**Issue by enricooliva** [ngx-formly/ngx-formly#1243]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```
This is my formlyfield with select type and async population of options.

` {
    fieldGroupClassName: 'row',
    fieldGroup:[
    {
      key: 'tipoemittenti_codice',
      type: 'select',
      className: "col-md-6",
      templateOptions: {
        options: this.service.getEmittenti(),
        valueProp: 'codice',
        labelProp: 'descrizione',
        label: 'Autorizzato da',     
        required: true               
      }     
    },     `

On the other side I have the model where I have 'tipoemittenti_codice' and a single value of the options "descrizione":"Senato"

{
"tipoemittenti_codice":"**SE**",
"tipoemittente":{"id":3,"codice":"**SE**","descrizione":"Senato"}}
}

How can I set "descrizione":"Senato" in the options and after waiting for the async values this.service.getEmittenti()?

**Comment by enricooliva** [comment]
@aitboudad 

This is a select with async load of options:
```
 fieldGroup:[
    {
      key: 'dipartimemto_cd_dip',
      type: 'select',
      className: "col-md-6",
      templateOptions: {
        options: this.service.getDipartimenti(),
        valueProp: 'cd_dip',
        labelProp: 'nome_breve',
        label: 'Dipartimento',     
        required: true               
      },        
    },  
```
the problem is:

I load a model with the key **dipartimemto_cd_dip** populated. The select is empty. This is a problem. 
When the async call for the **options** provide the data start a selection change. This is a problem.
 
One option came from the model but i'm not able to bind it.

**Comment by enricooliva** [comment]
I tried to modify a your example 
 https://stackblitz.com/edit/angular-txutgw-hfqnua

**Comment by enricooliva** [comment]
@aitboudad now the stackblitz not work :)
https://stackblitz.com/edit/angular-txutgw-hfqnua

**Comment by VladBozhinovski** [comment]
> @aitboudad the stackblitz
> https://stackblitz.com/edit/angular-txutgw-hfqnua

Did you managed to solve this problem ?

**Comment by aitboudad** [comment]
I think the problem has been fixed, if you still facing it, please open an issue with a reproduction example which uses the latest version.
