### ISSUE TITLE
Lifecycle onInit: Hide fields within fieldGroup doesn't work when fieldGroup has a hideExpression

### ISSUE THREAD

**Issue by juristr** [ngx-formly/ngx-formly#1259]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Having the following configuration, when setting the `field.hide` inside the `onInit` I'd expect the field to be hidden, even though the `hideExpression` in the `fieldGroup` evaluates to `true`.

```
  fields: FormlyFieldConfig[] = [
    {
      hideExpression: model => false,
      fieldGroup: [
        {
          key: 'test',
          type: 'textarea',
          templateOptions: {
            label: 'Test'
          },
          lifecycle: {
            onInit: (form: FormGroup, field: FormlyFieldConfig) => {
              field.hide = true;
            }
          }
        }
      ]
    },
  ];
```

Instead currently it is still being shown. Removing the `hideExpression` a level up in the `fieldGroup` fixes the behavior. Also dynamically adding a `hideExpression` from the `onInit` works as well, but is kind of cumbersome.

```
  fields: FormlyFieldConfig[] = [
    {
      hideExpression: model => false,
      fieldGroup: [
        {
          key: 'test',
          type: 'textarea',
          templateOptions: {
            label: 'Test'
          },
          lifecycle: {
            onInit: (form: FormGroup, field: FormlyFieldConfig) => {
              // works this way
              field.hideExpression = (model) => true
            }
          }
        }
      ]
    },
  ];
```

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-y9dvha

**What is the motivation / use case for changing the behavior?**

There could be a larger `fieldGroup` with a generic condition that all its children are hidden based on some flag. Some of the fields might have more specific rules, that are set either via a `hideExpression` or even in the `onInit` based on some "static" condition.

**Please tell us about your environment:**

* **Angular version:** 6.x (should be same with v7)

**Comment by aitboudad** [comment]
not sure what do you want to achieve with using both option at same time, only one approach is allowed, either rely `hideExpression` or `hide` not both,
when `hideExpression` is specified the hide property is delegated to the expression value and treated as a readonly.

**Comment by aitboudad** [comment]
I would consider this as limitation for now, the workaround is to define `hideExpression` to override the default one (`hideExpression: () => true`):

```patch
    {
      hideExpression: model => false,
      fieldGroup: [
        {
          key: 'test',
          type: 'textarea',
++        hideExpression: () => false,
          templateOptions: {
            label: 'Test'
          },
        }
      ]
    },
```
I'm planning to change the expression signature and merge `hideExpression` and `expressionProperties` into one path (`expression`) (I'll try to revisit this issue once done), we should have something like:

```ts
key: 'test',
type: 'textarea',
expression: {
  hide: field => false,
  className: field => 'col-12',
}
```

**Comment by juristr** [comment]
alright, I'm fine with that :)
