### ISSUE TITLE
allow opt-in `OnPush` changeDetection

### ISSUE THREAD

**Issue by albertthinc** [ngx-formly/ngx-formly#1272]
Hi

I have few questions and clarification.

1. I have model. I will filter the model based on a category and define 2 different objects.

I will use the 2 objects to 2 form.

Issue I am facing: when I do it the repeat section add is not working.

2. If I use lifecycle, and write a console.log in it. The console triggers when I hover any element the page.

3. Typing is slow. 

This happens when I use twice same key with different hideExpression. In a big form, as a repeat inside repeat section.

4. I am using 3 components, and passing model & options & form from parent. Fields config in respective child component.

 Is this approach ok or is there any better way?
Do you this approach may reduce the page performance because of @input & @output.

**Comment by aitboudad** [comment]
enabling `OnPush` changeDetection in `FormlyForm` would solve the slowness typing, but it'll introduce a breaking change, I'll try find a way to opt-in changeDetection.

**Comment by aitboudad** [comment]
I've a workaround (by overriding the default `formly-group` type) which solve the performance issue, can you try it and let me know if it solved yours:

https://stackblitz.com/edit/angular-y6y8dq-cg9bap
```ts
    FormlyModule.forRoot({
      types: [
        { name: 'formly-group', component: FormlyGroup },
      ],
    }),
```

**Comment by albertthinc** [comment]
Sure. Thank you

**Comment by aitboudad** [comment]
another way to solve this without on-push is to use virtual scroll in repeat section.
