### ISSUE TITLE
[TRULY-UI] add support for basic types

### ISSUE THREAD

**Issue by abalad** [ngx-formly/ngx-formly#1275]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```
**Add support for basic types**

- [ ]  Input
- [ ]  Radio
- [ ]  Checkbox
- [ ]  Select
- [ ]  Multiselect

**Comment by aitboudad** [comment]
PR welcomed!

**Comment by abalad** [comment]
@aitboudad  OK. We will be creating the implementations according to your standards and sending the PR

**Comment by abalad** [comment]
Thanks @aitboudad , I'll analyze and create this pattern;)

**Comment by aitboudad** [comment]
I'll take care of this, it will be part of the premium UI.

**Comment by aitboudad** [comment]
in order to fund our work on formly, starting from V5 we'll try to move/introduce some Premium UI which will be paid for commercial use.
not sure if it gonna but I'd give it a try :)

**Comment by abalad** [comment]
How cool. I am willing to assist in carrying out the integration.

**Comment by aitboudad** [comment]
close in favor of #1365
