### ISSUE TITLE
[Clarity] support basic types

### ISSUE THREAD

**Issue by strerene** [ngx-formly/ngx-formly#1292]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

**Support basic input types for Clarity Design System**
https://vmware.github.io/clarity/

- [ ]  Input
- [ ]  Radio
- [ ]  Checkbox
- [ ]  Select
- [ ]  Multiselect

**Comment by aitboudad** [comment]
PR welcomed and check the following PR #1034 as a starter implementation

**Comment by devesh23** [comment]
@aitboudad How can I take up this PR and contribute to formly?

**Comment by aitboudad** [comment]
sure, just go ahead!

**Comment by aitboudad** [comment]
@devesh23 sorry I've misread your comment, check my PR #1034  the initial work should be landed with an input field type and form-field wrapper

**Comment by aitboudad** [comment]
I'll take care of this, it will be part of the premium UI.

**Comment by aitboudad** [comment]
@mohammedzamakhan I think formly should move into a new [org](https://github.com/ngx-formly) which I've created recently in order to have full control of the package which is not the case right now for me, if you can assign me a `maintainer` role that would be cool.

**Comment by mohammedzamakhan** [comment]
I still want to keep in in formly-js org, because that's where @kentcdodds created the original angular-formly, and it has hosted other formly repos too like Vue-formly and the original angular-formly. And this new org name looks specific to Angular which doesn't make sense.

**Comment by aitboudad** [comment]
well, to be honest, the only active package on formly-js org is this one and I think we arrive at the point where the project should diverge and focus on other parts.
I've done a lot of work here and at least I should have a voice here (right now I'm the main maintainer since more than 2 years). anyway if there is no agreement on that part I'll try to make a fork and continue my adventure there!

**Comment by kentcdodds** [comment]
From my perspective, please feel free to do whatever you want. I don't care if you keep things in this org.

**Comment by aitboudad** [comment]
just tried the transfer and it seems working, many thanks!

**Comment by mohammedzamakhan** [comment]
@aitboudad I was just giving a perspective 😄 

Anyways, small news, I just started to write a book, "Angular Projects" for Packt Publication, and I will be including a chapter "Building an application using Formly with Ionic"

**Comment by aitboudad** [comment]
close in favor of #1365
