### ISSUE TITLE
messages errors summary

### ISSUE THREAD

**Issue by davidoween** [ngx-formly/ngx-formly#1297]
How could I get all the errors in a form? I want to list them when the user clicks on submit

**Comment by devesh23** [comment]
You can create a custom wrapper of your own by extending the formly field wrapper. Inside the TypeScript file of the extended wrapper you can write a function which will execute whenever the component becomes dirty and then you can save the component and error message associated with that component. 

You can probably save the same in an JSON Object and once the parsing of the form is complete, use the object to show the error to the user. 

If you can still need more explanation, you can tag me and I would be happy to help you out by giving an stackblizt example as my colleague and me have already solved this issue.

**Comment by smile2014** [comment]
https://github.com/ScottMGerstl/ng2-validate

**Comment by devesh23** [comment]
@aitboudad Can this be closed? I hope the above solution solves the problem

**Comment by aitboudad** [comment]
didn't have yet the time to check this one but I would prefer a solution that uses `formly-validation-message` component

**Comment by davidoween** [comment]
Yes, I think like you. Could I do it now? with what is available

**Comment by aitboudad** [comment]
here is a quick example https://stackblitz.com/edit/angular-bej44b but you have to deal with nested fieldGroup which is not covered in the example

**Comment by aitboudad** [comment]
this will be part of V6 (#1365)

**Comment by davidoween** [comment]
Hello, the code works perfectly, otherwise you have hidden fields. How could I solve it?

https://stackblitz.com/edit/angular-bej44b-t6uo3k?file=src/app/app.component.html

**Comment by davidoween** [comment]
fixed with condition !field.hide

thanks

**Comment by GlauberF** [comment]
@aitboudad is there a more elegant alternative any call to api or is the only alternative still the one mentioned here in the issue?

**Comment by aitboudad** [comment]
@GlauberF sorry not yet!

**Comment by GlauberF** [comment]
@aitboudad any news about this in V6?
