### ISSUE TITLE
is there a way to apply css class for json schema example

### ISSUE THREAD

**Issue by navneetagrwl** [ngx-formly/ngx-formly#1348]

**Comment by aitboudad** [comment]
not supported yet, we can use what `react-jsonschema-form` does by passing a `uiSchema` which allow passing extra options:

```ts
 uiSchema: {
    name: {
      classNames: 'col-xs-6  col-sm-6  col-md-6  col-lg-6',
    },
}
```
but not sure yet. @kenisteward any thoughts on this?

the only way right now to edit the converted result after `toFieldConfig` call

**Comment by devesh23** [comment]
There is a way to do it: 

1) Extend the component( textfield, textarea etc) for which you want to apply custom class using the example given in Formly Examples
2) Bind the class attribute. 

For ex: 

<input type="text" [class]="to.customClass">

3) Then when creating a json schema pass the custom class

```javascript
{
key:'SomeKey',
type:'YourCustomType'
templateOptions:{
customClass: 'ClassName'
}
}
```

**Comment by kenisteward** [comment]
@navneetagrwl take @aitboudad 's suggestion and simply manipulate the output formlyConfig.  It is what you would have done even we didn't have a jsonSchema converter in the first place.

@aitboudad 
https://github.com/hamzahamidi/angular6-json-schema-form  is another implementation of the same thing but with Angular.  I've been exploring the lib and it seems to be modeling react-json-schema-form which we want to model here as well.  I'm considering stripping some of the ui schema parsing and $ref parsing and adding it here but I haven't decided on the best way to do that.  If you have a sec to take a look at it and suggest a path let me know.  I was thinking somewhere along the lines of having a schemaParserUtils functions.  Not sure yet if that requires us to rewrite what you have done with the base jsonSchema parser yet though.

Another random idea I had,  allow for a "event based" translation api to let people hook in creating the configs for each one.  so when we check for type = enum it does the base parsing and then calls translations[0-n]() which are set by the developer.  this is probably over engineering though.

**Comment by devesh23** [comment]
@kenisteward What do you mean by base volcabulary? Manipulating the output formlyConfig is not a pretty way to handle this situation. If a person is using Formly, they are using it to decrease the effort it will take them to build the Form. But if in the end you are manipulating the output of formlyConfig then you are removing the essence of formly itself.

**Comment by juristr** [comment]
Cool, @kenisteward keep me posted about the progress. I'm also willing to contribute as we will very soon start to use JSONSchema based formly configs. Let me know 🙂

**Comment by kenisteward** [comment]
@devesh23 
https://json-schema.org/specification.html

Any changes that we make in this library will have the base specification in mind (which will be draft 8 soon)  because of this, putting erroneous keywords in general should not affect but is not a part of the base keyword specifications.  In the future, when it supports custom vocabulary then you can add keywords and we can add extensions to this to support you adding those keywords in.  Otherwise, I would not advise putting this in the base json-schema if you want to stay forward compatible.

Also take the scenario that you were creating a form at its base, you would have to iterate over all the configs int he first place if you were doing dynamic processing.  All the json-schema service does for you is create those configs.  It is a simple task to add class names to where you need them based on whatever criteria you want.

**Comment by aitboudad** [comment]
this will be part of V6 (#1365)

**Comment by saadmomin** [comment]
> not supported yet, we can use what `react-jsonschema-form` does by passing a `uiSchema` which allow passing extra options:
> 
> ```ts
>  uiSchema: {
>     name: {
>       classNames: 'col-xs-6  col-sm-6  col-md-6  col-lg-6',
>     },
> }
> ```
> 
> but not sure yet. @kenisteward any thoughts on this?
> 
> the only way right now is to edit the converted result after `toFieldConfig` call

Hi. Could you please help me with this. I am unable to figure out how to apply class via this method. Stackbliz would help a lot. Thanks

**Comment by kenisteward** [comment]
Just take the given formly config and iterate through to apply the styles
you need

You can also use the map function to check for the field and apply styles
there.

**Comment by aitboudad** [comment]
@saadmomin use `widget` or pass a `map` option to adjust the field config:

```ts
{
  "type": ...,
  "widget": {
    "formlyConfig": {
      "className": "custom_class"
    }
  }
}
```

**Comment by saadmomin** [comment]
Thank you so much and sorry for the delayed response.

I know this ain't the right post but just wanted to check if we have implemented wrappers yet? It's kinda necessary for me. You see I have a "part" of the form which is dynamic and I am using formly throughout the project. I don't want to have fields outside formly forms. Hence need the wrappers feature.

Thank you.

**Comment by aitboudad** [comment]
@saadmomin To create a custom wrapper:

1. https://ngx-formly.github.io/ngx-formly/guide/custom-formly-wrapper
2. pass your wrapper through `formlyConfig`:

```ts
{
  "type": ...,
  "widget": {
    "formlyConfig": {
      "wrappers": ["custom_wrapper"]
    }
  }
}
```
