### ISSUE TITLE
can we pass more than one config object in forRoot method

### ISSUE THREAD

**Issue by navneetagrwl** [ngx-formly/ngx-formly#1350]
export const config:ConfigOption = {
types:[]
}
export const configSecond:ConfigOption = {
types:[]
}
FormlyModule.forRoot(config,configSecond)

Or I have to create different module each time

**Comment by aitboudad** [comment]
for the second config use `forChild`:
```ts
FormlyModule.forRoot(config),
FormlyModule.forChild(configSecond),
```

**Comment by navneetagrwl** [comment]
So every other config I can use forChild like configThird?

**Comment by aitboudad** [comment]
> Is there any example in the documentation regarding this

nop, we'll focus on doc once v5 is landed.
