### ISSUE TITLE
[SUPPORT] Dynamic field add

### ISSUE THREAD

**Issue by b-barry** [ngx-formly/ngx-formly#1352]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request
```

**Current behavior**

Hello, 

I have a form where I have created a custom Field that has a select field with the key 'type'. When changing this field, I would like to add dynamically some new field with some new keys.
My goal is to get this structure:
```js
{
  customFieldKey:{
    type:'type1'
	newKeyAddedAfterSelectingType1:'lol'
  }
}
```
The new field could anything i.e a single text input or something more complex and should be fattened directly in the current formGroup

**Expected behaviour**

**Minimal reproduction of the problem with instructions**

I tried to use the prePopulate and the lifecycle but I am getting some errors
see the [link](https://stackblitz.com/edit/dynamic-field-v5-g8jzdb?file=src/app/select-requester-field.component.ts)

Thanks for your help

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
see the following example https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section

**Comment by b-barry** [comment]
I have already checked the repeat but I don't want to do perform a repeat.
The issue is that I don't which field I have to add before the user select something. 
I can not use also the hide expression because some field could have others orders in some 'type'

**Comment by aitboudad** [comment]
adding fields after the form is builded require to call `buildForm` manually see
 https://stackblitz.com/edit/dynamic-field-v5-71urpy

**Comment by b-barry** [comment]
Thanks a lot for the quick answer, it works perfectly. :)

Just a quick question, I saw that the demo is using formly v5, I am wondering if I could do the same with formly v4 or do I have to updgrade?

Thanks

**Comment by aitboudad** [comment]
you have to upgrade (check https://github.com/ngx-formly/ngx-formly/blob/master/UPGRADE-5.0.md)

**Comment by b-barry** [comment]
Thanks, I will try this coming day to upgrade then
