### ISSUE TITLE
Label is placed very close to the hint/description text for Material

### ISSUE THREAD

**Issue by skounis** [ngx-formly/ngx-formly#1353]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
In the case of Material the labels are moved very close to the hint/description text of the fields right above it. So there is no visual communication of their purpose something that increases the cognitive load. 
![hint label](https://user-images.githubusercontent.com/690575/50536824-2874fe80-0b61-11e9-98ed-8197d72f761f.png)

**Expected behavior**
This could be improved if we add some space after each field
![hint label-fix-1](https://user-images.githubusercontent.com/690575/50536836-46dafa00-0b61-11e9-83b6-eb93bb5c9dff.png)
![hint label-fix-2](https://user-images.githubusercontent.com/690575/50536739-28c0ca00-0b60-11e9-9d28-980ae579a19f.png)
![hint label-fix-3](https://user-images.githubusercontent.com/690575/50536740-2bbbba80-0b60-11e9-8a9d-9a86675673a9.png)

**Minimal reproduction of the problem with instructions**
Visit this app and enter a name and a city. Then check how close the hint text is to the label and the button
- https://stackblitz.com/edit/ngx-formly-ui-material-label-issue

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
any

* **Angular version:** 7.1

* **Browser:** [all]

* **Language:** [all]

**Comment by aitboudad** [comment]
well, I think this should be reported to the material team (https://github.com/angular/material2/issues/14671).
