### ISSUE TITLE
One field dependant on another how to write schema for the same

### ISSUE THREAD

**Issue by LalitKushwah** [ngx-formly/ngx-formly#1354]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Query
```
Hello All,

If I want to validate one field dependent on another filed's value how can I achieve this. example
1st field:
type: number

2nd field:
type: number

Expectation:
Value of first filed should be greater than second filed

Here is the schema created:

"inputSchema": [
    {
      "label": "Calendar",
      "fields": [
        {
          "wrappers": [
            "panel"
          ],
          "templateOptions": {
            "label": "Calendar"
          },
          "fieldGroup": [
            {
              "key": "from-year",
              "type": "input",
              "defaultValue": 1990,
              "templateOptions": {
                "label": "From Year",
                "description": "First value in year dropdown"
              }
            },
            {
              "key": "through-year",
              "type": "input",
              "defaultValue": 2018,
              "templateOptions": {
                "label": "Through Year",
                "description": "Last value in year dropdown"
              }
            },
            {
              "key": "future-date",
              "type": "checkbox",
              "defaultValue": true,
              "templateOptions": {
                "label": "Enable future date"
              }
            },
            {
              "key": "message",
              "type": "input",
              "templateOptions": {
                "label": "Message",
                "description": "Message to be displayed at the bottom of calendar"
              }
            }
          ]
        }
      ]
    }
  ]

**Comment by aitboudad** [comment]
see https://ngx-formly.github.io/ngx-formly/examples/validation/matching-two-fields

**Comment by LalitKushwah** [comment]
Thanks @aitboudad  I am using the JSON powered mechanism to achieve this but expression inside validators object is not recognized in json file. How can I achieve this in schema created in json file

**Comment by aitboudad** [comment]
define a custom validation through `NgModule` declaration see the following example https://stackblitz.com/edit/angular-n6foes
