### ISSUE TITLE
How to open custom component which has static form, save & display as an array.

### ISSUE THREAD

**Issue by ags504** [ngx-formly/ngx-formly#1356]
![image](https://user-images.githubusercontent.com/35792252/50558027-83008d00-0d10-11e9-97d0-183b5dd68226.png)
![image](https://user-images.githubusercontent.com/35792252/50558074-f2767c80-0d10-11e9-86be-cbeb2497b26b.png)
On click of add, a modal popup need to open with an existing component which has static form and on submit need to display in the ngx form.

**Comment by aitboudad** [comment]
you may check the demo examples, I think you're looking for a repeat field https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section
