### ISSUE TITLE
Warnings while running tests

### ISSUE THREAD

**Issue by vjanssens** [ngx-formly/ngx-formly#1357]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When running tests with Jest, test output contains a lot (+100) of `console.warn` statements with the following error message:

```
console.warn node_modules/@ngx-formly/bootstrap/bundles/ngx-formly-bootstrap.umd.js:442
    The following wrappers ('label', 'fieldset', 'description', 'validation-message') are depecated, rely on 'form-field' wrapper instead
```

When using the library in the browser, I do not get these warnings. 
Is there a way to disable this message?

**Expected behavior**
No warning messages

**Minimal reproduction of the problem with instructions**
1. Create new angular project with ngx-formly
1. Add Jest tests (possibly also with other test runners)
1. Run tests (observer `console.warn` messages in test output

**What is the motivation / use case for changing the behavior?**
Test output is cluttered with warning messages, distracting of the end result of the tests.

**Please tell us about your environment:**
* **Angular version:** 7.1.0
* **ngx-formly:** 4.8.2
* **Browser:** terminal
* **Language:** TypeScript 3.1.6

**Comment by aitboudad** [comment]
> Is there a way to disable this message?

somehow you're still using the deprecated wrappers (`label`, `fieldset`, `description` or `validation-message`), instead use `form-field` wrapper and the warning should disappear

**Comment by vjanssens** [comment]
What would cause this log to only appear during tests? If I was using some of those wrappers, i'd see them in the browser as well, right?

Could `ngx-formly-bootstrap.umd.js` be using these deprecated wrappers?
For me, it seems as if i'm only specifying a simple JSON of form fields, without custom wrappers.
