### ISSUE TITLE
deletion causes duplicate row when using FieldArrayType

### ISSUE THREAD

**Issue by spoon98** [ngx-formly/ngx-formly#1359]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have a repeater control and when I do a delete the last row is duplicated, I traced the issue back to ngx-formly-core.js line 2022 addFormControl. When this method is called it adds a duplicate row.

**Expected behavior**
No duplicate row

**Minimal reproduction of the problem with instructions**
Here is a working example demonstrating the issue
https://angular-rv7jtn-8sa2rq.stackblitz.io/

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X
here package json dep
{
  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/cdk": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.22",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/material": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@aspnet/signalr": "^1.0.4",
    "@ngrx/effects": "^6.1.0",
    "@ngrx/router-store": "^6.1.0",
    "@ngrx/store": "^6.1.0",
    "@ngrx/store-devtools": "^6.1.0",
    "@ngx-formly/core": "5.0.0-beta.15",
    "@ngx-formly/primeng": "^5.0.0-beta.15",
    "@types/js-cookie": "2.2.0",
    "angular2-toaster": "^6.1.0",
    "classlist.js": "^1.1.20150312",
    "concurrently": "^4.0.1",
    "core-js": "^2.5.4",
    "dotenv": "^6.1.0",
    "font-awesome": "^4.7.0",
    "js-cookie": "2.2.0",
    "lodash": "^4.17.11",
    "moment": "^2.22.2",
    "ngrx-store-freeze": "^0.2.4",
    "ngx-post-message": "^1.5.3",
    "post-robot": "^9.0.19",
    "primeflex": "^1.0.0-rc.1",
    "primeicons": "^1.0.0",
    "primeng": "6.1.5",
    "pym.js": "^1.3.2",
    "quill": "^1.3.6",
    "rxjs": "~6.3.3",
    "uuid": "^3.3.2",
    "yargs": "^12.0.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.3",
    "@angular/compiler-cli": "~7.0.0",
    "@angular/language-service": "~7.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.119",
    "@types/node": "~10.12.18",
    "codelyzer": "~4.5.0",
    "eslint-config-prettier": "^3.1.0",
    "eslint-plugin-prettier": "^3.0.0",
    "eslint-plugin-typescript": "^0.12.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "json-server": "^0.14.0",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "tslint-config-prettier": "^1.15.0",
    "tslint-eslint-rules": "^5.4.0",
    "typescript": "~3.1.1"
  }
}

**Comment by aitboudad** [comment]
can't reproduce it, could you provide a scenario to get it

**Comment by aitboudad** [comment]
`pTable` rely on a setter to detect model changes, so to make it work you may use `formControl.valueChanges` instead of `model`:

```patch
- [value]="model"
+ [value]="formControl.valueChanges|async"
```

here is a working example: https://stackblitz.com/edit/angular-rv7jtn-t4og2m

**Comment by spoon98** [comment]
That worked! I implemented your fix the next day, thanks for resolving this so quickly
