### ISSUE TITLE
Example for json schema is not there in demo section now why?

### ISSUE THREAD

**Issue by navneetagrwl** [ngx-formly/ngx-formly#1361]
https://ngx-formly.github.io/ngx-formly/examples

Json schema example is not there?

**Comment by aitboudad** [comment]
the current demo examples refer to the latest stable version (`v4`), `json schema` examples is landed in the next version which is not yet stable.
for now you may try to run the demo locally or check the following stackblitz example https://stackblitz.com/angular/krvypbogkbg
