### ISSUE TITLE
required validation in checkbox and multicheckbox

### ISSUE THREAD

**Issue by davidoween** [ngx-formly/ngx-formly#1362]
Why does not it work when I add requited: true in checkbox and multicheckBoxs?

example:

https://stackblitz.com/edit/angular-bshgv7-fre5xt?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
`required` just ensure that the provided value is not blank, what you're looking for is `requiredTrue` (requires the checkbox to be checked) which not provided by default.

check the following example https://stackblitz.com/edit/angular-bshgv7-r2mazx
