### ISSUE TITLE
Advanced Layout on Ionic

### ISSUE THREAD

**Issue by GleidsonHenrique** [ngx-formly/ngx-formly#1363]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

I'm trying to use rows and cols at Ionic, but it's not working. Can you please tell me if this feature it's working or need a fix?

On module I use FormlyIonicModule, FormlyBootstrapModule and both, none works.

I'm using this example: https://ngx-formly.github.io/ngx-formly/examples/bootstrap-specific/advanced-layout

* **Angular version:** 5.2.11

* **Browser:** Ionic DevApp and Chrome

* **Language:** TypeScript  3.2.2

* **Node (for AoT issues):** `node --version` = 10.9.0

**Comment by aitboudad** [comment]
the linked example use bootstrap grid style so just ensure to include the necessary bootstrap grid CSS in your stylesheet.

**Comment by aitboudad** [comment]
Ionic provide a responsive grid which it may be better to use it instead of bootstrap to avoid adding an extra deps, check https://ionicframework.com/docs/theming/responsive-grid/
