### ISSUE TITLE
Validator that accesses the model or alternatively the submitted-state of the form group directive?

### ISSUE THREAD

**Issue by blissi** [ngx-formly/ngx-formly#1364]
Hallo,

I need to know in my validator if the form has been submitted or not. For this, I was thinking if it is possible to either access the FormGroupDirective somehow or alternatively access the model, so that I can set a property on the model. Or is there another way to do this?

I need this to do the following:
The validation message should only be displayed when
a) the control is invalid.
b) the user has clicked on the submit button.

I am using the Bootstrap form-field wrapper.

Thanks,
Steven

**Comment by aitboudad** [comment]
I think you're looking for a custom `showError`, check my answer in https://github.com/ngx-formly/ngx-formly/issues/1180#issuecomment-423154658.

**Comment by blissi** [comment]
Thank you, I'll give it a try.
