### ISSUE TITLE
Is there functionality to transform values before we diplay them?

### ISSUE THREAD

**Issue by MarioAllegro** [ngx-formly/ngx-formly#1367]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
I want to format a utc date for display. Is there built in functionality to do that?

**Expected behavior**
I would expect that I can transform the date before displaying with a pipe or a custom transform function without declaring a new field with the date formatted.

@ngx-formly/core": "^4.8.2"

**Comment by aitboudad** [comment]
you can use `template` for displaying a date:
```ts
{ template: utcDate },
```

**Comment by rdev-software** [comment]
@aitboudad thats not the answer to the question, at all! 

How to transform model value is the question!

Not mentioning the fact, that using "template" will force you to write new component completely unnecessary.

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/issues/1597#issuecomment-495732998 is the answer to this issue.
