### ISSUE TITLE
Feature: addonRight and addonLeft for Material

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1369]
I am submitting 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

I've implemented the Bootstrap addonLeft and addonRight wrappers for Material Design. You can see the sample here: https://stackblitz.com/edit/formly-prefix-suffix?file=src%2Fapp%2Fapp.component.ts

Are you interested in submitting that as a PR to the library?

Thanks

**Comment by aitboudad** [comment]
right now I would accept adding it in the demo example, not to the library.

**Comment by bhaidar** [comment]
Hi @aitboudad 

I've added a new module under `/demo/examples/other` titled `material-prefix-suffix`. 

All necessary steps to add the module were followed. Still, the link to the new module is not showing in the demo page.

Are there any other steps needed to show this new module?

The steps I have taken were:
- Create a new folder under example/others
- Clone another folder and follow the same steps
- Add the new module to the navigation on examples.component
- Add the new module to the examples module

**Comment by bhaidar** [comment]
@aitboudad I was able to make it work. I pushed a PR. Thanks
