### ISSUE TITLE
Any idea why datepicker is not working?

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1370]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Datepicker field is not showing up.

**Expected behavior**
Datepicker should appear on the page

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/formly-datepicker?file=src%2Fapp%2Fapp.module.ts

**Comment by aitboudad** [comment]
importing from `@angular/material/core` would solve the issue (maybe related to https://github.com/angular/material2/issues/7947 but not sure)

```ts
import { MatNativeDateModule } from '@angular/material/core';
```

**Comment by bhaidar** [comment]
Thanks!

How to control the datepicker not to allow user to type in?

**Comment by anasvn** [comment]
@aitboudad Bro, I have been converting my form components to formly. Everything is fine except bootstrap datepicker. Spent 4 hours on this. Can you figure out why date isn't binding with my custom bootstrap datepicker type ?
https://stackblitz.com/edit/ngx-bootstrap-datepicker-kse7b3?file=app/type.ts

**Comment by aitboudad** [comment]
@anasvn you've missed passing `formControl`  which is required for `formly` to take account of input changes as it was mentioned in the [doc](https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field)
https://stackblitz.com/edit/ngx-bootstrap-datepicker-l69bux

```html
@Component({
  selector: 'app-form-datepicker-type',
  template: `
    <input
      [formControl]="formControl"
  ...
```
