### ISSUE TITLE
parent incorrectly set for fieldGroup childs when using buildForm()

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1371]
```
[x ] bug report
```

**Current behavior**
When adding/changing fields dynamically the `parent` is incorrectly set to the `field.fieldgroup`  instead of `field` when calling `buildForm()` .

**Expected behavior**
Correctly set `parent`, by adding the `field` to `buildForm()` and using it as the parent for fieldGroup childs.

**Minimal reproduction of the problem with instructions**
[https://stackblitz.com/edit/dynamic-field-v5-iimssr](https://stackblitz.com/edit/dynamic-field-v5-iimssr?file=src/app/select-requester-field.component.ts)

Run
select a new Type
inspect console log, 'before':
field.fieldGroup[0].parent.id == formly_1_select-requester-field_requester_0: CORRECT

In the source "Enable the following 2 statements"
Run
select a new Type
inspect console log, 'after':
field.fieldGroup[0].parent.id == missing WRONG
field.fieldGroup[0].parent is a link to field.fieldGroup WRONG

**Reference**
[SUPPORT] Dynamic field add #1352

**Comment by aitboudad** [comment]
buildForm doesn't know about the parent field, so instead pass the parent field:
```ts
const parentField = field.parent;
this.formBuilder.buildForm(
  parentField.form,
  parentField.fieldGroup,
  parentField.model,
  parentField.options,
);
```

**Comment by FritzHerbers** [comment]
@aitboudad 
Did you meant `parentField.form` instead of `parentField.formControl`?

And then those children of parentField will have parentField.fieldGroup set instead of parentField.

Updated the example with your snippet. 
Some errors appear in the console, these are the same errors I have in my application (here I used parent as in your snippit), which I wanted to solve:
- Cannot read property 'formControl' of undefined
- Cannot read property 'showError' of undefined

**Comment by aitboudad** [comment]
> Did you meant parentField.form instead of parentField.formControl?

`parentField.formControl`, https://stackblitz.com/edit/dynamic-field-v5-yzw9mz

**Comment by FritzHerbers** [comment]
@aitboudad 
I was struggling for some time and this solved my issues, thx a lot.

**Comment by pjobs** [comment]
@aitboudad the above example https://stackblitz.com/edit/dynamic-field-v5-yzw9mz, its NOT updating the model when you change/enter the input for type2. Is that a bug or working as expected

**Comment by aitboudad** [comment]
@pjobs the example use an old version,  here is an updated one https://stackblitz.com/edit/dynamic-field-v5-ft2wkz

**Comment by pjobs** [comment]
@aitboudad you are awesome man. thank you very much for all the hard work.
