### ISSUE TITLE
Inline editing

### ISSUE THREAD

**Issue by rakesh0692** [ngx-formly/ngx-formly#1373]
**I'm submitting a ...**  (check one with "x")
```
 Bug fix
 feature request
```

**Current behavior**
Inline Editing not available

**Expected behavior**
Inline editing should be there on button click or on double click

**Minimal reproduction of the problem with instructions**

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =8.11.3

**Comment by aitboudad** [comment]
the request is not clear to me, could you please elaborate more
