### ISSUE TITLE
focus: true does not work on ionic

### ISSUE THREAD

**Issue by GleidsonHenrique** [ngx-formly/ngx-formly#1374]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Not focus

**Expected behavior**
Focus on load

**Minimal reproduction of the problem with instructions**
{
                className: 'flex-6',
                key: 'number',
                type: 'ion-input-floating',
                focus: true,
                templateOptions: {
                  label: 'Número do cartão',
                  type: 'tel',
                  maxlength: 19,
                  brmasker: { mask: '0000 0000 0000 0000', len: 19, type: 'num' },
                  required: true
                }
              }

* **Angular version:** 5.2.11

* **Browser:**Ionic DevApp

* **Language:** TypeScript 3.2.2

* **Node (for AoT issues):** `node --version` = 10.9.0

**Comment by aitboudad** [comment]
sorry for the delay, I'll take account of this issue on my next iteration.

**Comment by GleidsonHenrique** [comment]
Thank you @aitboudad
