### ISSUE TITLE
Validation on both keyup and blur events

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ngx-formly/ngx-formly#1375]
Support Request:
We want to validate our password input on both keyup as well as blur event. Validation rules and messages should also be different. How can we achieve that?

**Please tell us about your environment:**

OS: Windows, IDE: Visual Studio Code, Package Manager: npm

* **Angular version:** 2.0.X
Angular 7.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, IE.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.7.2

**Comment by aitboudad** [comment]
use custom `showError` option https://github.com/ngx-formly/ngx-formly/issues/1180#issuecomment-423154658
