### ISSUE TITLE
selectionChange event is not working in Material UI select type inputs

### ISSUE THREAD

**Issue by maxi7587** [ngx-formly/ngx-formly#1376]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Using Material UI, selectionChange event in select type inputs is not firing correctly (only fires the first time, when the form is loaded)   

**Expected behavior**

selectionChange event should fire every time the selected option changes

**Minimal reproduction of the problem with instructions**

*Stackblitz reproducing the issue:* [https://stackblitz.com/edit/ngx-formly-ui-material-ownd4a]

- create an input with type = 'select'
- Assign a method to selectionChange attribute inside templateOptions

*Result:* When the selected option changes, the selectionChange event is not fired.

**What is the motivation / use case for changing the behavior?**

I want to trigger a custom event every time the selected option changes inside a select material input.

**Please tell us about your environment:**

IDE: Atom
Package manager: npm
Operating System: Ubuntu

* **Angular version:** 2.0.X

Angular 7.0.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

Typescript 3.1.6

* **Node (for AoT issues):** `node --version` =

9.11

**Comment by aitboudad** [comment]
use change instead https://stackblitz.com/edit/ngx-formly-ui-material-zrw9df
