### ISSUE TITLE
(Material) Number input field returning string instead of number.

### ISSUE THREAD

**Issue by zakjakub** [ngx-formly/ngx-formly#1377]
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Input with type _number_ set in template leads to return string.

**Expected behavior**

Input with type _number_ set in template leads to returns numeric value.

**Minimal reproduction of the problem with instructions**

`{
      key: 'someKey',
      type: 'input',
      templateOptions: {
        type: 'number'
      }
    }`

Output from form: `"5"`

Expected output: `5`

**What is the motivation / use case for changing the behavior?**

It's bug.

**Please tell us about your environment:**

* **Angular version:** 7.2

**Comment by zakjakub** [comment]
Oh, sorry, Material UI :)

**Comment by aitboudad** [comment]
ok then @juristr will take care of it soon :) https://github.com/ngx-formly/ngx-formly/pull/1372#issuecomment-453766749

**Comment by aitboudad** [comment]
well just checked the master version and I've noticed that it has been already implemented, it should be available in `v5`, here is a working example: https://stackblitz.com/edit/angular-bbfo7r
