### ISSUE TITLE
update model set all apart last one to null

### ISSUE THREAD

**Issue by adrienpsl** [ngx-formly/ngx-formly#1378]
Hello :) . 
I'm sorry for my not awesome english level
Thanks a lot for this awesome package !!
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
When I update model all fields are set to null apart the last one updated

**Expected behavior**
my model structure :
``` js
fields: {
      code      : {},
      objectives: {},
      reward    : {},
      sponsor   : {},
      image     : {},
    },
    tabs  : {
      translateText   : {},
      translateSponsor: {}
    }
```
Inside  ngInit, I update model with fetched data
```js
    this.model.fields = {
      code      : {code: data.code},
      objectives: {...data.objectives},
      reward    : {...data.reward},
      image     : {},
      sponsor   : {}
    };
```
all data apart the last one updated are set to null, like 
```
this.model.fields.objectives = someData
// all the other form value === null
```
I try to set the model in ngInit (model = {} at start) like  https://github.com/ngx-formly/ngx-formly/issues/1255 but I get an error because, I use fxLayout and I can set *ngIf in formly 
```
<ng-container *ngIf="loading">
        <formly-field
          *ngFor="let field of fields"
          [fxFlex]="field.templateOptions.fxFlex"
          [form]="form"
          [field]="field"
          [ngClass]="field.className"
          [options]="options">
        </formly-field>
      </ng-container>
```

the error = ERROR TypeError: Cannot read property 'code' of undefined

thanks !!!!

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1295#issuecomment-439453465
