### ISSUE TITLE
Model management, updateInitialValue and resetModel is not a function

### ISSUE THREAD

**Issue by enricooliva** [ngx-formly/ngx-formly#1384]
```
[ ] bug report => search GitHub for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behaviour**

I get an error using options in ngOnInit.
https://stackblitz.com/edit/angular-n9hwbp

The fuctions  `resetModel ` and  `updateInitialValue ` in FormlyFormOptions need to be created.

**Comment by aitboudad** [comment]
`options` isn't yet initialized during `ngOnInit`, try `ngAfterViewInit` instead.
