### ISSUE TITLE
Bug: Focus of Autocomplete wrapper does not always trigger list of options

### ISSUE THREAD

**Issue by samtsai** [ngx-formly/ngx-formly#1385]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I am having an issue with the Material Autocomplete example.  When you click on the label it will not always `focus` the input field and therefore options do not always show.  If you disable the `form-field` wrapper the input always shows the option on `focus`.

Related to #1337

**Expected behavior**
When you click on anything that brings focus to the input field (e.g. placeholder, label, etc), the autocomplete options should show.

Looking at the Material site, when you click on the floating label, it doesn't send the label back into the input as placeholder and than back like our `formly-field` does.  I will try to take a look at the differences.

See [Angular Material Autocomplete Stackblitz](https://stackblitz.com/angular/qoxppokkpyb?file=app%2Fautocomplete-filter-example.html)

**Minimal reproduction of the problem with instructions**

*STEPS TO REPRODUCE*

[Material Autocomplete Stackblitz](https://stackblitz.com/edit/angular-jnurbp?file=src%2Fapp%2Fautocomplete-type.component.ts)

1. Click into the Autocomplete input, see a list of options
2. Click on floating label, options disappear
3. Repeat steps 1-2, results may vary but options often disappear

(Note: In my fork, I first had to fix some dependency issues (e.g. import paths needed to be updated). I've also updated to the latest beta of ngx-formly and angular to 7.x.x, but it also fails in previous versions: https://stackblitz.com/edit/angular-g9txuh?file=src%2Fapp%2Fapp.module.ts).

* **Angular version:** 7.2.0 (also 6.1.10)

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All (only tested on latest Chrome and Firefox)

**Comment by samtsai** [comment]
@aitboudad I have some insight on the issue.

The Autocomplete Trigger directive has a method [`_floatLabel`](https://github.com/angular/material2/blob/88601fa51d581f538468a9b63890b0e285e519cb/src/lib/autocomplete/autocomplete-trigger.ts#L434) that manually manages floating of label.  If a `formField` exists it will try to call the `formField`'s [`_animateAndLockLabel`](https://github.com/angular/material2/blob/88601fa51d581f538468a9b63890b0e285e519cb/src/lib/form-field/form-field.ts#L390).

Our issue is that `formField` is not defined and I believe that is because DI uses [`@Optional() @Host() private _formField: MatFormField`](https://github.com/angular/material2/blob/88601fa51d581f538468a9b63890b0e285e519cb/src/lib/autocomplete/autocomplete-trigger.ts#L199
) and cannot find it due to the additional component wrappers we created with `formly`.

Trying to figure out how I can make sure `formField` is defined at the level of the Autocomplete trigger.

**Comment by samtsai** [comment]
A short fix is not to use the `form-field` wrapper type, but instead to add the `mat-form-field` directly into the `autocomplete-type` component, but ideally I wouldn't have to handle this any differently.

**Comment by aitboudad** [comment]
or try the following workaround https://stackblitz.com/edit/angular-g9txuh-zysdfi?file=src/app/autocomplete-type.component.ts

**Comment by aitboudad** [comment]
updated the demo with the above workaround, a proper fix should be landed once material fix the following issue https://github.com/angular/material2/issues/6728
