### ISSUE TITLE
How to handle several fields with the same key?

### ISSUE THREAD

**Issue by WPCleaner** [ngx-formly/ngx-formly#1386]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

I'm trying to create a form where several text fields have the same key, so that they will share the same value in the model. But when I edit one of the field, the model is correctly updated, but the modification is not reported on the other field.

**Expected behavior**

I'd like to have several fields displaying the same value: if the user modifies the value in one of the field, the other field is also modified.

**Minimal reproduction of the problem with instructions**

I modified the custom template example by duplicating the input field in the FormlyFieldConfig[], see https://stackblitz.com/edit/ngx-formly-custom-template-s8skf2?file=app/app.component.ts

**What is the motivation / use case for changing the behavior?**

I'm trying to convert PDF forms into Angular/ngx-formly forms, and some of the PDF have several fields displayed for the same value (for example, the form number is repeated on each page).

**Please tell us about your environment:**

* **Angular version:** 6.0.X

* **Browser:** only tested on Chrome

* **Language:** 

* **Node (for AoT issues):** `node --version` =10.14.1

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1358#issuecomment-450959179
