### ISSUE TITLE
Async validators and Observable?

### ISSUE THREAD

**Issue by rzych** [ngx-formly/ngx-formly#1387]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
Can I use async validators with service which returns observable (regular angular service based on Observable)? How to correctly handle the http response?

**Comment by thorgod** [comment]
@aitboudad   
I remember reading about useFactory and how to use one example
`    { provide: FORMLY_CONFIG, multi: true, useFactory: uniqueUsernameValidationConfig, deps: [RegistrationService] },`
Never would of crossed my mind this is how you would pass service.... you are amazing. How do you remember all those kind of things?

**Comment by aitboudad** [comment]
> Never would of crossed my mind this is how you would pass service.... you are amazing. How do you remember all those kind of things?

I'm just trying to find a solution :smile:,
IMO it's not about remembering but how much you've played with the knowledge you've learned.
