### ISSUE TITLE
Setting a field group as required

### ISSUE THREAD

**Issue by eduardoleopoldino** [ngx-formly/ngx-formly#1389]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Having a group of fields defined as a type (in order to reuse in other forms), i'd like to be able to set it as required in each form declaration, something along these lines

```
    {
      key: 'address',
      type: 'address',
      fieldGroupClassName: 'row',
      // ** desired behavior **
      templateOptions: {
        required: true,
      }
    },
```

This is related to #1045 ,  where you recommended upgrade to beta 5 and the usage of the new prePopulate hook, however, I not sure how to use it.

**Expected behavior**
Be able to set fields inside the group as required and/or change other properties before form init

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/ngx-formly-field-group-required?file=src%2Fapp%2Fdemo-form%2Fdemo-form.component.ts

**What is the motivation / use case for changing the behavior?**
Reusable field groups may have different behavior/properties on each form whitin the app

* **Angular version:** 6.0.X
* **ngx-formly version:** 5.0.0 beta 22

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/ngx-formly-field-group-required-6ukram
