### ISSUE TITLE
Apply the validator conditionally

### ISSUE THREAD

**Issue by wpcfan** [ngx-formly/ngx-formly#1393]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

Use Case: I have created a unique username async validator, and this validator checks if the username exists. it works prefect when I create a user, but when updating the user, we have to exclude the edited user's username, so I would like to ask if it is possible to conditionally apply a validator. Of course, I can write a new validator for editing, but is there better way to do this?

**Expected behavior**
It would be better to apply the validator conditionally

**Minimal reproduction of the problem with instructions**
None

**What is the motivation / use case for changing the behavior?**
See above

**Please tell us about your environment:**
macOS mojave, VSCode

* **Angular version:** 7.1.X

* **Browser:** [all  ]

* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
just mark the username as `disabled` or use `hideExpression` and the validator will be ignored, so you don't have to do any extra work.

**Comment by wpcfan** [comment]
@aitboudad nope, that's not my case, we are developing a data management project, so the field is allowed to change, but just need to exclude the value when editing.

**Comment by HangLoop** [comment]
@wpcfan May be we can start with this reproduction?
https://stackblitz.com/edit/angular-n8giaw-tr2rxm
If the input value is same as the initial value, validator return valid.

I would also like to know if we can get initial value in the validator or could we add a custom validator that read initial value as a parameter.

**Comment by aitboudad** [comment]
well, I think the edited user's username should be handled through the backend validation.
