### ISSUE TITLE
How to add button type in ngx-formely form repeater 

### ISSUE THREAD

**Issue by mihirhapaliya** [ngx-formly/ngx-formly#1394]
When I Add row in repeater , first one text box and button should appear .

![image](https://user-images.githubusercontent.com/32834137/51621038-a4dce080-1f59-11e9-98cc-838ad66b5a1e.png)

After clicking on button; data is fetched from the server  based on the textbox value and once data is fetched button and textbox will be  hidden and actual row form will be displayed with fetched data.

**How can I achieve this approach in ngx-repeater ?**

here you find the repeater , I have not added the requirement code , since I don't know how to implement it 
https://stackblitz.com/edit/angular-2jcfs7

when clicking on 'add another' row appears as per first image(button + text)
after clicking button actual  row appears as below.
![image](https://user-images.githubusercontent.com/32834137/51621518-b4105e00-1f5a-11e9-8dcf-0b4a0b8c4a3f.png)

**Comment by aitboudad** [comment]
you can achieve your requirement using a [custom template](https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field
) type (for the text box and button) and [hideExpression](https://stackblitz.com/edit/angular-rxlpp4-qjiunw) to display (qty, cost and subtotal) fields after clicking on button.

**Comment by mihirhapaliya** [comment]
I am uisng hide expression property , but I want to show only once button is clicked.

so whenever button is clicked , I am setting one field 'buttonClicked' to true model, and in hideexpression checking that model field and based on that showing another fieldgroup ,

but as per the below code its executing even without a click event ,so  how can I execute only when the button is clicked.

'templateOptions.click': (model) => {
                model['buttonClicked'] = true;
}

I have created custom button as below link.
https://stackblitz.com/edit/angular-ngxformly-button?file=app%2Fapp.component.ts

**Comment by mihirhapaliya** [comment]
please help me on this

**Comment by aitboudad** [comment]
ok only this time, https://stackblitz.com/edit/angular-pamxck
