### ISSUE TITLE
Track onModelChange(blur) by using  root-level(Formly-Form) config

### ISSUE THREAD

**Issue by rizwanspeaks** [ngx-formly/ngx-formly#1395]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Currently, I am getting change event of an individual field from the templateOptions object.

**Expected behavior**

 In formly-form, 'modelChange' event provides the entire model object. And also it triggers for every keyDown.  Here I am expecting a similar method with templateOptions.change behaviour(triggers only after change. (i.e.) not on every keyDown).  And also in this method, I am expecting the argument also as same as templateOptions.change arguments... In my scenario, I am getting 'fields' and 'model' from backend... Same as in your json-powered example. So I am not able to provide a change method to template options for each field... Is there any way to trace each model change from config level? or  do you have a suggestion how could I subscribe to fieldChanges in root component (the one which has formly form)? 

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
> And also it triggers for every keyDown. 

to take change only on blur just pass the following `modelOptions`  to the field
```ts
modelOptions: {
  updateOn: 'blur',
},
```

https://ngx-formly.github.io/ngx-formly/examples/field-options/model-options

**Comment by rizwanspeaks** [comment]
do you have a suggestion how could I subscribe to fieldChanges in root component (the one which has formly form)?

**Comment by aitboudad** [comment]
the method that you're looking for is [changeModel](https://github.com/ngx-formly/ngx-formly/blob/master/src/core/src/lib/components/formly.form.ts#L78).

I'm thinking to add it through the options input but not sure yet,
for now, you can use the following workaround https://stackblitz.com/edit/angular-wpsnfb

**Comment by rizwanspeaks** [comment]
Thanks for your update. It is working fine... One more thing, Is there possible to get 'FormlyFieldConfig' as an argument instead of 'key'?

**Comment by aitboudad** [comment]
nop, but we'll take account of it on it when working on that feature

**Comment by rizwanspeaks** [comment]
okay. Thanks

**Comment by aitboudad** [comment]
added to [V6 Roadmap](https://github.com/ngx-formly/ngx-formly/issues/1365)

**Comment by pdxhunter** [comment]
@aitboudad 

> the method that you're looking for is [changeModel](https://github.com/ngx-formly/ngx-formly/blob/master/src/core/src/lib/components/formly.form.ts#L78).
> 
> I'm thinking to add it through the options input but not sure yet, for now, you can use the following workaround https://stackblitz.com/edit/angular-wpsnfb

I used this workaround, but it no longer works in the latest version of formly. Is there an alternative way to capture the model change (and the field that actually changed) at a global level?

**Comment by aitboudad** [comment]
@pdxhunter can you check the following solution instead: https://github.com/ngx-formly/ngx-formly/issues/3495#issuecomment-1316704827
