### ISSUE TITLE
[Question] What is the `formly` way to remove a form field and its FormControl(s)?

### ISSUE THREAD

**Issue by samtsai** [ngx-formly/ngx-formly#1398]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

I am dynamically adding fields based on User selections on previous form fields.  All of this works as expected, but we allow the User to remove these fields (e.g. similar to repeater examples).  What I cannot figure out is how to properly do a full clean up.

I currently manually handle it by removing each part individually: field from `FormlyFieldConfig[]`, formControl from the form, `null` or deleting the property off of the model.  This process seems a little too manual and I wanted to know if there's a more `formly` way to do this.  See https://stackblitz.com/edit/ngx-formly-ui-material-i9sndp

Note: I'm not looking to using `hide` or `hideExpression` for these fields, since I would rather completely remove them.

**Comment by aitboudad** [comment]
we only deal with repeatable field, so to remove a form field you have to get the field and remove its formControl and model.
dealing with it on our side would produce a breaking change which I'm not sure it worth it right now.

**Comment by aitboudad** [comment]
let's give it a try!

**Comment by aitboudad** [comment]
I propose adding a new option `strict` which force immutability and cleanup the removed field (formControl and model value).

`strict` = immutable( #1427) + cleanup the formcontrol and its model value.

WDYT ?

**Comment by samtsai** [comment]
I generally like immutability pattern, so I think adding `strict` is reasonable!

**Comment by aitboudad** [comment]
added to `V6` roadmap
