### ISSUE TITLE
Cannot add validation dynamically when extending FieldType

### ISSUE THREAD

**Issue by nkovacic** [ngx-formly/ngx-formly#1403]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

**Current behavior**

Cannot add validation dynamically when extending FieldType. Is this possible in ngxFormly?
**Expected behavior**
Validation should be added to this.field.validators.validation field

**Minimal reproduction of the problem with instructions**
```
import { Component, OnInit } from '@angular/core';
import {  Validators } from '@angular/forms';
import { FieldType } from '@ngx-formly/core';

const emailRegex =  new RegExp(/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/);

export function EmailValidator(control: FormControl): ValidationErrors {
    if (control.value && !emailRegex.test(control.value)) {
        return {
            email: true
        };
    }

    return null;
}

@Component({
    selector: 'input-type',
    templateUrl: './input-type.component.html'
})
export class InputType extends FieldType implements OnInit {
    get type() {
        return this.to.type || 'text';
    }

    public ngOnInit() {
        this.prepareValidators();
    }

    private prepareValidators() {
        this.field.validators = this.field.validators || {};

        if (this.type == 'email') {
            //add email validation
        }
    }
}
````

**What is the motivation / use case for changing the behavior?**
Abstracts away email validator when type is set to 'email'

* **Angular version:** 6.0.X

**Comment by aitboudad** [comment]
assigning validation at `onInit` is too late since the field is already built, I'd suggest using the new `prePopulate` callback which is called during building field (but it requires using the new V5 version):
- inside field type: https://stackblitz.com/edit/angular-gqidyp
- using custom extension: https://stackblitz.com/edit/angular-gqidyp-ryhfnv
