### ISSUE TITLE
Proposal: formly-fields

### ISSUE THREAD

**Issue by CristhianParra** [ngx-formly/ngx-formly#1405]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**

Formly is awesome because we can write really less html in favor of JSON configurations, the problem comes when we need to do "complex layouts". 
As the whole form is rendered in a single "formly-form" tag, it is necessary to start writing HTML in the controller (TS file), in order to be able to layout and add other things not related to the form (labels, lines, spaces, helper texts, etc), like in the docs example
```HTML
<form [formGroup]="form" (ngSubmit)="submit()">
  <formly-form [model]="model" [fields]="fields" [options]="options" [form]="form">
    <button type="submit" class="btn btn-primary submit-button" [disabled]="!form.valid">Submit</button>
  </formly-form>
</form>
```
```TS
fields: FormlyFieldConfig[] = [
    {
      fieldGroupClassName: 'display-flex',
      fieldGroup: [
        {
          className: 'flex-1',
          type: 'input',
          key: 'firstName',
          templateOptions: {
            label: 'First Name',
          },
        },
        {
          className: 'flex-1',
          type: 'input',
          key: 'lastName',
          templateOptions: {
            label: 'Last Name',
          },
          expressionProperties: {
            'templateOptions.disabled': '!model.firstName',
          },
        },
      ],
    },
    {
      template: '<hr /><div><strong>Address:</strong></div>',
    },
    {
      fieldGroupClassName: 'display-flex',
      fieldGroup: [
        {
          className: 'flex-2',
          type: 'input',
          key: 'street',
          templateOptions: {
            label: 'Street',
          },
        },
        {
          className: 'flex-1',
          type: 'input',
          key: 'cityName',
          templateOptions: {
            label: 'City',
          },
        },
        {
          className: 'flex-1',
          type: 'input',
          key: 'zip',
          templateOptions: {
            type: 'number',
            label: 'Zip',
            max: 99999,
            min: 0,
            pattern: '\\d{5}',
          },
        },
      ],
    },
    {
      template: '<hr />',
    },
    {
      type: 'input',
      key: 'otherInput',
      templateOptions: {
        label: 'Other Input',
      },
    },
    {
      type: 'checkbox',
      key: 'otherToo',
      templateOptions: {
        label: 'Other Checkbox',
      },
    },
  ];
```

**Expected behavior**

If we could render each field separately with something like "formly-field", we can write classes related to layout, styles and other stuff inside the view (HTML file). This way the responsibilities of the controller and the view are kept separate, something like this

```HTML
<form [formGroup]="form" (ngSubmit)="submit()">
  <formly-form [model]="model" [fields]="fields" [options]="options" [form]="form">
    <div class="display-flex">
      <formly-field class="flex-1" key="firstName"></formly-field>
      <formly-field class="flex-1" key="lastName"></formly-field>
    </div>
    <hr/>
    <div><strong>Address:</strong></div>
    <div class="display-flex">
      <formly-field class="flex-2" key="street"></formly-field>
      <formly-field class="flex-1" key="cityName"></formly-field>
      <formly-field class="flex-1" key="zip"></formly-field>
    </div>
    <hr/>
    <formly-field key="otherInput"></formly-field>
    <formly-field key="otherToo"></formly-field>
    <button type="submit" class="btn btn-primary submit-button" [disabled]="!form.valid">Submit</button>
  </formly-form>
</form>
```
```TS
fields: FormlyFieldConfig[] = [
  {
    type: 'input',
    key: 'firstName',
    templateOptions: {
      label: 'First Name'
    }
  },
  {
    type: 'input',
    key: 'lastName',
    templateOptions: {
      label: 'Last Name'
    },
    expressionProperties: {
      'templateOptions.disabled': '!model.firstName'
    }
  },
  {
    type: 'input',
    key: 'street',
    templateOptions: {
      label: 'Street'
    }
  },
  {
    type: 'input',
    key: 'cityName',
    templateOptions: {
      label: 'City'
    }
  },
  {
    type: 'input',
    key: 'zip',
    templateOptions: {
      type: 'number',
      label: 'Zip',
      max: 99999,
      min: 0,
      pattern: '\\d{5}'
    }
  },
  {
    type: 'input',
    key: 'otherInput',
    templateOptions: {
      label: 'Other Input'
    }
  },
  {
    type: 'checkbox',
    key: 'otherToo',
    templateOptions: {
      label: 'Other Checkbox'
    }
  }
]
```
I really like to know what do you think about that, and submit a PR if the proposal is accepted :)

**Comment by aitboudad** [comment]
why not, this would allow more flexibility even though the use case can be achieved with a combination of a [custom wrapper](https://ngx-formly.github.io/ngx-formly/examples/other/nested-formly-forms) and [className](https://ngx-formly.github.io/ngx-formly/examples/other/advanced-layout-flex).

**Comment by juristr** [comment]
yep, while this would allow more flexibility, on the othr side for large complex forms you'd again end up with a lot of HTML you have to write, basically nearly returning to traditional reactive forms.

**Comment by mathpaquette** [comment]
I can understand the added flexibility that the PR brings but at some point this is in contradiction with the maintenability and reuse principle of  Formly. If you can’t extract a pattern out of your layout why using it?

**Comment by aitboudad** [comment]
@mathpaquette I've got your point, let say it may usefull when working on a prototype or for education purpose or a layout that you may need only for one specific form (not reusable).
also since angular doesn't allow yet to [apply directive dynamically](https://github.com/angular/angular/issues/11716) this may be the solution of the implementation of [Angular Material FlexLayout](https://github.com/ngx-formly/ngx-formly/issues/865) for example


I'll revise this after finishing with [V6](https://github.com/ngx-formly/ngx-formly/issues/1365), the implementation should be part of a separated package if we decide to go with it.

Also I've added a note about the ability to define an inline field type.
