### ISSUE TITLE
Integrate Angular Material Chips component into formly

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1410]
**I'm submitting a** 
```
[x] support request
```

Hello,

I've integrated the Angular Material Chips component to be used by formly. I am unhappy about 2 things in the integration and I am seeking your advice:

- Implementing the Angular Material Chips component requires clearing the form input control used. Hence, clearing the formControl on the formly field type. Formly requires this field specifically when to query the status of the field to know if it is valid or not and accordingly show an error message.

- To solve the above issue, I've introduced a new hidden form input field that is assigned the fromControl and formlyAttributes fields.

- The problem with the above approach is that the required error message is never shown on the chips component.

- In addition, at startup, I need to intialize the model of the chips component to be an array of things. Also, I need to load any defaultValue passed in, and finally, update the formControl value. This raises the famous Angular exception `ExpressionChangedAfterItHasBeenCheckedError`

**Current behavior**
- When the field is required the error message is not shown beneath the chips components.

- I am curently using the `setTimeout` with a waiting time of 0 to set the initial value of the formControl so that to avoid the `ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked`

**Expected behavior**
- The error message appears when I tap inside the field without selecting any value
- Be able to update `formControl` value without any exceptions

**Minimal reproduction of the problem with instructions**
You may try the same on StackBlitz: https://stackblitz.com/edit/ng-material-chips-formly

**What is the motivation / use case for changing the behavior?**
Integrate Angular Material Chips component into formly

**Please tell us about your environment:**

* **Angular version:** 7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [TypeScript X.X]

**Comment by aitboudad** [comment]
by managing model changes through `formControl` things are getting easy for other issues:
- `defaultValue` either pass it through `ngModule` declaration or through `defaultOptions` property which landed in `V5`
- for error message you've to use our 'form-field' wrapper

here is a working example https://stackblitz.com/edit/ng-material-chips-formly-r4ndpr

**Comment by bhaidar** [comment]
Thanks @aitboudad for your assistance.

**Comment by aitboudad** [comment]
> By the way, would you be interested to submit this to the demos? I can send the PR.

yes please!

**Comment by samtsai** [comment]
I was literally working on the same thing yesterday :)

**Comment by Githamza** [comment]
Is this added to the package since?

**Comment by ermarkar** [comment]
is this merged? no description about chips in documentation

**Comment by aitboudad** [comment]
> is this merged? no description about chips in documentation

Not yet, PR welcomed!

**Comment by AnilKumar-Brady** [comment]
How Can I use this if ` filter: ['Bilal', 'Haidar']`  comes from a http call?
