### ISSUE TITLE
Validation messages in the form config are ignored for min/max length

### ISSUE THREAD

**Issue by shtefanntz** [ngx-formly/ngx-formly#1411]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When setting validation.messages.minLength / validation.messages.maxLength, the message is not used

**Expected behavior**
The same behaviour as for validation.messages.required or validation.messages.pattern

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-rfcmjm

**What is the motivation / use case for changing the behavior?**
So we don't some internationalization for this errors as well

* **Angular version:** 7

Thanks a lot for all the effort with the library! :D it's awesome!

**Comment by aitboudad** [comment]
try with a lowercase name, since angular return an inconsistent key for these validators: https://stackblitz.com/edit/angular-rfcmjm-jacgfu

**Comment by shtefanntz** [comment]
thanks for the fast reply! :D
