### ISSUE TITLE
hide/show field group based on another field

### ISSUE THREAD

**Issue by ps011** [ngx-formly/ngx-formly#1412]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[X] Query
```

How can I use hideExpression to hide/show a field group?

I have tried but not working. Can you please share an example.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614
