### ISSUE TITLE
configure debounceTime on modelChange event

### ISSUE THREAD

**Issue by BartNetJS** [ngx-formly/ngx-formly#1414]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
ModelChange event fires on every keystroke

**Expected behavior**
Possible to configure a debounce time on modelchange (not field as already possible)

* **Angular version:** 7.2.4

**Comment by aitboudad** [comment]
see https://ngx-formly.github.io/ngx-formly/examples/field-options/model-options

**Comment by BartNetJS** [comment]
I'm I right that this is only a 'field' setting?
![image](https://user-images.githubusercontent.com/4865355/52736953-6a4fec00-2fcb-11e9-8dbf-dfecc49aeed8.png)

I like to set it on the FormlyFormOptions so it is debounced for all fields

**Comment by aitboudad** [comment]
sorry I've missed your note
> not field as already possible

**Comment by aitboudad** [comment]
use a custom extension (landed in `V5`) which allows you to pass the default options during the build process, see the following example https://stackblitz.com/edit/angular-gqidyp-zmudf2

**Comment by BartNetJS** [comment]
one question left, i see that you can name the extension. In your example "defaultOptions".
Is it than also possible to select the pre defined option when declaring a formly form control.
Let's say that i like to have one form to update the model immediately, and on another form debounced?

**Comment by aitboudad** [comment]
> Let's say that i like to have one form to update the model immediately, and on another form debounced?

just pass `options` input with an extra property to differentiate between the two scenario, then inside extension check that property from `field.options` to decide which case you may want to apply
