### ISSUE TITLE
Define functions in templateOptions with JSON Powered forms

### ISSUE THREAD

**Issue by mathpaquette** [ngx-formly/ngx-formly#1415]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

Using Formly with JSON powered forms and I want let my users to create their own event handlers in the templateOptions. I doubt it's possible but I want to confirm with you.
TemplateOptions are converted in simple objects.

**Expected behavior**

Be able to define callable functions in the templateOptions

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

6.0+

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
do you to apply them within a custom field type or globally?

**Comment by mathpaquette** [comment]
@aitboudad my use case is with a custom field type but I want them to be able to define custom function in order to use this custom type.

**Comment by aitboudad** [comment]
I see, check my comment https://github.com/ngx-formly/ngx-formly/issues/1403#issuecomment-458955243
