### ISSUE TITLE
Example "Repeating Section" on Stackblitz fails to load

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1423]
```
[x] bug report => search github for a similar issue or PR before submitting
```
Example
https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section

fails on Stackblitz to load: 
Error in /turbo_modules/@angular/compiler@7.2.4/bundles/compiler.umd.js (2496:21)
Can't resolve all parameters for RepeatTypeComponent: (?).

**Comment by aitboudad** [comment]
it should be fixed once rc2 released, injecting `FormlyFormBuilder` is now optional for `RepeatTypeComponent`.

in the meantime you may try with:

```ts
import { FormlyFormBuilder } from '@ngx-formly/core';
...
  constructor(builder: FormlyFormBuilder) {
    super(builder);
  }
``

**Comment by aitboudad** [comment]
`rc1` released, it should work now!

**Comment by FritzHerbers** [comment]
thx
