### ISSUE TITLE
npm versions out of sync with github version

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1424]
```
[x ] bug report
```

@aitboudad, as you said you just released rc-1 (github tag), however I see in npm already version rc-3.

https://www.npmjs.com/package/@ngx-formly/core, see version

Maybe this behaviour is not intended.

**Comment by aitboudad** [comment]
I've noticed that some files are missing in the `rc1` and after debugging (`rc2`) I've noticed that the latest `npm` version is the cause of that issue.
so  I've downgrade my version into `6.7` and published `rc.3` which seems working now.
