### ISSUE TITLE
Repeat section inside repeat section

### ISSUE THREAD

**Issue by albertthinc** [ngx-formly/ngx-formly#1432]
Hi

I have created a repeat section inside a repeat section.
The section forms will be opened in a modal window.

How do I reset/remove the formcontrol inside the child repeat section from parent..

Because when I hide the modal window, I want to reset the form and the child repeat sections...

Please suggest any idea to fix it..

**Comment by aitboudad** [comment]
could you please show me an example using `stackblitz`?

**Comment by albertthinc** [comment]
Ok. I will try to put an example.

One question, if I reset a form inside a repeat section, the formgroups created are not removed. Instead the controls inside that formgroup updated to null.

Is there any way to remove created repeat entries on form reset..?

**Comment by aitboudad** [comment]
> Is there any way to remove created repeat entries on form reset..?

update to root model should work (https://github.com/ngx-formly/ngx-formly/issues/1396#issuecomment-458110399) or using `options.resetModel(newModeValuel)`
