### ISSUE TITLE
Updating ngx-formly 5-rc6 in custom template get error 

### ISSUE THREAD

**Issue by enricooliva** [ngx-formly/ngx-formly#1435]
```
[] bug report 
[ ] feature request
[x ] support request
```

I updated ngx-formly from "^5.0.0-beta.5" to "5.0.0-rc.6"

Add now in my custom template I get the error
ERROR TypeError: Cannot read property 'showError' of undefined

This is the reproduction project:
https://stackblitz.com/edit/angular-iwpzfc

In the custom template, I would like to show two fields code description:
![](https://user-images.githubusercontent.com/11843561/45483112-3e94b580-b750-11e8-9769-515c48c4740a.PNG)

Please, can you suggest a solution? 
Thank you.

**Comment by aitboudad** [comment]
overriding the entire field during `ngOnInit` was the cause of losing some properties such as `options`. Either edit a specified property `this.field.fieldGroup[0].hooks = ....` or move the code into `onPopulate` callback or use `FormBuilder` to build your modified field.

**Comment by enricooliva** [comment]
I fixed the https://stackblitz.com/edit/angular-iwpzfc
edit each specific property as you suggested. 

In other cases is not enough if I use onPopulate never called ngOnInit.

In this example, the ngOnInit is never called and if I eliminate the onPopulate 
the component starts a recursion. 

This is the reproduction project:
https://stackblitz.com/edit/angular-iwpzfc-xnqkl4

If I use onPopulate the component has a different execution context?
![image](https://user-images.githubusercontent.com/11843561/53186204-d4d2de80-3600-11e9-8133-e8a45bfd71d4.png)

Please, can you suggest a workaround?
Thank you.

**Comment by aitboudad** [comment]
> If I use onPopulate the component has a different execution context?

normally those properties should be present except `formControl` try with `postPopulate`, if not
can you show me an example where I can reproduce it.

> In this example, the ngOnInit is never called and if I eliminate the onPopulate
the component starts a recursion.

probably you're trying to re-render the same component which produces a recursion.

**Comment by enricooliva** [comment]
> normally those properties should be present except `formControl` try with `postPopulate`, if not
> can you show me an example where I can reproduce it.

This is reproduction example with postPopulate: 
https://stackblitz.com/edit/angular-iwpzfc-ej2tvf

1) never called ngOnint
2) in the `onFileChanged(event) { ` get the error:
```
ERROR
Error: Cannot read property 'formControl' of undefined
```

I think is formly-field inside a formly-field the problem.

**Comment by enricooliva** [comment]
I removed the formly-field inside the template and now it's ok.
https://stackblitz.com/edit/angular-iwpzfc-ej2tvf

@aitboudad  in the custom template when in onPopulate I change the field type to a ngx-form type like input, select ... something broken.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1091#issuecomment-466511867
