### ISSUE TITLE
angular prod:aot build breakes custom fields

### ISSUE THREAD

**Issue by furier** [ngx-formly/ngx-formly#1439]
**I'm submitting a**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
`node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --prod --aot`

with the prod aot build formly cant seem to find any of my custom field types

```
main.db7df37e2df5d1221f3b.js:1 ERROR Error: [Formly Error] There is no type by the name of "pp-input-v2"
    at e.getType (main.db7df37e2df5d1221f3b.js:1)
    at e.createComponentInstance (main.db7df37e2df5d1221f3b.js:1)
    at e.prePopulate (main.db7df37e2df5d1221f3b.js:1)
    at main.db7df37e2df5d1221f3b.js:1
    at Array.forEach (<anonymous>)
    at e._buildForm (main.db7df37e2df5d1221f3b.js:1)
    at main.db7df37e2df5d1221f3b.js:1
    at Array.forEach (<anonymous>)
    at e._buildForm (main.db7df37e2df5d1221f3b.js:1)
    at e.buildForm (main.db7df37e2df5d1221f3b.js:1)
```

This does not happen with `ng serve`, and it has been tested on 4 different machines. The production build on two machines.

**Expected behavior**

Expect the angular prod aot build to work the same as development build.

**Please tell us about your environment:**

* **Angular version:** 7.2.3

* **Browser:** [Chrome 72, Edge *]

* **Language:** [TypeScript 3.2.4]

* **Node (for AoT issues):** `node --version` = 10.15.1

**Comment by aitboudad** [comment]
reproduction is needed here since our demo is working as expected using aot in production build

**Comment by furier** [comment]
will try to reproduce

**Comment by aitboudad** [comment]
feel free to reopen if you figure out a reproduction

**Comment by furier** [comment]
@aitboudad it was totally unrelated to ngx-formly, the issue was with the aot build not giving any error on the following code, but unable to compile it properly.

```
export const config: ConfigOption = {
  wrappers: (configv1.wrappers || []).concat(configv2.wrappers || []),
  types: (configv1.types || []).concat(configv2.types || []),
  validators: (configv1.validators || []).concat(configv2.validators || []),
};
```

refactoring the code to this made it work
```
export const config: ConfigOption = {
  wrappers: [...(configv1.wrappers || []), ...(configv2.wrappers || [])],
  types: [...(configv1.types || []), ...(configv2.types || [])],
  validators: [...(configv1.validators || []), ...(configv2.validators || [])],
};
```
