### ISSUE TITLE
Custom template control

### ISSUE THREAD

**Issue by maxkha-3** [ngx-formly/ngx-formly#1447]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

Hello, I am quite new to Formly and currently investigating, whether it can be used for my application, which I am working on at the moment.

**Expected behavior**
So, I have successfully created custom templates for radio button groups, multiselects, etc, by using the `[formControl]` binding in the template. However, now, I would like to implement a template, which works as a boolean type, by displaying a Card from PrimeNG library [https://www.primefaces.org/primeng/#/card](https://www.primefaces.org/primeng/#/card) with a white background being interpreted as false and blue background being interpreted as true. User should be able to click the card to alter its binary value. Binding to [formControl] does notwork, as this component is not able to hold any values (I get an error: No value accessor for form control with unspecified name attribute). So, I was wondering whether it is possible to bind a variable, declared in the class of the template to the formControl in following way:

``` typescript
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
    selector: 'app-formly-field-select-card',
    template: `
        <p-card [header]="to.label" [formlyAttributes]="field" [formControl]="value" (click)="onClick()">
            {{ to.placeholder }}
        </p-card>
    `,
})
export class SelectCardFormlyTypeComponent extends FieldType {
    value: boolean;

    constructor() {
        super();
        // Initialize this.value by getting it from the form model somehow.

    }

    onClick = () => {
        this.value = !this.value;
    }
}
```

I am running the latest versions of Angular and Ngx-Formly.

Thank you!

**Comment by aitboudad** [comment]
to get the field value you may use `this.formControl.value` and to set a new value use `setValue` or `patchValue`

```ts
onClick = () => {
  this.formControl.setValue(!this.formControl.value)
}
```

**Comment by maxkha-3** [comment]
Thanks alot for your help, much appreciate your quick reply! This did the trick. Closing the issue.

**Comment by aitboudad** [comment]
> I am running the latest versions of Angular and Ngx-Formly.

if you're working on a new project I'd suggest using the `V5` version which will be released soon

**Comment by maxkha-3** [comment]
Ok, I will keep that in mind, thanks!

**Comment by AhmedBHameed** [comment]
Hi @aitboudad, Dose the custom input work with version 3 ??
I'm getting an error related to
```txt
Can't bind to 'formlyAttributes' since it isn't a known property of 'input'. ("
            type="input"
            [formControl]="formControl"
            [ERROR ->][formlyAttributes]="field"
        />
    </div>
"): ng:///FormInputModule/FormlyInputTextComponent.html@5:12
```

**Comment by HamzaMoiyadi** [comment]
Hi, 
Commenting here since I see a thread existing on this issue.

I'm facing the same issue as @AhmedBHameed , except that I currently just have 1 custom component which throws the errors
```
Can't bind to 'formControl' since it isn't a known property of 'input'.
    
    12          <input type="button" value="yo" [formControl]="formControl" [formlyAttributes]="field" aria-label="Button" />
```
Using `"@ngx-formly/core": "^5.8.0",`

**Comment by aitboudad** [comment]
@HamzaMoiyadi you should import `ReactiveFormsModule` alongside with `FormlyModule` in the `AppModule`.

**Comment by HamzaMoiyadi** [comment]
I have, in both AppModule as well as my Lazy Loaded Module, but to no avail ._.

**Comment by aitboudad** [comment]
Ensure they are imported where the custom component is imported else I may need a reproduction example.

**Comment by HamzaMoiyadi** [comment]
> Ensure they are imported where the custom component is imported else I may need a reproduction example.

So I loaded both FormlyMaterialModule as well as FormlyModule in both the App & Lazy module, so it's working perfectly now!
Thank you :)
