### ISSUE TITLE
DevExtreme support

### ISSUE THREAD

**Issue by Logic-Bits** [ngx-formly/ngx-formly#1448]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[x] support request
```

Hello.

We are using DevExtreme - also a very popular framework.
Do you have interest in supporting that too?

Best!

**Comment by aitboudad** [comment]
added in our [roadmap](https://github.com/ngx-formly/ngx-formly/issues/1365), not sure if it worth it but we'll evaluate it for sure!

**Comment by revenger1986** [comment]
We are also using DevExtreme, so I am also interested if support for devextreme will be available.

**Comment by aitboudad** [comment]
@revenger1986 thanks for the comment, it'll be available soon!

**Comment by MussaratAziz** [comment]
@aitboudad any update?
