### ISSUE TITLE
Intended way of changing Repeating section repeats externally?

### ISSUE THREAD

**Issue by newsash** [ngx-formly/ngx-formly#1452]
```
[?] bug report => search github for a similar issue or PR before submitting
[?] feature request
[X] support request
```

I want to change Repeat section items count from the component where the form defined. Is there a clean way to do this?

Clean example where I want to bind 'investmentsCount' input to the repeat section: https://stackblitz.com/edit/angular-g1zhvb

Example with my best attempt, where expressionProperty doesn't updating value for some reason (**a bug probably?**) https://stackblitz.com/edit/angular-shputg 

UPD:
Finally got it working (but not as clean as I want) https://stackblitz.com/edit/angular-shputg-4xbkgz

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-shputg-roczzo

**Comment by newsash** [comment]
Thank you. Two more questions:
1. Could you please add this use case to the [examples](https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section)?
2. Should I create a separate issue with bug report about expression properties not working on "Repeating section"? https://stackblitz.com/edit/angular-12zvl5

**Comment by aitboudad** [comment]
> 1. Could you please add this use case to the [examples](https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section)?

PR welcomed.

> 2. Should I create a separate issue with bug report about expression properties not working on "Repeating section"? https://stackblitz.com/edit/angular-12zvl5

see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614
here is a working example: https://stackblitz.com/edit/angular-12zvl5-mm6alo
