### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by furier** [ngx-formly/ngx-formly#1456]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Very hard to add [Drag and Drop](https://material.angular.io/cdk/drag-drop/overview) to the tag `<formly-form>` and `<formly-field>`. I need to use `nativeElement.querySelector` stuff to get to the correct elements and add drag and drop functionality to those elements via their service and not via their directives as shown in the documentation. 

```
  private initDragAndDrop() {
    const _this = this;
    const dropListRef = _this.dragDrop
      .createDropList(_this.formlyForm.nativeElement)
      .withItems(Array.from(_this.formlyForm.nativeElement.querySelectorAll<HTMLElement>('formly-field')).map(field => {
        const dragRef = _this.dragDrop.createDrag(field);
        const dragHandle = field.querySelector<HTMLElement>('div.drag-handle');
        if (dragHandle) {
          dragRef.withHandles([dragHandle]);
        }
        dragRef.withBoundaryElement(_this.formlyForm.nativeElement);
        return dragRef;
      }));
    dropListRef.withOrientation('vertical');
    dropListRef.dropped.subscribe(({ previousIndex, currentIndex }) => {
      // BUG: previousIndex, currentIndex are not always updated and often the same number so nothing happens...
      // BUG: https://github.com/angular/material2/issues/14873#issuecomment-461039077
      // * The problem might be flexbox, display block may work better.
      moveItemInArray(_this.fields, previousIndex, currentIndex);
      _this.fields = [..._this.fields]; // force rerender of fields after reordering
    });
  }
```

The biggest problem tho is that the drag and drop functionality doesn't work properly, `previousIndex, currentIndex` when dragging and dropping elements bug out and are often if not always the same number, so nothing gets moved. I have read on the github [issue](https://github.com/angular/material2/issues/14873#issuecomment-461039077) that it might be flexbox problems, but I'm not sure if I have a way to override the display property on the `<formly-field>` elements?

**Expected behavior**
I would like it to be easier to add drag and drop functionality and I am hoping you guys have an idea on how I could go about doing that a simpler way, and in a way that works.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-material-ngx-formly-drag-and-drop

Change the order of the elements up and down and you will se that they do not always change place and jump up and down

**What is the motivation / use case for changing the behavior?**
Be able to change the order of fields in an ngx-formly form

**Please tell us about your environment:**
Windows 10
VS Code
NPM
ng serve

* **Angular version:** 7.2.3

* **Browser:** Chrome 72 

* **Language:** 3.2.4 

* **Node (for AoT issues):** `node --version` = 10.15.1

**Comment by aitboudad** [comment]
use custom field type with-in a field group, see https://stackblitz.com/edit/angular-material-ngx-formly-drag-and-drop-u5sy9g

**Comment by furier** [comment]
Thank you, I will have a look at that tomorrow at work. :)

**Comment by baryshkov** [comment]
@aitboudad if i use this.field.fieldGroup in moveItemArray visual representation changes, but not a model. What I can do to trigger the change?

**Comment by aitboudad** [comment]
@baryshkov the order of prop inside an object doesn't matter unless it's an array type which not the case for the above example.
