### ISSUE TITLE
Is there a way to access the material datepicker variable from an event or expression functions?

### ISSUE THREAD

**Issue by mattarau** [ngx-formly/ngx-formly#1461]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
The [ViewChild #picker](https://github.com/ngx-formly/ngx-formly/blob/dbc9ae20b570ebbf170ac6bec0df3942d261185b/src/material/datepicker/src/datepicker.type.ts#L23) doesn't seem to be exposed so it can be used from functions (unless I'm missing something from the functions docs)

**Expected behavior**
I can call the datepicker's `.open()`, `.close()` and `.select(date)` methods based on a field event (i.e. focus) or an expression.

**Minimal reproduction of the problem with instructions**
(It's not a bug)

**What is the motivation / use case for changing the behavior?**
This would allow a lot of different use cases, but the most obvious would be to open the datepicker when the user set focus on the field.

**Please tell us about your environment:**

macOS 10.14.13, Vim 8.1.800, yarn 1.13...

* **Angular version:** 2.0.X
7.1.1

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 3.1.6

* **Node (for AoT issues):** `node --version` =
8.9.2

**Comment by aitboudad** [comment]
I would prefer to wait until the following issue is fixed https://github.com/angular/material2/issues/8905.
for now, just create a custom `datepicker` which you may adjust, exposing it won't solve the issue anyway.
