### ISSUE TITLE
Multi-Step Form - Using a single form

### ISSUE THREAD

**Issue by gabrielemilan** [ngx-formly/ngx-formly#1463]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```
**What is the motivation / use case for changing the behavior?**

I would like to implement linear mode using a single form like

https://material.angular.io/components/stepper/overview#using-a-single-form

Is that feature supported? Someone can help me with configuration?

Thank you very much.

**Please tell us about your environment:**

* **Angular version:** 7.0.X

* **Browser:** all

* **Language:** all

**Comment by aitboudad** [comment]
see https://ngx-formly.github.io/ngx-formly/examples/advanced/multi-step-form

**Comment by gabrielemilan** [comment]
Thanks for reply, i saw that example, but i can't set it in linear mode. If I set the linear property i can always go to others step though the current is not valid

**Comment by aitboudad** [comment]
pass `stepControl` input to the `mat-step` component:

```html
<mat-step ... [stepControl]="form.at(index)">
  ...
</mat-step>
```

**Comment by gabrielemilan** [comment]
Ok i will try, thank you very much
