### ISSUE TITLE
How to call change function for JSON field source

### ISSUE THREAD

**Issue by princepc** [ngx-formly/ngx-formly#1464]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Can't assign a change event function like this in templateOptions:
"change": "function($event) { this.alertme(); }"
and binding like this:
if (f.templateOptions && f.templateOptions.change) {
          f.templateOptions.change = f.templateOptions.change.bind(this);
}
It produces this error in console:
Error: f.templateOptions.change.bind is not a function

**Expected behavior**
Able to call a change function for dynamically loaded fields

**Minimal reproduction of the problem with instructions**
see this stackblitz for example:
https://stackblitz.com/edit/angular-g1h2be-m7aekd

Chrome 71

**Comment by aitboudad** [comment]
in formly we only evaluate the js expression and not define the entire function, I'd suggest the following solution instead: https://stackblitz.com/edit/angular-g1h2be-hpwffy

**Comment by princepc** [comment]
worked perfectly many thanks!

**Comment by carlwang87** [comment]
@aitboudad  This solution is great. And I encountered another question, in the source code, the change event is FormlyTemplateOptions which accepts two arguments, field and event. So can I get these two arguments in the alterme() function in the example you took?

`type FormlyAttributeEvent = (field: FormlyFieldConfig, event?: any) => void`

Thanks.

**Comment by carlwang87** [comment]
There is an error,

`ERROR in src/app/ngx-formly/user-registry-form/user-registry-from.component.ts(222,61): error TS2345: Argument of type 'FormlyAttributeEvent' is not assignable to parameter of type 'string'.`

Caused by the 
`Function('$event', field.templateOptions.change)`

Ignore this error during the compiling ?

**Comment by aitboudad** [comment]
@carlwang87 rely on a new parameter name instead of `change` use for example `changeExpr`

> So can I get these two arguments in the alterme() function in the example you took?

https://stackblitz.com/edit/angular-g1h2be-hpwffy
