### ISSUE TITLE
Get Data from http to select 

### ISSUE THREAD

**Issue by boufenzi** [ngx-formly/ngx-formly#1465]
Hello Everybody, 
I'm having some trouble getting data from http to populate to select.
the issue is when i show the form,  the first time my select is empty because the data came undefined (probably due to asynchronos) but when i show my form the second time it works fine.
Do anybody know what i'm doing wrong in my code ? thank you in advance 
here is how i implement the select part in my component: 
```
   {
          className: 'col-4',
          type: 'select',
          key: 'ID_GROUPE',
          templateOptions: {
            label: 'Groupe',
            required: false,
            options: this.getBackEndData.getDonnee(),
            valueProp: 'id',
            labelProp: 'groupeName',
          },
        },
```

My service : 
```
  getDonnee(): Observable<any[]> {
     this.http.get('http://localhost:8080/groupes').toPromise().then(any => {
       this.groupes= any['content'];
     });
     return of(this.groupes);
  }
```

**Comment by juristr** [comment]
Hey, you can actually just directly hook the observable to the select

```
{
   key: 'ID_GROUP',
   type: 'select',
   templateOptions: {
      ...
      options: this.dataService.getDonnee()
   }
}
```

Note, `dataService.getDonne()` should return an `Observable`, not a `Promise`, so just leave the `toPromise()` out.

Moreover if you need to customize the data that gets returned, just use the RxJS `map(..)` operator, like

```
{
   key: 'ID_GROUP',
   type: 'select',
   templateOptions: {
      ...
      options: this.dataService.getDonnee()
                .pipe(
                  map(data => {
                     // transform/manipulate data and return the manipulated result
                    return data;
                  }
               )
   }
}
```

**Comment by boufenzi** [comment]
Thank you for your response, Btw i learned about angular formly by watching your videos, thank you ^^

**Comment by juristr** [comment]
@boufenzi Oh thank you, glad you liked them. I planning some more of them based on my experiences of using Formly in large projects. Stay tuned 😉.

And 👏 to @aitboudad for all the hard work on making Formly so awesome.

**Comment by stefani0** [comment]
What if our function from API is parametrized ?
