### ISSUE TITLE
Cannot quick start with Ionic UI (node_modules error)

### ISSUE THREAD

**Issue by hoamar** [ngx-formly/ngx-formly#1466]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When going through the ngx-formly Ionic UI quick start I am stuck on step 3 (Import the FormlyModule and UI (pre-defined types/templates)). When adding FormlyIonicModule an error is thrown:
ERROR in ./node_modules/@ngx-formly/ionic/fesm5/ngx-formly-ionic.js
Module not found: Error: Can't resolve 'ionic-angular' in '/Users/myUser/Projects/ionicTest/node_modules/@ngx-formly/ionic/fesm5'
 ｢wdm｣: Failed to compile.

**Expected behavior**
This error is a blocker and is not allowing me to continue with the initialization of the Ionic UI formly quick start.

**Minimal reproduction of the problem with instructions**
1) I started a new project with the Angular CLI (7.3.0) quick start: 
ng new my-app
2) From there I followed the quick start instruction of ngx-formly ionic UI:   
npm install @angular/forms @ngx-formly/core --save
npm install @ngx-formly/ionic --save
3) I then followed the instructions of importing the FormlyModule and UI. I ensured my module ts file had these imports:
import {NgModule} from '@angular/core';
import {ReactiveFormsModule} from '@angular/forms';
import {FormlyModule} from '@ngx-formly/core';
import {FormlyBootstrapModule} from '@ngx-formly/bootstrap';
import {FormlyIonicModule} from '@ngx-formly/ionic';
@NgModule({
  imports: [
    ...,
    ReactiveFormsModule,
    FormlyModule.forRoot(),
    FormlyBootstrapModule,
    FormlyIonicModule
  ]
})
4) I then saw an error appear in my terminal:
ERROR in ./node_modules/@ngx-formly/ionic/fesm5/ngx-formly-ionic.js
Module not found: Error: Can't resolve 'ionic-angular' in '/Users/myUser/Projects/ionicTest/node_modules/@ngx-formly/ionic/fesm5'
 ｢wdm｣: Failed to compile.
5) This stops me from proceeding with initializing the project. The line "FormlyIonicModule" seems to be issue because when adding it is when the error appears.

**Please tell us about your environment:**
MacOS High Sierra operating system Version 10.13.6
Visual Studio Code IDE Version 1.30.2

* **Angular version:** 
Angular 7.2.3
Angular CLI 7.3.0

* **Browser:** 
Google Chrome Version 63.0.3239.108 (Official Build)

* **Language:** 
typescript 3.2.4

* **Node (for AoT issues):** 
Node 10.15.1

**Comment by aitboudad** [comment]
ionic should be installed too by following their doc.
for the newest ionic v4, you may need to use our v5.rc version

**Comment by hoamar** [comment]
Going to my package.json and changing the "@ngx-formly/core": & "@ngx-formly/ionic" from "^4.8.2" to "^5.0.0-rc.11" got rid of the error.

I think an adjustment to the installation steps should be made so that it can run smoothly or new users will have the same issue I had.

Thanks

**Comment by sanjeevsubedi** [comment]
@hoamar 
I was also facing the similar issue. The following versions solved my problem
    "@ionic/angular": "^4.0.2",
    "@ngx-formly/core": "^5.0.0-rc.11",
    "@ngx-formly/ionic": "^5.0.0-rc.11"

@aitboudad I think we need to have an updated document, which is very much challenging for the constantly evolving library :) Also, the latest version in the npm is 4.8.2. Once, the rc version is finalized and stable and published in the npm, the problem should be resolved.

**Comment by aitboudad** [comment]
the stable version should be released this weekend.

> which is very much challenging for the constantly evolving library :) 

no worry about this :), after [V6](#1365) we'll have enough time to focus on the doc and website (not our hight priority for now).

**Comment by sanjeevsubedi** [comment]
@aitboudad Thank you.
