### ISSUE TITLE
Docs: Update section about json schema with new introduced changes about "widget"

### ISSUE THREAD

**Issue by juristr** [ngx-formly/ngx-formly#1469]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

Update docs with changes introduced in #1467

**Comment by aire-con-gas** [comment]
I'll take a shot at it.

**Comment by thorgod** [comment]
Nice job! Looking forward to seeing what widgets can do. (I have no clue even after reading the PR(s))

**Comment by aitboudad** [comment]
@thorgod this only concern `json-schema` support and not formly json format.
@aire-con-gas adding an example would be enough with a small description, the `json-schema` example can be added in https://github.com/ngx-formly/ngx-formly/tree/master/demo/src/app/examples/advanced/json-schema

**Comment by thorgod** [comment]
Oh so we can use "$ref": ....  Cool! =)

**Comment by aitboudad** [comment]
close in favor of #1459
