### ISSUE TITLE
Multiple instances of formly-form on the same page are overlapping

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1470]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
When placing multiple instances of formly-form on the same page, the fields overlap and only the latest wins.

This could be happening due to the fact that Angular re-uses components and hence I am getting this odd behavior.

I've put down a sample that you can check and assess.

https://stackblitz.com/edit/angular-xjh3ep

Thank you
Bilal

**Comment by aitboudad** [comment]
that's a mutability issue, we've introduced `immutable` mode in order to solve that common issue.

So you've several ways to solve that:
- copy fields input before passing it to the `formly-form`
- use `immutable` mode for a specific formly-form https://github.com/ngx-formly/ngx-formly/issues/1429#issuecomment-465186967
- enable `immutable` mode globally through `NgModule` declaration.
```ts
@NgModule({
  imports: [
    FormlyModule.forRoot({
      extras: { immutable: true }
    }),
  ],
})
```

**Comment by bhaidar** [comment]
Thanks @aitboudad 
When using `immutable` I cannot find the `resetModel()` function on the options object anymore!

When using the first option, it works fine for me. It happens that I have a loop and in each iteration, I render a form. Now, every form component receives its own copy of the fields.

Now the problem is that fields become read-only. Check again the sample after I deep copied the fields:

https://stackblitz.com/edit/angular-xjh3ep

Thanks

**Comment by aitboudad** [comment]
> Now the problem is that fields become read-only.

calling function that return a new object triggers a change detection infinitely, the solution is the copy fields see https://stackblitz.com/edit/angular-xjh3ep

> When using immutable I cannot find the resetModel() function on the options object anymore!

```html
    <form [formGroup]="form" (ngSubmit)="submit()">
      <formly-form #formlyForm ...></formly-form>
      <button type="button" (click)="formlyForm.options.resetModel()">Reset</button>
    </form>
```

**Comment by bhaidar** [comment]
@aitboudad I guess you didn't update the sample above! I still see the old one.

**Comment by bhaidar** [comment]
@aitboudad One more thing, why would change detection run infinitely when calling a function that returns a new object?

**Comment by bhaidar** [comment]
@aitboudad a kind reminder

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-xjh3ep-s6ceut

**Comment by bhaidar** [comment]
So basically, when rendering a form with `ngIf` I need to have a fields property per item form? I just cannot use the same `fields` property all over for each iteration. Is that what I understand?

**Comment by aitboudad** [comment]
with `ngIf` it should work, but rendering the same field in different places may produce some unexpected behavior.

**Comment by bhaidar** [comment]
In fact, my scenario is rendering multiple records in forms. So each form is using the same component, but, the model differs from one form to another.

**Comment by aitboudad** [comment]
but the passed fields input is shared which and each field is responsible to render one component type

**Comment by bhaidar** [comment]
@aitboudad 
True, that's why now what I've done is for each model I push to an array the fields. So I will have an array of the same length of the array of models, each item in this array has a copy of the fields.

Now, I am left with one issue. Since Angular re-uses, the same instance of my Custom Form Wrapper, any state inside the component is not being dealt with it properly. Is there a way to force Angular to either create a new instance of a component inside ngFor or come up with isolation for the state inside the Custom Form Wrapper component?

**Comment by aitboudad** [comment]
> Since Angular re-uses, the same instance of my Custom Form Wrapper

not true

**Comment by bhaidar** [comment]
I am not sure we are talking about the same Form Wrapper. It's a component I've created to wrap the formly form. I noticed that the same ID is given for the components which made me think they are being re-used.

**Comment by bhaidar** [comment]
Notice here. Two instances of my form components are being rendered. Both get the same id.

![image](https://user-images.githubusercontent.com/1163421/54456476-ff7b0780-4766-11e9-8a71-1a83fd355781.png)

**Comment by aitboudad** [comment]
sorry that's out of my scope :)

**Comment by top-dev830** [comment]
Hello, I have same problem.
Is there any solution to solve this?

**Comment by aitboudad** [comment]
@top-dev830 https://github.com/ngx-formly/ngx-formly/issues/1470#issuecomment-473011382

**Comment by top-dev830** [comment]
I've already tried that. But the problem is, I need to use ngFor for iterating several formly-form.
So now I have the same issue @bhaidar has.

**Comment by aitboudad** [comment]
which problem, can you provide a reproduction example using `stackblitz`?

**Comment by top-dev830** [comment]
https://stackblitz.com/edit/angular-hnekxc

plz check here. There's two wizards separated by tabs.
You can change any form fields, but after submit, you can see two models of each form are same.
This is the problem.

**Comment by aitboudad** [comment]
@top-dev830 for each wizard pass a separate form instance similar to the `model`

**Comment by top-dev830** [comment]
can you plz updateh the stackblitz?

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-ok3qiz

**Comment by top-dev830** [comment]
Thanks. It's working very well.
