### ISSUE TITLE
focus on dialog with repeater not working

### ISSUE THREAD

**Issue by BartNetJS** [ngx-formly/ngx-formly#1472]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When setting the focus in a repeater control on a specific row, and the component is called as dialog, the focus is not set

**Expected behavior**
set the focus on a specific row in a dialog component

**Minimal reproduction of the problem with instructions**
I have a sample here:
https://stackblitz.com/edit/angular-47rdkm-v17ztr
In the sample the row is set at customer id 2
It works when you open it by default.
When you click on 'Open as dialog', the same component is opened as dialog and you will notice that the focus is not set.

![image](https://user-images.githubusercontent.com/4865355/54547514-283d1000-49a6-11e9-84bc-0be5a87830fb.png)

![image](https://user-images.githubusercontent.com/4865355/54547551-3ee36700-49a6-11e9-94ea-6a6f780835b5.png)

**Please tell us about your environment:**
I think it is specific to Material.
I found the following, material is calling **FocusTrap.prototype.focusInitialElement** when the dialog is rendered:

When you set break points, you will notice that the focus function in expressionProperties is called, but afterwords the FocusTrap.prototype.focusInitialElement is called and sets the focus on the first element.

sidenote: When you click "open as dialog" yo will see shortly that the focus was set on customer with id 2

![image](https://user-images.githubusercontent.com/4865355/54547157-7e5d8380-49a5-11e9-8ce4-d103e3a35563.png)

* **Angular version:** 7.2.9
Formly: 5.0.0-rc.11

**Comment by aitboudad** [comment]
pass `false` to  `autoFocus` config:

```ts
this.dialog.open(AppComponent, <MatDialogConfig>{
  minWidth: '80vw',
  autoFocus: false,
});
```

**Comment by BartNetJS** [comment]
wow, you answer quicker than I can ask my question
Thanks!
