### ISSUE TITLE
[QUESTION] Really need reCaptcha, can I use ngx-recaptcha?

### ISSUE THREAD

**Issue by moplin** [ngx-formly/ngx-formly#1473]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I really need to use recaptcha, I am getting to much spam.

**Expected behavior**
Integrate captcha to de form.

* **Angular version:** 7.X

So the question,  I found ngx-recaptcha, can I integrate  it to formly, or what would be the best way to use recaptcha? Please some help.

**Comment by aitboudad** [comment]
yes and easy to implement, just follow our guide https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field
