### ISSUE TITLE
I'm getting strange error

### ISSUE THREAD

**Issue by AhmedBHameed** [ngx-formly/ngx-formly#1475]
My error is strange, I did not find any info about it so i'm wonder if you already encounter with this issue:

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
> Template parse errors: Can't bind to 'appearance' since it isn't a known property of 'mat-form-field' ...

**Expected behavior**
Following simple example in documentation [here](https://stackblitz.com/angular/roaogbqrodd?file=src%2Fapp%2Fapp.component.html) should make it work!!

**Minimal reproduction of the problem with instructions**
![error](https://i.ibb.co/Yddp3bM/Deepin-Screenshot-select-area-20190319200221.png)

**Please tell us about your environment:**

Angular: 5
angular-material: 5.0.0
Formly: 4.8.2
ngx-formly/material: 4.8.2

* **Browser:** Chrome

* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` = 11.6.0

**app.module.ts**
```typescript
@NgModule({
[...]
imports: [
FormlyModule.forRoot({}),
FormlyMaterialModule,]
}),
[...]
```

**lazy-module.module.ts**
```typescript
// imports module goes here.

@NgModule({
    imports: [
        CommonModule,
        ContactDetailsRoutingModule,
        ReactiveFormsModule,
        FormsModule,
        FormlyModule.forChild({}),
        FormlyMaterialModule
    ],
    exports: [MyPersonalContentsPageComponent],
    declarations: [
        ContactDetailsPageComponent,
        NavigationTabsComponent,
        MyPersonalContentsPageComponent
    ]
})
export class ContactDetailsModule {}
```

**my-personal-contents-page.component.html**
```html
<div class="my-personal-contacts-container">
    <form [formGroup]="form">
        <formly-form
            [model]="model"
            [fields]="fields"
            [options]="options"
            [form]="form"
        ></formly-form>
    </form>
</div>
```

**my-personal-contents-page.component.ts**

```typescript
import { Component, OnInit } from '@angular/core';
import { FormGroup } from '@angular/forms';
import { FormlyFieldConfig, FormlyFormOptions } from '@ngx-formly/core';

@Component({
    selector: 'app-my-personal-contents-page',
    templateUrl: './my-personal-contents-page.component.html',
    styleUrls: ['./my-personal-contents-page.component.scss']
})
export class MyPersonalContentsPageComponent implements OnInit {
    form = new FormGroup({});
    model: any = {};
    options: FormlyFormOptions = {};
    fields: FormlyFieldConfig[] = [
        {
            key: 'Input',
            type: 'input',
            templateOptions: {
                label: 'Input',
                placeholder: 'Placeholder',
                description: 'Description',
                required: true
            }
        }
    ];
    constructor() {}

    ngOnInit() {}

    submit(model) {
        console.log(model);
    }
}
```

**Comment by aitboudad** [comment]
for angular `v5` use `@ngx-formly/core@3.x`

| Angular version | Formly version         |
| --------------- | ---------------------- |
| Angular >= 6    | `@ngx-formly/core@4.x` |
| Angular >= 5    | `@ngx-formly/core@3.x` |
| Angular >= 4    | `@ngx-formly/core@2.x` |
| Angular >= 2    | `ng-formly@1.x`        |

**Comment by AhmedBHameed** [comment]
Thank for the rapid help. Well that was a dump mistake by my side.
I installed only the core and the same issue! is that the same applied to `@ngx-formly/material` version 3.x ??

**Comment by aitboudad** [comment]
> I installed only the core and the same issue! is that the same applied to @ngx-formly/material version 3.x ??

yep, the UI version is aligned with the core.

**Comment by AhmedBHameed** [comment]
Man you just save my day after 4.5 hours of searching.
Nice module. Thank you for you hard efforts.
Every thing work smoothly now.
