### ISSUE TITLE
created a type, placed in wrapper, but mat-hint does not show

### ISSUE THREAD

**Issue by cunundrummer** [ngx-formly/ngx-formly#1477]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request
```

**Current behaviour**

I have created a new _type_ of input -> an input with a counter for length.  It does not show up.  

So after some more reading solutions here and the docs, it was recommended to use a wrapper.  So I built a wrapper but the output is not in the right place (mat-hint to be placed at the end under the inputs 'line').  I placed it after the ng-content  #fieldwrapper.  

I tried again without the wrapper - only using the type - and it shows but now I have to 'lines'.

**Expected behaviour**

  A clean input - meaning errors show in the proper location, as should the hint show in the proper location.

**Minimal reproduction of the problem with instructions**
[Stackblitz for my issue](https://stackblitz.com/edit/ngx-formly-ui-material-syinvh)
  The **first** input does not show the <mat-hint>.  I also tried implementing it directly in the wrapper component.

  The **third** input shows the mat-hint, but also controls the maxlength(good!), however, the errors display under the extra line.  I believe the extra line is cause from the mat-form-field tag, but **if that is removed**, then I do see the counter but not properly - see the [stackblitz](https://stackblitz.com/edit/ngx-formly-ui-material-syinvh).

**IGNORE 2nd input**, it works as is.

**What is the motivation / use case for changing the behavior?**

I want to implement a counter for users to know how many chars left they can input & for experimentations sake.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**CHROME**: Version 72.0.3626.121 (Official Build) (64-bit), also used prior version.
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
    "typescript": "~3.2.2"
    "@angular/cli": "~7.3.1",
    "@ngx-formly/core": "^4.8.2",
    "@ngx-formly/material": "^4.8.2"
* **Node (for AoT issues):** `node --version` =  **v10.15.0**

**Comment by aitboudad** [comment]
you can use `description` within `expressionProperties` https://stackblitz.com/edit/angular-bvfka4.

**Comment by cunundrummer** [comment]
So I have tried your solution, and it wasn't the solution I needed.  I slogged on a little, and finally, have a working solution...

```
<mat-form-field>
  <mat-label>{{to.label}}</mat-label>
  <input matInput
         #genericInput
         [id]="to.id"
         [type]="to.type"
         [formlyAttributes]="field"
         [formControl]="formControl"
         [minlength]="to.minLength"
         [maxlength]="to.maxLength"
         [required]="to.required"
  >

  <mat-hint align="end">
    {{genericInput.value.length}} / {{to.maxLength}}
  </mat-hint>
  <mat-error *ngIf="formControl.hasError(errorStr$ | async)">
    <span>{{(errorStr$ | async) || ''}}</span>
    <span style="float: right">{{genericInput.value.length}} / {{to.maxLength}}</span>
  </mat-error>
</mat-form-field>

```

For the errors, I made a BehaviorSubject.  I wrote a method to get all the possible errors for that input (in this case, either 'required', 'maxlength', 'minlength'), and assigned it to the errorStr$ observable(BehaviorSubject).  Now I can get the letter count to show in both error AND no error states. 

Also, I removed the placeholder directive from the input and added a mat-label.  

Finally, I did:
```
this.renderer.listen(this.genericInput.nativeElement, 'input', (ev: Event) => {
      console.log('change registered!');
      this.errorStr$.next(this.getCurrentFormFieldError());
    });
```
in the components .ts file in order to get the proper error (from this.formControl.errors, then .forEach and compare against set of error strings.    

The description property solution worked _statically_, meaning not changing the value.  I tried implementing a change property too, but there is either a debounce or other delay.  I'll placing the renderer.listen method from the component into the formlyFieldConfig description, to see if I can reduce some code. But in the mean time, it works!

I hope this is enough info.  I tried adding an edited stackbiltz, but for some odd reason, stackblitz was bugging out.  Thank you anyway.

**Comment by aitboudad** [comment]
let me think about it, something like the prefix and suffix for cutom errors and hints https://ngx-formly.github.io/ngx-formly/examples/other/material-prefix-suffix

**Comment by cunundrummer** [comment]
I created a repository for my project (as a formly experiment), as thankfully it is going well.  It is still a little messy (as of this time) but functional.  If you or anyone else wants to check it out, it is at [my repostory](https://github.com/cunundrummer/ngx-FormCreator.)

**Comment by aitboudad** [comment]
for validation message you can use `formly-validation-message` which would simplify your wrapper, https://github.com/ngx-formly/ngx-formly/blob/master/src/material/form-field/src/form-field.wrapper.ts#L42

**Comment by aitboudad** [comment]
right now you can use a custom field type that doesn't use our `form-field` wrapper or override `form-field` wrapper.

I would prefer to wait until the following issue https://github.com/angular/material2/issues/6728 get solved before providing any further improvements on this part.

**Comment by Ammudhan** [comment]
@aitboudad Could you please show us some sample code on how to override the form-field wrapper?

**Comment by aitboudad** [comment]
@Ammudhan the material wrapper is the complicated one in our codebase so I would like to avoid overriding it for now, so what's your purpose of adding custom attribute to the Mat-Form-Field element?

**Comment by jasonhodges** [comment]
@aitboudad 

> @Ammudhan the material wrapper is the complicated one in our codebase so I would like to avoid overriding it for now, so what's your purpose of adding custom attribute to the Mat-Form-Field element?

I have a situation where in our project we have a custom directive that moves the label out of the default mat-form-field infix. I have experimented in creating a field type that I can apply said directive to however when I have a more advanced field such as one that has prefix/suffix this solutions fails. Being able to easily override the mat-form-field placed by Formly or attach a directive to the Formly mat-form-field would be great.

**Comment by aitboudad** [comment]
@jasonhodges I may need an example to understand the request as its not clear enough.
