### ISSUE TITLE
Repeat Type Model not Updating (Bug) in Version 4.8

### ISSUE THREAD

**Issue by kritisoft** [ngx-formly/ngx-formly#1478]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

[https://stackblitz.com/edit/angular-puuh1g-bpgbmu](https://stackblitz.com/edit/angular-puuh1g-bpgbmu)

Here the package version is 4.8

After adding rows,  The form is Submitted.

On Submit the Model is Reset, but it is not Updating  the Repeat Type.

**Expected behavior**
[https://stackblitz.com/edit/angular-puuh1g-odc9ek](https://stackblitz.com/edit/angular-puuh1g-odc9ek)

Here the package version is 4.4

After adding rows,  The form is Submitted.

On Submit the Model is Reset, and the View is Updated in the Repeat Type.

Kindly Make the Change in Version 4.8 or Suggest a WorkAround.

**Comment by kritisoft** [comment]
Are there any WorkArounds until the fix is Implemented?
My Project Timeline is ending soon :(

**Comment by aitboudad** [comment]
> Are there any WorkArounds until the fix is Implemented?

@kritisoft rollback to `V4.4` or use the `V5` version, I'll try to check this during this weekend.

**Comment by kritisoft** [comment]
V4.4 is giving errors in wrappers. Since I use the form-field wrappers for my custom Fields

**Comment by aitboudad** [comment]
@kritisoft try with `resetModel` which appear to be working:
```ts
this.options.resetModel({...this.model, investments:[]});
```

**Comment by kritisoft** [comment]
Yes , that is working , But my scenario is different , 
Which Gives me Error

See this [https://stackblitz.com/edit/angular-puuh1g-bpgbmu](https://stackblitz.com/edit/angular-puuh1g-bpgbmu)

**Comment by kritisoft** [comment]
Hi @aitboudad  , I could make it work by defining another form .

Dunno, if this is the correct way, https://stackblitz.com/edit/angular-puuh1g-rnmgpt

Just Check and Let me know if any better workarounds are there.

And Thanks for this Awesome Library, Love it.

**Comment by aitboudad** [comment]
there is a similar example to your use-case which was solved in the same way https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section-input
