### ISSUE TITLE
makeAsDirty method required for all fields when custom form.

### ISSUE THREAD

**Issue by AhmedBHameed** [ngx-formly/ngx-formly#1480]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
I'm not sure if this is already implemented or not but let me share it with you which may lead into a new feature to the nice formly module.

I created a custom form and bind it with formly module. Any error message should show up when form submit occurred for the first time (At least in my scenario). When the form is not touched and click on submit no error messages show up.

Note that i'm using `formControl.dirty && formControl.invalid` to show the errors. This will prevent showing error message on the initial of the form but until it get (dirty or touched).

May be we need another type rather than `Dirty` since the last may be used to other validation and making them as dirty will cause another problem somewhere else. But i assume that you get the point when the form is not `touched` and submitted directly.

**Expected behavior**
In my case i was searching for a method to make all fields dirty when submit occurred with not interference from the user.
I solved it in this way:
 ```js
makeFormDirty() {
        Object.keys(this.personalInfoForm.controls).forEach((key: string) => {
            this.personalInfoForm.controls[key].markAsDirty();
        });
    }
```
But since the formly has its own object wrapper, I was expecting to see this method their.

Angular: 5
angular-material: 5.0.0
Formly: 4.8.2
ngx-formly/material: 4.8.2

Browser: Chrome

Language: [TypeScript]

Node (for AoT issues): node --version = 11.6.0

**Comment by aitboudad** [comment]
already handled, to know if the form is submitted we rely on [options.parentForm.submitted](https://github.com/ngx-formly/ngx-formly/blob/v2/src/core/src/services/formly.config.ts#L33) property.
