### ISSUE TITLE
Cascaded select is not working with ngx formly v3.x

### ISSUE THREAD

**Issue by gnana504** [ngx-formly/ngx-formly#1483]
need an example for cascaded select with ng 5.x 

https://stackblitz.com/edit/angular-gnex1x?file=src%2Fapp%2Fapp.component.ts

can we use new version of formly with angular 5.x?

**Comment by aitboudad** [comment]
> can we use new version of formly with angular 5.x?

unfortunately no, it require ng 7.x

here is the v3 example: https://stackblitz.com/edit/angular-vgbgb3

**Comment by gnana504** [comment]
fab..thank you.
@aitboudad 
i would like to get the teams and players from a service and load options.
but the options are not overriding, new result set is appending to the existing.
could you pls help on this?

field.templateOptions.options = serviceCall();

**Comment by aitboudad** [comment]
> but the options are not overriding, new result set is appending to the existing DOM elements.
could you pls help on this?

could you please show me a `stackblitz` example that reproduce that issue

**Comment by gnana504** [comment]
> > but the options are not overriding, new result set is appending to the existing DOM elements.
> > could you pls help on this?
> 
> could you please show me a `stackblitz` example that reproduce that issue

**Comment by gnana504** [comment]
I have resolved it, thanks.
