### ISSUE TITLE
How to listen to the field change event in json schema.

### ISSUE THREAD

**Issue by carlwang87** [ngx-formly/ngx-formly#1484]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```

**Current behavior**

I'm creating the form with the JSON-Powered function, and the json is below:
`[
  {
    "key": "username",
    "type": "input",
    "templateOptions": {
      "label": "username",
      "required": true,
      "change": "(field, event) => {console.log(event)}"
    }
  }]`
The change event does't work. 

**Expected behavior**

I want to listen to the change event with json schema.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =v8.9.4

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1464#issuecomment-471500251
