### ISSUE TITLE
how do i use the repeat section type if i am using json schema for the form config.

### ISSUE THREAD

**Issue by Himanshu-Singhal** [ngx-formly/ngx-formly#1486]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
check the demo example: https://ngx-formly.github.io/ngx-formly/examples/advanced/json-schema
for stackblitz example: https://stackblitz.com/edit/angular-4xmz1x

**Comment by Himanshu-Singhal** [comment]
thanks a lot that worked!!.

One more thing I am trying to assign the enums/options dynamically with the data from a service call how do I do that?.

**Comment by Himanshu-Singhal** [comment]
> check the demo example: https://ngx-formly.github.io/ngx-formly/examples/advanced/json-schema
> for stackblitz example: https://stackblitz.com/edit/angular-4xmz1x

thanks a lot that worked!!.

One more thing I am trying to assign the enums/options dynamically with the data from a service call how do I do that?.
