### ISSUE TITLE
how do I dynamically add enums when using JSON schema for the form config. I am getting the enum/options from a service call in my component. 

### ISSUE THREAD

**Issue by Himanshu-Singhal** [ngx-formly/ngx-formly#1487]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
- using `formly` json: https://ngx-formly.github.io/ngx-formly/examples/other/observable-select
- for `json-schema`: extra options can be passed through `widget` attribute:
```ts
{
  "type": ...,
  "widget": {
    "formlyConfig": {
      "templateOptions": {
        "options": this.dataService.getOptions(),
      }
    }
  }
}
```
