### ISSUE TITLE
Custom radio issue.

### ISSUE THREAD

**Issue by HarshitChhipa** [ngx-formly/ngx-formly#1488]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
It does not behave as it described in the docs.
It breaks when there is multiple radio buttons.

**Expected behavior**
the respective radio should be highlight.
But now only one radio button is shown active in the enitire model.
Let me know if i m doing anything wrong.

**Minimal reproduction of the problem with instructions**
This is the reproduction.
https://stackblitz.com/edit/ngx-formly-custom-radio-zz7zpy

**Comment by aitboudad** [comment]
the issue is about name attribute, try with `id`:
```html
<input type="radio"
  [name]="id"
  ...
/>
```

**Comment by HarshitChhipa** [comment]
Thank You, man.
It worked.
