### ISSUE TITLE
File upload explained in docs is not working.

### ISSUE THREAD

**Issue by HarshitChhipa** [ngx-formly/ngx-formly#1491]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I don't know I might be wrong but i have tested the file upload build in docs and it doesn't give the file object when you upload any file to it.
I have simply console log the model and it does not contain any file object.
What Am i missing to do.

**Expected behavior**
there should be a file object in the model

**Minimal reproduction of the problem with instructions**
open the file upload explained in the docs and upload the file
<!--
If the current behavior is a bug or you can illustrate your feature request better with an example,
please provide the *STEPS TO REPRODUCE* and if possible a *MINIMAL DEMO* of the problem via
https://stackblitz.com or similar.

**Comment by HarshitChhipa** [comment]
Thank You, man.
It worked.

**Comment by HarshitChhipa** [comment]
Any suggestion from your side.
Like any live demo if it is working anywhere.

**Comment by thorgod** [comment]
It works for me. Any errors in the console? What is your browser/PC?

![image](https://user-images.githubusercontent.com/13910170/55096985-2a732e80-5078-11e9-8923-a458f23e2840.png)

**Comment by HarshitChhipa** [comment]
I m using Ubuntu 18.04 ...
Browser Chromium...
Actually, there should be a file object.
And as I can see there is an empty object...
Did you get what I m trying to explain?

**Comment by HarshitChhipa** [comment]
Actually when i m printing the model it gives me this url..
C:\\fakepath\\Harshit.pdf...
It is not making a file object.

**Comment by HarshitChhipa** [comment]
It Worked sorry I was doing some silly mistake.

**Comment by HarshitChhipa** [comment]
It Worked sorry I was doing some silly mistake.

**Comment by HarshitChhipa** [comment]
Hey @thorgod and @aitboudad...
Can you guys please suggest me something.
Is there anything extra we have to do to send the model to the server if the model contains file...
Actually, I m stuck in a scenario where I upload a file using the simple file uploader that I have shared above but it shows file object in the console but when I send the model to the backend it is going empty....neither backend is receiving that file object.
Any leads will be appreciated.

**Comment by aitboudad** [comment]
@HarshitChhipa sending a file to the server is different than a basic post which would require to pass `FormData` (note: there are other ways).
Anyway here is a simple example that transforms the form model into `FormData` instance:

```ts
  onSubmit() {
      const formData: FormData = new FormData();
      formData.append('file', this.model.file);
     ...

      this.http.post('medias', formData);
  }
```

**Comment by HarshitChhipa** [comment]
after appending the file object it is still sending formData empty. Am I missing anything?

**Comment by HarshitChhipa** [comment]
const formData: FormData = new FormData();
        console.log(this.mediamodel.file.File, 'This is file');
        formData.append('file', this.mediamodel.file.File);
        console.log('fychjaskjsduyg', formData, this.mediamodel.file);
        console.log(formData, 'This is Form Data');
        this._service.mediaUpload(1, formData)
            .subscribe(res => {
                console.log('this is uploaded files', res);
            });
    }

**Comment by HarshitChhipa** [comment]
formData.append('file', this.mediamodel.file); <-- Tried this also but same result.

**Comment by aitboudad** [comment]
Without a reproduction we can't help :(, sorry!

**Comment by bejgumshirisha** [comment]
@HarshitChhipa  Did you find any solution for fileupload sending to server/backend.

**Comment by bejgumshirisha** [comment]
@aitboudad  Please find the StackBlitz url for reproduction.

`https://stackblitz.com/edit/angular-formly-fileupload?file=src%2Fapp%2Fapp.component.ts`

When I log the FormData It is not showing anything.

**Comment by HarshitChhipa** [comment]
> @HarshitChhipa Did you find any solution for file upload sending to server/backend.

Indeed,I found a solution.
Need to write the code for it will update you soon.

**Comment by bejgumshirisha** [comment]
> > @HarshitChhipa Did you find any solution for file upload sending to server/backend.
> > @bejgumshirisha
> > Indeed,I found a solution.
> > Need to write the code for it will update you soon.
@HarshitChhipa  Please do share the demo code once it is done. I am unable to finish it up.

**Comment by HarshitChhipa** [comment]
> > > @HarshitChhipa Did you find any solution for file upload sending to server/backend.
> > > @bejgumshirisha
> > > Indeed,I found a solution.
> > > Need to write the code for it will update you soon.
> > > @HarshitChhipa  Please do share the demo code once it is done. I am unable to finish it up. Thanks

Can you provide me a repo I can write code there.
from there you can use this.

**Comment by bejgumshirisha** [comment]
> > > > @HarshitChhipa Did you find any solution for file upload sending to server/backend.
> > > > @bejgumshirisha
> > > > Indeed,I found a solution.
> > > > Need to write the code for it will update you soon.
> > > > @HarshitChhipa  Please do share the demo code once it is done. I am unable to finish it up. Thanks
> 
> Can you provide me a repo I can write code there.
> from there you can use this.

Please find the stackblitz url
https://stackblitz.com/edit/angular-formly-fileupload?file=src%2Fapp%2Ffile-type.component.ts

**Comment by snlaccount** [comment]
@HarshitChhipa @bejgumshirisha  Were you able to read file content and pass it to the backend. 
I am only able to get file info not the file content. Can anybody help me with passing the content of the file as bytes to backend.

**Comment by Siqlain-Hanif** [comment]
https://formly-file-type-multiple-demo.stackblitz.io

**Comment by Siqlain-Hanif** [comment]
https://stackblitz.com/edit/formly-file-type-multiple-demo?file=src/app/app.component.ts

**Comment by sparshbhardwajj** [comment]
I used follow the example from Stackblitz, but not able to select the file and choose file button is not working
https://stackblitz.com/edit/angular-lgq2cy?file=src%2Fapp%2Ffile-type.component.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Findex.html

**Comment by aitboudad** [comment]
@sparshbhardwajj https://formly.dev/examples/other/input-file

**Comment by sparshbhardwajj** [comment]
> @sparshbhardwajj https://formly.dev/examples/other/input-file

I tried that also but still not able to make my choose file button functional.

**Comment by madhumitha13579** [comment]
> Actually when i m printing the model it gives me this url.. C:\fakepath\Harshit.pdf... It is not making a file object.
