### ISSUE TITLE
Is there a color picker for formly?

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1492]
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

Is there a color picker for Formly? If not, any guide on how to go forward and build one?

Thanks

**Comment by thorgod** [comment]
Create a custom template.
Use this guide:
https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field
Use a library like:
https://www.npmjs.com/package/ngx-color-picker 

Here is a stackblitz example of both put together.
https://stackblitz.com/edit/ngx-formly-custom-template-zhho1m?file=app/formly-field-input.ts

Someone might have a better way to bind, this was just my first stab.

**Comment by bhaidar** [comment]
Thanks @thorgod What's a custom template in general? Is it different from custom fields?

**Comment by thorgod** [comment]
Well its just wording, in terms of ngx-formly it just uses the name **custom template** to describe a custom field.  So no its not different from a custom field.

**Comment by aitboudad** [comment]
here is another one for material https://stackblitz.com/angular/xlrjknqxmvr

**Comment by bhaidar** [comment]
> here is another one for material https://stackblitz.com/angular/xlrjknqxmvr

Is there a color picker there? I can only see auto-complete control. Thanks @aitboudad

**Comment by aitboudad** [comment]
Ooh I've missed the save button :cry:, it was the mix of the following packages: 

- https://scttcper.github.io/ngx-color/
- https://github.com/ncstate-sat/popover
- material input

I'll try to re-create another later.

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-arsdhq
