### ISSUE TITLE
Allow css attributes in the FormlyFieldConfig

### ISSUE THREAD

**Issue by twmobius** [ngx-formly/ngx-formly#1494]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

Great job guys, I've looked into all the similar solutions for angular and it looks that ngx-formly is the most actively maintained.

Currently to the best of my knowledge, one can pass a className to the `FormlyFieldConfig` but there is no way to explicitly specify css attributes.  So I would like to propose adding a new attribute on the FormlyFieldConfig to allow for css attributes to be applied on the components.

Apart from the field in the config, this would require an update on the components to add the `[style]=to.cssStyle` to the component.

Also really looking forward with the integration of the `UISchema`  :)

**Comment by aitboudad** [comment]
> Apart from the field in the config, this would require an update on the components to add the [style]=to.cssStyle to the component.

the implementation doesn't require a lot of work all we have to do is to add `style` into [FormlyField](https://github.com/ngx-formly/ngx-formly/blob/master/src/core/src/lib/components/formly.field.ts#L18)

> Also really looking forward with the integration of the `UISchema` :)

extra options can be passed through `widget` attribute which allows you to pass formlyConfig:

```ts
{
  "type": ...,
  "widget": {
    "formlyConfig": {
      "templateOptions": {
        "options": this.dataService.getOptions(),
      }
    }
  }
}
```

**Comment by twmobius** [comment]
> the implementation doesn't require a lot of work all we have to do is to add `style` into [FormlyField](https://github.com/ngx-formly/ngx-formly/blob/master/src/core/src/lib/components/formly.field.ts#L18)

Ah, that's even better, I guess I could try and craft something up

> extra options can be passed through `widget` attribute which allows you to pass formlyConfig:
> 
> ```ts
> {
>   "type": ...,
>   "widget": {
>     "formlyConfig": {
>       "templateOptions": {
>         "options": this.dataService.getOptions(),
>       }
>     }
>   }
> }
> ```

Yes I've seen it, thanks, this is probably what I'm going to use for now. I've been looking into the code in `FormlyJsonschema` to try and hack something up because:

a) I've been using UISchema myself mostly as an extra JSON to add custom properties to the form and 
b) I need to add `$ref` to the object type

To my knowledge `widget` attribute is not a valid json-schema attribute and I guess that's the reason the https://mozilla-services.github.io/react-jsonschema-form/ uses it as well

**Comment by aitboudad** [comment]
> I've been using UISchema myself mostly as an extra JSON to add custom properties to the form and
I need to add $ref to the object type

`$ref` isn't supported yet, expect more features in the next major version (#1365, #1459)

**Comment by twmobius** [comment]
Ok with regards to the css, 

I initially though that exposing a new configuration attribute to the `FormlyFieldConfig` and passing it to an `[ngStyle]` would do the trick. However due to the way the `FormlyField` and the `FormlyGroupField` are being defined, I cannot use `ngStyle` via the `host: {}` property of the `@Component({})`.

So to my knowledge (and I am no angular guru) we should resort to `[style]` directive in the `host` attributes and instead of a javascript object, pass a simple string containing the css attributes. However this in turn should be sanitized for it to work.

Something along the following lines:

```
...

import { DomSanitizer } from '@angular/platform-browser';

@Component({
  selector: 'formly-field',
  template: `<ng-template #container></ng-template>`,
  host: {
    '[style.display]': 'field.hide ? "none":""',
    '[style]': 'field.style? this.sanitizer.bypassSecurityTrustStyle(field.style) : this.sanitizer.bypassSecurityTrustStyle(style)',
    '[class]': 'field.className? field.className : className',
  },
})
export class FormlyField implements OnInit, OnChanges, DoCheck, AfterContentInit, AfterContentChecked, AfterViewInit, AfterViewChecked, OnDestroy {
  ...

  @Input('style') style: string = '';

  ...

  constructor(
    private formlyConfig: FormlyConfig,
    private componentFactoryResolver: ComponentFactoryResolver,
    private injector: Injector,
    private sanitizer: DomSanitizer,
    // tslint:disable-next-line
    @Attribute('hide-deprecation') hideDeprecation,
  ) {
    this.warnDeprecation = hideDeprecation === null;
  }
}
```

If you feel this is the way to go, let me know and I'll send you a PR

**Comment by aitboudad** [comment]
not sure if that way is performant either use cached sanitized value or init style during build process, anyway just send a PR and I'll check it.

**Comment by aitboudad** [comment]
not sure what's your use-case here but for info if you want to apply a style to the `input` of the field type you can use the following option which is already implemented:
```ts
templateOptions: {
  attributes: {
    style: "background: green; border-color: green;"
  }
}
```

**Comment by twmobius** [comment]
Oh ok I've missed that. :) So I guess there is no such need for a style explicit configuration option. 

In any case since I had roughly crafted it I am sending you a PR just to see it.

**Comment by aitboudad** [comment]
ok then I would prefer to wait until working on `V6` then I'll re-check your PR

**Comment by VladBozhinovski** [comment]
> not sure what's your use-case here but for info if you want to apply a style to the `input` of the field type you can use the following option which is already implemented:
> 
> ```ts
> templateOptions: {
>   attributes: {
>     style: "background: green; border-color: green;"
>   }
> }
> ```

When I apply this attribute style with background color it works on the formly-field. But how to apply width for the child element (mat-form-field) ?

**Comment by aitboudad** [comment]
@VladBozhinovski add `className` which will be added to the `formly-field` component and then target the child element using `css`:
```ts
{
  className: 'my-custom-style',
  key: 'name',
  ...
}
```

`style.scss`:

```scss
.my-custom-style .mat-form-field {
}
```

**Comment by VladBozhinovski** [comment]
Thanks, that helped me a lot

**Comment by Fatman452** [comment]
> ```css-scss
> .my-custom-style .mat-form-field {
> }
> ```

This do not work for me.

**Comment by aitboudad** [comment]
@Fatman452 then please provide a reproduction in order to see what you've missed.

**Comment by Fatman452** [comment]
Sorry, then I fixed it, sorry I forgot to comment

**Comment by aitboudad** [comment]
@Maciler use the following solution instead https://github.com/ngx-formly/ngx-formly/issues/1494#issuecomment-551655615

**Comment by webia1** [comment]
I had to overwrite and use `!important` in a global style sheet before (I use Material-UI), like:

```css
.mat-mdc-form-field {
  width: clamp(12.5rem, 100%, 30rem) !important;
}
```

because that's the whole structure 

```css
form 
  formly-form .my-formly-form-xy
    formly-field 
      formly-group
        formly-field .my-formly-form-field-className
          formly-wrapper-mat-form-field
            mat-form-field 
```

and the `mat-form-field` has 5 more classes:

```css
 mat-form-field 
  .mat-mdc-form-field  
  .mat-mdc-form-field-type-mat-input 
  .mat-form-field-appearance-fill 
  .mat-primary 
  .mat-form-field-hide-placeholder 
```
and the first one of them `.mat-mdc-form-field ` sets the width to 100%, which I had to overwrite.

Therefore the approach did not work for me:

```css
.my-custom-style .mat-form-field {
}
```

If there is a better way to achieve the same, I would be very thankful, until then, this is my workaround. 

fyi kind rgds
