### ISSUE TITLE
How to setup a Stepper/Tab field type

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1496]
```
[x] support request
```

https://stackblitz.com/edit/angular-yu7bzv?file=src%2Fapp%2Fapp.component.html

I transformed the Stepper example into a Stepper field type. However I have problems to get validation correct for the outer form.

The Stepper field type uses a `FormArray` with for each step a `formly-form` with a `FormGroup` (needed to have validation on the single steps).
The Stepper field type's `FormArray` is independent and not hooked up with a parent.

Changing the Stepper field type from `FieldType` to `FieldArrayType` (has a `FormArray`) is maybe only half way correct, we have an array (fieldGroups), but the model is a non-array. Also there is no `fieldArray`. Using add() to add the steps (Controls) might have some side-effects.

What modification on the field type is needed ?

**Comment by aitboudad** [comment]
using `formly-form` inside a field type is not necessary, just keep it simple and add a simple method to check the step validation here is a working example:

https://stackblitz.com/edit/angular-yu7bzv-hs1zg6

**Comment by FritzHerbers** [comment]
@aitboudad 
Thx a lot.

Can you please explain the difference between field.formControl and field.form.

Just noticed something which could be a bug, when adding a key to the stepper field configuration.
https://stackblitz.com/edit/angular-yu7bzv-ff255j?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
> Can you please explain the difference between field.formControl and field.form.

`formControl` is equal to `form` if the field has not key else `form` is the parent of `formControl`.

> Just noticed something which could be a bug, when adding a key to the stepper field configuration.

maybe a bug, I'll re-chech it.

**Comment by aitboudad** [comment]
`defaultValue` value is missing, pass it through the `defaultOptions`:
```ts
export class FormlyFieldStepper extends FieldType {
  defaultOptions = {
    defaultValue: {},
  };
};
```

**Comment by FritzHerbers** [comment]
@aitboudad 
Always thankful for your help.

Tried to add [stepControl] for which I need a form
https://stackblitz.com/edit/angular-yu7bzv-n1fwkc?file=src/app/stepper.type.ts

For the button next, we needed to go to the controls within the step Formgroup to look for their validity.
But for stepControl a AbstractControl is needed, which we don't have, with only the controls within this FormGroup.

FieldGroup != FormGroup ?
If I look into field.formControl or each steps field.formControl they all contain the 4 controls. For the fist step I would expect only firstname and age and let the Formgroup calculate the status values of its children. Only when each step has a key, formly behaves like I expect.

Adding keys means additional model handling.

Is this maybe a "flaw" in formly implementation (this is not disrespectal meant) ?
What is your opinion?

**Comment by aitboudad** [comment]
to my knowledge you can control the flow without `stepControl` else you may have to create a virtual FormGroup by grouping fields of each step, here is a quick attempt which you may need to complete (doesn't handle nested `fieldGroup`) https://stackblitz.com/edit/angular-yu7bzv-jrxppa

> For the button next, we needed to go to the controls within the step Formgroup to look for their validity.
But for stepControl a AbstractControl is needed, which we don't have, with only the controls within this FormGroup.

FormGroup is an instance of `AbstractControl`

**Comment by FritzHerbers** [comment]
> to my knowledge you can control the flow without `stepControl` 
To jump to a next step programmatically does not work, pressing the header always moves. A fix is long outstanding (not only with this issue, also in other material issues, not much progression is made). I made a fix:
https://github.com/angular/material2/issues/9733#issuecomment-423956599

The stepControl is an additional guard.

>else you may have to create a virtual FormGroup by grouping fields of each step, here is a quick attempt which you may need to complete (doesn't handle nested `fieldGroup`) https://stackblitz.com/edit/angular-yu7bzv-jrxppa

Thanks for the idea. For dynamically loading stepper fieldGroups will need some adaptions.
 
>doesn't handle nested `fieldGroup`
That's why I asked you for an opinion about what I think is a flaw. Please correct when I am wrong, but formly creates only a new FormGroup when a key exists for a fieldGroup.

https://stackblitz.com/edit/angular-yu7bzv-ugrm91?file=src/app/app.component.ts
As there is no key for the stepper and for the stepper steps, the control 'sometext' is contained in the stepper (and steps) formControl.controls.

When formly would use a FormGroup for each fieldGroup (independent if it has a key) the validity checking would work automatically and the use of FormGroup formControl (and FormControl, FormArray) would be straight forward.

Is there something which speaks against how I think it should be implemented, that it is implemented the way it is ?

**Comment by aitboudad** [comment]
> To jump to a next step programmatically does not work, pressing the header always moves. A fix is long outstanding (not only with this issue, also in other material issues, not much progression is made). I made a fix:

here is another easy workaround until material issue get fixed, https://stackblitz.com/edit/angular-yu7bzv-n1fwkc

> Is there something which speaks against how I think it should be implemented, that it is implemented the way it is ?

right now we rely on reactive-forms which currently doesn't support a such feature (nested group require key).

**Comment by aitboudad** [comment]
**note**: the example adjusted https://stackblitz.com/edit/angular-yu7bzv-bcmfip

**Comment by akhaderachana** [comment]
We are facing an issue with accessibility using screen reader and the same issue is in this example. When using a screen reader (NVDA, JAWS), it reads alternate fields. 

In the above example, when there are more than 2 fields (I added one more input field), screen reader will read the first field, then third field and then the second one.
This is when the screen reader is reading the entire page (not while tabbing into the fields).

Any help is appreciated.

**Comment by anushreenk** [comment]
Hi Team,
I need to listen to the event wehen user click on next or previous button , how can I achive the same please help
