### ISSUE TITLE
Wrap a component inside a Formly Field

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1497]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
I have a Component with defined Input/Output. I would like to wrap it inside Formly to be able to use it as a field on the form.

My first thought is to change the Component to implement `ControlValueAccessor` then create a custom FieldType to embed the CVA and finally bind `[formControl]="formControl"` and `[formlyAttributes]="field"` on the CVA.

Sounds good?

The other way around, is to create a custom field type, embed the component as is, and set manually the value on the formControl when the output is fired on the component.

Any preference?

Thanks

**Comment by thorgod** [comment]
CVA?

**Comment by thorgod** [comment]
Make an attempt on stackblitz, then I could try and fill in the rest.

**Comment by bhaidar** [comment]
@thorgod Something like this:
https://stackblitz.com/edit/ngx-formly-component-as-template

Thanks

**Comment by thorgod** [comment]
I am unsure what your question is? What are you trying to accomplish?

**Comment by thorgod** [comment]
Sounds like you want a wrapper but unsure what you are creating.

**Comment by bhaidar** [comment]
@thorgod Yes, I did create a wrapper. I am trying to wrap a normal component inside Formly. As you see, I handle the selection change event and update formControl accordingly.

**Comment by thorgod** [comment]
So what is your question then?

**Comment by bhaidar** [comment]
What do you think of this approach? Are there better options? Thanks

**Comment by thorgod** [comment]
Its such a simple example, I would not make it overly complex by placing it in a separate component, I would just make one custom field. But I don't see the overall picture of what you goal is so hard to say what is the best practice.

**Comment by bhaidar** [comment]
@thorgod That's just a simple example to demonstrate the idea.
I have a component with input and output already existing in the application. It's sort of a component that wraps Mat-Tree to allow the user to select nodes on a tree.

Now, we need to use this tree selector inside a form.

That's why I thought of wrapping it this way in formly so that I can use it as a normal field.

**Comment by aitboudad** [comment]
use the easy way (keep it simple), if the component is reusable somewhere then it makes sense else you may avoid an extra component.

I would use `ControlValueAccessor` if it would reduce the complexity of implementation or if you need it in a project that doesn't require `formly`.

**Comment by bhaidar** [comment]
Thanks @aitboudad. For now it seems to be working smooth using the current implementation and setting formControl manually. At the same time, the same component is being used somewhere else in the app, so we are fine till now!

I had this option in mind to make the component ControlValueAccessor, I will keep it an option in case I need it in the future.

Thanks
