### ISSUE TITLE
modelChange event not triggering when a property change inside nested object.

### ISSUE THREAD

**Issue by joharzmn** [ngx-formly/ngx-formly#1503]
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have form model like this.
```javascript
{
  "formGroupKey": {
    "field1Key": {
      "data": [
        {
          "prop1": 1,
          "prop2": 1,
          "Description": "",
          "children": [
            {
              "Percentage": "1"              
            }   
           ]
        }  
      ]
    },
    field2Key: 'value'  
  }
}
```

When i change something in field2Key it detected by modelChange event but if i change `"Percentage": "1" ` property which is nested in field1Key then modelChange not triggering.

**Note:** 
> I have bind the data property of prop1Key with grid data so when something change inside the grid it changes the percentage property. Model is changing in console but modelChange event is not triggering.

**Expected behavior**

modelChange() event should detect change in nested object for field.

* **Angular version:** 6.x

* **Language:** TypeScript 3.X

**Comment by aitboudad** [comment]
which version of `formly` you're using?

**Comment by joharzmn** [comment]
I am using 4.8.3 because v5 is not supported in angular 6.

**Comment by aitboudad** [comment]
I couldn't reproduce it, here is a working example https://stackblitz.com/edit/angular-bjmz49, 
could you please update the `stackblitz` example to reproduces your issue.

**Comment by joharzmn** [comment]
Here is the [link](https://stackblitz.com/edit/angular-bjmz49-1dreqh) to `StackBiltz`
The styling of grid is not as expected but i have reproduced the problem. When you click on any column of a row and edit the value. You will see the model will change but modelChange() event will not trigger.

**Comment by aitboudad** [comment]
you didn't notify formly for the new changed value, add an output `dataChange` form example and pass the new value to the formly formControl. here is a starting example https://stackblitz.com/edit/angular-bjmz49-wwvasy

**Comment by joharzmn** [comment]
Oh! Thank you for the help.

**Comment by joharzmn** [comment]
@aitboudad Hey I noticed that when we emit dataChange it's changing the structure of the model. Can you  tell me why it's changing the structure it should only update the changed value right?
https://stackblitz.com/edit/angular-bjmz49-wwvasy

**Comment by joharzmn** [comment]
@aitboudad 
Hey in formly 5.0.0 does it detect the changes automatically without emitting from the custom component?

**Comment by aitboudad** [comment]
@joharzmn nop, it detects the changes automatically for libs that implement `ControlValueAccessor` ( support angular reactive-forms)

**Comment by joharzmn** [comment]
Okay Thanks
