### ISSUE TITLE
ERROR TypeError: Cannot read property '_checkField' of undefined

### ISSUE THREAD

**Issue by LalitKushwah** [ngx-formly/ngx-formly#1505]
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
Hello All,

I am trying to wrap ngx-formly in an angular element. I have done that successfully but when I plugging into a plain html file and trying to provide [field] or [formGroup] via input property of my element then facing following error:

custom-button-element.js:4 ERROR TypeError: Cannot read property '_checkField' of undefined
    at jc.checkExpressionChange (custom-button-element.js:4)
    at jc.ngDoCheck (custom-button-element.js:4)
    at custom-button-element.js:4
    at custom-button-element.js:4
    at li (custom-button-element.js:4)
    at Ai (custom-button-element.js:4)
    at Object.updateDirectives (custom-button-element.js:4)
    at Object.updateDirectives (custom-button-element.js:4)
    at ii (custom-button-element.js:4)
    at pi (custom-button-element.js:4)

Here is the project that you can regenerate:
https://github.com/LalitKushwah/wrapper-formly

Target File:
test.html at the root location

**Comment by LalitKushwah** [comment]
Now I am getting 
<html>
<head>

<script src="http://127.0.0.1:5500/custom-button-element.js"></script>
</head>
<body>
<app-formly-wrapper-component name="text" input="[
    {
      fieldGroup: [
        {
          key: 'grid-title-url',
          type: 'input',
          templateOptions: {
            label: 'Grid Title URL',
            description: 'Link to destination for title text in header'
          }
        }
      ]
    }
  ]"></app-formly-wrapper-component>
<app-button name="It Worked!!"></app-button>
</body>
</html>

**Comment by aitboudad** [comment]
what you've done there is passing a string value to the formly fields (see https://github.com/angular/angular/issues/24415#issuecomment-396225443)

try with  the following code:
```patch
// formly-wrapper-component.component.html
-- <formly-form [model]="order" [fields]="input">
++ <formly-form *ngIf="input" [model]="order" [fields]="input">
```

```html
<app-formly-wrapper-component name="text"></app-formly-wrapper-component>
<script>
  document.querySelector('app-formly-wrapper-component').input = [
    {
      fieldGroup: [
        {
          key: 'grid-title-url',
          type: 'input',
          templateOptions: {
            label: 'Grid Title URL',
            description: 'Link to destination for title text in header'
          }
        }
      ]
    }
  ];
</script>
```
