### ISSUE TITLE
Repeat does not work with hideExpression.

### ISSUE THREAD

**Issue by HarshitChhipa** [ngx-formly/ngx-formly#1508]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have made a slackblitz and according to the selection of radio button, it should hide the fields created by repeat.
But I don't know why it initialized as undefined neither it works as expected. 

**Expected behavior**
According to the selection of the radio button, it should hide the field created by select but that's not happening clearly.

**Minimal reproduction of the problem with instructions**
Here is the Stackblitz that i have made to show the issue.
https://stackblitz.com/edit/angular-repeat-select-bhsazi?file=src/app/app.component.ts

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X+

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
the first argument `model` that represents the root model but the scoped one, if you want the root model use `this.model` or rely on `formState` for more info see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

**Comment by HarshitChhipa** [comment]
I have already read that comment.
And Tried Implementing it but it is not working.
Can you help me solve it?
Or any suggestion.

**Comment by HarshitChhipa** [comment]
https://stackblitz.com/edit/angular-repeat-select-uyxpu6?file=src/app/app.component.ts
I have tried it here.
But after creating repeats it does not hide them if we select radio.

**Comment by aitboudad** [comment]
seems there is an issue, I'll try figure out what going wrong when I have time.

**Comment by HarshitChhipa** [comment]
No Problem man...
Just if you get time to see what's going wrong just let me know.
I too am figuring it out what's going wrong if I got the solution I will let you know.
Thanx a lot for helping.

**Comment by aitboudad** [comment]
add `distinctUntilChanged` to `investmentsCount`, here is a working example: 
https://stackblitz.com/edit/angular-repeat-select-oyv77i

**Comment by HarshitChhipa** [comment]
Cool Man, it worked.
Thnx a lot for help.
And btw ngx-formly is awesome I m having fun using it.
