### ISSUE TITLE
Polymorph for Ver 5

### ISSUE THREAD

**Issue by thorgod** [ngx-formly/ngx-formly#1512]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```
**ngx-formly/core/5.0.1**
**Current behavior**
Currently Poloymorph on Ver 3.3 worked good. But using polymorph on ver 5 leaving the form or switching types causes problems. Infinite loop. 

- Ver 5.0.1 https://stackblitz.com/edit/angular-jqswqz?file=src/app/app.component.ts
- Ver 3.3 https://stackblitz.com/edit/angular-2tdkxm-gr5dgk
- Ver 3.3 Original Issue fixed for  https://github.com/ngx-formly/ngx-formly/issues/925

**Expected behavior**
Switch between types to cause the problem. 
ngx-formly/core/5.0.1
https://stackblitz.com/edit/angular-jqswqz?file=src/app/app.component.ts

**What is the motivation / use case for changing the behavior?**
Have polymorph work

Can you help me upgrade polymorph custom field type so it works on 5.0.1

**Comment by aitboudad** [comment]
I think it should work, I'll try to find what caused the issue tomorrow

**Comment by aitboudad** [comment]
seems already solved see my comment https://github.com/ngx-formly/ngx-formly/issues/1091#issuecomment-466511867

**Comment by thorgod** [comment]
I remembered reading your comment sometime ago, thinking I should go try it but couldn't find it. 

Thanks for the help, it works now.
