### ISSUE TITLE
Icons support / Tooltip

### ISSUE THREAD

**Issue by demiro** [ngx-formly/ngx-formly#1513]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request
```

Would be nice to add icon property obj to add it to the input...
left, right or inside orientation
icon name (or class name)

The same for the tooltip (Like the question mark next to the label that would show the description).

**Comment by mohammedzamakhan** [comment]
Like this https://ngx-formly.github.io/ngx-formly/examples/bootstrap-specific/input-add-ons

**Comment by demiro** [comment]
> Like this https://ngx-formly.github.io/ngx-formly/examples/bootstrap-specific/input-add-ons

yeah, exactly like that... wish it would be documented to know how to use it

**Comment by thorgod** [comment]
Looking at the source code is not sufficient? What is your question?
![image](https://user-images.githubusercontent.com/13910170/55642822-69933500-5786-11e9-9b07-5ac2b6134c64.png)

**Comment by aitboudad** [comment]
The above example uses a custom wrapper which is documented in https://ngx-formly.github.io/ngx-formly/guide/custom-formly-wrapper
in addition to that, it uses a custom extension (not documented yet) to apply the addon globally without explicitly setting it throughout the field config.

By checking the source code which I strongly suggest you may create your own implementation that relies on your UI.

If you're using material UI you may check the following example https://ngx-formly.github.io/ngx-formly/examples/other/material-prefix-suffix

**Comment by demiro** [comment]
> Looking at the source code is not sufficient? What is your question?
> ![image](https://user-images.githubusercontent.com/13910170/55642822-69933500-5786-11e9-9b07-5ac2b6134c64.png)

what do you mean? You serious?

examples just say: that for addonLeft/Right you can specify class or text property.... I would want the API for that in docs, not that I have to check every single example to see what other options are possible or check the source code... I was checking formly out in hope it would solve my issues (generating forms) quickly.... and not to take more time than doing it myself (tailored to my needs)

the things I noticed so far:
- the * in required fields are there, cannot find the way to remove it without the docs... I am sure there is an option, just couldn't find it fast enough
- I cannot add an icon with question mark to the right of the input box with a popover or tooltip since addonRight allows me only text/css (from the examples)
- bootstrap caters to more addonsLeft/Right, from the examples could see option for only one

I think the examples are great, I personally learn 5x more like this than a good API documentation, but the API is needed to see all the available options

**Comment by aitboudad** [comment]
> the * in required fields are there, cannot find the way to remove it without the docs... I am sure there is an option, just couldn't find it fast enough

`hideRequiredMarker` is what you're looking for https://github.com/ngx-formly/ngx-formly/blob/master/src/bootstrap/src/lib/wrappers/form-field.wrapper.ts#L10

> I cannot add an icon with question mark to the right of the input box with a popover or tooltip since addonRight allows me only text/css (from the examples)

you've to create you own addon, here is the source code of bootstrap addon https://github.com/ngx-formly/ngx-formly/tree/master/src/bootstrap/addons/src

Checking the source code is the only way to clearly understood the power of `formly` with all features.

Working on proper documentation is definitely on my todo :smiley: but not anytime soon (I've to get rid of my own issues first :sob:) we offer a great support and a stable lib with a set of examples that cover the majority of use-cases. My plan is to find a way to fund my work on `formly` so I can have more time to focus on things that matter but it's not that easy.

Sorry about that :pray:
