### ISSUE TITLE
ngx-formly website header is not being displayed properly on Safari 12.0.1

### ISSUE THREAD

**Issue by juarezpaf** [ngx-formly/ngx-formly#1518]
Such an amazing project y'all. Will start to dive into `ngx-formly` soon for an upcoming project.
Just wanted to let you know I found this issue while browsing https://ngx-formly.github.io/ngx-formly/ using Safari 12.0.1

Keep rocking! ⚡️
<img width="1392" alt="Screenshot 2019-04-08 21 36 49" src="https://user-images.githubusercontent.com/21221/55755426-dc323800-5a46-11e9-8b90-a4e0301668a0.png">

**Comment by aitboudad** [comment]
seems related to [Material toolbar](https://github.com/angular/material2/issues/9403)

**Comment by aitboudad** [comment]
it should be fixed now, thanks!

**Comment by juristr** [comment]
@juarezpaf hey man, good to see you here at the ngx-formly project 😉
