### ISSUE TITLE
Patch dynamic data to repeat type

### ISSUE THREAD

**Issue by Melechoris** [ngx-formly/ngx-formly#1522]
**I'm submitting a ...**

[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request

**What is the motivation / use case for changing the behavior?**
Hi! My goal is to patch external json data to a form which contains a FieldArrayType.

The problem is that at the initial load of the form, only one item is present in the repeat section. Therefore, if I patch data to the form which contains two or more items of the field array, only the first item is applied and stored in the model.

Is there a way to programmatically add items to the FieldArray before patching the data so the data is received by the model?

**Note:** The length of the data can vary. So unfortunately solutions mentioned in https://github.com/ngx-formly/ngx-formly/issues/1139 are not sufficient.

**Minimal reproduction of the problem with instructions**
Please see the following stackblitz:
https://stackblitz.com/edit/angular-vfykhx

Thanks!

**Comment by aitboudad** [comment]
Either use `options.resetModel` or assign the new value to the `model` itself:

```ts
    this.model = {
      ...this.model,
      cars: [
        {"type":"Type1","name":"Name1"},
        {"type":"Type2","name":"Name2"},
      ]
    };
```

see https://stackblitz.com/edit/angular-vaq4gq
