### ISSUE TITLE
Repeating section - custom field with async validator as directive

### ISSUE THREAD

**Issue by aportolan** [ngx-formly/ngx-formly#1523]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
If async validator directive is applied to the custom field type, which is part of the repeating section, validation works only for the field in the last repeating section. It seems that only on newly created fields can the validation be invoked.

**Expected behavior**
Validation should be invoked on every field in repeating section array

**Minimal reproduction of the problem with instructions**
Stackblitz contains modified code of repeating section example from the docs:
https://stackblitz.com/edit/angular-nnokca?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
seems you've to wrap repeat field by `formGroup` directive first in order to work, not sure why :thinking:,
anyway here is  a working example: https://stackblitz.com/edit/angular-nnokca-rmpav3

```ts

@Component({
  selector: 'formly-repeat-section',
  template: `
    <ng-container [formGroup]="field.formControl">
      ...
    </ng-container>
  `,
})
...
```

**Comment by gadreash** [comment]
This helped me with a similar issue as well. I have a ng-select custom type, within a repeating section, which wasn't rendering.
@aitboudad <ng-container> solution worked. Thanks!
