### ISSUE TITLE
Pass parameters into a wrapper.

### ISSUE THREAD

**Issue by uxohotteixo** [ngx-formly/ngx-formly#1526]
I want to make a wrapper for input with a picture. Url pictures I want to insert dynamically.

**Comment by aitboudad** [comment]
similar to the field type, you can pass the extra parameters throughout `templateOptions`:

- field config:

```ts
fields = [{
  key: 'photo',
  templateOptions: {
    url: '...',
  }
}]
```
- wrapper: 
```html
<img [src]="to.url"  />
...
```
  where `to` is an alias of `field.templateOptions`
