### ISSUE TITLE
Disabled not propagated to added FieldArrayType rows

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1528]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
templateOptions.disabled works for the rows with an existing model. Adding new rows however do not get this `disabled` propagated.

**Expected behavior**
On changes of the model or FormlyFieldConfig `disabled` should be propagated (again).

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-yg1gif-96ytzh?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
Seems strange but that's how `angular` manage `disable` status between parent and child control, we've changed that behavior when using `disabled` in expression.

**Comment by aitboudad** [comment]
fixed in `5.0.3`

**Comment by FritzHerbers** [comment]
@aitboudad 
Using 5.0.3
Setting disabled on a child only, incorrectly sets disabled to following siblings of this child.
https://stackblitz.com/edit/angular-yg1gif-of3byq?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
The fix would require some time, so I'm going to revert my previous commit for now.
If you want consistent behavior, I'd suggest using `expressionProperties` for such use-case.

**Comment by saisumughis** [comment]
@aitboudad My use case: if the checkbox is checked, the fields inside fieldArrayType should be enabled and vice-versa. Any workaround for this? 

https://stackblitz.com/edit/angular-csjtor

**Comment by aitboudad** [comment]
@saisumughis see https://github.com/ngx-formly/ngx-formly/issues/1589#issuecomment-493406314

**Comment by saisumughis** [comment]
@aitboudad Thanks, it worked!

**Comment by saisumughis** [comment]
@aitboudad Here's my slackblitz, disabled does not get propogated to multicheckbox. Am I missing anything here?

https://stackblitz.com/edit/angular-bshgv7-hmlqba

**Comment by aitboudad** [comment]
@saisumughis the provided example use an old version of formly which doesn't include the latest fixes, just ensure that you're using the latest version `5.1.7` and it should work!

**Comment by saisumughis** [comment]
@aitboudad Thanks for the quick response. 5.1.4 wasn't working, but 5.1.7 worked!

**Comment by aitboudad** [comment]
close in favor of #1743
