### ISSUE TITLE
Tab key functionality from Enter key

### ISSUE THREAD

**Issue by rizwanspeaks** [ngx-formly/ngx-formly#1531]
In formly-form, 'Tab' and 'Shift + Tab' function is working fine... I need a similar functionality with 'Enter' key instead of 'Tab'.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
In formly-form, 'Tab' and 'Shift + Tab' function is working fine... 

**Expected behavior**
I need a 'Tab' functionality with 'Enter' key in formly-form.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
you may use `keydown` event for example to control the desired behavior:

```ts
    {
      key: 'text',
      type: 'input',
      templateOptions: {
        keydown: (field, event) => {
          // ...
        }
      },
    },
```

**Comment by rizwanspeaks** [comment]
I want to do the following scenario in my application. when user press the enter key it will act as tab key.

**Comment by Darya-Balvanovich** [comment]
@rizwanspeaks Could you please explain how did you implement this solution? I have the same issue and need navigate with enter button.
Thanks in advance!

**Comment by Darya-Balvanovich** [comment]
@aitboudad , hello!
Could you please help with this challenge?
If I use `keydown` I can find current `field` but how can I indicate the next one?

**Comment by Darya-Balvanovich** [comment]
@aitboudad 
also with hardcode doesn't work

<img width="509" alt="image" src="https://github.com/ngx-formly/ngx-formly/assets/73887360/e544f007-5f3c-49a1-ac0f-4130980383d1">
