### ISSUE TITLE
cascaded multicheckbox using formlyBootstrap and data from backend

### ISSUE THREAD

**Issue by boufenzi** [ngx-formly/ngx-formly#1536]
Hello everybody, 
I'm using angular formly with spring data rest to get data from backend.
I have a little bit of trouble to find out how can i populate data from backend in a multicheckbox after checking another one.

In my first multichebox named modules i'm getting my data so everything is good but with my second multicheckbox who is using data ID from the first one, nothing populate after i click on my first checkbox  from the first multicheckbox and i think the second requete doesn't run thats why. 
A help will be great. thank you in advance guys.
```
 fields: FormlyFieldConfig[] = [
    {
      key: 'modules',
      type: 'multicheckbox',
      templateOptions: {
        label: 'Modules',
        options:  this.typeRequete.getData('modules?projection=ModulesForBaliseSelect&sort=moduleName, ASC').pipe(map(data => {
  return data['content'];
}
)),  valueProp: 'id',
        labelProp: 'moduleName',
      },
    },
    {
      key: 'roles',
      type: 'multicheckbox',
      templateOptions: {
        label: 'Roles',
        options: [],
      },
      expressionProperties: {
        'templateOptions.options': this.typeRequete.getData('modules/model.modules/roles?projection=RolesFromModuleIdForBalise').pipe(map(data => {
        return data['content'];
        })),
       },
    },

  ];
```
How can also get the id from the checked checkbox from my first multicheckbox?  is it correct that i'm using model.modules to get it ? 
I don't know what i am missing here.

**Comment by aitboudad** [comment]
check the demo example https://ngx-formly.github.io/ngx-formly/examples/other/cascaded-select which show exactly your scenario by updating options whenever the first one changes

**Comment by boufenzi** [comment]
i already tried it but i think there is a problem with the version i'm using (@ngx-formly/core@4.8.2 ) because in my example  i followed the same example but i always get the error 
![image](https://user-images.githubusercontent.com/32847718/56354619-272d1780-61cc-11e9-9801-9ccca83c8f28.png)

**Comment by aitboudad** [comment]
just added the demo for `V4` version which you may check https://ngx-formly.github.io/ngx-formly/v4/examples/other/cascaded-select

**Comment by boufenzi** [comment]
i tried to follow the example and change it so i can get what i'm looking for. but my main issue is that i don't know how to get the value of the checked one. 

```
 fields: FormlyFieldConfig[] = [
    {
      key: 'sport',
      type: 'multicheckbox',
      templateOptions: {
        label: 'Sport',
        options: [
          { id: '1', name: 'Soccer' },
          { id: '2', name: 'Basketball' },
        ],
        valueProp: 'id',
        labelProp: 'name',
      },
    },
    {
      key: 'team',
      type: 'multicheckbox',
      templateOptions: {
        label: 'Team',
        options: [],
        valueProp: 'id',
        labelProp: 'roleName',
      },
      hooks: {
        onInit: (field) => {
          const form = field.parent.formControl;
          form.get('sport').valueChanges.pipe(
            takeUntil(this.onDestroy$),
            startWith(form.get('sport').value),
            tap(sportId => {
              if(sportId) {
                console.log(sportId);
                field.templateOptions.options =  this.typeRequete.getData('modules/' + sportId+ '/roles?projection=RolesFromModuleIdForBalise').pipe(map(data => {
                  return data['content'];
                }))
              }
            }),
          ).subscribe();
        },
      },
    },
    ];
```

when i checked on my multicheckbox i get the value like this {1:true}  which is an object. i tried to get only the value 1 by using sportId.key, sportId.id, sportId.value and sportId[0] but it's not working. 
how can i get the sportId to only get me the value of the checked one not an object of the values (1 in my example).
Also  if i checked on the first one and checked on the second one after i get the object like this {1: false, 2: true }. 
Is there a way to only get the value 1 or 2 as a response ? 

Thank you for your help

**Comment by aitboudad** [comment]
Pass type `array` throughout `templateOptions`, and you'll get an array of the selected items instead.
```ts
templateOptions: {
  type: 'array',
  ...
},
```

**Comment by boufenzi** [comment]
didn't know about this parameter, thank you sir for your help.
