### ISSUE TITLE
No Label Row Display Issue

### ISSUE THREAD

**Issue by princepc** [ngx-formly/ngx-formly#1540]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
when displaying a row of input fields with some fields having labels some without
the fields without labels are displayed in the wrong position.
Also Classname on a field doesn't apply unless part of a row (see mac address).

**Expected behavior**
Fields in a row should remain in there row position
Classname gets applied so that a field will be show in the correct size.

**Minimal reproduction of the problem with instructions**
example here:
https://stackblitz.com/edit/angular-oqnqnw-zonhue?file=src%2Fassets%2Fjson-powered%2Fuser-form.json
-->

**What is the motivation / use case for changing the behavior?**
Consistent display

**Comment by aitboudad** [comment]
all of your issues are related to the bootstrap grid which can be solved by adding grid utilities.

> when displaying a row of input fields with some fields having labels some without
the fields without labels are displayed in the wrong position.

add `align-items-end` to `fieldGroupClassName`.
```ts
"fieldGroupClassName": "row align-items-end",
```

> Also Classname on a field doesn't apply unless part of a row (see mac address).

the parent component should contains `row` class in order to work
```html
<form class="container" ...>
  <formly-form class="row" ...></formly-form>
  ...
</form>
```

here is a working example https://stackblitz.com/edit/angular-oqnqnw-7asqnb

```

**Comment by princepc** [comment]
Thanks the align-items-end works nicely.
But if i use a class="row" that applies to all fields which can lead to odd things happening if the page is wider, e.g. in your example with a wider page the 'row of input labels' heading will appear on the same line as the name prompts, and the 'Color Preference' fields will be on the same line as the mac address field.
I would like those fields to still appear in a column layout, unless marked as a fieldGroup and for them to not take up the full width of the page.
Is there some way to achieve that - as we can by specifying the column width via className for a fieldGroup?

**Comment by aitboudad** [comment]
could you please provide me an example, thanks!

**Comment by princepc** [comment]
Sure, sorry if i'm not explaining it well...if you use your working example:

https://stackblitz.com/edit/angular-oqnqnw-7asqnb

and resize the display to make it wider - as it could be on a wider input form you can hopefully see what i mean in the screenshot below:
'row of input labels' heading is now on the same line as the name prompts, and the 'Color Preference' fields are on the same line as the mac address field.

![image](https://user-images.githubusercontent.com/48338295/56929754-cb448600-6b1d-11e9-9599-338e0d96b7e1.png)

What i would hope is that irrespective of the page width i can control how wide the fields are so that the form appears in a consistent way, e.g.
![image](https://user-images.githubusercontent.com/48338295/56929820-ffb84200-6b1d-11e9-8bdc-ae6f28d98b59.png)

**Comment by aitboudad** [comment]
you have to pass `className` to all your fields, see https://stackblitz.com/edit/angular-oqnqnw-7asqnb

**Comment by princepc** [comment]
OK thanks i'll try that out
