### ISSUE TITLE
how to change model in fieldArray child field with ngx-datatable

### ISSUE THREAD

**Issue by bkcsfi** [ngx-formly/ngx-formly#1546]
**I'm submitting a ...**  (check one with "x")
```

[X ] support request
```

**Current behavior**

I am using ngx-datable with material, similar to the example on the ngx-formly demo page.

GIven 3 columns  qty, unitPrice and extendedPrice. I need to calculate and update the 'readonly' extendedPrice input field when either qty or unitPrice changes.

Rows are laid out as a fieldGroup within a fieldArray

I can catch changes on the qty or unitPrice columns either using a validator or change hook on individual fields, or I can see changes using a validator at the fieldArray level.

However I am unable to target the model for extendedPrice, so there's no way to save the qty * unitPrice value into it's corresponding model.

I suppose I could try parsing 'id' on qty onChange control, then using getElementById to force a value onto the extendedPrice input element but that would be pretty ugly.

Any suggestions?

**Comment by bkcsfi** [comment]
ultimately I was able to work around this by:

- assigning a className to the qty, unitPrice and extendedPrice fields
- use the 'change' templateOption for qty and unitPrice to call a function that 
- calculates the extendedPrice by traversing the change event -> currentTarget.closest() to find the ancestor 'datatable-body-row', then querySelector for the "className input" I had set on the fields to get access to the qty, unitPrice and extendedPrice html input elements.

I had also tried adding a hideExpression on the FieldGroup. This gave me access to the model for that row and I was able to directly alter the model's extendedPrice field. However changing this value in the model did not change the UI, likely due to one-way binding.

ugly but works.. :-(

**Comment by aitboudad** [comment]
See https://github.com/ngx-formly/ngx-formly/issues/1447#issuecomment-467808849

**Comment by bkcsfi** [comment]
thanks for the pointer. Which hook or event would I use to get access to a formControl for the group?

**Comment by aitboudad** [comment]
It's better to replicate an example of what you've done using stackblitz so could provide some hints.

**Comment by aitboudad** [comment]
just provided an answer to a question that may be related to this too, see https://github.com/ngx-formly/ngx-formly/issues/1547
