### ISSUE TITLE
Modify field in repeat section

### ISSUE THREAD

**Issue by adde71** [ngx-formly/ngx-formly#1547]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

If considering the example provided on the website [https://stackblitz.com/angular/yogrrabnylm](https://stackblitz.com/angular/yogrrabnylm). How can I update a specific field in a repeat section based on another one? E.g. if I fill in a value in the "Name of Investment field", how can I update the value of "Stock identifier" in the exact same section programmatically?

**Comment by aitboudad** [comment]
- Method1: Subscribe to `valueChanges`: https://stackblitz.com/edit/angular-n9bnnt
- Method2: Use `expressionProperties`: https://stackblitz.com/edit/angular-auyewc

**Comment by adde71** [comment]
What if I want to create a function that changes the value?

**Comment by aitboudad** [comment]
not clear to me, could you elaborate a little more?

**Comment by adde71** [comment]
If I would pass the value to a function by an onChange event or so in the expressionProperties and then make the function update the "Stock identifier"-field.
E.g onChange: this.myfunction(this.model.investmentName)

**Comment by aitboudad** [comment]
pass the field as a second argument to your function, then set the new value:

```ts
onChange: (event, field) => this.myfunction(this.model.investmentName, field);
...
myfunction(value, field) {
  const form = field.parent.formControl;
  form.get('stockIdentifier').setValue(value);
}
```

**Comment by adde71** [comment]
Could you provide a working example? I can't make it work.

**Comment by aitboudad** [comment]
not sure what do you want to achieve so for me it's difficult to point you into the right path, could you show me what you've done (stackblitz example)

**Comment by bkcsfi** [comment]
@adde71  this is what worked for me. My example has the change event handler receiving 'field' as the first arg, which is opposite to @aitboudad 's example above

FormlyFieldConfig item  ..

```typescript
  {
	type: 'input',
	key: 'unitPrice',
	className: 'flex-1',
	templateOptions: {
	  label: 'unit Price',
	  required: true,
	  type: 'number',
	  min: 0.01,
	  change: (field, event) => {
		this.updateCCiLineVcc(field);
	  }
	}
  },
```

and the handler

```typescript
  updateCCiLineVcc(field) {
    const form = field.parent.formControl;
    const quantity = form.get('quantity').value;
    const unitPrice = form.get('unitPrice').value;
    const vcc = Number(quantity) * Number(unitPrice);
    if (vcc) {
      form.get('vcc').setValue(vcc.toFixed(3));
    } else {
      form.get('vcc').setValue(null);
    }
  }
```
