### ISSUE TITLE
Set/patch value doesn't trigger change event

### ISSUE THREAD

**Issue by eduardoleopoldino** [ngx-formly/ngx-formly#1548]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Setting programatically value to a field, doesn't trigger change event

**Expected behavior**
Trigger change event

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-fg6gne

**What is the motivation / use case for changing the behavior?**
Add extra logic whenever value changes

**Comment by aitboudad** [comment]
the change event is triggered only when UI changes, 
to get `valueChanges` in the UI or programmatically use `onInit` hook here is a working example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-krjefz
