### ISSUE TITLE
How to get if a checkbox is checked or unchecked

### ISSUE THREAD

**Issue by boufenzi** [ngx-formly/ngx-formly#1549]
Hello everybody, 
I'm trying to send a POST request depending on if a multicheckbox is checked or not. 
if checked i sent the Value of the checkbox and his statut if it was a checked action or a unchecked action 

i tried something like this but i don't think this is the best way to do it 

```
{
      className: 'col-5 titre_modules',
 key: 'roles',
 type: 'multicheckbox',
 templateOptions: {
        type: 'array',
        label: 'Roles',
        options: [],
        valueProp: 'id',
        labelProp: 'roleName',
      }, hooks: {
        onInit: (field) => {
       ....
        }, onChanges: (field) => {
          const form = field.parent.formControl;
          form.get('roles').valueChanges.pipe(takeUntil(this.onDestroy$), startWith(form.get('roles').value), tap(roleId => {
            if (roleId && roleId.length != 0) { // not sur if this is the best way to do it 
              console.log(form.get('roles'));
            } else {
              ...
            }
          }),).subscribe();
        },
      },
    }],
```

I searched on github documentation but there is not a lot of thing about the checkbox examples

Thank you in advance

**Comment by boufenzi** [comment]
after multiple search i found about this method "afterContentChecked" but i don't know how to use it for my purpose. anyone knows how we can use it to get the value of the checked option and of the unchecked option  .

**Comment by aitboudad** [comment]
I think that's correct if the `roleId.length > 0` then at least one of the `options` is checked,
I've only one note is to avoid relying on `onChanges` hooks and use `onInit` instead.

**Comment by boufenzi** [comment]
yes but it doesn't give you if the checkbox is checked or unchecked, example : if i checked the value 1 and then the value 2 then after i unchecked the value 2 it will give a response like this if i don't use the type array in template options {1: true, 2: false}, the main objective is to have only the last value checked or unchecked returned like this {2:  false} . is it possible with formly to do that ?

**Comment by aitboudad** [comment]
yes possible use the `pairwise` operator which allows getting the previous and current values to compare, here is a simple example https://stackblitz.com/edit/angular-btyg1f

**Comment by boufenzi** [comment]
omg i forgot about this rxjs operator.  thank you very much  for your help.

**Comment by boufenzi** [comment]
I tried to follow the example in the stackblitz but i have some issuses with is : 
 First: is there no other way to do it more simple because the checked and the unchecked status need to be a method that exist and not something we need to work on in my opinion. it will be great if there is on the futur an enhancement for that.
Second: There is a problem with pairewise if you use an observable with it to get data. 
the main problem is the statut of the value. example when we checked the value 4 it return {4: false} when it should return {4: true}

For example in my code i tried something like this : 
```
 fields: FormlyFieldConfig[] = [{
    fieldGroupClassName: 'row', fieldGroup: [{
      className: 'col-7 titre_modules', key: 'modules', type: 'radio', templateOptions: {
        type: 'array',
        label: 'Modules',
        options: this.typeRequete.getData('modules?projection=ModulesForBaliseSelect&sort=moduleName, ASC').pipe(map(data => {
          return data['content'];
        })),
        valueProp: 'id',
        labelProp: 'moduleName',

      },
    }, {
      className: 'col-5 titre_modules', key: 'roles', type: 'multicheckbox',
      templateOptions: {
        label: 'Roles', options: [], valueProp: 'id', labelProp: 'roleName',  type: 'array',
      },
      hooks: { onInit: (field) => {
        const form = field.parent.formControl;
        form.get('modules').valueChanges.pipe(takeUntil(this.onDestroy$), startWith(form.get('modules').value), tap(modulesId => {
          if (modulesId && modulesId.length != 0) {
            field.templateOptions.options = this.typeRequete.getData('modules/' + modulesId + '/roles?projection=RolesFromModuleIdForBalise').pipe(map(data => {
              return data['content'];
            }))
          } else {
            field.templateOptions.options = [];
          }
        }),).subscribe();
        form.get('roles').valueChanges.pipe(
          takeUntil(this.onDestroy$),
            startWith( form.get('roles').value),
            pairwise(),
            map(([a1, a2]) => {
              const diff = this.arrDiff(a1 || [], a2 || []);
                return diff.reduce((v, d) => {
// the a2.includes(d) always return with false
                v[d] = a2.includes(d);
                return v;
              }, {});
            }),
            tap(v => console.warn(v))
          ).subscribe();
        },
      },
    }],
  },];
```
as a beginner in formly I'm sorry to ask a lot of questions about that but i'm a big fan of formly  and i'm trying  to show whats are the main issues that me or someone else will face if he worked with checkbox.

Thank you.

**Comment by aitboudad** [comment]
> First: is there no other way to do it more simple because the checked and the unchecked status need to be a method that exist and not something we need to work on in my opinion. it will be great if there is on the futur an enhancement for that.

well you can create a custom field type to simplify that part (https://github.com/ngx-formly/ngx-formly/blob/master/src/bootstrap/src/lib/types/multicheckbox.ts) + PR welcomed!

> Second: There is a problem with pairewise if you use an observable with it to get data.

I couldn't reproduce it, could please provide me a reproduction using the following example https://stackblitz.com/edit/angular-btyg1f

**Comment by boufenzi** [comment]
Thank you for the quick response, 
The example i'm using is based on the stackblitz you showed me, the only difference is that i'm using a service to get data from backend for the radio button and the roles Multicheckbox.  when the first radiobutton is clicked then the multicheckbox get data from backend using the value of the first radio button, you can trie to get data from any backend it will return the same issue because the option of the checkbox in the onInit is empty : 

```
  fields: FormlyFieldConfig[] = [{
    fieldGroupClassName: 'row', fieldGroup: [{
      className: 'col-7 titre_modules', key: 'modules', type: 'radio', templateOptions: {
        type: 'array',
        label: 'Modules',
        options: 'here i'm getting the data from backend'
        valueProp: 'id',
        labelProp: 'moduleName',

      },
    }, {
      className: 'col-5 titre_modules', key: 'roles', type: 'multicheckbox',
      templateOptions: {
        label: 'Roles', options: [], valueProp: 'id', labelProp: 'roleName',  type: 'array',
      },
      hooks: { onInit: (field) => {
        const form = field.parent.formControl;
        form.get('modules').valueChanges.pipe(takeUntil(this.onDestroy$), startWith(form.get('modules').value), tap(modulesId => {
          if (modulesId && modulesId.length != 0) {
            field.templateOptions.options = 'here is my service that returns the data from my backend using the moduleId value to return only roles of this module i checked '
          } else {
            field.templateOptions.options = [];
          }
        }),).subscribe();
        form.get('roles').valueChanges.pipe(
          takeUntil(this.onDestroy$),
            startWith( form.get('roles').value),
            pairwise(),
            map(([a1, a2]) => {
              const diff = this.arrDiff(a1 || [], a2 || []);
                return diff.reduce((v, d) => {
                v[d] = a2.includes(d);
                return v;
              }, {});
            }),
            tap(v => console.warn(v))
          ).subscribe();
        },
      },
    }],
  },];
  arrDiff(a1, a2) {
    if(a1 && a2 ) {
      let a = [], diff = [];
      for (var i = 0; i < a1.length; i++) {
        a[a1[i]] = true;
      }

      for (var i = 0; i < a2.length; i++) {
        if (a[a2[i]]) {
          delete a[a2[i]];
        } else {
          a[a2[i]] = true;
        }
      }

      for (var k in a) {
        diff.push(k);
      }

      return diff;
    }
  }
  ngOnDestroy(): void {
    this.onDestroy$.next();
    this.onDestroy$.complete();
  }
```

**Comment by aitboudad** [comment]
still work for me https://stackblitz.com/edit/angular-btyg1f,

*Note*: you can use delay to simulate backend http.

**Comment by boufenzi** [comment]
but how can i get data from backend using service inside the of method. 
Like this i don't think it will work 
     field.templateOptions.options = of([
              this.typeRequete.getData('modules/' + modulesId + '/roles?projection=RolesFromModuleIdForBalise').pipe(map(data => {
                             return data['content'];
              }))
          ]).pipe(delay(1000));

**Comment by aitboudad** [comment]
I didn't mean that you should use delay with your backend service, just want to provide me a reproduction example and to simulate your backend calls you may use delay.
```ts
field.templateOptions.options = of([
  // pass here a portion of your backend result
  { ... },
  { ... },
]).pipe(delay(1000));
```

**Comment by boufenzi** [comment]
it is what i did but its not working for me, when you use pipe map to get data from backend . anyway thank you for your help sir, i really apreciate it, i will try to find the solution in another way. i will share the solution for multicheckbox when i find a easy way to get the status checked and unchecked without using all of this method. thank you for your help it really helped me a lot

**Comment by boufenzi** [comment]
i found out what was wrong with my code.
the     v[d] = a2.includes(d); should be v[d] = a2.some(e => e==d); because a2.includes(d) always return false if you use pipe map to get data from backend. hope this will help someone else whos working also with multicheckboxs
