### ISSUE TITLE
Field Label collapses when type is number and value is 0

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1551]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
Hi,
I am facing a weird issue when it comes to disabling the form. All fields work fine except a field with `type:number`. The label collapses when the value is 0 and Material is adding the `mat-empty` class to the label when the value is 0.

This is a snapshot.
![image](https://user-images.githubusercontent.com/1163421/56685192-0720bb00-66da-11e9-9b17-c0bc025da3f4.png)

The field is showing as disabled but the label collapses!

Hint: I am cloning the fields before rendering them as to allow dynamic forms (as recommended by @aitboudad.

I am not able to replicate the above on a sample!

If the model value is string "0" it works fine, only when the value is a number 0 this happens.

Any idea where I might dig and debug to see what's going on?

Thanks

**Comment by aitboudad** [comment]
a similar [issue](https://github.com/ngx-formly/ngx-formly/issues/1029#issuecomment-483570764) has been fixed in `5.0.4` (https://github.com/ngx-formly/ngx-formly/pull/1538 and https://github.com/ngx-formly/ngx-formly/pull/1533),  ensure you're using the latest version of formly else a reproduction is required.

**Comment by bhaidar** [comment]
@aitboudad omg! It works! Thanks a lot as always!

Is there a better way of keeping up with the latest changes on formly? Or at least, what's the proper way to keep an eye on the changes coming over?

**Comment by aitboudad** [comment]
Use release-only watch:
![Selection_005](https://user-images.githubusercontent.com/1753742/56688052-9b395500-66cf-11e9-9dd0-c296d1466973.png)
