### ISSUE TITLE
Is it possible to have more than one field match in a form?

### ISSUE THREAD

**Issue by blasferatu** [ngx-formly/ngx-formly#1557]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
Is it possible to have more than one field match in a form? I followed the password example (https://stackblitz.com/angular/reveaanjebg?file=src%2Fapp%2Fapp.component.ts). I wonder if I can do the same to more fields in the same form (e.g. besides password and password confirmation, e-mail and e-mail confirmation; please see example here: https://stackblitz.com/edit/multiplefieldmatch?embed=1&file=src/app/app.component.ts)

Thank you.

**Comment by aitboudad** [comment]
just create another fieldGroup for email https://stackblitz.com/edit/multiplefieldmatch-yjuswn
and if you've time refactor to make the validator generic would be good

**Comment by blasferatu** [comment]
Thank you.
