### ISSUE TITLE
Nested options are ignored

### ISSUE THREAD

**Issue by intellix** [ngx-formly/ngx-formly#1563]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

Nested options object is ignored. Only the first level is used/referenceable

**Expected behavior**

Nested options object should be accessible

**Minimal reproduction of the problem with instructions**
1) Provide options
2) Nest something and provide options again
3) Try to access that nested options object

Repro: https://stackblitz.com/edit/angular-5xverj?file=src%2Fapp%2Frepeat-section.type.ts

TL;DR of problem:
```
options: FormlyFormOptions = {
  formState: {
    a: 1,
  },
};
fields: FormlyFieldConfig[] = [
  {
    key: 'investments',
    type: 'repeat',
    options: {
      formState: {
        a: 2,
      },
    },
    fieldArray: {
      options: {
        formState: {
          a: 3,
        },
      },
      fieldGroup: [
        {
          options: {
            formState: {
              a: 4,
            },
          },
          expressionProperties: {
            label: (model, formState, field) => {
              console.log(formState.a); // prints 1 instead of 4, 3 or 2
            },
          },
```

**What is the motivation / use case for changing the behavior?**

You can provide an options object at all levels but none of them are used so it should either be taken into consideration, removed or documented. I guess currently you always get the root options object so I believe it should be changed to look up the tree for the closest one

I'm creating a QueryBuilder of sorts. I've created a custom FieldArrayType to populate the rest of the form using the formState object to pass in a set of types like so:

```ts
onPopulate(field: FormlyFieldConfig) {
  ...
  
  for (let i = field.fieldGroup.length; i < field.model.length; i++) {
    const { fieldDataOptions } = field.options.formState;
    field.fieldGroup.push({
      key: `${i}`,
      ...createFormlyFieldData(fieldDataOptions),
    });
  }
}
```

* **Angular version:** 7.2.14

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome, all probably

* **Node (for AoT issues):** `node --version` = 10.15.2

**Comment by intellix** [comment]
Actually, now I'm starting to think it's deprecated but I never saw any messages about that: https://github.com/ngx-formly/ngx-formly/blob/master/src/core/src/lib/components/formly.field.ts#L36

I guess the warnDeprecation only works when you pass an options object to the component itself?

**Comment by aitboudad** [comment]
we don't support a scoped options, I would expect typescript to raise an error in such case as
options is [readonly](https://github.com/ngx-formly/ngx-formly/blob/master/src/core/src/lib/components/formly.field.config.ts#L19).

instead, pass a state throughout `templateOptions` and assign it to the child fields using `onPopulate`, 
here is a simple example https://stackblitz.com/edit/angular-5xverj-8qrxmc.
you can make it generic using a custom extension.

**Comment by intellix** [comment]
Ended up doing that. Thanks :)
