### ISSUE TITLE
Contribution: ag-grid

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1565]
**Contribution**

I would like to share my ag-grid formly integration:

[https://stackblitz.com/edit/angular-pf888n-87wnyt](https://stackblitz.com/edit/angular-pf888n-87wnyt?file=src%2Fapp%2Fapp.component.ts)

You can add the implementation to the formly examples.

**Comment by aitboudad** [comment]
PR welcomed :), it can be added in https://github.com/ngx-formly/ngx-formly/tree/master/demo/src/app/examples/advanced

**Comment by FritzHerbers** [comment]
Added a PR https://github.com/ngx-formly/ngx-formly/pull/1567
