### ISSUE TITLE
On Upgrading formly to 5.0.4 ngPrime component accordiontab throws error

### ISSUE THREAD

**Issue by shikhaAtWork** [ngx-formly/ngx-formly#1571]
**I'm submitting a ...**  (check one with "x")
```
[ ] support request
```

**Current behavior**

After upgrading Formly to 5.0.4, accordiontab throws below error:(Using ngPrime 7.1.0 for components)
AccordionTabComponent.html:1 ERROR Error: StaticInjectorError(AppModule)[AccordionTab -> Accordion]: 
  StaticInjectorError(Platform: core)[AccordionTab -> Accordion]: 
    NullInjectorError: No provider for Accordion!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:717)
    at resolveToken (core.js:954)
    at tryResolveToken (core.js:898)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:795)
    at resolveToken (core.js:954)
    at tryResolveToken (core.js:898)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:795)
    at resolveNgModuleDep (core.js:17656)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:18345)
    at resolveDep (core.js:18716)

**Expected behavior**

Accordion tab should render and work properly.

**Minimal reproduction of the problem with instructions**

Upgrade Formly to 5.0.4 and try populating the p-accordiontab. You would get the above issue.
Accodion.component.html
<p-accordion [multiple]="to.multiple || true" [style]="to.style" [styleClass]="to.styleClass" [activeIndex]="to.activeIndex"
  [expandIcon]="to.expandIcon || 'pi pi-chevron-down'" [collapseIcon]="to.expandIcon || 'pi pi-chevron-up'" (onClose)="onClose($event)" (onOpen)="onOpen($event)">
  <ng-container #fieldComponent></ng-container>
</p-accordion>

Accordion-tab.component.html:
<p-accordionTab [header]="to.header" [selected]="to.selected || false" [disabled]="to.accordionDisabled">
  <ng-container #fieldComponent></ng-container>
</p-accordionTab>

Accordion.component.html
<p-accordion [multiple]="to.multiple || true" [style]="to.style" [styleClass]="to.styleClass" [activeIndex]="to.activeIndex"
  [expandIcon]="to.expandIcon || 'pi pi-chevron-down'" [collapseIcon]="to.expandIcon || 'pi pi-chevron-up'" (onClose)="onClose($event)" (onOpen)="onOpen($event)">
  <ng-container #fieldComponent></ng-container>
</p-accordion>

Accordion.component.ts
export class AccordionComponent extends FieldWrapper {
  @ViewChild('fieldComponent', {read: ViewContainerRef}) fieldComponent: ViewContainerRef;
  /**
   * Callback to invoke when an active tab is collapsed by clicking on the header.
   * @param $event Tabview event
   */
  onClose(event) {
    if (this.to.onClose) {
      this.to.onClose(event);
    }
  }
  /**
   * Callback to invoke when a tab gets expanded.
   * @param $event Tabview event
   */
  onOpen(event) {
    if (this.to.onOpen) {
      this.to.onOpen(event);
    }
  }
}

consumer Config:
accordion: FormlyFieldConfig = {
    key: 'accordion',
    wrappers: ['swb-accordion'],
    templateOptions: {
      activeIndex: 1,
      onOpen: (event) => {
        console.log('Opened');
      },
      onClose: (event) => {
        console.log('Closed');
      }
    },
    fieldGroup: [
      {
        key: 'accordionTabOne',
        wrappers: ['swb-accordionTab'],
        templateOptions: {
          header: 'Accordion One',
        },
        fieldGroup: [
          {
            key: 'customKey',
            type: 'swb-textfield',
            templateOptions: {
              label: 'customLabel',
              type: 'text',
            },
            validators: {
              validation: [], // Enter your validation function here
            },
          },
        ]
      }
    ]
  };

fields: FormlyFieldConfig[] = [
   this.accordion ];

consumer.html
<app-swb-form [model]="model" [fields]="fields" [options]="options" [form]="form"></app-swb-form>

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 6.0.X

* **Browser:** [ Chrome XX ]

* **Language:** [ TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =10.15.0

**Comment by aitboudad** [comment]
Maybe related to an issue in ngPrime, try to update ngPrime to 7.1.2 else I need a reproduction using stackblitz: https://stackblitz.com/edit/angular-o29jy7

**Comment by shikhaAtWork** [comment]
On upgrading ngPrime to 7.1.2, the issue still persists. Have reproduce the issue, please have a look https://stackblitz.com/edit/angular-o29jy7-muzyaq

**Comment by aitboudad** [comment]
does it work before, if yes in which version?

**Comment by aitboudad** [comment]
I doubt it was working before, anyway here is my proposal to handle the accordion type: https://stackblitz.com/edit/angular-o29jy7-oyoxxe

**Comment by shikhaAtWork** [comment]
On assigning a key to the accordion component, throws the below error:
Cannot set property 'undefined' of undefined
Please refer https://stackblitz.com/edit/angular-o29jy7-pai4bd
