### ISSUE TITLE
The 5.1.0 version isn't available on NPM ?

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#1572]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I wanted to try the hideExpression feature improvement but I can't update to the 5.1.0 version of Formly.

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ngx-formly/core@^5.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Am I the only one? or it isn't published yet?

**Expected behavior**
Be able to update to the 5.1.0 version

* **Angular version:** 7.2.13  

* **Formly version:** 5.0.4

* **Browser:** 
Chrome 73.0.3683.103

* **Language:** 
TypeScript 3.2.4

**Comment by aitboudad** [comment]
> Am I the only one?

possible as it works for me, maybe related to a typo issue on your package.json or your network.

**Comment by Jukien** [comment]
Ok @aitboudad, you were right. My NPM registry config was the cause.
Thank you for the quick answer and sorry for the disturbance.
Have a nice day!
