### ISSUE TITLE
Issues after updating from 5.0 to 5.1. Some properties is not initialised correctly

### ISSUE THREAD

**Issue by longtomjr** [ngx-formly/ngx-formly#1573]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
After updating from v5 to 5.1 my formly forms all started failing with `field.modelOptions is undefined` (firefox) and `Cannot read property 'debounce' of undefined` (chrome). 

**Expected behavior**
Expect the forms to render and no errors to be given.

**Minimal reproduction of the problem with instructions**
Currently I am failing to recreate this bug in a vacuum, will update the issue if I figure out.

**What is the motivation / use case for changing the behavior?**
I would like to prevent this from happening on my codebase and figure out what is wrong. Also it might be necessary to document this as a breaking change?

**Please tell us about your environment:**
Windows - Node - Angular

* **Angular version:** 7.2.14

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by longtomjr** [comment]
I tracked the issue down to this function and line: https://github.com/ngx-formly/ngx-formly/blob/7da132880f451019018037599e126214c17280f3/src/core/src/lib/components/formly.form.ts#L164

**Comment by aitboudad** [comment]
> Currently I am failing to recreate this bug in a vacuum

A reproduction is needed as I'm not able to reproduce it,
maybe one of the passed `field` is undefined so formly ignored that field during the initialization,
the following part should be called https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/extensions/core/core.ts#L61

> Also it might be necessary to document this as a breaking change?

Stability first, if there are any BC break, it should be reverted!

**Comment by longtomjr** [comment]
Thanks for the reply. It seems like having an `undefined` field breaks quite a few things. Is this expected behavior? What should happen in the case of an undefined field?

**Comment by aitboudad** [comment]
we don't expect passing an `undefined` field, I'll try to provide a fix for that, either ignore it or raise a warn log

**Comment by longtomjr** [comment]
Ok, this bug at least is not because of an undefined field, Explicitly filtered out all fields. and still getting the error.

Also - when i do 

```
              c.modelOptions = {
                    debounce: {
                        default: 20,
                    },
                };
```
(so set the model options for all of the fields)

i get `formControl is undefined`

**Comment by longtomjr** [comment]
Ok - I have an error - I think it might be related, the issue seems to be with fields in the `fieldGroup`: https://stackblitz.com/edit/angular-s48zcb

**Comment by aitboudad** [comment]
that expected as the type `input` is not compatible with `fieldGroup` that's why it raises an error.

**Comment by longtomjr** [comment]
Ok, After changing all of the fields that have `fieldGroup: null` to `fieldGroup: []` I now have rendering. All that is rendering is my wrappers though.

**Comment by aitboudad** [comment]
try to progressively enable one by one until you get the source of the issue.

**Comment by longtomjr** [comment]
Thanks, working on that :)

**Comment by longtomjr** [comment]
When I bypass the wrappers and just pass in a flat array of fields I get `Cannot find control with unspecified name attribute`. on my template. Did anything with templates change?

**Comment by aitboudad** [comment]
> Did anything with templates change?

that error is raised when the `formControl` is undefined, not related to the wrapper but when the field type is not set.

**Comment by longtomjr** [comment]
I think the issue might be related to : https://github.com/ngx-formly/ngx-formly/issues/1023 . I am also retrieving data. Poking around with that now.

**Comment by longtomjr** [comment]
Ok, I am going to go through every minor release for v5 and see when the error starts appearing. Then I will see if I can figure out from the diff what is going on. I cannot reproduce this at all outside of my codebase - so I think I might be doing something wrong and something changed so that whatever I was doing wrong is now obvious. I will keep you updated. Sorry for the bother.

**Comment by longtomjr** [comment]
@aitboudad Found the version the bug was introduced in. v5.0.4

Here is the diff: https://github.com/ngx-formly/ngx-formly/compare/v5.0.3...v5.0.4

**Comment by aitboudad** [comment]
can you check that you've called `FormlyModule.forRoot()` in your app ?

**Comment by longtomjr** [comment]
Nope, only `forChild()` in the modules I use formly. Should I be calling forRoot() ?

**Comment by aitboudad** [comment]
yep, it should be part of the root module,
add it where you've added `FormlyBootstrapModule` as mentioned in the readme:

```ts
@NgModule({
  imports: [
    ...,
    ReactiveFormsModule,
    FormlyModule.forRoot(),

    FormlyBootstrapModule,
  ],
})
export class AppModule {}
```

**Comment by longtomjr** [comment]
Ok, it is not giving me a different error - `field[type].validation.map is not a function` but I will have to restructure my app to use the .forRoot in anyways, so will report back. Thanks a lot for the help.

Is there an example of multiple modules using formly and how to configure it with `.forRoot` etc?

**Comment by longtomjr** [comment]
Ok the validation is broken on my end - after commenting out the validation builder part of my app it works. Thanks again for all the help!

**Comment by longtomjr** [comment]
Ok so one regression that I found is that `validators.validation` does not accept 1 `ValidatorFn` anymore.

**Comment by aitboudad** [comment]
`validation` expect an array, it was working before so I'll revert it and add a warn instead.
