### ISSUE TITLE
Validation red message not displayed on step click

### ISSUE THREAD

**Issue by mejriyassine** [ngx-formly/ngx-formly#1574]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

When i click on step 2 for example and form is not filled, required red message is not shown, Only when i focus and blur the field

**Expected behavior**

When click on Step two for example, required fields become red and Required message is displayed
**Minimal reproduction of the problem with instructions**

Keep fields empty and click on second step
You can test on this link
https://stackblitz.com/edit/form-stepper

**Please tell us about your environment:**

MacOS, visual code

* **Angular version:** 7.0.1

* **ngx formly version:** 4.8.0

**Comment by aitboudad** [comment]
related to https://github.com/angular/components/issues/6728 and unfortunately, there is no easy workaround to make work.
