### ISSUE TITLE
How to set fieldGroup as optional with required fields

### ISSUE THREAD

**Issue by xaviergxf** [ngx-formly/ngx-formly#1577]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X ] support request
```

**Current behavior**
I have a form A with an optional field fieldGroup B, and a field C required inside B . When submiting form A a required validation message regarding field C is showned event if my model is: {B:null} . 

**Expected behavior**
The required validation message on field C is only showed if any field on B is filled (B is not null).

Thanks

**Comment by aitboudad** [comment]
in which case `C` is required?

**Comment by xaviergxf** [comment]
C has templateoptions.required = true. All fields of B are set to null instead of B itself being null.

**Comment by aitboudad** [comment]
not sure I clearly understood that requirement, in order to apply required property conditionally you may use `expressionProperties` as shown in the following example https://stackblitz.com/edit/angular-vaey9j

**Comment by xaviergxf** [comment]
An example of form that would need this kind of required validation is a user form. User form contains some required properties such as login and name and optional fields such as address. Although address field is not required, some of their sub-fields such as as country and city are required. In formly when setting country and city as required and not filling anything inside address a required validation will be triggered and the form will show its message. Is there any way to correct this behavior?

Thanks

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-b9tct7

**Comment by xaviergxf** [comment]
with this demo i cannot leave address empty.

**Comment by aitboudad** [comment]
`required` expect a boolean value, I've updated the above example to make it work again.

https://stackblitz.com/edit/angular-b9tct7
