### ISSUE TITLE
Existing async directive validator removed on model change

### ISSUE THREAD

**Issue by aportolan** [ngx-formly/ngx-formly#1578]
**I'm submitting a ...**  (check one with "x")
```
[ *] bug report 
[ ] feature request
[ ] support request
```

**Current behavior**
Field with existing async validator as directive works fine until model is changed. When model changes, validator stops working
Formly version 5.0.0 was working as expected

**Expected behavior**
Field should be able to invoke validator after model change

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-nnokca-mrwcjd?file=src%2Fapp%2Fapp.component.ts

**Additional info**
It seems that changes introduced in class FieldFormExtension are causing this problem. Existing control.asyncValidator is overwritten with controlOptions.asyncValidators, although the latter is null.

```
export class FieldFormExtension implements FormlyExtension {
         ...
        // line 44
        if (controlOptions.asyncValidators !== control.asyncValidator) {
          control.setAsyncValidators(controlOptions.asyncValidators);
        }
        ...
```

**Comment by aitboudad** [comment]
that's an issue of angular https://github.com/angular/angular/issues/24472, for now
added a workaround in `5.1.3` but I would like to avoid supporting as such case in the future major version.

here is an example of an async validator using `formly` way: https://stackblitz.com/edit/angular-nnokca-wdeyyf
