### ISSUE TITLE
On assigning a key to the accordion component, throws the below error:

### ISSUE THREAD

**Issue by shikhaAtWork** [ngx-formly/ngx-formly#1581]
On assigning a key to the accordion component, throws the below error:
Cannot set property 'undefined' of undefined
Please refer https://stackblitz.com/edit/angular-o29jy7-pai4bd

_Originally posted by @shikhaAtWork in https://github.com/ngx-formly/ngx-formly/issues/1571#issuecomment-490751501_

**Comment by shikhaAtWork** [comment]
How would the user group accordions together in an object, say 'model', if we do not provide a key?

**Comment by aitboudad** [comment]
you've to define `defaultValue` for accordion type:
```ts
export class AccordionComponent extends FieldType {
  defaultOptions = {
    defaultValue: [],
  };
...
}
```

or within `FormlyFieldConfig`:
```ts
  accordion: FormlyFieldConfig = {
    type: 'accordion',
    defaultValue: [],
  }
  ...
```
