### ISSUE TITLE
Json Powered with Repeating Section With Length Input

### ISSUE THREAD

**Issue by loonis** [ngx-formly/ngx-formly#1583]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

**Current behavior**
I am trying to use Json Powered with Repeating Section With Length Input.
Here is a simple exemple of the problem : https://stackblitz.com/edit/angular-6jqc25

The json will be saved in the database so I'm trying to avoid putting Front code there. Instead, I preprocess the json to inject the functions and dependencies I'll need before passing it to Formly.

**Expected behavior**
Although the model is correctly injected to the field (same object reference), updating it does not render the change

**Minimal reproduction of the problem with instructions**
See stackblitz : https://stackblitz.com/edit/angular-6jqc25

* **Angular version:** 2.0.X
Angular 7.2.15
ngx-formly : "5.1.3"

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript : "3.1.1"

**Comment by aitboudad** [comment]
seems there is a simple way to do it without relying on hooks event, check the following example: https://stackblitz.com/edit/angular-6jqc25-4xh9so

**Comment by loonis** [comment]
Thank you for your quick answer.

The exemple I provided does not reflect the complexity of the real app.
AppComponent should be business agnostic. It will be fed with thousands of differents forms. So depending on the current form, business logic ( here modelChanges(model)) will be different.

That's why I'm trying to put all the business logic in the json. AppComponent is just a technical component that injects the function and dependencies from a library in the FormlyFieldConfig Object.

**Comment by aitboudad** [comment]
I see, so the better way is to manage it inside `RepeatTypeComponent`, I'll provide another way but when time allows

**Comment by loonis** [comment]
Thanks I'll try to investigate this way in the meantime.

**Comment by aitboudad** [comment]
I couldn't find a better way for now but here is a workaround that relies on internal API which you can use in the meantime https://stackblitz.com/edit/angular-6jqc25-4fijeg

**Comment by loonis** [comment]
Yes that does the trick thanks ! 
Here is how we use it : https://stackblitz.com/edit/angular-6jqc25-gbvjoz

In your example, the business logic is located in the RepeatTypeComponent. We try to avoid that because it will be used by different forms in different contexts.

That's we came up with injecting the logic (functions) outside of Formly.
It seems like a hack. 
I don't know if it is a commun use case among Formly users but I am open to alternatives.

Thank you for your help anyway :)

**Comment by aitboudad** [comment]
added a note in the [Roadmap](https://github.com/ngx-formly/ngx-formly/issues/1365) for 
`_buildForm` which an internal API that you can use in the meantime until we provide a better way.
