### ISSUE TITLE
Unable to patchValue/setValue on field when hideExpression is set to true

### ISSUE THREAD

**Issue by anthonymartinovic** [ngx-formly/ngx-formly#1585]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
If you attempt to patch a value or set a value on a field where `hideExpression` is set to true, it won't update the model anymore. This problems appears to be present as of the v5 release.

**Expected behavior**
Patching or setting a form value on a field with `hideExpression` set to true would still update the model object prior to v5.

**Minimal reproduction of the problem with instructions**
OLD BEHAVIOUR (v4.8.3) - https://stackblitz.com/edit/angular-qyncfy?file=package.json
If you don't type anything and just press submit once, the value of `model` will have the patched values for both `name` and `iLikeTwix`.

NEW BEHAVIOUR (v5.1.3) - https://stackblitz.com/edit/angular-qyncfy-n4knll?file=package.json
If you don't type anything and just press submit once, the value of `model` will only have the patched value for `name`. If you press submit again, only then will `iLikeTwix` have it's valued successfully patched. This is because it's `hideExpression` value is set to false after the first submission.

**What is the motivation / use case for changing the behavior?**
I want to be able to patch values to the form even if a particular field is hidden. At the moment (currently using v4.8.3), I'm able to achieve this by setting `hideExpression` to true and patching the value through anyway. Now that I've attempted to upgrade to v5.1.3, the patched values no longer get pushed to `model`, which has broken a handful of tests and general logic in my form setup.

If this change in behaviour is intentional, I'd appreciate if you could let me know the best way to achieve this same result as of v5.

**Please tell us about your environment:**
Mac OS Mojave - v10.14.4
VS Code - v1.33.1
npm - v6.7.0

* **Angular version:** 2.0.X
Angular 7+ (7.2.15 is the version used in the reproduction).

* **Browser:**
Reproduced in latest Firefox + Chrome.

* **Language:**
TypeScript - v3.2.4

**Comment by aitboudad** [comment]
Somehow that was working in `v4.8.3` :thinking: but that's expected behavior as the hidden field is detached from its parent form.

The better way to achieve that is to set value through the field instance: 
```ts
  submit() {
    ...
    this.getFieldControl('iLikeTwix').patchValue(true);
  }

  getFieldControl(key) {
    return this.fields.find(f => f.key === key).formControl;
  }
```
