### ISSUE TITLE
more than one ui library on one page, set ui library by code

### ISSUE THREAD

**Issue by emirtb** [ngx-formly/ngx-formly#1586]
Is posible use more than one ui library on same page? For example, for when the mobile is shown to use ionic and when it is shown in desktop use material?

**Comment by aitboudad** [comment]
yes possible I see two approaches, by loading the necessary module lazily or using a `prefix` for each `UI`.
I'll provide an example when time allows.

**Comment by emirtb** [comment]
I understand the problem of the time available, and I thank you for explaining the idea to me. The way to do it with lazy module I understand, but the one that is not clear to me is the "prefix", I would appreciate if you can explain me better, thank you.

**Comment by aitboudad** [comment]
> but the one that is not clear to me is the "prefix",

I mean registering material/ionic types with their prefix `mat`/`ion` respectively, not an ideal way as I would prefer the lazy load approach:

```ts
    FormlyModule.forRoot({
      types: [
        { name: 'mat-input', component: MatInputComponent },
        { name: 'ion-input', component: IonInputComponent },
      ],
    }),
```

```ts
  fields: FormlyFieldConfig[] = isMobile$.pipe(
    map(isMobile => {
      return [
        {
            key: 'name',
            type: isMobile ? 'mat-input' : 'ion-input',
        },
      ];
    })
  ),
```

**Comment by aitboudad** [comment]
added an example in https://github.com/aitboudad/formly-issue1586, check my last commit which contains all the necessary code to make it work.

**Comment by zakjakub** [comment]
Link is not working anymore :/

**Comment by aitboudad** [comment]
@zakjakub not public yet, so could you please describe your use-case?
