### ISSUE TITLE
Hide expression in repeating section

### ISSUE THREAD

**Issue by princepc** [ngx-formly/ngx-formly#1589]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
I have a JSON powered form with a repeating section, i would like to hide one of the repeating section fields based on a hideExpression referring to a field outside of the repeating section.

**Expected behavior**
hideExpression should work inside the repeating section, field should be hidden if it passed the test. Only works if referring to a field within the repeating section.

**Minimal reproduction of the problem with instructions**
refer to example:
https://stackblitz.com/edit/angular-oqnqnw-lfyvqm

Field Opinion in the examples repeating section should be hidden if the first field on the form!="NS" but doesn't display irrespective of the value of the first field.
The same kind of hideExpression test works if referring to a model field within the repeating section, refer to the field called 'Adjacent'

**What is the motivation / use case for changing the behavior?**
Control display of a field based on another field within a repeating section.

Is there something i'm missing in my hideExpression reference in the repeating section?

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

here is a working example: https://stackblitz.com/edit/angular-oqnqnw-o43ifu

**Comment by princepc** [comment]
Excellent, thanks again

**Comment by RamasubramanianA** [comment]
> see [#704 (comment)](https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614)
> 
> here is a working example: https://stackblitz.com/edit/angular-oqnqnw-o43ifu

Good example, helped me.  Thanks!
