### ISSUE TITLE
Accessibility - Repeating section - While Tabbing the focus remains on the Add hyperlink

### ISSUE THREAD

**Issue by akhaderachana** [ngx-formly/ngx-formly#1591]
**Current behavior**
When using keyboard for navigation, and clicking "Add" hyperlink, the focus remains on the hyperlink instead of resetting it to the first field in the added section 

**Expected behavior**
After adding a new section, the focus should be set to the first field in that section
 
**Minimal reproduction of the problem with instructions**
https://angular-l2tyre.stackblitz.io/
1. In the above example, using the keyboard, keep tabbing until the Add button.
2. When on "Add another investement",  Click Enter
3. The focus remains on Add button

**Comment by aitboudad** [comment]
that depends on the use-case, you may move the `Add` button to the top of the repeat section
or focus the first element of the repeat config which I would avoid but anyway here is a simple example https://stackblitz.com/edit/angular-l2tyre-dvy1r8?file=src/app/repeat-section.type.ts
