### ISSUE TITLE
Error: Can't resolve '@progress/kendo-angular-dropdowns'

### ISSUE THREAD

**Issue by kkseven07** [ngx-formly/ngx-formly#1593]
```
ERROR in ./node_modules/@ngx-formly/kendo/fesm5/ngx-formly-kendo.js
Module not found: Error: Can't resolve '@progress/kendo-angular-dropdowns' in '/Users/mymac/Work/node_modules/@ngx-formly/kendo/fesm5'
```

I just installed ngx-formly and kendo package and imported it to app.module.ts

**Comment by aitboudad** [comment]
`@progress/kendo-angular-dropdowns` is needed for `select` type, `npm install @progress/kendo-angular-dropdowns --save` would solve the issue.

**Comment by kkseven07** [comment]
![Screen Shot 2019-05-23 at 5 33 02 PM](https://user-images.githubusercontent.com/25701048/58249505-e4d59800-7d80-11e9-9de8-4f0b8f4e8cad.png)
After installing kendo-angular-dropdowns

**Comment by aitboudad** [comment]
related to https://github.com/telerik/kendo-angular/issues/2234, `rxjs-compat` is still needed unfortunetlty.
for a workaround add `rxjs-compat` to your deps.
