### ISSUE TITLE
Refresh Crud table data on change of select with PrimeNG

### ISSUE THREAD

**Issue by samir-kamble** [ngx-formly/ngx-formly#1595]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

Selectbox Change event is not able to capture for updating data in table.

**Expected behavior**

I have created a select box with some values which are to be linked with a crud table from PrimeNG. Which on change of value in selectbox will change values in Crud Table.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS: Win 7, IDE: VSCode

* **Angular version:** 2.0.X

NG7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All Browser.

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
fixed in `5.1.6`

**Comment by samir-kamble** [comment]
How do i use it can you please guide?

**Comment by aitboudad** [comment]
use `change` function:
```ts
{
  key: 'foo',
  type: 'select',
  templateOptions: {
    change: (field, $event)=> {
      console.log($event);
    }
  },
}
```

**Comment by samir-kamble** [comment]
i have updated my package. But is it not working.

**Comment by aitboudad** [comment]
a reproduction `stackblitz` example is needed to check what's going wrong, thanks!

**Comment by samir-kamble** [comment]
Hi,
It worked now I am getting value on selection, 

I did not took update on @ngx-formly/primeng. Updated only Core module.

Many thanks for your quick help.

But My question remains. Can I use Crud table from PrimeNG as a form field and read data from it on save.

Thanks,
Samir

**Comment by aitboudad** [comment]
> But My question remains. Can I use Crud table from PrimeNG as a form field and read data from it on save.

I think so, we've provided some examples but not with PrimeNg which you may check:

- https://ngx-formly.github.io/ngx-formly/examples/advanced/datatable-integration
- https://ngx-formly.github.io/ngx-formly/examples/advanced/grid-integration
