### ISSUE TITLE
convert "epoch time" to date format

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#1597]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Looking for help to convert "epoch time" value to a date format based on locale.
 
**Expected behavior**
I have seen a mention in #1367 on using template: utcDate, bit it is not clear to me on how to use it.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
enables us to display date based on local settings

**Please tell us about your environment:**

* **Angular version:** 7.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome and Firefox

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =
v10.15

**Comment by aitboudad** [comment]
could you elaborate more about your use-case,
do you want to parse the date before assigning it to the model or just for displaying purpose?

**Comment by argupta23** [comment]
@aitboudad 
Thanks for the prompt response.
In mongodb we save the date in "epoch/unix time" format eg: 1558320756902
we would like to be displayed in the Angular 7.x UI as "YYYY-MM-DD HH:MM:SS"

The format of Date in the UI should be adaptable to the users local preference (US / UK etc...)

Appreciate the help.

**Comment by aitboudad** [comment]
`template` allows only displaying static content, to take account of model change pass it throughout expression property or use a custom field type.

1. Custom field type with `date` pipe: https://stackblitz.com/edit/angular-w4nbpd-brxnxq
2. Simple template: https://stackblitz.com/edit/angular-w4nbpd
3. Template with expression property: https://stackblitz.com/edit/angular-w4nbpd-jak85f

**Comment by argupta23** [comment]
@aitboudad. thank you for the pointers.

https://stackblitz.com/edit/angular-w4nbpd solves my need for the time being,

**Comment by rdev-software** [comment]
I was able to use "Parsers" to transform dateTime to unix, but there are no "formatters" yet, so how to transform unix timestamp to dateTime ?

**Comment by rdev-software** [comment]
Or simple time picker, where I want to transform seconds value into time and back:

I can easily parse date from ion datepicker to seconds

`const parsedDate = new Date(date);
    return  (parsedDate.getHours() * 60 * 60) + (parsedDate.getMinutes() * 60) + parsedDate.getSeconds();`

And it will correctly save it in seconds to my model, but now when I need to display seconds as date
I cannot just pass formatting function to selected compoment

**Comment by aitboudad** [comment]
@rdev-software `formatters` not supported yet due to https://github.com/angular/angular/issues/3009.
