### ISSUE TITLE
How to make a wrapper for 2 field groups?

### ISSUE THREAD

**Issue by kkseven07** [ngx-formly/ngx-formly#1598]
Here is the link to the question.
https://stackoverflow.com/questions/56321390/how-to-make-custom-wrapper-for-2-field-groups-with-ngx-formly

**Comment by aitboudad** [comment]
check my answer on [StackOverflow](https://stackoverflow.com/questions/56321390/how-to-make-custom-wrapper-for-2-field-groups-with-ngx-formly/56327049#56327049)
