### ISSUE TITLE
Feature Request: 1:N relationships for cascaded select

### ISSUE THREAD

**Issue by mgcrmltd** [ngx-formly/ngx-formly#1600]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request
```

**Current behavior**

Currently, cascading option sets allow the child value to be linked to only one parent value. In the sports example, each team relates to exclusively Football or Basketball. 

**Expected behavior**

Take the example of a cascading option set list where the option set Subjects links to another one names Tutors. One tutor can teach multiple subjects. 

**Minimal reproduction of the problem with instructions**

N/A

**What is the motivation / use case for changing the behavior?**

Easier to implement cascading options for 1:N relationships

**Please tell us about your environment:**

* **Angular version:** 7

* **Browser:** [all ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
N/A

* **Node (for AoT issues):** `node --version` =
N/A

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-objlp6

**Comment by mgcrmltd** [comment]
Thanks, super helpful. I'm guessing this cannot work directly from Json?

**Comment by aitboudad** [comment]
it should work just check and adjust our demo example for [Cascaded Select JSON powered
](https://ngx-formly.github.io/ngx-formly/examples/other/cascaded-select-json) similarly to what I've done with the above example
