### ISSUE TITLE
How to track change event in radio buttons (ngx-formly)

### ISSUE THREAD

**Issue by radsin99** [ngx-formly/ngx-formly#1607]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
use the `change` event, see the following example https://stackblitz.com/edit/angular-kyerjg

**Comment by sawprogramming** [comment]
@aitboudad 

This doesn't seem to work with the PrimeNG components; it appears that the `[formlyAttributes]` binding is required for this feature to function, but those aren't present on the radio component for PrimeNG.

Example:
https://stackblitz.com/edit/angular-kyerjg-mpngg4

**Comment by aitboudad** [comment]
@sawprogramming change event is not exposed by [primeng radiobutton](https://www.primefaces.org/primeng/#/radiobutton)

**Comment by aitboudad** [comment]
here is an alternative way https://stackblitz.com/edit/angular-kyerjg-k9gqkg

**Comment by sawprogramming** [comment]
Thanks for the quick response!

**Comment by VijayaranganAYM** [comment]
Hi aitboudad, i need to show the date with time in formly. https://stackblitz.com/angular/gkyvgpnxaoj?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
@VijayaranganAYM The request is not clear, please elaborate!
