### ISSUE TITLE
custom type parameters

### ISSUE THREAD

**Issue by gtamas** [ngx-formly/ngx-formly#1609]
I'm submitting a 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**
A custom type is registered like this:

```
 FormlyModule.forRoot({
            types: [
                { name: 'flex-layout', component: FlexLayoutType },
              ],
```
I need to pass parameters to FlexLayoutType component, so I can use them in the template. Is this possible somehow? So I'm thinking of something like this:

```
<div
  fxLayout="{{ fxLayout }}"
  fxLayoutAlign="{{ fxLayoutAlign }}"
...
    >
```

Also, what data is available in the template? I mean, what's the context here?

**Expected behavior**
Some way to pass arbitrary data  to the custom type component and use this data in the template.

This is Angular 7.

Thanks in advance!

**Comment by aitboudad** [comment]
Pass the extra params through `templateOptions` of the field, you may check the following  example:
https://stackblitz.com/edit/ngx-formly-flex-layout

1. pass `fxLayout` through `templateOptions`:
```ts
{
    type: 'flex-layout',
    templateOptions: {
      fxLayout: 'row',
    },
}
```
2. use `templateOptions` inside the custom field type:
```ts
  template: `
    <div
      [fxLayout]="to.fxLayout" 
    >
```
**note**: `to` is shortcut name for `templateOptions`
