### ISSUE TITLE
Hide Expression across field group

### ISSUE THREAD

**Issue by mgcrmltd** [ngx-formly/ngx-formly#1612]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I have a hide expression for 'town' in the address field group. It is based on the value of 'name' in the address field group. It is not working as I expected. 

**Expected behavior**
I would like for the town field to show once text is added to name. I also wish to ultimately represent it using purely json.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-movjpt

* **Angular version:** 7

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614
