### ISSUE TITLE
How to apply change event on ngx-formly using bootstrap as lib

### ISSUE THREAD

**Issue by radsin99** [ngx-formly/ngx-formly#1613]
` change: (field, $event)=> {
          this.changeTable($event.value);
        }`
This doesn't work
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
changing the field value pragmatically can be done through `field.formControl.patchValue(value)`,
if that's exactly what're you looking for!
