### ISSUE TITLE
Array with alternating labels

### ISSUE THREAD

**Issue by HIAB-vesteel** [ngx-formly/ngx-formly#1617]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

I have a scenario where my model is an array [0, 255, 27]. 
I know that this is a Vector from my JSON-schema. I would like a repeat for the 3 values where each value have a different label.  Can't find any good examples where i could alternate information on index.

```
<input matInput placeholder="x" value="0">
<input matInput placeholder="y" value="255">
<input matInput placeholder="z" value="27">
```

**Comment by aitboudad** [comment]
here is an example that uses the field index as a label https://stackblitz.com/edit/angular-sukugx
