### ISSUE TITLE
 Opt-in to run expression on model changes only

### ISSUE THREAD

**Issue by silvl** [ngx-formly/ngx-formly#1620]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Typing lags on IE 11 when have expressions Lag is so extreme at times that causes mis-types with fast data entry. NOTE: It appears to work fine on Chrome.

**Expected behavior**
No lag when typing.

**Minimal reproduction of the problem with instructions**
Extending the example "Hide fields" with the following fields:

            "fields": [
                {
                    "key": "name",
                    "type": "input",
                    "templateOptions": {
                      "label": "Name",
                      "placeholder": "Type in here to display the hidden field"
                    }
                },
                {
                  "key": "full",
                  "type": "input",
                  "templateOptions": {
                    "label": "Full 1"
                  },
                  "hideExpression": "!model.name"
                },
                  {
                    "key": "full2",
                    "type": "input",
                    "templateOptions": {
                      "label": "Full 2"
                    },
                    "hideExpression": "!model.name"
                  },
                  {
                    "key": "full3",
                    "type": "input",
                    "templateOptions": {
                      "label": "Full 3"
                    },
                    "hideExpression": "!model.name"
                  },
                  {
                    "key": "full4",
                    "type": "input",
                    "templateOptions": {
                      "label": "Full 4"
                    },
                    "hideExpression": "!model.name"
                  },
                  {
                    "key": "full5",
                    "type": "input",
                    "templateOptions": {
                      "label": "Full 5"
                    },
                    "hideExpression": "!model.name"
                  },
                  {                   
                    "key": "empty",
                    "type": "input",
                    "templateOptions": {
                      "label": "Empty 1"
                    },
                    "hideExpression": "model.name"
                  },
                  {                   
                    "key": "empty2",
                    "type": "input",
                    "templateOptions": {
                      "label": "Empty 2"
                    },
                    "hideExpression": "model.name"
                  },
                  {                   
                    "key": "empty3",
                    "type": "input",
                    "templateOptions": {
                      "label": "Empty 3"
                    },
                    "hideExpression": "model.name"
                  },
                  {                   
                    "key": "empty4",
                    "type": "input",
                    "templateOptions": {
                      "label": "Empty 4"
                    },
                    "hideExpression": "model.name"
                  },
                  {                   
                    "key": "empty5",
                    "type": "input",
                    "templateOptions": {
                      "label": "Empty 5"
                    },
                    "hideExpression": "model.name"
                  }
            ]

To reproduce: in name field, type quickly something like user@test.com multiple times and even at some point the @ will display a 2 ...

**What is the motivation / use case for changing the behavior?**
Need for production. Is there a suggested best practice or workaround when using hideExpression or expressionProperties

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Tried with both Angular 7 & 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE 11

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
can you test in prod mode, generally IE11 Performance on dev mode is very slow

**Comment by silvl** [comment]
Yes, it is much improved in prod mode. Thank you. I was concerned as the ngDoCheck() in FormlyForm was called on every mousemove -- thus continuously invoking the checkExpressionChange(). If only do this on model changes, the checkExpressionChange() execution was decreased tremendously. Since expression changes are usually only dependent on model changes, I wonder if something should be done here to improve performance. Then, developers can set modalOptions to even decrease the number of times it is call, by setting updateOn to blur or using debounce property.

**Comment by aitboudad** [comment]
I was thinking about that before but I left it since no one noticed as such performance issue 
and I think `checkExpressionChange` doesn't cost too much even on a large form (it rely on a cached value plus a set of loops and conditions).

> Since expression changes are usually only dependent on model changes

not always but for the most of cases.

> Then, developers can set `modalOptions` to even decrease the number of times it is call, by setting updateOn to blur or using debounce property.

I think we should provide an opt-in for that, let me think about it.

**Comment by silvl** [comment]
An opt-in would be perfect!

**Comment by yluijten** [comment]
@aitboudad 

I've noticed you pushed some changes, concerning this issue, to the `master` branch. Is it possible to release a new version?

**Comment by aitboudad** [comment]
@yluijten not `master` but `v5` branch, the release is scheduled this week (`v5.3`), left just some minor features/fixes.

**Comment by aitboudad** [comment]
`5.3` is released which include an option that allows evaluating expressions on model change only, to enable that mode set the extra option `checkExpressionOn` to `modelChange` through the `NgModule` declaration:

```ts
@NgModule({
  imports: [
    FormlyModule.forRoot({
      extras: { checkExpressionOn: 'modelChange' }
    }),
  ],
})
export class AppModule {}
```
