### ISSUE TITLE
Error: @ngx-formly/core/lib/templates/field.type.d.ts(10,33): error TS1005: ';' expected.

### ISSUE THREAD

**Issue by mo-norant** [ngx-formly/ngx-formly#1621]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Does not build due to 
ERROR in node_modules/@ngx-formly/core/lib/templates/field.type.d.ts(10,33): error TS1005: ';' expected.

**Expected behavior**
has to build

**Minimal reproduction of the problem with instructions**

just install version 5v
**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

![image](https://user-images.githubusercontent.com/15997574/59108633-ac66ba00-893b-11e9-951a-1f845d966a78.png)

**Comment by aitboudad** [comment]
couldn't reproduce it, just ensure your `deps` are updated or match angular/formly requirements.
