### ISSUE TITLE
Component-level injectors don't work

### ISSUE THREAD

**Issue by franzeal** [ngx-formly/ngx-formly#1622]
**I'm submitting a ...**
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
In version 5, [component-level injectors](https://angular.io/guide/hierarchical-dependency-injection#component-level-injectors) do not work.

**Expected behavior**
[Component-level injectors](https://angular.io/guide/hierarchical-dependency-injection#component-level-injectors) should work.

**Minimal reproduction of the problem with instructions**
Below is a demonstration of component-level injectors.  I'm demonstrating a parent/child relationship of wrappers (A) and components (B) (these don't behave differently, which is expected).  In the console, each parent/child logs its service dependency.  The expectation is that all parent/child log output should have the service, but in the v5 demo the children receive null.

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-component-injectors-v3 (works)
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-component-injectors-v4 (works)
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-component-injectors-v5 **(issue)**

**What is the motivation / use case for changing the behavior?**
Trying to address:  https://github.com/franzeal/ngx-formly-tabs/issues/2

* **Angular version:**
Tested with Angular 6 and 7.

* **Browser:**
Chrome 75, Firefox 67

**Comment by ilijev07** [comment]
Any progress on this one?

**Comment by aitboudad** [comment]
I'll check it during this week but not sure if I would find a proper fix, the order of creation field component and its wrappers has been changed and we can't revert it.

**Comment by ilijev07** [comment]
Like a workaround for https://github.com/franzeal/ngx-formly-tabs/issues/2 it can be made with providing TabsetService in the module directly instead of component, I tried and it works fine.

**Comment by thiagogjt** [comment]
You can provide it on the container component. The drawback is that you cant have more than one tabset in the form...

**Comment by aitboudad** [comment]
@franzeal the fix should be landed in `ngx-formly-tabs` for now the only way to make it work is to set the parent as a `type` instead of `wrapper`.

- https://stackblitz.com/edit/ngx-formly-ui-bootstrap-component-injectors-v5-n9r5px
- Working example with `ngx-formly-tabs` https://codesandbox.io/s/angular-7-template-5zw4j?fontsize=14

**Comment by franzeal** [comment]
@aitboudad that works to an extent, certainly enough that I can address the issue on my end.  Wanting to keep the usage consistent, I was surprised to see that it won't work if I change both to types:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-component-injectors-v5-no-wrappers

**Comment by aitboudad** [comment]
I think I've got an idea to make it work, let me check it first :)

**Comment by aitboudad** [comment]
@franzeal in `5.2` version you can declare both as a type, component-level injectors for field type is now supported (only between field type components) so in `ngx-formly-tabs` the `TabsetService` provider should be declared in `FormlyFieldTabsetComponent` in order to work properly.

**Comment by franzeal** [comment]
@aitboudad I really appreciate it, thank you!
