### ISSUE TITLE
Extension not called in production mode.

### ISSUE THREAD

**Issue by silvl** [ngx-formly/ngx-formly#1624]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have a hooks extension whose job is to convert the hook function from strings to actually FormlyHookFn.  This is done during the prePopulate() method. This works fine during development build. However, if compile in production, the extension's method is never called.

**Expected behavior**
Work the same in production mode as development

**Minimal reproduction of the problem with instructions**
export const FieldHooksExtension: FormlyExtension = {
    prePopulate(field: FormlyFieldConfig) {
        try {            
            const toHookFunctions = (options: object = {}) => {
                let hookFns = {};
                _keys(options).forEach((option) => {
                    hookFns[option] = _isString(options[option])   ? Util.toFunction<FormlyHookFn>(options[option]) :
                                      _isFunction(options[option]) ? options[option] : null;
                });
                return hookFns;
            };   

            // Since we cannot store hook functions directly in our JSON, we will need to convert
            // strings to functions.
            field.hooks = toHookFunctions(field.hooks);
        } catch(e) {

        }
    },

    onPopulate(field: FormlyFieldConfig) {},
    postPopulate(field: FormlyFieldConfig) {}
  };

In the main module, it is then added as follows...
FormlyModule.forRoot({ 
      extensions: [
        {
          name: 'field-hooks',
          extension: FieldHooksExtension
        }
      ],  
     ... 
      

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 8.0

* **Browser:** all
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
I need a reproduction repo for this :pray:

**Comment by silvl** [comment]
I will try, but I need some time. I am in crunch time...

**Comment by silvl** [comment]
FormlyModule.forRoot is called only once. However, it is called in a custom angular library. The main application then imports that library module

**Comment by silvl** [comment]
It turns out that the extension was not properly being registered in production mode.

FormlyModule.forRoot({
    extensions: [{name: 'field-hooks', extension: FieldHooksExtension}],
    ...
})

HAD TO CHANGE:
    export const FieldHooksExtension: FormlyExtension = {
        prePopulate(field: FormlyFieldConfig) { ... }
    }

TO:
   export function prePopulateFieldHooks(field: FormlyFieldConfig) { ... }
   export const FieldHooksExtension: FormlyExtension = {
      prePopulate: prePopulateFieldHooks
   }

**Comment by juristr** [comment]
> FormlyModule.forRoot is called only once. However, it is called in a custom angular library.

Note,`forRoot` should always only be called in the `AppModule`. That's a common pattern in Angular and important to follow to avoid misbehavior 😃

**Comment by silvl** [comment]
NgxFormly was not imported into main app module directly; the main app only needs to import the custom angular library.

**Comment by aitboudad** [comment]
> HAD TO CHANGE:
export const FieldHooksExtension: FormlyExtension = {
prePopulate(field: FormlyFieldConfig) { ... }
}
TO:
export function prePopulateFieldHooks(field: FormlyFieldConfig) { ... }
export const FieldHooksExtension: FormlyExtension = {
prePopulate: prePopulateFieldHooks
}

or use the following way:
```ts
export function fieldHooksExtension(field: FormlyFieldConfig) {
  ..
}

@NgModule({
  imports: [
    FormlyModule.forRoot({
      extensions: [
        { name: 'field-hooks', extension: { prePopulate: fieldHooksExtension } },
      ],
    }),
  ]
})
```

that's an angular limitation which we hope the next ivy solve it!
