### ISSUE TITLE
Question: Typing response is really slow inside a form

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1629]
Hi,
I am opening a Material Dialog that renders a form. This technique is being used in all the app and all is working well.

Except today in a new dialog, there is slowness when typing inside the form fields. This dialog has different implementation than the rest but I made sure I didn't miss anything from the other implementation. 

This new dialog renders a `<form>` with `<formly-form>` component.

It has also the OnPush Strategy.

Can you please guide on what to debug in order to know the reason behind this behavior?

Thanks

**Comment by kenisteward** [comment]
Could you please give a demo repository or stackblitz with example?

**Comment by bhaidar** [comment]
@kenisteward That's really difficult in this case. That's why I am asking for hints on where to look in the source code.

**Comment by aitboudad** [comment]
Two main part that you can check else there is something wrong on your code:
* when using expression properties as we evaluate the expression during `ngDoCheck` (I'm thinking to provide an opt-in to eval only on model change). Comment on the following line https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/components/formly.form.ts#L68 and check if that fixes the issue.

* when using `repeat` field type check the following issue https://github.com/ngx-formly/ngx-formly/issues/1489#issuecomment-479651796

**Comment by aitboudad** [comment]
* avoid using `formly-form` inside field type

**Comment by bhaidar** [comment]
@aitboudad Thanks for your response.

What do you want me to do try exactly? comment out the line inside ngDoCheck? so I build the source code and reference it or how?

**Comment by aitboudad** [comment]
the easy way is to modify the source code through the `node_modules` else build the source code and use `npm link`.

**Comment by bhaidar** [comment]
@aitboudad Nothing changes after commenting out the line of code inside node_modules!

**Comment by aitboudad** [comment]
Then try one of the following ways :)

- try to provide a reproduction example
- or use google chrome performance profiler https://github.com/ngx-formly/ngx-formly/issues/1489#issuecomment-478718776
- or keep commenting you code app until you find what it is going wrong

**Comment by bhaidar** [comment]
Have a look at this diagram. Events (click, keypress, etc.) are taking a lot of time

![image](https://user-images.githubusercontent.com/1163421/59633171-91beed00-9154-11e9-93e3-9cbadd5217be.png)

I open a formly form inside a mat dialog and start typing in the input fields.

The form itself works fine outside the mat dialog. Although other forms work fine too inside a mat dialog.

**Comment by aitboudad** [comment]
can you upload the profiler as described in https://github.com/ngx-formly/ngx-formly/issues/1489#issuecomment-478718776

**Comment by bhaidar** [comment]
[Profile-20190617T231228.json.zip](https://github.com/ngx-formly/ngx-formly/files/3298682/Profile-20190617T231228.json.zip)

**Comment by aitboudad** [comment]
well I think the issue is not related to `formly`,
the slowness is caused by a `setTimeout` callback that is called whenever `keydown` event is triggered, the whole view is re-rendered (I think `AdminTableComponent`) which took ~1second for each `keydown`.

**Comment by bhaidar** [comment]
I cannot see any setTimeout in the source code except for the addon for formly when implementing matPrefix and matSuffix.

how were you able to read that info from the performance logs? I've never used them before.

**Comment by aitboudad** [comment]
**Hint**: when `formly` model change, the table list should be updated only after the dialog is closed else the `AdminTableComponent` will be rerendred on each trigger.

* Event: Keydown

![Selection_009](https://user-images.githubusercontent.com/1753742/59636623-ddb96400-914b-11e9-8d42-1f6ec0aadf2c.png)

**Comment by bhaidar** [comment]
@aitboudad Can you illustrate more plz?

**Comment by aitboudad** [comment]
just forget about `setTimeout`, the root cause of slowness is whenever an event (`Keydown`) is triggered some components are re-rendered that include `AdminTableComponent`.
start by commenting some part of your code until you find the component that caused that issue.
as from our side, we can't help much more than that without a reproduction example :pray:!

**Comment by bhaidar** [comment]
In fact, I have an ngFor that loops over an array and render an AdminTableComponent. For some reason, when the lists variable is defined as a getter on the component it was causing all this delay in response. When I moved the declaration to the ngOnInit, everything works smooth now!

**Comment by aitboudad** [comment]
Awesome, `getter` is called whenever zone.js trigger a check, so in case of it returning a new object each time, the view is re-rendered.

**Comment by bhaidar** [comment]
Amazing @aitboudad Glad to know this detail :-) Long Live formly :-)
