### ISSUE TITLE
Question on implementing  a custom event receiver/emitter in a Formly Field

### ISSUE THREAD

**Issue by idzer0lis** [ngx-formly/ngx-formly#1630]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```
Hei, I was wondering and headbanging to figure if its possible and how to implement _a custom event receiver/emitter. in a custom formly field_

My use case is not typical:
I am trying to integrate angular-material-upload into this library, but the question is general I guess.

I am defining a custom field containing the angular material upload:
````
// Custom Formly Field, I removed the clutter for clarity
@Component({
  selector: 'formly-field-file',
  template: `
    <input type="file"  [formlyAttributes]="field" [fileUploadInputFor]= "fileUploadQueue"/>
    <mat-file-upload-queue #fileUploadQueue>
      <mat-file-upload ... (onUpload)="fileUploaded($event)">
      </mat-file-upload>
    </mat-file-upload-queue>
  `,
})

export class FormlyFieldFile extends FieldType {
  @Output() onUploadChange = new EventEmitter();

  fileUploaded(event) {
    console.log('this works', event);
    this.onUploadChange.emit(event); // this I want to send further
  }
}

// I am using the field like this:
  fields: [
        {
          key: 'file',
          type: 'file',
          templateOptions: {
            onUploadChange: ($event) => console.log($event), // I need this
            change: (field, $event) => console.log($event), // works but does not contain the event that I need
          }
        },
// I also tried in my html template, could not succed.
<formly-form ... (onUploadChange)="iNeedThis($event)">
</formly-form>
````
I also tried ControlValueAccessor but I didnt really succeed, I dont really know how exactly or if its the right way to do it.
````
export class FileValueAccessor implements ControlValueAccessor {
  value: any;
  onUploadChange = () => { };


  writeValue(value) { }
  registerOnUploadChange(fn: any) { this.onUploadChange = fn; }
}
...
{
     key: 'file',
     type: 'file',
     templateOptions: {
        onUploadChange: ($event) => console.log($event), // Like this?
     }
}
````

Any suggestions or ideas? Mega thanks in advance!

**Comment by aitboudad** [comment]
```ts
  fileUploaded(event) {
    this.field.templateOptions.onUploadChange(event);
  }
```

**Comment by aitboudad** [comment]
pass that event through `templateOptions` and it should work :)

**Comment by Yagneshdxt** [comment]
> ```ts
>   fileUploaded(event) {
>     this.field.templateOptions.onUploadChange(event);
>   }
> ```

@aitboudad how will we achieve this in JSON form

**Comment by aitboudad** [comment]
@Yagneshdxt it depends on the use cases, the above solution can be done inside custom field type and doesn't rely on JSON form.

To apply some extra config that requires js you can try one of the following solutions:
- `expressionProperties`: https://formly.dev/examples/field-options/expression-properties
- use map function which you may check in https://formly.dev/examples/other/json-powered
- use custom extension which is a global way to adjust Formly field https://formly.dev/examples/advanced/i18n-alternative
