### ISSUE TITLE
Handling ng-invalid when integrating third party input component (ngx-select2)

### ISSUE THREAD

**Issue by devnull69** [ngx-formly/ngx-formly#1632]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

I have tried to integrate a third-party input component called ngx-select2. I can use the control outside of ngx-formly definitions.

First thing I did: I added a component called 'Select2TypeComponent' in order to handle the new type:
```typescript
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'formly-field-select2',
  template: `
    <l-select2 class="form-control" [data]="to.data" [options]="to.select2options" [disabled]="false" (valueChange)="valueChange($event)"></l-select2>
  `
})

export class Select2TypeComponent extends FieldType {
  valueChange(e) {
    this.field.templateOptions.valueChange(e);
  }
}
```

Of course, I also added the new type to my app.module.ts

```typescript
      types: [
        {
          name: 'mf-select',
          component: Select2TypeComponent,
          defaultOptions: {
            wrappers: ['form-field'],
            templateOptions: {
              "data": [],
              "select2options": {}
            }
          }
        }
      ]
```

I'm working with this field configuration for the new type:

```javascript
            {
               key: 'select2wert',
               type: 'mf-select',
               className: 'col-sm-4',
               templateOptions: {
                 label: "Bitte wählen",
                 data: [
                  { id: '0', text: '', value: '', flag: ''},
                  { id: '1', text: 'Dies ist a1', value: 'a1', flag: 'a' },
                  { id: '2', text: 'Dies ist b2', value: 'b2', flag: 'b' }
                 ],
                 required: true,
                 valueChange: (e) => {
                   this.model.select2wert = e.value;
                 }
               }
            }
```

First thing I noticed is that I had to implement the valueChange method inside of the configuration in order to set `this.model.select2wert` explicitly even though there is already the key property 'select2wert'. How can I prevent mentioning `this.model.select2wert` explicitly here?

Second, and more dominantly: How can I make sure that the form-control turns VALID (and TOUCHED and DIRTY) when selecting a value from the select2 box? You see that I set required to true, but this will always prevent the form from being submitted even though I selected a value from the select2 box.

**Please tell us about your environment:**
Windows, NPM

* **Angular version:** 8.X

* **Browser:** Chrome

* **Language:** TypeScript

* **Node (for AoT issues):** `node --version` = v12.4.0

**Comment by devnull69** [comment]
I managed to do it

Step 1: Remove the `valueChange` method from the formly field configuration
Step 2: Use `formControl.setValue()` to set the value for the field programmatically whenever the control value changes
Step 3: Use a `@ViewChild` to access the LSelect2Component by name `#myselect2`
Step 4: Set the initial model value to the select2 control from inside ngOnInit

```typescript
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';
import { OnInit, ViewChild } from '@angular/core';
import { LSelect2Component } from 'ngx-select2';

@Component({
  selector: 'formly-field-select2',
  template: `
    <l-select2 #myselect2 class="form-control" [data]="to.data" [options]="to.select2options" [disabled]="false"
     (valueChange)="valueChange($event)"></l-select2>
  `
})

export class Select2TypeComponent extends FieldType implements OnInit{
   @ViewChild("myselect2", {static: true}) myselect2: LSelect2Component;

   valueChange(e) {
      this.formControl.setValue(e.value);
   }

   ngOnInit() {
      const selectedEntry = this.to.data.filter(entry => entry.value == this.model[this.key])[0];
      this.myselect2.writeValue(selectedEntry);
   }
}
``` 

```javascript
            {
               key: 'select2wert',
               type: 'mf-select',
               className: 'col-sm-4',
               templateOptions: {
                 label: "Bitte wählen",
                 data: [
                  { id: '0', text: '', value: '', flag: ''},
                  { id: '1', text: 'Dies ist a1', value: 'a1', flag: 'a' },
                  { id: '2', text: 'Dies ist b2', value: 'b2', flag: 'b' }
                 ],
                 required: true
               }
            }
```

This automatically corrects the validation of the field and the form respectively

**Comment by kenisteward** [comment]
Thank you for posting your solution here! Much appreciated 👍
