### ISSUE TITLE
Ngx-Formly undefined with Angular 8

### ISSUE THREAD

**Issue by VladBozhinovski** [ngx-formly/ngx-formly#1633]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

I have updated my project that previous worked on Angular 6 to Angular 8 and now id doesnt work. I tried to look up for that particular error that happened but could not find anything. 

**Expected behavior**

Normal clean ngx formly form

**Minimal reproduction of the problem with instructions**

```
**FormlyForm.html:2 ERROR TypeError: Cannot read property 'insert' of undefined
    at FormlyField.renderField (ngx-formly-core.js:1024)
    at FormlyField.ngOnChanges (ngx-formly-core.js:995)
    at checkAndUpdateDirectiveInline (core.js:24499)
    at checkAndUpdateNodeInline (core.js:35163)
    at checkAndUpdateNode (core.js:35102)
    at debugCheckAndUpdateNode (core.js:36124)
    at debugCheckDirectivesFn (core.js:36067)
    at Object.eval [as updateDirectives] (FormlyForm.html:2)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:36055)
    at checkAndUpdateView (core.js:35067)**
```

**Please tell us about your environment:**
Windows 10, VsCode, Node.JS 12, TypeScript 3.4.5

* **Angular version:** 2.0.X

Angular 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

![Screenshot_4](https://user-images.githubusercontent.com/8876745/59831094-5a616380-9341-11e9-83b4-cac7f5151775.png)

**Comment by VladBozhinovski** [comment]
It wasn't exact problem with ngx-formly, but in case someone get this kind of error, when you create fieldComponent with ViewChild, you should use.
`@ViewChild('fieldComponent', { read: ViewContainerRef, static: true }) fieldComponent: ViewContainerRef;`

Im closing this issue.

**Comment by damsorian** [comment]
the problem is the **static** property, it should be **true**, not **false**

**Comment by aitboudad** [comment]
Added a message error in `5.3`, to clarify the missing `static` flag.
Thanks for reporting this :+1: !!!
