### ISSUE TITLE
Adding accesskey attribute to fields

### ISSUE THREAD

**Issue by princepc** [ngx-formly/ngx-formly#1634]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Expected behavior**
I'd like to be able to specify the accesskey attribute for formlyfields to allow for alt+accesskey to jump to a field.

Is there are a way to specify this in the form definition?

**What is the motivation / use case for changing the behavior?**
Enable easier navigation between form fields.

**Comment by aitboudad** [comment]
use `attributes` property:
```ts
templateOptions: {
  attributes: {
    accesskey: '...'
  }
}
```

**Comment by princepc** [comment]
Excellent thanks, is there somewhere this is documented?
I tried searching but didn't find it.

**Comment by aitboudad** [comment]
> is there somewhere this is documented?

we didn't yet give the doc what it deserves due to the lack of time but it's in our roadmap.
