### ISSUE TITLE
Custom Validation - Additional data from Injectable service

### ISSUE THREAD

**Issue by DolphinAlex** [ngx-formly/ngx-formly#1635]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Custom validators currently give access to FormControl and FormlyFieldConfig

**Expected behavior**
Is there a way to access external data from with in the custom validation functions, such as calling a function within a Service class

**Please tell us about your environment:**
Windows

* **Angular version:** 2.0.X
Angular v7

**Comment by TechMachineX** [comment]
Have a look at these, might help with what you are looking for

#1521
#1387

**Comment by aitboudad** [comment]
By passing `formly` config through providers you can inject the desired service as described in the above comment. hope that would help you :smiley:.

Thanks @TechMachineX!
