### ISSUE TITLE
Avoiding XSS when storing formly config.

### ISSUE THREAD

**Issue by DownGoat** [ngx-formly/ngx-formly#1636]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
We allow users to create forms on the frontend, which are serialized and stored, and later shown on some other page. Currently we are just serializing the fields (a list of `FormlyFieldConfig` objects), and then deserialize this on the page where we show the form. I'm wondering which of the properties are safe to serialize, and then deserialize without additional parsing. Are there any other properties than `expressionProperties` and `hideExpression` I need to strip out on the backend? I guess any property that has a function signature should be avoided, but is there anything else?

**Expected behavior**
Not get pwned.

**Minimal reproduction of the problem with instructions**
Alert gets executed.
```"expressionProperties": {"a": "alert('ngx-formly')"}```

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

**Comment by DownGoat** [comment]
Have also identified `FormlyTemplateOptions.attributes`.

Example:
```
"templateOptions": {
          .
          .
          .
          "attributes": {
	          	"oninput": "alert('ononline')"
	          }
        },
```

**Comment by aitboudad** [comment]
AFAIK those are the options that allow fn calls:
- expressionProperties
- hideExpression
- attributes
