### ISSUE TITLE
Loading different Formly forms within the same Angular component via click event

### ISSUE THREAD

**Issue by phillipe2002** [ngx-formly/ngx-formly#1638]
I've been searching around for a solution to load different ngx-formly forms via a click event. I have an application that provides a component list on the left and then each component's properties on the right. If you click a component, it's ngx-formly form loads (well that was the plan).

I'm using Angular and see that once you load a component, which includes the ngx-formly field and data configs, you're done for changing it on a click event (seemingly, not going to happen).

I thought I could use a modal window to load different forms via a route that posts a variable specifying which form configurations to load. This is a bit messy and not ideal. Preference is to load each form into a right-hand app panel.

Could you suggest, or know of, a solution for changing out the ngx-formly form, within a component, from a click event?

Thank you kindly for any help you can provide :-)

[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request

**Current behavior**
Trying to change forms via a click event. Unfortunately, it seems once a component loads, even if using a service for ngx-formly configuration, there is no way to switch out forms within the same component.

**Expected behavior**
Load an Angular component, generate a list with unique ids, click an item from the list which opens a corresponding ngx-formly form into a right-hand panel. 

**Minimal reproduction of the problem with instructions**

I have no specific publicly available example of this. It's more of a request or to be pointed in the right direction.

**What is the motivation / use case for changing the behavior?**

To enable a more dynamic application with minimal page refreshes.

* **Angular version:** 
7.x

* **Browser:** 
All

* **Language:** 
TypeScript

* **Node (for AoT issues):**
12

**Comment by kenisteward** [comment]
If you could setup a stackblitz with a minimal representation I can take a
look at this.

**Comment by phillipe2002** [comment]
OK, thank you. I'll try to setup by early next week.

**Comment by aitboudad** [comment]
just ensure to reset all `formly` inputs, here is a working example https://stackblitz.com/edit/angular-j9euue

**Comment by bappy004** [comment]
Hi @aitboudad , I tried the above approach; it works to some extent, but it does not fully release JS heap memory that it was using prior to the switch. So for example if when you loaded the first form, the heap memory increased by say 5MB, after you switch to another form (say this new form is just one input, so would not required more than a few hundred KB at most), the amount of decrease of the heap memory is just a fraction of the original form's occupied memory (typically ~3MB)So the heap memory keeps growing if you switch back and forth. I suspect this is a memory leak? Any suggestions in this regard?
Thanks for a very useful forms library. it works really well.

**Comment by aitboudad** [comment]
@bappy004 probably related to https://github.com/angular/angular/issues/20007, but I would love to investigate on that part when time permits. Could you please fill a new issue instead? Thanks!
