### ISSUE TITLE
Question: Is there a way to get a loaded event for formly after changing the fields

### ISSUE THREAD

**Issue by talamaska** [ngx-formly/ngx-formly#1640]
**I'm submitting a ** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
I change the fields and the models, dynamically, imagine a wizard which has one panel and inside it is a formly form. I generate the json on the fly and pass it to the formly. I'm not sure how to actually detect if the form have rendered after I change the fields.

**What is the motivation / use case for changing the behavior?**
I need to block the user interaction until the form have loaded.

**Please tell us about your environment:**
VS Code, Windows 10, Chrome 69

* **Angular version:** 7.3
I can't upgrade to latest Angular.

* **Language:** Typscript 3.2.2

**Comment by aitboudad** [comment]
there is no such event but I think it can be done using `ngZone`:
```ts
changeFields() {
    ...
    this.ngZone.onStable.asObservable().pipe(first())
      .subscribe(() => { ... });
}
```
