### ISSUE TITLE
Setting default values for all FormFieldConfig used

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1643]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

Is there a way to set default values to some properties on the FormlyFieldConfig so that I don't have to repeat them on fields?

Thanks

**Comment by aitboudad** [comment]
use custom extension

**Comment by aitboudad** [comment]
another way is to set `defaultValue` through the custom field type or `NgModule` declaration using `defaultOptions`:

1.  Custom field type: 
```ts
export class FormlyGroup extends FieldType {
  defaultOptions = {
    defaultValue: {},
  };
}
```

2.  `NgModule` declaration:
```ts
FormlyModule.forRoot({
  types: [{ 
    name: 'input',
    defaultOptions: { defaultValue: {} }       
  }],
}),
```

**Comment by SulaimanGit** [comment]
> another way is to set `defaultValue` through the custom field type or `NgModule` declaration using `defaultOptions`:
> 
> 1. Custom field type:
> 
> ```ts
> export class FormlyGroup extends FieldType {
>   defaultOptions = {
>     defaultValue: {},
>   };
> }
> ```
> 
> 1. `NgModule` declaration:
> 
> ```ts
> FormlyModule.forRoot({
>   types: [{ 
>     name: 'input',
>     defaultOptions: { defaultValue: {} }       
>   }],
> }),
> ```

can u please provide a example for this
