### ISSUE TITLE
Element change event is fired twice when using Angular Material

### ISSUE THREAD

**Issue by SnakeME** [ngx-formly/ngx-formly#1644]
```
[x ] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
A change event of an Formly element is fired twice when using Angular Material.

**Expected behavior**
The change event should only be fired once.

**Minimal reproduction of the problem with instructions**

change event is fired twice when using Formly with Material:
https://stackblitz.com/edit/angular-im45ub

If you use Formly with Bootstrap, the change event is only fired once:
https://stackblitz.com/edit/angular-kyerjg

I've already tried to stop the second event from firing with stopPropagation or preventDefault but without luck. Someone has an idea how to get the change event to be fired only once?

* **Angular version:** 8.X.X

* **Browser:** All

**Comment by SnakeME** [comment]
As a workaround I'm now subscribing to Form changes this way: 

myForm: FormGroup;
formattedMessage: string;

constructor(private formBuilder: FormBuilder) {}

ngOnInit() {
  this.myForm = this.formBuilder.group({
    name: '',
    email: '',
    message: ''
  });

  this.onChanges();
}

onChanges(): void {
  this.myForm.valueChanges.subscribe(val => {
    console.log(val);
  });
}

Or for specific form controls:

onChanges(): void {
  this.myForm.get('name').valueChanges.subscribe(val => {
    console.log(val);
  });
}

**Comment by aitboudad** [comment]
fixed in `5.2.0`
