### ISSUE TITLE
expressionProperties - Unexpected identifier

### ISSUE THREAD

**Issue by bhaidar** [ngx-formly/ngx-formly#1645]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
Hi,

I am trying to set some templateOptions values based on formState using Expression Properties. I get the "unexpected identifier" when I use inline expression. However, when using an arrow callback function it works fine.

Here's a [StackBlitz](https://stackblitz.com/angular/yjprpxeebvpx) to see it.

Appreciate checking it out.

Thanks

**Comment by aitboudad** [comment]
please provide a valid StackBlitz example :pray:

**Comment by bhaidar** [comment]
@aitboudad I must have pasted wrong URL :-)

I need to set `min` on a DatePicker based on `formState`.

https://stackblitz.com/angular/ybqpjakdajx

**Comment by aitboudad** [comment]
I need a full example to avoid wasting my energy :smile: please!

**Comment by bhaidar** [comment]
Hi @aitboudad I did above, check the url please: https://stackblitz.com/edit/angular-xufvhd-5vznry

**Comment by aitboudad** [comment]
set `today` in `formState`:
```ts
export class AppComponent {
  form = new FormGroup({});
  model: any = {};
  options: FormlyFormOptions = {
    formState: {
      limitDate: true,
      today: new Date()
    }
  };
  fields: FormlyFieldConfig[] = [
    {
      key: 'Datepicker',
      type: 'datepicker',
      templateOptions: {
        label: 'Datepicker',
        placeholder: 'Placeholder',
        description: 'Description',
        required: true,
        datepickerOptions: {}
      },
      expressionProperties: {
        'templateOptions.datepickerOptions.min': `formState.limitDate ? formState.today : null`
      }
    },
  ];
}
```
