### ISSUE TITLE
Drag and Drop - FieldGroup

### ISSUE THREAD

**Issue by VidhyaK29** [ngx-formly/ngx-formly#1647]
HI,

![Drag and Drop](https://user-images.githubusercontent.com/52420846/60721701-673ea380-9f4c-11e9-83b0-184d7d459c4a.PNG)
 
Is it possible to add drag and drop behavior for the fieldgroup in ngx-formly. I need to sort the whole fieldGroup with other.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1456#issuecomment-469894882

**Comment by VidhyaK29** [comment]
I have seen it. It seems to drag and drop each field within an array. But I need to drag and drop the whole field array( set of fields).  Need to change the sequence of one fieldarray to another fieldarray. Is it possible.

**Comment by aitboudad** [comment]
just apply the same for the repeat field, if I clearly understood your case
