### ISSUE TITLE
Select undefined defaultValue not working in IE

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ngx-formly/ngx-formly#1660]
I'm submitting a ... (check one with "x")
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[] support request

Current behavior
We want to set an observable select's value to undefined initially. It is working as expected in Chrome but not in IE. It is still setting the first index as default. Select dropdown's, options "defaultValue" and set undefined from model, both are not working in IE.
 
Expected behavior
Select's value should be set to undefined in IE too.

Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-bsc35c

Please tell us about your environment:
Angular Version - 7.0.0
ngx-formly - 5.2.0
Browser: Internet Explorer 11.0.130

**Comment by aitboudad** [comment]
the passed value is a string and not `undefined`, try with:

```ts
{
  key: 'candy',
  type: 'select',
  defaultValue: undefined,
  ...
}
```

**Comment by ShahanaFarooqui** [comment]
Thanks for the quick reply. 

We tried with and without quotes, both are not working in IE. Setting the value through model is also not working.

**Comment by aitboudad** [comment]
can you try with `null` value

**Comment by ShahanaFarooqui** [comment]
Null is also not working, tried model as well as defaultValue option.

**Comment by aitboudad** [comment]
Ok I'll check it on my side later

**Comment by aitboudad** [comment]
tested on IE and it seems working as expected, the only case that remains is when the passed model value doesn't match the list of passed options which is related to the following issue https://github.com/angular/angular/issues/10010.

but for `null` and `undefined` it should work.also please ensure you're using the latest version of formly `5.2.0` also I'm assuming that you're using formly bootstrap UI?

**Comment by ShahanaFarooqui** [comment]
Sorry, I tested it with Formly v5.0.0-rc.11 due to some confusion. It is working with v5.2.0. Thanks.
