### ISSUE TITLE
Need help dynamically generate fields based on data

### ISSUE THREAD

**Issue by pmariani** [ngx-formly/ngx-formly#1661]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
Hi there. 
I am trying to define a form based on data. I have one data structure for the form fields and another data structure for the data. I would like these data structures to be decoupled.

For example, the form defines 1 multicheckbox field, but the list of options is defined in the other structure.

I am running into issues trying to generate 1 field (select in this case) per element in the data. 

I have taken the approach to create a custom template and defining its onPopulate method. There I am able to update the fieldGroup and generate one field per element. 

First, is this the correct way to implement this?
Second, it seems that this approach breaks or bypasses evaluation of both hideExpression and expressionProperties. The latter in particular is an issue as I am relying on expressionProperties to pass my data to the form.

So, could you please show me how to achieve my goal?
Hopefully this makes sense, but I think the stackblitz will clarify.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-al1yza 

**Please tell us about your environment:**

* **Angular version:** 8.X

* **Browser:** all

* **Language:** TypeScript

**Comment by aitboudad** [comment]
Generate field type based on the data is not supported yet but on our roadmap.

- for `hideExpression` to target the main model use `formState` or parent field 
- for `expressionProperties`, you may need to track subfields changes anyway here is a working example but be careful as it relies on some internal API: see https://stackblitz.com/edit/angular-i29psx
