### ISSUE TITLE
JSCON Schema Reference and Schema Dependencies is not working in stalkblitz example

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1678]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

In Demo, link is given to stack blitz for JSON Schema Reference example and Schema Dependencies is not working as expected.

**Expected behavior**

JSON Schma -> References example
Your Stack blitz example is not showing any control except submit button 
but in Demo website it shows the all the control. 

JSON Schma -> Schema Dependencies example
As per my understanding, if user enter credit card, it should show billing_address control but it is not appearing.

**Minimal reprod uction of the problem with instructions**

JSON Schema -> References
https://stackblitz.com/angular/moypbyylmorl?file=src%2Fapp%2Fapp.component.ts

JSON Schema -> Schema Dependencies
https://stackblitz.com/angular/moypbyylmorl?file=src%2Fassets%2Fjson-schema%2Fschema_dependencies.json
The above link is your stackblitz example

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 8.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Google Chrome Version 75.0.3770.142 (Official Build) (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
those features should be part of the next release `5.3`, which should be released this week.

To get notified, use the watch button:
![Selection_005](https://user-images.githubusercontent.com/1753742/56688052-9b395500-66cf-11e9-9dd0-c296d1466973.png)
