### ISSUE TITLE
Add/Remove for FieldArrayType does not mark the form dirty.

### ISSUE THREAD

**Issue by Jascen** [ngx-formly/ngx-formly#1679]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
Adding/Removing records in a custom FieldArrayType does not mark the dirty flag.

**Expected behavior**
Any user-driven actions will mark a form dirty.  Per [Angular's #16370](https://github.com/angular/angular/issues/16370#issuecomment-326705308), it is the action's responsibility to call markAsDirty().

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-ferxhg

**What is the motivation / use case for changing the behavior?**
Every implementation of Field Array will have to override, call super, and then mark the form as dirty for both Add() and Remove().

**Comment by aitboudad** [comment]
added in [v5.5.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.0) and thanks for the suggestion!
