### ISSUE TITLE
Is there a way to replace formGroup with another one

### ISSUE THREAD

**Issue by talamaska** [ngx-formly/ngx-formly#1681]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

is there a way to just replace one fromGroup in the FormlyFieldConfig?
When doing reassignement I got error
```
const config = [].concat(this.fields);
config[0].fieldGroup[0].fieldGroup[index].fieldGroup = fields;
this.fields = config;
```

**Comment by aitboudad** [comment]
not clear to me, could you please provide a `stackblitz` example, to see what you're trying to achieve.
