### ISSUE TITLE
Optional repeating section generates empty object for non existing model property

### ISSUE THREAD

**Issue by aportolan** [ngx-formly/ngx-formly#1684]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```
**Current behavior**
Form not updating when repeating section array field doesn't exist in model

**Expected behavior**
Example has 1-N connection between Investor and investments:
```
 export interface Investor {
  name: string;
  surname: string;
  investments?: Investments;
}

export interface Investments {
  investmentName: string;
  investmentDate: Date;
  stockIdentifier: string;
}
```
Let's say I'm inserting new Investor that has 2 new Investments. If I want to switch to another investor that has no investments defined ('investments' field does not exist/is not serialized), form retains 'investments' values form the former Investor.
Only if Investments are explicitly set to empty array, form behaves as expected.

I'm not sure if this is desired behavior, but for the described case the repeating section should be reset

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-raxxnl?file=src%2Fapp%2Fapp.component.ts

1. Input name and surname
2. Add couple of investments
3. Press on 'Simulate server fetch next row'
4. Name and surname have changed but past users' investments are not removed (and are also added to model)

**Please tell us about your environment:**
I'm using:
@ngx-formly/core: "5.2.0"
@ngx-formly/material": "5.2.0"

**Comment by aitboudad** [comment]
Fixed in `5.3` version :smiley:, happy coding!!!
