### ISSUE TITLE
Select all option event in multi-select

### ISSUE THREAD

**Issue by erjimmmy** [ngx-formly/ngx-formly#1686]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
There is no event

**Expected behavior**
Something similar to change event
```javascript
 change: (field, $event) => {
            console.log($event.value);
          }
```

**What is the motivation / use case for changing the behavior?**
More flexibility

* **Angular version:** 
Angular 8.0.3

**Comment by aitboudad** [comment]
instead, rely on `formControl.valueChanges`: https://stackblitz.com/edit/angular-ayr4bs

**Comment by erjimmmy** [comment]
Thanks @aitboudad!
