### ISSUE TITLE
Textarea label doesn't float with prefilled model value

### ISSUE THREAD

**Issue by 4typen** [ngx-formly/ngx-formly#1688]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
After open a dialog with a formly-form inside, the label on the prefilled textarea does not float initially. But only if the other input-field has the type 'number'.

![grafik](https://user-images.githubusercontent.com/5257147/61808134-22b37300-ae3b-11e9-8187-128e8157aa84.png)

**Expected behavior**
Textarea-label is floating right after the dialog opens.

**Minimal reproduction of the problem with instructions**
See https://github.com/4typen/formly-textarea-bug

* **Browser:** Firefox (Tested in 68.0.1)

**Comment by aitboudad** [comment]
released in `5.4` version.
