### ISSUE TITLE
Strategy to add support for custom admin template

### ISSUE THREAD

**Issue by patran** [ngx-formly/ngx-formly#1689]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

What would be a good strategy to add support for a custom template such as the one below? Is there a list of "in order to port, do the following" ? Thank-you

https://wrappixel.com/demos/angular-admin-templates/material-angular/landingpage/index.html

**Comment by kenisteward** [comment]
@patran 
Please review the documentation here.  If you have any more questions let us know.

https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field

**Comment by kenisteward** [comment]
@aitboudad I noticed the docs can't be directly linked to can we fix this easily?  I assume it's a github redirect issue.

**Comment by aitboudad** [comment]
I'll check it!

**Comment by aitboudad** [comment]
the above link should work now.
