### ISSUE TITLE
MultiCheckbox in two grid columns

### ISSUE THREAD

**Issue by mehdi1802** [ngx-formly/ngx-formly#1690]
**I'm submitting a ...** 
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
In my form there is a checkbox group with 20 check boxes. type = 'multicheckbox' creates checkboxes next to each other.
![Screen Shot 2019-07-25 at 2 24 24 PM](https://user-images.githubusercontent.com/10376739/61910051-7334da00-aee8-11e9-826c-cc00a476b471.png)

**Expected behavior**
I want to divide the checkboxes in two columns. 
<img width="1198" alt="Screen Shot 2019-07-25 at 2 26 59 PM" src="https://user-images.githubusercontent.com/10376739/61910068-7af47e80-aee8-11e9-9b43-a262011a0245.png">

**Minimal reproduction of the problem with instructions**
Based on the angular material official document:
https://material.angular.io/components/grid-list/overview
I created a custom type and it is working as expected with text fields and other single items. 

But I cannot use it for 'multicheckbox' because it puts each fieldGroup into one cell. 

**Workaround/Solution?**
I can create a new custom type (for example 'multiCheckboxInGrid') and inside the loop put each checkbox in a mat-grid-tile but I was wondering if any easier way to achieve this

**Please tell us about your environment:**
Angular 7.2  - Angular Material 7.3.7

* **Angular version:**
7.2

* **Browser:** 
all

* **Language:** 
Typescript 3.2.4

* **Node (for AoT issues):** `node --version` =
10.15.3

**Comment by aitboudad** [comment]
> I was wondering if any easier way to achieve this

the easy way is to use CSS, check the following example https://stackblitz.com/edit/angular-wj7mme

```scss
formly-field-mat-multicheckbox {
  display: grid;
  grid-template-columns: auto auto;
  grid-gap: 10px;
  padding: 10px;
}
```
