### ISSUE TITLE
Limit number of repeat type fields that can be added

### ISSUE THREAD

**Issue by swillisstudio** [ngx-formly/ngx-formly#1692]
**I'm submitting a ...**
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Expected behavior**
Is there a way to limit the number of items that can be added using the repeat type? For instance, in the [example on stackblitz](https://stackblitz.com/angular/amnkljxkprd?file=src%2Fapp%2Fapp.component.ts) you can click the ADD button as many times as you want, but I would like to limit it so that only up to 3 items can be added.

**What is the motivation / use case for changing the behavior?**
Sometimes a form needs to be able to add a specific number of user details, etc.

**Comment by aitboudad** [comment]
pass an extra option `maxItems` which you may use to conditionally hide the add button, check the following example https://stackblitz.com/edit/angular-5hxuzd

**Comment by argupta23** [comment]
@samwilliscreative, @aitboudad 

Can you please clarify how this would work in a multi-field repeat scenario ?

Thanks

**Comment by aitboudad** [comment]
@argupta23 please fill a new issue with more details.
Thanks!

**Comment by caisys** [comment]
> pass an extra option `maxItems` which you may use to conditionally hide the add button, check the following example https://stackblitz.com/edit/angular-5hxuzd

With the latest version of typescript:

*ngIf="!to.maxItems || to.maxItems > field.fieldGroup.length"

generates an  error TS2532: Object is possibly 'undefined'.
Thanks

**Comment by caisys** [comment]
With the latest version of typescript the proposed solution generates an object possibly undefined error.

The following works:
*ngIf="!to.maxItems ||  $any(field?.fieldGroup).length < to.maxItems "

**Comment by aitboudad** [comment]
@caisys it should be fixed using optional chaining (`field?.fieldGroup?.length`) in [Angular 13.2](https://github.com/angular/angular/releases/tag/13.2.0)
