### ISSUE TITLE
Angular Ivy : ERROR TypeError: Cannot read property 'createComponent' of undefined

### ISSUE THREAD

**Issue by rahulbhooteshwar** [ngx-formly/ngx-formly#1693]
**I'm submitting a 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

With ***Angular Ivy*** enabled ngx-formly throws error at runtime as following:
```
core.js:4799 ERROR TypeError: Cannot read property 'createComponent' of undefined
    at FormlyField.createComponent (ngx-formly-core.js:1518)
    at ngx-formly-core.js:1506
    at Array.forEach (<anonymous>)
    at FormlyField.createFieldComponent (ngx-formly-core.js:1505)
    at FormlyField.ngOnInit (ngx-formly-core.js:1472)
    at callHook (core.js:2355)
    at callHooks (core.js:2319)
    at executeHooks (core.js:2270)
    at executePreOrderHooks (core.js:2242)
    at refreshDescendantViews (core.js:9156)
```

**Expected behavior**
It should work in regular fashion irrespective of Ivy enabled flag in Angular apps

**Minimal reproduction of the problem with instructions**
* Create a new Angular CLI app (with latest angular CLI)
* install @ngx-formly/bootstrap, @ngx-formly/core
* try to use formly in regular fashion using json

**What is the motivation / use case for changing the behavior?**
I am not sure if @ngx-formly/ivy compatible or not yet

* **Angular version:** 8.1.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =v10.15.3

**Comment by aitboudad** [comment]
the support should be landed in `v5.3`, expect a release within 1 or 2 weeks.

**Comment by rahulbhooteshwar** [comment]
@aitboudad Thanks a lot for the quick response & fix.

**Comment by rahulbhooteshwar** [comment]
> the support should be landed in `v5.4`, expect a release within 1 or 2 weeks.

@aitboudad is there date planned for v5.4 ? Eagerly waiting for enabling Ivy on my Angular app :-)

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/issues/1691#issuecomment-521261285

**Comment by aitboudad** [comment]
released in `5.4` version.

**Comment by intellix** [comment]
I believe this is only partially done. Still getting errors when trying to serve an app which consumes FormlyMaterial:

```
Uncaught TypeError: Cannot set property 'ngBaseDef' of undefined
```

If I do a search for ViewChild there's still many more instances without `{ static }` defined

**Comment by aitboudad** [comment]
I've missed that part 😄, tested only with `bootstrap-ui`

**Comment by aitboudad** [comment]
fixed by #1733

**Comment by intellix** [comment]
Awesome, any idea when a release can be created to use it? :) Think it's the last piece of the puzzy for Ivy for us

**Comment by aitboudad** [comment]
> Awesome, any idea when a release can be created to use it? :)

Today 😃!

**Comment by aitboudad** [comment]
@intellix you can give it a try now with `5.4.1` release.

**Comment by intellix** [comment]
Not sure if it's something particular to my setup but now I get:

```
ngx-formly-material-form-field.js:304 Uncaught TypeError: Cannot set property 'ngBaseDef' of undefined
    at ngx-formly-material-form-field.js:304
    at Module.../../node_modules/@ngx-formly/material/__ivy_ngcc__/fesm5/ngx-formly-material-form-field.js (ngx-formly-material-form-field.js:313)
    at __webpack_require__ (bootstrap:84)
    at Module.../../node_modules/@ngx-formly/material/__ivy_ngcc__/fesm5/ngx-formly-material.js (ngx-formly-material.js:1)
```

<img width="659" alt="Screenshot 2019-08-26 at 22 20 07" src="https://user-images.githubusercontent.com/1162531/63724559-ec10b400-c84f-11e9-9ece-f461217fe77f.png">

If I rename `FieldType$1` to `FieldType$$1` it works... no idea why it happens

My setup:
```
Angular CLI: 8.3.0
Node: 10.16.0
OS: darwin x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.1
@angular-devkit/build-angular      0.803.0
@angular-devkit/build-optimizer    0.803.0
@angular-devkit/build-webpack      0.803.0
@angular-devkit/core               8.3.0
@angular-devkit/schematics         8.1.1
@angular/cdk                       8.1.3
@angular/cli                       8.3.0
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.1.3
@angular/material-moment-adapter   8.1.3
@ngtools/webpack                   8.3.0
@nguniversal/common                8.1.1
@nguniversal/express-engine        8.1.1
@schematics/angular                8.1.1
@schematics/update                 0.803.0
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by aitboudad** [comment]
Seems an `ngcc` issue which should be reported in `angular` repo this only occurs for `es5` build,
passing `es2015` as `target` for `tsconfig.json` should works:

```patch
{
  "compilerOptions": {
--    "target": "es5",
++    "target": "es2015",
  },
}
```

\cc @JoostK @petebacondarwin
