### ISSUE TITLE
Disable doesn't work when multiple fields have the same key

### ISSUE THREAD

**Issue by IdanE** [ngx-formly/ngx-formly#1700]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When having multiple fields with the same key in a single form, if you attempt to disable the form only the last field with the same key will be correctly disabled, even if the other fields are hidden.

**Expected behavior**
All fields with the same key should react to the changes

**Minimal reproduction of the problem with instructions**
****
Stackblitz: https://stackblitz.com/edit/formly-duplicate-key-issue
Using the provided Stackblitz, I've added a 'Type' dropdown that changes the visible field for the `param1` key. When disabling the form, only the second field with `param1` reacts to it, whereas the first remains enabled.

**What is the motivation / use case for changing the behavior?**
My use case for this is a field which is saved in a generic column but may have multiple types. In the form, this may translate into different types of controls. These different fields may also have different validations, and different `expressionProperties`. I don't want/care about model synchronisation across these inputs, and only want them to control their templateOptions independently.

**Comment by kenisteward** [comment]
@aitboudad is there any merit to allowing the synchronization of data? I'm thinking for if/then/else in jsonschema

**Comment by aitboudad** [comment]
@kenisteward already covered by `formly`, when the hidden field is shown we assign the model value to the attached field.

**Comment by aitboudad** [comment]
[v5.5.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.2) is released which includes a fix for this issue!
