### ISSUE TITLE
Add to formly-field custom elements

### ISSUE THREAD

**Issue by Nexeuz** [ngx-formly/ngx-formly#1702]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

I need customize my MatNativeSelect that is in fieldGroup, I need  mat-spinner in its label, 
for figure out   I send the Observable via templateOptions in  my fieldGroup dictionary, but when I try to retrieve that  Observable in my wrapperComponent vía {{ to.observable }} the key only be applies for the whole FieldGroup not for the formly-wrapper-mat-form-field  as I need.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.8

* **Browser:** [all  ]

* **Language:** [all]

**Comment by aitboudad** [comment]
Hi, can you replicate your example using `stackblitz` in order to have a clear idea of the issue, here is a starter one https://stackblitz.com/angular/yggqbdbmynn?file=src%2Fapp%2Fapp.component.ts

Thanks!
