### ISSUE TITLE
Material Select field floating label bug when using appearance

### ISSUE THREAD

**Issue by ramarivera** [ngx-formly/ngx-formly#1703]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
I am using a Material Select field, but when no option has been select and no value has been provided to the form, the floating label for the select field appears on top. This is when using appearance outline.

**Expected behavior**

When the field has not been touched, and no value has been provided thro the model, the label should not be floating.

**Minimal reproduction of the problem with instructions**

For a repro stackblitz go to: https://stackblitz.com/edit/angular-qwenyx.
There there is a bare `mat-select` with outline appearance and a ngx-formly mat select.

**What is the motivation / use case for changing the behavior?**

I would like all my form fields to look the same when the form is untouched

**Please tell us about your environment:**

Latest windows 10 build.

* **Angular version:** 8.0.X

* **Browser:** [Chrome  75.0.3770.142 | Firefox 68.01 | ]
Have not tested all the browsers

* **Language:** [TypeScript ]

**Comment by ramarivera** [comment]
Btw, if someone could point me in the direction of the issue I would be more than happy to send a PR your way

**Comment by aitboudad** [comment]
already fixed yesterday, maybe next time :)!
