### ISSUE TITLE
Create dymanic  array inputs with data

### ISSUE THREAD

**Issue by oLejikOnMyEvent** [ngx-formly/ngx-formly#1704]
Hello. Sorry, I 3 days tried do it, but without success.
I have 1 select element. Through This selector user choice data from server, and every choice, different data user get in page. But I have i problem with dynamic data. How I can generate dynamic form with ngx  formly and post object to server, can u help me ?

[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**
[https://stackblitz.com/edit/angular-hnvhr3](url)

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
use repeat type, https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section

**Comment by sudharsan203** [comment]
How can show repeated fields on view 

> use repeat type, https://ngx-formly.github.io/ngx-formly/examples/advanced/repeating-section

How can I show repeated fields on view after submit?

**Comment by aitboudad** [comment]
@sudharsan203 the question is not clear, please elaborate!
