### ISSUE TITLE
Listbox with checkbox and multi selection

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1705]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[* ] feature request
[ ] support request
```

**Current behavior**

I could not find list box control in any of your example.

**Expected behavior**

I need list box with check box and multi selection option.
In addition, on selection event, I should able to call API and bind the response to another list box

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

This feature is not available in the component

**Please tell us about your environment:**

I would like dynamically generate the form with JSON Schema and model
* **Angular version:** 8.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
actually, there is a type for multi-selection named `multicheckbox`:
```ts
    {
      key: 'multicheckbox',
      type: 'multicheckbox',
      templateOptions: {
        options: [
          { value: 1, label: 'Option 1' },
          { value: 2, label: 'Option 2' },
        ],
      },
    },
```

by  default, the model value is an object, if you want to an array of selected options check https://github.com/ngx-formly/ngx-formly/issues/1599#issuecomment-496222890
