### ISSUE TITLE
How to add third party control instead of default control

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1706]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[* ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**

I would like to use third party control instead of default control.
For instance,
i) instead of default check box, prefer to use switch
ii)instead of default HTML 5 Date control, prefer to use third part date component.
iii)instead of default File upload, prefer to use third party File Upload control.
In addition, Would like to know list of control this component support.
and also provide, how to extend new/third party control.
similarly, how to customize the CSS for the form level, control level and individual control with name/etc.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I would like to use the control that is better than default control.
For instance, 
1)we prefer switch for check box 
2)we prefer bootstrap date control instead of HTML 5
3) we may need to customize the css form level, type of control, individual control with name, etc

**Please tell us about your environment:**

Windows 10
* **Angular version:** 2.0.X

Angular 8.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript
* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
see https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field
