### ISSUE TITLE
The Field required message is not shown

### ISSUE THREAD

**Issue by SudeshAK** [ngx-formly/ngx-formly#1708]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```
In the example given at
https://ngx-formly.github.io/ngx-formly/examples/bootstrap-specific/bootstrap-horizontal
'The field is required' message is not shown only the border is becoming red

**Comment by aitboudad** [comment]
the message should be declared through `NgModule` config:

```ts
    FormlyModule.forRoot({
      validationMessages: [
        { name: 'required', message: 'This field is required' },
      ],
    }),
```

you may check the validations demo example https://ngx-formly.github.io/ngx-formly/examples/validation/built-in-validations

**Comment by SudeshAK** [comment]
Its not displaying in the formly example itself
https://ngx-formly.github.io/ngx-formly/examples/bootstrap-specific/bootstrap-horizontal
though it is declared in NgModule..

**Comment by kenisteward** [comment]
This is intended.

By default the bootstrap module has a wrapper defined that I corporates the
validation messages for form-fields. You can see this working in the
introduction example.

https://ngx-formly.github.io/ngx-formly/examples/introduction

The example you are looking at used an implementation of a different
wrapper that does not implement showing the validation messages.
@aitboudad please confirm.

We may want to update the example to be more clear.

**Comment by aitboudad** [comment]
the doc example should be updated, the wrapper `'form-field-horizontal'` should replace the default wrapper ([form-field](https://github.com/ngx-formly/ngx-formly/blob/v5/src/bootstrap/src/lib/wrappers/form-field.wrapper.ts)).

the missing parts are `description` and `validation`:

```ts
      <div *ngIf="showError" class="invalid-feedback" [style.display]="'block'">
        <formly-validation-message [field]="field"></formly-validation-message>
      </div>
      <small *ngIf="to.description" class="form-text text-muted">{{ to.description }}</small>
```

**Comment by SudeshAK** [comment]
Thank you ..
