### ISSUE TITLE
How to get a nested object property for LabelProp

### ISSUE THREAD

**Issue by Nexeuz** [ngx-formly/ngx-formly#1709]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

I need to get a deep object key of my API response for templateOptions.labelProp
[Select options with nested keys](https://stackblitz.com/edit/angular-bbt25z
)
**Minimal reproduction of the problem with instructions**

Try to get a nested object key in select options for paint that in a select label. it doesn't possible 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
pass `labelProp` as a function:

```ts
labelProp: p => p.Name.prueba
```
