### ISSUE TITLE
Custom css for input control

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1710]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[* ] feature request
[ ] support request
```

**Current behavior**

as per UI framework controls are appearing.
Please let me know if I want to change all input control behavior or one specific input control, How do I do?

**Expected behavior**

I would  like customize the CSS for Application level, Page level, input control by type level, input control by name.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

In addition to UI framework, We may need to change text box width, height, border,font,color etc. application level, page level, control  level by type and control level by name.

**Please tell us about your environment:**

Windows 10
* **Angular version:** 8.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript X.X |
* **Node (for AoT issues):** `node --version` =

**Comment by kenisteward** [comment]
This sounds like you need to implement a separate framework that works with
firmly

Instructions for that are here

https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field

**Comment by Rajanusa** [comment]
Hi kenisteward,

Thanks for the response.
I don't want to implement separate framework but want to apply some css/style to primeNG controls.
some time conditionally add css/style.

Thanks
Raj

**Comment by aitboudad** [comment]
Here are some options that you may use to customize the css/style:

- `className`: which will be applied to the root selector of the field (`formly-field`):
```ts
{
  key: 'name',
  className: 'custom-class'
}
```
- `attributes`: which allow rendering extra attributes to the input selector (`input`, `select` ...):
```ts
templateOptions: {
  attributes: {
    class:  'custom-input-class'
  }
}
```
