### ISSUE TITLE
Add type `hidden` to add value to the form without adding it to the DOM

### ISSUE THREAD

**Issue by jfcere** [ngx-formly/ngx-formly#1711]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**

Currently, the only way to include a value to the form that should not appear visually to the user (for example an `id` field which is the primary key) is by adding a hidden input so.

But doing so, with the following field configuration, the `id` input is still added to the DOM but is hidden with `display: none`:

```javascript
{
  key: 'id',
  type: 'input',
  hide: true,
}
```

**Expected behavior**

I was hoping for a type `hidden` that would add the property to the form without adding anything to the DOM.

```javascript
{
  key: 'id',
  type: 'hidden'
}
```

**Minimal reproduction of the problem with instructions**

Example available where `id` property is submitted with the form using...
- ngx-formly `id` input hidden
- reactive-form `id` not part of the DOM but added to form

See stackblitz here: https://stackblitz.com/edit/ngx-formly-issue-1711

**What is the motivation / use case for changing the behavior?**

Follow Angular's best practices by not putting in the DOM something that is not needed as Angular will still process the bindings and change detection on it.

**Please tell us about your environment:**

* **Angular version:** 8.2.0

* **Browser:** All

* **Language:** All

* **Node (for AoT issues):** `node --version` = 10.16.0

**Comment by aitboudad** [comment]
defining the `id` in the initial model should be enough or a field with a key with empty type:

```ts
{ key: 'id' }
```

**Comment by aitboudad** [comment]
right now the only missing part is generation the `formControl` when a field has no `type` which I think it may be useful in somecases.

you can even pass a `defaultValue` :)

```ts
{ key: 'id', defaultValue: '123' }
```

**Comment by jfcere** [comment]
@aitboudad you are right it works: https://stackblitz.com/edit/ngx-formly-issue-1711-notype

Would you find it more consistent to have an `hidden` property?
If so, I can maybe give it a try otherwise I guess this issue can be closed.

Respect :metal:

**Comment by aitboudad** [comment]
if you want to have a hidden filed in the dom, I think it's possible https://stackblitz.com/edit/angular-v7hkae:
```ts
{
  key: 'id',
  type: 'input',
  templateOptions: { type: 'hidden' }
}
```

**Comment by jfcere** [comment]
Sorry maybe I was not clear... I meant instead of not adding the `type` property would you find it more consistent to have a possible `hidden` value to `type` property...

```javascript
// what works currently to add a value to the form
// without generating any element in the DOM
{
  key: 'id'
}

// what it could be to have a `type` value `hidden`
// for the same use-case (maybe more consistent, but its a matter of opinion)
{
  key: 'id',
  type: 'hidden'
}
```

But I can see this could bring some confusion with the `hide` property that add the element to the DOM but apply `display: none` on it.

**Comment by aitboudad** [comment]
> after all if there is no type it works as intended, so I have no problem with closing the issue if there is no place for improvement.

right type `hidden` can be omitted with the above proposal (no type = hidden)
the `hide` property has a different purpose when passing `true` the field is detached from the root `form`

**Comment by jfcere** [comment]
All good, thanks for your help and nice work on the library!

**Comment by jfcere** [comment]
I might have been to fast on the trigger, if I don't specify the `type` property the value will be part of the `model` (of course) but not part of `form.value` because no `FormControl` is generated.

**Comment by aitboudad** [comment]
yep, I'll check it later https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/extensions/field-form/field-form.ts#L15

**Comment by aitboudad** [comment]
released in `5.4` version.

**Comment by jfcere** [comment]
@aitboudad thanks for the fix and the follow-up!

**Comment by Presar** [comment]
> if you want to have a hidden filed in the dom, I think it's possible https://stackblitz.com/edit/angular-v7hkae:
> 
> ```ts
> {
>   key: 'id',
>   type: 'input',
>   templateOptions: { type: 'hidden' }
> }
> ```

This works for bootstrap, but not work for angular material.

**Comment by aitboudad** [comment]
@Presar omitting the `type` property would be enough to have a hidden field: `{ key: 'id' }`
