### ISSUE TITLE
Generate form from Model with Array and Objects

### ISSUE THREAD

**Issue by crackjack** [ngx-formly/ngx-formly#1712]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[x] support request
```

**Current behavior**
I am trying to generate the form using a Model. But my Model has fields that are of another Model type and also has fields that are same Model type. I'm having challenges in going beyond 1 level of array.

Eg:

`export class Variant {
    year: number;
    color?: string;
} 

export class Car { 
    brand: string;
    model: string;
    variants: Variant[];
    similar: Car[];
}`

Now to generate something that is formly friendly I would have to do a little initialization and conversion like in the stackblitz here: https://angular-p5rqay-rlf4zh.stackblitz.io

I am having trouble in getting the objects recursively and generate the form for child objects in the similar cars object.

**Expected behavior**
This is not a bug. It is rather a question or support request if something like this has been achieved or can be achieved easily.

**Minimal reproduction of the problem with instructions**

Example: https://angular-p5rqay-rlf4zh.stackblitz.io

UI Material: https://stackblitz.com/edit/ngx-formly-ui-material

**What is the motivation / use case for changing the behavior?**
If something like this can be achieved, it will be possible to generate fields based on the model, optional fields can be honored and type can be converted to some extent.

**Please tell us about your environment:**
MacOS HighSeierra, VSCode

* **Angular version:** 7.xx

* **Browser:** [all | Chrome XX |] Only tried in Chrome, should not matter for this case

* **Language:** TypeScript | ES5]

**Comment by aitboudad** [comment]
that's on the plan :) but not soon!
I'll try to provide you an example when time allows, we've done a similar feature in `json-schema` for a recursive array: https://angular-12fcs4.stackblitz.io/

**Comment by crackjack** [comment]
oh, okay. good to know that it is on the plan. about the example, is it the same as the json-schema link you shared or is there anything else?

if there is a branch somewhere or a work in progress, I could help bringing it to a certain level if I can. I don't know what you think about it. But I'm not 100% that I can actually make a difference.

**Comment by aitboudad** [comment]
here is an example of recursive repeat type: https://stackblitz.com/edit/angular-rhagg9 which you may use.

>  is it the same as the json-schema link you shared or is there anything else?

yes, part of https://ngx-formly.github.io/ngx-formly/examples/advanced/json-schema

> if there is a branch somewhere or a work in progress

right now still an experimental feature which is only implemented for `json-schema` extension.

**Comment by intellix** [comment]
is it possible to do recursion with FieldGroup instead? Have tried but seems to trigger: **Maximum call stack size exceeded**.

**Comment by aitboudad** [comment]
fill a new issue with an example of what you want to achieve.

**Comment by intellix** [comment]
Created: https://github.com/ngx-formly/ngx-formly/issues/1882
