### ISSUE TITLE
Load Ngx-Formly JSON (build-in-validation example) Schema from file instead of hard coding in component

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1713]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[* ] support request
```

**Current behavior**

I would like to load ngx-formly-json schema from file.
I tested norm JSON schema from file with pattern validation, it is working.
When I load build-in-validation formly JSON schema from file, all validation is not happening.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

we need to load formly json schema from file, 
In real scenario, API would return this formly json schema.

**Please tell us about your environment:**

Windows 10
* **Angular version:** 8.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript
* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
could you please provide a reproduction example, our demo uses an Http call to get the `json-schema` file and it seems working as expected https://ngx-formly.github.io/ngx-formly/examples/advanced/json-schema

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad ,

Thanks for timely response.
Please find the stackblitz [link](https://stackblitz.com/edit/angular-ngx-formly-jsonschema-file)

Thanks
Raj

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad, 

It is working when schema is JSON standard.
if I try schema in "FormlyFieldConfig" compatible and  read from file, I am facing issue since I store "FormlyFieldConfig" type json to file. your own JSON key is not string ie within double quotes.
I am keep both key and value of your build-in-validation is causing problem.

Please help me storing your "FormlyFieldConfig" schema format in json file and read from there.

Thanks
Raj

**Comment by Rajanusa** [comment]
> could you please provide a reproduction example, our demo uses an Http call to get the `json-schema` file and it seems working as expected https://ngx-formly.github.io/ngx-formly/examples/advanced/json-schema

[stakcblitz](https://stackblitz.com/edit/angular-ngx-formly-jsonschema-file)

**Comment by aitboudad** [comment]
passing `validator` as a function is not supported instead it should be declared throughout `NgModule` declaration. You may check our demo example https://ngx-formly.github.io/ngx-formly/examples/validation/validation-message
