### ISSUE TITLE
Form is not dirty when multicheckbox field is modified

### ISSUE THREAD

**Issue by goosmurf** [ngx-formly/ngx-formly#1721]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Modifying a multicheckbox field doesn't cause the form to be marked as dirty.

**Expected behavior**
Modifying a multicheckbox field should cause the form to be dirty.

**Minimal reproduction of the problem with instructions**
See https://ngx-formly-multicheckbox-dirty.stackblitz.io

Checking any of the multicheckbox options doesn't change the form to dirty, whereas if you enter anything into the text input the form is marked dirty.

Note that the Submit button has [disabled]="!form.dirty", i.e. it should become enabled if multicheckbox worked as expected.

* **Angular version:** 8.2.0 (current latest)
* **ngx-formly version:** 5.3.0

**Comment by goosmurf** [comment]
Many thanks for the quick turnaround!

**Comment by aitboudad** [comment]
released in `5.4` version.

**Comment by geert-put** [comment]
This problem still seems to exist. 
using ngx-formly/core 5.8.0

**Comment by aitboudad** [comment]
@geert-put try with the latest version of Formly which is `v5.9.3`.

**Comment by geert-put** [comment]
This does seem to work correctly with the latest version. Many thanks.

**Comment by aitboudad** [comment]
Then could you please fill a new issue with a reproduction example :pray:!

**Comment by snekku-dev** [comment]
Hi, I was noticing that the problem seems to be back (I am using 5.12.0). I was thinking if maybe adding a markAsDirty() inside the bootstrap multicheckbox onChange function could solve the issue since patchValue apparently doesn't mark the control as dirty

```typescript
onChange(value: any, checked: boolean) {
    if (this.props.type === 'array') {
      this.formControl.patchValue(
        checked
          ? [...(this.formControl.value || []), value]
          : [...(this.formControl.value || [])].filter((o) => o !== value),
      );
    } else {
      this.formControl.patchValue({ ...this.formControl.value, [value]: checked });
    }
    this.formControl.markAsTouched();
    //  this.formControl.markAsDirty(); // would add this
  }
  ```

**Comment by aitboudad** [comment]
@snekku-dev please open a new issue with a reproduction example.
Thanks!
