### ISSUE TITLE
Disable gets lost with FieldArrayType when model is loaded

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1722]
```
[x] bug report
```

**Current behavior**
When the model changes and the number of array items changes the disabled property is reset (false).

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-yg1gif-bamsxg?file=src/app/app.component.html

The FieldArraytype is initially set to disable (true). Klick "Load Model", the disable property is now false.

**Motivation**
I wanted to use this field property to use expressionProperties on the array items as described in #1528, but as the property gets reset I can not go this way
```
   prePopulate(field: FormlyFieldConfig) {
       field.fieldArray.fieldGroup.map((f, index) => {
         f.expressionProperties = {
           ...(f.expressionProperties || {}),
           'templateOptions.disabled': 'field.parent.templateOptions.disabled',  // still have to check if this is correct
         };
       });
   }
```

**Related issues**
#1528
Maybe this is the source of the problem which then causes the issue in #1528.

**Comment by aitboudad** [comment]
Probably related to #1528 which require a noticeable work to properly fix it :), anyway I'd give it a second attempt to see if I can figure out an easy fix.

**Comment by aitboudad** [comment]
close in favor of #1743

**Comment by FritzHerbers** [comment]
Works as aspected with v5.5.6. Thanks a lot.
