### ISSUE TITLE
Question: How to set label name and its label type(input/ text)horizontally in UI

### ISSUE THREAD

**Issue by RollsBean** [ngx-formly/ngx-formly#1723]
Question: How to set  label name and its label type(input/ **select**)horizontally in UI, i read docs in [https://ngx-formly.github.io](https://ngx-formly.github.io/ngx-formly/guide/properties-options), i saw all label is vertical layout, for example [!formly ui bootstrap!](https://ngx-formly.github.io/ngx-formly/ui/bootstrap), how can i put label name and label to one line not two line?
I'm a beginner of formly, don't know how to implement it.

**Current behavior**
label name and label itself show in one line

**Expected behavior**
label name and label itself show in two line

**Please tell us about your environment:**
Win10 Webstorm 

* **Angular version:** Angular 7

* **Browser:**
Chrome

**Comment by aitboudad** [comment]
see https://ngx-formly.github.io/ngx-formly/examples/bootstrap-specific/bootstrap-horizontal
