### ISSUE TITLE
How to prevent duplicate saving in database using multi step form in ngx-formly

### ISSUE THREAD

**Issue by Mayank0311** [ngx-formly/ngx-formly#1724]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**
I have created data entry form using multi step control in ngx-formly. As per the business requirement, I have insert/update data on every NEXT button click when user navigates to another step. If user comes back to previous page and they have not update any data, I am still calling the API to save records.

**Expected behavior**
1) Is there any way I can prevent the API call if user has not updated any entry in the form ?
2) If user has updated the entry then I should call the UPDATE API to update the records ?
3)  I have multiple forms so I am looking for a single function that can do this validation and returns Boolean value.

**Minimal reproduction of the problem with instructions**
Please let me know in case you need a demo to produce the issue.

**What is the motivation / use case for changing the behavior?**
As per the business requirement.

**Please tell us about your environment:**
Operating system: Windows 7, IDE: VS Code, package manager: NPM, HTTP serve: AWS,

* **Angular version:** 2.0.X
Angular 7

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All browsers

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] = all

* **Node (for AoT issues):** `node --version` = v8.11.3

**Comment by LucasJAlba** [comment]
There are 2 ways:

1. You can capture the navigation event then prevent the API call.
2. You can check if the form in context is dirty or pristine.
