### ISSUE TITLE
Apply over-all layout to formly

### ISSUE THREAD

**Issue by flobiber** [ngx-formly/ngx-formly#1726]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

The generate an overall layout for formly i have to wrap formly by another component like that: 

```
        <div class="ui-fluid">
            <div class="ui-g">
                <div class="ui-g-12">

                   <formly-form [form]="form" [fields]="fields" [model]="model"></formly-form>

                </div>
            </div>
        </div>
```

**Expected behavior**

Is there a possibility to do that without wrapping the formly-form? 

* **Angular version:** 7.X.X

**Comment by aitboudad** [comment]
That could be done using custom field wrapper or type, to have an idea check our example of `flex-layout` integration: https://stackblitz.com/edit/ngx-formly-flex-layout
