### ISSUE TITLE
ControlValueAccessor methods not called

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1731]
```
[x] support request
```

**Current behavior**
Wanted to expand the ag-grid example to allow adding rows. Because ag-grid does not detect model changes, I wanted to solve it with ControlValueAccessor, however the interface methods are not called, any reasons why?

Instead of using the ControlValueAccessor I could solve the issue by calling the ag-grid API to reflect model changes within FieldArrayType.Add().

Just want to understand why my ControlValueAccessor implementation does not work.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-tz9xq9?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
Angular reactive form requires binding `[formControl]` in order to match `ControlValueAccessor` implementation. AFAIK there is no way to trigger a directive dynamically.

An example of `ControlValueAccessor` implementation can be found in https://ngx-formly.github.io/ngx-formly/examples/other/input-file

**Comment by aitboudad** [comment]
I've got an idea that possibly would make it work, I'll explore that while working on `V6`.

**Comment by kurtnagel** [comment]
Any progress on this?  We are running into an issue where we have created a custom component that contains mat-tree and mat-input and we get to/from the model nor can we register the ControlValueAcessor.  Formly generates it's own formControlName, which does not match the @Component provider for the ControlValueAccessor.

**Comment by aitboudad** [comment]
@kurtnagel your issue not related to this I guess, could you please fill a new one with a `stackblitz` example of what you've done.

**Comment by FritzHerbers** [comment]
@aitboudad 
I was reading https://indepth.dev/posts/1143/a-thorough-exploration-of-angular-forms:
> Only FormControl instances can 'directly' interact with a ControlValueAccessor, because, in a tree of AbstractControls, a FormControl can only be the leaf node as it is not supposed to contain other nodes. Along these lines, we can deduce that updates that come from the view will start from leaf nodes.

Does the above imply, that a ControlValueAccessor is only possible on a FieldType and not on a FieldArrayType ?

`export class GridTypeComponent extends FieldArrayType implements ControlValueAccessor`

**Comment by aitboudad** [comment]
I think so

**Comment by aitboudad** [comment]
I've decided to not go in that direction, for now, our approach is better and easy than `ControlValueAccessor`, maybe in the future but can't guarantee.
