### ISSUE TITLE
Allow <ion-item> to take  lines="none"

### ISSUE THREAD

**Issue by ols87** [ngx-formly/ngx-formly#1732]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

**Current behavior**
There is no way to set lines="none" on the form field wrapper ion-item. This makes it ridiculously hard to style inputs with custom css because of Ionic 4 shadow DOM. I'm forced to use the awful default ionic styles.

**Expected behavior**
A simple template option such as "itemLines" would be perfect.

![ngx-formly](https://user-images.githubusercontent.com/39114128/63317995-1f7aac80-c33f-11e9-8cfd-395b62c339c7.png)

**Comment by aitboudad** [comment]
added in [v5.5.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.0), through `itemLines` option:

```ts
{
  key: 'name',
  type: 'input',
  templateOptions: {
    itemLines: 'none',
  },
},
```
