### ISSUE TITLE
How to pass model for multiple Tab Form that has identical control for each tab

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1734]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I have created tab using your tab example. but do not know how to pass model data when it has identical control name in multiple tab.

**Expected behavior**

I should be able to pass different data for each tab, though it ha identical control name.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-1xyxbv
I have 3 tab (client1, client 2 and client3)
Each has same set of controls. if I pass model object, it bind the same data to all tabs.
I would like to know, how to pass model for each tab.

**What is the motivation / use case for changing the behavior?**

A form has multiple tab and each tab has same set of controls and control's name. if I pass model as object, it bind the same data to all tab but I wan to pass different data for each tab.

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

Angular 8.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
here is another approach which uses custom field type https://stackblitz.com/edit/angular-yu7bzv-bcmfip

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad,

Thanks for the timely response.

Thanks
Raj

**Comment by aitboudad** [comment]
> Can I use fieldGroup instead field in the TAB JSON?

can you elaborate, please!

**Comment by Rajanusa** [comment]
> > Can I use fieldGroup instead field in the TAB JSON?
> 
> can you elaborate, please!

I have use case where form has multiple Tab / Accordion. 
Each Tab/Accordion would have same set of user control  or may have  some extra control.
We are passing model object to set the default values 
  model = {"firstname":"client nane1", "age":25};''
[https://stackblitz.com/edit/angular-1xyxbv](url)
In the above link it shows the firstname as "client nane1" in all tab.
but I want to pass each tab different value.
  model ={
                 "tab1": {"firstname":"client nane1", "age":25},
                 "tab2": {"firstname":"client nane2", "age":35},
                 "tab3": {"firstname":"client nane3", "age":45}
               }

As per your response, fieldGroup can be used to achieve this. 
I tried below on tab but it not rendering the form with tab.
[https://stackblitz.com/edit/angular-1xyxbv-m2ea2b](url)

Please help me on TAB.

In addition, May I know the use of option. it always set to empty.
options: FormlyFormOptions = {};

Thanks 
Raj

**Comment by aitboudad** [comment]
the above example provides a different approach, which you may need to follow in order to work,

1. define a custom type [stepper](https://stackblitz.com/edit/angular-yu7bzv-bcmfip?file=src%2Fapp%2Fstepper.type.ts)

2. register it through the NgModule declaration:

```ts
    FormlyModule.forRoot({
      types: [
        { name: 'stepper', component: FormlyFieldStepper, wrappers: ['form-field'] },
      ]
    }),
```

3. define your fields config where each tab is represented by a `fieldGroup` and a `key`: (`tab1`, `tab2`).


> In addition, May I know the use of option

options is an optional input which allows passing some extra config such as formState, resetForm ...

**Comment by Rajanusa** [comment]
> the above example provides a different approach, which you may need to follow in order to work,
> 
> 1. define a custom type [stepper](https://stackblitz.com/edit/angular-yu7bzv-bcmfip?file=src%2Fapp%2Fstepper.type.ts)
> 2. register it through the NgModule declaration:
> 
> ```ts
>     FormlyModule.forRoot({
>       types: [
>         { name: 'stepper', component: FormlyFieldStepper, wrappers: ['form-field'] },
>       ]
>     }),
> ```
> 
> 1. define your fields config where each tab is represented by a `fieldGroup` and a `key`: (`tab1`, `tab2`).
> 
> > In addition, May I know the use of option
> 
> options is an optional input which allows passing some extra config such as formState, resetForm ...


> the above example provides a different approach, which you may need to follow in order to work,
> 
> 1. define a custom type [stepper](https://stackblitz.com/edit/angular-yu7bzv-bcmfip?file=src%2Fapp%2Fstepper.type.ts)
> 2. register it through the NgModule declaration:
> 
> ```ts
>     FormlyModule.forRoot({
>       types: [
>         { name: 'stepper', component: FormlyFieldStepper, wrappers: ['form-field'] },
>       ]
>     }),
> ```
> 
> 1. define your fields config where each tab is represented by a `fieldGroup` and a `key`: (`tab1`, `tab2`).
> 
> > In addition, May I know the use of option
> 
> options is an optional input which allows passing some extra config such as formState, resetForm ...

Thank a lot.
Please correct me if I am wrong
You suggest me to extend type for Tab similar to stepper right?
Initially, I thought of it, since not sure how to extend TAB, I created library with multiple module.
One module for Tab and another module for accordion.
The consumer instead using ngx-formly tag use my tag and pass the json as ngx-formly standard.

In Tab, I created formarray contain formgroup for each tab.
I am not sure how this can be achieved when extending this as type.

Please let me know if you have any example that has extending type for TAB.

Thanks
 Raj

**Comment by Rajanusa** [comment]
Hi 

Thanks a lot.
Please correct me if I am wrong
You suggest me to extend type for Tab similar to stepper right?
Initially, I thought of it, since not sure how to extend TAB, I created library with multiple module.
One module for Tab and another module for accordion.
The consumer instead using formly-form tag use my tag and pass the json as ngx-formly standard.

In Tab, I created formarray contain formgroup for each tab.
I am not sure how this can be achieved when extending this as type.

Please let me know if you have any example that has extending type for TAB.

In addition, Please let me know where option is used in your example.
Could not understand the following 
Options for the form. The formState property is passed to all formly-fields and is a mechanism for communicating between fields (without having to mess with your model).

Thanks
 Raj
