### ISSUE TITLE
Extend Type for TAB/Accordion, etc

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1735]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I would like to add Tab,Accordion, etc as part of ngx-formly.
I build angular library that encapsulate building Tab / Accordion based on schema passed to it and call formly-form internally. 

[The library would be similar to this here](https://github.com/franzeal/ngx-formly-tabs)

**Expected behavior**

if possible, I would like to extend type for Tab, Accordion, etc
What is the difference between extending type and creating angular library?

**Minimal reproduction of the problem with instructions**

[Extend type for Tab is not working here](https://stackblitz.com/edit/angular-yu7bzv-eywe95)

[As per your Tab example here](https://stackblitz.com/edit/angular-ngx-formly-hsgiah), consumer has to create "formarray" and pass that to "formly-form"
in .ts
form = new FormArray(this.tabs.map(() => new FormGroup({})));

In HTML
      <formly-form
        [form]="form.at(index)"
        [model]="model"
        [fields]="tab.fields"
        [options]="options[index]">
      </formly-form>

When I extend "Tab" as type, I implemented similar to [stepper](https://stackblitz.com/edit/angular-yu7bzv-bcmfip)

**How "form" is created is not clear to me.** 

[Extended Type for Tab works here](https://stackblitz.com/edit/angular-yu7bzv-saghux)

**What is the motivation / use case for changing the behavior?**

We would like to extend ngx-formly for Tab, Acordion, etc so that consumer need not write anything and by passing respective JSON Schema and model ngx-formly should render the form.

What is the right approach for TAB, Accordion, etc? 
Whether to extend the type or creating the library.

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

Angular 8.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Type script
* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
> What is the difference between extending type and creating angular library?

 if the component is reusable somewhere then it makes sense to declare it separately and then consumes it in `formly` by custom type else extending type would be enough.
