### ISSUE TITLE
Can we validate Model with FormlyFieldConfig Schema.

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1736]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```
I would like to validate the model with FormlyFieldConfig Schema.
The use case is before binding the model and schema to formly-form, the model must be confirm to schema.

[Similar to JSON Schema Validator](https://www.jsonschemavalidator.net/) from Newtonsoft
We could not use FormlyFieldConfig schema since key and value is not enclosed in quotes.
The above validator is not accepting the formlyfiledconfig. 

**Current behavior**

The angular formgroup.valid function can be used to check whether the form met the schema.
But I need to validate the model before binding to formly-form tag. since I may get the mode data from different source.

**Expected behavior**

I need to validate the model before binding to formly-form tag. since I may get the mode data from different source.

if I use JSON Schema, I can use newtonsoft to validate the model.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10
* **Angular version:** 2.0.X

Angular 8
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
> if I use JSON Schema, I can use newtonsoft to validate the model.

there is no such tool for `formly`, you may use `json-schema` too which is supported (#1459).
Check the following link: https://ngx-formly.github.io/ngx-formly/examples/advanced/json-schema

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad,

Thanks 

I already seen this example.

It is easy to generate FormlyFieldConfig schema  with [ngx-formly-designer here](https://franzeal.github.io/ngx-formly-designer/)

Can you please suggest any such designer for JSON schema?

Thanks
Raj

**Comment by aitboudad** [comment]
> Can you please suggest any such designer for JSON schema?

no idea 🙏, there is another approach which you may explore is to convert `FormlyFieldConfig` to `JsonSchema` for the validation process.

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad,

Sorry to bother you.
Please let me know the approach to to convert from FormlyFieldConfig to JsonSchema.

Thanks
Raj.

**Comment by aitboudad** [comment]
@Rajanusa create a custom function that converts your form fields to JsonSchema to be able to use JSON Schema Validator tool https://www.jsonschemavalidator.net/:
```ts
function fieldsToJsonSchema(fields) {
  ...
  return schema; 
}
```
