### ISSUE TITLE
How to write unit test for extend type

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1737]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I create one wrapper library over ngx-formly to use internally in our company and extend type for tab, accordion, etc. I need to write unit test for extend type.

**Expected behavior**

Please provide example for unit test of extend type.

**Minimal reproduction of the problem with instructions**

[Please find the extend type for Tab here](https://stackblitz.com/edit/angular-extend-type-tab-1).
I need to write unit test for extend type. Please provide some example.

**What is the motivation / use case for changing the behavior?**

Need to write unit test

**Please tell us about your environment:**

windows 10
* **Angular version:** 2.0.X

Angular 10.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
see select type example https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/select/src/select.spec.ts
