### ISSUE TITLE
Dynamically adding multicheckbox to the forn does not show label and value

### ISSUE THREAD

**Issue by aniruddhadas9** [ngx-formly/ngx-formly#1738]
**I'm submitting a bug**  (check one with "x")
```
[x ] bug report
```

**Current behavior**

when dynamically adding adding a `multicheckbox`, it does not show correctly. Cab seen here

https://stackblitz.com/edit/angular-2ouh7u?file=src/app/app.component.ts

```
   {
      key: 'multiselect',
      type: 'select',
      templateOptions: {
        label: 'Multi-select',
        multiple: true,
        options: [
          {label: 'Iron Man', value: 'iron_man'},
          {label: 'Captain America', value: 'captain_america'},
          {label: 'Black Widow', value: 'black_widow'},
          {label: 'Hulk', value: 'hulk'},
          {label: 'Captain Marvel', value: 'captain_marvel'},
        ],
        change: (field, $event) => {
            this.getChange();
          }
      },
    },
  ];

  getChange() {
    this.fields.push ({
        key: 'demo',
        type: 'multicheckbox',
        templateOptions: {
          label: 'Demo',
          options: [{
            key: 'me',
            value: 'you'
          }]
        }
      })

  }
```

**Expected behavior**

it show show the passed value as label in the UI, in this case "you"

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

mac, webstorm, npm, real rest endpoints server

* **Angular version:** 2.0.X

angular 8
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 3.5.3
* **Node (for AoT issues):** `node --version` =
12.x.x

**Comment by kenisteward** [comment]
@aniruddhadas9 hey buddy!

If you want this to work under the current circumstances don't use 

```this.fields.push()```

and instead use

```this.fields = [...this.fields, newField];```

or do a push and rebind the entire fields array with.

That being said, I'm not sure why just directly appending a field as long as change detection is occurring isn't properly propagating things but what I've provided to you now will fix that.

@aitboudad should this.fields.push() have no ill effects?

**Comment by kenisteward** [comment]
@aitboudad upon further investigation it looks like no formControl gets generated when you use this.fields.push as opposed to rebinding the entire fields array.  I'm not sure where but I was able to figure that out from console errors.

@aniruddhadas9 this is the reason why it doesn't get displayed properly.  console error causes break in the JS due to exceptions and you get a ton of "formcontrol isn't defined" errors.  Until that is corrected, you'll simply have to do what I previoiusly suggested.

**Comment by aitboudad** [comment]
`push` doesn't change the `fields` reference which angular rely on to detect changes, spread assign is the right way to solve the issue.

```ts
this.fields = [...this.fields, newField];
```
