### ISSUE TITLE
Bind Observable to select inside repeat section not working

### ISSUE THREAD

**Issue by SudeshAK** [ngx-formly/ngx-formly#1739]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question
```
Hi, 
I want to bind observable to select(second dropdown) inside a repeat section . 
In repeat section, observable for the first dropdown is set properly but on select of the first the second dropdown is not set . 
Replicating example is 
`https://stackblitz.com/edit/angular-l6ekwn`

Same approach I have used without repeat section It is working fine
this is the example
`https://stackblitz.com/edit/angular-yanbj1`
Same if it is used inside repeat section it wont work

**Comment by aitboudad** [comment]
rely on the passed `field` instance:
```patch
change: (field, $event) => {
+ field.parent.fieldGroup[1].templateOptions.options = this.dataService.getSports();
- this.fields[0].fieldArray.fieldGroup[1].templateOptions.options = this.dataService.getSports();
}
```

**Comment by SudeshAK** [comment]
Thanks it works..

**Comment by SudeshAK** [comment]
@aitboudad can we place repeat section inside a table i.e each row with delete inside a table with single header. when user click each row adds and when delete is click that row is deleted?
Thanks

**Comment by aitboudad** [comment]
yes possible:
- https://stackblitz.com/edit/angular-rv7jtn-pkhqkg
- https://github.com/ngx-formly/ngx-formly/issues/1595#issuecomment-495678025
