### ISSUE TITLE
Hidden field does not effect form validity when required or validator set

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1742]
```
[x] bug report 
```

**Current behavior**
When hide is set for a field, but either required is set or a validator is set the field status is evaluated.

**Expected behavior**
Hidden fields should not be taken into account for form validation.

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/angular-nr5wln-lx5tnq?file=src/app/app.component.html

**Comment by aitboudad** [comment]
>   Form is also invalid for hidden fields with required
 
that's a bug :)

> Toggling "togglHide" does not effect form validity.

use `hideExpression`: use https://stackblitz.com/edit/angular-nr5wln-yqkjnw

**Comment by aitboudad** [comment]
close in favor #1743

**Comment by aitboudad** [comment]
fixed in `v5.5.3`.

**Comment by FritzHerbers** [comment]
@aitboudad 
https://stackblitz.com/edit/angular-gy49oz-jtfgu5?file=src/app/app.component.ts
When there is only one field and it is disabled, the form is not valid.
Use case: a form is either editable or a person has to review the form where all fields are disabled, in both cases the submit needs to be clickable.

**Comment by aitboudad** [comment]
The `forms` cannot be valid and disabled at the same time, it accepts only one state (when calling `disable` the form clear all errors related to disabled field).

> Use case: a form is either editable or a person has to review the form where all fields are disabled, in both cases the submit needs to be clickable.

The solution is to prevent disabling an invalid `form`.

**Comment by FritzHerbers** [comment]
Thanks for the pointers, found references on Angular explaining the behaviour.

Well actually there is a need for readonly, which is not supported by Reactive Forms.
Also need something recursive, as you just have implemented with disabled.
