### ISSUE TITLE
Attribute disabled API

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1743]
```
[x] feature request
```

**Current behavior**
We are running into a show stopper for our going live in two months.
There are several issues when changing disabled flag programmatically.

**Expected behavior**
As most of the changing of the attributes are done after interacting with the backend or otherwise programmatically would it make sense to have a formly API to set these attributes?
The application finds the field in the FieldConfig[] and calls a method.

**Related Issues**
#1528
#1722 (maybe with some callback to the custom type to process attribute changes in the children)

**Your opinion**
What would be the best strategy to fix these issues?

**Comment by aitboudad** [comment]
> The use of expressionProperties to overcome the required problem slows the typing

for slow typing check https://github.com/ngx-formly/ngx-formly/issues/1620#issuecomment-514639091

**Comment by aitboudad** [comment]
Most of the above issue could be solved with expression properties, except `disabled` which is out of our control, unfortunately.

The fix for`disabled` will introduce a BC which I think it can be landed `V6` instead

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.6).

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
