### ISSUE TITLE
Custom error messages with material

### ISSUE THREAD

**Issue by MarieCharbonneau2** [ngx-formly/ngx-formly#1747]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
I want to create custom error messages with svg before the message. I have a custom wrapper and a custom field type and i want to put the custom message inside the wrapper.
I tried something like that : https://stackblitz.com/edit/angular-bej44b in my wrapper but validationMessage.errorMessage is empty in the wrapper.
When I put it in the custom field it is not empty but i don't want it here.

![example](https://user-images.githubusercontent.com/54543609/63873911-c5be5600-c9c0-11e9-9e4e-1e2423676772.png)

And the original message set by default is always here and i don't want it.

**Please tell us about your environment:**
Angular 7, Material

I'm looking for examples for custom error messages but i didn't find.

**Comment by aitboudad** [comment]
could you please provide a reproduction example using `stackblitz`, thanks!

**Comment by MarieCharbonneau2** [comment]
Of course, this is a reproduction example : https://stackblitz.com/edit/angular-qrttnm

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-pqfz6r

**Comment by MarieCharbonneau2** [comment]
thanks a lot !
But I also don't want to see the original message. How could I desactivate it ?

**Comment by aitboudad** [comment]
use `css` to hide it

**Comment by MarieCharbonneau2** [comment]
thanks !
