### ISSUE TITLE
Make 'Enter' key act as 'Tab' key

### ISSUE THREAD

**Issue by rizwanspeaks** [ngx-formly/ngx-formly#1751]
In formly-form, **when user presses the enter key from the input field it will act as tab key. (i.e) focus will goto the next field**..

How can I get this functionality in ngx-formly?

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
well, that's a js question not specific to `formly`, we've already provided a hint https://github.com/ngx-formly/ngx-formly/issues/1531#issuecomment-484247126 to handle such use-case.
