### ISSUE TITLE
Dynamiclly hide/show template

### ISSUE THREAD

**Issue by Et3rnal** [ngx-formly/ngx-formly#1752]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I have created a custom type of tabs, I need to have the ability to hide/disable a tab when value X in the model changes.
Currently, the model value is dynamic and I can use that, however, I want the value to be part of the field options so this feature becomes generic.
The value I'm passing to the type now doesn't reflect the changes in the model, it always the inial value

**Minimal reproduction of the problem with instructions**
this is one of the ways I tried but `hideIt` always has the inial value when checking what is inside this.to
```
label: 'Infection details',
              templateOptions: {
                hideIt: this.model.impact != 2,
              },
```

**What is the motivation / use case for changing the behavior?**
A generic solution to hide/show tabs dynamically, the reason I don't want to implement the role inside the type itself so I can keep it generic because I have many roles like this :\

* **Angular version:** 8.0
* **Browser:** [Chrome]
* **Language:** [TypeScript]

**Comment by aitboudad** [comment]
use `hideExpression`: https://ngx-formly.github.io/ngx-formly/examples/field-options/hide-fields

**Comment by Et3rnal** [comment]
What do you mean? `hideExpression` doesn't seem to work on the custom template and reading its value myself isn't changing dynamically.

I think this is more of what I need maybe!
https://stackblitz.com/edit/angular-i29psx

I'm not quite clear about what going on there and not sure if I should use it, to simplify what im trying to achive is

stepper/tab custom template with ablity to hide/show the whole step/tab dynamically as values in other steps changes
