### ISSUE TITLE
Async Validation fires multiple times for single field when loading form from JSON Schema

### ISSUE THREAD

**Issue by Prace** [ngx-formly/ngx-formly#1754]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
When loading a form from a json schema file, I add an async validation to one of the fields. Validation gets fired multiple times on startup for the single field (apparently equal to to the total number of fields in the form ). After that, the validation fires correctly when field is touched.

**Expected behavior**
Validation should only fire once when field is touched or instructed to do so.

**Minimal reproduction of the problem with instructions**
Repro on stackblitz ->[https://stackblitz.com/edit/angular-k1i8qu]( https://stackblitz.com/edit/angular-k1i8qu)
On startup, check dev console for the validation method calls.

**What is the motivation / use case for changing the behavior?**
Need to add async validation to a form loaded from json schema. I read that json validation is in the making, but thought this was a possible workaround. Thanks in advance for your support.

**Please tell us about your environment:**
Windows 10, VisualStudio Code, ngx-formly latest NPM package

* **Angular version:**
Angular CLI 8.1.1

* **Browser:** 
all

* **Language:**
Typescript

* **Node (for AoT issues):** `node --version` =
10.16.0

**Comment by NickStack-dev** [comment]
Quick add, not only async validators have this problem.

Minimal reproduction of the problem:
https://stackblitz.com/edit/angular-wj7mme-u74x4v
Check console, validator gets called twice on init.

**Comment by aitboudad** [comment]
I'd give it another chance to see if there is an easy way to fix it in the next minor version.

*note*: The proper fix will be implemented in the next major version (`v6`) as it may introduce a breaking change.

**Comment by aitboudad** [comment]
[v5.5.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.2) is released which includes a fix for this issue!

**Comment by Prace** [comment]
Hi I tried updating the previous stckblitz with 5.5.2, but the validation is called twice on startup. Here's a link:

[https://stackblitz.com/edit/angular-k1i8qu-bjhfoh](https://stackblitz.com/edit/angular-k1i8qu-bjhfoh)

Could it be because I am adding the validation during runtime and this forces a reload of the form object?

**Comment by aitboudad** [comment]
not sure why? I'll check it. Before it was called 8 times ;)

**Comment by aitboudad** [comment]
I've tried with angular reactive form without using `formly` and the calls are the same as what we've got with `formly` https://stackblitz.com/edit/angular-taojrp?file=src/app/input-form-example.ts
maybe related to https://github.com/angular/angular/issues/21500

so the fix is out of our scope, unfortunately, I'll try to provide a fix in angular itself when time allows!

**Comment by Prace** [comment]
I see. Thank you for your support! :)
