### ISSUE TITLE
Automatic local storage question

### ISSUE THREAD

**Issue by princepc** [ngx-formly/ngx-formly#1757]
Is there a way to add automatic browser local storage+retrieval to all prompts on formly form?

**Comment by aitboudad** [comment]
please provide more info about the use-case, thanks!

**Comment by princepc** [comment]
On some complex forms with lots of prompts i'd like to be able to save the data entered after each question is answered. So they don't lose the data in case of disconnections. I don't want to do a round trip to the server until the user saves the completed form, so local storage in the browser seems the best place for this to happen.
if there was some mechanism to hook into this at the form level rather that would be great.

**Comment by kenisteward** [comment]
Is there a reason why you can't listen for change detection of data and
store in local storage?

**Comment by princepc** [comment]
Possibly, just wondered if there was a formly way of doing this or not?

**Comment by aitboudad** [comment]
there is a way using a custom extension but it may not be a good solution, it would be better to rely on data changes as suggested by @kenisteward.
