### ISSUE TITLE
How to set default value to a text field dynamically on repeat section

### ISSUE THREAD

**Issue by SudeshAK** [ngx-formly/ngx-formly#1758]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] question
```
I am trying to set default value to a text field in repeat section
example:
`https://stackblitz.com/edit/angular-47rdkm-ucjvzw`
In this example you can see the first text field default value is set but when I click on add button
default value is not set(i.e; Customer Id field). How to set default value for the text field which came after add button?

* **Angular version:** 8.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
the request is not clear, please elaborate 🙏!

**Comment by SudeshAK** [comment]
Ok.. in this example https://stackblitz.com/edit/angular-47rdkm-ucjvzw you can see the first field Customer Id is set to 100 when you click on add button you can see customer id field is blank. Here I want that Customer id field to set 100. How can I do that?

**Comment by aitboudad** [comment]
in your example, the `customerId` rely on `test` input value (`customerId` equal to `test`).
after the first add `test` is empty.

> Here I want that Customer id field to set 100.

```ts
{
  type: 'input',
  key: 'customerId',
  defaultValue: 100
},
```

>  set default value to a text field dynamically

```ts
{
  type: 'input',
  key: 'customerId',
  hooks: {
    onInit(field) {
      const control = field.formControl;
      if (control.value === null) {
        control.setValue(100);
      }
    }
  },
},
```

**Comment by SudeshAK** [comment]
Thank you

**Comment by abhihotmail** [comment]
I want to set default value in JSON schema, can you pls provide an example.

**JSON SCHEMA:**
"items": {
                        "type": "number",
                        "title": "Periods",
                        "pattern": "^\\d{0,2}$",
                        "widget": {
                          "formlyConfig": {
                            "expressionProperties": {
                              "templateOptions.prevEntered": "field.model[field.index-1]",
                              "templateOptions.min": "field.templateOptions.prevEntered?field.templateOptions.prevEntered+1:0",
                              **_"templateOptions.default": "field.templateOptions.min?field.templateOptions.min:0",_** <=== NOT WORKING
                              
                              
 **MODEL FORMING:**
  {
  "enable": true,
  "data": {
    "x": false,
    "Periods": [
      0,
      **_null <= === Its forming null here, I wanna add default value dynamically ( the previous entered textfield value should be default value of the next item text field_**
    ]
  }
}
