### ISSUE TITLE
Testing tab extend type is failing since there is no field.fieldGroup is defined

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1759]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

The unit test fails.

**Expected behavior**

The unit test to be pased.

**Minimal reproduction of the problem with instructions**

The code is given below and this is similar to multi step extend.

```
import { Component, OnInit } from '@angular/core';
import { FieldType } from '@ngx-formly/core';


@Component({
  selector: 'formly-field-tab',
  template: `
  <p-tabView (onChange)="handleChange($event)">
    <p-tabPanel *ngFor="let tab of field.fieldGroup;let index = index;" header="{{tab.key}}" [selected]="selectedTab==index">
      <ng-template pTemplate="content">
          <formly-field [field]="tab"></formly-field>
      </ng-template>
    </p-tabPanel>
  </p-tabView>
`,
})

export class FormlyFieldsTab extends FieldType {
  selectedTab: number = 0;
  public index: number;
  handleChange(event) {
    var index = event.index;
    this.activateTab(event.index);
  }
  activateTab(tabNumber) {
    this.selectedTab = tabNumber;
  }
}

```
The sample is [here ](https://stackblitz.com/edit/angular-extend-type-tab-primeng-1) without code FormlyFieldsTab .

In my library, with handleChange and activateTab, it is not opening the first tab with control. so added this code.
Now challenge is test case fail because it is not able to create component.

The template has **field.fieldGroup** which is not a variable in a component so test case fail. [Spectator ](https://github.com/ngneat/spectator) is used for Unit Test.

The error I get is as follow
**TypeError: Cannot read property 'fieldGroup' of undefined**
Please advise, how to overcome.

**What is the motivation / use case for changing the behavior?**

The unit test should pass.
How to write unit test for Tab extended type.

**Please tell us about your environment:**

Windows 10

* **Angular version:** 2.0.X

Angulr 8.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by Rajanusa** [comment]
Hi,

We over come this problem bu add  ***ngIf="field"**  in the template as below.

```
<p-tabView *ngIf="field" (onChange)="handleChange($event)">
```

**Comment by aitboudad** [comment]
custom field type requires passing a built `field` input, you may use `FormlyFormBuilder` service to manually init the field before passing it to the component or valid field object.
