### ISSUE TITLE
Access to XMLHttpRequest at '' has been blocked by CORS policy:

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1761]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**

The unit test on Angular library that uses nngx-formly gives CORS error

**Expected behavior**

The unit test should pass.

**Minimal reproduction of the problem with instructions**

**The following error is comming in the console.**

Access to XMLHttpRequest at 'ng:///DynamicTestModule/FormlyFieldsTab.ngfactory.js' from origin 'http://localhost:9876' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

zone-evergreen.js:2981 Access to XMLHttpRequest at 'ng:///DynamicTestModule/ObjectTypeComponent.ngfactory.js' from origin 'http://localhost:9876' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

ObjectTypeComponent and FormlyFieldsTab are extended type.

**What is the motivation / use case for changing the behavior?**

Please help me.

**Please tell us about your environment:**

WIndows 10

* **Angular version:** 2.0.X

Angular 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
use stackoverflow.
