### ISSUE TITLE
How to increase or reduce column width

### ISSUE THREAD

**Issue by SudeshAK** [ngx-formly/ngx-formly#1763]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[x] Question
```

Hi,
In this example https://stackblitz.com/angular/qmqjkdgqvyo how to increase or reduce
column width of ngx datatable?
Thanks

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 8.0.X

**Comment by aitboudad** [comment]
use CSS or check `ngx-datatable` doc.
