### ISSUE TITLE
Expression property not working when checking against an observable

### ISSUE THREAD

**Issue by swillisstudio** [ngx-formly/ngx-formly#1765]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I have a select box which populates the options through an API using an observable. If there are less than 2 options then I want to disable the box to show there is nothing that can be changed, but it doesn't seem to do anything.

**Expected behavior**
If the observable returns 1 or 0 options then I want the select box to be disabled.

**Minimal reproduction of the problem with instructions**
[Stackblitz](https://stackblitz.com/edit/angular-cyko4o-2gmbjq)

**Comment by aitboudad** [comment]
pass the options through `expressionproperties` which resolve 'templateOptions.options' into `any[]`:

```ts
expressionProperties: {
  'templateOptions.options': of([
    { value: 'blue', label: 'Blue' },
    { value: 'red', label: 'Red' },
  ]),
},
```
