### ISSUE TITLE
Datepicker icon not showing `OnPush`

### ISSUE THREAD

**Issue by motykadaw** [ngx-formly/ngx-formly#1766]
**I'm submitting a ...** 
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Datepicker field does not show the calendar icon in `mat-suffix` until the field is focused with `ChangeDetectionStrategy.OnPush`.

**Expected behavior**
Calendar icon is displayed without the need to focus the field. 

**Minimal reproduction of the problem with instructions**
just a basic datepicker example with `ChangeDetectionStrategy.OnPush`:
https://stackblitz.com/edit/angular-rtfggz

**What is the motivation / use case for changing the behavior?**
With deeply nested components I would have to set the cd strategy in multiple components to default just to get this to work or create a custom datepicker field that manually calls the change detection.

**Comment by aitboudad** [comment]
released in `5.4.2` version.
