### ISSUE TITLE
FormlyFieldConfig[] as valid JSON in Build-in-validation example fail for IP address

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1768]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

Ngx-formly schema can be defined either as FormlyFieldConfig or JSON Schema.

FormlyFieldConfig is not a valid JSON and your example hard coded the schema in the .ts file.

My use case schema is stored in database and UI get the schema through API.
UI call the API. In order to return the FormlyFieldConfig from API, I made it as valid JSON [here ](https://stackblitz.com/edit/formlyfield-as-json-build-in-validation) and it works except IP address validation and it message. Since IP address is a pattern and it enclosed in a quotes, validation and it's message is not working.

**Expected behavior**

The IP address validation would be proper and its message would be displayed properly.

**Minimal reproduction of the problem with instructions**

Please find your build-in-validation example [here ](https://stackblitz.com/angular/qdxvlamrlxr)
Please find the same schema in valid JSON [here](https://stackblitz.com/edit/formlyfield-as-json-build-in-validation). I did not know, how to convert FormlyFieldConfig to JSON Schema, so I just made it as valid JSON by enclosing key and values in quotes.

Appreciate if you provide a function to do the same. It would be a grate help.

**What is the motivation / use case for changing the behavior?**

Since we store the schema in the database and API return the schema, I made it valid JSON.
so ngx-formly could not read the validation defined in the pattern string.

**Please tell us about your environment:**

windows 10
* **Angular version:** 2.0.X

angular 8
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript
* **Node (for AoT issues):** `node --version` =

**Comment by kenisteward** [comment]
I'm not at my desktop right now but at a cursory glance your configuration
is incorrect. You have lambda expressions in strings which is not right.

The proper thing to do is to store the function body as a string in a
config file that you get from the server. Then iterate over your config and
convert those strings to real functions.

Also in general validators are defined in the .forRoot not at the field
level. At the field level you just provide a simple tag. See our validation
guide under guides on the demo site.

**Comment by kenisteward** [comment]
You can define validators In a field definiton and it is in our docs.  You
just have to do the conversions properly

**Comment by Rajanusa** [comment]
Hi Keni Steward

Thanks for timely response.
Since I store the FormlyFieldConfig schema to database, how to do I return that to from REST API. 

As per my design, UI call API and it return Schema and Model as JSON.
The UI read the schema and mode and assign to respective field.

Alternative may be sending whole this as string but reading schema and model would be a problem in UI.

To make it JSON, enclosed quotes in Key and Values that causes problem.

If I manipulate the JSON at client side and remove the quotes in a JSON, it become invalid JSON.

If I try to store as string, it not valid since it has single quotes inside.

Please advise.

Thanks
Raj

**Comment by aitboudad** [comment]
it's better to use custom validation declared in `NgModule` for such case or something like https://github.com/ngx-formly/ngx-formly/issues/1744#issuecomment-525878630
