### ISSUE TITLE
Hide expression doesn't work if model gets set to itself

### ISSUE THREAD

**Issue by swillisstudio** [ngx-formly/ngx-formly#1769]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
I have a select box where the options are populated via API through an observable. I then pre-select the first option like so:

`this.model = {
              ...this.model,
              color: branches[0].value,
            };`

However, other fields using a hide expression no longer work once the model gets set.

**Expected behavior**
Other fields with hide expressions should still work.

**Minimal reproduction of the problem with instructions**
[Stackblitz](https://stackblitz.com/edit/angular-cyko4o-2gmbjq)

**Comment by aitboudad** [comment]
for a workaround use:

```ts
this.form.get('color').patchValue(branches[0].value);
```

**Comment by aitboudad** [comment]
you must re-assign the new model to the `formState.mainModel` in order to work properly:

```ts
this.model = {
    ...this.model,
    color: branches[0].value,
};

this.options.formState.mainModel = this.model;
```
