### ISSUE TITLE
Need Conversion Function from FormlyFieldConfig Schema to JSON Schema

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1770]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request
```

**Current behavior**

FormlyFieldConfig schema could not be used to validate the model before binding.
Since it is not JSON, it is difficult to pass from API to UI and difficult to manipulate.

**Expected behavior**

If there is a conversion function like below, would be grate help.
```
formlyJsonschema.toFieldConfig(this.jsonSchema)
```
Since there is [designer ](https://franzeal.github.io/ngx-formly-designer/) for FormlyFieldConfig, it is easy to build schema. 

but could not find any such tool for JSON Schema. 
if we define manually, we are not sure key name is correct and would convert properly to FormlyFieldConfig, etc.

For instance, we extend many type like tab, accordion, etc and don't know how to define the same in JSON schema.

**Minimal reproduction of the problem with instructions**

Feature Request.

**What is the motivation / use case for changing the behavior?**

Would be grate help for developer to covert FormlyFieldConfig Schema to JSON schema.
Please give some some sample/document for mapping between FormlyFieldConfig schema to JSON Schema.

I know we can use JSON schema but need to know the mapping between these two.

**Please tell us about your environment:**

Windows 10
* **Angular version:** 2.0.X

Angular 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
added a note in https://github.com/ngx-formly/ngx-formly/issues/1459
