### ISSUE TITLE
Material datepicker, min value not working?

### ISSUE THREAD

**Issue by timvaines** [ngx-formly/ngx-formly#1771]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```
**Current behavior**
Using the Material datepicker control, provided 'min' value does not have any effect on the validation or the datepicker control.
The templateOptions > min property seems to expect a number, not a string or date?

**Expected behavior**
I would expect with the min set on the control for the datepicker to disable date selection before the min value and for validation to fire (if typed directly) if the date is less than the min?

**Minimal reproduction of the problem with instructions**
Example demo on Stackblitz:
https://stackblitz.com/edit/angular-et5ag5-bugyf8

**Comment by timvaines** [comment]
I did actually get this working as I would expect my tweaking an earlier example of the datepicker component on another issue.

https://stackblitz.com/edit/formly-datepicker-debug

I don't know if what I described as my expected behaviour is actually the desired behaviour?

**Comment by aitboudad** [comment]
pass the min value through the `datepickerOptions` [property](https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/datepicker/src/datepicker.type.ts#L17):

```ts
    templateOptions: {
      datepickerOptions: {
        min: 'month',
      },
    },
```

**Comment by timvaines** [comment]
Thanks this works! I knew it was my misunderstaning. An example in the docs of the datepicker would be really handy.
