### ISSUE TITLE
formlyJsonschema.toFieldConfig() is not converting JSON Schema written for Accordion

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1772]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```
**Current behavior**

Extend the type for Accordion similar to [steps] (https://stackblitz.com/edit/angular-yu7bzv-bcmfip) and It uses FormlyFieldConfig Schema.

I created JSON schema and convert that to FormlyFieldConfig  using the following
```
fields: FormlyFieldConfig[] = [this.formlyJsonschema.toFieldConfig(this.schema)];
```
It fail to convert full schema and gives only title.

Please find the FormlyFieldConfig schema working [here](https://stackblitz.com/edit/angular-extend-type-tab-primeng-1).

Please find the JSON schema [here](https://stackblitz.com/edit/angular-extend-type-tab-primeng-json-schema).

I don't not know, how to give fieldGroup in JSON Schema. 
Please advise.

**Expected behavior**

The JSON Schema should be able to convert to FormlyFieldConfig Schema with the following statement.

```
fields: FormlyFieldConfig[] = [this.formlyJsonschema.toFieldConfig(this.schema)];
```

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

We prefer to JSON Schema for UI generation.

**Please tell us about your environment:**

Windows 10
* **Angular version:** 2.0.X

Angular 8.

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-yu7bzv-e319t8
