### ISSUE TITLE
Manually trigger model change

### ISSUE THREAD

**Issue by yluijten** [ngx-formly/ngx-formly#1773]
In my form I've enabled `checkExpressionOn: 'modelChange'`. 

The form has a read and write mode which I can toggle by setting `templateOptions.readonly`. When I switch to write mode I set the `readonly` property for each field to `false`. Unfortunately this change isn't picked up because of the `checkExpressionOn` setting. The readonly attribute still exists on the HTML element.

I can work around this issue by doing `options.resetModel`. The model change is triggered and because of that the HTML element is updated as well.

My question; what's the best practice to manually trigger the model change so the field and HTML are updated?

Example:
https://stackblitz.com/edit/angular-gwjfs6-dxp983

**Comment by aitboudad** [comment]
internally we use `_checkField` which is an internal API that you can use in the meantime until we make it public (in V6).
see https://stackblitz.com/edit/angular-gwjfs6-ymjklb
