### ISSUE TITLE
How to set the max property of datepicker dynamically?

### ISSUE THREAD

**Issue by timvaines** [ngx-formly/ngx-formly#1774]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**
I have a requirement in my form to dynamically change the allowable min/max dates of the datepicker field based on some other form fields. I thought this would be achievable using an expressionProperties, something like:

`expressionProperties: { 'templateOptions.datepickerOptions.max': 'model.maxDate', }`

However this approach does not appear to work as I might expect.

Question: is this entriely the wrong approach, can you suggest a better way of achieving the expected behaviour?

**Expected behavior**
When changing the model.maxDate value (via the button click in the sample) the max property of the datepicker should be updated.

**Minimal reproduction of the problem with instructions**
Here is a sample on Stackblitz:
https://stackblitz.com/edit/dyn-max-date

**Comment by aitboudad** [comment]
`expressionProperties` should be passed to the field object and not inside `templateOptions`:

```patch
{
  key: 'startDate',
  type: 'datepicker',
  templateOptions: {
    label: 'Period Start',
    required: true,
    datepickerOptions: {
      min: '2019-09-10'
    },
--  expressionProperties: { 'templateOptions.datepickerOptions.max': 'model.maxDate', }, 
  },
++  expressionProperties: { 'templateOptions.datepickerOptions.max': 'model.maxDate', }, 
}
```

here is a working example https://stackblitz.com/edit/dyn-max-date-xkkhsz
