### ISSUE TITLE
Validation message in JSON Schema

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1775]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**

We use JSON Schema for our app and you have provided some example.
We saw your example to pass validation message in the FormlyFieldConfig schema [here](https://stackblitz.com/angular/qdxvlamrlxr). 
Similarly, we would like to supply validation message as part of JSON Schema. 
The validation message could be static or dynamic based on the content in current control or any other control in the form.

There are many such validation used in FormlyFieldConfig. 
May I know where can I find all possible validation in your documentation.
How to apply the same in JSON schema 
For instance 

```
{
      key: 'maxWordCount',
      type: 'textarea',
      templateOptions: {
        label: 'maxWordCount',
        maxWordCount: 4,
        rows: 5,
      },
      validation: { show: true }
    },
```

The above example uses maxWordCount and rows. 
How do I give this in JSON Schema.

Please advise.

**Expected behavior**

Validation Message could not be provided in the JSON schema. 
You have given example to add generic validation function at the module level. 
but we want to define at the JSON Schema level.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

We prefer to use JSON Schema.

**Please tell us about your environment:**

Windows 10
* **Angular version:** 2.0.X

Angular 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
similar to https://github.com/ngx-formly/ngx-formly/issues/1772#issuecomment-530618830, in `json-schema` you can pass a custom `formly` config through `widget` property.

**Comment by Rajanusa** [comment]
Hi Abdellatif Ait boudad,

Thank you very much for the response.

I tried as per your suggestion to set textarea rows and maxWordCount but it is not working.
Similarly tried validation message for IP that also not works. 

Please find the same [here](https://stackblitz.com/edit/angular-multi-step-json-schema) and advise.

```
        "properties": {
          "firstname": {
            "type": "textarea",
            "title": "First name",
            "widget": {
              "formlyConfig": {
                "maxWordCount": 25,
                "rows": 5
              }
            },
          },
          "ip": {
            "$id": "#/properties/ip",
            "type": "string",
            "title": "The Ip Schema",
            "default": "",
            "examples": [
            "111.123.789.654"
            ],
           "pattern": "^(\\d{1,3}\\.){3}\\d{1,3}$",
           "widget": {
            "validation": {
               "messages": {
                 "pattern": (error, field: FormlyFieldConfig) => `${field.formControl.value} is not a valid IP Address`
                }
              }
            }
          }
        },
```

Thanks
Raj

**Comment by aitboudad** [comment]
your `json` is not valid, here is a working example https://stackblitz.com/edit/angular-multi-step-json-schema-u3mgpf
for `textarea` pass those options through `templateOptions`:

```patch
"widget": {
  "formlyConfig": {
    "templateOptions": {
      "maxWordCount": 1,
      "rows": 5
    }
  }
},
```

for `ip` field:
```ts
"widget": {
  "formlyConfig": {
    "validation": {
      "messages": {
      "pattern": (error, field: FormlyFieldConfig) => `${field.formControl.value} is not a valid IP Address`
      }
    }
  }
}
```

**Comment by Rajanusa** [comment]
Hi  Abdellatif Ait boudad,

Thanks for timely response.

Raj

**Comment by Rajanusa** [comment]
Hi,

I face one challenge, when I store the JSON into the file and parse using newtonsoft.
It is not accepting the arrow function without quotes. if I add quotes for arrow function, it is not working.

Please let me know any work around.

Thanks
Raj

**Comment by burjua** [comment]
Hello, having the same question about validation message. 
The example given by @aitboudad is not JSON, it's Javascript. Is it possible to achieve the same by pure JSON?

**Comment by aitboudad** [comment]
For those who are willing to use pure JSON for `ip` field example above https://github.com/ngx-formly/ngx-formly/issues/1775#issuecomment-531279301, you may try with `expressionProperties`:

```json
"widget": {
  "formlyConfig": {
    "expressionProperties": {
      "validation.messages.pattern": "field.formControl.value + 'is not a valid IP Address'"
    }
  }
}
```
