### ISSUE TITLE
Add fabric js as a custom field type

### ISSUE THREAD

**Issue by princepc** [ngx-formly/ngx-formly#1776]
[x] support request

I'd like to know how to go about adding the fabric js library as a custom field type which could then be used to load/save images as a form field.

thanks

**Comment by aitboudad** [comment]
see https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field

> be used to load/save images as a form field.

to assign the new value to the field inside you custom field use `this.formControl.setValue(value)`

**Comment by princepc** [comment]
Hi thanks for your reply, I'm looking for more functionality than just loading/saving images, the fabric.js library allows for drawing/manipulation of images etc.
I found an angular wrapper for fabric and added it to this stackblitz:
https://stackblitz.com/edit/fabric-image
adding the fabric element directly to the app.component.html and it works ok, you can click and draw on it.

but the formly field fabric component below it doesn't appear to work.

I'd like to be able to do something similar to the example here as a formly custom field https://stackblitz.com/github/zefoy/ngx-fabric-wrapper/tree/master/example?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
seems working, the only missed part is the config property: 
https://stackblitz.com/edit/fabric-image-ajplb1

```patch
export class ImageTypeComponent extends FieldType {
++  public config = {
++   isDrawingMode:true
++ }
}
```

**Comment by princepc** [comment]
doh! thank you again!
