### ISSUE TITLE
Grouped Repeat Section

### ISSUE THREAD

**Issue by feloff** [ngx-formly/ngx-formly#1778]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**
My model has an array of elements that can be grouped by a specified property. I extended the repeat example to group the array elements by the specified section id. Initial adding and deleting of items works as expected. The order in which items are added and removed can cause other group results' fields to partially disappear. The model is still correct, however, so the logic of adding and removing seems OK.

**Expected behavior**
The model is still fine, and expect form to model the model.

**Minimal reproduction of the problem with instructions**
Stackblitz based on investment sample prepared to replicate the issue:
Working: add 2 investments to group 1, and then 1 to group 2. Remove the one from the second and all is still fine.
Not working: Add investment to group 1, then group 2, then group 1 again. remove the invesment from the second group => the second item in group 1 goes wonky. 
[https://stackblitz.com/edit/angular-qdsayt](https://stackblitz.com/edit/angular-qdsayt)

**What is the motivation / use case for changing the behavior?**
I really want to group the investments :)
**Please tell us about your environment:** Mac OS
* **Angular version:** 7.0.X
* **Browser:** [ Chrome XX ]
* **Language:** [TypeScript ~3.1.1]

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-qdsayt-26tngc

**Comment by feloff** [comment]
Thank you, but still a problem, unfortunately. Add one in group 1, then 2, then 1, then 2, then 1, then 2. Start removing items from group2 - should start removing from goup 1 on second remove

**Comment by aitboudad** [comment]
@feloff example fixed, update the remove call argument to `j` index:

```patch
-- (click)="remove(i)
++ (click)="remove(j)
```

**Comment by feloff** [comment]
great - thank you
