### ISSUE TITLE
JSON Schema has Validation Message as Arrow Function is not valid JSON and could not send from API

### ISSUE THREAD

**Issue by Rajanusa** [ngx-formly/ngx-formly#1782]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

**Expected behavior**

Ngx-Formly Provide different way to add validation message.
1. Create a function and  add it to the the module level and use it in schema
2. Import the function at component level and use it in Schema
3. Directly use it in schema.

I face challenge in 3rd option. Since the JSON Schema come from API and newtonsoft is not parsing the JSON Schema without quotes in arrow function in validation message as below.
```

      "ip": {
        "$id": "#/properties/ip",
        "type": "string",
        "title": "The Ip Schema",
        "default": "",
        "examples": [
          "111.123.789.654"
        ],
        "pattern": "^(\\d{1,3}\\.){3}\\d{1,3}$",
        "widget": {
          "formlyConfig": {
            "validation": {
              "messages": {
                "pattern": (error, field: FormlyFieldConfig) => `${ field.formControl.value } is not a valid IP Address`
              }
            }
          }
        }
      }

```
The following C# code fail, since JSON is not valid. 
```
 var wraperobject = JObject.Parse(ui_schema);
```

If I add quotes like below as given below.

```
      "ip": {
        "$id": "#/properties/ip",
        "type": "string",
        "title": "The Ip Schema",
        "default": "",
        "examples": [
          "111.123.789.654"
        ],
        "pattern": "^(\\d{1,3}\\.){3}\\d{1,3}$",
        "widget": {
          "formlyConfig": {
            "validation": {
              "messages": {
                "pattern": "(error, field: FormlyFieldConfig) => `${ field.formControl.value } is not a valid IP Address`"
              }
            }
          }
        }
      }

```
The validation message is not appearing as expected but appear as it is like below.
```
(error, field: FormlyFieldConfig) => `${ field.formControl.value } is not a valid IP Address`
```
We prefer defining validation message in JSON Schema, Since no need to build the app.

Please suggest some workaround when we return the JSON schema from API

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

JSON is not hard coded in the UI layer. 
It comes from API, since arrow function does not enclosed in quotes, it is not a valid JSON.

**Please tell us about your environment:**

Window 10

* **Angular version:** 2.0.X

Angular 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
I think I've provided an answer in https://github.com/ngx-formly/ngx-formly/issues/1768#issuecomment-531280919.

Define your validation through NgModule declaration instead:

```ts
export function IpValidator(control: FormControl): ValidationErrors {
  return !control.value || /(\d{1,3}\.){3}\d{1,3}/.test(control.value) ? null : { 'ip': true };
}

export function IpValidatorMessage(err, field: FormlyFieldConfig) {
  return `"${field.formControl.value}" is not a valid IP Address`;
}
@NgModule({
  imports: [
    FormlyModule.forRoot({
      validators: [
        { name: 'ip', validation: IpValidator },
      ],
      validationMessages: [
        { name: 'ip', message: IpValidatorMessage },
      ],
    }),
  ],
})
export class AppModule { }
```

then pass the `ip` validator in your `json-schema`:

```json
"ip": {
  "$id": "#/properties/ip",
  "type": "string",
  "title": "The Ip Schema",
  "default": "",
  "examples": [
    "111.123.789.654"
  ],
  "widget": {
    "formlyConfig": {
      "validators": { "validation": ["ip"] }
    }
  }
}
```
