### ISSUE TITLE
Better way to change select templateoptions options.

### ISSUE THREAD

**Issue by josepacelli** [ngx-formly/ngx-formly#1783]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x ] support request
```
To change the Select options, i use 
 this.fields[1].fieldGroup[2].templateOptions.options = this.newOptions;

to access the options value and change after the form is created.

There is a better way to do this?

The FormlyFieldConfig is this:

```
fields: FormlyFieldConfig[] = [
    {
      className: 'section-label',
      template: '<hr /><div><strong>Dados:</strong></div>'
    },
    {
      fieldGroupClassName: 'row',
      fieldGroup: [
        {
          className: 'col-12',
          type: 'input',
          key: 'nome',
          templateOptions: {
            label: 'Nome:',
            placeholder: 'Nome da Potência',
            required: true
          }
        },
        {
          className: 'col-12',
          type: 'input',
          key: 'razaoSocial',
          templateOptions: {
            label: 'Razão Social:',
            placeholder: 'Razão Social',
            required: true
          }
        },
        {
          className: 'col-12',
          type: 'select',
          key: 'gestorAtual',
          templateOptions: {
            label: 'Gestor atual:',
            placeholder: 'Nome do gestor atual',
            required: true,
            options: [],
            labelProp: 'nome',
            valueProp: 'matricula'
          }
        }
      ]
    },
}]

```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
that depends on the use case, here are some ways:

- `onInit` event: https://ngx-formly.github.io/ngx-formly/examples/other/cascaded-select
- Using an Observable object: https://ngx-formly.github.io/ngx-formly/examples/other/observable-select
- Using expression properties: https://ngx-formly.github.io/ngx-formly/examples/other/cascaded-select-json

> To change the Select options, i use
this.fields[1].fieldGroup[2].templateOptions.options = this.newOptions;

or you may define a helper function to find the field by its key:

```ts
getField('nome').templateOptions.options = this.newOptions;
```

**Comment by josepacelli** [comment]
How I do that? 
getField('nome').templateOptions.options = this.newOptions;

**Comment by aitboudad** [comment]
```ts
  function getField(key: string, fields: FormlyFieldConfig[]): FormlyFieldConfig {
    for (let i = 0, len = fields.length; i < len; i++) {
      const f = fields[i];
      if (f.key === key) {
        return f;
      }
      
      if (f.fieldGroup && !f.key) {
        const cf = this.getField(key, f.fieldGroup);
        if (cf) {
          return cf;
        }
      }
    }
  }

class AppComponent {
  ...
  updateSelectOption() {
    getField('nome', this.fields).templateOptions.options = this.newOptions;
  }
}
```

**Comment by josepacelli** [comment]
Thanks.
