### ISSUE TITLE
form.valueChanges not working properly (after recent ngx-formly updates?)

### ISSUE THREAD

**Issue by Jop3K** [ngx-formly/ngx-formly#1790]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

I am using this.form.valueChanges to check if a field is edited so i can compare initValues and newValues. For some reason which i and my partner are unable so solve; the "initValues" synchronizes with newValues inside the subscribe method.

This code worked perfectly before and has now stopped working completely. I think this issue came with the recent updates to ngx-formly?

```
this.form.valueChanges.subscribe(newValues => {

console.log(newValues);  // this shows correctly the updated model as object
console.log(this.initValues); // this should be the unchanging / once initialized value which we use to compare with newValues, but it logs exactly the same key[value]'s as newValues each time a field is edited. 
})
```

Why i need the initial values is to check if the fields have been edited.

```
  if (_.isEqual(newValues, this.initValues)) {
            this.formIsEdited = false;
          } else {
            this.formIsEdited = true;
          }
```

This error shows up when i try to Object.freeze(); the initValues to make sure it stays the same.
```
core.js:6014 ERROR TypeError: Cannot assign to read only property 's_id' of object '[object Object]'
    at assignModelValue (ngx-formly-core.js:61)
    at FormlyForm.changeModel (ngx-formly-core.js:769)
    at ngx-formly-core.js:887
    at SafeSubscriber.schedulerFn [as _next] (core.js:35378)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at EventEmitter.next (Subject.js:39)
    at EventEmitter.emit (core.js:35297)
```

**Expected behavior**

The expected behavior is that "initValues" would preserve the old "model" object value which is saved to a variable a single time through a service subscribe call in ngOnInit.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 10, VSC, NPM, Express

* **Angular version:** 2.0.X

8.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
Hi, could you please provide an example using [stackblitz](https://stackblitz.com/angular/baqpkjdrqjy), thanks!

**Comment by Jop3K** [comment]
Here:

https://stackblitz.com/angular/baqpkjdrqjy

I am unable to reproduce the problem here, but that is pretty much how it's supposed to work. The only difference that i can think of is that instead of giving initValues its value like this: 

```
initValues : any = {
    input1 : "Input1",
    input2 : "Input2",
    input3 : "Input3"
  };

```
... It comes from a service instead

**Comment by aitboudad** [comment]
the following assign looks wrong, `updateInitialValue` doesn't return the model value.

```
this.initValues = this.options.updateInitialValue();
```

**Comment by Jop3K** [comment]
> the following assign looks wrong, `updateInitialValue` doesn't return the model value.
> 
> ```
> this.initValues = this.options.updateInitialValue();
> ```

That line of code works for me flawlessly though. Also in the provided stackblitz it does exactly what i'm aiming for.

The issue is not in the save() function. It believe it has to do with the relation between initValues and `this.form.valueChanges.subscribe(newValues => {})   ` in my case

**Comment by aitboudad** [comment]
well without a reproduction I can't guess where the issue comes, so try to check firstly if you're using the latest version of formly `5.4.2`.

**Comment by Jop3K** [comment]
Yup, using the last version on ngx-formly.

package.json:
`    "@ngx-formly/bootstrap": "^5.4.2",
    "@ngx-formly/core": "^5.4.2", `

I'll try to provide a better example later, if i'm unable to fix the issue myself. Interesting that i got it to work with the stackblitz though; quite an eye opener. Maybe the next step is to revert changes in my own code to get to the root of the cause. 

Just so weird to see that all kinds of copies of the `variable` that contains `initValues` in my own code; kind of syncs with `newValues`. Tried it as `const` and `Array[Object]` > same result.

**Comment by aitboudad** [comment]
probably the `newValues` is linked to the formly `model` changes, so either:

1. try to copy the `model`  instead:
```ts
this.newValues = _.copy(this.model);
```

2. use form.value:

```ts
this.newValues = this.form.value;
```

2. use `immutable` https://github.com/ngx-formly/ngx-formly/issues/1429#issuecomment-497754350

**Comment by Jop3K** [comment]
> probably the `newValues` is linked to the formly `model` changes, so either:
> 
> 1. try to copy the `model`  instead:
> 
> ```ts
> this.newValues = _.copy(this.model);
> ```
> 
> 1. use form.value:
> 
> ```ts
> this.newValues = this.form.value;
> ```
> 
> 1. use `immutable` [#1429 (comment)](https://github.com/ngx-formly/ngx-formly/issues/1429#issuecomment-497754350)

Thanks a lot!

These changes seem to have fixed my problem for the time being:

Old: 
```
  if (_.isEqual(newValues, this.initValues)) {
            this.formIsEdited = false;
            console.log('it is the same!')
          } else {
            this.formIsEdited = true;
            console.log('it is different!')
          }
```

New: 

```
  if (_.isEqual(_.pickBy(newValues, _.identity), this.initValues)) {
            this.formIsEdited = false;
            console.log("Value is the same!")
          } else {
            this.formIsEdited = true;
            console.log("Form is edited!")
          }
```

Old:
`this.initValues = this.formData.r_data;`

New: 
`this.initValues = _.cloneDeep(this.formData.r_data);`
