### ISSUE TITLE
Need help on writing unit test and integration test for a page with formly

### ISSUE THREAD

**Issue by albertthinc** [ngx-formly/ngx-formly#1791]
Hi,

I have built an application with 50+ fields in a template. 
Now I need to write case and integration testing for the dynamic forms page. 

But, I am clueless on how to write for a dynamic form.

Require your input

For now, I need below checks to be done
1. Whether the field is displayed
2. Whether it is marked as required.
3. And whether model blinded properly and saved.

Thank you

**Comment by aitboudad** [comment]
we didn't yet give testing what it deserves 😄 and I think we should add a section about testing in our doc, right now the only examples we have is our components which you may check:
- https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/templates/field-array.type.spec.ts
- https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/select/src/select.spec.ts

sorry about that 🙏!!

**Comment by albertthinc** [comment]
Thank you.... 
Looking forward for the document.......

**Comment by pedy711** [comment]
What is the best way to unit test formly forms?

**Comment by aitboudad** [comment]
@pedy711 see https://github.com/ngx-formly/ngx-formly/issues/2723#issue-818214519

**Comment by pedy711** [comment]
I see that testing "createComponent" is going to be released with version 6. Is there a fixed date for the version 6 release?

**Comment by aitboudad** [comment]
@pedy711 In less than a month you can already start using it, we're in `rc` release (https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-rc.1).
