### ISSUE TITLE
Problems with hidden fields being flagged as in error

### ISSUE THREAD

**Issue by JakeEllis1993** [ngx-formly/ngx-formly#1793]
**I'm submitting a ...** 
```
[ ] bug report
[ ] feature request
[x ] support request
```

**Current behavior**
I currently have a form with numerous hidden inputs that are revealed conditionally based on answers to previous questions. If the user submits the form with a revealed question in error it correctly prevents submission and flags the relevant inputs as in error. However if the user fills in the input and it reveals a previously hidden question, that question will start off as flagged in error. 
**Expected behavior**
We need to not have that happen and only flag a field in error if it was visible at time of submissions

**Minimal reproduction of the problem with instructions**
Have any config with 2 fields, one required and the other initially hidden. Submit the form without filling in the mandatory field, this will be highlted as in error. Then reveal the hidden question this will start of in error despite never being touched by the user.

* **Angular version:** 7.0.0

* **Browser:** all 

* **Language:**  TypeScript 3.1.6

**Comment by aitboudad** [comment]
could you please try with `hideExpression` instead of `hide`?
