### ISSUE TITLE
Specific Identification of Formly Field.

### ISSUE THREAD

**Issue by ajay1208** [ngx-formly/ngx-formly#1795]
I Have created a form using dynamic JSON. Is there any way i can find the specific field?  

(ie) I have a functionality to perform on the field based on the other field changes in different component. Before i used to do using id and document.getElementById old school method. Now I have upgraded the formly form and removed all the hard coded id's of the field due to the duplicate id accessibility issue we where facing when using in the repeating section.

**Current behavior**
We don't have any specific attribute to find the formly field from other components.

**Expected behavior**
Any ways to find the specific field in the form.

**Comment by aitboudad** [comment]
something like https://github.com/ngx-formly/ngx-formly/issues/1783#issuecomment-533058837 ?

**Comment by ajay1208** [comment]
We don't have the form reference in the other component. Both are separate component. In this situation any suggestion would be helpful.

**Comment by aitboudad** [comment]
you can get the form reference using `@ViewChild`:

```ts
import { FormlyForm } from '@ngx-formly/core';

export class AppComponent {
  @ViewChild(FormlyForm) formlyForm: FormlyForm;
  ...

  const fields = this.formlyForm.fields;
}
```

**Comment by ajay1208** [comment]
Ok thanks! I hope would help will using in the component level. Any suggestion for automation scripts, because they were also using the id's before.

**Comment by ajay1208** [comment]
And is there any logic or pattern will be used while generating the id? If so can you please share the details.

**Comment by aitboudad** [comment]
The generated id is based on the following fields: 
- global form order
- field type
- field key
- field index

you can use a custom extension to define your own criteria see https://github.com/ngx-formly/ngx-formly/issues/1150#issuecomment-416239430
