### ISSUE TITLE
set field value based on dropdown selection

### ISSUE THREAD

**Issue by chandrahanish** [ngx-formly/ngx-formly#1796]
I am new to ngx-formly. I am bulding simple form with textbox and dropdown, I have created change event  on dropdown selection and trying to set textbox value on that event.  here is my sample code. Please help me how to set textbox value on dropdown change.

export const employeeDetails = { 
    name: 'employeeDetails',
    extends: 'formly-group',
    defaultOptions: {
         fieldGroup:[
                        { key: 'employmentStatus', type: 'select', templateOptions: { label: 'Employment Status',  required: true,
                        options: [
                            { label: 'Employed', value: '1' },
                            { label: 'Unemployed', value: '2' },
                            { label: 'Retired', value: '3' }],
                            change: (field, $event) => {

                            }
                        }
                    },
                        { key: 'occuption', type: 'input', 
                        templateOptions: { label: 'Occuption',  required: true, onChange: 'this.setOccuptionValue()' },
                    }
                    ]
    }
  };

**Comment by aitboudad** [comment]
see https://ngx-formly.github.io/ngx-formly/examples/other/cascaded-select
