### ISSUE TITLE
Conditionally Hidden Field are not able to patch value 

### ISSUE THREAD

**Issue by ajay1208** [ngx-formly/ngx-formly#1798]
I am facing a issue while trying to patch the value. I have got a field which will be shown on condition of the other field (ie radio group field). On change of the radio group value i need to show some fields and i need to patch the fields with some value.

In hiddenexpression i am using the condition to show the field (ie hideExpression": "model.childrenrisk === 'Y'") and on change of the radio group i have logic to conditionally patch the value and disable the fields (ie "onChange": "formState.modelService.clearFamilyViolenceChildrenRisk(this)")

**Current behavior**
values are not patching and disabled are throwing error has it was not able to get that hidden values.

**Expected behavior**
Values are being patched and fields are disabled.

**Comment by aitboudad** [comment]
Hi, can you replicate your example using our stackblitz starter example https://stackblitz.com/angular/yggqbdbmynn?file=src%2Fapp%2Fapp.component.ts

Thanks!

**Comment by ajay1208** [comment]
Hi below is the link with example
https://yggqbdbmynn.angular.stackblitz.io

**Comment by aitboudad** [comment]
The link doesn't work for me + I may need the EDITOR URL.

**Comment by ajay1208** [comment]
Can yu try this.
https://stackblitz.com/angular/yggqbdbmynn

**Comment by aitboudad** [comment]
work now but you've missed saving changes (the content is the same of the ones I've shared)

**Comment by ajay1208** [comment]
Sorry.. Some issue its not saving my changes. created new can you check this.
https://stackblitz.com/edit/angular-fdjd5u

**Comment by aitboudad** [comment]
the assign doesn't change the model reference which angular rely on to detect changes.
use the following assign instead:

```ts
  public patch() {
    this.model = { ...this.model, line2: this.model.line1 };
  }
```

**Comment by ajay1208** [comment]
Even using that it was not helpful this.model = { ...this.model, line2: this.model.line1 };
I tried even that.

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-fdjd5u-qhtick

```patch
-- onChange: this.patch(),
++ change: () => this.patch(),
