### ISSUE TITLE
The pipe 'formlySelectOptions' could not be found 

### ISSUE THREAD

**Issue by patrickrioux** [ngx-formly/ngx-formly#1801]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
When customizing the select template, it complains about missing formlySelectOptions. Obviously I am missing an import but don't know how to fix this.

**Expected behavior**
Rendering the select using a custom template.

**Minimal reproduction of the problem with instructions**
I have followed the following instructions https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field
This works great for input but select is causing the issue with the missing pipe.

* **Angular version:** 7.2.15

**Comment by aitboudad** [comment]
The `formlySelectOptions` pipe is part of `FormlySelectModule` which you may need to import:

```ts
import { FormlySelectModule } from '@ngx-formly/core/select';

@NgModule({
  imports: [
    ...
    FormlySelectModule,
  ],
})
export class AppModule { }
```

**Comment by patrickrioux** [comment]
Thank you for the quick response. Perhaps adding a custom select as an example will be more appropriate than a input?  By anyway, it is all good now.

**Comment by aitboudad** [comment]
> Perhaps adding a custom select as an example will be more appropriate than an input? 

why not or adding a note in the custom templates guide.
PR welcomed!
