### ISSUE TITLE
*ngIf evaluating to false still creates control in formly field

### ISSUE THREAD

**Issue by silvl** [ngx-formly/ngx-formly#1803]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
I have implemented a formly repeat section, such that the items may be filtered out of the array and not included on a form using *ngIf.  While the controls did not appear on the screen, they still were referenced in the form object. Thus, if there are any validation errors in the repeat-section (even though not included), it still results in the form being invalid.

**Expected behavior**
Repeat sections that are excluded via *ngIf should not be included in the forms control array.

**Minimal reproduction of the problem with instructions**
I modified the sample repeat-section to include an *ngIf="false" and attached it here.

[ynevkxlbdlk.angular.zip](https://github.com/ngx-formly/ngx-formly/files/3659887/ynevkxlbdlk.angular.zip)

 If you run the sample, you will note that the Investment repeat section is not displayed.  If you then click submit, the form object is displayed in the console window.  Please inspect the object in the console window. Note, while the repeat section is NOT included in the DOM, it still exists in the form.controls.  This causes problems with validation on the form as the entire form.controls is validated, even though it is not displayed in the DOM.

**What is the motivation / use case for changing the behavior?**
I need the capability to filter out items in the repeat-section (and to exclude them from the controls array and hence any further validation)

**Please tell us about your environment:**

* **Angular version:** 8.0.0

* **Browser:** Chrome 

Version 77.0.3865.90

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
pass `hideExpression: true` to the field that you wish to remove from the controls.

https://stackblitz.com/edit/angular-ws2q9x

**Comment by silvl** [comment]
That would hide the entire repeat control.  I only want to hide one item in the array

**Comment by aitboudad** [comment]
> That would hide the entire repeat control. I only want to hide one item in the array

then pass the `hideExpression` inside fieldArray:
```ts
fieldArray: {
  hideExpression: 'field.key === "0"',
}
```
