### ISSUE TITLE
upgrading ngx-datatable to 16.0.x breaks ngx-formly datatable.type.ts(3,29): error TS2307: Cannot find module '@swimlane/ngx-datatable/release/types'.

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#1804]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
when using DataTable.type in ngx-formly upgrading to ngx-datatable v16.0.x leads to compilation failure and the above error message generated.

**Expected behavior**
DataTable.type.ts needs to be updated to the new directory structure implemented in ngx-datatable 16.0.x

**Minimal reproduction of the problem with instructions**
using @ngx-formly/core@latest and @swimlane/ngx-datatable@latest
copy the below code into a file called "datatable.type.ts"

`import { Component, ViewChild, TemplateRef, OnInit } from '@angular/core';
import { FormlyFieldConfig, FieldArrayType } from '@ngx-formly/core';
import { TableColumn } from '@swimlane/ngx-datatable/release/types';

@Component({
  selector: 'formly-field-datatable',
  template: `
    <ngx-datatable
      #table
      class="material"
      [rows]="model"
      [columns]="to.columns"
      [columnMode]="to.columnMode"
      [rowHeight]="to.rowHeight"
      [headerHeight]="to.headerHeight"
      [footerHeight]="to.footerHeight"
      [limit]="to.limit"
      [scrollbarH]="to.scrollbarH"
      [reorderable]="to.reorderable"
      [externalSorting]="true"
      [selectionType]="'single'">
      <ng-template #defaultColumn ngx-datatable-cell-template let-rowIndex="rowIndex" let-value="value" let-row="row" let-column="column">
        <formly-field [field]="getField(field, column, rowIndex)"></formly-field>
      </ng-template>
    </ngx-datatable>
`,
})
export class DatatableTypeComponent extends FieldArrayType implements OnInit {
  @ViewChild('defaultColumn') public defaultColumn: TemplateRef<any>;

  ngOnInit() {
    this.to.columns.forEach(column => column.cellTemplate = this.defaultColumn);
  }
  getField(field: FormlyFieldConfig, column: TableColumn, rowIndex: number): FormlyFieldConfig {
    return field.fieldGroup[rowIndex].fieldGroup.find(f => f.key === column.prop);
  }
}`

**What is the motivation / use case for changing the behavior?**
the current fix is to update the import statement to
import { TableColumn } from '@swimlane/ngx-datatable/lib/types/table-column.type';

Please refer to the change log of @swimlane/ngx-datatable located here for changes

https://github.com/swimlane/ngx-datatable/blob/master/docs/changelog.md

**Please tell us about your environment:**

* **Angular version:** 2.0.X
Angular 7.3.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =
10.x

**Comment by argupta23** [comment]
@aitboudad 

Thanks for assigning the appropriate tag to it.

Wanted to make sure that it was captured, in case others ran into the same issue.

**Comment by aitboudad** [comment]
Thanks!
