### ISSUE TITLE
Kendo radio template is missing name property

### ISSUE THREAD

**Issue by patrickrioux** [ngx-formly/ngx-formly#1805]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
The Kendo radio group is allowing more than one option being checked.

**Expected behavior**
Kendo radio group should allow one selected value

**Minimal reproduction of the problem with instructions**
Kendo radio group example should replicate that issue. I am new to ngx-formly and not quite sure if something is missing in my code below.  

Kendo radio template doesn't have the name property set. I've created a custom template trying to fix this issue but for some reason name isn't assigned at all in the generated html code. When is possible to check more than one radio value is because the name properly is not set.

If I manually assign the name property using the Chrome dev tool, the radio group is working as expected.

For some reason, the name is not assigned to the generated html below. Just the ng-reflect-name is. Not sure what the problem is and how to resolve.

Thank you so much for you guidance.
-Patrick

--

**Custom Kendo radio template**
`<ng-container *ngFor="let option of to.options | formlySelectOptions:field | async; let i=index;">
  <input type="radio" **[name]="id"** [id]="id + '_' + i" [value]="option.value" [formControl]="formControl"
    [formlyAttributes]="field" class="k-radio" />
  <label class="k-radio-label" [for]="id + '_' + i">{{ option.label }}</label>
</ng-container>
<small *ngIf="to.description" class="form-text text-muted">{{ to.description }}</small>`

**Generated HTML**
`<app-formly-field-radio _nghost-gre-c21="" class="ng-star-inserted"><input _ngcontent-gre-c21="" class="k-radio ng-star-inserted ng-touched ng-dirty ng-valid" type="radio" ng-reflect-name="formly_7_radio_Radio_3" ng-reflect-value="1" ng-reflect-form="[object Object]" id="formly_7_radio_Radio_3_0" required="required" placeholder="Placeholder" ng-reflect-field="[object Object]"><label _ngcontent-gre-c21="" class="k-radio-label ng-star-inserted" ng-reflect-for="formly_7_radio_Radio_3_0" for="formly_7_radio_Radio_3_0">Option 1</label><input _ngcontent-gre-c21="" class="k-radio ng-star-inserted ng-touched ng-dirty ng-valid" type="radio" ng-reflect-name="formly_7_radio_Radio_3" ng-reflect-value="2" ng-reflect-form="[object Object]" id="formly_7_radio_Radio_3_1" required="required" placeholder="Placeholder" ng-reflect-field="[object Object]"><label _ngcontent-gre-c21="" class="k-radio-label ng-star-inserted" ng-reflect-for="formly_7_radio_Radio_3_1" for="formly_7_radio_Radio_3_1">Option 2</label><input _ngcontent-gre-c21="" class="k-radio ng-star-inserted ng-touched ng-dirty ng-valid" type="radio" ng-reflect-name="formly_7_radio_Radio_3" ng-reflect-value="3" ng-reflect-form="[object Object]" id="formly_7_radio_Radio_3_2" required="required" placeholder="Placeholder" ng-reflect-field="[object Object]"><label _ngcontent-gre-c21="" class="k-radio-label ng-star-inserted" ng-reflect-for="formly_7_radio_Radio_3_2" for="formly_7_radio_Radio_3_2">Option 3</label><input _ngcontent-gre-c21="" class="k-radio ng-star-inserted ng-touched ng-dirty ng-valid" type="radio" ng-reflect-name="formly_7_radio_Radio_3" ng-reflect-value="4" ng-reflect-form="[object Object]" id="formly_7_radio_Radio_3_3" required="required" placeholder="Placeholder" ng-reflect-field="[object Object]"><label _ngcontent-gre-c21="" class="k-radio-label ng-star-inserted" ng-reflect-for="formly_7_radio_Radio_3_3" for="formly_7_radio_Radio_3_3">Option 4</label><small _ngcontent-gre-c21="" class="form-text text-muted ng-star-inserted">This is the field description for radio</small></app-formly-field-radio>`

**Comment by aitboudad** [comment]
the fix is now part of [v5.5.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.0) release!
