### ISSUE TITLE
Disable Field Doesn't update the the form value. 

### ISSUE THREAD

**Issue by ajay1208** [ngx-formly/ngx-formly#1810]
I have conditional hidden and disabled field and i try to assign the values with model assign.  The values are not patched to the forms.

**Current behavior**
Values are not patching to form

**Expected behavior**
Values are patched to the form

I have provided the stackblitz example in the below link.

https://stackblitz.com/edit/angular-fdjd5u

1. enter value in line 1
2. click option 2 radio
3. now you should see line 2 disable fields and patched with line  value.  
4. But if you check the form.value the line two are not there in json object.

**Comment by aitboudad** [comment]
that's expected, the disabled field doesn't emit a value so instead, you may use `readonly`:
```ts
expressionProperties: {
  "templateOptions.readonly": "model.Radio != 1"
},
```

**Comment by ajay1208** [comment]
If we use native select, checkbox then we are not able to use the readonly property.

**Comment by aitboudad** [comment]
well that something we may try to support in the future version (maybe `v6`).
for now, you can apply some custom `css` to make them as readonly

**Comment by aitboudad** [comment]
Hi, just figured out that you can get the form value including any disabled field using 
`getRawValue` method:

```ts
form.getRawValue()
```
