### ISSUE TITLE
Having issues in the latest version for input type file value accessor

### ISSUE THREAD

**Issue by albertthinc** [ngx-formly/ngx-formly#1814]
I am using ngx-formly v5.1.9. 
Using the input type file and value accessor working perfectly fine.

When I updated to latest version, I am getting invalid error when accessing the file object.

Because of this I am not able upload the file using ngx-uploader.

Https://stackblitz.com/edit/angular-b4y2qf

**Comment by aitboudad** [comment]
the issue has been fixed in `5.4.3`, just update the `formly` version and it should work!
