### ISSUE TITLE
There is no type by the name of "repeat"  error 

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#1815]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ x] support request
```

**Current behavior**
When calling a Formly form component in a different component which includes a "Repeat" / " Wrapper" type we get the following error

`DeviceaddDialog.html:4 ERROR Error: [Formly Error] There is no type by the name of "repeat"
    at FormlyConfig.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.FormlyConfig.getType (ngx-formly-core.js:400)
    at FormlyConfig.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.FormlyConfig.createComponent (ngx-formly-core.js:474)
    at CoreExtension.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.CoreExtension.getFieldComponentInstance (ngx-formly-core.js:2979)
    at CoreExtension.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.CoreExtension.prePopulate (ngx-formly-core.js:2805)
    at ngx-formly-core.js:702
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.FormlyFormBuilder._buildForm (ngx-formly-core.js:698)
    at ngx-formly-core.js:713
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.FormlyFormBuilder._buildForm (ngx-formly-core.js:709)
View_DeviceaddDialog_0 @ DeviceaddDialog.html:4
proxyClass @ compiler.js:18239
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24139
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15772
(anonymous) @ core.js:18126
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:18126
(anonymous) @ core.js:18010
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:17213
next @ core.js:18010
schedulerFn @ core.js:13515
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13499
checkStable @ core.js:17268
onHasTask @ core.js:17312
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:443
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:463
push../node_modules/zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:291
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:212
drainMicroTaskQueue @ zone.js:601
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
Show 3 more frames
DeviceaddDialog.html:4 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 11, nodeDef: {…}, elDef: {…}, elView: {…}}
View_DeviceaddDialog_0 @ DeviceaddDialog.html:4
proxyClass @ compiler.js:18239
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24139
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15777
(anonymous) @ core.js:18126
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17258
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:18126
(anonymous) @ core.js:18010
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17299
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:17213
next @ core.js:18010
schedulerFn @ core.js:13515
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:192
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:130
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:76
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:53
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:13499
checkStable @ core.js:17268
onHasTask @ core.js:17312
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.hasTask @ zone.js:443
push../node_modules/zone.js/dist/zone.js.ZoneDelegate._updateTaskCount @ zone.js:463
push../node_modules/zone.js/dist/zone.js.Zone._updateTaskCount @ zone.js:291
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:212
drainMicroTaskQueue @ zone.js:601
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
Show 3 more frames
DeviceaddDialog.html:4 ERROR TypeError: Cannot read property 'formState' of undefined
    at FieldExpressionExtension.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.FieldExpressionExtension.checkFieldVisibilityChange (ngx-formly-core.js:2434)
    at ngx-formly-core.js:2353
    at Array.forEach (<anonymous>)
    at FieldExpressionExtension.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.FieldExpressionExtension._checkField (ngx-formly-core.js:2347)
    at Object._checkField (ngx-formly-core.js:2200)
    at FormlyForm.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.FormlyForm.checkExpressionChange (ngx-formly-core.js:1002)
    at FormlyForm.push../node_modules/@ngx-formly/core/fesm5/ngx-formly-core.js.FormlyForm.ngDoCheck (ngx-formly-core.js:872)
    at checkAndUpdateDirectiveInline (core.js:22102)
    at checkAndUpdateNodeInline (core.js:23363)
    at checkAndUpdateNode (core.js:23325)`

**Expected behavior**
Should work. 
Form load right if you remove reference to Repeat and Wrapper

**Minimal reproduction of the problem with instructions**
Can provide more details if needed.

**What is the motivation / use case for changing the behavior?**
It is not clear to me if this is a bug or if I am doing something wrong.

**Please tell us about your environment:**
Ubuntu- Bionic, Node 10.x, @ngx-formly/core@5.4.3

* **Angular version:** 2.0.X
Angular 7.3.x, 

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by argupta23** [comment]
@aitboudad 
I was able to get around the issue by creating a separate Module for the different ngx-formly types all combined into one and then importing it into the required modules.

For some reason defining in app.module was not working for me when the Formly component/module was being called by another module/component via a button that would open a mat-dialog containing the form.

If you can please try it on your side and check if there is a bug that would be greatly appreciated.

**Comment by aitboudad** [comment]
Hi, can you provide a reproduction example using our stackblitz starter example https://stackblitz.com/angular/ynevkxlbdlk

Thanks!

**Comment by argupta23** [comment]
> Hi, can you provide a reproduction example using our stackblitz starter example https://stackblitz.com/angular/ynevkxlbdlk
> 
> Thanks!

@aitboudad 
Yes, I will create one and share it with you in a couple of days.

Thanks

**Comment by aitboudad** [comment]
just ensure to register the `repeat` type in a shared module which both components rely on.
