### ISSUE TITLE
how to integrate Ace-editor / Monaco-editor? 

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#1816]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**
Looking for an example / guidance that enables integrating editors like ace-editor / monaco-editor as input field 

@ng2-ace-editor / monaco-editor

Thanks in advance for your help.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
just follow our guide https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field

**Comment by argupta23** [comment]
@aitboudad 

Appreciate the pointer

I created a wrapper below and am able to save the data input, but when I try to read that data back into the wrapper it does not seem to work. I feel that I am missing something basic here. 

Can I please request your help to see what I am doing wrong?

Thanks

Wrapper Component
import {  Component, EventEmitter, forwardRef, Input, Output  } from '@angular/core';
import { FieldType } from '@ngx-formly/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
 selector: 'formly-field-input',
 template: 
 < div ace-editor
  [(text)]="text" 
  [mode]="'javascript'" 
  [theme]="'eclipse'"
  [readOnly]="false"
  [autoUpdateContent]="true" 
  [durationBeforeCallback]="1000" 
  (textChanged)="onChange($event)"
  style="min-height: 200px; width:100%; overflow: auto;">< / div >

})

export class AceEditorFormlyComponent  extends FieldType implements ControlValueAccessor {

  text:string = "";
  options:any = {maxLines: 1000, printMargin: false};
  
  onChange(code) {
    this.formControl.setValue(
      (this.formControl.value || '') + code
    );
      console.log("new code", code);
  }


**app.component.ts**

`  options: FormlyFormOptions = {};
  dataHandlerModel: any = {};
  dataHandlerForm = new FormGroup({});
  dataHandlerFields: FormlyFieldConfig[] = [
    {
      fieldGroupClassName: 'display-flex',
      wrappers: ['panel'],
      templateOptions: { label: 'Data - Parsing Logic' },
      fieldGroup: [
        { type: 'aceditor', key: 'parserfunction', className: 'flex-1', templateOptions: { label: 'Data Handler Details', placeholder: 'Data Parsing Logic ', type: 'string', required: true, }, },
      ]
    },
  ];
`

**the JSON model looks like below**
`
{
  "parserfunction": "tetedfsfdstetedfsfds\n\nfdsfds\n\ndfs\n",
   "id": "5dd82322b9fa590e2be3b4b1",
 }`


here are some pointers to help you

([(https://github.com/fxmontigny/ng2-ace-editor/issues/71)])
[https://stackoverflow.com/questions/34761399/angular2-2-way-databinding-between-parent-component-and-directive]
