### ISSUE TITLE
UpperCase on fields json

### ISSUE THREAD

**Issue by josepacelli** [ngx-formly/ngx-formly#1819]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 7.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

There is a way to uppercase the key value?

**Comment by josepacelli** [comment]
There is a way to uppercase the key value on input key press or exit?

**Comment by aitboudad** [comment]
do you mean to uppercase the field key or the field value?

**Comment by josepacelli** [comment]
the field value

SORRY!

**Comment by aitboudad** [comment]
use `parsers`:

```ts
{
  key: 'name',
  parsers: [toUpperCaseFn]
}
```

**Comment by josepacelli** [comment]
Thanks

**Comment by saurabh1234** [comment]
@josepacelli  and @aitboudad  could you please give an example of how an `toUpperCaseFn` function might look like. I am defining my formly config in `.json` files so i was wondering this will work or not.

**Comment by aitboudad** [comment]
@saurabh1234 use one of the following methods:

- To provide a global way to customize fields (`toUpperCaseFn` for example) in all your forms, use custom extension which allows you to update field during the build step (check i18n example https://formly.dev/examples/advanced/i18n-alternative)
- In case you want just to apply it for a specific field, then an extension is not needed just adjust the fields on load see https://github.com/ngx-formly/ngx-formly/issues/1102#issuecomment-411491538

**Comment by josepacelli** [comment]
To key value and on form stay in UPPERCASE. 

```
{
    fieldGroupClassName: 'row',
    fieldGroup: [
        {
            className: 'col-12 col-sm-6',
            key: 'name',
            type: 'input',
            defaultValue: null,
            templateOptions: {
                label: 'Nome:',
                required: true,
                placeholder: 'Nome do usuário',
                minLength: 3,
                attributes: {
                    style: 'text-transform: uppercase'
                }
            },
            parsers: [
                value => {
                    return (value = value.toUpperCase());
                }
            ]
        }
    ]
}
```

**Comment by annelaureducrocq** [comment]
@josepacelli I tried to use your first solution and I can see my input in upper case but when I look into the internal form, my input is still in lower case...

{
    fieldGroupClassName: 'flex-container',
    fieldGroup: [
        {
            className: 'mat-form-field',
            key: 'name',
            type: 'input',
            defaultValue: null,
            templateOptions: {
                label: 'Name:',
                attributes: {
                    style: 'text-transform: uppercase'
                }
            },
            parsers: [
                value => {
                    return (value = value.toUpperCase());
                }
            ]
        }
    ]
}
