### ISSUE TITLE
extending FieldArrayType requires the control is added onInit

### ISSUE THREAD

**Issue by internalsystemerror** [ngx-formly/ngx-formly#1829]
I'm not exactly sure why this happens. I have a custom control:

```
@Component({
    selector: 'custom-options',
    templateUrl: './options.component.html',
    styleUrls: ['./options.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class OptionsComponent extends FieldArrayType implements OnInit {
    ngOnInit(): void {
        if (!this.form.contains(this.key)) {
            this.form.addControl(this.key, this.formControl);
        }
    }
}
```

If I do not add the control in ngOnInit(), then upon navigating to the form the control isn't added to the parent form. I'm not convinced this would be repeatable outside of my code and I'm unable to use stackblitz successfully due to my cookie settings (I've tried to solve that before but gave up).

The field configuration is used as follows:

```
{
        key: 'options',
        type: 'options',
        model: [{}],
        templateOptions: {
            label: 'Options',
            addText: 'Add New Option'
        },
        fieldArray: {
            fieldGroupClassName: 'row',
            fieldGroup: [
                // some inputs here
            ]
        }
    }
```

Does anybody who knows the code better have any idea why this is required, if there's something I may be missing? Alternatively, is anyone able to reproduce this. My steps without this fix resulted in:

Using OnPush Change Detection
Load a page with a form on that contains the options
Console.log the form (options control exists)
Navigate to a page without any form
Navigate back to the form page
Console.log the form (options control doesn't exist)

**Comment by aitboudad** [comment]
Hi, can you replicate your example using our stackblitz starter example https://stackblitz.com/angular/ebxkvelexle
Thanks!
