### ISSUE TITLE
initialize repeat sections with value within the form

### ISSUE THREAD

**Issue by mathpaquette** [ngx-formly/ngx-formly#1831]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I'm using repeatable blocks within a form containing fields. Most of our forms come from JSON based config so I don't have the flexibility to use functions. In the repeatable section, I wish to be able to copy value from the main form if this one is available when adding a new section. Is it possible somehow to use defaultValue in such way to refer model.someField? 

Please about some ways of doing it. It could be through JSON or code.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Formly 5.5
Angular 7+

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
use custom extension which allows you to adjust fields during the build step, you may check the following examples:

- https://ngx-formly.github.io/ngx-formly/examples/advanced/i18n-alternative
- https://ngx-formly.github.io/ngx-formly/examples/other/material-prefix-suffix
