### ISSUE TITLE
Unable to set value to FormControl

### ISSUE THREAD

**Issue by saadmomin** [ngx-formly/ngx-formly#1832]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**

I am creating a form to create Ad listings by generating formly fields with an API object. All the fields are created properly, the form works great on its own along with select bindings and everything. However, I am trying to use the same form also for editing the same listing. I am able to pass the value to all the field's formcontrols. However, it is not working with selects. I tried several methods like setting the value directly to the form, changing the model property values, using hooks (OnInit and afterContentInit). As I see in the output, the value is assigned to the formControl, however the field does not populate with that value. Also, the options of the fields aren't loaded too. 

**Expected behavior**
Want to select one of the option as the value of the select (I have multiple of such selects).

**What is the motivation / use case for changing the behavior?**
Need to use the same form to create and update.

**Please tell us about your environment:**
Formly 5

* **Angular version:** 2.0.X
Angular 8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

* **Language:** [ TypeScript]

**Comment by aitboudad** [comment]
Hi, can you provide a reproduction example using our stackblitz starter example https://stackblitz.com/angular/yggqbdbmynn
Thanks!

**Comment by saadmomin** [comment]
Hi. @aitboudad. Sorry for such a late response. I am so happy you haven't closed the issue. It took me a long time to repro this in stackblitz. I have deployed a simple version of what I am doing inside stackblitz. I am using json however all the data comes from the api. I have added a simple button for injecting existing "listing" in the formly form but that is actually suppose to work like an Edit form for existing listing. When I inject it, the input fields are populated with the existing values but selects are not. Need some help with that.

https://stackblitz.com/edit/formly-dynamic-api-form

Thanks a ton,
Saad

**Comment by aitboudad** [comment]
but your select fields doesn't seem to have options, the selected value should be included in options in order to be displayed.

**Comment by saadmomin** [comment]
> but your select fields doesn't seem to have options, the selected value should be included in options in order to be displayed.

**Comment by saadmomin** [comment]
Sorry closed it by mistake. i am having a hard time with this. Trying something which I think will work. Will update. Thanks

**Comment by saadmomin** [comment]
Thanks a ton. I was able to resolve the issue. I just checked for the selectedValue prop in the existingListing and matched it with the option Ids. Thanks a ton man!!!
