### ISSUE TITLE
Regression v5.5.0 - ngModelChange / Maximum call stack size exceeded

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1841]
```
[x] bug report
```

Upgraded from v5.4.3 to v5.5.0 and have a regression.

I have a ng-selectize type. When selecting a/another option (ngModelChange) is called.

Since the upgrade the method is repeatedly called and ends in a "Maximum call stack size exceeded".

[https://stackblitz.com/edit/angular-ffxroy](https://stackblitz.com/edit/angular-ffxroy?file=src%2Fapp%2Fng-selectize.type.ts)

**Comment by aitboudad** [comment]
fixed in `5.5.1`
