### ISSUE TITLE
When removing fields dynamically, the invalid state is not updated

### ISSUE THREAD

**Issue by Devqon** [ngx-formly/ngx-formly#1846]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
When removing a field dynamically (in my example, based on a selected value in a dropdown), the validation of the field is still taken in account on the form validation.

**Expected behavior**
When removing a field from the formly configuration, the validation of that field does not cause the form to be invalid.

**Minimal reproduction of the problem with instructions**
Remove a required, **empty valued** field after initializing the form. Trigger a validation (with submit).
See [this example](https://stackblitz.com/edit/angular-danpyt)

**What is the motivation / use case for changing the behavior?**
I have dynamic forms based on the first field. Fields can be added and removed dynamically based on the selected value.

**Please tell us about your environment:**
Not applicable

* **Angular version:** 2.0.X
7.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =
Not applicable

**EDIT**
This might be actually an angular bug, because when viewing the form the control is still in the controls of the `FormGroup`.

**Comment by aitboudad** [comment]
that's a known [issue](https://github.com/ngx-formly/ngx-formly/issues/1398#issuecomment-458543578) which we'll try to solve it by introducing a `strict` mode which cleanup the removed field and its control.

initialize the `form` to solve the issue:

```ts
this.fields = ...
this.form = new FormGroup({});
```
