### ISSUE TITLE
Change not triggered after custom Input update model

### ISSUE THREAD

**Issue by nobald282** [ngx-formly/ngx-formly#1851]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

legend:

FORM: the controller where is declared the form.
CUSTOM_INPUT: the custom input created with ngx-form.
COMPONENT: the component declared in the template of CUSTOM_INPUT.

I created a custom type input in ngx-formly, the template of this custom input is COMPONENT that bind out a value with formControl (COMPONENT implements ControlValueAccessor).
COMPONENT is formed by 3 select box.
When value of COMPONENT is bind to CUSTOM_INPUT, i try to bind it with this.formControl.setValue(myValue); to FORM.
The problem is that "change" method of templateOptions of CUSTOM_INPUT it not trigger.
I try also to pass formlyAttributes to COMPONENT and i see that if i set formlyAttributes to my 3 select box of COMPONENT the method change in FORM is triggered, but is triggered every time that i change value of one of the 3 selectbox of COMPONENT.

**Expected behavior**
I expected that the change event is triggered when formControl.setValue(MyValue) is called inside CUSTOM_INPUT.

**Minimal reproduction of the problem with instructions**
This is a use case found on google that is exactly the same of my problem.
https://stackblitz.com/edit/angular-ngx-formly
Just add

`change: (field: FormlyFieldConfig, event?: any) => { debugger }`

in templateOptions of

`fields: FormlyFieldConfig[] = [ { key: 'state'.....`
  
in app.component.ts file

**What is the motivation / use case for changing the behavior?**
I expected to can create custom ngx-form input that use custom input component like template.
In this case with 3 select, i can't use formlyAttributes, for the problem of triggering that i said before.

**Please tell us about your environment:**
Ubuntu 18.04, Visual Studio Code, npm

* **Angular version:**
8.2.9

* **Browser:**
Chromium 77

* **Language:**
TypeScript 3.6.0

* **Node (for AoT issues):**
`node --version` = 10.16.3

**Comment by aitboudad** [comment]
the `change` callback is triggered when the UI changes, for UI & programmatically changes may use `formControl.valueChanges`:

```ts
export class AppComponent implements OnDestroy {
  onDestroy$ = new Subject<void>();

  fields: FormlyFieldConfig[] = [
    {
      key: 'name',
      hooks: {
        onInit: (field) => {
          field.formControl.valueChanges
            .pipe(takeUntil(this.onDestroy$))
            .subscribe(value => { ... });
        },
      },
    }
  ];

  ngOnDestroy(): void {
    this.onDestroy$.next();
    this.onDestroy$.complete();
  }
}
```

we'll try to simplify it in the future to something like:
```ts
{
  key: 'name',
  valueChanges: ({ field, value }) => { ... },
}
```

**Comment by nobald282** [comment]
I tried it and it works with my custom input! Thank you for the explanation

**Comment by comrem** [comment]
@aitboudad I'm sorry to bother you but I'm unable to use the valueChange prop, and after checking in releases notes I didn't found any reference to #2244, commit ef0eb11 or 4b6764c. I've even checked in my formly node modules and didn't find it either.

I've formly 5.10.6 installed :
```
├─ @ngx-formly/core@5.10.6
├─ @ngx-formly/schematics@5.10.6
```

**Comment by aitboudad** [comment]
@comrem not part of `v5` releases, here is an alternative way:

```ts
{
  hooks: {
    onInit: (field) => {
      // subscription and unsubscribe is handled by formly
      return field.formControl.valueChanges
        .pipe(tap(value => console.warn(value))),
      ;
    }
  }
}
```

**Comment by comrem** [comment]
@aitboudad ok, thanks for the quick answer ! I already used the alternative way because you provided it above, just wanted to make it as clean as possible and wasn't able wasn't able to find the valuChange propertie while the PR was tag as merged.

Have a nice day and keep up the good work !

**Comment by hitha2688** [comment]
Hi team,
would like to get help on how to change the type of input dynamically,lets say from input field to autocomplete based on a condition.Any help is highly appreciated!!

**Comment by codehit8826** [comment]
Hi team,
would like to get help on how to change the type of input dynamically,lets say from input field to autocomplete based on a condition.Any help is highly appreciated!!
