### ISSUE TITLE
`select all` does not work in multiselect with group

### ISSUE THREAD

**Issue by fontsie** [ngx-formly/ngx-formly#1852]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

When a select has grouped options, nothing happens when click `select all`.

**Expected behavior**

Select all!!

Ref -> https://github.com/ngx-formly/ngx-formly/pull/1552#pullrequestreview-300719356

**Comment by aitboudad** [comment]
[v5.5.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.2) is released which includes a fix for this issue!

**Comment by fontsie** [comment]
Super! Thanks a lot
