### ISSUE TITLE
Passing array with field to custom type

### ISSUE THREAD

**Issue by Et3rnal** [ngx-formly/ngx-formly#1856]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**
The value within the array doesn't change

**Expected behavior**
Model to reflect the nested changes (in the array)

**Minimal reproduction of the problem with instructions**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-3mqe3u

I know the above is definitely wrong, I have tried a few other things without luck but this is the one that compiles without problem 

**What is the motivation / use case for changing the behavior?**
I have an array of 3 values in my modal which needs to be presented in a table with checkbox
`{
name: "the name",
type: "The type",
isChecked: true,
}`
I created a custom template which takes the array and represents the data but lost at the last column (checkbox) not sure what is the right way to achieve that.

* **Angular version:** 8.0
* **Browser:** [all]
* **Language:** [all]

**Comment by aitboudad** [comment]
use field array type instead https://stackblitz.com/edit/ngx-formly-ui-bootstrap-3qhxfc
