### ISSUE TITLE
Model update not seen in formly-field but in interpolated field

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1858]
```
[x] support request
```

**Current behavior**
[https://stackblitz.com/edit/angular-e241wn](https://stackblitz.com/edit/angular-e241wn?file=src/app/datatable.type.ts)

What is the reason that the view of a formly-field is not updated and the value of an interpolated field is updated, after the model changed ?

Is there a way to force the update for the formly type (and it's children)?

**Comment by aitboudad** [comment]
model inside field type is `readonly` to prevent losing its ref, changing the model value should go throughout the `formControl` instead.
