### ISSUE TITLE
Disabling form fills all empty fields in the model with null

### ISSUE THREAD

**Issue by swillisstudio** [ngx-formly/ngx-formly#1861]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When having optional fields, calling the disable method on the form fills those fields in the model with null as the value.

**Expected behavior**
Disabling the form shouldn't update any model values.

**Minimal reproduction of the problem with instructions**
[Stackblitz](https://stackblitz.com/edit/angular-qx5tcv)
Filling in the required field and clicking submit, you can see the json shows the optional fields with null. Removing the form.disable line and trying again will show only the populated field is in the model.

**Comment by aitboudad** [comment]
the initial value for `formControl` is `null` which is emitted during `disable` call, the proper fix is to change the initial value to `undefined` but it would introduce a breaking change so I postpone it to the next major version (`v6`), you may use the following workaround instead: 

```ts
this.form.disable({ emitEvent: false });
```
