### ISSUE TITLE
[SUPPORT] input type="tel" for angular material

### ISSUE THREAD

**Issue by vishnu-dev** [ngx-formly/ngx-formly#1863]
**I'm submitting a support request**  (check one with "x")
```
[ ] bug report
[ ] feature request
[ X ] support request
```

**Current behavior**

Specifying `type='tel'` doesn't work

**Expected behavior**

`type='tel'` should look something like [this](https://stackblitz.com/angular/jnejqgdmlbb?file=app%2Finput-prefix-suffix-example.ts)

**Minimal reproduction of the problem with instructions**

Current Angular Material Behaviour
https://stackblitz.com/angular/jnejqgdmlbb?file=app%2Finput-prefix-suffix-example.ts

**What is the motivation / use case for changing the behavior?**

Phone number as input should be supported

**Please tell us about your environment:**

* **Angular version:** 8.3.X

* **Browser:** all

* **Language:** all

**Comment by aitboudad** [comment]
create a custom field type, below some links may help:
- https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field
- https://github.com/ngx-formly/ngx-formly/issues/806#issuecomment-373299577

**Comment by vishnu-dev** [comment]
I agree to use a custom template, But shouldn't this be supported natively by `ngx-formly` as it is supported by `Angular Material`?

**Comment by aitboudad** [comment]
could you tell me which part do you mean by supported by Angular Material:
- prefix-suffix
- `tel` type

**Comment by aitboudad** [comment]
- for prefix-suffix check https://ngx-formly.github.io/ngx-formly/examples/other/material-prefix-suffix

- for `tel` type, pass `type`throughout `templateOptions`:

```ts
{
  type: 'input',
  templateOptions: { type: 'tel' },
}
```

**Comment by vishnu-dev** [comment]
I meant `tel` type and this
```
{
  type: 'input',
  templateOptions: { type: 'tel' },
}
```
is not working.

**Comment by aitboudad** [comment]
still, don't get it, could you please describe to me what going wrong with the following example https://stackblitz.com/edit/angular-b9vm5j 🤔, thanks!

**Comment by vishnu-dev** [comment]
Really sorry. Totally misunderstood the way it works. `type='tel'` is no different than a `type=number` input. Thanks for assisting BTW.

**Comment by lartheon** [comment]
> still, don't get it, could you please describe to me what going wrong with the following example https://stackblitz.com/edit/angular-b9vm5j 🤔, thanks!

This still allows you to enter alpha characters, it should only accept integer values.

**Comment by aitboudad** [comment]
@lartheon use can pass a pattern to validate the entered phone number, there is an example of pattern usage in our doc https://formly.dev/examples/validation/built-in-validations or create a custom field type https://formly.dev/guide/custom-formly-field which rely on angular lib for phone.

**Comment by lartheon** [comment]
Thank you, I'll try it out

**Comment by lartheon** [comment]
> @lartheon use can pass a pattern to validate the entered phone number, there is an example of pattern usage in our doc https://formly.dev/examples/validation/built-in-validations or create a custom field type https://formly.dev/guide/custom-formly-field which rely on angular lib for phone.

I got it working, however email doesn't seem to work, I thought Formly validated email addresses out of the box. If not, could you direct me to an example of how to implement and email only field correctly?
Thank you
