### ISSUE TITLE
Formly-Wrapper is not working with Kendo Panel Bar

### ISSUE THREAD

**Issue by joharzmn** [ngx-formly/ngx-formly#1868]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

I have created a wrapper (Kendo Panel Bar) to wrap formly control inside that wrapper. 
Code for Wrapper: 
```html
 <kendo-panelbar>
            <kendo-panelbar-item [title]="to.label" expanded="false">
                <ng-template kendoPanelBarContent>                    
                    <div>
                      <ng-container #fieldComponent></ng-container>
                    </div>

                </ng-template>
            </kendo-panelbar-item>
        </kendo-panelbar>
```

Fields Json: 
```
{
              fieldGroupClassName: "diplay-flex",
              fieldGroup: [
                {
                  className: "flex-1",
                  key: "key",
                  wrappers: ['auty-panel'],
                  type: "grid",
                  templateOptions: {
                    id: "fieldsMapping",
                    label: 'Other Fields',
                   }                  
                }
              ]
            }
```

**Expected behavior**

It should show the control inside the Wrapper which is Kendo Panel Bar.  

**Minimal reproduction of the problem with instructions**
Link to reproduce:
https://stackblitz.com/edit/angular-igoaqx

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**Vscode, npm

* **Angular version:** 7.3.7

* **Browser:** Latest Chrome

* **Language:** [all]

**Comment by aitboudad** [comment]
register kendo panel bar as a type instead:

```patch
@Component({
  template: `
    <kendo-panelbar>
      <kendo-panelbar-item [title]="to.label" expanded="false">
        <ng-template kendoPanelBarContent>                    
          <div>
+            <formly-field *ngFor="let f of field.fieldGroup" [field]="f"></formly-field>
-            <ng-container #fieldComponent></ng-container>
          </div>
        </ng-template>
      </kendo-panelbar-item>
    </kendo-panelbar>
  `,
})
export class KendoPanelbarTYPE extends FieldType {
  defaultOptions = {
    defaultValue: {},
  };
}
```


Fields Json:

```patch
{
+  type: 'auty-panel',
  fieldGroup: [
    {
      className: "flex-1",
      key: "key",
-      wrappers: ['auty-panel'],
      type: "grid",
      templateOptions: {
        id: "fieldsMapping",
        label: 'Other Fields',
      }                  
    }
  ]
}
```

**Comment by joharzmn** [comment]
@aitboudad Thanks for the suggestion but Actually I need this to work generically with all the types. 
Because I have so many types I need to wrap those fields into a wrapper(Kendo Panel Bar), So I cannot create two types one with Panel bar and one without Panel bar.

**Comment by joharzmn** [comment]
@aitboudad Is there any way we can achieve the above functionality?

**Comment by aitboudad** [comment]
Unfortunately, that's the only solution because the kendo panel destroys the view created by `formly` when toggling the panel.
I have an idea to make work with wrapper but require some time to be implemented (probably in `v6`).

Sorry about that 🙏!

**Comment by joharzmn** [comment]
Okay, no problem.  Thanks for the help

**Comment by joharzmn** [comment]
I just wanted to say thank you so much for this wonderful product. 

We really want to show our appreciation for your quick response and help so we are donating $50 and then another $50  once you let us know when this feature is ready? When do you think your idea will be ready?

**Comment by aitboudad** [comment]
Your support is highly appreciated ❤️!

> When do you think your idea will be ready?

Will be available in the next major version (`v6`) (may take up to 3 months), but if you really need that feature soon I may provide you in private a workaround next week.

**Comment by joharzmn** [comment]
@aitboudad  
We tried to donate through paypal link but it's giving error 
![img](http://ta-snagit.s3.amazonaws.com/Donate_2019-10-25_05-51-33.png)

Is there any other way to donate? 
We really want this change, if you can provide private workaround it will be awesome. 

Thanks

**Comment by aitboudad** [comment]
revisited the issue again but I couldn't find any other workaround expect the above one, sorry about that 🙏

**Comment by joharzmn** [comment]
@aitboudad 
This response from Kendo may help: 
> After digging through the source code of ngx-formly, I found where the error is coming from - https://github.com/ngx-formly/ngx-formly/blob/ce3759d1d5d6594ce06f0a7f5775c68cc0e69f29/src/core/src/lib/components/formly.field.ts#L127 . It seems like the problem is that ngx-formly does not handle <ng-template> properly.

Thanks

**Comment by aitboudad** [comment]
I know the source of the issue, the wrapper should be resolved asynchronously instead in order to be resolved which a did but still facing some issues.
I'm checking it again.

**Comment by joharzmn** [comment]
> @aitboudad
> We tried to donate through paypal link but it's giving error
> ![img](https://camo.githubusercontent.com/5a6d54d0ee1dcb673da4b4d6577b4db9df3d77c7/687474703a2f2f74612d736e616769742e73332e616d617a6f6e6177732e636f6d2f446f6e6174655f323031392d31302d32355f30352d35312d33332e706e67)
> 
> Is there any other way to donate?
> We really want this change, if you can provide private workaround it will be awesome.
> 
> Thanks

@aitboudad Do you know anything about this error?

**Comment by aitboudad** [comment]
a fix will be landed in `5.5.2` release,
for the donation probably related to the payment card, I've sent to Bryan some other ways.

**Comment by joharzmn** [comment]
Okay Thank you 👍

**Comment by aitboudad** [comment]
[v5.5.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.2) is released which includes a fix for this issue!

**Comment by joharzmn** [comment]
@aitboudad Okay Thank you, I'll test it
