### ISSUE TITLE
Deeply nested model can't assign model value during initialization

### ISSUE THREAD

**Issue by 0x253** [ngx-formly/ngx-formly#1869]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
A deeply nested form (with some form groups, and a custom implemented `section` type) throws an error during initialization:
```
ERROR TypeError: Cannot set property 'c' of undefined
    at assignModelValue (utils.ts:42)
    at CoreExtension.initFieldOptions (core.ts:89)
    at CoreExtension.onPopulate (core.ts:30)
    at eval (formly.form.builder.ts:26)
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder._buildForm (formly.form.builder.ts:26)
    at eval (formly.form.builder.ts:29)
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder._buildForm (formly.form.builder.ts:29)
    at eval (formly.form.builder.ts:29)
```
Note that some form groups have a key, some of them have no key. The input text should be saved within the model path `a.b.c.d`.

**Expected behavior**
The form should initialize without error.

**Minimal reproduction of the problem with instructions**
See https://stackblitz.com/edit/angular-vgc8mm?file=src%2Fapp%2Fapp.component.ts

**What is the motivation / use case for changing the behavior?**
Bugfix

**Please tell us about your environment:**

* **Angular version:** 7.2.X

* **Browser:** all

* **Language:** Typescript

* **Node (for AoT issues):** `node --version` = 10.16.3

**Comment by aitboudad** [comment]
`section` type should define a `defaultValue` in order to work properly:

```patch
export class SectionComponent extends FieldType {
+  defaultOptions = {
+    defaultValue: {},
+  };
}
```

**Comment by 0x253** [comment]
> `section` type should define a `defaultValue` in order to work properly:
> 
> ```diff
> export class SectionComponent extends FieldType {
> +  defaultOptions = {
> +    defaultValue: {},
> +  };
> }
> ```

Thank you for your fast response! Should this be defined in every custom field group type? I implemented some other custom field group types, which work properly without initializing `defaultOptions`.

**Comment by aitboudad** [comment]
yes but in the next version `V6` grouped field can be nullable so defaultValue can be omitted, you may add a note:

```ts
export class SectionComponent extends FieldType {
  // TODO: remove defaultOptions once upgrading to `V6`
  defaultOptions = {
    defaultValue: {},
  };
}
```

**Comment by 0x253** [comment]
cool, thanks for clarification!
