### ISSUE TITLE
Getting NPM warning for Kendo package

### ISSUE THREAD

**Issue by patrickrioux** [ngx-formly/ngx-formly#1870]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[] support request
```

**Current behavior**
The Kendo UI dependencies need to be updated to use recent Kendo component.
When running NPM install, I am getting that following warning. I am actually using v4.2.0.

npm WARN @ngx-formly/kendo@5.5.1 requires a peer of @progress/kendo-angular-dropdowns@^3.2.0 but none is installed. You must install peer dependencies yourself.

**Expected behavior**
Changing the version dependencies to use the latest Kendo component will remove that warning.

Thank you.

**Comment by aitboudad** [comment]
for now, just ignore that message, change the version would produce some breaking changes for those who rely on the old version, we'll change the deps in our next major version `v6`.
Thanks for letting us 👍!
