### ISSUE TITLE
QUESTION: How can I delete all elements in a repeat-section via model

### ISSUE THREAD

**Issue by silvl** [ngx-formly/ngx-formly#1871]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

Is there any way to reset the model to [] for a repeat-section control? I know you can use remove/add to delete/insert new objects. But, if I want to set the model to the empty array [], using either the reset or setValue functions of angular, the controls in the repeat-section are not removed.

UI Bootstrap: https://stackblitz.com/edit/ngx-formly-ui-bootstrap

-->

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 8.0.X

* **Browser:** [all ]

* **Language:** [all]

* **Node (for AoT issues):** `node --version` =

**Comment by aitboudad** [comment]
from the AppComponent or inside the field type ?

**Comment by silvl** [comment]
From the app component.  Using .setValue or reset and setting it to []

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1522#issuecomment-482087551

**Comment by aitboudad** [comment]
@silvl Hi, can you provide a reproduction example using `stackblitz`.
Thanks!

**Comment by aitboudad** [comment]
if you want a solution, provide a reproduction example!
