### ISSUE TITLE
fieldArray resetModel() only works one time

### ISSUE THREAD

**Issue by daddel** [ngx-formly/ngx-formly#1872]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When dealing with with `fieldArray` / Repeating Section, the `options.resetModel()` only works the first time it is invoked.

**Expected behavior**
Each time `options.resetModel()` is invoked, I expect the form to reset to its initial state/values (or to the state/values set with `options.updateInitialValue()`)

**Minimal reproduction of the problem with instructions**
Added a reset button on a fork of the Repeating Section stackblitz:
https://stackblitz.com/edit/angular-4revlr

1. Enter text in `Name of Investment`
2. Click `Reset` => The form/model resets. ✔️ 
3. Enter text in `Name of Investment`
2. Click `Reset` => Nothing happens ❌ 

* **Formly version:**
"@ngx-formly/core": "^5.5.1"
"@ngx-formly/material": "^5.5.1"

**Comment by aitboudad** [comment]
[v5.5.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.2) is released which includes a fix for this issue.
