### ISSUE TITLE
Initialize a custom formly select type field using service

### ISSUE THREAD

**Issue by alabanu** [ngx-formly/ngx-formly#1877]
Hello,
I 've created a custom select type component using an api to fill the dropdown list.
There is a stackblitz example for this. 
[Stackblitz](https://stackblitz.com/edit/angular-formly-fed-select-jipxit?file=app%2Ffed-select-type.component.ts
)
The problem is that I want to initialize the select field  with a value from another api service  (like setting a default value).In fact,  I m using this code with groups where there is no constructor to call a service so I cant solve it. Any help?
[https://stackblitz.com/edit/ngx-formly-demo?file=src%2Fapp%2Fforms%2Fgroups%2Faddress.group.ts](https://stackblitz.com/edit/ngx-formly-demo?file=src%2Fapp%2Fforms%2Fgroups%2Faddress.group.ts)

**Comment by alabanu** [comment]
I ve changed it a bit. Can you please check out this stackblitz example? I can't set an initial value for the select type component
[https://stackblitz.com/edit/angular-formly-fed-select-dgdkgh?file=app/app.component.ts](url)

**Comment by aitboudad** [comment]
you don't need to create a custom type for such case, `options` allows passing an observable value see https://stackblitz.com/edit/angular-yz51jm

**Comment by alabanu** [comment]
I am using different groups to define fields. like this example [https://stackblitz.com/edit/ngx-formly-demo?file=src%2Fapp%2Fforms%2Fgroups%2Faddress.group.ts](https://stackblitz.com/edit/ngx-formly-demo?file=src%2Fapp%2Fforms%2Fgroups%2Faddress.group.ts)  How could I pass the Observable if there isn't any constuctor? I posted it also at stackoverflow and they suggest a solution with  compareWith [https://stackoverflow.com/questions/58602212/how-to-set-initial-value-to-select-formly-field-in-angular/58602584#58602584](https://stackoverflow.com/questions/58602212/how-to-set-initial-value-to-select-formly-field-in-angular/58602584#58602584).

**Comment by aitboudad** [comment]
pass the `defaultOptions` throughout group component where you can inject services: https://stackblitz.com/edit/ngx-formly-demo-ncfxap
