### ISSUE TITLE
How to extend ionic subset

### ISSUE THREAD

**Issue by rdev-software** [ngx-formly/ngx-formly#1879]
Hi I tried to follow example about custom template, I just tried to copy existing component for date-time picker

`<ion-datetime
[displayFormat]="to.displayFormat"
[pickerFormat]="to.pickerFormat"
[min]="to.min"
[max]="to.max"
[formControl]="formControl"
[ionFormlyAttributes]="field">
</ion-datetime>`

But "ionFormlyAttributes" is not available, any idea what to import into component.

Or what is the correct way of extending ionic components ?

**Comment by aitboudad** [comment]
[v5.5.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.2) is released which allows you  use `ionFormlyAttributes`
