### ISSUE TITLE
custom validation error message

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1883]
I need to include my custom validation error message template, how could i do?

**Comment by aitboudad** [comment]
The question is not clear enough, you may check our doc  example which provides several ways to add custom error message https://ngx-formly.github.io/ngx-formly/examples/validation/validation-message

**Comment by GlauberF** [comment]
Today, when you define that a field is required, if the user does not type, the validation message appears as follows.
![Captura de Tela_selecionar área_20191029163758](https://user-images.githubusercontent.com/11314585/67803446-cda38080-fa6b-11e9-9ef5-d93a91088339.png)


however, I need to include my error message component, which looks like this:
![Captura de Tela_selecionar área_20191029164204](https://user-images.githubusercontent.com/11314585/67803452-d1370780-fa6b-11e9-9b04-6139bd7dc5a2.png)

**Comment by aitboudad** [comment]
I see two ways to customize the validation error:

1. Customize it using global style
2. Override the provided default wrapper which will give you the ability to control the `html` content: https://stackblitz.com/edit/angular-pe3czd?file=src/app/app.component.ts

**Comment by GlauberF** [comment]
perfect, how can i see all the standard wrapper for material?
Based on them, I will modify as I need

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/form-field/src/form-field.wrapper.ts

The material wrapper is the complicated one in our codebase, unfortunately!

**Comment by GlauberF** [comment]
I think I expressed myself badly, I want to see the material types.
The components created for the material, based on them I can create custom type as I need.
Don't have a / src repository with types for material?

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/tree/v5/src/material
