### ISSUE TITLE
translate fields

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1886]
how can i add a key to translate from the field, example.

I tried to put it this way:
![Captura de Tela_selecionar área_20191030092634](https://user-images.githubusercontent.com/11314585/67858182-603d3180-faf7-11e9-804f-f0c2aa82bf18.png)

and in my translation file it is there:
![Captura de Tela_selecionar área_20191030092702](https://user-images.githubusercontent.com/11314585/67858208-721ed480-faf7-11e9-8513-aa86b5672a8a.png)

**Comment by aitboudad** [comment]
see https://ngx-formly.github.io/ngx-formly/examples/advanced/i18n-alternative

**Comment by GlauberF** [comment]
@aitboudad 
is TranslateExtension a service?
Because if so I can use the:

 ```
@Injectable({
    providedIn: 'root'
})
```

**Comment by aitboudad** [comment]
not a service, just a simple class.

**Comment by GlauberF** [comment]
thanks
