### ISSUE TITLE
JSON powered + Autocomplete 

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1894]
I need to store json in my database, but I have a problem, because autocomplete needs to call a function from my server file and pass the search term.
ie how will a json be saved in the bank if I put it like this:

```javascript
filter: (term) => of (term? this.filterStates (term): states.slice ())
```

or like this:

```javascript
options: this.dataService.getSports()
```

will give json sitax error when I submit to the database.
And if I put in quotes, then it's no longer a function or variable, then it won't work.

Is there any way to listen to any event via form and intercept the field identifier and the value entered?
Or is there any other solution to my problem?

I pressed save in quotation marks as string and after I recover from the database, I convert to function.
however how to convert to function?

**Comment by GlauberF** [comment]
what do you think of putting as a string, like
`options: 'this.dataService.getSports ()'`
and then map and do the following
`options: eval(options)`

**Comment by aitboudad** [comment]
use custom extension similar to translate example https://ngx-formly.github.io/ngx-formly/examples/advanced/i18n-alternative
