### ISSUE TITLE
[IONIC] Formfield "slot" expose

### ISSUE THREAD

**Issue by rdev-software** [ngx-formly/ngx-formly#1895]
Can you expose "slot" attribute for ion-label in formfield ?

```
 <ion-label [position]="to.labelPosition">
        {{ to.label }}
        <span *ngIf="to.required && to.hideRequiredMarker !== true">*</span>
      </ion-label>
```

add there
[slot] = "to.labelSlot"

@aitboudad

**Comment by aitboudad** [comment]
we're focusing now on the next major version `v6` so I'd suggest creating a custom wrapper that overrides the `formly` one (https://github.com/ngx-formly/ngx-formly/pull/1830#issuecomment-541316883)

**Comment by aitboudad** [comment]
There is no `slot` input for `ion-label`, doc: https://ionicframework.com/docs/api/label
