### ISSUE TITLE
validation messages, not showing up

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1896]
set the field to required, ta highlighting the field in red, but the message does not appear.

img result:
![Captura de Tela_selecionar área_20191104153723](https://user-images.githubusercontent.com/11314585/68148566-04214580-ff1b-11e9-8931-2657909e426e.png)

form html:
![Captura de Tela_selecionar área_20191104155056](https://user-images.githubusercontent.com/11314585/68148581-0d121700-ff1b-11e9-8321-4399ba78b348.png)

code:
```javascript
this.tabs = [
            {
                label: 'informaçoes basicas',
                fields: [
                    {
                        key: 'slug',
                        type: 'input',
                        templateOptions: {
                            label: 'slug',
                            translate: true,
                            required: true,
                            appearance: 'outline'
                        }
                    },
                    {
                        key: 'name',
                        type: 'input',
                        templateOptions: {
                            label: 'name',
                            translate: true,
                            required: true,
                            appearance: 'outline'
                        }
                    },
                    {
                        key: 'language',
                        type: 'input',
                        templateOptions: {
                            label: 'language',
                            translate: true,
                            required: true,
                            appearance: 'outline'
                        }
                    },
                    {
                        key: 'code',
                        type: 'input',
                        templateOptions: {
                            label: 'code',
                            translate: true,
                            required: true,
                            appearance: 'outline'
                        }
                    }
                ]
            }
        ];
        this.form = new FormArray(this.tabs.map(() => new FormGroup({})));
        this.options = this.tabs.map(() => ({}));
```

**Comment by aitboudad** [comment]
just ensure you've defined the validation messages first through the `NgModule` declaration,
check https://ngx-formly.github.io/ngx-formly/examples/validation/validation-message

**Comment by GlauberF** [comment]
@aitboudad 
but the required one is not standard?
In your example, for the required you do not define the **validation** object

**Comment by aitboudad** [comment]
```patch
@NgModule({
  imports: [
    FormlyModule.forRoot({
      validationMessages: [
+        { name: 'required', message: 'This field is required' },
      ],
    }),
  ],
})
export class AppModule { }
```

**Comment by GlauberF** [comment]
@aitboudad perfect,
Another question, thinking about this scenario, is how can I pass additional fields to external functions, eg minlengthValidationMessage or get the name of the validation that is wrong.
why in a field you can have more than one validation rule, example in the image below, has required and pattern

![Captura de Tela_selecionar área_20191105091318](https://user-images.githubusercontent.com/11314585/68203242-23b08080-ffa4-11e9-8091-d373630062cb.png)

if I call this way, it will already be executed, will it have a way to pass an additional field, without calling the function directly

```javascript
validationMessages: [
        { name: 'required', message: 'This field is required' },
        { name: 'minlength', message: minlengthValidationMessage(err, field, 'minlength') }
]
```

the third parameter would be the additional field, in which I pass the name of the validation that showed error

**Comment by aitboudad** [comment]
I don't get it, the passed third argument refers to the used validation so, in my opinion, it's just a duplication:
```ts
minlengthValidationMessage == minlength
```

**Comment by GlauberF** [comment]
yes, but would use a function as generic name, example.

```javascript
export function validationMessage(err, field, validatorName) {
  return `some text ${field.templateOptions[validatorName]} `;
}
```

As the function is generic, I can call both, but it would have to have the 3 field, for me to specify the name of the validation.

```javascript
FormlyModule.forRoot({
      validationMessages: [
        { name: 'required', message: validationMessage(err, field, 'required') },
        { name: 'minlength', message: validationMessage(err, field, 'minlength') }
    })
```

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-1wdnzr

**Comment by GlauberF** [comment]
thanks @aitboudad

**Comment by eng-dibo** [comment]
I use validation, but the validation message doesn't shown up

![image](https://user-images.githubusercontent.com/57308531/146273801-b7ba1ee1-a7ba-466c-ac58-0f1537c4f0bd.png)

![image](https://user-images.githubusercontent.com/57308531/146273854-7565c84a-67cd-4b26-b187-476539bd3d90.png)

**Comment by aitboudad** [comment]
there is an exception for minLength, maxLength validators, the key should be in lowercase: minlength, maxlength.

**Comment by eng-dibo** [comment]
it worked for minLength and maxLength, but no message displayed for `required`
should I add a custom message for `required`, or just the default one will be displayed?

I'm curious why that exception for minLength and maxLength? also the docs should be updated to clearly indicate this information.

**Comment by aitboudad** [comment]
> I'm curious why that exception for minLength and maxLength?

We use Angular validator `maxLength` which returns `maxlength` key when the field is invalid instead of `maxLength`, to make it consistent for us I'll try to wrap the returned object.

**Comment by sravani-laptop** [comment]
thank  you its working
