### ISSUE TITLE
Debounce should be ignored when using 'blur' or 'submit'

### ISSUE THREAD

**Issue by Devqon** [ngx-formly/ngx-formly#1898]
**Description**
When setting modeloptions with debounce **and** `updateOn` is `blur` or `submit`, the model is not updated on `blur` and `submit`.

**Minimal Reproduction**
Set a default debounce on a field type, and set `modelOptions` to `blur` on a field. When typing into the field, and immediately clicking `submit`, the model isn't updated.

See: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-qcvtrn

**Your Environment**
- Angular version: 7.x
- Formly version: 5.5.3

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.4](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.4).

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
