### ISSUE TITLE
Material form:  error message does not show until 2nd focus

### ISSUE THREAD

**Issue by freon27** [ngx-formly/ngx-formly#1900]
Disclaimer: this is my first time using Formly, but since the bug seems to occur in the Formly demo pages, I'm assuming it's valid.  Apologies if not.

**Description**

Using Material:

When a field blurs, it is marked red but the error message is not shown (although the field is marked red to show there is an error. The error appears when the user focuses the field again.  The behaviour in Angular Material and Material UI is to show the error message as soon as blur occurs.

I see this problem in my application but also in the demo pages.

**Minimal Reproduction**

Compare the behaviour of the  `TextArea` in https://ngx-formly.github.io/ngx-formly/ui/material

With the behaviour of the input in the `Error Messages` section of https://material.angular.io/components/form-field/overview.

I have also checked Material UI and the behaviour matches Angular Material (https://codesandbox.io/s/W6YnZm1po).

**Your Environment**

Demo pages
Chrome: 78.0.3904.70

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.4](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.4).

Thank you!

**Comment by freon27** [comment]
Thanks for fixing this so quickly! :)

**Comment by freon27** [comment]
Hi, sorry to reply to a closed issue this but I'm not sure if this is still a valid bug. If  it is, I'm happy to raise a new issue with the new reproduction steps.

The problem *is* fixed on the Formly demo page but it seems that with the latest version and copying the demo code from that Formly page, I still see the problem in a minimal app: 

https://stackblitz.com/edit/angular-qfeba8

Am I doing something wrong?

**Comment by aitboudad** [comment]
This second issue has been fixed and released as part of [v5.5.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.5).

Thanks!
