### ISSUE TITLE
transpile extension string to code

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1902]
Since I keep json in a database, I need everything to be string.
However there are cases that we need function / variable in some fields.

My solution would be to save to string and create an extension that transpile code.

but I'm having scope problem now, because as soon as he transpiles from string to code, he doesn't find that function inside tranpile, there is a better solution or a way to bind what is inside the component and send it together

**json code, see autocomplete:**
```javascript
{
    key: 'Autocomplete',
    type: 'autocomplete',
    templateOptions: {
        required: true,
        label: 'Autocomplete',
        placeholder: 'Placeholder',
        filter: '(term) => of(term ? this.filterStates(term) : states.slice())',
    }
}
```

**transpile:**
```javascript
import { FormlyFieldConfig } from '@ngx-formly/core';

export class TranspileStringToCode {
    constructor() {}
    prePopulate(field: FormlyFieldConfig): void {
        const to = field.templateOptions || {};

        console.log('field', field);
        //typeof t2 === 'string' ? eval(t2) : t2;

        field.expressionProperties = {
            ...(field.expressionProperties || {}),
            'templateOptions.options': (typeof to.options === 'string') ? eval(to.options) : to.options,
            'templateOptions.filter': (typeof to.filter === 'string') ? eval(to.filter) : to.filter,
        };
    }
}

export function registerTranspileStringToCode(): any {
    return {
        extensions: [
            {
                name: 'TranspileStrCodVimbo',
                extension: new TranspileStringToCode()
            }
        ]
    };
}
```

**error example:**

![Captura de Tela_selecionar área_20191105204529](https://user-images.githubusercontent.com/11314585/68255906-4a56d180-000d-11ea-8b38-bb53c3bd79f7.png)

Ali is giving error in `of` but could give error in any other function or variable

**Comment by Devqon** [comment]
`of` is an `rxjs` function, which is not known as a 'window' function.. A dirty workaround would be something like this:
```
import { FormlyFieldConfig } from '@ngx-formly/core';
import { of } from 'rxjs/operators';

declare var window: any;

export class TranspileStringToCode {
    constructor() {
        window.of = of;
    }
    prePopulate(field: FormlyFieldConfig): void {
       // ...
    }
}
```

**Comment by GlauberF** [comment]
This does not solve my problem, since the transpile file only converts string to / var function, to be used only where json will be loaded and not in the transpiler.
I have no way to call all possible functions inside the transpiler.
What I would look for would be a way to bind (this) where json is and send it together, so when I use eval to turn a string into a function call for example, it would not return a referenceError

**Comment by aitboudad** [comment]
using `eval` is not the right way at all, it will make your form hard to maintain and vulnerable to `XSS` attack, if I'm going to fully rely on `json` I'd prefer to use an `http` calls for the filter so in that the filter option will contains the api link.

```ts
    prePopulate(field: FormlyFieldConfig): void {
        ...,
        field.options = this.httpClient.get(to.optionsUrl);
    }
```

another way is to define some utils which you may link them to field, for example `filterStates`:
```ts
    prePopulate(field: FormlyFieldConfig): void {
        ...,
        if (field.templateOptions.filter === 'filterStates') {
          field.templateOptions.filter = (term) => of(term ? this.filterStates(term) : states.slice());
        }
    }
```

**Comment by GlauberF** [comment]
@aitboudad 
would have one usage example for each of the two examples in stackblitz ?

**Comment by aitboudad** [comment]
sorry but I think you can made it by yourself 🤔, I've provided enough details on that specific part and I don't think a `stackblitz` example would add any relevant info.

**Comment by GlauberF** [comment]
@aitboudad  you're right.
but I'm here studying some ways to do this in a way that I can enjoy the service, which already has the functions.

I almost got it, but I still haven't found a way to pass the term, just see how I'm doing.

in my component where I define the field, I left:
```javascript
                 {
                        key: 'city',
                        type: 'autocomplete',
                        templateOptions: {
                            required: true,
                            label: 'Autocomplete',
                            placeholder: 'Placeholder',
                            appearance: 'outline',
                            filter: 'this.filterStates("city", term)',
                            filerKeys: ['sigla', 'nome']
                        }
                    }
```

and I created a function to transform into a function, since it's string.
```javascript
prePopulate(
        field: FormlyFieldConfig
    ): void {

        const to = field.templateOptions || {};

        field.expressionProperties = {
            ...(field.expressionProperties || {}),
            'templateOptions.filter':
                typeof to.filter === 'string' ? (term) => of(new Function('return ' + to.filter)(term)) : to.filter
        };
    }
```

But is giving error in the term, you know how I could solve this, following this idea?
