### ISSUE TITLE
Material Slider doesn't like being dragged by the thumb.

### ISSUE THREAD

**Issue by clark-stevenson** [ngx-formly/ngx-formly#1907]
**Description**

The Material Slider doesn't like being dragged by the thumb.

**Minimal Reproduction**

- [Formly Material Slider Demo](https://ngx-formly.github.io/ngx-formly/ui/material)
- [Material Slider Demo](https://material.angular.io/components/slider/overview) as expected

Attempt to grab the control and move it.  

**Your Environment**

- Angular version: 8.2.12
- Formly version: 5.5.3
- Formly Material version: 5.5.3

**Additional context**

I thought this may be a configurable option somewhere over on the material slider API but I was unable to find anything.

**Comment by aitboudad** [comment]
> From https://material.angular.io/components/slider/overview

Note: the sliding behavior for this component requires that HammerJS is loaded on the page.
https://material.angular.io/guide/getting-started#installing-hammerjs

**Comment by clark-stevenson** [comment]
Sorry to clutter your email with that!  I appreciate your outlook.

For others who may see this.  I was importing hammerjs into my main module.  However, because I was using this as a lazy module, I had to use this work around.  https://github.com/angular/components/issues/8207

Doing so resolved the issue.  This library is awesome 👍
