### ISSUE TITLE
Not show * (star) in required field label and placeholder

### ISSUE THREAD

**Issue by jdavidhermoso** [ngx-formly/ngx-formly#1908]
**Question**
I'd like to know if there's a config or a way to not show the start when the field is required.

I take the opportunity to thank all the people creating this great tool.

Thanks!

**Comment by aitboudad** [comment]
use `hideRequiredMarker`:
```ts
{
  templateOptions: {  hideRequiredMarker: true }
}
```

> I take the opportunity to thank all the people creating this great tool.

👍

**Comment by jdavidhermoso** [comment]
Thank you so much!
