### ISSUE TITLE
mat-icon-button + mat-icon + click in template, not working.

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1909]
I have the following code and I need to render it, but it's not working

```javascript
{
	template: `
       <p>
	    <span class="mr-8" transl>Code</span>
	    <button (click)="openEditor()" mat-icon-button aria-label="Open editor">
	        <mat-icon>code</mat-icon>
	      </button>     
       </p>                   
	`,
}
```

in my rendered html just comes this
![Captura de Tela_selecionar área_20191107091540](https://user-images.githubusercontent.com/11314585/68388406-4e830c00-013f-11ea-9bd5-bc5a26169ebb.png)

**Comment by aitboudad** [comment]
`template` only render the provided content, use custom field type instead (https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field), you may check also the following examples:

- Button type: https://ngx-formly.github.io/ngx-formly/examples/other/button
- Prefix and Suffix: https://ngx-formly.github.io/ngx-formly/examples/other/material-prefix-suffix

**Comment by GlauberF** [comment]
Thanks
