### ISSUE TITLE
Toggle required field from different group 

### ISSUE THREAD

**Issue by alabanu** [ngx-formly/ngx-formly#1911]
I am trying to make the field "organizationName" in address.group.ts required when select type field "custype" has value "4" which is defined in demo-form.component.ts. I updated this [stackblitz](https://stackblitz.com/edit/ngx-formly-demo-6um6o5?file=src/app/demo-form/demo-form.component.ts) to show you the case. If these fields are in the same fieldGroup it works but if not it doesn't.

**Comment by dummdidumm** [comment]
You can also pass a function to an `expressionProperties`-entry and do arbitrary stuff in it. As far as I know this function will get invoked on every change detection cycle (maintainer please correct me if I'm wrong). So you could do this:

```
...
expressionProperties {
   'templateOptions.required': () => this.otherForm.value.custype === "4"
}
```

**Comment by alabanu** [comment]
custype field is in the same form but in different formly-group, so I tried this 
'templateOptions.required': () => this.form.value.custype === "4"
and I get ERROR
Error: Cannot read property 'custype' of undefined

**Comment by dummdidumm** [comment]
The form will only get initialized when the formly form component is in the dom. If this is not the case, the value will be `null`. So you just need to add an additional check

`'templateOptions.required': () => !!this.form.value && this.form.value.custype === "4"`

**Comment by alabanu** [comment]
I changed it and now it's always required even if I select custtype1, custtype2 or custtype3

[stackblitz](https://stackblitz.com/edit/ngx-formly-demo-vvw12c?file=src/app/forms/groups/address.group.ts)

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

**Comment by alabanu** [comment]
Thanks it worked!
https://stackblitz.com/edit/ngx-formly-demo-flohyh?file=src/app/forms/groups/address.group.ts
