### ISSUE TITLE
Show different value in input field than formControl

### ISSUE THREAD

**Issue by internalsystemerror** [ngx-formly/ngx-formly#1913]
**Question**

A clear and concise description of what the question is.

I have a text input field into which I wish the user to see and enter a monetary value in pounds, for instance: 102.00.

When I access formControl.value, I need this to be in pence, i.e. 10200.

Is there a way to manipulate the value between the formControl and the elementRef? I need be able to accomplish the following:

Set the value from the API (pence [API] -> pounds [input]).
The input value is shown in pounds.
The user can edit the input value as pounds.
On form submit, (I send form.value to the backend) I need to retrieve this value in pence.

I've been trying various methods of using a ControlValueAccessor, parsers in the config, hooks and no luck.

Any advice, suggestions on how I can accomplish this? I'd be sharing the final directive/custom field type that works (could add to the examples page), (I'm using ```extras: {immutable: true}```)

**Comment by aitboudad** [comment]
related to https://github.com/ngx-formly/ngx-formly/issues/180 which require `formatters` in order to be implemented in `formly` way :).

here is a quick attempt which use `ControlValueAccessor`: https://stackblitz.com/edit/angular-hv7mnc

**Comment by internalsystemerror** [comment]
Please reopen as this does not offer a fix:

If you add ```extras: {immutable: true}``` to the FormlyModule config, the model doesn't change, so I'm unable to retrieve the modified value.

**Comment by internalsystemerror** [comment]
this.form.value does contain the modified value, so this does actually offer a fix

**Comment by aitboudad** [comment]
or use `modelChange` output:
```html
<formly-form (modelChange)="modelChange($event)">
</formly-form>
```

**Comment by willyd** [comment]
@aitboudad The stack blitz example above is great. Is it possible to do the same thing with a model that has other fields. My use case is similar to the price example above except that the model contains the price value and another key that specifies the currency like this:
```js
model = {
price: 600,
currency: "EUR",
};
// or
model = {
price: 400,
currency: "CAD",
};
```
the model could store the value in any currency but the input should always be in USD.  Thus the `ControlValueAccessor` must not only know the price value, but also the currency to perform the right conversion. In what way the example stackblitz should be modified to support this use case?
