### ISSUE TITLE
super.ngAfterViewInit(), super.ngOnInit() Autocomplete 

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1914]
What is the need to put `super.ngAfterViewInit()` and `super.ngOnInit()`?
Why I modified the autocomplete and put ngOnDestroy, so inside it too, put `super.ngOnDestroy()`?

And have trouble instantiating `this._unsubscribeAll = new Subject()` in `ngOnInit`?

see how it was and if it is inside how it should be.
https://stackblitz.com/edit/angular-pdfypy?file=src%2Fapp%2Fautocomplete-type.component.ts

**Comment by aitboudad** [comment]
the `super` call is to apply the parent `FieldType` code which is required in order to link the common `form-field` wrapper with that field.

In case you don't want to use our common `form-field` wrapper, just follow our guide https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field without using a wrapper.
Here is a starter example: https://stackblitz.com/edit/angular-wqb92q

**Comment by GlauberF** [comment]
@aitboudad In my example you can see that it is an array of objects, but in value I show two fields, but I would like to return to my form all the values of the object, you know how I can do this based on my example attached above?

**Comment by aitboudad** [comment]
The provided example link doesn't work, could you please check it.
Thanks!

**Comment by GlauberF** [comment]
https://stackblitz.com/edit/angular-autocomplete-dinamico

**Comment by aitboudad** [comment]
the example works for me, could you elaborate more!

**Comment by GlauberF** [comment]
right, the way it is, when I save, comes this data

![Captura de Tela_selecionar área_20191111092309](https://user-images.githubusercontent.com/11314585/68587109-02003f00-0465-11ea-8d34-8395e310b1e9.png)

I need the whole object to come
```javascript
{
      "id":1,
      "sigla":"AL",
      "nome":"Alabama"
    }
```

however in the autocomplete view, it should look like this, with values separated by (-)

**Comment by aitboudad** [comment]
that's a material question so next time its better to check http://material.angular.io or ask the question in their channel.

the solution is to pass the desired value through `mat-option` component:
```html
<mat-option *ngFor="let value of filter" [value]="value">
```
and pass the `displayWith` to the `mat-autocomplete` to control the displayed value:
```ts
<mat-autocomplete #auto="matAutocomplete" [displayWith]="displayWith">
...
export class AutocompleteTypeComponent {
  ...
  displayWith(value) {
    return value ? value.nome : '';
  }
```

**Comment by GlauberF** [comment]
I'm sorry, but thanks.
I'm just having trouble accessing within the `displayWith` function` this.to`

**Comment by GlauberF** [comment]
solved `[displayWith]="displayWith.bind(this)">`

**Comment by rishisc** [comment]
Refered below example:
[https://stackblitz.com/edit/angular-autocomplete-dinamico](url)

I have an object in the same scenario
`[{
      "id":1,
      "sigla":"AL",
      "nome":"Alabama"
    },{
      "id":2,
      "sigla":"DC",
      "nome":"District Of Columbia"
    },{
      "id":3,
      "sigla":"MC",
      "nome":"Michigan"
    }]`

My desired output as:
`{ "Autocomplete": "Alabama" }`
OR
`{ "Autocomplete": "AL" }`

Currently I am getting output in model as:
`{ "Autocomplete": { "id": 1, "sigla": "AL", "nome": "Alabama" } }`

**Comment by aitboudad** [comment]
@rishisc pass the desired property to the value input of `mat-option` or make it configurable:

```ts
<mat-option *ngFor="let option of options" [value]="option.sigla">
  {{option.nome}}
</mat-option>
```
