### ISSUE TITLE
Validators

### ISSUE THREAD

**Issue by jopperknopper** [ngx-formly/ngx-formly#1918]
We are heavy users of formly for AngularJS and when migrating to ngx-formly we encountered a "quirk".
First some background:
We are working with a server that whose data model is defined as a schema and contains lists, containers and attributes. The schema for a list entry or container can be requested from the server, and contains all attributes with type information and values.

The schema has a predefined set of types (int8,uint8,int16,uint16, etc .. ) and we have created a reflection of those types in formly with validators.

So when we build the form config we use the predefined types and extends the form types with other validators.

Here is the question; 
When we want to extend the validators on a predefined type it removes the validators of the type and replaces them with the one in the field configuration.

In angularjs-formly the validators was extended.

Is this behavior a "new design" or is it a bug?

**Comment by aitboudad** [comment]
Hi, can you show me a simple example using our `stackblitz` starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by jopperknopper** [comment]
I think that I have updated the stackblitz example that you sent, can you see my changes?

**Comment by jopperknopper** [comment]
https://ngx-formly-ui-bootstrap-ccsfbg.stackblitz.io

Thats better ;-)

**Comment by aitboudad** [comment]
We didn't follow that behavior, the merge only takes account of an object so in case of array value we prioritize the field one.

to deal with it you may use a custom extension, which allows you to adjust fields during the build step, you may check the following examples:

- https://ngx-formly.github.io/ngx-formly/examples/advanced/i18n-alternative
- https://ngx-formly.github.io/ngx-formly/examples/other/material-prefix-suffix

**Comment by jopperknopper** [comment]
Hmm, so why can you define a type at startup when its values are overwritten instead of merged?

**Comment by aitboudad** [comment]
there's one use case that prevents me to go with that proposal, if I want to override the existing validation of `int8` type, how I could achieve it?

**Comment by jopperknopper** [comment]
Then you don't use that type. 

I understand the implementation, but what is the purpose of defining a type if it isn't rigid?

The way I think about it is that I want to define my types and refine it when I build the field configuration, like i did in the example.

**Comment by aitboudad** [comment]
I see your concern but change the merge way would introduce a breaking change, if there are more requests about that part I'd be happy to implement it somehow. but for now, I think you can achieve it using custom extension as shown above (if you need some help on implementation let me knew!)

**Comment by jopperknopper** [comment]
Yea, breaking changes is not what anybody wants. 

What happend is that we implemented  our own type system where we manage the merge/copy/clone of configs our self and feed formly that configuration, it works but I still think that the framework should provide that functionality through the type system.

Enough of this, it works for us now and I still love formly and really appreciate the work you put in to make our day easier.

Thank you and have a nice weekend :-)

/Jesper
