### ISSUE TITLE
Checkbox and multi-checkbox allignement problem 

### ISSUE THREAD

**Issue by enricooliva** [ngx-formly/ngx-formly#1920]
I used this the following example with bootstrap 
but the control goes over the label.

Any suggestion? 

`{
      type: "multicheckbox",
      key: "LoginTypes",
      templateOptions: {
        options: [
          {
            key: "google",
            value: "Google"
          },
          {
            key: "facebook",
            value: "Facebook"
          },
          {
            key: "twitter",
            value: "Twitter"
          }
        ],
        label: "Login As"
      }
    },`

![checkbox](https://user-images.githubusercontent.com/11843561/68680038-3e18ca00-0561-11ea-92e0-70a0cc709d04.PNG)

**Comment by aitboudad** [comment]
checked with a simple example but not be able to reproduce it https://stackblitz.com/edit/angular-g9ukgt.

just ensure the bootstrap style is included and match the latest one.

**Comment by enricooliva** [comment]
It was a not updated bootstrap style. :(

**Comment by aitboudad** [comment]
then I may need a reproduction example 🙏!

**Comment by aitboudad** [comment]
Just noticed the same issue while updating the bootstrap `stackblitz` example, the solution is to remove the bootstrap style that is included in the `index.html`.
