### ISSUE TITLE
Need help for the formly

### ISSUE THREAD

**Issue by rahul-rautwar** [ngx-formly/ngx-formly#1922]
First of all this is not the ngx-formly issue, but I need help in our issue,

I am using [formly-wrapper-angular-element](https://github.com/rahul-rautwar/formly-wrapper) for ngx-formly.

In my stenciljs component, I have used the [formly-wrapper-angular-element](https://github.com/rahul-rautwar/formly-wrapper) to create the form dynamically based on JSON passed.

**[My repository](https://github.com/rahul-rautwar/formly-wrapper)**

I am able to create the form but **field change/blur event** is not working for me.

Below is my json object which I am passing to [formly-wrapper-angular-element](https://github.com/rahul-rautwar/formly-wrapper) 

`this.componentSchema=[{
        key: 'country',
        type: 'select',
        className: 'col-6',
        templateOptions: {
          label: 'Country',
          description: 'Input Field Label',
          options: [{ name: 'Afghanistan', code: 'AF' },
          { name: 'India', code: 'IN' }],
          valueProp: 'code',
          labelProp: 'name',
          change: () => {
            //want to do some opration here
            console.log('country changed')
          }
        }
      }]`

Inside render block:
`<app-formly-wrapper input={JSON.stringify(this.componentSchema)}></app-formly-wrapper>}`

Could you please help me to get the field **change/blur event** to work properly.
(It seems like the issue is with the **change field value**, How can I passed it to [formly-wrapper-angular-element](https://github.com/rahul-rautwar/formly-wrapper) so that ngx-formly will work for me)

Steps to check issue:

- clone **[My repository](https://github.com/rahul-rautwar/formly-wrapper)**
- at root level(stencil-component-starter) do npm install and then npm start

**Comment by rahul-rautwar** [comment]
@aitboudad could you please help me with this?

**Comment by rahul-rautwar** [comment]
As JSON doesn't understand functions so JSON.stringify not parsing function.
So I have created one function to stringify it 
` makeString (obj) {
    return JSON.stringify(obj, function (_key, value) {
      return (typeof value === 'function') ? value.toString() : value;
    });
  }` 

and eval it on the other side 

`parseString(str) {
    return JSON.parse(str, (key, value) => {
      if (typeof value !== 'string') { return value; }
      // tslint:disable-next-line:no-eval
      return (value.substring(0, 8) === 'function') ? eval('(' + value + ')') : value;
    });
  }`

its working with the above approach :)

**Comment by aitboudad** [comment]
Custom element accepts only a string value so if you want to pass a non-string value it should be done through component props (https://github.com/ngx-formly/ngx-formly/issues/1505#issuecomment-478711772).
