### ISSUE TITLE
Json schema nested array properties incorectly mapped.

### ISSUE THREAD

**Issue by Adam-Michalski** [ngx-formly/ngx-formly#1923]
**Description**
Json schema nested array properties incorectly mapped in array on second level (don't know what happens deeper).
At first level in root array we can see that `hidden` property is correctly mapped and age is not displayed for two of three elements but on the second array with `hidden` property specified exacly the same like in root array `age` is displayed.

You can observe that `mapFn` param `mapSource` passed to map for every field is passed (as it seams) as first element from second level array properties.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ngx-formly-array-type-with-different-item-properties

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.5).

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
