### ISSUE TITLE
JSON-Schema dependencies of boolean type doesn't hide on false

### ISSUE THREAD

**Issue by NiestrojMateusz** [ngx-formly/ngx-formly#1928]
Hi,
I try to set up a form with json-schema with dependencies. I set up checkbox input which on true should reveal another input and it works for the reveal but when I uncheck the input doesn't disappear.

If the 

**Minimal Reproduction**
Here is a fork from your JSON-schema stackblitz with simple setup 

https://stackblitz.com/edit/angular-quodaz

Schema is in simple.json file

If it is not a bug could you help me to setup that?

**Comment by aitboudad** [comment]
use `oneOf`: https://stackblitz.com/edit/angular-quodaz-wvabux

**note**: require `v5.5.5`
