### ISSUE TITLE
How To Find The Form Fields Has Error Other Then Required.

### ISSUE THREAD

**Issue by ajay1208** [ngx-formly/ngx-formly#1929]
**Question**

How To Find The Form Fields Has Error Other Then Required ?

Description:

1. I have a functionality to check whether the form fields are valid and submit the forms. But checking of form validity should not consider the required error, it should consider only other errors like pattern, maxlength, minlength, custom validation etc.

**Comment by aitboudad** [comment]
Not sure what you're looking for 🤔, other errors indirectly rely on required (ignore the empty value which is covered by `required`).

for more advanced validation you may use a custom validation or get errors from `field.formControl.errors`
