### ISSUE TITLE
The options in the cascaded select are getting truncated in the latest firefox version

### ISSUE THREAD

**Issue by santosh099** [ngx-formly/ngx-formly#1931]
**Description**

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: X.Y.Z
- Formly version: X.Y.Z

**Additional context**

**Comment by Devqon** [comment]
Please add more details, and a working stackblitz link

**Comment by aitboudad** [comment]
a reproduction is required, feel free to reopen if you have more details!
