### ISSUE TITLE
Disabled property change does not propagate to hidden fields correctly

### ISSUE THREAD

**Issue by arteme** [ngx-formly/ngx-formly#1932]
**Description**

I have a form that has a top-level "templateOptions.disabled" expression. The form has a number of fields that are programmatically hidden by a wrapper. When the disabled expression changes, the new value is not propagates to hidden fields. When a hidden field is revealed, the value of its "disabled" property will be the one that was set when it was not hidden last time.

Worked correctly with formly 5.5.2, broke in 5.5.3.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-g4ljjr

The app has "edit mode" check-box that control the "templateOptions.disabled" expression, a bunch of text input fields, which are hidden by a wrapper and a list of check-boxes that control which inputs are hidden by the wrapper.

To repoduce:
1. Toggle "eng", an "eng" input field will appear, disabled.
2. Toggle "fin", a "fin" input field will appear, disabled.
3. Toggle "edit mode", the "eng" and "fin" fields will become enabled.
4. Toggle "swe", a "swe" input field will appear, **disabled** (expected to be enabled).
5. Toggle "eng", an "eng" input field will disappear.
6. Toggle "edit mode", the "fin" and "swe" fields will become disabled.
7. Toggle "eng", an "eng" input field will appear, **enabled** (expected to be disabled).

**Your Environment**

- Angular version: 7.2.5
- Formly version: 5.5.3 / 5.5.4 (worked correctly with 5.5.2).

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.5).

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
