### ISSUE TITLE
Tab out of Datepicker input is broken

### ISSUE THREAD

**Issue by pascalbe-dev** [ngx-formly/ngx-formly#1935]
**Description**
When using the existing Material Datepicker form field type, it is not possible to tab out of the datepicker's input field. Focus is kept within the input field.

**Minimal Reproduction**
The issue is actually present in the official documentation site (https://ngx-formly.github.io/ngx-formly/ui/material).

**Your Environment**

- Angular version: 8.2.13
- Angular Material version: 8.2.3
- Formly version: 5.5.4

**Comment by pascalbe-dev** [comment]
Great. I see, this is fixed with your latest commit. Thanks for the quick feedback.
Looking forward to the next release. Thanks.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.6).

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
