### ISSUE TITLE
How to get multicheckbox is checked or not

### ISSUE THREAD

**Issue by a2928897** [ngx-formly/ngx-formly#1937]
**Question**
As a example,
User can pick which hero he want(multi), also can pick otherhero to input what he want.

The "other" input  default is disabled,
Only when User check "otherhero", the input will be able,

How can I implement this require?
thanks a lot.

json example like below:

        **{
      key: 'favhero',
      type: 'multicheckbox',
      templateOptions: {
        label: 'Multi-checkbox',
        options: [
          { label: 'Iron Man', value: 'iron_man' },
          { label: 'Captain America', value: 'captain_america' },
          { label: 'Black Widow', value: 'black_widow' },
          { label: 'Hulk', value: 'hulk' },
          { label: 'otherhero', value: 'otherhero' },
        ],
      },
    },{
      key: 'other',
      type: 'input',
      templateOptions: {
        label: 'Input',
        placeholder: 'input other hero',
        description: 'Description',
        required: true,
      },          expressionProperties: {
            'templateOptions.disabled': '!favhero.otherhero is checked',
          },
    }**

A clear and concise description of what the question is.
- Material

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-ao8mkt

**Comment by a2928897** [comment]
Thanks for your help!
