### ISSUE TITLE
field.templateOptions.componentRef  error

### ISSUE THREAD

**Issue by smile2014** [ngx-formly/ngx-formly#1938]
Error after upgrading to 5.5.4

5.5.0 is ok

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
I can't use it after reading the changes from 5.5.3.

**Comment by smile2014** [comment]
export class ApesField extends FieldType {

  protected onDestroy$ = new Subject<any>();

  protected oldValues = {};

  protected listenFuncs: Function[] = [];

  constructor(protected apiService: ApiService, protected events: Events, protected expressionService: ExpressionService, protected subject: SubjectService) {
    super();
  }

  ngOnInit(): void {

  }


  ngOnDestroy(): void {
    this.onDestroy$.next();
    this.onDestroy$.complete();
    if (this.field && this.field.templateOptions.componentRef) {
      delete this.field.templateOptions.componentRef;
    }
    this.listenFuncs.forEach(listenFunc => {
      // Removes "listen" listener
      listenFunc();
    });
  }

  private _field: FormlyFieldConfig;

  set field(field) {
    this._field = field;
    this._field.templateOptions.componentRef = this;
  }

  get field() {
    return this._field;
  }
  interceptFrom(fieldName: string, expression: string) {
}

**Comment by smile2014** [comment]
https://github.com/ngx-formly/ngx-formly/pull/1881/commits/4f5c51a44dc464b1eb6b4482a65483b61e3cf530

**Comment by aitboudad** [comment]
Hi, can you provide a reproduction example using our stackblitz starter example https://stackblitz.com/angular/yggqbdbmynn?file=src%2Fapp%2Fapp.component.ts

Thanks!

**Comment by smile2014** [comment]
https://angular-hy9vlk.stackblitz.io

**Comment by smile2014** [comment]
https://stackblitz.com/edit/angular-hy9vlk?file=src/app/app.component.ts @aitboudad  5.5.4 error

**Comment by smile2014** [comment]
So how do I modify this code?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.6).

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by smile2014** [comment]
@aitboudad  Hello aitboudad ，it can no longer be used normally after using v6.x.
