### ISSUE TITLE
Mask (https://github.com/JsDaddy/ngx-mask)

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1942]
I am using this package for masks, as I define it in the field.

Since I have to include the mask in some cases (prefix and suffix)

**Comment by aitboudad** [comment]
The question is not clear, could you please elaborate, please 🙏!
The `mask` is not part of the `formly` core so in order to use it, you'll need to create a custom field type.

**Comment by GlauberF** [comment]
Excuse me.
I want to use this mask package within the formly fields.
but how can i report this and get it reflected in formly inputs dynamically?

**Comment by aitboudad** [comment]
Just follow https://ngx-formly.github.io/ngx-formly/guide/custom-formly-field and you'll be able to use `ngx-mask`.

also, there is an example which you may check https://github.com/ngx-formly/ngx-formly/issues/889#issuecomment-381744331

**Comment by GlauberF** [comment]
Right, I will need to create a template.
I was trying to look for an alternative that doesn't need to create a new template

**Comment by Devqon** [comment]
@GlauberF it seems to have something to do with the `mask` input properties. When you delete all of them except `[mask]="mask"` itself, it does work:

```
        <input matInput
               [id]="id"
               [readonly]="to.readonly"
               [type]="type"
               [errorStateMatcher]="errorStateMatcher"
               [formControl]="formControl"
               [formlyAttributes]="field"
               [placeholder]="to.placeholder"
               [mask]="maskTypes[mask].mask"
               >
```

https://stackblitz.com/edit/angular-mask-vimbo-8zqqku?file=src/app/input-mask-field.component.ts

**Comment by jehoshua02** [comment]
Removing just `[specialCharacters]="maskTypes[mask].specialCharacters"` gets @Devqon stackblitz working for me.
