### ISSUE TITLE
JSON Schema parsing: Cannot read property "required" of undefined

### ISSUE THREAD

**Issue by juristr** [ngx-formly/ngx-formly#1944]
**Description**

When using the `map` callback in the `toFieldConfig` of the formly json schema service, the user can potentially manipulate the `field` object, returning something like

```
field = {
   template: `...`
}
```

...which is a valid formly config for rendering some template. However this results in an exception because the `templateOptions` property is undefined as can be seen here:

![image](https://user-images.githubusercontent.com/542458/69229563-efcd8180-0b85-11ea-9123-90b60b73593b.png)

**Your Environment**

- Angular version: 8.2.9
- Formly version: 5.5.5

@aitboudad I have a fix + test ready to be submitted as PR (basically guarding that src code line to only enter when a `templateOptions` object is present). My question is just whether the PR should be against `master` or `v5`.

**Comment by aitboudad** [comment]
`v5` for bugfix

**Comment by juristr** [comment]
👍 alright, gonna send you a PR

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.6).

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by signoredellarete** [comment]
Hi, we have the same issue in v5.12.

**Comment by aitboudad** [comment]
@signoredellarete Hi, could you please create a new issue with a reproduction example.
Thanks!
