### ISSUE TITLE
Does formly support custom type for Web components?

### ISSUE THREAD

**Issue by rahul-rautwar** [ngx-formly/ngx-formly#1945]
**Question**
**Does formly support custom type for Web components?**

I am trying to create a **custom type** field using Web Component, it's getting rendered but while submitting form, **model** dose not contains the **custom type field value**

For example

Inside FormlyModule, I am creating a custom type like
`types:[
   {
          name: 'mycustominput',
          component: MyCustomInputComponent
        }
]
`

and MyCustomInputComponent Component like 

`@Component({
    selector: 'app-input',
    templateUrl: './mycustominputcomponent.html'
})
export class MyCustomInputComponent extends FieldTyp{
 }`

and **mycustominputcomponent.html** template contains another MyInput component like

`<my-input [type]="to.type" [label]="to.label" [accessibility-text]="to.accessibilityText" 
 [placeholder]="to.placeholder" [required]="to.required" [disabled]="to.disabled">
</my-input>`

MyInput component has a **shadow: true** which contains **<input> tag**

So what I want is, **Formly model** should return the MyCustomInputComponent value.

**Comment by aitboudad** [comment]
the value can be controlled by  `formControl` instance:

- Get the value: `field.formControl.value`
- Change the value: : `field.formControl.setValue(newValue)`

**Comment by rahul-rautwar** [comment]
@aitboudad I am not able to get value with the suggestion you suggested

Could you plz update me in the below repo.
[Test Formly for custom type with web component](https://github.com/rahul-rautwar/angular-test-formly)

**Comment by aitboudad** [comment]
you should provide a change event from your custom component `my-component` in order to update the model value:

```ts
export class MyInputComponent extends FieldType implements OnInit {
    get value() { return this.formControl.value; }

    onChange(value) {
      this.formControl.setValue(value);
    }
}
```

**Comment by rahul-rautwar** [comment]
Thanks it worked :)

but what I am seeing in my custom type field, it's not supporting form validation,
I have passed **required=true** and without entering values, clicking on submit and submit events getting called for me. It's not giving required error msg for custom type.
