### ISSUE TITLE
Angular Material Datepicker properties

### ISSUE THREAD

**Issue by swillisstudio** [ngx-formly/ngx-formly#1947]
**Question**
I am trying to set a `startView` property for a date picker but cannot get it working. I have passed it in through `templateOptions` but it doesn't seem to pick it up.

I also want to limit the range of dates that can be selected, for example, the date needs to be at least 18 years in the past.

**Comment by aitboudad** [comment]
> I am trying to set a `startView` property
 
pass it through `datepickerOptions`:
```ts
    templateOptions: {
      datepickerOptions: {
        startView: 'month',
      },
    }
```

> I also want to limit the range of dates that can be selected, for example, the date needs to be at least 18 years in the past.

use `min` and `max`:
```ts
    templateOptions: {
      datepickerOptions: {
        min: ...,
        max: ...,
      },
    }
```

https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/datepicker/src/datepicker.type.ts#L28

**Comment by lartheon** [comment]
Hi, I am trying to figure out how you set the format to `dd/mm/yyyy`. This is the format we use in the UK.

**Comment by aitboudad** [comment]
see https://material.angular.io/components/datepicker/overview#customizing-the-parse-and-display-formats

**Comment by lartheon** [comment]
> see https://material.angular.io/components/datepicker/overview#customizing-the-parse-and-display-formats

Tried that but found that if you manually type the date it thinks you are typing in mm/dd/yyyy, it then flips it to dd/mm/yyyy  
e.g I type '1/12/2000' 1st of December 2000 gets flipped to '12/1/2000' 12th of January 2000 :(
Thanks anyway, I'll have to stick with the standard date input and figure out how to stop the label overlapping the default placeholder dd/mm/yyyy

**Comment by bappy004** [comment]
@lartheon you need to use the parse() and format() functions as described in https://stackoverflow.com/questions/46392275/angular-material-2-change-datepicker-date-format-mm-dd-yyyy-to-dd-mm-yyyy-s . the parse() is used by eg the manual entry by the user, this function makes mat-dp 'understand' the input. the format() function handles the display of the Date object to the UI
