### ISSUE TITLE
LabelClass for label for formly-wrapper-form-field

### ISSUE THREAD

**Issue by stanislaus18** [ngx-formly/ngx-formly#1950]
I have simplified my html to greater extend using formly.
But I have a situation where i use the formly input but only apply a different class for the label, I am not able to apply class through scss or options in the formly config.

Although i can do it building a wrapper.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1494#issuecomment-551655615

**Comment by stanislaus18** [comment]
> see [#1494 (comment)](https://github.com/ngx-formly/ngx-formly/issues/1494#issuecomment-551655615)

Yes that doesnt work on the Angular encapsulation point of view.. I had to use :host :ng-deep to over ride styles, Because 

<formly-wrapper-form-field>
<label> <-- encapsulated the class to apply on the child 
  <formly-input-field-label>
     <input>


and :ng-deep is going to be deprecated

**Comment by aitboudad** [comment]
could you please provide me a `stackblitz` example?

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/687#issuecomment-564216302
