### ISSUE TITLE
transform data into component before sending to model

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1952]
I have this component:
https://stackblitz.com/edit/angular-mask-vimbo?file=src%2Fapp%2Finput-mask-field.component.ts

In the component I show the percentage values, separated by (,) but before reaching the value in the model I need to execute something like `Number(this.formControl.value.replace (',', '.')) / 100`

But this transformation should only be sent to my model and not change the value in this.formControl.

how could i do this?

Note, I will only apply this transformation when `this.to.mask` is` percent`

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1913#issuecomment-551837281

**Comment by GlauberF** [comment]
@aitboudad  ok, but as it is a directive, as i will control for only when the percent type uses.
`this.to.mask === percent`

**Comment by aitboudad** [comment]
@GlauberF please avoid asking the unnecessary questions as we don't have enough time for such support.
if you're looking for a paid support you may contact me by email. Thanks!

**Comment by GlauberF** [comment]
I'm sorry
but I'm really in trouble, see the picture.
![Captura de Tela_selecionar área_20191121135741](https://user-images.githubusercontent.com/11314585/69359336-2d560b80-0c67-11ea-933d-56c00cc487dc.png)

Is there any other way to do it, see the example here.
https://stackblitz.com/edit/angular-mask-vimbo
