### ISSUE TITLE
exclude field in resetModel 

### ISSUE THREAD

**Issue by alabanu** [ngx-formly/ngx-formly#1955]
Hello,

I am trying to reset form on changing select option. 
There is an example https://stackblitz.com/edit/angular-2tdkxm-8qpnv6?file=app/app.component.ts but it resets model including select field. Is it possible to exclude select type field from resetting?

Thanks

**Comment by aitboudad** [comment]
then pass its current value to the `resetModel`:

```ts
reset() {
  this.options.resetModel({ type: this.model.type });
}
```
