### ISSUE TITLE
Allow an icon name to be selected for Ionic forms

### ISSUE THREAD

**Issue by bastibense** [ngx-formly/ngx-formly#1956]
Right now it is (impossible?) to add an `<ion-icon name="globe" slot="start"></ion-icon>` to a generated form. Icons are usually available in Ionic projects (see: http://ionicons.com).

**Describe the solution you'd like**
It would be nice to be able to provide an `iconName` property for form fields in Ionic.
If set, it should add an additional `ion-icon` element to the `<ion-item>` with a slot set to "start" (or maybe make this configurable, too, with a default of "start"?).

Attached are screenshots of a form without and one with icons in place. I think it would be useful for many Ionic developers to be able to set an icon in this rather standard way.

**No Icons:**
<img width="659" alt="image" src="https://user-images.githubusercontent.com/115002/69650948-a393ad00-106f-11ea-8d83-8a8aba111c09.png">

**With Icons:**
<img width="634" alt="image" src="https://user-images.githubusercontent.com/115002/69650991-b1e1c900-106f-11ea-9bad-1af4767d3c48.png">

**Comment by Devqon** [comment]
I don't think icons would be a standard form implementation, it doesn't sound logical to me. You can always create a custom input type/wrapper for this.
I think the way to go is to create a form field wrapper, and include the icon in there.

**Comment by aitboudad** [comment]
create a custom ionic wrapper that overrides the default one as @Devqon suggested.
