### ISSUE TITLE
Using custome template type in nested forms within modals

### ISSUE THREAD

**Issue by Et3rnal** [ngx-formly/ngx-formly#1958]
**Question**
In short: I have 3 levels nested form where the second and third represented in modals
So:
MainComponenet -> ListWithCustomeTypeButton (opens a modal) -> CustomeTypeButton2 (Opens another modal)

More details:
What I have now model with a list of items, each item can be edited inside a `ngx-bootstrap` modal, and you can add a new item using the same modal.

While in the edit/new modal I need to load another formly custom template which also has a list and button that open another modal.

I have tried many thing including working around formly without luck

This is my attempt to create a minimal example using what I think is the right way to do what I need:
[https://stackblitz.com/edit/ngx-formly-array-nested](https://stackblitz.com/edit/ngx-formly-array-nested)

**Comment by aitboudad** [comment]
have tried repeating section example: https://formly.dev/examples/advanced/repeating-section

**Comment by Et3rnal** [comment]
Thanks! I think that did what I need.
https://stackblitz.com/edit/ngx-formly-nested-repeat
