### ISSUE TITLE
Is formState an Observable?

### ISSUE THREAD

**Issue by bartlenaerts** [ngx-formly/ngx-formly#1959]
**Question**

Hi,

I'm building a custom UI library consisting out of own templates/fields and wrappers. Because this will be a very large enterprise application, we decided to use ChangeDetectionStrategy.OnPush on all our components, and thus also on these custom templates and wrappers we are building.

I'd like to use formState in my Formly forms, to disable my fields when necessary. I've started out with a FormService that manages the FormGroup, Model and Options (i.e. formState):

```
@Injectable({ providedIn: 'root' })
export class UiFormService {
  form: FormGroup = new FormGroup({});
  model: any = {};
  options: FormlyFormOptions = { formState: { disabled: true } };

  public get disabled(): boolean {
    return this.options.formState.disabled;
  }

  public set disabled(value: boolean): void {
    this.options.formState.disabled = value;
  }
}
```

Next, we have a FormFactory...

```
@Injectable({ providedIn: 'root' })
export class UiFormFactory {
  constructor(private translateService: TranslateService) {}

  public createInput(key, label, { email = false, placeholder = label, required = true, type = 'text' } = {}): FormlyFieldConfig {
    return {
      expressionProperties: {
        'templateOptions.label': this.translateService.stream(label),
        'templateOptions.disabled': 'formState.disabled'
      },
      key,
      templateOptions: { email, placeholder, required, type },
      type: 'input'
    };
  }
}
```
...and a FormComponent:
```
<formly-form [fields]="fields" [form]="uiFormService.form" [model]="uiFormService.model" [options]="uiFormService.options"></formly-form>
```
```
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'ui-form',
  templateUrl: './ui-form.component.html'
})
export class UiFormComponent {
  constructor(public uiFormService: UiFormService) {}

  @Input() public fields: FormlyFieldConfig[];
}
```

With these services, I construct a form:

```
<ui-form [fields]="fields"></ui-form>
```
```
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'person',
  templateUrl: './person.component.html'
})
export class PersonComponent {
  fields: FormlyFieldConfig[] = [
    this.uiFormFactory.createInput('firstName', 'labels.firstName'),
    this.uiFormFactory.createInput('lastName', 'labels.lastName'),
  ];
}
```
So far, so good. Everything works perfectly. Now, I add a toggle button to my toolbar to enable/disable the form:

```
<button (onClick)="toggle()" type="button">Toggle Form</button>
```
```
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'toolbar',
  templateUrl: './toolbar.component.html'
})
export class ToolbarComponent {
  constructor(public uiFormService: UiFormService) {}

  public toggle(): void {
    this.uiFormService.disabled = !this.uiFormService.disabled;
  }
}
```

The formState toggles correctly. The value is changed from true to false and back. But visually, on the form, nothing happens. As soon as you click/give focus to one of the input fields, their state is changed as expected. The behavior is correct because of the ChangeDetectionStrategy.OnPush. To have this working correctly, the formState should be an Observable (or Subject) that triggers the 'rerendering'.

I've tried to make the formState and disabled property observable like this, but no luck.

```
options: FormlyFormOptions = { formState: { disabled: new BehaviorSubject<boolean>(true) } }
```

Do you have any idea, how we can make our custom templates and wrappers listening to formState and react to changes, even with ChangeDetectionStrategy.OnPush enabled?

Thank you for your answer.

Regards,
Bart

**Comment by bartlenaerts** [comment]
Sometimes, you need to write it down, look in to the Github source code and try again to find the solution :-).

https://angular-8ndmti.stackblitz.io

**Comment by aitboudad** [comment]
That the right answer :), since you'll rely on Observable you may consider using `checkExpressionOn` option to evaluate expressions on model change only https://github.com/ngx-formly/ngx-formly/issues/1620#issuecomment-514639091

**Comment by FloNeu** [comment]
@bartlenaerts i know it has been a long time - but how did you get this to work? Can't see the sourcecode on the stackblitz.
