### ISSUE TITLE
How can I write unit test in my own form-ui-library？ 

### ISSUE THREAD

**Issue by hellojayjay** [ngx-formly/ngx-formly#1965]
**Question**

I create my own formly library based on @ngx-formly/core and ng-zorro-antd, and now I want to write its unit test. 
I refer to 
https://github.com/ngx-formly/ngx-formly/blob/92d4cfeffac36a0ee33dc6d9f9ee87554606ec17/src/bootstrap/src/lib/types/select.spec.ts
and 
https://github.com/ngx-formly/ngx-formly/blob/f5625ea31405c1e432b155a4c72ed8302ef2c79c/src/material/select/src/select.spec.ts
but these two files pass unit test by testing the doms whether has specific dom, and my form components class in my formly library has their method. 
so I want to test these method in form components, How can I do to solve this? 
or how can I get the instance of form component in unit test?

**Comment by aitboudad** [comment]
you can get the component instance using `query` fn: 
```ts
fixture.debugElement.query(By.css('formly-field-input')).componentInstance
```

We've improved our testing in the `master` branch by introducing [createFormlyFieldComponent](https://github.com/ngx-formly/ngx-formly/blob/master/src/ui/bootstrap/input/src/input.type.spec.ts) helper (it'll be part of `v6`).

for `ng-zorro-antd` we've made an initial work which you may check:
- Source code: https://github.com/ngx-formly/ngx-formly/tree/master/src/ui/ng-zorro-antd
- Demo: https://master.formly.dev/ui/ng-zorro-antd

**Comment by aitboudad** [comment]
*Note*: published an early version `0.0.1` for `@ngx-formly/ng-zorro-antd` which you can use with `v5`, a stable version is expected in `formly@v6`.

Happy coding!

**Comment by loxy** [comment]
I want to use `import { createFormlyFieldComponent } from '@ngx-formly/core/testing';`
But it is still impossible to import `createFormlyFieldComponent `. When will it be available?

**Comment by aitboudad** [comment]
> When will it be available?

yes but in `V6` (we'll release an alpha version soon)

**Comment by aitboudad** [comment]
you can copy the code from [src/core/testing/src/component-factory.ts](https://github.com/ngx-formly/ngx-formly/blob/main/src/core/testing/src/component-factory.ts) as helper in your project:

**Comment by loxy** [comment]
I did that. But I had to adapted to this:
```ts
useFactory: (builder: FormlyFormBuilder) => () => {
  builder.buildForm(new FormGroup({}), [field], model, options);
  return of(null);
},
```
Because function `build` is not available...

**Comment by zzhimin** [comment]
you can also use this library：https://github.com/zzhimin/ngx-ng-zorro-formly
