### ISSUE TITLE
hide true does not display value in the hidden field

### ISSUE THREAD

**Issue by SudeshAK** [ngx-formly/ngx-formly#1966]
**Question**

Hi,
I want to keep some values in a hidden input so I used hide: true but when I console the form it returns error

https://stackblitz.com/edit/angular-k5qin9

Regards,
Sudesh K

**Comment by aitboudad** [comment]
When `hide` is set to `true` the field control is detached from the form,

I think you're looking for a `hidden` field which can be done by keeping the `type` empty:
```ts
{
  key: 'iLikeTwix',
  defaultValue: 10,
}
```
