### ISSUE TITLE
hideexpression- console warnings

### ISSUE THREAD

**Issue by alabanu** [ngx-formly/ngx-formly#1967]
Hello,
 I am using hidexpression property to show/hide fields while changing  options of select type field but i am getting warnings (see pics below). My hideexpression example is this:

  ```
{
                key: 'ea_VerAMKA__c',
                type: 'checkbox',
                className: 'col-md-6',
                defaultValue:false,
                templateOptions: {
                    label: 'Πιστοποίηση ΑΜΚΑ',
                    indeterminate: false,
                    color: "primary",
                },
                hideExpression: hideIfCompany
            },
```

```
export function hideIfCompany(model: any, formState: any) {
  if ((formState.rootModel && formState.rootModel.customerType && (formState.rootModel.customerType.type === "2")))
    return true;
  else if (localStorage.getItem("customertype") == "2") {
    return true;
  }
}
```

![warings_exp](https://user-images.githubusercontent.com/6996975/70388596-b3d75080-19bc-11ea-8108-c0da2f6f64f1.PNG)
![warnings](https://user-images.githubusercontent.com/6996975/70388597-b3d75080-19bc-11ea-8a5e-87748ba25126.PNG)

)

**Comment by aitboudad** [comment]
fixed since [5.5.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.3) release, just update your formly version into the latest version which is [5.5.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.6) to get rid of that console 😄.
