### ISSUE TITLE
Focus in Material Radio Group

### ISSUE THREAD

**Issue by pascalbe-dev** [ngx-formly/ngx-formly#1969]
**Description**
There are a few strange behaviors of the material radio type which I guess should be changed to behave like the normal angular material components in their docs.

- Mat Radio Group is tabbable (tabindex is passed to the group) --> this adds one extra step when tabbing through a form, which is usually not wanted

- When selecting one Radio Button for the first time after the component was created, the ripple around the radio button does not go away --> I guess there is an issue with the focusing stuff within the OnContainerClick

**Minimal Reproduction**
Issue appears in the official docs.

**Your Environment**

- Angular version: 8.2.14
- Formly version: 5.5.6

**Additional context**
Current workaround is of course to create a custom type, but I guess, this should be somehow fixed in the standard radio type.

**Comment by aitboudad** [comment]
I'm not able to reproduce the second issue, here is my screenshot record:
![formly-mat-radio](https://user-images.githubusercontent.com/1753742/70618047-2d1bb100-1c12-11ea-8ef4-de9088aef299.gif)

I may need more details 🙏!

**Comment by pascalbe-dev** [comment]
Sure. This seems to only happen if you don't select the first option.

![radio](https://user-images.githubusercontent.com/26909176/70625253-56dcd400-1c22-11ea-8f0d-f2024a3563ee.gif)

Running on Chrome.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
