### ISSUE TITLE
Accessing event of submitted

### ISSUE THREAD

**Issue by VladBozhinovski** [ngx-formly/ngx-formly#1971]
**Question**

I'm using custom types where where I'm loading data for example on select options. They are tree type of loading. The problem is when I submit the form that data in the select options is not cleared/reset. How can I access to the sumitted event value so I can listen and clear the value of the select type field?

**Comment by aitboudad** [comment]
```ts
import { Component, Optional } from '@angular/core';
import { FieldType } from '@ngx-formly/core';
import { FormGroupDirective } from '@angular/forms';

@Component({ ... })
export class CustomFieldType extends FieldType {
  constructor(private ngForm: FormGroupDirective) {
    super();

    ngForm.ngSubmit.subscribe(event => {
      console.warn('submitted !');
    });
  }
}
```
