### ISSUE TITLE
Best way to update multiple keys after select

### ISSUE THREAD

**Issue by Et3rnal** [ngx-formly/ngx-formly#1974]
**Question**

Using the select type, I need to pass the selected value and the label to the model! There are many ways I can think off to do that but I'm after the best reusable way through formly, something like a pipe maybe? but I don't know how pipes work with formly?

I know all my label keys are the same as the value keys but with Txt at the end
```
theOption
theOptionTxt
```
I'm trying to avoid creating my own select unless this is the best way!

**Comment by aitboudad** [comment]
for select, you can adjust the provided option with the following templateOptions: 

-  labelProp: (option: any) => string;
- valueProp: (option: any) => any;
- disabledProp: (option: any) => boolean;
- groupProp: (option: any) => string;

here is an example of material select which include the label of the selected option: https://stackblitz.com/edit/angular-l2rkjk

**Comment by Et3rnal** [comment]
@aitboudad Thanks for the example, while it did help me another thing I was trying to solve I couldn't use it with this issue due to the model structure 

https://stackblitz.com/edit/ngx-formly-select-value-text

**Comment by Et3rnal** [comment]
I came up with this now

`
change: (field, event) => {
          field.formControl.patchValue(event.value);
          field.model[field.key+'Txt'] = event.label;
        }
`
No idea if this is a good practice ?

**Comment by aitboudad** [comment]
`compareWith` was missing in bootstrap which is added in [v5.5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.7) release.
Here is a working example with bootstrap https://stackblitz.com/edit/angular-jaq5ek
