### ISSUE TITLE
ERROR in Cannot determine the module for class XComponent in '/var/XComponent'. Add XComponent to the NgModule to fix it

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#1976]
I am having trouble deploying, for custom components created for formly and not yet declared in any module, not yet in use.
The others that were created and are in use gave no problem, it seems that to solve must associate the component with a module.

how to solve ?

![Captura de Tela_selecionar área_20191212140111](https://user-images.githubusercontent.com/11314585/70733197-9bcb3e00-1ce8-11ea-9105-750b18eb91a6.png)

![Captura de Tela_selecionar área_20191212140647](https://user-images.githubusercontent.com/11314585/70733258-bbfafd00-1ce8-11ea-9997-adfa30969258.png)

**Comment by aitboudad** [comment]
That's an angular issue, the solution is to include them in an NgModule or use `tsconfig` to exclude those files:

```json
{
  "exclude": [
    "..."
  ]
}
```
