### ISSUE TITLE
How can I get a timepicker

### ISSUE THREAD

**Issue by a2928897** [ngx-formly/ngx-formly#1983]
**Question**
I use Material UI in my project,
How can I get a **timepicker** in ngx-formly?

thx a lot.

**Comment by aitboudad** [comment]
Material doesn't provide a timepicker yet (https://github.com/angular/components/issues/5648) so you may need to find firstly a package that provides a such feature and then from `formly` side you'll need to create a custom field type in our doc https://formly.dev/guide/custom-formly-field.
Also you can check the source code of the available types: https://github.com/ngx-formly/ngx-formly/tree/v5/src/material

**Comment by a2928897** [comment]
thanks a lot,
I'll try create custom field.
