### ISSUE TITLE
Proposal: Allow onInit/afterViewInit/afterContentInit to return observables

### ISSUE THREAD

**Issue by dummdidumm** [ngx-formly/ngx-formly#1986]
It would be great if formly would support observables on the `hooks` `onInit` `afterViewInit` and `afterContentInit`. If an observable is returned from one of the hooks, Formly would automatically subscribe to that observable until the field is destroyed. This would free users from subscribing to the observable and handling the `onDestroy`-hook themselves.

Example usage:

```js
fields = [{
   ...
   hooks: {
      // Patch value of some other form control every time this value changes
      // subscription and unsubscribe is handled by formly
      onInit: field => field.formControl.valueChanges.pipe(
                    tap(value => field.form.patchValue({someOtherField: value})
                 )
   }
 },
...
];
```

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
