### ISSUE TITLE
Hidden field should be always ignored for validation

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#1987]
**Description**
When an item is removed or added to an array all the hidden field are added for validation.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-gpvje8

After the initialisation the submit button is enabled. After removing or adding an item, the submit button is disabled.

**Your Environment**

- Angular version: 7.2.15
- Formly version: 5.5.7

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.8](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.8) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
