### ISSUE TITLE
Directive not instantiated for formly-field

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#1988]
**Question**

We are in the process to use Cypress for testing our workflows.

To make things easier we would like to have an _id_ on _formly-field_. Similar like _formly-attribute_ does with _id_ on a fields HTML element.

However, a directive with selector 'formly-field[field]', even a directive with selector 'input' does not work within a formly form.

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-txz1tg?file=src/app/formly-field-intlid.directive.ts

Extensions and hooks don't offer a possibility to retrieve the native element formly-field.

Is there a mistake in my directive or is there another possibility to render an attribute on formly-field?

**Comment by pascalbe-dev** [comment]
If I may try to help: 
I guess your directive is not used by Formly, because it is not declared or imported to the module which creates the components (some Formly module). If you had a custom type, the input directive would work on that one (see [here](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-bxf5jb?file=src%2Fapp%2Finput.directive.ts)). 

Since you do not want to have custom types for everything, here's how our team adds and uses attributes for testing.
`
key: 'someKey',
type: 'input',
templateOptions: {
  attributes: {
    'data-cy': 'testKey'
  }
}
`
This will add the data-cy attribute to the input element as you described it with the `id` attribute. If you then want to reach the parent formly-field or anything else above (e.g. mat-form-field), you could use the parents method. 

`cy.get('[data-cy=testKey]').parents('mat-form-field').eq(0)`

Maybe there's also a better way, but this one should work.

**Comment by FritzHerbers** [comment]
@pascalbe-dev 
@aitboudad 
> I guess your directive is not used by Formly, because it is not declared or imported to the module which creates the components (some Formly module). If you had a custom type, the input directive would work on that one (see [here](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-bxf5jb?file=src%2Fapp%2Finput.directive.ts)).

Nice observation that a custom _input_ field works with the input directive. Why is _input.directive_ not working for formly's _input_ field (FormlyFieldInput)?

> Since you do not want to have custom types for everything, here's how our team adds and uses attributes for testing.
> `key: 'someKey', type: 'input', templateOptions: { attributes: { 'data-cy': 'testKey' } }`
> This will add the data-cy attribute to the input element as you described it with the `id` attribute. If you then want to reach the parent formly-field or anything else above (e.g. mat-form-field), you could use the parents method.

This solution is based on `formly-attribute`. Almost all of our custom fields do not use formly-attribute as there is no added functionality for using it. To avoid conflicts, we would need to add some dummy div to add `formly-attribute`..

Adding a new directive with just the functionality (access to field-config is needed, E2E testing for role based workflows, not only focused on visualisation) we need would be the easiest and cleanest way.  
Why is `formly-attribute` working and my `formly-field-intlid.directive` not?

> `cy.get('[data-cy=testKey]').parents('mat-form-field').eq(0)`

Another command would be `cy.get('[data-cy=testKey]').closest('formly-field')`, when there is exactly one parent.

**Comment by aitboudad** [comment]
> Why is input.directive not working for formly's input field (FormlyFieldInput)?

to my understanding directive recognize only the components that belong to the declared module.
`input.directive` should be added to the module where the `input` selector is used .

**Comment by pascalbe-dev** [comment]
> Another command would be cy.get('[data-cy=testKey]').closest('formly-field'), when there is exactly one parent.
Good point.

**Comment by FritzHerbers** [comment]
@aitboudad 
@pascalbe-dev 

core.module.ts
```
@NgModule({
  declarations: [
    FormlyForm,
    FormlyField,
    FormlyAttributes,
    FormlyGroup,
    FormlyValidationMessage,
    FormlyTemplateType,
  ],
  entryComponents: [FormlyGroup, FormlyTemplateType],
  exports: [FormlyForm, FormlyField, FormlyAttributes, FormlyGroup, FormlyValidationMessage],
  imports: [CommonModule],
})
export class FormlyModule {
```

I noticed that my directive is working for
- formly-form, maybe because it is used in a html in my module
- formly-group, maybe because it is declared as an entry component

The two cases only worked in my own setup where ngx-formly is configured in a shared module.
In Stackblitz it didn't work: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-rrktmz?file=src%2Fapp%2Fapp.component.ts

Maybe when FormlyField would be added to entryComponents (would it make sense?) it might work.

**Comment by aitboudad** [comment]
> Maybe when FormlyField would be added to entryComponents (would it make sense?) it might work.

doesn't work on my side.
