### ISSUE TITLE
formlyAttributes attribute in custom fields

### ISSUE THREAD

**Issue by 0x253** [ngx-formly/ngx-formly#1991]
**Question**

We have forms with a lot of form fields (> 300 input elements). We are using custom form fields, and we noticed that the `[formlyAttributes]="field"` attribute has a major performance impact on the rendering and keypress events of an input element. What is the `formlyAttributes` attribute required for, and do we have to set it in our custom fields?

Example of a custom component:
```
@Component({
  selector: 'app-formly-field-text',
  template: `
    <div [class.input-group]="to.picker"
         *ngIf="!to.readonly else readonly">
      <input appFormlyFieldText
             type="text"
             class="form-control"
             [formControl]="formControl"
             [formlyAttributes]="field"
             [class.is-invalid]="showError">
      <div class="input-group-append" [class.d-none]="!to.picker">
        <button class="btn btn-secondary"
                appPicker
                autoClose="outside"
                (click)="togglePicker()"
                type="button">A
        </button>
      </div>
    </div>
    <ng-template #readonly>
      <p [id]="id" class="form-group-text">{{ formControl.value }}</p>
    </ng-template>
  `,
})
export class TextComponent extends FieldType {
  ...
}
```

**Comment by aitboudad** [comment]
probably not related to `formlyAttributes`, can you try `checkExpressionOn` option if that solves the issue.
https://github.com/ngx-formly/ngx-formly/issues/1620#issuecomment-514639091

**Comment by 0x253** [comment]
Upgraded to 5.5.7 and set `checkExpressionOn` to `modelChange`, but can't see a major performance increase, at least not in dev mode. Regrading the initial question, is `formlyAttributes` a required prop?

**Comment by aitboudad** [comment]
a new area to improve then 😄, we use [host](https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/components/formly.attributes.ts#L8) but apparently doesn't go well. The solution is to register those events on-demand instead.

I'll try to fix that soon!

**Comment by 0x253** [comment]
Looks great, will test the performance improvements in the next days.

**Comment by smile2014** [comment]
The function corresponding to the event is considered to support string

fields: FormlyFieldConfig[] = [
    {
      key: 'team',
      type: 'select',
      templateOptions: {
        label: 'Team',
        options: [],
        valueProp: 'id',
        labelProp: 'name',
        click:' if (value==1){ return true;} else  return false;'
      },
      expressionProperties: {
        'templateOptions.options': 'formState.selectOptionsData.teams.filter(team => team.sportId === model.sport)'
      },
    }

@aitboudad

**Comment by aitboudad** [comment]
@smile2014 I'm looking only to make it easy in the future (but not an out of the box solution at least right now) using custom extension would help to have a generic solution ([i18n example](https://formly.dev/examples/advanced/i18n-alternative))

**Comment by smile2014** [comment]
thank you @aitboudad

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.8](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.8) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by 0x253** [comment]
@aitboudad Thank you for your great support. The performance improvements of this issue and the other improvements of v5.5.8 are huge. As far as I can see in my first tests with Chrome/FF/IE the performance of large forms (300 inputs) is now much better.

**Comment by aitboudad** [comment]
Awesome 👍!

💡Still there some improvements which I postpone to the next major version (`v6`) due to the BC break that may introduce.
