### ISSUE TITLE
JSON Schema - Uniqueness check on property in an array of objects

### ISSUE THREAD

**Issue by johnRambo2k14** [ngx-formly/ngx-formly#1993]
**Question**
Is there a way to have a uniqueness check on a property in an array of objects within an array?

for example:

```javascript
 model: [
    {
        description: 'Calendars',
        id: 'Calendar',  // <--- must be unique
        type: 'object'
    },
    {
        description: 'A date which can be assigned to a calendar.',
        id: 'Date',  // <--- must be unique
        type: 'object'
    }
]
```

**Comment by kenisteward** [comment]
https://json-schema.org/understanding-json-schema/reference/array.html#uniqueness

That's not how uniqueness works in Jason schema so if using the conversion
feature here it won't be how it works either

**Comment by johnRambo2k14** [comment]
Ahh okay, can ngx-formly allow custom validation via Json schema?

Perhaps I need to do this in my custom array type component and access the model state. 🤔

**Comment by kenisteward** [comment]
Currently if you'd like to add it you can use the map function to further
change a formly field based on configuration

You can add a key to your base schema to represent it as there will be no
errors in doing that.

**Comment by aitboudad** [comment]
as @kenisteward pointed either use a `map` option (https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527) or `widget` where you can pass `formlyConfig`:

```ts
{
  "type": ...,
  "widget": {
    "formlyConfig": {
      "wrappers": ["custom_wrapper"]
      validators: {
        validation: ['customUniqueValidation'],
      },
    }
  }
}
```

to define a custom validation you may check our demo example https://formly.dev/examples/validation/custom-validation
