### ISSUE TITLE
Model attribute incomplete when using immutable extra

### ISSUE THREAD

**Issue by pascalbe-dev** [ngx-formly/ngx-formly#1994]
**Description**
When setting the extra `immutable: true`, the model of the form is not updated with the values being set within the form. Furthermore, also the defaultValue attribute of the FormlyFieldConfig is not added to the model. Only presetting the model works.

**Minimal Reproduction**
[Stackblitz](https://stackblitz.com/edit/ngx-formly-ui-material-y5mtkv?file=src/app/app.component.ts)

- set immutable extra to true
- set form values via UI or defaultValue
- check out the model

**Your Environment**

- Angular version: 7.2.15, 8.2.14
- Formly version: 5.5.7

**Additional context**
Current workaround is using the value of the Reactive Forms FormGroup (this.model.value).

**Comment by pascalbe-dev** [comment]
Or is that intended? I was expecting the model to still be mutable and the formly field config to be immutable in order to reuse in different UIs.

**Comment by aitboudad** [comment]
yep, that's intended, to have a mutable model use:

```ts
(modelChange)="model = $event"
```

**Comment by pascalbe-dev** [comment]
Yeah, just found the discussion [here](https://github.com/ngx-formly/ngx-formly/issues/1429#issuecomment-465186967). The way, you outlined works.
