### ISSUE TITLE
Default value for JSONSchema oneOf

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#1995]
**Description**
Within the JSONSchema oneOf, the default value is used only at the initialisation. When the oneOf choice is changed the default value is not set.

**Minimal Reproduction**

Here is a modified example of the official JSONSchema example:

https://stackblitz.com/edit/angular-mgdft6, change the oneOf choice, the default value is not in the input field.

**Your Environment**

- Angular version: 7.2.15
- Formly version: 5.5.7

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.8](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.8) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by navnita-170310093** [comment]
Similar issue I am facing when default value is initialized from model.

**Comment by navnita-170310093** [comment]
Description
Within the JSONSchema oneOf, the default value taken from **model** is used only at the initialization. When the oneOf choice is changed the default value is not set.

Minimal Reproduction

Here is a modified example of the official JSONSchema example:

https://angular-1dt17d.stackblitz.io   

Change the oneOf choice, the default value is not in the input field.

The Schema looks like this..

{
  "schema": {
    "type": "object",
    "properties": {
      "Form": {
        "title": "Form",
        "oneOf": [
          {
            "title": "Option 1",
            "properties": {
              "Name": {
                "title": "Name",
                "type": "string"
              }
            },
            "type": "object"
          },
          {
            "title": "Option 2",
            "items": {
              "properties": {
                "Name": {
                  "title": "Name",
                  "type": "string"
                }
              },

              "type": "object"
            },
            "type": "array"
          }
        ]
      }
    }
  },
  "model": {
    "Form": [{ "Name": "Navnita" }, { "Name": "Tanu" }, { "Name": "Swii" }]
  }
}
