### ISSUE TITLE
default label and placeholder

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2004]
I suggest to make default values for fields:
  name, label, placeholder = key

```
{
      key: "title",
      type: "input",
      templateOptions: {
        label: "title", //default = field.key value
        placeholder: "title", //default = field.key value
       name:"title", //default = field.key value
        required: true
      }
```

**Comment by aitboudad** [comment]
use custom extension which allows you to update the field instance during the build step. check the following example: https://formly.dev/examples/advanced/i18n-alternative
