### ISSUE TITLE
className & attributes don't work with material

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2005]
```
{
      key: "test",
      type: "input",
      className:"test1", 
      attributes: { attr1: "attr1" }
      templateOptions: {
           className:"test2", 
           attributes: { attr2: "attr2" }
      }
    }
```

inspecting the output code, both className and templateOptions.className don't work
the same with attributes

**Comment by aitboudad** [comment]
- `className`: is assigned to the `formly-field` component which is the root wrapper of the each field.
- `attributes`: ⚠️ there is no such option.
- `templateOptions.className`: ⚠️ there is no such option.
- `templateOptions.attributes`: is applied to the `input` tag which works as expected.
