### ISSUE TITLE
How can I use the array index as key for a repeat section?

### ISSUE THREAD

**Issue by dnmd** [ngx-formly/ngx-formly#2011]
**How can I use the array index as key for a repeat section?**

Maybe I over complicate things to much. But after hours of tinkering I can't seem to figure out how to use the array index as `key` within a repeat section for the `model` below. I just have an array with strings that I want to add/remove. So not an array of objects.

````json
{
  "fruits": [
    "Apple 2"
  ]
}
````

I managed it as you can see in the following example: https://stackblitz.com/edit/angular-gn4diu but you will also notice that you cannot edit the data (I can't figure why... because of the missing `fieldArray`?).

The closest - editable - version can be seen here https://stackblitz.com/edit/angular-hharav but there it creates the nested object structure which I don't want.

````
{
  "fruits": [{
      "0": "Apple"
    }]
}
````

Any help / directions are appreciated!

**Comment by aitboudad** [comment]
`fieldArray` expect to pass a simple field too 😄:

```ts
fieldArray: {
  type: 'input',
  templateOptions: {
    label: 'Fruitname:'
  },
},
```

**Comment by tawani** [comment]
How can you get the index of the current item? 
e.g.
```
fieldArray: {
  type: 'input',
  templateOptions: {
    label: 'Fruitname ' + $index
  },
},
```

**Comment by aitboudad** [comment]
@tawani $index = `field.key`:

```ts
fieldArray: {
  type: 'input',
  expressionProperties: {
    'templateOptions.label': '"Fruitname " + field.key'
  }
},
```

**Comment by carmenschiop** [comment]
How can I get the "field.key" in this case https://stackblitz.com/angular/xlxoldjlylp?file=src%2Fapp%2Fapp.component.ts . I want to add after "Name of Investment" the index : Name of Investment 1, Name of Investment 2 ..

**Comment by aitboudad** [comment]
@carmenschiop https://stackblitz.com/edit/angular-geeuoa?file=src/app/app.component.ts

**Comment by arj060892** [comment]
This works fine with `fieldArray` but when we have a `fieldGroup[]` inside `filedArray` it returns the key name rather than the index 
```

{
    key: 'investment',
    type: 'repeat',
    fieldArray: {
      fieldGroupClassName: 'row',
      fieldGroup: [
        {
          type: 'select',
          key: 'investmentType',
          templateOptions: {
            placeholder: '-- Select investment type --',
            options:
              this.fakeService.getInvestments(),
            valueProp: 'id',
            labelProp: 'name'
          },
          expressionProperties: {
            'templateOptions.label': '"Investment" + field.key'
          }
        },
        {
            template:'Add investments'
        }
      ]
    }
  }
```

**Comment by aitboudad** [comment]
@arj060892 please check `field.parent.key` instead
