### ISSUE TITLE
turn off form autocompletion

### ISSUE THREAD

**Issue by josepacelli** [ngx-formly/ngx-formly#2012]
**Is your feature request related to a problem? Please describe.**
I was researching how to disable the "form autocomplete". And I saw this site [https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion
](form autocomple)

but I didn't find this tag in formOptions

**Describe the solution you'd like**
Is there a way to add the autocomplete = "off" property in formly?

**Describe alternatives you've considered**

**Additional context**

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/987#issuecomment-396647505

**Comment by signoredellarete** [comment]
This worked for me:

```
templateOptions: {
    label: 'COUNTRY',
    placeholder: 'Country',
        attributes: {
            autocomplete: 'off'
        },
    required: true,
}
```
