### ISSUE TITLE
expressionProperties callback function doesn't seem to subscribe to observables

### ISSUE THREAD

**Issue by juristr** [ngx-formly/ngx-formly#2013]
**Description**

I didn't yet look into the implementation, but from a usage perspective it looks like the callback functions in the expression properties don't subscribe to observables. Not sure whether this is intended.

I tried this example https://formly.dev/examples/advanced/i18n but changed it slightly to not use

```
expressionProperties: {
   'templateOptions.label': this.translate.stream('HOME.SELECT'),
},
```

but rather

```
expressionProperties: {
   'templateOptions.label': () => this.translate.stream('HOME.SELECT'),
},
```

The goal being to be able to access information from the passed params of the callback function such as the field configuration.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-dqx3uc?file=src/app/app.component.ts
https://stackblitz.com/...

**Comment by aitboudad** [comment]
not supported yet(related to https://github.com/ngx-formly/ngx-formly/issues/1818), as an alternative, you may use:
- https://github.com/ngx-formly/ngx-formly/issues/1818#issuecomment-541207382.
- or https://formly.dev/examples/advanced/i18n-alternative

**Comment by juristr** [comment]
@aitboudad alright, I assumed this might be the case. Yes I'm actually using the extension way of embedding ngx-translate 😃. _(Hint: recording the egghead course. 15 lessons recorded, 2 more to go. Will probably publish on Monday 🎉. Let's spread the ngx-formly awesomeness)_

Closing this issue for now then

**Comment by aitboudad** [comment]
Wow, awesome, I can't beat you on that part 😄💪.
Once ready you may add it to our doc as an official video course of `formly` (main menu or the home page as you prefer).
