### ISSUE TITLE
Expression property update with ngx-mask

### ISSUE THREAD

**Issue by bpetex** [ngx-formly/ngx-formly#2018]
**Description**
After the last update (5.5.8) we experienced cursor jump issue related to expressionProperty and ngx-mask. 
After some debugging I found that it happens  because of this commit: https://github.com/ngx-formly/ngx-formly/commit/b7567a1
Removing 'this.useDebounce = true; ' locally fixes the issue.

Didn't experienced this issue with other custom types we have, but I think this could be a potential issue with other libs as well.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-sd5pnu

**Your Environment**

- Ngx-Mask: 8.1.7
- Formly version: 5.5.8

**Comment by bpetex** [comment]
🙇

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.9](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.9) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
