### ISSUE TITLE
How to split a FieldGroup into multiple rows when using display-flex?

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2019]
@aitboudad 

I am using ngx-formly/core and /material version 5.5.7 with Angular 7.2.15

Appreciate all the hard work that is going into ngx-formly. 

I am looking for some help here.

I would like to split a FieldGroup into multiple rows. I have tried the below example, but it results in the following image.

![image](https://user-images.githubusercontent.com/39933836/72092585-3f077700-32d8-11ea-8d8a-d2c214b37cfb.png)

I would like to see the second repeat section as a new row as compared to where it is today.

Also for some reason when using Flex-8 (custom CSS - see below) the field stretches to the entire row when it is the only field. Work fine when there are 2 or more fields. 

`.flex-8 {
  // flex-flow: flex-direction flex-wrap;
  // flex-direction: row ;
  // flex-wrap: wrap;

  .mat-form-field-infix {
    width: 200px;
    // min-width: 250px;
    // max-width: 400px;
    
  }
}
`
Looking forward to your guidance.

Thanks

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

`  deviceAlertFields: FormlyFieldConfig[] = [
  {
      fieldGroupClassName: 'display-flex',
      key: 'devicesensors',
      type: 'repeat',
      wrappers: ['panel'],
      templateOptions: { addText: 'Add Sensor',  },
      fieldArray: {
        fieldGroup: [
          {
            fieldGroupClassName: 'display-flex',
            fieldGroup: [
              { type: 'input', key: 'sensorid', className: 'flex-8', templateOptions: { label: 'Sensor', placeholder: 'Sensor ID ', type: 'string', appearance: 'outline', required: true },
.........  code deleted .......... },
              { type: 'input', key: 'unit', className: 'flex-8', templateOptions: { label: 'Unit', placeholder: 'unit of measurement ', type: 'string', appearance: 'outline', required: true } },
              { type: 'input', key: 'min', className: 'flex-8', templateOptions: { label: 'Min Value', placeholder: 'Min Value', type: 'string', appearance: 'outline', } },
              { type: 'input', key: 'max', className: 'flex-8', templateOptions: { label: 'Max Value', placeholder: 'Max Value', type: 'string', appearance: 'outline',  } },
              {
              fieldGroupClassName: 'display-flex,',
              key: 'alerts',
              type: 'repeat',
              
              wrappers: ['panel'],
              templateOptions: { addText: 'Add Alert' , },
              fieldArray: {
                fieldGroup: [
                  { type: 'select', key: 'alertlevel', className: 'flex-8', templateOptions: { label: 'Alert Level', placeholder: '', //multiple: true, enableSelectAll: true,
                    options: [
                      { label: 'Major', value: 'Major' },
                      { label: 'Minor', value: 'Minor' },
                      { label: 'Critical', value: 'Critical' },
                    ],
                    }
                  },
                  { type: 'input', key: 'high', className: 'flex-8', templateOptions: { label: 'High Value', placeholder: 'Max Value', type: 'string', appearance: 'outline',  } },
                  { type: 'input', key: 'low', className: 'flex-8', templateOptions: { label: 'Low Value', placeholder: 'Max Value', type: 'string', appearance: 'outline',  } },
                ]
              },
            },
            ],
          },
        ],
      },
    },`

**Comment by kenisteward** [comment]
Could you set it up in a stackblitz?

**Comment by argupta23** [comment]
@kenisteward, @aitboudad  

Here is a stackblitz I created.

https://angular-ipvwaf.stackblitz.io

Please Click on Add-Sensor and you will see Add-Alert appear to the right which I would like to see as a new row below the first sensor row.

Hope this helps.

Thanks

**Comment by aitboudad** [comment]
The flex example is just a starting point for those who have advanced knowledge in `css`, you may need to add a class to control the [flex-direction](https://developer.mozilla.org/en-US/docs/Web/CSS/flex-direction).

There are some advanced libs that you may use instead such as:
- [Bootstrap grid](https://getbootstrap.com/docs/4.0/layout/grid/): 
https://formly.dev/examples/bootstrap-specific/advanced-layout

*note*: you don't have to import the entire bootstrap style, just the grid one `bootstrap-grid.css`


- [Angular flex layout](https://github.com/angular/flex-layout):
https://stackblitz.com/edit/ngx-formly-flex-layout
