### ISSUE TITLE
unable to pass api retrieved value back into object (ace-editor) when using wrapper

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2020]
**Question**

@aitboudad 

Following up on my initial request #1816, I did create a template based around your feedback.

While I can save the data that is being input within ace-editor for some reason when I retrieve the data back from my DB via API calls, it does not pass it back to ace-editor.

I might be missing something very basic here. Can you please help me out?

Here is a stackblitz I created around the issue.
((https://angular-d7waaw.stackblitz.io))

thanks

**Comment by aitboudad** [comment]
rely on `formControl.value` to get the field value: 

```patch
 <div ace-editor
--  [(text)]="text"
++  [text]="formControl.value" 
```

and for the components that support angular reactive forms use `formControl` input:
```html
<custom-component [formControl]="formControl">
</custom-component>
```

**Comment by argupta23** [comment]
@aitboudad 

Thanks. It addresses the issue I was running into.
