### ISSUE TITLE
textarea - how many words can I type

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2021]
I have the following code:

```javascript
{
                    key: 'bcc_descricao',
                    type: 'textarea',
                    templateOptions: {
                        label: 'Descrição',
                        translate: false,
                        required: true,
                        maxLength: 20,
                        rows: 5,
                        appearance: 'outline'
                    }
                }
```

Image
![Captura de Tela_selecionar área_20200110112702](https://user-images.githubusercontent.com/11314585/72159918-22cd0e00-339c-11ea-9467-d09f623d287f.png)

on the right side I would like to include how many words can I type.
example: 10/20

and I wouldn't want to create a custom template just because of it

**Comment by aitboudad** [comment]
use a custom wrapper, here is a starter example https://stackblitz.com/edit/angular-xrh4dg

**Comment by GlauberF** [comment]
ok, but I don't want to apply to all fields, just for some textarea.
How can I specify within json which textarea should use this wrapper?

**Comment by aitboudad** [comment]
it's just an example where you can adjust it based on your needs.

> How can I specify within json which textarea should use this wrapper?

Either pass an extra option through `templateOptions`

```ts
{
  templateOptions: {
    enableWorkCount: true
  }
}
```

or pass the wrapper through `wrappers`:

```ts
{
  wrappers: ['custom_wrapper', 'form-field']
}
```

**Comment by GlauberF** [comment]
In your example, how would I put what is selected?

![Captura de Tela_selecionar área_20200113140127](https://user-images.githubusercontent.com/11314585/72275697-2ddaa500-360d-11ea-8db1-f2f2209438b3.png)

**Comment by aitboudad** [comment]
not possible with our current implementation of `formly` wrapper, we'll try to provide a better way in `v6`.

**Comment by GlauberF** [comment]
Thanks for taking the subject.

Are you forecasting for the stable version of V6?
From v5 to v6, will we have to make many changes?

**Comment by aitboudad** [comment]
> Are you forecasting for the stable version of V6?

it's our main focus for now but it may take some time to be ready.

> From v5 to v6, will we have to make many changes?

not too much, we'll provide a smooth upgrade path to follow anyway.

**Comment by GlauberF** [comment]
Perfect, Thanks and looking forward to the V6. :)
