### ISSUE TITLE
Array of long list is slow on firefox.

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2022]
**Description**
Rendering an array of long list is slow on firefix only.

**Minimal Reproduction**

Try the following example and add a new element: it is immediate on chrome and safari but takes several seconds on firefox.

This can be seen as a strange use case but I have an editor based on jsonschema with a repeatable language field which is an enum of all iso languages.

https://stackblitz.com/edit/angular-rbwppc

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.5.8
- Firefox version: 72.0.1 (seem to be also the case for previous versions)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.9](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.9) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
