### ISSUE TITLE
[Help] Bind a button to function in parent component when using JSON String to construct form.

### ISSUE THREAD

**Issue by dthk-cogmatix** [ngx-formly/ngx-formly#2026]
Currently I'm building a dynamic form using a JSON string being provided by a REST API.  (Very similar to the example: https://stackblitz.com/angular/ybddrmgqabg?file=src%2Fassets%2Fjson-powered%2Fuser-form.json

Everything is working as expected to construct the form/input.  I'm trying to define buttons inside the form and bind to an onClick, but I'm struggling to do so.  Most examples I've seen assumes the button/form is being constructed in the angular application, rather than being created from a JSON string.  (ex. https://stackblitz.com/edit/angular-t9xn4r-kpx1pc?file=src%2Fapp%2Fapp.component.ts)

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/issues/1819#issuecomment-571117573
