### ISSUE TITLE
Loading Radio/Select values from Service on init

### ISSUE THREAD

**Issue by ivorodriguezv** [ngx-formly/ngx-formly#2029]
Hey there! I'm needing some help with this issue.
I'm currently trying to load all the field values from an Employee Service which contains employees data. With textfields and calendars i had no problems at all but when it comes to radios, checkboxes and selects, the employee's attribute it's not rendered.(It's not a default value, it's the employee's value for that attribute)
I also load the options available for each one of this fields from arrays that are built from other service's data (parametrics)

Demo: https://stackblitz.com/edit/ngx-formly-ui-primeng-yjq4na

Thanks in advance!

**Comment by aitboudad** [comment]
The question is not clear enough, form what I've noticed in the attached example:
- the options should contain object with (`label` and `value`), you can adjust them through templateOptions: `valueProp` and  `labelProp`:

```ts
    {
      type: 'select',
      templateOptions: {
        options: [...],
        valueProp: 'id',
        labelProp: 'label',
      },
    },
```

- the passed model value expect passing number type and not object in order to match one the provided options:

```ts
    // Loads model
    this.model = {
      radio: 2034,
      select: 2034,
    }
```

https://stackblitz.com/edit/ngx-formly-ui-primeng-nnv4cc

**Comment by ivorodriguezv** [comment]
> The question is not clear enough, form what I've noticed in the attached example:
> 
> * the options should contain object with (`label` and `value`), you can adjust them through templateOptions: `valueProp` and  `labelProp`:
> 
> ```ts
>     {
>       type: 'select',
>       templateOptions: {
>         options: [...],
>         valueProp: 'id',
>         labelProp: 'label',
>       },
>     },
> ```
> 
> * the passed model value expect passing number type and not object in order to match one the provided options:
> 
> ```ts
>     // Loads model
>     this.model = {
>       radio: 2034,
>       select: 2034,
>     }
> ```
> 
> https://stackblitz.com/edit/ngx-formly-ui-primeng-nnv4cc

That actually fixed the problem. Thank you so much!!
