### ISSUE TITLE
Add fields dynamically after base json was generated

### ISSUE THREAD

**Issue by ivorodriguezv** [ngx-formly/ngx-formly#2030]
Hey! I've got another question for you guys:

I'm trying to add fields to an specific fieldgroup after a base json, with some default fields, was generated.
What i would like to do is to have an object that extends from a class (let's say it's FormlyFieldConfig) that contains the attributes that i need in order to push it into that specific fieldgroup.
For some reason, if I push an explicit object, it works but, when i try to push an object that has a type or extends an interface i get the "formGroup expects a FormGroup instance" error.

Demo: https://stackblitz.com/edit/ngx-formly-ui-primeng-4dewrm

Thanks in advance!

**Comment by aitboudad** [comment]
The second example should be initialized:
```patch
    // This is what I would like to do and does not work
++  let dynamic: FormlyFieldConfig = {};
--  let dynamic: FormlyFieldConfig;
    dynamic.key = 'custom_test';
    dynamic.type = 'input';

++  dynamic.templateOptions = {};
    dynamic.templateOptions.type = 'text';
```


Could you please update the above example that reproduces the error: "formGroup expects a FormGroup instance" error

**Comment by ivorodriguezv** [comment]
> The second example should be initialized:
> 
> ```diff
>     // This is what I would like to do and does not work
> ++  let dynamic: FormlyFieldConfig = {};
> --  let dynamic: FormlyFieldConfig;
>     dynamic.key = 'custom_test';
>     dynamic.type = 'input';
> 
> ++  dynamic.templateOptions = {};
>     dynamic.templateOptions.type = 'text';
> ```
> 
> Could you please update the above example to reproduces the error: "formGroup expects a FormGroup instance" error

Well, that actually fixed it! Thanks for that quick reply.
I was getting that error with the example I provided, but with those two initializations, the error disappeared!
