### ISSUE TITLE
Hide Expression Check is too late when using checkExpressionOn modelChange

### ISSUE THREAD

**Issue by pascalbe-dev** [ngx-formly/ngx-formly#2031]
**Description**
When using the extra `checkExpressionOn: 'modelChange'` to improve performance, the hideExpression Check is not evaluated early enough. It should be validated after the modelChange Event is fired, so that field hideExpressions can rely on the model. However, it is evaluated later which causes unwanted effects.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-1dm2uq

**Your Environment**

- Angular version: 7.2.15, 8.2.14
- Formly version: 5.5.9 (this does not appear with 5.5.8)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.10](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.10) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
