### ISSUE TITLE
tabindex on mat-radio-group is always set to -1

### ISSUE THREAD

**Issue by madmiki80** [ngx-formly/ngx-formly#2032]
Is there a way to set tabindex in a mat-radio-group?

I tried to use tabindex property in templateOptions in my formly configuration but when rendered is always set to -1

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.10](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.10) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
