### ISSUE TITLE
How to Create Dynamic Repeating Field

### ISSUE THREAD

**Issue by brownish** [ngx-formly/ngx-formly#2035]
**Question**
I am trying to create a repeat that allows a user to repeatedly create one of several field types, instead of the fields defined in `fieldArray`.

[Here's my stackblitz](https://stackblitz.com/edit/ngx-formly-ui-material-g1dyl2)

The way I've got it set up works, but it doesn't keep track of the model values. What do I need to do to get this to work?

Thanks!

**Comment by aitboudad** [comment]
the repeat type create field based on the model value, so the easy way is to rely on `hideExpression` and `model` value here is a quick attempt: https://stackblitz.com/edit/ngx-formly-ui-material-cstzpa

**Comment by darrenmothersele** [comment]
Is there any way to achieve this without having the hidden markup in the DOM for the unused field types? I have some very large forms where I've added this, and I feel like the overhead is significant.

**Comment by darrenmothersele** [comment]
Here's another example you posted that I was using for reference before: https://stackblitz.com/edit/angular-rxlpp4-qtkqng?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
@darrenmothersele which version of `formly` do you use?

**Comment by darrenmothersele** [comment]
Hey, I'm using 5.5.10

**Comment by aitboudad** [comment]
@darrenmothersele probably related to #1215 and the solution is to override our existing `formly-group` type by adding `*ngIf="!f.hide"` to the `formly-field` component, here is an example https://stackblitz.com/edit/angular-rxlpp4-qtkqng

```patch
    FormlyModule.forRoot({
      types: [
        { name: 'repeat', component: RepeatComponent },
+       { name: 'formly-group', component: GroupFieldType },
      ],
    }),
````
```ts
import { Component, HostBinding } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'formly-group',
  template: `
    <ng-container *ngFor="let f of field.fieldGroup">
      <formly-field [field]="f" *ngIf="!f.hide"></formly-field>
    </ng-container>
  `,
})
export class GroupFieldType extends FieldType {
  @HostBinding('class')
  get klass() {
    return this.field && this.field.fieldGroupClassName || '';
  }

  defaultOptions = {
    defaultValue: {},
  };
}
```

test it in your app and let me know if that improves the performance, if so I may consider adding it as a feature in 5.6 instead of v6 (but not sure yet).

**Comment by darrenmothersele** [comment]
Yes! Thank you that's much better.

**Comment by aitboudad** [comment]
I've got another optimization, noticeable during the first render (https://github.com/ngx-formly/ngx-formly/pull/2078).

To give a try, remove entirely the `form` tag:

```patch
- <form [formGroup]="form" (ngSubmit)="submit()">
  <formly-form
    [model]="model"
    [fields]="fields"
    [options]="options"
    [form]="form">
  </formly-form>
- </form>
```

*Note*: removing the `form` tag just for testing a proper fix will be released in the next version.

**Comment by darrenmothersele** [comment]
Thanks, we'll try that out

**Comment by aitboudad** [comment]
**Note**:

You may consider using `lazyRender` instead of overriding the `field-gropup` which has been introduced in [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0)
