### ISSUE TITLE
Form being marked as invalidad when navigating back and forward

### ISSUE THREAD

**Issue by jdavidhermoso** [ngx-formly/ngx-formly#2038]
Hi!

Thanks for the great work!
I have a project with different lazy loaded modules.
I created a wrapper component with the formly-form tag, where I actually create the FormGroup object.
The problem I have is when I navigate to a form page, wrote invalid values (form get's invalid) and navigate back and forward to the form, it's still invalid despite I'm recreating the FormGroup when user navigates to the component containing the formly-form tag.

An example can be seen here: https://github.com/jdavidhermoso/transporterapp

Steps to reproduce (using that repo)
1. Navigate to http://localhost:4200/dashboard/services
2. Focus all fields, but don't write any value (they are required, so with no value, they'll be invalid)
3. Navigate to http://localhost:4200/dashboard/locations
4. Navigate again to http://localhost:4200/dashboard/services
5. All fields in the form are invalid

Thanks in advance!

**Comment by aitboudad** [comment]
we store some internal state of the passed `fields` which require to recreate the fields, the solution is either to enable `immutable` mode:

```ts
@NgModule({
  imports: [
    FormlyModule.forRoot({
      extras: { immutable: true }
    }),
  ],
})
```

or use a `function` instead of `const` for `FormConfig`:

```patch
-export const LOCATION_FORM_CONFIG: FormConfig = {
-  acceptButtonTranslateKey: 'Guardar',
-  ...
-}
+export function LOCATION_FORM_CONFIG(): FormConfig {
+  return {
+    acceptButtonTranslateKey: 'Guardar',
+    ...
+  };
+}

export interface FormsConfigMap {
-  [name: string]: FormConfig;
+  [name: string]: () => FormConfig;
}

export class FormsConfigService {
   public getFormConfig(formName: string): FormConfig {
-    return formsConfigurations[formName];
+    return formsConfigurations[formName]();
   }
 }
```

**Comment by jdavidhermoso** [comment]
Thank you so much, @aitboudad!!! :)
