### ISSUE TITLE
template is sanitized by Angular

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2039]
```
{
      key: "test",
      template: `test: <input>`,
      templateOptions: {
        label: "test"
      }
    }
```
 WARNING: sanitizing HTML stripped some content, see http://g.co/ng/security#xss

this causes that <input> not being rendered.

**Comment by aitboudad** [comment]
use `sanitizer` service:

```ts
import { DomSanitizer } from '@angular/platform-browser';
...

fields: = [{
  key: "test",
  template: this.sanitizer.bypassSecurityTrustHtml(`test: <input>`),
  templateOptions: {
    label: "test"
  }
}];

constructor(private sanitizer: DomSanitizer) {}
```

**Comment by eng-dibo** [comment]
I know about `sanitizer`  service, but I mean that formly should do `bypassSecurityTrustHtml()`  for template value by default

**Comment by aitboudad** [comment]
ok, I'll mark this as a feature, adding an extra option to mark it safe but not by default:

```patch
fields: = [{
  key: "test",
  template: `test: <input>`,
  templateOptions: {
+    safeHtml: true
  }
}];
```

**Comment by eng-dibo** [comment]
I'm voting up for this feature, but what is the problem with making it safe by default, the template value is not dynamically created *i.e via an API call).

**Comment by aitboudad** [comment]
> with the problem with making it safe by default?

1. Breaking change
2. Consistency with angular HTML binding behavior
3. Devs should be aware of enabling this feature (in case the template is controlled by end-users/dynamically created).

**Comment by eng-dibo** [comment]
> use `sanitizer` service:
> 
> ```ts
> import { DomSanitizer } from '@angular/platform-browser';
> ...
> 
> fields: = [{
>   key: "test",
>   template: this.sanitizer.bypassSecurityTrustHtml(`test: <input>`),
>   templateOptions: {
>     label: "test"
>   }
> }];
> 
> constructor(private sanitizer: DomSanitizer) {}
> ```

keep in mined that this method will cause error TS2322: Type 'SafeHtml' is not assignable to type 'string'.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.6.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by eng-dibo** [comment]
wow, great news. ❤
I will give a try and give you a feedback.

**Comment by eng-dibo** [comment]
did'nt work 
https://stackblitz.com/edit/formly-dynamic-checkboxes?file=src%2Fapp%2Fapp.component.ts

also please check this [issue ](https://github.com/ngx-formly/ngx-formly/issues/2208)

I updated formly to the latest version.

**Comment by aitboudad** [comment]
```patch
  fields: [{
    key:"categories",
    template:'<input type="checkbox" name="test" value="ok"/> test<br />',
-    safeHtml: true
+    templateOptions: {
+      safeHtml: true
+    }
  }],
```

**Comment by eng-dibo** [comment]
still dosen't work.
the checkbox doesn't appear and a warning for sanitizing html stripped logged in the console.
