### ISSUE TITLE
How to use primeng autocomplete in angular formly(How to use completeMethod event in formly JSON)

### ISSUE THREAD

**Issue by praveenjm** [ngx-formly/ngx-formly#2041]
//I am using primeng lib in my lib. As I am implementing autocomplete functionality in formly so created autocomplete type with the help of"https://stackblitz.com/edit/ngx-formly-custom-template-3yvkcd" link. 

//AutoCompletecComponent
import { Component} from '@angular/core';
import { FieldType } from '@ngx-formly/core';   
@Component({
  selector: 'formly-autocomplete',
  template: `<p-autoComplete [suggestions]="results" 
  (completeMethod)="searchCity($event)"></p-autoComplete>`,
})
export class FormlyAutoCompleteComponent extends FieldType { 
    
}

//ParentComponent - trying to us searchCity function here
@Component({
  selector: 'parent-component',
  template: `<form [formGroup]="form">
    <formly-form [form]="form" [fields]="fields" [model]="testModal" [options]="options"> 
   </formly-form></form>`
export class ParentComponent{
constructor(){}
fields: FormlyFieldConfig[] = [
  "fieldGroup": [
    {
      "key": 'city',
      "type": 'autocomplete',
      "templateOptions": {
        "label": "City name",
        "placeholder": "Enter city"
      }
    },
    {
      "key": 'country',
      "type": 'select',
      "templateOptions": {
        "label": "country name",
        "placeholder": "select country"
      }
    }
  ]
] 
/*How to use it here, where this function triggers on **completeMethod event** from autoCompleteComponent?*/

_searchCity(event){
//do something
}_
}

**Comment by praveenjm** [comment]
Please help, If anyone know about this

**Comment by aitboudad** [comment]
`completeMethod` should be exposed through field `templateOptions` which allows being caught in `ParentComponent`:

```patch
@component({
  selector: 'parent-component',
  ...
})
export class ParentComponent {
  fields: FormlyFieldConfig[] = [
    {
      "key": 'city',
      "type": 'autocomplete',
      "templateOptions": {
        "label": "City name",
        "placeholder": "Enter city",
+        onComplete: () => { ... } 
      }
    }
  ];
}
```

```patch
@component({
  selector: 'formly-autocomplete',
  template: `
    <p-autoComplete
      [suggestions]="results"
+      (completeMethod)="to.onComplete($event)">
    </p-autoComplete>
  `
})
export class FormlyAutoCompleteComponent extends FieldType {}
```

** `to` is an alias of `field.templateOptions`.

** primeng use a `form-field` wrapper which displays label and validation so make sure to define it in NgModule declaration:

```patch
FormlyModule.forRoot({
  types: [{
    name: 'autocomplete',
    ...,
+    wrappers: ['form-field'],
  }]
}),
```

**Comment by praveenjm** [comment]
Hey thanks for the reply. Small correction to.complete() wont work to.change() is working

**Comment by aitboudad** [comment]
@praveenjm to update the model value either ensure your component support reactive forms which you'll need to add `[formControl]="formControl"` or update the value manually using `this.formControl.setValue(value)`.
if it doesn't work then I may need to share with me your example using `stackblitz`.

> Can you please make some documentation so that we can avoid asking questions everytime

I'm aware of that but it just a matter of time 😄!
