### ISSUE TITLE
Ngx-Formly Material Textarea matNativeControl

### ISSUE THREAD

**Issue by VladBozhinovski** [ngx-formly/ngx-formly#2042]
**Question**

Trying to get material textarea to look like bootstrap textarea with matNativeControl.

- Material: https://stackblitz.com/edit/ngx-formly-ui-material

Im using Angular Material NgxFormly. While using custom textarea component inside mat-form-field I would like to use matNativeControl on textarea to look like bootstrap textarea. Is it possible to achieve this? I tried everything but could not make it, al lI get is material like textarea.

**Comment by aitboudad** [comment]
Hi, can you share a `stackblitz` example of what you've done?

**Comment by VladBozhinovski** [comment]
> Hi, can you share a `stackblitz` example of what you've done?

I have fixed, it. We can close now. Just removed matInput and matNativeControl  in order toget normal textarea. Thanks for fast response.

**Comment by aitboudad** [comment]
I've filled an issue in material repo https://github.com/angular/components/issues/18254

**Comment by VladBozhinovski** [comment]
> I've filled an issue in material repo [angular/components#18254](https://github.com/angular/components/issues/18254)

Thank you for that @aitboudad

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
