### ISSUE TITLE
Firefox select box requiring two selects to work

### ISSUE THREAD

**Issue by nigelsim** [ngx-formly/ngx-formly#2043]
**Description**
This is a race condition that occurs in our application, which has a number of components interacting, and utilising the Angular UpgradeModule for some AngularJS components we are migrating. 

Using the Formly Bootstrap module, we have a form within a modal. We also have another component (Sortablejs) that registers a `mousedown` handler on `<body>`.

On Firefox, when the user clicks on the select box and then the option:
1. the native select box selects
2. the mousedown handler fires
3. this causes a change detection
4. the `FormlyFieldSelect.ngAfterViewChecked` method runs. at this point `this.formControl.value` has not been updated, so is null, causing the select box to be reset back to `this.select.nativeElement.selectedIndex = -1;`

On second selection the `this.formControl.value` === '' which prevents this occurring a second time.

My work-around is to set `changeDetection: ChangeDetectionStrategy.OnPush` on my component to prevent the change detection propagating to Formly.

None of this occurs on Chrome, but I don't know enough about the difference between the browsers to understand why.

**Minimal Reproduction**

I've not managed to do this yet, because of the complexity of the setup. I'll continue working on this, but for now I wanted to flag that this was occurring.

**Your Environment**

- Angular version: 8.2.14 (this has been happening from when we started with Angular 7)
- Formly version: 5.5.8 (this has been happening from when we started with Formly 4)

**Additional context**
This is the stack trace:

```
ngAfterViewChecked (select.ts#58)
callProviderLifecycles (provider.ts#572)
callElementProvidersLifecycles (provider.ts#541)
callLifecycleHooksChildrenFirst (provider.ts#529)
checkAndUpdateView (view.ts#375)
callViewAction (view.ts#615)
execEmbeddedViewsAction (view.ts#580)
checkAndUpdateView (view.ts#360)
callViewAction (view.ts#615)
execComponentViewsAction (view.ts#559)
checkAndUpdateView (view.ts#370)
callViewAction (view.ts#615)
execEmbeddedViewsAction (view.ts#580)
checkAndUpdateView (view.ts#360)
callViewAction (view.ts#615)
execComponentViewsAction (view.ts#559)
checkAndUpdateView (view.ts#370)
callViewAction (view.ts#615)
execEmbeddedViewsAction (view.ts#580)
checkAndUpdateView (view.ts#360)
callViewAction (view.ts#615)
execComponentViewsAction (view.ts#559)
checkAndUpdateView (view.ts#370)
callViewAction (view.ts#615)
execComponentViewsAction (view.ts#559)
checkAndUpdateView (view.ts#370)
callWithDebugContext (services.ts#630)
debugCheckAndUpdateView (services.ts#347)
detectChanges (refs.ts#261)
tick (application_ref.ts#642)
constructor (application_ref.ts#522)
invoke (zone.js#396)
onInvoke (ng_zone.ts#273)
invoke (zone.js#395)
run (zone.js#153)
run (ng_zone.ts#171)
constructor (application_ref.ts#522)
subscribe (event_emitter.ts#104)
__tryOrUnsub (Subscriber.ts#266)
next (Subscriber.ts#208)
_next (Subscriber.ts#140)
next (Subscriber.ts#100)
next (Subject.ts#71)
emit (event_emitter.ts#86)
checkStable (ng_zone.ts#240)
onLeave (ng_zone.ts#312)
onInvokeTask (ng_zone.ts#264)
invokeTask (zone.js#430)
runTask (zone.js#198)
invokeTask (zone.js#513)
invokeTask (zone.js#1671)
globalZoneAwareCallback (zone.js#1708)
```

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
