### ISSUE TITLE
Bind Subject Value - How to use?

### ISSUE THREAD

**Issue by Blucbo** [ngx-formly/ngx-formly#2048]
Hi. I try to bind subject input in custom field but do not work.

I create a custom field and want to subscribe input value like `[typeahead]`

Just see how works [[typeahead]](https://stackblitz.com/edit/ng-select-typeahead-when-search-cleared?file=src%2Fapp%2Fapp.component.html)

My demo with problem emit value to `typeahead: this.companyInput$,`
If I have subscribe it never call :( [ `companyInput$`](https://stackblitz.com/edit/angular-qiaypg?file=src%2Fapp%2Fapp.component.ts)

**Comment by aitboudad** [comment]
@Blucbo do you still need help on that part or you've got the solution?

**Comment by Blucbo** [comment]
@aitboudad How I can add custom types in to(templateOptions)?
something like this:
```
to: {
    initialValue: IOption[],
    request: (name: string) => void,
    items$: Observable<IOption[]>
  };
```

**Comment by aitboudad** [comment]
> How I can add custom types in to(templateOptions)?

@Blucbo if you mean for Typescript Typings, define a common `AppFormlyFieldConfig` where you merge all custom types with the `FormlyFieldConfig` as shown below:

```ts
interface NgAsyncSelectConfig extends FormlyFieldConfig {
  type: 'ng-async-select',
  templateOptions: FormlyTemplateOptions & {
    initialValue: IOption[],
    request: (name: string) => void,
    items$: Observable<IOption[]>
  };
}

type AppFormlyFieldConfig = FormlyFieldConfig
	| NgAsyncSelectConfig
    | ...;
```

Then import `AppFormlyFieldConfig` instead of `FormlyFieldConfig`:

```ts
import { AppFormlyFieldConfig } from '@libs/forms';
...
export class AppComponent {
  fields: AppFormlyFieldConfig[];
  ...
}
```


*Note*:
`to` is an alias of `templateOptions` that allows you to link field config inside your custom type.

**Comment by Blucbo** [comment]
Excuse me, my understanding is that expand types to(templateOptions) it is bad, but in HTML I have unresolved variables like(to.typeToSearchText)  why I am making in the custom field:
```
  to: FormlyTemplateOptions & {
      clearable: boolean,
      loading: boolean,
      hideSelected$: boolean
    };
```
https://stackblitz.com/edit/angular-qiaypg?file=src%2Fapp%2Ftypes%2Fng-select.type.component.ts

**Comment by aitboudad** [comment]
sorry but I'm still not clearly understood the issue/question.

> my understanding is that expand types to(templateOptions) it is bad

that's ok from my point of view.
