### ISSUE TITLE
matPreffix bug, using #matPrefix

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2049]
**Description**
when I use matPreffix the label is out of position (buggy)

![Captura de Tela_selecionar área_20200127154049](https://user-images.githubusercontent.com/11314585/73203190-52f60a00-411b-11ea-998e-b3367d3e209b.png)

Result
![Captura de Tela_selecionar área_20200127152757](https://user-images.githubusercontent.com/11314585/73203199-57babe00-411b-11ea-8106-9be02de9eaa8.png)

**Comment by aitboudad** [comment]
remove `matPrefix` in span:
```patch
- <span matPrefix
+ <span
```

if the issue still persist I may need a reproduction `stackblitz` example.

**Comment by GlauberF** [comment]
this did not solve my problem, however I created a different component to simulate suffix and preffix with specific customizations that I need.
thanks.
