### ISSUE TITLE
Expression Properties template Options are not instantly reflected in UI

### ISSUE THREAD

**Issue by pascalbe-dev** [ngx-formly/ngx-formly#2050]
**Description**
When using an observable as expression properties for template options, the values emitted by the observable are not instantly reflected in the UI. Say, we set the label via an Observable (it was not previously set), then the form field has no label until the field catches focus. Same applies e.g. to description.

current workaround: set the label to some static value. In this case the observable then overrides the values which is also reflected within the UI.

**Background**:
In our real example we're applying translated labels to all fields. Therefore we have an extension, which takes the key of the field and uses the ngx-translate translation service to get a translation stream. This stream is passed to the templateOptions.label expression property.

**Minimal Reproduction**
Check out, how the label becomes visible when we click the input field.
https://stackblitz.com/edit/ngx-formly-ui-material-xph8ca

**Your Environment**

- Angular version: 7.2.15, 8.2.14
- Formly version: 5.5.10

This is no show stopper since we can easily work around that, but I think, it should behave differently.

**Comment by aitboudad** [comment]
a part of this issue is related to material form-field which I've just filled a new issue in material repo https://github.com/angular/components/issues/18310

**Comment by pascalbe-dev** [comment]
Great, thanks for the quick feedback as usual.

**Comment by aitboudad** [comment]
since you're using an extension you may set translatable label with empty space as a workaround until material fixes the issue in their side:

```
label = ' ';
```

**Comment by pascalbe-dev** [comment]
yea, that's what I did (see above). so this is not very urgent. just wanted to mention it, since I think it should behave differently.

**Comment by aitboudad** [comment]
@pascalbe-dev could you please reply to https://github.com/angular/components/issues/18310#issuecomment-690979596 as he asked for a good use-case :thinking:
