### ISSUE TITLE
bind observable into input

### ISSUE THREAD

**Issue by boufenzi** [ngx-formly/ngx-formly#2053]
Hello guys, can someone help me find an example on how to bind observable into the default Value of an input. 
I tried something like this but it doesn't work : 

```
 {
          key: 'id',
          type: 'input',
          defaultValue: this.requete.get('http:...') .pipe(map(id => id)),
         templateOptions: {
            label: 'Numero CG',
             },
        },
```

thank you guys.

**Comment by aitboudad** [comment]
get first the config from the request then fill fields config.

```ts
@Component({
  selector: 'formly-app-example',
  template: `<formly-form [fields]="fields$|async" ...></formly-form>`
})
export class AppComponent {
  ...
  fields$ = this.requete.get('http:...').pipe(map(defaultValue => {
    return [
      {
        key: 'id',
        type: 'input',
        defaultValue,
        templateOptions: {
          label: 'Numero CG',
        },
      },
    ];
  }));
}
```

**Comment by boufenzi** [comment]
not the most cleanest code for a simple thing like defaultValue but thank you for your response.

**Comment by aitboudad** [comment]
we may allow passing an observable field instance in the future which will allow using the cleanest way 😄.

**Comment by boufenzi** [comment]
i found out a better solution hope it will help someone in the futur : 

```
         hooks: {
            onInit: (field => {
       this.requete.get('http:...')
                .toPromise().then(id=>  field.formControl.setValue((id)));
            }),
          },
```

**Comment by Blucbo** [comment]
@boufenzi I bind observable like this https://stackblitz.com/edit/angular-qiaypg?file=src%2Fapp%2Fapp.component.ts
