### ISSUE TITLE
Using YAML as the source for FormlyFieldConfig

### ISSUE THREAD

**Issue by dinhtrung** [ngx-formly/ngx-formly#2055]
I love this library. Have used it for all my angular projects for some time.

I saw in issues list, there is already proposal for JSON Schema. However, more and more ppl prefer YAML over JSON, because we can add comments and have more semantics way to describe the structure with YAML.

With js-yaml it is easy to convert between YAML into JSON, and assign the object to fields to describe the form.

The YAML also can be retrieve via static files or API so that dynamic form builder can be made.

For demonstration purpose, I have build a draft angular project to describe the approach here:

https://github.com/dinhtrung/angular-ryk7qv

(Unfortunately, cannot make it works on Slackblitz. :( )

What do you think of supporting YAML as the resource for Form Builder, instead of using JSON Schema?

**Comment by aitboudad** [comment]
Supporting multiple schemas is one of our priorities but first, I would like to simplify the implementation in `v6` by introducing a schema input.

For now `js-yaml` doesn't require too much work (compared to the `json-schema`) to be implemented and I think providing a demo example in our demo instead would be enough (similar to JSON https://formly.dev/examples/other/json-powered).

**Comment by dinhtrung** [comment]
Will json schema support expressionProperties like FieldConfig?

I found lots of use case with expressionProperties, from field validation, disable, enable, and extract user profile info. If that one missing from json-schema, that would be a huge step back.

In fact the most used widget i use in formly is ng-select, for lookup reference entries. I think that would be great if we have that field built in.

**Comment by aitboudad** [comment]
> Will json schema support expressionProperties like FieldConfig?

see https://github.com/ngx-formly/ngx-formly/issues/1993#issuecomment-568180138

**Comment by aitboudad** [comment]
After rethinking about this, `YAML` format doesn't require any special or extra work from our side, `js-yaml` should be enough so I'm going to close this issue.

Thank you for the proposal!
