### ISSUE TITLE
template bind model

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2057]
I don't know if you can already do that, but I haven't found it anywhere, but it would be very interesting to be able to print a certain value within a template type

```javascript
{
    className: 'section-label',
    template: '<div>{{model.label}}</div>',
}
```

**Comment by aitboudad** [comment]
use `expressionProperties`:

```ts
{
  className: 'section-label',
  expressionProperties: {
    'template': model => `<div>${model.label}</div>`
  }
}
```

**Comment by GlauberF** [comment]
Wow, this library is really good! :)
Thnaks @aitboudad

**Comment by GlauberF** [comment]
taking advantage of the issue, is it possible to render an existing component inside the formly?

**Comment by aitboudad** [comment]
it's on our todo, if you mean something like:

```ts
{ type: MyCustomComponent }
```
But already possible by overriding `FormlyConfig` service, in case you need it, let me know to provide you an example when time allows.

**Comment by GlauberF** [comment]
Perhaps something could be developed based on the idea of the material portal.
https://material.angular.io/cdk/portal/api

When you have time, if you want to send me an example replacing the FormlyConfig service, I am grateful.

and if you can send me the link to follow this feature, I am grateful.

**Comment by aitboudad** [comment]
Well, I think creating a custom field type `portal` that uses `cdk` portal would do the job too.

> and if you can send me the link to follow this feature, I am grateful.

To get notified when a new release is published:

- Follow us on https://twitter.com/formlydev
- Or use watch on release only:

<img width="336" alt="Capture d’écran 2020-01-30 à 12 10 30" src="https://user-images.githubusercontent.com/1753742/73444827-b53c4e00-4359-11ea-983a-63c9b61613b4.png">
