### ISSUE TITLE
IE11 - Radio Button Group - Change/Selection Not Occuring

### ISSUE THREAD

**Issue by devinci** [ngx-formly/ngx-formly#2058]
**Question**
Our company uses this library to dynamically generate forms. We've one of our clients is required to use IE, however one of the issues that's been raised is that radio buttons groups & checkboxes aren't working on forms. I couldn't test via your site as the UI examples fail to render. 

From my testing it looks like the change event isn't being fired and the mat-radio-group doesn't get the value of the mat-radio-button selected along with the class update for the mat-radio-group.

Using the same code from Angular Material (which works on IE11) here:
https://material.angular.io/components/radio/examples

However, as soon as I pass this through formly as a custom FieldType (as type 'radio' fails as well), it fails.

Do you have any suggestions or workarounds for this? 

_unfortunately IE isn't capable of plunkr or stackblitz to share an example_

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by devinci** [comment]
Thank you for the quick turn around on this. Fixed on my side now. Nice to see your site working on IE as well. 😅 

Appreciate it. 👍
