### ISSUE TITLE
Cannot inject parent wrapper components into child field components

### ISSUE THREAD

**Issue by vespertilian** [ngx-formly/ngx-formly#2060]
**Description**

Wrapper components are created after field components, for a FieldGroup. This means you cannot inject the parent wrapper into the child fields. Being able to inject parent components is a super handy Angular feature I was taking advantage of in V4 of Formly. 

The component hierarchy is created correctly it's just that the fields are created before the wrapper so they cannot be injected. 

<img width="1007" alt="formly-issue" src="https://user-images.githubusercontent.com/441418/73410570-c768bd00-4356-11ea-86a9-85f12c8fad52.png">

**Minimal Reproduction**
See the example in this branch of the ngx-formly repo
https://github.com/vespertilian/ngx-formly/tree/wrappers-are-created-before-their-child-fields

**Your Environment**

- Angular version: 8
- Formly version: 5

**Additional context**
This was not an issue in Formly V4

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by vespertilian** [comment]
@aitboudad Thank you for your quick work on this, I will check it out today and let you know how I go.

**Comment by vespertilian** [comment]
@aitboudad mostly looks good. The only thing I have noticed is that it still creates the header (field) before the wrapper. It also creates another header (field) after the wrapper. So injection works for the second field we create. 

The first header field we create I assume we do nothing with and don't really need to create at all?

5.5.10
<img width="1496" alt="10" src="https://user-images.githubusercontent.com/441418/73701447-bbf20900-473d-11ea-86f0-7173fc320ef4.png">

5.5.11
<img width="1497" alt="11" src="https://user-images.githubusercontent.com/441418/73701473-ce6c4280-473d-11ea-93e7-65a738947290.png">

**Comment by aitboudad** [comment]
> The first header field we create I assume we do nothing with and don't really need to create at all?

That's expected, the first created one is not for a specific field but a global one where we can update the field before rendering step.
