### ISSUE TITLE
Sometimes the input fields are not filled even tho the model has content inside it

### ISSUE THREAD

**Issue by zakircinjarevic** [ngx-formly/ngx-formly#2064]
Dear Formly creators !

I enjoy using formly in my project, but I have stumbled on some problems, and I don't know if it's me or something else.

This is the issue : The page loads for editing of content, the model gets filled, and all the inputs that have the key bound to the model should be filled with data,  but recently I added a couple of inputs that hold image url, and when I enter the edit component, the fields are not filled. I wonder why. I had a similar problem before and I solved it on one field by checking if I am using async await properly, but the problem now occured on another field. I dont know if its because the amount of data in the component and the asynchronousness of the component.

I would appreciate any tips you might have for me. 
Thank you for creating formly and thank you for your response !

**Comment by aitboudad** [comment]
Hi, could you please provide an example using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap that reproduces the issue.

Thanks!
