### ISSUE TITLE
Wierd behavior if you hide then show a form

### ISSUE THREAD

**Issue by bchehab** [ngx-formly/ngx-formly#2066]
Hello,

I am getting wierd behavior after I updated formly to 5.5.10.

I was previously using 5.5.6 and wasn't facing these issues but I'm not sure if this behavior is by design or if it's is a bug.

Please check the following link to reproduce it: https://angular-wqn8sy.stackblitz.io

1. Hide textbox (using a checkbox)
2. Hide form
3. Show form
4. try to uncheck the checkbox to show the textbox again. The textbox won't show. so HideExpression doesn't function properly anymore.

Thank you.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
