### ISSUE TITLE
Model value changed by dynamically. but the formly form component render when action.

### ISSUE THREAD

**Issue by sbala69gmail** [ngx-formly/ngx-formly#2070]
**Question**

I need to design formly like belows example. 

![image](https://user-images.githubusercontent.com/2879062/73593701-e8830680-452c-11ea-9990-7496a9bf004a.png)

Senario:

1. upload from one attribute and update it to another attribute. how to do it. 

The upload component calls upload function and upload to the server and return the upload ID. 
Bind that ID to the model component `this.model =  { ...this.model, ["documents"] : [...this.model["documents"], {}] }`, but the form is not rendered properly. I use `this.form.patchValue(this.model)` also. Even I click submit that time form render and shows the field.

Note: 'It's all in UploadComponent.ts'

Thanks in advance.

**Comment by aitboudad** [comment]
To update the model value use `this.formControl.setValue`, to define a hidden field you may use `{ key: 'id' }` without passing type and to access to that field value from the `form` instance use `this.form.get(id).patchValue(id)`.

 
I'm assuming that you're https://formly.dev/examples/advanced/repeating-section which would simplify the implementation of the above example in that case you may create a custom field type for upload (UploadComponent) in addition to the repeat field type:

```ts
// UploadComponent
onUploaded(id) {
  this.formControl.setValue(id);
}
```

for the `id` field config: 
```ts
{
  key: 'id',
  type: 'upload',
}
```

**Comment by sbala69gmail** [comment]
My requirement was to change `this.model` value in child component. The parent component was CompanyComponent, The child component is `UploadComponent` it upload file to server and get a unique ID and set to the `this.documents[]`. DocumentComponent is a custom repeat component. 

My Problem. 
If I change `this.documents` value in parent component form render automatically. The child component `UploadComponent` is a read-only model. So not possible to set model value. Only possible to set the `form.setValue`. 


Please:
I use `BehaviorSubject` for model value change from child to parent (hope this is not current method). is any other function is available in formly to update the parent model value?

**Comment by aitboudad** [comment]
why not just merge the upload field type with repeat one, I think that allows you to add a field using the `add` method:

```ts
export class UploadComponent extends FieldArrayType {}
  onUplaoded(fieldId: string) {
    this.add(null, { fieldId, "name" : "john", "valid_till": "" });
  }
  ...
}
```

and the field config should be:
```ts
export class CompanyComponent {
  form = {
    "fieldGroupClassName": "row clearfix",
    "fieldGroup": [
      {
        "key": "documents",
        "type": "files-upload",
        ...
      }
    ]
  }
}
```
