### ISSUE TITLE
Trigger custom validator after server side validation

### ISSUE THREAD

**Issue by yluijten** [ngx-formly/ngx-formly#2074]
**Use case**
I have a form and a submit button. When the form is submitted, it will perform some additional validation on server side. A validation message needs to be mapped on a form field if the key of that specific field is listed in the respons object from the server.

**Question**
Is it possible to manually trigger a custom validator and show a validation message as soon as I've received the respons?

**Example**
[https://stackblitz.com/edit/formly-validate-on-submit](https://stackblitz.com/edit/formly-validate-on-submit)

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/703#issuecomment-364660359
