### ISSUE TITLE
Tabs with input type content and other tabs that also have content

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2075]
I need to create the following screen below and before I leave writing code I would like an idea / suggestion, how I could do that.

I have a main TAB, called ( **Informações** ),
inside this tab, I have input type fields and I have other Tabs and in these other tabs, plus other fields, as the image shows
If you can help me and share a stackblitz, how would you do that, I would be grateful :)

![Captura de Tela_selecionar área_20200204094011](https://user-images.githubusercontent.com/11314585/73746221-7a5c6080-4733-11ea-93fa-b42a33975652.png)

**Comment by aitboudad** [comment]
You may register a custom field type for that, there are some examples that you may check:

- https://github.com/ngx-formly/ngx-formly/pull/1294/files
- https://github.com/franzeal/ngx-formly-tabs

**Comment by GlauberF** [comment]
@aitboudad 
I don't know if you can help me, but I would be very grateful if I could. We could use it as an example for those who come looking for something similar to what I'm developing in the future.

I'm trying to create a specific type to handle what I need, following the library as a base (https://github.com/franzeal/ngx-formly-tabs).
There's the stackblitz here: https://stackblitz.com/edit/mat-tabs-vimbo-form

However I cannot function 100%, the first TAB does not appear, the others do and I would like some ideas to make it less verbose, cleaner.

the folder responsible for the customizable type is `mat-tabs`
