### ISSUE TITLE
Global "find by key"

### ISSUE THREAD

**Issue by ivorodriguezv** [ngx-formly/ngx-formly#2076]
Hey there!
I would like to know if there's a way to find a field in a Tabs form that also has groups without using indexes.
Currently I'm using this.tabs[0].fields[0].fieldGroup[3].templateOptions.options in order to set gender's field options (key= 'gender'). It would be awesome to do something like: this.tabs.fields.find(x => x.key === 'gender').templateOptions.options.
Thanks in advance!

**Comment by aitboudad** [comment]
Why not just passing the `options` through `templateOptions` 🤔:

```ts
{
  key: 'gender',
  templateOptions: { options: [...] }.
}
```

**Comment by ivorodriguezv** [comment]
Im generating the json through a service that brings it's base structure (which is stored in the database). After i generate it, i insert it's fields options (which are obtained through different parametrics, that's why i insert them, so i don't have to save them in the database).

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/815#issuecomment-374586474
