### ISSUE TITLE
Adding ngx-admin (nebular) templates

### ISSUE THREAD

**Issue by raphxyz2** [ngx-formly/ngx-formly#2079]
**Description of request.**
I will just to use ngx-formly with an ngx-admin (nebular)

**Solution**
Adding ngx-admin to templates (@ngx-formly/ngx-admin)

**Additional context**
```typescript
@NgModule({
  imports: [
    ...,
    ReactiveFormsModule,
    FormlyModule.forRoot(),
    FormlyNgxAdminModule,
    ...
  ],
})
export class AppModule {}
```
Thanks for your great Jobs.

**Comment by aitboudad** [comment]
`ngx-admin` use `nebular` UI which is in our [Roadmap](https://github.com/ngx-formly/ngx-formly/issues/1365) 😄.

close in favor of #1365
