### ISSUE TITLE
Advanced Layout (Flex) - fxFlex inputs

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2080]
I'm following this example (https://formly.dev/examples/other/advanced-layout-flex) to create a flex layout, but the example is very simple and I would like to know how to work with input sizes using fxFlex, as there is no need for me to be creating classes, if there are options to be used that controls that.

if you can share any example working with fxFlex the inputs within the fieldGroup, thank you.

if you also have more references on how to use and available options

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/issues/2019#issuecomment-573456870
