### ISSUE TITLE
Question regarding error: Cannot find control with unspecified name attribute

### ISSUE THREAD

**Issue by zulis** [ngx-formly/ngx-formly#2083]
Creating form builder. Using formly with Angular drag & drop. Getting an error `Cannot find control with unspecified name attribute` on field add. As suggested here https://github.com/ngx-formly/ngx-formly/issues/1023 we should return new ref for the fields, unfortunately can't find a solution that works when Angular drag & drop is used.

Please check an example: https://stackblitz.com/edit/ngx-formly-drag-drop-field-1a82a4?file=src%2Fapp%2Fdrag-drop.type.ts

How to make it work?

**Comment by aitboudad** [comment]
The form requires to be re-built, you may use `_buildForm` after `copyArrayItem`:

```ts
// Try #1
copyArrayItem(...);

(<any> this.options)._buildForm(true);
```
