### ISSUE TITLE
Required Custom Fields

### ISSUE THREAD

**Issue by ivorodriguezv** [ngx-formly/ngx-formly#2084]
Hey there!

I would like to know if it's possible to set the "Required" option from a custom field. Im trying to do so by doing the following, but it's ignoring the required status.

`{
                key: 'photo_url',
                type: 'profile-picture',
                templateOptions: {
                  required: true,
                  label: 'Profile Picture',
                  options: [],
                },
},`

Thanks in advance!

**Comment by aitboudad** [comment]
validation message is included in `form-field` wrapper so use one of the following solutions:

1. use `form-field` wrapper in your custom field type:
```patch
    FormlyModule.forRoot({
      types: [
        {
          name: 'custom',
          component: CustomFieldType,
+          wrappers: ['form-field'],
        },
      ],
    }),
```

2. or include `formly-validation-message` component

```html
<formly-validation-message *ngIf="showError" [field]="field"></formly-validation-message>
```
