### ISSUE TITLE
Mat Tabs, Example and Problem

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2085]
I am opening a new issue, based on https://github.com/ngx-formly/ngx-formly/issues/2075, to be easier to be found by future developers who need to implement dynamic tabs.

Stackblitz here:  https://stackblitz.com/edit/mat-tabs-vimbo-form

@aitboudad, I don't know if you can help me, but it's still not 100%.
When I have more than one TAB, it shows only the last one, maybe it can be something with ng-content, if you can help me, I am grateful and follows as an example for future developers, because on the internet there is no example.

Improvements are also welcome.

**Comment by aitboudad** [comment]
Please consider reducing asking a lot of questions (use https://stackoverflow.com/ instead), I've already provided enough info in the previous issue.
Thanks!

**Comment by GlauberF** [comment]
ok @aitboudad , I opened a question there (https://stackoverflow.com/questions/60121060/custom-type-mat-tabs-for-ngx-formly-does-not-render-the-content-of-all-tabs)
but if you can help me, I would like it.
I've tried everything already.
