### ISSUE TITLE
Allow passing TemplateRef to template

### ISSUE THREAD

**Issue by dummdidumm** [ngx-formly/ngx-formly#2086]
https://formly.dev/examples/bootstrap-specific/advanced-layout shows how to use the `template` option to have arbitrary html between fields. So far we can only pass strings to it, so the content is static. It would be great if we could also pass `TemplateRef` to it.

```html
<ng-template #myTemplate>
  <p (click)="doStuff()">{{ 'Dynamic content' | translate }}</p>
</ng-template>
```

```ts
@ViewChild('myTemplate') myTemplate: TemplateRef<any>;
fields = [
  ....
  { template: myTemplate },
  ...
];
```

**Comment by aitboudad** [comment]
relying on `ViewChild` would require to wait until the view is initialized to get the template ref instance, so instead, here is my proposal, so let me know WDYT:

```ts
@Component({
  selector: 'app',
  template: `
    <form-form [form]="form" [fields]="fields" [model]="model">
      <ng-template formlyTemplate="customId">
        <p (click)="doStuff()">{{ 'Dynamic content' | translate }}</p>
      </ng-template>
    </form-form>
  `,
})
export class AppComponent {
  fields: FormlyFieldConfig[] = [
    { templateRef: 'customId' }
  }];
}
```

**Comment by dummdidumm** [comment]
Feels very elegant, no boilerplate needed to import ViewChild -> looks great!

**Comment by lohiaad** [comment]
@aitboudad nice solution for custom template support. 
Can we use this solution to show custom option in dropdown / autocomplete. eg - my autocomplete FieldType will use this template to render options. in this way we will have only 1 autocomplete FieldType which can be used at multiple places.
eg - https://ng-select.github.io/ng-select#/templates

**Comment by aitboudad** [comment]
updated my solution https://github.com/ngx-formly/ngx-formly/issues/2710#issuecomment-792260405 which will be available in `V6` alpha version, let me know WDYT

**Comment by shinde-prasad** [comment]
@aitboudad 

> relying on `ViewChild` would require to wait until the view is initialized to get the template ref instance, so instead, here is my proposal, so let me know WDYT:
> 
> ```ts
> @Component({
>   selector: 'app',
>   template: `
>     <form-form [form]="form" [fields]="fields" [model]="model">
>       <ng-template formlyTemplate="customId">
>         <p (click)="doStuff()">{{ 'Dynamic content' | translate }}</p>
>       </ng-template>
>     </form-form>
>   `,
> })
> export class AppComponent {
>   fields: FormlyFieldConfig[] = [
>     { templateRef: 'customId' }
>   }];
> }
> ```

In this how to get that method response (return values) in your parent components.?

**Comment by aitboudad** [comment]
> In this how to get that method response (return values) in your parent components.?

not clear what do you mean, the inline type is part of `v6` which you can give a try using `6.0.0-next.1` version

https://github.com/ngx-formly/ngx-formly/issues/2710#issuecomment-792260405

**Comment by eng-dibo** [comment]
`ViewChild` is available only in `ngAfterViewInit` and not available in `ngOnInit`. that is mean the template reference is available after the form is rendered.

if you render the form in `ngAfterViewInit` you will get an error of changing the view after it has been checked
