### ISSUE TITLE
Angular 9, Multicheckbox not working - please help

### ISSUE THREAD

**Issue by pjobs** [ngx-formly/ngx-formly#2089]
**Description**
With No code changes when angular project is upgraded from Angular 8.x to 9.0.0, multicheckbox types and some times regular checkboxes are not working. I have upgraded to ngx-formly 5.5.11 too.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-63eynk?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 9.0.0
- Formly version: 5.5.11

-> Cannot select or doesn't show them selected when the model has values too.

**New Update**
-> Just realized that it might be a style issue of selected checkboxs

**Comment by aitboudad** [comment]
that's a material regression, I've filled an issue https://github.com/angular/components/issues/18465

**Comment by aitboudad** [comment]
you'll need to wait until material release `9.0.1` which fixes this issue.

**Comment by pjobs** [comment]
thank you very much

**Comment by pjobs** [comment]
@aitboudad, I was hoping 9.0.1 of @angular/components would fix this, but still happening

**Comment by aitboudad** [comment]
I'll provide a workaround then :), I'll let you know once done!

**Comment by JCarroll2019** [comment]
I am also having this issue.  Was this fixed in a later release?

**Comment by aitboudad** [comment]
@JCarroll2019 yes, the issue has been fixed in [v5.5.13](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.13).
