### ISSUE TITLE
Autocomplete with ChangeDetectionStrategy.OnPush - not working

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2092]
My components, I try to develop them all using `changeDetection`, like` ChangeDetectionStrategy.OnPush`.

Everything works perfectly, but I'm having trouble making the autocomplete work properly.
If you access this stackblitz (https://stackblitz.com/edit/angular-autocomplete-dinamico), and type two words and delete them one by one, you will notice that sometimes it does not search for all values, it takes time to reflect the change on the screen.

**GIF showing error**
![Cfr4vto](https://user-images.githubusercontent.com/11314585/74284166-f17c9080-4d01-11ea-877c-480f47371ba6.gif)

I came up with a solution, which would be to use `pipe` and` tap`:
```javascript
filter: (term) => {
          return of(
            this.filterStates('Autocomplete', term)
          ).pipe(
              tap(() =>
                  this._changeDetectorRef.markForCheck()
              )
          );
        }
```

But I believe there is a better way to do this.
If you can help, I am very grateful.

**Comment by aitboudad** [comment]
Our example works with Onpush as expected https://stackblitz.com/edit/angular-akmbez, so you may need to investigate what's going wrong with your code.

**Comment by GlauberF** [comment]
I found a problem, but I had done that way because of the loading.

in the old way, I had a load set to true in the request and false at the end of it within the subscriber.
```javascript
this.formControl.valueChanges
      .pipe(
        takeUntil(this._unsubscribeAll),
        startWith(''),
        debounceTime(100),
        tap( () => {
          this.isLoading = true
        } ),
        switchMap( term => this.to.filter(term) )
      ).subscribe( (val) => {
          // if (!val) {
          //   return null;
          // }
          this.filter = val;
          this.isLoading = false;
      });
```

to work just like your example, I need to leave it like this, I can put the `tap` method to set it to true, but I don't know how to set it to false after the data returned

```javascript
this.filter = this.formControl.valueChanges
      .pipe(
        takeUntil(this._unsubscribeAll),
        debounceTime(300),
        startWith(''),
        tap(() => {
          this.isLoading = true
        }),
        switchMap(
          term => this.to.filter(term)
        )
      );
```

any suggestions, how to set false after the request ?

tried this, but it doesn't work properly.
```javascript
this.filter
      .pipe(
        takeUntil(this._unsubscribeAll)
      )
      .subscribe( r => {
        console.log('res', r);
        this.isLoading = false
      })
```

**Comment by GlauberF** [comment]
Solution

```javascript
this.result$ = this.formControl.valueChanges
      .pipe(
        takeUntil(this._unsubscribeAll),
        debounceTime(300),
        startWith(''),
        tap((a) => {
            this.isLoading = true
        }),
        switchMap(
          term => this.to.filter(term)
            .toPromise()
            .then( response => {
              this.isLoading = false
              return response;
            })
        )
      );
```

**Comment by GlauberF** [comment]
@aitboudad   it is necessary in these cases below, within the custom type, to put a `takeUntil(this._unsubscribeAll)`, then call on `ngOnDestroy`.

in this example:
```javascript
this.result$ = this.formControl.valueChanges
      .pipe(
        takeUntil(this._unsubscribeAll),
        debounceTime(300),
        startWith(''),
        tap((a) => {
            this.isLoading = true
        }),
        switchMap(
          term => this.to.filter(term)
            .toPromise()
            .then( response => {
              this.isLoading = false
              return response;
            })
        )
      );
```

and in this example
```javascript
this.result$
            .pipe(takeUntil(this._unsubscribeAll))
            .subscribe(res => {
                this.noResultsFound = !(res && res.length);
            })
```

???
