### ISSUE TITLE
Cannot type in more than one char in fields with immutable set to true

### ISSUE THREAD

**Issue by yuchuan1** [ngx-formly/ngx-formly#2093]
**Question**

After adding extras: { immutable: true } to module and  (modelChange)="model = $event" to formly-form, cannot continuously type in UI fields. It only allows one character.

[stackblitz](https://stackblitz.com/edit/angular-jn49oq)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.12) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
