### ISSUE TITLE
Expression properties check is too late when using checkExpressionOn modelChange

### ISSUE THREAD

**Issue by 0x253** [ngx-formly/ngx-formly#2095]
**Description**
Similar to https://github.com/ngx-formly/ngx-formly/issues/2031, when using the extra checkExpressionOn: 'modelChange' to improve performance expressionProperties are checked to late (after the second key stroke or after the input focus has been lost).

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-eijnkd

**Your Environment**
- Angular version: 8.2.14
- Formly version: 5.5.11

**Additional context**
This bug is similar to https://github.com/ngx-formly/ngx-formly/issues/2031 and has already been fixed in version [v5.5.10](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.10)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.12) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by 0x253** [comment]
Awesome, works as expected!
