### ISSUE TITLE
dynamically create a custom type

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2099]
I want to conditionally create a custom field type, based on some data that is fetched from API.

example:
I want to fetch the categories from the server, and create a custom checkbox inputs  with tabs (spaces) 
before each child category.

for instance: 
  - development
      - front-end
          - Angular
          - React
          - Vue
      - back-end
         - nodejs
         - php
- another category
   - child category
      - child of child
           - child of child of child

to achieve this goal, I have to create a custom field type `categories` which might be created dynamically based on the response from the API, which is an array contains the categories: `[ {title, parent} ]`

I reviewed the following issues, but couldn't get arround my issue:
https://github.com/ngx-formly/ngx-formly/issues/1091
https://github.com/ngx-formly/ngx-formly/issues/1147
https://github.com/ngx-formly/ngx-formly/issues/1233

I also tried to use a variable inside the custom field, and then pass the fetched categories to it, and it will create the inputs based on the received entries.

**Comment by aitboudad** [comment]
well I don't see the need for the dynamic field type, just passing observable option (to make the `api` call) and render the categories using a tree component that supports reactive-form: for material check https://material.angular.io/components/tree/overview else use CDK tree https://material.angular.io/cdk/tree/overview

**Comment by eng-dibo** [comment]
Ok, and after the categories fetched and rendered by <mat-tree> how can I bind it to the form?

**Comment by eng-dibo** [comment]
do you mean?
```
{
 template: getCategories().subscribe(categories=>{
   //use <mat-tree>
   return categories
 })

}
```

**Comment by aitboudad** [comment]
Maybe you didn't describe well the desired behavior. if I correctly understood you're looking for a tree category field type where users can select one or more categories.

1. Create a custom [field type](https://formly.dev/guide/custom-formly-field)  with name `tree-category`:

```ts
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
 selector: 'formly-tree-category',
 template: `
   <mat-tree ...>
   </mat-tree>
 `,
})
export class TreeCategoryFieldType extends FieldType {}
```


```ts
@NgModule({
 declarations: [TreeCategoryFieldType],
 imports: [
   ....
   FormlyModule.forRoot({
     types: [
       { name: 'tree-category', component: TreeCategoryFieldType },
     ],
   }),
 ],
})
export class AppModule {}
```



2. pass the list of `categeries` through `templateOptions` of the field config:

```ts
fields = [
  {
    key: 'categories',
    type: 'tree-category',
    templateOptions: {
      categories: this.http.get('API_URL'),
    }
  },
]
```

**Comment by sparshbhardwajj** [comment]
Hi, Can I populate the input field from API, I want to auto-populate the input field from the login API once the user comes to the form so his name and email should be pre-filled.

Please suggest.

**Comment by aitboudad** [comment]
@sparshbhardwajj pass the value to `defaultValue` property

**Comment by sparshbhardwajj** [comment]
@aitboudad {
          type: 'input',
          key: 'customerId',
          hooks: {
            onInit(field) {
              const control = field.formControl;
              if (control.value === null) {
                control.setValue(this.userName);
              }
            }
          },
        },
        
        this is not working for me, my username is in userName, please suggest.

**Comment by sparshbhardwajj** [comment]
@aitboudad please responde.

**Comment by kenisteward** [comment]
@sparshbhardwajj 

Just as a heads up, in general it would be nice to allow people who are helping up to 24 hours to respond.  There may be other things they have to do before they can come back to assisting you.  Also, this is a closed ticket that has to do with something completely different than what originally was being asked so it might help to always update with a new ticket that has exactly what you are asking for in it.

It would be very helpful if you would provide and example of what you are not able to figure out in stackblitz.  This is the baseline suggestion we make to people as it makes it easier for us to provide an example of what people are looking for.

That being said, there are ample examples over at https://formly.dev 
Here's the example to how to set a default value for a field:
https://formly.dev/examples/field-options/default-value

Also note: in this it suggests setting default values by defaulting the model first but if you want to use default value on the field config you can.

**Comment by sparshbhardwajj** [comment]
Apologies!

I have an HTML form for login by which the user login and comes to formly multi-step form, here I want to set his name and email to be prefilled by the login API which he has filled there.
I am able to console the name and email on the formly form page but was not able to populate those in the input field.

I have tried using defaultValue but here I can only set defaultValue like 100 but not able to pass the variable userName that contains his name in the input field.

Please suggest.

**Comment by aitboudad** [comment]
@sparshbhardwajj, just assign those value to the model input and Formly will populate them:

```
this.model = {
  email: '***',
  password: '***'
}
```

You may check our example as well https://formly.dev/examples/other/json-powered, which show how to populate those field from the API.

**Comment by sparshbhardwajj** [comment]
Great, It works for me. Thanks for your help.

**Comment by its-dibo** [comment]
> 2\. pass the list of `categeries` through `templateOptions` of the field config:

now this won't work, after changing `templateOptions` into `props`, it seems that props now doesn't accept arbitrary data.
so we cannot do this:

```
{
  props:{
    // or any arbitrary data
    categories:[]
  }
}
```

@aitboudad
