### ISSUE TITLE
Mat-Checkbox isn't clickable anymore on Angular 9

### ISSUE THREAD

**Issue by flobiber** [ngx-formly/ngx-formly#2101]
**Description**
With Angular & Material 9 the checkbox isn't changing it status by clicking on it!

**Minimal Reproduction**
https://stackblitz.com/edit/angular-formly-mat-checkbox

**Your Environment**

- Angular version: 9
- Formly version: 5.5.11

**Additional context**
No error inside the console!

**Comment by aitboudad** [comment]
related to https://github.com/ngx-formly/ngx-formly/issues/2089#issuecomment-584774504

**Comment by johannesjo** [comment]
Just for the record: It's clickable and works fine, it's just that the checkmark is barely visible.

**Comment by pjobs** [comment]
It is still happening even with  9.0.1 of @angular/components,

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.13](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.13) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
