### ISSUE TITLE
Question: Modify/Transform values model -> view -> model

### ISSUE THREAD

**Issue by JanLoebel** [ngx-formly/ngx-formly#2102]
**Question**

Hi everyone! First of all thanks for the great project of yours :)

I have a (in my mind) simple question but don't find a good solution. In my model I have a numeric value e.g.: 100 this needs to be editable in an input type=number field. The problem now is that I want to display/edit it with a factor. So 100 should end up as "1" if I change it now to 3.4 i want to update the model to 340. I've found parsers but they just work one way. I already have a custom control and also need validation to work. Any best practices here or have I to handle the conversion in my custom control?

Thanks for any help/tipp/idea!
Best regards, Jan

**Comment by aitboudad** [comment]
see https://stackoverflow.com/a/59741142/1406096
