### ISSUE TITLE
Custom Radio/Checkboxes inline support

### ISSUE THREAD

**Issue by asadsahi** [ngx-formly/ngx-formly#2103]
Currently radio/checkbox controls supports following options:

```
      formCheck: 'custom', // 'custom' | 'stacked' | 'inline'

```
Can this also support custom inline as shown [here](https://getbootstrap.com/docs/4.4/components/forms/#inline-1)

![image](https://user-images.githubusercontent.com/3470892/74649987-a1c21d00-5178-11ea-8b51-2fc0deb7f036.png)

Of course custom field is one option. But nice to have a built in option.

Thanks

**Comment by aitboudad** [comment]
added inline support in [v5.6.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.0) release.

**Comment by asadsahi** [comment]
Awesome work @aitboudad . Thanks you very much.
