### ISSUE TITLE
[Question] How to add additional attribute in ngx-formly model?

### ISSUE THREAD

**Issue by vishnu-dev** [ngx-formly/ngx-formly#2105]
https://stackoverflow.com/questions/60280550/how-to-add-additional-attribute-in-ngx-formly-model

I have my formly fields configured as below,

    fields: FormlyFieldConfig[] = [
        {
          key: 'uuid',
          type: 'input',
          templateOptions: {
            label: 'Input',
            placeholder: 'Placeholder',
            description: 'Description',
            required: true,
            attributes: {
              mapsTo: 'somevalue'
            }
          },
        },
      ];

**I have an extra field called `mapsTo` that I need for some business logic. But how do I have the value in the model?**

My HTML is as below

    <form [formGroup]="form">
      <formly-form [model]="model" [fields]="fields" [options]="options" [form]="form"></formly-form>
    </form>
    
    {{model | json}}

So, the model has

    { "uuid": "some input" }

But I'm not able to add `mapsTo` to the final form data.

https://stackblitz.com/angular/xvrmevmqnnq

**Comment by aitboudad** [comment]
> What I need is, something like
{ "uuid": {"value": "some input", "mapsTo": "somevalue"} }

use `fieldGroup`:

```ts
fields: FormlyFieldConfig[] = [
  {
    key: 'uuid',
    fieldGroup: [
      {
        key: 'value',
        type: 'input',
        templateOptions: {
          label: 'Input',
          placeholder: 'Placeholder',
          description: 'Description',
          required: true,
        },
      },
      { 
        key: 'mapsTo',
        defaultValue: 'somevalue',
      }
    ]
  }
];
```
