### ISSUE TITLE
Angular Material - validation message not showing if required set dynamically

### ISSUE THREAD

**Issue by Gobikannan** [ngx-formly/ngx-formly#2106]
First of all, thanks alot for the awesome library. It is easy to configure and flexible to modify as we want.

I have an requirement to set field2 as required based on field1. It works absolutely fine but validation message doesn't show properly. Here is the simple example which I have created,

[stackblitz](https://stackblitz.com/edit/ngx-formly-validation-msg)

Steps to reproduce:

1. Enter something on field1 and it shows asterik (*) on field2 but it doesn't show the message as Field required.
2. I tried clicking on the field2 but still it doesn't show message.

I am not sure if this is something to do with Angular material.

**Comment by Gobikannan** [comment]
Thanks @aitboudad.. when will be this available?

**Comment by aitboudad** [comment]
up to Monday

**Comment by Gobikannan** [comment]
Thanks @aitboudad, that's pretty quick..

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.13](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.13) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by Gobikannan** [comment]
Thanks @aitboudad.. Now it shows validation message but it doesn't hide once it is shown.

I have updated the packages on same sample link - https://stackblitz.com/edit/ngx-formly-validation-msg

If i add some test to field1 then field2 show mandatory (*) and if focus on field2, then it shows validation message but it doesn't hide the validation message and shows red even if i remove values from field1 (which is not mandatory - but removes (*) from field2)..

Is it something you can take a look please? let me know if you need more details on replicating it.

Thanks.

**Comment by aitboudad** [comment]
`required` expects a boolean value, try with:
```patch
expressionProperties: {
  'templateOptions.required': (model: any, formState: any, fieldConfig: FormlyFieldConfig) => {
+    return !!model.field1;
-    return model.field1;
  },
}
```

**Comment by Gobikannan** [comment]
Ofcourse.. Thanks, it works fine on our code. 
Cheers,
