### ISSUE TITLE
get value of checked inputs

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2108]
I have created two custom types, one for checkbox inputs and another for radio inputs.
(I don't want to use the built-in checkbox & radio types)

radio inputs work fine, but checkbox inputs value always null even if it already checked.

https://stackblitz.com/edit/angular-jcu3ib

**Comment by aitboudad** [comment]
the rendered HTML through `innerHTML` will not be recognized by angular (directives and component won't work), the template should be compiled first which won't work in AOT mode. 

The only feasible way can be found in  https://github.com/ngx-formly/ngx-formly/issues/1091#issuecomment-466511867

**Comment by eng-dibo** [comment]
the inputs are already rendered correctly, since I use native input elements, not custom components.

the radio input modifies the model when it checked as expected, but the checkbox input doesn't.

**Comment by aitboudad** [comment]
the radio input is rendered through the angular template but the checkbox is using `innerHTML` which is not the same.

**Comment by eng-dibo** [comment]
I'm sorry that I removed my comment. I understood your answer and I will try the mentioned answer.

**Comment by eng-dibo** [comment]
I modified the code and used `fieldGroup` as mentioned, but this solution didn't help me.

**Comment by aitboudad** [comment]
sorry, but the request still not clear enough to me and there is an angular limitation for rendering an HTML content. From my side, I've provided all the necessary information, the provided example for runtime field type is working as expected you've to adjust it to your needs.
