### ISSUE TITLE
Material Slider using input-event value

### ISSUE THREAD

**Issue by WastedFreeTime** [ngx-formly/ngx-formly#2110]
Hello Community, 
I want to sync the material slider value smooth with a number input field while dragging the slider but to do something like this i need the current slider value(while sliding).  
Currently the model value gets only updated after releasing the slider.
Is this the wanted behavior? 

In Material i would use the input event for this.
<mat-slider (input)="onInputChange($event)"></mat-slider>

Can you please add a way to access the slider input event value or update the model based on input to get the value while sliding. 
What you think?

**Comment by aitboudad** [comment]
Hi, I'll check it later (when time allows 😄) but for now, I'd suggest creating your own slider type here is the Formly slider source code: https://github.com/ngx-formly/ngx-formly/tree/v5/src/material/slider/src
