### ISSUE TITLE
Template not responding to delayed model values that are pushed using the Repeating Sections feature.

### ISSUE THREAD

**Issue by hshm1944** [ngx-formly/ngx-formly#2112]
**Description**
I am using the Repeating Sections feature. I have an array in the `model` called `accounts` which is empty. In the `ngOnInit()` method, I added a delayed Promise of 10 seconds (to mock real requests) that resolves to a function that pushes an object to the `accounts` array. The model object itself is updated, but the template is not. I have to manually click "Add" to make the form appear.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ddghfa

**Your Environment**

- Angular version: 8.2.14
- Formly version: 5.0.0

**Comment by hshm1944** [comment]
I was able to get the form rendered by re-building it using `FormlyFormBuilder` after the data are fetched successfully. But, is this the correct way of getting the form rendered?

Example:
```
constructor(private builder: FormlyFormBuilder) {}

ngOnInit() {
    ...
    .then(() => {
        this.builder.buildForm(this.form, this.fields, this.model, this.options);
    });
}
```

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/975#issuecomment-394647380
