### ISSUE TITLE
Cannot set property 'undefined' of undefined

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2113]
When inserting a field group, inside another one, I am returning the following error:
**Cannot set property 'undefined' of undefined**

![Captura de Tela_selecionar área_20200221135418](https://user-images.githubusercontent.com/11314585/75054468-deac4d80-54b1-11ea-929e-76e02297e98d.png)

the error is where it is selected, but if I define a type, it works.
however, I cannot have a type or a key, as I will use it to group only for layout purposes

**Comment by aitboudad** [comment]
use https://stackoverflow.com/
