### ISSUE TITLE
Bypass Async Validation

### ISSUE THREAD

**Issue by githubUserVV** [ngx-formly/ngx-formly#2114]
Hello, 

So I have a pretty long form and one of the fields has an asyncValidator. 
if (res) from someFunction() is true, ill hide item2, if it's false, i'll hide item1. 
I also set the value of those fields to whatever the response is.
The problems resides when I change the hideexpression to true or false. 
I'm guessing that calls the updateValueAndValidity() which calls my async validator. 
The problem is, it calls it a billion times and never stops. 
I'm wondering how I can stop the validation since it's calling the asyncValidator on "validatingField" which is not even being changed.

Hopefully this small example helps you gain a good understanding of what I am saying. 
It looks vaguely like this:

```
options: {
  formState:{
      hideexpression: true
   }
}
```

```
{ 
fieldGroup:[
 key:'validatingField',
  asyncValidators:{
     validator:{
        expression:{
             .....
            return new Promise ((resolve, reject) => {
                service.validate(control.value).subscribe(d => { 
                    if(d.value == 1){
                    { this.someFunction(d) }
                 resolve{d.value == 1}}
        }
      }
  ]
 },
 {
  fieldGroup:[
      key: 'item1',
      hideExpression : '!formState.hideexpression'
    },
   {
      key: 'item2',
      hideExpression : 'formState.hideexpression'
    },
  ]
}
```
  
      

```
someFunction(d){
  this.anotherService(d).subscribe((res) => {
     if(res == true){
         //problem here
         this.options.formState.hideexpression = true;
         this.form.get('item1).setValue(res);
      }
      else if(res == false){
          //problem here
          this.options.formState.hideexpression = false;
          this.form.get('item2).setValue(res)
      }
  }
}
```

**Comment by aitboudad** [comment]
can you try https://github.com/ngx-formly/ngx-formly/issues/1620#issuecomment-514639091

**Comment by githubUserVV** [comment]
Doing that doesn't trigger the hideexpression change :/

**Comment by aitboudad** [comment]
it should be triggered manually for `formState` https://github.com/ngx-formly/ngx-formly/issues/1773#issuecomment-531766229

**Comment by aitboudad** [comment]
Note: the above solution is just a temporary workaround until I've got the time to fix the issue

**Comment by githubUserVV** [comment]
I have actually looked into that solution but for some reason, it still calls my asyncValidator indefinitely SOMETIMES.

it ONLY does that when i change the options.formState.hideexpression.

**Comment by githubUserVV** [comment]
I was able to fix it. I moved around the initialization of a field within someFunction()

Because the validator was being called multiple times, the field was being changed too often and it was stuck in a loop.

The validator is only being called twice per hideexpression change but I can see that was something that was still a problem despite your 5.5.2 fix because it's an angular issue

Thank you for your quick answers :)
