### ISSUE TITLE
Ngx Formly Repeat section radio buttons

### ISSUE THREAD

**Issue by imran-hub** [ngx-formly/ngx-formly#2115]
I have added radio button in repeat section, whenever I am clicking a radio button it is getting selected even if previous row radio button is already selected. What I want that if a radio button is selected then , it should deselect the previous ones and select current. I am unable to do that, please suggest me how can I achieve this in ngx formly.
Angular version: 8.3.22
ngx-formly/core:  4.0.2
ngx-formly/material: 4.0.2

![contact](https://user-images.githubusercontent.com/40102304/75219348-87b0bc00-57c2-11ea-84a3-7b3deb492f69.PNG)

**Comment by aitboudad** [comment]
Hi, can you replicate your example using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-material
also updating to Formly `v5` is highly recommended (all relevant changes are mentioned in [UPGRADE-5.0](https://github.com/formly-js/ngx-formly/blob/master/UPGRADE-5.0.md)) 
Thanks!

**Comment by Arth1993** [comment]
Hello,

Were there any updates on this issue? I have created a sample stackblitz: https://angular-f32jic.stackblitz.io/

Basically, is there a function which would select the Primary Flag radio button only once across all the repeated blocks? When user selects one of the Primary radio buttons, all other radio buttons should be de-selected. 
![image](https://user-images.githubusercontent.com/12847675/118728849-d5b84200-b802-11eb-90db-1495cd72bb9d.png)

**Comment by aitboudad** [comment]
@Arth1993 see https://stackblitz.com/edit/angular-f32jic-uew38o?file=src/app/app.component.ts

**Comment by kenisteward** [comment]
@aitboudad 

@Arth1993 actually works for the same company I do.  I wrapped our proprietary logic and components around ngx-formly with support for separate schemas/layouts :)

I'm glad the solution you gave coincides with the one we came up with internally!

**Comment by Arth1993** [comment]
Thank you @kenisteward and @aitboudad. Really Appreciate your help.

**Comment by aitboudad** [comment]
> I'm glad the solution you gave coincides with the one we came up with internally!

:+1:, the only missing part that we should improve is to simplify finding the field, something like:

```patch
- const radioField = f.fieldGroup.find(f => f.key === 'PrimaryFlag');
+ const radioField = f.get('PrimaryFlag');
```

https://github.com/ngx-formly/ngx-formly/issues/2854
