### ISSUE TITLE
Dynamically set custom validators

### ISSUE THREAD

**Issue by dima12qw** [ngx-formly/ngx-formly#2116]
Hello,

I have such situation, I have a field, and based on value, I want to set validators on another field: 

`if(value === 'X'){
field.validators = {validation: ['custom1']};
field.formControl.updateValueAndValidity();
} else{
field.validators = {validation: ['custom2']};
field.formControl.updateValueAndValidity();
}`

It works in OnInit, but when I change the value, it doesn't update validity on formControl.

**Comment by aitboudad** [comment]
right now we only support changing the built-in validations, for custom ones either pass extra params through `templateOptions` instead:

```
{
  key: 'name',
  validators: { validation: ['custom1', 'custom2'] },
  templateOptions: {
    custom1: false, //  custom1 validator enabled unless `custom1 === false`
  }
}
```

**Comment by dima12qw** [comment]
> right now we only support changing the built-in validations, for custom ones either pass extra params through `templateOptions` instead:
> 
> ```ts
> {
>   key: 'name',
>   validators: { validation: ['custom1', 'custom2'] },
>   templateOptions: {
>     custom1: false, //  custom1 validator enabled unless `custom1 === false`
>   }
> }
> ```

**Comment by aitboudad** [comment]
you can get the field instance as the second argument of the custom validator:
```ts
export function custom1Validator(c: AbstractControl, field: FormlyFieldConfig): ValidationErrors | null {
  if (field.templateOptions.custom1 === false) {
    return null;
  }
  ...
}

**Comment by dima12qw** [comment]
> you can get the field instance as the second argument of the custom validator:
> 
> ```ts
> export function custom1Validator(c: AbstractControl, field: FormlyFieldConfig): ValidationErrors | null {
>   if (field.templateOptions.custom1 === false) {
>     return null;
>   }
>   ...
> }
> ```

I did it in another way, I set validator on field, and on field.formControl, and then called updateValueAndValidity and worked.

**Comment by aitboudad** [comment]
ok just be aware in that case the [built-in validations](https://formly.dev/examples/validation/built-in-validations) such as `required` may not be triggered.
