### ISSUE TITLE
Access values of other fields in validation

### ISSUE THREAD

**Issue by WastedFreeTime** [ngx-formly/ngx-formly#2117]
Hey one question;
Is there a way to get the value of other fields in validation without putting them into a fieldGroup? 
Something like: 

```
{ 
    key: 'a',
    type: number,
    validators: { 
         validation: {
              if ((a + b + c) > 100) return  true;
         }
},
{
    key: 'b',
    type: number,
},
{
    key: 'c',
    type: number,
}
```
In my case i need to check the sum of three values.
Iam sure you have an idea @aitboudad .

Thanks for help!

**Comment by aitboudad** [comment]
use `control.parent.get('c')`.

Note: the validation won't be triggered when `b` or `c` changes, that's why the validator should be defined in the parent field.

**Comment by aitboudad** [comment]
see https://formly.dev/examples/validation/matching-two-fields
