### ISSUE TITLE
modelChange event not triggering when custom field is updated second time

### ISSUE THREAD

**Issue by Priyesha** [ngx-formly/ngx-formly#2118]
**Current behavior**: 

I have a field like this - 
```
fields: FormlyFieldConfig[] = [

    {
      key: 'data',
      wrappers: ['datawrapper'],
      templateOptions: { label: 'Keyword' },
      fieldGroup: [{
        key: 'firstName',
        type: '**autocomplete**',
        templateOptions: {
          label: 'Auto Complete',
          hideLabel: true,
        },
      }]
    }
```

For type 'autocomplete', there is a custom component that also implements ControlValueAccessor. 
 `<custom-input [formControl]="formControl"></custom-input>
`

When i update the field first time, the modelChange is triggered, however on updating again, the model is not updated and modelChange does not get triggered.

**Your Environment**

Angular Version - 7.0.0
@ngx-formly/core Version - 5.5.11

Expected Behaviour: 
Everytime on updating the input field, modelChange should trigger.

**Comment by aitboudad** [comment]
Hi, could you please provide a `stackblitz` example to reproduce the issue.
Thanks!
