### ISSUE TITLE
If parent control is readOnly:true then child controls should be readOnly:true also?

### ISSUE THREAD

**Issue by Adam-Michalski** [ngx-formly/ngx-formly#2119]
**Description**
When control in schema has `readOnly: true` (tasks) then all of its children (title, details, done in item) should be set to readOnly.
In my reproduction example you can see that when parent is set to `readOnly` children are not responding to this change, but only for their individual set of `readOnly` value

**Minimal Reproduction**
[StacBlitz nested example](https://stackblitz.com/edit/angular-ngx-formly-parent-readonly?file=src%2Fassets%2Fjson-schema%2Fnested.json)

**Comment by aitboudad** [comment]
why not using `disabled` instead, which take account of parent control

**Comment by Adam-Michalski** [comment]
I am mapping readOnly to diasbled in mapFn but when schema is 'globaly' marked as readOnly form does not disable in cause readOnly is interpreted for properties and not to whole form.
[formly-json-schema.service.ts only one place with readOnly](https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/json-schema/src/formly-json-schema.service.ts#L62)

[Stackblitz example nested schema with global readOnly](https://stackblitz.com/edit/angular-ngx-formly-parent-readonly?file=src%2Fassets%2Fjson-schema%2Fnested.json)

Is this how it's supposed to work?

**Comment by aitboudad** [comment]
for `json-schema` I think we should mark field children as readOnly too
