### ISSUE TITLE
Focus on dynamically hidden/unhidden fields

### ISSUE THREAD

**Issue by githubUserVV** [ngx-formly/ngx-formly#2120]
Hello, I am here for another question.

I see that this issue is _similar_ but I was not able to use it for my problem. 
https://github.com/ngx-formly/ngx-formly/issues/1203

I have a form that hides/unhides two templates.
One is an input ("input1"), one is a select box ("select1"). 
"input1" is thedefault. 

Based on what is entered in "name" input field, I either hide or unhide the "input1"/"select1" box. Only one of them are shown at any given time. I enable/disable hide based on a "hideexpression" in my options object. 

```
fieldGroup:[
  {
     fieldGroup: [
       {
         key: "name",
         type: 'input"
        }
      ],
     fieldGroup: [
       {
         key: "input1",
         type: 'input",
         ...
         {expressionProperties: { 'hideExpression' : '!formState.hideexpression'}}
        }
      ],
     fieldGroup: [
       {
         key: "select1",
         type: 'select"
         ...
         {expressionProperties: { 'hideExpression' : 'formState.hideexpression'}}
         *NEEDS FOCUS HERE WHEN UNHIDDEN AND OPEN THE SELECT BOX AUTOMATICALLY*
        }
      ],
  }
]
```
     

If something is entered in the "name" field that unhides the select box.
How can I set the focus onto the select box when that is NOT the form that is in the initial creation.
**And on top of that, is there a way to OPEN the select box when the focus is on that box?**

Thank you

**Comment by aitboudad** [comment]
> How can I set the focus onto the select box when that is NOT the form that is in the initial creation.

set `field.focus` to true, `hideExpression` allow passing a function so it should be handled to something like:

```ts
'hideExpression' : (m, formState, field) => {
 const hide = !formState.hideexpression;
 if (field.hide && !hide) {
   setTimeout(() => field.focus = true, 100);
 }

 return hide;
},
```

> is there a way to OPEN the select box when the focus is on that box?

not sure if there is a straight way to open the native select box programmatically, but any way to get the select element from the field use `field.id`:

```ts
document.querySelector(`#${field.id}`); // <select ...
```
