### ISSUE TITLE
Error "passing 'type' property is not allowed when 'template' is set" even when template set to null

### ISSUE THREAD

**Issue by rogercoder** [ngx-formly/ngx-formly#2121]
Yes! I did!

**Description**

In ngx-formly version 4 I had been emitting field json like this:
```
"type":"select", 
"template":null,
```
This worked fine, but this was broken in commit 71d343e02dc49f3981cff5383b1ff76ff34eedc0, where the check was previously:
`if (field.template) ...`
So if the template were null, everything was fine.
But in this commit the check was changed to:
`if (field.hasOwnProperty('template') ...)`
which is true even if the value of "template" is null.
So now I'm getting the error:
`NgxFormly: passing 'type' property is not allowed when 'template' is set.`
In my opinion the error is not really correct ... if "template" is null it is not actually being "set" to anything.

Is there a reason you are no longer checking to see if the template has been set?

I don't know about the larger issue you were trying to fix, but if you have no objection I could do a pull request with line 77 changed to:
`(field.hasOwnProperty('template') && field.template)`
**Minimal Reproduction**

In the stackblitz note that the text input and select question have disappeared because I set `template: null` for both of them:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-bsjvxi?file=src/app/app.component.ts

**Your Environment**

- Angular version: 9.0.2
- Formly version: 5.5.12

**Additional context**

**Comment by rogercoder** [comment]
I have downgraded to 5.5.7 for the time being and the fields in my forms are showing again.

**Comment by aitboudad** [comment]
is there any relevant reason that prevent you to remove entirely `template` instead of set it to `null`?

**Comment by rogercoder** [comment]
The json is generated programmatically using Spring on the server side. So if the template is not set the json is generated as `template: null`. 

The problem, starting with ngx-formly 5.5.8, is that the code no longer checks if the template is set (despite what the error message says): it now only checks to see if the _template attribute exists_.

In my proposed fix ngx-formly would once again check to see if the template were set.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.14](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.14) release.

as @kenisteward suggested It would be better to avoid passing unnecessary data 😄!
