### ISSUE TITLE
How to get notification, event about build form process from fields and model end?

### ISSUE THREAD

**Issue by Adam-Michalski** [ngx-formly/ngx-formly#2123]
How to get notified when build process/creation from fields and model form is finished?

When form is populated with model to associated fields.

```
<formly-form [model]="model" (modelChange)="onModelChange($event)" [form]="form" [fields]="fields"></formly-form>
```

**Comment by aitboudad** [comment]
related to https://github.com/ngx-formly/ngx-formly/issues/1912
