### ISSUE TITLE
How to upload xls,csv and pdf type of files using formly module?

### ISSUE THREAD

**Issue by bejgumshirisha** [ngx-formly/ngx-formly#2124]
I have a requirement where user can submit file attachments(any type of file formats) and after submitted user can download the submitted files along with other content.I tried with custom field type file but I am unable to send it to server.

I want to know how to send the files to server.If it is a image I can send as base64 format.whereas if file type is other than image how can I send the file data to server.

**Please find the stackblitz url for the sample application which I tried.**
**https://stackblitz.com/edit/angular-wqiool?file=src%2Fapp%2Fapp.component.ts**

**Comment by aitboudad** [comment]
well that's not a Formly question, you've got a FileList instance from the model and the rest can be handled by HTTP request anyway check my comment for the upload part https://github.com/ngx-formly/ngx-formly/issues/1491#issuecomment-484849907
