### ISSUE TITLE
How to use ngx-formly hideExpression to hide and display child elements based on parents value

### ISSUE THREAD

**Issue by siddheshpdy** [ngx-formly/ngx-formly#2125]
**How to use ngx-formly hideExpression to hide and display child elements based on parents value**

> I want to use formly to build a form for the following scenario:

1. there are three sibling elements
2. out of which two elements are dependant on the value of one sibling element which is radio button group. i.e I want to hide or display basic and advance form based on recipientQueryOption
3. I am using the JSON file to store schema so not able to write hide expression directly into the schema.

I tried using Extension for hiding expression, But as I found that in Extension data available in the model is limited to the element where hide expression is written and its child elements and doesn't contain data for its parent element. As data for a parent is not available, I am not able to check the value of the radio button and not able to decide whether to hide an element or not.

> following is JSON schema:

```
{
	key: 'Recipients',
	fieldGroup: [{
			key: 'recipientQueryOption',
			type: 'radio',
			templateOptions: {
				required: true,
				options: [{
						value: 'queryBuilder',
						label: 'queryBuilder'
					},
					{
						value: 'queryEditor',
						label: 'queryEditor'
					},
				],
			},
			defaultValue: 'queryBuilder'
		},
		{
			key: "basic",
			fieldGroup: [{
				key: 'recipients',
				type: 'chips',
				templateOptions: {
					label: 'Recipients',
					placeholder: 'add recipients...',
					required: true,
				}
			}],
			hideExpression: "hide_expression"
		},
		{
			key: "advance",
			fieldGroup: [{
					key: 'recipients',
					type: 'textarea',
					templateOptions: {
						label: 'Recipients',
						placeholder: 'Enter Query',
						required: true,
					}
				},
				{
					template: '<b>Note:</b> No validation is done on the queries submitted from the Query Editor tab.',
				}
			]
		}
	]
}
```

Is there any workaround for this?

**Comment by aitboudad** [comment]
try with:

```ts
hideExpression: "field.parent.model.recipientQueryOption !== 'queryBuilder'"
```

or:
```ts
hideExpression: () => this.model.recipientQueryOption !== 'queryBuilder',
```

more details can be found in https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

**Comment by rinku435** [comment]
how to markAsUntouched()?

**Comment by aitboudad** [comment]
@rinku435 you can get access of `markAsUntouched` from `field.formControl` property.
