### ISSUE TITLE
How to use datepicker options for material datepicker

### ISSUE THREAD

**Issue by siddheshpdy** [ngx-formly/ngx-formly#2127]
**How to use date picker option for material date picker**

Hello,
I want to use the following material date picker options:
1. dateChange
2. want to disable input field of date picker so that date picker will only be opened when a user clicks on the icon
3. change min and max date values - there are 2 date pickers to get date range. 

Following is angular material date picker example that I want to generate using formly:

```
     <mat-form-field>
          <input matInput [(ngModel)]="configuration.parameters.fromDate"     
               [max]="getMaxDate(configuration.parameters.toDate,today)"
               [matDatepicker]="fromDate" placeholder="from Date" 
               (dateChange)="changeEvent('changeFromDate')" disabled>
          <mat-datepicker-toggle matSuffix [for]="fromDate"></mat-datepicker-toggle>
          <mat-datepicker #fromDate disabled="false"></mat-datepicker>
     </mat-form-field>
     <mat-form-field style="margin-left: 10px;">
          <input matInput [(ngModel)]="configuration.parameters.toDate" 
               [min]="getMinDate(configuration.parameters.fromDate)" [max]="today"
               [matDatepicker]="toDate" placeholder="to Date"                    
               (dateChange)="changeEvent('changeToDate')" disabled>
          <mat-datepicker-toggle matSuffix [for]="toDate"></mat-datepicker-toggle>
          <mat-datepicker #toDate disabled="false"></mat-datepicker>
     </mat-form-field>
```
I want to use highlighted options:

<input matInput [(ngModel)]="configuration.parameters.fromDate"     
    **[max]="getMaxDate(configuration.parameters.toDate,today)"**
    [matDatepicker]="fromDate" placeholder="from Date" 
    **(dateChange)="changeEvent('changeFromDate')"**  **disabled**>
<mat-datepicker-toggle matSuffix [for]="fromDate"></mat-datepicker-toggle>
<mat-datepicker #fromDate **disabled="false"**></mat-datepicker>

is there any way to use these parameters with formly?

**Comment by siddheshpdy** [comment]
@aitboudad I have created my custom type for date picker and used it in JSON, it is working fine.

I can get the date-change event in JSON and invoke the function for it **(currently, the schema is in TS file but have to move it to JSON file)**. now the issues are: 
1. that how to write that function call into JSON file.
2. how to assign variables value to maxDate when the variable is in TS file and ref is in JSON file

```
{
          key: 'dateOn',
          id: 'dateOn',
          type: 'date',
          templateOptions: {
                    label: 'on Date',
                    placeholder: 'on Date',
                    dateChange: ($event) =>this.changeEvent($event),
                    changeEventName:"changeOnDate",
                    maxDate : this.today
          },
 },
```

**Comment by aitboudad** [comment]
> 1. that how to write that function call into JSON file.

https://github.com/ngx-formly/ngx-formly/issues/1819#issuecomment-571117573

>  2. how to assign variables value to maxDate when the variable is in TS file and ref is in JSON file

use [formState](https://formly.dev/examples/form-options/form-state)

**Comment by aitboudad** [comment]
added dateInput and dateChange option in [v5.6.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.0) release.

**Comment by shinde-prasad** [comment]
@aitboudad I am using mat-datepicker with custom header. Where I cant use (click) method events on next and previous button click. So how can I get that method response in json as a custom method in templateOptions:{}.
