### ISSUE TITLE
field's dynamic labels always show 'true' when fieldArray expressionProperties'['templateOptions.disabled']' evaluate as true

### ISSUE THREAD

**Issue by CharithFIT** [ngx-formly/ngx-formly#2128]
please refer  https://stackblitz.com/edit/angular-4nqyar-ylxewh to reproduce the issue.

![image](https://user-images.githubusercontent.com/321686/75963569-ade00580-5f00-11ea-9737-cca439393398.png)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.14](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.14) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
