### ISSUE TITLE
Material guidelines for checkbox/radio-buttons

### ISSUE THREAD

**Issue by fetters5** [ngx-formly/ngx-formly#2131]
**Question**
I was wondering if you could explain the reasoning behind nesting mat-checkbox and mat-radio inside of mat-form-field, my understanding was that the material team recommended against doing that. 

I love the product, I currently use my own custom material implementation but was hoping to move  to your implementation

```
The following Angular Material components are designed to work inside a <mat-form-field>

<input matNativeControl> & <textarea matNativeControl>
<select matNativeControl>
<mat-select>
<mat-chip-list>

```

Thanks!

**Comment by aitboudad** [comment]
see https://github.com/angular/components/issues/7891

**Comment by fetters5** [comment]
Thank you, my googlefu failed me when trying to find the reasoning.  Awesome piece of software you all created
