### ISSUE TITLE
How to add translations for the datepicker, dropdown and radio buttons

### ISSUE THREAD

**Issue by SwapnilChidrawar** [ngx-formly/ngx-formly#2134]
**Question**

I have integrated Date picker into my angular version 8 and it is working as expected. My form uses internationalization to which ngx-formly supports with the help of ngx-translate. I would like to know how these controls date picker, dropdown and radio button options get translated because workaround or any sample example for it is not present anywhere.

Angular version: 8
ngx-formly version: 5.5.13

**Comment by aitboudad** [comment]
The [doc example](https://formly.dev/examples/advanced/i18n-alternative) shows how to translate the field label but doesn't prevent you to add extra fields.

for `options`, pass all labels to the `stream` method and then replace them with the loaded ones:

```ts
if (Array.isArray(field.templateOptions.options)) {
  const options = field.templateOptions.options;
  field.templateOptions.options = this.translate
    .stream(options.map(o => o.label)).pipe(
      map(labels => {
        return options.map(o => ({ ...o, label: labels[o.label] }));
      })
    )
  ;
}
```

**Comment by SwapnilChidrawar** [comment]
Not getting ... please send me example on any of the control

**Comment by aitboudad** [comment]
I don't have enough time for that :pray:, it's better to provide me a stackblitz example which you can export it from our doc example https://formly.dev/examples/advanced/i18n in order to identify what's going wrong on your side.

Thanks!

**Comment by ranibb** [comment]
> The [doc example](https://formly.dev/examples/advanced/i18n-alternative) shows how to translate the field label but doesn't prevent you to add extra fields.
> 
> for `options`, pass all labels to the `stream` method and then replace them with the loaded ones:
> 
> ```ts
> if (Array.isArray(field.templateOptions.options)) {
>   const options = field.templateOptions.options;
>   field.templateOptions.options = this.translate
>     .stream(options.map(o => o.label)).pipe(
>       map(labels => {
>         return options.map(o => ({ ...o, label: labels[o.label] }));
>       })
>     )
>   ;
> }
> ```

This returns back label undefined

**Comment by eggp** [comment]
@SwapnilChidrawar and @ranibb 

easy ;)

```
import { TranslocoService } from '@ngneat/transloco';
import { FormlyExtension, FormlyFieldConfig } from '@ngx-formly/core';
import { isEmptyString } from '@XXXX/type-guard';

export class TranslocoExtension implements FormlyExtension {
  constructor(private translocoService: TranslocoService) {}

  prePopulate(field: FormlyFieldConfig) {
    const to = field.templateOptions || {};
    if (!to.transloco || to._translocoTranslated) {
      return;
    }

    to._translocoTranslated = true;

    const translatedTexts = {
      'templateOptions.label': this.translocoService.selectTranslate(to.label)
    };
    if (!isEmptyString(to.placeholder)) {
      translatedTexts['templateOptions.placeholder'] = this.translocoService.selectTranslate(to.placeholder);
    }

    field.expressionProperties = {
      ...(field.expressionProperties || {}),
      ...translatedTexts
    };
  }
}

export function registerTranslocoExtension(translocoService: TranslocoService) {
  return {
    /* validation not required, because use out implementation validation component */
    extensions: [
      {
        name: 'transloco',
        extension: new TranslocoExtension(translocoService)
      }
    ]
  };
}
```

**Comment by aitboudad** [comment]
> Can you please explain why for label translation you use expressionProperties like `field.expressionProperties['templateOptions.label']` and for options translation you do it directly on templateOptions? Why not `field.expressionProperties['templateOptions.options']` ?

That's just an example, if `field.expressionProperties['templateOptions.options']` is suitable to your needs then its ok as well.
