### ISSUE TITLE
Invalid validation message class name in PrimeNG

### ISSUE THREAD

**Issue by rternavskyi** [ngx-formly/ngx-formly#2135]
**Description**
In Formly
```
<div class="ui-message ui-messages-error" *ngIf="showError">
    <formly-validation-message [field]="field"></formly-validation-message>
</div>
```
It must be PrimeNG-specific
```
<div class="ui-message ui-message-error" *ngIf="showError">
    <formly-validation-message class="ui-message-text" [field]="field"></formly-validation-message>
</div>
```
https://primefaces.org/primeng/showcase/#/validation
PrimeNG uses ui-message-... classes for validation and ui-messages-... classes for global ones

**Environment**

- Angular version: 8.2.9
- PrimeNG version: 8.0.4
- Formly version: 5.0.0
- Formly PrimeNG version: 5.5.12

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.15](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.15) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
