### ISSUE TITLE
Custom template formControl cause error

### ISSUE THREAD

**Issue by a2928897** [ngx-formly/ngx-formly#2137]
Already give a star! ngx-formly is the best!

**Description**
I add a custom template using ng-zorro for a timepicker,
In angular 8, everything is work fine.

But last day I update to angular 9,
When I click the timepicker, error will happen
`ERROR Error: Uncaught (in promise): TypeError: this._value.getHours is not a function`

the template like this 
`<nz-time-picker nzFormat="HH:mm" [formControl]="formControl" [formlyAttributes]="field"></nz-time-picker>`

I found if I take off formControl, the error will not happen.
If I use timepicker in my form without ngx-formly, timepicker is work fine.

My enviroment
    "@angular/animations": "~9.0.5",
    "@angular/cdk": "~9.1.1",
    "@angular/common": "~9.0.5",
    "@angular/compiler": "~9.0.5",
    "@angular/core": "~9.0.5",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.0.5",
    "@angular/material": "^9.1.1",
    "@angular/platform-browser": "~9.0.5",
    "@angular/platform-browser-dynamic": "~9.0.5",
    "@angular/router": "~9.0.5",
    "ng-zorro-antd": "^8.3.0",
    **"@ngx-formly/core": "^5.5.13",**

**Comment by aitboudad** [comment]
Could you please test with `ng-zorro-antd` version 9.0.0-beta.0

**Comment by a2928897** [comment]
@aitboudad Thanks for your suggestion.
I already update my ng-zorro to "ng-zorro-antd": "^9.0.0-beta.0",
But the error still happend.

**Comment by aitboudad** [comment]
Ok I'll check it on my side to see what's going wrong but I doubt it may be related to an `ng-zorro-antd` issue.

**Comment by aitboudad** [comment]
tested on my side and it seems working as expected, the error is raised when passing a string value instead of a `Date` instance that `timepicker` expect.

The solution is to transform the `timepicker` value to `Date` instance.

```ts
this.model = {
  ...model,
  time: model.time ? new Date(model.time) : model.time,
}
```

**Comment by a2928897** [comment]
Thanks a lot!
Sorry about wasting your time.
