### ISSUE TITLE
How to add translations for the custom validation messages

### ISSUE THREAD

**Issue by SwapnilChidrawar** [ngx-formly/ngx-formly#2140]
**Question**

I have integrated ngx formly with my angular version 8 application. I have also gone through official documentation of how to integrate ngx translate with ngx formly. I managed to translate labels, placeholder and built in validations like required, minLength, maxLength etc. Somehow i am not able to translate the custom validations which I have created in my form. I have gone through [1368](https://github.com/ngx-formly/ngx-formly/issues/1368) but I did not get any success on this. Please share any workaround for this or any suggestions will help me lot.

Thanks

**Comment by aitboudad** [comment]
similar to #1368 but use `stream` instead, also you can register them in `AppModule` instead:


```ts
export class AppModule {
  constructor(
    trans: TranslateService,
    config: FormlyConfig
  ) {
    trans.stream('REQUIRED').subscribe((message) => {
      config.addValidatorMessage('required', message);
    });
  }
}
```

**Comment by aitboudad** [comment]
or use https://github.com/ngx-formly/ngx-formly/issues/1368#issuecomment-491270207 and register the `ValidationLoader` in AppModule constructor:

```ts
export class AppModule {
  constructor(loader: ValidationLoader) {
    loader.init();
  }
}
```

**Comment by SwapnilChidrawar** [comment]
Again you have explained me about the inbuilt validation. How do i apply same to custom validation like accept only strings or only numbers.

**Comment by aitboudad** [comment]
The question is not clear, please elaborate more with an example!
Thanks!

**Comment by aitboudad** [comment]
In [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) defining the validation message has been simplified, I've added an example in https://formly.dev/examples/advanced/i18n-alternative:

The `ValidationLoader` is not needed anymore and can be removed.

```patch
export function registerTranslateExtension(translate: TranslateService) {
  return {
+   validationMessages: [
+     {
+       name: 'required',
+       message() {
+         return translate.stream('FORM.VALIDATION.REQUIRED');
+       },
+     },
+   ],
    extensions: [{
      name: 'translate',
      extension: new TranslateExtension(translate)
    }],
  };
}
```
