### ISSUE TITLE
Subscribing to MatStepper selectionChange event

### ISSUE THREAD

**Issue by vishnu-dev** [ngx-formly/ngx-formly#2143]
**Question**

I need to subscribe to the selection change event of MatStepper. Accessing `stepper` instance using  `ViewChild` doesn't work. How do I subscribe to selection changes via `FormlyFeildConfig`?

There is a `selectionChange` event emitter in `MatStepper` component.
https://material.angular.io/components/stepper/api#MatStepper

How do I access the emitter in
https://stackblitz.com/edit/form-stepper

**Comment by aitboudad** [comment]
I'm not sure what you're talking about please provide more details, a stackblitz example with what you've done would be better, thanks!

**Comment by vishnu-dev** [comment]
I have added the details. @aitboudad

**Comment by aitboudad** [comment]
sorry still not clear :smiley:, what prevent you to add `selectionChange`:

```ts
@Component({
  selector: 'formly-app-example',
  template: `
    <mat-horizontal-stepper linear (selectionChange)="onSelectionChange($event)">
    ...  
  `,
})
export class AppComponent {
  activedStep = 0;

  onSelectionChange(val) {
    // your code 
  }
}
```


`Side note`: there is another approach to manage stepper through a custom field type which you may check: https://stackblitz.com/edit/angular-yu7bzv-uucyxg

**Comment by vishnu-dev** [comment]
OMG! Totally missed the custom stepper that I made. My bad. Sorry for bothering you. This helped me https://stackblitz.com/edit/angular-yu7bzv-uucyxg. Thanks.
