### ISSUE TITLE
Minimum repetition sections of custom type "repeat"

### ISSUE THREAD

**Issue by enricooliva** [ngx-formly/ngx-formly#2144]
**Question**

I get an ExpressionChangedAfterItHasBeenCheckedError using Repeat custom type with the minimum number of repetition sections.  (min = 2)

My requirements are
* set the minimum number of repetition sections in the repeat type
* use the hiddenExpression to dynamically hide the repeat type

This is stackblitz example
https://stackblitz.com/edit/angular-3ffgat

Thank you for your attention.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.5.15](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.5.15) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
