### ISSUE TITLE
Stepper with conditional fields

### ISSUE THREAD

**Issue by dbrils** [ngx-formly/ngx-formly#2147]
First of all I'd like to say that I really love the library! Creating forms is really easy and enjoyable.

I'm trying to create a stepper for a survey, where only 1 question is displayed on the screen at all times. To get an idea of how this would look like: [here](https://i.pinimg.com/originals/4a/09/f6/4a09f6768daf150f24ba49eefa86a5f5.gif)

The user answers a set of questions that can depend on each other. Imagine the following question tree:
1. What is your name?
2. What is your age?
3. Do you wear glasses?
3.1 if 3 is yes -> What brand do you wear?
3.2. if 3 is no -> Have you ever measured your eyes?
4. Where do you live
5. etc.

If the user answers question 3 with yes he gets a different fourth question than when he would answer No. I got the dependency working between questions, as can be seen here: https://stackblitz.com/edit/angular-sw7lbt 

But in my stackblitz it's still one big form. I would like to split this into a view where only 1 relevant question is shown.

Is something like this possible with ngx-formly? If so, where should I start?

**EDIT**: just fyi: I have looked into mat-stepper, such as [this stackblitz](https://stackblitz.com/edit/angular-yu7bzv-ncdquw). However this doesn't satisfy my needs, in the example an additional field appears inside the current step. Would it be possible to add a new step, based on some input?

Keep up the great work guys!
Hope to hear from you :)

**Comment by vishnu-dev** [comment]
There is something called `hideExpression` in the field configuration. Use that to do what you want. Example: https://stackblitz.com/edit/angular-yu7bzv-uucyxg
After answering the second question, the third question comes based on the condition.

**Comment by dbrils** [comment]
> There is something called `hideExpression` in the field configuration. Use that to do what you want.
> Also to show questions one by one you might use stepper with hidden header.
> Example: https://stackblitz.com/edit/angular-yu7bzv-uucyxg
> After answering the second question, the third question comes based on the condition.

I'm aware of `hideExpression` however I'm not looking to add another field in the _current_ step. I'm looking to add an extra step or show the step (if it's already there) based on the input in the current step. I also tried to add a `hideExpression` property to the step itself, but then the step is still visible, just without any content.

**Comment by dbrils** [comment]
Right now I got this: https://stackblitz.com/edit/angular-hvajyx, however it only hides the content of the fieldgroup with `hideExpression.` I'm looking to also hide the stap **and** have the next button skip the question that is hidden.

**Comment by dbrils** [comment]
I got it to work for now: https://stackblitz.com/edit/angular-hvajyx, however I'm unsure whether or not this is the best/cleanest approach. Currently I'm checking within my `stepper.type.ts` if the step has a hide field or not with the `*ngIf` directive. Any suggestions on a better approach would be welcome.

Also within stackblitz I'm getting the following error:
`Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.`

**Comment by aitboudad** [comment]
`hideExpression` is the right solution.

> Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.

I'm not able to reproduce it, maybe it has been already fixed in `5.5.15`.

**Comment by HangLoop** [comment]
@aitboudad 

> Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.

Error can be found in mat stepper examples, it is using `5.9.1`.  Not sure how to avoid it by not using custom type. 

https://stackblitz.com/angular/lydogpnjjmg?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
@HangLoop only occurs with Ivy and the only viable solution is to build the form first https://github.com/ngx-formly/ngx-formly/issues/2279#issuecomment-634645438
