### ISSUE TITLE
ngx-formly does not update the model

### ISSUE THREAD

**Issue by stefani0** [ngx-formly/ngx-formly#2148]
**I have created a dynamic template that work well with a little mockup, but when i call service does not show nothing. It looks like the template its not taking the model from call.**

----file1.html---

`<form [formGroup]="form" (ngSubmit)="submit()">
    <formly-form [model]="modelTable1" [fields]="fields" [options]="options" [form]="form">
    </formly-form>
  </form>`

-----file1.ts----

 constructor( private service: service, ) {
 ```

    this.service.getPrenotazioni().subscribe(
      (result) => {
        if (result.success) {
          this.modelTable1 = {
            data:result.data           
          },
         // this.modelTable1 = {...this.modelTable1} 
          console.log('data from service', this.modelTable1);         }
      },
      (error) => console.log('errore')
    );
  }
```
-----dynaimc-form.html------
```

<div *ngFor="let field of field.fieldGroup; let i = index;">
  <formly-group [model]="model[i]" [field]="field" [options]="options" [form]="formControl">



  ====some content===

  </formly-group>
</div>
```
--------dynamic-form.ts--------
```

constructor(builder: FormlyFormBuilder) {
    super(builder);}
```

**Comment by aitboudad** [comment]
Hi, can you replicate your code using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by stefani0** [comment]
> Hi, can you replicate your code using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap
> 
> Thanks!
Sure. This is demo. 
When i try to call from function with some delay the model is not shown.
Thank you
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-rdny1v

**Comment by aitboudad** [comment]
The context `this` when the function is invoked will not update the expected `model` instance defined in the AppComponent so either:

1. use Arrow function:

```ts
callFunction() {
  setTimeout(() => { this.modelTable = ...; }, 1000);
}
```

2. use bind:

```ts
callFunction() {
  setTimeout(function() { this.modelTable = ...; }.bind(this), 1000);
}
```

**Comment by stefani0** [comment]
Thank you

> The context `this` when the function is invoked will not update the expected `model` instance defined in the AppComponent so either:
> 
>     1. use Arrow function:
> 
> 
> ```ts
> callFunction() {
>   setTimeout(() => { this.modelTable = ...; }, 1000);
> }
> ```
> 
>     1. use bind:
> 
> 
> ```ts
> callFunction() {
>   setTimeout(function() { this.modelTable = ...; }.bind(this), 1000);
> }
> ```

thank you
