### ISSUE TITLE
Get data from custom field

### ISSUE THREAD

**Issue by ivorodriguezv** [ngx-formly/ngx-formly#2149]
Hello there!
Im currently working on a custom field that contains a lot of information. Let's call it FieldA.
FieldA has 3 inputs in it: Input1, Input2 and Input3. When i set FieldA's model, i'm able to set its inputs data (by also using FieldA's templateOptions.options).
I have a submit button that logs the model on the console. The problem is that, when i modify any of FieldA's inputs data, they are not being logged as part of the model (so i don't know how to get their data).
Im at a dead end right now!!
I would appreciate some help. Thanks in advance!

**Comment by aitboudad** [comment]
Hi, can you replicate your code using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Note: The model inside field type is marked as readonly, to update the field value use: `this.formControl.setValue`


Thanks!
