### ISSUE TITLE
display nested json data in field?

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2150]
I have a field that contains nested json data coming from the server side and I would like to display using JSONpipe or similar mechanism if possible.

Will appreciate any guidance / pointer on how to do it.

Thanks

example here is

 "shape": "circle",
  "coordinates": {
    "lat": 43.19174996796747,
    "lng": -90.53678068893021,
    "r": 27787.73767066941
  },

In this case coordinates field is displayed as [object object] within the form.

**Comment by vishnu-dev** [comment]
How is this related to ngx-formly. If it is, an example would be nice. @argupta23

**Comment by argupta23** [comment]
> How is this related to ngx-formly. If it is, an example would be nice. @argupta23

@vishnu-dev see update to my original post.

**Comment by aitboudad** [comment]
@argupta23 if you're looking for straight way use `template` https://github.com/ngx-formly/ngx-formly/issues/2057#issuecomment-579724475
or create a custom field a type https://formly.dev/guide/custom-formly-field.

**Comment by radvansky-tomas** [comment]
That not correct response @aitboudad , question was about nested data. Your example covers single input. So what if in template you want to have 5 inputs filing model with nested properties ?
