### ISSUE TITLE
Formly is overlapping the number 0 with the label

### ISSUE THREAD

**Issue by DavidML3** [ngx-formly/ngx-formly#2152]
**Question**

I am using formly and passing in a number value. The default value in my model is 0 so when formly sees this it gets confused. It is overlapping the number and the label together. If the value is anything other than 0 it works as expected.

See the stackblitz below

https://stackblitz.com/edit/angular-formly-demo-rmeezs?file=src%2Fapp%2Fapp.component.css

**Comment by aitboudad** [comment]
Either use `ViewChild` which mark [matInput](https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/input/src/input.type.ts#L32) as `MatFormFieldControl` implementation or override `empty` inside your custom field type to take account of `0` value:

```ts
get empty() { return this.value === undefined || this.value === null || this.value === ''; }
```

**Comment by aitboudad** [comment]
I just noticed that the provided `stackblitz` example uses an old version of Formly, make sure updating it to the latest one `v5.5.15` which is already fixed that issue.
