### ISSUE TITLE
Access a field that was hidden in the change event of another field

### ISSUE THREAD

**Issue by GillesVercammen** [ngx-formly/ngx-formly#2154]
Hello,

in my project i have a select box that toggles the visibility of another field.
I want to reset the hidden field everytime it reappears from being hidden.

So what i did was put a change event on the select, then try to access the other field to reset it.
now when the field goes from visible to hidden, i still have access to the field in the change event.
BUT when the field goes from hidden to visible, i can't access the field.
The hideExpression triggers after the change event.

Is there some other way, or should i be able to do it like this?

[Stackblitz](https://stackblitz.com/edit/angular-eereac)

Thank you

**Comment by aitboudad** [comment]
```ts
field.parent.fieldGroup.find(f => f.key === 'firstName').formControl
```

**Comment by aitboudad** [comment]
another approach https://github.com/ngx-formly/ngx-formly/issues/1847#issuecomment-576666051
