### ISSUE TITLE
`maxLength` and `minLength` for field `type: 'number'` do not work

### ISSUE THREAD

**Issue by lartheon** [ngx-formly/ngx-formly#2155]
**Description**
`maxLength` and `minLength` for field `type: 'number'` do not work

**Minimal Reproduction**
`fields: FormlyFieldConfig[] = [
    {
      key: 'Input',
      type: 'input',
      templateOptions: {
        label: 'Input',
        type: 'number',
        maxLength: 5,
        placeholder: 'Placeholder',
        description: 'Description',
        required: true,
      },
    },
  ];`

**Your Environment**

- Angular version: 9.0.7
- Formly version: 5.5.15

**Additional context**
Appears to work correctly if type is set to text but not for number

Thank you

**Comment by lartheon** [comment]
I also noticed this bug report https://github.com/ngx-formly/ngx-formly/issues/1377
However in my case I wish users to only be able to input numbers however these numbers may start with a 0, so I would like to store them as a string rather than integer (I just want to prevent them typing letters).

**Comment by GillesVercammen** [comment]
Just jumping in here, but don't you want to be using max and min instead of maxLength/minLength?

**Comment by aitboudad** [comment]
`maxLength/minLength` are for string type, for phone type check my reply
https://github.com/ngx-formly/ngx-formly/issues/1863#issuecomment-606128422

**Comment by lartheon** [comment]
> Just jumping in here, but don't you want to be using max and min instead of maxLength/minLength?

Hi, not really the fields I'm using it for is for things like membership card IDs, so I may have IDs so I will have ids like 00000 or 99999 but always a max and min of 5 characters

**Comment by aitboudad** [comment]
ok then create a custom validation instead of using `maxLength/minLength` :) https://formly.dev/examples/validation/custom-validation
