### ISSUE TITLE
Ionic grid

### ISSUE THREAD

**Issue by Paul-ICS** [ngx-formly/ngx-formly#2156]
I'm trying to create a layout with an ion-grid, but I can't get the columns to go next to each other.

Here's a StackBlitz: https://stackblitz.com/edit/ionic-4proht

What I want is each of the fields to be next to each other on a line, however the columns keep wrapping. I think this is because Formly adds extra tags in the ion-row, so the tags look like:
```
<ion-row>
  <formly-field>
    <formly-group>
      <formly-field>
        <formly-grid-wrapper-ion-form-field>
          <ion-col>
      <formly-field>
        <formly-grid-wrapper-ion-form-field>
          <ion-col>
```

when it needs to be 
```
<ion-row>
  <ion-col>
  <ion-col>
```

I've added an example in the stackblitz of what I want it to look like but without Formly and also what I think is going wrong (div after the ion-row)

Any help would be appreciated!

**Comment by aitboudad** [comment]
define grid as a custom type instead of `wrapper`, check the `@angular/flex-layout` integration to have an idea https://stackblitz.com/edit/ngx-formly-flex-layout
