### ISSUE TITLE
Can't bind observable to asyncValidators

### ISSUE THREAD

**Issue by TheYoxy** [ngx-formly/ngx-formly#2160]
**Question**
I'm currently using observable to validate some fields. I was wondering if it's possible to bind observable to async validators as the error message tells that you can bind a Promise or an Observable ?

**Example**
Fill anything inside the input and see the console output.
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-obs?file=src/app/exist.validator.ts
> I've removed the service for more clarity, but I must register it by using `FORMLY_CONFIG` as it require this dependency.

**Environment**
- Angular version: 9.0.5
- Formly version: 5.5.15
- Tested with and without Ivy enabled and I get the same result.

**Comment by aitboudad** [comment]
it will be part of the next major version https://github.com/ngx-formly/ngx-formly/pull/1849, as a workaround try to return a promise using `.toPromise();` call

**Comment by TheYoxy** [comment]
Thanks ! 
Any idea of the date of the release for the next version ?

**Comment by aitboudad** [comment]
not anytime soon as I'm busy right now with other stuff.
