### ISSUE TITLE
Add dummy field on form without adding/updating form model

### ISSUE THREAD

**Issue by irenagroup** [ngx-formly/ngx-formly#2166]
**Question**

A clear and concise description of what the question is.
> There is field on form which is autocomplete where user can select address and other  other fields based on which other disabled textfields gets populated. I do not want the model of autocomplete field to be find to form model. Is there any way to add field to form without polluting form model. Either we can achieve via formState or similar approach?

**Comment by aitboudad** [comment]
Create a custom field type https://formly.dev/guide/custom-formly-field and keep the key empty to avoid polluting the form model.

```ts
fields = [
  { type: 'autocomplete' }
];
```
