### ISSUE TITLE
The bootstrap addon example is not showing fontawesome icons

### ISSUE THREAD

**Issue by ilpizze** [ngx-formly/ngx-formly#2170]
The bootstrap addon example is not showing fontawesome icons:

https://stackblitz.com/angular/rydpaqlrgav?file=src%2Fapp%2Fapp.component.html

My Environment: 
- Angular version:9.1.0
- Formly version: 5.5.15

Stackblitz example environment
- Angular version:7.2.16
- Formly version: 5.5.15

Thank you

**Comment by aitboudad** [comment]
The `fontawesome` style is not included, we'll fix that!
Thanks!
