### ISSUE TITLE
Get specific field's FormControl not working

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2171]
within a custom type, take the value of a field (get) and assign a new value (setValue).

I've tried the following options and none work:

- `this.field.parent.form.at(this.field.parent.key)`, in this error call **Cannot read property 'at' of undefined**
- `this.field.parent.formControl.get(this.field.parent.key)`
- `this.formControl.get(this.field.parent.key)`
- `this.field.formControl.get(this.field.parent.key)`

**Comment by GlauberF** [comment]
I managed to solve it with this one: `this.field.parent.formControl.get(this.field.parent.key)`

but I was wondering why when used at, it gives an error that is not a definite

**Comment by aitboudad** [comment]
`at` exist in `FormArray` instance which is created when using `fieldArray` type.
