### ISSUE TITLE
Custom Component Nested Object

### ISSUE THREAD

**Issue by radvansky-tomas** [ngx-formly/ngx-formly#2172]
I've checked your documentation for Custom Templates https://formly.dev/guide/custom-formly-field

However I have no idea how to create more complex structures...

Lets say that you want to render custom component with couple inputs, maybe some map with location etc and you want to render it all together (not split in form declaration)

So how I can pass model information in custom template. Can you demonstrate for example here:
https://stackblitz.com/edit/ngx-formly-custom-template?file=app%2Fformly-field-input.ts

Same example but with two inputs, where you will hardcode keys in model. I've made example from your code:
https://stackblitz.com/edit/ngx-formly-custom-template-atitse

As I said, I know that example I provided can be easily done with 2 fields in schema, but thats not the purpose. I want to know how I can perform 2-way binding between dynamic form and my custom component. So I can feed it with complex object and render it with custom template.

@aitboudad

**Comment by radvansky-tomas** [comment]
For example I thought that I can do:
  ```
 <input type="input" [formControl]="formControl" [(ngModel)]="model[key].value1">
     <input type="input" [formControl]="formControl" [(ngModel)]="model[key].value2">
```

And Like that specify "nested keys"

**Comment by aitboudad** [comment]
We rely on Angular reactive form so the 2-way binding is not supported and the model value inside custom field type should be considered as read-only.
Passing `[formControl]="formControl"` would take care of model changes and if you want to update the model value manually use `formControl.setValue(your_value)`.

To handle nested keys there are some Formly ways you may check first:

1. Pass a nested key throughout the field type using dot notation:
```ts
{
  key: 'address.city'
}
```
2. use `fieldGroup`: https://formly.dev/examples/other/nested-formly-forms
3. use `fieldArray`: https://formly.dev/examples/advanced/repeating-section

**Comment by radvansky-tomas** [comment]
@aitboudad thank you for reply, however thats not what I asked. 2 & 3 will basically create two separate input and you will control key with 1. 

My question was how to pass complex object (with nested keys) and process them on template level.

**Comment by radvansky-tomas** [comment]
It could be probably achieved using custom type...like you use 'object' type in json schema 

import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

```
@Component({
  selector: 'formly-object-type',
  template: `
    <div class="mb-3">
      <legend *ngIf="to.label">{{ to.label }}</legend>
      <p *ngIf="to.description">{{ to.description }}</p>
      <div class="alert alert-danger" role="alert" *ngIf="showError && formControl.errors">
        <formly-validation-message [field]="field"></formly-validation-message>
      </div>
      <formly-field *ngFor="let f of field.fieldGroup" [field]="f"></formly-field>
    </div>
  `,
})
export class ObjectTypeComponent extends FieldType {
  defaultOptions = {
    defaultValue: {},
  };
}
```

However when I try to create new type, for example: 'Pricing' which has completely same source code than your object class. It renders empty panel. Which is probably because you've hardcoded types and their behaviour here, instead of specifying what is possible for each type (ie passing properties as field groups)
https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/json-schema/src/formly-json-schema.service.ts

**Comment by aitboudad** [comment]
for complex object (with nested keys) I would use the `fieldGroup`:

```ts
{
  key: 'price',
  fieldGroup: [
    { type: 'input', key: 'value' },
    { type: 'select', key: 'currency', ... },
  ]
}
```

The default type for group is [formly-group](https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/templates/formly.group.ts) and to override it pass type prop:
```patch
{
  key: 'price',
+ type: 'price',
}
```

inside group type either use `formly-field` to render each type or define your inputs manually:

```html
<!-- auto render field -->
<formly-field *ngFor="let f of field.fieldGroup" [field]="f"></formly-field>

<!-- custom render -->
<input type="input" [formControl]="field.fieldGroup[0].formControl">
<input type="input" [formControl]="field.fieldGroup[1].formControl">
```

**Comment by radvansky-tomas** [comment]
Are you sure that this works in json schema? As I said I tried that, but "field.fieldGroup" is not available for custom types. Its populated in "object", but when I create price.type.ts and define it in module, then that property is not being passed. 

As I already mentioned, I suspect that because of hardcoding here:
https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/json-schema/src/formly-json-schema.service.ts#L116

**Comment by aitboudad** [comment]
you can adjust the generated schema using `widget` or `map` option, see https://github.com/ngx-formly/ngx-formly/issues/1993#issuecomment-568180138

**Comment by radvansky-tomas** [comment]
Ok let me try ;) THX for help

**Comment by radvansky-tomas** [comment]
Great that worked. For anyone wants to do same thing:

Create custom type, register in module and pass it in scheme.
Then call 'map':
`this.fields = [this.formlyJsonschema.toFieldConfig(this.schema, { map: this.mapFields })];`

In my case, type is called 'pricing', so I temporary call it object -> process it as object and return back with 'pricing' type as field.

 ```
 mapFields(mappedField: FormlyFieldConfig, mapSource: JSONSchema7): FormlyFieldConfig {
    console.log(mappedField);
    console.log(mapSource);
    if (mapSource.type === 'pricing') {
      mapSource.type = 'object';
      const formlyJsonschema = new FormlyJsonschema();
      mappedField = formlyJsonschema.toFieldConfig(mapSource);
      mappedField.type = 'pricing';
      return mappedField;
    }
    return mappedField;
  }
```

Now I can have custom components in my type and full access to model and fieldGroup data.
