### ISSUE TITLE
Can we do Auto-complete in repeat section?

### ISSUE THREAD

**Issue by bejgumshirisha** [ngx-formly/ngx-formly#2175]
**How to do Cascade Select in repeat section?**

I have a requirement where in repeat section I want to give auto-complete.When user selects an option from auto -complete then based on the selection I have to pre-populate the other fields in the repeat section.

Here are our starter templates in a case you may need/want to reproduce an example:
[https://stackblitz.com/edit/angular-g9txuh-pzaugt?file=src%2Fapp%2Fapp.component.ts](url)

Please suggest me how to do it.
Thanks

**Comment by aitboudad** [comment]
check a similar example https://formly.dev/examples/advanced/repeating-section-input
