### ISSUE TITLE
"this.field" is undefined inside a function provided as a part of config in "defaultOptions"

### ISSUE THREAD

**Issue by antonama** [ngx-formly/ngx-formly#2176]
**Description**
- there is a custom formly component with custom directive in a template
- directive accepts configuration object
- a function, for example, `onClick` is a part of this configuration object
- I provide this function in custom component's `defaultOptions`

Trying to access `this.field` inside the function results in "undefined", accessing `this.to`, `this.formControl` etc. results in "ERROR TypeError: Cannot read property 'templateOptions' of undefined".

Temporary workaround is to re-assign the function before providing configuration object to a directive, see minimal reproduction.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-dpnvyp

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.5.15

**Additional context**
Originally problem was found when I was working with flatpickr library, so I thought this may be bug in their code also, but then I got rid of it and the problem still remained. 
Access to `this.to` is needed to retrieve dateFormat string, which is provided by backend as a part of field configuration in JSON format.
The minimal reproduction is completely made up, flatpickr actually expects a return value from a provided function, so it can't be simply moved to @Output in a binding directive.

**Comment by aitboudad** [comment]
I've figured out the issue that was introduced since `5.5.11` version, for now, use `5.5.10` version until I find a fix.

**Comment by aitboudad** [comment]
Seems the issue exist in the old versions too but occurs only when the field is re-rendered, the only solution for that is to assign functions) that rely on `this` in `onInit` instead of `defaultOptions`:

```ts
export class CustomComponent extends FieldType {
  ...

  ngOnInit() {
    this.to.some = {
      onClick: this.onClick
    };
  }
}
```
