### ISSUE TITLE
field state reflects an error that does not exist

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2179]
**Description**
I was testing a CRUD today and I noticed something strange, that I couldn't come up with an appropriate name for this issue.
First see the GIf below, then I will describe the problem.
![vokoscreen-2020-04-15-09-28-11](https://user-images.githubusercontent.com/11314585/79337074-3cca3f80-7efb-11ea-806a-925ce77cc3f9.gif)

When editing a value and clicking inside the field that has a mask, when clicking outside it accuses an error.
At first I even thought it could be a mistake with the mask, but after several tests, I found that it was not.
because if you look at the gif, you can see that after I just deleted the last number and typed it again, I can click in the field and click out that the error no longer appears.

it seems to me that something in the state of the field is not updating and when a change in the field is updated.

remember that in the component where this field is, I use `ChangeDetectionStrategy.OnPush`

**Your Environment**
- Angular version:8.2.14
- Formly version: 5.5.15

**Comment by aitboudad** [comment]
A reproduction stackblitz example is required :pray:, thanks!

**Comment by GlauberF** [comment]
it took me a while because I had to find a way to reproduce the error.

**link**: https://stackblitz.com/edit/angular-mask-vimbo-error-validations?file=src%2Fapp%2Fapp.component.html

**Simulation explanation:**

the Field 'Test Mask Error' it simulates that the field came from the database, where according to the interface you can see that it is a string.
This field, if you click on it and out, will already show that it is wrong.
But if you click on the field and hit any number, it won't add any more value (because the entered value is right), but it will remove the error.
it looks like an update was forced, I'm not sure.

The same logic and mask has been added to the 'Test Mask Right' field, this field I save the data to, so you can simulate an edition as well.
fill in the data and click on 'Save Item Storage', then you can give a f5 and update the page, the value will be in the list, just click above to edit again.
after that, you can test clicking in and out of the 'Test Mask Right' field it will not point out error.

**Comment by aitboudad** [comment]
not sure this is related to Formly, the value emitted to the mask type is `26821193000135` which is not the expected one "00.00.00/0000-00" (I would expect formatting the value before validation):

```ts
{
  "mask": {
    "requiredMask": "00.00.00/0000-00",
    "actualValue": "26821193000135"
  }
}
```

when you change the value manually `actualValue` equal to `26.82.11/9300-01`

**Comment by GlauberF** [comment]
I solved it temporarily by transforming the field value in the model.ts file.
I need to investigate further, as the number of characters is compatible with the number of zeros in the mask, I believe it should work and not need an initial transformation.
I will open an issue in the other library, thanks @aitboudad

**Comment by GlauberF** [comment]
@aitboudad Second tests the error is not related to the mask library but to ngx formly, you can see it here.
https://github.com/JsDaddy/ngx-mask/issues/723#issuecomment-616526304

**Comment by GlauberF** [comment]
@aitboudad Any solution ?

**Comment by aitboudad** [comment]
not a Formly issue either, passing `dropSpecialCharacters: true` makes the field valid, not sure why but that may help.

**Comment by GlauberF** [comment]
I'm sorry for my ignorance, but I believe it's a formly mistake.
Because in the case of the field (dropSpecialCharacters) I explicitly pass the value false, so it is not set to true.

In the example above, it can be set to true and you will see that at startup it applies the mask.

![Captura de Tela_selecionar área_20200429074022](https://user-images.githubusercontent.com/11314585/80587023-3c966d80-89ec-11ea-9b8e-d8d4db52629a.png)

**Comment by aitboudad** [comment]
try the same example in Formly first then report the issue, you're wasting my time in addition of yours 😞, you should work on your example where you've passed several options in order to produce the issue, the basic example works on Formly too.
