### ISSUE TITLE
Model is not synchronised with the form value when using 'hideExpression' and Custom Form Control (ControlValueAccessor)

### ISSUE THREAD

**Issue by pedrolcd** [ngx-formly/ngx-formly#2180]
### Description

**Formly is not synchonizing the model with the current form** where a given _Field Configuration_ is a custom form control.

When using a custom field  (eg: Dual List in the Stackblitz example, provided below) the form value for the custom type is always updated when changing the field value.

The opposite happens for the model - it only takes the first change and is never updated again.

**My question**: How to keep the model and its field updated when using custom types in this type of use cases?

Thanks!

### Minimal Reproduction

Check JSON when dual list values are updated: _the group property is not synchonizing_ 
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-vzv2js

**Your Environment**

- Angular version: 9.0.1
- Formly version: 5.5.12

**Comment by aitboudad** [comment]
not related to `hideExpression`, we use the `distinctUntilChanged` operator for tracking the form value changes which don't detect the added value through `push` call.

For now, you may use the following workaround:

```ts
this.formControl.setValue([...this.selectedItems]);
```

**Comment by pedrolcd** [comment]
In fact, it works 👍 Thanks for the answer!
