### ISSUE TITLE
Adding mat-slide-toggle to a form

### ISSUE THREAD

**Issue by lartheon** [ngx-formly/ngx-formly#2181]
**Question**
I'm trying to add a toggle option to my form that will allow admins to edit forms and resubmit them.

The issue I have is that I cannot seem to add the toggle to my form using the template parameter.

e.g
ts
```
key: `adminToggle`,
template:`<div>
        <mat-slide-toggle matInput color="primary" (click)="adminToggle()">
        Unlock fields
      </mat-slide-toggle></div>`
```

When I view the form all I see is the text 'Unlock fields'

What am I doing wrong, I've used template to add material buttons with no issue.

**Comment by aitboudad** [comment]
`template` property render Html content only and for the component, you may need to define a custom field type as documented in https://formly.dev/guide/custom-formly-field.

For `mat-slide-toggle` you can use the provided one which is available in our material UI (section Toggle type) https://formly.dev/ui/material.

**Comment by lartheon** [comment]
Thank you I used the one provided by your good selves. Thank you for the quick response, much appreciated!

**Comment by lartheon** [comment]
@aitboudad  It might be my structure causing the function to not enable.  I created a test project and the following code example works on the initial toggle but then stops working after the initial enable.

```
export class AppComponent {
  form = new FormGroup({});
  model = { email: 'email@gmail.com', name: '' };
  fields: FormlyFieldConfig[] = [{
    key: 'email',
    type: 'input',
    templateOptions: {
      label: 'Email address',
      placeholder: 'Enter email',
      required: true
    }
  },
  {
    key: 'name',
    type: 'input',
    templateOptions: {
        label: 'Field 1',
        placeholder: 'Formly is terrific!'
      },
  },
  {
        key: "adminToggle",
        type: 'toggle',
        defaultValue: false,
        templateOptions: {
          label: 'Unlock restricted fields for editing',
          change: () => this.adminToggle()
        },
         expressionProperties: {
          'templateOptions.disabled': () => false,
        },
      }
  ];
adminToggle(){
    if(this.form){
      console.log("adminToggle Pressed disabled:" + this.form.disabled);
     
    this.form.disabled 
      ? this.form.enable()
      : this.form.disable();
    }
  }
  submit(model) {
    console.log(model);
  }
}
```

**Comment by aitboudad** [comment]
To control the disabled state using Formly way, rely on `disabled` property:

```ts
field.templateOptions.disabled = true or false
```
the expression `'templateOptions.disabled': () => false` will force the field to be enabled forever which I think not the desired behavior, you can, for example, control the disabled state based on the model value.

**Comment by lartheon** [comment]
> ```ts
> .templateOptions.disabled = true
> ```

Sorry I'm a newbie, this is my first angular application, is there any working example you can share to help me understand.

Thank you.

**Comment by warrendodsworth** [comment]
Use an expression with  'templateOptions.disabled': 'formState.disabled' 
Then toggle this.options.formState inside the adminToggle function
