### ISSUE TITLE
How to get Validation event

### ISSUE THREAD

**Issue by a2928897** [ngx-formly/ngx-formly#2182]
When there is a column is required, and user didn't filled this column,
The validation will be false,
I want to pop up a message(like material's snack bar) to tell user which column need to be filled,
How can I get this Validation event?

Thanks a lot.

**Comment by kenisteward** [comment]
Need a bit more information here. Can you setup a stackblitz?

**Comment by a2928897** [comment]
Just like this example https://stackblitz.com/angular/vrjbbnxkvbr
If user didn't write 'Name',
I want to pop up a message using material snack bar "Name is require!"

**Comment by kenisteward** [comment]
Okay so you want to know how to get the current errors of a form?

**Comment by a2928897** [comment]
Yes

**Comment by kenisteward** [comment]
This is not a firmly question but an angular question.

Since you have to pass in the form group simply create a flatmap of the
errors on data change.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1297#issuecomment-444172637
