### ISSUE TITLE
Response from custom validators

### ISSUE THREAD

**Issue by freon27** [ngx-formly/ngx-formly#2184]
Hi,

Reading the documentation it seems that a custom validator function is expected to return `true` and it seems that when I end up returning something other than true (but still truthy), I end up just getting `true` in the custom message function. 

Angular reactive forms allow me to return an arbitrary structure which can then be used when building the error message. 

e.g:

```
return `${validation.fileCount} files were over ${validation.fileSizeLimit}`
```
My questions are:

1. Am I doing something wrong (I'm pretty new to Formly so definitely a good possibility)? *Should* it be possible to get the data structure I'm returning from the validator in Formly?

2. If it's not possible is there a reason for not making this available?

**Comment by aitboudad** [comment]
return an object with message key would work `{ message: 'custom message' }` but that depends on the type of validation you're using https://formly.dev/examples/validation/validation-message

**Comment by freon27** [comment]
Thanks for the reply :)  

This is what I was finding confusing... If I understand right the validation works differently depending how you define the validation.  

My problem is that it needs to be on a per field basis (I pass custom parameters into a function returning the validation function) but I also want to be able to return an object like you suggested - but that is only possible when the validation is defined in the module if I understand correctly?

From the examples I can do what I want. I was just hoping that the interface would be the same as the normal Reactive Form validators so that I could re-use them across our application (we don't use Formly every yet). I think I will just have to write Formly specific wrappers for everything.

Thanks for your help.

**Comment by aitboudad** [comment]
Reactive Form validator interface is supported in both ways:

1- Through `NgModule`:

```patch
@NgModule({
  imports: [
    ...,
    FormlyModule.forRoot({
      validators: [
+        { name: 'custom', validation: CustomValidator },
      ],
    }),
  ],
})
export class AppModule { }

export class AppComponent {
  options: FormlyFormOptions = {};

  fields: FormlyFieldConfig[] = [
    {
      key: 'name',
      type: 'input',
      validators: {
+       validation: ['custom'],
      },
    },
  ]
}
```

2- or through the field declaration:

```patch
{
  key: 'name',
  type: 'input',
  validators: {
+   validation: [CustomValidator],
  },
},
````

if you want to return a message for `custom` validator, return an object with `message` prop:

```
export function CustomValidator(control: FormControl): ValidationErrors {
  ...
  return isValid 
    ? null
    : { custom: { 'message': `files were over ...` } };
}
```
