### ISSUE TITLE
How to use MaxItems in a multi-field FieldArray/Repeat

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2185]
@aitboudad  Appreciate all the efforts you have put in into this package and your prompt follow-up

**Question**
How to use MaxItems in a multi-field FieldArray/Repeat

I have looked at issue #1692 where you have an example for MaxItems in a single field.

I have created the following stackblitz to capture my usage scenario.

[https://stackblitz.com/edit/angular-uurguv?file=src%2Fapp%2Fapp.component.ts](url)

Additionally I have one more observation to make.

For some reason in my setup when I add "location" into the model as shown in this stackblitz I don't see the fields appear on my screen unless I click the "Add" button. But it does work in the stackblitz.

Any thoughts on what could be causing this behavior?

**Comment by aitboudad** [comment]
There is no diff between single and multi-field array, rely on `to.maxItems` option:

```ts
<button *ngIf="!to.maxItems || to.maxItems > field.fieldGroup.length" (click)="add()">
 {{ to.addText }}
</button>
```

> Any thoughts on what could be causing this behavior?

verify the model input is defined `[model]="model"` and avoid using `push` or object assignment which doesn't detect model changes:

```ts
// detect change
this.model = { location: [{}] };
this.model = { ...this.model, location: [{}] };

// won't detect change
this.model.location = [{}];
this.model.location.push({});
```

**Comment by argupta23** [comment]
@aitboudad 

Thank you for the prompt response and the recommendation.

Looking back the original example, it looks like I missed the "ngIf....." part within the repeat type. I have tested it and it works fine.

On the second part of the question, I am using the the first option in the "won't detect change"  which explains the behavior in my setup.
