### ISSUE TITLE
All the fields getting dirty after adding fields in repeat section

### ISSUE THREAD

**Issue by saurabh47** [ngx-formly/ngx-formly#2189]
**Description**
All the fields present in the repeat section getting dirty after adding extra fields & touching one of the mandatory fields in the repeat section.

**Minimal Reproduction**
***Please checkout below example:-***
https://stackblitz.com/edit/ngx-formly-ui-ng-zorro-antd-vht62g?file=src%2Fapp%2Frepeat-section%2Frepeat-section.component.html

1. Click on **add  another Offering** button for **twice**
2. select Offering from the drop-down

After that, all the fields present in the repeat section getting dirty.

**Environment**

- Angular version: 8.2.14
- Formly version: 5.5.15
- Formly /ng-zorro-antd version: 0.0.1

***Thank you so much for this wonderful library***

**Comment by aitboudad** [comment]
fixed by  https://github.com/ngx-formly/ngx-formly/pull/2087 and it will be part of the next release. For a workaround check my comment https://github.com/ngx-formly/ngx-formly/issues/2044#issuecomment-577723109

**Comment by aitboudad** [comment]
The workaround can be removed after updating to [5.6.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.0) version.
