### ISSUE TITLE
`'expressionProperties templateOptions.disabled' : TRUE` For a Field Disables Entire Form

### ISSUE THREAD

**Issue by lartheon** [ngx-formly/ngx-formly#2193]
**Description**
My form has multiple fields, some fields are disabled by default and require the user to press a slider/button to enable these disabled fields to be editable.

Using the below code as an example if I set the `employeeNumber` field to `'templateOptions.disabled': () => false,` then the field is always disabled even when the `unlockOrLockForm()` method is executed. This works as expected, the rest of the form switches from being enabled or disabled.

However, if I want this field to always be enabled I change the statement to true `'templateOptions.disabled': () => true,` . This is where the bug occurs. On initial load everything appears to be correct, the `employeeNumber` field is editable whilst the rest of the form is disabled. If I now execute the `unlockOrLockForm()` method I expect the rest of the form to become editable, it does not, everything remains disabled.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-ootz1a?file=src%2Fapp%2Fapp.component.ts

```
unlockOrLockForm(){
     this.form.disabled ? this.form.enable() : this.form.disable();
}
.....
{
        key: "employeeNumber",
        type: "input",
        className: 'flex-3 h2',
        defaultValue: this.data.employeeNumber,
        templateOptions: {
          label: "Emp# ",
          placeholder: "Emp# ",
        },
        expressionProperties: {
          'templateOptions.disabled': () => false,
        },
      },
```

**Your Environment**

```
"@ngx-formly/core": "^5.5.14",
"@ngx-formly/material": "^5.5.14",
"@ngx-formly/schematics": "^5.5.15",

@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-optimizer    0.900.7
@angular-devkit/build-webpack      0.900.7
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@angular/cdk                       9.1.3
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.1.3
@angular/material-moment-adapter   9.2.0
@ngtools/webpack                   9.0.7
@schematics/angular                9.0.7
@schematics/update                 0.900.7
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
```

**Comment by aitboudad** [comment]
The root form disabled state is based on its children state (return `disabled=true` when every child form is disabled).
So in your case, the root form state will never be disabled since `Input` field is always enabled.

The solution, in that case, is to toggle the state of each field separately.

**Comment by lartheon** [comment]
> toggle the state of each field

Thank for the reply, could you point me in the right direction how to do this, I'm doing google searches but a lot of the questions and answer are almost 5 years old or are from the old angular formly website.

**Comment by aitboudad** [comment]
try using formState https://formly.dev/examples/form-options/form-state

**Comment by lartheon** [comment]
Thanks I'll try it out looks so simple! 👍

**Comment by madeeha96** [comment]
@aitboudad I'm facing setting up field templateOptions.disabled = true and on clicking on edit certain fields are marked disabled false. It's working for every field except text input field. Please guide

**Comment by aitboudad** [comment]
@madeeha96 could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
