### ISSUE TITLE
integration with nz table

### ISSUE THREAD

**Issue by lorschtan** [ngx-formly/ngx-formly#2194]
Sorry if i asked dumb question, but i saw the integration with ngx data table at https://formly.dev/examples/advanced/datatable-integration
and it give me an idea of creating template for all my table. I'm currently using ng zorro table with the involve of server side pagination, server side sorting and etc... i'm using data source to do so, but I'm wondering how will I be able to set data source and execute those method in data source? currently I created a general data source object at my nz table template but I couldn't found any way to pass my data source into the template. i tried passed the data source object through template option but it could access any of my data source method. Please help !!! Thank You very much !!!

**Comment by aitboudad** [comment]
Hi, can you replicate your example using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-ng-zorro-antd

**Note**: In the above example, I would say Formly could be only suitable if you want to handle small data set as It may have an impact on performance, I would prefer to use a datatable with an edit button for each row to open the form on demand using dialog or a popover.

**Comment by lorschtan** [comment]
hmmm. nvm, I have found an alternative way of doing it. Thanks for the response.
