### ISSUE TITLE
JSONSchema oneOf properties with initial values

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2195]
**Description**
When the editor with a JSONSchema oneOf property is loaded with an initial model, the wrong option is selected.

**Minimal Reproduction**

In this example, the model value correspond to only one option: the second. But the editor select the first option.
https://stackblitz.com/edit/angular-157bka?file=src%2Fassets%2Fjson-schema%2FoneOf.json

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.5.15

**Additional context**
This is probably due to the fact that the two oneOf options have the same `name` property. This is probably not easy to solve as the `additionalProperties` should be checked.

**Comment by aitboudad** [comment]
The following PR #2196 improves the select `oneOf` which takes account of the number of matched model properties (the highest is selected).

**Comment by aitboudad** [comment]
`oneOf` try to select the valid option first so if you want to rely on `additionalProperties`, just define `additionalProperties` validator in your project and it should work as expected without waiting for the above fix.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.6.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
