### ISSUE TITLE
Cannot read property 'formState' of undefined

### ISSUE THREAD

**Issue by rmannibucau** [ngx-formly/ngx-formly#2197]
**Description**
After upgrading from 5.5.13 to 5.5.15, console is full of errors.

> Cannot read property 'formState' of undefined

It happens in a fieldgroup with a hiddenExpression.

Bypassing this error (forcing options:{} in the field) I get others error, mainly that model is undefined in the hiddenExpression.

I didn't check in detail yet but I suspect https://github.com/ngx-formly/ngx-formly/commit/32a3a9d9cde62f82fd563784f1799f5dadf81ddd can cause it since the fieldgroup does not have a key.

**Your Environment**

- Angular version: 9.1.1
- Formly version: 5.5.15

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction example, here is a starter one https://stackblitz.com/edit/angular-yetvdu
Thanks!

**Comment by rmannibucau** [comment]
@aitboudad here is one example having the same behavior https://stackblitz.com/edit/angular-yetvdu-5kianv

**Comment by aitboudad** [comment]
The provided example throws the following error: `[Formly Error] There is no type by the name of "toggle"` which not related to this I think, I changed `toggle` to `checkbox` and the demo works as expected maybe you didn't save your changes :thinking:

**Comment by rmannibucau** [comment]
@aitboudad found the cause, a not initialized nested object was causing that, the error is just failling in the whole nested object (model.nestedObject == undefined), if i add defaultValue = {} fo nestedObject it works as expected. So let's change this issue as "error should be more precise about the cause"? Guess it should log model is null and subform can't be init. Wdyt?

**Comment by aitboudad** [comment]
Only relevant when passing a string expression, PR welcomed!
