### ISSUE TITLE
This.field is empty for second added entry in ARRAY using JSON schema

### ISSUE THREAD

**Issue by radvansky-tomas** [ngx-formly/ngx-formly#2200]
After you @aitboudad advised me to use MAP function and widget object inside my JSON schema, everything worked fine.

But I noticed today that EVERY second added entry in my forms are incorrectly rendered, and thats because for some reason, JSON schema is not parsing schema anymore, but its properties.

To explain deeper, in my definition I have object
```
 "price": {
            "title": "Price",
            "type": "pricing",
            "properties": {
              "min": {
                "type": "number",
                "title": "Min"
              },
              "max": {
                "type": "number",
                "title": "Max"
              },
              "unit": {
                "type": "string",
                "title": "Unit"
              },
              "delimiter": {
                "type": "string",
                "title": "Delimiter"
              },
              "format": {
                "type": "string",
                "title": "Format"
              }
            }
          }
```

This is then used within Array:
```
  "properties": {
                  "prices": {
                    "title": "Prices",
                    "type": "array",
                    "items": {
                      "$ref": "#/definitions/price"
                    }
                  }
```

When I add first instance of Price in array, everything works fine. Second added object (third and so on) instead of passing "pricing" schema, starts passing properties! (ie. "min", "max", ...) So they are converted into primitive controls (string inputs), instead of custom control "pricing".

You can see behavior in this video:
https://www.youtube.com/watch?v=wjiLeMUQgN8&feature=youtu.be

**Comment by aitboudad** [comment]
try with:

```patch
"price": {
  "title": "Price",
-  "type": "pricing",
+  "widget": {
+    "formlyConfig": {
+      "type": "pricing",
+    }
+  }
}
```

**Comment by radvansky-tomas** [comment]
Thank you again, I dont know why this works, but I am glad

**Comment by aitboudad** [comment]
We rely on [type](https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/json-schema/src/formly-json-schema.service.ts#L116) to generate Formly schema so passing an unsupported type (`pricing`) would generate an unexpected result.
