### ISSUE TITLE
Disable field in expression not working

### ISSUE THREAD

**Issue by ChristianKlima** [ngx-formly/ngx-formly#2201]
Hello,

I think our problem is related to Bugfix #1528. Our expression to disable a field works after a browser refresh. Navigating to the same route without a browser-refresh => the expression is evaluated but nothing changes.

I debugged for a while and found that the following code behaves differently:
utils.ts line 59. In this If statement, formControl is not null in the event of an error. Therefore line 63 is not executed => WrapProperty is missing.

Could it be that wrapProperty has to be executed even if the formControl is set? Unfortunately I didn't understand everything exactly, but maybe you can help?

Thanks and regards

Christian

**Comment by aitboudad** [comment]
Hi, can you provide a reproduction example using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
