### ISSUE TITLE
upgrade material

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2203]
please update the peerDependency `@angular/material` to 9.2.1

**Comment by aitboudad** [comment]
That's on our roadmap (`V6`) not soon but I'll try to provide an early version as alpha.
To get notified use release-only watch:
![Selection_005](https://user-images.githubusercontent.com/1753742/56688052-9b395500-66cf-11e9-9dd0-c296d1466973.png)
