### ISSUE TITLE
How to specify ngx-formly field formatter when field config is fetched from a REST service call ?

### ISSUE THREAD

**Issue by SathyaramSoni** [ngx-formly/ngx-formly#2204]
In the application that I am working on. We are getting the fields config as part of service json response.

For some input fields we need to have a specific formatter. Example : For few input fields we need to turn the entered input value to uppercase. All the backend can send is a flag for fields whose value should be formatted.

Example: templateOptions : { tranformToUpperCase : true }

Is there a  way to do such transform/formatting on input text.

**Comment by aitboudad** [comment]
You may try to use `ngx-mask` as a [custom field type](https://formly.dev/guide/custom-formly-field)  here is a starter example: https://stackblitz.com/edit/angular-masking-dynamics

**Comment by SathyaramSoni** [comment]
Hi.. Sorry for coming back late on this topic. Looks like ngx-mask is not helpful to solve the problem

**Comment by aitboudad** [comment]
the question was not clear enough, you need to adjust the fields on load, check my reply in a similar question https://github.com/ngx-formly/ngx-formly/issues/1102#issuecomment-411491538
