### ISSUE TITLE
modelChange is not working by default (works only on blur) in ng elements / web components

### ISSUE THREAD

**Issue by Gobikannan** [ngx-formly/ngx-formly#2205]
**Description**
I am using ngx-formly with material and it works absolutely fine. But if i move the same components to ng elements and try to use that as Web Components, then modeChange event is not firing on change of value. It fires only on blur but I haven't specified blur anywhere. I assumed, updateOn works as change by default.

Other than that, everything works fine.

- Angular version: 9.0.5 and also tried very latest version
- Formly version: 5.5.13 and also tried very latest version 

Everything else works fine.

**Comment by aitboudad** [comment]
the `change` event behaves that way I think you're looking for `input` event to get value instantly.

**Comment by Gobikannan** [comment]
not really.. 
here is the code,
<formly-form [form]="form" [fields]="fields" [model]="model" (modelChange)="modelChange($event)"></formly-form>

I use modelChange event to check if the input value has changed. I use this particular event which is common for all fields, so that I don't need to listen for each fields.

**Comment by aitboudad** [comment]
Well in that case I'm may need a minimal reproduction example to figure out what's going wrong.

**Comment by Gobikannan** [comment]
Sure, I will create a sample and attach it here or stackblitz.. thanks for your support.

I will notify you when i attach the sample here..

**Comment by Gobikannan** [comment]
Hi @aitboudad 

Please find the attached sample app and ng-elements web components below,

I have already referenced ng elements in the sample app. You just need to run this sample_app,

[sample_app.zip](https://github.com/ngx-formly/ngx-formly/files/4539964/sample_app.zip)

and here is the ng elements project which has all formly fields related.

[ng-elements-components.zip](https://github.com/ngx-formly/ngx-formly/files/4539968/ng-elements-components.zip)

TIA.

**Comment by Gobikannan** [comment]
@aitboudad - I found a workaround for now. If i wrap fields binding by ngZone, then it works fine.

**ts:**
`this.ngZone.run(() => {
      this.localFields =  [{
      key: 'text',
      type: 'input',
      templateOptions: {
        label: 'Some awesome text',
        placeholder: 'Some sweet text',
        required: true,
      },
    }
  ];
});
`
**html:**
`<formly-form [form]="form" [fields]="localFields"
                    [options]="options" [model]="model" (modelChange)="modelChange($event)"></formly-form>`

**Comment by aitboudad** [comment]
Seems Angular Elements has some known issues with NgZone :disappointed:, another workaround is to use the following package https://github.com/remackgeek/elements-zone-strategy.

**Comment by Gobikannan** [comment]
Thanks for the update. I will take a look at the package.

Cheers,
Gobi
