### ISSUE TITLE
Custom Extension - Inserting fields

### ISSUE THREAD

**Issue by andyong79** [ngx-formly/ngx-formly#2207]
Hi guys,

Firstly thanks for building a great package with a lot of really useful functionality. We've been having a play with it to create a survey and it's working for most things we are doing but we have a few things we're looking to extend on and am having a few hiccups with the custom extensions. One example is adding a None of the above checkbox to the end of a multiple choice question which disables the multiple choice question when selected and re-enables when deselected. In the custom extension I create a new object for the none of the above checkbox that implements the FormlyFieldConfig interface and then generate a new array of fields containing the original fields, but with the newly created none of the above field added at the right positions, and then I update the fieldGroup with the new array of fields in the prePopulate method.
The resulting FormlyFieldConfig looks correct to me at the end of prePopulate but the new fields don't get rendered.
I may be trying to do something that isn't supported but if you have any pointers that might help getting things to work I'd appreciate your thoughts.

Thanks

Andy

**Comment by kenisteward** [comment]
Do you have a stackblitz example we could take a look at? I have a seanking
suspicion but I need to see code to confirm.

**Comment by andyong79** [comment]
Hmmm so I bodged together a stackblitz example with the extension I was trying to get working and it seems to work. Go figure. Must be something else we have in the project breaking it somehow?
https://stackblitz.com/edit/angular-l8gavt

**Comment by aitboudad** [comment]
then probably related to https://github.com/ngx-formly/ngx-formly/issues/1624#issuecomment-502771903
