### ISSUE TITLE
add safeHtml to FormlyTemplateOptions 

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2208]
I inspected the code after adding he new feature `safeHtml`, [here ](https://github.com/ngx-formly/ngx-formly/commit/bbd70097b6de9fa7c51b593f4f90cc04c11ea9c8#diff-6b1ce39d87dbf75aa7dd58bf1e421745R14)

I also checked the definition of [FormlyTemplateOptions](https://github.com/ngx-formly/ngx-formly/blob/85b21227b3041a85a9d27ff241a5cbcafc6c71f2/src/core/src/lib/components/formly.field.config.ts#L195
), but I found that it dosen't include the property `safeHtml`.

**Comment by aitboudad** [comment]
`template` will be moved into a sub-package which we will add a separate `FormlyTemplateOptions`.
