### ISSUE TITLE
declare variables and get reference to an Html element

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2209]
```
fields =  [{
    key:"test",    
    template: `<ng-template #ref> </ng-template> {{ test }}`,
    templateOptions:{
      safeHtml: true,
    },
   init(){
     //declare variables here, as we normally do in components.
    test;
    @ViewChild("ref", { read: ViewContainerRef, static: true }) ref: ViewContainerRef;
     
  },
    hooks:{
      onInit(){
        console.log("onInit"),
        this.test = "ok"
        //do something with ref
        },
 
    }   
    
  }]

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2086#issuecomment-584847953

**Comment by eng-dibo** [comment]
looks good, but does it support multi-step form logic? [check this](https://formly.dev/examples/advanced/multi-step-form)

the user may want to show this element only in a specific step.

**Comment by eng-dibo** [comment]
I created a custom formly field whitch is `stepper` as you did in your example for "multi-step forms"
now I need to get a reference for the created custom field `<mat-horizontal-stepper #formlyStepper>`

```
// app.component.ts

@component(...){
  export class AppComonent{
    @ViewChild('formlyStepper') formlyStepper: any;
   fields=[{
     type:'stepper',
     ....
  }]

    

   // after the template has rendered and checked
  next(){
    this.formlyStepper.next()
}
```

I want to reach [this approach](https://stackoverflow.com/a/46469671/12577650) to move the stepper buttons to `AppComponent`

**Comment by aitboudad** [comment]
seems you want to get access of `MatStepper` ourside of the field type which can be done by assigning the `stepper` to `field.templateOptions`:

1. FormlyFieldStepper: Define `goBack` and `goForward`:
```ts
export class FormlyFieldStepper extends FieldType {
  @ViewChild('stepper') set myStepper(stepper: MatStepper) {
    this.to.goBack = () => stepper.previous();
    this.to.goForward = () => stepper.next();
  }
}
```

2. AppComonent:

```ts
export class AppComonent{
   fields=[{
     type:'stepper',
     ....
  }]

  next(){
    this.fields[0].templateOptions.goBack();
  }
}
