### ISSUE TITLE
antd status

### ISSUE THREAD

**Issue by Selion05** [ngx-formly/ngx-formly#2210]
**Question**

I'm using [antd](https://ng.ant.design/docs/introduce/en)  as my ui theme. But the [npm package](https://www.npmjs.com/package/@ngx-formly/ng-zorro-antd) hasn't been updated in a while and  its repository points to this but I can't find it here.

So I was wondering what's the support status for antd? Will antd be dropped?

**Comment by aitboudad** [comment]
`andt` is supported and it should be aligned with Formly version in `V6`.
