### ISSUE TITLE
Is there an easy way to find all dirty fields in the form?

### ISSUE THREAD

**Issue by raviada** [ngx-formly/ngx-formly#2211]
**Question**

I have a requirement to capture all modified fields for an audit log. Before posting the form to API, is there a quick way find all dirty fields? Do we have an API method that returns an array of all dirty fields? If it doesn't exist already, I will loop thru the form and check each field if it is dirty.

**Comment by aitboudad** [comment]
loop thru the form and check each field if it is dirty.
