### ISSUE TITLE
Required inputs should have html 'required' attribute on Material theme, too

### ISSUE THREAD

**Issue by FloppyNotFound** [ngx-formly/ngx-formly#2212]
Attention: I'm submitting the same bug as https://github.com/ngx-formly/ngx-formly/issues/1582, but now for material instead of bootstrap.

I'm submitting a ... (check one with "x")

[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
Current behavior

If an input is required, the label shows the asterisk but the input element does not include the 'required' html attribute, and the "aria-required" attribute is false.

Expected behavior

If an input is required then the input element should have the html 'required' attribute, and the aria-required attribute set with a value of "true".

Minimal reproduction of the problem with instructions

The base ngx-formly material stackblitz shows this:
https://stackblitz.com/edit/angular-material-formly-input-required

You can check for the behavior in Bootstrap theme when you exchange the commented-out import in app.module.ts

Right click on the required input field and the input tag does not have the 'required' attribute.

What is the motivation / use case for changing the behavior?

For ARIA/WCAG compliance, required inputs should have the 'required' attribute.
If this attribute is used on any form field it is identified as required by assistive technologies.
See, for just one example, a discussion at http://john.foliot.ca/required-inputs/

Please tell us about your environment:

Windows 10, VS Code

Angular version: 2.0.X
Angular 9

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome 81.0.4044.129

Language: [all | TypeScript X.X | ES6/7 | ES5]
TypeScript ~3.1.1
Node (for AoT issues): node --version =
12.6.0

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.6.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
