### ISSUE TITLE
use html for label ?

### ISSUE THREAD

**Issue by mickael-poulachon** [ngx-formly/ngx-formly#2215]
**Question**

how can i can use html in label like this : 

`label: 'Input <b>here</b>',`

thx

**Comment by aitboudad** [comment]
This has been requested before and we're still not convainced to support it by default, so either define a custom wrapper or override our `form-field` wrapper to control the label part.

- Custom wrapper: check the following example https://formly.dev/examples/bootstrap-specific/bootstrap-horizontal
- Override our [form-field](https://github.com/ngx-formly/ngx-formly/blob/v5/src/bootstrap/src/lib/wrappers/form-field.wrapper.ts): 
Similar to the above example, just use `form-field` as name:

```patch
    FormlyModule.forRoot({
      wrappers: [{
-        name: 'form-field-horizontal',
+        name: 'form-field',
         component: FormlyHorizontalWrapper
      }],
      validationMessages: [
        { name: 'required', message: 'This field is required' },
      ],
    }),
```

Another way is to use `template`:

```ts
{ template: 'Input <b>here</b>' }
```

**Comment by mickael-poulachon** [comment]
Ok thank you

**Comment by anoop-chauhan** [comment]
👋 Hi @mickael-poulachon and @aitboudad, can you please share a stackblitz project to know how it will be done. 🙏

**Comment by mickael-poulachon** [comment]
hi, you can find a exemple here :
https://stackblitz.com/angular/brlpjkrnorvg?file=src%2Fapp%2Fapp.component.ts

Le lun. 8 févr. 2021 à 13:52, Anoop Chauhan <notifications@github.com> a
écrit :

**Comment by anoop-chauhan** [comment]
@mickael-poulachon Thanks for your quick response, I will check this.
