### ISSUE TITLE
Custom template with a FormGroup doesn't update the model

### ISSUE THREAD

**Issue by fabioportieri** [ngx-formly/ngx-formly#2219]
Hi all
my issue is basically the same of 
Implementing custom template as group of fields #1045

i'd like to be able to implement a custom template, in which there are a bunch of fromgroups/controls inside

so far, even if i define those in the component, the formcontrols i add don't get reflected in the model

if i update the FieldType formControl, i get an updated model, but i can't manage to bind more than that one

for my usecase i don't want to make use of fieldsGroups but instead keep my logic inside the custom template, if possible

as of right now i'm trying to implement "hidden" fieldsGroups meaning i don't want them to be rendered by formly but i want to be able to manage them from my main custom template

i'm hoping for a simpler solution

P.S. another solution i have already in place is to simply listen for my formgroup valuechanges
and the write the value inside the fieldtype formcontrol

many thanks in advance

**Comment by aitboudad** [comment]
Still not clear to me what do you want to achieve, so it would be better to replicate your example using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap in order to check your attempt :)

Thanks!

**Comment by kurtnagel** [comment]
Sorry,

   I did figure out what I was doing wrong. I needed my component (A mat-input and a mat-tree) to be a viewChild of the formly field. 

  Then the value accessor is correctly registered and I am able to pass/update the model as needed. 

Kurt

**Comment by khaldrago96** [comment]
> needed my component (A mat-input and a mat-tree) to be a viewChild of the formly

Hi there, apparently I'm facing the same problem you had. Could you provide more information how you solved it? Thanks!

**Comment by fabioportieri** [comment]
Thanks for the response
i'll try to add an example as soon as i can
meanwhile i'll try to explain myself better
i have a complex custom template in which i want to use a complex formgroup and i want to bind that formgroup into the formly model.. out of the box it works only with the default formcontrol associated to the formly custom template.. if i declare my formgroup inside the custom template the formly model won't be reflected with such formgroup

for now i bypass this issue by listening via valuechanges to the formgroup and writing the value inside the custom template default formcontrol, it works but i was wondering if there is a "cleaner" solution

thanks for the good work

**Comment by khaldrago96** [comment]
@fabioportieri 
In my case [this approach](https://github.com/ngx-formly/ngx-formly/issues/1222) works like a charm
