### ISSUE TITLE
Reset validation on form change

### ISSUE THREAD

**Issue by saadmomin** [ngx-formly/ngx-formly#2220]
**Question**

I have integrated formly for a dynamic form which is called from an api. Many fields are same for different forms like Description (text area field). When user has called a form and a field errors for required validator and the user changes the form to some other form, the required error is still displayed for the Description field (or any other field which is same as previous form)

I have a stackblitz setup where the issue is reproducible. Steps are below:
1. Select subcategory 1 from the dropdown.
2. click on one of the fields but dont select any option. It will show the error for required.
3. Now change the subcategory from the dropdown to another one. the required error stays.

Link - https://stackblitz.com/edit/formly-dynamic-api-form

I need to reset this errors. Help is appreciated.

**Comment by aitboudad** [comment]
```patch
this.fields = [...];
+ this.form = new FormGroup({});
```

**Comment by damsorian** [comment]
@3437 I have a question, to change the fields, you always have to re-create the form?
