### ISSUE TITLE
Disable input field of datepicker

### ISSUE THREAD

**Issue by mham1** [ngx-formly/ngx-formly#2221]
I am trying to disable the input field of the datepicker component, the equivalent of what would be achieved by
 `
<mat-form-field>
  <mat-label>Input disabled</mat-label>
  <input matInput [matDatepicker]="dp3" disabled>
  <mat-datepicker-toggle matSuffix [for]="dp3"></mat-datepicker-toggle>
  <mat-datepicker #dp3 disabled="false"></mat-datepicker>
</mat-form-field>
`
But cannot find any way to do this using `templateOptions` or `datepickerOptions`
Do I have to create a custom date picker template to enable this functionality, or is there a way to do it with the pre-existing datepicker template?

**Comment by aitboudad** [comment]
PR welcomed!

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release. You can now pass the `disabled` value through the `datepickerOptions` property:
```ts
  templateOptions: {
    datepickerOptions: {
      disabled: true,
    },
  },
```

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by SubrahmanyaV** [comment]
I am on Formly Material 5.10.3. 

- This : **<field>.templateOptions.datepickerOptions.disabled = true;** did not work 
- While **<field>.templateOptions.disabled = true;**  works for the input but the datepicker icon is not disabled & on clicking the pop-up shows up, this should get disabled too ...

Worse, the other fields which were disabled gets enabled

**Comment by aitboudad** [comment]
> Worse, the other fields which were disabled gets enabled

@SubrahmanyaV Could you please provide a reproduction example

**Comment by SubrahmanyaV** [comment]
> > Worse, the other fields which were disabled gets enabled
> 
> @SubrahmanyaV Could you please provide a reproduction example

- **field.templateOptions.datepickerOptions.disabled = true;** was resulting in an error because of which the other fields were not getting disabled. 

- I had to revert to using **field.templateOptions.disabled = true;** for now but just for your attention this does not disable the datepciker (the icon remains enabled & allows the User to choose a date & the value is reflected in the input)

**Comment by aitboudad** [comment]
> (the icon remains enabled & allows the User to choose a date & the value is reflected in the input

fixed by #2613

**Comment by SubrahmanyaV** [comment]
- I upgraded to Formly 5.10.6 just before testing this
- The datepicker icon button is still 'not disabled' & it allows me to select a date from the calendar & the same is reflected in the input.
- I use the following code to disable the Formly fields;
        **// --- Disable Document entry fields
        this.documentFields.forEach(docField => {
          docField.templateOptions.disabled = true;
        });**

Below is the screen shot showing the icon button still enabled
![Datepicker disable issue](https://user-images.githubusercontent.com/43541702/101327083-30349600-3894-11eb-9b80-d3f6dd3d7c85.png)

**Comment by aitboudad** [comment]
the fix will be available in `v5.10.7`, I'll let you know once released.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by SubrahmanyaV** [comment]
- I upgraded to v5.10.7 before testing this. 
- The datepicker icon button is now getting disabled.
Many thanks for the fix.  This issue may be closed...

**Comment by bedojs** [comment]
Is there an option to only disable the input field and use only the material date picker icon?

**Comment by aitboudad** [comment]
> Is there an option to only disable the input field and use only the material date picker icon?

use `true` to `readonly`:
```patch
{
  "templateOptions": {
+   "readonly": true
  }
}
``````
