### ISSUE TITLE
Custom date picker for type string.

### ISSUE THREAD

**Issue by hiepnh610** [ngx-formly/ngx-formly#2222]
I have a schema json like this. Can I create a custom date picker for this?

```
"$schema": "http://json-schema.org/draft-04/schema#",
"type": "object",
"properties": {
  "contact_dob": {
    "title": "DOB",
    "type": "string",
    "format": "date-time",
    "widget": {
        "id": "date"
    }
  }
}
```

**Comment by aitboudad** [comment]
The format option is not supported yet in Formly so right now there are two ways: use a `map` option (https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527) or `widget` where you can pass `formlyConfig`:

in case you want to use native `datetime` picker:
```patch
{
  "type": "string",
  "format": "date-time",
  "widget": {
+   "formlyConfig": {
+     "templateOptions": { "type": "datetime-local" }
+   }
  }
}
```


And for a custom dateppicker type:

```patch
{
  "type": "string",
  "format": "date-time",
  "widget": {
+   "formlyConfig": {
+     "type": "datepicker"
+   }
  }
}
```

**Comment by hiepnh610** [comment]
Tks!!! You saved my life. <3
