### ISSUE TITLE
Dynamically load the questionnaire within ngx-formly based on business rules [multiple condition].

### ISSUE THREAD

**Issue by nikitsatpute** [ngx-formly/ngx-formly#2223]
Using ngx-Formly we need to render form dynamically based on the questions response from backend i.e. CMS which we will be getting it via API call but along with it all questions should not render to user.

Subsequent Questions should be shown based on previous questions [more than one] answer.
e.x. : 
Q1 - First question [ YES/NO] 
Q2 - Second question [ Dopr Down with Option 1,2,3]  
Q3 - Third question [ This question should show if Q1 answe is YES and Q2 option selected is 2]  .

I have tried using oneAll, allOf from JSONFormlySchema but not able to added more than one condition.
Can you please let me know what is the best approach and how can we solve this using ngx-form?

**Comment by kenisteward** [comment]
Don't even really need json schema specifically here 

Sounds like you can just take advantage of hiddenExpression for each of the fields. 

See example here https://formly.dev/examples/field-options/hide-fields

If you want to use jsonschema there is a map function you can pass to it to further manipulate the fields or use the widget option to set the firmly config for hidden expression for that field.

**Comment by nikitsatpute** [comment]
Yes, we tried that one but rules need to be governed by backend content server or in some JSON file to show and hide. On the Fly rules might change to show questionnaire. 
As of now we have not finalized the contract but below details we will get from backend CMS :
Question Label
Question Option
IsRequired
Question Depend on which question and output of question.

Below are few usecase where business rule to render Q3 might change on the fly.

UseCase 1 :
Q1 - First question [ YES/NO]
Q2 - Second question [ Dopr Down with Option 1,2,3]
Q3 - Third question [ This question should show if Q1 answe is YES and Q2 option selected is 2] .

UseCase 2 :
Q1 - First question [ YES/NO]
Q2 - Second question [ Dopr Down with Option 1,2,3]
Q3 - Third question [ This question should show if Q1 answer is NO and Q2 option selected is 1] .

**Comment by kenisteward** [comment]
You can also bind the same key more than once. So question 3 can have 2 field configs one with one expression one with the other. Then you can use formstate in your hide expression to decide which one should show.

The important thing here is when are you deciding which use case. If the server is doing it just simply use the different config. If it is client side the latter option might be more viable.

**Comment by kenisteward** [comment]
Also you can put all of the logic you have for question three in a single hideExpression .  What you have given in the example is mutually exclusive due to question 1.

**Comment by nikitsatpute** [comment]
I need to evaluate JSON into hideExpression logic.
E,X : Below is JSON File : Second Question shown only if it meets ConditionToShowThisQuestion condition i.e. Question 1 answer is Yes else hide.
How can I evaluate this into hideExpression on the fly.
{
  "schema":[
				{
					"key": "areYouCitizen",
					"label": "Are You a Citizen?",
					"options":[
                                       {
                                          "label":"Yes",
                                          "value":"Yes"
                                       },
                                       {
                                          "label":"No",
                                          "value":"No"
                                       }
                      ],
					"isRequired": true,
					"hasChildren": false,
					"directParent": [],
					"isDependantonQuest": true,
					"dependencyTree": {},
					"order": 1,
				},
				{
					"key": "areYouTravelling",
					"label": "Are You Travelling?"
					"options":[
                                       {
                                          "label":"Yes",
                                          "value":"Yes"
                                       },
                                       {
                                          "label":"No",
                                          "value":"No"
                                       }
                      ],
					"isRequired": true,
					"hasChildren": false,
					"directParent": [],
					"ConditionToShowThisQuestion": {
						"dependantQuest": ["areYouCitizen"],
						"ifValue": "Yes"
						}
					},
					"order": 2
				}
			]
}

**Comment by kenisteward** [comment]
What type of configuration is this?  It doesn't look like formly config or json schema to me so it would be hard for me to advise you on how to fix it.  

Could you please setup an example in stackblitz with your problem?

**Comment by classifieds-dev** [comment]
You can alter the definition using a callback function.

Here is an example based on something I'm trying to working.

```typescript
@Component({
  selector: 'classifieds-ui-create-profile',
  templateUrl: './create-profile.component.html',
  styleUrls: ['./create-profile.component.scss']
})
export class CreateProfileComponent implements OnInit {

  activedStep = 0;

  steps: Array<StepType> = [
    {
      label: 'Profile Type',
      fields: [this.formlyJsonschema.toFieldConfig(schema, {
        map: (mappedField: FormlyFieldConfig, mapSource: JSONSchema7) => {
          const label = mappedField.templateOptions.label;
          /*if(!['Profile','Type', 'Subtype', 'Adspace'].includes(label)) {
            mappedField.hideExpression = 'true';
          }*/
          return mappedField;
        }
      })]
    }
    /*{
      label: 'General Info',
      fields: [this.formlyJsonschema.toFieldConfig(schema, {
        map: (mappedField: FormlyFieldConfig, mapSource: JSONSchema7) => {
          const label = mappedField.templateOptions.label;
          if(['FirstName','LastName', 'PreferredName', 'MiddleName'].includes(label)) {
            mappedField.hideExpression = 'model.Type !== 0';
          } else if(['CompanyName'].includes(label)) {
            mappedField.hideExpression = 'model.Type === 0';
          } else if(mapSource.title !== 'Profile') {
            mappedField.hideExpression = 'true';
          }
          return mappedField;
        }
      })]
    }*/
  ];

  form = new FormArray(this.steps.map(() => new FormGroup({})));
  options = this.steps.map(() => <FormlyFormOptions> {});
  model = new Profile();

  constructor(private formlyJsonschema: FormlyJsonschema) { }

  ngOnInit(): void {
  }

  prevStep(step) {
    this.activedStep = step - 1;
  }

  nextStep(step) {
    this.activedStep = step + 1;
  }

  submit() {
    console.log(this.model);
  }

}
```

**Comment by aitboudad** [comment]
The questionnaire can be done using `hideExpression` or a `multistep` form:

- Hide expression: https://formly.dev/examples/field-options/hide-fields
- Multi-Step form:
	- using custom field type: stackblitz.com/edit/angular-yu7bzv-uucyxg
	- without custom field type: https://formly.dev/examples/advanced/multi-step-form

For `json-schema` to apply `hideExpression` or extra definition check https://github.com/ngx-formly/ngx-formly/issues/2222#issuecomment-623602210
