### ISSUE TITLE
Disable multicheckbox by 'templateOptions.disabled' regression

### ISSUE THREAD

**Issue by johncotter** [ngx-formly/ngx-formly#2224]
**Description**
Attempting to disable a multicheckbox using the expressionProperties for templateOptions.disabled. Seems like it may be a regression of https://github.com/ngx-formly/ngx-formly/issues/1601.

**Minimal Reproduction**

https://stackblitz.com/edit/ng9-formly-multicheck-disabled

**Your Environment**

- Angular version: 9.1.4
- Formly version: 5.6.1

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.6.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
