### ISSUE TITLE
SSN Mask with ******* value

### ISSUE THREAD

**Issue by ajay1208** [ngx-formly/ngx-formly#2229]
**Question**
Is there a way to hide the ssn user entering in input value ? Like i need to hide the ssn what user enters.

Sample ssn 123-12-8585 need to be hide with * like ***-**-**** on focus out.  But formcontrol value or model should not change. 

Is there any options you can you please suggest to get this functionality?

**Comment by lartheon** [comment]
You can change the fieldoptions type to 'password' https://formly.dev/examples/validation/matching-two-fields
eg

```
{
        key: 'password',
        type: 'input',
        templateOptions: {
          type: 'password',
          label: 'Password',
          placeholder: 'Must be at least 3 characters',
          required: true,
          minLength: 3,
        },
      },
```

**Comment by ajay1208** [comment]
Thanks lartheon. But business requirement is "*" symbol, for password we get different and if its type password browser give option to save in the browser memory. That should not happen.

**Comment by aitboudad** [comment]
You may try to use `ngx-mask` as a [custom field type](https://formly.dev/guide/custom-formly-field)  here is a starter example: https://stackblitz.com/edit/angular-masking-dynamics
