### ISSUE TITLE
Unsubscribing to value changes on a dropdown

### ISSUE THREAD

**Issue by zero-1** [ngx-formly/ngx-formly#2238]
Stackblitz... please check the comment on line #39
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-nopxgo

Whats the recommended way to unsubscribe to a value changes subscription in formly.

This question has been raised before in https://github.com/ngx-formly/ngx-formly/issues/1664
and answered, but I was unable to see any 'onDestroy' or 'unsubscribe' in the attached answer/example at https://formly.dev/examples/other/cascaded-select

In the example the observable is being passed to an 'optionList' but we are not really unsubscribing anywhere.

**Comment by aitboudad** [comment]
```patch
export class AppComponent implements OnDestroy {
+  onDestroy$ = new Subject<void>();
  ...
  fields: FormlyFieldConfig[] = [
    {
      key: 'select1',
      type: 'select',
      hooks: {
        onInit: (field: FormlyFieldConfig) => {
          form.get('sport').valueChanges.pipe(
+            takeUntil(this.onDestroy$),
            tap(sportId => ...),
          ).subscribe();
        },
      },
    },
  ];


+  ngOnDestroy(): void {
+    this.onDestroy$.next();
+    this.onDestroy$.complete();
+  }
}
```

The cascaded-select example has been cleaned in https://github.com/ngx-formly/ngx-formly/pull/1833 which doesn't rely on subscription.

well, I think I'm going to simplify that part https://github.com/ngx-formly/ngx-formly/issues/1986, so expect to be released in `5.7` version (
I'll let you know once done).

**Comment by zero-1** [comment]
thanks for the quick reply...

**Comment by aitboudad** [comment]
**Note**: with [v5.7.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release, `onInit` can return and observables so the  subscription and unsubscribe is handled by Formly:

```patch
```patch
export class AppComponent implements OnDestroy {
-  onDestroy$ = new Subject<void>();
  ...
  fields: FormlyFieldConfig[] = [
    {
      key: 'select1',
      type: 'select',
      hooks: {
        onInit: (field: FormlyFieldConfig) => {
+          return form.get('sport').valueChanges.pipe(
-           takeUntil(this.onDestroy$),
            tap(sportId => ...),
+          );
-          ).subscribe();
        },
      },
    },
  ];

-  ngOnDestroy(): void {
-    this.onDestroy$.next();
-    this.onDestroy$.complete();
-  }
}
```

**Comment by MotassemJa** [comment]
> **Note**: with [v5.7.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release, `onInit` can return and observables so the subscription and unsubscribe is handled by Formly:
> 
> ```diff
> ```patch
> export class AppComponent implements OnDestroy {
> -  onDestroy$ = new Subject<void>();
>   ...
>   fields: FormlyFieldConfig[] = [
>     {
>       key: 'select1',
>       type: 'select',
>       hooks: {
>         onInit: (field: FormlyFieldConfig) => {
> +          return form.get('sport').valueChanges.pipe(
> -           takeUntil(this.onDestroy$),
>             tap(sportId => ...),
> +          );
> -          ).subscribe();
>         },
>       },
>     },
>   ];
> 
> -  ngOnDestroy(): void {
> -    this.onDestroy$.next();
> -    this.onDestroy$.complete();
> -  }
> }
> ```

@aitboudad Hi, does that mean we don't have to manually complete our observables in the hooks methods?

**Comment by aitboudad** [comment]
> does that mean we don't have to manually complete our observables in the hooks methods?

yes, but only for `onInit` hook
