### ISSUE TITLE
ngx formly repeat section - hide the field after field is updated in repeating section

### ISSUE THREAD

**Issue by Syedhussain88-git** [ngx-formly/ngx-formly#2239]
https://stackblitz.com/angular/ovmrpppeojm

Hi @aitboudad ,
I referring the following example. In my case i have a scenario like after i put the values in the field and clicking the add button new field is generated but my need is the old field should be **hide** from the page and keep the existing model.

could you please help me to fix this?

**Comment by aitboudad** [comment]
well the solution may depend on the use case, I see two approaches:

1- within `*ngFor="let field of field.fieldGroup; let i = index;"` you may use `*ngIf` to display the last item only.

2- use `hideExpression`: https://stackblitz.com/edit/angular-myhesx
