### ISSUE TITLE
timeout focus:true

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2246]
**Describe the solution you'd like**
I'm doing an implementation where I need at the beginning of the form to focus on the first field, but I need to apply the focus after a few seconds.

I don't know if there is a way to apply focus after a while as true.

I thought about doing with:
```javascript
expressionProperties: {
       'focus': () => {
            return window.setTimeout (() => true, 300)
      }
}
```

but then I would need to control a field to set it to true, so that it doesn't go straight in.

Is there a more elegant way to do this?

**Comment by aitboudad** [comment]
use observable or `hooks`:

1- Observable:

```ts
expressionProperties:{
  focus: of(true).pipe(delay(1000)),
}
```

2- hooks:

```ts
hooks: {
  onInit: (field) => {
    setTimeout (() => field.focus = true, 300);
  }
}
```
