### ISSUE TITLE
i18n support of validation message might be broken

### ISSUE THREAD

**Issue by zgldh** [ngx-formly/ngx-formly#2247]
**Description**
The validation message does not show correctly.
It shows ```[object Object]```

**Minimal Reproduction**

Go to https://stackblitz.com/angular/vbyqnmnbabq
Which is the official sample from here https://formly.dev/examples/advanced/i18n-alternative

I'm not sure why they have different behaviours.

**Your Environment**

- Angular version: 9.1.6
- Formly version: 5.6.1

**Additional context**
![image](https://user-images.githubusercontent.com/312404/82117898-0e63ac80-97a6-11ea-8419-2cb9d2d74c87.png)

**Comment by aitboudad** [comment]
That's a new feature that allows passing an observable validation message which will be released next week (`v5.7.0`).

**Comment by aitboudad** [comment]
for now, I've reverted the deployed version to the latest release `v5.6`.
Thank you!

**Comment by aitboudad** [comment]
The  [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) is released so the above [example](https://formly.dev/examples/advanced/i18n-alternative) should work now.

**Comment by zgldh** [comment]
Thank you. Appreciate your great work!
