### ISSUE TITLE
Focus border around radio button group

### ISSUE THREAD

**Issue by Gobikannan** [ngx-formly/ngx-formly#2248]
**Description**
If i set to focus true for Radio button field (on page load), then it sets the focus (border) for the entire group.. I m expecting that to set for the first option in the radio buttons.

https://stackblitz.com/edit/ngx-formly-radiobtn-focus

**Your Environment**
- Angular version: 9.1.x
- Formly version: 5.6.1

It works fine for other input controls and it was fine before i upgrade to 5.6.x.

Any workaround for this?

**Comment by Gobikannan** [comment]
Thanks for fixing it real quick. When this change available? any dates in mind?
I assume it will be released in 5.6.2.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.6.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.6.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
