### ISSUE TITLE
Repeated Section + http call display

### ISSUE THREAD

**Issue by tiddle** [ngx-formly/ngx-formly#2250]
**Question**
How do i get the repeated fields to display when the model gets updated by a http call?

Example:
https://stackblitz.com/edit/angular-hrumxw-sav1ta?file=src/app/app.component.ts

If you click on "Add new investment", the form displays somewhat correctly.

**Scenario**
I want to edit Bill's investments and I want the form to display his current investments that was retrieved from a http call.

**Comment by aitboudad** [comment]
When using `push` or object assignment Angular doesn't detect model changes:

```ts
// detect change
this.model = { investments: items };
this.model = { ...this.model, investments: items };

// won't detect change
this.model.investments = [{}];
this.model.investments.push({});
```
