### ISSUE TITLE
Multiple select for json schema has type array.

### ISSUE THREAD

**Issue by hiepnh610** [ngx-formly/ngx-formly#2252]
I am using select component of material.

`multiple.component.html`
```
<mat-form-field
  appearance="outline"
  fxFlex="30"
>
  <mat-label>{{ to.label }}</mat-label>

  <mat-select
    [formControl]="formControl"
    [disabled]="false"
    [required]="false"
    [multiple]="true"
  >
    <mat-option [value]="" *ngIf="!to.options">
      --
    </mat-option>

    <mat-option *ngFor="let option of to.options" [value]="option.value">
      {{ option.label }}
    </mat-option>
  </mat-select>

  <mat-error>
    <formly-validation-message [field]="field"></formly-validation-message>
  </mat-error>
</mat-form-field>
```

`multiple.component.ts`
```
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'formly-select-multiple-type',
  templateUrl: './select-multiple.component.html',
})
export class SelectMultipleTypeComponent extends FieldType {}
```

`json schema`
```
"business_types": {
  "title": "business_types",
  "type": "array",
  "widget": {
      "formlyConfig": {
          "className": "col-4"
      }
  },
  "items": {
      "type": "string",
      "oneOf": [
          {
              "enum": [
                  "1"
              ],
              "title": "Offline"
          },
          {
              "enum": [
                  "2"
              ],
              "title": "Online"
          }
      ]
  }
}
```

This is the result I get. It not working.
![Screen Shot 2020-05-19 at 10 13 31 PM](https://user-images.githubusercontent.com/25858975/82344356-25143880-9a1e-11ea-945d-a940f101d7bc.png)

I expect it look like this.
![Screen Shot 2020-05-19 at 10 13 58 PM](https://user-images.githubusercontent.com/25858975/82344481-4aa14200-9a1e-11ea-8db0-50ae2e48d35c.png)

How can I do that? Thanks!

**Comment by aitboudad** [comment]
to have a multi-select in `json-schema`, you must pass `"uniqueItems": true`:

```patch
"title": "business_types",
"type": "array",
+ "uniqueItems": true,
```

**Comment by hiepnh610** [comment]
@aitboudad I tried to add `"uniqueItems": true` to json schema but it not working. I changed my template like this. It working correctly. Should I use this way?

```diff
- <mat-option *ngFor="let option of to.options">
+ <mat-option *ngFor="let option of field.fieldArray.templateOptions.options [value]="option.value">
  {{ option.label }}
</mat-option>
```

**Comment by aitboudad** [comment]
I don't think so, here is the rendered multi-select type when `uniqueItems` is set to `true`: https://stackblitz.com/edit/angular-zjpysp

**Comment by hiepnh610** [comment]
@aitboudad Cool, it work perfectly. Thanks!!

**Comment by thnguyen308** [comment]
> I don't think so, here is the rendered multi-select type when `uniqueItems` is set to `true`: https://stackblitz.com/edit/angular-zjpysp

Hi @aitboudad,  does this example work when using the PrimeNG library? I tried using your example in my project, but it's not working. It rendered the select component, but throw an error when I choose an option
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/003eec12-f989-4128-98d4-907f12417248" />
