### ISSUE TITLE
Matching Two Fields from examples is not working as expected

### ISSUE THREAD

**Issue by LarryZhou** [ngx-formly/ngx-formly#2253]
Here is my code: https://stackblitz.com/edit/angular-n6foes-jwpy5g

It's modified from sample code (https://formly.dev/examples/validation/matching-two-fields).  I made the modification to get rid of **fieldGroup** and the resulting nesting object.  However, the expected error msg 'These fields must match' was never triggered.  Although debugging indicates that the custom validator code **passwordFieldMatch** runs without any issue, the error was set properly.

Of course, when I used **fieldGroup** and nesting object, it's working: https://stackblitz.com/edit/angular-n6foes-cprrrs.  But I don't really want a **fieldGroup**.

**Comment by aitboudad** [comment]
duplicate of #2255

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release. Check our demo example https://formly.dev/examples/validation/matching-two-fields

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
