### ISSUE TITLE
How to correctly create a custom select type ... and then extend it to my needs?

### ISSUE THREAD

**Issue by devnull69** [ngx-formly/ngx-formly#2254]
I have setup this on stackblitz: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-ykp6sc

Essentially, I would like to create a custom select type in order to add a "x" icon on the right hand side so that a user can clear the model of this element once it is clicked.

So, I copied the template from the ngx-formly/src/bootstrap/src/lib/types/select.ts folder ... but this is already not working (no options are showing, the bottom margin/padding is not correct, the label is not showing etc.).

What am I doing wrong, essentially?

I wanted to add that I LOVE ngx-formly. I have been using angular-formly before ... and it's still getting better :-)

**Comment by devnull69** [comment]
I wanted to add that I LOVE ngx-formly. I have been using angular-formly before ... and it's still getting better :-)

**Comment by devnull69** [comment]
I managed to do it ... see updated Stackblitz

I forgot to set wrappers for the new type to ['form-field']

**Comment by aitboudad** [comment]
Another alternative way is to use Input add-ons  https://formly.dev/examples/bootstrap-specific/input-add-ons

**Comment by devnull69** [comment]
Can those input add-ons be made clickable?

I have added an 'x' icon which (when clicked) calls this.formControl.setValue("")

**Comment by aitboudad** [comment]
use `onClick` https://github.com/ngx-formly/ngx-formly/blob/v5/src/bootstrap/addons/src/addons.component.ts#L12

**Comment by devnull69** [comment]
Thanks for this valuable feedback!
