### ISSUE TITLE
Confirm Password return object I just want string.

### ISSUE THREAD

**Issue by kyawswarthwin** [ngx-formly/ngx-formly#2255]
What I want.
password: "123456"

What I got.
password: {
  "password": "123456",
  "passwordConfirm": "123456"
}

**Comment by LarryZhou** [comment]
This is what I tried to accomplish by getting rid of fieldGroup (and nesting object). However, the custom validator function appears to require a nesting setup.  

See my question: https://github.com/ngx-formly/ngx-formly/issues/2253

**Comment by aitboudad** [comment]
That's a feature (done in https://github.com/ngx-formly/ngx-formly/pull/1980) which was planned for `v6`, but I'll try to make it available in `v5.7` instead

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release. Check our demo example https://formly.dev/examples/validation/matching-two-fields

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
