### ISSUE TITLE
autocomplete causes control.registerOnChange is not a function error

### ISSUE THREAD

**Issue by entspannt** [ngx-formly/ngx-formly#2256]
**Description**
If I create a form with a material autocomplete field that represents an object and another field that accesses a property of that object, I get the following error:
ERROR TypeError: control.registerOnChange is not a function

If I switch the fields (input first, then autocomplete) I get a different error:
ERROR TypeError: parent.setControl is not a function

My goal is to be able to display/switch the object name in the autocomplete and to display/change its properties in separate fields.

**Minimal Reproduction**
https://stackblitz.com/edit/formly-dropdown-issue

**Your Environment**
- Angular version: 9.0.0
- Formly version: 5.6.1

Any help is highly appreciated.

**Comment by aitboudad** [comment]
`autocomplete` expect formControl to be an instance of `FormControl` where `start` field is a `FormGroup` instance, I think to make it simple the `autocomplete` should not be part of the form.

The solution is to define the `autocomplete` inside a wrapper
https://stackblitz.com/edit/formly-dropdown-issue-savxcl

**Comment by entspannt** [comment]
That's great, thank you for the quick help!
