### ISSUE TITLE
Support switch style checkboxes in Bootstrap theme

### ISSUE THREAD

**Issue by essh** [ngx-formly/ngx-formly#2257]
**Is your feature request related to a problem? Please describe.**
Bootstrap supports displaying checkboxes as switches with the appropriate classes according to https://getbootstrap.com/docs/4.5/components/forms/#switches. It would be nice if there was an option to control if this style of checkbox is used under the Bootstrap theme.

**Describe the solution you'd like**
The ability to display checkboxes in switch style as per the above documentation.

**Comment by aitboudad** [comment]
added support in [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0).

```patch
{
  templateOptions: {
+   formCheck: 'custom-switch',
  },
}
```
