### ISSUE TITLE
Formly Table

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2258]
**Describe the solution you'd like**
Exactly yesterday I needed to create a dynamic table, where each column should receive a type of formly or more.
I didn't find anything simple and in the issues I looked for, I had examples with third party libraries.

**Describe alternatives you've considered**
With that, I needed to create something simple, without third party libraries and if you like @aitboudad , I would like to contribute and create this type based on the example below, to make available to the community.
If you have ideas for improvement, you are also welcome.

**Additional context**
stackblitz: https://stackblitz.com/edit/angular-formly-table

**Comment by aitboudad** [comment]
if I'm not wrong that's quite similar to the Repeating Section https://formly.dev/examples/advanced/repeating-section :thinking:

**Comment by GlauberF** [comment]
It's a little more complex than that,
1 - It is a table.
2 - Control of hiding columns, based on fields.
3 - Extract the label from the field that goes inside and play in the column.
4 - Possibility to hide the label from the internal field, since it is used in the header.
And other details, if you look deeply, you will see that it is different, even though it has a slight resemblance to repeating section.

And the idea is to add more things, according to the needs of the community.

**Comment by aitboudad** [comment]
Well right now I would prefer to keep our examples shows the minimal work, more complex ones require a lot of works (more docs, more questions from the community :)) where currently we're still struggling to handle.

**Comment by aitboudad** [comment]
After `v6` I may consider providing full examples that this example can be part of it.

**Comment by GlauberF** [comment]
I am available to help when you need it. :)

**Comment by alindberg** [comment]
@GlauberF - Have you made any updates and/or changes to your example you linked above?

I have been looking for an implementation of a custom table type for Formly and Angular Material and stumbled on your example.

Thanks.
