### ISSUE TITLE
Bootstrap and Materials both in one form?

### ISSUE THREAD

**Issue by Nzkhan** [ngx-formly/ngx-formly#2260]
> Question

Can we use Material and Bootstrap controls both in one form ?
If yes Can someone please share an example or snippet.

I tried installing @ngx-formly/bootstrap on a Material Formly project but wasn't successfull.
Got this error
```
ERROR in ./node_modules/@ngx-formly/bootstrap/fesm5/ngx-formly-bootstrap.js
Module not found: Error: Can't resolve '@ngx-formly/core/select' in 'C:\Users\XXX\Desktop\desktop\workspace\angular6\node_modules\@ngx-formly\bootstrap\fesm5'
```

**Comment by aitboudad** [comment]
They can be used in one project but not in the same form (https://formly.dev/ui).
not sure if it's relevant but if there is a real need why not.

> Can't resolve '@ngx-formly/core/select'

make sure `@ngx-formly/core` is installed and match the same version of `@ngx-formly/material` and `@ngx-formly/bootstrap`.

**Comment by Nzkhan** [comment]
> They can be used in one project but not in the same form (https://formly.dev/ui).
> not sure if it's relevant but if there is a real need why not.
> 
> > Can't resolve '@ngx-formly/core/select'
> 
> make sure `@ngx-formly/core` is installed and match the same version of `@ngx-formly/material` and `@ngx-formly/bootstrap`.

Okay, I guess i have not checked the version , will check the version numbers and reply.
Thanks for the support ✌🏻

**Comment by Nzkhan** [comment]
The issue was solved by matching the version numbers of 
```
@ngx-formly/core  
@ngx-formly/material 
@ngx-formly/bootstrap.
```

Thanks
