### ISSUE TITLE
How to get custom component instance in hooks in formly 5.6.1 and above

### ISSUE THREAD

**Issue by irenagroup** [ngx-formly/ngx-formly#2262]
**Question**
Till ngx-formly 5.5.10 i was able to get custom component type instance using 
 field._componentFactory.componentRef.instance; and invoke methods and dependencies within that component. We are using json-schema with ngx-formly and wrapping onInit hook with closure.

However as part of 5.6.1.  field._componentFactory gets undefined. 
Can you please let me know if this is intentional?
Also how can i get component instance from OnInit hook?

**Comment by aitboudad** [comment]
Well, you should not rely on an internal API :).
Could you please share more details about your use-case in order to see if it worth exposing that part.

**Comment by irenagroup** [comment]
True. I thought there would not be other way to invoke custom input methods from json configs.
Here is reproduction example.  Use case is to trigger method from auto-compelete component method whenever checkbox is clicked. 

https://stackblitz.com/edit/ngx-formly-custom-template-yegjbi

**Comment by aitboudad** [comment]
You may assign the component instance or just the desired method during `onInit`:

```
  ngOnInit() {
    // assign openAutoComplete method
    this.to.openAutoComplete = this.openAutoComplete.bind(this);

	// or assign component instance
    this.to.componentInstance = this;
  }
```

call from hooks:
```ts
// using method call
field.templateOptions.openAutoComplete();

// using component instance
field.templateOptions.componentInstance.openAutoComplete();
```

**Comment by irenagroup** [comment]
Thanks will give it a try!
