### ISSUE TITLE
Validation and masking not working together

### ISSUE THREAD

**Issue by anindyab** [ngx-formly/ngx-formly#2264]
I would like formly masking and validation to work together - but right now it does not.

**Is your feature request related to a problem? Please describe.**
I modified https://stackblitz.com/edit/ngx-formly-custom-template?file=app%2Fformly-field-input.ts

so that I have a phone masking component as follows:

@Component({
  selector: 'formly-field-phone-input',

  template: `
    <div class="form-group">
      <label> {{ to.label }} <span>*</span></label>
      <input mask="000-000-0000" [type]="type" [formControl]="formControl" [formlyAttributes]="field" />
    </div>
  `,
})
export class FormlyFieldPhoneInput extends FieldType {
  get type() {
    return this.to.type || 'text';
  }
}

and in my app.module ts:
    FormlyModule.forRoot({
      types: [
        { name: 'phone', component: FormlyFieldPhoneInput },
      ],

I also have this field defined as :
          {
            "key": "phone",
            "type": "phone",
            "classname": ".col-md-5",
            "templateOptions": {
              "label": "Phone #",
              "placeholder": "Phone #",
              "required": true,
              "pattern": "^[0-9]{3}-[0-9]{3}-[0-9]{4}$"
            },
            "validation": {
              "messages": {
                "pattern": "Phone is not valid. Valid format is: 555-555-5555"
              }
            }
          }

If I change the field type to input, the validation works, but masking does not.
If I change the field type to phone, the masking works but not validation (not even required field validation) - and the interesting part is that the form is invalid and the phone field is also ng-invalid and ng-touched - so formly knows that that the validation has failed - but it is not showing any message or anything else to user.

**Describe the solution you'd like**
I would like formly masking and validation to work together - where if my validation fails, I get the visible indication for the user (eg. red border, validation message) and the field accepts masked input as well.

**Describe alternatives you've considered**
For now I just have the validation. But I would like masking + validation.

**Additional context**

**Comment by aitboudad** [comment]
an input mask shows the format `000-000-0000` but emit the value `0000000000`, so in order to make it work, adjust the pattern validation.

**Comment by anindyab** [comment]
What you said is true, but still masking + validation does not work. eg.

            "key": "phone",
            "type": "phone",
            "classname": ".col-md-5",
            "templateOptions": {
              "label": "Phone #",
              "placeholder": "Phone #",
              "required": true,
              "pattern": "^[0-9]{10}$"
            },
            "validation": {
              "messages": {
                "pattern": "Phone is not valid. Valid format is: 555-555-5555"
              }
            }

or 

            "key": "phone",
            "type": "phone",
            "classname": ".col-md-5",
            "templateOptions": {
              "label": "Phone #",
              "placeholder": "Phone #",
              "required": true
            },
            "validation": {
              "messages": {
                "pattern": "Phone is not valid. Valid format is: 555-555-5555"
              }
            }

**Comment by aitboudad** [comment]
that works for me: https://stackblitz.com/edit/angular-masking-dynamics-p3vj77

**Comment by anindyab** [comment]
Many thanks aitboudad. Appreciate your help.
