### ISSUE TITLE
Nullable Extension

### ISSUE THREAD

**Issue by Sebastian-Habiger** [ngx-formly/ngx-formly#2265]
**Question**
Hi first of all,thanks for that awesome Project :D

I would like to write a nullable extension for formly, that enables formly to have a null value for fieldGroups, based on a templateOption nullable=true.
I was thinking of caching somehow the fieldGroup and based on the model value set it to the fieldConfig or remove it dynamically.
To accomplish that I would also need to track the changes made to the fieldGroup.
Is it possible to do that inside the prePopulate hook of an extension?

Any help or other approaches are highly appriciated.

Thanks

**Comment by Sebastian-Habiger** [comment]
Awesome! Thank you very much.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
