### ISSUE TITLE
How to pass down options from FormArray to fields

### ISSUE THREAD

**Issue by devnull69** [ngx-formly/ngx-formly#2266]
This is my current Stackblitz: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-ykp6sc

You can see that I used a custom repeat section type and a custom select type. When you add a new line (Add another Jedi), you'll see that the new line fields don't show their own labels. Only one line of labels is showing for the repeat section itself.

I achieved this by using a custom templateOption called "showMasterLabels" on the repeat type combined with explicit hideLabel: true settings for each field in the repeat section.

Would it be possible to "pass down" the showMasterLabels setting from the repeat section to the hideLabel settings of all fields inside of this section so that I wouldn't have to explicitly set it for every field?

**Comment by aitboudad** [comment]
Another way is to rely on `expressionProperties`: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-2udhau
