### ISSUE TITLE
Add hooks dynamically on Formlyfieldconfig 

### ISSUE THREAD

**Issue by tamilvjm** [ngx-formly/ngx-formly#2270]
Hi, I want to add hooks dynamically. Other configs are loaded from API as json. Here I need to add onInit hook dynamically and call other API on select changes.

**Comment by aitboudad** [comment]
to adjust the fields on load, check my reply in a similar question https://github.com/ngx-formly/ngx-formly/issues/1102#issuecomment-411491538

**Comment by tamilvjm** [comment]
thanks
