### ISSUE TITLE
select compareWith and ionic 5

### ISSUE THREAD

**Issue by kyawswarthwin** [ngx-formly/ngx-formly#2275]
select compareWith and ionic 5 not work.

**Comment by kyawswarthwin** [comment]
sir please update @ngx-formly/ionic pkg

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
