### ISSUE TITLE
how can we use tabbed panel along with fields outside the tabbed panel in ngx-formly 

### ISSUE THREAD

**Issue by Nzkhan** [ngx-formly/ngx-formly#2276]
> Question / Support Request / Enhancement

I need to develop a page with fields and then tabbed panels and these tabbed panels containing multiple fields respectively

I was able to get the reference from this link [Tabs Form - ngx-formly](https://formly.dev/examples/advanced/tabs), but here I get the form in the below structure

```
Form Start
- tab1
       - field1
       - field2
- tab2
       - field3
       - field4
- Submit button
```

Instead what i actually need to get the form is in the below structure

```
Form Start
- field1
- field2
- tab1
       - field3
       - field4
- tab2
       - field5
       - field6
- field7  
- Submit button

```

how can i achieve the above form structure with dynamic forms

**Comment by aitboudad** [comment]
create a custom field type check the stepper example https://stackblitz.com/edit/angular-yu7bzv-uucyxg
