### ISSUE TITLE
Support click event in non-input template element like an <img> tag

### ISSUE THREAD

**Issue by LarryZhou** [ngx-formly/ngx-formly#2281]
Here is my code: https://stackblitz.com/edit/angular-k5n95b-uenmq4

Basically I would like to add in custom event handlers to external JSON defined elements.  My code has two handlers. The one that is attached to a form field works, but the other that is attached to an icon doesn't.  I couldn't find any sample code for this.

Anyone know how to make the second one works?

**Comment by aitboudad** [comment]
`template` doesn't allow binding events an alternative way is to create a custom field type (check the button type example https://formly.dev/examples/other/button).
