### ISSUE TITLE
Allow to bind API endpoints to the options prop of select fields

### ISSUE THREAD

**Issue by abdelhadibentabet** [ngx-formly/ngx-formly#2282]
**Is your feature request related to a problem? Please describe.**
I'm trying to use observables for select options instead of static data in JSON Powered.

**Describe the solution you'd like**
Allow to bind an URL to the options prop and convert it to an HTTP GET observable.

**Describe alternatives you've considered**
I put the URL in a property called optionsSource and process JSON (create observable from URL)

**Comment by aitboudad** [comment]
use a custom extension (check the i18n example https://formly.dev/examples/advanced/i18n-alternative) where you can transform or apply some changes to the fields (convert options to HTTP GET observable)

```ts
  prePopulate(field: FormlyFieldConfig): void {
    ...
    const to = field.templateOptions || {};
    if (!to || !to.optionsUrl || to.options) {
      return;
    }

    to.options = this.httpClient.get(to.optionsUrl);
  }
```
