### ISSUE TITLE
binding event from json

### ISSUE THREAD

**Issue by mickael-poulachon** [ngx-formly/ngx-formly#2286]
**Question**

How can i bind a event like change from a formly loaded by json like : 

`"fieldGroup": [
            {
              "key": "5ece5f58fbfbd14e2d991465",
              "type": "input",
              "templateOptions": {
                "label": "<p>Q1</p>",
                "required": false,
                "options": [],
                "change": "(field) => { this.variable['5ecd2fca3fe9790b31045044'] = this.model[field.key];}"
              }
            },`

method change is doesn't evaluate error : "this.to.change is not a function" from ngx-formly-core

**Comment by aitboudad** [comment]
I've added an example that you may check https://github.com/ngx-formly/ngx-formly/pull/2273/files

**Comment by mickael-poulachon** [comment]
thank you !
