### ISSUE TITLE
formly Array, message: NgxFormly: passing 'model' input to 'exempleComponent' component is not required anymore, you may remove it!

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2287]
**Description**
I don't know if maybe I'm doing something that has already changed (that's what the message says), but in practice I'm not doing anything other than reassigning the model value.

example: I have an array (table), every time a new itme is added to that array, I need to create a field called _index, where I assign the index of a particular item (table row).

How do I do:
I hear changes through the following function:
```ts
this.formControl.valueChanges
            .pipe(takeUntil(this._unsubscribeAll$))
            .subscribe(() => {
                this._createControlIndexes();
            });
```

my _createControlIndexes function and where the reported message fires:
```ts
private _createControlIndexes(): void {
        const _model = (this.model || []);
        _model.map((value, index) => {
            if (value) {
                value._focused = {};
                value._index = index + 1;
            }
            return value;
        });
        // this.formControl.patchValue(_model, { emitEvent: false });
        this.model = {
            ...this.model,
            ..._model
        }
    }
```

![Captura de Tela_selecionar área_20200528081337](https://user-images.githubusercontent.com/11314585/83134723-2519d580-a0bb-11ea-89f7-271b6bee903f.png)

**Comment by aitboudad** [comment]
`model` inside a custom field type should be considered as read-only, try to add those extra props when calling `add` method:

```ts
(click)="add(null, { _index: field.fieldGroup.length, _focused: {} })"
```

**Comment by GlauberF** [comment]
thanks, it worked :)
