### ISSUE TITLE
Date validation question

### ISSUE THREAD

**Issue by battika** [ngx-formly/ngx-formly#2288]
**Question**

First of all thank you for the great library it really makes things easier.
Just started using ngx-formly and I'm trying to find the best solution to a general use case in my app but I don't feel I've found the best one, hence this support request.

I have two date fields in my model one of the is called `startDate`, other one is called `endDate`. Managed to get ngx-datepicker work with ngx-formly and they work together like a charm.
Now I need to write a validator that makes sure `startDate` will be on or before `endDate` which is a very simple use case.
I can simply attach validators to both of them and display a validation error when `startDate`>`endDate` but the problem is the following. 
When `startDate` is before `endDate`, everything is fine. Then, I move the `startDate` after `endDate` and validation error on the `startDate` field will be displayed. So far, so good. However when I fix the situation by setting `endDate` to a later date than startDate's current date, startDate's validator will not seem to re-run and the error message remains on screen and even worse the form state will stay being invalid.
I had a look into the password matching example on the website where the password and passwordConfirm fields are put in a fieldGroup and a common validator on the fieldGroup takes care of the validation. My problem with that approach is it changes the model as it introduces a new object key with the name of the fieldGroup ( {`password: {password: 'aaa', confirmPassword: 'aaa'}`) which is undesirable as far as my model is concerned and as I move forward I will need to write validators on not so closely connected fields too where putting fields in a fieldGroup will probably not be possible.

So, I'm wondering if someone can suggest a solution for making my date validator work and/or a strategy for validators across various fields where validation state of fields can depend on values of different fields across the form.

Thank you very much in advance.

**Comment by aitboudad** [comment]
Fixed by [#2271](https://github.com/ngx-formly/ngx-formly/pull/2271/files).

The validator that relies on multi fields should be passed through `fieldGroup` and changing the model structure will not be required in `v5.7` which will be released soon :).

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0) release. Check our demo example https://formly.dev/examples/validation/matching-two-fields

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by battika** [comment]
Very nice, thank you!

**Comment by mohammmedimran** [comment]
Hi i need to validate future date in formly how can i do
