### ISSUE TITLE
formControl.setErrors lost when model changes

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#2290]
**Question**

When we set an error programmatically on a field and the model value is changed, the error is removed.
https://stackblitz.com/edit/angular-rdlufz?file=app%2Fapp.component.ts

As a quick fix, we do:
update model before
_formControl.setErrors_ (the error can be seen programmatically)
_setTimeout(formControl.setErrors())_
or update model after
_formly-form->onChange_: error is removed, the error is not detected programmatically thereafter, which can have side-effects
_on next tick setTimeout is run_: the error is set again and is seen programmatically.

During the update of the model and setting the error with setTimeout again, a side-effect can happen, that the error is missing. Also there might be more than one error setting on the same field, the setTimeouts might not run in the wanted sequence, showing not the latest error.

Another possibility we have looked into was setting the error in _templateOptions_ and using a custom validator, however the validation expression only uses the _AbstractControl_ argument, we are missing access to the field.

Is there another solution which doesn't have the above described side-effects ?

**Comment by aitboudad** [comment]
That's an expected behavior.
