### ISSUE TITLE
Select with multiple: true, limit to 1 item in array?

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2293]
Looking for some help here.
I have a case where I need to change the number of items a user can select for a field based on parent field type.

**Environment:** 
Angular 9.0.1
ngx-formly/bootstrap: 5.6.1

The child called by the parent currently has the following
`{
      fieldGroupClassName: "row",
      fieldGroup: [
        {
          type: "select",
          key: "devices",
          className: "col-6 col-sm-4 col-md-4 col-lg-3 ",
          templateOptions: {
            options: [],
            label: "Select Devices",
            placeholder: "Device List",
            required: true,
            multiple: true, 
            enableSelectAll: true,
          },
          hooks: { ..... this is populating the options from a server side query }`

Based on parent field select I would like to
1. Case A - enable multiple select from the list
2. Case B - limit selection to 1 item from the list

When I comment out "multiple: true" the "devices" field is no longer an array.

Additionally, I would like to know if a dropdown like approach is available in the current version as compared to all items being shown under the select?

Thanks

**Comment by aitboudad** [comment]
The simplest way is to keep the select unchangeable and show an error in `Case B` 
which can be done using a custom validator in the parent field as shown in the following example: https://formly.dev/examples/validation/matching-two-fields.

The second solution is to disable all select options except the selected one in `Case B` using `hooks.onInit` and relying on `field.parent`:

```ts
{
  hooks: {
    onInit: (field) => {

      return field.parent.formControl.valueChanges
        .pipe(tap(value => {
           // if Case A
		   field.templateOptions.options = DEVICES_OPTIONS;

           // if Case B
		   field.templateOptions.options = DEVICES_OPTIONS.map(option => {
             return { ...option, disabled: value_selected && option.value !== value_selected }
           });
        })),
      ;
    }
  }
}
```
