### ISSUE TITLE
Text inputs behave strangely after update from 5.6.0 to 5.7.0

### ISSUE THREAD

**Issue by johannesjo** [ngx-formly/ngx-formly#2294]
When changing a input type text based component formly seems to submit either `null` or sometimes just the first character. 

In case of a custom input based custom component I only get null values:
https://github.com/johannesjo/super-productivity/tree/master/src/app/ui/duration/input-duration-formly

This can be tested with the Break Reminder config fields of Super Productivity using the redux dev tools.

Do you need also a stackblitz reproducing the issue?

**Comment by aitboudad** [comment]
fixed in `v5.7.1`

**Comment by johannesjo** [comment]
Thank you!
