### ISSUE TITLE
Two column layout

### ISSUE THREAD

**Issue by devnull69** [ngx-formly/ngx-formly#2295]
Is there a built-in way to have a two column (or three, four maybe six column) layout with ngx-formly?

I tried to set a fieldGroup with fieldGroupClassName "row" on the outside, and inside I wanted to use two fieldGroups with fieldGroupClassName "col-sm-6". The fields inside of the columns would have col-sm-12, so that they would line up vertically.

However, this doesn't work correctly.

Is it possible to have two columns, where fields are vertically aligned per column? It would be nice if the column width could be set like "col-sm-4" for each column

**Comment by aitboudad** [comment]
have you checked the example https://formly.dev/examples/bootstrap-specific/advanced-layout ?

**Comment by devnull69** [comment]
Yes ... but this layout is still row oriented. The fields of a group are in one row

I would like to have two (or more) field groups. Each group in a column, vertically aligned. The grouped fields constitute a logical group (e.g. address information, car information etc.)

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-yp4t9a

**Comment by devnull69** [comment]
Ah interesting. I thought I had to use fieldGroupClassName for fieldGroups. Obviously, it would have worked with just className

What is the exact difference between those two?

**Comment by aitboudad** [comment]
Each field group is rendered using the following component tree where `className` is applied to `formly-field` and `fieldGroupClassName` to `formly-group` component:

```html
<formly-field [class]="fieldGroup.className">
 <formly-group [class]="fieldGroup.fieldGroupClassName">
  <formly-field [class]="child1.className"></formly-field>
  <formly-field [class]="child2.className"></formly-field>
 </formly-group>
</formly-field>
```

**Comment by devnull69** [comment]
Thank you, it works fine now
