### ISSUE TITLE
Dynamic hook not loading dropdown

### ISSUE THREAD

**Issue by vanmig90** [ngx-formly/ngx-formly#2301]
I have radio and dependent dropdown in dynamic schema from API,
Functionality: On selecting radion dropdown list should load based on the selection
Create Mode is working file
When I try fresh form, on selecting radio option dependent dropdown is loading , But When I try the same in edit mode it is not working. Please suggest

**Comment by vanmig90** [comment]
Working only if I set model on AfterViewInit for Edit model , Not sure why hooks.onInit is setting afterViewInit

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction of the issue.

**Comment by vanmig90** [comment]
Step-1: Initialiaze model with radiofield1=2
S-2: Create dynamic form  from json and hook for radiofield1=2 change and set dependent drop-down values... Not working

**Comment by vanmig90** [comment]
Step-1: Initialiaze model with radiofield1=2
S-2: Create dynamic form from json and hook for radiofield1=2 change and set dependent drop-down values... Not working
If I step-2 to afterinit it is working

**Comment by aitboudad** [comment]
sorry but I need a reproduction and that's why we've provided a starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap which you may edit.

**Comment by vanmig90** [comment]
Sure will do it
