### ISSUE TITLE
Change Detection not working inside Formly Wrapper Component

### ISSUE THREAD

**Issue by joharzmn** [ngx-formly/ngx-formly#2306]
**Description**
I have a Kendo Panelbar wrapper which I am using as Formly Wrapper. I have a variable which I bound to expanded property of Kendo Panel Bar Item. When I am changing that property value its not affecting the 

**Minimal Reproduction**

Here is the stackbiltz where I have reproduced the issue:
https://stackblitz.com/edit/change-detection-not-working-in-wrapper?file=src%2Fapp%2Fwrapper.component.ts

**Your Environment**

- Angular version: 9.1.9 (Ivy disabled)
- Formly version: 5.5.10

**Additional context**
I had to change the property in the subscription but it's also not working without subscription.

**Comment by aitboudad** [comment]
instead of `detectChanges` use `_markForCheck`:

```patch
Vars.sub.subscribe((value) => {
  this.isExpanded = !this.isExpanded;

+  (this.options as any)._markForCheck(this.field);
-  this.changeDetectorRef.detectChanges();
});
```

**Comment by joharzmn** [comment]
@aitboudad Its still not working. 
I have updated the stackbiltz. Can you look into it again. Thanks

**Comment by aitboudad** [comment]
@joharzmn I've missed the let you know that you should also update Formly lib to the latest version (`5.7.1`) in order to work properly.

**Comment by joharzmn** [comment]
Okay Thanks I'll try that
