### ISSUE TITLE
Set dateformat as MM/yyyy in material datepicker 

### ISSUE THREAD

**Issue by vanmig90** [ngx-formly/ngx-formly#2308]
How to set dateformat as MM/yyyy in material datepicker in formly schema

**Comment by aitboudad** [comment]
see https://material.angular.io/components/datepicker/overview#watching-the-views-for-changes-on-selected-years-and-months

**Comment by vanmig90** [comment]
Is this option implemented in formly datepicker or I need create custom datepicker component ?

**Comment by aitboudad** [comment]
for now, create a custom `datepicker` component, I'll try to see if that can be done with Formly datepicker when time permits.

Formly datepicker: https://github.com/ngx-formly/ngx-formly/tree/main/src/ui/material/datepicker/src

**Comment by aitboudad** [comment]
added `monthSelected` and `yearSelected` in [v5.8.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.8.0), so it can be done using the following config:

```ts
...
templateOptions: {
  datepickerOptions: {
    startView: 'multi-year',
    monthSelected: (f: FormlyFieldConfig, value: Date, datepicker) => {
      f.formControl.setValue(value);
      datepicker.close();
    },
  },
}
```

for the displayed format `MAT_DATE_FORMATS` is necessary.

**Comment by vanmig90** [comment]
Great, will check and let u know
