### ISSUE TITLE
Chrome Input autofill password over labels

### ISSUE THREAD

**Issue by rnogueira-namoadigital** [ngx-formly/ngx-formly#2314]
**Description**
Form login with username and password get label over autofill input value.

**Minimal Reproduction**
- Source with Material: https://stackblitz.com/edit/ngx-formly-ui-material-rsvufl

To reproduce, you need access it direct here.
https://ngx-formly-ui-material-rsvufl.stackblitz.io/

Steps:
1. Open: https://ngx-formly-ui-material-rsvufl.stackblitz.io/
2. fill the form.
3. click submit button
4. click "key" icon right side avatar user Chrome
<img width="139" alt="Screen Shot 2020-06-18 at 14 47 38" src="https://user-images.githubusercontent.com/62571329/85054673-cbb13d80-b172-11ea-8b9c-e95a718a8644.png">
5. click save password
<img width="316" alt="Screen Shot 2020-06-18 at 14 49 16" src="https://user-images.githubusercontent.com/62571329/85054758-ed122980-b172-11ea-8e7f-7884e1a6febc.png">
6. reload page
7. see input label over username and password autofilled
<img width="306" alt="Screen Shot 2020-06-18 at 14 50 41" src="https://user-images.githubusercontent.com/62571329/85054895-1cc13180-b173-11ea-9b2d-936a097fe665.png">
8. click anyware in the page and input get fixed by it self.
<img width="255" alt="Screen Shot 2020-06-18 at 14 51 24" src="https://user-images.githubusercontent.com/62571329/85054954-3498b580-b173-11ea-89bc-fdd282259f39.png">

**Your Environment**

- Chrome
- Angular version: 9.x
- Formly version: 5.7.1

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.7.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
