### ISSUE TITLE
Reading templateOptions.options

### ISSUE THREAD

**Issue by workplacetimakers** [ngx-formly/ngx-formly#2315]
I have created my own type of formlydesigner specific to my webapp. When I try to edit a FormlyFieldConfig, I am having issues reading the templateoptions.options of a select type field.

console.log shows the options as an array, but typescript is screaming at me saying it is an Observable<any[]>. So, when I try to foreach and map, it then shows each object as any[] despite console.log showing it as a single object. 

What is a good way to read the options from templateoptions.options in order to populate my custom components?

**Comment by aitboudad** [comment]
`options` can be an array or an instance of `Observable`:

- Option 1: define the expected type (when you're sure that the passed options is always an array).

```ts
(field.templateOptions.options as any[]).map(v => ...)
```

- Option 2: check if the passed options is an array first.

```ts
if (Array.isArray(field.templateOptions.options)) {
  field.templateOptions.options.map(v => ...)
}
```
