### ISSUE TITLE
multiple inputs from array

### ISSUE THREAD

**Issue by AHCHRISTIANSEN95** [ngx-formly/ngx-formly#2318]
**Question**

Hello, wondering how i can make a more dynamic form for setting stocks, im fairly new with Formly. And are wondering how i can make a fieldGroup of 3 inputs based on an array. i added a StackBlitz containing a custom input for stock with a wrapper for the fieldGroup. 

is it possible to generate a fieldGroup  based on array like this? 

```
const warehouses = [
  { id: 1, name: "location1", stockvalue: 0 },
  { id: 2, name: "location2", stockvalue: 0 },
  { id: 3, name: "location3", stockvalue: 0 }
];
```

StackBlitz: [https://stackblitz.com/edit/ngx-formly-custom-template-exuxvt](https://stackblitz.com/edit/ngx-formly-custom-template-exuxvt)

**Comment by aitboudad** [comment]
use FieldArrayType: https://formly.dev/examples/advanced/repeating-section
