### ISSUE TITLE
Custom field using kendo combo - selected item is select option rather than bound object

### ISSUE THREAD

**Issue by jwevans** [ngx-formly/ngx-formly#2322]
Hi - Firstly just want to say what a great job you guy's have done with Formly, I have been using it for about 3 months now and it's awesome and so productive to create forms. 

My question:

I am creating a custom formly field for a kendo combo box. I am populating this with a list of objects and would like to display the code - name as the label and bind the selected object to my model. I have most of this working but my issue is that I am getting a formly select option being bound to the model rather than the actual object in my list.

I have reproduced the issue in stackblitz. When the combo item is selected notice the model has an object with a label, value and disabled properties - I would only like to bind just the value to my model. 

https://stackblitz.com/edit/ngx-formly-ui-kendo-ooehx1

**Comment by aitboudad** [comment]
Hi, a similar issue can be solved using `valueProp` which allows controlling the selected value:

```ts
valueProp: item => item.value,
```

In case the value is an object, the [select type](https://github.com/ngx-formly/ngx-formly/issues/2272#issuecomment-633296703) has an input named `compareWith` that compare the option values with the selected value which unfortunately not available in Kendo ComboBox.

For more details https://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/value-binding/#toc-object-values.

**Comment by jwevans** [comment]
Thanks for response - so looks like I can't bind the selected value in the way that I was hoping. The main thing I am trying to achieve is to get the portfolioGroupIk, portfolioGroupCode and portfolioGroupName from the selected option and apply them to the model. I could bind using portfolioGroupIk as the value and on selection change get the selected option and read the  portfolioGroupCode and portfolioGroupName and apply them to the model manually. 

How does this sound as an approach? 
How would I go about getting the selected option?
