### ISSUE TITLE
problem with scope (this)

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2323]
**Description**
I need inside a * focus * event, call a function(adds55StartPhoneBr) from my control,
example:
```
{
    key: 'numero',
    type: 'inputMask',
    templateOptions: {
        mask: 'phones',
        translate: true,
        label: 'Telefone',
        appearance: 'outline',
        focus: (f) => {
            this.adds55StartPhoneBr();
        }
    }
}
```

but doing as in the example above, I get the error
![Captura de Tela_selecionar área_20200622104803](https://user-images.githubusercontent.com/11314585/85295131-e2f37200-b475-11ea-9cb0-29c5c5fdc435.png)

**Comment by aitboudad** [comment]
Could you please provide a reproduction example https://stackblitz.com/edit/angular-rdkazu.
Thanks!

**Comment by GlauberF** [comment]
I'm sorry.
it was a compiler problem, for some reason it did not compile the modifications (when the new function was included).
It only worked after stopping the angular CLI and rotating again.
so it gave the mentioned error.
