### ISSUE TITLE
Model not updated in `change` event

### ISSUE THREAD

**Issue by Devqon** [ngx-formly/ngx-formly#2324]
**Description**
After updating angular from 8.2.14 to 9.1.11, when the `change` event is triggered the model is not updated yet.
I am not sure if this has anything to do with formly itself, but maybe you can point me in the right direction as of why the `model` does not contain the updated value anymore at the moment of the `change` event.
No (console) errors are displayed anywhere.

**Minimal Reproduction**
I am sadly unable to reproduce this in a clean ng9 and formly5.7.2 project, but am more hoping that you could point me to why this could happen to me.

```
@Component({
  template: `
      <form [formGroup]="form" (ngSubmit)="onSubmit()">
        <formly-form
          [form]="form"
          [model]="model"
          [fields]="fields">
        </formly-form>
      </form>
  `,
  selector: 'my-form'
})
export class MyFormComponent {
  model = {};
  form = new FormGroup({});
  this.fields = [{
    key: 'select',
    type: 'select',
    options: [{ label: 'Value', value: 'value' }],
    templateOptions: {
      change: () => console.log(this.model) // does not container 'value' anymore
    }
  }];
}
```

**Your Environment**

- Angular version: 9.1.11
- Formly version: 5.7.2
- Formly bootstrap: 5.7.2
- bootstrap: 4.5.0

**Additional context**
It did work prior the update from angular 8 to 9.

**Comment by aitboudad** [comment]
calling order has been changed in Ivy which may the root cause of that issue but not sure, for a workarround either use:

1- setTimeout

```ts
templateOptions: {
  change: () => setTimeout(() => console.log(this.model))
}
```

2- valueChanges

```ts
{
  hooks: {
    onInit: (field) => field.formControl.valueChanges.pipe(
      tap(value => console.warn(value)),
    ),
  }
}
```

**Comment by Devqon** [comment]
@aitboudad thank you both seem to work!
The second one however causes a `Maximum call stack size exceeded`. Could this be because I reset the form with amongst others the value that is updated?:
```
{
  hooks: {
    onInit: (field) => field.formControl.valueChanges.pipe(
      tap(value => this.resetFormType(value)),
    ),
  }
}
...
private resetFormType(code: string) {
  const extraFields = this.getExtraFields(code);
  this.fields = [...this.basicFields, ...extraFields];
  // Does this re-trigger the `valueChanges`?
  this.form.reset({
    select: code
  });
}
```

**Comment by aitboudad** [comment]
add `distinctUntilChanged`:

```patch
{
  hooks: {
    onInit: (field) => field.formControl.valueChanges.pipe(
+     distinctUntilChanged(),
      tap(value => this.resetFormType(value)),
    ),
  }
}
```
