### ISSUE TITLE
Include position="floating" on ionic theme labels

### ISSUE THREAD

**Issue by tlarrain** [ngx-formly/ngx-formly#2330]
**Is your feature request related to a problem? Please describe.**
I am working on an Ionic app and all my forms are "material" like design (without using Angular Material). This is achieved by using a position="floating" parameter in the ion-label HTML tag. This makes the label move up or down just like material, but it keeps up if the input has a placeholder. 

**Describe the solution you'd like**
I would like to have the option to use that setup of ion-items, which I believe is when you put  `position="floating"` to the ion-label inside the ion-item

**Describe alternatives you've considered**
I've considered using Formly Material, but the design is not the same as the ones I'm using and it's very hard to radically change styles using this library. I was thinking of making my own wrapper, but I'm storing the FormlyFieldConfig in a database on my server, so I don't want to have too much overhead when creating a new form.

**Additional context**
Here you can see the style of the form when having a placeholder:
![localhost_8100_(Pixel 2)](https://user-images.githubusercontent.com/7906220/85562579-9be2b980-b5fa-11ea-9d2d-a84e2151844c.png)
Here is a snippet of that code:
`<form [formGroup]="userInfoForm" (ngSubmit)="onSubmit()">`
`    <div class="form-item">`
`      <ion-item>`
`        <ion-label class="form-label mat-primary" position="floating">Email</ion-label>`
`        <ion-input placeholder="juan@ejemplo.com" autocapitalize="on" type="text" formControlName="email"></ion-input>`
`      </ion-item>`
`    </div>`
`    .... rest of the form ....`
`</form>`

Here is a form without placeholder, with the label inside the input (as Material does):
![localhost_8100_(Pixel 2) (1)](https://user-images.githubusercontent.com/7906220/85562855-df3d2800-b5fa-11ea-9e18-a994c3faac45.png)

And here is with the input filled, with the label in a smaller font:
![localhost_8100_(Pixel 2) (2)](https://user-images.githubusercontent.com/7906220/85562902-e9f7bd00-b5fa-11ea-88d4-22a60524a29b.png)

The code is similar for this one as well:
`<form class="login-form" [formGroup]="loginForm" (ngSubmit)="logIn()">`
`    <div class="form-item">`
`      <ion-item>`
`        <ion-label class="form-label" position="floating">Email</ion-label>`
`        <ion-input  type="email" formControlName="email"></ion-input>`
`      </ion-item>`
`    </div>`
`    ... rest of the form ...`
`</form>`

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1263#issuecomment-434982843
