### ISSUE TITLE
Include monthNames and monthShortNames on Ionic datetime picker

### ISSUE THREAD

**Issue by tlarrain** [ngx-formly/ngx-formly#2331]
**Is your feature request related to a problem? Please describe.**
I am writing an app in Ionic, and it's in Spanish, so I want to put the month names in Spanish as well. Ionic 5 does not give you the option to set them at a global level (in Ionic 3 it was possible, though), so I have to put the names on each DateTime instance.

**Describe the solution you'd like**
Put on the template options a space for `monthNames` and `monthShortNames` for ion-datetime. Additionally, you could put the support for days as well (`dayNames` and `dayShortNames`).

**Describe alternatives you've considered**
I tried to configure it in a global level on my `app.module.ts`, but it seems that it's not possible.

**Additional context**

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.8.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.8.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
