### ISSUE TITLE
I can't add ng-zorro-antd

### ISSUE THREAD

**Issue by KevinGF** [ngx-formly/ngx-formly#2333]
I wanted to use ng-zorro-antd. So I used 'ng add @ngx-formly/schematics --ui-theme=ng-zorro-antd' to add. But I got the following error:
Cannot parse arguments. See below for the reasons.
    Argument --ui-theme could not be parsed using value "ng-zorro-antd". Valid values are: "material", "bootstrap", "ionic", "nativescript", "primeng", 
"kendo".

**Comment by aitboudad** [comment]
Fixed in `5.8` version, give it a try again with the following option:

```batch
ng add @ngx-formly/schematics@5.8.1 --ui-theme=ng-zorro-antd
```
