### ISSUE TITLE
How to have an additional attributes in model - model as an object? 

### ISSUE THREAD

**Issue by cibinthomasjacob** [ngx-formly/ngx-formly#2334]
Can i have the model as an object instead of just plain text? 

Our use case is to dynamically build forms based on JSON from API. We have a requirement to auto populate some fields based on the selection in another field. The templateOption.options in the base field holds more than just label and value, is there any way I can have those additional attributes also in the selected item model? .

I can try to come up with a stackblitz example if you need that.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2272#issuecomment-633296703
