### ISSUE TITLE
ngx-Formly with PrimeNG - Apply CSS at "formly-field-primeng-radio"

### ISSUE THREAD

**Issue by nikitsatpute** [ngx-formly/ngx-formly#2343]
Formly with PrimeNG - CSS

**Question**
I am trying to apply CSS class at “formly-field-primeng-radio” level within formly so that it will take care of margins which is defined in CSS Class.

Is there any way to apply CSS i.e. apply CSS Class at formly-field-primeng-radio level. Example as below.

Actual : <formly-field-primeng-radio>
Expected : <formly-field-primeng-radio class=”ut-align-right label__block-margin”>

NGX-Formly with PrimeNG : Primeng: https://stackblitz.com/edit/ngx-formly-ui-primeng

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1494#issuecomment-551655615

**Comment by aitboudad** [comment]
I think it does but somehow in an indirect way https://stackblitz.com/edit/ngx-formly-primeng-integration-uvj4wf.
Another approach is to create a custom field type that overrides the [original type](https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/primeng/radio/src/radio.type.ts) which gives you total control.
