### ISSUE TITLE
Access model with key containing special characters

### ISSUE THREAD

**Issue by smorandi** [ngx-formly/ngx-formly#2344]
**Question**

Consider following model:
```
export interface Custom {
  id: string;
  'this:is:a:valid:property:for:a:json:object:1.0': object;
}

```

How would i need to declare the "key" property in a FormlyFieldConfig in order to bind it to the "special" property of the model?
I'd appreciate if you could give me a hint on that.

**Comment by kenisteward** [comment]
What have you tried so far?

**Comment by smorandi** [comment]
All sorts of different escape sequences, e.g.:
```
{
  key: 'this:is:a:valid:property:for:a:json:object:1.0'
  key: '[this:is:a:valid:property:for:a:json:object:1.0]'
  key: '\'this:is:a:valid:property:for:a:json:object:1.0\''
}
```

**Comment by smorandi** [comment]
but looking into the code which resolves the "keypath" out of the key in https://github.com/ngx-formly/ngx-formly/blob/bf45b971f38eba07d94d081b8cbe45771b01c5a5/src/core/src/lib/utils.ts#L17
 it does not look as if it would consider this case.

But i am not really sure

**Comment by aitboudad** [comment]
We support a nested key using dot notation which leads into an undesired model value in your case

```ts
// model
{ "this:is:a:valid:property:for:a:json:object:1": [ "dddd" ] }

// instead of
{ "this:is:a:valid:property:for:a:json:object:1.0": "dddd" }
```

Right now there is no way to escape It the dot notation so I'm open to any better proposal.

**Comment by smorandi** [comment]
well i guess multiple approaches would make sense:

-  make key accept a string array with own model path, e.g. [xxx:yyy][id][value]

- dot notation, or rather the split operation on „.“ could take into account that it should omit dots if contained within e.g. single quotes or double quotes

just a thought though

**Comment by aitboudad** [comment]
> make key accept a string array with own model path, e.g. [xxx:yyy][id][value]

That's already supported.

**Comment by smorandi** [comment]
No, does not work.
first of all the type for key is string not string[] or rather string | string[]
second i juut tried multiple variants of the following:

```
export interface Custom {
  id: string;
  'meta:1.0': SomeOtherObject;
}

```
```
export interface SomeOtherObject {
  x: string;
}
```

so assuming i want to access 'x' in SomeOtherObject...so considering you say it should already work. how would you then define the key?

```
fields: {
   key: ['meta:1.0', 'x'] <-- does not work
   key: '[meta:1.0][x]' <-- does not work
}
```

so am i missing something here?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.9.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.9.0) release.

The field now accept passing an array value to field key, so in your case, try passing the following path:

```ts
{
  key: ["this:is:a:valid:property:for:a:json:object:1.0"],
  ...
}
```

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by smorandi** [comment]
that fantastic, thank you very much for fixing this.

unfortunately even though i can now pass in an array, i get an exception if one of the values in the chain of the keypath is null or undefined in the model.

**Comment by aitboudad** [comment]
Tested the above key and it seems working from my side https://stackblitz.com/edit/angular-ssjrom, could you please provide a reproduction example

**Comment by smorandi** [comment]
yes, i will as soon as i can

in the meantime i can show you the stacktrace:

```
cannot read property 'get' of null
    at registerControl (ngx-formly-core.js:1952)
    at FieldFormExtension.addFormControl (ngx-formly-core.js:2989)
    at FieldFormExtension.onPopulate (ngx-formly-core.js:2934)
    at ngx-formly-core.js:710
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder._buildForm (ngx-formly-core.js:706)
    at ngx-formly-core.js:716
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder._buildForm (ngx-formly-core.js:712)
    at ngx-formly-core.js:692
```

seems that the property "parent" in ngx-formly-core is null, for whatever reason

**Comment by smorandi** [comment]
https://codesandbox.io/s/eloquent-surf-vezpr?file=/src/app/app.component.ts

**Comment by aitboudad** [comment]
> seems like we have some different "opinions" how to define a keypath when we talk about string arrays

Parsing that part can be somehow a little complicated and also it may introduce some breaking changes so that's why passing an array is the better choice here.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.9.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.9.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by alikaang-bvk** [comment]
> We support a nested key using dot notation which leads into an undesired model value in your case
> 
> ```ts
> // model
> { "this:is:a:valid:property:for:a:json:object:1": [ "dddd" ] }
> 
> // instead of
> { "this:is:a:valid:property:for:a:json:object:1.0": "dddd" }
> ```
> 
> Right now there is no way to escape It the dot notation so I'm open to any better proposal.

This dot notation is causing a lot of problems for me too is there any way I can bypass it now? I used to fix it by assigning field keys that contain dots manually when generating data from model but my models became very complex now

**Comment by aitboudad** [comment]
@alex-novikov-1990 see https://github.com/ngx-formly/ngx-formly/issues/2344#issuecomment-658155625
