### ISSUE TITLE
ngcc postinstall script crashes on current main branch

### ISSUE THREAD

**Issue by fynnfeldpausch** [ngx-formly/ngx-formly#2345]
**Description**
Using the current main branch as a dependency in my app crashes the yarn task with the following result:

```
error /node_modules/@ngx-formly/core: Command failed.
Exit code: 127
Command: ngcc --properties es2015 module main --first-only && ngcc --properties main
Arguments: 





```

I was not able to build a proper reproduction example via StackBlitz.

**Your Environment**

- Angular version: 9.1.11
- Formly version: main

**Additional context**
I know that this is not an official release yet but I though it is worth sharing. Might be related to https://github.com/angular/angular/issues/36278

**Comment by fynnfeldpausch** [comment]
Amazingly fast response / resolution. Thx @aitboudad

**Comment by aitboudad** [comment]
I've removed the postinstall script, somehow yarn doesn't recognize `ngcc` command.
