### ISSUE TITLE
Material checkbox "required" issue

### ISSUE THREAD

**Issue by bpetex** [ngx-formly/ngx-formly#2349]
**Description**
With material 9 and latest formly 5.8.0 the checkbox required doesn't work as expected anymore. When checkbox is set to "false" state the required error is triggered.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-xzoxnl-3n8gqk

**Your Environment**

- Angular version: 9.1.11
- Formly version: 5.8.0

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.9.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.9.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
