### ISSUE TITLE
Array of items with anyOf properties in json schema

### ISSUE THREAD

**Issue by capital-d** [ngx-formly/ngx-formly#2354]
**Question**

Hello,
tried create array of objects that uses different properties with json shema.
Something like:
`"content": [{"name": "Bond", "idCode": "Some code"},  {"firstName": "James", "lastName": "Bond"}]`

Schema: 
`"content": {
     "title": "Arrays of anyOf",
     "type": "array",
      "items": {
         "anyOf": [
            {...`

Is this possible and how need to compound schema to achieve this?

Create demo with my try:
[stackblitz](https://stackblitz.com/edit/angular-psq6ct?file=src%2Fassets%2Fjson-schema%2FarrayAnyOf.json)

**Comment by aitboudad** [comment]
move `content` field to `properties`:

```patch
{
  "type": "object",
  "properties": {
    "age": {
      "type": "integer",
      "title": "Age"
    },
+   "content": { ... }
  }
- "content": { ... }
}
```

**Comment by capital-d** [comment]
Thank you, my mistake.

Form is working partly. No fields for edit model:
![image](https://user-images.githubusercontent.com/31654219/87212485-6d1d5080-c327-11ea-969e-ba0dd8d529e5.png)

**Comment by capital-d** [comment]
Got it work with next config:

`"content": {
        "title": "Arrays of anyOf",
        "type": "array",
        "items": {
          "type": "object",
          "anyOf": [
            {`

Seems like "type": "object" before "anyOf" is required.

Maybe this fail if items contain different types ie object and string.
