### ISSUE TITLE
Typing char or string in integer type field is possible on Firefox, no validation message

### ISSUE THREAD

**Issue by AoNoOokami** [ngx-formly/ngx-formly#2360]
**Description**
It is possible to type char, for example 'a', 'b' or 'c', or even string, in integer-type fields when using Firefox. There is no validation error message to warn the user.

**Minimal Reproduction**
Use the simple example here: https://formly.dev/examples/advanced/json-schema with Firefox
Type in "Age" field like this:

![formly](https://user-images.githubusercontent.com/28982829/87406500-1468e480-c5c1-11ea-96ef-761ce33ff7e2.png)

**Your Environment**

- Angular version: 8.2.9
- Formly version: 5.8.0
- Firefox version: 78.0.1

**Comment by enricouniurb** [comment]
It is not a bug it is a horrible Firefox behaviour in numeric type.

In the numeric filed I controlled the input character in the keydown event.

This is my solution:
```

{
  name: 'numore',
  extends: 'input',       
  defaultOptions: {            
    templateOptions: {
      required: false,
      type: 'number',
      min: 0,
      max: 3000,   
      //for different behavior on Firefox
      keydown: checkNumeric,
      attributes: {
        onpaste: 'return false;',
      },                           
    },        
  },
},

...

export function checkNumeric(field,event){
  if (event.shiftKey){
    event.preventDefault();     // Prevent character input
  }
  
  if( !(event.keyCode == 9  //Tab!!
    || event.keyCode == 8    // backspace
    || event.keyCode == 46      // delete
    || (event.keyCode >= 35 && event.keyCode <= 40)     // arrow keys/home/end
    || (event.keyCode >= 48 && event.keyCode <= 57)     // numbers on keyboard
    || (event.keyCode >= 96 && event.keyCode <= 105))   // number on keypad
    ) {      
        event.preventDefault();     // Prevent character input
  }       
}


```
