### ISSUE TITLE
How can I pass arbitrary data to a form such that it is accessible by fields?

### ISSUE THREAD

**Issue by thaibossaw** [ngx-formly/ngx-formly#2362]
I have a field called "Address Selector" that is intended to present a list of addresses and require a user to select one.

These addresses are dynamic and can change based on the context the form is being viewed in.

For example, if the user is looking at Client A, then the list of addresses will be that listed for Client A.
If the user is looking at Client B, then the form will present a list of addresses for Client B.

The addresses are available in the parent component that the ngx-form is being used within.

I was hoping for something along the lines of:

`<formly-form 
    [fields]="initialStateEntryFields"
    [form]="form"
    [client]="client">
</formly-form>`

With the client object having an attribute called "addresses" which can then be accessed by a custom field type.

However, short of extending FormlyForm, I'm not sure how this is possible.

Are there any existing solutions to something like this?

**Comment by aitboudad** [comment]
use `model` and pass `address` as key to the field:

```patch
- <formly-form [fields]="initialStateEntryFields" [form]="form" [client]="client"> </formly-form>
+ <formly-form [fields]="initialStateEntryFields" [form]="form" [model]="client"> </formly-form>
```

for a simple address https://formly.dev/examples/other/nested-formly-forms
for array of addresses use array type: https://formly.dev/examples/advanced/repeating-section

**Comment by thaibossaw** [comment]
Hi @aitboudad,

The problem with that, is that the form itself is not representing the client. It's asking for a lot more information completely unrelated to the client and the form doesn't represent the client model in anyway. The address input is a selector to choose between multiple addresses via a dropdown.

The form is json generated and dynamic, and completely unrelated to the client, aside from asking the user to choose a particular address from a list of addresses.

**Comment by aitboudad** [comment]
> Form is presented with various random fields, one of which is "please select one of client's previous addresses"

you can control the displayed fields using `hideExpression`: https://formly.dev/examples/field-options/hide-fields
and to fill the form with the selected data you may rely on form `valueChanges`: https://formly.dev/examples/other/cascaded-select
