### ISSUE TITLE
access global validation messages from custom field component

### ISSUE THREAD

**Issue by fabioportieri** [ngx-formly/ngx-formly#2365]
Hi
i succesfully added global validation messages using i18n plugin, like in this example
https://formly.dev/examples/advanced/i18n-alternative

my issue is i don't know how to access global messages defined as such

export function registerTranslateExtension(translate: TranslateService) {
  return {
    validationMessages: [
      {
        name: 'required',
        message() {
          return translate.stream('global.messages.validate.required');
        }
      }
    ],

in a custom type component (i.e. extending FieldType)

i know i could set a validation message directly in the component config, but i would like to avoid it since i have already a global in place that is shared across my form

in my component i have something like

   <mat-error
          class="mat-error"
          role="alert"
          *ngIf="formControl.invalid && (formControl?.errors)['required'] && (formControl.touched || formControl.dirty)"
        >
          <mat-icon>error_outline</mat-icon> << I18N REQUIRED ERROR MESSAGE HERE >>
        </mat-error>

Thank you for any help

**Comment by aitboudad** [comment]
just use `formly-validation-message` component which render formControl errors:

```ts
<mat-error [id]="null">
  <formly-validation-message [field]="field"></formly-validation-message>
</mat-error>
```

or rely on `form-field` wrapper which can be set through type declaration:

```patch
FormlyModule.forRoot({
  types: [
    {
      name: 'input',
      component: FormlyFieldInput,
+     wrappers: ['form-field'],
    },
  ],
}),
```

**Comment by fabioportieri** [comment]
wonderful, formly-validation-message tag is perfect for my use case.. i guess i must dig into the codebase to know the ins and outs
thank you very much
