### ISSUE TITLE
hideExpression, value is not assigned

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2369]
**Description**
I have a field where I use the **hideExpression** attribute, but when I send the value to that field, it does not update.
And it happens exclusively for this field that uses this attribute.

after a few tests, I checked if it put in **hideExpression**, a timeout, it works perfectly.

I don't really know the reason for that, but I can't generate a minimal reproduction, because it's a very big project. but I believe that it is not ideal to use the timeout, but it works temporarily.

my code:
```typescript
{
    key: 'mis_id_mbcst',
    type: 'autocomplete',
    templateOptions: {
        translate: true,
        label: 'Modalidade de determinação da BC do ICMS ST',
        placeholder: this._translateService.instant('Buscar'),
        appearance: 'outline',
        filter: (term, handle, limit, page, orderBy) => this._icmsStBcDeterminationMethodsService.autocompleteSearch(term, handle, limit, page, orderBy),
        filterOptions: {
            keys: ['mis_codigo', 'mis_descricao'],
            textNoResultsFound: this._translateService.instant('Nenhum resultado encotrado para ')
        }
    },
    hideExpression: (currentData) => {
        // this._virtualDOMService.windowRef().setTimeout(() => {
            if (this.currentData.icms && (this.currentData.icms.cic_id_icms_cst || this.currentData.icms.cso_id_csosn)) {
                return !(
                    (
                        this.currentData.icms.cic_id_icms_cst &&
                        (this.currentData.icms.cic_id_icms_cst.cic_codigo === '10' ||
                            this.currentData.icms.cic_id_icms_cst.cic_codigo === '30' ||
                            this.currentData.icms.cic_id_icms_cst.cic_codigo === '70' ||
                            this.currentData.icms.cic_id_icms_cst.cic_codigo === '90')
                    ) ||
                    (
                        this.currentData.icms.cso_id_csosn &&
                        (this.currentData.icms.cso_id_csosn.cso_codigo === '201' ||
                            this.currentData.icms.cso_id_csosn.cso_codigo === '202' ||
                            this.currentData.icms.cso_id_csosn.cso_codigo === '203' ||
                            this.currentData.icms.cso_id_csosn.cso_codigo === '900')
                    )
                );

            }
            return true;

        // });
    }
}
```
**note**, commenting out the timeout (this._virtualDOMService.windowRef().setTimeout), works.

video example:
https://streamable.com/d341gp

**note**: when i click on edit in the list, i simply take the contents of the list and update the icms field, using patchValue.
And the mentioned field that is using **hideExpression**, is within the icms

**Your Environment**

<pre>
<code>
Formly: 5.9.0

Angular CLI: 10.0.3
Node: 12.18.1
OS: linux x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.3
@angular-devkit/build-angular      0.1000.3
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.1000.3
@angular-devkit/core               10.0.3
@angular-devkit/schematics         10.0.3
@angular/cdk                       10.0.2
@angular/cli                       10.0.3
@angular/flex-layout               9.0.0-beta.29
@angular/material                  10.0.2
@angular/material-moment-adapter   10.0.2
@ngtools/webpack                   10.0.3
@nguniversal/builders              10.0.1
@nguniversal/common                10.0.1
@nguniversal/express-engine        10.0.1
@schematics/angular                10.0.3
@schematics/update                 0.1000.3
rxjs                               6.6.0
typescript                         3.9.7
webpack                            4.43.0

</code>
</pre>

**Comment by aitboudad** [comment]
`patchValue` won't affect the hidden fields instead update the root `model` to trigger an update that will take account of hidden fields.

**Comment by GlauberF** [comment]
@aitboudad  I'm doing it this way:
this.field.parent.formControl.get('icms').patchValue({
     index,
     ...(this.model?.[this.field.key as string | number]?.[index] ?? {})
});

**Comment by aitboudad** [comment]
I was going to suggest `resetModel` :smile: not the better approach but the only available one for now.
