### ISSUE TITLE
Values of model are not loaded correctly when 'oneOf' properties have the same name

### ISSUE THREAD

**Issue by AoNoOokami** [ngx-formly/ngx-formly#2374]
**Description**

Please see the stackblitz example prepared below to reproduce the behaviour. It's based on the 'oneOf' example of the documentation. The model contains values (main type: animal, sub type: dog) that should be displayed when the form is loaded, but it's not the case.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-uyjhdk

**Your Environment**

- Angular version: 8.2.9
- Formly version: 5.9.0

**Additional context**

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.9.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.9.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
