### ISSUE TITLE
this.form.disable() not working in NativeScript

### ISSUE THREAD

**Issue by jigsawmegs** [ngx-formly/ngx-formly#2379]
**Description**
I need to present the form and data previously entered but prevent changes.
I have tried to use form.disable() but its not being honoured.
I have also tried setting isEnabled on <form> and <formly-form>

**Comment by aitboudad** [comment]
try to call `disable` after the form is built which can be done inside `hooks`:

```ts
  fields: FormlyFieldConfig[] = [
    {
      hooks: { onInit: ({ form }) => form.disable() },
      fieldGroup: [
        {
          key: 'text',
          type: 'input',
          templateOptions: {
            label: 'First Name',
          },
        },
      ]
    }
  ];
```

another approach is to rely on form-state: https://formly.dev/examples/form-options/form-state
