### ISSUE TITLE
bypassSecurityTrustHtml in formly lib increases potential for XSS

### ISSUE THREAD

**Issue by aorlowski-g** [ngx-formly/ngx-formly#2380]
**Description**
The addition of bypassSecurityTrustHtml in [this change](https://github.com/ngx-formly/ngx-formly/pull/2090/commits) raises some security concerns due to the potential of library clients using the safeHtml flag incorrectly. This is limiting us from bringing formly into our internal project.

Suggested alternative is to change template type to (string | SafeHtml) and let consumers call bypassSecurityTrustHtml themselves if they so choose. This is needed to avoid compilation error described here -https://github.com/ngx-formly/ngx-formly/issues/2039#issuecomment-583890544

This helps stick to the angular team's guidance on using bypassSecurityTrust functions - "When using bypassSecurityTrust..., make sure to call the method as early as possible and as close as possible to the source of the value, to make it easy to verify no security bug is created by its use."

**Minimal Reproduction**
Commit in question - https://github.com/ngx-formly/ngx-formly/pull/2090/commits/2205eaed7eb55925a45979a6d49a93aebbe14bd8

**Comment by aitboudad** [comment]
`bypassSecurityTrustHtml` is not enabled by default, you must pass `true` to `safeHtml` option in order to by pass it.

**Comment by aitboudad** [comment]
You can even prevent using that feature in your app by creation a custom extension and throw an Error when `safeHtml` is true.
