### ISSUE TITLE
how to implement material datepicker with custom validation

### ISSUE THREAD

**Issue by fabioportieri** [ngx-formly/ngx-formly#2382]
Hi
i'm trying to implement a custom type with a material datepicker into it

i started from the example in 
https://stackblitz.com/edit/angular-gkwj6z?file=app%2Fdatepicker-type.component.ts 

and i want to modify it in order to directly show the validation messages into it, preferably via a formly-validation-message in order
to have full control of the markup (suppose i want to add an icon to the message)

this is so far my attempt
https://stackblitz.com/edit/angular-e4ac6e?file=app%2Fdatepicker-type.component.ts

i have a major issue with the formly validation message:

ERROR TypeError: Cannot read property 'errors' of undefined
    at FormlyValidationMessage.get [as errorMessage] (formly.validation-message.ts:14)

and another issue i have is somewhat the calendar popup icon isn't showing anymore

any help is appreciated, thank you

**Comment by aitboudad** [comment]
The above example uses an outdated Formly version, just update your deps and it should work!

**Comment by fabioportieri** [comment]
thank you.. i updated the formly version here:

https://stackblitz.com/edit/angular-qgebin?file=src%2Fapp%2Fapp.module.ts

and it indeed it works.. mostly

the only issue left is, i don't understand why i don't get the error message for the validator registered in the ngmodule, 'dateValidator'
if i register it inside the component it works

also as a bonus question: is there a way to show all the registered validators error messages? so far i'm under the impression only one error message at a time get shown, with multiple validators

thank you very much

**Comment by aitboudad** [comment]
> the only issue left is, i don't understand why i don't get the error message for the validator registered in the ngmodule, 'dateValidator'
if i register it inside the component it works

The returned object id should match the validation message id, try with:

```ts
export function dateValidator(control: FormControl): ValidationErrors {
  return { 'dateValidator': true }
}
```

Another way is to return the message through the validator itself:

```ts
export function dateValidator(control: FormControl): ValidationErrors {
  return { 'date': { message: 'why this doesnt print' } };
}
```


> also as a bonus question: is there a way to show all the registered validators error messages? so far i'm under the impression only one error message at a time get shown, with multiple validators

The current implementation shows only one error at a time. Please open a new issue and I'll try to find a solution when time permits!

**Comment by fabioportieri** [comment]
Thank you again :)
