### ISSUE TITLE
expressionProperties and hideExpression are called dozens of time when I log them

### ISSUE THREAD

**Issue by jesseboydgsa** [ngx-formly/ngx-formly#2383]
Yes
**Description**
When I log my hideExpression I see my log dozens of times in the console.
Is this normal?  Sometimes I've seen like up to 50 calls on clicking a select button.  What should I look for that might be causing this?
Thank you all for your hard work on this project!  

**Minimal Reproduction**

![image](https://user-images.githubusercontent.com/58823468/88240952-9ac69b80-cc3d-11ea-9afb-0b08adaa8b12.png)

can only share snippets of non-secure code

**Your Environment**
Angular 8
Formly : not sure it is in a wrapper from the design team, probably at least 1 version back, will update when I'm told.
- Angular version: X.Y.Z
- Formly version: X.Y.Z

**Additional context**
Not sure if this affects the model or calls but I have an array for the formlyFieldConfig and define fields in different classes then add them all to this one array.

**Comment by aitboudad** [comment]
The expression is evaluated whenever Change detection is triggered which may lead to a performance issue for a large Form, the solution is to rely on `modelChange` that can be done by passing an extra option through the config:

```ts
@NgModule({
  imports: [
    FormlyModule.forRoot({
      extras: { checkExpressionOn: 'modelChange' }
    }),
  ],
})
export class AppModule {}
```

**Note**: In `V6` the `modelChange` will be the default behavior.
