### ISSUE TITLE
Can textarea contains multi new line data in a form?

### ISSUE THREAD

**Issue by bejgumshirisha** [ngx-formly/ngx-formly#2386]
I have a form where I am using a textarea.If I enter a multiline data and again showing it back It is showing as invalid format.

Can you please suggest me how to handle  multiline data?

**Comment by aitboudad** [comment]
Hi, the request is not clear to me but to my understanding in textarea the new line is presented by `\n` character so when showing it back you should apply the reverse in your data handler.

> Can you please suggest me how to handle multiline data?

The easy way is to keep the data as it is or use an appropriate tool such as https://github.com/KillerCodeMonkey/ngx-quill
