### ISSUE TITLE
Warning: circular source file mapping dependency

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2387]
**Description**
after updating the angle to version 10.0.4, these warning started

<pre><code>
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/services/formly.config.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/services/formly.config.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/services/formly.config.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/services/formly.form.builder.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/services/formly.form.builder.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/services/formly.form.builder.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.form.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.form.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.form.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.field.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.field.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.field.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.attributes.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.attributes.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/components/formly.attributes.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field.type.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field.type.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field.type.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field.wrapper.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field.wrapper.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field.wrapper.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/formly.group.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/formly.group.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/formly.group.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/formly.validation-message.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/formly.validation-message.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/formly.validation-message.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field-template.type.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field-template.type.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/templates/field-template.type.d.ts.map
Warning: Unable to fully load /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/core.module.d.ts for source-map flattening: Circular source file mapping dependency: /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/core.module.d.ts.map -> /var/www/html/pwa_vimbo/node_modules/@ngx-formly/core/lib/core.module.d.ts.map

</code></pre>

**Your Environment**
<pre><code>
Angular CLI: 10.0.4
Node: 12.18.1
OS: linux x64

Angular: 10.0.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.3
@angular-devkit/build-angular      0.1000.4
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.1000.4
@angular-devkit/core               10.0.3
@angular-devkit/schematics         10.0.4
@angular/cdk                       10.1.0
@angular/cli                       10.0.4
@angular/flex-layout               9.0.0-beta.29
@angular/material                  10.1.0
@angular/material-moment-adapter   10.1.0
@ngtools/webpack                   10.0.4
@nguniversal/builders              10.0.1
@nguniversal/common                10.0.1
@nguniversal/express-engine        10.0.1
@schematics/angular                10.0.4
@schematics/update                 0.1000.4
rxjs                               6.6.0
typescript                         3.9.7
webpack                            4.43.0

</code></pre>

**Comment by aitboudad** [comment]
see https://github.com/angular/angular/issues/38001#issuecomment-656759837

**Comment by GlauberF** [comment]
@aitboudad thanks!
