### ISSUE TITLE
Add Directive

### ISSUE THREAD

**Issue by stefanofalasca** [ngx-formly/ngx-formly#2388]
Hi,
I'm trying to add a my directive to an input component. Directive should draw a rectancle around component on mouse over with ctrl key button pressed. 

Directive selector name is appInfo, so I added it like follow field. I see the attribute appInfo into dom input, but the directive is not instanced
`{
          key: 'firstname',
          type: 'input',
          templateOptions: {
            label: 'First name',
            required: true,
            attributes: {
              appInfo: null
            }
          },
        }`

here there is a sample, how you can see directive work on last two components out of formly, and doesn't work into formly field. 

https://stackblitz.com/edit/angular-l4ckdw

**Comment by aitboudad** [comment]
using `attributes` won't apply a directive as it requires to be compiled in order to work so the only solution is to set it explicitly through a custom field type (https://formly.dev/guide/custom-formly-field).

**Comment by stefanofalasca** [comment]
Hi,
I need to use this directive for all components, I can't wrap all material library components. Is there a work round ?

**Comment by 10229428** [comment]
> Hi,
> I need to use this directive for all components, I can't wrap all material library components. Is there a work round ?

Do you solve this? I ran into the same problem. 
@aitboudad

**Comment by aitboudad** [comment]
custom wrapper would solve partially your need, you may check how we did for prefix/suffix on material ui https://formly.dev/examples/other/material-prefix-suffix
