### ISSUE TITLE
How to implement a compare validator  based on more than one field?

### ISSUE THREAD

**Issue by cibinthomasjacob** [ngx-formly/ngx-formly#2389]
**How to implement a compare validator  based on more than one field**

I have a use case for a validation involving more than one field , only one field will get the validator , but the check/expression should be evaluated on change of both fields. I am not able to get the validation to refresh onchange of the other field. Please advise.

I have come across your [workaround suggestions](https://github.com/ngx-formly/ngx-formly/issues/966)  to use errorpath which requires combining these fields into a formgroup, Since my use case involves dynamic forms , the fields end up being spread across multiple form groups for how apart they are on screen.

I have tried using both expression as well as with parameters, please find below samples for what I am trying to accomplish

Example 1: https://stackblitz.com/edit/angular-3iqefb
Example 2: https://stackblitz.com/edit/angular-cb3ggj
 
The actual use case involves dates, start date and an end date, one always needs to fall before the other. But if it works for simple integers, i can manage for dates as well.

**Comment by aitboudad** [comment]
The solution is to define the validator in their root field an example can be found in our demo https://formly.dev/examples/validation/matching-two-fields
