### ISSUE TITLE
Events Mouse hover,leave and keys up/dn

### ISSUE THREAD

**Issue by stefanofalasca** [ngx-formly/ngx-formly#2393]
Hi,
I need to trap events mouse hover,leave and keys up/dn, to draw a rectangle when key CTRL is pressed and mouse is over on component. I don't want write a custom component, because should be work on all components.
Then on click event with CTRL key pressed I need to trap click, for show a my pop up dialog.
How can I do it ?

**Comment by kenisteward** [comment]
If you wanted to do this the approach would be to write a custom map extension that applied to all elements that has the configuration you are looking for.

https://github.com/ngx-formly/ngx-formly/issues/1624#issuecomment-502771903


This could be an example of a start of something like that.  Then you'd just add the function onto the template options that would be included in the formlyatteibutes to be applied to the component tfor keyup/keydown events and do what. You'd want. 

I'm on mobile so I can't whip up an example atm for you sorry.
