### ISSUE TITLE
JSON schema oneOf with $ref definition

### ISSUE THREAD

**Issue by capital-d** [ngx-formly/ngx-formly#2394]
**Question**

Hi, can't manage to work array of oneOf and $ref definitions, got errors "Cannot find a definition for #/definitions/top-image.".

JSON config:
`"content": {
        "title": "Main content",
        "type": "array",
        "items": {
            "type": "object",
            "oneOf": [
              {
                "title": "Top image",
                "$ref": "#/definitions/top-image"
              },
              {
                "title": "Simple text",
                "$ref": "#/definitions/text"
              }
            ]
        }
      }`

Works fine if put schema directly in oneOf block.

And without "type": "object" formly didn't render input ether.

Test project: 
https://stackblitz.com/edit/angular-psq6ct?file=src%2Fassets%2Fjson-schema%2FworkRef.json

Is in possible? Thanks in advance.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.9.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.9.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
