### ISSUE TITLE
How to Force Error State inside a custom-template?

### ISSUE THREAD

**Issue by cibinthomasjacob** [ngx-formly/ngx-formly#2395]
How to Force Error State inside a custom-template?

I am trying a custom search input which also includes a button. On click of the button, I need to trigger required validation for the search field and not other fields in the form. I am trying to make use of expression properties to trigger validation.show after the button click. But am not able to get the validation.show to work in case of a custom template.Please advise.

Example : https://stackblitz.com/edit/ngx-formly-ui-material-fqgsbg

**Comment by kenisteward** [comment]
On my phone so short answer

Look up showerror in documentation

**Comment by cibinthomasjacob** [comment]
I am referring the Force Error State example from documentation in my example, it works fine for default types, but not for custom templates, I am probably missing something in my custom template, please have a look at my example too if you can.

**Comment by aitboudad** [comment]
import `FieldType` from formly material:

```ts
import { FieldType } from '@ngx-formly/material/form-field';
```
