### ISSUE TITLE
Found Vulnerability in @ngx-formly/schematics@5.9.3

### ISSUE THREAD

**Issue by saurabh47** [ngx-formly/ngx-formly#2398]
Hello sir,
In [Synk](https://snyk.io/) test,Found Vulnerability in **@ngx-formly/schematics@5.9.3**
[Here is Synk Report](https://app.snyk.io/test/npm/@ngx-formly/schematics/5.9.3)
This Vulnerability is because of  **@angular-devkit/core@0.6.8** which uses **ajv@6.4.0** dependency
This issue is fixed in latest **@schematics/angular** **@angular-devkit/core**

[ngx-formly/schematics](https://github.com/ngx-formly/ngx-formly/blob/main/src/schematics/package.json) uses **@angular-devkit/core": "^9.1.9** dependency.But in the **[@ngx-formly/schematics/5.9.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.9.3)** release build it uses **@angular-devkit/core": "^0.6.5**
In release note this [ecf1646eefd2](https://github.com/ngx-formly/ngx-formly/commit/ecf1646eefd29b97294bbe3b269fa5c9ee666019) commit is included.
Please check with the latest release.

**Environment**

- Angular version: 8.2.14
- Formly version: 5.9.3

Thank you so much

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by saurabh47** [comment]
Thanks you so much @aitboudad
