### ISSUE TITLE
Material autocomplete does no reset options on value change

### ISSUE THREAD

**Issue by ElesGergo** [ngx-formly/ngx-formly#2399]
**Description**
Material autocomple does no reset on value change.

I have two fields depending on each other, one is a selection the other is an autocomplete.
Whenever the user selects an item from the selection it changes the value array of the autocomplete (from where it does the filtering).

**Minimal Reproduction**

1.Click into the autocomplete field to see results.
2.Press the change button which will change the value array for the autocomplete
3.Click into the autocomplete input
4. ISSUE it shows options with wrong value array.

https://stackblitz.com/edit/angular-nuqgtc-i6u2ap?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: X9.1.11
- Formly version: 5.8.0

**Additional context**
I thought it is something with change detection, however immuteably changing the value array does not solve the issue for me.

**Comment by jizza** [comment]
Hi @aitboudad, thanks for your reply. Coincidentally I just to ran into a similar issue. However, I don't fully understand your solution. Could you elaborate a bit on how you'd implement that?

**Comment by ElesGergo** [comment]
@jizza 
Reassigning the "fields" triggers cdr. Here is an example:
https://stackblitz.com/edit/angular-nuqgtc-i6u2ap?file=src%2Fapp%2Fapp.component.ts
What I am curious about is why immutably reassigning the array does not trigger cdr. @aitboudad would be appriciated if you could help us out I update the stackblitz example.

**Comment by aitboudad** [comment]
The better approach is to rely on rxjs https://stackblitz.com/edit/angular-nuqgtc-vkgxm6
