### ISSUE TITLE
Placeholder with Bootstrap UI not showing

### ISSUE THREAD

**Issue by PyrolaMinor** [ngx-formly/ngx-formly#2401]
**Question**
Hello,

I'm using formly with bootstrap UI on Angular 9 and using JSON Schema source.
Here's a simplified example of my JSON Schema: 
{
    "schema": {
        "type": "object",
        "properties": {
            "ip": { "title": "My IP", "placeholder": "0.0.0.0", "type": "string", "pattern": "^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$", "description": "My awesome IP description" },
        }
     }
}

I simply load the JSON like this :
this.http.get<any>('/assets/exemple.json').pipe (
      tap(({schema}) => {
        this.myForm = new FormGroup({});
        this.fields = [this.formlyJsonschema.toFieldConfig(schema)]
        this.options = {};
      }),
    ).subscribe();

With very little tweaks:
FormlyModule.forRoot({
...
types: [
        { name: 'string', extends: 'input', component:CustomInputComponent},
...
]

And a custom template: 
<input class="form-control" [type]="type" [formControl]="formControl" [formlyAttributes]="field"> 

Everything is working well except the placeholder... I can't set it visible... 😢 
I can force a default value with templateOptions but can't read the value from the JSON Schema.

Even if I try to set the to.placeholder in another field it's not working.

Non working example (with placeholder):
<input class="form-control" placement="top" [ngbTooltip]="to.placeholder" [type]="type" [formControl]="formControl" [formlyAttributes]="field">

Working example (with description):
<input class="form-control" placement="top" [ngbTooltip]="to.description" [type]="type" [formControl]="formControl" [formlyAttributes]="field">

I'm maybe missing something, but I couldn't found solution or similar problem since days....

Thank you.

**Comment by aitboudad** [comment]
placeholder is not part of `json-schema`, instead pass it through widget option https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
