### ISSUE TITLE
Custom validator expression only triggered on value change

### ISSUE THREAD

**Issue by ashishjain85** [ngx-formly/ngx-formly#2402]
**Question**

Hi,

I have a scenario where I have defined custom validator on a field

validators: {
                maximumLength: {
                    expression: (control: AbstractControl, field: FormlyFieldConfig) => {
                        return !control.value || control.value.length <= field.templateOptions.maximumLength;
                    },
                    message: (error, field) => {
                        return this.translate.instant('MaxLengthExceeded', { length: field.templateOptions.maximumLength });
                    }
                },
            },
This is only getting triggered when the value of the control changes or when user types anything on the input. 
Is there any way this validator can be triggered when control is marked touched because I want to show all controls in error state when user presses save button?

A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
> Is there any way this validator can be triggered when control is marked touched because I want to show all controls in error state when user presses save button?

that the default behavior just ensure you're using the submit button another option is to rely on formState https://github.com/ngx-formly/ngx-formly/issues/566#issuecomment-345509067
