### ISSUE TITLE
Saving formly state in a database including hideExpression values and or options

### ISSUE THREAD

**Issue by jesseboydgsa** [ngx-formly/ngx-formly#2405]
**Question**

A clear and concise description of what the question is.

We need to save the state of the form when the user chooses to save.  I have successfully stored the filter model and re-inflated it which restores the users search state.  The problem is that filter model does not hold hideExpression values so when I restore the users filter Model all the values are there but some fields with values do not display because these filters are hidden by default.  All the values are correct.  I am trying to store the 'fields' but that causes a 'Type error: cyclic object value' message because I think fields can not be stringified.  I am seeking guidance on how to save not only the formly values but also the state of the form.  What is best practice for fomly persistence and retrieval?   Thank you!

**Comment by aitboudad** [comment]
`hideExpression` should not be saved as it evaluates the form state, the only part that you should save is the `model` and `formState` except if you generate the Formly fields dynamically, is it the case?

**Comment by jesseboydgsa** [comment]
no formly fields are static.  for example question1 is not shown by default.  you pick a value for question1 it stores correctly, but when you load saved search you don't see question1 it is hidden by default, when you pick it in more filters you see the correct value is there.  this may be confusing for user because the value loads correctly but the filter does not 'unhide'

**Comment by aitboudad** [comment]
ok then you don't have to save the Formly fields, just rely on the `model` which may work
In that case could you please provide me a minimum reproduction in order to identify the issue?

**Comment by jesseboydgsa** [comment]
filtermodel loads all the saved fields correctly (even if it's hidden).  is there a nice way to set hideExpression to false for any field that has a valid value?

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/issues/2381#issuecomment-662953993

**Comment by jesseboydgsa** [comment]
autoClear is helpful and we use that during a user session.  in this case we replace the filterModel with a saved filterModel.  we don't want to clear a hidden field, we want to show it if it has a value after loading the new filterModel.  sorry i can't share the code because of corporate restrictions.  Right now I'm looking at the possibility of checking the filter model against any fields.hide=true and change that to false if the new model has a value for that field but it's a bit of a hassel to search all the leafs of our filtermodel for values.   i guess it might be the only way right now

**Comment by aitboudad** [comment]
Still not clear to me and without a minimal reproduction it even hard to provide some guidance, sorry 🙏!
