### ISSUE TITLE
hideExpression hide item does not work

### ISSUE THREAD

**Issue by juanmafcuesta** [ngx-formly/ngx-formly#2406]
**Question**

I am working on angular with ngx-formly for creating dynamic forms. I have a problem when returning the expression "hideExpression" from the backend, it gives me the following error:

Unexpected token ':'
at Function (<anonymous>)
    at evalStringExpression (ngx-formly-core.js:2301)
    at FieldExpressionExtension._evalExpression (ngx-formly-core.js:2468)
    at FieldExpressionExtension.onPopulate (ngx-formly-core.js:2438)
    at ngx-formly-core.js:710
    at Array.forEach (<anonymous>)

I am currently retrieving the form, saving it, and even editing it. Without the expression "hideExpression" it shows me the form correctly.

thank you!!!

**Comment by aitboudad** [comment]
probably passed expression is not valid, could you please show me the used `hideExpression` value.

**Comment by juanmafcuesta** [comment]
Hello @aitboudad, thanks for answering!!!.

In the backend the value I have is the following:

`      <column name="esquema">
        <![CDATA[ [{ "template": "<div class='informacion'><p>A efectos de este formulario se consideran intervenciones o pruebas los trabajos concretos que requieran la <strong>concurrencia directa del ser humano</strong> sujeto de la experiementación bien porque se vaya a obtener de él las muestras biológicas (de forma invasiva o no) o datos de carácter personal o tenga que realizar algún test, encuesta, ejercicio, etc.. </p></div>" },{"key": "intervencionesSeresHumanosRadio", "type": "radio", "templateOptions": {"label": "¿En esta actividad se realizan intervenciones o pruebas en seres humanos?", "placeholder": "", "description": "", "options": [{ "value": "1", "label": "No" },{ "value": "2", "label": "Sí" }]}}, {"key": "intervencionesSeresHumanosCheck", "type": "multicheckbox", "hideExpression": "(model: any) => { if (this.model.intervencionesSeresHumanosRadio === 2) {return false;} return true;}", "templateOptions": {"label": "Elegir opciones:", "options": [{ "value": "entrevistasEncuestas", "label": "Entrevistas, encuestas, cuestionarios, etc."},{ "value": "obtencionImagenes", "label": "Obtencion de imágenes, sonido o similares (fotos, vídeos, grabaciones, RX, ECO, ect)" }, { "value": "pruebasFisicas", "label": "Pruebas físicas" }, { "value": "pruebasPsiquicas", "label": "Pruebas psíquicas" }, { "value": "otras", "label": "Otras. Especificar" }]}}, {"key": "otrasTexto", "className": "descripcion", "type": "textarea", "templateOptions": { "rows": "3", "placeholder": "Especificar" } }] ]]>
      </column>`

Where you are giving me the error is in the following:
`"hideExpression": "(model: any) => { if (this.model.intervencionesSeresHumanosRadio === 2) {return false;} return true;}"`

Thank you!! :+1:

**Comment by aitboudad** [comment]
try with:

```ts
"hideExpression": "model.intervencionesSeresHumanosRadio === 2 ? false : true"
```

**Comment by juanmafcuesta** [comment]
This solution had come to remove the error in console but the problem is that it does not show the checkbox "HumanHealthCheck interventions". Only when I hit "YES" should these options be shown and always showing them to me. 

I do not know if it is a bug, if you need more information on how I have developed this, do not hesitate to ask me! But the problem comes with the 'hideExpression'

Thanks :) :)

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

**Comment by juanmafcuesta** [comment]
I attach an image:

[Image](https://ibb.co/48Sq6ht)
[Image2](https://ibb.co/QFKzz5j)

The image does not recognize the hideExpression, when clicking on an option it does not enter the expression

I have followed the steps of task [704](https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614) and none of the steps have worked correctly for me.

I have tried to do a function out, a change ... but with no expected result.


What am I doing wrong? Thankss!! :+1:

**Comment by aitboudad** [comment]
Could you please provide a simple reproduction example using our `stackblitz`?
Thanks!
