### ISSUE TITLE
Datepicker is not pre-populated with default date in production Build.

### ISSUE THREAD

**Issue by bejgumshirisha** [ngx-formly/ngx-formly#2407]
**When I run Angular application it is showing date with default value loaded.But I generate it with production build the it is not prepopulating with the defaultdate**

Please find the stackblitz code I tried.

https://stackblitz.com/edit/angular-bpz8qg?file=src/app/app.component.ts.

Please let me know if am missing any configuration.
Thanks

**Comment by aitboudad** [comment]
Hi, could you please let me know how to reproduce the issue.
Thank you!

**Comment by bejgumshirisha** [comment]
> Hi, could you please let me know how to reproduce the issue.
> Thank you!

When I am generating a dist folder using ng build --prod and after uploading it to s3 bucket there datepicker is not prepoulating with the default date.

**Comment by aitboudad** [comment]
Test on my side and it seems work as expected https://deploy-preview-2412--formly-dev.netlify.app/ui/material

**Comment by bejgumshirisha** [comment]
> Tested on my side and it seems work as expected https://deploy-preview-2412--formly-dev.netlify.app/ui/material

Thanks @aitboudad .

It is working after replacing it with FormlyMatDatepickerModule.Initially I used to do with datepicker custom component.
But after replacing it with FormlyMatDatepickerModule (Default datepicker type) Angular material css effects are not reflectin after adding datepicker module. 
Any idea about the issue Please.

Angular version : 9.2.4

**Comment by aitboudad** [comment]
> Any idea about the issue Please.

sorry I have not idea!
