### ISSUE TITLE
Cannot set selected values from Material select from API model

### ISSUE THREAD

**Issue by xapr170** [ngx-formly/ngx-formly#2408]
Fist of all I would like to say Formly is awesome!

I am trying to load multiselect options and then setting the ones that where previously saved from the user for editing but cannot load it using JSON powered example.

Please see  example:
https://stackblitz.com/edit/angular-a1v7ww?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
The select expect a scalar value and not object in case you want to pass an object use `compareWith` https://github.com/ngx-formly/ngx-formly/issues/2272#issuecomment-633296703

**Comment by xapr170** [comment]
seems like is working but the select dissapeared.
https://stackblitz.com/edit/angular-a1v7ww?file=src%2Fassets%2Fjson-powered%2Finvoice-form.json

**Comment by xapr170** [comment]
> The select expect a scalar value and not object in case you want to pass an object use `compareWith` [#2272 (comment)](https://github.com/ngx-formly/ngx-formly/issues/2272#issuecomment-633296703)

I cant seem to make it work with material multiselect

**Comment by aitboudad** [comment]
> seems like is working but the select dissapeared.

`valueProp` and `compareWith` expect a function and not string value, to make it work for loaded json config check https://formly.dev/examples/other/json-powered


> I cant seem to make it work with material multiselect

https://stackblitz.com/edit/angular-kpharh
