### ISSUE TITLE
Repeating Section check all values in section

### ISSUE THREAD

**Issue by CharlesDeJager** [ngx-formly/ngx-formly#2409]
**Question**

I would like to understand how I can manage repeating sections to check all the values in the section.  This example [https://stackblitz.com/edit/ngx-formly-repeating](https://stackblitz.com/edit/ngx-formly-repeating) contains a repeating section with three fields:

1. Email Type (select field with 4 options)
2. Email (input for the email)
3. Default (checkbox to indicate the default email)

I would like to be able to do the following:

1. Allow for only 1 default email address
2. Remove options / Add options to the email type based on what has already been selected

How can I go about achieving this?

**Comment by CharlesDeJager** [comment]
I have created an example of what I am after using a standard ReactiveForm.  [https://stackblitz.com/edit/ng-repeat-example](https://stackblitz.com/edit/ng-repeat-example)

Would like to be able to do this using Formly.

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/ngx-formly-repeating-vtb9qp
