### ISSUE TITLE
How to preselect a Radio Button List with a defaultValue  when its model is an object?

### ISSUE THREAD

**Issue by cibinthomasjacob** [ngx-formly/ngx-formly#2410]
How to preselect a Radio Button List with a defaultValue  when its model is an object?

I am having a radio button and select box for which I need the model to be object. I am using valueProp & compareWith . The select works fine and defaults to the option I pass inside model , but the radio button would not show the option as selected eventhough the model has the passed value . Please help.
 
Example with behavior : https://stackblitz.com/edit/ngx-formly-ui-material-bwre25

**Comment by aitboudad** [comment]
not supported https://github.com/angular/components/issues/10495

**Comment by Mohammed-Asad-Raza** [comment]
> not supported [angular/components#10495](https://github.com/angular/components/issues/10495)

Does this supports now in the formly angular version 6.1.8?
