### ISSUE TITLE
Formly + antdesign + Grid System

### ISSUE THREAD

**Issue by juniorpaiva95** [ngx-formly/ngx-formly#2411]
**Question**

I am using formly with the theme of ant design and I would like to know if the library supports the form construction with grid system.
I didn't see any feature that would allow me to use the grid system.

It is possible?

**Comment by aitboudad** [comment]
This can be done on your side by using a grid type, check the `@angular/flex-layout` integration to have an idea https://stackblitz.com/edit/ngx-formly-flex-layout
