### ISSUE TITLE
How to get a fields original config on click

### ISSUE THREAD

**Issue by blitzmann** [ngx-formly/ngx-formly#2414]
**Question**

(v5.9.3)

I'm attempting to build a kind of WYSIWYG editor, where the end user can configure the form how they want. The idea would be that, in edit mode, they can click on a field to bring up the edit window, do their changes, save it back, and regenerate the form.

So with that out there, I have a couple of questions:
* I'm noticing that I can set a click event on the fields using `templateOptions.click`. This returns the processed field config. Is there any way to get the original?
    * To the above point, ofc we have the original object because. we generated the form with it. But we would have to search it. If there's no way to get to the original config, is there some sort of property that identifies it's path in the original? `_keyPath` doesn't seem to do this (I can have multiple fields with the same `key`, so I don't have a way of using that to identify the form, and this doesn't seem to go more than 1 level deep even if I have fields in nested groups?)
* Is there a way to apply this click event enmasse on all fields on the form without having to loop through and apply it before generating the form? 

I'm continuing to dig through the source and look to see if there's anything that can help me in this situation, will update if I find anything.

Thanks for this awesome projects!

**Comment by aitboudad** [comment]
> I'm noticing that I can set a click event on the fields using templateOptions.click. This returns the processed field config. Is there any way to get the original?

the click event emit the field through its argument

> Is there a way to apply this click event enmasse on all fields on the form without having to loop through and apply it before generating the form?

yes, use custom extension see https://formly.dev/examples/advanced/i18n-alternative
