### ISSUE TITLE
Custom type dont work in oneOf json schema

### ISSUE THREAD

**Issue by capital-d** [ngx-formly/ngx-formly#2417]
**Question**

Hi, got several issues, not sure but seems connected to each other, will start from simple as i don't know is it intended behavior.

Had array of oneOf items and want to use custom type 'file' instead of object, got error:
https://stackblitz.com/edit/angular-psq6ct?file=src%2Fassets%2Fjson-schema%2FcustomOneOf.json

Work if object is directly in 'properties':
https://stackblitz.com/edit/angular-psq6ct?file=src%2Fassets%2Fjson-schema%2Fcustom.json

In final i want to put $ref with custom type in array of oneOf items.

Thanks in advance.

**Comment by aitboudad** [comment]
pass type as `object` and in widget use `file`:

```json
{
  "type": "object",
  "oneOf": [
    {
      "title": "Top image",
      "type": "object",
      "properties": { ... },
      "widget": {
        "formlyConfig": {
          "type": "file"
        }
      }
    },
  ]
}
```

**Comment by capital-d** [comment]
Thank you for response.

I did it, but formly rendered standard fields (text inputs) for this object.
Here is my try https://stackblitz.com/edit/angular-psq6ct?file=src%2Fassets%2Fjson-schema%2Fcustom.json
Fell free to edit it.

@aitboudad can you point what i doing wrong?
Thank you!

**Comment by aitboudad** [comment]
```patch
"widget": {
  "formlyConfig": {
+   "type": "file"
-   "templateOptions": {
-     "type": "file"
-   }
  }
}
```

**Comment by capital-d** [comment]
Great, thank you, it's work.
