### ISSUE TITLE
FieldIdInjector extension not working with aot compilation

### ISSUE THREAD

**Issue by AoNoOokami** [ngx-formly/ngx-formly#2418]
**Description**
Using the suggested extension (https://github.com/ngx-formly/ngx-formly/issues/1150#issuecomment-416239430) to create custom id for formly fields is not working with aot compilation.

**Minimal Reproduction**
Clone the project https://github.com/AoNoOokami/editor-custom-id and install dependencies.
Launch the app with `ng serve` -> custom id is working fine.
Launch the app with `ng serve --aot` -> custom id is not used.

**Your Environment**

* "@angular/core": "~8.2.9"
* "@ngx-formly/core": "^5.9.3"

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1624#issuecomment-502771903
