### ISSUE TITLE
How to extend FormlyForm Component.

### ISSUE THREAD

**Issue by juniorpaiva95** [ngx-formly/ngx-formly#2419]
Is it possible in some way to extend the **FormlyForm component**?

Suppose I want to pass a new property to the form, or do any other type of operation such as changing the form template and adding an h1 at the end (Just an idea that comes to mind now) or even changing the selector . It's possible ?

**Comment by aitboudad** [comment]
Possible but instead of extending the `FormlyForm` (you may rely on internal API) I suggest wrapping `formly-form` component inside another component where you can use another selector/add extra content.
