### ISSUE TITLE
Model not populated in array oneOf

### ISSUE THREAD

**Issue by capital-d** [ngx-formly/ngx-formly#2420]
**Question**

Hi data not shown in array oneOf items in json schema.

Created test https://stackblitz.com/edit/angular-psq6ct?file=src%2Fassets%2Fjson-schema%2FarrayOneOfList.json
( please see 'arrayOneOfList' tab in this project )

Thank you.

**Comment by aitboudad** [comment]
Hi, the fix is now included in the dev version `5.10.0-dev.ad26817d` which you may use until the stable release `5.10.0` is available (scheduled for Saturday).

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by capital-d** [comment]
Hi, @aitboudad thank you for your hard work!
Tried 5.10.0-dev.ad26817d and indeed forms populated right, but output from formly in my opinion is not what expected.

Waited release to [recreate on stackblitz](https://stackblitz.com/edit/angular-psq6ct?file=src%2Fassets%2Fjson-schema%2FcustomRef.json)

If i submit without changes in form i got:
```
"content":[
  {"string":"<span>Room:</span> 36 м²"},
  {"entries":["4","4"]}
]
```
objects missing my custom 'type' property.

And if i add new object to array:
```
"content":[
  {"string":"<span>Room:</span> 36 м²","type":"text","entries":[]},
  {"entries":["4","4"],"type":"text"},
  {"string":"t43"}
]
```
issues:
'type' property is added to objects exept last.
'type' property is not right in second object.
'entries' property added to first object.

Please let me know does this behavior is expected, and i'm using oneOf array in wrong manner? Or i should create a separate issue for this.

Thank you in advance!

**Comment by aitboudad** [comment]
the default value is not applied when field is marked as `hide`, remove type in case you don't want to display those fields:

```patch
{
- "type": "string",
  "readOnly": true,
  "default": "list-numeral",
  "const": "list-numeral",
- "widget": {
-   "formlyConfig": {
-     "hideExpression": "true"
-   }
- }
}
```

**Comment by capital-d** [comment]
Hi, @aitboudad thank you, yes without "type": "string" works.

But still got 'entries' property added to 'my- text' object after i add new item to array.

Reproduce issue: https://stackblitz.com/edit/angular-psq6ct?file=src%2Fassets%2Fjson-schema%2FcustomRef.json

Steps:
1. Add new item to Main content array in formly.
2. Hit submit.

Output from formly (partly):
```
"content":[
  {"type":"my-text","string":"<span>Room:</span> 36 м²","array":[],"entries":[]},
  {"type":"my-number","data":445,"array":[],"entries":[]},
  {"type":"my-text","string":"r"}
]
```

Got additional properties 'array', 'entries' from other types, that not presented in "type":"my-text".

Thank you in advance!

**Comment by aitboudad** [comment]
Tested with the latest version of Formly `5.10.1` and it seems working as expected so update your deps and make sure to enable `resetFieldOnHide` feature:

```patch
    FormlyModule.forRoot({
+      extras: {
+        resetFieldOnHide: true,
+      },
    }),
```

**Comment by capital-d** [comment]
Indeed 5.10.1 - work perfect, thank you for help!
Maybe messed release number in test.
