### ISSUE TITLE
FormlyFieldConfig.key allows string[] - breaking material stepper solution

### ISSUE THREAD

**Issue by freon27** [ngx-formly/ngx-formly#2421]
Hi 🙂 

It seems that the signature for `key` in `FormlyFieldConfig` was update  to also allow `string[]` (RE https://github.com/ngx-formly/ngx-formly/issues/2344).  

We had followed advice and this [stackblitz](https://stackblitz.com/edit/angular-yu7bzv-jrxppa?file=src%2Fapp%2Fstepper.type.ts ) to implement a wizard in a material-stepper. The key is used to add  the FormControls to the object, but `string[]` can't be used as an index type.

What would be the best way for us to resolve this? I read through the issue that the change was made for but I didn't totally understand how the array is designed to be used so it's not clear to me what the most generic solution would be.

Thanks in advance.

**Comment by aitboudad** [comment]
Hi, it doesn't break the material stepper unless you're using `string[]` for key, in that case, change the following form assign:

```patch
- form[f.key] = f.formControl;
+ form[Array.isArray(f.key) ? f.key[0]: f.key] = f.formControl;
```

**Comment by freon27** [comment]
Great, thanks :)
