### ISSUE TITLE
Nested form fields values are not reflected on submit

### ISSUE THREAD

**Issue by suraj740** [ngx-formly/ngx-formly#2423]
Hi, I am using ngx-formly. in my project to create dynamic tab based forms.

i have a similar model like below: 

```
model = {
    areas_data: [{
            "area_id": "someuuid",
            "description": "ewrwr",
            "nested": [
                {
                  "name":  'rerw',
                  "desc": 'ewe'
                }
            ]
    }]
  };
```

I have created form field structure using tabs and repeat example from demo.
Here is stackblitz demo for the same [Demo](https://stackblitz.com/edit/angular-v7rvwf?file=src%2Fapp%2Fapp.component.ts)

I got one issue here whenever i try to open a nested element in other tab , **the nested elements field values are not reflected on submit.**

To reproduce issue:

Just click on `Nested Button` 
Then in nested tab model fields are not populating by default.
@aitboudad please help me , how can i achieve this?
Any suggestions, what i am doing wrong here?

Thanks!!

**Comment by aitboudad** [comment]
>  the nested elements field values are not reflected on submit.

the model does not match the passed formly schema:

```patch
    areas_data: [{
      "area_id": "someuuid",
      "description": "ewrwr",
-     "nested": [
-       {
-         "name": 'rerw',
-         "desc": 'ewe'
-       }
-     ]
+     "nested": {
+       "name": 'rerw',
+       "desc": 'ewe'
+     }
    }]
```

**Comment by suraj740** [comment]
Sorry if i misguided you, but model was correct , i want the `nested` as array
