### ISSUE TITLE
Bind Property not working

### ISSUE THREAD

**Issue by ViniciusAlberkovics** [ngx-formly/ngx-formly#2424]
When updating the value of some information in the model, the value in the component and on the screen is not updated.

Sample: https://stackblitz.com/edit/ngx-formly-ui-material-rpwjuc

import { Component } from '@angular/core';
import {FormGroup} from '@angular/forms';
import {FormlyFieldConfig} from '@ngx-formly/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
})
export class AppComponent {
  form = new FormGroup({});
  model = {
    input: "Initial Value"
  };
  constructor(){
    setTimeout(() => {
      alert('updating model');
      this.model.input = "NewValue"
    }, 2000)
  }
  fields: FormlyFieldConfig[] = [
    {
      key: 'input',
      type: 'input',
      templateOptions: {
        label: 'Input',
        placeholder: 'Input placeholder',
        required: true,
      }
    }
  ];

  onSubmit() {
    if (this.form.valid) {
      alert(JSON.stringify(this.model, null, 2));
    }
  }
}

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/975#issuecomment-394647380
