### ISSUE TITLE
Is it possible to render a custom template in property template?

### ISSUE THREAD

**Issue by juniorpaiva95** [ngx-formly/ngx-formly#2427]
Real case situation, I have a product form array in which you receive a group form that contains fields such as unit value and quantity, and within that group form I would like to render a customized template that contains the calculation of the product value x quantity.

I checked in the documentation that the option * template * only receives one * string *, my idea was to try to use the template to pass an elementRef or a component.

**Comment by aitboudad** [comment]
not implemented yet https://github.com/ngx-formly/ngx-formly/issues/2086, you can achieve that by creating a custom field type.
