### ISSUE TITLE
oneOf model value impacted by an add array element action

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2429]
**Description**
A very strange behaviour: one element of the form (oneOf) is impacted by an array action.

**Minimal Reproduction**

Go to the following example which is a bar JSONSchema example with a modified oneOf JSONSchema.

https://stackblitz.com/edit/angular-qnzo2m?file=src%2Fassets%2Fjson-schema%2FoneOf.json

First, as the second entry has a default value the second option is selected by default, but this is not the main problem.
Steps:
1. select the option1 in the oneOf select => the model is empty OK!
2. add an new value in the values field (+ button) => the model contains a value of the option 2 of the oneOf while the option 1 did not change.

**Your Environment**

- Angular version: 7.2
- Formly version: 5.9.3

**Additional context**

**Comment by aitboudad** [comment]
fixed by #2426

**Comment by aitboudad** [comment]
> First, as the second entry has a default value the second option is selected by default, but this is not the main problem.

if I'm not wrong I think the first entry should be selected in that case :thinking:

**Comment by aitboudad** [comment]
> if I'm not wrong I think the first entry should be selected in that case :thinking:

it should be fixed by #2431

**Comment by aitboudad** [comment]
Hi, the fix is now included in the dev version `5.10.0-dev.ad26817d` which you may use until the stable release `5.10.0` is available (scheduled for Saturday).

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
