### ISSUE TITLE
Nested form fields values are not reflected on submit.

### ISSUE THREAD

**Issue by suraj740** [ngx-formly/ngx-formly#2432]
Thanks for your reply. Sorry if i misguided you, but model was correct , i want the `nested` as array.
I am doing something wrong in schema, can you please help?
How to  achieve the same ?

_Originally posted by @suraj740 in https://github.com/ngx-formly/ngx-formly/issues/2423#issuecomment-670074471_

**Comment by aitboudad** [comment]
I'm not sure what do you want to achieve, the easy way is to pass fieldArray to `nested` without using the button:

```ts
{
  "key": "nested",
  type: 'repeat',
  fieldArray: {
    fieldGroup: [
      { "key": "name" },
      ....
    ]
  }
}
```

In case you want to add a nested field for the current `areas_data` item https://stackblitz.com/edit/angular-v7rvwf-sf6oxt`

**Comment by suraj740** [comment]
Thanks 😍@aitboudad, `${field.parent.key}` this is what i wanted.
Thanks again for your help😊.
