### ISSUE TITLE
Re-evaluate default validators on field change

### ISSUE THREAD

**Issue by ashishjain85** [ngx-formly/ngx-formly#2434]
**Question**
Hello,

I have a small form where I have address fields. Field attributes like what is required and what is valid pattern depend on country selected. I am storing this info in form state and am using expression properties like this:

`
 'templateOptions.required': (model, formState, field) => {
       return !!formState.fieldsMetadata['state'].required
  },
'templateOptions.pattern': (model, formState, field) => {
    return formState.fieldsMetadata['postcode'].inputRegex
 },
`

The issue is that the built in validations of Angular are not getting cleared or re-evaluated and hence not getting cleared from the underlying FormControl whenever I am changing the country, therefore errors remain visible on screen.

I have checked in debugger and the expression property is getting re-evaluated but somehow the underlying form control is not getting updated.

The field label has got no * indicator after changing country(as it shouldn't based on the metadata for that country) but the required error message still getting displayed. Same for the pattern validation. 

Also, the validation messages are not getting re-evaluated on country field change. e.g. if a field has input pattern to enter only numbers then after changing country if the new pattern is to allow alphanumeric but it keeps on displaying the old message with old pattern.

Please help as it is super urgent and has taken a lot of time and I am almost out of options to try. I am using Formly material as well here.

A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
Hi, can you please provide a reproduction using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by ashishjain85** [comment]
Hello @aitboudad  please refer to https://stackblitz.com/edit/ngx-formly-ui-bootstrap-exbwb8

**Comment by ashishjain85** [comment]
I have tried https://github.com/ngx-formly/ngx-formly/issues/2220#issuecomment-622994535 but does not work

**Comment by ashishjain85** [comment]
Hello, found any time to look at this issue? Thanks.

**Comment by aitboudad** [comment]
Hi, I've checked the provided example and it seems working as expected, am I missing something?

**Comment by ashishjain85** [comment]
Notice the "Textarea" field. I am updating required validation on change of "Select" control. The * on Textarea control goes away but the validation message doesn't.

**Comment by ashishjain85** [comment]
Thanks for acknowledging the issue.

**Comment by aitboudad** [comment]
just remove `[required]="to.required"` and it should work somehow there is an issue in Angular, from Fromly side the required attr is handled by `formlyAttributes` directive.

**Note: you can rely on `form-field` which manages the validation message and field label.

```patch
    FormlyModule.forRoot({
      types: [
        {
          name: 'custom',
          component: FormlyFieldCustomInput,
+         wrappers: ['form-field']
        },
      ],
    }),
```

**Comment by ashishjain85** [comment]
Thanks for the answer @aitboudad really appreciate the help. I think the UI libraries need to be updated because they are using the same syntax [required]="to.required"

**Comment by aitboudad** [comment]
@ashishjain85 combining `switch` with `required` produce the issue which is not the case in our UI.
