### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by petros-greece** [ngx-formly/ngx-formly#2435]
**Description**

Line 172901

this

return isEmpty(value) || (value % schema.multipleOf === 0);

should be

return isEmpty(value) || (Math.floor(value\*100)%Math.floor( schema.multipleOf\*100) === 0);

in order to work with floating point numbers. In this example it works until two decimals.

**Comment by aitboudad** [comment]
Hi, the fix is now included in the dev version `5.10.0-dev.ad26817d` which you may use until the stable release `5.10.0` is available (scheduled for Saturday).

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
