### ISSUE TITLE
How can we repeat array inside array

### ISSUE THREAD

**Issue by suraj740** [ngx-formly/ngx-formly#2437]
Hi, i wanted model like below:
```
model = {
    investments: [
      [1,  3], // i need two input fields here
      [4, 5]
    ]
};
```
I tried many things , but didnt found any solution.
i got the example of array of objects in the document, but here i want array of arrays.

Here is the demo for the same, [demo](https://stackblitz.com/edit/repeat-section?file=src%2Fapp%2Fapp.component.ts)

Thanks!!

**Comment by ViniciusAlberkovics** [comment]
Try this

```
model = {
    investments: [
      [1,  3],
      [4, 5]
    ],
  };
  options: FormlyFormOptions = {};

  fields: FormlyFieldConfig[] = [
    {
      key: 'investments[0]',
      type: 'repeat',
      templateOptions: {
          addText: 'Add',
      },
      fieldArray: {
        type: 'input',
        key: 'investmentName',
        templateOptions: {
          label: '',
          required: true,
        },
      },
    },
  ];
```

**Comment by suraj740** [comment]
Thanks, but thats doesnt work , if we try to add fields again.

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/repeat-section-mmievk

**Comment by suraj740** [comment]
Great it worked. Thanks😊 🙏  @aitboudad .
