### ISSUE TITLE
How can I implement ngx-datatable row grouping with formly

### ISSUE THREAD

**Issue by Suraj786** [ngx-formly/ngx-formly#2438]
**How can I implement ngx-datatable row grouping & row details with ngx-formly**
I have tried implementing but not working properly. Can any one please help me out.

- ngx-datatable with row grouping and row details:-
https://stackblitz.com/edit/angular-ngx-datatable-row-grouping-and-row-detail

- ngx-datatable with ngx-formly:-
https://stackblitz.com/edit/angular-gknj8z-voa1yu

**Comment by aitboudad** [comment]
By just following their example, here is a working example with Formly
https://stackblitz.com/angular/ebjjxvrjyyj
