### ISSUE TITLE
Bootstrap validation styles lost in custom field

### ISSUE THREAD

**Issue by Thremulant** [ngx-formly/ngx-formly#2442]
Hi, I'm having a similar problem. The custom validation works as per this example:

https://github.com/ngx-formly/ngx-formly/issues/2264#issuecomment-632336990

But, I'm missing the Bootstrap styles in my custom fields. Even after adding the line: **wrappers: ['form-field']** to the field. 

I forked your StackBlitz and added that line, but the red border and the icon to the right are missing. https://stackblitz.com/edit/angular-masking-dynamics-5ek6u8?file=app%2Fapp.module.ts

Do you know if I'm missing something in the custom field? 

Thanks in advance,
Daniel.

**Comment by aitboudad** [comment]
check the input type for missing attrs https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/bootstrap/input/src/input.type.ts#L11-L13
