### ISSUE TITLE
Avoid empty prefix / suffix elements in Material form fields

### ISSUE THREAD

**Issue by fynnfeldpausch** [ngx-formly/ngx-formly#2443]
**Description**
The Material form field wrapper will always render prefix and suffix elements even if these are not provided via the template options.

**Minimal Reproduction**
This can be seen in the DOM on every example at https://formly.dev/ui/material

**Your Environment**
- Angular version: 9.1.2
- Formly version: 5.9.3

**Additional context**
This usually is not a problem, as they are collapsing to 0px width. However, we are using formly in as special setup and the prefix and suffix elements show up. Would be great to be able to use them and not go for custom ones. Furthermore, it would just be nice to avoid these unnecessary DOM elements.

**Comment by aitboudad** [comment]
Hi, the fix is now included in the dev version `5.10.0-dev.ad26817d` which you may use until the stable release `5.10.0` is available (scheduled for Saturday).

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
