### ISSUE TITLE
Changing the rendered field type based on model value

### ISSUE THREAD

**Issue by gadreash** [ngx-formly/ngx-formly#2445]
**Question**

I have a repeating group, rendered using a custom repeating component.
Now as is evident below I have a Basket = [{tag, value}] structure where the "repeatable" component lets me add or remove the instances as need be, for a blank form.

Now this form may be loaded with model containing predefined basket e.g., [{tag: 'red1', value: 'apples'}, {tag: 'orange1', value: 'oranges'}, ...]

How do I use the above model and change the rendered field for the tag for the above 2 instances to a simple template, instead of  "type": "autoComplete" , while allowing any newly added repeating instances to have the autocomplete/select as the type.
I have tried to use hooks, but onInit is still too late, because at that point the Form is already rendered. Really could use some help here. Also for those rendered repeated groups, is it possible to hide the "Remove" button as well?

Here's a [demo ](https://stackblitz.com/edit/ngx-formly-ui-material-f8gufe?file=src/app/app.component.ts)
```
[
   {
    "key": "Basket",
    "type": "repeatable",
    "templateOptions": {
      "addText": "Add a Tag-Value for the Basket",
      "removeText": "Remove Tag",
      "disableRemove": false
    },
    "fieldArray": {
      "fieldGroup": [
        {
          "key": "tag",
          "type": "autoComplete",
          "templateOptions": {
            "label": "RF Tag",
            "placeholder": "Enter/Select a RF TAG",
            "required": true
          },
        },
        {
          "key": "value",
          "type": "input",
          "templateOptions": {
            "label": "Enter the tag's value",
            "required": true
          }
        }
      ]
    }
  }
```

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/ngx-formly-ui-material-yisigv

**Comment by gadreash** [comment]
That's just perfect! That solution opened me up to a lot of possibilities!
My next challenge is to re-render a form with new formlyFieldConfigs based on which pre-defined basket a user selects from a drop-down. Let me know if you guys have some example for it, or i'll experiment my way through it! Thanks
