### ISSUE TITLE
Not able to edit "fieldGroup" within fields to change input element type "input" to "view" based on click of EDIT Button. 

### ISSUE THREAD

**Issue by nikitsatpute** [ngx-formly/ngx-formly#2446]
We have implemented form using ngx-formly and having custom JSON to show different elements on the page i.e. Text, Input Elements, Links, Button etc. Everything on the UI i.e Form elements has to be rendered using JSON which is provided to Formly.

Usecase : Initially Read Only Label as an element should show and then when user clicks on Edit Button then that label should be input box to change the data. Below is screenshot 

Before Edit
![image](https://user-images.githubusercontent.com/6504578/90047847-97ed2280-dca0-11ea-92c9-ae4570d04aff.png)

After Edit
![image](https://user-images.githubusercontent.com/6504578/90047873-a20f2100-dca0-11ea-9ecc-cf84e9673987.png)

We have created below app which have Panel Wrapper to show input elements and we have created custom view-component.
Form is managed/rendered using custom JSON [assets/appCycleForm.json]
 
**https://stackblitz.com/edit/angular-ngxformly-input-view-mod?file=app/panel-wrapper.component.ts** 

Questions : 
1. Is it possible to change the field group from one type to another i.e. in this case from view to edit type so that respective selectors will be show on the fly on click of edit button.
2. If yes, how this can be achieved?
3. Is it possible to update JSON on the fly and update fields provided to Formly?

**Comment by aitboudad** [comment]
> Is it possible to change the field group from one type to another i.e. in this case from view to edit type so that respective selectors will be show on the fly on click of edit button.

yes, but you should re-assign the edited value to the fields in order to trigger the change detection
https://stackblitz.com/edit/angular-ngxformly-input-view-mod-1rgzxw?file=app/app.component.ts
