### ISSUE TITLE
In Formly, what all attributes can be updated on the fly? Is there any restrictictions to manipulate fields JSON

### ISSUE THREAD

**Issue by nikitsatpute** [ngx-formly/ngx-formly#2447]
Is it possible to update all the attributes of the FormlyFieldGroup i.e. JSON on the fly based on any action of any link or button.
e.x. In below JSON fieldGroup type needs to be updated from Input to View or simililarly like that.

{
    "data":[
    {
      "key": "appModeCycle.address",
      "type": "panel",
      "templateOptions": { 
        "label": "Address",
        "actionButtons":
          [
            {
            "title" : "Approve",
            "bootstrapClass" : "primary",
            "enabled":"true"
            },
            {
              "title" : "Cancel",
              "bootstrapClass" : "secondary",
              "enabled":"true"
            },
            {
                "title" : "Edit",
                "bootstrapClass" : "secondary",
                "enabled":"true"
            }
          ]
        },
      "fieldGroup": [
          {
            "key": "town",
            "type": "input",
            "templateOptions": {
            "required": true,
            "label": "Town"
          
            }
          },
          {
            "key": "city",
            "type": "input",
            "templateOptions": {
            "required": true,
            "type": "text",
            "label": "City"
          }
    }
      ]
    }
    ]
}

**Comment by aitboudad** [comment]
The question is not clear enough, could you please elaborate more with an example or a use-case :pray:!
