### ISSUE TITLE
Material Datepicker  Clear input

### ISSUE THREAD

**Issue by ecarogonzale82** [ngx-formly/ngx-formly#2448]
I love Formly

**Question**
Is there any way to add clear button to material datepicker using toggle like this example? I am trying to disable input readonly.
https://stackblitz.com/edit/angular-mat-datepicker-clear-input?file=app%2Fdatepicker-overview-example.html

**Comment by aitboudad** [comment]
use https://formly.dev/examples/other/material-prefix-suffix
