### ISSUE TITLE
Custom components constructor is executed even if they shoudn't

### ISSUE THREAD

**Issue by zdenekhatak** [ngx-formly/ngx-formly#2449]
**Description**
Imagine you have custom components that render your fields. Every components constructor is executed together with registering HostListeners. The problem is, that when the component gets destroyed, these Listener are not destroyed (because of that extra run on the very beginning).

The same thing happens if e.g you have a formly wrapper that is not in the DOM (*ngIf="false") but formly creates those components anyway.

Not sure if this is a duplicate of https://github.com/ngx-formly/ngx-formly/issues/2285

**Minimal Reproduction**
See the stackblitz - open up the console and you will see **twice** `input constructor` outputs whereas there should be only one. Then click the `toggle` button and try to resize the window. The resize listener is never destroyed because with the first run there was no ngOnDestroy called - that **creates memory leakes**. 

https://stackblitz.com/edit/angular-ivy-91shfx?file=src%2Fapp%2Finput-formly.component.ts

**Your Environment**

- Angular version: 10.0.1
- Formly version: 5.9.3

**Comment by aitboudad** [comment]
related to #2285 as mentioned above and for a workaround we may destroy them when FormlyForm is destroyed.

**Comment by zdenekhatak** [comment]
How would I achieve that in the example I mentioned?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by ibsus** [comment]
Thank you for the fix. Unfortunately ngOnDestroy on the custom component is now called before ngOnInit, breaking the angular event flow.

https://angular-ivy-3wiavn.stackblitz.io

**Comment by aitboudad** [comment]
That's not the case, the custom component is created twice so the first instance is destroyed after constructor call (without `ngOnInit` call), and the second instance which is then rendered follow the normal flow.

To my understanding, there are some cases where a component is destroyed before `ngOnInit` call (router for example).

**Comment by ibsus** [comment]
I have to admit you are right! (https://www.bennadel.com/blog/3356-ngoninit-may-not-get-called-before-ngondestroy-is-called-in-angular-4-4-6.htm). I did not realize.

Thank you for the quick response
