### ISSUE TITLE
Functions in string form not evaluated correctly in expressionProperties

### ISSUE THREAD

**Issue by timhuang77** [ngx-formly/ngx-formly#2450]
**Question**
I'm looking to provide functions (as strings to be evaluated) in order to set expressionProperties, but it doesn't appear to be working as intended.

**Minimal Reproduction**
I forked one of the expressionProperties examples to pass a function in a string. But it doesn't seem to be working for me:
https://stackblitz.com/edit/angular-r6rkhf

I'm essentially trying to pass a function / lambda as an expression to be evaluated. In this example...

```typescript
{
      key: 'text2',
      type: 'input',
      templateOptions: {
        label: 'Hey!',
        placeholder: 'This one is disabled if there is no text in the other input',
      },
      expressionProperties: {
        'templateOptions.disabled': '((model) => { if (model.text == null) { return true } else { return false } })',
      },
    }
```

I'm attempting to set the `text2` field as **disabled** `templateOptions.disabled = true` when `text` field is null or empty.

**Motivation / Goal**
We use ngx-formly to build highly configurable form UI's. All of our forms are stored in database and referenced on demand and all the form are in JSON string forms.

Based on our current experience, I know that the short conditional (ternary) expressions can be used in expressionProperties, even in string form, is working fine for us.

I referenced the ngx-formly source, it appears that under the hood, the method evalStringExpression is used for evaluating these expressions in string form (extensions/field-expression/utils.ts ). **Therefore, TS lambda functions should work just fine in a string?**

The end-goal in my project is to be able to dynamically set the underlying model value, such as the following:

```typescript
{
      key: 'text2',
      type: 'input',
      templateOptions: {
        label: 'Hey!',
        placeholder: 'This one is disabled if there is no text in the other input',
      },
      expressionProperties: {
        'templateOptions.disabled': '((model) => { if (model.text == null) { return true } else { return false } })',
        'model.text2': '((model) => { if (model.text == null) { return 'text1 is empty'} else { return model.text2 } })',
      },
    }
```
..where the 2nd input-field is disabled conditionally based on the first field, and the 2nd input-field's value is also conditionally set.

**Your Environment**
- Angular version: 8.2.14
- Formly version: 5.7.2

Thank you!

**Comment by aitboudad** [comment]
we only evaluate the body of function for string expression, you may try with:

```ts
'templateOptions.disabled': 'model.text === null ? true: false'
```

**Comment by timhuang77** [comment]
Yes, we currently use conditional ternary expressions. But we're looking to add more complexity to these interactions e.g.

```typescript
if (condition_A) {
  return X;
} else if (condition_B) {
  return Y;
} else {
  return Z;
}
```

Would it be possible to evaluate this? I think the method evalStringExpression() does a return of the expression like the following
```javascript
 Function(...argNames.concat(`return ${expression};`));
```

Perhaps I would be able to reference a Function that is stored elsewhere?
e.g.
``` JSON
templateOptions.disabled': 'this.formlyCheckIfDisabled(model.text)'
```

**Comment by timhuang77** [comment]
Hi @aitboudad ,

It turns out because only the body of the functions are executed (expressions) in `evalStringExpressions()`, we could simply return an **immediately-invoked function** or **immediately-invoked lambda** since it needs a function to executed right-away.

**That being said, however, I'm still curious what the scope of `expressionProperties` is, and whether we could reference methods outside of the formly config, instead of storing all the methods inside the config string, which we are doing now.**

**Comment by aitboudad** [comment]
Our aims are to be able to evaluate a simple expression but for more advanced expressions I think it javascript is required here by post-processing the loaded `fields`.

Right now there are two ways:
- use map function which you may check in https://formly.dev/examples/other/json-powered
- use custom extension which is a global way to adjust Formly field https://formly.dev/examples/advanced/i18n-alternative

**Comment by hobojoe** [comment]
> Hi @aitboudad ,
> 
> It turns out because only the body of the functions are executed (expressions) in `evalStringExpressions()`, we could simply return an **immediately-invoked function** or **immediately-invoked lambda** since it needs a function to executed right-away.
> 
> _So I'm able to get string functions working for ngx-formly in this manner._
> 
> **That being said, however, I'm still curious what the scope of `expressionProperties` is, and whether we could reference methods outside of the formly config, instead of storing all the methods inside the config string, which we are doing now.**

Hi @tyh77 , did you manage to get it working? I would like to achieve the same behavior as you!

**Comment by tyh77** [comment]
It's been a while since I've done this but if I recall correctly, you can pass in the string expression and append `()` to evaluate it. But based on aitboudad's explanation, this may not be officially supported behavior. YMMV

**Comment by hobojoe** [comment]
> It's been a while since I've done this but if I recall correctly, you can pass in the string expression and append `()` to the string to ensure it is evaluated. But based on aitboudad's explanation, this may not be officially supported behavior. YMMV

@tyh77 Thanks for the reply!

Not sure I understood what you meant by appending '()'. Should it be done when I get the json from the database or should the string have it already?

Could you please provide an example?

Thank you very much for you help!

**Comment by tyh77** [comment]
@hobojoe yes I believe the string should have the eval symbol `()` to get it to evaluate immediately when `evalStringExpressions()` is invoked.

You may need to experiment with this a little bit as I don't have an example on hand to show.
