### ISSUE TITLE
Expression has changed after it was checked after update to Angular 10

### ISSUE THREAD

**Issue by matthias-dev** [ngx-formly/ngx-formly#2451]
I want to disable a datepicker field depending on a global state. I have an observable representing that state and bind this observable to the readonly templateoption of the datepicker. After upgrading to angular 10 this throws a ExpressionChangedAfterItHasBeenCheckedError.
Is there a better way to disable a datepicker input and button?

https://stackblitz.com/edit/angular-yfv7tq

**Comment by gethari** [comment]
@matthias-dev You can fix that by calling `changeDetector` manually `afterViewInit`

```
 constructor(private _cd:ChangeDetectorRef){}
  ngAfterViewInit() {
    this.readonlyDate.next(true);
    this._cd.detectChanges();
  }
```

**Comment by matthias-dev** [comment]
Perfect, thanks! This works for me.
