### ISSUE TITLE
Binding select to observable not compatible with json-schema

### ISSUE THREAD

**Issue by przemyslaw-k** [ngx-formly/ngx-formly#2452]
https://stackblitz.com/edit/angular-smgm5p-eeskvk?file=src/app/app.component.ts

labels appear in select from items that are not selected e.g :

Reproduction steps:

1. add first item
2. add second item
3. choose first item
4. delete first item

label from select should be removed after deletion of first item but label from second item is used although there is still first item value in the model

**Comment by aitboudad** [comment]
You should handle that case on your side https://stackblitz.com/edit/angular-smgm5p-pyvadu
