### ISSUE TITLE
Is it possible to integrate this with ngrx-forms?

### ISSUE THREAD

**Issue by joncorrin** [ngx-formly/ngx-formly#2454]
**Question**
I would love to use ngx-formly and ngrx-forms together. I know you can implement ngrx separately but this library ngrx-forms does a good job at removing a lot of boiler plate code for ngrx on forms. Is it possible to use ngrx-forms state/form control in place of the normal FormControl on ngx-formly?
https://ngrx-forms.readthedocs.io/en/master/user-guide/

A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
It may be possible but I may need to find some spare time to play with `ngrx-forms`!

**Comment by joncorrin** [comment]
Is there anything I can do on my side to test this?

**Comment by aitboudad** [comment]
Right now, I have no idea :pray:!

**Comment by joncorrin** [comment]
Thanks! Really quick non-sequitur. Is there a pre-built form builder library out there for this awesome forms library?

**Comment by aitboudad** [comment]
https://github.com/franzeal/ngx-formly-designer

**Comment by aitboudad** [comment]
The integration is somehow not as easy as I was thinking, so I'm going to close this issue as resolved.
