### ISSUE TITLE
passing 'type' property is not allowed when 'template' is set.

### ISSUE THREAD

**Issue by bejgumshirisha** [ngx-formly/ngx-formly#2455]
**Question**
Hi I am using canvas as custom component in the application.
I get Forms JSON from Spring Boot Service API's. When I try to load a JSON which contains canvas type then I can able to see some below mentioned warning messges.

**NgxFormly: passing 'type' property is not allowed when 'template' is set.**

I am unable to trace what is cause of Issue.

**Comment by aitboudad** [comment]
its a deprecation warning when using `template` in your field config you should not pass the `type` property:

- `{ template: 'foo', ... }` ✔️
- `{ type: 'input', ... }` ✔️
- `{ type: 'input', template: 'foo' }` ❌

**Comment by bejgumshirisha** [comment]
@aitboudad  Please find the stackblitz url to reproduce it.

https://stackblitz.com/edit/angular-j3rc3n?file=src%2Fapp%2Fapp.component.ts

I removed template value from JSON and  also while adding actions and events also. By at that time am getting context error.

Please comment out the canvas bypass code from addEvents() function and check it.

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-j3rc3n-wpzk7y

```patch
<canvas
-  [id]="field.name"
+  [id]="field.id"
></canvas>
```
