### ISSUE TITLE
Formly-Material Date-picker disable future dates 

### ISSUE THREAD

**Issue by h-arora** [ngx-formly/ngx-formly#2456]
**Is your feature request related to a problem? Please describe.**
While rendering a form using a JSON file it is not straightforward to disable future dates due to the dynamic nature you will have to process the config to pass in today's date

**Describe the solution you'd like**
It will. be great if the future dates can be disabled by passing a flag in the datepickerOptions like so:
    `datepickerOptions: {
        "disableFutureDates": true
    }`

**Describe alternatives you've considered**
using `max` right now but will have to process the JSON config

**Comment by aitboudad** [comment]
You can introduce that option by using the custom extension, check the following example https://formly.dev/examples/advanced/i18n-alternative to know how to create your own extension:

```ts
export class DatepickerExtension {
  prePopulate(field: FormlyFieldConfig) {
    if (field.type === 'datepicker' && disableFutureDatesEnabled) {
      // set max property
    }
  }
}

```
