### ISSUE TITLE
Is there a side effect if I remove the formlySelectOptions from the select component?

### ISSUE THREAD

**Issue by luizfbicalho** [ngx-formly/ngx-formly#2457]
**Question**

I'm using the kendo select and multiselect, but I want the select to store the complete object from the options observable, I have scenarios where I use other properties from the object, for example I have an object with Id, Description and Price, and when I select it should show the price in another field.

`<kendo-dropdownlist
      [class.k-state-invalid]="showError"
      [formControl]="formControl"
      [formlyAttributes]="field"
      [data]="to.options | async"
      [textField]="to.labelProp"
      [valueField]="to.ValueProp"
      [valuePrimitive]="to.primitive"
      (valueChange)="to.change && to.change(field, $event)"
    >
    </kendo-dropdownlist>`

What side effects should I expect by doing this?
I already use the kendo in other projects both to primitive and not primitive value, and I never had problem.

**Comment by aitboudad** [comment]
No side effects, it a helper that simplifies dealing with options in your template (an observable or an array of items) by transforming them into the following signature `Observable<ISelectOption[]>`.

```ts
interface ISelectOption {
  label: string;
  disabled?: boolean;
  value?: any;
  group?: ISelectOption[];
}
```

**Comment by luizfbicalho** [comment]
Thanks
