### ISSUE TITLE
Best practices on creating new Components

### ISSUE THREAD

**Issue by luizfbicalho** [ngx-formly/ngx-formly#2459]
**Question**

I'm trying to create components for kendo to use in formly.
My idea is to create some components, an to give more options, create more fields in the FormlyFieldConfig, obviously not change this class, but extend it, to do so, my question is if there is one Best practices tutorial to create components.

For example:
To create a component with more properties, folow these rules.

To create a form group component, folow these rules.

To create a Form Array component .....

To implement a wrapper to change layout of the component

And so on.

I think that this way would be easier for adoption and extension of formly.

**Comment by aitboudad** [comment]
Our best practices right now is by checking our [doc examples](https://formly.dev/examples/introduction) also, checking our UI source code https://github.com/ngx-formly/ngx-formly/tree/main/src/ui

PR welcomed to improve our docs :)
- https://formly.dev/guide/custom-formly-field
- https://formly.dev/guide/custom-formly-wrapper

**Comment by luizfbicalho** [comment]
One thing that I didn't find any case is extending the FormlyFieldConfig for some component, do you have an example of it?

**Comment by aitboudad** [comment]
if you're talking about extra options, it should be done through `templateOptions` and for `FieldType`:

```ts
interface CustomFieldConfig extends FormlyFieldConfig {
  ...
}

export class CustomFieldType extends FieldType<CustomFieldConfig> {}
```

**Comment by luizfbicalho** [comment]
Thanks, I'll try to implement some components here and show it to you, let's see if it's a good implementation for extensions
then you can use it for future references
