### ISSUE TITLE
Mixing Repeat, Multi-step and Wrapper

### ISSUE THREAD

**Issue by joncorrin** [ngx-formly/ngx-formly#2460]
**Question**

A clear and concise description of what the question is.

I've been trying to use formly to replace our current forms which are multi-step forms that show one questionGroup at a time which has a few fields per question (which are inputs, selects, etc.). Those questionGroups are also nested in sections.

```
Form = {
  id: 1,
  title: "Auto Form"
  sections: [
     {
        title: "Drivers",
        questionGroups: [  {header: "Can you tell us about the driver?", questions: [ { placeholder: "First Name", type: "input" }   ] } ]
     } 
  ]
}
```

Using formly - I found a mix of features that I would need in order to show one section, one questionGroup, and multiple questions at one time. This includes the Repeat Custom Type for repeating objects, Multi-step approach shown in the docs and the Wrapper feature so I can wrap each questionGroup with a header and some styling. 

I'm having a tough time putting it all together in the best way possible. Here is my stackblitz: 
https://stackblitz.com/edit/angular-s5v2qa?file=src%2Fapp%2Fapp.component.html

You'll see here I've implemented Repeat, Wrapper, and a loop that emulates the multi-step approach. The problems I'm having are: 

1. In your example of Repeat, it shows you calling a field directly and not field.fieldArray - I for some reason have to call field.fieldArray to get this to work.
2. When using the repeat field alongside the non-repeat fields, its making it tough to loop through and show the appropriate form. Im not sure if Im doing this right, but Im checking to see if field.type === 'repeat' and if so I am implementing slightly different logic. This could be because my initial object is setup incorrectly, does it look right to you?  
3. Im having trouble sending events from the repeat component back to the original app.component. I'd then ideally output that event to the parent component. Should I be using one of the FieldConfig properties to do this? 
4. I'm also having trouble with some of the nesting when it comes to repeat types. The form should only show one questionGroup at a time, regardless if its a repeat type or not, but in your example, the repetitive objects list multiple questions at once. How can I transform the repeat.html file so that adding a "Driver" would take me back to questionGroup 1 for Driver 2? 

Any advice would be extremely helpful! Each one of the features isolated isnt a problem for me but when I tried to mix them together to create a multi-step form that shows one question

**Comment by aitboudad** [comment]
Sorry, I don't have much time to check your example also the shared stackblitz is not working but here is a side note which may help you to simplify Multi-step approach shown in the docs https://stackblitz.com/edit/angular-yu7bzv-uucyxg.

**Comment by joncorrin** [comment]
Thank you! Do you have any examples of emitting events from a custom component back to the parent component? Ive tried adding @Output in the custom component with no luck. Im trying to do it on button click in the child component.

**Comment by joncorrin** [comment]
So I made great progress. I didn't realize that fieldGroup was populated upon adding an instance of something in the repeat component (Im assuming add() clones the fieldGroup from the fieldArray into the fieldGroup property). So I was able to get the repeat component to work. I also layered a few custom components called formType, sectionType and questionGroupType which helped clean up the looping a lot as you suggested in your example (thank you again!). This means 1, 2, and 4 are handled. The only trouble I'm having is handling events between the parent component and the formly component (child) (#3 above). We're using formly as a lib in an nx mono-repo so that we can show the form on the form builder preview and in the actual form view where users fill out forms. It looks something like this: 

```
// Our form app => apps/form/app-form.component.html
<section>
  <app-mono-form-viewer
    [form]="appForm"
  ></app-mono-form-viewer>
</section>
<div>
  <button>Next</button>
</div>

// app-mono-form-viewer => lib/formly/app-mono-form-viewer.component.html
<form [formGroup]="form" (ngSubmit)="submit()">
  <formly-form 
    [model]="model" 
    [fields]="fields" 
    [options]="options"
    [form]="form">
  </formly-form>
</form>
```

I've successfully made it so I can progress one questionGroup at a time using the buttons in the custom components (i.e. Next Question Group or Add Driver). Do you know off the top of your head how we'd get those events from the button clicks into the top parent component `app-form.component.ts`. We need to update some UI components in the parent level that only exist in the app-form component and not in the formly lib?

**Comment by joncorrin** [comment]
It looks like I could add this onClick event Im just wondering since Im nesting 2 - 3x how I can get the event to persist upward. 

```
    {
      type: 'button',
      templateOptions: {
        text: 'With Function',
        onClick: ($event) => alert('You clicked me!'),
      },
```

**Comment by aitboudad** [comment]
That depends on the use-case but here are some ways:

- emit an extra event the `field.options.fieldChanges`:

```ts
field.options.fieldChanges.next({
  field,
  type: 'app-mono-custom-event',
  value: hide,
})
```

- get the parent field through `parent` property, and trigger your event

```
this.field.parent...
```

- use `formState`

**Comment by joncorrin** [comment]
Thanks! I was able to figure it out. Just for anyone looking to attempt similar stuff, here's the solution I came up with mixing the user of `field.parent`  and events in `templateOptions`
