### ISSUE TITLE
How to use change event with autocomplete?

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2461]
**Question**

I am using autocomplete field, to populate the values. I have used templateOptions.change in expression properties to set value of other field, but i have noticed that change event is called only when the value of autocomplete is deselected. when i am trying to select the value from autocomplete change event is not called.

**Comment by aitboudad** [comment]
normally it should work but you may try this alternative way instead:

```ts
{
  hooks: {
    onInit: (field) => {
      return field.formControl.valueChanges
        .pipe(tap(value => console.warn(value))),
      ;
    }
  }
}
```

**Comment by chandelshashank** [comment]
@aitboudad 
I have created a stackblitz link to achieve my requirement, I am noticing that onchange event only calls after we change the value of autocomplete dropdown, and if it is blank and then we select any value it doesn't call the change event.
I want to know whether there is an option for onselect of dropdown rather than the change event.
I tried using the hooks code with the template option provided by you, but didn't work out, it will be helpful if you can assist on this.
Thank you

Please find this link: **https://stackblitz.com/edit/angular-bf6g6m-6twrjw**

**Comment by aitboudad** [comment]
Check the autocomplete doc https://material.angular.io/components/autocomplete/api, there is `optionSelected` event which you may use

**Comment by chandelshashank** [comment]
In formly autocomplete component i created a call back on select: (Ng-prime formly)

(onSelect)="to.onValueSelect(field,$event)"

Now it works, thank you.
