### ISSUE TITLE
Question: UISchema support?

### ISSUE THREAD

**Issue by sookoll** [ngx-formly/ngx-formly#2462]
**Question**

Do I understand correctly, that Formly currently do not support UISchema, like https://jsonforms.io/ do? For me it is impossible situation. I need form generation from JSONSchema, UISchema in Angular + Bootstrap project. jsonforms.io do not have Bootstrap renderer (nor native) and Formly doesn't seems to support UISchema. Any other library that just works?

**Comment by aitboudad** [comment]
UISchema is not supported yet but it's on our todo, for now, you may check the alternative way see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
