### ISSUE TITLE
Showing validation errors on init

### ISSUE THREAD

**Issue by TomaszKasowicz** [ngx-formly/ngx-formly#2465]
**Question**
Hi.
Thanks for the great lib which allows me to create Forms from JSON Schema :-).

I have one question.
Is it possible to show form errors when form is initialized?

i.e. 
When input field has "minLength" set and it is initialy empty then field is not marked as "not valid"
I would like to know if there is an option which after enabling would show errors (or mark field as "not valid") upon form init
(Here's the link the starter which has "minLengh: 4" added to input field: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-rxrpwh)

Also i noticed that the first validation runs on 1st blur, so when i start typing it is still not marked as "not valid"
If I click again the input field after "blur" then validation is executed on every keystroke.
It seems that validation is enabled only on 1st blur.

Thanks
Tomasz Kasowicz

**Comment by aitboudad** [comment]
see https://formly.dev/examples/validation/force-show-error
