### ISSUE TITLE
How to change select options dynamically based on radio selected value

### ISSUE THREAD

**Issue by bejgumshirisha** [ngx-formly/ngx-formly#2466]
**Question**

I want to change select options based on the radio input values changes.I tried to handle it in select change event but it is not reflecting.

Please find the below stackblitz url for reproduce

https://stackblitz.com/edit/angular-selec-radio-change?file=src/app/app.component.ts

**Comment by bejgumshirisha** [comment]
Resolved it by using 

`getField('nome', this.fields).templateOptions.options = this.newOptions;`

**Comment by kenisteward** [comment]
@bejgumshirisha where are you getting the 'getField()' function from

**Comment by aitboudad** [comment]
@kenisteward https://github.com/ngx-formly/ngx-formly/issues/1783#issuecomment-533058837

**Comment by kenisteward** [comment]
That's super helpful!  I wonder if it would be a good idea to add this as a
base utility and also be able to access the root field config from each
config.

**Comment by aitboudad** [comment]
@kenisteward yep that would be useful so either through options or the field itself!
