### ISSUE TITLE
Building custom form with FormlyFormBuilder buildForm

### ISSUE THREAD

**Issue by 0x253** [ngx-formly/ngx-formly#2467]
**Question**

I'm building a custom form using the `FormlyFormBuilder.buildForm` function. I don't use the `fieldArray` but construct the `FormlyFieldConfig` by iterating through the model elements.

The form fields are rendered in the view with `<formly-field [field]="getFormField(rowIndex, 'prop')"></formly-field>`.

The form is rendered correctly, and the field validation works, but the field expressions are not working. Furthermore, the  binding between the form inputs and the model isn't working. Is there anything else I have to do to have all functionality of a formly form?

See https://stackblitz.com/edit/angular-nxaze5?file=src%2Fapp%2Fapp.component.ts for a full example.

**Comment by 0x253** [comment]
Ok, I think I'm one step closer. I have created a new `<formly-form>` component with a different template, by inheriting from the original `FormlyForm` component class:

```js
@Component({
  selector: 'app-formly-form',
  template: `
    <ng-container #content>
      <ng-content></ng-content>
    </ng-container>
  `,
  providers: [FormlyFormBuilder],
})
export class FormlyFormComponent extends FormlyForm {
}

```

This component does not render the `<formly-field>` elements, which can now be rendered by my own template.

**Comment by aitboudad** [comment]
The request is not clear to me but I would say `FormlyForm` is required to ensure the form is working properly and for the template you should add it:

```html
<formly-field *ngFor="let f of fields" [field]="f"></formly-field>
```

For a custom form I would go for a custom type instead, you may check
- [Stepper type](stackblitz.com/edit/angular-yu7bzv-uucyxg)
- [FieldArray type](https://formly.dev/examples/advanced/repeating-section)
