### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError on Tabs Form example

### ISSUE THREAD

**Issue by m3niza** [ngx-formly/ngx-formly#2469]
**Description**
I am getting Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'false'. Current value: 'true'. while trying to run the example code for Tabs Form.
https://formly.dev/examples/advanced/tabs

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formy-tabs-form

Or https://stackblitz.com/angular/jamgbvngbgbj in Angular 10.0.2 and ngx-formly 5.0.0

**Your Environment**

- Angular version: 10.0.2
- Formly version: 5.0.0

**Additional context**
The stackblitz example in https://formly.dev/examples/advanced/tabs doesn't cause any errors but I'm using it in my latest version of Angular and it is throwing the error.

**Comment by aitboudad** [comment]
use tabs as a type https://stackblitz.com/edit/angular-e7ew9t?file=src/app/app.component.ts

**Comment by m3niza** [comment]
> use tabs as a type https://stackblitz.com/edit/angular-e7ew9t?file=src/app/app.component.ts

Thanks @aitboudad it works now.
