### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by Adam-Michalski** [ngx-formly/ngx-formly#2470]
Hi @aitboudad 

**Question**

When do you plan to release next version, cause I reported few issues and those are fixed, also this is a month without release. 

Are You ok? Is there something wrong? I am worried.

**Comment by aitboudad** [comment]
Hi, Nothing wrong just not having enough time right now btw I've pushed a dev release `5.10.0-dev.42c25be5` that you can use until `5.10.0` is released.
