### ISSUE TITLE
How can I achieve angular ngx-formly horizontal alignment without wrappers.

### ISSUE THREAD

**Issue by sivakumaraala** [ngx-formly/ngx-formly#2471]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aitboudad** [comment]
The wrapper is mandatory, another way is to override the default wrapper `form-field` so in that case you can omit passing wrappers through the field config:
```patch
{
  type: 'input',
- wrappers: ['form-field-horizontal'],
},
```

https://stackblitz.com/edit/angular-wvczwc-c6q9q4
