### ISSUE TITLE
Advanced Layout (Flex columns) in json schema

### ISSUE THREAD

**Issue by ezequiel-gg** [ngx-formly/ngx-formly#2472]
**Question**

How can i make an advance layout like this:
[https://stackblitz.com/edit/angular-yp4t9a?file=src%2Fapp%2Fapp.component.ts](url)
but in json schema .
its possible to add 'fieldGroup' in a json schema? thanks!

**Comment by aitboudad** [comment]
you can pass FormlyConfig through `widget.formlyConfig`:

```patch
{
  "type": "object",
+ "widget": { "formlyConfig": { "fieldGroupClassName": "row" } },
  "properties": {
    "firstName": {
      "type": "string",
+     "widget": { "formlyConfig": { "className": "col-6" } }
    },
    "lastName": {
      "type": "string",
+     "widget": { "formlyConfig": { "className": "col-6" } }
    },
  }
}
```

### object.type.ts

```patch
+ <div [class]="field.fieldGroupClassName">
  <formly-field *ngFor="let f of field.fieldGroup" [field]="f"></formly-field>
+ </div>
```

https://stackblitz.com/edit/angular-lmdq82

**Comment by dorijangrgic** [comment]
Can you, somehow, create multiple fieldGroups inside one object type? I would like to have a form like this (https://formly.dev/examples/other/advanced-layout-flex) but using json schema.

**Comment by dorijangrgic** [comment]
@aitboudad I am really sorry to bother you, but can you give me an answer on the possibility of such implementation? It would be extremely helpful to me.

**Comment by aitboudad** [comment]
Hi @dorijangrgic,
json schema doesn't support a such case so the easy solution is to use `map` (as mentioned above), another way if you want to control the group using a generic solution you may use a custom extension alongside `widget` property.

1. widget: custom groups
```patch
{
  "title": "A registration form",
  "description": "A simple form example.",
  "type": "object",
+ "widget": {
+   "formlyConfig": {
+     "templateOptions": { "groups": ['firstName', 'lastName'], ['age', 'bio'], ['password', 'telephone'] }
+   }
  }
}
```

2- Define a custom extension which adjust the field group based on `groups` property.
https://main.formly.dev/guide/custom-formly-extension

**Comment by Shourya2100** [comment]
Hi @aitboudad !! I am working on a similar issue of generating multiple fieldgroups from the json schema. Just wanted to know that with the approach that you have suggested of using custom extensions, Do we also need to use ngx-translate to map the JSON schema to fieldConfig ?
