### ISSUE TITLE
Formly, primeng not able to set value of mindate(datepicker) in component using angular

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2473]
I am using angular formly and primeng. I have FormlyFieldCalendar and AppComponent in place. Setting the property of minDate in and initialiting the value in FormlyFieldCalendar with minDate works fine, but when i am trying to set the minDate in AppComponent field its not working. Please find below both the scenarios, i have built the sample on StackBlitz for demonstration with link :
[StackBlitz](https://stackblitz.com/edit/ngx-formly-ui-primeng-d7v5g4-nu6ctj?file=app/formly-field-primeng-calendar.ts)

**Scenario 1: (working)**

When i set the minDate in FormlyFieldCalendar

`export class FormlyFieldCalendar extends FieldType {
   minDate =  new Date();
}`

**Scenario 2: (Not working)**

I now tried removing the code of setting minDate in FormlyFieldCalendar instead trying to set in Appcomponent by 2 ways.

1.  By using datePickerOptions provided in formly.dev webpage but seems doesnt work with primeng.

`templateOptions: {
        required: false,
        placeholder:"Start Date",
        datePickerOptions:{
          minDate:'08/29/2020'
      }`

2. By assigning in templateOptions and using datePickerOptions.

  `  {
      key: 'startDate',
      type: 'datepicker',
      templateOptions: {
        required: false,
        placeholder:"Start Date",
        minDate:'08/20/2020'
      }
   }`

**Comment by aitboudad** [comment]
```patch
- [minDate] ="minDate"
+ [minDate] ="to.minDate"
```

`to` is an alias for `field.templateOptions`.

**Comment by chandelshashank** [comment]
ohh that is basic and i missed it. 
Thanks for the support.
