### ISSUE TITLE
Is there way I can bind service call data to select drop down options in formly?

### ISSUE THREAD

**Issue by nikitsatpute** [ngx-formly/ngx-formly#2478]
**Question**
I have been trying to get Options Values for colors and heights drop down from API Call i.e. as of now from JSON response.
But from Formly Field Config, I am not able to access UserService methods which gets me the data.

Below example is giving me an error that service functions are not defined.
https://stackblitz.com/edit/angular-binding-select-options-formly

Please let me know how can I map in APPCYCLE_FORM - Options to call API on the fly and fill up the options i.e. drop down values from API call.

**Comment by aitboudad** [comment]
define `APPCYCLE_FORM` as a function and pass the needed services on initialization:
```ts
this.fields = APPCYCLE_FORM(this.userService);
```

and if fields are loaded through HTTP, check our example https://formly.dev/examples/other/json-powered that shows how to adjust the loaded JSON form.
