### ISSUE TITLE
Single-select with size

### ISSUE THREAD

**Issue by kasztnert** [ngx-formly/ngx-formly#2479]
Is there a possibility to set the size of a select (&lt;select size=&quot;15&quot;&gt;? I have to offer a single selection from a bigger list of strings, for which I normally use a typeahead, but in this case the options are hard to guess. Therefore I would like to load all of them in a select control with a bigger size (e.g. 15 lines visible at a time). Is there a way to set the size attribute of the select element?

**Comment by aitboudad** [comment]
use `attributes`:

```ts
{
  key: 'Select',
  type: 'select',
  templateOptions: {
    ...
    attributes: { size: 10 },
  },
},
```

**Comment by kasztnert** [comment]
Thank you for the quick response, works perfectly!
