### ISSUE TITLE
Default value for repeatable section with the resetFieldOnHide enabled

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2480]
**Description**
The default value is ignored for repeatable section with the resetFieldOnHide extra option enabled.

**Minimal Reproduction**

https://stackblitz.com/edit/formly-array-default-value?file=src%2Fapp%2Fapp.module.ts

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.10.0

**Note**
Works perfectly before 5.10.

**Comment by aitboudad** [comment]
I've missed that one :smile:, fixed in `v5.10.1`

**Comment by jma** [comment]
I will check thanks.
