### ISSUE TITLE
How do I set errorPath for Matching Fields Validation Inside repeat section for each row

### ISSUE THREAD

**Issue by cibinthomasjacob** [ngx-formly/ngx-formly#2481]
I have a formly form  and I am programmatically generating the formly configuration based on JSON from API. I need to be able to validate dates within each row by comparing each other. 

1. Currently I am not able to achieve this with errorPath.

2. I need to be able to use the index and set each row invalid individually. I dont have a way of obtaining the index of the repeated-row inside validator.expression = (control: AbstractControl) => {}

Please advise. Much appreciate your directions.

Minimal illustration of Issue 1 using the matching fields example: https://stackblitz.com/edit/angular-zymk2s

**Comment by aitboudad** [comment]
The easy way is to pass the validator though `fieldArray` https://stackblitz.com/edit/angular-zymk2s-n82ymm another alternative is to return the path from the validator itself in [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0) you can return multi-errors from a single validator

```ts
export function fieldMatchValidator() {
  ...

  return {
    password: {
      errorPath: 'passwords[0].passwordConfirm',
      message: 'Password Not Matching' , 
    },
    password1: {
      errorPath: 'passwords[1].passwordConfirm',
      message: 'Password Not Matching' , 
    },
  };
}
```
