### ISSUE TITLE
is there complete documentation?

### ISSUE THREAD

**Issue by sanyashvets** [ngx-formly/ngx-formly#2485]
Hi all
First of all, thanks for you work!
My question is - is there full docs on site? I'm trying to find all possible `templateOptions` params for every input with every framework (ionic/material/etc). Till now, I used to find smth here in issues via googling, but there are no single word (or I'm too stupid to find it) in certain cases (like which properties exists for every input type)

And the next question - examples with ionic framework on official site failed in stackblitz all the time. Would be good to fix it

Thanks in advance!

**Comment by aitboudad** [comment]
There is no full doc (require a huge amount of effort which I can't afford for now :pray:), our UIs is pretty simple, so the complete doc is the source code, just go and check each IONIC type https://github.com/ngx-formly/ngx-formly/tree/main/src/ui/ionic.

Our progress is small but better than nothing!

**Comment by aitboudad** [comment]
> And the next question - examples with ionic framework on official site failed in stackblitz all the time. Would be good to fix it

I'll check it and let you know once fixed :+1:
