### ISSUE TITLE
How to set defaultValue for autocomplete field using primeng autocomplete field in formly

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2486]
`**Question**`

I am using Autocomplete field, by using <p-autocomplete> of prime ng in formly, i am not able to set the. default value of this field from one of the options in the list.  I have gone through the primeng documentation of angular it suggests to use ngModel in which it works fine, but how can we use this with formly fields.

In my FormlyAutocomplete comoponent following properties are used: 

`<p-autoComplete`
       `field="label"`
       `[formControl]="formControl"` 
       `[formlyAttributes]="field"` 
       `[forceSelection]="true"`
     ` [suggestions]="to.results"`
      `[style]="{'width':'100%'}"` 
      `[inputStyle]="{'width':'100%'}"`
      `(completeMethod)="to.searchObject(to,` $event)"
      `(onSelect)` ="to.onSelect(field,$event)"
      `[dropdown]="true"></p-autoComplete>`

In the component where i am consuming the code is as follows:

`{`
            `className: 'form-group col-md-6',`
            `key: 'employee',`
            `type: 'autocomplete',`
           ` wrappers: ['form-field'],`
            `defaultValue: formState.employees[0].value,`
            `templateOptions: {`
             ` results: [],`
              `placeholder: 'Select Employee',`
             ` required: true,`
              `searchObject: (templateOptions, $event) => {`
                `templateOptions.results =`
` formState.employees.filter(item =>item.label.toLowerCase().indexOf($event.query.toLowerCase()) > -1);`
             ` },`
              `},`
            `}`

**Comment by aitboudad** [comment]
it should be set if `p-autoComplete` support reactive-form (`[formControl]="formControl"`), could you please provide a reproduction example using one of our stackblitz starter example.
Thanks!

**Comment by chandelshashank** [comment]
@aitboudad  I have created the example in stackblitz, i just want to set any of the default values from the country list available there.

Link for [Stackblitz, prime ng autocomplete](https://stackblitz.com/edit/ngx-formly-ui-primeng-ncrfyl-formly-autocomplete?file=src/app/app.component.ts)

Thank you response and support.

**Comment by aitboudad** [comment]
primeng autocomplete emit an object so the default value should be an object too https://stackblitz.com/edit/ngx-formly-ui-primeng-ncrfyl-formly-autocomplete-dpkxj2?file=src/app/app.component.ts

**Comment by chandelshashank** [comment]
This was very helpful, it worked for me, thank you for quick response and resolution.

Thank you @aitboudad

**Comment by ahmedyouseeff** [comment]
what if I want to return one value from the object?
