### ISSUE TITLE
Ionic: The type "multicheckbox" could not be found

### ISSUE THREAD

**Issue by mwyld** [ngx-formly/ngx-formly#2487]
**Description**
I'm not sure wether the mutlicheckbox is enabled in ionic or it's something I'm missing but I'm getting the error

`[Formly Error] The type "multicheckbox" could not be found. Please make sure that is registered through the FormlyModule declaration.`

Every other component works okay, it's just this type that doesn't show

**Minimal Reproduction**

This is the JSON i am using
![Screenshot 2020-09-04 at 16 47 44](https://user-images.githubusercontent.com/12820928/92258354-9ba24c80-eece-11ea-9cee-5af051f3a11a.png)

**Your Environment**

    "@ionic/angular": "^5.0.0",
    "@ngx-formly/core": "^5.0.0",
    "@ngx-formly/ionic": "^5.10.0",
    "@ngx-formly/schematics": "^5.10.0",

**Additional context**

**Comment by aitboudad** [comment]
right `multicheckbox` is available for bootstrap and material only, we'll make it available in other UI later, so I suggest to create a custom field type instead.

**Comment by mohammmedimran** [comment]
Hi iam getting these error
 core.js:6241 ERROR Error: [Formly Error] The type "datepicker" could not be found. Please make sure that is registered through the FormlyModule declaration.
    at FormlyConfig.getType (ngx-formly-core.js:492) 
can any one tell what is the issue i have added in json styles bootstrap ngx

**Comment by Vinoth-deva** [comment]
> Hi iam getting these error core.js:6241 ERROR Error: [Formly Error] The type "datepicker" could not be found. Please make sure that is registered through the FormlyModule declaration. at FormlyConfig.getType (ngx-formly-core.js:492) can any one tell what is the issue i have added in json styles bootstrap ngx



impoty this module your respective  module.ts FormlyMatDatepickerModule

**Comment by aitboudad** [comment]
@mohammmedimran Ionic doesn't have a `datepicker` type, use `datetime`  instead (https://formly.dev/ui/ionic)
