### ISSUE TITLE
Disable Attribute for Radio Button Options

### ISSUE THREAD

**Issue by SwissKerim** [ngx-formly/ngx-formly#2489]
Hello together

I am trying to disable an option for radio buttons, but it does not work without html.

```
{
       key: 'region',
       type: 'radio',
          templateOptions: {
          label: 'Region',
          required: true,
          options: [
            {
              value: 1,
              label: 1,
            },
            {
              value: 2,
              label: 2,
              disabled: 'true' //also tried true or 'disabled'
            },
            {
              value: 3,
              label: 3
            }
          ]
       }
}
```

And I tried this too:

```
        hooks: {
          onInit: (field) => {
            field.expressionProperties.options[0].disabled = true;
          }
```

Is it possible to disable it without adding html? I only want to work in the component.

My template:

```
<form [formGroup]="form">       
  <formly-form         
       [model]="model"         
       [fields]="fields"        
       [options]="options"        
       [form]="form">       
</formly-form>
```

Versions:

-     "@angular/core": "^7.1.4",
-     "@ngx-formly/core": "^5.4.1",

**Comment by aitboudad** [comment]
which UI do you use? also, update Formly version to the latest one `5.10.1`.

**Comment by SwissKerim** [comment]
> which UI do you use? also, update Formly version to the latest one `5.10.1`.

I'm using Materials:

- "@angular/material": "^7.2.0",
- "@ngx-formly/material": "^5.4.1",

**Comment by aitboudad** [comment]
Then just update Formly to `5.10.1` and it should work.
