### ISSUE TITLE
Model is binding incorrectly when using nested components

### ISSUE THREAD

**Issue by joncorrin** [ngx-formly/ngx-formly#2490]
**Description**
Im trying to implement nested components that use a mix of the repeat component as well other types of custom components that group together fields. For some reason, the model is binding incorrectly. It produces hundreds of nulls in an array as opposed to forming the correct object based on the form data. The issue is reproduced in the stackblitz below

**Minimal Reproduction**

https://stackblitz.com/edit/angular-s5v2qa?file=src%2Fapp%2Fapp.component.ts

**Additional context**
In order to reproduce it, just fill in a field and and notice the printed JSON which is seen in form.component.ts

Any help is appreciated!

**Comment by aitboudad** [comment]
When the default value is not provided, Formly rely on the key value to assign whether is an object or an array.
For a quick fix, define default value for `section` and `questionGroup`: https://stackblitz.com/edit/angular-s5v2qa-ujdqji

I may check later if it can be fixed on our side.

**Comment by joncorrin** [comment]
Thanks! This work around is simple and sufficient.
