### ISSUE TITLE
defaultValue: null - Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by damsorian** [ngx-formly/ngx-formly#2491]
**Description**
In the version 5.10.1 when the defaultValue is **null** the ngx-formly-core.js breaks

I think the problem is this logic changed related to the **defaultValue** https://github.com/ngx-formly/ngx-formly/compare/v5.10.0...v5.10.1#diff-9b2d3151ef7629725cd42759a64296adR99

```
handle-error.service.ts:51 TypeError: Cannot read property 'parent' of undefined
    at assignFieldValue (ngx-formly-core.js:92)
    at CoreExtension.initFieldOptions (ngx-formly-core.js:3299)
    at CoreExtension.onPopulate (ngx-formly-core.js:3199)
    at ngx-formly-core.js:719
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder._buildForm (ngx-formly-core.js:715)
    at ngx-formly-core.js:725
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder._buildForm (ngx-formly-core.js:721)
    at ngx-formly-core.js:725
```
**Minimal Reproduction**

Only set a defaultValue to null in any component

_I don't know why I can't reproduce the issue on stackblitz but in local with a minimal stack, it throws that error and breaks the app_

**Your Environment**

- Angular version: 10.1.0
- Formly version: 5.10.1

**Comment by aitboudad** [comment]
could you please provide a reproduction example, thanks!

**Comment by damsorian** [comment]
@aitboudad I don't know why I can't reproduce the issue on stackblitz but in local with a minimal stack, it throws the error  _Cannot read property 'parent' of undefined_

I think the problem is this logic changed related to the **defaultValue** https://github.com/ngx-formly/ngx-formly/compare/v5.10.0...v5.10.1#diff-9b2d3151ef7629725cd42759a64296adR99

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by damsorian** [comment]
gracias!!

**Comment by miko-engr** [comment]
Dear @aitboudad, I am experiencing same issue on my end with data-table integration. Just added screenshot for them. 
![image](https://user-images.githubusercontent.com/36751399/109019484-0d41a300-7687-11eb-81d8-719446ed5b52.png) Please let me know if you have any solution for it. Thanks!

**Comment by aitboudad** [comment]
@miko-engr I think there is a bug somewhere but I need a reproduction scenario/example 🙏 in order to fix it also make sure you're using the latest version of Formly.

**Comment by bandman0226** [comment]
I am getting the same issue. I am trying to use the latest next version with primeng. It happens when clicking the datepicker. 
[](https://stackblitz.com/edit/ngx-formly-flex-layout-6ksvaw?file=src%2Fapp%2Fapp.component.ts)

**Comment by aitboudad** [comment]
@bandman0226 the mentioned stackblitz is working for me, could you please check it again or maybe I'm missing something 🤔.

**Comment by bandman0226** [comment]
My apologies. It was not working but I got it working after messing with the  stackblitz for the datepicker code from the formly site. There were some things missing to run the demo code for that datepicker in stackblitz so I fixed the same on the original one I had trouble with.

Thanks again for taking the time to look at it :)
