### ISSUE TITLE
hideExpression does not work for complex condition string

### ISSUE THREAD

**Issue by msanjeevkumar-1** [ngx-formly/ngx-formly#2492]
**Description**
hideExpression does not seem to be working for complex condition string expression

```
hideExpression: 'model.city.indexOf("cal") > -1' // this is not working
hideExpression: 'model.city == "cal"' // this is working
```

**Comment by kenisteward** [comment]
Are you starting with a value? As in is it always a string? If not,
.indexof will return an error and break the hide expression.

If you can stack blitz this or show console errors that would be helpful.
Probably just need to make sure model.city is an actual string first though.

model.city && model.city.includes()

Also unless you are using super old browsers .includes() might be better
for this particular case.

**Comment by joncorrin** [comment]
Thanks @kenisteward ! The issue I was having was actually model.city was undefined in my case which was breaking includes

**Comment by kenisteward** [comment]
Yup it happens all the time. If you want to fix that another way is to set
the defaultValue to ''

**Comment by aitboudad** [comment]
As @kenisteward mentioned make sure the value is defined first and for a complex expression, I would prefer to use a function instead.
