### ISSUE TITLE
If model is null you can't add element to array type on any level

### ISSUE THREAD

**Issue by Adam-Michalski** [ngx-formly/ngx-formly#2493]
Hi,

I found that if model is not provided, and I use `[form]` and `[fields]` passed to `formly-form` I can't add elemenent to any array in my form

[Example](https://stackblitz.com/edit/angular-fsd7sq?file=src%2Fassets%2Fjson-schema%2Farrays.json)

Also if You add two way data binding to `model` set to `null` this issue is no longer present
![image](https://user-images.githubusercontent.com/5684123/92581694-47adb400-f290-11ea-8ea0-b2a994cfa451.png)

This looks like problem is with that the model is not changed outside.

formly version checked 5.7.2 and 5.10.1

Also when I updated to 5.10.1 with TypeScript 3.2.2 I have error in `input.type.d.ts` about ambient context on `get: type()` I do think that this is fixable to keep backwards compatibility

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
