### ISSUE TITLE
Fields declaration in multiple classes (types)

### ISSUE THREAD

**Issue by rcp87** [ngx-formly/ngx-formly#2495]
Hi, I'm looking to do this with Formly, but I'm not sure it can be done with this great library. 
I want to do a large multi-step form having each step in different components. I have seen it can be done by one of your examples with material-stepper, and creating different custom types with their own templates.
But always all the fields are declared in the main component class, I only see the types for declaring the templates, but not the fields declarations in these component classes.
What I have seen:
- Main component
    - Template.
    - Field(s) -> Custom types.

- Custom type component
   - Template

What I want:
- Main component
    - Template.
    - Field(s) -> Custom type

- Custom type components
   - Template
   - Fields in ts component class.

It is possible to have each step fields declaration in their own classes? I don't know if this is possible, or it breaks the paradigm of formly/stepper??
I hope I make myself clear, thanks in advance.

**Comment by aitboudad** [comment]
possible and that's how we manage [array type](https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/templates/field-array.type.ts#L13) so in your case:

```
export class CustomTypeComponent extends FieldType {
  onPopulate(field: FormlyFieldConfig) {
    if (field.fieldGroup && field.fieldGroup.length > 0) {
		return;
    }

    field.fieldGroup = [
      ...
    ];
  }
}
```

another approach is to use `defaultOptions` (can be done through custom component or NgModule declaration):

```
export class CustomTypeComponent extends FieldType {
  defaultOptions = {
    fieldGroup: [ ... ],
  };
}

**Comment by rcp87** [comment]
Thank you sir for your quick response. It would be great if you can provide me with a small example of this. What option is better for reusability? I'm thinking in a big form with four or five steps and complex form inside each of them.
Thank you.

**Comment by aitboudad** [comment]
if you're looking for multi-step form check our doc https://formly.dev/examples/advanced/multi-step-form
and to group each step in a component all you have to do is to create a custom type https://formly.dev/guide/custom-formly-field and use the above [suggestion](https://github.com/ngx-formly/ngx-formly/issues/2495#issuecomment-690940320)
