### ISSUE TITLE
addonLeft (addonRight) requires CSP style-src unsafe-inline

### ISSUE THREAD

**Issue by mdantonio** [ngx-formly/ngx-formly#2496]
Hello I'm using ngx-formly/bootstrap on Angular 10 behind a nginx reverse proxy configured with very strict settings

When adding a addonLeft (addonRight), the input is wrapped by a input-group-prepend (input-group-append) div with an inline style:

`[ngStyle]="{ cursor: to.addonLeft.onClick ? 'pointer' : 'inherit' }"`
(should be [here](https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/bootstrap/addons/src/addons.component.html))

the inline style fails on restrictive CSP, i.e. when `style-src: unsafe-line` is disabled
(Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' ". Either the 'unsafe-inline' keyword, a hash ('sha256-wbXKiBB6WnennlkmjwHOqyRyzFGShUxSsRaScR3oXVY='), or a nonce ('nonce-...') is required to enable inline execution)

Is there any chance to convert the NgStyle in a NgClass to prevent issues with CSP?

**Comment by aitboudad** [comment]
for a workaround just override the existing addon wrapper

**Comment by mdantonio** [comment]
Ok, thank you... I will try!

Should be something like:

```
 FormlyModule.forRoot({
   wrappers: [
     { name: 'addons', component: CustomFormlyWrapperAddons },
   ],
 }),

```
With CustomFormlyWrapperAddons inspired from [src/ui/bootstrap/addons/src/addons.component.ts](https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/bootstrap/addons/src/addons.component.ts)

Is that correct?

anyway, is there no plan to include similar improvements directly in ngx-formly itself?

**Comment by aitboudad** [comment]
> Is that correct?

correct

> is there no plan to include similar improvements directly in ngx-formly itself?

there is a plan for sure!

**Comment by mdantonio** [comment]
I did some tests and I confirm that by removing the 
`[ngStyle]="{ cursor: to.addonLeft.onClick ? 'pointer' : 'inherit' }"` in the addons template the problem is fixed

It can be replaced with a:

`[ngClass]="(to.addonLeft.onClick)? 'pointer-cursor' : 'inherit-cursor'`

with corresponding css classes defined in addons.component.scss

```
.pointer.cursor {
    cursor: pointer;
}
.cursor.inherit {
    cursor: inherit;
}
```

or maybe just defining the first is enough?

`[ngClass]="{'pointer.cursor': to.addonLeft.onClick'}"`


> there is a plan for sure!

Thank you the reassurance. If you plan to introduce this fix in any of the following releases I will avoid to dirt my project with local patches like this and wait for an official fix

Thank a lot for all the support!

**Comment by mdantonio** [comment]
Hello, can I ask if the fixes to prevent inline styles are still in the planning for future releases?

**Comment by aitboudad** [comment]
yes, you could send a PR to the `main` branch.
