### ISSUE TITLE
Unable to add subscribe on templateOptions.options. change detection on to.options is not happening 

### ISSUE THREAD

**Issue by Thiru0808** [ngx-formly/ngx-formly#2497]
Hi,

I created a custom select type field(not the formly provided one), binded templateOptions.option in expressionProperties and fetches to.Options in ngInit in  my custom select field component,

But when the options are changed I don't see the changed options in my select field I  have tried CD as onPush as well, but no luck.

**Comment by aitboudad** [comment]
use `formlySelectOptions` pipe:

```html
<option *ngFor="let option of to.options | formlySelectOptions: field | async">
  ...
</option>
```

**Comment by Thiru0808** [comment]
@aitboudad That worked thank you.
