### ISSUE TITLE
safari ios 13 focus bug with material ui

### ISSUE THREAD

**Issue by fetters5** [ngx-formly/ngx-formly#2498]
**Description**
Since version 5.6.2 I believe this PR (https://github.com/ngx-formly/ngx-formly/pull/2249) Safari(ios 13.7) keeps focus on the previous item if it matched the default value, after the first click it works as intended again, I confirmed this issue did not start occurring until to 5.6.2

**Minimal Reproduction**
https://angular-hazkoe1.stackblitz.io
![unnamed](https://user-images.githubusercontent.com/3276557/93137549-a8cbf200-f6ab-11ea-92c3-793b3db71b4e.jpg)

**Your Environment**

- Angular version: 10.1
- Formly version: 5.10.1 (issue started with 5.6.2)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
