### ISSUE TITLE
tabindex issue with material select

### ISSUE THREAD

**Issue by rtrompier** [ngx-formly/ngx-formly#2501]
**Description**
Hi guys, 
The tabindex value in template option seem to be bugged with material select component.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-6sygem-h6mouk?file=src/app/app.component.ts

**Your Environment**
- Angular version: All version
- Formly version: 5.10.1

**Additional context**
Start to write in first form element, and use TAB key to switch to next element.
All select element are not selected in the correct order.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by rtrompier** [comment]
Working with V5.10.2, well done ! Thank you very much.
