### ISSUE TITLE
Grid table

### ISSUE THREAD

**Issue by vukasin992** [ngx-formly/ngx-formly#2502]
Hi, any clue how to config the grid(table) to have input or link as type of field like on screen shot
![Screen Shot 2020-09-16 at 11 40 41 AM](https://user-images.githubusercontent.com/24272055/93320576-881dac80-f811-11ea-9691-5bc03471c0ad.png)

**Comment by aitboudad** [comment]
check our demo example:

- https://formly.dev/examples/advanced/datatable-integration
- https://formly.dev/examples/advanced/grid-integration
