### ISSUE TITLE
When data come with delay the list is not visibile.

### ISSUE THREAD

**Issue by stefani0** [ngx-formly/ngx-formly#2503]
https://stackblitz.com/edit/ngx-formly-ui-kendo-fo1475?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
delayed data can be done either using promise or observable and not `setTimout`:
https://stackblitz.com/edit/ngx-formly-ui-kendo-sciyqg?file=src/app/data.service.ts

in case of an `http` call:

```ts
 public getPortfolioGroups(): Observable<PortfolioGroup[]> {
   return this.httpClient.get('porfolio_url');
 }
```
