### ISSUE TITLE
Radio Field fires click event twice

### ISSUE THREAD

**Issue by Thiru0808** [ngx-formly/ngx-formly#2504]
Hi,

I am using a custom radio field with <input type="radio" [formControl]="form" [formlyAttributes]="field" (click)="to.click(field, selection)" .... >

it fires two events one with (field,mouseEvent). and the second is (field, selection)

I noticed when I remove  [formlyAttributes]="field", I get only one event (field, selection)

**Comment by aitboudad** [comment]
` [formlyAttributes]` emit the click event too, so either uses another callback to track the click with (field, selection) or remove `[formlyAttributes]`.

```patch
+ (click)="to.onSelect(field, selection)"
- (click)="to.click(field, selection)"
```
