### ISSUE TITLE
Model state not updated after setting value

### ISSUE THREAD

**Issue by lylebuchanan** [ngx-formly/ngx-formly#2505]
Trying to accomplish something like this post: https://github.com/ngx-formly/ngx-formly/issues/180
I want to auto format the users input as they type but the model state is a step behind.

https://stackblitz.com/edit/angular-zmw9wb-ubt9vw?file=src%2Fapp%2Fapp.component.html

Does anyone have thoughts on how to solve this or an alternate way to accomplish formatting user input?

**Comment by aitboudad** [comment]
use `distinctUntilChanged()` and remove emitEvent parameter:

```ts
hooks: {
  onInit: ({ formControl }) => {
    return formControl.valueChanges.pipe(
      distinctUntilChanged(),
      startWith(formControl.value),
      tap((v) => {
        if (v) {
          formControl.patchValue(v.toUpperCase());
        }
      }),
    );
  }
}
```

https://stackblitz.com/edit/angular-zmw9wb-2gwah5?file=src/app/app.component.ts
