### ISSUE TITLE
No value accessor for form control with unspecified name attribute

### ISSUE THREAD

**Issue by sunger** [ngx-formly/ngx-formly#2507]
Hello，I clone the code(main,"6.0.0-alpha") and try custom "ng-zorro-antd/transfer" 

but get error

"No value accessor for form control with unspecified name attribute"

transfer.type.ts

`import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'formly-field-nz-transfer',
  template: ` <nz-transfer
    [formControl]="formControl" [formlyAttributes]="field"
    [nzDataSource]="to.list"
    [nzTitles]="to.titles"
    [nzOperations]="to.operations || ['', '']"
  >
  </nz-transfer>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
// tslint:disable-next-line: component-class-suffix
export class FormlyFieldTransfer extends FieldType {

}
`
but without [formControl]="formControl" [formlyAttributes]="field"
the error disappear

angular   : "^9.1.11",
![screenshot](https://user-images.githubusercontent.com/630072/93692278-b22de200-fb23-11ea-9332-7eb9a3bdaa62.png)

**Comment by aitboudad** [comment]
The error may happen in case you've defined the type without passing a key:

```patch
{
+  key: 'file',
  type: 'transfer',
}
```

Also make sure `ReactiveFormsModule` and `FormlyModule` are imported where the `FormlyFieldTransfer` is declared and check if `ng-zorro-antd/transfer` support the reactive form.

**Comment by sunger** [comment]
Thank you for your prompt reply
my fields：

`[{
	"id": "1600828594318",
	"key": "f1600828594318",
	"type": "transfer",
	"templateOptions": {
		"label": "穿梭框",
		"placeholder": "穿梭框",
		"required": false,
		"titles": ["未拥有", "已拥有"],
		"list": [{
			"title": "item1",
			"value": 10
		}, {
			"title": "item2",
			"value": 11
		}, {
			"title": "item3",
			"value": 12
		}, {
			"title": "item4",
			"value": 13
		}],
		"name": "f1600828594318"
	}
}]`

**Comment by aitboudad** [comment]
remove the following input `[formControl]="formControl"` as the transfer component doesn't support Angular Reactive Form and instead rely on change events:

```html
    <nz-transfer
      [formlyAttributes]="field"
      [nzDataSource]="to.list"
      [nzDisabled]="formControl.disabled"
      (nzSelectChange)="onSelect($event)"
      (nzChange)="onChange($event)"
    >
    </nz-transfer>
```

To get the field value use `formControl.value` and `formControl.setValue(value)` to update it.
