### ISSUE TITLE
Regarding ngx-quill: 'formcontrol' is not defined in FieldQuillType

### ISSUE THREAD

**Issue by Shravani2093** [ngx-formly/ngx-formly#2510]
Hi,
I have integrated the ngx-quill into the project, but I'm unable to get the form control value. I'm getting formcontrol is not defined in FieldQuillType.ts.
https://stackblitz.com/edit/angular-elwtix-tmme97?file=src%2Fapp%2Fapp.module.ts  is the code which I have integrated into the project. I'm using angular 9 version. Please, help me out!!
Thanks.

**Comment by aitboudad** [comment]
A reproduction example is needed here also make sure you're using the latest version of Formly!

**Comment by Shravani2093** [comment]
I'm using the latest version of formly too. The thing is, it is working in stackblitz but when integrated in project I'm getting the following error,
TypeError: Cannot read property 'formControl' of undefined at FieldQuillType.get [as formControl]

**Comment by aitboudad** [comment]
Well, I think you're trying to access to the field too early (`constructor`), where the field is not defined yet.
make sure the field is defined before calling `formControl`
