### ISSUE TITLE
when "<formly-form..." tag in my component, view not update reassignment “fields”

### ISSUE THREAD

**Issue by sunger** [ngx-formly/ngx-formly#2512]
my costom component like this:
`
@Component({
  selector: 'dyn',
  template: `<formly-form #ff [form]="form" [fields]="fields" [(model)]="model"></formly-form>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DynComponent implements OnInit {

  @Input() data: ListItem;

  form = new FormGroup({});
  model = {};
  fields: FormlyFieldConfig[] = [
    {
      id: '',
      key: '',
      type: 'input',
      templateOptions: {
        label: '',
        placeholder: '',
        required: false,
      },
    },
  ];
  constructor(private obDtSv: DynItemPropChangeSv, private ngZone: NgZone) {
    this.obDtSv.obPropChange().subscribe((r: ListItem) => {
      console.log('fields changed', r);
      const f = this.fields[0];
      Object.assign(f, r);

      Object.assign(this.model, r.templateOptions);
      this.fields = JSON.parse(JSON.stringify(this.fields));

      console.log(this.model, this.fields);
    });
  }
`

use like this:

`
<dyn [data]="mydata" ></dyn>
`

when "mydata" changed,view unchanged, but when click the fomly's formControl , view changed

![QQ图片20200923110553](http://wrj.ruiqiapp.cn/static/dist/assets/1.png)

**Comment by aitboudad** [comment]
probably due to the change detection, so try to call `detectChanges` manually or remove `OnPush` CD.

```patch
this.obDtSv.obPropChange().subscribe((r: ListItem) => {
  ...
+  this.form = new FormGroup({});
+  this.changeDetectorRef.detectChanges();
});
```
