### ISSUE TITLE
Tabs from JSON shema

### ISSUE THREAD

**Issue by vukasin992** [ngx-formly/ngx-formly#2513]
Hi, I am trying to convert current tabs fields into JSON schema, so basically I want to change this fields configuration into JSON schema
![Screenshot 2020-09-23 at 16 17 06](https://user-images.githubusercontent.com/24272055/94024977-4f08ad80-fdb8-11ea-95b6-efb2a62fa9f5.png)

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527

It can be done manually after `toFieldConfig` call and for a generic way you may rely on `widget` and `map` fn to the convert the generated field config into tabs:

1- add widget to the schema:

```patch
const schema = {
  "type": "object",
+  "widget": {
+    "type": "tabs",
+    "tabs": [
+      { title: 'Personal data', fields: ['firstName', 'lastName'] },
+      { title: 'Destination', fields: ['country'] },
+    ],
+  },
  "properties": { ... }
}
```

2- Use `map` fn:

```
const field = this.formlyJsonschema.toFieldConfig(
  schema,
  {
    map: (field, schema) => {
      if (schema.widget && schema.widget.type == 'tabs') {
        field.fieldGroup = schema.widget.tabs.map(tab => ...);
      }

      return field;
    }
  }
);
```
To get field by key you may use this [getField](https://github.com/ngx-formly/ngx-formly/issues/1783#issuecomment-533058837) util.

**Comment by BhagyashreeCH** [comment]
@aitboudad @vukasin992 I have to show formly forms in tabs structure but getting error while converting structure in formlyJsonschema service

widget not exist in JSONschema7, could you please provide inputs
