### ISSUE TITLE
How to do disable all fields in a tab

### ISSUE THREAD

**Issue by quietgecko** [ngx-formly/ngx-formly#2514]
I am using the tabs form to design my form using this example: [(https://formly.dev/examples/advanced/tabs)](https://formly.dev/examples/advanced/tabs)

In my tab there are a lot of fields and I want to disable all the fields based on some condition ( for example  a particular user is not allowed to edit this tab) . 

I can add a expressionProperty as shown in the code and test case below , but that only works if I specified the "key"( for example -  key: "personal_info ) . But on adding the key, it groups the resulting form model in an additional hierarchy

`{"personal_info":{"firstname":"jon ","lastname":"doe","age":22},"country":"utopia","day":"2020-02-02"}`

If I comment out the key: personal_info, I don't get the extra hierarchy in the model,  but the fields are not disabled
`{"firstname":"jon ","lastname":"doe","age":22,"country":"utopia","day":"2020-02-02"}`

{
```
        key: "personal_info",
        expressionProperties: {
        'templateOptions.disabled': 'true'
        },
        templateOptions: { label: 'Personal data' },
        fieldGroup: [
          {
            key: 'firstname',
            type: 'input',
            templateOptions: {
              label: 'First name',
              required: true,
            },
          },
           {
            key: 'lastname',
            type: 'input',
            templateOptions: {
              label: 'Last name',
              required: true,
            },
          },
          {
            key: 'age',
            type: 'input',
            templateOptions: {
              type: 'number',
              label: 'Age',
              required: true,
            },
          },
        ],
      },
```

I can probably add the expression property to each field in the tab, but i was looking at a way to disable all the fields as a group condition. But I  don't want to introduce the extra hierarchy.
How can I disable all the fields in a tab without adding the key ( key: 'personal_info') 

Here is sample [test case ](https://stackblitz.com/edit/angular-1kthr8-gjvfvz)

**Comment by KingDarBoja** [comment]
Looking for same way to disable all fields without extra hierarchy, in the meantime, I can live with it 👍

**Comment by aitboudad** [comment]
You need to go through all tab fields, here is an example:

```ts
export class FormlyFieldTabs extends FieldType {
  ...
  disableField(field: FormlyFieldConfig) {
    if (field.key) {
      field.formControl.disable();
    } else if (field.fieldGroup) {
	    field.fieldGroup.forEach((f) => this.disableField(f));
    }
  }
}
```
