### ISSUE TITLE
Using an observable when evaluating templateOptions.disabled in expressionProperties - Error: Cannot read property 'disabled' of undefined

### ISSUE THREAD

**Issue by ibsus** [ngx-formly/ngx-formly#2515]
**Description**
If an observable is used in an expressionProperty that is disabling a field, an error "Cannot read property 'disabled' of undefined" is raised.

This only occurs when the field config is a fieldArray.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-jk8mcd?file=src/app/app.component.ts

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.10.1

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
