### ISSUE TITLE
dynamic formGroup validator change doesn't seem to get picked up? 

### ISSUE THREAD

**Issue by NickFranceschina** [ngx-formly/ngx-formly#2524]
**Description**

Using the demo of the "validating two fields"... I have created a formly form with a validator and then a formGroup next to it with two fields.  when the form load this validator does get called as expected (just like the demo).  but if I then set the `fields` list to a new list of FormlyFieldConfig objects, with a new validator and new formGroup, the new form group appears (the controls change), but the validator does not, and instead the original seems to persists. 

am I doing something wrong?

**Minimal Reproduction**

modiied your original "validate two fields" stackblitz and removed everything I possibly could to make this as straightforward as possible... logging state/validation calls to the console:

https://stackblitz.com/edit/angular-dnbeax?file=src/app/app.component.ts

**Your Environment**

- Formly version: 10.2

**Comment by aitboudad** [comment]
for a workaround init the form instance too:

```ts
  replace() {
    console.log('replace');
    this.form = new FormGroup({});
    this.fields = [{ ... }];
  }
```

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by slash33** [comment]
when i add dynamically another field in form, i loose my validators on previous fields , i think its  clearControl(this.form); that cause the problem.

ngOnChanges(changes: SimpleChanges) {
    if (changes.fields && this.form) {
      clearControl(this.form);
    }

**Comment by aitboudad** [comment]
@slash33 better fill a new issue with a reproduction stackblitz example

**Comment by jopperknopper** [comment]
@slash33 after you have added a field dynamically, try this:
            (<any>this.field.options)._buildForm( false );
it solved my problems.

It re-initializes the fields in the form :-)
