### ISSUE TITLE
expressionProperties key no longer supports array notation

### ISSUE THREAD

**Issue by silvl** [ngx-formly/ngx-formly#2525]
**Description**
In v5.1.8, expression properties supported:
"expressionProperties": {
   "templateOptions.options[0].label": "some expression"
}

In latest version, this is no longer supported,  The error happens in code introduced in the FieldExpressionExtension.setExprValue. It appears that it now will only accept format "templateOptions.options.0.label".  However, changing the format is not an option as we have many layouts used by various clients that are persisted to the database.

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: 9
- Formly version: 5.10.2

**Additional context**

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by inigoiparragirre** [comment]
Hi, @aitboudad 

Recently I updated formly to v5.10.3 and I see that I can use expressionProperties for options array. I am using something like this:
            expressionProperties: {
              'templateOptions.label': this.ts.stream('DOCUMENT'),
              'templateOptions.placeholder': this.ts.stream('TYPE_DOCUMENT_PLACEHOLDER'),
              'templateOptions.options[0].label': this.ts.stream('DOCUMENT.X'),
              'templateOptions.options[1].label': this.ts.stream('DOCUMENT.Y'),
              'templateOptions.options[2].label': this.ts.stream('DOCUMENTO.Z'),
              'templateOptions.cancelText': this.ts.stream('CANCELA'),
              'templateOptions.okText': this.ts.stream('SELECT'),
            }

For the expression I use ngx-translate and I can translate string expressions, like templateOptions.okText..., but somehow the options array labels are not showing the values. Any hint?

Thank you!

**Comment by aitboudad** [comment]
without a reproduction it may be hard to guess, you may try the extension solution provided in our doc https://formly.dev/examples/advanced/i18n-alternative and for options check https://github.com/johannesjo/super-productivity/blob/master/src/app/ui/formly-translate-extension/formly-translate-extension.ts#L14

**Comment by inigoiparragirre** [comment]
I think the Observable is not working as expected for the options array. Any other Observable assignations in expressionProperties are working perfect. Anyway as a workoround I used TranslateService.instant() method for templateOptions properties, after getting the language translations in the TranslateService.use() subscription. I will check the links provided. Thank you!

**Comment by codewithtushar** [comment]
yes binding observable stream to option's label is not working for me either tried copying https://github.com/johannesjo/super-productivity/blob/master/src/app/ui/formly-translate-extension/formly-translate-extension.ts#L14 

I'm using below versions
```
"@ngx-formly/core": "^5.10.14",
"@ngx-formly/material": "^5.10.14",
"@ngx-formly/schematics": "^5.10.14",
```


@
