### ISSUE TITLE
How to select oneOf value

### ISSUE THREAD

**Issue by rohitb7** [ngx-formly/ngx-formly#2528]
https://stackblitz.com/edit/angular-vv82f7?file=src%2Fassets%2Fjson-schema%2Fschema_dependencies.json

Check "schema_dependencies" in stackblitz

					"items": {
						"type": "object",
						"properties": {
							"mainKey": {
								"oneOf": [{
										"type": "string",
										"description": "Route policy contents as a single quoted string",
										"format": "WORD"
									},
									{
										"type": "null",
										"description": "Set value to null to delete this leaf"
									}
								]
							}
						},
						"additionalProperties": false,
					},

**I want to pick/assign oneOf the values to the mainKey .** 

**Objects inside oneOf can be of any type, hence I cannot assign type : ' object ' to the mainKey**

 **because then it will always give me { mainKey : {} } which cannot be true always,**

 **since the value can be any string { mainKey : "abc" }, number { mainKey : 123 } , etc  **

I guess there should some dynamic behavior for this.

**Comment by aitboudad** [comment]
We don't support a such format yet, try with the following schema:

```json
"items": {
  "type": "object",
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "mainKey": {
          "type": "string",
          "description": "Route policy contents as a single quoted string",
          "format": "WORD"
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "mainKey": {
          "type": "null",
          "description": "Set value to null to delete this leaf"
        }
      }
    }
  ]
}
```

**Comment by rohitb7** [comment]
Thanks for your quick reply. When can we expect this enhancement?

**Comment by aitboudad** [comment]
within 1 or 2 weeks
