### ISSUE TITLE
entry-point "@ngx-formly/core/select" has missing dependencies

### ISSUE THREAD

**Issue by bobying** [ngx-formly/ngx-formly#2530]
After I run the commands on the porject with local ngx-formly. I clone the source code  of ngx-formly to the path with project   
`
npm i
npm link ../ngx-formly/dist/@ngx-formly/core
npm link ../ngx-formly/dist/@ngx-formly/ng-zorro-antd
npm start
`
I got the error:
`The target entry-point "@ngx-formly/core/select" has missing dependencies:
 - @ngx-formly/core`

What should I do for correct the problem?

**Comment by aitboudad** [comment]
Rely on the dist folder which contains the generated `package.json` that includes that entry-point. Firstly run `npm run build` then link the desired package located in the dist folder.
