### ISSUE TITLE
Disable Attribute for Bootstrap Radio Button Options

### ISSUE THREAD

**Issue by silvl** [ngx-formly/ngx-formly#2532]
**Description**
Setting disabled: true on a radio button option does not disable the option in bootstrap UI. 
There was an issue #2489, which addressed this issue for Material UI and I see looking at the examples provided it does work. But, when use the Bootstrap UI sample for Radio and modify the template for an option to add disabled: true, it has no effect.

**Minimal Reproduction**
Using Bootstrap example provided (https://stackblitz.com/angular/gqydjyolbak?file=src%2Fapp%2Fapp.component.ts) for radio buttons, modify fields and add disabled: true for one of the options. When ran, the option is not disabled.

  fields: FormlyFieldConfig[] = [
    {
      key: 'Radio',
      type: 'radio',
      templateOptions: {
        label: 'Radio',
        placeholder: 'Placeholder',
        description: 'Description',
        required: true,
        options: [
          { value: 1, label: 'Option 1' },
          { value: 2, label: 'Option 2', disabled: true },
          { value: 3, label: 'Option 3' },
          { value: 4, label: 'Option 4' },
        ],
      },
    },
  ];

https://stackblitz.com/...

**Your Environment**

- Angular version: 9.1.12
- Formly version: 5.10.3

**Additional context**

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.4](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.4) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by mrfoster** [comment]
This is still a problem :(  For some reason `[attr.disabled]` is being overwritten by `[formlyAttributes]` unless Ivy is disabled.

It took me a long while to figure out why it was working on StackBlitz but not locally until I discovered that it was related to Ivy and StackBlitz has it disabled for some reason.

**Comment by mrfoster** [comment]
I have managed to workaround it for now by keeping Ivy and adding this extension:

```
import { FormlyExtension, FormlyFieldConfig } from '@ngx-formly/core';

export const RemoveDisabledExtension: FormlyExtension = {
  postPopulate(fieldConfig: FormlyFieldConfig) {
    if (!fieldConfig.templateOptions) {
      return;
    }

    fieldConfig.templateOptions = {
      ...fieldConfig.templateOptions,
      disabled: fieldConfig.templateOptions.disabled
        ? fieldConfig.templateOptions.disabled
        : undefined,
    };
  },
};
```

**Comment by aitboudad** [comment]
@mrfoster it should be fixed in https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.31
