### ISSUE TITLE
How can I add custom validation on fields which have changing key number based on question order

### ISSUE THREAD

**Issue by Suraj786** [ngx-formly/ngx-formly#2533]
**How can I add custom validation on fields which have changing key number based on question order**

Hey @aitboudad 

I have controls with key as a number leading with "_". E.g "_23". Reason is because we have around 700 to 800 questions.
Below is sample json for question.

```
"fieldGroup": [
    {
        "key": "_23",
        "type": "input",
        "templateOptions": {
                "label": "",
                "type": "date",
                "placeholder": "Start Date"
        }
    },
    {
        "key": "_24",
        "type": "input",
        "templateOptions": {
                "label": "",
                "type": "date",
                "placeholder": "End Date"
        }
    },
    {
        "key": "_344",
        "type": "input",
        "templateOptions": {
                "label": "",
                "type": "time",
                "placeholder": "Start Time"
        }
    },
    {
        "key": "_345",
        "type": "input",
        "templateOptions": {
                "label": "",
                "type": "time",
                "placeholder": "End Time"
        }
    }
}
```

Now I have to add custom validation for date and time fields like "End Date" field value should be greater then "Start Date". And same for Time also.
Now thing is question order may change. So how can I Implement custom validation for matching field or dependent field.

Can you please help me out with this issue. Let me know if more clarification required.

**Comment by aitboudad** [comment]
see https://formly.dev/examples/validation/matching-two-fields

**Comment by Suraj786** [comment]
In your example you have the easily accessible key name like "password", "passwordConfirm". But in my case I have unique but unidentified or not easy accessible key. So I am not able to find that control and add validation against that question. 
As mention we have 800+ questions. 

Can you please help me out @aitboudad

**Comment by kenisteward** [comment]
It may help for you to structure your questions in a hierarchical / objective way.  

My question to you is how do you know one field from another if the keys are always dynamic?  If you have the answer to that then why not just use that when you dynamically generate the fields? 


I have no clue how you are generating your fields right now but you'd take a huge performance hit by having to loop through all the fields looking for a particular title when instead you could just tie the same question to the same key.
