### ISSUE TITLE
Form.valid seems to be initially true even if config implies it's not valid

### ISSUE THREAD

**Issue by yanzacheus** [ngx-formly/ngx-formly#2535]
Hello
it seems that form is initially created with the field valid equals to true, even if the model has no valid values.
I reproduced with the introduction example : https://formly.dev/examples/introduction
Using the stackblitz provided (see https://stackblitz.com/edit/angular-s2dueu?file=src/app/app.component.html), 
I just added at the beginning of the html:
**<app-essai [valid]="form.valid"></app-essai>**
<form [formGroup]="form" (ngSubmit)="submit()">
...
where EssaiComponent just displays: <p>{{ valid}} </p>
When I run the sample, it then displays in the console: 
ERROR
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'valid: true'. Current value: 'valid: false'.
(see screenshot in the attached file)
[![form_valid_is_initially_true](https://user-images.githubusercontent.com/9139910/95660316-50abd280-0b27-11eb-90d1-d5a408fcac5f.png]
)
I think because form.valid is initially true, but becomes false because of the model (but too late), it's normal that this error occurs in development mode.
Is it possible at least to force the initial value to the right value (false) ?
Thanks

**Comment by aitboudad** [comment]
Related to the rendering order and not Formly itself, if you move the `app-essai` after the `form` the error will be gone.
```patch
-- <app-essai [valid]="form.valid"></app-essai>
<form [formGroup]="form" (ngSubmit)="submit()">...</form>
++ <app-essai [valid]="form.valid"></app-essai>
```

You may use one of the following proposals to fix the issue in your side:

1. build the form using `FormlyFormBuilder`:

```ts
import { FormlyFormBuilder } from '@ngx-formly/core';

export class AppComponent {
  constructor(private builder: FormlyFormBuilder) {}

  ngOnInit() {
    this.builder.buildForm(this.form, this.fields, this.model, this.options);
  }
}
```

1. use delay to trigger change detection:

```ts
@Component({
  selector: 'formly-app-example',
  template: `
    <formly-field-custom-input [valid]="valid$|async"></formly-field-custom-input>
    ...
  `,
})
export class AppComponent {
  valid$ = this.form.statusChanges.pipe(
    delay(100),
    map(() => this.form.valid),
  );
}
```

**Comment by kimpixel** [comment]
@if (form) {
  <button [disabled]="form.invalid" >...
}

fixed for me
