### ISSUE TITLE
double custom template invocation

### ISSUE THREAD

**Issue by ngiovin** [ngx-formly/ngx-formly#2536]
**Question**

Hi, I noticed that using a custom template (i.e. extending FieldType) causes double invocation of the related component's constructor.
Simple replication: https://stackblitz.com/edit/ngx-formly-custom-template-azyggu?file=app%2Fformly-field-input.ts
'Bye' is logged twice.
 I might be missing something. 
Tks to all

**Comment by aitboudad** [comment]
That's expected behavior (it may change in `V6`), as we use a dummy instance of those components to build the form then we construct a new instances during the render step.

**Comment by ngiovin** [comment]
Thanks for the explanation
