### ISSUE TITLE
Open MatDialog from button in an ngx-formly form

### ISSUE THREAD

**Issue by m3niza** [ngx-formly/ngx-formly#2538]
**How to add a button in a ngx-formly form that opens a MatDialog and helps to populate a textbox in the ngx-formly form**

Currently, I have a form containing two fields, name and nickname both of which are textboxes. This form is made out of ngx-formly. Currently on double-clicking the nickname textbox, a MatDialog opens up that contains another form which helps me to populate the nickname textbox on submitting the form in the MatDialog. Instead of double-clicking the nickname textbox, I would like to have a button beside the nickname textbox which says "..." and on clicking the button, it should open the MatDialog, and then it should help me populate the nickname textbox in the parent form.

Sample Stackblitz: https://stackblitz.com/github/m3niza/ngx-formly-modal

I want the double-clicking to be removed and add a button performing the above mentioned action.

**Comment by m3niza** [comment]
My provided code is not working from stackblitz but it will work from local workspace. Github: https://github.com/m3niza/ngx-formly-modal

**Comment by aitboudad** [comment]
use https://formly.dev/examples/other/material-prefix-suffix
