### ISSUE TITLE
scrollTop input mobile

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2539]
I looked in the documentation but found nothing.
I need that on mobile when clicked on one (input, autocomplete, select) scroll the scroll up and leave the field that was clicked on the top of the page.
Because on mobile, when you click on an input type field, the keyboard appears.
I would like a way to apply in all fields of type input and autocomplete, perhaps using providers.
If you have an example of how to do this with providers

I thought about creating in the focus event, but the focus event can have other functions.
So I can't subscribe the focus function

**Comment by kenisteward** [comment]
Can you give an example somewhere of what exactly you want that would be helpful.  

Right now, the only example I can currently think of is web based and doesn't require formly.  You simply select the element you want to go to (either propagated that element out generically with a formly extension or setting each field's id and selecting it with document.getElementById).

I'm not sure if when you say mobile you mean mobile code or browser code for mobile.  Either way, using default api's for scrolling should work.

**Comment by GlauberF** [comment]
@kenisteward  when you are going to fill in an information using the cell phone, when you click on an input type field, the keyboard appears (normal action on the cell phone).
I want to create an extension / providers that when the application is being accessed through the cell phone and click on an input type field, it calls a function that scrolls to the top, leaving the field in focus, always at the top of the page.
Why not the cell phone keypad when it appears in some cases is covering the field I want to fill.

I think now I have managed to explain it better.

**Comment by aitboudad** [comment]
that's out of Formly scope, you may check the following question https://stackoverflow.com/questions/23757345/android-does-not-correctly-scroll-on-input-focus-if-not-body-element
