### ISSUE TITLE
Adding fields dynamically within an accordion

### ISSUE THREAD

**Issue by nirmpate** [ngx-formly/ngx-formly#2540]
**Question**

Hello, I'm trying to add more formlyFields within an accordion-type component after the first paint of the formly form.  

In the example, I have a panel-wrapper.component.ts file.  In its ngOnInit, I am adding new formly fields within the child accordion field.  It is able to create the tabs but the input elements in each tab are not getting rendered.

Here is the example. 

https://stackblitz.com/edit/angular-o29jy7-wubwu4?file=src/app/panel-wrapper.component.ts

**Comment by aitboudad** [comment]
use PanelWrapperComponent as a type and rely on FormlyExtension events: https://stackblitz.com/edit/angular-o29jy7-c48t1g?file=src/app/panel-wrapper.component.ts

**Comment by nirmpate** [comment]
FormlyExtension events seem to fire even if a section is hidden using hideExpression.  How can I populate fields only if the section is not hidden? 

I want to add new form fields within an accordion-based on API data.  So that means I need to update the FormGroup after the prePopulate function fires.  Here's an example below where I tried calling prePopulate in ngOnInit but it didn't work.  

https://stackblitz.com/edit/angular-o29jy7-k18kwu?file=src%2Fapp%2Fpanel-wrapper.component.ts

**Comment by nirmpate** [comment]
> use PanelWrapperComponent as a type and rely on FormlyExtension events: https://stackblitz.com/edit/angular-o29jy7-c48t1g?file=src/app/panel-wrapper.component.ts

FormlyExtension events seem to fire even if a section is hidden using hideExpression. How can I populate fields only if the section is not hidden?

I want to add new form fields within an accordion-based on API data. So that means I need to update the FormGroup after the prePopulate function fires. Here's an example below where I tried calling prePopulate in ngOnInit but it didn't work.

https://stackblitz.com/edit/angular-o29jy7-k18kwu?file=src%2Fapp%2Fpanel-wrapper.component.ts
