### ISSUE TITLE
Options of a select not appear if I use it inside repeat using fieldArray

### ISSUE THREAD

**Issue by ELGUERMEZ-Meryem** [ngx-formly/ngx-formly#2542]
Hey guys, so my ts is ;

import { Component } from "@angular/core";
import { FormGroup } from "@angular/forms";
import { FormlyFormOptions, FormlyFieldConfig } from "@ngx-formly/core";

@Component({
  selector: "formly-app-example",
  templateUrl: "./app.component.html"
})
export class AppComponent {
  form = new FormGroup({});
  model = {
    investments: "111"
  };
  options: FormlyFormOptions = {};

  fields: FormlyFieldConfig[] = [
    {
      key: "investments",
      type: "repeat",
      fieldArray: { type: "select" },
      wrappers: null,
      fieldGroup: null,
      templateOptions: {
        addText: "Add (max 3)",
        options: [{ label: "dddd", value: "f" }, { label: "szz", value: "s" }],
        maxItems: 4,
        minItems: 0
      }
    }
  ];

  submit() {
    alert(JSON.stringify(this.model));
  }
}

and my repeat section ts is ;

import { Component } from "@angular/core";
import { FieldArrayType } from "@ngx-formly/core";

@Component({
  selector: "formly-repeat-section",
  template: `
    <label>{{ field.key }}</label>
    <div *ngFor="let f of field.fieldGroup; let i = index" class="row">
      <formly-field class="col" [field]="f"></formly-field>
      <div
        *ngIf="
          !to.minItems ||
          to.minItems != field.fieldGroup.length ||
          to.minItems < field.fieldGroup.length
        "
        class="col"
      >
        <button class="btn btn-danger" type="button" (click)="remove(i)">
          remove
        </button>
      </div>
    </div>
    <div
      style="margin:30px 0;"
      *ngIf="!to.maxItems || to.maxItems > field.fieldGroup.length"
    >
      <button class="btn btn-primary" type="button" (click)="add()">
        add
      </button>
    </div>
  `
})
export class RepeatTypeComponent extends FieldArrayType {}

So the problem is the list of options does not work!!!

Thanks

**Comment by aitboudad** [comment]
pass `options` to `select` type instead:

```patch
fields: FormlyFieldConfig[] = [{
  key: "investments",
  type: "repeat",
  fieldArray: {
    type: "select",
++  options: [{ label: "dddd", value: "f" }, { label: "szz", value: "s" }],
  },
  templateOptions: {
    addText: "Add (max 3)",
--  options: [{ label: "dddd", value: "f" }, { label: "szz", value: "s" }],
    maxItems: 4,
    minItems: 0
  }
}];
```
