### ISSUE TITLE
Creating Dynamic Fields using  FormlyExtension events

### ISSUE THREAD

**Issue by nirmpate** [ngx-formly/ngx-formly#2546]
use PanelWrapperComponent as a type and rely on FormlyExtension events: https://stackblitz.com/edit/angular-o29jy7-c48t1g?file=src/app/panel-wrapper.component.ts

_Originally posted by @aitboudad in https://github.com/ngx-formly/ngx-formly/issue_comments/709649147_

FormlyExtension events seem to fire even if a section is hidden using hideExpression. How can I populate fields only if the section is not hidden?

I want to add new form fields within an accordion after getting API data. So that means I need to update the FormGroup after the prePopulate function fires. 

In the example below, I tried to mock an API call by using a setTimeout within an ngOnInit to mimic updating the field at a future time.

https://stackblitz.com/edit/angular-o29jy7-k18kwu?file=src%2Fapp%2Fpanel-wrapper.component.ts

**Comment by aitboudad** [comment]
> I want to add new form fields within an accordion after getting API data. So that means I need to update the FormGroup after the prePopulate function fires.

Then you need to rebuild the form manually, that's possible but you may rely on an internal API (will be exposed in `v6`):

```patch
-- this.prePopulate(this.field);
++ (<any> this.options)._buildForm(true);
```

**Comment by nirmpate** [comment]
I see. I did notice this method but it was private.  I'm glad it will be exposed in the next version.  Thank you!

**Comment by FritzHerbers** [comment]
@aitboudad 
In the StackBlitz of the OP an initialization of the fieldGroup in prePopulate was made. I remember doing this myself some time ago and noticed strange behaviour. 

I adapted the SB: https://stackblitz.com/edit/angular-o29jy7-tzpbxr?file=src%2Fapp%2Fpanel-wrapper.component.ts
Doing an initialization in prePopulate, works, but the timeout update is not visable
Remove the initialization in prePopulate and the timeout update works

Why is it that when updating/initializing the fieldGroup in prePopulate further updates do not work?
What is allowed in prePopulate? What is strictly forbidden or better not be done in prePopulate?

**Comment by aitboudad** [comment]
@FritzHerbers `prePopulate` is called during the build step and its sync so using setTimeout inside `prePopulate ` may not work as expected. So in case, a timeout is needed, move the initialization part to ngOnInit and use the `_buildForm` call.
In the future, we may consider returning an observable from extension events.

**Comment by FritzHerbers** [comment]
@aitboudad 
Maybe I was not clear in my comment.

The prePopulate in my SB is sync it initializes a formGroup. There is a timeout set in ngOninit(), which tries to update the formGroup.

When formGroup is set in prePopulate, the overwriting in the timeout section does not work, the form is not updated/visualized.
When there is no formGroup initialisation in prePopulate, the setting/updating of formGroup in the timeout section is working and visualized.

Why is it that when updating/initializing the fieldGroup in prePopulate further updates do not work?
What is allowed in prePopulate? What is strictly forbidden or better not be done in prePopulate?
