### ISSUE TITLE
key name with dot-notation regression

### ISSUE THREAD

**Issue by silvl** [ngx-formly/ngx-formly#2547]
**Description**
In v5.1.8, the following fields configuration would work
  fields: FormlyFieldConfig[] = [
    {  key: "**applicants.1.xRelationshipTypeList**", ...  },
    { key: "applicants",
      fieldGroup: [ 
        {  key: "0",  fieldGroup: [  {  key: "firstName", ...   }    ]  },
        {  key: "1",  fieldGroup: [  {  key: "firstName", ...   }    ]  }
      ]
    }
  ];

In the latest version, this causes issues and run-time exceptions are thrown.

Please use link below to reproduce.  You will see that only the first field "applicants.1.xRelationshiptTypeList" is initially displayed.  It appears that it is attempting to auto register FormGroup controls for "applicants" and "1".

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-keyissue

**Your Environment**

- Angular version: 9
- Formly version: 5.10.2

**Additional context**
We have clients that define their own layouts and they are stored in a database so it is difficult to locate as well as manually make changes to the layouts...

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.5) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by silvl** [comment]
That fixed it.  Thank you!
