### ISSUE TITLE
Update ngx-formly/core and ngx-formly/material from 4.8.2 to 5.1.10 and facing below issue.

### ISSUE THREAD

**Issue by sagarMehta1907** [ngx-formly/ngx-formly#2548]
@aitboudad 

I am facing issues after updating @ngx-formly/core and @ngx-formly/material from 4.8.2 to 5.1.10.

![Screenshot_13](https://user-images.githubusercontent.com/73217831/96685090-3fba5700-139a-11eb-8154-b377324d8b99.png)

Please help.

**Comment by kenisteward** [comment]
Could you please try updating to the latest 5.10.4 instead?

**Comment by aitboudad** [comment]
The proper way to set the model value is through `formControl`:

```ts
this.field.formControl.setValue(new_value);
```

And for another solution since you're not passing array value to the `key` (which is a new feature) just use the following cast:

```ts
let input = this.field.key as string;
```
