### ISSUE TITLE
Formly Material Autocomplete Reset: Style not resetting (.mat-selected) / Initial style not applied

### ISSUE THREAD

**Issue by FloppyNotFound** [ngx-formly/ngx-formly#2550]
### Style not resetting
When an an autocomplete control is reset, the material style does not reset accordingly.

I have adapted the autocomplete sample and added a reset button for demonstration purposes:
https://github.com/FloppyNotFound/ngx-formly-autocomplete-style-issue

1) Open the autocomplete
2) Select an entry
3) Click reset
4) Open the autocomplete again

=> the previously selected item still has the class .mat-selected set, which causes the style to display the red background color.

Expected behavior:
the .mat-selected class is gone, no background is set.

Actual behavior:
the .mat-selected class is still set, the item has a red background.

Note: this seems to be only an issue with the styles, the component works as expected otherwise.

### Initial style not applied
There also is a probably connected issue:
when you set the selected value programmatically, or if you set an initial value, the style is not applied initially.

Reproduce:
Use the same link as above (https://github.com/FloppyNotFound/ngx-formly-autocomplete-style-issue) and replace
model = { };
with
model = { state: "Alabama" };

Expected behavior:
the .mat-selected class is applied, the selected item has a red background

Actual behavior:
the .mat-selected class is not applied, the selected item looks just like the others and has a white background.

**Comment by FloppyNotFound** [comment]
unfortunately, the stackblitz project seems broken, I'm gonna create a new one

**Comment by aitboudad** [comment]
That's material issue, I've opened an issue there https://github.com/angular/components/issues/20878, thanks!

**Comment by FloppyNotFound** [comment]
What about the second point, that the initial style is not applied? Is this a material issue too?

**Comment by aitboudad** [comment]
> Is this a material issue too?

I think so, you may add a comment in the issue https://github.com/angular/components/issues/20878 for the second point.
