### ISSUE TITLE
Pass custom dynamic wrappers and type in FormlyModule.forRoot - fails to recognize type in AOT/production Mode

### ISSUE THREAD

**Issue by nikitsatpute** [ngx-formly/ngx-formly#2551]
I am using custom formly wrappers and types in my application and exporting it to constant file.
Then I am importing in my App Module as - **FormlyModule.forRoot(formConfigConstant.APPLICATION_CONFIG)**

export const APPLICATION_CONFIG: ConfigOption = {
   wrappers:[],
  types:[]
};

But this fails to recognize types and wrappers when I run application on AOT mode i.e.
**ng serve application --aot**

Is thr way I can acheive this by passing constant to FormlyModule.ForRoot dynamically?
Thanks

**Comment by aitboudad** [comment]
try with `FORMLY_CONFIG` provider:

```ts
import { FORMLY_CONFIG } from '@ngx-formly/core';

export function registerFormlyConfig(): ConfigOption {
  return  {
    wrappers:[],
    types:[]
  };
}

@NgModule({
  imports: [],
  providers: [
    { provide: FORMLY_CONFIG, multi: true, useFactory: registerFormlyConfig },
  ],
})
export class AppModule { }
```
