### ISSUE TITLE
Typescript 4 error with property overriding accessor

### ISSUE THREAD

**Issue by aorlowski-g** [ngx-formly/ngx-formly#2552]
formControl in field-array.type.ts overrides the base class accessor which is a compiler error as of typescript 4.0

https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#properties-overriding-accessors-and-vice-versa-is-an-error

Override: https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/templates/field-array.type.ts#L11
Original declaration of the accessor: https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/src/lib/templates/field.type.ts#L23

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.5) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
