### ISSUE TITLE
Inject content with different  buttons inside a wrapper

### ISSUE THREAD

**Issue by souhail-chougrani** [ngx-formly/ngx-formly#2554]
**Question**

I'm trying to inject content  inside formly-form wrapper as mentioned in [#555](https://github.com/ngx-formly/ngx-formly/issues/555#issue-272137484) . My  content has  two buttons one for submit and other for cancel.
The probleme here is : by clicking in any button my form triggring validation and dispaly validation message as you can see in this example [Stackblitz](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-sfkars?file=src/app/app.component.html)
Is there any solution to make distinction between submitting button and other buttons?

**Comment by aitboudad** [comment]
button inside form has type submit by default so add `type` attr to button to make distinction:

```html
<button type="button">Cancel</button>
<button type="submit">Submit</button>
```

**Comment by souhail-chougrani** [comment]
@aitboudad  Thank u sooooo match
