### ISSUE TITLE
Dynamically change css classes for row

### ISSUE THREAD

**Issue by sanyashvets** [ngx-formly/ngx-formly#2556]
Hi all
The question is - how to change css classes for rows? 

Overview: 
I have REPEATING 2 rows - A and B. Row A contains some button by clicking of which - row B should be displayed
I've tried to play around with `hideExpression` and somehow toggle classes for `fieldGroupClassName` and so some stuff with button (unlucky). No success

Help is highly appreciated. Thanks in advance!

```
fields: FormlyFieldConfig[] = [
    {
      key: "topkey",
      type: "repeat",
      templateOptions: {
        addText: "Add another investment",
        haveRepeatBtn: true
      },
      fieldArray: {
        fieldGroup: [ 
          {
            fieldGroupClassName: 'display-flex',
            fieldGroup: [
              {
                type: 'button',
                templateOptions: {
                  label: 'Click this guy',
                  text: 'JSON Only',
                  btnType: 'info',
                  onClick: ($event) => {

                  },
                },
              },
              { 
                key: "images", // map to property
                type: "input", // image
                templateOptions: {
                  placeholder: "images"
                }
              },
            ],
          },
          
           {
            fieldGroupClassName: 'display-flex',
            // hideExpression: '...' play with it somehow? how?
            fieldGroup: [
              {
                className: 'flex-1',
                type: 'input',
                key: 'firstName',
                templateOptions: {
                  label: 'First Name',
                },
              },
              {
                className: '',
                type: 'input',
                key: 'lastName',
                templateOptions: {
                  label: 'Last Name',
                },
              },
            ],
          },
        ]
      }
    }
  ];
```

**Comment by aitboudad** [comment]
The question is not clear enough, so if you want to change className based on some criteria (model value) use `expressionProperties` here is an example which applies a background color to the field based on the selected value https://stackblitz.com/edit/angular-pscmpm?file=src/app/app.component.ts

**Comment by sanyashvets** [comment]
> The question is not clear enough, so if you want to change className based on some criteria (model value) use `expressionProperties` here is an example which applies a background color to the field based on the selected value https://stackblitz.com/edit/angular-pscmpm?file=src/app/app.component.ts


Yes, you have dependency between `model` and variable for `className`. In my case, I want to have a button (which is not included with `key`
(e.g. updated code:


```
fields: FormlyFieldConfig[] = [
    {
      type: 'input',
      templateOptions: {
        type: 'button',
        label: 'button'
      }
    },
    {
      key: "color",
      type: "select",
      defaultValue: "bg-red",
      templateOptions: {
        label: "Color",
        placeholder: "Select background color",
        required: true,
        options: [
          { value: "bg-red", label: "Red" },
          { value: "bg-blue", label: "Blue" },
          { value: "bg-green", label: "Green" }
        ]
      },
      expressionProperties: {
        className: model => model.color
      }
    }
  ];
```
and when user clicks on that button (which is in config, but without described `key` so it won't be available in `model` variable here
```
 expressionProperties: {
        className: model => model.color
      }
```
) I want to modify that `className` with any string

**Comment by aitboudad** [comment]
The use case is not clear enough to me please elaborate, anyway `model` is also accessible from button type so I don't see yet the issue
