### ISSUE TITLE
How to remove a element from repeat on selection of other field value

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2561]
**Question**

I have a select field and a repeat field, in the repeat field i have a text box for which i can repeat and add multiple values, now if i change the value from my select dropdown i need to check if the textboxes of repeat has value 100 if yes then remove it.
An example to illustrate more: 

Dropdown ( values : engineer and software developer)
Repeat textbook "Expenses"  (values : 100, 200)
Now when i change the value of dropdown i need to check the textboxes if it has 100 remove it and only 200 should be there.

A reproduction example is as follows:

 Stackblitz : [Click here](https://stackblitz.com/edit/angular-formly-repeat-1lqs1f?file=app/repeat-section.type.ts)

It would be helpful if someone can assist me for this.
<img width="398" alt="Screenshot 2020-10-25 at 8 12 12 PM" src="https://user-images.githubusercontent.com/12397854/97110288-6bbd3b80-16fe-11eb-95a1-0b2ed4d03268.png">

**Comment by aitboudad** [comment]
check the following example https://formly.dev/examples/advanced/repeating-section-input

**Comment by chandelshashank** [comment]
This will probably start  removing elements from the last i waana remove particular element from the repeat elements for Eg: 

Expense values 300,200,100 of repeat elements i waana remove only element having value 200. Pls refer screenshot below, it will be helpful if you can help me through this, thanks for your support. 

<img width="442" alt="Screenshot 2020-10-26 at 12 46 32 AM" src="https://user-images.githubusercontent.com/12397854/97116703-f153e200-1724-11eb-88d6-7358f1a2f0d1.png">

**Comment by aitboudad** [comment]
you may use filter to control the emitted model value:

```patch
this.model = {
  ...this.model,
+  items: this.model.items.filter(item => item.expense !== 200),
};
```

**Comment by chandelshashank** [comment]
> you may use filter to control the emitted model value:
> 
> ```diff
> this.model = {
>   ...this.model,
> +  items: this.model.items.filter(item => item.expense !== 200),
> };
> ```



> you may use filter to control the emitted model value:
> 
> ```diff
> this.model = {
>   ...this.model,
> +  items: this.model.items.filter(item => item.expense !== 200),
> };
> ```

@aitboudad  I am able to filter the value and reassign it to the model.expense but its not reflecting in UI of repeat textbox. (Modified code with stackblitz link : [stackblitz demo](https://stackblitz.com/edit/angular-formly-repeat-1lqs1f?file=app/app.component.ts)
Can you please help me into this i am stuck since 4 days :(

**Comment by aitboudad** [comment]
You should change the model and not just its property in order to be let Angular detect changes:

```patch
change: (field, $event) => {
+  this.model = {
+    ...this.model,
+    expenses: this.model.expenses.filter(x => x.value !== "200")
+  };
}
```

https://stackblitz.com/edit/angular-formly-repeat-zm5q5x?file=app/app.component.ts

**Comment by chandelshashank** [comment]
The solution provided by you works fine but in case I am using multiple fields in which on load I am initializing some of the values in the model and for any changes in the model I explicitly call my onModelchange customized function. Here I put my code of  this.model = { ...this.model } but in my case, it resets the default value of some field how can I avert this while using this.model = { ...this.model }, need your help @aitboudad  badly as i am stuck into this.

**Comment by aitboudad** [comment]
not clear enough to me better provide a reproduction
