### ISSUE TITLE
How to config all inputs and outputs for custom component?

### ISSUE THREAD

**Issue by 10229428** [ngx-formly/ngx-formly#2563]
**Question I**

I have a custom component, which has some input properties and output events, for example, 'colorType', 'preSize', 'icon', and so on. Do I need define all properties in the component class, like below:
```
@Component({
    selector: 'formly-custom-button',
    template: `
        <custom-button [colorType]="to.colorType"
                       [disabled]="to.disabled"
                       [preSize]="to.preSize"
                       [width]="to.width"
                       [height]="to.height"
                       [icon]="to.icon"
                       (xxxEvent)="to.xxxEvent && to.xxxEvent($event)"
                       (click)="to.click && to.click($event)">
            {{ to.text }}
        </custom-button>
    `,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FormlyCustomButton extends FieldType {}
```
config:
```
fields: FormlyFieldConfig[] = [{
        type: 'jigsaw-button',
        templateOptions: {
            text: 'FormlyJigsawButton',
            disabled: false,
            preSize: 'default',
            colorType: 'primary',
            icon: 'fa fa-edit',
            height: 60,
            width: '200px',
            click: ($event) => alert('You clicked me!'),
        },
        expressionProperties: {
            'templateOptions.disabled': 'model.checkbox',
        }
}];
```
If the component have many inputs and outputs, it will be very cumbersome. Is there an easy way？

**Question II**
My custom componen can accept the content between tag, implement by `ng-content`. How can I config the html template, which can be projected to the component?

**Comment by aitboudad** [comment]
> Question I

I really need such a feature but unfortunately not possible with Angular, in React they use a spread operator:

```
<Button {...props}></Button>
```

> Question II

The question is not clear, you may use CDK Portal to project a component see https://github.com/ngx-formly/ngx-formly/issues/555#issuecomment-342776429

**Comment by Alberto02001** [comment]
Hei is this been solved ? Can you link to me a example ?
