### ISSUE TITLE
Ref to closed issue with dynamic update if css classes

### ISSUE THREAD

**Issue by sanyashvets** [ngx-formly/ngx-formly#2564]
Sorry for creating the new one, but prev. issue was closed

The question is not clear enough, so if you want to change className based on some criteria (model value) use `expressionProperties` here is an example which applies a background color to the field based on the selected value https://stackblitz.com/edit/angular-pscmpm?file=src/app/app.component.ts

_Originally posted by @aitboudad in https://github.com/ngx-formly/ngx-formly/issues/2556#issuecomment-716139942_

My reply link is https://github.com/ngx-formly/ngx-formly/issues/2556#issuecomment-716416644

**Comment by aitboudad** [comment]
No need to create a new issue, I rely on `github` notification to track issue comments
