### ISSUE TITLE
Support for checkbox List 

### ISSUE THREAD

**Issue by jtushar53** [ngx-formly/ngx-formly#2565]
**Question**
On mobile phones it is better to have checkboxes as a list, just like below. How to create one 
https://stackblitz.com/angular/pbrqonoeojn?file=src%2Fapp%2Flist-selection-example.ts

A clear and concise description of what the question is.

I am using material theme and wanted to display checkboxes with list just like below

Anybody please help on making this UI, also wanted to add a header , still trying to figure out how should i goo ahead,  i've created a custom field first with checkbox and created a wrapper which can add a header to that list

stuck in the first part, getting below error

![image](https://user-images.githubusercontent.com/48051351/97167790-6c60db00-17ad-11eb-8459-5e06a67ddf3f.png)

**Comment by aitboudad** [comment]
Please provide a `stackblitz` of your work in order to check what you've missed!

**Comment by aitboudad** [comment]
To create a custom type, just follow our doc https://formly.dev/guide/custom-formly-field,
also, there is a multi checkbox type which you may use instead https://stackblitz.com/edit/angular-tab7ut
