### ISSUE TITLE
expressionProperties evaluated before field constructed/ngOnInit events regression

### ISSUE THREAD

**Issue by silvl** [ngx-formly/ngx-formly#2566]
**Description**
In v5.1.8, expressionProperties were not evaluated until after ngOnInit.

In the latest version, expressionProperties are evaluated prior to field's constructor/ngOnInit being triggered

**Minimal Reproduction**
https://stackblitz.com/edit/angular-4sg11v

**Your Environment**

- Angular version: 9
- Formly version: 5.10.5

**Additional context**

**Comment by aitboudad** [comment]
not true, can you provide an example?

**Comment by silvl** [comment]
Sorry, forgot to add stackblitz project.  Updated original issue above.  

Note, if you open the console window, I am logging when the expression is called and when onInit is triggered.  The expression is being evaluated prior to the onInit.

**Comment by aitboudad** [comment]
I've got the same result with `v5.1.8`, expressions are evaluated during the build step (before onInit call)

**Comment by silvl** [comment]
You are correct. I have looked into this further.  The problem I am seeing is caused by the changes to the FieldExpressionExtension. If an expression refers to an object that does not exist until after the onInit, an exception is being thrown in the latest version, but was not in v5.1.8.

I have a templateOption ladda that accepts a simple Boolean value or a configuration object.  If initially set using a Boolean value, it is modified in the onInit procedure to reference the full object with default values set depending if ladda was set to true or false.

If v5.1.8, the expressionValueSetter was being done as follows:

` const expressionValueSetter = evalExpressionValueSetter(`field.${key}`, ['expressionValue', 'model', 'field']);
`

Thus when setting the value field.templateOptions.ladda.show and ladda was not converted to an object yet in the onInit hook, it was not throwing an exception. 


In the latest version, FieldExpressionExtension was changed to do the following when setting the expression value, which does not handle it the same and is throwing an exception.

```
  setExprValue(field, prop, value) {
        try {
            /** @type {?} */
            let target = field;
            /** @type {?} */
            const paths = (prop.indexOf('[') === -1 ? prop : prop.replace(/\[(\w+)\]/g, '.$1')).split('.');
            /** @type {?} */
            const lastIndex = paths.length - 1;
            for (let i = 0; i < lastIndex; i++) {
                target = target[paths[i]];
            }
            target[paths[lastIndex]] = value;
        }
        catch (error) {
            error.message = `[Formly Error] [Expression "${prop}"] ${error.message}`;
            throw error;
        }
        if (prop === 'templateOptions.disabled' && field.key) {
            this.setDisabledState(field, value);
        }
        if (prop.indexOf('model.') === 0) {
            /** @type {?} */
            const path = prop.replace(/^model\./, '');
            /** @type {?} */
            const control = field.key && prop === path ? field.formControl : field.parent.formControl.get(path);
            if (control
                && !(isNullOrUndefined(control.value) && isNullOrUndefined(value))
                && control.value !== value) {
                control.patchValue(value, { emitEvent: false });
            }
        }
        this.emitExpressionChanges(field, prop, value);
    }

```

**Comment by aitboudad** [comment]
could please update the above stackblitz with a small reproduction example? thanks!

**Comment by silvl** [comment]
I have updated the above stackblitz.  Thank you for your help.

**Comment by aitboudad** [comment]
I would prefer to not fix it on our side and instead try to find an alternative way to avoid relying on such behavior unless you've no choice!

**Comment by aitboudad** [comment]
Feel free to reopen in case you need any help on that part.

**Comment by silvl** [comment]
The issue is I cannot fix this by changing the json config as there are many and they are stored in the database.  Do you have any ideas for a workaround?

**Comment by silvl** [comment]
Hi @aitboudad, Thank you for reopening this issue.  Do you have any thoughts?

**Comment by aitboudad** [comment]
Hi, sorry still not having the time for this issue. Probably next week so my plan is to provide a fix unless we've got a workaround.

**Comment by silvl** [comment]
Thank you for the update.

**Comment by aitboudad** [comment]
@silvl instead of `onInit` use `onPopulate`, please give it a try and let me know if that fix your issue:

```ts
export class FormlyFieldButton extends FieldType {
  onPopulate(f: FormlyFieldConfig) {
    const to = f.templateOptions;
    if (to.ladda === true) {
      to.ladda = { show: true }
    } else if (to.ladda === false) {
      to.ladda = { show: false }
    }
  }
}
```

**Comment by silvl** [comment]
HI @aitboudad,  that works!  The onPopulate is called early enough in the lifecycle.
