### ISSUE TITLE
Formly/Angular-Material Select Multiple - selectAll should not select disabled mat-option.

### ISSUE THREAD

**Issue by singhinderpal** [ngx-formly/ngx-formly#2568]
Hi, I find formly to be a great tool to create reactive forms and easier the process of handling models.

**Description**
I am using formly with angular material. When an option is disabled, selectAllOption must not select the disabled mat-option!

**Demo**
I created a demo, which can be seen here-
https://stackblitz.com/edit/ngx-formly-ui-material-wdcvcg?file=src/app/app.component.ts

PS- I am new to formly and if this was designed to be like this intentionally & was not an issue, I request you to pardon me in that case.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.6) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
