### ISSUE TITLE
oneOf default values are not restored after an hide/show

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2569]
**Description**
When a JSONSchema oneOf field is hide and show again, the default values are lost.

**Minimal Reproduction**

https://stackblitz.com/edit/formly-oneof-default?file=src/assets/json-schema/oneOf.json

Hide and show the field using the "show/hide" button. The default value disappears.

**Your Environment**

- Angular version: 7.2
- Formly version: 5.10.5

**Additional context**
Seems broken since 5.10.2

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.6) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
