### ISSUE TITLE
Control resetOnHide for a specific field

### ISSUE THREAD

**Issue by Suraj786** [ngx-formly/ngx-formly#2570]
**Description**
Hideexpression is not working with repeat and ngx-datatable control

[demo link](https://stackblitz.com/edit/angular-nbze38-ma3dmg)

**Your Environment**
- Angular version: 8.1.2
- Formly version: 5.10.5

**Additional context**
Even we have nested hideexpression inside repeat control. 
Can you please help me find a solution.

Thanks in advance.

**Comment by aitboudad** [comment]
The passed model value for `fieldArray` and `fieldGroup` is the scoped one, what you're looking for is the root model which can be accessed using `field.parent.model` https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

**Comment by Suraj786** [comment]
Thanks for the reply,

Now I have added the `field.parent.model` but if you see when we switch radio button options 2-3 times then datatable's initial values will disappear. 
Even on repeater if you click on add another then nested hideexpression wont work in that case.

updated demo link - [https://stackblitz.com/edit/angular-nbze38-retv6u](https://stackblitz.com/edit/angular-nbze38-retv6u)

can you please have a look at this scenario.

Thanks in advance.

**Comment by aitboudad** [comment]
I think that's expected behavior when `resetFieldOnHide` is enabled as Formly expected a valid initial model value (when the radio button is empty the data table data should be empty).

**Comment by Suraj786** [comment]
Hi @aitboudad 

Can we have feature like `autoClear: false` for control level we don't reset for few selected control when on module we have `resetFieldOnHide: true`.
So on above example datatable can retain its initial values.

Can you please have a look at this scenario.
Thanks in advance.

**Comment by Suraj786** [comment]
Hi @aitboudad 

Can you please help me out on above commented scenario. Sorry for bothering you but I am stuck on that issue.
[Above comment](https://github.com/ngx-formly/ngx-formly/issues/2570#issuecomment-738596546)

Thanks in advance.

**Comment by aitboudad** [comment]
did you try to pass `autoClear: false`, its an internal feature which we may expose later

**Comment by Suraj786** [comment]
Hi @aitboudad 

Yes, I have tried adding `autoClear: false` but its showing below error.
Object literal may only specify known properties, and `autoClear` does not exist in type `FormlyFieldConfig`.

Even after removing `FormlyFieldConfig`  type its not working.

I am using Formly `version: 5.10.5`

Thanks in advance.

**Comment by aitboudad** [comment]
it's not part of FormlyFieldConfig yet also make sure to pass it to all field children as it doesn't take account of the parent state.

**Comment by Suraj786** [comment]
Hi @aitboudad 

I have tried that also, it's not working. Might be I'm doing something wrong. Can you please update on this
[Demo Link](https://stackblitz.com/edit/angular-nbze38-retv6u)

Thanks in advance.

**Comment by aitboudad** [comment]
added a fix in `5.10.8`, instead of `autoClear` use `resetOnHide` but still a hidden feature.

**Comment by Suraj786** [comment]
Hi @aitboudad 

It's working fine as expected.
Thanks for the update and fixes.

**Comment by Suraj786** [comment]
Hi @aitboudad 

Found other issue after package update. We have checkbox on datatable row. based on selection we are enabling remaining column data. But looks like there is some issue with your recent checkbox update. 
[Sample Link](https://stackblitz.com/edit/angular-nbze38-9tgxfb)

Can you please have a look.
Thanks in advance.

**Comment by aitboudad** [comment]
that's a bug I'll try to fix it in the next release, for a workaround:

```patch
{
  type: "checkbox",
  key: "investmentDate",
+  expressionProperties: {
+    ["templateOptions.disabled"]: "false"
+  }
},
```

**Comment by aitboudad** [comment]
pushed a fix for disabled state issue in `5.10.9`

**Comment by KamilSocha91** [comment]
This should be closed issue?

**Comment by aitboudad** [comment]
not yet, still not part of the public API.
