### ISSUE TITLE
 value after parsers not reflected in formControl.value

### ISSUE THREAD

**Issue by dhiliptdk** [ngx-formly/ngx-formly#2573]
using parsers for field sometimes not reflecting in `formControl.value`, I guess workaround for https://github.com/angular/angular/issues/13792 causing this problem. 
[](url)
https://github.com/ngx-formly/ngx-formly/blob/0a76c7e9b1a1264d4d1b3abec611d9ddf46ba69f/src/core/src/lib/components/formly.field.ts#L209-L216

here `patchValue` is applied before applying parsers pipeline.
i think reordering the code like 
``` 
if (field.parsers && field.parsers.length > 0) { 
   field.parsers.forEach((parserFn) => (value = parserFn(value))); 
 }

// workaround for https://github.com/angular/angular/issues/13792 
 if (control instanceof FormControl && control['_fields'] && control['_fields'].length > 1) { 
   control.patchValue(value, { emitEvent: false, onlySelf: true }); 
 } 
  

```
may resolve but not sure it may cause any other issue. 
happy to receive suggestions on how to resolve? or what to do ?

**Comment by aitboudad** [comment]
That's not a bug because the parser concern the emitted model value, I think you're looking for a formatter which can be done using ngx-mask https://stackoverflow.com/questions/59736785/how-do-i-format-a-value-in-angular-formly/59741142#59741142
