### ISSUE TITLE
Formly Ionic requires @ionic/angular@^4.0.0 but Ionic's default is now ^5.0.0

### ISSUE THREAD

**Issue by battika** [ngx-formly/ngx-formly#2575]
**Description**
When I attempt to install @ngx-formly/ionic v 5.10.5 it is giving me a warning:
npm WARN @ngx-formly/ionic@5.10.5 requires a peer of @ionic/angular@^4.0.0 but none is installed. You must install peer dependencies yourself.

**Minimal Reproduction**
Unfortunately no Stackblitz example due to the missing dependency.

1. Create a basic Ionic Angular project, eg. using ionic start FormlyTest blank
2. Add the required Formly dependencies, "@ngx-formly/core": "^5.0.0" and "@ngx-formly/ionic": "^5.0.0" to package.json
3. Run npm install

**Your Environment**

- Angular version: 10.0.14
- Formly version: 5.10.5

**Comment by battika** [comment]
Thanks @aitboudad !

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.6) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
