### ISSUE TITLE
Any way to provide MaterialSelect default option without a "hack"?

### ISSUE THREAD

**Issue by renatoaraujoc** [ngx-formly/ngx-formly#2580]
**Question**

Hello,

Is there any way to provide a "select empty"/default select option using MaterialSelect?

This is what I want to accomplish right now:

![Captura de Tela 2020-11-02 às 19 16 18](https://user-images.githubusercontent.com/358128/97925277-e3fbb080-1d3f-11eb-8dca-26378af5900a.png)

This is how the code is structured to achieve a "null" value right now.

```typescript
{
  key: 'tipo',
  type: 'select',
  className: 'flex-1',
  defaultValue: 'null', // does not work if put null
  templateOptions: {
  label: 'Tipo',
  options: [{
      label: 'Selecione...',
      value: 'null' // thus why null has to be a string here
  }].concat(data.tipos.map(tipo => ({
      label: tipo.names.pt,
      value: `${tipo.id}` // and these values also be a string (wanted them to be number)
  })))
}
```

Thank you!

Renato

**Comment by aitboudad** [comment]
That's a material issue as I'm unable to get it working with `mat-select` either https://stackblitz.com/edit/angular-gxxcsq.

Please fill an issue in the [material](https://github.com/angular/components) repo instead.
