### ISSUE TITLE
ResetModel and updateInitialValue form options does not work when model is updated within code

### ISSUE THREAD

**Issue by lohiaad** [ngx-formly/ngx-formly#2581]
**Description**
ResetModel and updateInitialValue form options does not work when model is updated within code

**Minimal Reproduction**
https://ngx-formly-edit-model-reset.stackblitz.io

**Steps to reproduce**
1. Enter some value in text and options
2. click on `Update initial Values` button
3. click on `edit` button
4. click on `reset` button

**Current behaviour**
model / form values are not getting reset to initial value. it takes editModel value.

**Actual behaviour**
model / form values should get reset to initial value.

**Your Environment**

- Angular version: 7
- Formly version: 5.10

**Comment by aitboudad** [comment]
That`s expected behavior when the model input changes the initial value is updated too.

**Comment by lohiaad** [comment]
what is your recommended solution to implement this scenario. 
currently i am storing initial model values in temp variable then whenever i want to reset i just replace model with temp variable. is this correct approach?

**Comment by aitboudad** [comment]
I think so, or you can pass the `initialModel` to `resetModel` method:

```ts
options.resetModel(initialModel)
```
