### ISSUE TITLE
Nebular theme support for ngx-formly

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2583]
@aitboudad 

I have seen that you have a feature for adding Nebular theme support in the near future.

I wanted to bring to your attention some of the great work that Vijay has put in building a library around it.

His work can be found here.

[https://github.com/vijhhh2/Nebular-Formly](https://github.com/vijhhh2/Nebular-Formly
)
It will be good if the two of you can collaborate and figure out the next steps.

Thanks

**Comment by aitboudad** [comment]
see #2557

**Comment by argupta23** [comment]
@aitboudad 

I had asked Vijay to reach out to you as well, but missed thread #2557.
It is good that Vijay and you have connected.

The one question I have is when integrated into the main branch would it also support the other features that come with bootstrap and material UI?

**Comment by aitboudad** [comment]
> The one question I have is when integrated into the main branch would it also support the other features that come with bootstrap and material UI?

Yes
