### ISSUE TITLE
Boolean without default value is not set in form value on submit

### ISSUE THREAD

**Issue by Adam-Michalski** [ngx-formly/ngx-formly#2584]
Boolean without default value is not set in form value on submit
But when I check it and uncheck it everything is ok. There is this first initialization missing I think. 
For third option state we need to create different control for formly, so I think this third state when nothing is set is not used.
Is this as expected? 

**Expected behaviour**
As I expect boolean has two values true/false
So when default value is not set then we have falsy values in boolean fields => field is set to false

**Minimal Reproduction**
https://stackblitz.com/edit/angular-boolean-example?file=src/app/app.component.ts

**Environment**
- Angular version: any
- Formly version: any

**Comment by aitboudad** [comment]
I think that's expected so either mark the field as required or use the default value
