### ISSUE TITLE
Marking optional vs required fields

### ISSUE THREAD

**Issue by rickvandermey** [ngx-formly/ngx-formly#2586]
Hi, 

There is always a lot of discussion about the fact wether to mark required fields with an asterisk or marking optional fields with a 'custom tag' (eg. optional): https://uxdesign.cc/form-field-required-vs-optional-9b4d7cdbf400

We would like a setting wether to choose between one or the other for our projects. 
Is something like this already possible?

**Comment by aitboudad** [comment]
you can hide the asterisk by passing `true` to the following option: `hideRequiredMarker`:

```patch
{
  key: 'name',
  templateOptions: {
+   hideRequiredMarker: true
  }
}
```

**Comment by rickvandermey** [comment]
and how about the `showOptionalMarker: boolean` and `optionalMarkerLabel: string = 'optional'`

**Comment by aitboudad** [comment]
I think `hideRequiredMarker` is also good so I don't see the need for changing the option name unless there is a good reason!
