### ISSUE TITLE
hideExpression is not working when used with wrappers

### ISSUE THREAD

**Issue by suraj740** [ngx-formly/ngx-formly#2587]
Hi, I want to hide some fields by default and  show it after some condition is met.
I am using hideExpression as mentioned in document, it doesnt work when i use wrappers.
How can we achieve the same using wrappers.

Here is the reproducible example of the same.[Link](https://stackblitz.com/edit/angular-yu7bzv-oz4hz8?file=src%2Fapp%2Fapp.component.ts)

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

**Comment by suraj740** [comment]
It doesnt work when we use wrappers and how can we acheive the same with json powered forms.

**Comment by aitboudad** [comment]
For json powered forms you may try with `field.parent.model`:

```json
"hideExpression": "field.parent.model.name === 'ddd'"
```
