### ISSUE TITLE
Error on enable/disable with kendo latest source

### ISSUE THREAD

**Issue by luizfbicalho** [ngx-formly/ngx-formly#2588]
**Description**
THIS ERROR DOESN'T HAPPEN WITH THE LATEST VERSION (5.10.6), ONLY WITH LATEST SOURCE OF KENDO PACKAGE

**Minimal Reproduction**
I updated the https://stackblitz.com/angular/xlboxbbqapo?file=src%2Fapp%2Fapp.component.ts with latest version of angular
and added a feature to enable and disable the form
after that, if I update the kendo components to the latest version with onpush
if I disable, the combo doesn't get disabled, if I click on the combo it disables, and after that I can't enable it anymore.

https://stackblitz.com/edit/angular-ivy-ptynw2?file=src%2Fapp%2Fapp.module.ts

**Your Environment**

- Angular version: 10.2.3
- Formly version: 5.10.6

**Additional context**
Seems to be related to the ChangeDetectionStrategy.OnPush on the wrapper and the select

I'm making many components for kendo
select with filter, Multiselect, grid, treegrid
and I'm stuck on this problem, I would like to collaborate with this components after that

[package.zip](https://github.com/ngx-formly/ngx-formly/files/5518740/package.zip)

**Comment by 3g2ld1n0** [comment]
Hi, I'm also waiting for this component

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
