### ISSUE TITLE
Repeat section

### ISSUE THREAD

**Issue by Satishreddy29** [ngx-formly/ngx-formly#2589]
Hi,

I'm using form with pagination , Inside the form I have fomly repeat section with dynamically formed controls .
On the first page the dynamic controls inside the repeater works good , but on the next page controls are not forming dynamically its repeating the same type of controls shown in the first page.

Is there any example for this scenario to follow.

Thanks

**Comment by aitboudad** [comment]
On paginate you need to trigger the model changes anyway a reproduction example using stackblitz is needed 🙏!

**Comment by Satishreddy29** [comment]
Thanks for your response. I fixed my issue.
