### ISSUE TITLE
Nested element using material stepper not working ?

### ISSUE THREAD

**Issue by mignam** [ngx-formly/ngx-formly#2590]
**Question**

Why my model is not nested when using a Stepper ?

I don't understand why, with the same fields definition, my model structure is different when i use a Stepper.

**I want**
```
{
 cat1: {
    input: data
  },
 cat2: {
    textarea: data
  },
}
```
I have this when not using stepper

**I have**
```
{
    input: data,
    textarea: data
}
```
 i have this when using stepper

Thanks for your help :)

i reproduced it here:

https://stackblitz.com/edit/ngx-formly-ui-material-qnn4tv

**Comment by aitboudad** [comment]
Hi, the above example work as expected, Am I missing something?

**Comment by mignam** [comment]
Whoops, sorry. 

Now, i reproduced it.

https://stackblitz.com/edit/ngx-formly-ui-material-qnn4tv

My model is not nested :(

**Comment by aitboudad** [comment]
You've passed the `fieldGroup` object to `formly-form` which doesn't include the step key `cat1` so either includes the key inside `fieldGroup` or use our new solution which rely on a custom field type https://formly.dev/examples/advanced/multi-step-form

**Comment by mignam** [comment]
Thank's ! I've updated my example, i passed the step key in the fieldGroup, so i had to change my fields Model. 
It's working. 👍
