### ISSUE TITLE
Make repeating input readonly

### ISSUE THREAD

**Issue by Malkoba1982** [ngx-formly/ngx-formly#2591]
Hi,
First of all, Thank you very much for the awesome implementation. This is a question and not an issue. I seems unable to select this as a question.

I'm new to angular and formly altogether. I have created a repeating control with just 1 input box. What I want is to make all the previous inputs readonly once I click the add button. Only the new input added should be editable. I tried with expression properties, but seems I cannot get it to work. Following is the repeating control.
<div *ngFor=.........>
<formly-field ..........>
<button click="remove(i)></button>
</div>
<button click="add()></button>

in the field array, I have defined an input field.

Any help is really appreciated.

**Comment by kenisteward** [comment]
Setup a stackblitz with the problem you are having and I'll try to get back to you asao

**Comment by Malkoba1982** [comment]
This is my code.
<div *ngFor=.......>
<formly-field [field]="field"></

**Comment by Malkoba1982** [comment]
Sorry my bad. Please find the link for stackblitz below.
https://stackblitz.com/edit/angular-ivy-4btut8

**Comment by kenisteward** [comment]
https://stackblitz.com/edit/angular-ivy-bvvt89

this does exactly what you want.  you can also do this just string-based by converting the arrow function body to a string

**Comment by Malkoba1982** [comment]
Perfect. Thank you very much. :+1:
