### ISSUE TITLE
How can I reorder complex repeat section without breaking model ?

### ISSUE THREAD

**Issue by comrem** [ngx-formly/ngx-formly#2592]
**Context**

I am having troubles handling complex repeat-sections with nested fields inside. I achieved pretty much everything that I needed to do with formly excepted for a particular but very important point for my app in repeat-sections, which is reordering sections. Those repeat sections permit to generate an array of sections with particular properties, in my example there are sections of type (myType) 'a' and 'b' and I'm trying to move the sections up or down in the array. 
The core problem is that my app's behavior is based on onInit hook. I would have used hideExpression if I could  but my app has a recursively generated part, then I didn't succeed using hideExpression.
I tried with onChanges hooks but didn't succeed either, while I wasn't able to get the information of which section I moved, especially when moving 'up' the section.

**Question**

How could I reorder sections in a repeat-section without breaking the bindings with the model/field/form ?
One of my idea is to rely on resetFieldOnHide, but to achieve this I have to recalculate the hide value of my options for each sections when moving a section, and I don't know how to get the info in definitions of _fields_ that something was moved.

**Minimal reproduction example**

https://stackblitz.com/edit/repeat-section-move-with-options

As you can see in the example the move up button merges models of the section that was above and the section we try to move, and the moved section doesn't show the corresponding inputs since it didn't pass the onInit hook. The problem also occurs on down button for larger array. 

Thanks for help, have a great day !

**Comment by aitboudad** [comment]
`hideExpression` would solve the issue else an entire re-render is required. Try the following solution instead https://stackblitz.com/edit/repeat-section-move-with-options-9e51cv?file=src/app/repeat-section.type.ts

**Comment by comrem** [comment]
Well the answer is pretty much working but there is a weird behavior : when you move a section twice, the model ends up merged. I didn't find the origin of this issue yet, do you have any idea @aitboudad ?

Thank you su much for spending time helping people who try to use formly

**Comment by aitboudad** [comment]
> when you move a section twice

would you please provide the reproduction steps?

**Comment by comrem** [comment]
> would you please provide the reproduction steps?

Yes of course : 

1. write something in sub option 1 and/or sub option 2
2. move one of the section up or down
3. move again one of the section up or down
4. see model for b type, _options_ contains both options corresponding to a and to b

**Comment by aitboudad** [comment]
Updated the example so instead of `buildForm` call, just reorder the fields.

**Comment by comrem** [comment]
Thank you for your time and patience, this is working perfectly as expected, and solves most of my app's problems !

**Comment by FritzHerbers** [comment]
@aitboudad 
Reordering might become a common requirement. As not all are familiar with ngx-formly's internas it would be nice to have a method available:
```
reorder(i1: number, i2: number, { markAsDirty } = { markAsDirty: true })
```

**Comment by aitboudad** [comment]
@FritzHerbers make sense, not sure about the method signature 🤔, PR welcomed!
