### ISSUE TITLE
Need to build a complex type for terms agreements

### ISSUE THREAD

**Issue by madmiki80** [ngx-formly/ngx-formly#2594]
Hi, I have to create a custom type but I'm not sure how to start.
I need to create an agreement checkbox with custom label text containing a link opening a modal with agreement text.

This is an example of what i need to have:

![Cattura](https://user-images.githubusercontent.com/19203476/99644225-f53a0200-2a4d-11eb-971c-02dfd991964a.JPG)

Any suggestion on how i have to proceed , any advice or example ?

TY 👍

**Comment by aldovelco** [comment]
You could create a custom field type and register it with formly. You should be able to add the modal inside it.
Just create an angular component extending FieldType and inject your modal service or whatever you're using for modals.
https://formly.dev/guide/custom-formly-field

I like to go through the source code for formly's ui libraries for inspiration/tips when creating my own custom fields. i.e.
https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/material/checkbox/src/checkbox.type.ts

**Comment by aitboudad** [comment]
Thank you @aldovelco!
