### ISSUE TITLE
Field parent sometimes doesn't have key

### ISSUE THREAD

**Issue by Pietrex** [ngx-formly/ngx-formly#2595]
Is there rule when fields have key property?
We use formly (v5.10.1) with json schema and combine `key` properties from parents to create field path.
For most schemas it works seamlessly, but with `oneOf` field in schema we lose `key` property in parents.

Steps to reproduce - log `this.field.parent.key` in ngOnInit inside src\ui\bootstrap\input\src\input.type.ts and go to json schema example. Then click through tabs - for some fields their parents have `key`, for some they haven't

Is this behavior desired?

Thank you

**Comment by aitboudad** [comment]
`key` is optional which provides a way to create a virtual group, for `json-schema` I think it is necessary for `oneOf` implementation but we're willing to remove any extra/unnecessary group.

Thanks for asking :) and sorry for the late reply!
