### ISSUE TITLE
Support bootstrap 5 and floatting labels

### ISSUE THREAD

**Issue by rmannibucau** [ngx-formly/ngx-formly#2603]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use bootstrap v5 floating labels without writing a custom wrapper (https://v5.getbootstrap.com/docs/5.0/forms/floating-labels/).

**Describe the solution you'd like**
A proper bootstrap v5 support with a global option at module level to enable floating labels would be neat (or worse case in form options).

**Describe alternatives you've considered**
Writing the wrapper myself but it is not satisfying on the long run and seems to be a built in feature.

**Comment by aitboudad** [comment]
still too early for us to rely on v5 (alpha version), just override the default `form-field` wrapper to take account of floating labels, check the horizontal layout example https://stackblitz.com/edit/angular-wvczwc-c6q9q4

**Comment by rmannibucau** [comment]
@aitboudad when do you plan to support it? on rc? Final is supposed to come this month https://mdbootstrap.com/docs/standard/bootstrap-5/#section-next-releases

**Comment by aitboudad** [comment]
> when do you plan to support it? on rc?

rc

**Note**: The above link is not a bootstrap roadmap, I would expect some months before rc release
