### ISSUE TITLE
Output a value in a label

### ISSUE THREAD

**Issue by Luca-diciannove** [ngx-formly/ngx-formly#2604]
I have a very simple form, and i'd like to output a variable, passed to the form, inside a label.

For example, in a form to input a weight measurement, i'd like to write the unit of measure next to the input box (es. Kg). The unit of measure would be the variable i pass to the form.

Is it possible?
Thank you very much!!

**Comment by aitboudad** [comment]
not sure which UI do you use:
- for bootstrap use addons https://formly.dev/examples/bootstrap-specific/input-add-ons
- for material use suffix https://formly.dev/examples/other/material-prefix-suffix
