### ISSUE TITLE
fieldGroup not populating on add() when repeat type is loaded first in parent fieldGroup

### ISSUE THREAD

**Issue by joncorrin** [ngx-formly/ngx-formly#2606]
**Question**
Do you have any idea why fieldGroup wouldnt populate the correct object when my repeat field type if first in the parent fieldGroup array? 

**Description**
I have a fairly complex form that I've created with formly as the logic engine (see below all the custom types). 
```
  imports: [
    FormlyModule.forRoot({
      types: [
        { name: 'repeat', component: RepeatTypeComponent },
        { 
          name: 'intake-repeat', 
          component: IntakeRepeatTypeComponent,
          defaultOptions: { defaultValue: [] }
        },
        { 
          name: 'customer-repeat', 
          component: CustomerRepeatTypeComponent,
          defaultOptions: { defaultValue: [] }
        },
        {
          name: 'customer-section',
          component: CustomerSectionTypeComponent,
          defaultOptions: { defaultValue: {} }
        },
        {
          name: 'intake-section',
          component: IntakeSectionTypeComponent,
          defaultOptions: { defaultValue: {} }
        },
        {
          name: 'customer-form',
          component: CustomerFormTypeComponent,
          defaultOptions: { defaultValue: {} }
        },
        {
          name: 'intake-form',
          component: FormIntakeTypeComponent,
          defaultOptions: { defaultValue: {} }
        },
        {
          name: 'question-group',
          component: QuestionGroupTypeComponent,
          defaultOptions: { defaultValue: {} }
        },
        { name: 'address', component: AddressComponent },
        { name: 'input', component: CustomInputComponent },
        { name: 'firstName', component: CustomFirstNameComponent },
        { name: 'lastName', component: CustomLastNameComponent },
        { name: 'select', component: CustomSelectComponent },
        { name: 'radio', component: CustomRadioComponent },
        { name: 'checkbox', component: CustomCheckboxComponent },
        { name: 'phonenumber', component: PhoneNumberComponent },
        { name: 'textarea', component: CustomTextareaComponent },
        { name: 'table', component: CustomTableComponent },
      ],
      wrappers: [
        { name: 'customer-section-panel', component: FormViewerCustomerSectionPanelWrapperComponent},
        { name: 'question-panel', component: FormViewerQuestionPanelWrapperComponent },
        {
          name: 'section-panel',
          component: FormViewerSectionPanelWrapperComponent,
        },
      ],
    })
....
```

In this form I have a repeat type similar to your stepper example that shows or hides sections based on the active index. In order to get the repeat type to work, I have to run the add() method on init so that the data is populated correctly (see below): 

.ts file
```
  ngOnInit() {
    if (this.field.fieldGroup && this.field.fieldGroup.length === 0) {
      this.add();
    }
  }
```

.html file
```
<div 
    *ngFor="let fg of field.fieldGroup; let index = index;">
    <formly-field *ngIf="to.subIndex === index" [field]="fg"></formly-field>
</div>
```

Ideally I'd create an example on stackblitz but I can't seem to reproduce it and because its a complex implementation its hard to copy everything over. 

My question to you is do you have any idea why fieldGroup wouldnt populate after add() is ran on a repeat type similar to the stackblitz below? Usually in less complex examples where Im using the repeat type, both fieldArray and fieldGroup have values once add() is ran but when I have the repeat type first in the parent fieldGroup array the fieldGroup value is empty after add() is ran. If you look at the two images below, one is the actual app where fieldGroup doesnt populate after add() and the other is a less complex stackblitz (https://formly-cf-test.stackblitz.io/) where it does. Both have similar setups. 

Empty fieldGroup
https://ibb.co/vx7SkN7

Not Empty
https://ibb.co/FYYbMgR

Any guidance would be much appreciated!

**Comment by aitboudad** [comment]
`fieldGroup` is populated based on the model value so:

- Ensure `add` function is called
- Check the `field.model` and the root `model` values they should both include the new item after the `add` call, else somehow the field model is detached from the root model.
- use `setTimeout` before calling `add`

**Comment by joncorrin** [comment]
The setTimeout worked, thank you!

**Comment by aitboudad** [comment]
Great, `setTimeout` is just a workaround so don't hesitate to reopen in case you've got a reproduction.
