### ISSUE TITLE
Radio group value depending on something

### ISSUE THREAD

**Issue by mignam** [ngx-formly/ngx-formly#2607]
**Question**
My case is simple, i want the value of a radio group depending on the value of another radio group.

For example, when i select option 3 of radio group 1, i want option 4 of radio group 2 selected by default.

    radio group 1:
        - option 1
        - option 2
        - **option 3**. (is selected by the user)

    radio group 2:
        - option 1
        - option 2
        - option 3
        - **option 4** (is selected by default)

I 'm pretty sur that i have to use expressionProperties, but in my case, my formly config is in JSON format. It's seems like i can't use arrow fonction in it.

As i can see here, https://formly.dev/examples/other/json-powered, this is working.

```
"expressionProperties": {
      "templateOptions.label": "'Why did you choose ' + model.color + '?'"
    },
```

but i want something more like this.

```
"expressionProperties": {
      "valueOfMyRadioGroup": "() => { if something then do something}"
    },
```

Is it possible ? Am i wrong or missing something ?

**Comment by aitboudad** [comment]
```ts
"expressionProperties": {
  "model.radio2": "model.radio1 === 3 ? model.radio1 : model.radio2"
},
```

**Comment by mignam** [comment]
Hello, thank's it's working !

But i have that common issue when i click on radio button:

`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'mat-radio-disabled: true'. Current value: 'mat-radio-disabled: false'.`

I read that it only occur on debug, i don't realy know how to fix it or prevent it.

Anyway, thanks for your help and for your work.

**Comment by aitboudad** [comment]
Could you please provide a reproduction example? Thanks!
