### ISSUE TITLE
Difference between Formly.Form.value and Formly.Model

### ISSUE THREAD

**Issue by luizfbicalho** [ngx-formly/ngx-formly#2608]
**Question**

I created some forms using kendo, in this form I have a dropdown, sometims if I don't select a item, the form.value is null and the model is {}

other times the form.value has property = null and the model doesn't have the property.

How do I control the form.value to the model?

https://stackblitz.com/edit/angular-ivy-wdjv5y?file=src%2Fapp%2Fapp.component.ts

What I really need is the object with the explicit nulls for each property that doesn't have any selected item.

**Comment by luizfbicalho** [comment]
I even added the defaultValue to the formField , set as null, set as 0 anyway it doesn't return explicit properties as null

**Comment by aitboudad** [comment]
The diffs:
  - Formly model uses `undefined` rather than `null` by defaul (in `V6` Form value will use `undefined` too)
  - Form value doesn't allow passing `null` or `undefined` for an object or array type where Formly model does.


> What I really need is the object with the explicit nulls for each property that doesn't have any selected item.

Have you tried with our bootstrap ui for example, if it works then probably you may check if kendo select support that case?

**Comment by luizfbicalho** [comment]
I changed the example to boostrap and It start generating null,
but I will try another way, I though that formly had some control over the model creation from the form value, I'll try to pass a constructor in a generic service. what do you think of this alternative?

https://stackblitz.com/edit/angular-ivy-wdjv5y?file=src%2Fapp%2Fapp.module.ts

**Comment by aitboudad** [comment]
Sorry, I don't have an answer to your second question because that depends on how do you want to structure your project but anyway, the initial request is done I think.
