### ISSUE TITLE
Is there any solution for bootstrap autocomplete/typeahead? 

### ISSUE THREAD

**Issue by mahbub-hasaan** [ngx-formly/ngx-formly#2616]

**Comment by Suraj786** [comment]
@mahbub-hasaan You can create a custom type of element, as shown in the example

[custom-formly-field](https://formly.dev/guide/custom-formly-field)

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/708#issuecomment-364903803
