### ISSUE TITLE
Regression: defaultValue is removed when doing resetModel

### ISSUE THREAD

**Issue by Toktik** [ngx-formly/ngx-formly#2621]
**Description**
Recently we have migrated from ngx-formly 4 to 5 and we're having issue.

If you have defaultValue in the form, and you call resetModel, the default value is removed. This was not working like it in the v4, and I think this is a regression.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ocbyhy?file=src/app/app.component.ts

**Your Environment**

- Angular version: 10.2.3
- Formly version: 5.10.6

**Comment by Toktik** [comment]
@aitboudad Thanks for the fix! Do you expect a release soon?

**Comment by aitboudad** [comment]
yep, just pushed a release [v5.10.10](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.10)
