### ISSUE TITLE
Validation message doesn't show after update angular from 6 to 9

### ISSUE THREAD

**Issue by rologarcia** [ngx-formly/ngx-formly#2622]
Hi, I have an application in wich I implemented a few custom fields, that extends from FieldType. I have custom validators too. I was using angular 6 and ngx-formly 4.8.3. All was working fine. After upgrade to angular 9 and ngx-formly 5.10.6, the validation message dissapears, the controls are invalid but the message doesn't appear.

I have validationMessges defined in the module

`FormlyModule.forRoot({
      validationMessages: mensajesValidaciones,
....
export const mensajesValidaciones = [
  { name: 'required', message: requiredMessage },
  { name: 'min', message: minMessage },
  { name: 'max', message: maxMessage },
  { name: 'minLength', message: minLengthMessage },
  { name: 'maxLength', message: maxLengthMessage }
];`

I don't know if there are some lib, that have conflict with the new version of ngx-formly. my package.json is:

`"dependencies": {
    "@angular/animations": "^9.1.12",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "^9.1.12",
    "@angular/compiler": "^9.1.12",
    "@angular/core": "^9.1.12",
    "@angular/forms": "^9.1.12",
    "@angular/localize": "^9.1.12",
    "@angular/material": "^9.2.4",
    "@angular/platform-browser": "^9.1.12",
    "@angular/platform-browser-dynamic": "^9.1.12",
    "@angular/router": "^9.1.12",
    "@auth0/angular-jwt": "^2.1.0",
    "@babel/polyfill": "^7.8.7",
    "@fortawesome/angular-fontawesome": "^0.6.1",
    "@fortawesome/fontawesome-free": "^5.15.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@ng-select/ng-select": "^4.0.0",
    "@ngx-formly/bootstrap": "^5.10.6",
    "@ngx-formly/core": "^5.10.6",
    "@swimlane/ngx-datatable": "^15.0.0",
    "@types/go": "^1.6.20",
    "@usig-gcba/autocompleter": "^2.0.6",
    "angular2-text-mask": "^9.0.0",
    "bootstrap": "^4.3.1",
    "core-js": "^3.1.3",
    "file-saver": "^1.3.8",
    "flatpickr": "^4.6.2",
    "font-awesome": "^4.7.0",
    "gojs": "^2.1.30",
    "jquery": "^3.3.1",
    "lodash": "^4.17.20",
    "moment": "^2.24.0",
    "ngx-bootstrap": "^5.6.1",
    "ngx-captcha": "^8.0.1",
    "ngx-chips": "^2.2.2",
    "ngx-clipboard": "^12.3.0",
    "ngx-editor-vs": "^4.1.1",
    "primeng": "^5.2.0-rc.2",
    "rxjs": "~6.6.3",
    "rxjs-compat": "^6.2.1",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.12",
    "@angular/cli": "~9.1.12",
    "@angular/compiler-cli": "^9.1.12",
    "@angular/language-service": "^9.1.12",
    "@types/jasmine": "^2.8.16",
    "@types/jasminewd2": "^2.0.6",
    "@types/lodash": "^4.14.165",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",    
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "3.8.3"
  }`

Any ideas?

**Comment by aitboudad** [comment]
Hi, can you provide a reproduction example https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
