### ISSUE TITLE
Fields become disabled after re-creation

### ISSUE THREAD

**Issue by SonyStone** [ngx-formly/ngx-formly#2624]
**Description**
If the FormlyFieldConfig is used for the second time and the first field is disabled, then other fields are also disabled.

It's hard to explain. If you click the **toggle button** several times in the example, you can see that the second and third fields are also disabled, when they shouldn't.

**Minimal Reproduction**
https://stackblitz.com/edit/formly-bug-disabled-fields?file=src/app/app.component.ts

**Your Environment**
- Angular version: 9.1.0
- Formly version: 5.10.8

**Comment by luizfbicalho** [comment]
I'm not sure, but looks like it's related with #2598 

what do you think?

**Comment by aitboudad** [comment]
I've reverted the commit that caused the issue, fixed in `v5.10.9`.
