### ISSUE TITLE
Model is not as expected when working with JSON Schema dependencies

### ISSUE THREAD

**Issue by anmoreno** [ngx-formly/ngx-formly#2625]
**Description**
When using JSON Schema as the source to render by Formly and the schema is using dependencies the model has an object with the enum that was used for the dependency instead of only the field that you are supposed to be working with.
For my use case I am trying to create a custom date picker that meets our needs but can't make it generic enough since how the model is structured right now I would need to know the Key name to be able to correctly manipulate the model.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ukxg9y

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.10.8

**Additional context**
This makes it hard to create a generic component for every field since the date picker component model would be different when working with dependencies than when it's a straight up attribute.
The reason why I am trying to build a custom component is because in my JSON schema I have the date attribute to accept a format of 'date' and the datepicker returns the date object that when is sent to the api becomes a ISO8601 date time string causing the api to fail because it has a 00:00:00 as the time and it is only expecting the date.

**Comment by aitboudad** [comment]
Sorry but not sure I clearly understood the request just a side note for the `model` input it should be an object else rely on `modelChanges` output.

```patch
export class AppComponent implements OnInit {
  form: FormGroup = new FormGroup({});
-  model: any;
+  model: any = {};
}
```

for the emitted date value, either transform the model value on submit or use `parsers`:

```ts
export function transformDate(d) {
  ...
}

export class CustomDateComponent extends FieldType {
  defaultOptions = {
    parsers: [transformDate]
  };
}
````

**Comment by anmoreno** [comment]
Hello @aitboudad, 
My issue is that the model when using dependencies is:
```json
{ "birthStatus": "Known", "dateOfBirth": "" }
```
Instead of only being the dateOfBirth attribute it has the whole "birthDetails" object.
In the stackblitz example in the red box I am printing the model from within the custom-date component which I am using for the dateOfBirth field, if you see that is the object with the birthStatus.

What this complicates for me is that for the custom-date component I need to know whether it is rendered from a dependency to treat the model differently. For example in this case for birthDetails I have a dateOfBirth field to transform it I would need to know to work with model.dateOfBirth explicitly, I wouldnt be able to use this for another date field that is called 'eventDate' for example.

**Comment by anmoreno** [comment]
I will play around with the "parser" see if I can get the functionality I want with that. I think I might be able to use the provided formly datepicker with that.

**Comment by aitboudad** [comment]
I see, in case of `Unknown` status, what's the expected value of the `dateOfBirth`?

**Comment by anmoreno** [comment]
In the case of `Unknown`, `dateOfBirth` should be nothing which is why it is not part of the properties in the `oneOf`.
In my real uscase I have an `Estimated` where you would enter an `estimatedDateOfBirth` value which is to be treated the same way.

**Comment by aitboudad** [comment]
then you may not need `dependencies` here, just `oneOf` would do the job https://stackblitz.com/edit/angular-ukxg9y-cmrwkt?file=src/app/app.component.ts

**Comment by anmoreno** [comment]
I believe the issue would still be present if you were to add more properties to the oneOf. https://stackblitz.com/edit/angular-ukxg9y-tfvolj?file=src%2Fapp%2Fapp.component.ts
If you see there I added a second property to the Known option, if you select that option you will see that the `model` for the `dateOfBirth` field is still the whole object. So I still think that if you are trying to have some manipulation of a field within a oneOf you will not just be able to easily access the field value within the model without knowing the key name.

The parser will work great for what I need. I just did a few tests and will be able to get the date transformed as needed based on the field type.

```javascript
       {
          name: 'date',
          extends: 'datepicker',
          defaultOptions: {
            parsers: [transformDate]
          }
        },
        {
          name: 'time',
          extends: 'datepicker',
          defaultOptions: {
            parsers: [transformTime]
          }
        },
        {
          name: 'time',
          extends: 'datepicker',
          defaultOptions: {
            parsers: [transformDateTime]
          }
        }
```

**Comment by aitboudad** [comment]
I think we may solve that once we add support of passing oneOf to a single field, close in favor of  https://github.com/ngx-formly/ngx-formly/issues/2528
