### ISSUE TITLE
Stepper linear mode doesnt work when use type as stepper

### ISSUE THREAD

**Issue by suraj740** [ngx-formly/ngx-formly#2626]
Hi @aitboudad , i tried the solution which you have provided in #1330, but that is not working when we create separet type for stepper and use it.
[stepControl]="form.at(index)"
Error : _co.form.at is not a function
Here is the reproducible example [Link](https://stackblitz.com/edit/angular-dqbdal?file=src/app/stepper.type.ts)

How can i achieve linear mode in that?
Thanks.

**Comment by aitboudad** [comment]
`[stepControl]="form.at(index)"` only work for an array field type, you may check our latest stepper example https://formly.dev/examples/advanced/multi-step-form

**Comment by suraj740** [comment]
checked the lastest example it same as previous one.

**Comment by aitboudad** [comment]
As I said `[stepControl]="form.at(index)"` should not be used unless your form is an array type or each step should be grouped by key so if its the case, you may pass the the `step.formControl`  to `stepControl` input else rely on `isValid` function to check each step is valid.
