### ISSUE TITLE
Timing issue - with Validator & Change Expression 

### ISSUE THREAD

**Issue by warrendodsworth** [ngx-formly/ngx-formly#2627]
I've got 2 fields, A - with a validation fn & B - with a change expression. 
On change A - triggers B's change expression
I need A's validation fn to wait for B's change expression to complete - as A needs the latest value from B.

Is there a way to control the timing so A fires after B or any chance of adding a timing option?

**Comment by aitboudad** [comment]
Declare the validation in their parent field in order to get notified whenever one of them is updated, see https://formly.dev/examples/validation/matching-two-fields
