### ISSUE TITLE
Different control type or control configuration for nested elements

### ISSUE THREAD

**Issue by Adam-Michalski** [ngx-formly/ngx-formly#2628]
**Question**:

Can I declare in configuration different type or different configuration for controls for different level controls?

**Case**:

I want to display string differently in `array` type and differently in `object` type

**Expected**:

string type is declared for object and for array and is represented as declared for it's predecessors/parents

**Other case**:

I have configuration module imported with specified configration for my forms and I want to display `object` types under `override` type differently but I cannot easily recognize which object it is to map its type in map function 

```
      { name: 'override', component: FormlyOverrideComponent },
```

**Expected**:

In one configuration I have specified `object` and different kind of object which is under `override`.

I think it could be solved by some kind of conditional wrapper

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
