### ISSUE TITLE
How to integrate kendo-numericTextBox.

### ISSUE THREAD

**Issue by sivakumaraala** [ngx-formly/ngx-formly#2629]
Can you please advice best practices to integrate kendo specfic controls to formly. How can we pass specific properties. Example: kendo-numericbox has format, min, max.. properties particularly to that control. My aim is to integrate below code into formly.

`<kendo-numerictextbox [format]="'p'" [step]="0.1" [min]="0" [max]="1" [value]="percentage"></kendo-numerictextbox>`

Thanks in advance.

**Comment by aitboudad** [comment]
see https://formly.dev/guide/custom-formly-field
