### ISSUE TITLE
Missing Bootstrap validation message with custom field type

### ISSUE THREAD

**Issue by msacket** [ngx-formly/ngx-formly#2630]
I have a custom input type that formats a date and converts it to a specific format on blur.  Specifically, we're going from `mmddyy` to `yyyy-mm-dd`.  So `121120` becomes `2020-12-11`.

That all seems to work fine, but the issue I'm having is that I can't get the proper validation messages to appear.  Even the basic required messages won't kick in for that field.  What am I missing?

https://stackblitz.com/edit/custom-input-validation-missing

**Comment by aitboudad** [comment]
The validation seems working in the provided example. Just I think you may need to call `onTouched` for blur event:

```patch
  onBlur(value) {
    let pValue = this.parseValue(value);
    this.writeValue(pValue);
+   this.onTouched();
  }
```

**Comment by msacket** [comment]
Good grief.  I figured I was missing something simple.  Thanks for the help!
