### ISSUE TITLE
Bind a component on click of element in multiselect of formly, can i use view child?

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2631]
**I have a reuquirement in which i am using a multiselect dropdwon which also has logo for each row. On click of this logo i want to load other component, like we use viewchild in template driven approach is it possible to use it in Reactive formly form component?**

Step 1: Select multiselect of formly element. 
Step 2:  On click of logo from any row of multiselect method is called and need to load calender component in popup.(popup is secondary part to acheive i may use Swal for this). 
Step 3 : Load contents of calendar-component-html.

Stackblitz workaround of example for demonstration :  [Click here](https://stackblitz.com/edit/ngx-formly-ui-primeng-zlekna?file=app/app.component.ts)

Screenshot for logo in multiselect 
<img width="368" alt="Screenshot 2020-12-19 at 12 48 05 AM" src="https://user-images.githubusercontent.com/12397854/102652836-0b91c580-4194-11eb-9008-f19667f80468.png">

**Comment by chandelshashank** [comment]
@aitboudad  Need your support for this, it would be helpful if you can provide assistance.

**Comment by aitboudad** [comment]
use `hideExpression` https://stackblitz.com/edit/ngx-formly-ui-primeng-tkejjw

**Comment by chandelshashank** [comment]
Thanks for quick response @aitboudad 
I have modified the code accordingly, my requirement is when i click the logo of formly element, calling function **displayCalender()** through which calenderComponent should load in bootstrap modal can you please help me out in this Link for modified code: https://stackblitz.com/edit/ngx-formly-ui-primeng-cjukhx?file=app/app.component.ts

**Comment by aitboudad** [comment]
Sorry, I think you can do it using your Angular knowledge :) as I don't much time to provide a full example but if you've any questions then let me know.

**Comment by chandelshashank** [comment]
Thank you for the response, i am working over it hope it goes well, if i need any clearfication will ask for your inputs.

**Comment by chandelshashank** [comment]
@aitboudad  coming back to you as i am still struggling to call a component from my formly element, i have created a stackblitz examples :

1. [Stackblitz click here](https://stackblitz.com/edit/ngx-modal-x1stln?file=src/app/app.module.ts) This link demonstrates my requirement of display other component data in a bootstrap modal .

2. [StackBlitz click here](https://stackblitz.com/edit/ngx-formly-ui-primeng-pgtbb5?file=app/app.component.ts) link is my work around of using the same functionality of bootstrap modal on click of the formly multiselect element, but in this case my observation is the modal initalised in constructor is not accessible in template options. 

How can i achieve this ? need your support.

**Comment by aitboudad** [comment]
@chandelshashank sorry for the delay, do you still need help about that request?

**Comment by chandelshashank** [comment]
@aitboudad this requirement is achieved thanks for your support
