### ISSUE TITLE
ngx-formly in library

### ISSUE THREAD

**Issue by sixbras** [ngx-formly/ngx-formly#2633]
Hi,

I work on a angular monorepo project, with multiple front end / backend apps.
I've a directory 'shared -models' to share models in all of my apps, and i would like to add FormlyFieldConfig related to models.

Shared-models is just a simple ts project, with a package.json, and it's seems impossible to run "ng add @
ngx-formly/core" in a non angular context. I try to "npm i @
ngx-formly/core" but with no success.

My question is, is there any option to only import/export "FormlyFieldConfig" definition ?

Thanks for your help.

**Comment by aitboudad** [comment]
Sorry but the request is not clear enough to me, need more further details, thanks!
