### ISSUE TITLE
created wrapper on top of primeng p-tree control but model is not working

### ISSUE THREAD

**Issue by anandarch** [ngx-formly/ngx-formly#2634]
Hi,

I have created custom wrapper on top of primeng p-tree control, I am being able to load the data but not being able to bind the model and get the selected value.

Please help me on this

**Comment by aitboudad** [comment]
Hi, could you please replicate your work using our stackblitz starter example https://stackblitz.com/edit/ngx-formly-ui-primeng
Thanks!

**Comment by anandarch** [comment]
Hi @aitboudad,

I have added the code, though its not coming as expected here. but the major concern is model. not getting the selected value.

Thanks,
Anand

**Comment by aitboudad** [comment]
Sorry but without an example I can't provide the help, feel free to reopen once you've got a reproduction example.
