### ISSUE TITLE
Extensions should have a fixed order as the core extension needs to come before other extensions 

### ISSUE THREAD

**Issue by vespertilian** [ngx-formly/ngx-formly#2637]
Hey thanks again for all your work on this super useful library. 

**Description**

Ok, lots of explaining to do.

I was following this [example](https://formly.dev/examples/other/material-prefix-suffix) to create a suffix extension for Angular materials.

After getting a base version of my suffix extension working I went to package it up like the [bootstrap add-on](https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/bootstrap/addons/src/addons.module.ts).

When writing some unit/integration tests I could not get the form to render correctly. Deep diving into the underlying issue and it seems to be that when using a module to add the extension, if you add it inline after `FormlyModule.forRoot()` it puts the added extension first before the core extension which causes a failure on the form. 

formly.builder.ts ... this is the line that's likely the issue
```
  private getExtensions() {
    return Object.keys(this.config.extensions).map((name) => this.config.extensions[name]);
  }
```

See an example spec here:

https://github.com/vespertilian/angular-test-app-jasmine/blob/formly-extension/src/app/mat-suffix/mat-suffix.spec.ts

*** be aware it's in the formly-extension branch. 

mat-suffix.spec is the file in the repo you should look at. You can comment out the setup to see the two different scenarios. 

```
 fit("should create", () => {
    const { fixture, config} = setup()
    fixture.detectChanges()

    // component works when extensions are in this order
    // when passing the extension in as a module mat-suffix is the first extension
    // weirdly if you lazy load the MatSuffixModule there is no error
    expect(Object.keys(config.extensions)).toEqual(['core', 'field-validation', 'field-form', 'field-expression', 'mat-suffix'])

    expect(fixture.debugElement.query(By.css("input"))).toBeTruthy()
    const suffixComponent = fixture.debugElement.query(By.css("app-mat-suffix"))
    expect(suffixComponent).toBeTruthy()

    expect(fixture.debugElement.query(By.css("mat-icon"))).toBeTruthy()
  })
```

Also  see a stack blitz here: the repo has the more useful spec... hard to get working in stack blitz

https://stackblitz.com/edit/angular-ivy-caybuy?file=src%2Fapp%2Fmat-suffix%2Fmat-suffix.module.ts

In both these cases if you add the extension manually in the root it works. 

So this works:
```
   FormlyModule.forRoot({
      wrappers: [{ name: "mat-suffix", component: MatSuffixComponent }],
      extensions: [{ name: "addons", extension: { onPopulate: onPopulate } }]
    })
```

Also, as stated earlier it seems to work if you load the module lazily (which I do in my app)

I think that the core extension probably needs to always run first ? So it should be changed to be deterministic. No sure how you want to do that? 

Happy to try for a PR if you can give me some direction on how best to fix the order.

If any of this does not make sense happy to clarify or jump on a hangout and show you. 

Thanks again.

**Comment by aitboudad** [comment]
> Happy to try for a PR if you can give me some direction on how best to fix the order.

I was about asking to work on it but I've got an easy way to fix so next time then!

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [5.10.11](https://github.com/ngx-formly/ngx-formly/releases/tag/5.10.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by vespertilian** [comment]
@aitboudad Thanks for your quick fix. I didn't get a PR in for this feature but if you're interested I could package this extension up in the materials library. Let me know.

Thanks again!

**Comment by vespertilian** [comment]
@aitboudad ngx-formly uses jest right? If you do want that PR we will have to wait until I find out why this all works with Jasmine and not Jest.  See thymikee/jest-preset-angular#703
