### ISSUE TITLE
the field group dropdown's value changes is emitting multiple values as I change the tab

### ISSUE THREAD

**Issue by Praveen-1998** [ngx-formly/ngx-formly#2638]
**Description**
I have three different tabs on each tab selection I am getting response from backend and binding it to fields variable of forlmy-form , but in one of the tab I have dropdown also but this is not there in other tabs and I am using ng-select here and if I filled one dropdown I am getting response for other dropdown from API but if I change the tab to other tab and agian if I come back to my tab which is having this dropdown in its form and this time if I choose any value from first dropdown the API is calling multiple time as the valuechanges even I selected single value from the dropdown and the API is increasing as the tab changing is increased.

Can you please help me out where I am doing wrong here 

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: 8.0.0
- Formly version: 5.10.7

**Additional context**

**Comment by aitboudad** [comment]
The request is not clear enough and a reproduction example using our `stackblitz` is needed, feel free to reopen when you have got a reproduction example.

`hint`: To reduce the value changes emits you may use `distinctUntilChanged` pipe.

**Comment by neo1380** [comment]
> **Description**
> A clear and concise description of what the bug is.
> I have three different tabs on each tab selection I am getting response from backend and binding it to fields variable of forlmy-form , but in one of the tab I have dropdown also but this is not there in other tabs and I am using ng-select here and if I filled one dropdown I am getting response for other dropdown from API but if I change the tab to other tab and agian if I come back to my tab which is having this dropdown in its form and this time if I choose any value from first dropdown the API is calling multiple time as the valuechanges even I selected single value from the dropdown and the API is increasing as the tab changing is increased.
> 
> Can you please help me out where I am doing wrong here
> 
> **Minimal Reproduction**
> 
> https://stackblitz.com/...
> 
> **Your Environment**
> 
> * Angular version: 8.0.0
> * Formly version: 5.10.7
> 
> **Additional context**
> Add any other context about the problem here.

@Praveen-1998  Did you fix this issue ? i seem to be facing similar issue  with ng select
