### ISSUE TITLE
angular 11 library

### ISSUE THREAD

**Issue by smile2014** [ngx-formly/ngx-formly#2640]
ERROR: Error during template compile of 'FlameZorroModule'
  Function calls are not supported in decorators but 'FormlyModule' was called.

An unhandled exception occurred: Error during template compile of 'FlameZorroModule'
  Function calls are not supported in decorators but 'FormlyModule' was called.

@NgModule({
  declarations: FIELD_TYPE_COMPONENTS,
  imports: [
    ReactiveFormsModule,
    CommonModule,
    NzInputModule,
    FormlyModule.forChild(ZORRO_FORMLY_CONFIG)
  ],
  exports: []
})
export class FlameZorroModule { }

**Comment by aitboudad** [comment]
Make sure `ZORRO_FORMLY_CONFIG` doesn't contain a function call you also check the following issue https://github.com/angular/angular/issues/23609#issuecomment-386876693.

**Comment by smile2014** [comment]
thank you,However, I will not report an error when I use it directly in the application. This error will only be reported when I put it in the library.

**Comment by aitboudad** [comment]
Yes but most probably it's an issue either on your side or in the Angular compiler and providing a reproduction repo is required here.

**Comment by smile2014** [comment]
can I email the demo to you for help?

**Comment by aitboudad** [comment]
ok

**Comment by smile2014** [comment]
[Uploading flame-success.zip…]()

**Comment by smile2014** [comment]
[Uploading flame-erro.zip…]()

**Comment by smile2014** [comment]
Thank you ，One is that it can be used normally without using the library, and the other is to use the library to compile an error
