### ISSUE TITLE
Drag and Drop text to Input Fields

### ISSUE THREAD

**Issue by kswaroop** [ngx-formly/ngx-formly#2642]
Hello 

Working on Drag and Drop Functionality, 
My scenario is - drag text from "Un Order List" to any of the available Formly Input fields in another container

Normal Drag and Drop from one container to another or in the same container is working for me

Thanks in advance, It will be great any idea/suggestion.

**Comment by aitboudad** [comment]
Declare a custom field type that takes care of HTML content or use the `template` property:

```ts
{ template: elementContent }
```

but better define a custom type which you'll a full control, for drag and drop starter example check the following issue: https://github.com/ngx-formly/ngx-formly/issues/1456#issuecomment-469894882

**Comment by yadavnandakishore67** [comment]
but we have a requirement like we need to drop text on every field of ngx-formly. if we are using custom template for every field it doesn't make sense right?
