### ISSUE TITLE
Want to use MatDialog to insert/update the record on ngx-datatable/mat-table

### ISSUE THREAD

**Issue by Suraj786** [ngx-formly/ngx-formly#2643]
**Want to use MatDialog to insert/update the record on ngx-datatable/mat-table either using repeater or datatable type**

Hi @aitboudad 

I have used formly-form within repeater block so I am getting warning like `NgxFormly: content projection for 'formly-form' component is deprecated since v5.5, you should avoid passing content inside the 'formly-form' tag.` 
How we can remove this warning, is there any alternate way to achieve this scenario. 

Thing is I want to use mat-dialog to insert and update the records in ngx-datatable/mat-table. 

[Sample Link](https://stackblitz.com/edit/angular-rv7jtn-rfphzs)
Angular version: 8.1.2
Formly version: 5.10.10

Can you please help me to find a solution.

Thanks in advance.

**Comment by aitboudad** [comment]
Just move the `div` content outside of `formly-form` component:

```patch
<formly-form [model]="mdl" [fields]="singleField" [form]="singleForm" [options]="ops">
-  <div fxLayout="row" fxLayoutAlign="left center">...</div>
</formly-form>
+ <div fxLayout="row" fxLayoutAlign="left center">...</div>
```

**Comment by Suraj786** [comment]
Hi  @aitboudad 

I have implement the mention scenario. Link:- [formly-add-ngxdatatablerow](https://stackblitz.com/edit/formly-add-ngxdatatablerow-cm2cat)
