### ISSUE TITLE
Setting Input width when using flex-layout

### ISSUE THREAD

**Issue by SubrahmanyaV** [ngx-formly/ngx-formly#2648]
Hi,

I use flex-layout & am trying to set the width of a formly input, but haven't succeeded.
I have attached a screen shot of the form below:
- Inputs highlighted in green are Angular Material Inputs. I use fxFlex as in the example **<mat-form-field fxFlex="40%">**
- The one highlighted in yellow (& the ones that follow) are formly Inputs. 

Please guide me on how I can achieve setting the width of Formly Inputs using fxFlex.  Formly always uses the parent container & fxFlex always defaults to 100%.  I am not sure if I can explicitly set a parent container in Formly.  I cannot use 'class' configuration for this.  

Thanks

![InputWidth](https://user-images.githubusercontent.com/43541702/103480975-e04adf80-4dfd-11eb-9dc8-a225b6e3f015.png)

**Comment by aitboudad** [comment]
Hi, can you provide a reproduction using the following `stackblitz` example http://stackblitz.com/edit/ngx-formly-flex-layout

Thanks!
