### ISSUE TITLE
HideExpression with Nested fields and Default values not working

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2651]
@aitboudad A Very Happy New Year to you.

I have this following scenario that I am trying to put together and for some reason I am not able to get it to work.

Some details around setup is

I am using the latest version of the formly software 
I am using a .ts file to store my filed config which is then imported into the component.

1. if I try to do hide expression at the key: "mqttv5" level it does not work
2. If I comment out key: "mqttv5" and set hide expression at field level  key: "sessexpinterval" 
    a. and comment out its default value, it works and it is added to model when I enter a value.
    b. v/s uncomment its default value the field is hidden in the form, but is present in the model with the set default value.

Ideally I would like the hide to work at the higher level (i.e: key: "mqttv5") and some default values for the nested fields be set.

Will appreciate your help in getting this to work.

Thanks

```
export const SandboxMqttFields: FormlyFieldConfig[] = [
  {
    fieldGroupClassName: "row",
    fieldGroup: [
      {
        type: "select",
        key: "mqttprotover",
        className: "col-12 col-md-3",
        templateOptions: {
          label: "MQTT Version",
          placeholder: " Select MQTT Version",
          options: [
            { label: "V3", value: "3" },
            { label: "V3.1.1", value: "4" },
            { label: "V5", value: "5" },
          ],
          // disabled: true,
        },
      },
     ]
   },
  {
    // key: "mqttv5",
    // hideExpression: 'model.mqttprotover != "5"',   <--- for some reason hide expression does not work at this level
    fieldGroupClassName: "row",
    fieldGroup: [
      {
        type: "input",
        key: "sessexpinterval",
        className: "col-12 col-md-3",
        // defaultValue: 100,                       <-- if default value is uncommented, then field is always present in model
        templateOptions: {
          label: "Session Expiry Interval",
          placeholder: "1000",
          type: "number",
        },
        hideExpression: 'model.mqttprotover != "5"',  <!-- hide expression works here
      },
     // .... I have more fields here that are omitted
     ]
}
]
```

**Comment by aitboudad** [comment]
Happy New Year, check my comment https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

**Comment by BhagyashreeCH** [comment]
@aitboudad I am having hide expression issue when passing nested object value through json schema, these are the changes I have made here https://stackblitz.com/angular/eyoexxxgvpg?file=src%2Fapp%2Fapp.component.ts in nested.json schema

 "hideExpression": "field.parent.model.title === 'test'" => this also I have tried, Am I missing something, please suggest me **it will resolve my lot of issues related to disable or hide conditionally**

![image](https://github.com/ngx-formly/ngx-formly/assets/54449571/cc019a53-2fc0-4f89-b9ac-77e089e671e5)

**Comment by voidove** [comment]
@BhagyashreeCH , I encountered the same issue. Did you eventually find a solution?
