### ISSUE TITLE
JSONSchema readOnly is not supported for enum values

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2652]
**Description**
When an enum value is defined with a default value and is read only. The value can be changed.

**Minimal Reproduction**

Go to this example and try to change the values.

https://stackblitz.com/edit/select-readonly

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.10.11

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.12) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
