### ISSUE TITLE
Remove keys and values of hidden fields from model?

### ISSUE THREAD

**Issue by Adelost** [ngx-formly/ngx-formly#2653]
**Question**

If a field that has been changed is hidden (e.g. with `hideExpression`) then its key and value is still present in the model. Is there any easy way of removing these hidden keys from the model?

We have a lot of conditional sections in our GUI and we would want to prevent hidden sections from being submitted.

**Comment by aitboudad** [comment]
Enable `resetFieldOnHide` options which was introduced since [v5.10.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0) release.

```patch
    FormlyModule.forRoot({
+      extras: {
+        resetFieldOnHide: true,
+      },
    }),
```
