### ISSUE TITLE
Access to fields array from custom wrapper to remove field dynamically added

### ISSUE THREAD

**Issue by paulodiff** [ngx-formly/ngx-formly#2654]
### I need to access this.fields array from custom wrapper.
I've added a custom wrapper and i can't access to this.fields array to remove a field dynamically added.

On Stackblitz: [https://stackblitz.com/edit/angular-formly-ngx-config](https://stackblitz.com/edit/angular-formly-ngx-config)

Step to reproduce behavior:

- Click on DYNAMIC:FORM
- From select "Add dynamically field to form:" and click on "infoHeader" item
- Click on green button "Add field" and a field has added to form.
- The field is defined with a wrapper:

   app/formly/formly-cfg.all.wrapper.ts
   
   with a button "remove" with a function cannot access this.fields array to remove the field.

Thanks for support!

**Comment by aitboudad** [comment]
I couldn't find `DYNAMIC:FORM` in your example, we don't provide `fields` in the wrapper/type but instead a field instance so in case the field is a repeat type you can define `add` and `remove` function where you'll be able to call them inside the wrapper.

Here is an example that provides remove to be accessible outside the Repeat type:
https://stackblitz.com/edit/angular-rsg1kj?file=src%2Fapp%2Frepeat-section.type.ts

**Comment by km4dlpx** [comment]
How can we do the same in the latest version? I am using this.options.build() but formControl is getting emptied after that.
