### ISSUE TITLE
Disable some options of an "AnyOf" schema

### ISSUE THREAD

**Issue by zannkukai** [ngx-formly/ngx-formly#2656]
**Is your feature request related to a problem? Please describe.**
I can be great if an "anyOf" section could be disabled (or readonly). 

https://stackblitz.com/edit/anyof-readonly-value?file=src%2Fassets%2Fjson-schema%2FanyOf.json
In this exemple, the "patron" role should be disabled ; only "librarian" role should be active.

**Describe the solution you'd like**
Adding the `readOnly` or `disabled` tag into the jsonSchema, the corresponding anyOf option should be disabled.
It will be interesting to implement the same behavior for other schema (oneOf, allOf, ...)

**Additional context**
In our application, a user can have multiple roles into a list of three roles (patron, librarian, system_librarian). Depending of the connected user, some roles should be disabled (a librarian, cannot give "system_librarian" role to other user), ...
This restrictions are retrieve from a API call.

Thanks for your help

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.12) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
