### ISSUE TITLE
Materialize theme

### ISSUE THREAD

**Issue by KamilSocha91** [ngx-formly/ngx-formly#2657]
## I'm submitting a new theme proposition.

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Expected behavior

I propose to add new theme based on - [materialize](https://materializecss.com/text-inputs.html)

I could do it, with Readme.md and demo update.

**Comment by aitboudad** [comment]
For now, our goal is limited to support only the popular themes in Angular.
