### ISSUE TITLE
formGroup.statusChange has different last value as in formGroup.status

### ISSUE THREAD

**Issue by Greegko** [ngx-formly/ngx-formly#2658]
Maybe it fits more like a question, wasn't sure about this. I have a problem as I handle these form in different components, and to get the form value and status I send back via output. But for some reason, when hiding and showing the component's field doesn't trigger the status changes into form.statusChange stream.

Created a repo which can reproduce this behaviour.

https://stackblitz.com/edit/angular-dpnk9z-t9xsez

The group.statusChange last emitted value doesn't syncronized with group.status actual value.
Have a field where there is a validator and when displayed this field and the validation is wrong, I am still getting the "VALID" status as the last result.

- Angular version: tested with 10 & 11
- Formly version: 5.10.11

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.13](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.13) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
