### ISSUE TITLE
accessibility support

### ISSUE THREAD

**Issue by datasmithadvtech** [ngx-formly/ngx-formly#2662]
template options does not support aria-label, which is required for accessibility compliance

- Angular version: "^11.0.4",
- Formly version: "5.10.6",

**Additional context**

**Comment by aitboudad** [comment]
it does by using `attributes` property:

```
{
  templateOptions: {
    attributes: {
	  'aria-labelledby': 'value'
    }
  }
}
```

**Comment by pain0486** [comment]
@aitboudad is the value the key then? And then it will use the generated id?
