### ISSUE TITLE
How to override  remove method of repeat element and allow both operations of removing and adding some logic

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2663]
**How to override  remove method of repeat element and allow both operations of removing and adding some logic**

I am using a repeat field in which there is a remove button this works fine normally, but my requirement is to perform some logic while removing the element for which I will call a customize function onRemove instead of remove(i), could anyone help me to achieve this, following is the stackblitz demo: [click here stackblitz demo](https://stackblitz.com/edit/angular-formly-repeat-i91pwz?file=app/repeat-section.type.ts)

Explanation with Screenshot:

Step 1. Click on remove button, function remove(i) is called.
<img width="447" alt="Screenshot 2021-01-14 at 1 57 24 PM" src="https://user-images.githubusercontent.com/12397854/104566532-ba320480-5673-11eb-8bf1-9986abf58900.png">

Step 2. Instead of remove, I need to call a function that will perform some logic before removing it, I tried doing it I was able to call the function but was not able to remove the element.

Code snippet of which I tried using for removing element in formlytype component:

In repeat-section.type.ts:

  `<button class="btn btn-danger" type="button" (click)="OnRemove(i)">Remove</button>`
   `export class RepeatTypeComponent extends FieldArrayType {`
      `constructor(builder: FormlyFormBuilder) {`
     ` super(builder);`
     ` }`
       `onRemove() {`
         `console.log('---->remove');`
     `  }`
   `}`

This calls the method but does not remove the element.

**Comment by FritzHerbers** [comment]
Use the following:

```
  onRemove(i: number) {

    // your logic

    // calls the extended FieldArrayType remove() method to delete the row from the model and 
    // the formly FormlyFieldConfig's for that row from your repeat type fieldGroup
    super.remove(i);   
}
```

**Comment by chandelshashank** [comment]
@aitboudad  could you help me with this.

**Comment by chandelshashank** [comment]
This works out perfectly, but instaed of using I in the onRemove(i) how is it possible to pass the value of the field to be removed, I tried using $event like I do for other fields that hold the value of the control as well but this doesn't work out well. 
Could you please help me out in this.

**Comment by FritzHerbers** [comment]
FieldArrayType extends FieldType. In an instance from FieldType (or derived from this) you have access to this.field in the class and in the onRemove method.

The only exception to this is with on/pre/postPopulate where formly provides the field in the method arguments.

You can also write 
```
(click)="OnRemove(field, i)
```
This provides this.field from the template into your method. But their is no added value going this extra mile.

**Comment by chandelshashank** [comment]
I got that, thank you for your efforts, helped alot @FritzHerbers I was already binding the model to the repeat element so I used that to pass the value.
