### ISSUE TITLE
Not found - Request ID: 001cc4ac-dfb1-40aa-8a6d-07d88e10009a-8328721 on https://master.formly.dev/ when switching version to next.

### ISSUE THREAD

**Issue by 3vil4aron** [ngx-formly/ngx-formly#2664]
**Description**
Not found - Request ID: 001cc4ac-dfb1-40aa-8a6d-07d88e10009a-8328721 on https://master.formly.dev/ when switching version to next.

I'm was looking into what's upcoming for formly, but when going to the dropdown and selecting next, I get an error.
 Looing for using a schema to generate a webform. like this example: [stackblitz](https://stackblitz.com/edit/angular-rbv4qw)

Thanks!

**Comment by aitboudad** [comment]
it should be fixed once starting on `V6` alpha release, to get notified make sure to watch our releases:

![Selection_054](https://user-images.githubusercontent.com/1753742/107330541-ffe6bf00-6ab1-11eb-8836-dcf157f487d8.png)
![Selection_055](https://user-images.githubusercontent.com/1753742/107330553-037a4600-6ab2-11eb-873b-1b53140ddbd7.png)
