### ISSUE TITLE
Incorrect type for `min` and `max` attributes for the Ionic `datetime` field

### ISSUE THREAD

**Issue by jits** [ngx-formly/ngx-formly#2666]
Firstly, a huge thanks for this impressive library – it makes managing forms much more pleasant 😃 

**Description**

Using the UI adapter for Ionic, I'm attempting to set the `min` and `max` attributes for the `datetime` field type. However I'm getting a type mismatch error (as in the screenshot below):

![Screen Shot 2021-01-19 at 16 00 08](https://user-images.githubusercontent.com/31973/105061014-e7febb00-5a70-11eb-93f0-80a7f9b53ff2.png)

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formly-ui-ionic-ukfd2a?file=app%2Fapp.component.ts

**Your Environment**

- Angular version: 11.0.9
- Formly version: 5.10.11

**Additional context**

I expect this is due to the types set on the `min` and `max` fields in the `FormlyTemplateOptions` interface:
https://github.com/ngx-formly/ngx-formly/blob/fe2314d5f50ff61d46af01175b158dc3f9fd4e4e/src/core/src/lib/models/fieldconfig.ts#L189-L190

Happy to contribute a PR to fix this, but wanted to check first on the best approach here. Should we do something like `min: number | string` or is there a better way to enable this just for the Ioinic `datetime` type?

**Comment by aitboudad** [comment]
I've pushed a fix in [v5.10.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.12) release.

Instead of using `min` and `max`, use `minDate` and `maxDate`.

**Comment by jits** [comment]
> I've pushed a fix in [v5.10.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.12) release.
> 
> Instead of using `min` and `max`, use `minDate` and `maxDate`.

Amazing! Thank you for sorting this out so quickly.
