### ISSUE TITLE
JSONSchema field is processed twice

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2667]
**Description**
JSONSchema field is processed twice in the formlyJsonschema.toFieldConfig map function.

**Minimal Reproduction**

https://stackblitz.com/edit/one-of-processed-twice

Check the console log.

Does not appear for version<5.10.

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.10.11

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.12) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
