### ISSUE TITLE
Neither hidden nor hide work with JSON forms using Material

### ISSUE THREAD

**Issue by sweeneki** [ngx-formly/ngx-formly#2668]
**Description**
Neither hidden nor hide work with JSON forms

**Minimal Reproduction**
See you own StackBlitz for JSON:
https://stackblitz.com/angular/apeyxvnpoxb?file=src%2Fapp%2Fapp.component.ts

and the modification to the 'age' field below.

**Your Environment**

- Angular version: 9.1.2
- Formly version: 5.0.0

**Additional context**
      "age": {
        "type": "integer",
        "title": "Age",
        "hide":"true",
        "widget": {
          "formlyConfig": {
            "templateOptions": {
              "hidden": "true"
            }
          }
        }
      },

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-ju1je9

```patch
"age": {
  "type": "integer",
  "title": "Age",
  "widget": {
+    "formlyConfig": {
+      "hide": true
+    }
  }
},
```

**Comment by sweeneki** [comment]
Thank you!
