### ISSUE TITLE
How to make autocomplete with FormlyBootstrap

### ISSUE THREAD

**Issue by OrhanOzkercin** [ngx-formly/ngx-formly#2669]
**Question**
I want to use Bootstrap typeahead in formly.  I created a wrapper for typeahead and send my array to this wrapper but could not get the value of input because the only thing this wrapper does was show a list of array that I gave. I want to make a typeahead and want to get the value of that input.

**Comment by aitboudad** [comment]
have you checked the material autocomplete example https://formly.dev/ui/material, it should be done somehow using a similar approach
