### ISSUE TITLE
Display value from model in FieldType template

### ISSUE THREAD

**Issue by Adelost** [ngx-formly/ngx-formly#2670]
**Question**

Is there any recommended way of displaying a value from the model in the HTML-template?

If I try `{{model[key]}}`, I get the error "Type 'string[]' cannot be used as an index type".

```ts
@Component({
  template: `
    <div class="row">
      <div class="col-sm-3 label">{{to.label}}</div>
      <div class="col-sm-9 value">{{model[key]}}</div>
    </div>
  `,
})
export class LabelValueComponent extends FieldType {}

```

I could fix it by casting the key into a string. Something like the following. But maybe there is a better way that I am missing?

```ts
getValue(): string {
    return this.model[this.key as string];
  }
```

**Comment by aitboudad** [comment]
The casting would do the job, but ensure to always use a string/number value to the `key` property and not an array. Another solution is to use `formControl.value`.

**Comment by Adelost** [comment]
@aitboudad Thanks for the suggestion. "formControl.value" seems like a cleaner solution so I switched to using that one instead.
````ts
<div class="col-sm-9 value">{{formControl.value}}</div>
```
