### ISSUE TITLE
Allow setting css style to FormlyGroup

### ISSUE THREAD

**Issue by jkremlacek** [ngx-formly/ngx-formly#2671]
**Is your feature request related to a problem? Please describe.**
Formly Group allows styling only via `className` property. In most cases this is enough, but in some cases it is not ideal. 

E.g.: When form layout is using css grid and I want to span the field group over N columns. Yes, I can create specific class for it, however this is not ideal solution when there can be countless number of variants of row/col spanning.

**Describe the solution you'd like**
Allow FormlyGroup component to set css style directly to element `<formly-group>` via attribute `style`, something like it is for `input` element:

```
templateOptions: {
  attributes: {
    style: "**css style here**"
  }
}
```

**Describe alternatives you've considered**
Create specific class for every reasonable combination of grid-column/row values, which is possible but not practical.

**Comment by aitboudad** [comment]
`attributes` is handled by `formlyAttributes` which is not suitable to be used in a field group, instead override the default field group type provided by Formly and add your custom implementation.

I may think about a proper solution later.

**Comment by aitboudad** [comment]
The solution is either  define a custom component that override field-group or using inline-type as described here https://github.com/ngx-formly/ngx-formly/issues/2086#issuecomment-584847953

**Comment by narcisbuzatuJ** [comment]
If that can help you I can show you using some bootstrap grid styles.

You must treat the <formly-group> tag as if it were a row, how? Like this :

(In you're component NgOnInit)

`
document.addEventListener('DOMContentLoaded', function () {
      let elements = document.getElementsByTagName('formly-group');

      for (let i = 0; i < elements.length; i++) {
        elements[i].classList.add('row');
      }
});
`

that will assing the Bootstrap's row class but you can assing also your custom classes.

now we need only to assing classes to our fields:

`
{
    "key": "description",
    "className" : "col-lg-9 col-sm-12", //thats the Bootstrap's col class
    "type": "textarea",
    "props": {
        "label": "Descrizione"
    }
},
`

That's a tricky walkaround.
I hope that can help you all.
