### ISSUE TITLE
hideExpression with Sibling Fields

### ISSUE THREAD

**Issue by joncorrin** [ngx-formly/ngx-formly#2672]
I have the following field definition:
```
{
  "type": "form",
  "fieldGroup": [
    {
      "key": "",
      "type": "repeat",
      "label": "Students",
      "fieldArray": {
        "type": "section",
        "wrappers": [
          "section-panel"
        ],
        "fieldGroup": [
          {
            "key": "",
            "type": "input",
            "templateOptions": {
              "label": "First Name",
              "required": true,
              "className": "input",
              "placeholder": "First Name"
            }
          },
          {
            "key": "",
            "type": "input",
            "templateOptions": {
              "label": "Last Name",
              "required": true,
              "className": "input",
              "placeholder": "Last Name"
            }
          },
        ],
        "templateOptions": {
          "label": "Student",
          "hasRepeatButtons": true
        }
      },
      "templateOptions": {
        "label": "Student",
        "subIndex": 0
      }
    },
    {
      "key": "",
      "type": "section",
      "wrappers": [
        "section-panel"
      ],
      "fieldGroup": [
        {
          "key": "",
          "type": "input",
          "templateOptions": {
            "label": "School Name",
            "required": true,
            "className": "input",
            "placeholder": "School Name"
          }
      },
      ],
      "templateOptions": {
        "label": "School"
      }
    }
  ]
}
```
Currently `Student` repeat section is hidden on child field change and `School` section is also working to hide itself with its child fields change. But How can I hide `Student` section with `School` section on child fields change?
The problem here is that when I have several sections on a form with `repeat` and `section` type., hideExpression with its child value change is working well, but not sure how I can detect sibling child value change, and implement with hideExpression. For Example: if first name is "ABC" and i set it with hideexpression, then student repeat section will also be hidden when the first name is "ABC". How we want it to work is that if school name is "DEF", then the student section should be hidden, as school and student fields are siblings.

**Comment by aitboudad** [comment]
`school` is a separate section, how is it assigned to a student??, the provided `json` example is not clear enough to have a clear idea about the model structure and the desired behavior.

**Comment by joncorrin** [comment]
The simpler question would be: 
How can I hide the entire students section if School Name = 'High School'? 

When we I set hideExpression on the student section based on the School Name field, it still shows.

**Comment by aitboudad** [comment]
I see, your need is to have access to parent model which can be achieved by using `field.parent.model`:

```ts
{
  "type": "repeat",
  "label": "Students",
  "hideExpressions": "field.parent.model.schoolName === 'High School'"
}
```
