### ISSUE TITLE
11.1.0 Dependency injection will not be able to resolve the parameters of FieldArrayType's constructor. 

### ISSUE THREAD

**Issue by vespertilian** [ngx-formly/ngx-formly#2674]
In Angular 11.1.0 you cannot extend `FieldArrayType` for now you can downgrade to 11.0.9. 

I think this is an issue with Angular as it was working prior to 11.1.0. Just logging it here for anyone else who gets the error on the `FieldArrayType`

I logged the issue on the main Angular repo here. 
https://github.com/angular/angular/issues/40532

**Minimal Reproduction**

this commit is working

vespertilian/angular-test-app-jasmine@5163dbd

this commit is not

vespertilian/angular-test-app-jasmine@fae6f38

^^^ two last commits in the master branch will let you toggle the scenarios

**Comment by aitboudad** [comment]
I think that's a regression better to wait for an Angular fix

**Comment by aitboudad** [comment]
feel free to reopen if Angular doesn't provide a fix.

**Comment by vespertilian** [comment]
From https://github.com/angular/angular/issues/40532

> I looked into your statement that ngx-formly does have the `@Directive` decorator applied, but this is not the case for version 5.10.12 that is latest on NPM. The decorator is only present on the master branch, but I suspect that hasn't yet been released. The simplest workaround would be to add that directive also to the 5.x branch of ngx-formly.

I did check the master branch and you have added the decorator. So we just need to pull it into the 5.x branch?

**Comment by jgluhov** [comment]
the problem still exists!!!

**Comment by aitboudad** [comment]
@vespertilian would you like to work on this?

**Comment by jgluhov** [comment]
As far as I understand everything is already in the main branch, the only thing we should do is to make a release ? Am I correct ?

**Comment by JoostK** [comment]
Oh btw, another workaround could be to add an explicit constructor in the subtype, as then you avoid the necessity for the base class to have an Angular decorator.

**Comment by aitboudad** [comment]
I see, so I think removing `FieldArrayType` decorators which was used to show deprecation would solve the issue then!

**Comment by JoostK** [comment]
> I see, so I think removing `FieldArrayType` decorators which was used to show deprecation would solve the issue then!

I'm not sure I understand; `FieldArrayType` should retain its `@Directive()` decorator as it extends from a class with Angular behavior. So the master branch is currently correct.

**Comment by vespertilian** [comment]
@aitboudad Happy to help out in any way I can, but as I understand it we just need to make the 5.x branch match the main branch that has FieldArrayType with an `@Directive()` decorator, so can we (you) just pull that in and release it? Or would you like a separate PR for the 5.x branch? I can do that if you like. Just let me know.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.13](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.13) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
