### ISSUE TITLE
Formly Tabbed UI

### ISSUE THREAD

**Issue by Stusaw** [ngx-formly/ngx-formly#2678]
Hello,

I've tried to recreate the material tabbed ui example but can't get any of the fields to render with the following code:
```
<mat-tab-group>
    <mat-tab *ngFor="let tab of field.fieldGroup; let i = index; let last = last;"
      [label]="tab.templateOptions.label"
      [disabled]="i !== 0 && !isValid(field.fieldGroup[i - 1])">
      <formly-field [field]="tab"></formly-field>

      <button *ngIf="last" class="btn btn-primary" [disabled]="!form.valid" type="submit">
        Submit
      </button>
    </mat-tab>
  </mat-tab-group>
```
It seems like I have to iterate like this:
```
<formly-field *ngFor="let field of tab.fieldGroup" [field]="field "></formly-field>
```
but even this does not work and the fields are not displayed. Do I have to add my own input directives here instead?

**Comment by aitboudad** [comment]
We may need a reproduction :pray: but I'd suggest checking our working example https://formly.dev/examples/advanced/tabs.

Feel free to reopen when you've got a reproduction.

**Comment by Stusaw** [comment]
Thanks for the reply. I am currently trying to create a stack for this but it appears to related to the latest versions of Angular.

I'll update here once I have a idea of the solution.
