### ISSUE TITLE
Update field and model when changes occur in other field. 

### ISSUE THREAD

**Issue by Adelost** [ngx-formly/ngx-formly#2679]
**Question**

I would like to update a field when the model of another field is changed. I have found a workaround, but I am wondering if there is a easier solution to the problem that I am missing.

This is a contrived example, but it illustrates the problem I am facing. I have created two text input fields with key "foo" and "bar". If field "foo" is changed I also would like to update field "bar" with the same value.

If I try this solution then "foo" is updated initially, but "bar" is not. However, writing inside the "foo" field, causes "bar" to be updated.

```ts
this.form.get('foo').valueChanges.subscribe(foo => {
  this.form.get('bar').setValue(foo);
})
this.model = { foo: 'new-value' };
```

![image](https://user-images.githubusercontent.com/609802/105881571-f74bae80-6004-11eb-98f1-aab37057af37.PNG)

If I instead try to update the model, then "bar" is updated correct initially, but "bar" does not pick up changes when writing inside "foo".

```ts
this.form.get('foo').valueChanges.subscribe(foo => {
  this.model.bar = foo;
})
this.model = { foo: 'new-value' };
```

![image](https://user-images.githubusercontent.com/609802/105882568-18f96580-6006-11eb-80e7-1760b38c127d.png)

If I combine both I finally get the expected behavior, "bar" is updated correctly initially and is able to listen to changes to "foo":

```ts
this.form.get('foo').valueChanges.subscribe(foo => {
  this.form.get('bar').setValue(foo);
  this.model.bar = foo;
})
this.model = { foo: 'new-value' };
```

![image](https://user-images.githubusercontent.com/609802/105883960-bacd8200-6007-11eb-9282-314252b1d5ed.png)

However, combining the two feels like a bit of a hack. Maybe there is a more straightforward solution that I am missing?

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2607#issuecomment-737913181
