### ISSUE TITLE
pattern Observable|http

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2680]
Today I have a crud that returns me a regex record, where I can use it within the system as needed.
I would like to be able to call within the pattern field a function that returns an observable with the regex string.
I couldn't find examples.

**Comment by aitboudad** [comment]
use `expressionProperties` which resolve observable value:
```ts
{
  expressionProperties: {
    'templateOptions.pattern': ...
  }
}
```

**Comment by GlauberF** [comment]
Thanks :)

**Comment by GlauberF** [comment]
@aitboudad Implementing it, I can't use it in expressionProperties, because an excessive call to the server (http) would have a different form?

**Comment by aitboudad** [comment]
When passing an observable, the call will be done just once

**Comment by GlauberF** [comment]
right. I thought better of it here, I will create a provider, which checks if a certain property exists within the templateOptions, if it exists, added the regex that comes via http to the pattern field.

Thank you.

**Comment by aitboudad** [comment]
wait if it's defined in multi fields of the same form multi calls will be made so if you want to optimize it you should cache the result instead of a direct call

**Comment by GlauberF** [comment]
excellent idea, I will do that.

**Comment by GlauberF** [comment]
I did some tests, but all result in an error, because the return is a promise and it seems to me by the error and inspecting the code, that the pattern field should be RegExp or string.
However it is an observable / promisse.

Erro:
![Captura de Tela_selecionar área_20210201100937](https://user-images.githubusercontent.com/11314585/106458822-afe37900-646f-11eb-9c70-dd0456d0e174.png)

Some ways that I have stated and that result in the above error.

![Captura de Tela_selecionar área_20210201102503](https://user-images.githubusercontent.com/11314585/106458852-beca2b80-646f-11eb-8d9c-8b9f40591a14.png)
![Captura de Tela_selecionar área_20210201102406](https://user-images.githubusercontent.com/11314585/106458854-bf62c200-646f-11eb-8a59-b4be183bcc0d.png)

**Comment by aitboudad** [comment]
you should pass an observable, if you're using Promise, then use `from` operator to resolve the promise value

**Comment by GlauberF** [comment]
Adjust according to what happened
![Captura de Tela_selecionar área_20210202110348](https://user-images.githubusercontent.com/11314585/106603988-c6f09c80-653d-11eb-960c-54ea0874c316.png)

But it keeps returning the error (TypeError: regex.test is not a function) and analyzing how the pattern field was assigned within templateOptions, I believe it will give an error.
Why it became an observable, not a String or RegExp
![Captura de Tela_selecionar área_20210202110139](https://user-images.githubusercontent.com/11314585/106604232-1cc54480-653e-11eb-906d-c9a6af37829b.png)

And analyzing the pattern field, you can see that the value of my regex is inside.
![Captura de Tela_selecionar área_20210202111345](https://user-images.githubusercontent.com/11314585/106604960-1c797900-653f-11eb-879c-04207e4a2046.png)

**Comment by aitboudad** [comment]
you should pass an observable and not a function, here is a working example: https://stackblitz.com/edit/angular-7gtpae?file=src/app/app.component.ts

**Comment by GlauberF** [comment]
A function was actually passing and then the observable returned, I corrected.
however there is a problem that I noticed and that testing in your example also gives this problem.

In your example you put it that way and it works perfectly, because it is passing a regex
```typescript
expressionProperties: {
    "templateOptions.pattern": of(/(\d{1,3}\.){3}\d{1,3}/)
}
```
But as this value comes from the database it is a string, ie the value comes within quotation marks, example:
```typescript
expressionProperties: {
    "templateOptions.pattern": of("/(\d{1,3}\.){3}\d{1,3}/")
}
```
In this case the value is always invalid, you can test here
https://stackblitz.com/edit/expressionproperties-regex-test?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
if the source is a string then make sure to return a `RegExp` instance https://stackblitz.com/edit/expressionproperties-regex-test-5uyuts
