### ISSUE TITLE
Regression v5.5.8 formControl.value and model not in sync

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#2684]
**Description**
In v5.5.8 a regression starts where the model is not correctly updated, formControl.value and model are not in sync.
The problem is in conjunction with ng-selectize.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ffxroy?file=src%2Fapp%2Fapp.component.html

- One option is selected, add a second option, add a third option, now we are out of sync.
- One option is selected, add a second option, remove one of the options, now we are out of sync.

**Your Environment**

- Angular version: 10.2, 11.1.11 (SB)
- Formly version: since 5.5.8 - 5.10.12

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.13](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.13) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
