### ISSUE TITLE
Implement NgbDatepicker to Formly

### ISSUE THREAD

**Issue by OrhanOzkercin** [ngx-formly/ngx-formly#2688]
**Question**

A clear and concise description of what the question is.

I want to add ngbootstrap date picker as a type to formly like the image below. Can anyone show me the road I should follow?

![ngb](https://user-images.githubusercontent.com/25130814/106396633-3d947980-641a-11eb-9708-166ad7b1d469.gif)

**Comment by aitboudad** [comment]
define a custom field type https://formly.dev/guide/custom-formly-field
