### ISSUE TITLE
Disable has side effect when having two fields with the same key

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#2689]
**Description**
When having two fields with the same key, disable set for one field, disables also the other field.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-pxykls?file=src%2Fapp%2Fapp.component.ts

The use of fields with the same name would be used in conjunction with hideExpression, like in QueryBuilder:
https://stackblitz.com/edit/ngx-formly-ui-material-querybuilder-ejcmh3?file=app%2Fformly-query-builder%2Futils.ts

**Comment by aitboudad** [comment]
There is no solution for that specific case as they share the same `FormControl` instance

**Comment by FritzHerbers** [comment]
Using the same `formControl` for multiple fields like QueryBuilder does, especially with different formly types and data structures, is problematic (e.g. input strings and arrays for selects).
I changed the QueryBuilder in the meantime to use different keys, e.g. values.field1, values.field2 and grab the selected field value at submit.
