### ISSUE TITLE
ERROR  Error: setting getter-only property "model"

### ISSUE THREAD

**Issue by egastorres79** [ngx-formly/ngx-formly#2690]
**Description**
I´m getting **Error: setting getter-only property "model"**, when I have a **formly-form** inside a **formly-form**.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-hoamzt

- Angular version: 11.1.1
- Formly version: 5.10.12

**Comment by aitboudad** [comment]
Using `formly-form` inside a `formly-form` is not recommended instead could you please try the following solution https://formly.dev/examples/advanced/tabs

**Comment by egastorres79** [comment]
Tks, I made it work with out problems using **formly-field**
