### ISSUE TITLE
form.value and model not in sync

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#2696]
**Description**
The model and form.value are getting out of sync. 

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-querybuilder-jtjbwe?file=app%2Fapp.component.ts
Press right/upper "-" to remove the ruleset around "field1"

The model and form.value are not in sync.

In my personal application with a specific ruleset, and after deleting rulesets (always the most upper one) and adding rules, the old rulesets start bleeding through (also in the model).

** Question **
When an element of a FieldArrayType is deleted, will all FieldTypes and further FieldArrayTypes be recursively deleted?

**Comment by aitboudad** [comment]
it is in sync, overridden internal Formly methods could produce such effect.
