### ISSUE TITLE
How cam make clearable a select list

### ISSUE THREAD

**Issue by alfredoizdev** [ngx-formly/ngx-formly#2697]
**Question**

Is any way if add icon on click in it allowed me to set my empty label back

        key: 'label',
        type: 'select',
        templateOptions: {
          floatLabel: 'always',
          placeholder: 'Select Detection Type',
          label: 'Detection',
          valueProp: 'key',
          labelProp: 'key',
          emptyLabel: 'any', // here my default empty value
          emptyOption: true,
        },
      },

**Comment by aitboudad** [comment]
The select type is the one provided by Formly or a custom one, also which UI do you use?

For material use Prefix/Suffix clear button https://formly.dev/examples/other/material-prefix-suffix
For bootstrap use addons https://formly.dev/examples/bootstrap-specific/input-add-ons
