### ISSUE TITLE
How to un-sync fields with the same key?

### ISSUE THREAD

**Issue by BabaDorin** [ngx-formly/ngx-formly#2699]
There are more fields in my form having the same key. The problem is that when I insert a value in one of them, that value will be automatically inserted in all of the fields having the same key as the first one, I know this is a normal formly behaviour, but I'm looking to disable this feature for my form.

I want my fields to be treated individually, event if their keys are not unique.

I'm using nesting forms which are based on the same model. For example - I have the 'Equipment' model with the 'identifier' property. I want to create a form to register a Computer, which is an 'Equipment', and it has a nested model - the PSU, which is also an 'Equipment', so the form structure will be the following:

```
Computer
|__model
|__identifier
|__Children:
          PSU
          |__model
          |__identifier
          |__Children:
```

When I type the computer's identifier, that value appears in the identifier field for the PSU too, I want them to be unlinked.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1882
