### ISSUE TITLE
Looking for npm module supporting dynamic tables based on ngx-formly

### ISSUE THREAD

**Issue by alindberg** [ngx-formly/ngx-formly#2700]
I am building an application that requires extensive use of table oriented data.  `Formly` seems to fit the bill with the exception of native supports for tables.. 

I my googling I have found the following example of a custom type implementation to supporting tables (Forked from the original to add class information to support rows.)

https://stackblitz.com/edit/angular-jhvhvn-tvjtyv

At one point in my wandering around google, I came across a custom npm package that extends `Formly` to supports tables with features such as sorting, pagination, etc.  The problem is I can't find it....

Can anyone provide a URL?

As a suggestion for `formly.dev`, it would be nice if the site would provide links to 3rd party packages/libraries that extend `formly`.

As always, thank you for your time.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2534#issuecomment-710868631
