### ISSUE TITLE
How to hide select placeholder from options

### ISSUE THREAD

**Issue by OrhanOzkercin** [ngx-formly/ngx-formly#2705]
**Question**

A clear and concise description of what the question is.

I added some text to placeholder but I don't want to this placeholder shown in options. Couldn't find easy way to do it. Is there any way to do it ?

<img width="278" alt="placeholder" src="https://user-images.githubusercontent.com/25130814/108064061-30f46000-706d-11eb-8407-2dbecd3d4c11.png">

<img width="314" alt="placeholdershwon" src="https://user-images.githubusercontent.com/25130814/108064057-2fc33300-706d-11eb-9a2b-d750b50e71fb.png">

**Comment by aitboudad** [comment]
not possible, the select box doesn't support `placeholder` so we use it as an option in order to have a placeholder in the select box.

instead, rely on a non-native select such as `ng-select` https://stackblitz.com/edit/angular-ngx-formly-ngselect-material-2bj3sf
