### ISSUE TITLE
Add option to create separate label for Angular Material template

### ISSUE THREAD

**Issue by patrickrioux** [ngx-formly/ngx-formly#2706]
The templateOptions is currently supporting the floatLabel although if you set templateOptions.floatLabel = 'never'; the Angular Material templates are not creating a label control for each supported component.

I am currently blocked with this. It this something that could be considered as a new feature?

In the mean time, I have tried to create a custom template but I am unable to compile the project. I am running Angular 11 and it is complaining about not being Ivy compatible. Is someone from this group have successfully override Angular Material select template using Angular 11?  I wish someone can provide a stackblitz demo.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2704#issuecomment-780095179
