### ISSUE TITLE
Content projection support

### ISSUE THREAD

**Issue by aleixsuau** [ngx-formly/ngx-formly#2707]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to separate the CSS/Layout from the form config when using Formly.

**Describe the solution you'd like**
Allow content projection.

**Describe alternatives you've considered**
```
  <formly-form [model]="model" [options]="options" [form]="form">
    <div *ngFor="let field of fields"
             fxLayout="dynamicValue">
        <formly-field  [field]="field">
        </formly-field>
    </div>
  </formly-form>
```

**Comment by aitboudad** [comment]
can you try the following alternative solution https://stackblitz.com/edit/ngx-formly-flex-layout

**Comment by aleixsuau** [comment]
Hi @aitboudad ,

Thank you for your response. I already saw this example but it is not what I'm looking for since it mixes layout and form config and, afaik, it doesn't allow dynamic values (e.g. fxLayout="dynamicValue").

Is there any reason/limitation to not allow content projection by design? If not, I could try to make a pull request.

Best

**Comment by aleixsuau** [comment]
Hi @aitboudad ,
I have created an example/proposal [here](https://stackblitz.com/edit/formly-content-projection). What do you think?
Thanks!

**Comment by aitboudad** [comment]
I liked your proposal but I have a better approach which I'm currently working on (in progress).
would you like to provide a doc instead once done?

**Comment by aitboudad** [comment]
let me know WDYT: https://github.com/ngx-formly/ngx-formly/issues/2710#issuecomment-792260405

**Comment by aleixsuau** [comment]
Hi @aitboudad ,

Great solution, let me know if you need help. 

I'd be glad to contribute to the docs. When do you plan to release it?

Best

**Comment by aitboudad** [comment]
> When do you plan to release it?

within 1 or 2 weeks.

> I'd be glad to contribute to the docs

:pray:
