### ISSUE TITLE
Can we use custom JSON format to generate forms?

### ISSUE THREAD

**Issue by avifox** [ngx-formly/ngx-formly#2708]
I am using the angular ngx-formly library to generate dynamic forms. I am following this example: https://stackblitz.com/angular/bxpovqrjjql?file=src%2Fapp%2Fapp.component.ts

The code makes use of a JSON format as below:

[
  {
    "key": "firstName",
    "type": "input",
    "templateOptions": {
      "label": "First Name"
    }
  },
  {
    "key": "lastName",
    "type": "input",
    "templateOptions": {
      "label": "Last Name"
    }
  },
  {
    "key": "mac",
    "type": "input",
    "templateOptions": {
      "label": "Mac Address",
      "pattern": "([0-9A-F]{2}[:-]){5}([0-9A-F]{2})"
    }
  },
  {
    "key": "color",
    "type": "input",
    "templateOptions": {
      "label": "Color Preference (try this out)"
    }
  },
  {
    "key": "reason",
    "type": "textarea",
    "templateOptions": {
      "label": "Why?"
    },
    "expressionProperties": {
      "templateOptions.label": "'Why did you choose ' + model.color + '?'"
    },
    "hideExpression": "!model.color"
  }
]
I need to use a different type of JSON as per below:

        "fields": [
            {
                "index": 0,
                "label": "First Name",
                "type": "text",
                "placeholder": "Enter First Name",
                "employeeMapping": {
                    "section": "Employee",
                    "key": "firstName"
                }
            }
        ]

Is this feasible with formly or do we need to use the standard JSON format provided?

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
