### ISSUE TITLE
How to display a hyperelink

### ISSUE THREAD

**Issue by Rossco8** [ngx-formly/ngx-formly#2709]
**Question**
How to display a simple HTML hyperlink in a form?

This is my custom type
```
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
 selector: 'formly-link-component',
 template: `
 <a [href]="to.url">{{ to.title }}</a>
 `,
})
export class FormlyLinkComponent extends FieldType {

}
```

In app.module.ts I have added
```
{ name: "link", component: FormlyLinkComponent },
```

Here is a stackblitz example. The link component is always ignored when loading from JSON
https://stackblitz.com/edit/ngx-formly-ui-material-fv4a2x?file=src/assets/simple.json

**Comment by aitboudad** [comment]
use `widget`:

```patch
{
  "type": "string",
+ "widget": {
+   "formlyConfig": {
+     "type": "link",
+     "templateOptions": { "url": "https:\/\/en.wikipedia.org\/wiki\/Chuck_Norris" }
+   }
+ }
}
```

https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527

**Comment by Rossco8** [comment]
thanks, that worked
