### ISSUE TITLE
Is it somehow possible to eliminate <formly-field>?

### ISSUE THREAD

**Issue by loxy** [ngx-formly/ngx-formly#2710]
**Is your feature request related to a problem? Please describe.**
I would like to use CSS Grid to style my forms. Therefore it is needed to eliminate this (`<formly-field>`) structural element, due to the internal working (direct children mechanics like CSS Flexbox) of CSS Grids. So, I need a structure like that:

```html
<formly-form class="css-grid" [form]="form" [fields]="fields" [model]="model">
  <ng-container *ngFor="let e of fields">
    <div class="label"></div>
    <div class="control"></div>
  </ng-container>
</formly-form>
```

To apply a CSS Grid on `<formly-field>` make not really sense, because each row is an "own" CSS Grid. What do your think?

**Comment by manuelmeister** [comment]
I think you could just set form-field to 
```css
formly-field {
   display: contents;
}
```

**Comment by aitboudad** [comment]
That's something I was thinking about and now I have the solution which is ready and it'll be introduced in `V6` alpha version.

Could you please help me find a better name for the opt-it :pray::

```patch
FormlyModule.forRoot({
+ extras: {
+   eliminateFormlyField: true,
+ },
}),
```

**Comment by manuelmeister** [comment]
I think it depends how you accomplish this.

What are the implications of this change anyway?

Just for the record, is it true that the author's example would undermine the basic functionality of Formly?

**Comment by aitboudad** [comment]
The new behavior will act like `<router-outlet></router-outlet>`, the content will be rendered right after the `formly-field` component and not inside.

Also I'm working on a way to define an inline type which allows override all formly types (including the core ones):

For example to define input type:

```html
    <form-form [form]="form" [fields]="fields" [model]="model">
      <ng-template formlyTemplate="input" let-field>
		<input [formControl]="field.formControl" />
      </ng-template>
    </form-form>
```

and `fields` which concern this issue it would be something like:

```html
    <form-form [form]="form" [fields]="fields" [model]="model">
      <ng-template formlyTemplate let-field>
        <ng-container *ngFor="let f of field.fieldGroup">
          <div class="label">...</div>
          <div class="control">...</div>
        </ng-container>
      </ng-template>
    </form-form>
```

Or: 
```
    <form-form [form]="form" [fields]="fields" [model]="model">
      <ng-template formlyTemplate let-field>
        <formly-field *ngFor="let f of field.fieldGroup" [field]="f"></formly-field>
      </ng-template>
    </form-form>
```


This will solve many issues including this one:

- https://github.com/ngx-formly/ngx-formly/issues/2707
- https://github.com/ngx-formly/ngx-formly/issues/2077
- https://github.com/ngx-formly/ngx-formly/issues/2086

hope you like it!

**Comment by manuelmeister** [comment]
For naming, I would choose something along the lines of _render formly field element: false_ because I think that way could/should be the new standard.

**Comment by kenisteward** [comment]
What about

externallyRenderFields: false

That way we define rendering fields as baseline internal to the firmly
field and this allows to externally render them.

**Comment by loxy** [comment]
> I think you could just set form-field to
> 
> ```css
> formly-field {
>    display: contents;
> }
> ```

That's right. But the support is still very  "experimental" and buggy. See: https://caniuse.com/css-display-contents.

I would also tend to name it `renderFormlyFieldElement: false`, but set it internally to true on default (so that the old behavior is the default).

**Comment by aleixsuau** [comment]
I think the proposal is great and makes Formly much more flexible:

- It allows detaching the form from the layout, so we don't need to declare wrapper components.
- It allows using input types without having to register them on the Formly module (I understand that it would work with any Form ControlValueAccessor, right?). This way we'd be able to use lazy-loaded components.
-It keeps the default functionality.

Thanks!

**Comment by manuelmeister** [comment]
> That's right. But the support is still very "experimental" and buggy. See: https://caniuse.com/css-display-contents.  

I looked it up on MDN: https://caniuse.com/mdn-css_properties_display_contents
I don't understand the difference between the two datasets, so you are probably right to be suspicious.

----

@aitboudad very cool, I like the improvement!

**Comment by beeman** [comment]
@aitboudad great to see this feature being added! Just what I was looking for too!

I agree with the others that `renderFormlyFieldElement: false` would be a good way to configure this.

**Comment by ahmedderkaoui** [comment]
When the release will be published ?

**Comment by aitboudad** [comment]
Late Today/ or Tomorrow I'll push an initial work, but be aware it's an alpha version and your feedback is a must 😄.

👍 for `renderFormlyFieldElement`

**Comment by ahmedderkaoui** [comment]
Could it be applied also the the <formly-group> tag (Which I really want to omit with the formly-field 😞) ?

**Comment by aitboudad** [comment]
You can now give it a try by using `6.0.0-next.1`

**Comment by aitboudad** [comment]
@ahmedderkaoui 

1. `formly-field`: use `renderFormlyFieldElement`

```ts
FormlyModule.forRoot({
  extras: { renderFormlyFieldElement: false },
})
```

2. `formly-group`: either override the default `formly-group` type or use the inline type (better approach):

```html
<form-form [form]="form" [fields]="fields" [model]="model">
  <ng-template formlyTemplate let-field>
    <formly-field *ngFor="let f of field.fieldGroup" [field]="f"></formly-field>
  </ng-template>
</form-form>
```

for those who're willing to upgrade from `v5` check the [UPGRADE-6.0.md](https://github.com/ngx-formly/ngx-formly/blob/main/UPGRADE-6.0.md)

**Comment by aleixsuau** [comment]
Hi @aitboudad ,

Nice, it works fine, thank you very much. 

In my case, adding ``extras: { renderFormlyFieldElement: false }`` doesn't make any difference, both ways (with custom formlyTemplate and without) worked well.

I like it this way because:
- The experience is smoother; the form behaves as always and if you pass a ``formlyTemplate`` then the formly-form uses it without the need of configuring the global behavior (renderFormlyFieldElement).
- It allows using both flavors everywhere. The renderFormlyFieldElement in the forRoot seems to indicate that all the forms in the app will behave the configured way (renderFormlyFieldElement or not), which would be limiting.

I start working on the docs.

Cheers!

**Comment by ahmedderkaoui** [comment]
Here is a solution that worked well for me (no need here to set something inside Formly, only CSS trick):

in your styles.css, add :
```
formly-group {
    display: contents;
}

formly-field {
    display: contents;
}
```
and for each `FieldType` and `FieldWrapper` you have in your project, and which it seems not to be shown correctly with CSS, do the same as above with its Component Selector. 

Example :
```
..
@Component({
 selector: 'buttonType',
 template: `
 // TEMPLATE
 `,
})
..
```
add:
```
buttonType {
    display: contents;
}
```

**Comment by aitboudad** [comment]
Another interesting feature not related to this issue but I would like to know your thoughts if you've any :smiley:, please let me know https://github.com/ngx-formly/ngx-formly/issues/2853
