### ISSUE TITLE
How to split column form fields with FormlyMaterialModule

### ISSUE THREAD

**Issue by ricBun** [ngx-formly/ngx-formly#2711]
Hi there, I'm trying to follow example shown here: [advanced layout](https://formly.dev/examples/bootstrap-specific/advanced-layout). trying to have more than one field in one row.

From looking at the code, it seems that it is using the FormlyBootstrapModule, is there anyway I can achieve the same sort of column splitting layout with the FormlyMaterial UI?

**Comment by BukicMicko** [comment]
@ricBun not to much experience with Material but maybe you can use layout grid from  @material/layout-grid (https://material.io/develop/web/supporting/layout-grid)? Apply material classes like example for Bootstrap.
