### ISSUE TITLE
Generate a PDF of the form values

### ISSUE THREAD

**Issue by sonalswarnkar25** [ngx-formly/ngx-formly#2715]
Can we generate a pdf through JSON?

We have a tabular form and need to generate PDF of form values such that the layout is same as the form.

Alternate option can be generating PDF of single page form with same layout and values as the form.

**Comment by MaxKless** [comment]
I feel like this really isn't in the scope of what formly is for or should be able to do. Maybe look into a tool to convert html to pdf? There's a lot of those on the internet.
