### ISSUE TITLE
Material Autocomplete

### ISSUE THREAD

**Issue by d4rkglow** [ngx-formly/ngx-formly#2718]
There seems to be an issue with the current version of formly, together with the angular (utilising angular material).
![Screenshot 2021-02-26 155419](https://user-images.githubusercontent.com/74179150/109315681-18453080-784b-11eb-84b8-8e4b2e2aa2af.png)

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction, the `filter` option need to be defined for the autocomplete type:

```patch
    {
      key: 'Autocomplete',
      type: 'autocomplete',
      templateOptions: {
+       filter: ...,
      },
    },
```
