### ISSUE TITLE
What is the best approach for reusable sub-forms?

### ISSUE THREAD

**Issue by cca-developer** [ngx-formly/ngx-formly#2719]
**Question**
I have what will eventually be a very large form, and I would like to break it down into smaller components for better maintainability.  It seems like the approach suggested [here](https://github.com/ngx-formly/ngx-formly/issues/1045#issuecomment-406040078) would be ideal for this.  I would like to be able to create separate files for each portion of the form, such as:
```
export const DwgRevTitleBlockForm = {
  name: 'dwg-rev-title-block',
  extends: 'formly-group',
  defaultOptions: {
    fieldGroup: [
      ...
    ]
  }
};
```
However, I am going to have a number of fields where I need to use a service to populate the select options, so just having a `const` file won't work for that.  I thought about trying to create a custom template for some of the select fields, thinking that I could then reference their type directly in the `const` file.  Here's my attempt at that:

```
@Component({
  selector: 'employee-form',
  templateUrl: './employee-form.component.html',
  styleUrls: ['./employee-form.component.scss']
})
export class EmployeeFormComponent extends FieldType {
  formControl!: FormControl;

  field: FormlyFieldConfig = {
    key: 'employee',
    type: 'select',
    templateOptions: {
      label: 'Employee',
      options: this.employeeService.getAllMinimal(),
      valueProp: 'employeeID',
      labelProp: 'lastName'
    }
  };

  constructor(private employeeService: EmployeeService) {
    super();
  }
}
```
with
```
<mat-label *ngIf="to.label">{{ to.label }}</mat-label>
<mat-select [formControl]="formControl" [formlyAttributes]="field">
  <ng-container *ngFor="let item of (field.templateOptions?.options | async)">
    <mat-option [value]="item.value">{{ item.label }}</mat-option>
  </ng-container>
</mat-select>
```
But I haven't gotten that to actually compile yet.

Am I even on the right track, or is there some other approach that I should be using to break down a complex form?  Thanks!

**Comment by aitboudad** [comment]
You can adjust the field using `onPopulate` function:

```ts
export class EmployeeFormComponent extends FieldType implements FormlyExtension {
  formControl!: FormControl;

  onPopulate(field: FormlyFieldConfig) {
    // skip if the field is already initialized
    if (field.fieldGroup) {
       return;
    }

    field.fieldGroup = [{
      key: 'employee',
      type: 'select',
      templateOptions: {
        label: 'Employee',
        options: this.employeeService.getAllMinimal(),
        valueProp: 'employeeID',
        labelProp: 'lastName'
      }
    }];
  }


  constructor(private employeeService: EmployeeService) {
    super();
  }
}
```

**Comment by cca-developer** [comment]
Okay, that sounds promising.  What should my template look like for that?  What I have above is throwing errors related to `field.templateOptions.options | async`.  I'm just wanting to use a material select field.  Thanks for the help!

**Comment by cca-developer** [comment]
@aitboudad, I'm still having a hard time getting the template correct.  I'm not sure if I'm over-complicating it, or if I'm not including stuff that I need.  But that goes back to my original question: what is the recommended approach for reusable sub-forms?  If this is the best approach, it may be nice to have an example somewhere for people to follow.

**Comment by cca-developer** [comment]
Okay, I got something that appears to be working.  The template can be as simple as:
`<formly-field *ngFor="let field of field.fieldGroup" [field]="field"></formly-field>`

**Comment by aitboudad** [comment]
> Is this the recommended approach for reusable sub-forms?

yes, we used the same approach for array type https://formly.dev/examples/advanced/repeating-section

**Comment by tarektaamali** [comment]
> You can adjust the field using `onPopulate` function:
> 
> ```ts
> export class EmployeeFormComponent extends FieldType implements FormlyExtension {
>   formControl!: FormControl;
> 
>   onPopulate(field: FormlyFieldConfig) {
>     // skip if the field is already initialized
>     if (field.fieldGroup) {
>        return;
>     }
> 
>     field.fieldGroup = [{
>       key: 'employee',
>       type: 'select',
>       templateOptions: {
>         label: 'Employee',
>         options: this.employeeService.getAllMinimal(),
>         valueProp: 'employeeID',
>         labelProp: 'lastName'
>       }
>     }];
>   }
> 
> 
>   constructor(private employeeService: EmployeeService) {
>     super();
>   }
> }
> ```

@aitboudad  how call this component inside formlyField config??

**Comment by aitboudad** [comment]
**Note**: In `v6` a new approach is introduced for reusable sub-forms: [formly.dev/docs/guide/formly-field-presets](https://formly.dev/docs/guide/formly-field-presets).

**Comment by tarektaamali** [comment]
@aitboudad in my case ,I'm using version 5

**Comment by tarektaamali** [comment]
> You can adjust the field using `onPopulate` function:
> 
> ```ts
> export class EmployeeFormComponent extends FieldType implements FormlyExtension {
>   formControl!: FormControl;
> 
>   onPopulate(field: FormlyFieldConfig) {
>     // skip if the field is already initialized
>     if (field.fieldGroup) {
>        return;
>     }
> 
>     field.fieldGroup = [{
>       key: 'employee',
>       type: 'select',
>       templateOptions: {
>         label: 'Employee',
>         options: this.employeeService.getAllMinimal(),
>         valueProp: 'employeeID',
>         labelProp: 'lastName'
>       }
>     }];
>   }
> 
> 
>   constructor(private employeeService: EmployeeService) {
>     super();
>   }
> }
> ```

can you provide an example  in stackblitz ? @aitboudad
