### ISSUE TITLE
is FormlyFieldConfig contains component as properties-options.md says?

### ISSUE THREAD

**Issue by ha-akelius** [ngx-formly/ngx-formly#2729]
from  properties-options.md : 

https://github.com/ngx-formly/ngx-formly/blame/main/demo/src/app/guides/properties-options.md#L39
says
`| component            | `any`        | Can be set to replace the component that is defined in `type`. |`

but I can't find `component` property inside [fieldconfig](https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/models/fieldconfig.ts#L6)

**Comment by aitboudad** [comment]
Not supported yet, we'll provide it in `V6` but not soon.
In case you need that feature just sent me an email and I'll provide you the solution.
