### ISSUE TITLE
Understanding the differences between model and formstate.model

### ISSUE THREAD

**Issue by Stusaw** [ngx-formly/ngx-formly#2730]
I've been having a few difficulties getting my views to update with changes I am making to the model and trouble in combining this with hideExpressions. 

First thing I've noticed is that in hideExpressions is that the model parameter is always empty. No matter what changes I apply?. This has led me to explore using formstate.mainModel, but with this I am finding it very hard to keep the whole UI in the correct updated state with this.model. 

For example I may retrieve a collection asynchronously and push it to the model but nothing is reflected unless I call this.options.resetModel({...this.model}). All examples of creating a new reference like this.model = {...this.model} did not work.

Is there a correct approach to follow as I seems confusing that I should constantly need to keep models in sync when ngx=formly is built on reactive forms?

I will provide a stackblitz for you but was hoping you may be able to give me some pointers in the first instance.

Many thanks

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614
