### ISSUE TITLE
minLengh and maxLength don't work for TO type 'number'

### ISSUE THREAD

**Issue by alindberg** [ngx-formly/ngx-formly#2733]
**Description**
When the TO type is number, the `minLength` and `maxLength` validators don't work.

**Minimal Reproduction**
Simply change the example [stackblitz](https://stackblitz.com/angular/mjnkagoqqvg?file=src%2Fapp%2Fapp.component.ts): password field type to number.

**Additional context**
In many cases it is easier to specify the length of a string of digits rather than the max and minimum values

**Comment by alindberg** [comment]
To work around this limitation, I created a custom validator and message:

    {
        key:             'numberStgring',
        type:            'input',
        templateOptions: {
          label:    'This is a string of numbers 7 to 10 digits,
          required: true,
          type:     'number',
          minLength: 7,
          maxLength: 10
        },
        validators: {
          validation: ['stlLen', 'stlLenValidator']
        }`

In `app.module.ts`: 

    export function stlLenValidator(control: FormControl): ValidationErrors {
      return !control.value || /^(\d{7,10})$/.test(control.value) ? null : { stlLen: true};
    }


    export function stlLenValidatorMessage(err, field: FormlyFieldConfig) {
      const maxLen = field.templateOptions.maxLength; const minLen = field.templateOptions.minLength; 
      return `${field.templateOptions.label} must be between ${minLen} and ${maxLen} digits`;
    }

    FormlyModule.forRoot({
      validationMessages: [
        { name: 'stlLen', message: stlLenValidationMessage }
      ],
      validators: [
        { name: 'stlLenValidator', validation: stlLenValidatorFN}
      ]
    }),

**Comment by aitboudad** [comment]
Custom validator would do the job, the `maxLength` and `mixLength` validator is intended to be used only for types that have a numeric `length` property, such as strings or arrays.
