### ISSUE TITLE
Material form-field wrapper issue when using type number

### ISSUE THREAD

**Issue by guuurris** [ngx-formly/ngx-formly#2734]
The **"floating label"** above a Formly form input does not float when using an input field with type number. It looks correct for any value except **0**. Input field of type **text** is not affected with this issue

The problem can be seen in the field **Minimum** that is an input with type number (screenshot from my project)

![Screenshot from 2021-03-02 13-49-55](https://user-images.githubusercontent.com/4192534/109651331-acbad600-7b5e-11eb-8fb7-d6b6f79f958d.png)

I think the issue can be fixed by making a stronger value check on currentValue here:

https://github.com/ngx-formly/ngx-formly/blob/55d414415b1d627e2866f0efb76ff954d62b61f8/src/ui/material/form-field/src/form-field.wrapper.ts#L97

My package.json:

``` json
    "@angular/core": "9.0.6",
    "@ngx-formly/core": "^5.10.6",
    "@ngx-formly/material": "^5.10.6",
    "@ngx-formly/schematics": "^5.10.6",
```

**Comment by aitboudad** [comment]
it seems working as expected https://stackblitz.com/edit/angular-hfh3qz, I may need a reproduction example.

feel free to reopen once you've got a reproduction example.
