### ISSUE TITLE
Custom component with AG grid not tightly coupled with formly need to bind the rowselections of aggrid to formly field model

### ISSUE THREAD

**Issue by mayankagarwal8188** [ngx-formly/ngx-formly#2735]
**Question**
I have used ag grid as custom component of formly and not binded the aggrid tightly with formly meaning its just a custom component and i am not passing the gridoptions and other properties from formly. So how should i bind the row selections of ag grid to formly model.

**Comment by aitboudad** [comment]
the question is not clear, you may check `ag-grid` example in our doc https://formly.dev/examples/advanced/grid-integration
