### ISSUE TITLE
Where to put our config file?

### ISSUE THREAD

**Issue by OrhanOzkercin** [ngx-formly/ngx-formly#2739]
Hello, 
 I was wondering how to handle my formly settings.  Now I have a separate file that holds my formly field config and I am getting these fields from my TypeScript file. But in this way, I can not use lifecycle hooks of formly. So I was wondering how to scruct my formly field settings in Angular generally. In case it's not clear I'm adding an example of my problem.

![Screenshot_1](https://user-images.githubusercontent.com/25130814/110090610-85efe000-7da8-11eb-8bf3-7152ea2ab34a.png)
![Screenshot_2](https://user-images.githubusercontent.com/25130814/110090612-86887680-7da8-11eb-91de-655f7dc09fae.png)

**Comment by aitboudad** [comment]
I think you use `hooks` of Formly unless there is you need some defined variable in the AppCompoent if so simply pass those dependencies to the `data` function as arguments.
