### ISSUE TITLE
Required field shown in black color instead of Red. Reason: Angular is adding a CSS class ng-star-inserted

### ISSUE THREAD

**Issue by shaleen76** [ngx-formly/ngx-formly#2744]
In ngx-formly for any field when we provide required: true then the asterisk is shown in black color instead of red. 
Reason when using Angular Material, Angular is adding a CSS class to all HTML elements ng-star-inserted. 

Can you please resolve this issue and provide the asterisk to be in Red or Custom color.

http://benprograms.net/2018/06/30/angular-ng-star-inserted/

**Comment by aitboudad** [comment]
> In ngx-formly for any field when we provide required: true then the asterisk is shown in black color

not sure that is related to `ng-star-inserted`,  Angular Material itself had that class:

![image](https://user-images.githubusercontent.com/1753742/111164963-d16f6e80-859e-11eb-8074-861cd2e9ad8d.png)

**Comment by aitboudad** [comment]
Feel free to reopen if you have a reproduction example!
