### ISSUE TITLE
custom type change not getting detected

### ISSUE THREAD

**Issue by anushreenk** [ngx-formly/ngx-formly#2747]
Hi I have created custom type:
import { Component, EventEmitter, Output } from '@angular/core';
import { MatCalendarCellCssClasses } from '@angular/material/datepicker';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'formly-field-inline-date',
  template: `

  <mat-card class="calenderWrapper">
  <mat-calendar 
  [selected]="selectedDate" 
  [startAt]="to.startAt"
  [minDate]="to.minDate" 
  [maxDate]="to.maxDate" 
  [(dateFilter)]="dateFilter" 
  [dateClass]="dateClass()" 
  (selectedChange)="onSelect($event)"
  (monthSelected)="handleMonthSelected($event)"
  (yearSelected)="handleYearSelected($event)"
  ></mat-calendar>
</mat-card>
<input type="hidden" [formControl]="formControl" [formlyAttributes]="field" value="{{this.selectedDate}}">
  `,
})
export class FormlyFieldInlineDatePicker extends FieldType  {
  renderer: any;
  // renderer: any;
  //  monthPrevBtn = document.querySelectorAll(
  //   '.mat-calendar-previous-button'
  // );
  ngOnInit(): void {
    console.log("init");
  }
  ngOnChanges() {
    console.log("onchange");
  }
  ngDoCheck() { 
    console.log("Do check")
    console.log(this.to.dateDisabled);
    //console.log(this.to.dateDisabled1);
  }
  ngAfterViewInit() {
    console.log("here221122");
    const monthPrevBtn = document.querySelectorAll(
      '.mat-calendar-previous-button'
    );
    const monthNextBtn = document.querySelectorAll('.mat-calendar-next-button');

    if (monthPrevBtn) {
      Array.from(monthPrevBtn).forEach((button) => {
        this.renderer.listen(button, 'click', (event) => {
          //handle month change
          console.log("month");
        });
      });
    }

    if (monthNextBtn) {
      Array.from(monthNextBtn).forEach((button) => {
        this.renderer.listen(button, 'click', (event) => {
          //handle month change
          console.log("month");
        });
      });
    }
  }
    selectedDate:any;
   // this.to.datetoHighlight = ["2021-02-18", "2021-02-17"];
  datas=[];
    constructor(){
        super();

     
    }
  
  onSelect(event) {
   
    if (this.to.onClick) {
      this.selectedDate = event;
      this.formControl.setValue(this.selectedDate);
     this.to.onClick(event);
    }
   
  }
  
  handleMonthSelected(event) {
    console.log("Month changed", event);
    //handler logic
}
handleYearSelected(event) {
  console.log("Year changed", event);
  //handler logic
}
dateFilter = (d: Date): boolean => {
//const time=d.getTime();
//return !this.to.dateDisabled.find(x=>x.getTime()==time);
return this.to.dateDisabled.findIndex(item => item.toDateString() == d.toDateString()) < 0;
}

dateClass() {
  return (date: Date): MatCalendarCellCssClasses => {
    const highlightDate = this.datas.map(strDate => new Date(strDate))
      .some(d => d.getDate() === date.getDate() && d.getMonth() === date.getMonth() && d.getFullYear() === date.getFullYear());
    return highlightDate ? 'special-date' : '';
  };
}
}

and 

on change of option of radio button  i need to change the disable date value and show the updated calender
here is my json
--------------
{
          key: 'Radio',
          type: 'radio',
          templateOptions: {
            label: 'Radio',
            placeholder: 'Placeholder',
            description: 'Description',
            required: true,
            options: [
              { value: 1, label: 'Option 1' },
              { value: 2, label: 'Option 2' },
              { value: 3, label: 'Option 3' },
              { value: 4, label: 'Option 4', disabled: true },
            ],
            change: (field, $event) => {
              console.log("change");
              this.tobeDisabled = [new Date('2021-03-21'),
  new Date('2021-03-23'),
  new Date('2021-03-16')];
            }
          },
          expressionProperties: {
           // 'templateOptions.options[0].extra':"test", 
          }
          
        },
 {
          key: "date",
          type: "inline_datepicker",
          
          templateOptions: {
            
            className:"",
            selectedDate:'',
          startAt:'',
          minDate:'',
          maxDate:new Date(new Date().setMonth(new Date().getMonth() + 1)),
       
       
         dateDisabled: this.tobeDisabled
   
        datetoHighlight: ["2021-02-18", "2021-02-17"],
            required: true,
            onClick: ($event) => console.log($event),
          },

``````````````````
how can I achive it?

**Comment by aitboudad** [comment]
Try the following solution instead, by subscribing to Radio change inside `date` field so you can have access to the `date` field instance

```ts
{
  key: "date",
  type: "inline_datepicker",
  hooks: {
    onInit: (field) => {
       return field.form.get('Radio').valueChanges.pipe(
         tap(() => {
           field.templateOptions.tobeDisabled = [
             new Date('2021-03-21'),
             new Date('2021-03-23'),
             new Date('2021-03-16'),
           ];
         }),
       );
    }
  }
}
```

**Comment by abhihotmail** [comment]
V6 is still in-progress I think.  is it stable..Can I upgrade from 5.10.21?
