### ISSUE TITLE
JSONSchema with string of arrays is not validated correctely

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2750]
**Description**
For a required array property with a minimum of string items and each string has a minimal length. An empty model should not be valid.

**Minimal Reproduction**
Go to:
- https://stackblitz.com/edit/angular-array-required?file=src%2Fassets%2Fjson-schema%2Farrays.json

The `Submit` button should not be enabled.

**Your Environment**

- Angular version: X.Y.Z
- Formly version: X.Y.Z

**Additional context**

**Comment by aitboudad** [comment]
minLength should not ignore the empty string value in addition we need to add also type validator
