### ISSUE TITLE
multi-field validator without FormlyModule definition

### ISSUE THREAD

**Issue by rainerhahnekamp** [ngx-formly/ngx-formly#2760]
Is it possible to have multi-field validators without defining them in a `FormlyModule`? Like it can be done with the normal validators, it would be good if I can define them individually per form.

Example: https://stackblitz.com/edit/ngx-formly-ui-material-me9vis?

Thank you

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/ngx-formly-ui-material-5jcez5?file=src/app/app.component.ts
