### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.  -- Nebular Stepper

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2763]
⭐

**Question**
I am using Nebular theme based Stepper and I get the above / following error when the form is initialized.

Please find attached a Stackblitz that reproduces the issue.

[https://stackblitz.com/edit/github-7hbtnh-yyz6mm](https://stackblitz.com/edit/github-7hbtnh-yyz6mm)

Can I please request your help in figuring out what I am doing wrong in this setup?

Additionally I looked at your updated Stepper solution and followed the steps and created this forked Stackblitz.

[https://stackblitz.com/edit/github-7hbtnh](https://stackblitz.com/edit/github-7hbtnh)

I am missing a few things in here and would like your feedback on how to get the result similar to the previous example.
*** ExpressionChanged error does not appear in this case.
1. labels are not getting populated
2. Save and Update buttons don't show up  
3. since the save / update button are now in the custom stepper what is the best way to pass events between the two component

Thanks

**Comment by argupta23** [comment]
@aitboudad 
Can I please request your help with this one? 
Thx.

**Comment by aitboudad** [comment]
That was a known issue which we solved by updating our approach so just make sure you follow the same approach as our doc example shows: https://formly.dev/examples/advanced/multi-step-form.
