### ISSUE TITLE
Allow FormlyValidationMessage to display FormControl error messages by default

### ISSUE THREAD

**Issue by aleixsuau** [ngx-formly/ngx-formly#2765]
**Is your feature request related to a problem? Please describe.**
Currently, the FormlyValidationMessage seems to only show error messages defined in the validationMessages' array of the FormlyModule config, so dynamically error messages returned from FormlyFieldConfig.validators.validation are not shown.

**Describe the solution you'd like**
Show FormControl.errors messages by default. Show Global validationMessages if there is no FormControl message for the error.

**Describe alternatives you've considered**
It would be nice that the FormlyValidationMessage would give priority to the FormControl.errors[FormlyFieldConfig.key].message, defaulting to the validationMessages[FormlyFieldConfig.key] if no present.

**Comment by aitboudad** [comment]
I think it does https://formly.dev/examples/validation/validation-message
if the validator target the child field then pass it through `errorPath` (check the [allow passing multiple errors from a single validator section](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.0)

**Comment by aleixsuau** [comment]
Thanks @aitboudad
