### ISSUE TITLE
Custom Mat Form Field Wrapper

### ISSUE THREAD

**Issue by Stusaw** [ngx-formly/ngx-formly#2766]
I am trying to adapt the out-of-the-box mat-form-field wrapper by creating a custom wrapper. It's essentially a copy/paste of yours, with a different wrapper name.

The error I recieve is 
Error: mat-form-field must contain a MatFormFieldControl

My assumption is that because this is a wrapper it doesn't know the field type?

```
 <mat-form-field
        [hideRequiredMarker]="true"
        [floatLabel]="to.floatLabel"
        [appearance]="to.appearance"
        [color]="to.color"
        [style.width]="'100%'"
      >
        <ng-container #fieldComponent></ng-container>
```
Any help appreciated. TIA

**Comment by Stusaw** [comment]
https://stackblitz.com/edit/ngx-formly-ui-material-ngx1ht?file=src%2Fapp%2Fapp.component.ts

**Comment by betorobson** [comment]
I am facing the same problema, any tip?

**Comment by Stusaw** [comment]
Nothing sorry. I'm currently just using the shipped form-field wrapper and just using the available templateOptions to show/hide/configure what I need.

**Comment by aitboudad** [comment]
Our current implementation is a little complicated and relies on private API of Material so I would avoid extending our implementation but that's up to you 😄!

The Custom Mat Form Field Wrapper that you're using is not the same version of `V5` branch so either uses the `FormlyWrapperFormField` of `V5` branch or make a copy of [FieldType](https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/material/form-field/src/field.type.ts) to extends in your custom type.
