### ISSUE TITLE
Add/remove fields in the FieldArray in case of using virtual scroll

### ISSUE THREAD

**Issue by Sash-OK** [ngx-formly/ngx-formly#2770]
Hello!

Thanks for this powerful library!

What is the proper way to add/remove items in FieldArray programmatically in case of use virtual scroll?
Here is [an example](https://stackblitz.com/edit/angular-ivy-srq2ot) with my problem. It works only if I recreate the fields inside parent form component.
**add** and **remove** buttons inside the FieldArray component modify the array of fields(you can see it at the top of the exaple), but changes are not displayed.
Should I recreate the fields each time when model changed or there is a better way?

**Comment by aitboudad** [comment]
I'll provide a fix for that, for a workarround try the following solution:

```ts
  remove(i) {
    super.remove(i);

    this.field.fieldGroup = [...this.field.fieldGroup];
  }
```

**Comment by Sash-OK** [comment]
@aitboudad 
It works, Thanks for the quick response!

**Comment by alindberg** [comment]
I was able to use a `fieldGroup` inside a `fieldArray` using the Material UI and inline forms.  See [here](https://stackblitz.com/edit/angular-material-formly-table?file=src/app/formly/my-formly-array-type.component.ts).

My solution uses calls to `super.add(idx)` and `super.remove(idx)` then calling `this.table.renderRows()`;  The important bits of the formly custom type component are below.

     @ViewChild('formTable', { static: true }) table: MatTable<any>;      

     constructor(injector: Injector) {  super();   }

     remove(e?) {
        super.remove(e);
        this.table.renderRows();
     }
    
     add(e?) {
        super.add(e);
        this.table.renderRows();
     }
