### ISSUE TITLE
Bind dynamic data to template field on click of other field in angular formly

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2771]
**I have been using a form in which there is a section in which I display dynamic HTML, I made use of the template field in which I am initializing HTML on load. When I click the other field value I need to change this HTML however the value change is assigned but not reflected in HTML UI, I have created stackblitz example for the scenario: **

[Click here stackblitz demo](https://stackblitz.com/edit/formly-example-uqzopj?file=src/app/app.component.ts)

**Initialized HTML value is following:**

` htmlValue =   '<p>test</p>';`

field value assigned : 
    `{
        template : this.htmlValue
      }`

**On click of submit button assigned HTML is following:**

`  this.htmlValue = ``<div>
              <p class="mb-2"><b>Maximum Spend Per Cricketer:</b></p>
              <div class="alert alert-secondary border flex-column mb-0">
                <div class="row">
                  <div class="col">Snacks:</div>
                  <div class="col">$15.00</div>
                </div>
                <div class="row">
                  <div class="col">Breakfast:</div>
                  <div class="col">$25.00</div>
                </div>
                <div class="row">
                  <div class="col">Lunch:</div>
                  <div class="col">$45.00</div>
                </div>
              </div>
            </div>``

Please help me to replace the html in the UI with the new one

**Comment by chandelshashank** [comment]
@aitboudad  It would be helpful if you can help (Y)

**Comment by chandelshashank** [comment]
I tried by adding getter to the FormlyFieldConfig it worked as expected but in my implementation, I cannot apply a getter as I did in the demo **so is there any other alternative to achieve this ?**
Stackblitz example demo by applying getter [Click here](https://stackblitz.com/edit/formly-example-yh7jcm?file=src/app/app.component.ts)

**Comment by quietgecko** [comment]
See if this example from @aitboudad helps: [https://github.com/ngx-formly/ngx-formly/issues/1302] Dynamic Custom template

**Comment by chandelshashank** [comment]
Thanks for suggesting me the article, i have managed to achieve this and realized that I changed directly the htmlValue but the field value is not changed. A simple way to solve this would be to use a getter function and other way would be accessing the field and setting it. 

Here is the change in code by using getter function :
`get fields(): FormlyFieldConfig[] {
    return [
      {
        key: "header",
        type: "input",
        templateOptions: {
          type: "text",
          label: "Page Header",
          placeholder: "Enter page header",
          required: true
        }
      },
      {
        template: this.htmlValue
      }
    ];
  }`

Please find below the link for Demo of the solution [Click here Demo](https://stackblitz.com/edit/formly-example-qwblgb?file=src/app/app.component.ts)

**Comment by aitboudad** [comment]
use `expressionProperties`: https://github.com/ngx-formly/ngx-formly/issues/2057#issuecomment-579724475

**Comment by chandelshashank** [comment]
Can I use for loop to bind to template in expression properties ? 
As I am binding to html that will have multiple rows so I wanted to use for each to bind but was unable to do that.
