### ISSUE TITLE
Problem with adding formControl to the from using hideExpression in Stepper/Tab field type.

### ISSUE THREAD

**Issue by abdelkrimAitaddi** [ngx-formly/ngx-formly#2774]
⭐

**Description**

hey,
i forked your example on Stackblitz: how to setup a Stepper/Tab field type. The stepper validation work  fine until i add a new field with `hideExpression`.

the problem is address `formControl` is not added to formGroup when `hideExpression` is false.

```
  {
  key: 'age',
  ...
  },
  {
      key: 'address',
      type: 'input',
      templateOptions: {  
        required: true
      },
      hooks: {
        onInit: (field) => {
          field.hideExpression = (model) => !model.age
        }
      }
  }
```
i know that `hideExpression` detach the `formControl` from it's parent but i expect that the `formControl` for address field will be added to the form when the `hideExpression` is false.
can you check it please ?

**Minimal Reproduction**
https://stackblitz.com/edit/angular-yu7bzv-3fc482

**Your Environment**

- Angular version: 11.0.6
- Formly version: ^5.10.14

**Comment by aitboudad** [comment]
assign the `hideExpression` on `onInit` is not supported and may produce unexpected behavior and require to rebuild the form in order to work properly, it should be passed in the `field` instead:

```patch
{
  key: 'address',
  type: 'input',
  templateOptions: {  
    required: true
  },
+  hideExpression: (model) => !model.age,
-  hooks: {
-    onInit: (field) => {
-        field.hideExpression = (model) => !model.age
-    }
-  }
}
```

we may consider supporting a such case if there is a real need.
