### ISSUE TITLE
Addon wrapper (suffix) not working with datepicker?

### ISSUE THREAD

**Issue by Zdenalus** [ngx-formly/ngx-formly#2775]
Hi,

I use formly material and I have problem to display datepicker and addon wrapper suffix at the same time.
Thank you for suggestions a comments

BR
Zdenek

**Comment by aitboudad** [comment]
The suffix is used by `mat-datepicker-toggle` what do you want to achieve?

**Comment by Zdenalus** [comment]
Hi, I use addon wrapper to display additional icons, I need it for datepicker too.

**Comment by aitboudad** [comment]
In [v5.10.16](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.16) release, you can re-use the mat internal prefix & suffix in `FormlyWrapperAddons`:

```patch
  <ng-template #matSuffix>
+   <ng-container *ngTemplateOutlet="to._matPrefix"></ng-container>
    <span *ngIf="to.addonRight" ...></span>
  </ng-template>
```

**Comment by Zdenalus** [comment]
It's working now. Thank you!
