### ISSUE TITLE
Forgotten console.log in json schema comverter

### ISSUE THREAD

**Issue by MarenkovIgor** [ngx-formly/ngx-formly#2777]
**Description**
console.log here https://github.com/ngx-formly/ngx-formly/blob/94919715d411f8ec733c7c34aa809e899286311d/src/core/json-schema/src/formly-json-schema.service.ts#L352 (last 5.x release)

**Minimal Reproduction**
Install @ngx-formly/core 5.10.15,start app, open console, convert json schema

![image](https://user-images.githubusercontent.com/13851068/112981661-b77c8100-9185-11eb-9dd8-ada39b2d73f4.png)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.16](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.16) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
