### ISSUE TITLE
ngxs form plugin with ngx-formly

### ISSUE THREAD

**Issue by kgathi2** [ngx-formly/ngx-formly#2778]
**Question**
I'd like to use ngx-formly with ngxs-form https://www.ngxs.io/plugins/form for state management of forms. 

Not sure how to go about that. ngxs needs us to define the formControlName for the field. How do I do that in ngx-formly

**Comment by aitboudad** [comment]
it should work out of the box as we use ReactiveFormsModule which they rely on it too, https://stackblitz.com/edit/ngxs-forms-plugin-simple-example-2jdojt?file=src/app/app.component.ts
