### ISSUE TITLE
Share FormGroup between multiple Formly-Forms 

### ISSUE THREAD

**Issue by freon27** [ngx-formly/ngx-formly#2779]
Hi, hopefully a relatively simple question... 

I'm working on integrating formly and mat-table for a bulk update view (so click to edit doesn't really match the requirements unfortunately). 

Currently we have a solution that uses a formly-form per cell (not ideal but so far the performance is just about good enough!). I was hoping that I could share a single FormGroup across all the formly-forms in a row. 

I tried this out but the controls get overwritten rather than added to. Is there a way to achieve this? Not sure if there's an option I've missed.

Otherwise I also have to have a FormGroup per cell which is pretty heavy.

Thanks in advance 🙂

**Comment by aitboudad** [comment]
Passing `form` input would do the job I think if not I may need a reproduction :pray:, to improve the performance part use https://material.angular.io/cdk/scrolling/overview
