### ISSUE TITLE
[Formly Error] The type "input" could not be found

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2780]
I got the error `[Formly Error] The type "input" could not be found`

```
const fields: FormlyFieldConfig[] = [
  {
    key: 'title',
    type: 'input',
    templateOptions: {
      label: 'Title',
      description: '...'
    }
  }
];
```

**Comment by aitboudad** [comment]
I may need a reproduction, make sure you've imported one of our themes or you've defined your own custom input.

**Comment by aitboudad** [comment]
feel free to reopen if you've got a reproduction
