### ISSUE TITLE
Validation messages not showing until control is touched

### ISSUE THREAD

**Issue by ngabello** [ngx-formly/ngx-formly#2782]
Having a bit of an issue here. I recently upgraded to Angular 11 using  "@ngx-formly/core": "5.10.14",
    "@ngx-formly/material": "5.10.14", prior to upgrading my error messages were displaying properly after hitting submit. However now they are not showing required until I touch the control itself. 
currently after submit() I see the form is invalid I run the following commands
    this.form.markAsTouched();
    this.form.updateValueAndValidity();

when I examine the controls in the debugger they are all marked as touched and the errors are populated with required but do not show the error until I select it.

any help is appreciated thanks

**Comment by ngabello** [comment]
Figured it out I added 'changeDetection: ChangeDetectionStrategy.OnPush' to all the formly components, upon removing everything is now working

**Comment by aitboudad** [comment]
it should work with `OnPush` too, we may need a reproduction example in order to see what was wrong, anyway feel free to reopen if you've got a reproduction.
