### ISSUE TITLE
How is it possible to change hideExpression of input dynamically?

### ISSUE THREAD

**Issue by emelamud** [ngx-formly/ngx-formly#2783]
I'm passing config downloaded from server to formly. In my form I have a complex visibility condition, it depends of emptiness of some form fields and values that are entered outside of the form.

The config of that field is something like the following

```
{
  "key": "bad_input",
  "type": "input",
  "hideExpression": "!model.key1 || !model.key2 || !${externalObject.property}",
  "templateOptions": {
    "label": "Label"
  }
}
```

I'm handling changes of `externalObject.property`, put it in `!model.key1 || !model.key2 || !${externalObject.property}` expression, find the description of this field and change `fields[index].hideExpression`. After that `hideExpression` is either `!model.key1 || !model.key2 || !true` or `!model.key1 || !model.key2 || !false`. Still that seem to have no effect. Field is not visible on both values.

I've created simple StackBlitz with similar problem. I'm trying to change `hideExpression` of input -- https://stackblitz.com/edit/ngx-formly-ui-material-8bxaru?file=src%2Fapp%2Fapp.component.ts
`hideExpression` changes on 'toogle visibility' click, while actual visibility of input does not. Input disappears after first click and stay hidden. 

Please note that I'm getting json from server, hence using function in hide expression is not an option in my case.

Formly version is 5.10.6 if that matters

**Comment by 10229428** [comment]
try this:
```
"expressionProperties": {
     "hide": () => !this.model.key1 || !this.model.key2 || !this.externalObject.property
}
```

**Comment by emelamud** [comment]
Thanks for your answer @10229428 ! Still using functions is not the best option here, cause I'm getting JSON from backend, there can be no functions. 

I've tried to rewrite my example and change `expressionProperties.hide` instead of changing `hideExpression`. Still result merely the same - https://stackblitz.com/edit/ngx-formly-ui-material-jnqvzs?file=src%2Fapp%2Fapp.component.ts

BTW, what is the difference between using `expressionProperties.hide` and using `hideExpression`?

**Comment by aitboudad** [comment]
you need to re-assign a new value for the fields in order to detect changes:
```ts
toogle() {
  ...
  this.fields[0] = { ...this.fields[0] };
  this.fields = [...this.fields];
}
```

if you handle the changes only on the initialization step then just make sure to not render `formly-formly` until you've done with the changes (check our doc example https://formly.dev/examples/other/json-powered)

**Comment by aitboudad** [comment]
> what is the difference between using `expressionProperties.hide` and using `hideExpression`?

better rely on `hideExpression`, `expressionProperties.hide` doesn't take into account the field validation.
