### ISSUE TITLE
Can't bind to 'formlyAttributes' since it isn't a known property of 'quill-editor'.

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#2785]
I'm trying to add quill to formly

```
@Component({
  selector: "formly-field-quill",
  template: `
    <quill-editor
      [formControl]="formControl"
      [formlyAttributes]="field"
      [modules]="to.modules"
    ></quill-editor>
  `
})
export class FormlyFieldQuill extends FieldType {
  formControl:  FormControl;
}
```

but I got the error:
`Can't bind to 'formlyAttributes' since it isn't a known property of 'quill-editor'.`

in app.module, I added `QuillModule.forRoot()` and `FormlyModule.forRoot({ types: [...] })`

**Comment by aitboudad** [comment]
just make sure that `FormlyModule` is imported either in the shared module or where `FormlyFieldQuill` is declared.

**Comment by lalalalaluk** [comment]
thank you @aitboudad , i added my component to the wrong module
