### ISSUE TITLE
Ahout `How to bind a variable to the model`

### ISSUE THREAD

**Issue by 10229428** [ngx-formly/ngx-formly#2788]
> 
> 
> There are several ways to achieve that:
> 
>     1. for a specific field the better option is to use `formControl.valueChanges`:
> 
> 
> ```ts
> {
>   key: 'firstName',
>   type: 'input',
>   hooks: {
>     onInit: (field) => {
>       return field.formControl.valueChanges.pipe(
>         tap(value => {
>           this.dataBus.value = value;
>         }),
>       );
>     },
>   },
> },
> ```
> 
>     1. use `modelChange` output:
> 
> 
> ```
> <formly-form (modelChange)="update($event)"></formly-form>
> ```
> 
> ```ts
> export class AppComponent {
>   update(model) {
>     this.dataBus.value = model.firstName;
>   }
> }
> ```
> 
>     1. subscribe to `form.valueChanges`:
> 
> 
> ```
> ngOnInit(): void {
>   this.from.valueChanges.subscribe(model => this.dataBus.value = model.firstName)
> }
> ```

_Originally posted by @aitboudad in https://github.com/ngx-formly/ngx-formly/issues/2784#issuecomment-812926572_

Thanks for your reply! All the three ways can achieve that, when the field value changes, the var `dataBus.value` changed sync. But, what I need is that, <strong>when I change the value of `dataBus.value`, I hope the field value can change</strong>. Is there any way to achieve this requirement? 
Thanks again!

**Comment by aitboudad** [comment]
To change field value use `formControl.setValue`:

```ts
onChange(dataBusValue) {
  this.form.get('firstName').setValue(dataBusValue);
}
```

`Note`: Please avoid creating a new issue for the same question, just reply in the previous issue instead.

**Comment by 10229428** [comment]
> 
> 
> To change field value use `formControl.setValue`:
> 
> ```ts
> onChange(dataBusValue) {
>   this.form.get('firstName').setValue(dataBusValue);
> }
> ```
> 
> `Note`: Please avoid creating a new issue for the same question, just reply in the previous issue instead.

I'm sorry for creating a new issue for the same question...

The method `onChange` in your answer, is it a custom method or an inner method for some interfaces, and how does it trigger?
By your way, I only can change the field value by calling the `onChange` method, but in my scene, the user only can change it by these code `this.dataBus.value = xxxx`. Because, the variable name, `this.dataBus.value `, is defined by users. So, when they call  `this.dataBus.value = xxxx` in their codes,  the field value shuld updated sync.

**Comment by aitboudad** [comment]
ok I see, you may create a setter of that property in order to get notified whenever the value changes:

```ts
let value = this.dataBus.value;
Object.defineProperty(this.dataBus, 'value', {
  get: () => value,
  set: (v) => {
    value = v;
    this.form.get('firstName').setValue(v);
  },
});
```

Another way is to use `formState`: https://formly.dev/examples/form-options/form-state with the combination of `expressionProperties`:

```ts
expressionProperties: {
  'model.firstName': 'formState.dataBus.value',
},
```

**Comment by 10229428** [comment]
> 
> 
> Another way is to use `formState`: https://formly.dev/examples/form-options/form-state with the combination of `expressionProperties`:
> 
> ```ts
> expressionProperties: {
>   'model.firstName': 'formState.dataBus.value',
> },
> ```

Thank you very much! The second way works ok! 
But, oninit, I have to set this `this.options.formState.dataBus = this.dataBus;`, otherwise, I will get the errors bellow :
```
ERROR TypeError: Cannot read property 'value' of undefined
    at Object.eval (eval at evalStringExpression (utils.ts:3), <anonymous>:3:26)
    at evalExpression (utils.ts:11)
    at Object.model.firstName (field-expression.ts:97)
    at FieldExpressionExtension.checkExpressions (field-expression.ts:125)
    at field-expression.ts:130
    at Array.forEach (<anonymous>)
    at FieldExpressionExtension.checkExpressions (field-expression.ts:130)
    at field-expression.ts:70
    at reduceFormUpdateValidityCalls (utils.ts:293)
    at Object.field.options.checkExpressions (field-expression.ts:70)
```
I hope this binding codes has no other side effects.

Thanks for your kind help again.
