### ISSUE TITLE
v5.10.15 fails to build when targeting ES5

### ISSUE THREAD

**Issue by lbsn** [ngx-formly/ngx-formly#2789]
**Description**
Version 5.10.15 of ngx-formly/core contains a testing package that causes Angular build to fail when targeting ES5:

```
Compiling @ngx-formly/core/testing : module as esm5
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected TestComponent to have an inner class declaration
```

Downgrading to version 5.10.14 solves the problem (no testing package anymore).

**Your Environment**

- Angular version: 9.1.12
- Formly version: 5.10.15

**Additional context**
I can see from the changelog that `@ngx-formly/core/testing` has been added on v6.0.0-next.1. That should probably be considered as a breaking change and removed from all 5.x.x. versions.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.16](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.16) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
