### ISSUE TITLE
Dinamically add FormGroup to FieldArrayType

### ISSUE THREAD

**Issue by Luca-diciannove** [ngx-formly/ngx-formly#2790]
Hi everyone! Thanks for your attention.
I use formly material and what i'm trying to achieve is to dinamically add a FormGroup to a FieldArrayType.
In particular i'd like to add a new FormGroup on the value change of a select-type field.

**Comment by aitboudad** [comment]
see https://formly.dev/examples/advanced/repeating-section-input
