### ISSUE TITLE
--project option for multi-project solutions 

### ISSUE THREAD

**Issue by Metrophobe** [ngx-formly/ngx-formly#2791]
Maybe i missed it but, how do you exactly select the project to which you wish to add formly in a multi-project folder? 

Angular Material supports a --project option to specify the project for installing material.  I assumed that this parameter pertained to the 'ng add' command ... but I was wrong.  
If this is missing (or i am in the wrong) is there a manual workaround to set it up ?  

Assuming you got two apps in a folder called "store" and "admin" If you try to add formly to "admin" you would write..... 

`ng add @ngx-formly/schematics --ui-theme=material --project=admin` 

Currently this gives  `Unknown option: '--project'`

Any pointers would be appreciated.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.17](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.17) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
