### ISSUE TITLE
Error: [Formly Error] The type "input" could not be found. Please make sure that is registered through the FormlyModule declaration

### ISSUE THREAD

**Issue by keertikasp** [ngx-formly/ngx-formly#2795]

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2780#issuecomment-811403012

**Comment by keertikasp** [comment]
import { FormlyIonicModule } from '@ngx-formly/ionic'; i have used this import.

**Comment by keertikasp** [comment]
Its working for bootstrap but its not working for the ionic

**Comment by aitboudad** [comment]
Can you give it a try now with the latest version: `v5.10.17`
