### ISSUE TITLE
Dynamic default values don't work when inserting into a FieldArray

### ISSUE THREAD

**Issue by cwgormanIBM** [ngx-formly/ngx-formly#2799]
**Description**
By "dynamic default values," I mean defaults that are set at runtime, not as part of the form config. (For example, an "Address" field getting its default value populated from the user's profile.) This issue might simply be because I'm not implementing this correctly.

For these dynamic default values, I'm using two approaches: 
 * for certain `type`s, in `ngOnInit` of the component calling `formControl.setValue` and then `options.updateInitialValue()`.
 * a formly extension, that, for fields with certain parameters in their `templateOptions`, adds a `field.hooks.afterViewInit` which calls `formControl.setValue` and `options.updateInitialValue()`.

Again, I'm not sure of its correctness, but this approach seems to be working fine. That is, until we go to change the order of insertion of our `FieldArrayType`. Appending to the end (eg, using `add()`) works fine, but inserting at the beginning (`add(0)`, or presumably anywhere else) does *not* work. My hunch is that formly is "re-using" the existing components, so the only one for whom these lifecycle events are being called (and therefore whose `formControl.setValue` gets called) is the last one in the array; but that one already has a value since it was "bumped down" by the insertion.

Any advice? Should I be handling defaults differently? Or is this actually a bug?

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: 10.2.4
- Formly version: 5.10.14

**Additional context**

**Comment by aitboudad** [comment]
Hi,

> By "dynamic default values," I mean defaults that are set at runtime, not as part of the form config.

instead of using `defaultValue` you can pass the model value to the `add` method:

```ts
add(0, defaultValue);
```

>  but inserting at the beginning (add(0), or presumably anywhere else) does not work.

I may need a reproduction example :pray:,


Thanks!

**Comment by matheo** [comment]
For the record, `FormArrays` doesn't fill unexisting items
I mean, it needs to have 5 items if you are about to patch an array of lenght 5.

**Comment by cwgormanIBM** [comment]
>For the record, FormArrays doesn't fill unexisting items
I mean, it needs to have 5 items if you are about to patch an array of lenght 5.

I don't believe that is related.

I'll try to make a reproduction on stackblitz and re-open as a new issue.
