### ISSUE TITLE
Select Multiple - selectAllOption doesn't update Form Validation for being dirty

### ISSUE THREAD

**Issue by devinci** [ngx-formly/ngx-formly#2800]
**Description**
Currently the "Select All" option on a multi-select doesn't update the form validation state to not be pristine, causing validation issues.

**Minimal Reproduction**
Choose the "Select All" option from the multi-select.  

https://stackblitz.com/edit/angular-vknu7m?file=src/app/app.component.ts

**Expected Results**
To mark the field dirty and validate the form the same way as selecting a specific option.

**Actual Results**
No change to validation state.

**Your Environment**

- Angular version: 10.1.5
- Formly version: 5.10.3

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.18](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.18) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by devinci** [comment]
Can confirm it's resolved in the version specified. 👍 Thank you.
