### ISSUE TITLE
*May Day* I'm using ngx-formly and appreciate it very well ... I'm trying to update an object observable by passing it to the model with Of rxjs operator...  I got the error of uninitialized object despite I get object in ngOnit() function

### ISSUE THREAD

**Issue by ADNtheJabber** [ngx-formly/ngx-formly#2801]
**Question**

A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by ADNtheJabber** [comment]
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-ldby3y?

**Comment by ADNtheJabber** [comment]
thanks !

**Comment by aitboudad** [comment]
The provided example work without issue https://ngx-formly-ui-bootstrap-ib4b6x.stackblitz.io
Feel free to reopen if you've got a reproduction example.

Thanks!
