### ISSUE TITLE
When using anyOf as a multi-select field, it does not populated the selected options correctly when you come back

### ISSUE THREAD

**Issue by anmoreno** [ngx-formly/ngx-formly#2802]
**Description**
I am using an anyOf to simulate a multi choice dropdown. Whenever you make multiple selections and return to the dropdown with the model populated with the selections they do not show as selected.
All the data is persisted but it does not show when it's rendered.

**Minimal Reproduction**
https://stackblitz.com/edit/formly-anyof-issue

**Your Environment**

- Angular version: 10.2.5
- Formly version: 5.10.17

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.18](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.18) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by anmoreno** [comment]
The fix worked! Thanks @aitboudad
