### ISSUE TITLE
Pagination issue with formly Repeat section

### ISSUE THREAD

**Issue by abhip5369** [ngx-formly/ngx-formly#2808]
**Description**
Pagination issue with formly Repeat section when page is changed, few fields go missing

**Minimal Reproduction**

https://stackblitz.com/edit/angular-ap3aic-jesdq9?file=src/app/repeat-section.type.ts

**Angular-v11 | Stackbliz**

- Angular version: { "full": "7.2.16", "major": "7", "minor": "2", "patch": "16" }
- Formly version: 
"@ngx-formly/core": "^5.10.8",
"@ngx-formly/material": "5.10.6",

**Additional context**
Paginator must appear only when No. of repeat sections > 3

**Comment by mohamedelshorbagy** [comment]
your issue is not `ngx-formly` bug, it's issue with in your `setPage` function for setting `startIndex` & `endIndex` you can check a solution for that in this `stackblitz`
https://stackblitz.com/edit/angular-ap3aic-cypgle
