### ISSUE TITLE
JSON-Schema forms - why fieldArray is defined as only getter property?

### ISSUE THREAD

**Issue by arturzx** [ngx-formly/ngx-formly#2809]
**Question**

Is there any specific reason for using only get() property for fieldArray defined by JSON-schema service?

[core/json-schema/src/formly-json-schema.service.ts line 228](https://github.com/ngx-formly/ngx-formly/blob/60bece9b9dd4e1719bb6cdf3e49d804453438fb3/src/core/json-schema/src/formly-json-schema.service.ts#L228)

This prevents modification fields in fieldArray after schema load. In code I have workaround for this, but I want to know it is not breaking something.

Best regards,
Artur

**Comment by kenisteward** [comment]
> **Question**
> 
> Is there any specific reason for using only get() property for fieldArray defined by JSON-schema service?
> 
> [core/json-schema/src/formly-json-schema.service.ts line 228](https://github.com/ngx-formly/ngx-formly/blob/60bece9b9dd4e1719bb6cdf3e49d804453438fb3/src/core/json-schema/src/formly-json-schema.service.ts#L228)
> 
> This prevents modification fields in fieldArray after schema load. In code I have workaround for this, but I want to know it is not breaking something.
> 
> Best regards,
> Artur

@arturzx it is made this way so validations an expressions are always dynamically calculated.

If you need to do manipulations, I would suggest these. Either:

1. Use the map function to add changes to the field config of the array.

2. Simply use the getter to copy and then change the underlying property on the field config after the fact.

I have done both with an internal library.

**Comment by aitboudad** [comment]
That was just a workaround until we allow passing a function to `fieldArray`.

Totally missed it, it should be part of `V6`.

**Comment by luizfbicalho** [comment]
I'm having a lot of errors in my code, is there any helper to get the fieldGroup from the fieldArray property? 
Or some code to replicate and use everywhere?

` error TS2339: Property 'fieldGroup' does not exist on type 'FormlyFieldConfig<FormlyFieldProps & { [additionalProperties: string]: any; }> | ((field: FormlyFieldConfig<FormlyFieldProps & { [additionalProperties: string]: any; }>) => FormlyFieldConfig<...>)'.`

**Comment by aitboudad** [comment]
@luizfbicalho please create a separate issue with a reproduction.

**Comment by luizfbicalho** [comment]
> @luizfbicalho please create a separate issue with a reproduction.

I  created two methods to get the correct information, I'll post them here to see if it's useful somewhere


```typescript
import { FormlyFieldConfig } from "@ngx-formly/core";

    export function isFormlyFieldConfig(fieldArray: FormlyFieldConfig | ((field: FormlyFieldConfig) => FormlyFieldConfig)): fieldArray is FormlyFieldConfig {
  return (fieldArray as FormlyFieldConfig).fieldGroup !== undefined;
}
  export function isFormlyFieldConfigFunction(fieldArray: FormlyFieldConfig | ((field: FormlyFieldConfig) => FormlyFieldConfig)): fieldArray is((field: FormlyFieldConfig) => FormlyFieldConfig) {
  return (typeof fieldArray === "function") && (fieldArray as ((field: FormlyFieldConfig) => FormlyFieldConfig)) !== undefined;
}

@Pipe({
  name: 'gridFieldGroup',
  pure: false
})
export class GridFieldGroupPipe implements PipeTransform {
  transform(value: FormlyFieldConfig): FormlyFieldConfig[] {
    if (isFormlyFieldConfig(value.fieldArray)) {
      return value.fieldArray.fieldGroup;
    }
    else {
      return value.fieldArray(value).fieldGroup;
    }
  }
}
```

then I used like this in my kendo grid component

```html
 <kendo-grid-column *ngFor="let f of field | gridFieldGroup ; let i = index"
                    [field]="f.key | gridKey"
                    [title]="f.templateOptions.label"
                    [width]="f.templateOptions.width">

```

I'm not sure that's the best way to use it.

**Comment by aitboudad** [comment]
> I'm not sure that's the best way to use it.

seems good to me.

**Comment by luizfbicalho** [comment]
> > I'm not sure that's the best way to use it.
> 
> seems good to me.

if you want you can add it to the library, glad to help
