### ISSUE TITLE
FieldArray  remove and add button not working as expected 

### ISSUE THREAD

**Issue by zubair-saif** [ngx-formly/ngx-formly#2810]
i am trying to add same repeat section as provided in formly  [example](https://formly.dev/examples/advanced/repeating-section) in my code but remove and add button not working as expected.

![image](https://user-images.githubusercontent.com/11749126/115765985-d6ef7e00-a3c0-11eb-9879-194c6e813750.png)

as above when i click on remove button it also remove add button as well like this

![image](https://user-images.githubusercontent.com/11749126/115766722-b96ee400-a3c1-11eb-8ace-3e161a274b03.png)

**Comment by mohamedelshorbagy** [comment]
Can you please try to provide a `stackblitz` with your example?

**Comment by zubair-saif** [comment]
hi thanks for replying me issue now fixed...
