### ISSUE TITLE
how i change text of dropdown based on selected radio button

### ISSUE THREAD

**Issue by zubair-saif** [ngx-formly/ngx-formly#2813]
how i change text of dropdown based on selected radio button
For example i select **non time series** radio button than i want to change text of dropdown **line** and **column** in case of **non time series** checkbox selected. when i select **time series radio button** than i want to get same text as shown in screenshot as in default option. Thanks in advance

![image](https://user-images.githubusercontent.com/11749126/115972806-0988aa80-a56a-11eb-9e6e-1728da8b886c.png)

e.g in case of non time series radio button

![image](https://user-images.githubusercontent.com/11749126/115973530-2378bc00-a56f-11eb-92ee-f89e1b025d2e.png)

**Comment by zubair-saif** [comment]
` fields: FormlyFieldConfig[] = [
   
    {
      key: 'seriestype',
      type: 'radio',
      templateOptions: {
        type: 'radio',
        label: 'Select Series',
        options: [{ value: 'Non Time Series', key: 'X keys' }, { value: 'Time Series', key: 'Group By' }],
        // change:(field,$event)=>{
        //   this.checkboxData()
        //   console.log($event.value)
        // }
      },
      
    },
    {
      key: "plotType",
      type: "select",

      templateOptions: {
        label: "Plot Type",
        multiple: false,
        required: true,
        options: [
          { label: 'Time Series Line', value: "timeseries" },
          { label: "Time Series Column", value: "timeseriescolumn" },
        ],
        
      },
      // expressionProperties: {
      //   template: "(model.seriestype=='Non Time Series'?'line':'column')"
      // }
    },
    {
      key: "multipleSeries",
      type: "select",
      templateOptions: {
        label: "Multiple Series",
        multiple: true,
        valueProp: "Id",
        labelProp: "Name",
        change: (field, $event) => {
          this.getPresentationData($event.value);
        },
      },
      hooks:{
        onInit:(field:FormlyFieldConfig)=>{
         this.getPresentationData(1);

        },
      }
    },
    {
      key: "xkeys",
      type: "select",
      templateOptions: {
        label: "group by",
        multiple: false,
        valueProp: "AttributeName",
        labelProp: "Label",
      },
      expressionProperties: {
        "templateOptions.label": "model.seriestype"
      },
    },

    {
      key: "ykeysrepeat",
      type: "repeat",
      fieldArray: {
        fieldGroupClassName: "display-flex",
        fieldGroup: [
          {
            className: "flex-1",
            key: "ykeys",
            type: "select",
            templateOptions: {
              label: "Y Keys (Values)",
              multiple: false,
              valueProp: "AttributeName",
              labelProp: "Label",
            },
          },
          {
            className: "flex-1",
            key: "aggregation",
            type: "select",
            templateOptions: {
              label: "Aggregation",
              multiple: false,
              options: [{}],
              valueProp: "Value",
              labelProp: "Value",
            },
          }
        ]
      },
    },

  ];`

**Comment by aitboudad** [comment]
see https://formly.dev/examples/other/cascaded-select
