### ISSUE TITLE
Hosted Documentation Bug

### ISSUE THREAD

**Issue by warrendugan** [ngx-formly/ngx-formly#2816]
**Description**
The documentation has a bug in the menu. Clicking on next in the versions dropdown should take me to the documentation for future enhancements. Actual result, error page is delivered.

**Additional context**
- Looks like the default branch was switched from master to main at some point and the hosting was updated to reflect the default branch.  

**Image for more context**
![image](https://user-images.githubusercontent.com/23459839/116127315-873cdb00-a67c-11eb-8e5f-1e1c66ce4cf5.png)

**Comment by aitboudad** [comment]
it should be fixed now.
Thank you!
