### ISSUE TITLE
I want disable or remove already selected option in next array arrayfield

### ISSUE THREAD

**Issue by zubair-saif** [ngx-formly/ngx-formly#2819]
i am working with fieldarray  repeat section where i have added dropdown list in it.now i want to remove selected option from dropdown when i click on add button of fieldarray and don't show previous selected option in newly added section

**Comment by zubair-saif** [comment]
@beeman @Tom-V @blowsie

**Comment by zubair-saif** [comment]
like below screenshot 

![image](https://user-images.githubusercontent.com/11749126/116273675-67e89f80-a79b-11eb-9658-202c0f5a0a57.png)

**Comment by zubair-saif** [comment]
@aitboudad

**Comment by aitboudad** [comment]
rely on `valueChanges` to get the selected options then apply `filter` the the select `options`, see https://formly.dev/examples/other/cascaded-select

**Comment by zubair-saif** [comment]
have you got this because i try it before but did't work

**Comment by aitboudad** [comment]
it should, could you replicate what you've done using `stackblitz` https://stackblitz.com/angular/ybodqdqqjmm

**Comment by blowsie** [comment]
don't @ people like that!
