### ISSUE TITLE
material select can't pass in aria-label

### ISSUE THREAD

**Issue by dahang** [ngx-formly/ngx-formly#2821]
[https://github.com/ngx-formly/ngx-formly/commit/b8f1834ad9b0fb74918974dc54254c7f4c09a355#r50145939](https://github.com/ngx-formly/ngx-formly/commit/b8f1834ad9b0fb74918974dc54254c7f4c09a355#r50145939)

[https://stackblitz.com/edit/angular-qa7mcp?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-qa7mcp?file=src/app/app.component.ts)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.19](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.19) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
