### ISSUE TITLE
How to access method of custom field type component on select of value in dropdown of other field

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2822]
I have been working for a requirement in which i have 2 fields as follows 
1. select (dropdwon)
2. searchtable (custom component)

I have created a method in searchtable component ts file, I need to access this on the selection of my other select field. I am calling onchange on change of select dropdown in expression properties.

**Stackblitz example here is as follows** [Click here](https://stackblitz.com/edit/angular-formly-datatable-iflhqu?file=app/app.component.ts)  

**table-type.component.ts**
       ` search() {
          console.log("---->search operation");
        }`

**app.component.ts**

 ` expressionProperties: {
            "templateOptions.change": `(field, $event)=> {
               console.log('-->call search funtion of table component here');
      } `

**Comment by chandelshashank** [comment]
@aitboudad  can you please help me out with this?

**Comment by aitboudad** [comment]
Assign it to `templateOptions`:

```ts
export class TableTypeComponent extends FieldArrayType {
  ...

  ngOnInit() {
    this.to.search = this.search.bind(this);
  }
}

```ts
expressionProperties: { "templateOptions.change":(field, $event)=> {
  field.templateOptions.search(...);
}
```

**Comment by chandelshashank** [comment]
@aitboudad  Thanks for looking into this, I agree to assign it to templateOptions and call it accordingly but how can I access the other field instead of using the field of onchange event I want to use the field of searchtable (custom component).

So in `expressionProperties: { "templateOptions.change":(field, $event)=> {
  field.templateOptions.search(...);
}`

instead of the field of select, I want to use the field of the serchtable how can I achieve this?

**Comment by aitboudad** [comment]
@chandelshashank the question is not clear, please elaborate :pray:

**Comment by chandelshashank** [comment]
Sorry for the inconvenience,  i have used   this.to.search = this.search.bind(this); in TableTypeComponent but i am not able to use this in app.component.ts in this component i am calling it on change of select (i.e other field) for reference the stackblitz : 
[click here](https://stackblitz.com/edit/angular-formly-datatable-iflhqu?file=app/app.component.ts)

In app.component.ts : 
       ` expressionProperties: {
            "templateOptions.change": `(field, $event)=> {
               //not able to call the search method of TableTypeComponent here
                console.log('-->call search funtion of table component here');
              }`
          }`

**Comment by aitboudad** [comment]
when passing a string to `expressionProperties`, the function declaration should not be used:

- With function:

```ts
expressionProperties: {
  "templateOptions.change":(field, $event)=> field.templateOptions.search(...);
}
```

- With string:

```ts
expressionProperties: {
  "templateOptions.change": "field.templateOptions.search"
}
```

**Comment by chandelshashank** [comment]
@aitboudad Thanks for response, I have tried using field.templateOptions.search using string way,  but here the field.templateOptions doesn't have a search method as this is the other field i.e select field whereas the search method  is of other field type, please find the below screenshot for reference 

![Capture](https://user-images.githubusercontent.com/12397854/117136173-a4348500-adc5-11eb-978c-d8c21f3e7f5d.PNG)

Can we access the search in this method by using anything other than the field?
