### ISSUE TITLE
Recursive schema with hideExpression: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by cmv13** [ngx-formly/ngx-formly#2823]
**Question**
I am trying to create a recursive schema using $ref combined with hideExpression with json-schema, but am getting a "Maximum call stack size exceeded" error. 

Stackblitz reproduction:
https://stackblitz.com/edit/ngx-formly-ui-material-m3sd3w?file=src/assets/json-schema/references.json

Clicking on the `+` sign will trigger the error. If the hideExpression is removed in the references.json file for matchers then the recursive schema works fine. 

I tried with both v5 and v6, getting the same error.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.19](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.19) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by cmv13** [comment]
@aitboudad thanks for the quick fix! Wondering when this would also be released in v6? There is a feature from v6 we want but we need this as well, just to know if I need to come up with a workaround. Thanks!

**Comment by cmv13** [comment]
@aitboudad thanks for looking into this! 

I have updated my stackblitz to now use the latest version 5.10.19: 
https://stackblitz.com/edit/ngx-formly-ui-material-txbrbn?file=src%2Fassets%2Fjson-schema%2Freferences.json

I am not getting the 'maximum call stack size error' anymore but the hideExpression is not working for the recursive 'matching' like it is for the 'check'. I would like for the 'matching' array to only be visible depending on the value of the enum. Any ideas?

Thanks

**Comment by aitboudad** [comment]
fixed by https://github.com/ngx-formly/ngx-formly/pull/2839

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.20](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.20) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
