### ISSUE TITLE
how can I use two UI in different module?

### ISSUE THREAD

**Issue by a2928897** [ngx-formly/ngx-formly#2824]
Hi,

I have two module A、B for different business situation,

I need use ngx-formly in A、B with different UI,
A with material
B with ngzorro

app.module import A & B modules 
A & B import ngx-formly for independent,
But when B import ngzorro, the A's UI will be change to ngzorro,
How can I do?

**Comment by aitboudad** [comment]
To have a separate UI for each module, just ensure to call `FormlyModule.forRoot` in the import declaration in both A & B module, that's how we've done it in our docs https://formly.dev/ui/bootstrap.

```ts
FormlyModule.forRoot(),
```
