### ISSUE TITLE
JSONSchema: bad oneOf selection with initial data

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#2826]
**Description**
With an optional object as sub property, the initial value of the JSONSchema oneOf is wrong.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-jsonschema-load-oneof?file=src%2Fassets%2Fjson-schema%2FoneOf.json

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.10.18

**Comment by aitboudad** [comment]
indirectly fixed by https://github.com/ngx-formly/ngx-formly/pull/2817 :smiley:, I'll push a release soon!

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.19](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.19) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by jma** [comment]
Great thank you.
