### ISSUE TITLE
The form does not reload correctly the property disabled when changing fields

### ISSUE THREAD

**Issue by fontsie** [ngx-formly/ngx-formly#2829]
Hello!

When I click on `Submit` I change the fields object but the form is not reloaded correctly.
Disabled fields remain disabled.

Demo:
https://stackblitz.com/edit/formly-example-tcl3mw

Some workaround?
Thanks!

**Comment by aitboudad** [comment]
The provided example use an old version of Formly, here is a working example https://stackblitz.com/edit/angular-eh3pb5 which use the latest version.

**Comment by fontsie** [comment]
Thanks for quikly reply.
I have tried to update Formly but the problem still remains.

Investigating I think it is related to `FormlyMaterialModule`

Demo:
https://stackblitz.com/edit/angular-1wah83

**Comment by fontsie** [comment]
@aitboudad is it possible to reopen this issue?

Thanks

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.20](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.20) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
