### ISSUE TITLE
Material chips autocomplete does not keep the dropdown open 

### ISSUE THREAD

**Issue by orlando1108** [ngx-formly/ngx-formly#2830]
**Description**
Material chip component with autocomplete behavior does not keep the dropdown open when clicking inside a zone between:
- input element
- mat-chip-list-wrapper element.

Event 'mousedown' put the value 'true' in '[aria-expanded]' attribute and the event 'mouseup' put the value 'false', while 'formly-wrapper-mat-form-field' component has the class 'cdk-focused' (given by FocusMonitor service) and 'mat-form-field' component has also the class 'mat-focused'

**Minimal Reproduction**
https://stackblitz.com/edit/ng-material-chips-formly-r4ndpr?file=src/app/formly-chips/formly-chips.component.ts

the zone corresponds to the space between the two rectangles with black borders.

**Your Environment**

    "@angular/animations": "^11.2.11",
    "@angular/cdk": "^11.2.11",
    "@angular/common": "^11.2.11",
    "@angular/compiler": "^11.2.11",
    "@angular/core": "^11.2.11",
    "@angular/forms": "^11.2.11",
    "@angular/material": "^11.2.11",
    "@angular/platform-browser": "^11.2.11",
    "@angular/platform-browser-dynamic": "^11.2.11",
    "@ngx-formly/core": "^5.10.18",
    "@ngx-formly/material": "^5.10.18",
    "core-js": "^3.6.5",
    "rxjs": "^6.6.7",
    "tslib": "^2.0.1",
    "zone.js": "^0.11.4"

**Comment by aitboudad** [comment]
you've missed adding the following `ViewChild`, please make sure to follow our autocomplete example (https://formly.dev/ui/material) in order to get the expected behavior:

```patch
export class AutocompleteTypeComponent extends FieldType implements OnInit, AfterViewInit {
+  @ViewChild(MatInput) formFieldControl: MatInput;
+  @ViewChild(MatAutocompleteTrigger) autocomplete: MatAutocompleteTrigger;
   ...
}
```
