### ISSUE TITLE
Multischema initializes required contents as optional

### ISSUE THREAD

**Issue by camden-penn** [ngx-formly/ngx-formly#2831]
**Description**

This bug was introduced in ngx-formly/core v 5.10.19. When a multischema contains items that are required, these items are initially rendered as optional. The multischema contents' true required status is only rendered once something in the multischema has been interacted with. This also affects overall form validity.

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formly-multischema-required-as-optional?file=app%2Fapp.component.ts

**Your Environment**

- Angular version: 10.2.5
- Formly version: 5.10.19

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.20](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.20) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
