### ISSUE TITLE
Bootstrap 5 Plans

### ISSUE THREAD

**Issue by internalsystemerror** [ngx-formly/ngx-formly#2832]
**Is your feature request related to a problem? Please describe.**
Bootstrap 5 has now been released and this library prevents its use.

**Describe the solution you'd like**
Bootstrap 5 to be supported.

**Describe alternatives you've considered**
I'm not convinced, but it may be possible to support both 4 and 5 in future minor release.

**Additional context**
I'm mainly interested in what the plans are as I assume there are/will be some. It will be some time yet before other libraries such as `@ng-bootstrap/ng-bootstrap` also support Bootstrap 5.

**Comment by aitboudad** [comment]
it there are no major changes that prevent us to support both, why not!

**Comment by internalsystemerror** [comment]
Do you propose having 2 UI libraries? Since I think there are a substantial amount of changes that would not be backwards compatible.

see: https://getbootstrap.com/docs/5.0/migration/#forms

**Comment by aitboudad** [comment]
I see then we should drop `v4` support :thinking:, it should be done in `v6`

**Comment by internalsystemerror** [comment]
the v6 branch `main` is using npm 7 which I'm not on yet, but I can help with this if needed

**Comment by aitboudad** [comment]
sure, PR welcomed!

**Comment by asadsahi** [comment]
@aitboudad v6 seem to be tied to bootstrap 4. Isn't there any work done for bootstrap 5 yet? Can't see anything in changelog either.

I would love formly to be supportive for bootstrap 5 as soon as possible. Can you please give a high level of steps that we can take to support you doing the upgrade?

Thanks

**Comment by internalsystemerror** [comment]
Already on with it, expect a PR soon. I'll need help testing though.

**Comment by asadsahi** [comment]
Excellent @internalsystemerror, changes look good to me so far.
