### ISSUE TITLE
include link within the description field

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2834]
I have a field where in its description, I need to put a link, but today what I put in the description field, it will be rendered as text, I need it to render as html.

![Captura de Tela_selecionar área_20210507094926](https://user-images.githubusercontent.com/11314585/117451924-89732500-af19-11eb-9a44-932da80dd06d.png)

**Comment by GlauberF** [comment]
My current solution was to create a new field (descriptionHtml) and create addons.

If you have a better approach, I’d like to know.

**Comment by Et3rnal** [comment]
In my case, I have simple HTML (newlines) so I used a replace() to have `\n` instead of HTML and set the style to be `white-space: pre-wrap;`

Having an htmlDescription would be nice.

**Comment by GlauberF** [comment]
yes, i ended up doing it myself.
