### ISSUE TITLE
Label-Only Type or Title Type

### ISSUE THREAD

**Issue by Galaxydragonx0** [ngx-formly/ngx-formly#2835]
My Gs I need help with how to create an Label-Only type or Title type so I can get text without an input field

**Comment by nirmpate** [comment]
https://stackblitz.com/edit/ngx-formly-custom-template-97j8lp?file=app%2Fapp.component.ts

Check out this example.  Is this what you are looking for?

**Comment by Galaxydragonx0** [comment]
Yes exactly this. Thanks very much 😌
