### ISSUE TITLE
How to set Value for formly controls dynamically based on value of other fields?

### ISSUE THREAD

**Issue by sonammarda** [ngx-formly/ngx-formly#2837]
**How to set Value for formly controls dynamically based on value of other fields?**

I am using formly to dynamically create a form from API response. Below is a part of API response that I receive for setting value of checkbox(fieldName : CNNRCRDeclInd) to true when user enters value in other input control(fieldName: CNNRCRDeclRsn1).

"71": {
                        "conditions": [
                            {
                                "field": "CNNRCRDeclRsn1",
                                "conditionType": "When",
                                "conditionOperator": "NotEquals",
                                "conditionValue": ""
                            }
                        ],
                        "events": [
                            {
                                "field": "CNNRCRDeclInd",
                                "eventType": "UpdateFieldValue",
                                "value": true
                            }
                        ]
         }

I tried to do this with expression properties but not able to update value of control with it. How can I do this with formly?

**Comment by aitboudad** [comment]
The request is not clear, please elaborate!
