### ISSUE TITLE
Formly Material Checkbox Cannot read property '_inputElement' of undefined at FormlyFieldCheckboxComponent.ngAfterViewInit

### ISSUE THREAD

**Issue by hkadim** [ngx-formly/ngx-formly#2838]
**Description**
Erro on **HIDDEN** checkbox using hideExpression()
Cannot read property '_inputElement' of undefined at FormlyFieldCheckboxComponent.ngAfterViewInit (ngx-formly-material-checkbox.js:58)

Repro in ngAfterViewInit
Angular version: 11.2.12
Formly version: 5.10.19 and 6.0.0-next.1
ERROR TypeError: Cannot read property '_inputElement' of undefined
at FormlyFieldCheckboxComponent.ngAfterViewInit (ngx-formly-material-checkbox.js:58)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.20](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.20) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
