### ISSUE TITLE
Focus is trapped when multiple radio buttons present on a screen - iOS VoiceOver only

### ISSUE THREAD

**Issue by lallsonu** [ngx-formly/ngx-formly#2840]
**Description**
Focus is trapped when multiple radio buttons present on a screen - iOS VoiceOver only

**Minimal Reproduction**
When the user is on a Formly page with multiple radio buttons with a iOS VoiceOver, the focus is trapped in different areas, sometimes between some sections (‘two’ and four’) or some radio buttons (first and second). The same behaviour is not observed with other Screen Readers or when the page has 2 radio buttons only.
 

**Your Environment**

- iOS 14.1 VoiceOver
- Safari v.14
- "@angular/core": "11.0.9",
- "@ngx-formly/core": "5.10.16",

**Comment by aitboudad** [comment]
which UI?

**Comment by lallsonu** [comment]
Angular Ui

**Comment by aitboudad** [comment]
Do you mean material https://formly.dev/ui/material ?

**Comment by lallsonu** [comment]
Yes , that’s right

**Comment by aitboudad** [comment]
I did a check with material UI https://formly.dev/ui/material but it seems working as expected.
The issue occurs with Bootstrap UI https://formly.dev/ui/bootstrap and it can be reproduced without enabling the VoiceOver only.

Please let me know if that's what you've experienced on your side or there is something else I didn't notice.

**Comment by aitboudad** [comment]
feel free to reopen once you've got some steps to follow for reproduction.
