### ISSUE TITLE
Type 'AbstractControl' is not assignable to type 'FormControl'

### ISSUE THREAD

**Issue by muuvmuuv** [ngx-formly/ngx-formly#2842]
**Description**

Using strict template checking prints `Type 'AbstractControl' is not assignable to type 'FormControl'.ngtsc(2322)`, because the FormControlDirective requires a FormControl not AbstractControl. Is there a reason why AbstractControl was used as the control type? I think it would change a lot because we always only push FormControls to an input.

**Minimal Reproduction**

```html
<input matInput [formControl]="formControl" />
```

```json
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
```

**Your Environment**

- Angular version: latest
- Formly version: latest

**Additional context**

**Comment by scatcher** [comment]
I ran into a similar problem but if you add `public formControl: FormControl;` to your component definition it resolves it.

**Comment by muuvmuuv** [comment]
Thanks, will use that as a workaround for now.

**Comment by aitboudad** [comment]
> Thanks, will use that as a workaround for now.

That's actualy the solution and not a workaround because the `formControl` property can be either an instance of `FormControl`, `FormGroup` or `FormArray`.

**Comment by Allcharles** [comment]
@aitboudad This solution may need an update in version 6 as you used a getter instead. My current workaround is to add the following to my code (although there may be a much cleaner solution):

Option A:

```typescript
public get control() {
  return this.formControl as FormControl;
}
```

Option B:

```typescript
  public asFormControl = (formControl: AbstractControl): FormControl =>
    formControl as FormControl;
```

**Comment by aitboudad** [comment]
@Allcharles here is my solution which will be available in `V6`:

  ```patch
  - import { FieldType } from '@ngx-formly/core';
  + import { FieldType, FieldTypeConfig } from '@ngx-formly/core';
  @Component({
    template: `<input [formControl]="formControl" />`,
  })
  - export class CustomFieldType extends FieldType {}
  + export class CustomFieldType extends FieldType<FieldTypeConfig> {}
  ```

In addition `FieldTypeConfig` which expect `formControl` property to be instance of `FormControl`, you may use:
- FieldGroupTypeConfig: expect `formControl` property to be instance of `FormGroup`.
- FieldArrayTypeConfig: expect `formControl` property to be instance of `FormArray`.

please let me know your opinion :pray:!

**Comment by Eisie96** [comment]
That's perfect. Thanks a lot! Is there any plan when the v6 is released?

**Comment by aitboudad** [comment]
>  Is there any plan when the v6 with this change will be released?

You can give it a try with next release https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.7

**Comment by geno-github** [comment]
Version 6 is working great with this change!  Thank you!

Version 6 seems to be pretty bullet proof all-around so far for me.  Thanks for getting around to address the strict type issues, they can be difficult for non-experts.

Any way this can be flagged in the docs?  I got lucky to find this thread.

**Comment by tobieeniafe** [comment]
@aitboudad Hi I'm using version `5.10.33` and none of the solutions here work. Any workaround asides making `strictTemplates: false`?

**Comment by tobieeniafe** [comment]
> @tobieeniafe Try to pass `any` to your custom type:
> 
> ```ts
> export class CustomFieldType extends FieldType<any> {}
> ```
> 
> I may consider adding `FieldTypeConfig` feature in `v5` as well.

Thanks for this. Still threw the same error tho. Guess I'd just wait for `v6` and leave `strictTemplates` as `false` till then.

**Comment by aitboudad** [comment]
`Note`:  `strictTemplates` support had been add to `v5` branch as well, so in case you like to give a try make sure to update Formly to the latest version: [v5.11.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.11.1) release, for usage check https://github.com/ngx-formly/ngx-formly/issues/2842#issuecomment-1016476706

**Comment by eng-dibo** [comment]
> @Allcharles here is my solution:
> 
> ```diff
> - import { FieldType } from '@ngx-formly/core';
> + import { FieldType, FieldTypeConfig } from '@ngx-formly/core';
> @Component({
>   template: `<input [formControl]="formControl" />`,
> })
> - export class CustomFieldType extends FieldType {}
> + export class CustomFieldType extends FieldType<FieldTypeConfig> {}
> ```
> 
> In addition `FieldTypeConfig` which expect `formControl` property to be instance of `FormControl`, you may use:
> 
> * FieldGroupTypeConfig: expect `formControl` property to be instance of `FormGroup`.
> * FieldArrayTypeConfig: expect `formControl` property to be instance of `FormArray`.
> 
> please let me know your opinion 🙏!



this causes an error
```
@Component({
 selector: 'test',
 template: `  
   <input 
     [formControl]="formControl"  //<---error: Type 'FormArray<any>' is missing the following properties ....
     [formlyAttributes]="field" 
   />`  
})
export class MyCustomType extends FieldType<FieldArrayTypeConfig> {}
```
error:
```
Type 'FormArray<any>' is missing the following properties from type 'FormControl<any>': defaultValue, registerOnChange, registerOnDisabledChangengtsc(2739)
```

**Comment by aitboudad** [comment]
> [formControl]="formControl"  //<---error: Type 'FormArray<any>' is missing the following properties ....

That's an expected behavior, input expect a `FormControl` instance

> also this doesn't work `<input [formControl]="formControl.at(0)" ...>`

Could you please create a separate issue with provide a reproduction. Normally it should work if `formControl.at(0)` is a `FormControl` instance else you should use `formControl.at(0).get('firstname')` for example.

**Comment by KakashiOfAnbu** [comment]
In Angular 15 / Formly 6.0.0 I implemented the first example, but the models don't update. the only ways I can make it update is to do it manually using valueChanges.

**Comment by atgillette** [comment]
> In Angular 15 / Formly 6.0.0 I implemented the first example, but the models don't update when the values of one or both inputs change. the only ways I can make it update is to do it manually using valueChanges.

I'm experiencing the same thing when using `formControl.get('xxxxx')`

**Comment by ermarkar** [comment]
I have migrated to angular16 and I am using 

```
"@ngx-formly/core": "6.1.7",
  "@ngx-formly/material": "6.1.7",
```

my code 

```
import { FieldTypeConfig, FieldType } from '@ngx-formly/core';
export class FormlyChipsComponent extends FieldType<FieldTypeConfig> implements OnInit, OnDestroy, AfterViewInit {
```


```
ngOnInit(): void {
    super.ngOnInit();

    this.filter = this.itemControl.valueChanges.pipe(
      takeUntil(this.onDestroy$),
      startWith(null),
      map((item: any | null) => item ? this._filter(item) : this._filter(""))
    );
  }
```


and I am facing

```
Property 'ngOnInit' does not exist on type 'FieldType<FieldTypeConfig<FormlyFieldProps & { [additionalProperties: string]: any; }>>'
```
same is for ngAfterViewInit

any solution
