### ISSUE TITLE
Focus not working correctly in Material

### ISSUE THREAD

**Issue by craigsh** [ngx-formly/ngx-formly#2847]
**Description**
I set focus: true on a field in my form. When the form is shown focus goes to the control but is then immediately lost.

**Minimal Reproduction**

https://github.com/craigsh/ngx-formly-focus-test

**Your Environment**

- Angular version: 11.2.0
- Formly version: 5.0.0

**Additional context**

Haven't been able to reproduce in a StackBlitz but reproduced in my repo above.

**Comment by craigsh** [comment]
Interestingly, hacking ngx-formly-core.js to put a setTimeout around the focus call solves the issue:

`    toggleFocus(value) {
        /** @type {?} */
        const element = this.fieldAttrElements ? this.fieldAttrElements[0] : null;
        if (!element || !element.nativeElement.focus) {
            return;
        }
        /** @type {?} */
        const isFocused = !!this.document.activeElement
            && this.fieldAttrElements
                .some((/**
             * @param {?} __0
             * @return {?}
             */
            ({ nativeElement }) => this.document.activeElement === nativeElement || nativeElement.contains(this.document.activeElement)));
        if (value && !isFocused) {
			setTimeout(() => {
				element.nativeElement.focus();
			});
        }
        else if (!value && isFocused) {
            element.nativeElement.blur();
        }
    }
`

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.20](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.20) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by craigsh** [comment]
Great, thanks for the quick action on this - much appreciated, and a fantastic library!
