### ISSUE TITLE
The immutable extra option breaks Set and Map objects defined in templateOptions 

### ISSUE THREAD

**Issue by skrtheboss** [ngx-formly/ngx-formly#2848]
**Description**

When passing a Set or a Map in the templateOptions, with immutable extra option set to true, then the Set/Map is no longer usable.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-ph6845?file=src%2Fapp%2Fapp.component.html

**Your Environment**

- Angular version: 11.2.5
- Formly version: 5.10.19

**Additional context**

Maybe a check should be added to the [clone](https://github.com/ngx-formly/ngx-formly/blob/60bece9b9dd4e1719bb6cdf3e49d804453438fb3/src/core/src/lib/utils.ts#L154-L198) function.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.20](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.20) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
