### ISSUE TITLE
Notification for changed Field(values) / detect Add in FormArray components

### ISSUE THREAD

**Issue by StefanKoenigMUC** [ngx-formly/ngx-formly#2849]
Hi all,

For few months I'm using Formly in a quite dynamic environment and today an issue came up, which was not solvable very nicely so far.

My first problem is about notifications from changed fields, so basically if Field below FormConfig A gets changed, I'm looking for a notification/event "FormConfig A has changed to value asdf".

At the moment I'm iterating over all FormFields and add an observer manually, like this:

```
  protected addFieldHandler(fieldConfig: FormlyFieldConfig) {
    fieldConfig.formControl.valueChanges.subscribe(obj => {
      console.log('FieldConfig: ' + fieldConfig.key + ' has changed value: ' + obj);
    });
  }
```

is there any better option available?

Second problem, I'm having dynamic grids within my form using FormArrays (analogous to https://formly.dev/examples/advanced/grid-integration).

So far it works fine, but if I'm adding new Rows:

```
 onAddRowClicked() {
    this.add();
    this.gridApi.setRowData(this.model);
  }
```

there is obviously no observer, which notifies me about changes in those lines. But I didn't find a solution, how to get notified about added FormArray elements in there - is there an easy solution available for that? 

Thanks in advance for your help,

best,
Stefan

**Comment by nirmpate** [comment]
How about adding your addFieldHandler function to each fields onInit hook?

https://stackblitz.com/edit/angular-xb9agn-j4rbt6?file=src%2Fapp%2Fapp.component.ts

Here is a quick example.

**Comment by StefanKoenigMUC** [comment]
thx, i'll give it a try

**Comment by aitboudad** [comment]
Done in `v6`, through `options.fieldChanges` which emit the desired event
