### ISSUE TITLE
Material select type should support readonly

### ISSUE THREAD

**Issue by guuurris** [ngx-formly/ngx-formly#2850]
Most `formly types` supports 'templateOptions.readonly' that can be used to show form data in a readonly state. 
This is not supported for the  **select type** which is frustrating as it forces code to either accept that data can be missing on re-submit or by systematically remove select-options not selected.

**Describe the solution you'd like**
That form type select should listen for **templateOptions.readonly** and when it is set to **true** it should only display currently selected and no longer be possible to expand options that normally is used for selection.

**Describe alternatives you've considered**
I have no alternative solutions. I am currently using the workarounds described above to make my GUI functional

**Additional context**
URL to code for select type: https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/material/select/src/select.type.ts

**Comment by aitboudad** [comment]
`select` tag doesn't support `readonly` properly, you can use `disabled` instead of `readonly`.
