### ISSUE TITLE
add helper function to get the field by key

### ISSUE THREAD

**Issue by aitboudad** [ngx-formly/ngx-formly#2854]
```patch
- const radioField = field.fieldGroup.find(f => f.key === 'firstname');
+ const radioField = field.get('firstname');
```

**Comment by nirmpate** [comment]
Where would this method go in the code base?  We have a helper function to recursively find fields within a fieldGroup in our codebase.  I can port it over to here but I'm facing some issues.  

1.) Will the FormlyFieldConfig need a new property "get"?

 `get: (key: string | number | string[]) => FormlyFieldConfig`
 
 2.) Would this get function be defined inside the formly-group..ts file under templates?  I have been trying to add it there but in the unit test it's never defined.  Looking into it more but maybe this method needs to get binded another way?
 https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/templates/formly.group.ts

**Comment by kenisteward** [comment]
> Where would this method go in the code base?  We have a helper function to recursively find fields within a fieldGroup in our codebase.  I can port it over to here but I'm facing some issues.  
> 
> 1.) Will the FormlyFieldConfig need a new property "get"?
> 
>  `get: (key: string | number | string[]) => FormlyFieldConfig`
>  
>  2.) Would this get function be defined inside the formly-group..ts file under templates?  I have been trying to add it there but in the unit test it's never defined.  Looking into it more but maybe this method needs to get binded another way?
>  https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/templates/formly.group.ts

It should go in the field config TS file. Based on what @aitboudad put for the new API we should pass a key name to the field config get function and internally the field should know if it needs to use the field group or field array to get the corresponding let's config

**Comment by aitboudad** [comment]
I'm open to any better solution, the assignment can be done here [CoreExtension](https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/extensions/core/core.ts#L24).

Also, I see the need of providing a way to find the field from the root (parent fields) :thinking:, any suggestions?

**Comment by kenisteward** [comment]
@aitboudad when I get back from vacation I'll send you a sample of what we
have to do it.

**Comment by nirmpate** [comment]
https://github.com/ngx-formly/ngx-formly/pull/2864

I made an attempt at a PR.  Please feel free to review and provide feedback.

**Comment by aitboudad** [comment]
close in favor of #3040
