### ISSUE TITLE
v6.0.0-next.1 adds a formly-field and a formly-group wrapping the original fields

### ISSUE THREAD

**Issue by aleixsuau** [ngx-formly/ngx-formly#2859]
**Description**
v6.0.0-next.1 adds a formly-field and formly-group wrapping the original fields:
<img width="541" alt="Captura de pantalla 2021-05-24 a las 17 47 32" src="https://user-images.githubusercontent.com/25689432/119373407-ad27c080-bcb8-11eb-95b3-0d404e38bb16.png">

In v5.10.19:
<img width="524" alt="Captura de pantalla 2021-05-24 a las 17 55 19" src="https://user-images.githubusercontent.com/25689432/119373898-3b9c4200-bcb9-11eb-9bfd-1c48077c419c.png">

**Minimal Reproduction**
I haven't been able to load v6.0.0-next.1 in Stackblitz: `preview-b0a8f458b6a7269649beb.js:1 ERROR Error: No component factory found for FormlyGroup. Did you add it to @NgModule.entryComponents?`. [Link](https://stackblitz.com/edit/ngx-formly-ui-material-fjs6v3?file=src/app/app.component.ts)

**Your Environment**

- Angular version: 12.0.1
- Formly version: v6.0.0-next.1

**Additional context**
--

Thanks!

**Comment by aitboudad** [comment]
That's an expected feature that allows managing the root field inside field-group type, need to update upgrade

**Comment by hrmcdonald** [comment]
@aitboudad is there a way to define classes to apply to this root field and group? This change definitely mucks up some layout situations.

**Comment by kenisteward** [comment]
@hrmcdonald do you mean a class just for the root field and group?

1 possible solution on hand could be to query for all form groups and just take the first one as it will always be the top.

Otherwise I believe you should be able to use className on the field config

**Comment by hrmcdonald** [comment]
> @hrmcdonald do you mean a class just for the root field and group?
> 
> 1 possible solution on hand could be to query for all form groups and just take the first one as it will always be the top.

It can be mitigated pretty easily in our case (bootstrap grid based layout system) with css alone, but it's harder to recommend copying that everywhere where people need it when this just worked out of the box before. For now I will probably just bake a class to handle this into our (internal) library and document the need to add the class when layout options are needed.

Example:
```scss
// formly override
form.formly-grid-form > formly-form > formly-field {
  width: 100%;

  & > formly-group {
    // .row
    display: flex;
    flex-wrap: wrap;
    margin-right: -12px;
    margin-left: -12px;
  }
}
```


```html
<form [formGroup]="form" class="col-12 formly-grid-form">
    <formly-form [form]="form" [fields]="fields" [model]="model"></formly-form>
</form>
```

```typescript
fields = [
    {
      key: 'example',
      type: 'input',
      className: 'col-12 col-md-6',
      templateOptions: {
        label: 'Example',
        required: true,
      },
    }
    // ...
];
```

**Comment by hrmcdonald** [comment]
Well never mind, I found how to do what I was looking for with this example: [https://formly.dev/examples/bootstrap-specific/advanced-layout](https://formly.dev/examples/bootstrap-specific/advanced-layout)

**Comment by kenisteward** [comment]
@hrmcdonald closing this ass you found what you needed and thank you for posting your answer!
