### ISSUE TITLE
Some multischemas initialize required contents as optional

### ISSUE THREAD

**Issue by camden-penn** [ngx-formly/ngx-formly#2860]
**Description**
In 5.10.20, a fix for issue #2831 was published. However, it only seems to take effect if the property that uses a multischema pattern is named `multischema`. I read over the associated commit, but am honestly at a loss as to how this behavior came about.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-multischema-required-as-optional-2

**Your Environment**
- Angular version: 10.2.5
- Formly version: 5.10.20

**Comment by aitboudad** [comment]
`a_multischema_by_any_other_name` is not required so its required properties will be mandatory only when   the value is an object (that's part of JSON-SCHEMA spec also you may check the original issue https://github.com/ngx-formly/ngx-formly/issues/2752#issue-834019827)

So the solution is to set `a_multischema_by_any_other_name` as required or set object as default value.
