### ISSUE TITLE
Jsonschema array tuples can lead to submittable forms that don't meet the schema

### ISSUE THREAD

**Issue by camden-penn** [ngx-formly/ngx-formly#2862]
**Description**
The Formly `array` component doesn't have a way to distinguish between list-validation arrays and tuple-validation arrays. This can cause problems because tuple-validation means the position of elements matters. As the current implementation seems to assume list-validation, always allowing users to delete items from the middle of an array, it is possible for a user to arrive at a form that believes itself valid without actually meeting the schema.

**Minimal Reproduction**
https://stackblitz.com/edit/formly-jsonschema-tuple-shenanigans?file=src%2Fassets%2Fjson-schema%2Ftuple.json

**Your Environment**
- Angular version: 10.2.5
- Formly version: 5.10.20

**Additional context**
This minimal example was based on the second negative example under [json-schema.org's explanation of tuple validation](https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation).

**Comment by aitboudad** [comment]
We didn't add the `type` validator yet, postponed it to `V6`.

Related issues:
- https://github.com/ngx-formly/ngx-formly/issues/2750
- https://github.com/ngx-formly/ngx-formly/issues/2360

**Comment by camden-penn** [comment]
If the array component knew whether it was working with a list or a tuple, couldn't it simply not let the user delete from the middle of the tuple? As far as I can tell, that would prevent the problem from happening in the first place.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [5.10.23](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.23) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
