### ISSUE TITLE
Number type with multipleOf 0.01 errors on certain values

### ISSUE THREAD

**Issue by anmoreno** [ngx-formly/ngx-formly#2863]
**Description**
When using multipleOf of 0.01 in a number JSON Schema type it makes the field invalid whenever certain values are hit (0.07, 0.14, 0.28, 0.29 are some examples of this)

**Minimal Reproduction**
https://stackblitz.com/edit/formly-multipleof-issue

**Your Environment**

- Angular version: 10.1.0
- Formly version: 5.10.1

**Comment by camden-penn** [comment]
This seems like typical floating-point error at its root.
A common tactic to avoid this sort of thing when dealing with money, for example, is to store an integer value in cents in the backend and display the amount in dollars in the frontend. Maybe putting together a component along those lines would fit your use case?

**Comment by anmoreno** [comment]
@aitboudad when is the next planned npm package version push that will get this update?

**Comment by aitboudad** [comment]
@anmoreno done https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.21

**Comment by aitboudad** [comment]
> A common tactic to avoid this sort of thing when dealing with money, for example, is to store an integer value in cents in the backend and display the amount in dollars in the frontend.

:+1:
