### ISSUE TITLE
Add support to widget in json-schema properties with $ref 

### ISSUE THREAD

**Issue by enricooliva** [ngx-formly/ngx-formly#2865]
I changed the example json-schema reference adding the property `widget`
in order to add a custom wrapper:

`
 "properties": {
      "billing_address": {
        "title": "Billing address",      
        "$ref": "#/definitions/address", 
        "widget": {
            "formlyConfig": {
                "wrappers": ["riquadro"],
                "templateOptions": {
                    "title": "Billing address"
                }
            }
        }      
      },
....
`

The property `widget` is deleted by the resolveDefinition function in ngx-formly-core-json-schema.js
Adding the `widget `to the list in line 566 seem to work  ['title', 'description', 'default', 'widget']

https://stackblitz.com/edit/angular-og72iy?file=src/app/object.type.ts

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.21](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.21) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
