### ISSUE TITLE
Optional objects with required contents stop being optional when contents' values change

### ISSUE THREAD

**Issue by camden-penn** [ngx-formly/ngx-formly#2866]
**Description**

Issue #2860 was actually exhibiting this issue. Since the symptom was so similar to issue #2831, I misinterpreted what I was seeing. If an optional object or multischema contains entries that it marks required, these entries will correctly render as optional. However, when interacted with, they become required and stay that way.

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formly-multischema-optional-as-required?file=app%2Fapp.component.ts

**Your Environment**

- Angular version: 10.2.5
- Formly version: 5.10.20

**Comment by aitboudad** [comment]
> This multischema is optional, but its contents are required.

that's a bug

> Optional object

this present a little confusion, once an item is updated under that object the model becomes:

```
{ field: "" }
```

that need additional info to remove the entire object when an item is empty :thinking:

**Comment by aitboudad** [comment]
close in favor #2894
