### ISSUE TITLE
Fix for re-render in Material causes regression

### ISSUE THREAD

**Issue by craigsh** [ngx-formly/ngx-formly#2868]
The fix for #2847 seems to have caused a regression.

I get this in my application:

Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'ng-untouched': 'true'. Current value: 'false'.. Find more at https://angular.io/errors/NG0100
    at throwErrorIfNoChangesMode (:4300/vendor.js:29728)
    at bindingUpdated (:4300/vendor.js:35871)
    at checkStylingProperty (:4300/vendor.js:39703)
    at Module.ɵɵclassProp (:4300/vendor.js:39611)
    at NgControlStatusGroup_HostBindings (:4300/vendor.js:247578)
    at processHostBindingOpCodes (:4300/vendor.js:32171)
    at refreshView (:4300/vendor.js:32449)
    at refreshComponent (:4300/vendor.js:33569)
    at refreshChildComponents (:4300/vendor.js:32200)
    at refreshView (:4300/vendor.js:32453)

but this doesn't happen in 5.10.19.

It's only happening in one scenario in my application, so I've not been able to build a reproducer.

**Comment by aitboudad** [comment]
Could you please push a reproduction example to your repo if possible https://github.com/craigsh/ngx-formly-focus-test

**Comment by craigsh** [comment]
Hi

I've now updated the repro with a simple reproducer. Basically, click the Show the tabs button and the error will appear in the console.

Thanks,
Craig

**Comment by aitboudad** [comment]
Not related to Formly, its either Angular or Material issue:

# app.component.html
```patch
   <mat-tab label="Details">
-    <app-details></app-details>
+    <input #inputELM [formControl]="formControl" type="text">
   </mat-tab>
```

# app.component.ts
```patch
 export class AppComponent {
+  @ViewChild('inputELM', { static: false }) input: any;
+  formControl = new FormControl();
   
   ...
   onShow() {
+    setTimeout(() => this.input.nativeElement.focus(), 500);
     ...
   }
 }
```

**Comment by craigsh** [comment]
OK, thanks for your work on this.
