### ISSUE TITLE
Can we create JSON schema to build a form on basis of plain JSON?

### ISSUE THREAD

**Issue by chandelshashank** [ngx-formly/ngx-formly#2877]
We have a requirement in which we are planning to build a form according to the JSON received and convert it to JSON schema which is supported by formlyJsonschema, is there any way of achieving this? 

Eg JSON:

`{`
  `"isSignInRequired": true,`
  `"isEmployee": false,`
  `"noOfEmployees": {`
    `"minValue": 3,`
    `"maxValue": 50`
  `}`
`}`

**Requirement:**  If the value is a boolean convert to a type of toggle and if there is an integer or string value convert to a type of textbox

**Desired converted JSON Schema  supported by  _formlyJsonschema_ is as follows:** 

  `"schema" :[`
  ` {`
    `"properties": {`
     ` "isSignInRequired": {`
        `"type": "toggle",`
        `"default": true`
     ` },`
     ` "isEmployee": {`
      ` "type": "toggle",`
        `"default": true`
      `}`
   ` }`
`},`
`{`
    `"description": "noOfEmployees",`
    `"type": "object",`
   ` "properties": {`
     ` "minValue": {`
        `"type": "integer",`
        `"title": "minValue"`
      `},`
      `"maxValue": {`
       `"type": "integer",`
        `"title": "maxValue",`
        `"minLength": 3`
     ` }`
    `}`
 ` }]`

I tried using some JSON schema-based examples but was not able to fit my  requirement in to it eg is as follows:

[stackblitz demo](https://stackblitz.com/edit/angular-json-editor-usingformly?file=src/app/app.component.ts)

**Comment by camden-penn** [comment]
A couple of things:

First, that schema doesn't exactly match the example JSON. For example, the JSON is a single object that has an object as a member, but the schema is an array of multiple objects.

Second, guessing a schema from sample JSON isn't one of the problems Formly was built to solve. It does, however, sound like something that might have been done before.
![image](https://user-images.githubusercontent.com/32797049/120659029-f5cb4080-c453-11eb-9fed-0ff9b6ae7183.png)
![image](https://user-images.githubusercontent.com/32797049/120659221-257a4880-c454-11eb-9e42-e3f8dd6bc353.png)
Perhaps a tool like these would generate the schemas for Formly to use?

**Comment by chandelshashank** [comment]
@camden-penn  Thank you for elaborating the process of generating JSON Schema which in fact is useful for building forms. I came across Inferred JSON schema but I tried finding some angular-based code to generate the schema instead of converting it manually from liquid technologies like online tools **_is there any way to generate schema in angular?_**
@aitboudad  it would be helpful if you can provide some suggestions for this. 

Stackblitz i tried on basis of liquid-tech based json schema generatror : [Click here](https://stackblitz.com/edit/angular-json-editor-usingformly-8txbwb?file=src/assets/json-schema/simple.json)
Thanks!

**Comment by aitboudad** [comment]
I think you need to create a custom converter which out of our scope right now as pointed above :pray:

**Comment by chandelshashank** [comment]
Thanks, @aitboudad I am working on creating a custom converter.
