### ISSUE TITLE
Angular Formly - TS2322: Type 'any[] | Observable<any[]> | undefined is not aassignable to type '(any[] & NgIterable<any>) | null | undefined'

### ISSUE THREAD

**Issue by svranic** [ngx-formly/ngx-formly#2880]
I'm trying to create a custom select component with Angular Formly. I extended the existing example (https://stackblitz.com/edit/angular-g1h2be) which is creating default html bootstrap select control. I'm having a problem with filling a select from JSON file via service.

I created Stackblitz example: https://stackblitz.com/edit/angular-g1h2be-dktib5 which is based on this one https://stackblitz.com/edit/angular-g1h2be.

My example works fine, but the same code doesn't work in my local IDE (PyCharm 2021.1). Error is shown on the figure.

![image](https://user-images.githubusercontent.com/13032056/121014724-94c8a300-c79a-11eb-8f0e-b91e1d2217d4.png)

I'm not sure what is the problem. Since it works on Stackblitz I'm wondering if it is a problem with my local configuration. I added property to compilerOptions `"strictPropertyInitialization": false` to my `tsconfig.json` but without any result, error keeps on showing. Could someone provide some help or advice?

Thanks in advance!

**Comment by aitboudad** [comment]
use `formlySelectOptions` pipe https://github.com/ngx-formly/ngx-formly/issues/2558#issuecomment-716134577
