### ISSUE TITLE
How to add Save/Update button vs Submit to custom Stepper/Tabs types in  example code

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2881]
@aitboudad 
Appreciate your efforts in evolving this library and the continued level of support.

I would like to understand how one can replace the Submit button in the Stepper / Tabs example to Save/Update.

Save is shown when user is creating a new entry
Update is shown when user is editing an existing entry

Currently I control that using a "_indicator" boolean flag within TS/HTML to display the appropriate button.

How would one pass such info to the custom Stepper / Tabs type in this case?

Looking forward to your help.

Thanks

**Comment by aitboudad** [comment]
> How would one pass such info to the custom Stepper / Tabs type in this case?

pass the desired config through `templateOptions`:

```patch
{
  "type": "stepper",
  "templateOptions": {
+    "submitBtnText": "Edit"
  }
}
```

```patch
<button class="btn btn-primary" type="submit">
+  {{ to.submitBtnText }}
</button>
```

*Note*: `to` is an alias of `field.templateOptions`

**Comment by argupta23** [comment]
@aitboudad 
Appreciate the quick turnaround.

In that case, what I am missing is, how does one trigger change of "SubmitBtnText" from "Edit" to "Save" within templateOptions

In normal mode, I have two buttons "Add" and "Edit" in my html/ts code which set the appropriate flag for me
```
addItem(){
_indicatorFlag = false;
}

editItem() {
_indicatorFlag=true
}
```

as part of Formly form I have these buttons
```
          <formly-form id="parserFormid" [form]="form" [fields]="fields" [model]="model">
          </formly-form>
        <div class="row">
          <div *ngIf="_indicatorFlag === false>
            <button [disabled]="!form.valid"  (click)="Save()" >SAVE</button>
          </div>
          <div *ngIf="_indicatorFlag === true>
            <button [disabled]="!form.valid"  (click)="Update()" >UPDATE</button>
          <div>
        </div>

```
My thought was to move these buttons into Stepper/Tabs and eliminate the Submit button for which I need a way to pass the _indicator flag into the custom Stepper/Tabs type.

Thanks

**Comment by aitboudad** [comment]
better inside `stepper` type just check our example https://formly.dev/examples/advanced/multi-step-form which rely on the submit event (triggered by `type="submit"`).
Another way is to emit `save / update` methods through `templateOptions`

**Comment by argupta23** [comment]
For the emit option would  something along the lines of # 720 be the way to go? or is there a simpler way to do it.?

**Comment by aitboudad** [comment]
> For the emit option would something along the lines of # 720 be the way to go? or is there a simpler way to do it.?

```patch
fields: FormlyFieldConfig[] = [{
  type: 'stepper',
  templateOptions: {
    label: 'Personal data',
+    onUpdate: () => ....
  },
  ...
}]
```

```patch
export class FormlyFieldStepper extends FieldType {
+ save() {
+   this.to.onUpdate();
+ }
}
```

**Comment by argupta23** [comment]
@aitboudad 

Sorry to bother you with this again. I finally managed to create a stackblitz around my scenario.
Can I please request your help in updating it with the relevant changes? I really need to get this to work and am out of ideas.

[https://stackblitz.com/edit/github-7hbtnh-anagsi](https://stackblitz.com/edit/github-7hbtnh-anagsi)
Thanks in advance

**Comment by argupta23** [comment]
@aitboudad 

Can I please request your help with this one. It has become a blocking issue for me?
