### ISSUE TITLE
Angular strict mode breaks custom validators

### ISSUE THREAD

**Issue by kingjordan** [ngx-formly/ngx-formly#2882]
**Description**
When I turn on strict mode for my angular project in the tscofig file
```
  "compilerOptions": {
    "strict": true,
  },
```

I get the following errors on my custom validators:

> (property) ValidatorOption.validation: FieldValidatorFn
> Type '(control: FormControl) => ValidationErrors' is not assignable to type 'FieldValidatorFn'.
>   Types of parameters 'control' and 'c' are incompatible.
>     Type 'AbstractControl' is missing the following properties from type 'FormControl': registerOnChange, registerOnDisabledChange, _applyFormStatets(2322)
> formly.config.d.ts(75, 5): The expected type comes from property 'validation' which is declared here on type 'ValidatorOption'

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-kendo-custom-valisdator?file=src%2Fapp%2Fapp.module.ts

NOTE: this does not produce the error because I cannot find out how to turn on strict mode as the tsconfig file is not exposed by stack blitz

**Your Environment**

- Angular version: 12.0.0
- Formly version: 5.10.21

**Additional context**
Formly did not want to instal in the angular 12 project because of peer dependecy issues related to the kendo controls.  I --forced it anyways to get it in.

Also, my use case is actually a lib inside an nx workspace, but the angular lib is totally isolated and is solely for setting up formyl forms in the repo.  So the formly implementation is actually quite isolated from anything else.

**Comment by kingjordan** [comment]
okay, so after fighting with his for a while, I restarted vs code and the error went away. Hopefully no one wasted time on this.

**Comment by kingjordan** [comment]
sorry about this, but after closing and opening vs code the error reappears.

**Comment by aitboudad** [comment]
Can you try with `AbstractControl`:

```patch
- emailValidator(control: FormControl): ValidationErrors {
+ emailValidator(control: AbstractControl): ValidationErrors {
```

**Comment by kingjordan** [comment]
this worked for me, thanks!
