### ISSUE TITLE
falseValue or trueValu in checkbox

### ISSUE THREAD

**Issue by Gianguodala** [ngx-formly/ngx-formly#2883]
Hi!
I ran into problems on understanding how to set falseValue or trueValue in a checkbox from the controller.
I tried in some ways (ex. declaring in `templateOptions`) unsuccesfully.
Could you please help me?

**Question**

A clear and concise description of what the question is.

**Comment by kenisteward** [comment]
Gonna have to give an explicit example. Please try pointing to formly.dev
example to explain your problem

**Comment by Gianguodala** [comment]
Thank you for the answer!
This is and example of one of the attempts i made
[https://stackblitz.com/edit/angular-eslxwq-4yxewc?file=src%2Fapp%2Fapp.component.ts](url)

**Comment by Gianguodala** [comment]
Hi! [Here](https://stackblitz.com/edit/angular-eslxwq-4yxewc?file=src%2Fapp%2Fapp.component.ts) is an example of my desired behavior with trueValue and falseValue ...hope to find a solution!

**Comment by quietgecko** [comment]
hi, Check this soln if this is what you are looking for
[trueFalse-expressionProperties](https://stackblitz.com/edit/angular-eslxwq-t9pr9u)

**Comment by aitboudad** [comment]
another way is to use `parsers`:
```patch
{
  key: 'IwantTObeAnumber',
  type: 'checkbox',
+ parsers: [v => v ? 1: 0]
}
```
