### ISSUE TITLE
Certain schemas can cause unhandled `undefined` in Formly JSON parser

### ISSUE THREAD

**Issue by camden-penn** [ngx-formly/ngx-formly#2884]
**Description**

Came to light in discussion of issue #2875. Schemas such as

```json
{
  "type": "object",
  "properties":{
    "prop":{
      "type":"array"
    }
  }
}
```

cause the parser to call `FormlyJsonschema.resolveSchema(schema, options)` with `schema` set to the unexpected value `undefined`. This function is not hardened against such a possibility, and errors out before the schema can be parsed.

**Minimal Reproduction**

https://stackblitz.com/edit/extended-formly-config-does-not-intercede?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 8.2.14
- Formly version: 5.10.20

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.22](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.22) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
