### ISSUE TITLE
Model has no assigned values nor values are updated after change

### ISSUE THREAD

**Issue by svranic** [ngx-formly/ngx-formly#2889]
I created custom select component. I'm able to catch change event, but I cannot get the value of the select component when value is selected. Then, I noticed that model is not updated at all after the initial values are set.
Example: https://stackblitz.com/edit/angular-g1h2be-dktib5

I'm missing something, but not sure what it is. Could you please help?

**Comment by aitboudad** [comment]
To get or update the field value use `formControl`, passing `[formControl]="formControl"` to `select` would take care of model changes and if you want to update the model value manually use `formControl.setValue(your_value)`.
