### ISSUE TITLE
Ellipsis hides required-marker (material)

### ISSUE THREAD

**Issue by ChristianKlima** [ngx-formly/ngx-formly#2890]
We use ngx-formly in our application and are absolutely thrilled. We have a small suggestion for improvement. The required-marker under material is currently hidden by the ellipsis if there is not enough space. We have a suggestion on how to easily rebuild it. The required-marker should not be part of the string indicated by the ellipsis. It concerns the following code in the class 'material / form-field / src / form-field.wrapper.ts':
 ```
<mat-label * ngIf = "to.label && to.hideLabel! == true">
        {{to.label}}
        <span * ngIf = "to.required && to.hideRequiredMarker! == true" class = "mat-form-field-required-marker"> * </span>
      </mat-label>
```

Change proposal:
```
<mat-label * ngIf = "to.label && to.hideLabel! == true" style = "display: flex">
<span style = "text-overflow: ellipsis; overflow: hidden">
        {{to.label}}
</span>
        <span * ngIf = "to.required && to.hideRequiredMarker! == true" class = "mat-form-field-required-marker" style = "padding-left: 3px"> * </span>
      </mat-label>
```

What do you think of this suggestion? We are currently manipulating the DOM in a custom wrapper as suggested ... but that is not a nice solution.

Thanks and Greetings

Christian
![required-marker-visible](https://user-images.githubusercontent.com/64196518/122363706-73fe0b80-cf59-11eb-98c7-66c3eb28ea36.PNG)
![rquired-marker-not-visible](https://user-images.githubusercontent.com/64196518/122363756-7b251980-cf59-11eb-860c-23986519b1bc.PNG)

**Comment by aitboudad** [comment]
if we use ellipsis here, the required marker will disappear so I think it better to leave it as it is for now :pray:.
