### ISSUE TITLE
Required properties on a not-required object in json-schema

### ISSUE THREAD

**Issue by JoelOnGithub** [ngx-formly/ngx-formly#2891]
Hi,

First of all: Thanks for putting so much effort in this library. It's going to save a ton of time. 

So we experience the following problem: 
- The schema has a not-required object `OpleveringsDt`.
- The `OpleveringsDt` object consists of 3 required fields: `Dag`, `Maand`, `Jaar`.
- Now if I enter 3 values on those fields, validation is fine. But then if I remove values in all 3 fields, I get "This field is required".

I believe in the background an empty object is still living. This is resulting in the user being stuck if they have no date to supply.

Stackblitz sample: https://stackblitz.com/edit/angular-shkjus?file=src%2Fassets%2Fjson-schema%2Fbug.json

```
{
  "schema": {
    "$id": "hi.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
      "OfferteAanvraag": {
        "$ref": "#/definitions/ObjectEntiteitType"
      },
      "required": [
        "ObjectEntiteitType"
      ]
    },
    "definitions": {
      "DatumType": {
        "required": [
          "Dag",
          "Maand",
          "Jaar"
        ],
        "properties": {
          "Dag": {
            "description": "Het veld dag wordt gevuld met een waarde van minimaal 1 en maximaal 31",
            "maximum": 31,
            "minimum": 1,
            "type": "integer"
          },
          "Maand": {
            "description": "Het veld maand wordt gevuld met een waarde van minimaal 1 en maximaal 12",
            "maximum": 12,
            "minimum": 1,
            "type": "integer"
          },
          "Jaar": {
            "description": "Jaartal, bijvoorbeeld 2006",
            "minimum": 0,
            "pattern": "\\d{4}",
            "type": "integer"
          }
        },
        "type": "object"
      },
      "N12_2Type": {
        "pattern": "-?\\d{1,12}\\.\\d{2}",
        "type": "number"
      },
      "ObjectEntiteitType": {
        "required": [
          "ServiceKosten"
        ],
        "properties": {
          "OpleveringsDt": {
            "$ref": "#/definitions/DatumType",
            "description": "Verwachte datum waarop het onderpand wordt overgedragen aan koper."
          },
          "ServiceKosten": {
            "$ref": "#/definitions/N12_2Type",
            "description": "Bedrag van de maandelijkse servicekosten."
          }
        },
        "type": "object"
      }
    }
  }
}
```

**Comment by camden-penn** [comment]
The stackblitz actually demonstrates a couple of bugs.

First, Formly doesn't handle a `null` model very well. If it would be null, it should instead be initialized to `{}`, as in the following code snippet.

```ts
tap(({ schema, model }) => {
          this.type = type;
          this.form = new FormGroup({});
          this.options = {};
          this.fields = [this.formlyJsonschema.toFieldConfig(schema)];
          this.model = model || {};
        })
```

You can see the difference by filling out the form; without the `|| {}`, pressing `Submit` pops up as `undefined`, while with it, the popup displays the data that was entered.

Second, a group of bugs introduced in 5.10.19 affect the required-ness of children of optional objects, arrays, and multischemas. Your schema is affected by an equivalent issue to #2866; you can see this by giving the various records titles, as the Bootstrap theme only shows whether an entry is required if it has a title as well. They start out optional, but changing one makes a `*` appear on each of the three (indicating that it's required). 

Putting it all together, here's [a stackblitz)](https://stackblitz.com/edit/angular-shkjus-6sjs2i?file=src%2Fapp%2Fapp.component.ts) that illuminates things a little more.

**Comment by aitboudad** [comment]
close in favor #2894
