### ISSUE TITLE
FormlyField excessive Descriptions don't automatically adjust padding & leads to overlaps

### ISSUE THREAD

**Issue by devinci** [ngx-formly/ngx-formly#2892]
**Description**
When descriptions are excessive, they exceed to predefined padding of the formly field element.

https://stackblitz.com/edit/ngx-formly-ui-material-nkvia1?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/7167770/122395593-6f485000-cf77-11eb-8971-1053881f7580.png)

**Expected Behavior**
For padding to automatically adjust based on the content present

**Your Environment**

- Angular version: 9.1.3
- Formly version: 5.10.18

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.22](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.22) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by devinci** [comment]
Looks to be resolved if I update the stackblitz package v. Will confirm again when we do our next round of deps updates, but looks to be sorted atm. Thank you!

**Comment by aitboudad** [comment]
Hi, just want to mention that the above fix has been reverted in https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.27 as it introduces another [issue](https://github.com/ngx-formly/ngx-formly/issues/3082#issuecomment-988503007).
If the solution is suitable for your case just add the following code in your app:

```
```


So the solution can be done on your

**Comment by aitboudad** [comment]
Hi, just want to mention that the above fix has been reverted in https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.27 as it introduces another [issue](https://github.com/ngx-formly/ngx-formly/issues/3082#issuecomment-988503007).
So  we decided to let end users to decide how it should be fixed, if the previous solution is suitable for your case just add the following code:

```scss
formly-wrapper-mat-form-field .mat-form-field {
  // https://github.com/angular/components/issues/4580
  &-underline, &-subscript-wrapper {
    position: static;
  }
}
```

it's an Angular Material issue which you can check here https://github.com/angular/components/issues/4580 for more info.
