### ISSUE TITLE
Array initializes required object contents as optional

### ISSUE THREAD

**Issue by camden-penn** [ngx-formly/ngx-formly#2893]
**Description**

An array with object-type items initializes required contents as optional, affecting form validity. Similar to #2831. Extant since v10.5.19.

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formly-array-required-as-optional?file=app%2Fapp.component.ts

**Your Environment**

- Angular version: 10.2.5
- Formly version: 10.5.19 - 10.5.21

**Comment by aitboudad** [comment]
close in favor #2894
