### ISSUE TITLE
Observable to share data between wrapper and main component?

### ISSUE THREAD

**Issue by koolkunz** [ngx-formly/ngx-formly#2896]
How can I share data that is fetched asynchronously (on click of a button through an api) in the main component to wrapper component?

One way I tried was using formState by mapping data in main component to formState and then trying to fetch that data in the wrapper but I couldnt find a way to subscribe to changes on formState inside the wrapper. Is that even possible?

**Comment by MaxKless** [comment]
How about passing an observable in the templateOptions? The wrapper can access it and subscribe to it. 

Alternatively, you could expose the Observable in a service. Both the component and wrapper can inject the service and subscribe to it that way.

**Comment by koolkunz** [comment]
Yeah, thanks I went the exposing observable in a service way.  Forgot to close the issue.
