### ISSUE TITLE
Getting error when I have a dependency and a required array inside of a oneOf.

### ISSUE THREAD

**Issue by anmoreno** [ngx-formly/ngx-formly#2898]
**Description**
I have nested objects with a few dependencies in those objects. Whenever an inner object has dependencies making a field rquired based on another one having a value and if the object is required by the parent it throws an error

Error: [Formly Error] [Expression "templateOptions.required"] Cannot read property 'middleName' of undefined

It's going to be easier to see it than to explain it with words.

**Minimal Reproduction**
https://stackblitz.com/edit/issue-with-v21?file=src%2Fapp%2Fapp.component.ts

In the example if you remove the required array on line 67 the error goes away or if you remove the dependencies in line 62 it works. It's something about that combination that is making it break.

When it's broken you can see that the radio button doesn't actually change the fields that correspond to the value in the oneOf, when it works you can see the fields change when you change the option.

**Your Environment**

- Angular version: 10.2.5
- Formly version: 5.10.21

**Additional context**
We don't have these problems when running version 5.10.18, when we tried to upgrade to 5.10.21 our application became unusable because of this.
I did some testing and this issue starts showing on version 5.10.19

**Comment by anmoreno** [comment]
I think the issue might have been introduced by this commit

https://github.com/ngx-formly/ngx-formly/pull/2817/commits/28e7def1e708768453ddf9f3da46a5eb8e434102

**Comment by andmoredev** [comment]
Thanks for looking into this @aitboudad. Do you have an idea of when the next minor version of the npm package will be release?

Thank you!

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.22](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.22) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
