### ISSUE TITLE
Repeat inside repeat section is not showing

### ISSUE THREAD

**Issue by saurabh1234** [ngx-formly/ngx-formly#2899]
Hi Team,

Thank you for creating this awesome library. Saved a lot of my maintenance time.
Recently i stumbled upon a issue which i am not able to solve and I wonder if the owners can help me to solve the issue.

[Try out url ](https://stackblitz.com/edit/angular-formly-repeat-edit-xcbp2k?file=src/app/app.component.ts)

**I am trying to build the following structure.**

✅ Build a repeat section using Material table
✅ Section repeat works fine with native elements eg. Input & Checkbox
✅ Build a custom Key value repeat element `KeyValueTypeComponent`.
❌ The custom key value repeat element (key=detail) is not showing up and showing as empty space.
<img width="553" alt="Screenshot 2021-06-27 at 08 35 42" src="https://user-images.githubusercontent.com/488160/123535200-ab6f7380-d722-11eb-8f05-23f2a4eab828.png">
❓ How to `pre populate keys` like below with dynamic data.
<img width="836" alt="Screenshot 2021-06-26 at 12 44 58" src="https://user-images.githubusercontent.com/488160/123535240-df4a9900-d722-11eb-92ac-b4e3dfbdce9f.png">

**Comment by rezres** [comment]
Hi, 
something seems wrong within your keyvalue type, it is not working well, you can investigate more on that, try to follow what you did in repeat type,  you can also use nested repeat, and you will end up with similar result. 
All you need to do is change the type from keyvalue to repeat, add column templates, and add a default value,
the code will look like this 
![image](https://user-images.githubusercontent.com/16581173/124552603-5d671800-de66-11eb-8c08-baecaab390b4.png)

here is how the UI will look like
![image](https://user-images.githubusercontent.com/16581173/124552462-28f35c00-de66-11eb-8c63-6eec744bd12e.png)

**Comment by aitboudad** [comment]
make sure you're using the latest version and follow our doc example toward that topic:
https://formly.dev/examples/advanced/repeating-section

here is a quick fix of the above example which edit the `keyvalue-type` to make nested repeat working:

- https://stackblitz.com/edit/angular-formly-repeat-edit-pu4tmy

the issue was in `ngFor`:
```patch
-  *ngFor="let f of field.fieldArray.fieldGroup"
+  *ngFor="let f of field.fieldGroup"
```
