### ISSUE TITLE
Adding html / dividers etc. to form via template.

### ISSUE THREAD

**Issue by hhetland** [ngx-formly/ngx-formly#2900]
Hello, and thank you for a superb product!

I’m using formly together with a self built “form designer” and I’m trying to add dividers, alerts,  informational text etc above and below the actual inputs. Some of it should also be displayed/hidden via hide expressions.

Is it possible to create a custom template or wrapper that would allow me to use ckeditor in my “builder” and get the html created there outputted in the resulting form?

My idea is to make a custom template with field type “infotext” and then use it as a ordinary field in my “builder” adding the html to value/label for example and then use the template to display this as html in the form.

Possible?

How? ;-)

Thanks again,

**Comment by MaxKless** [comment]
I'm not quite following you about ckeditor and the build, but I think you're asking about how to include infotext and additional html in your forms.

 If this infotext is related to a specific input, maybe a [custom wrapper](https://formly.dev/guide/custom-formly-wrapper) is the right approach. It has full access to a field's `FormlyFieldConfig` so you can use templateOptions to en/disable features - with [expressionProperties](https://formly.dev/guide/expression-properties) you can make it dynamic.

If you're looking to just insert things like dividers in your forms, you can use a `FormlyFieldConfig` with the `template` property. Check out an example that does just this: [Advanced Layout](https://formly.dev/examples/bootstrap-specific/advanced-layout)

**Comment by aitboudad** [comment]
in addition, you may check this repo https://github.com/franzeal/ngx-formly-designer too
