### ISSUE TITLE
 ype 'AbstractControl' is missing the following properties from type 'FormControl': registerOnChange, registerOnDisabledChange, _applyFormState

### ISSUE THREAD

**Issue by ashvinspatel** [ngx-formly/ngx-formly#2901]
Error: src/app/signup/signup.component.html:18:38 - error TS2739: Type 'AbstractControl' is missing the following properties from types from type 'FormControl': registerOnChange, registerOnDisabledChange, _applyFormState

18                                     [formControl]="myForm.controls['firstName']">
                                        ~~~~~~~~~~~

  src/app/signup/signup.component.ts:6:16
    6   templateUrl: './signup.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component SignupComponent.

**Comment by ashvinspatel** [comment]
my code
@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.css']
})
export class SignupComponent implements OnInit {
  myForm: FormGroup;
   
  
  constructor(public fb: FormBuilder) {

    this.myForm =this.fb.group({
      myFormControl: new FormControl(),
      
      firstName: [''],
      lastName: [''],
      email: [''],
      password: [''],
      confirmPassword: ['']
    })


   }



  onSubmit(signupform: { value }){
    console.log(signupform.value);
  }
  ngOnInit(): void {
  }

}
and html as**********************


div class="container">

    <div class="row">
        <div class="offset-sm-2 col-sm-8">
            <div class="card text-blank border-0">
                <div class="card-body">
                    <div class="card-title text-center">
                        <h5>Sign up for free</h5>
                    </div>
                    <div class="card-text">


                        <form [formGroup]="myForm" (ngSubmit)="onSubmit(myForm)">   
                            <div class="form-row">  
                                <div class="form-group col-sm-6">
                                    <input type="text" class="form-control"
                                    placeholder="First Name"
                                    [formControl]="myForm.controls['firstName']">
                                   
                                </div>
                                <div class="form-group col-sm-6">
                                    <input type="text" class="form-control"
                                    placeholder="Last Name">
                                </div>
                             </div>
              `               <div class="alert alert-danger">
                                 First and Last name are required
                             </div>
                             <div class="form-group">
                                <input type="email" placeholder="Enter your email"
                                class="form-control">
                                <small class="form-text text-muted">
                                    we'll never share your email with anyone else
                                </small>
                             </div>
                             <div class="alert-danger">   
                                 A valid email is required
                                 </div>
                             <div class="form-group">
                                 <input type="password" class="form-control"
                                 placeholder="Password"
                                  >
                             </div>
                             <div class="form-group">
                                <input type=" password" class="form-control"
                                placeholder="ConfirmPassword">
                                
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-black btn-warning">
                                    Submit
                                </button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

**Comment by aitboudad** [comment]
The provided example doesn't use Formly, please ask the question in the Angular channel instead.
