### ISSUE TITLE
Update docs to show how Bootstrap 4's .custom-select class can be used

### ISSUE THREAD

**Issue by aashwath** [ngx-formly/ngx-formly#2902]
Hello,

I've been using this superb library since the past month. Our application is using `Bootstrap 4.6` and we apply the `.custom-select` to all our `select` form controls, as it provides a cross browser compatible style.

It took me a while to figure out how to apply `.custom-select` when automating forms with Angular Formly. (To my knowledge) It wasn't mentioned in the docs nor in the examples' debug options. It was only when I delved into the source code did I realise that we can use `customSelect: true` in the `templateOptions` property.

This is a handy feature, which is optimal for cross-browser compatibility of the UI as mentioned earlier. Could be specified in the docs, maybe as a toggle in the 'debug' mode for the Bootstrap demos. Would be happy to lend a hand!

**Tech stack used**

1. Angular 11
2. Angular Formly v5
3. Bootstrap 4.6

**Comment by aitboudad** [comment]
that's on our scop, we'll provide an API doc that will explain all the extra options for each type so not only bootstrap but all our UIs.
Thanks!
