### ISSUE TITLE
Custom select type doesn't work correctly

### ISSUE THREAD

**Issue by Dzhavad** [ngx-formly/ngx-formly#2903]
Hello everyone. According to my needs I created a new type select 2
But it doesn't work correctly
![image](https://user-images.githubusercontent.com/52409434/123558758-c80aba80-d7b9-11eb-8a26-8f0b19f27129.png)
It only opens if I click on the center, i want it open if I click on the whole select area

Project for example
https://stackblitz.com/edit/ngx-formly-select-value-text-zutund

Could you help me please

**Comment by aitboudad** [comment]
> It only opens if I click on the center, i want it open if I click on the whole select area

you can control that by using the `onContainerClick` method:

```ts
onContainerClick(event: MouseEvent): void {
  super.onContainerClick(event);

  this.selectElm.open(...);
}
```
