### ISSUE TITLE
How to create a custom control for <label/> with data binding from model

### ISSUE THREAD

**Issue by sranjan-m** [ngx-formly/ngx-formly#2905]
**Question**
Can anyone here please help me with creating a custom control for label?
I want to create a custom control which will bind the data from the model
A real-time use case scenario is to show the "Ref #" which is a system generated number for each record and it's not supposed to be edited. So, we need to show the Ref # on a label control.

Thank you.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2215#issuecomment-622125324
