### ISSUE TITLE
Fields of a fieldGroup (all disabled) become enabled when the model is set

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#2907]
When ALL fields of a fieldGroup are disabled=true (by configuration or programmatically), on a later set of the model, these fields become disabled=false.

https://stackblitz.com/edit/angular-iiq1b5?file=src%2Fapp%2Fapp.component.ts

- Angular version: 12.0
- Formly version: 5.20.21

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.22](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.22) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
