### ISSUE TITLE
Preselect a radio in datatable column

### ISSUE THREAD

**Issue by kaydaga** [ngx-formly/ngx-formly#2909]
**Preselect a radio button in datatable column**

I have a need to auto select a radio button which is in a swimlane/ngx-datatable column. Based on a selection of certain field the radio buttons should auto select to a specific value inside that datatable. Sample for reference is at <a> https://stackblitz.com/edit/angular-1bsezq</a>. I have tried using expression properties but it does not seem to work. Please tell where is it going wrong.
Appreciate your help here!

**Comment by aitboudad** [comment]
The question is not clear, please elaborate :pray:

**Comment by kaydaga** [comment]
I have two fields i.e one radio button with options Yes & No and the other one a  data table with a column which has radio buttons in that with option Yes & No. If on the first field Yes is selected then the data column which has the radio button should also have Yes selected. I am using expressionproperties for the same. The example is at <a>https://stackblitz.com/edit/angular-1bsezq</a>

**Comment by aitboudad** [comment]
`expressionProperties` is evaluated in both directions so it may be suitable if the radio button is read-only, in your case better rely on `valueChanges` instead: https://stackblitz.com/edit/angular-1bsezq-qgkub8
