### ISSUE TITLE
Immutable and Parser not working together

### ISSUE THREAD

**Issue by rainerhahnekamp** [ngx-formly/ngx-formly#2911]
**Description**
If you configure the `FormlyModule` with immutable property set to true, parsers will not be processed anymore.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-ixlc83

**Comment by aitboudad** [comment]
the `model` is not updated when `immutable` is enabled,you need to rely on `modelChange` output:

```patch
<formly-form
+ (modelChange)="model = $event"
  ...
>
</formly-form>
```

**Comment by rainerhahnekamp** [comment]
Thanks a lot!
