### ISSUE TITLE
Saved value not displayed when editing Cascaded field

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#2920]
I have followed your Cascaded (observable) example and it works fine when I am creating a new entry and it does get saved to the database.

But when I try to edit it the value of the cascaded field is not displayed in the form.

I have created a stackblitz around the problem I am facing.

[https://stackblitz.com/edit/github-7hbtnh-inxxln](https://stackblitz.com/edit/github-7hbtnh-inxxln)

Can I please request your help in figuring out what I am doing wrong?

Thanks in advance for your help.

**Comment by argupta23** [comment]
I believe the issue is with this line.

`tap(() => field.formControl.setValue(null)),`

It causes the field to be set to "null" in edit mode.

What would be the correct syntax be?? Thx

**Comment by aitboudad** [comment]
move that line before `startWith` call:

```patch
field.templateOptions.options = sportControl.valueChanges.pipe(
+ tap(() => field.formControl.setValue(null)),
  startWith(sportControl.value),
- tap(() => field.formControl.setValue(null)),
);
```

**Comment by argupta23** [comment]
@aitboudad 
Really appreciate the quick response. It works.

Can I please request your help on the other issue #2881 ? 

Thx
