### ISSUE TITLE
How to get one model property data to another model property in json schema angular

### ISSUE THREAD

**Issue by MonalisaPatnaik** [ngx-formly/ngx-formly#2921]
I have two input components.
On change of one input component, the entered value to be displayed in the another component

In json schema ,
 "Input1": {
      "type": "string",
      "widget": {
        "formlyConfig": { "className": "col-xs-6" }
      },
      "title": "Input 1"
    }
 "Input2": {
        "type": "string",
        "widget": {
          "formlyConfig": {
            "className": "col-6",
            "templateOptions": {
              "disabled": true
            }
          }
        },
        "title": "Input2"
      },

Expected Output:

mode.Input1 = "test"
model.Input2 = mode.Input1

**Comment by aitboudad** [comment]
you can achieve that by using either `expressionProperties` or subscribe to `valueChanges`:

- https://github.com/ngx-formly/ngx-formly/issues/2607
- valueChanges:

```ts
hooks: {
  onInit: ({ form, formControl }) => {
    return formControl.valueChanges.pipe(
      tap(value => {
        form.get('Input2').setValue(value)
      })
    );
  }
}
```


to apply that solution to `json-schema` see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
