### ISSUE TITLE
Expression property changed value not reflecting in the UI

### ISSUE THREAD

**Issue by MonalisaPatnaik** [ngx-formly/ngx-formly#2925]
In the below example, the 
 "model.age": "model.bio" value is not getting display in the UI. But the model data is updated properly.

Example:

{
  "schema": {
    "title": "A registration form (nullable)",
    "description": "A simple form example using nullable types",
    "type": "object",
    "required": [
      "fullName"
    ],
    "properties": {
      "fullName": {
        "type": "string",
        "title": "First name",
        "default": "Chuck"
      },
      "age": {
        "type": [
          "integer",
          "null"
        ],
        "title": "Age"
      },
      "bio": {
        "type": [
          "string",
          "null"
        ],
        "title": "Bio",
        "widget": {
          "formlyConfig": {
            "type": "textarea",
            "templateOptions": {
              "placeholder": "Leaving this field empty will cause formData property to be `null`",
              "rows": 5
            },
            "expressionProperties": {
              "model.age": "model.bio"
            }
          }
        }
      }
    }
  },
  "model": {
    "fullName": "Chuck",
    "age": 75,
    "bio": null
  }
}

**Comment by kenisteward** [comment]
@MaxKless could you please setup a stackblitz?  I believe i have a PR that will fix this for you but i want to just make sure it's the same thing I have an issue with.

**Comment by MaxKless** [comment]
Hi, I just randomly read this and saw I was mentioned :D Are you talking about @MonalisaPatnaik  or do you really want me to setup a Stackblitz?

**Comment by kenisteward** [comment]
> Hi, I just randomly read this and saw I was mentioned :D Are you talking about @MonalisaPatnaik  or do you really want me to setup a Stackblitz?

I am soooo sorry! I was on my phone when I made that comment and used the auto complete!

@MonalisaPatnaik please make a stackblitz :)
