### ISSUE TITLE
How to focus on group at index in formArray

### ISSUE THREAD

**Issue by begandroide** [ngx-formly/ngx-formly#2926]
**Question**

Hi! thanks for the lib, very nice one. I'm extending custom form field array (aka repeat) with the functionality of add a new group at index next of group selected and all works fine with the `add(index)` method. But when I want provide functionality of focus on the new item at index added, the focus going to the last element and not in the previous group created.

Since is a question I don't provide stackblitz example, but if you need it I can share my repo [https://github.com/begandroide/ngformly-uitesis/tree/feature/section](https://github.com/begandroide/ngformly-uitesis/tree/feature/section)

Regards.

**Comment by begandroide** [comment]
I found a workaround working with `formState` and `expressionProperties`:
```typescript
formState = { selectedIndex: 0};

fields = [
{
      key: 'questions',
      type: 'repeat',
      fieldArray: {
        wrappers: ['container'],
        fieldGroupClassName: 'row',
        templateOptions: {
          label: 'Title',
          btnText: 'Add another investment',
        },
        focus: true,
        fieldGroup: [
          {
            defaultValue: '',
            className: 'col-sm-4',
            type: 'input',
            key: 'name',
            expressionProperties: {
              focus: 'field.parent.key == formState.focusedIndex',
              blur: 'field.parent.key != formState.focusedIndex'
            },
            templateOptions: {
              label: 'Test:',
            },
          },
        ],
      },
    },
]
```

**Comment by kenisteward** [comment]
@begandroide I'm going to close this as it looks like you've found a solution for the problem that you were having.  If there are any more things feel free to open a new issue!
