### ISSUE TITLE
Formly selector loading for some seconds

### ISSUE THREAD

**Issue by RamasubramanianA** [ngx-formly/ngx-formly#2928]
**Question**

I have implemented complex custom wrapper. If the FORM contain 10+ fields, each one is a complex custom wrapper it is hanging HTML UI page for some seconds.
means Formly tag taking time to prepare and load the form element.

Is there any Event - Telling that when the FORM loading is completed? 
Can we run it in web worker or like background so that UI will never hang?

**Comment by aitboudad** [comment]
> Is there any Event - Telling that when the FORM loading is completed?

Not yet, related to https://github.com/ngx-formly/ngx-formly/issues/2762

> Can we run it in web worker or like background so that UI will never hang?

The rendering task is deligated to Angular, we would love Angular to provide a such option :pray:
