### ISSUE TITLE
Promote typeless Jsonschema FormlyFieldConfigs to 'undefined' type

### ISSUE THREAD

**Issue by camden-penn** [ngx-formly/ngx-formly#2929]
**Is your feature request related to a problem? Please describe.**
When a Jsonschema record doesn't have type information, the type in the FormlyFieldConfig is left as `undefined`. This leads to downstream issues in which the renderer gives up before attempting to look up if a relevant component exists.

**Describe the solution you'd like**
If `formlyJsonschema.guessType()` would return `undefined`, instead return `'undefined'`. This would allow for fallback components and the like without meddling with other aspects of Formly.

**Comment by kenisteward** [comment]
Would it make sense to just define a common 'undefined' type that will
generate?

The problem with having typeless is we have no way of knowing what is
supposed to generate component wise. At least with 'undefined' one can add
that type as a name and do with what they please.

**Comment by camden-penn** [comment]
That's what the suggested solution would do - it substitutes in a `'undefined'` type whenever it would otherwise be `undefined`. The current behavior seems to be setting type to `undefined`, then a silent shrug during component selection and a blank patch where a component should be.

**Comment by kenisteward** [comment]
I I read that backwards! I approve of this idea!

**Comment by aitboudad** [comment]
still not clear to me :confused:, but anyway have you tried to apply the fallback using `map` option:

```ts
this.formlyJsonschema.toFieldConfig(
  schema,
  {
    map: (field: FormlyFieldConfig, schema: JSONSchema7) => {
      if (!field.type) {
        field.type = 'undefined';
      }

      return field;
    },
   },
);
```
