### ISSUE TITLE
Form Value is not updating

### ISSUE THREAD

**Issue by joharzmn** [ngx-formly/ngx-formly#2930]
**Question**

How to populate a calculated field based on other fields and also it should update in the form so it can be validated? The calculated field should be read-only.
**Here is the example setup:** 
[Reproducible Example](https://stackblitz.com/edit/ngx-formly-ui-kendo-gdego3?file=src%2Fapp%2Fapp.component.ts)

I tried to use expression properties but not sure how it will work.

**Note:** The formly configuration is coming from the database (as json).

**Comment by vitale232** [comment]
Hi joharzmn... There's probably a bunch of ways to solve this. This way seems pretty straight forward to me...

[I forked your blitz.](https://stackblitz.com/edit/ngx-formly-ui-kendo-yedtkm?file=src%2Fapp%2Fapp.component.ts) In the HTML, I've added the [`modelChange`](https://formly.dev/guide/properties-options) event to the `formly-form` component element. The event is bound to a simple handler, `onModelChange`.

In the TypeScript, the `onModelChange` method checks that the model has a defined, non-null value stored in the `num1` and `num2` properties. If so, the values are coerced to a number and the `model.total` is updated manually.

That's enough to get the value computed, but it still doesn't show up in the UI. To accomplish that, I'm simply calling `setValue` on the `total` `FormControl` with the newly computed total.

I also added validation messages into the `app.module.ts` to accommodate the `min` and `max` validations.

**Note** regarding `onModelChange` in `app.component.ts`: a simple `if` leads to a bug where 0 is not an accepted value, hence the `model.prop != null` checks.

**Note** regarding UX: you may want to experiment with the [`updateOn`](https://formly.dev/examples/field-options/model-options) config if you find the immediate updates to the total are distracting.

Hope this helps.

**Comment by AlirezaEbrahimkhani** [comment]
This problem is because of the formly can not detect your changes 
try this it will solve your problem

add this to your html code 
`<formly-form [form]="form" [model]="model" [fields]="fields" (modelChange)="onModelChange($event)">
  </formly-form>`

and this to your typescript file
`
onModelChange($event) {
    this.model = {...this.model}
  }
`

**Comment by joharzmn** [comment]
> Hi joharzmn... There's probably a bunch of ways to solve this. This way seems pretty straight forward to me...
> 
> [I forked your blitz.](https://stackblitz.com/edit/ngx-formly-ui-kendo-yedtkm?file=src%2Fapp%2Fapp.component.ts) In the HTML, I've added the [`modelChange`](https://formly.dev/guide/properties-options) event to the `formly-form` component element. The event is bound to a simple handler, `onModelChange`.
> 
> In the TypeScript, the `onModelChange` method checks that the model has a defined, non-null value stored in the `num1` and `num2` properties. If so, the values are coerced to a number and the `model.total` is updated manually.
> 
> That's enough to get the value computed, but it still doesn't show up in the UI. To accomplish that, I'm simply calling `setValue` on the `total` `FormControl` with the newly computed total.
> 
> I also added validation messages into the `app.module.ts` to accommodate the `min` and `max` validations.
> 
> **Note** regarding `onModelChange` in `app.component.ts`: a simple `if` leads to a bug where 0 is not an accepted value, hence the `model.prop != null` checks.
> 
> **Note** regarding UX: you may want to experiment with the [`updateOn`](https://formly.dev/examples/field-options/model-options) config if you find the immediate updates to the total are distracting.
> 
> Hope this helps.

Hello @vitale232, 
I have generic configurations for formly in the database so it will be difficult to achieve this functionality if I don't know what field I need to update in `onModelChange` method. Do you know any way to achieve this through expression properties or any other configuration?

**Comment by vitale232** [comment]
@joharzmn Is this closer to what you need?

You can bind to the model in `expressionProperties`. In [this Blitz](https://stackblitz.com/edit/ngx-formly-ui-kendo-yedtkm?file=src%2Fapp%2Fapp.component.ts), I'm binding to the `model.total` in the calculated field's expression props, applying the same logic as before.

Just out of curiosity, are you saving formly configs as JSON in your db, or is there an API that's generating the config based off of database field types? If the former, do you just develop the form as you go and then commit it? I'd like to start heading this direction in my use of Formly... It would be really neat to build configs off of the database metadata.

**Comment by joharzmn** [comment]
@vitale232 Actually I am saving formly config as JSON in the DB. So I can't use lambda expression in expression properties. 
But I fixed It by manually updating the formControl that is not the ideal solution but it is working as a workaround.

**Comment by vitale232** [comment]
@joharzmn I think you can achieve the same thing with a string:

```
      expressionProperties: {
        'model.total':
          'model.num1 != null && model.num2 != null ? Number(model.num1) + Number(model.num2) : null'
      }
```

https://stackblitz.com/edit/ngx-formly-ui-kendo-zhk15z?file=src%2Fapp%2Fapp.component.ts

**Comment by joharzmn** [comment]
> @joharzmn I think you can achieve the same thing with a string:
> 
> ```
>       expressionProperties: {
>         'model.total':
>           'model.num1 != null && model.num2 != null ? Number(model.num1) + Number(model.num2) : null'
>       }
> ```
> 
> https://stackblitz.com/edit/ngx-formly-ui-kendo-zhk15z?file=src%2Fapp%2Fapp.component.ts

@vitale232  this worked for me. Thanks.
