### ISSUE TITLE
Cannot read property 'length' of undefined at FieldExpressionExtension.toggleFormControl

### ISSUE THREAD

**Issue by AlirezaEbrahimkhani** [ngx-formly/ngx-formly#2931]
**Description**
Hi
when i use hideExpression for some fields i got an error

Error
`ERROR TypeError: Cannot read property 'length' of undefined
    at FieldExpressionExtension.toggleFormControl (ngx-formly-core.js:2681)
    at ngx-formly-core.js:2564
    at Array.forEach (<anonymous>)
    at FieldExpressionExtension.checkField (ngx-formly-core.js:2560)
    at ngx-formly-core.js:2400
    at reduceFormUpdateValidityCalls (ngx-formly-core.js:370)
    at Object.field.options._checkField (ngx-formly-core.js:2397)
    at FormlyForm.checkExpressionChange (ngx-formly-core.js:1235)
    at FormlyForm.ngDoCheck (ngx-formly-core.js:1118)
    at callHook (core.js:3285)`

and my code

`
{
            className: "flex-22-5 padding-x-5",
            key: "CountryID",
            type: "select",
            templateOptions: {
              label: "Country",
              options: this.sharedService.countries,
              valueProp: "value",
              labelProp: "name",
              appearance: "outline",
              change: (field, $event) => {
                this.sharedService.getStates($event.value);
              },
            },
          },
          {
            className: "flex-22-5 padding-x-5",
            key: "StateID",
            type: "select",
            templateOptions: {
              label: "State",
              options: this.sharedService.states,
              valueProp: "value",
              labelProp: "name",
              appearance: "outline",
              change: (field, $event) => {
                this.sharedService.getCity($event.value);
              },
            },
            hideExpression: (model) => {
              let temp = false;
              if (model.CountryID != 226) temp = true;
              return temp;
            },
          },
          {
            className: "flex-22-5 padding-x-5",
            key: "CityID",
            type: "select",
            templateOptions: {
              label: "City",
              options: this.sharedService.city,
              valueProp: "value",
              labelProp: "name",
              appearance: "outline",
              required: true,
            },
            hideExpression: (model) => {
              let temp = false;
              if (model.CountryID != 226) temp = true;
              return temp;
            },
          },
          {
            className: "flex-22-5 padding-x-5",
            key: "CityName",
            type: "input",
            templateOptions: {
              label: "City Name",
              appearance: "outline",
            },
            hideExpression: (model) => {
              let temp = true;
              if (model.CountryID != 226) temp = false;
              return temp;
            },
          },
`

- Angular version: 10.2.2
- Formly version: 5.0.0

**Comment by MaxKless** [comment]
Could you format the code? I'd love to see if I can help but it's unreadable like this.

**Comment by aitboudad** [comment]
A reproduction is needed here, feel free to reopen once you've got a reproduction, here is our `stackblitz` starter example: https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
