### ISSUE TITLE
Using captcha

### ISSUE THREAD

**Issue by girish66** [ngx-formly/ngx-formly#2934]
Do you have an example of using Captcha?

**Comment by kenisteward** [comment]
Not currently.
  It would be ok formly.dev if we did though!

If you happen to get it going and would like to make a contribution to the docs it would be appreciated!

**Comment by aitboudad** [comment]
By following our guide https://formly.dev/guide/custom-formly-field, you can easily integrate https://www.npmjs.com/package/ngx-captcha for example.

1. install `ngx-captcha`: https://github.com/Enngage/ngx-captcha#installation

2. Register `captcha` type (https://formly.dev/guide/custom-formly-field)

```patch
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
 selector: 'formly-field-catcha',
 template: `
  <ngx-recaptcha2 #captchaElem
    ...
+	[formControl]="formControl"
    >
  </ngx-recaptcha2>
 `,
})
export class FormlyFieldCaptcha extends FieldType {}
```

2. define captcha as required in the field config:

```patch
  fields: FormlyFieldConfig[] = [
    {
      key: 'captcha',
      type: 'captcha',
      templateOptions: {
        label: 'Captcha',
+       required: true,
      }
    }
  ];
```

> If you happen to get it going and would like to make a contribution to the docs it would be appreciated!

:pray:
