### ISSUE TITLE
Add an empty row to the custom FieldType table on click of a custom FieldType button 

### ISSUE THREAD

**Issue by sranjan-m** [ngx-formly/ngx-formly#2935]
**Question**
I have 2 custom types for button and an html table with repeating tr from the model.
I want to add an empty row to the table when click the button.
How can I add a row to the table model on click of the button?

It's pretty confusing and difficult because the models are available only to the respective types. How can I access the table's model to add a row from the custom button type?

Here's a sample [Stackblitz](https://stackblitz.com/edit/angular-ivy-ay1lyo) example

Thanks.

**Comment by sranjan-m** [comment]
Does anyone have any idea about how to achieve this? Any reference to this would be really helpful.
Thanks.

**Comment by kenisteward** [comment]
Instead of extending fieldtype, extend arrayfieldtype and use
this.add(null, {})

**Comment by aitboudad** [comment]
Use `FieldArrayType` which simplifies managing the arrays and provide `add`/`remove` methods https://formly.dev/examples/advanced/repeating-section.

if you need access to those methods, which can be used in custom button type check the following example https://stackblitz.com/edit/angular-rsg1kj?file=src%2Fapp%2Frepeat-delete.type.ts
