### ISSUE TITLE
Model doesn't bind to input field inside custom fieldtype table

### ISSUE THREAD

**Issue by sranjan-m** [ngx-formly/ngx-formly#2940]
**Description**
As the stackblitz below explains,
I have a custom field type table with 3 columns (Name, Address, Mob. No).
Name and Address to show the plain text from the model and Mob. No. is an input field suppose to bind from the model.

But when the table is rendered, it shows the values for Name & Address, but the input field for Mob. No. doesn't bind to the model and it stays as just a blank input text field.

**Minimal Reproduction**
This is a [Stackblitz](https://stackblitz.com/edit/angular-ivy-v9sk3u) reproduction link for the above problem.

**Additional context**
I'm not sure how to pass the column's model to `<formly-field>`. Need help.

**Environment**

- Angular version: 10.1.4
- Formly version: 5.0.0

Thank You.

**Comment by aitboudad** [comment]
use `FieldArrayType` to properly handle arrays, https://formly.dev/examples/advanced/repeating-section
