### ISSUE TITLE
bind change event to formly with ionic custom select box with json

### ISSUE THREAD

**Issue by w4web** [ngx-formly/ngx-formly#2941]
My code is here..

constructor(public eventService: EventService) {
    this.eventService.getEventOverviewFields().subscribe((fields: any) => {
      this.editForm = new FormGroup({});
      this.fields = fields.map((field: any) => {
        if (field.fieldGroup) {
          field.fieldGroup.map((fg1: any) => {
            if (fg1.fieldGroup) {
              fg1.fieldGroup.map((fg2: any) => {
                if (fg2.fieldGroup) {
                  fg2.fieldGroup.map((f: any) => {
                    if (f.templateOptions && f.templateOptions.changeExpr) {
                      f.templateOptions.change = Function('field', '$event', f.templateOptions.changeExpr).bind(this);
                    }
                    if (f.templateOptions && f.templateOptions.keyupExpr) {
                      f.templateOptions.keyup = Function('field', '$event', f.templateOptions.keyupExpr).bind(this);
                    }
                  });
                }
              });
            }
          });
        }
        return field;
      });

      console.log("this.fields", this.fields);
      
      this.setTotal();
    });

.
.
.
.
{
                "className": "col-lg-4 col-12 single-field",
                "key": "startGel",
                "type": "numberSelect",
                "defaultValue": 0,
                "templateOptions": {
                  "label": "Start Gel",
                  "selectOptions" : {
                    "startValue": 0,
                    "endValue": 1
                  },
                  "unit": "P",
                  "changeExpr": "this.changeStartGel($event, field)"
                }
              },
.
.
.
.
.

My custom select component

<div class="selector-wrap" *ngIf="isWeb">
        <ion-row>
          <ion-col size="5" class="flex al-center">
            <ion-label><span class="label-txt">{{to.label}}</span> <span *ngIf="showInfoIcon" (click)="openModal()" class="info-icon"><ion-icon name="information-circle-outline"></ion-icon></span></ion-label>
          </ion-col>
          <ion-col size="7">
            <ion-item lines="none">
              <ion-label>{{to.label}}</ion-label>
              <ion-select [formControl]="formControl" [formlyAttributes]="field">
                <ng-container *ngFor="let item of selectValues">
                  <ion-select-option [value]="item.value">{{ item.label }}</ion-select-option>
                </ng-container>
              </ion-select>
              <div *ngIf="to.unit" class="end-slot" slot="end">
                <p>{{to.unit}}</p>
              </div>
            </ion-item>
          </ion-col>
        </ion-row>
      </div>

**Comment by aitboudad** [comment]
check our demo example https://formly.dev/examples/other/json-powered, which include how to bind change event using map function .
