### ISSUE TITLE
dynamic row addition on ag-grid/table

### ISSUE THREAD

**Issue by thashutasleem** [ngx-formly/ngx-formly#2942]
Hello i'm  trying implementing ag-grid to achieve dynamically addition of rows on clicking a button in every row (something like repeating section to add a row), but looks like number of rows is depends on data in the model,  Can anyone suggest possible solution with ag-grid or using any other module to achieve the following. 

1- Grid/Table structure with field names as Column
2- Last column as a check-box or button to add another row to the table dynamically

**Comment by aitboudad** [comment]
see https://formly.dev/examples/advanced/grid-integration

**Comment by smile2014** [comment]
cell cascade,In a row of data, I enter the quantity and unit price to automatically calculate amount  @aitboudad
