### ISSUE TITLE
angular-material select element is doesn't working on angular formly

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#2944]
{
      key: 'country',
      type: 'select',
      // defaultValue:'India',
      templateOptions: {
        label: 'select country',
        placeholder: 'select country',
        required: true,
        appearance:'outline',
        options: [
          { label: 'India', value: 'India' },
          { label: 'America', value: 'America' },
          { label: 'Australia', value: 'Australia' },
        ],
      },

**Comment by dc-p8** [comment]
https://stackblitz.com/edit/formly-example-kfii7z

**Comment by dc-p8** [comment]
https://stackblitz.com/edit/ngx-formly-ui-material-xajg7u

**Comment by vardhan1122** [comment]
HIi Dear. Thank you for early responding...

this is my code doesn't work, please guide me where i was wrong

import { Component, OnInit } from ***@***.***/core';
import { FormGroup } from ***@***.***/forms';
import { FormlyFormOptions, FormlyFieldConfig  } from ***@***.***/core';

@Component({
  selector: 'app-disabled-fields',
  templateUrl: './disabled-fields.component.html',
  styleUrls: ['./disabled-fields.component.css']
})
export class DisabledFieldsComponent implements OnInit {

  form = new FormGroup({});
  model: any = {
    // selectCountry:'select country',
    // selectState:'select state'
  };
  options: FormlyFormOptions = {};
  fields: FormlyFieldConfig[] = [
    {
      key: 'firstName',
      type: 'input',
      templateOptions: {
        label: 'First Name',
        placeholder: 'Type here to see the other field become enabled...',
        required: true,
        appearance:'fill',
      },
      validation: {
        messages: {
          required:'First Name must be required',
        },
      },
    },

    {
      key: 'lastName',
      type: 'input',
      templateOptions: {
        label: 'Last Name',
        placeholder:
'This one is disabled if there is no text in the first-name  input',
        required: true,
        appearance:'fill',
      },
      expressionProperties: {
        'templateOptions.disabled': '!model.firstName',
      },
      validation: {
        messages: {
          required:'Last Name must be required',
        },
      },
    },

    {
      key: 'country',
      type: 'select',
      defaultValue:'India',
      templateOptions: {
        label: 'select country',
        placeholder: 'select country',
        required: true,
        appearance: 'outline',
        options: [
          { label: 'India', value: 'India' },
          { label: 'America', value: 'America' },
          { label: 'Australia', value: 'Australia' },
        ],
      },
      hooks: {
        onInit: field => {
          field?.formControl?.valueChanges.subscribe(v => {
            console.log('changed', v);
          });
        }
      },
      expressionProperties: {
        // 'templateOptions.placeholder': 'model.selectCountry',
      },
      validation: {
        messages: {
          required:'Country must be required',
        },
      },
    },

    {
      key: 'indianStates',
      type: 'select',
      // defaultValue:'India',
      templateOptions: {
        label: 'select state',
        placeholder: 'select State',
        required: true,
        appearance:'outline',
        // attributes:{
        //   class:'form-control, form-select'
        // },
        options: [
          { label: 'Tamilnadu', value: 'Tamilnadu' },
          { label: 'karnataka', value: 'Karnataka' },
          { label: 'Telengana', value: 'Telengana' },
        ],

      },
      expressionProperties: {
        // 'templateOptions.placeholder': 'model.selectState',
        // 'templateOptions.disabled': '!model.country',

// 'templateOptions.disabled':(model:any) => (model.country &&
this.model.country !== 'India')

// 'templateOptions.disabled':(model:any) => (!model.country ||
model.country && this.model.country !== 'India')
      },
      validation: {
        messages: {
          required:'State must be required',
        },
      },
    },

    {
      key: 'americanStates',
      type: 'select',
      // defaultValue:'India',
      templateOptions: {
        label: 'select state',
        placeholder: 'select State',
        required: true,
        // attributes:{
        //   class:'form-control, form-select'
        // },
        options: [
          { label: 'Washington', value: 'Washington' },
          { label: 'Los Angeles', value: 'Los-Angeles' },
          { label: 'New York', value: 'New-York' },
        ],

      },
      expressionProperties: {
        // 'templateOptions.placeholder': 'model.selectState',
        'templateOptions.disabled':(model:any) => (!model.country || model.
country && this.model.country !== 'America')
      },
      validation: {
        messages: {
          required:'State must be required',
        },
      },
    },

    {
      key: 'australianStates',
      type: 'select',
      // defaultValue:'India',
      templateOptions: {
        label: 'select state',
        placeholder: 'select State',
        required: true,
        // attributes:{
        //   class:'form-control, form-select'
        // },
        options: [
          { label: 'Sydney', value: 'Sydney' },
          { label: 'Perth', value: 'Perth' },
          { label: 'Adelaide', value: 'Adelaide' },
        ],

      },
      expressionProperties: {
        // 'templateOptions.placeholder': 'model.selectState',
        'templateOptions.disabled':(model:any) => (!model.country || model.
country && this.model.country !== 'Australia')
      },
      validation: {
        messages: {
          required:'State must be required',
        },
      },
    },

  ];

  submit() {
    // alert(JSON.stringify(this.model));
    console.table(this.model);
    // this.form.reset();
  }


  constructor() { }

  ngOnInit(): void {
  }

}

**Comment by vardhan1122** [comment]
"dependencies": {
    ***@***.***/animations": "~12.1.0",
    ***@***.***/cdk": "^12.2.0",
    ***@***.***/common": "~12.1.0",
    ***@***.***/compiler": "~12.1.0",
    ***@***.***/core": "~12.1.0",
    ***@***.***/forms": "~12.1.0",
    ***@***.***/material": "^12.2.0",
    ***@***.***/platform-browser": "~12.1.0",
    ***@***.***/platform-browser-dynamic": "~12.1.0",
    ***@***.***/router": "~12.1.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4",
    ***@***.***/core": "^5.0.0",
    ***@***.***/material": "^5.0.0"
  },

**Comment by vardhan1122** [comment]
Thanks you so much , now its works.


How to pass valid custom messages to user.

**Comment by aitboudad** [comment]
> How to pass valid custom messages to user.

https://formly.dev/examples/validation/validation-message
