### ISSUE TITLE
Unable to Type X key in Chips component using @ngx-formly/core 5.9.3

### ISSUE THREAD

**Issue by KarthiRathinavelu** [ngx-formly/ngx-formly#2945]
**Description**
I'm using @ngx-formly/core chip component. it working amazing, but when user try add Sex, Execute words at time user press x key on time it generate chip.
Ex: Se is one chip and E is one chip   

- Angular version: 9
- Formly version: 5.9.3

**Additional context**

**Comment by aitboudad** [comment]
There is no such restriction from Formly side so it would be better if you can provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by aitboudad** [comment]
feel free to reopen once you have got a reproduction.
