### ISSUE TITLE
Cannot read property 'formState' of undefined // Cannot read property 'showError' of undefined

### ISSUE THREAD

**Issue by oividioscaeremos** [ngx-formly/ngx-formly#2946]
**Description**
When I try to add a new FormFieldConfig into the present `formFields[0].fieldGroup` object with `hideExpression` it throws this error. And the form does not render. I saw [this#2197](https://github.com/ngx-formly/ngx-formly/issues/2197) which was talking about the same problem but I couldn't figure out what can be done to make the error go away.
And also when I remove the `hideExpression`, it gives me the error `Cannot read property 'showError' of undefined`. So there's not a way for me to extend the `formFields[0].fieldGroup` array. 

**Minimal Reproduction**
https://stackblitz.com/edit/formly-starter-example-fcnweb?file=src/app/app.component.ts

**Your Environment**

- Angular version: 11.0.9
- Formly version: 5.10.21

**Additional context**
It doesn't occur when the initial object has the same `hideExpression`. 
And it doesn't occur when I try to push new objects into the `formFields` array. But when I try to push a new object into `formFields[0].fieldGroup` then the error occurs.

**Comment by aitboudad** [comment]
The `push` doesn't detect the new changes, your spread operator instead or update fields after the push call:

```patch
  this.newFields.forEach(f => this.fields[0].fieldGroup.push(f));
+ this.fields = [...this.fields];
```
