### ISSUE TITLE
How to pass valid custom messages to UI

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#2947]
Hi Dear, Good evening.

I wan a showing valid message in the UI using formly. Could you please explain...

Thanks in Advace.

**Comment by kenisteward** [comment]
Please check formly.dev for examples

There should be one for validations messages.

Currently only phone or I'd send it to you.

**Comment by joharzmn** [comment]
@vardhan1122 

Example from formly.dev 

This is how you can add custom validation messages that will show in the formly fields based on validation type.

```typescript
export function IpValidatorMessage(err, field: FormlyFieldConfig) {
  return `"${field.formControl.value}" is not a valid IP Address`;
}
...
@NgModule({
  imports: [
    ...
    FormlyModule.forRoot({
      validationMessages: [
        { name: 'ip', message: IpValidatorMessage },
        { name: 'required', message: 'This field is required' },
      ],
    }),
  ]
})
```
