### ISSUE TITLE
How to showing success validation messages? 

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#2948]
Hi Dear, 
For example we had create login form, once email validations successfull, I want showing success validation message for ex: your email is good, like that

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/703#issuecomment-364660359

**Comment by MaxKless** [comment]
That sounds like a job for a [custom wrapper](https://formly.dev/guide/custom-formly-wrapper). You can access the `FormControl` from there and show a validation message depending on the state of the control (for example when it is dirty).

Sadly, there is nothing like the `showError` attribute for validation that you could use, check out #2728 where I asked about that :D If you need it too, I'm sure @aitboudad would be glad to know.

**Comment by aitboudad** [comment]
Agreed, the custom wrapper would be the solution, from Formly side we may think to provide a solution out of the box or at least simplify it.

@MaxKless if #2728 would solve this issue too, go for it!

**Comment by aitboudad** [comment]
you may check the addon example as a starting point: https://formly.dev/examples/other/material-prefix-suffix.
