### ISSUE TITLE
error TS2739: Type 'AbstractControl' is missing the following properties from type 'FormControl'

### ISSUE THREAD

**Issue by instantgis** [ngx-formly/ngx-formly#2949]
I am using ngx-formly 6.0.0.next with material and Angular 12.

In trying to integrate "@stumpam/ngx-date-input": "^2.0.0" as a substitute to Angular Material's datepicker because the latter is giving me problems with its calendar panel (CDK overlay) showing up in the wrong places at times.

Here is my template for a custom "date" type

<ngx-date-input [formControl]="formControl"></ngx-date-input>

Here is the ts

import { ChangeDetectionStrategy, Component, OnInit, ViewEncapsulation } from '@angular/core';
import { FormControl } from '@angular/forms';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'ngx-formly-date',
  templateUrl: './ngx-formly-date.component.html',
  styleUrls: ['./ngx-formly-date.component.css'],
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class NgxFormlyDateComponent extends FieldType implements OnInit {
  constructor() {
    super();
  }
  ngOnInit(): void {
  }
}

ngc barks at me...

Error: libs/shared-ui/src/lib/formly-extensions/ngx-formly-date/ngx-formly-date.component.html:1:18 - error TS2739: Type 'AbstractControl' is missing the following properties from type 'FormControl': registerOnChange, registerOnDisabledChange, _applyFormState

  libs/shared-ui/src/lib/formly-extensions/ngx-formly-date/ngx-formly-date.component.ts:7:16
    7   templateUrl: './ngx-formly-date.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component NgxFormlyDateComponent.

I had gotten around this problem elsewhere in other custom controls before using this ugly hack...

in the component ts I add...
  fc: FormControl;

Then in ngOnInit I do this
    this.fc = this.formControl as FormControl;

In the template I bind to fc

<ngx-date-input [formControl]="fc"></ngx-date-input>

<ngx-date-input> does not show anyway when I do this but I am not asking about that.

I am asking why does this compiler error show up in the first place in 6.0.Next ?

 error TS2739: Type 'AbstractControl' is missing the following properties from type 'FormControl'

FieldType has formControl defined as 

get formControl(): import("@angular/forms").AbstractControl;

I never had this compiler error with 5.x

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1981#issuecomment-566027035

**Comment by jam-ayub** [comment]
<ngx-date-input [formControl]="$any(formControl)">

I made this change and it worked for me.

**Comment by AlMax** [comment]
Mate don't use $any(formControl), the error is in the extends, you must extend this class:
FieldType<FieldTypeConfig> and not just FieldType.

**Comment by prios-mbenyakoub** [comment]
> <ngx-date-input [formControl]="$any(formControl)">
> 
> I made this change and it worked for me.

Worked for me, thank you!

I know it is just a patch, it could be because of a migration between angular 14 and 15, my project didn't biuld.
