### ISSUE TITLE
Default value selection in anyof/oneof json schema

### ISSUE THREAD

**Issue by MonalisaPatnaik** [ngx-formly/ngx-formly#2952]
How to do the default value selection as **"Second method of identification"** ?

https://stackblitz.com/edit/angular-kybqqe-3x2shm?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
The default selection is based on the passed model and whether is valid or not, for example to select "Second method of identification" by default `idCode` needs to be present in model.

```ts
model = { idCode: null };
```

Are you looking for a manual selection?

**Comment by aitboudad** [comment]
> Are you looking for a manual selection?

For manual selection, you may use [map](https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527) option to set a default value for enum type https://github.com/ngx-formly/ngx-formly/blob/main/src/core/json-schema/src/formly-json-schema.service.ts#L324
