### ISSUE TITLE
Array value update at runtime between two model

### ISSUE THREAD

**Issue by MonalisaPatnaik** [ngx-formly/ngx-formly#2954]
Array value update at runtime between two properties

https://stackblitz.com/edit/angular-tm1wrq?file=src%2Fassets%2Fjson-schema%2Farrays.json

**Comment by aitboudad** [comment]
use `map` option https://stackblitz.com/edit/angular-tm1wrq-dh62ge?file=src/app/app.component.ts
Also see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
