### ISSUE TITLE
Native Material Stepper Step Errors

### ISSUE THREAD

**Issue by bakaproject** [ngx-formly/ngx-formly#2957]
Is it possible to use the native step error indicator on the material stepper? https://v9.material.angular.io/components/stepper/overview#error-state
![Screen Shot 2021-08-19 at 1 51 22 PM](https://user-images.githubusercontent.com/3053843/130134982-f36d777a-efc4-44ca-99fc-494fa30bceb6.png)

I can't find any examples with this working. I currently have a functioning stepper using ngx-formly with proper field and overall form validation. Does anyone have a working example of this?

To create my stepper I have a custom stepper component that takes a FormlyFieldConfig Array that has an array of FieldGroups that represent each step.

**Comment by aitboudad** [comment]
A proper solution will be added in the next version (see https://github.com/ngx-formly/ngx-formly/issues/2682)
For a workaround, you may create a custom pipe from your side which return the field error
https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/templates/formly.validation-message.ts#L20


you may also check our doc example for our multistep implementation https://formly.dev/examples/advanced/multi-step-form.
