### ISSUE TITLE
V6 private and non-existent data

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2959]
**Description**
I migrated to version v6, but the documentation does not address the problems I found and what is the solution

**Minimal Reproduction**

formlyField.form
![Captura de Tela_20210820095316](https://user-images.githubusercontent.com/11314585/130236539-537409b9-6035-48ac-ac42-4699fc85450f.png)

formlyField.model
![Captura de Tela_20210820095353](https://user-images.githubusercontent.com/11314585/130236541-f251b60c-b293-403f-b392-2f0e1ca75cd1.png)

**Comment by GlauberF** [comment]
I solved it using `formlyField?.field?.form?.touche` and `formlyField?.field?.model`

But I will use the issue to ask if anything has changed in the structure of what is sent in:
change: () => {}
expressionProperties: {}
hideExpression: ''

I have this concern, because I have a CMS and the formly structure is in the database, so if something has changed, I will see the error happening only by accessing screen by screen, where these structures and definitions are loaded from the database.

**Comment by aitboudad** [comment]
> I have this concern, because I have a CMS and the formly structure is in the database

do not worry about that part at all, if there will be any change in Formly structure we'll make sure to support the old syntax as well either by default or by using a custom extension.

**Comment by GlauberF** [comment]
Thank you very much :)
