### ISSUE TITLE
Cannot create fieldGroup via add() function - FieldArrayType

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#2962]
**Description**
I'm having a problem and I can't identify why this is happening. This was one of the problems that made me go to V6, however as it is still not recommended to send it to production, I went back to V5.

And I noticed that this happens when the object is nested and is large.

I have an addNewRow function, which internally I call this.add().

However, when calling it, it creates the new position in the model, but not in the formGroup.
This happens when you don't have any position in the formGroup yet, once you have one, it works normally.

my function.
```typescript
async addNewRow(event: MouseEvent, button: any, tooltip: any): Promise<void> {
        // Close tooltip
        (tooltip as any)?.hide();
        // Remove focus button
        (button as any)?.blur();
        // Assigns true to control variabl
        this._newRowClicked = true;
        // Create fields with Null value
        const _fieldNullable = (this.field?.fieldArray?.fieldGroup ?? ([] as any)).reduce((accumulator, actualElement) => {
            if(actualElement?.key) {
                accumulator[actualElement.key] = null;
            }
            return accumulator;
        }, {});
        // Add
        this.add(null, {
           ...(_fieldNullable ?? {}),
            _index: this.field.fieldGroup.length + 1,
            _focused: {}
        });

        this._removeLabelFields();
        this._checksDefaultFocusField();

        console.log('this.model: ', this.model);
        console.log('this.field.fieldGroup: ', this.field.fieldGroup);
        // (<any> this.options)._buildForm();
        // (<any> this.options)._markForCheck(this.field);
        // event.preventDefault();
    }
```

console output:
![Captura de Tela_selecionar área_20210820213156](https://user-images.githubusercontent.com/11314585/130304867-9bad95e2-887e-44cd-961b-2bcab54084fd.png)

![Captura de Tela_selecionar área_20210820213206](https://user-images.githubusercontent.com/11314585/130304871-f0174a48-7195-43ed-99cf-98c01e203141.png)

**Your Environment**
```
Angular CLI: 12.2.2
Node: 14.16.1
Package Manager: npm 6.14.12
OS: linux x64

Angular: 12.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1202.2
@angular-devkit/build-angular     12.2.2
@angular-devkit/build-optimizer   0.1101.4
@angular-devkit/core              12.2.2
@angular-devkit/schematics        12.2.2
@angular/flex-layout              12.0.0-beta.34
@nguniversal/builders             12.1.0
@nguniversal/express-engine       12.1.0
@schematics/angular               12.2.2
rxjs                              6.6.7
typescript                        4.3.5
```

<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Version to use?</strong></p>

Angular version | Formly version
-- | --
Angular >= 11 | @ngx-formly/core@6.x

It is recommended to use version v6 from Angular 11, but I can't use it, because in my tests and already report, it has some problems in V6.

**Comment by aitboudad** [comment]
I need more details here as I'm unable to reproduce it on my side, so probably the issue resides in `_removeLabelFields` function :thinking:

**Comment by aitboudad** [comment]
feel free to reopen once you've got a reproduction :pray:
