### ISSUE TITLE
Support for rows and cols in kendo text-area

### ISSUE THREAD

**Issue by sk0gen** [ngx-formly/ngx-formly#2963]
Support for rows and cols in kendo text-area

I'd like it to have same behaviour like bootstrap textarea component.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [5.10.23](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.23) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
