### ISSUE TITLE
Complex formly custom field

### ISSUE THREAD

**Issue by zarija-gavrilovic** [ngx-formly/ngx-formly#2964]
Does anyone know how to  create this type of custom formly component ?
You have radio buttons as label and different fields (primeng calendars) as options.
It should be required fields for both options. My major problem is validation.

First option:
![image](https://user-images.githubusercontent.com/58690622/130470142-1688c6ac-4d7c-4a41-9c81-34e05c6b82e2.png)

Second option:
![image](https://user-images.githubusercontent.com/58690622/130470442-5cd11721-ff0a-4c2a-bdac-3630534b6391.png)

Thanks :)

**Comment by aitboudad** [comment]
The custom type here is a set of fields (field1, field2), you may check the stepper type as starting example https://formly.dev/examples/advanced/multi-step-form
