### ISSUE TITLE
Custom validation does not work when loading field config asynchronously

### ISSUE THREAD

**Issue by hobojoe** [ngx-formly/ngx-formly#2965]
**Description**
I am using the "Matching Two Fields" example as a reference and if I load the field config asynchronously, the custom validation is not triggered.

See the stackblitz below:
https://stackblitz.com/edit/angular-gsrpnv?file=src/app/app.component.ts

Any suggestion on what I can do to make it work?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.27](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.27) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
