### ISSUE TITLE
Separate layout and json-schema

### ISSUE THREAD

**Issue by anuj9196** [ngx-formly/ngx-formly#2967]
**Question**
I'm using the following `json-schema` for the validation in the backend (Django).
```
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Schema for short answer",
  "type": "object",
  "required": ["matchKeywords"],
  "items": false,
  "properties": {
    "caseSensitive": {
      "type": "boolean",
      "default": false
    },
    "matchKeywords": {
      "description": "List of keywords to search against",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "minMatch": {
      "description": "Minimum number of correct matches required for the correct answer",
      "type": "number",
      "default": 1
    }
  }
}
```
In the frontend, I hit an endpoint that returns the above schema and wants to render forms as per the schema. This renders a basic form where no template specific data is provided.

Now, I want to have a separate JSON configuration for layout which bind the `key` with the JSON schema and defines the template specific properties like `className`, `placeholder`, etc.

Since the backend will be used by other application types (mobile app, etc.) I do not want to write template properties in the backend schema.

Is there a way to separate the layout configuration in case of using `json-schema`?

A clear and concise description of what the question is.

**Comment by kenisteward** [comment]
I currently do this on an internal library. There is no way to do it in
formly proper itself but it is slated for 6.0.0 to possibly be added.

@aitboudad can confirm on that.

**Comment by aitboudad** [comment]
> @aitboudad can confirm on that.

I confirm :pray:!

@anuj9196 you can easily do a manual merge using the following function [mergeFields](https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/json-schema/src/formly-json-schema.service.ts#L551)
