### ISSUE TITLE
Add class to <label> attribute

### ISSUE THREAD

**Issue by anuj9196** [ngx-formly/ngx-formly#2968]
**Question**
I want to pass a class to the `<label>` element
```
<label class="form-control-label">Answer Type</label>
```
Following is my field config
```
export const field = [
  {
    key: "minMatch",
    type: "number",
    templateOptions: {
      placeholder: "Number of minimum matches required",
      label: "Minimum Match",
    }
  }
];
```
 How can I pass a class for the `label` element?

Also, the description for `templateOptions` in the documentation states
> This is reserved for the templates. Any template-specific options go in here. Look at your specific template implementation to know the options required for this.

Where to look for the template options?

I also tried creating a custom input field like
```
import {FieldType} from "@ngx-formly/core";
import {Component} from "@angular/core";
import {FormControl} from "@angular/forms";

@Component({
  selector: 'formly-field-input',
  template: `
    <label class="form-control-label" *ngIf="to.label" [htmlFor]="field.id">{{to.label}}</label>
    <input type="input" class="form-control form-control-sm" [formControl]="formControl" [formlyAttributes]="field">
  `
})
export class InputTypeComponent extends FieldType {
  formControl: FormControl;
}
```
But then it is showing two labels.

![Screenshot 2021-08-29 at 3 20 51 AM](https://user-images.githubusercontent.com/6560085/131231938-2e23b0c9-20b0-4748-81f9-695419faf45f.png)

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1494#issuecomment-551655615

**Comment by aitboudad** [comment]
> Where to look for the template options?

if you're using a custom field type, you can pass extra option to `templateOptions`:

```patch
export const field = [
  {
    key: "minMatch",
    type: "number",
    templateOptions: {
      placeholder: "Number of minimum matches required",
      label: "Minimum Match",
+     labelClass: "customClass"
    }
  }
];
```

```patch
<label *ngIf="to.label"
  class="form-control-label"
+ [ngClass]="to.labelClass"
  [htmlFor]="field.id"
>
  {{to.label}}
</label>
```

**Note**: `to` is a shortcut of `field.templateOptions`.
