### ISSUE TITLE
Disable other checkbox in array field

### ISSUE THREAD

**Issue by anuj9196** [ngx-formly/ngx-formly#2969]
**Question**
I want to create a form with array fields where only one value has to be selected and other values will be disabled.
![Screenshot 2021-08-30 at 11 07 37 AM](https://user-images.githubusercontent.com/6560085/131290347-e940dd5e-d092-41e6-833b-81bb9d6d2ca2.png)

There can be only one `isCorrect` checkbox checked.

Following is the schema 
```
export const multipleChoice = [
  {
    key: "choices",
    type: "array",
    fieldArray: {
      fieldGroup: [
        {
          key: "value",
          type: "input",
          templateOptions: {
            placeholder: "Value",
            label: "Value",
            required: true
          }
        },
        {
          key: "isCorrect",
          type: "checkbox",
          defaultValue: false,
          templateOptions: {
            label: "Is Correct?"
          },
          expressionProperties: {
            'templateOptions.disabled': '!model.value',
          },
        }
      ]
    }
  }
];
```

**How can the other checkboxes be disabled when there is one selected and enable all checkboxes for selection when unchecked?**

**Comment by aitboudad** [comment]
Two solutions:
- using expressionProperties: https://stackblitz.com/edit/angular-vs9soe
- subscribe to `valueChanges` and update the disabled state of each field https://formly.dev/examples/advanced/repeating-section-input
