### ISSUE TITLE
ExpressionProperties between individual formly field usage

### ISSUE THREAD

**Issue by Greegko** [ngx-formly/ngx-formly#2977]
I am using formly for certain case, when I do not use the form predefined structure, just want to use an individual field, as it contains everything what I need, like validations, but let me to have more dynamic template structure.

I have one extra component, like: 

`<app-single-formly-field [value] (valueChange) [fieldConfig] [state?] />`

Which will create one formly field but wrappered by formly-form. Couldn't use `formly-field` directly, as it doesn't fire `expressionProperties` evaluation and validations. (Is there any way to do it without formly-form ?)

I would like to connect 2 individual fields, to use the expression properties and the validations. Is there any way to have those 2 in one model / one state ?

I tried to use formGroup settings for the field and for the formly-form, but it doesn't seem to have any effect. Also tried to inject the formGroup via directive (`[formGroup]="group"`), but in the end both cases they won't store in one model, but in 2 individual ones.

**Comment by Greegko** [comment]
Created an example, maybe that helps a bit: https://stackblitz.com/edit/angular-xm4ucn-2cunn1

**Comment by Greegko** [comment]
After some investigation, didn't find a proper solution, where the fields are not rendered, but only in template.

One of the attempt was something like this:
```
<div formlyForm>
  <formly-field [field]="dateFieldConfig"></formly-field>
  [Nasty custom template]
  <formly-field [field]="typeFieldConfig"></formly-field>
</div>
```

I tried to make a directive, where the `[formlyFrom]` just collects all content, and initializing the form skeleton (expressionProperties and other validations), but not render the fields yet. Wasn't success without altering the current implementation, as I couldn't override `formly-form` class implementation via inheritance.

At the moment I solved it with sharing the state like:
```
<app-single-formly-field #dateField [value] (valueChange) [fieldConfig] [state?] />
<app-single-formly-field [value] (valueChange) [fieldConfig] [state]="{ selectedDate: dateField.value }" />
```

which works fine, but was hoping for more straightforward solution, as merging 2 forms models somehow.

If you have any advice about the solution let me know, maybe I didn't find something clever feature which would help in my case.

PS: Are you planning to support dynamic template solutions ?

**Comment by kenisteward** [comment]
In v6 you will be able to override template quite easily. This include base
types like formly-field / formly-group.

As for what you are looking for, could you give the use case directly so I
can better understand and hopefully provide some insight? I'm not exactly
following what you are trying to do.

**Comment by Greegko** [comment]
> As for what you are looking for, could you give the use case directly so I
can better understand and hopefully provide some insight? I'm not exactly
following what you are trying to do.

I have created an example for it:

> Created an example, maybe that helps a bit: https://stackblitz.com/edit/angular-xm4ucn-2cunn1

I have two forms, and they should have an interaction between them, in this case expressionProperties evaluation or validation. In the code example, each field is a form itself due to the implementation, but the question still applies to them, how they can see each other through configuration and not external component based implementation. 
```
    expressionProperties: {
      'model1.echo_input': 'model2.hello_input',
    }
```

**Comment by aitboudad** [comment]
To get rid of `formly-form` I see two missing parts:
- Build field (you can use FormlyFormBuilder service) (we're looking to make it optional in `v6`)
- A parent component or a directive is needed to connect those fields (or manually) then call [checkExpressions](https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/components/formly.form.ts#L94) for each field

I do prefer to use `V6` which simplifies the process as we're trying to make rendering one field possible but still in progress.

**Comment by Greegko** [comment]
It seems I made a mistake when I was assigning the `model` and `formGroup` to the individual fields, and now it works when I am using the same model across the fields. Thanks, my mistake.

Waiting for V6, thanks for the hard work!
