### ISSUE TITLE
Dependent dropdowns data using API requests

### ISSUE THREAD

**Issue by saswatpatro** [ngx-formly/ngx-formly#2978]
I have a use case where I have a dropdown whose data is being populated using an API request done to the backend.
Now I have another dropdown whose data depends on the value selected in the previous dropdown.
In simple words, I need to do an API call after I select the 1st dropdown's data so that I can fetch the data for the 2nd dropdown using the value selected in the 1st one!
How can I achieve this using formly?

Thanks in advance!

**Comment by shorbagyDH** [comment]
You can achieve this by following this example in the docs: https://formly.dev/examples/other/cascaded-select, it's the exact case you try to achieve. you just need in `valueChanges` to use `(switch|concat|merge)Map` for your API Request observable and populate the fields.

**Comment by mohamedelshorbagy** [comment]
You can achieve this by following this example in the docs: https://formly.dev/examples/other/cascaded-select, it's the exact case you try to achieve. you just need in valueChanges to use (switch|concat|merge)Map for your API Request observable and populate the fields.

**Comment by saswatpatro** [comment]
Thanks @mohamedelshorbagy for the quick reply.
I tried this solution but how do I call a service on click of a dropdown..in this example data is already present which is being filtered but I want the data coming from a backend API.
Could you please help me with an example!

**Comment by mohamedelshorbagy** [comment]
Here is an example I excluded the whole data into a service and returning `Observable` Type from all functions to emulate an http request so you can try to adjust it with your needs.
https://stackblitz.com/edit/angular-ipev6a?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
to adjust the loaded JSON form you may use a map function, check JSON powered https://formly.dev/examples/other/json-powered
