### ISSUE TITLE
ExpressionProperties model change doesn't trigger modelChange event

### ISSUE THREAD

**Issue by Greegko** [ngx-formly/ngx-formly#2980]
I am building the form and having the validation and synchronization between them in the form config via expressionProperties. Noticed, when model updated via this option, the event is not fired.

Example: https://stackblitz.com/edit/angular-xm4ucn-uiden7

**Comment by aitboudad** [comment]
we may end into in circular calls :thinking: :

1- model-changes fired execute expressions (step 2)
2- expressions fire model-changes (step 1)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [5.10.23](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.23) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
