### ISSUE TITLE
Cascading select list inside repeater loading model from database

### ISSUE THREAD

**Issue by rc201612** [ngx-formly/ngx-formly#2981]
Hi, 

I'm looking for some help loading an existing form from JSON in Edit Mode. 

The behaviour I am seeing can be seen in the below stackblitz example. 

https://stackblitz.com/edit/angular-n7s2u6-say9fe?file=src%2Fapp%2Fapp.component.ts

Here I am setting the default model up with some default values. However, these values are being lost when I click "Add another sport". Is this desired behaviour supported? What am I missing? 

Thanks you for any help!

Attached video also for reference:

https://user-images.githubusercontent.com/18450631/133105191-4e1cb60b-1ef5-481e-ad03-c92c7afedb82.mp4

**Comment by aitboudad** [comment]
use `distinctUntilChanged` see https://stackblitz.com/edit/angular-n7s2u6-fpvx7i?file=src/app/app.component.ts

**Comment by rc201612** [comment]
This already has a `distinctUntilChanged` as per the example you posted. 

The issue is that when there is a default model they are being ignored somehow

**Comment by aitboudad** [comment]
seems `distinctUntilChanged` should be added after `startWith`, use the following solution instead:

```ts
onInit: field => {
  const teams = [...];

  const sportControl = field.form.get('sport');
  field.templateOptions.options = sportControl.valueChanges.pipe(
    startWith(sportControl.value),
    distinctUntilChanged(),
    map(sportId => {
      const options = teams.filter(team => team.sportId === sportId);
      if (!options.find(option => sportId === option.id)) {
        field.formControl.setValue(null);
      }

      return options;
    }),
  );
}
```
