### ISSUE TITLE
Can't Duplicate Value in Nested Form Field

### ISSUE THREAD

**Issue by devbyray** [ngx-formly/ngx-formly#2984]
**Question**
I'm a longtime Formly user and lover 😁! So thanks for building and maintaining this project 👍

But I want to duplicate the value of a form in another form field. That is working, but as soon as I put a wrapper around it (a custom wrapper), the `expressionProperties` won't work.

Hopefully, someone can see the problem in my code ([stackBlitz](https://stackblitz.com/edit/angular-mjengs-j9qozc?file=src%2Fapp%2Fapp.component.ts)). Because I can't see the problem.

Thanks in advance! 🙏

**Comment by devbyray** [comment]
I think I found out why. When checking what's inside `model`, it looks like it refers to model to the nested property automatically 😅

https://stackblitz.com/edit/angular-mjengs-s9f8lq?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
could you please try with: `field.parent.model`, may related to https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614

**Comment by aitboudad** [comment]
> I'm a longtime Formly user and lover grin! So thanks for building and maintaining this project +1

:pray:
