### ISSUE TITLE
Dynamically setting the model inside expressionProperties

### ISSUE THREAD

**Issue by austalakov** [ngx-formly/ngx-formly#2985]
**Description**
I am trying to do something very similar to the "Cascaded Select JSON powered" example, but instead of clearing down the `model`, I want to set it to a specific value. What seems to happen is, the model itself is set to the specified value, but the select field does not adjust to reflect it - as can be seen below.

I realize that in this specific example, setting the model value to `1` should work only 50% of the time - I would expect when switching from `Basketball` to `Soccer`, that `Bayern Munich` (team with `id 1`) should be selected, but obviously not when switching the other way around.

![image](https://user-images.githubusercontent.com/32936040/133795403-517f81e6-6e87-45ed-bb52-23f14450a156.png)

**Minimal Reproduction**

https://stackblitz.com/edit/angular-ddn2tf?file=src/app/app.component.ts

**Your Environment**

- Angular version: 10.1.6
- Formly version: 5.10.22

**Comment by aitboudad** [comment]
fixed by #2982

**Comment by aitboudad** [comment]
Seems not related to the above issue, `model.team` expect a string value rather than int:

```patch
- 'model.team': `field.templateOptions.options.find(o => o.id === model.team) ? model.team:1`,
+ 'model.team': `field.templateOptions.options.find(o => o.id === model.team) ? model.team:"1"`,
```

**Comment by austalakov** [comment]
Just for completenes - while the above was the error with the minimal reproduction attempt I made, the actual error in my real code was that I was missing the `ReactiveFormsModule` import.
