### ISSUE TITLE
Drag N Drop Form Builder feature available?

### ISSUE THREAD

**Issue by weilies** [ngx-formly/ngx-formly#2987]
Is there any DND form builder like 
https://formbuilder.online/ or https://formio.github.io/angular-demo/#/forms/builder
Both are very powerful in building a new form. But i am having challenge integrate into my angular app.

I know how to build ng forms (via code) but i am looking for a package allowed me to build the form JSON schema and save into DB, and later call out to collect response from user. Does ngx-formly provide such builder?

i ain't lookin for a solution to manually input JSON but to auto-gen the JSON via builder.

**Comment by aitboudad** [comment]
I'm working on it, a beta version will be available around December.

For now, you may check https://github.com/franzeal/ngx-formly-designer
or https://github.com/ngx-formly/ngx-formly/issues/1456#issuecomment-469894882

**Comment by smartsense-as** [comment]
> I'm working on it, a beta version will be available around December.
> 
> For now, you may check https://github.com/franzeal/ngx-formly-designer or [#1456 (comment)](https://github.com/ngx-formly/ngx-formly/issues/1456#issuecomment-469894882)

Does this project support Radio Group or is there a way for me to add it?

**Comment by aitboudad** [comment]
> Does this project support Radio Group or is there a way for me to add it?

you can create a custom type by following our guide https://formly.dev/guide/custom-formly-field in case it doesn't exist

**Comment by smile2014** [comment]
@aitboudad   https://github.com/ADCSD/formbuilder

**Comment by smile2014** [comment]
https://swimlane.github.io/ngx-dnd/builder#builder-demo

**Comment by venkateshwarans** [comment]
> I'm working on it, a beta version will be available around December.
> 
> For now, you may check https://github.com/franzeal/ngx-formly-designer or [#1456 (comment)](https://github.com/ngx-formly/ngx-formly/issues/1456#issuecomment-469894882)

Is there any update on this? Any other latest one that is compatible with newer angular versions would also be helpful. Thanks.

**Comment by smile2014** [comment]
https://github.com/alibaba/x-render

**Comment by smile2014** [comment]
@aitboudad   https://github.com/alibaba/x-render

**Comment by lscavelli** [comment]
> > Questo progetto supporta Radio Group o c'è un modo per aggiungerlo?
> 
> puoi creare un tipo personalizzato seguendo la nostra guida https://formly.dev/guide/custom-formly-field nel caso non esista

use ngx formly => https://jacksloan.github.io/ng-dnd-form-builder/form-builder-material

**Comment by lscavelli** [comment]
> > Ci sto lavorando, una versione beta sarà disponibile intorno a dicembre.
> > Per ora, puoi controllare https://github.com/franzeal/ngx-formly-designer o [#1456 (commento)](https://github.com/ngx-formly/ngx-formly/issues/1456#issuecomment-469894882)
> 
> C'e 'qualche aggiornamento su questo? Anche qualsiasi altro ultimo compatibile con le versioni angolari più recenti sarebbe utile. Grazie.

use ngx formly => https://jacksloan.github.io/ng-dnd-form-builder/form-builder-material

**Comment by klocus** [comment]
https://github.com/sesan07/formly-editor
