### ISSUE TITLE
FieldArrayType with table structure doesn't render the table's rows and column correctly. 

### ISSUE THREAD

**Issue by sranjan-m** [ngx-formly/ngx-formly#2988]
**Description**
I extended FieldArrayType to create a custom control which is in table tr and td format. But the columns and rows aren't rendered as expected.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ivy-v9sk3u

**Your Environment**

- Angular version: 12.0.0
- Formly version: 5.0.0

**Additional context**
**_Expected rendering :_**

![image](https://user-images.githubusercontent.com/18301541/134541228-83d82509-5e8f-41b6-a094-d6cc5d075559.png)

Unable to get the expected result. Tried using ngFor in both tr and td, which is not an expected result.

![image](https://user-images.githubusercontent.com/18301541/134541705-99b84a41-59be-4325-9835-db9e58d1310b.png)

I don't find a way to render the table as expected. Please somebody help.
Thanks.

**Comment by kenisteward** [comment]
You have to use classes that will add the necessary styles for your rows.
This is shown in the docs here

https://formly.dev/examples/bootstrap-specific/advanced-layout

Otherwise in your component itself you need to loop over the fields in each
field group itself for a particular row for the object.

**Comment by sranjan-m** [comment]
@kenisteward Thanks for your quick response.

What do you mean by "need to loop over the fields in each field group itself for a particular row for the object"?
I have only 3 columns here and the values are loaded correctly, but the way it renders the table is quite awkward. It puts all the properties of the model either in columns or rows as you can see in the attached image (2nd one).

If you think "looping over the fields in each field group itself for a particular row for the object" would work, can you please help me with this? It'll be really helpful.

Thanks.

**Comment by kenisteward** [comment]
@sranjan-m 

Solution using the array component itself. only downfall doing this is it is specifically programmed to an array of objects only.
https://stackblitz.com/edit/angular-ivy-vxvawr?file=src%2Fapp%2Fcustom-table%2Fcustom-table.type.ts

**Comment by sranjan-m** [comment]
Thanks a lot @kenisteward 
Will try to implement the same in our actual project and try.
Thank you.

**Comment by sranjan-m** [comment]
What if I want a column to display as a label instead of a formly-field? Is it possible?
For example, I want to display the name as a label. Address and Number can be modified by user.
Binding the model to the label shows [object Object] instead of the value from the model, may be it's because label is not an user input field or it's not a form control? Not sure.

Is there a way to bind the model to a label?

**Comment by sranjan-m** [comment]
Found a solution by tweaking around my custom label control to load from the model.
```
<label class="{{to.className}}"
  *ngIf="to.type && to.type == 'label'">
  {{to.label}}
</label>
<label class="{{to.className}}"
  *ngIf="to.type && to.type == 'model'">
  {{formControl.value}}
</label>
```

**Comment by sranjan-m** [comment]
Just a suggestion, may be the formly dev team should include a "label" control in ngx-formly with more options.
It's an awesome component and Thanks.

**Comment by aitboudad** [comment]
> Found a solution by tweaking around my custom label control to load from the model.

another solution is to use `expressionProperties`:

```ts
'expressionProperties': {
  'templateOptions.label': 'field.formControl.value',
},
```

**Comment by sranjan-m** [comment]
Thanks @aitboudad 
Your solution is much easier.

**Comment by sranjan-m** [comment]
> @sranjan-m
> 
> Solution using the array component itself. only downfall doing this is it is specifically programmed to an array of objects only. https://stackblitz.com/edit/angular-ivy-vxvawr?file=src%2Fapp%2Fcustom-table%2Fcustom-table.type.ts

After upgrading to formly v6, it fails at `<th *ngFor="let tHead of fieldConfig.fieldArray.fieldGroup">`

How to get the `fieldGroup` from `fieldConfig.fieldArray` with the new implementation?
