### ISSUE TITLE
Is there any expansion panel solution?

### ISSUE THREAD

**Issue by a2928897** [ngx-formly/ngx-formly#2995]
Hi is ngx-formly have any expansion panel solution?
I have a large form, it's hard to read.
So I need a expansion panel or something like this.
like material ["expansion panel" ](https://material.angular.cn/components/expansion/overview#expansion-overview)
material tab solution is fine, but not suit enough on this situation.

Thanks a alot.

UI:Material

**Comment by sranjan-m** [comment]
You could try to create a custom control by extending `FieldType` or you can create a custom wrapper too.

**Comment by aitboudad** [comment]
Just follow one of the following examples and you'll be able to do it:

- https://formly.dev/examples/advanced/multi-step-form
- https://formly.dev/examples/advanced/tabs
