### ISSUE TITLE
Add new element to FieldArray with value from parent's model

### ISSUE THREAD

**Issue by sranjan-m** [ngx-formly/ngx-formly#2996]
**Question**

I have extended FieldArrayType to create a custom table control and want to add a new row to model on button click. I'm aware of using the add() & remove() function of FieldArrayType, but as per our project's requirement I'm facing some problem while doing so.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ivy-tqbny1

As per the above reproduction link, the model is something like the following.

```
this.model = {
  TrainingDetails: {
    _id: '10001',
  },
  Participants: [
    {
      TrainingId: '10001',
      Name: 'David',
      Address: 'Mexico',
      Number: '123456',
    },
    {
      TrainingId: '10001',
      Name: 'Stefan',
      Address: 'LA',
      Number: '456856',
    },
  ],
};
```

**Problem that I'm facing**
1. When using add() it adds an empty row, but I want to add the new row with _id from `model.TrainingDetails._id` as `TrainingId` (same as in each object of `model.Participants`). Is there a way how can I extend the add() method of FieldArrayType to achieve this or is there any workaround to do this?
2. If the above could be possible then I would like to create a custom button control and would want to handle the add() and remove() from a configurable button control. 

But for now I just want to achieve No. 1 first and then explore improvising it as per No. 2.
Any help, reference or suggestion will be really helpful.

Thanks!

**Comment by sranjan-m** [comment]
Is there a way to do it? Really waiting for help.

**Comment by kenisteward** [comment]
You have everything you need in the stackblitz,. A quick look at the add method for the field array type shows all you need to do is pass add(null, starterModel)  to get baseline data.  How you decide you want to get your starter data is up to you.  I'd probably just add a templateOption called "initialAddData" that is a string that represents the expression you want to use to create the add data.  Then override the add function to do that expression before calling super.add()

As an aside, we try to get the questions as soon as we can.  Please have patience!

**Comment by sranjan-m** [comment]
Hi @kenisteward Thanks for your response.
Where to add the templateOption? Inside fieldGroup of fieldArray? And how to access it from the overridden add function?

**Comment by sranjan-m** [comment]
Tried putting expressionProperties in fieldGroup of fieldArray to access the parent model, but unable to access it. Hence while adding a new row it doesn't add to the fieldArray's model.

**Comment by kenisteward** [comment]
https://stackblitz.com/edit/angular-ivy-ff8j1z?file=src%2Fapp%2Fapp.component.ts

See the fork.  You can make it simpler if the data is supposed to be static all the time by just setting it on formState and directly using it in the component.

**Comment by sranjan-m** [comment]
Thanks @kenisteward 
I wasn't aware about `defaultModelExpression` until now and have been struggling with `expressionProperties`.
I have a question though. Noticed the `evalExpression` function and it's not being used. What's the purpose of this function or in which scenario we need it?

Thank you so much.

**Comment by kenisteward** [comment]
> Thanks @kenisteward 
> I wasn't aware about `defaultModelExpression` until now and have been struggling with `expressionProperties`.

This is a field I made up to get what you needed. Formly is very customizable so you don't have to only use what is given. You can think of template options as a generic configuration that can be extended just by passing data.


> I have a question though. Noticed the `evalExpression` function and it's not being used. What's the purpose of this function or in which scenario we need it?

I was making a generic function that accepts any string and evaluates it as JavaScript. Unless you are doing this often in your types you don't need it. Just a leftover artifact
