### ISSUE TITLE
how to upload local images using angular formly

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#2997]
I had creating a one shopping product upload form, i want upload local images to mongodb using angular formly, please give reference .... 

Thanks in advance.

**Comment by kenisteward** [comment]
I'm assuming this is what you need which is linked in our docs.
https://stackblitz.com/angular/kbknmvyayxp?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
https://formly.dev/examples/other/input-file
