### ISSUE TITLE
Cannot read properties of undefined (reading 'length') - Stacktrace: TypeError: Cannot read properties of undefined (reading 'length')     at FieldExpressionExtension.toggleFormControl

### ISSUE THREAD

**Issue by preeteeg** [ngx-formly/ngx-formly#2998]
**Description**

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: 11
- Formly version: 5.10.22

**Additional context**
When using a select dropdown to hide some fields  i have make use the hideExpression , i have the following error Cannot read properties of undefined (reading 'length') - Stacktrace: TypeError: Cannot read properties of undefined (reading 'length')
    at FieldExpressionExtension.toggleFormControl
Thank you for your kind response

**Comment by aitboudad** [comment]
The issue has been fixed in [5.10.23](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.23)

**Comment by preeteeg** [comment]
@aitboudad
Hi thank you for your response. Indeed it works with this version . Good day to you
