### ISSUE TITLE
Issues when editing a previously stored DateTime value using Nebular DateTime picker 

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#3000]
⭐⭐⭐⭐⭐
**Question**

I am using Nebular theme and trying to integrate one of their newer features that  support Date and Time in the same datepicker component. (nb-date-timepicker)

While I have been able to integrate it, I am able to save the form to the backend with no issues.
I am also able to retrieve the value back and display it within the field / form.

I am running into issues when I try to edit the value in the field which invokes the nebular component where in it fails to pass the  time portion back to the picker.

I was wondering if this scenario was supported in ngx-formly?

I can try to put together a stackblitz around the scenario.

Thanks

**Comment by aitboudad** [comment]
The simplest way is to adjust the model before passing it to the `formly-form` component.

> I can try to put together a stackblitz around the scenario.

yes, please.
