### ISSUE TITLE
Show placeholder text/html when a field is hidden using hideExpression

### ISSUE THREAD

**Issue by freon27** [ngx-formly/ngx-formly#3002]
Hi,

Is there a way to show a placeholder when a field is hidden using hideExpression?  

Instead of the field just disappearing and the position of the remaining fields changing, I would like to replace it with some text or an icon.

Thanks in advance

**Comment by aitboudad** [comment]
just define an additional field alongside the hidden one, and display it instead:

```ts
[
  {
    key: 'firstname,
    hideExpression: 'model.hideFirstname',
    ...
  },
  {
    hideExpression: '!model.hideFirstname',
    ....
  },
]
```

for a generic way, you may use a custom extension.
