### ISSUE TITLE
WCAG A 4.1.2: Required fields not read as required.

### ISSUE THREAD

**Issue by tanvir2991** [ngx-formly/ngx-formly#3009]
OS: Android

Principle: Robust

Guideline/Success criterion: https://www.w3.org/TR/WCAG21/#name-role-value

Testing details:

Assistive technology/tool used: Talkback

Browser: Chrome

Test prerequisites: 	

Go to Settings->Convenience tool->Accessibility->Talkback(Enable talkback)

Flick your finger right to browse through the screen and listen to whether talkback reads all the elements properly in sequential order.

Issue description: 

Talkback simply reads the field labels without mentioning them as required fields.

Example : https://stackblitz.com/edit/formly-example

#3028

**Comment by aitboudad** [comment]
The best approach I think is to include `required` in the label. So instead of adjusting the required marker "*" in our codebase, use a custom extension to add `required` to all fields.
Here is an example https://stackblitz.com/edit/angular-q4dwsz?file=src/app/app.module.ts

**Comment by h-arora** [comment]
> The best approach I think is to include `required` in the label. So instead of adjusting the required marker "*" in our codebase, use a custom extension to add `required` to all fields. Here is an example https://stackblitz.com/edit/angular-q4dwsz?file=src/app/app.module.ts

including required in the label is not always an option as it leads to an entire UX change.

**Comment by aitboudad** [comment]
I'm open to any good solution, the proposed fix https://github.com/ngx-formly/ngx-formly/pull/3028 has two points that need to be addressed:

- set aria-hidden on Android only (target only one specific devise)
- target one language (English app only)
