### ISSUE TITLE
When value change the value inside the validation save the original value

### ISSUE THREAD

**Issue by matishwlocusview** [ngx-formly/ngx-formly#3011]
**Description**
When validator compares data to an external variable, it seems to cache/store the variable value. Changing the variable value does not change the validation.

**Minimal Reproduction**
Using the supplied example in the documents we simply pass in an external variable for the comparison
https://stackblitz.com/edit/angular-7acd51?file=src/app/app.component.ts

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.1

**Comment by aitboudad** [comment]
use one of the following solutions:

- use object: https://stackblitz.com/edit/angular-7acd51-tbh6gu
- assign the new value to field: `this.fields[1].validation...options = 3`
- use formState: https://formly.dev/examples/form-options/form-state
