### ISSUE TITLE
Calendar open  in formly 

### ISSUE THREAD

**Issue by prachi23S** [ngx-formly/ngx-formly#3016]
**Description**
Is it possible to open the calendar, clicking on everywhere in the input field of formly?

**Your Environment**

- Angular version: 8.3.20
- Formly version: 5.9.3
![calender](https://user-images.githubusercontent.com/92859730/138235504-f60970b8-147d-4151-a103-0a9c855e8d33.PNG)

Can someone suggest any solution for this

@aitboudad

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-meffkb
