### ISSUE TITLE
Should not scroll down after opened formly dropdown

### ISSUE THREAD

**Issue by kashidP** [ngx-formly/ngx-formly#3018]
I am using ngx-formly.
when I open the drop-down and scroll down the page then these dropdown options also get shifted down .

![dp](https://user-images.githubusercontent.com/92910019/138242718-845a7669-9c63-4cd4-9e25-e74fea3fce5b.png)

Can anyone suggest the root cause here?

**Comment by aitboudad** [comment]
I thought you're using Angular Material, so passing `disableOptionCentering` won't work, you may check ng-select doc and look at which option provides a similar behavior.
