### ISSUE TITLE
Formly warning issue

### ISSUE THREAD

**Issue by prachi23S** [ngx-formly/ngx-formly#3019]
**Description**
formly warning issue

Sometimes the warnings are coming in misaligned (Strike through  on warnings) 
![image](https://user-images.githubusercontent.com/92859730/138235251-4e711c51-818b-4d44-8534-6b2f172bf133.png)

**Your Environment**

- Angular version: 8.3.10
- Formly version: 5.3.9
Can someone suggest any solution here 

@Abdellatif Ait boudad

**Comment by aitboudad** [comment]
Hi,
could you please please provide a reproduction using our starter example:
https://stackblitz.com/edit/ngx-formly-ui-material

Thanks!
