### ISSUE TITLE
hintEnd not works as expected. render nothing.

### ISSUE THREAD

**Issue by jon9090** [ngx-formly/ngx-formly#3020]
**Description**
`hintEnd` not works as expected. I put a string content or `templateRef`, but the field doesn't render it.

I searched in `node_modules` in `ngx-formly` for keyword `hintEnd` but got no results. under `webpack:///./node_modules/@ngx-formly/material/fesm2015/ngx-formly-material-form-field.js` I have code without any `hintEnd` there. I have only `<mat-hint *ngIf="to.description" [id]="null" ...>...`

It's seems the last version doesn't have the content of the source file.
https://github.com/ngx-formly/ngx-formly/blob/60bece9b9dd4e1719bb6cdf3e49d804453438fb3/src/ui/material/form-field/src/form-field.wrapper.ts#L80

**Minimal Reproduction**
```

 fields: FormlyFieldConfig[] = [
    {
      key: 'Textarea',
      type: 'textarea',
      templateOptions: {
        label: 'Textarea',
        placeholder: 'Placeholder',
        description: 'Description',
        required: true,
        hintEnd: 'blabla',
      },
    },
  ];

```
https://stackblitz.com/edit/angular-cuknck?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 12.2.10
- Formly version: ^5.10.23

**Additional context**

**Comment by aitboudad** [comment]
available in `V6` only: https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.1

**Comment by kernokus** [comment]
Hello. I ran into a similar problem with the library version 5.10.32 as well. However, we are not able to migrate to the 11th version of the angular yet. Please tell me how we can work around this and add a hint in the library version 5.10.32? Can we ask you to add this functionality to version 5 of the library? Thank you very much
