### ISSUE TITLE
fields hidden using hideExpression and bootstrap set to col-X take up space even while hidden (bootstrap)

### ISSUE THREAD

**Issue by seiyria** [ngx-formly/ngx-formly#3024]
**Description**
When using `hideExpression`, bootstrap, and column classes, the parent element containing the `<formly-wrapper-form-field>` gets the `col-4` attribute, meaning that when `hideExpression` is true, the element still takes up empty space, leading to awkward gaps.

![image](https://user-images.githubusercontent.com/763609/138560462-f8b32355-8a3d-4069-8239-734905153281.png)

![image](https://user-images.githubusercontent.com/763609/138560455-568cf275-793f-4280-b72f-32857d04168d.png)

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-zruupx (unfortunately I could not get it to run the code, but this is the code I'm using if stackblitz works for others)

**Your Environment**

- Angular version: 12.2.0
- Formly version: 5.0.0

**Comment by aitboudad** [comment]
Without  a reproduction, I can't guess where the issue resides, feel free to reopen once you've got a reproduction :pray:

**Comment by seiyria** [comment]
Unfortunately I have no idea why stackblitz isn't working, but I do have code that reproduces it: 

- https://github.com/MagicConnect/content/tree/master/frontend is the project
- https://github.com/MagicConnect/content/blob/master/frontend/src/app/components/ability-effect-form/ability-effect-form.component.ts is the component that shows it
- if you run the project, go to characters, new, add ability, add effect, and change the dropdown "effect type"

**Comment by aitboudad** [comment]
I'm able to reproduce it, will provide a fix soon!

**Comment by seiyria** [comment]
any idea when this will make it to a tagged release @aitboudad? or is there any release I can get to use this fix? :D

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.24](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.24) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by seiyria** [comment]
Thanks! It looks like it's all working.
