### ISSUE TITLE
i want apply password visible icon or checkbox, how to impliment please guide me?

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#3025]
{
      key: 'password',
      type: 'input',
      templateOptions: {
        type: 'password',
        label: 'Password',
        placeholder: 'Password ...',
        required: true,
      },
      validation: {
        messages: {
          required:'Password must be required ',
        },
      },
    }

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/3031#issuecomment-960669637
