### ISSUE TITLE
clear selection for 'select' type in formly

### ISSUE THREAD

**Issue by EjazIris** [ngx-formly/ngx-formly#3026]
If user accidently select any option from the drop down, and later wants clear its selection , how can I achieve this requirement in select type field in Angular Formly.
can you please suggest a solution for this. @aitboudad 

https://stackblitz.com/edit/angular-ugbqbg?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
I see two solutions for that:

1- Add an extra empty option:

```patch
options: [
+ { value: null, label: '' },
  { value: 1, label: 'Option 1' },
  { value: 2, label: 'Option 2' },
  { value: 3, label: 'Option 3' },
],
```
2- add clear button by using material suffix https://formly.dev/examples/other/material-prefix-suffix
