### ISSUE TITLE
How to handle several fields with the same key of the other formFields?

### ISSUE THREAD

**Issue by CanopusTest3** [ngx-formly/ngx-formly#3030]
**I want to use same value for the "**meet**" which is available in two nested formFields**
If someone add meet = "Hotel" then other field should auto filled  meet = "Hotel". I am using them with mat-tabs angular.

`fields: FormlyFieldConfig[] = [{
  type: 'tabs',
  fieldGroup: [
    {
      key:1,
      id:'contact_mail',
      templateOptions: { 
        label: 'Basic',
        attributes:{isEdit:0}
      },
      fieldGroupClassName: 'row ml-1 pb-3',
      fieldGroup: [

        { 
          className: 'col-lg-8 col-md-8 mt-2 pb-3',
          fieldGroup: [
            {
              type: 'input',
              key: 'firstName',
              defaultValue:'',
              id:'assets/icons/ContactCard.svg',
              className:'inputsFields firstArray d-none line-show icon-show',
              templateOptions: {
                placeholder:'First Name',             
                required: true,
                addonLeft: {
                  icon: 'assets/icons/ContactCard.svg',
                },
                
              },
              
            },
            {
              type: 'input',
              key: 'lastName',
              defaultValue:'',
              id:'assets/icons/ContactCard.svg',
              className:'inputsFields firstArray d-none line-show',
              templateOptions: {
                placeholder:'Last Name',
                required: true,                
                defaultValue:'',
                addonLeft: {
                  icon: 'assets/icons/ContactCard.svg',
                },
                
              },
              
            },
            
          ],
        },
        {
          className: 'col-lg-12 col-md-12 material-icons-outlined',
          fieldGroup: [
            {
              key: 'location',
              type: 'fed-select',
              defaultValue:'',
              id:'assets/icons/location.svg',
              className:'inputsFields locationIcon line-show',
              templateOptions: {
                placeholder:'Current Location',
                addonLeft: {
                  icon: 'assets/icons/location.svg',
                },
                valueProp: 'id',
              }
            },
            {
              key: 'meet',
              type: 'input',
              defaultValue:'',
              id:'assets/icons/meet.svg',
              className:'inputsFields line-show',
              expressionProperties: {
                'model.facebook':'model.occupation'
              },
              templateOptions: {
                placeholder:'How did you meet?',
                addonLeft: {
                  icon: 'assets/icons/meet.svg',
                },
              },
            },
            {
              key: 'hobbies',
              type: 'hobby',
              defaultValue:'',
              id:'assets/icons/HobbyInterest.svg',
              className:'material-icons-outlined inputsFields hobbiesIcon line-show',
              templateOptions: {
                placeholder:'Interests/Hobbies',
                addonLeft: {
                  icon: 'assets/icons/HobbyInterest.svg',
                },
              }
            },
            {
              key: 'occupation',
              type: 'input',
              defaultValue:'',
              id:'assets/icons/occupation.png',
              className:'inputsFields occupationIcon line-show',
              templateOptions: {
                placeholder:'Occupation',
                addonLeft: {
                  icon: 'assets/icons/occupation.png',
                },
              },
            },
            {
              key: 'notes',
              type: 'textarea',
              defaultValue:'',
              id:'assets/icons/note.svg',
              className:'inputsFields noteIcon line-show',
              templateOptions: {
                placeholder:'Notes',
                autosizeMinRows: 4,
                autosizeMaxRows: 5,
                autosize:"{minRows:to.minRows, maxRows: to.maxRows}",
                addonLeft: {
                  icon: 'assets/icons/note.svg',
                },
              },
            },
            {
              key: 'birthdate',
              wrappers: ['BirthdateFields'],
              defaultValue:'',
              type: 'input',
              id: 'assets/icons/birthday.png',
              className:'inputsFields birthDateIcon line-show',
              templateOptions: {
                placeholder: 'Birthdate',
                addonLeft: {
                  icon: 'assets/icons/birthday.png',
                },
              },
            },
            {
              key: 'tags',
              type: 'tags',
              defaultValue:'',
              id:'assets/icons/tag.svg',
              className:'material-icons-outlined tagsIcon inputsFields line-show',
              templateOptions: {
                placeholder:'Tags',
                addonLeft: {
                  icon: 'assets/icons/tag.svg',
                },
              }
            }
          ],
        },
        
      ],
    },
    {
      key:2,
      id:'public',
      templateOptions: { 
        label: 'Social',
        attributes:{isEdit:0} 
      },
      fieldGroupClassName: 'row ml-1 mt-2 pb-3',
      fieldGroup: [
        {
          className: 'col-lg-12 col-md-12 material-icons-outlined',
          fieldGroup:[
            {
              key: 'meet',
              type: 'input',
              defaultValue:'',
              id:'assets/icons/meet.svg',
              className:'inputsFields line-show',
              expressionProperties: {
                'model.facebook':'model.occupation'
              },
              templateOptions: {
                placeholder:'How did you meet?',
                addonLeft: {
                  icon: 'assets/icons/meet.svg',
                },
              },
            },
            {
              className:'inputsFields',
              key: 'linkedin',
              type: 'input',
              defaultValue:'',
              id:'assets/images/socialMedia-images/027-linkedin.svg',
              templateOptions: {
                placeholder:'Linkedin',
                addonLeft: {
                  icon: 'assets/images/socialMedia-images/027-linkedin.svg',
                },
              },
            },
            {
              className:'inputsFields',
              key: 'facebook',
              type: 'input',
              defaultValue:'',
              id:'assets/images/socialMedia-images/036-facebook.svg',
              templateOptions: {
                placeholder:'Facebook',
                addonLeft: {
                  icon: 'assets/images/socialMedia-images/036-facebook.svg',
                },
              },
            },
            {
              className:'inputsFields',
              key: 'instagram',
              type: 'input',
              defaultValue:'',
              id:'assets/images/socialMedia-images/029-instagram.svg',
              templateOptions: {
                placeholder:'Instagram',
                addonLeft: {
                  icon: 'assets/images/socialMedia-images/029-instagram.svg',
                },
              },
            },
          ]
        },
      ],
    },
    {
      key:3,
      id:'contact_phone',
      templateOptions: { 
        label: 'Contact',
        attributes:{isEdit:0} 
      },
      fieldGroupClassName: 'row ml-1 mt-2 pb-3',
      fieldGroup: [
        {
          className: 'col-lg-12 col-md-12 material-icons-outlined',
          fieldGroup:[
            {
              className:'inputsFields ',
              key: 'email',
              type: 'input',
              defaultValue:'',
              id:'assets/icons/envelope.svg',
              templateOptions: {
                type: 'email',
                placeholder:'Email',
                pattern:/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
                addonLeft: {
                  icon: 'assets/icons/envelope.svg',
                },
              },
             validators: {
               PatternValidator: emailValidationMessage // 'ip' matches the ip validation message
             }
            },
            {
              className:'inputsFields',
              key: 'phoneNumber',
              type: 'input',
              defaultValue:'',
              id:'assets/icons/phone.svg',
              templateOptions: {
                type: 'tel',
                placeholder:'Phone Number',
                addonLeft: {
                  icon: 'assets/icons/phone.svg',
                },
              },
            },
            {
              className:'inputsFields',
              key: 'address',
              type: 'textarea',
              defaultValue:'',
              id:'assets/icons/mailbox.svg',
              templateOptions: {
                placeholder:'Address',
                autosize: true,
                autosizeMinRows: 1,
                autosizeMaxRows: 10,
                addonLeft: {
                  icon: 'assets/icons/mailbox.svg',
                },
              },
            },
          ]
        },
      ],
    },
  ],
}];`
```

**Comment by aitboudad** [comment]
The question is not clear enough, could you please elaborate more :pray:!
