### ISSUE TITLE
i want apply password visible icon or checkbox, how to impliment please guide me

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#3031]
{
key: 'password',
type: 'input',
templateOptions: {
type: 'password',
label: 'Password',
placeholder: 'Password ...',
required: true,
},
validation: {
messages: {
required:'Password must be required ',
},
},
}

**Comment by aitboudad** [comment]
Here is one example that uses bootstrap add-ons https://stackblitz.com/edit/angular-peapdh?file=src/app/app.component.ts
- Bootstrap https://formly.dev/examples/bootstrap-specific/input-add-ons
- Material https://formly.dev/examples/other/material-prefix-suffix

Also in case, you want to use an extra lib for that feature you could easily create a specific custom type by following our guide  https://formly.dev/guide/custom-formly-field

**Comment by vardhan1122** [comment]
Hi Dear,
Thanks , Thanks a lot.
