### ISSUE TITLE
value change before on destroy

### ISSUE THREAD

**Issue by fontsie** [ngx-formly/ngx-formly#3033]
**Question**
I find it strange that the value change is called when there is a destroy.
If you open console of the stackblitz and press che button "restart" you see before "destroy" a "change".
Is it correct?

https://stackblitz.com/edit/angular-cbjqxj?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
see https://stackblitz.com/edit/angular-meffkb

**Comment by aitboudad** [comment]
That's expected, we perform a validation check on each re-build which trigger `valueChanges` event, not desired but didn't find any solution to prevent that at the moment :pray:.

Just a side note if you return an observable in `onInit`, Formly will handle the subscription automatically:
```ts
hooks: {
  onInit: (field: FormlyFieldConfig) => {
    return field.formControl.valueChanges
      .pipe(
        tap((z) => console.log('change', z)),
      );
  },
},
```
