### ISSUE TITLE
Getting the base64 format of a file(s) in model json of a form

### ISSUE THREAD

**Issue by saswatpatro** [ngx-formly/ngx-formly#3037]
Hi Team,
I have a case where there is a requirement of changing the format( e.g. - base64) of a file or multiple files being uploaded using a file upload option in a form. 
I have a form where I get array of model jsons like mentioned below when I upload files : 
{
entry_date: "2021-11-03T10:59"
file: "C:\\fakepath\\upload test.txt"
id: "xx"
remarks: 21
name: "yyyyyyy"
shift: "1"
}
Here in place of the fakepath string in the file key I want the base64 or any format which I can easily use to send the information to the backend for saving the file.
I mention below a stackblitz code where I am able to convert it to base64 format while uploading but I am not able to replace it in the model json.
https://stackblitz.com/edit/angular-sh4af1?file=src%2Fapp%2Ffile-type.component.ts
This is another stackblitz which I tried (issue remains the same - file not in a format to transfer to backend) :
https://stackblitz.com/edit/angular-lgq2cy?file=src%2Fapp%2Fapp.component.ts
Any help would be highly appreciated!
Thanks!

**Comment by aitboudad** [comment]
Use on of the following solutions:

1- use `setValue`:

```patch
@Component({
  template: `
    <input type="file"
-     [formControl]="formControl"
      ...
   >
  `,
})
export class FormlyFieldFile extends FieldType {
  onChange(event) {
    ...
+  this.formControl.setValue(...)
  }
}
```

2- The second solution `parsers`:

```ts
{
  type: 'file',
  parsers: [formatBase64]
},

**Comment by saswatpatro** [comment]
Hi @aitboudad and thanks a lot for the solutions.
I don't know why but I am not successful in implementing your solution 1...Could you please help me implement it in the stackblitz link I have provided below? It would have been really helpful!
https://stackblitz.com/edit/angular-lgq2cy?file=src%2Fapp%2Ffile-type.component.ts
Thanks!

**Comment by aitboudad** [comment]
```ts
import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';

@Component({
  selector: 'formly-field-file',
  template: `
    <input type="file"
      (change)="onChange($event.target.files)"
      (blur)="onTouched()"
      [formlyAttributes]="field" [multiple]="'true'"
    >
  `,
})
export class FormlyFieldFile extends FieldType {
  // formControl;
  onChange(files) {
    const base64Value = toBase64(files);

    this.formControl.setValue(base64Value);
    this.formControl.markAsDirty();
  }

  onTouched() {
    this.formControl.markAsTouched();
  }
}
```
