### ISSUE TITLE
Excessive call within a provider/extension.

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#3038]
I have a table and inside that table I have several lines(tr) and in these lines several fields(td).
Inside each td is a formly field.
For each formly field, I have an extension where I have a field called hideColumnsBody that calls a function that analyzes whether or not it should appear.

Excerpt from the code that does this.

```javascript
field['expressionProperties'] = {
    ...(field['expressionProperties'] || {}),
    'templateOptions.tableFieldOptions.hideColumnsBody': (model,formState,field) => hideColumnsBody(model, formState, field),
};
```

However it is having an excessive call and I would like to know how to improve it, because the number of times it is called when clicking on the screen is exaggerated.

You can follow it here by opening the developer tool and following the number of times `console.log` appears.
https://stackblitz.com/edit/angular-formly-table?file=src%2Fapp%2Fproviders%2Ftable-hide-columns-body.extension.ts

I didn't think of anything other than registering inside expressionProperties, if you have any other suggestions, I'd love to hear.

And as much as v6 can be more performant I can't update now, the company requires that to update the version of the project libraries, it needs to have a stable version and that it has been released for more than 4 months.

**Comment by aitboudad** [comment]
it's an excessive call within hideExpression I think, pass `modelChange` to the extra option `checkExpressionOn` in order to reduce the number of calls

```
FormlyModule.forRoot({
  extras: {
    checkExpressionOn: 'modelChange'
  },
})
```


> And as much as v6 can be more performant I can't update now, the company requires that to update the version of the project libraries, it needs to have a stable version and that it has been released for more than 4 months.

I understand but we can't provide those features in `V5` due to the breaking changes :pray:!

**Comment by GlauberF** [comment]
thanks, i will try this.

**Comment by GlauberF** [comment]
after some tests @aitboudad 
solves the performance problem, but it is not evaluated correctly.

See here, how it behaves "wrongly"
https://stackblitz.com/edit/angular-formly-table

Gif the wrong way, using `checkExpressionOn: 'modelChange'`
![vokoscreen-2021-11-04_14-44-17](https://user-images.githubusercontent.com/11314585/140391833-e9529f45-ebb1-4eca-8558-2664f8c9adde.gif)


Gif in the right way, without using `checkExpressionOn: 'modelChange'`
![vokoscreen-2021-11-04_14-45-26](https://user-images.githubusercontent.com/11314585/140392058-4d474068-bc8c-4b45-bfb5-0f93c70a6e71.gif)

**Comment by GlauberF** [comment]
after upgrading to v5.10.23, it works.
