### ISSUE TITLE
validation.show is not relevant for scenarios where you want to hide error after field has been updated

### ISSUE THREAD

**Issue by frankyvij** [ngx-formly/ngx-formly#3041]
I am working on a solution that only shows the error message when the field is in focus.

I went through this example: https://formly.dev/examples/validation/force-show-error, and it seems that we could show/hide error message through expressionProperties: validation.show.

The bug is that validation.show = false is not acknowledged after you focus and blur out of the field.

Steps to reproduce the bug in the example 'force-show-error':
1. Focus on the Email
2. Focus out of Email
3. Uncheck the 'Force show error state'

Expected result: Validation error is no longer visible since validation.show is now set to false
Actual result: Validation error is still visible

**Comment by aitboudad** [comment]
To change that behavior you can pass a custom [showError](https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/services/formly.config.ts#L31-L36) function:

```ts
export function showError(field: FieldType) {
  return ....;
}

@NgModule({
  imports: [
    FormlyModule.forRoot({ extras: { showError } }),
  ],
})
```
