### ISSUE TITLE
I want my dropdown to be in single column but it isnt working. Is it an issue of Bootstrap.

### ISSUE THREAD

**Issue by shiv-aye** [ngx-formly/ngx-formly#3042]
- What i am getting = https://user-images.githubusercontent.com/68880887/140871136-8a375b6f-b54d-4e89-a7ef-43d44dfc06d0.png"

- What i want  = https://user-images.githubusercontent.com/68880887/140871146-71c79975-cafc-4570-ad7c-640751ca421c.png

`fields: FormlyFieldConfig[] = [
    this.fieldsService.FlexRow([
      this.fieldsService.Col6([
        {
          key: "test",
          type: "Typeahead",
          templateOptions: {
            label: "Name",
            options: this.fakedata.name(),
            placeholder: "Name",
            valueProp: "test",
            labelProp: "test",
            required: false,
          },
        },
      ]),`

**Comment by aitboudad** [comment]
Without a reproduction example, it is hard for us to know exactly the issue.
Feel free to reopen once you've got a  reproduction example.
