### ISSUE TITLE
lazyRender, empty `formly-field` element

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#3043]
when I set `lazyRender`, an empty `formly-field` element is created, but taking up space.

![Captura de Tela_20211109173450](https://user-images.githubusercontent.com/11314585/141000957-9b4a1312-f98b-4a87-9859-0ceae9bf9a60.png)

**Your Environment**

- Angular version: 12.2.13
- Formly version: 5.10.23

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.24](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.24) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by GlauberF** [comment]
Thanks!
I will test.

**Comment by GlauberF** [comment]
@aitboudad  It worked 100%.
Sorry for my ignorance, but how does lazyRender work behind the scenes, how does it work?

**Comment by aitboudad** [comment]
By default, we render all components even the hidden one (we rely on style to hide the field `display: none`), the new behavior (`lazyRender`  which is enabled by default in `V6`) doesn't render the hidden field so it'll not be present on the DOM (it should act like virtual dom) which improve the perf.

**Comment by GlauberF** [comment]
Thank you for the explanation.
