### ISSUE TITLE
`checkExpressionOn:  'modelChange'`, manually force re-evaluate

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#3044]
We used the `checkExpressionOn: 'modelChange'` option in our project, and we really got a big improvement in performance, as we have less event triggering.

But I solve a problem and another challenge arises, I'll try to describe the scenario below and if you have a solution to force the reassessment manually.

I have an `autocomplete` field, which when I type something to look for in the API, I show a loading
![vokoscreen-2021-11-09_17-47-58](https://user-images.githubusercontent.com/11314585/141004551-8b605833-8c29-4ac9-b32c-5b69c85e88db.gif)

And this loading appears based on a variable that I set `true` or `false` inside `expressionProperties`, however using `checkExpressionOn: 'modelChange'`, I change the variable and don't remove the loading, because the `expressionProperties`, it is only re-evaluated when the model changes.
![Captura de Tela_selecionar área_20211109175101](https://user-images.githubusercontent.com/11314585/141004587-c79d6e27-3891-4f21-a65c-0ea6161a4742.png)

in this case, there would be some way to manually force revaluation in some cases, however much my setting is `checkExpressionOn: 'modelChange'`

**Comment by aitboudad** [comment]
force re-evaluate are needed for some cases when `modelChange` is enabled, we've introduced a new mode that try to detect changes without impacting the performance which you may try in `V6`.

**Comment by GlauberF** [comment]
okay, but there is some method in V5 that I can call to force re-evaluate ?

**Comment by aitboudad** [comment]
You may try `_markForCheck`:

```ts
(<any> field.options)._markForCheck(field);
```
