### ISSUE TITLE
How pass data to wrapper component that  extends FieldWrapper for Storybook?

### ISSUE THREAD

**Issue by matishwlocusview** [ngx-formly/ngx-formly#3045]
**Question**

we use formly and recently we insert Storybook to our app.
I want to do a story for a wrapper component that use formly.

```
export default {
  title: 'Infra/formly/LvFormlyEditorCardComponent',
  component: LvFormlyEditorCardComponent,

} as Meta;

const Template: Story<LvFormlyEditorCardComponent> = (args: LvFormlyEditorCardComponent) => ({
  props: args,
});


const baseArgs = {
  fieldGroup: [
    {
      wrappers: [FORMLY_CUSTOM_TEXT.card],
      templateOptions: {
        className: 'flex-column',
        isEditable: true,
        hidePencil: true,
        icon: 'web-hook',
        title: 'WEB_HOOK_HOST',
        hasTopIcon: true,
        editStateValid: true,
        isEditStateDirty: true,
        hasPadding: true,
      },
    }],
  primary: true,
};

export const Primary = Template.bind({});
Primary.args = {...baseArgs};
```
I got error "Cannot read properties of undefined (reading 'templateOptions')"
How I need to pass the data that the component will know to read it?

**Comment by matishwlocusview** [comment]
I found a way to this , I am not sure is it the best practice.
I added  this code to the component
` @Input() public field: FieldType;`

**Comment by kenisteward** [comment]
If you inherit FieldType in your component this shouldn't be needed.  The
bast field type has this defined.

**Comment by matishwlocusview** [comment]
yes it's has defined, but I don't how to pass data there Through Storybook

**Comment by aitboudad** [comment]
We build the field first then pass it to `formly-field` component, we've simplified our testing by providing some utils but
not sure if it could be helpful for Storybook.
see https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/bootstrap/form-field/src/form-field.wrapper.spec.ts#L11
