### ISSUE TITLE
multicheckbox flexbox colum

### ISSUE THREAD

**Issue by diomededavid** [ngx-formly/ngx-formly#3051]
**Is your feature request related to a problem? Please describe.**
I'm am having issues overriding styles to allow multicheckbox's to stack vertically.

**Describe the solution you'd like**
When using CSS or Angular fxgrid, multicheckbox are unable to stack vertically, and do not space between items

Current display:
<img width="335" alt="Screen Shot 2021-11-16 at 3 34 15 PM" src="https://user-images.githubusercontent.com/14153189/142070634-f9aac85e-f710-46b4-a2bc-904cd57649f4.png">

Desired display:

<img width="337" alt="Screen Shot 2021-11-16 at 3 34 10 PM" src="https://user-images.githubusercontent.com/14153189/142070845-6b67e374-76f3-4280-b464-f3cb04441021.png">

Having an option to align along a flex direction of row or column would be ideal for multicheckbox.

**Comment by aitboudad** [comment]
> Having an option to align along a flex direction of row or column would be ideal for multicheckbox.

why not!

For the moment you could use a custom class that you may pass to `className` property https://github.com/ngx-formly/ngx-formly/issues/978#issuecomment-394832904

**Comment by diomededavid** [comment]
for anyone who might have been having the same issue. This example helped.
https://stackblitz.com/edit/multicheckbox?file=src%2Fstyles.scss

I found the only way that worked for me was adding the css override to the root stylesheet. Overrinding in app.component or the components stylesheets did not work.

My code:

`formly-field-mat-multicheckbox {
  .mat-checkbox {
    display: flex;
  }
}`
