### ISSUE TITLE
v6 Roadmap

### ISSUE THREAD

**Issue by manuelmeister** [ngx-formly/ngx-formly#3053]
**Question**
What is missing for v6 to be released as non-next?

**Comment by aitboudad** [comment]
Just time :), I'm starting to have more time so I'll try to release a second alpha version this week then we switch to `rc`  or stable if nothing critical appears.

**Comment by manuelmeister** [comment]
Okay, if you need help, just tell me.

**Comment by aitboudad** [comment]
> Okay, if you need help, just tell me.

my main next target is documentation, so any help would be welcomed :pray:, see https://github.com/ngx-formly/ngx-formly/issues/2723 (I'll provide more if needed).

**Comment by aitboudad** [comment]
Angular v13 support is released in [v6.0.0-next.4 (release)](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.4), we'll switch into beta release within 1/2 weeks.
