### ISSUE TITLE
"Chained" hide expressions using JSON

### ISSUE THREAD

**Issue by anders80** [ngx-formly/ngx-formly#3054]
I am working on a project using formly JSON schema and I am having problems with hide expressions. My JSON has a structure similar to this:
...
  {
    "key": "cb1",
    "type": "checkbox",
  },
  {
    "key": "cb2",
    "type": "checkbox",
    "hideExpression": "!model.cb1"
  },
  {
    "key": "label1",
    "type": "label",
    "hideExpression": "!model.cb2"
    "templateOptions": {
      "label": "Show only when cb2 is visible in DOM and checked"
    }
  }
...

The user checks cb1, then checks cb2, label1 is shown in the DOM. If theu user then unchecks cb1, cb2 disappears from the DOM, but label1 is still visible.
What I am trying to do is to hide label1 when cb2 is either unchecked or invisible in the DOM and do this without directly referencing cb1 in label1's hide expression. 
I was hoping label1's hideExpression could be changed to "!form.value.cb2", since cb1 is removed from form.value when it is removed from the DOM by its own hide expression. But form.value is undefined.
Is there a way to do what I am trying?

**Comment by aitboudad** [comment]
Pass `true` to the following option `resetFieldOnHide` which clear the value of hidden fields:

```patch
FormlyModule.forRoot({
  extras: {
+   resetFieldOnHide: true
  },
}),
```
