### ISSUE TITLE
i want display today date displaying inside form filed default?

### ISSUE THREAD

**Issue by vardhan1122** [ngx-formly/ngx-formly#3058]
{
key: 'todayDate',
type: 'input',
defaultValue: new Date(),
templateOptions: {
label: 'Today Date',
type:'date'
},
},
![Screenshot (190)](https://user-images.githubusercontent.com/67161080/142726878-33408330-5b52-4829-b4d9-5bd3bb20a0fd.png)

**Comment by pain0486** [comment]
I think for bootstrap, it has to be formatted yyyy-mm-dd as a string

**Comment by aitboudad** [comment]
type `date` expect a string value https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
in case you're using material UI, passing `Date` instance should work.

**Comment by vardhan1122** [comment]
Thank you so much, i need monthName instead of monthNumber, i am trying this way, didn't get in ,please...

  monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
  ];
  joiningDateAsStr = `${this.today.getFullYear()}-${this.monthNames[this.today.getMonth()]}-${this.today.getDate()}`;


{
      key: 'joiningDate',
      type: 'input',
      defaultValue: this.joiningDateAsStr,
      templateOptions: {
        label: 'Joining Date',
        type:'date'
      },
}

**Comment by pain0486** [comment]
If you want the control to have that format, I think your looking at making your own control in formly and using that over the built in one and creating the datePicker in that control, passing the format you would like to use.
[example of change bootstrap format](https://stackoverflow.com/questions/19992727/change-bootstrap-datepicker-date-format-on-select#:~:text=Open%20the%20file%20bootstrap-datepicker.js%20Go%20to%20line%201399,http%3A%2F%2Fwww.eyecon.ro%2Fbootstrap-datepicker%2F%20%29%20format%20worked%20only%20with%20upper%20case%3A)

you might be able to accomplish that via parsers, hooks or and using the DatePipe, but I don't think Bootstrap will recognize the  value without getting the format on Bootsrap set. I am not aware of a way to pass the bootstrap options via formly, but I don't use bootstrap with formly so there might be a way that I don't know about.

if you only need the end result like that, you can always update that on submit of the form.
