### ISSUE TITLE
Loading a model after the JSONSchema does works.

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3059]
**Description**
Loading the model after the JONSchema does not work correctly.

**Minimal Reproduction**

Go to the following example and try the `set Model` button. Nothing happens, but the oneOf should switch from property one to property 2.

https://stackblitz.com/edit/angular-4cslvk?file=src/assets/json-schema/oneOf.json

Here is a second example with the `simple` example; after pushing `set Model` the `firstName` should be removed:

https://stackblitz.com/edit/angular-4cslvk-s93cav?file=src/app/app.component.ts

_Note_: here is a second example that does
**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.10.22

**Comment by jma** [comment]
This bug comes from the version 5.10.12, it woks with the version 5.10.11. I hope that helps.

**Comment by jma** [comment]
Any news?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.26](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.26) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
