### ISSUE TITLE
How do I subscribe to a valueChanges of a field that is being hidden via "hideExpression"?

### ISSUE THREAD

**Issue by ThomazAquino** [ngx-formly/ngx-formly#3061]
How do I subscribe to a valueChanges of a field that is being hided via "hideExpression"?

    {
      key: 'meat',
      hideExpression: '!model.bread',
    },
   
    {
      key: 'salad',
      hideExpression: '!model.bread || !model.meat',
      hooks: {
        onInit: (field: FormlyFieldConfig) => {
         // *** Here is the problem, I cannot subscribe to meat valueChanes cause it is outside of the form ***
          field.templateOptions.options = field.form
            .get('meat')
            .valueChanges.pipe(
              switchMap((meatType) => getSaladsBasedOnMeatType(meatType))
            );
        },
      },
    },

This code give me the following error:
`ERROR Error: Cannot read properties of null (reading 'valueChanges')`

Please, check this template example on StackBlitz: https://stackblitz.com/edit/ngx-formly-ui-material-fshqie?file=src%2Fapp%2Fapp.component.ts

The example above is a hamburger bulder with 3 steps where the options of every step is loaded via HTTP depending on the previous selection.

I would like to do this without calling a function in the component like this:

    {
      key: 'meat',
      hideExpression: '!model.bread',
          templateOptions: {
            change: () => this.activelyLoadNextField(),
          },
    },

I believe this configuration should be stand alone, not depending on componet's methods.

**Comment by ThomazAquino** [comment]
I found a solution.

I can actively load the next field using the `templateOptions.change` without call a local function.

So the code will be like this:
```
{
  key: 'meat',
  templateOptions: {
    change: (field) => {
      // Add Next field (Salad)
      const nextField = field.parent.fieldGroup.find((f) => f.key === 'salad');
      nextField.templateOptions.options = getMeatsBasedOnBreadType(field.form.get('meat').value);
    },
  },
  hideExpression: '!model.bread',
}
```
I put this solution in another StackBlitz project: https://stackblitz.com/edit/ngx-formly-ui-material-ujms2f

Do you guys think this is ok, or there is a better approch?

**Comment by aitboudad** [comment]
> Do you guys think this is ok, or there is a better approch?

yes but the only limitation I see is `change` may not be triggered in case of programmatic changes `formControl.setValue(value);`.

I usually rely on the field itself to get its `formControl`, in `next` version you'll be able to find the `field` using [get](https://github.com/ngx-formly/ngx-formly/issues/2854) call:

```patch
- field.parent.fieldGroup.find((f) => f.key === 'salad');
+ field.parent.get('salad');
```

**Comment by ThomazAquino** [comment]
Hey aitboudad, sorry but I don't quite get the second line of your answer.

I understood that the  programmatic changes `formControl.setValue(value)`; does not trigger the `change` function.
Is there any approach that will work also for  programmatic changes?

**Comment by aitboudad** [comment]
> Is there any approach that will work also for programmatic changes?

```ts
hooks: {
  onInit: (field: FormlyFieldConfig) => {
     const saladField = field.parent.fieldGroup.find((f) => f.key === 'salad');
    return saladField.formControl.valueChanges
      .pipe(
        tap(...),
      );
  },
},
```

the second line is just a side note of the coming feature, so instead of using `find` you'll be able to use `get`:
```patch
- field.parent.fieldGroup.find((f) => f.key === 'salad');
+ field.parent.get('salad');
```

**Comment by MussaratAziz** [comment]
field.parent.get('salad');  giving error field.parent is possibly 'undefined' ??

**Comment by its-dibo** [comment]
> field.parent.get('salad'); giving error field.parent is possibly 'undefined' ?? @aitboudad

just use null-safe operators
