### ISSUE TITLE
Adding a new field dynamically by updating the FormlyFieldConfig throws an error "Cannot find control with unspecified name attribute"

### ISSUE THREAD

**Issue by johngamble** [ngx-formly/ngx-formly#3063]
**Description**
We need to be able to dynamically add, remove or update fields without reloading the form. The standard angular way is that when the input properties of an angular component update, the component responds by updating itself. Therefore, changing the field config passed into the [fields] input property of the <formly-form> element should cause the changes to be rendered.

This works well when removing a field.
This seems to work well updating an existing field
However when inserting a new field into the existing fieldGroup, we get errors.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-formly-examples-ceqe2c?file=src/app/app.component.ts

**Your Environment**

- Angular version: 7.2.15
- Formly version: 5.5.1

**Additional context**

When inserting the new field, the field does appear on screen immediately, however it's label doesn't render, and there are errors on the console:

ERROR Error: Cannot find control with unspecified name attribute
    at _throwError (shared.ts:140)
    at setUpControl (shared.ts:36)
    at FormControlDirective.ngOnChanges (form_control_directive.ts:186)
    at checkAndUpdateDirectiveInline (provider.ts:208)
    at checkAndUpdateNodeInline (view.ts:429)
    at checkAndUpdateNode (view.ts:389)
    at debugCheckAndUpdateNode (services.ts:430)
    at debugCheckDirectivesFn (services.ts:391)
    at Object.eval [as updateDirectives] (VM7992 FormlyFieldInput.ngfactory.js:77)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:385)

I would really appreciate any assistance with this.
Has formly not been designed to cater to this use case, or is there something wrong with my reproduction?
I need to get this working one way or another, so I would appreciate any help or direction you could give.

**Comment by johngamble** [comment]
I've created a another minimal reproduction with a newer version of formly:

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-nyufp4?file=src/app/app.component.html

This one doesn't give any errors, but still completely ignores new fields that are inserted.

Formly 5.10
Angular 10.2

**Comment by aitboudad** [comment]
The building is required, you can use `(this.options as any)._buildForm();` after insert: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-1mftjh?file=src/app/app.component.ts

You may check also [FieldArrayType](https://formly.dev/examples/advanced/repeating-section)

**Comment by johngamble** [comment]
Thanks Abdellatif, that's brilliant. Thank you so much for the quick response.

I'm glad it was such a simple thing.

It does seem a little hacky to call a private library function from external code though. Just wondering if there are plans to improve this going forward?

Thanks again Abdellatif, have a great day :)

**Comment by kenisteward** [comment]
> Thanks Abdellatif, that's brilliant. Thank you so much for the quick response.
> 
> I'm glad it was such a simple thing.
> 
> It does seem a little hacky to call a private library function from external code though. Just wondering if there are plans to improve this going forward?
> 
> Thanks again Abdellatif, have a great day :)

@johngamble this becomes a public API in v6 as buildField and buildForm.
