### ISSUE TITLE
Support lazy loading of components that requires an NgModule

### ISSUE THREAD

**Issue by InnovativeUS** [ngx-formly/ngx-formly#3064]
### Issue

We are a heavy user of NgxFormly. Thank you!

We have an enterprise application that lazy loads components as they are identified in a form. This works well for most components. However, we cannot use it when the component relies on imports from other NgModules.

https://stackblitz.com/edit/angular-ivy-fvdn64?file=src/app/form-wrapper/form-wrapper.module.ts

In the example above the boolean config loads correctly,  but datepicker relies on MatDatePickerModule and therefore cannot be displayed.

We can work around this by importing the dependent modules in AppModule, but that defeats the purpose of lazy loading.

### Possible solution

Include a reference to the module in FormlyConfig

```ts

{
  types: [
    {
      name: 'datepicker',
      component: DatepickerFormatComponent,
      module: DatepickerFormatModule,
      wrappers: ['form-field'],
    },
  ],
}

```

Use this reference when creating the component

V5
https://github.com/ngx-formly/ngx-formly/blob/b0d612ab7fbaf3e567f230326ddf381cf9f9a641/src/core/src/lib/components/formly.field.ts#L123

V6
https://github.com/ngx-formly/ngx-formly/blob/2a71f03ac6513db2abd28199a6d1e08da2da1357/src/core/src/lib/components/formly.field.ts#L101

We are happy to submit a pull request but want to make sure this is the correct way of solving the issue.

**Comment by aitboudad** [comment]
PR welcomed!

**note**: use the `main` branch.

**Comment by aitboudad** [comment]
The supported way for lazy loading component is to pass the config to `FormlyModule.forChild(DatepickerFieldConfig)` and import `DatepickerFormatModule` in `LazyDatepickerFormModule`:

Here is a working example: https://stackblitz.com/edit/angular-ivy-bsxvwr
