### ISSUE TITLE
Unable to add onchange event to each field inside array type in json schema

### ISSUE THREAD

**Issue by abhihotmail** [ngx-formly/ngx-formly#3065]
**Description**

I have a requirement like one textbox depends on other textbox value inside array of textboxes. I am adding a change event to one textbox dynamically but its not adding.

**Minimal Reproduction**
JSON Schema:

    {
  
  "type": "object",
  "title": "Rules",
  
  "properties": {

    "LR": {
      "type": "array",
      "maxItems": 9,
      "title": "LR",
      "items": {
        "type": "object",
        "properties": {

          "PMR": {
            "type": "string",
            "title": "PMR",
            "pattern": "^(\\d{1,3})(\\.\\d{0,2})?$",
            "widget": {
              "formlyConfig": {
                "templateOptions": {
                  "maxLength":"3",
                  "pmrChange":"this.pmrChange($event, field)"
                }
              }
            }
          }
        }
      }

    }
  }
}

-------
extendFieldConfigs(): FormlyFieldConfig[] {
    
    this.fieldConfig.fieldGroup.map((field) => {
     
      const key = field.key ? field.key.toUpperCase() : null;
      if (!key) return;
      debugger;
      switch (key) {
        case "LR":
         

          field.fieldArray &&
            field.fieldArray.fieldGroup.map((fgrpItem) => {
              const childKey = fgrpItem.key ? fgrpItem.key.toUpperCase() : null;
              switch (childKey) {
                case "PMR": {
                  fgrpItem.templateOptions.change = Function(
                    "field",
                    "$event",
                    fgrpItem.templateOptions.pmrChange
                  ).bind(this);
                  
                  break;
                }
              }
            });

          break;
      }
    });

    return [this.fieldConfig];
  }

 pmrChange(a, b) {
    alert(a);
  }

**Your Environment**

- Angular version: 9.0.4
- Formly version: 5.5.13

**Additional context**

When its direct element like textbox its fine , but when we add in type array then event is not working.. pls help.

**Comment by aitboudad** [comment]
Related to https://github.com/ngx-formly/ngx-formly/issues/2809 which has been fixed in `next` version. Fields in array are generated during the build step we've used a getter in `v5` (as workaround), the proper way can be found in `next` version which allows passing a function to the field array.

- [Next](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.4): https://github.com/ngx-formly/ngx-formly/blob/main/src/core/json-schema/src/formly-json-schema.service.ts#L265
- V5: https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/json-schema/src/formly-json-schema.service.ts#L265

**Comment by abhihotmail** [comment]
V5: https://github.com/ngx-formly/ngx-formly/blob/v5/src/core/json-schema/src/formly-json-schema.service.ts#L265

How to use this in my above  code :?
 fgrpItem.templateOptions.change = Function(
                "field",
                "$event",
                fgrpItem.templateOptions.pmrChange
              ).bind(this)

**Comment by aitboudad** [comment]
I would suggest using `v6` if you can, for `v5` use a similar way of the source code but not recommended:

```ts
const fieldArray = Object.getOwnPropertyDescriptor(field, 'fieldArray').get;
Object.defineProperty(field, 'fieldArray', {
  get: function () {
    const fgrpItem = fieldArray();
    ....
    
    return fgrpItem;
  }
}
```

**Comment by abhihotmail** [comment]
V6 is still in-progress I think. is it stable..Can I upgrade from 5.10.21?

**Comment by aitboudad** [comment]
Still in-progress but the major parts are done, we may still introduce some breaking changes before going to stable.
