### ISSUE TITLE
How to have input field with attribute list?

### ISSUE THREAD

**Issue by hansaliyad1** [ngx-formly/ngx-formly#3069]
I am trying to use input datalist like below example. I am using formly with bootstrap template. I tried to look for resources online but wasn't able to find anything. I will really appreciate if someone can assist me with this.

My end goal is to have an input field with autocomplete. The autocomplete suggestions are populated via API. It doesn't have to be achieved via datalist, but I haven't found any other solution which could be achievable using formly. Thank you!

```
<label for="ice-cream-choice">Choose a flavor:</label>
<input list="ice-cream-flavors" id="ice-cream-choice" name="ice-cream-choice" />

<datalist id="ice-cream-flavors">
    <option value="Chocolate">
    <option value="Coconut">
    <option value="Mint">
    <option value="Strawberry">
    <option value="Vanilla">
</datalist>
```

**Comment by mohamedelshorbagy** [comment]
Hey @hansaliyad1, I think what you're looking for is custom formly field type, you can find it explained well here
https://formly.dev/guide/custom-formly-field
also I tried to make a quick example with what you're looking for you can check it here:
https://stackblitz.com/edit/angular-zl2e66-t8k2jv?file=src%2Fapp%2Fapp.component.html.

**Comment by hansaliyad1** [comment]
@mohamedelshorbagy Thank you so much for your response. I will check this out. I really appreciate it.
