### ISSUE TITLE
Issue with type: radio label gets ellipsis if too long

### ISSUE THREAD

**Issue by mansevmann** [ngx-formly/ngx-formly#3073]
Hello

We're experiencing that the label get text-overflow: ellipsis; if it's beyond a certain length. Our customer often have to write longer, matriculate descriptions due to specifics with laws and legalization. Is there a way to make the label show the entirety of the text?

Here's a stackblitz with an example: https://stackblitz.com/edit/angular-sngrp1

Thanks

**Comment by aitboudad** [comment]
That's part of the material spec, not sure there is a straight way to write longer (they use position absolute), you may check the material repo if someone could point you to the right solution.

From Formly side you may use one of the following solutions:
- define a custom css for that specific field.
- use a custom field type https://formly.dev/guide/custom-formly-field which doesn't rely on https://material.angular.io/components/form-field/overview
