### ISSUE TITLE
Adding a matPrefix or matSuffix to a custom Material field type does not work

### ISSUE THREAD

**Issue by tzehetner** [ngx-formly/ngx-formly#3074]
**Description**

Adding a matPrefix or matSuffix to a custom Material field type via ng-template (as demonstrated under the following link) does not work:

https://github.com/ngx-formly/ngx-formly/issues/715#issuecomment-365894017

**Minimal Reproduction**

See my demo repo: https://github.com/tzehetner/formly-custom-field-suffix

Unfortunately importing the repo into stackblitz did not work.

**Your Environment**

- Angular version: 13.0.0
- Formly version: 5.10.24 and 6.0.0-next.4

**Comment by aitboudad** [comment]
The issue has been fixed on both versions:

- https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.25
- https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.5

**Comment by tzehetner** [comment]
Thanks a lot!
