### ISSUE TITLE
JSON Schema with oneOf and default values for integer/numbers does not work properly

### ISSUE THREAD

**Issue by bytepoets-mzi** [ngx-formly/ngx-formly#3075]
![output](https://user-images.githubusercontent.com/46591443/144828883-e79c8c72-64b8-4b06-8bab-8370eae75c71.gif)

**Description**

JSON schema with oneOf and defaults for number/integer does not work when changing the selection.

**Minimal Reproduction**

[Stackblitz](https://stackblitz.com/edit/angular-mgdft6-eqheuh?file=src/assets/json-schema/oneOfIntDefault.json)

This JSON works, but the defaults for integer values are cleared when changing the type. I guess it is related to #2569.

<!--**Your Environment**

- Angular version: 10.2.4
- Formly version: 5.10.24 w/ Material 5.10.24 & Schematics 5.10.25

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.26](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.26) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by bytepoets-mzi** [comment]
That was fast. Really appreciated!
