### ISSUE TITLE
JSON Schema Powered Formly Config: Unable to add dynamic values to validation messages

### ISSUE THREAD

**Issue by abhihotmail** [ngx-formly/ngx-formly#3081]
"Test": {
      "type": "number",
      "title": "Test",
      "widget": {
        "formlyConfig": {
          "templateOptions": {
              "min":"1",
              "max":"99999",
              **"validation.messages.max": "Must be lesser than {{field.templateOptions.max}}". <==== NOT WORKING**
          },
          "validation": {
            "messages": {
              "required": "Interest rate code is mandatory",
              "min":"Must be greater than 0",
              **"max":"Must be lesser than {{field.templateOptions.max}}". <==== NOT WORKING**
            }
          }
        }
      }
    }
    
    
    **Environment**

Angular version: 9.0.4
Formly version: 5.5.13

**Comment by aitboudad** [comment]
You should use `expressionProperties`: https://stackblitz.com/edit/angular-qd77cw?file=src/app/app.component.ts
For alternative ways check our doc examples: https://formly.dev/examples/validation/validation-message
