### ISSUE TITLE
Remove mat-form-field static position

### ISSUE THREAD

**Issue by nzbin** [ngx-formly/ngx-formly#3082]
https://github.com/ngx-formly/ngx-formly/blob/77997893b145506bdc15df5db36f17c467c53b89/src/ui/material/form-field/src/form-field.wrapper.scss#L5-L8

The style would cause some other small issues. This solution is useful for some cases and not for some other cases. So I think it would be better to be set for user themselves.

**Comment by aitboudad** [comment]
we use position static to solve the following issue https://github.com/angular/components/issues/4580, could you please point me to the other cases that may not be suitable?

**Comment by nzbin** [comment]
https://ng-matero.github.io/ng-matero/forms/dynamic

Please check this page. I have fix the issue by overriding the `position: static`. You can open the Chrome DevTools and turn off the style to checkout the changing of `form field` and `city select panel`.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.27](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.27) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
