### ISSUE TITLE
Cannot submit a form after and hide and show action on array

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3083]
**Description**
When a field is hidden and show again is not at his initial state.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-e9ng4s?file=src/assets/json-schema/arrays.json

1. Enter a value for the name of car in cars.
2. Hide the field by clicking the button.
3. Show the field again by clicking the button.
4. It is not possible to submit the form.

Thanks a lot.
**Your Environment**

- Angular version: 7.2
- Formly version: 5.10.26

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.27](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.27) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
