### ISSUE TITLE
intersectionObserver at <tr> for large tables

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#3085]
Before starting, I'd like you to look at this video (https://user-images.githubusercontent.com/11314585/145086514-8d085a6e-65fe-4605-9846-607bd088c25f.mp4) where I demonstrate my implementation, and then come up with a point that I would like your help on and how for me this approach works very well.

Today, inside my table in the `<tr>` of the table, I have a directive where I use the intersectionObserver(https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

Once the directive returns me that the element(`<tr>`) is visible on the screen, I show the table row with all the formly elements that are inside a `<td>`.

when the directive returns that the element(`<tr>`) is not visible on screen, I remove the formly elements and all the `<td>`, creating just a `<td>` with a background, to keep the `<tr>` position, otherwise the mouse scroll would change.

But I have a problem today, when the directive returns that the element(`<tr>`) is visible on the screen, I use a `*ngIf` to show the `<td>` and the formly elements.
This causes slow scrolling of the mouse, as it recreates the fields.

I already use the `lazyRender: true` option today.

1 - Is there anything I can do to keep the fields already created in cache, so that a second time it shows on screen faster?
2 - How could I make the process of showing the fields (create) be faster?

Thinking about my approach, today inside the `<tr>` not visible, I create a `<td>` with background just to keep the position, would there be any suggestion not to create the `<tr>` or `<td>`, as it is a simple element, but it is one more element in the DOM.
And I use this approach to keep the `tr` element position and keep the scroll position

This approach and idea has nothing related on the internet, so I would love to share experiences and serve as a help for other people looking for something here in the issue.
And I can't use cdk-virtual, because it depends on the page's scroll, I can't fix a size for the table.

**Comment by aitboudad** [comment]
it's hard to know where the issue exists without a reproduction but here are some hints:
- use `*ngIf` for the first render only, keep them in the DOM and use `display: none` if necessary.
- test `v6` which uses `OnPush` change detection.

Ideally `cdk-virtual` is the solution for scrolling, the only criteria you'll have to accept is having scroll on table body instead of relying on page scroll.

Feel free to reopen in case you've a reproduction so I may check it on my side when time allows.
