### ISSUE TITLE
Unable to remove the selected item from master data source inside array type

### ISSUE THREAD

**Issue by abhihotmail** [ngx-formly/ngx-formly#3086]
Json schema powered formly:

```
"blood": {
      "type": "array",
      "title": "bloodGroup",
      "items": {
        "enum": [
          "A",
          "B",
          "O"
        ]
      }
    }
```

    When user selects A from 1st dropdown then A should not appear in 2nd dropdown.
    When user select B from 2nd dropdown then both A and B should not appear in 3rd dropdown ...etc..
 After all the items added by the user, then the PLUS icon should be disabled automatically so that user cant add more than the master data items length
    
    Finally model should be : ["A","B","C"]

**Comment by aitboudad** [comment]
we solved that differently, pass `true` to `uniqueItems`:

![Selection_073](https://user-images.githubusercontent.com/1753742/145100994-8afb66c9-368a-4ab8-b67b-e0c54f22da47.png)

**Comment by abhihotmail** [comment]
Thanks. I will try and let you know. One more doubt is if I wanna navigate from child to parent in Json schema, is it mandatory to define like this "templateOptions.disabled": "field.parent.parent?.parent?.model?.type==='A'"?

**Comment by abhihotmail** [comment]
We are using bootstrap module, how can we add checkboxes on each blood group.

**Comment by aitboudad** [comment]
Using Formly format you can use `multicheckbox` type:

```ts
{
  key: 'blood'
  type: 'multicheckbox',
  templateOptions: {
    type: 'array',
  }
}
```

To do it in `json-schema` use the following solution https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527

**Comment by abhihotmail** [comment]
{
  key: 'blood'
  type: 'multicheckbox',
  templateOptions: {
    type: 'array',
  }
}

The above is not working in json schema with bootstrap module.
Do you want me to use toFieldConfig map function to iterate over child items and remove the data source and reassign ?

**Comment by aitboudad** [comment]
> Do you want me to use toFieldConfig map function to iterate over child items and remove the data source and reassign ?

yes
