### ISSUE TITLE
options.onChange is not working as expected  for select

### ISSUE THREAD

**Issue by nbpro** [ngx-formly/ngx-formly#3092]
`expressionProperties: {
            'options.onChange': ($viewText, $modelValue, $scope) => {
              console.log('hi');
            },
          },`

onChange event is triggered in an infinite loop even though there is no user event in the browser.

Angular : 11.0.0
"@ngx-formly/core": "^5.10.14",
"@ngx-formly/ng-zorro-antd": "0.0.1",

**Comment by aitboudad** [comment]
The issue has been already fixed in https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.26, just make sure to update Formly to the latest version.

**Comment by zzhimin** [comment]
you can also use this library：https://github.com/zzhimin/ngx-ng-zorro-formly
