### ISSUE TITLE
json schema performance issue in version 5.10.26

### ISSUE THREAD

**Issue by jomalla123** [ngx-formly/ngx-formly#3093]
I am using a very large json schema to produce a form. On version 5.10.25 this form opened up in an instant. After upgrading to 5.10.26 it now takes approx. 20 seconds. I siwitched back between 5.10.25 and 5.10.26 multiple times with every other dependency hold constant and the issue occurs only with 5.10.26.

Any idea what the reason for this could be?

**Environment**
- Angular version: 12.2.0
- Formly version: 5.10.26

**Comment by aitboudad** [comment]
maybe related to this fix https://github.com/ngx-formly/ngx-formly/pull/3080, I may need a reproduction to further check :pray: !

**Comment by aitboudad** [comment]
Feel free to leave a comment here once you've got a reproduction example.
