### ISSUE TITLE
Difficulty installing latest Formly for Angular 13

### ISSUE THREAD

**Issue by Dragonwolf** [ngx-formly/ngx-formly#3095]
Hi there,

I am quite new to the ethos and have been struggling to add Formly to my Angular 13 project.

When I execute `ng add @ngx-formly/schematics --ui-theme=bootstrap` I am met with an error after the package installation 
```
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "C:\Users\User~1\AppData\Local\Temp\ng-YmthAw\angular-errors.log" for further details.
```
I do see on the GitHub page that Angular 13 is supported when using `@ngx-formly/core@6.x ` but when executing the first command I see that the package installed is `@ngx-formly/schematics@5.10.26` might this be an issue? I also see that nothing is added to the AppModule with regards to Formly.

In my error logs, I see files and in investigating the files, I do not see mention of the 'id' the error speaks of.

Am I doing something incorrectly? Please assist.

My package versions.
```
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
```
Error Logs:
```
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (C:\WorkfolderLocation\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (C:\WorkfolderLocation\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at C:\WorkfolderLocation\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\WorkfolderLocation\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\WorkfolderLocation\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\WorkfolderLocation\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\WorkfolderLocation\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\WorkfolderLocation\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\WorkfolderLocation\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\WorkfolderLocation\node_modules\ajv\dist\compile\codegen\index.js:568:18)
```

**Comment by Dragonwolf** [comment]
I have figured out where the version numbers of Formly are and attempted to add @ngx-formly/core@6.0.0-next.6 but now I am confronted with (what I assume is a warning, it's in red though) `The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.`

Would this pose any serious complications down the line?

**Comment by aitboudad** [comment]
a stable version of `V6` is not released yet, try with `next` tag instead:

```
ng add @ngx-formly/schematics@next --ui-theme=bootstrap
```

**Comment by Dragonwolf** [comment]
Thank you very much for the response.

I think this may just work, I've seen that it updates the AppModule now.  I'll have to do some more digging to make sure that it is working 100% in terms of it still being under development. But I think it will work. 

Thank you again.
