### ISSUE TITLE
How to use Material Autocomplete with inline options and no external functions

### ISSUE THREAD

**Issue by digeomel** [ngx-formly/ngx-formly#3096]
Hello, the example for the Material Autocomplete here: https://formly.dev/ui/material defines the options (`states`) and some required methods (`filterStates`) outside the Formly configuration (`fields: FormlyFieldConfig[]`). I am new to Formly so please correct me if I'm wrong, but I was under the assumption that the goal is to have the back-end drive the form UI entirely with JSON, so ideally, I would like to have those (i.e. the options and whatever functions needed) transported within the JSON.
Is this possible? Am I missing something?

**Comment by aitboudad** [comment]
Material Autocomplete is not part of our core component yet, it's a starting example that illustrates how to pass some config to the custom type, you could pass for example an URL, and inside autocomplete make an HTTP.

> but I was under the assumption that the goal is to have the back-end drive the form UI entirely with JSON, so ideally, I would like to have those (i.e. the options and whatever functions needed) transported within the JSON.

Not entirely but mostly and it's an ongoing process some steps are left for end-users to decide how they're willing to implement it, our goal is to simplify the process.

> Is this possible? Am I missing something?

We're also experimenting with some standard ways to achieve that, which you may check https://formly.dev/examples/advanced/json-schema
