### ISSUE TITLE
expressionProperties at some point is not evaluated or evaluated wrongly

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#3097]
Note the following code snippet.

```typescript
{
    key: 'pai_id_pais',
    type: 'autocomplete',
    className: 'flex-1',
    templateOptions: {
        translate: true,
        label: 'País',
        placeholder: 'Buscar',
        appearance: 'outline',
        filter: (term, handle, limit, page, orderBy) => this._countriesService.autocompleteSearch(term, handle, limit, page, orderBy),
        filterOptions: {
            keys: ['pai_nome'],
            textNoResultsFound: this._translateService.instant('Nenhum resultado encotrado para ')
        }
    },
    expressionProperties: {
        'templateOptions.required': (currentData) => {
            console.log('Check: ', this._resolveObject.check(this.currentData, '_enderecos.pes_cep'))
            return this._resolveObject.check(this.currentData, '_enderecos.pes_cep')
        }
    }
}
```

you can see that I put a console inside `'templateOptions.required`.
After I updated from version 5.10.23, it started to give problem.
As much as I return inside `templateOptions.required` false, the field remains mandatory, as if I were sending true instead of false.
see console.log

![Captura de Tela_selecionar área_20211210170402](https://user-images.githubusercontent.com/11314585/145634749-ec76c9c7-b1c1-4e98-9f41-d3955dac9343.png)

And I don't know how to reproduce this, because our application is big.

**Comment by aitboudad** [comment]
could you please test it with `v5.10.26` which is the latest version?

**Comment by GlauberF** [comment]
`v5.10.26` is the current version I'm using today.

**Comment by aitboudad** [comment]
A reproduction is needed in order to check it further.

> And I don't know how to reproduce this, because our application is big.

We're not asking for the entire codebase, just replicate the part that produces the issue using the minimum code to reproduce a `simple` example.

**Comment by aitboudad** [comment]
Feel free to leave a comment here once you've got a reproduction example.
