### ISSUE TITLE
How to add hooks and templateoptions.options in array type items in JSON schema powered form

### ISSUE THREAD

**Issue by abhihotmail** [ngx-formly/ngx-formly#3103]
I am using JSON schema as input to my form (Separate JSON file). I want to add hooks and templateOptions.options dynamically to field items and for each item inside array (repeat sections). Likewise, I tried, but it's not working.

@ngx-formly/bootstrap 5.5.13
@ngx-formly/core 5.5.13
@angular/core 9.0.5

**Comment by aitboudad** [comment]
I've provided enough info in the following issue https://github.com/ngx-formly/ngx-formly/issues/3065#issuecomment-988768157, so could you please provide me your attempt using a stackblitz example so I may be able to check it on my side.
Thanks!

**Comment by abhihotmail** [comment]
// Data structure should not be changed:
  // 1. duplicate values validation should perform only on "bloodGroupCode" property not on "active" property. As of now, formly checking both properties and deciding duplicate or not. How can I make active property to not to go under duplicate check?
  // 2. I want to remove the item which is selected in previous item. ex: If A+ is selected in 1st dropdown, then B+ only should show in next dropdown. A+ should be removed
  // 3. I need to add hooks (onchange|click etc) to each item inside array ( i mean select element )

https://stackblitz.com/edit/angular-multi-step-json-schema-l1dthy?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
here is the solution: https://stackblitz.com/edit/angular-multi-step-json-schema-ypnvab?file=src/app/app.component.ts
