### ISSUE TITLE
How to show validation message using JSON Schema

### ISSUE THREAD

**Issue by burjua** [ngx-formly/ngx-formly#3104]
Hello,

This is basically reopening of this issue https://github.com/ngx-formly/ngx-formly/issues/1775 

We are looking into using ngx-formly in a system where the form config will be loaded dynamically from an api in JSON format so it can't be Javascript with arrow functions. Is there a way to achieve this by using JSON Schema?

**Comment by aitboudad** [comment]
You can achieve that by using `expressionProperties`: https://stackblitz.com/edit/angular-qcw7vl?file=src/app/app.component.ts

need to check it further as I'm noticing some issues related to that solution.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.29](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.29) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
