### ISSUE TITLE
could not load iframe in template

### ISSUE THREAD

**Issue by rubinim95** [ngx-formly/ngx-formly#3105]
template: `<iframe width="100%" height="500" id="myIframe" #myIframe  src="http://localhost:4200/" ></iframe> . i'm trying to load this formly template ..but i cannot see the iframe

**Comment by aitboudad** [comment]
Pass `true` to `safeHtml`:

```patch
{
  template: `...`,
+ templateOptions: { safeHtml: true }
}
```

Other solutions that you can use are:
- custom field type https://formly.dev/guide/custom-formly-field
- inline field type (V6 only) https://github.com/ngx-formly/ngx-formly/issues/2086#issuecomment-584847953
