### ISSUE TITLE
access a custom field type properties

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#3106]
I have a custom formly field type and I want to access its properties via a template reference

custom-field-type.html
```
<div #customField> example </div>
```

in my app component
```
@component({...})
export AppComponent{
  @viewChild('customField') customField:any;
  
  constructor(){
     console.log(this.customField); //<---- undefined
}
}
```

also in your example for [firmly stepper](https://formly.dev/examples/advanced/multi-step-form) I want to access the variables `step`, `index` and `last` from the host component

use case: I want to move the `next` and `previous` buttons outside the stepper component, i.e the host component will handle them.

**Comment by aitboudad** [comment]
`ViewChild` instance is available only after `AfterViewInit`:

```ts
@component({...})
export AppComponent{
  @viewChild('customField') customField:any;
  
  ngAfterViewInit(){
    console.log(this.customField); //<---- undefined
  }
}
```

> use case: I want to move the next and previous buttons outside the stepper component, i.e the host component will handle them.

`ngTemplateOutlet` would do the job, we've done a similar approach for material prefix & suffix: https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/material/form-field/src/form-field.wrapper.ts#L70-L72
