### ISSUE TITLE
Cannot find control with name

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#3107]
I'm trying to create a custom formly field type, with `<mat-tree>` of checkboxes, but I got an error 
```
Error: Cannot find control with name: 'Fruits'
```

please note that the tree data is dynamically created and doesn't be known at compile time

[minimal reproduction](https://stackblitz.com/edit/angular-ivy-bqv8bm?file=src%2Fapp%2Fformly-tree%2Fformly-tree.component.html)

**Comment by aitboudad** [comment]
You don't have to use `FormGroup` else you need to pass the tree config to Formly or create it based on the passed model.
Instead, I suggest relying on `FormControl`  and use `(change)` to update the selected items.

to have an idea see how we did for multi-checkbox type https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/multicheckbox/src/multicheckbox.type.ts

**Comment by eng-dibo** [comment]
it worked,
but there is another issue using `<mat-tree>` inside `<mat-stepper>`

I used [your example](https://formly.dev/examples/advanced/multi-step-form) form multi-step form, and added a custom field type which is a `<mat-stepper>`

when I try to  `this.formControl.setValue()` inside `ngOninit()` I got `There are no form controls registered with this group yet`, I know it may be solved using `setTimeout` but I want to avoid this bad practice.

[minimal reproduction](https://stackblitz.com/edit/angular-yodgeg?file=src%2Fapp%2Fformly-tree%2Fformly-tree.component.ts)



it seems that this error doesn't occur in these cases:
1- using `<mat-tree>`  without mat-stepper
2- using a custom field inside mat-stepper but not mat-tree. [this one](https://stackblitz.com/edit/angular-yodgeg?file=src%2Fapp%2Fformly-custom-field.ts) worked
