### ISSUE TITLE
Nebular theme Autocomplete with options containing object (not working)  vs string (working)

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#3109]
@aitboudad 
**Question**

I am trying to send an array of objects in options using Nebular theme AutoComplete component and for some reason it does not seem to work.

It works fine when I send an array of strings.

Any thoughts on what I could be doing wrong?

My custom Autocomplete component is

```html

    template: `
    <input
        nbInput
        type="text"
        [formControl]="formControl"
        [formlyAttributes]="field"
        [required]="to.required"
        [placeholder]="to.placeholder"
        [disabled]="to.disabled"
        [status]="showError ? 'danger' : 'info'"
        [nbAutocomplete]="autoControl"/>
        
<!--  the below commented code works fine for array of strings  -->
        <!-- <nb-autocomplete #autoControl >
          <nb-option
          *ngFor="let value of filter | async"
          [value]="value">
          {{ value }}
          </nb-option>
        </nb-autocomplete>  -->

<!-- When I send array of objects, the options are populate properly, but autocomplete does not work -->
         <nb-autocomplete #autoControl  >
        <nb-option
        *ngFor="let option of filter | async"
        [value]="option">
        {{ option.label }}
        </nb-option>
    </nb-autocomplete>
`,
    styles: [],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
```
```javascript
export class FormlyNbAutoCompleteComponent extends FieldType implements OnInit/*, AfterViewInit*/ {

    public filter: Observable<any>;

    public ngOnInit(): void {
        this.filter = this.formControl.valueChanges.pipe(
            startWith(''),
            /** works for array of strings*/
            // switchMap((term) => this.to.filter(term)),

           /** works for array of objects*/
            switchMap((term) => this.to.filter(term.label)),
        );
    }
```

FormlyFieldConfig where I use Autocomplete contains
```javascript

// const modelNames = ['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',]

   const modelNames = [
     { value: 'Alabama', label: 'Alabama'},
     { value: 'Alaska', label: 'Alaska'},
     { value: 'Arizona', label: 'Arizona'},
     { value: 'Arkansas', label: 'Arkansas'},
     { value: 'California', label: 'California'},
     ]

          fieldGroupClassName: "row",
          fieldGroup: [
            {
              type: "nbautocomplete",  
              key: "deviceTypeUuid",
              className: "col-12 col-md-6 col-lg-3",
              templateOptions: {
                multiple: false,
                filter:  (term) => of(term ? this.filterModelName(term) : modelNames.slice()),
                filerKeys: ['value'],
                label: "Device Model",
                placeholder: "Select Device Template",
              },


  filterModelName(name: string) {
    if (typeof name !== 'string' && typeof name !== 'number') {
      return null;
  }
    return modelNames.filter(modelName =>
      /** Array of Strings*/
      // modelName.toLowerCase().indexOf(name.toLowerCase()) === 0);

     /** Array of Objects*/
      modelName.label.toLowerCase().indexOf(name.toLowerCase()) === 0);
  }
```

**Comment by argupta23** [comment]
@aitboudad 

I created a stackblitz around the issue

[https://stackblitz.com/edit/github-owd65f-mv5bnb](https://stackblitz.com/edit/github-owd65f-mv5bnb)

**Comment by aitboudad** [comment]
> I created a stackblitz around the issue
> stackblitz.com/edit/github-owd65f-mv5bnb

The provided `stackblitz` link is not working, could you please check it on your side.

**Comment by argupta23** [comment]
@aitboudad 

The stackblitz link seems to be working from my side. I have noticed that it takes longer to load.

**Comment by argupta23** [comment]
@aitboudad 
I figured out the mistake I was making.
Thanks for taking the time to look into the issue.

**Comment by nouramine878** [comment]
can you send me please the code that you maintain to solve this probleme,
i face the same probleme and i struggled for find a solution but i can't find a solution please send me the correct code for resolving this problem

**Comment by nouramine878** [comment]
> @aitboudad I figured out the mistake I was making. Thanks for taking the time to look into the issue.
can you send me please the code that you maintain to solve this probleme,
i face the same probleme and i struggled for find a solution but i can't find a solution please send me the correct code for resolving this problem

**Comment by argupta23** [comment]
> can you send me please the code that you maintain to solve this probleme, i face the same probleme and i struggled for find a solution but i can't find a solution please send me the correct code for resolving this problem


@nouramine878 

I have moved away from nebular, looking back into my old code, this is what I had. Hope this helps you.

The custom type for nebular autocomplete  would look something like this....

```html
import { Component, ViewChild, ChangeDetectionStrategy, AfterViewInit, OnInit } from '@angular/core';
import { FieldType } from '@ngx-formly/core';
import { Observable } from 'rxjs';
import { map, startWith, switchMap } from 'rxjs/operators';

@Component({
    selector: 'ngx-nbautocompletetype',
    template: `
    <span 
    *ngIf="to.tooltip" 
    class="help-text-icon" 
    placement="right" 
    nbTooltip={{to.tooltip}} >?
    </span>
    <input
        nbInput
        fullWidth
        type="text"
        [formControl]="formControl"
        [formlyAttributes]="field"
        [required]="to.required"
        [placeholder]="to.placeholder"
        [disabled]="to.disabled"
        [status]="showError ? 'danger' : 'info'"
        [nbAutocomplete]="autoControl"/>
        <nb-autocomplete #autoControl  >

        <nb-option
        *ngFor="let option of filter | async"
        [value]="option.value">
        <nb-icon [icon]=option.icon pack="font-awesome"></nb-icon>
        {{ option.label }}
        </nb-option>
    </nb-autocomplete> 
`,
    styles: [],
    changeDetection: ChangeDetectionStrategy.OnPush,
})


// Array of Strings
// <!--        <nb-autocomplete #autoControl >
// <nb-option
// *ngFor="let value of filter | async"
// [value]="value">
// {{ value }}
// </nb-option>
// </nb-autocomplete>  -->

// Array of Objects
// <nb-autocomplete #autoControl  >
// <nb-option
// *ngFor="let option of filter | async"
// [value]="option.value">
// {{ option.label }}
// </nb-option>
// </nb-autocomplete> 

export class FormlyNbAutoCompleteComponent extends FieldType implements OnInit {

    public filter: Observable<any>;

    public ngOnInit(): void {
        this.filter = this.formControl.valueChanges.pipe(
            startWith(''),
            switchMap((term) => this.to.filter(term)),
            // switchMap((term) => this.to.filter(term.label)),
        );
        console.log(this.filter)
    }

}
```

**Comment by nouramine878** [comment]
@argupta23  thanx u for your help it's really helpful

**Comment by nouramine878** [comment]
> > can you send me please the code that you maintain to solve this probleme, i face the same probleme and i struggled for find a solution but i can't find a solution please send me the correct code for resolving this problem
> 
> @nouramine878
> 
> I have moved away from nebular, looking back into my old code, this is what I had. Hope this helps you.
> 
> The custom type for nebular autocomplete would look something like this....
> 
> ```
> import { Component, ViewChild, ChangeDetectionStrategy, AfterViewInit, OnInit } from '@angular/core';
> import { FieldType } from '@ngx-formly/core';
> import { Observable } from 'rxjs';
> import { map, startWith, switchMap } from 'rxjs/operators';
> 
> @Component({
>     selector: 'ngx-nbautocompletetype',
>     template: `
>     <span 
>     *ngIf="to.tooltip" 
>     class="help-text-icon" 
>     placement="right" 
>     nbTooltip={{to.tooltip}} >?
>     </span>
>     <input
>         nbInput
>         fullWidth
>         type="text"
>         [formControl]="formControl"
>         [formlyAttributes]="field"
>         [required]="to.required"
>         [placeholder]="to.placeholder"
>         [disabled]="to.disabled"
>         [status]="showError ? 'danger' : 'info'"
>         [nbAutocomplete]="autoControl"/>
>         <nb-autocomplete #autoControl  >
> 
>         <nb-option
>         *ngFor="let option of filter | async"
>         [value]="option.value">
>         <nb-icon [icon]=option.icon pack="font-awesome"></nb-icon>
>         {{ option.label }}
>         </nb-option>
>     </nb-autocomplete> 
> `,
>     styles: [],
>     changeDetection: ChangeDetectionStrategy.OnPush,
> })
> 
> 
> // Array of Strings
> // 
> 
> // Array of Objects
> // <nb-autocomplete #autoControl  >
> // <nb-option
> // *ngFor="let option of filter | async"
> // [value]="option.value">
> // {{ option.label }}
> // </nb-option>
> // </nb-autocomplete> 
> 
> export class FormlyNbAutoCompleteComponent extends FieldType implements OnInit {
> 
>     public filter: Observable<any>;
> 
>     public ngOnInit(): void {
>         this.filter = this.formControl.valueChanges.pipe(
>             startWith(''),
>             switchMap((term) => this.to.filter(term)),
>             // switchMap((term) => this.to.filter(term.label)),
>         );
>         console.log(this.filter)
>     }
> 
> }
> ```

thanx for your support @argupta23  it's really helpful to me
