### ISSUE TITLE
Disabling drop down options inside array type: not disabling the element options but background field config is showing with disabled attribute

### ISSUE THREAD

**Issue by abhihotmail** [ngx-formly/ngx-formly#3110]
I have to disable the selected items in the array or items in formly (JSON schema powered). I added functionality in mapFunction and I achieved. but the previous select item is not disabling the option we disabled.

      public mapFun(
           mappedField: FormlyFieldConfig,
         mapSource: JSONSchema7 & MySchema
        ): FormlyFieldConfig {
   
    mappedField.hooks = mappedField.hooks || {};
    mappedField.hooks.onInit = (field?: FormlyFieldConfig): void => {
     
      const countryCodeField= field.key == "countryCode" ? field : null;
      if (countryCodeField) {
        countryCodeField.hooks = countryCodeField.hooks || {};
        countryCodeField.formControl.valueChanges
          .pipe(distinct((v) => v))
          .subscribe(selectedItem => {
            // Disable the country  code in MASTER ITEMS
                        field.options.formState.MASTERITEMS.map((f: { label: string, value: number, disabled?: boolean }) => {
            

              f.disabled = selectedItem == f.value ? true : f.disabled;
            });

          });

      }
---------
JSON FILE:

                  "templateOptions.options": "formState.MASTERITEMS",

------
Image attached:

![image](https://user-images.githubusercontent.com/36687981/146902397-fdd65fdc-467d-4186-be11-a3546e42bd2d.png)

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction using `stackblitz` starter example
Thanks!
