### ISSUE TITLE
`FormlyDatepickerTypeComponent` is not listed as apart of the Formly Public API

### ISSUE THREAD

**Issue by vitale232** [ngx-formly/ngx-formly#3116]
**Description**
The `FormlyDatepickerTypeComponent` type is not exported from [`@ngx-formly/material/datepicker`](https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/datepicker/src/public_api.ts).

It appears the built-in types are re-exported for the other Material types (e.g. [select](https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/select/src/public_api.ts), [checkbox](https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/checkbox/src/public_api.ts)) . This appears to be present in both the `v5` branch and `main`. It's affecting my ability to extend the type and re-write the template.

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formly-ui-material-ejvkjo?file=src%2Fapp%2Fcustom-datepicker%2Fcustom-datepicker.component.ts

**Your Environment**

- Angular version: 13.1.0
- Formly version: ^5.10.27

**Additional context**
I think this is simply an oversight, but if not, can you please provide an explanation as to why this particular type is private?

Also, here's another star :-) ⭐

**Comment by aitboudad** [comment]
Would you like to provide a PR? Also `FormlyToggleTypeComponent` is missing as mentioned here https://github.com/ngx-formly/ngx-formly/issues/3094#issuecomment-991962538

For naming:
- FormlyFieldToggle
- FormlyFieldDatepicker

**Comment by vitale232** [comment]
Yes! I'd like to provide something. Should I PR `v5`, `main`, both?

**Comment by aitboudad** [comment]
> Yes! I'd like to provide something. Should I PR v5, main, both?

`V5`

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.28](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.28) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
