### ISSUE TITLE
Radio button options do not update with ngx-translate

### ISSUE THREAD

**Issue by hassanrashid725** [ngx-formly/ngx-formly#3120]
⭐⭐⭐

**Description**
I am using ngx-translate but the radio button options do not update when language is changed.
I can see in the console that the translations are working fine but the radio button options do not change.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-k8dzcs-c2avjr?file=src/app/app.component.ts

**Your Environment**

- Angular version: 7.2.15
- Formly version: 5.10.27

**Additional context**
### **Problem:**

**The radio button options do not change when a different language option is selected.**

![image](https://user-images.githubusercontent.com/44922051/148406325-854f0d1a-a832-4d94-8352-d3a759d01fd0.png)

![image](https://user-images.githubusercontent.com/44922051/148406385-dc748d0f-9c81-47f9-a83b-d48e0558f6ea.png)

### **Desired Behavior:**

**The radio button options should update when a different language option is selected.**

![image](https://user-images.githubusercontent.com/44922051/148406888-f79698b8-7bde-4973-b62a-11fa66655838.png)

![image](https://user-images.githubusercontent.com/44922051/148407192-5a6185c1-97c8-4aab-bdd2-d55704c7c89c.png)

@aitboudad Can you please help? I would really appreciate it if you can look into this. Thank you very much.

**Comment by aitboudad** [comment]
You should override options in order to let Angular detect your changes, also better define `testingFields` as a function
https://stackblitz.com/edit/angular-k8dzcs-fsrsau?file=src/app/view-formly.ts
