### ISSUE TITLE
Validation is not working when using several formly-form

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#3121]
**Description**
I know that I don't use Formly like exepected but I need to use several `formly-form` within my form to display informations below some fields.
And when I do that, the validation only works for the last `formly-form`.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-phqaf3?file=src/app/app.component.html
And click on submit. Only the last validation of the last field is triggered.

**Your Environment**

- Angular version: 7.2.16 and also with the 13.1.1
- Formly version: 5.10.27

**Additional context**
My real example to show you why I need to use several formly-form.
As you can see, only the validation of the last group of fields is triggered. The validation of the first field which is in a different fields group is not working.

![image](https://user-images.githubusercontent.com/32452023/148586684-92f6a866-f817-4322-b0eb-dce2b0244ef2.png)

**Comment by aitboudad** [comment]
That's was supported but it has some undesired behavior so I've decided to not support a such case.
So either passes a difference `form` input instance or use one `formly-form` component.

Could you please share more details about the use case, what prevents you to use one `formly-form` component.


> I need to use several formly-form within my form to display informations below some fields.

You could use one of the following solutions:
1. template:
```ts
fields = [
  { template: `...` },
]
```

2. custom field type https://formly.dev/guide/custom-formly-field (for an advanced custom type check https://formly.dev/examples/advanced/multi-step-form)
3. inline field type (V6 only) https://github.com/ngx-formly/ngx-formly/issues/2086#issuecomment-584847953

**Comment by Jukien** [comment]
Thank you @aitboudad for your quick response.

I can't use template to place fields like I want or do css stuff like use icon with angular-fontawesome.
I need this freedom for placing my elements. Furtheremore for me field type must remain the most standard to be reused.

Here the full form:

![image](https://user-images.githubusercontent.com/32452023/148688244-c45a9557-8274-45ab-9843-6b4fa4ce6a19.png)

and the HTML code:
```
<form [formGroup]="form" (ngSubmit)="onSubmit(model)">
  <div class="row g-0">
    <div class="col-5">
      <div class="modal-body">
        <formly-form [form]="form" [fields]="fieldsLeft" [model]="model"></formly-form>
      </div>
    </div>
    <div class="col-7">
      <div class="modal-header border-bottom-0">
        <h5 class="modal-title">New<span *ngIf="null != model.study"> {{model.study.acronym}}</span></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" (click)="activeModal.dismiss('Cross click')"></button>
      </div>
      <div class="modal-body py-0">
        <formly-form [form]="form" [fields]="fieldsStudyAndParticipant" [model]="model"></formly-form>
        <ul class="list-unstyled">
          <li class="d-flex" *ngFor="let appointmentParticipantUser of model.appointmentParticipantUsers">
            <div class="me-auto"><fa-icon [icon]="['fas', 'user']" class="me-2"></fa-icon>{{appointmentParticipantUser.user.fullName}}<span *ngIf="!appointmentParticipantUser.user.fullName">{{appointmentParticipantUser.user.email}}</span></div>
            <div>
              <span class="badge rounded-pill bg-danger ms-2 fw-normal"
                    *ngIf="appointmentParticipantUser.user.conflictMessage">{{appointmentParticipantUser.user.conflictMessage}}</span>
            </div>
            <button type="button" class="btn-icon text-muted ms-3" (click)="removeAppointmentParticipantUser(appointmentParticipantUser)"><fa-icon [icon]="['fas', 'times']"></fa-icon></button>
          </li>
        </ul>

        <formly-form [form]="form" [fields]="fieldsLocation" [model]="model"></formly-form>
        <ul class="list-unstyled">
          <li class="d-flex" *ngFor="let appointmentParticipantLocation of model.appointmentParticipantLocations">
            <div class="me-auto"><fa-icon [icon]="['fas', 'door-open']" class="me-2"></fa-icon>{{appointmentParticipantLocation.location.name}}</div>
            <div>
              <span class="badge rounded-pill bg-danger ms-2 fw-normal" *ngIf="appointmentParticipantLocation.location.conflictMessage">{{appointmentParticipantLocation.location.conflictMessage}}</span>
            </div>
            <button type="button" class="btn-icon text-muted ms-3" (click)="removeAppointmentParticipantLocation(appointmentParticipantLocation)"><fa-icon [icon]="['fas', 'times']"></fa-icon></button>
          </li>
        </ul>

        <formly-form [form]="form" [fields]="fieldsComment" [model]="model"></formly-form>
      </div>
      <div class="modal-footer border-top-0" ngbAutofocus>
          <button type="submit" class="btn btn-sm btn-primary">Enregistrer</button>
          <button type="button" class="btn btn-sm btn-light" data-bs-dismiss="modal" (click)="activeModal.close('Close click')">Annuler</button>
      </div>

<!--      <pre>{{model | json}}</pre>-->
    </div>
  </div>
</form>
```

I tried with several forms, I think it could work. Need to test further but the validation of each formly-form is trigger now.

I don't know if you are going to add the functionality to formly but I was hoping when I saw an another issue on the same thing.

**Comment by aitboudad** [comment]
You can achieve that using one single `formly-form` component by combining the following solutions:

- Bootstrap grid: https://formly.dev/examples/bootstrap-specific/advanced-layout
- Participants: [Repeat section](https://formly.dev/examples/advanced/repeating-section)
- Modal: by using [wrappers](https://formly.dev/examples/other/nested-formly-forms)


> I need this freedom for placing my elements.

I understand the need for flexibility and that's the main purpose of the inline field type (V6 only) https://github.com/ngx-formly/ngx-formly/issues/2086#issuecomment-584847953 which you could give it a try as well.

**Comment by Jukien** [comment]
Thank you @aitboudad for your response.

I think inline field type could be the right solution. I haven't try yet but I will inform you if it's fill my needs.

Thank you again!

**Comment by aitboudad** [comment]
Great, just an additional hint that that may be useful when dealing with child fields: `formly-field` component and `get` method:

```html
<formly-field [field]="field.get('address')"></formly-field>
```
