### ISSUE TITLE
oneOf select change when an item is added in a sub array

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3124]
**Description**

**Minimal Reproduction**

https://stackblitz.com/edit/angular-4cslvk-ng47fh?file=package.json

- click the further link
- Select "Values Object"
- add an item
- the one if is back to "Name" (it should not)

**Your Environment**

- Angular version: X.Y.Z
- Formly version: 5.10.28

**Additional context**
This is a new bug since the version 5.10.26.

**Comment by aitboudad** [comment]
> the one if is back to "Name" (it should not)

the last step is not clear

**Comment by jma** [comment]
> > the one if is back to "Name" (it should not)
> 
> the last step is not clear

When we add a new item the selection of the oneOf is changed from "Values Object" to "Name".

**Comment by jma** [comment]
Let me know if it still not clear. Thanks a lot.

**Comment by aitboudad** [comment]
It's clear now, thanks!

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.10.29](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.29) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
