### ISSUE TITLE
Pass image selected in File Input / stored in backend, to a separate Custom type for preview

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#3127]
@aitboudad 

**Question**
It is related to one of my previous questions around file input.

While I have been successful in selecting and storing the image using File input to a database, I am not sure how I can show a preview of the selected / saved file in a formly form.

I have created a custom type for the preview (image-preview.type.ts)
```javascript

<div class="image-wrapper">
  <img src="{{ to.src }}" />
</div>

export class FormlyImagePreviewComponent extends FieldType implements OnInit {
  ngOnInit(){
    console.log(this.to)
  }
}
```

I have two scenarios in mind here that I would like to achieve.

Scenario 1
1. It is a new form with two inputs
2. File Input and Preview Input

Scenario 2
1. Form is in edit mode.
2. we get the image data from backend in the Preview Input field.

```javascript
      fieldGroup: [
/*** this is my file upload part
        {
          type: "file",
          key: "avatar",
          // wrappers: ['form-field-horizontal'],
          className: "col-12 col-md-3",
          templateOptions: {
            label: "Select Avatar",
            type: "object",
            accept: ".jpg,.png",
/*** here I get a base64 encoded data of the selected file and I assign that to the below field.
            onUploadChange: ($event) => this.modelUserProfile.image64 = $event,

/*** In create mode, I can see the model getting updated with the selected file data,
/*** How do I pass that data to key "image64" for it to populate and update "templateoptions.src" for it to send to the custom type above????

          },
        },

/*** this is my preview part
        {
          type: "image",
          key: "image64",
          className: "col-12 col-md-6",
          templateOptions: {
            label: "Selected Image",
/*** If I uncomment the below line containing hardcoded data,  I can see the image within the form for this field.
            // src: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyBAMAAADsEZWCAAAAG1BMVEVEeef///+4zPaKq/ChvPPn7vxymu3Q3flbieqI1HvuAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAQUlEQVQ4jWNgGAWjgP6ASdncAEaiAhaGiACmFhCJLsMaIiDAEQEi0WXYEiMCOCJAJIY9KuYGTC0gknpuHwXDGwAA5fsIZw0iYWYAAAAASUVORK5CYII="
          },
      ],

```

How do I pass the selected file / backend file data to the ImagePreview custom type?

Appreciate the help.

Thanks

**Comment by aitboudad** [comment]
My preference is to show the image preview inside the `file` type, and in edit mode, you'll get the value from the model (`formControl.value`). Also to assign the new file you may use `formControl.setValue()` and Formly will update the model will update accordingly without the need of `onUploadChange`.
But in case you want to have a separate type for preview, use one of the following solutions:

1. use the same key to get updated whenever the file value changes (suitable for Scenario 1 & Scenario 2 ):
```ts
{ type: 'image', key: 'avatar' }
```

2. pass the new value through `onUploadChange`:

```ts
onUploadChange: ($event) => this.fields.find(f => f.key === 'image').templateOptions.src = $event,
```

3. use formState: https://formly.dev/examples/form-options/form-state
