### ISSUE TITLE
How can I trigger asyncValidator by custom event?

### ISSUE THREAD

**Issue by 10229428** [ngx-formly/ngx-formly#3128]
**How can I trigger asyncValidator by custom event?**

In the demo, the validator wiil be triggered by updateOn property config.
![image](https://user-images.githubusercontent.com/42016535/149312303-32a6dc77-b37b-4ab1-a1c0-1b8104e8d824.png)

But, I want the validator can be triggered by my costom event, for example, when click a button in the page:
![image](https://user-images.githubusercontent.com/42016535/149330336-75c41795-a115-439d-8914-30b0c601f710.png)

Thanks!

**Comment by aitboudad** [comment]
can you try with `updateValueAndValidity`:

```ts
field.formControl.updateValueAndValidity()
```

**Comment by 10229428** [comment]
> can you try with `updateValueAndValidity`:
> 
> ```ts
> field.formControl.updateValueAndValidity()
> ```

Ok ,thanks! I will try it.

And I have another question, can you help me to check?
I want to submit form manually. But, when I click submit outside form, the model not updated, and the validator is not triggered too. I submit by these codes:
```
this.form.markAsTouched();
(this.myForm as any).submitted = true;
```
is this the right way？

The demo:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-d4fmhl
