### ISSUE TITLE
Two column layout without formly bootstrap

### ISSUE THREAD

**Issue by mithunvenkatesh18** [ngx-formly/ngx-formly#3129]
Hello,

I would like to achieve a two column layout using ngx-formly but without using bootstrap

**What I want is a form which is something like in the image below**  
![image](https://user-images.githubusercontent.com/62587635/149332508-0562bb20-dfe2-4259-81a7-5725d66b9ce3.png)

**But what I'm getting is** 
![image](https://user-images.githubusercontent.com/62587635/149333014-c9c568f8-addb-40a8-bf91-386d39217dd7.png)

**Stackblitz link to what I've tried**:https://stackblitz.com/edit/angular-material-ngx-formly-zgm3mp?file=src%2Fapp%2Fapp.component.ts

Can anyone please provide inputs how I can achieve my expected result?

**Comment by aitboudad** [comment]
There is an example in our website that you may check https://formly.dev/examples/other/advanced-layout-flex

**Comment by mithunvenkatesh18** [comment]
I've already checked that and my requirement is different to the example shared. 
Can you please have a look at the stackblitz illustration that I've shared and provide solution?

**Comment by mithunvenkatesh18** [comment]
The custom template loops through the fieldArray and tries to render each field type

HTML
```
<ng-template>
        <formly-field [field]="getField(item)"></formly-field>
</ng-template>
```

ts
```
getField(field: FormlyFieldConfig): FormlyFieldConfig {
    return field;
  }
```

**Comment by mithunvenkatesh18** [comment]
Hello,

```
<ng-template>
        <formly-field [field]="item"></formly-field>
</ng-template>
```
The above html code is not rendering the field and I can't seem to figure out why
Would really appreciate any help I can get

**Comment by aitboudad** [comment]
here is an example: https://stackblitz.com/edit/angular-material-ngx-formly-pthnby?file=src/app/vertical-grid/opx-form-vertical-grid.component.html
