### ISSUE TITLE
select type: async update of options doesn't check/reset model

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#3131]
When options are asynchronously updated for a formly select type (bootstrap) the model value is not checked to exist within the new options. The model contains an old non-existing option value.

I am unfamiliar how HTML/Browser has this implemented (e.g. per JavaScript or jQuery).

- Will they reset the select input value? 
- When yes, this might need an enhancement as it is not recognized by the formly select type (or formControl) ?
- Or the application itself is responsible to solve this situation (e.g. tap the observable, check the existence of the value within the options, call patchValue). 

Thanks for your opinion.

**Comment by aitboudad** [comment]
It's a validation issue, ideally, the sync should be done during the delete of that option so purely a backend task.

Anyway IMO the application is responsible to solve the situation which can be solved by one of the following solutions:
- Check the existence of the value within the options, call patchValue as suggested above
- Define a custom validation that checks if the selected option exists in select options
- Save the selected option as an object, so the user may still save that option.
