### ISSUE TITLE
json-schema - ERROR Error: [Formly Error] The type "string" could not be found

### ISSUE THREAD

**Issue by digeomel** [ngx-formly/ngx-formly#3132]
Hello, I'm trying to replicate the examples from json-schema in my own app, and I'm getting the following error in console:

`ERROR Error: [Formly Error] The type "string" could not be found. Please make sure that is registered through the FormlyModule declaration.`

I cannot find any special type definition for `string` in the examples. What am I missing?

**Update:**
I noticed that in `material/input/input.module.ts` (I'm using Material) there is this code:

```
FormlyModule.forChild({
      types: [
        {
          name: 'input',
          component: FormlyFieldInput,
          wrappers: ['form-field'],
        },
        { name: 'string', extends: 'input' },
        {
          name: 'number',
          extends: 'input',
          defaultOptions: {
            templateOptions: {
              type: 'number',
            },
          },
        },
        {
          name: 'integer',
          extends: 'input',
          defaultOptions: {
            templateOptions: {
              type: 'number',
            },
          },
        },
      ],
    }),
```

but I get the same error even after importing this module.

**Update 2:**
The only way I could find to get around this was to add the line `{ name: 'string', extends: 'input' },` in my own FormlyModule types.

**Comment by aitboudad** [comment]
If you're using `V5`, you need to explicitly define all those types (`string` ...) as pointed in our demo example https://formly.dev/examples/advanced/json-schema.

in `V6` you can skip that part as we're trying to simplify the JSON-SCHEMA integration.
