### ISSUE TITLE
How can I submit a form manually?

### ISSUE THREAD

**Issue by 10229428** [ngx-formly/ngx-formly#3133]
**How can I submit a form manually?**

I want to submit form manually. But, when I click submit outside form, the model not updated, and the validator is not triggered too. I submit by these codes:
```
this.form.markAsTouched();
(this.myForm as any).submitted = true;
```
is this the right way？ Can you help me to check?

The demo:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-d4fmhl

**Comment by aitboudad** [comment]
Use the following approach:

```ts
formElm.dispatchEvent(new Event('submit', { cancelable: true }));
```
