### ISSUE TITLE
Changing formlyModel does not change the formControl

### ISSUE THREAD

**Issue by rahulthewall** [ngx-formly/ngx-formly#3135]
I am using formly to render dynamic forms. My rendered document has several paragraphs, and on clicking each paragraph, I want to render a new formly form. The form configuration for the three paragraphs is exactly the same, I just want to collect unique values for each of the three paragraphs. 

I render the formly form thus

```
  <form [formGroup]="form" (ngSubmit)="onSubmit()" [style.maxHeight]="formMaxHeight" class="annotation-form border-top">
    <formly-form
        #formlyForm
        [form]="form"
        [fields]="modifiedFormlyConfig"
        [model]="formlyModel"
        (modelChange)="onModelChange($event)"
    ></formly-form>
  </form>
```

The relevant parts of the angular file that accompanies the template are provided below

```
export class DocumentFormSidebarComponent implements OnInit, OnChanges, AfterViewChecked {
    form: FormGroup = new FormGroup({});

    @Input() formlyConfig: FormlyFieldConfig[];
    @Input() formlyModel: any = {};
    constructor(private changeRef: ChangeDetectorRef) {}

    ngOnInit() {
        this.form.markAsUntouched();
    }

    onSubmit() {
        this.handleSubmit.emit();
        this.formStatusChange.emit(this.form.valid);
    }

    ngOnChanges(changes: SimpleChanges) {

        if (changes.formlyModel) {
            console.log(this.formlyModel);
            console.log({formControl: this.form.controls});
        }
    }

}

```

On clicking the first paragraph, I have the following two console logs. 

```
{
	"g1": {
		"key2": [{
			"highlightGuid": "e119ddd6-1487-4579-ade7-4ccff760a7ea",
			"highlightType": "TEXT",
			"elementId": "paragraph-0",
			"entityId": "0",
			"content": "Ut morbi",
			"contentType": "TEXT",
			"range": {
				"start": 525,
				"end": 533,
				"startXPath": null,
				"endXPath": null
			},
			"sortOrder": 0.3841145833333333,
			"isInitial": false,
			"isEvidence": false,
			"configId": null,
			"comment": "",
			"hidden": false
		}],
		"key1-evidence": [{
			"highlightGuid": "261d0890-eebd-40cc-9597-21ab7a5d47b0",
			"highlightType": "TEXT",
			"elementId": "paragraph-0",
			"entityId": "",
			"content": "ortor v",
			"contentType": "TEXT",
			"range": {
				"start": 242,
				"end": 249,
				"startXPath": null,
				"endXPath": null
			},
			"sortOrder": 0.13411458333333334,
			"isInitial": false,
			"isEvidence": true,
			"configId": null,
			"comment": "",
			"hidden": false
		}],
		"key1": "Para 0"
	}
}
```

The corresponding value for `form.control.g1.value` is given below

```
{
    "key1": "Para 0",
    "key1-evidence": [
        {
            "range": {
                "start": 242,
                "end": 249
            },
            "content": "ortor v",
            "comment": "",
            "hidden": false,
            "highlightGuid": "261d0890-eebd-40cc-9597-21ab7a5d47b0",
            "color": null,
            "lock": null,
            "sortOrder": 0.13411458333333334
        }
    ],
    "key2": [
        {
            "range": {
                "start": 525,
                "end": 533
            },
            "content": "Ut morbi",
            "comment": "",
            "hidden": false,
            "highlightGuid": "e119ddd6-1487-4579-ade7-4ccff760a7ea",
            "color": null,
            "lock": null,
            "sortOrder": 0.3841145833333333,
            "entityId": "0"
        }
    ]
}
```

This is as expected. However, when I switch to the second paragraph, my formly Model is

```
{ }
```

However, the corresponding value of form.control.g1.value is 

```
{
    "key1": undefined,
    "key1-evidence": [
      {
        "range": {
          "start": 242,
          "end": 249
        },
        "content": "ortor v",
        "comment": "",
        "hidden": false,
        "highlightGuid": "261d0890-eebd-40cc-9597-21ab7a5d47b0",
        "color": null,
        "lock": null,
        "sortOrder": 0.13411458333333334
      }
    ],
    "key2": [
      {
        "range": {
          "start": 525,
          "end": 533
        },
        "content": "Ut morbi",
        "comment": "",
        "hidden": false,
        "highlightGuid": "e119ddd6-1487-4579-ade7-4ccff760a7ea",
        "color": null,
        "lock": null,
        "sortOrder": 0.3841145833333333,
        "entityId": "0"
      }
    ]
  }
```

So while key1 does get reset, the other two fields are not reset. 

Could someone please guide me in how I go about debugging this? I am lost.

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by rahulthewall** [comment]
Hi, 

Reproduction would be rather hard here, as there are multiple components in place. There is a separate component that renders the HTML template (the one with paragraphs to click that change the form), another that renders the form, and the form components are custom. I will also have to strip the code to comply with NDAs and at that point it probably won't be the same code anymore. 

I know this doesn't help, but could you please perhaps have a few ideas on how I go about debugging this?

The form components that are encapsulated by key1, key1-evidence and key2 are all custom components. key1 is just a simple string, the other are arrays. But why the array ones are not reset when the form changes? 

Is there a callback (or similar) that I can hook into to force a custom update of formControl when the formlyModel changes?

**Comment by aitboudad** [comment]
well, it's even hard for me to understand the wrong part without looking at the code :smile: , I'm asking for a minimal reproduction example not the full app.

> The form components that are encapsulated by key1, key1-evidence and key2 are all custom components. key1 is just a simple string, the other are arrays. But why the array ones are not reset when the form changes?

try to pass a new instance of `form`, to avoid any collision:
```patch
    ngOnChanges(changes: SimpleChanges) {
        if (changes.formlyModel) {
+           this.form = new FormGroup({});
            console.log(this.formlyModel);
            console.log({formControl: this.form.controls});
        }
    }
```

**Comment by rahulthewall** [comment]
I tried that, and that didn't work. I will work on a recreation and get it to you.

**Comment by aitboudad** [comment]
Feel free to leave a comment once you've got a reproduction example, thanks!
