### ISSUE TITLE
can I extract the i18n from formly source code?

### ISSUE THREAD

**Issue by ha-akelius** [ngx-formly/ngx-formly#3138]
**Question**
I want to run `ng xi18n --out-file i18n/en.xlf` but this work on html files only not ts :( 

I am following this [i18n ngx-translate](https://formly.dev/examples/advanced/i18n-alternative) example
- my goal is after running `ng xi18n`  I want to see 'FORM.LANG', 'FORM.NAME' inside the en.xlf
is there a correct way or  workaround to do this?
- do we have to use @ngx-translate

Thank you for this cool library

**Comment by aitboudad** [comment]
The [i18n ngx-translate](https://formly.dev/examples/advanced/i18n-alternative) solution is for runtime translation which is not supported yet by Angular i18n (if I'm not wrong https://github.com/angular/angular/issues/38953).

> my goal is after running ng xi18n I want to see 'FORM.LANG', 'FORM.NAME' inside the en.xlf
is there a correct way or workaround to do this?

I think using `$localize` would do the job:
```
{
  ...
  templateOptions: {
    label: $localize `FORM.LANG`,
  },
},
```

> do we have to use @ngx-translate

no, unless there is a need for runtime translation.

**Comment by ha-akelius** [comment]
Thank you 

> I think using $localize would do the job:

this solution working fine 🥇
