### ISSUE TITLE
Is it possible to transpose a ngx-datatable integrated with angular formly?

### ISSUE THREAD

**Issue by mithunvenkatesh18** [ngx-formly/ngx-formly#3141]
Hello,

I wanted to check if it was possible to transpose a ngx-datatable integrated with angular formly where the column names appear as rows and the rows(formly-fields) appear as columns?

Stackblitz link: https://stackblitz.com/edit/angular-vaschu?file=src%2Fapp%2Fdatatable.type.ts

Thanks in advance

**Comment by aitboudad** [comment]
yes, check the following example for row reorder https://stackblitz.com/edit/repeat-section-move-with-options-9e51cv?file=src/app/repeat-section.type.ts

**Comment by mithunvenkatesh18** [comment]
I checked the example you shared but I'm still wondering how I can apply this to transpose a table.
My table has contents like 
                     C1                                         C2                                  C3
        R1(formly-input fields)      R1(formly-input fields)      R1(formly-input fields)
        R2(formly-input fields)      R2(formly-input fields)      R2(formly-input fields)
   
and I want it to look like
C1    R1(formly-input fields)    R2(formly-input fields)
C2    R1(formly-input fields)    R2(formly-input fields)
C3    R1(formly-input fields)    R2(formly-input fields)

Would really appreciate if you could point me to any resource materials that could help me or if you could work up an example for my use case

Thanks
