### ISSUE TITLE
Is there any library known for build json schema templates?

### ISSUE THREAD

**Issue by ThomazAquino** [ngx-formly/ngx-formly#3142]
Hi, 
I am using JSON schema as input to my form.

I want provide a tool for the user define how the form should looks like. Something  where the user can choose the field name, the field type, the position in the form, if is required or not, etc. And in the end generate a json schema to be used on the forms.

Do you guys know if there is an open source platform who provide such feature? Or do I need to go custom on this?

**Comment by aitboudad** [comment]
you may check this tool: https://json-editor.github.io/json-editor/
