### ISSUE TITLE
Enums being mapped to Object with "value" and "label" when using json-schema

### ISSUE THREAD

**Issue by ThomazAquino** [ngx-formly/ngx-formly#3149]
Hello,
I am using Json schema to populate my form, and I notice that when I pass any value to a enum it got map to an object that have `{value: {…}, label: {…}}`:

This is my schema:

` 
  const JSONSchema = {  

    title: 'The Main title',  
    type: 'object',  
    properties: {  
    test: {  
      title: 'The title',  
      type: 'enum',  
        enum: [  
          { id: '0000001', text: 'A text for the first option', ... More props },  
        ],  
        enumNames: [  'This property seems to do anything' ],  
      },  
    },  
  };`

Somehow when redered by the select component the `fied.templateOptions.options` is getting the fallowing values:

`  [

    // First option
    {
      "value": {  "id": "0000001",  "text": "A text for the first option" },
      "label":  {  "id": "0000001",  "text": "A text for the first option" }
    },
     // Second option
     ....
  ]  `
  
  

First I thought that I could control the way that `fied.templateOptions.options` is map via `enumNames` porperty in the json schema, but so far as I can see `enumNames` does not change anything.

So my question is: 
- why my options are getting map to `{value: {…}, label: {…}}` ?
- Is there a way where I can control the way that this got mapped?
- What the `enumNames` do in the schema?

I have an stackblitz project where you can see these values:
https://stackblitz.com/edit/ngx-formly-ui-material-u8uzaa?file=src%2Fapp%2Fapp.component.ts

Thanks

**Comment by kenisteward** [comment]
1. We support Jason schema spec 7 which I believe does not have enumName ( I don't think anything after does either )

2. The schema way to control titles / values is to provide oneOf: [{ const: "value" , title: "title"}] which will in turn be processed as such by schema validators and the mapper.


3. You could also use the map function to convert your enums to what you want ( it is passed when toFormFields() is called )

I'm on my phone so I can't give better examples than this atm .

**Comment by aitboudad** [comment]
> Is there a way where I can control the way that this got mapped?

yes, see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527

`enumNames` is not implemented from our side (as pointed @kenisteward not part of json schema spec 7), `enum` is used to render a select field but nothing prevent you to adjust it to your need.
Also I would suggest to check the demo example which contains a bunch of of example that shows the implemented features:
https://formly.dev/examples/advanced/json-schema
