### ISSUE TITLE
Detecting changes to templateOptions

### ISSUE THREAD

**Issue by Lith1um** [ngx-formly/ngx-formly#3158]
I'm building a custom formly field that uses an autocomplete to set a chip list within a single formly field. Since the chips are the form value for this field, I create a formControl in the custom component to handle the text input for the autocomplete.

When the field is disabled from the start, I'm able to set the text input field to disabled in the onInit, but the problem I have is we also use expressionProperties to set the disabled state. When this disabled flag changes, the text input I created doesn't also disable since it was set in the onInit and I don't think there's a way to detect changes to the templateOptions?

The only way I can think to get around this is to create a nested component for the text input and pass the disabled flag from the templateOptions to it, so that I can use angular's onChanges hook to set the disabled state on my formControl. I'm confident that would work, but I was wondering if you know a simpler/better way to handle this?

**Comment by aitboudad** [comment]
If I clearly understood, you've create a `formControl` doesn't belong to the form (a separated instance) and at the same time you want to keep `disabled` state in sync with origin `field.formControl`.
The solution is to subscribe to the field.formControl.statusChanges

```ts
field.formControl.statusChanges.subscriber(status => {
 // disable/enable autocomplete control based on status value
})
```

**Comment by Lith1um** [comment]
Don't know how I've never come across the statusChanges property before, works great, thanks!
