### ISSUE TITLE
Validate uniqueness across a field in repeated sections

### ISSUE THREAD

**Issue by chenco5555** [ngx-formly/ngx-formly#3161]
Hi,

I have a form that is constructed with repeating sections. In each section, I have a "title" field and I need to make sure that its value is unique across all the other repeated sections. 

Is there an easy/built-in way to write such a custom validator or should I go the "manual" way and go through all the fields in the form and check for duplicates?

Thanks in advance,
Chen.

**Comment by aitboudad** [comment]
Define a custom validation using one of the solutions provided in our demo example https://formly.dev/examples/validation/custom-validation.
The solution is to define the validation in the root field (`repeat` type) so you can check the validity whenever a child field changes (`title` for example).

To show the message error in repeat type, use `formly-validation-message`:
```
<div *ngIf="showError">
  <formly-validation-message [field]="field"></formly-validation-message>
</div>
```

**Comment by shawnss** [comment]
Thanks,
Where should this be added? I don't find any documentation for it.
