### ISSUE TITLE
Repeat type by default display no fields

### ISSUE THREAD

**Issue by EjazIris** [ngx-formly/ngx-formly#3162]
**Question**

@aitboudad 
HI, I am using repeat type in my formly form, By default it is showing all the fields that I want to repeat, but my requirement is by default it does no show all the fields except add new button, 
How can I achieve this in formly, Can you please help me in resolving this requirement.

https://stackblitz.com/edit/angular-iguzew?file=src%2Fapp%2Fapp.component.ts

**Comment by henkieee** [comment]
I hope this example will help you out:
https://stackblitz.com/edit/angular-iguzew-8mu2tu?file=src%2Fapp%2Frepeat-section.type.ts

**Comment by EjazIris** [comment]
HI @henkieee 
Thank You for the reply, 
In my current project they have used repeated type in a complex, it will be difficult for me to apply this approach,
Is there any another way like a different attribute to add along with key, templateOptions, defaultValue etc.?

**Comment by aitboudad** [comment]
> but my requirement is by default it does no show all the fields except add new button,

Not sure what do you means by default here :thinking:, the repeat field is populated based on the passed model value.
In the above example the `investments` length is 1 which is the same as generated repeat fields so if you want to have `add new button` just ensure `investments` value is empty.
```patch
model = {
-  investments: [{}],
};
```

**Comment by EjazIris** [comment]
Hi @aitboudad 
Thank you for the reply
The solution provided by @henkieee  in the previous comment https://github.com/ngx-formly/ngx-formly/issues/3162#issuecomment-1025687922 is exactly my requirement, but that implementation is quite complex for me to to implement in my project,
Is there any other way achieve the same requirement.
Default means ; when the page loads it will show only add new button, after clicking on add new it will show the form fields that I want to display/repeat

**Comment by aitboudad** [comment]
The solution doesn't look complex, to make it simple you may update `to.showFields` value manually instead of using `expressionProperties`.

**Comment by aitboudad** [comment]
```ts
...
export class RepeatTypeComponent extends FieldArrayType {
  add(...args) {
    if (!this.to.showFields) {
      this.to.showFields = true;
    } else {
      super.add(...args);
    }
  }
}
```
