### ISSUE TITLE
Validate uniqueness across a field in repeated sections

### ISSUE THREAD

**Issue by chenco5555** [ngx-formly/ngx-formly#3166]
Hi,

I have a form that is constructed with repeating sections. In each section, I have a "label" field and I need to make sure that its value is unique across all the other repeated sections.

see in https://github.com/chenco5555/formly-custom-validation 
I pass the model as a parameter to 'labelUniquenessValidation' validation

  validators: {
              validation: [{name: 'labelUniquenessValidation', options: {model: this.model}}],
            },

The model is not updated when I change the label value.

Thanks in advance,
Chen.

**Comment by aitboudad** [comment]
you can get the field value through the first argument of `labelUniquenessValidation`: `control.value`
