### ISSUE TITLE
Interpolating values in ngx-translate extension

### ISSUE THREAD

**Issue by calogar** [ngx-formly/ngx-formly#3167]
Hello, thank you for this nice library. I am using ngx-translate as [the documentation](https://formly.dev/examples/advanced/i18n-alternative) suggests, in order to translate validation messages. The example works fine, however I do not know how to use the interpolate variable feature of ngx-translate in that extension. 

```
export class TranslateExtension {
  constructor(private translate: TranslateService) {}
  prePopulate(field: FormlyFieldConfig) {
    const to = field.templateOptions || {};
    if (!to.translate || to._translated) {
      return;
    }

    to._translated = true;
    field.expressionProperties = {
      ...(field.expressionProperties || {}),
      'templateOptions.label': this.translate.get(to.label),
    };
  }
}

function buildMessage(translate: TranslateService, validationName: string, translateKey: string) {
  return {
    name: validationName,
    message() {
      return translate.get(translateKey);
    },
  };
}

export function registerTranslateExtension(translate: TranslateService) {
  return {
    validationMessages: [
      buildMessage(translate, 'required', 'common.validation.required'),
      buildMessage(translate, FieldValidatorUITypes.Min, 'common.validation.min-value'),
      buildMessage(translate, FieldValidatorUITypes.Max, 'common.validation.max-value'),
    ],
    extensions: [
      {
        name: 'translate',
        extension: new TranslateExtension(translate),
      },
    ],
  };
}
```

![image](https://user-images.githubusercontent.com/19515824/151980078-3cc81866-aebf-4390-8b9e-e9f1ad5f290a.png)

Is there any way to inject the value in the message from the extension? I am not finding much information about creating custom extensions in the docs, having access to the current state of the form inside it could solve it.

**Comment by aitboudad** [comment]
we pass the validation output `(error, field)` to the  `message` function defined `buildMessage` declaration:

```ts
function buildMessage(translate: TranslateService, validationName: string, translateKey: string) {
  return {
    name: validationName,
    message(error, field: FormlyFieldConfig) {
      return translate.get(translateKey);
    },
  };
}
```

check more examples here: https://formly.dev/examples/validation/validation-message

**Comment by calogar** [comment]
Ok, so it was quite straightforward... Thank you!
