### ISSUE TITLE
Repeat validation message not displaying

### ISSUE THREAD

**Issue by shawnss** [ngx-formly/ngx-formly#3168]
**Question**

Trying to validate repeating value in my app [sample app](https://stackblitz.com/edit/angular-websyp?). User can select a column and a new name in each repeat , but the  new name should not be duplicated in other repeat  fields. The validation is defined in the root field (repeat type) and it works as the form is set to invalid when validation fails, but the message is not displayed. What am I missing? How should I define the validation message so it'll display either under "new name" or for the repeat group. Thanks in advance.

**Comment by aitboudad** [comment]
To show the message error in repeat type, use `formly-validation-message`:

```
<div *ngIf="showError">
  <formly-validation-message [field]="field"></formly-validation-message>
</div>
```

**Comment by shawnss** [comment]
Thanks, Where should this be added to? I don't find any documentation for this. added it to the repeate-section.types and still not working.

**Comment by aitboudad** [comment]
Inside `repeate-section.types`, I've checked the above provided `stackblitz` example and it seems working:

![image](https://user-images.githubusercontent.com/1753742/152200427-e686422c-53a4-4ad9-a057-f970ea26784b.png)

**Comment by aitboudad** [comment]
I made a little adjustment to the above solution see https://github.com/ngx-formly/ngx-formly/issues/3170#issuecomment-1029762431
