### ISSUE TITLE
When validator is set on a type the expression is negated

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#3169]
When validator is set on a type the expression is negated, at minimum not conform as the examples show.

https://stackblitz.com/edit/angular-mjbvnf-tbfexy?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
passing an Angular validator should be through `validation` key:

```ts
{
  name: 'ip',
  extends: 'input',
  defaultOptions: {
    validators: {
      validation: [IpValidator]
      // ip:  // 'ip' matches the ip validation message
    }
  },
},
```
