### ISSUE TITLE
How to add style for error message - formly-validation-message

### ISSUE THREAD

**Issue by nikitagawande65** [ngx-formly/ngx-formly#3170]
I am using formly-validation-message and I want to add some css style to show the error message. I have added some style class but it show the css whenever form gets invalid(for other validation) and validation message appear when we enter duplicate value in field.
The issue is - It shows the style even if duplicate validators returns false
sample app - https://stackblitz.com/edit/angular-websyp-hf2b9d?file=src/app/repeate-section.type.ts

**Comment by aitboudad** [comment]
`showError` only check the field validity, so either the field itself has errors or one of its child. The solution here is to add an additional check `showError && formControl.errors`:

```html
<div *ngIf="showError && formControl.errors" class="error-message">
  <formly-validation-message [field]="field"></formly-validation-message>
</div>
```

**Comment by nikitagawande65** [comment]
Thanks!
