### ISSUE TITLE
hideExpression error when using fieldGroup

### ISSUE THREAD

**Issue by adora-tech** [ngx-formly/ngx-formly#3172]
Hello,

I want to use fieldGroup, and at this level I want to hide fieldC, based on fieldB, using:

`hideExpression: '!model.child.fieldB',`

this returns an error, TypeError: [Formly Error] [Expression "hide"] Cannot read properties of undefined (reading 'child')

```
    {
      key: 'fieldA',
      type: 'select',
    },
    {
      key: 'child',
      fieldGroup: [
        {
          key: 'fieldB',
          type: 'select',
        },
        {
          key: 'fieldC',
          type: 'input',
          hideExpression: '!model.child.fieldB',
        },
      ],
    },
```

I use:

```
"@ngx-formly/bootstrap": "^6.0.0-next.7",
"@ngx-formly/core": "^6.0.0-next.7",
"bootstrap": "^5.1.3",
```

I need some help.

Thank you,
Iulius

**Comment by adora-tech** [comment]
I sovled this, using:

`hideExpression: 'field?.form?.get('fieldB')?.value !== 'SELECTED_VALUE''`

for string values, use backquotes `` in the example above

Thank you!
Iulius

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614
