### ISSUE TITLE
bindValue is not allowed with multiple ng select with formly

### ISSUE THREAD

**Issue by preeteeg** [ngx-formly/ngx-formly#3173]
Hi am using ngselect component in formly with multiple directive set to true. Am encountering the following error when selecting an option

> **error in console ng-select-ng-select.js:613 Binding object({"label":student","value":"12"}) with bindValue is not allowed.**

Below is the form-multiple-select-component.html
```
<ng-select
  #ngSelect
  bindLabel="label"
  bindValue="value"
  [clearable]="to.select?.clearable"
  [formControl]="formControl"
  [formlyAttributes]="field"
  [items]="to.options"
  [placeholder]="to.placeholder"
  [multiple]="to.multiple"
  [searchable]="to.select?.searchable"
  [virtualScroll]="to.select?.virtualScroll"
  (blur)="blur()"
  (keydown.delete)="clear(ngSelect)"
  (search)="search()"
>
```
Any help much appreciated , being stuck on it for a while. thank you
when I do save the following is added to the model

["01", "11",{ "label": "student", "value": "12"}] instead of 12

Options is an observable of UiFormSelectOption
```
options: Observable<UiFormSelectOption[]>,
export interface UiFormSelectOption {
  label: string;
  value: string | number ;
}
```

**Comment by aitboudad** [comment]
Seems working to me, here is the link https://stackblitz.com/edit/angular-ntysej.
Please check the example and compare it with your implementation, in case the issue persist  I may need a reproduction :pray:.

Thanks!
