### ISSUE TITLE
bug: formly field config with '' vs undefined returns different values in @ngx-formly@6.0.0

### ISSUE THREAD

**Issue by dereekb** [ngx-formly/ngx-formly#3175]
**Description**
I noticed a regression in the newest branch, @ngx-formly@6.0.0-next.7. If you put in a key as an empty string for a field that only has a fieldGroup, it differs (in an unexpected way) from having no key defined at all. In ngx-formly v5 branch it has same behavior between '' and undefined.

https://stackblitz.com/edit/ngx-formly-ui-material-jmuhqp

From app.component.ts:
```
  works = undefined;
  broken = '';

  fields: FormlyFieldConfig[] = [
    {
      key: this.broken,
      fieldGroup: [
        {
          key: 'input',
          type: 'input',
          templateOptions: {
            label: 'Input',
            placeholder: 'Input placeholder',
            required: true,
          },
        },
      ],
    },
  ];
```

At the very least I'd expect the key value to be '', but it is undefined.

With '':
```
{
"undefined": {
"input": "test 2"
}
}
```

With undefined:
```
{
"input": "test 2"
}
```

**Your Environment**

- Angular version: 13.2.2
- Formly version: 6.0.0-next.7

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.0-next.8](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-next.8) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
