### ISSUE TITLE
The data should not get saved in the model if it is invalid.

### ISSUE THREAD

**Issue by nbisht11** [ngx-formly/ngx-formly#3176]
**Problem Statement:** 
We have two fields, **_user email_** and **_user name_**, and the email has a _string pattern validation_. The email field will be **invalid** if the user enters some random strings and **not an email with proper email format**. In the application we have a **submit** button and we have a **save as draft** button to save the data of incompletely filled form.We are disabling the submit button if the form is invalid. 

Now the user tries to enter some random characters into the email field that makes the email field invalid and as the email field is invalid, the whole form is invalid and because of that the submit button will be disabled. 
But the **Save as Draft** button is still there to save the data into the database, so when we click on Save as draft, the model data will be sent to back-end. And as of now, the model is having both the valid and invalid data as well and that data is being sent to back-end to save it in the database. The feature I'm raising this issue for is: if a field is invalid, it's data should not get saved in the model.

Looking forward for your response. 

As an alternative we can enable the save as draft button only when valid data is entered, but the button should also be enabled when the form is not completely filled.

**Comment by aitboudad** [comment]
Our approach is to keep model updated even invalid ones, so the solution may depend on the case, so I see two solution that you may implement:

1. Enable the save as draft button only when valid data is entered (as mentioned above) (preferred one).
2. Define a separate model that contains the valid value only:

```ts
@Component({
  selector: 'app',
  template: `
      <formly-form [form]="form" [fields]="fields" [model]="model" (modelChange)="onModelChange($event)"></formly-form>
  `,
})
export class AppComponent {
  ...
  draftModel = {};

  onModelChange(value) {
    if (this.form.valid) {
      this.draftModel = value;
    }
  }
}
```
