### ISSUE TITLE
Async validators not running before all required fields are filled

### ISSUE THREAD

**Issue by weckonet** [ngx-formly/ngx-formly#3177]
**Description**
When there are required fields in the form, then async validator does not run until all required fields are filled. This is probably not correct (you want to validate the field at the time the person is filling it). 

Expectations: Fill a wrong password (example: **54321**) and get an error. 
Current behavior: Fill a wrong password and not get any error until you fill age as well. 

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-pwzmze?file=src/app/app.component.ts

**Your Environment**

- Angular version: 10
- Formly version: 5.10.32 (does not work on latest either)

**Additional context**

Adding a key to the asynchronously validated form group solves the issue (and will use that as a work-around for the time being). 

Is that expected behavior? It feels counter-intuitive because it works differently for synchronous validators.

**Comment by 627721565** [comment]
您好，邮件已经收到，查阅后会尽快给您回复！

**Comment by aitboudad** [comment]
That's on purpose, Async validators are called only when form state (invalid -> valid) is changed to avoid an unnecessary calls.
In the above example since the initial form state is invalid (password & age marked required), the call will be done once both fields are filled.

**Comment by weckonet** [comment]
The thing is, that the "password" field is embedded in a group, and my expectation was that it would check only for the validity of the group, as it has no reason to wait for other fields when all fields it depends on are already filled and valid. This is actually what happens when i add a key to the group (like `key: 'passwordGroup'`), so it struck me as an inconsistency, since i didn't expect this to make a difference. 

Thanks for the answer though, i can work around this by transforming the model.

**Comment by aitboudad** [comment]
when `fieldGroup` doesn't have a key we attach its children to the parent Form instance.

> i can work around this by transforming the model.

Better :+1:
