### ISSUE TITLE
How to add icon for tooltip with form field label

### ISSUE THREAD

**Issue by nikitagawande65** [ngx-formly/ngx-formly#3178]
I want to add icon and show tooltip content on hover of that icon. I tried it with addOn( templateOptions property ) but it's not working.
stackblitz example -https://stackblitz.com/edit/angular-websyp-6bngyv?file=src/app/app.component.ts
Is there any other way with formly?
![image](https://user-images.githubusercontent.com/38561323/153595957-9316fc88-4f90-4e92-9729-94a6e18f3d06.png)

Kindly reply.

**Comment by aitboudad** [comment]
if the build-in add-on isn't suitable you may define yours, its a combination of [custom wrapper](https://formly.dev/guide/custom-formly-wrapper) (to add icons) and [custom extension](https://main.formly.dev/guide/custom-formly-extension) (to apply that wrapper on all fields).

For a working example check: https://main.formly.dev/examples/other/material-prefix-suffix
