### ISSUE TITLE
custom bootstrap template not being wrapped

### ISSUE THREAD

**Issue by bobingham** [ngx-formly/ngx-formly#3183]
**Question**
- Bootstrap: https://stackblitz.com/edit/ngx-formly-ui-bootstrap
- "@ngx-formly/schematics": "^6.0.0-next.7",
- "@ngx-formly/core": "^6.0.0-next",
- "@ngx-formly/bootstrap": "^6.0.0-next"

I have implemented a date picker component using the _ngx-bootstrap_ library.
This is in v6 (which  understand is pre-release) as per versions above.
I have copied code from examples in github:
```
    <input
        #dp="bsDatepicker"
        type="text"
        class="form-control mb-3"
        id="{{field.key}}"
        placeholder="{{ field.templateOptions.placeholder}}"
        [formControl]="formControl"
        [formlyAttributes]="field"
        bsDatepicker
        [bsValue]="bsValue"
        datePickerLuxonModifier
        [bsConfig]="bsConfig"
        [class.is-invalid]="showError">
```
and my module:
```
    FormlyBootstrapModule,
    FormlyModule.forRoot({
      validationMessages: [
        { name: 'required', message: requiredValidationMessage },
        { name: 'minlength', message: lengthValidationMessage },
        { name: 'maxlength', message: lengthValidationMessage },
        { name: 'min', message: minValidationMessage },
        { name: 'max', message: maxValidationMessage },
      ],
      types: [
        { name: 'datetime', component: NgxDateTimePickerTypeComponent },
        {name: 'guidance', component: NgFormGuidanceTextTypeComponent}
      ]
    }),
    BsDatepickerModule.forRoot(),
```
However, when I run the project I can see I have no wrapper:
![image](https://user-images.githubusercontent.com/6200331/154092059-24676249-82f3-49e3-b469-5bbbc88bf4f8.png)
The _datepicker_ has no label and validation messages are not being passed.  As you can see from the image above validation messages are being passed for other inputs such as the _text_ input, _textarea_ and _select_. 
Is there something I am missing here?
Should I downgrade to v5?

**Comment by aitboudad** [comment]
you need to pass `form-field` to `wrappers` in order to use bootstrap layout:

```patch
        {
          name: 'datetime',
          component: NgxDateTimePickerTypeComponent,
+         wrappers: ['form-field'],
        },
```

**Comment by aitboudad** [comment]
> Is v6 due full release and are any breaking changes possible?

I think we're close, remain just few releases (1 or 2 which may contains some breaking changes).
