### ISSUE TITLE
How to i18n datetime months names and toolbar buttons

### ISSUE THREAD

**Issue by sergiorodriguez82** [ngx-formly/ngx-formly#3185]
Hi, We are using ionic formly for simple questionnaires that are store in our database in json format, and then render dynamically in our ionic app.
We have both english and spanish versions for the questionnaires. 
The question is how I can i18n the calendar buttons and months? This is always in english.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/38695777/154575724-ef54fd5c-9f4e-4b11-97b4-c79bdb700263.png">

Any help appreciated!
Here the fork for testing 
https://stackblitz.com/edit/ngx-formly-ui-ionic-vsqhkt?file=app%2Fapp.component.ts

**Comment by aitboudad** [comment]
`locale` is only available in ionic `v6` (which is not added yet in our codebase).

The above example refer to `v5` which you should pass the following options for each language:

- dayNames
- dayShortNames
- monthNames
- monthShortNames

check ionic doc for more info https://ionicframework.com/docs/v5/api/datetime

**Comment by sergiorodriguez82** [comment]
Thanks for the quick reply @aitboudad, what about the cancel and ok buttons?

**Comment by aitboudad** [comment]
same as above `cancelText` and `doneText`.
