### ISSUE TITLE
RangeError: Maximum call stack size exceeded in v5.10.22/5.10.23/5.10.26/5.10.32

### ISSUE THREAD

**Issue by sshanmu91** [ngx-formly/ngx-formly#3187]
Hi Team,
I am getting the following error -
ERROR RangeError: Maximum call stack size exceeded

![image](https://user-images.githubusercontent.com/36123879/154769311-c6e53ed2-4cb3-4ec7-9245-0faeb450f403.png)

Here is my Schema and View

![image](https://user-images.githubusercontent.com/36123879/154769359-b743f92c-da47-4b4d-bbb4-5c9e4fce25d1.png)

![image](https://user-images.githubusercontent.com/36123879/154769377-aab17a83-a484-4ecf-9b07-5ebcd810c27d.png)

![image](https://user-images.githubusercontent.com/36123879/154769697-9b11b554-606f-4bce-91f1-dd4e16202027.png)

Looks like the modelChange keeps getting triggered continuously.

Tried to switch to different versions from 5.10.23 to 5.10.22 / 5.10.26 / 5.10.32
Keep getting the Maximum Call Stack Size Exceeded Error

- Angular : 7.3.10
- ngx-formly/core : 5.10.22/5.10.23/5.10.26/5.10.32
- ngx-formly/primeng : 5.10.22/5.10.23/5.10.26/5.10.32

![image](https://user-images.githubusercontent.com/36123879/154769506-b52ecf12-e80f-4607-92b0-3e465d54ca50.png)

Tried a lot of searching on the related issue but couldn't get a probable solution. Please do help!
Thanks in Advance!

**Comment by aitboudad** [comment]
Hi, could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-primeng

**Comment by sshanmu91** [comment]
@aitboudad 

I understand. But couldn't exactly try to put it in the Replication Code as it's been binded within the Component in the Project

Here are the Field Config.

fields: FormlyFieldConfig[] = [
    {
      className: 'form-group',
      key: 'Date',
      type: 'datepicker',
      templateOptions: {
        label: 'Date',
        required: true,
        disabled: false,
      },
    },
    {
      className: 'form-group column-wth-gap',
      key: 'IsWorkingDay',
      defaultValue: false,
      type: 'checkbox',
      templateOptions: {
        label: 'Is Working Day',
        required: true,
        disabled: false,
      },
    }
  ];
  
  Here is the Package.json
  
 {
  "name": "ngx-formly-ui-primeng",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.16",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.16",
    "@angular/compiler": "^7.2.16",
    "@angular/core": "^7.2.16",
    "@angular/forms": "^7.2.16",
    "@angular/material": "^7.2.16",
    "@angular/platform-browser": "^7.2.16",
    "@angular/platform-browser-dynamic": "^7.2.16",
    "@ngx-formly/core": "5.10.22",
    "@ngx-formly/primeng": "5.10.22",
    "core-js": "2.6.12",
    "primeng": "^7.1.3",
    "rxjs": "^6.6.7",
    "tslib": "1.14.1",
    "zone.js": "^0.8.28"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular/cli": "^7.3.10",
    "@angular/compiler-cli": "^7.2.16",
    "@angular/language-service": "^7.2.16",
    "@types/node": "6.4.10",
    "@types/jasmine": "2.8.9",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "^8.8.2",
    "tslint": "~5.9.1",
    "typescript": "3.2.4"
  }
}


![image](https://user-images.githubusercontent.com/36123879/154771604-6a578259-41ad-411b-b41e-e15a5844a485.png)

Line-Number 1152 seem to keep hitting continuously on seeing the Error Frames.

Please do help out on this.

**Comment by aitboudad** [comment]
> I understand. But couldn't exactly try to put it in the Replication Code as it's been binded within the Component in the Project

just a small reproduction example not the code used in your project as I've no idea of what could be wrong there.

**Comment by sshanmu91** [comment]
@aitboudad 

Hooray! Finally replicated the error.

Here is the code throwing the Error.

https://stackblitz.com/edit/ngx-formly-ui-primeng-hseuce

https://ngx-formly-ui-primeng-hseuce.stackblitz.io

![image](https://user-images.githubusercontent.com/36123879/154773734-5498b60c-c54c-4646-af6e-fe4ed27acdde.png)

**Comment by aitboudad** [comment]
removing `[(ngModel)]="model[field.key.toString()]"` solve the issue on your side, we support angular reactive form only.

**Comment by sshanmu91** [comment]
@aitboudad  Thanks a lot for the help!
