### ISSUE TITLE
A validation for checking if fields of an array store unique values

### ISSUE THREAD

**Issue by nbisht11** [ngx-formly/ngx-formly#3189]
**Problem Statement:**

Let's suppose we have an **array**(FieldArrayType) **of users** with **two fields**(FieldType): **userName** and **userEmail**. As it is an array we can add multiple users at once, but there is a catch, we can have two(or more than two) users with the same name but any two users cannot have the same email address. 

How can we add a validation to check if there are two userEmail fields which contains the same email address?

**P.S.** I will suggest that you add the **unique** validator to the list of default validations provided by formly, in the next formly version(v6) as it may have a lot of use cases like one mentioned above.

**Comment by kenisteward** [comment]
I'm on my phone so I can't give code here but theoretically have you had any issue with using a "validators" definition on the array field that will check for duplicate data in the model?

It could follow our detect same password example but doesn't even have to.

Could be made generic with an extension as well.

**Comment by nbisht11** [comment]
@kenisteward 
Can you please ping the url of the **same password example** in the comments? 
It'll be really helpful.

**Comment by kenisteward** [comment]
> @kenisteward 
> Can you please ping the url of the **same password example** in the comments? 
> It'll be really helpful.

Sorry not password I meant our unique value example

https://formly.dev/examples/validation/unique-value-async-validation

Instead of doing it at the formgroup level you could do it at the formarray level.

**Comment by nbisht11** [comment]
@kenisteward,
In this example we have an array of existing userNames but in the scenario described above we will not have that. Instead we will have them in a model that will look like this: 
```
{
 "users": [
        {
            "userName": "userName1", 
            "userEmail": "userEmail1@example.com"
        }, 
        {
            "userName": "userName2", 
            "userEmail": "userEmail2@test.com"
        }, 
        {
            "userName": "userName3", 
            "userEmail": "userEmail3@test.com"
        }
    ]
}
```
Is it possible to do that without involving the field group and index?

**Comment by kenisteward** [comment]
> @kenisteward,
> In this example we have an array of existing userNames but in the scenario described above we will not have that. Instead we will have them in a model that will look like this: 
> ```
> {
>  "users": [
>         {
>             "userName": "userName1", 
>             "userEmail": "userEmail1@example.com"
>         }, 
>         {
>             "userName": "userName2", 
>             "userEmail": "userEmail2@test.com"
>         }, 
>         {
>             "userName": "userName3", 
>             "userEmail": "userEmail3@test.com"
>         }
>     ]
> }
> ```
> Is it possible to do that without involving the field group and index?

The example assumes you want the validation to show on the actual field itself and not on the array. If it is acceptable for the error to show in an errors box then formatting for that for the field array is fine.

If not you can still apply the unique to every field by simply using the fieldconfig's parent property to get to the array field config and grab the model or form control to find unique values in it.

Again sorry I'm on my phone so coding this out would be awkward but we have docs on the fields I'm talking about in the comments of the formlyfieldxonfig ( that should show up when using intellisense I believe )

The validator always passes enough information to go up and down the model chain to make any type of validator the user wants. We do this internally on a wrapper library I made very often.

**Comment by nbisht11** [comment]
> The example assumes you want the validation to show on the actual field itself and not on the array. If it is acceptable for the error to show in an errors box then formatting for that for the field array is fine.
> 
> If not you can still apply the unique to every field by simply using the fieldconfig's parent property to get to the array field config and grab the model or form control to find unique values in it.
> 
> Again sorry I'm on my phone so coding this out would be awkward but we have docs on the fields I'm talking about in the comments of the formlyfieldxonfig ( that should show up when using intellisense I believe )
> 
> The validator always passes enough information to go up and down the model chain to make any type of validator the user wants. We do this internally on a wrapper library I made very often.

Yes,
The assumption you made is absolutely correct. I was also thinking about using the parent property of fieldConfig to grab the model. 
I'll try that now.
Thanks for your quick response @kenisteward .
