### ISSUE TITLE
Advanced Layout Issue

### ISSUE THREAD

**Issue by oguzhanet** [ngx-formly/ngx-formly#3204]
As seen in the pictures there is the Advanced Layout Issue.
I use the one in the link but it doesn't work.
https://formly.dev/examples/bootstrap-specific/advanced-layout

![1](https://user-images.githubusercontent.com/77545698/155667719-663a446a-bb81-490b-9995-4a2c633cee91.png)
![2](https://user-images.githubusercontent.com/77545698/155667737-a9741974-5e10-4b18-aa17-19eb97bf7769.png)

**Comment by MaxKless** [comment]
Is this in your personal project? Do you have bootstrap installed? 

To really see if this is a bug, it would be great if you could provide a minimal reproduction so it's easier for the maintainers to retrace your issue.

**Comment by oguzhanet** [comment]
It was due to the lack of bootstrap, I was using angular material. Thank you so much.
