### ISSUE TITLE
Please consider adding hintdEnd/hintStart to version 5.10.33 of the library.

### ISSUE THREAD

**Issue by kernokus** [ngx-formly/ngx-formly#3211]
Good afternoon. Please consider my request to add support for hintEnd/hintStart to the current stable version of the library 5.10.33 (apparently in 5.10.34).
At the moment, I see that this functionality is only provided for the 6^ version of the library, which requires at least 13 angular. (I saw on one of the pages that 11 is needed).Hint is quite important for many projects and I would be very grateful if you could add it to the current stable version of Angular, which only works with version >=9.
A crutch in the form of description + shifting it to the right does not help, since the matError error overwrites description at the time of occurrence. Only one displayed at a time...
I would be very grateful if this is possible! Thanks!

**Comment by aitboudad** [comment]
Hi, the solution doesn't work properly in `v5` and raise `ExpressionChangedAfterItHasBeenCheckedError` error which is only solved in `v6`.

So instead here is the steps to make it available in you project (by overriding the existing `form-field`):

1. copy the file https://github.com/ngx-formly/ngx-formly/blob/v5/src/material/form-field/src/form-field.wrapper.ts into your project
2. add hint to `FormlyWrapperFormField` template (replace existing `mat-hint` with the code below)

```html
  <mat-hint *ngIf="to.description || to.hintStart as hintStart">
    <ng-container [ngTemplateOutlet]="stringOrTemplate" [ngTemplateOutletContext]="{ content: hintStart }">
    </ng-container>
  </mat-hint>
  <mat-hint *ngIf="to.hintEnd as hintEnd" align="end">
    <ng-container [ngTemplateOutlet]="stringOrTemplate" [ngTemplateOutletContext]="{ content: hintEnd }">
    </ng-container>
  </mat-hint>
  <ng-template #stringOrTemplate let-content="content">
    <ng-container *ngIf="!content.createEmbeddedView; else template">{{ content }}</ng-container>
    <ng-template #template>
      <ng-container *ngTemplateOutlet="content"></ng-container>
    </ng-template>
  </ng-template>
```

4. define `form-field`  wrapper in your `AppModule`:
```ts
@NgModule({
  declarations: [FormlyWrapperFormField],
  imports: [
    FormlyModule.forRoot({
      wrappers: [{
        name: 'form-field',
        component: FormlyWrapperFormField,
      }],
    }),
  ],
})
export class AppModule { }
```
