### ISSUE TITLE
Added Fields in prePopulate-methode not updated/visualized 

### ISSUE THREAD

**Issue by ng-commander** [ngx-formly/ngx-formly#3214]
**Description**
After updating formly to Version >= 5.5.11, the form is not updated/visualized the dynamic added Fields in prePopulate-methode.

**Minimal Reproduction**
Working with Formly-Version 5.1.6: https://stackblitz.com/edit/angular-u4hep4-fsmcee?file=src/app/residences.component.ts
Issue with Formly-Version 5.10.33: https://stackblitz.com/edit/angular-u4hep4-c5yl12?file=src/app/residences.component.ts

**Your Environment**

- Angular version: 7.2
- Formly version: 5.10.33

**Comment by aitboudad** [comment]
related to https://github.com/ngx-formly/ngx-formly/issues/2285 which has been fixed in `v6`, please rely on field to get the attached fields:

```ts
<formly-field [field]="field.fieldGroup[0]"></formly-field>
<formly-field [field]="field.fieldGroup[1]"></formly-field>
<formly-field [field]="field.fieldGroup[2]"></formly-field>
```

or `ngFor`:
```ts
<formly-field *ngFor="let f of field.fieldGroup" [field]="f"></formly-field>
```
