### ISSUE TITLE
Will formly v6 support strict mode?

### ISSUE THREAD

**Issue by craigsh** [ngx-formly/ngx-formly#3215]
Hi

Thanks for the great library. I've just started a new project and intending using Formly as I've used it successfully in a previous Angular 11 project.

My new project is on the latest Angular (13.2.5 today). I'm using the 6.0.0.0-next version and was trying to use the [field wrapper example for Angular Material](https://formly.dev/examples/other/material-prefix-suffix)

I run into a couple of problems making it work:

1, turning strict: true in tsconfig.json fails to compile because of something in the validation.messages.minlength and maxlength in fieldconfig.
2. turning noPropertyAccessFromIndexSignature: true raises lots of issues with accessing this.to. E.g. this.to.addonLeft must be replaced with this.to['addonLeft'] otherwise I get:  error TS4111: Property 'addonLeft' comes from an index signature, so it must be accessed with ['addonLeft'].

Thanks,
Craig

**Comment by aitboudad** [comment]
I would say supporting partial strict mode is an option for us right now else it will complicate our work. Have you tried with `skipLibCheck` option so you'll be able to use strict mode without waiting an external lib to support strict mode?

```patch
"compilerOptions": {
+  "skipLibCheck": true
},
```


> 1, turning strict: true in tsconfig.json fails to compile because of something in the validation.messages.minlength and maxlength in fieldconfig.

Already fixed, will be part of next release.

**Comment by craigsh** [comment]
OK, thanks for the quick response.

Yes, turning on the skipLibCheck suppresses the error relating to the minlength and maxlength.

Thanks - I look forward to the next release :)

**Comment by aitboudad** [comment]
We've made a partial support which is enough for now, we may reach the full strict mode progressively.
