### ISSUE TITLE
ngx-formly queries related to expression properties.

### ISSUE THREAD

**Issue by thenm** [ngx-formly/ngx-formly#3216]
**Question**
ngx-formly queries related to expression properties.
In our angular application we are using the ngx-formly version 5.10.23

I have few question related to that

1. Are formly fields rendered synchronously? If it is happening asynchronously can we make this synchronously by setting some property
2. When is the expression properties are triggered after field are rendered and thier default values are set?
3. Can one field depend on the multiple field values and how can we create expression property for the same.
A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
> 1. Are formly fields rendered synchronously? If it is happening asynchronously can we make this synchronously by setting some property

yes, its sync

> 2. When is the expression properties are triggered after field are rendered and thier default values are set?

Expression are evaluated before the render step and whenever new changes is detected

> 3. Can one field depend on the multiple field values and how can we create expression property for the same.
A clear and concise description of what the question is.

Depencencies are resolve automatically.
