### ISSUE TITLE
Required-true(mandatory) not works when key is empty(not to add it in model)

### ISSUE THREAD

**Issue by nikitagawande65** [ngx-formly/ngx-formly#3221]
I have added one field with key value empty so that it doesn't get added in model(key: '') so after keeping key empty, required : true doesn't work. It shows form valid. How can we mark field mandatory with keeping key empty?

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by nikitagawande65** [comment]
Here it is - https://stackblitz.com/edit/ngx-formly-ui-bootstrap-kkdq72?file=src/app/app.component.ts
Required true not working for input field. As I don't want to add first- input field in model so I added key value empty('').

**Comment by aitboudad** [comment]
Working for me by updating Formly version to the latest one (`5.10.33`): https://stackblitz.com/edit/ngx-formly-ui-bootstrap-xzypqm

**Comment by nikitagawande65** [comment]
Thanks.
