### ISSUE TITLE
|| and && operator not working with ExpressionProperties

### ISSUE THREAD

**Issue by prashantraj16** [ngx-formly/ngx-formly#3222]
In my application, we have 3 control, checkbox1, checkbox2 and textbox1. When Checkbox1 is checked and Textbox1 is not empty, checkbox2 should get checked. Here is the expression I have put in the expressionproperties, but checkbox2 is not getting checked when Checkbox1 is checked and textbox1 is not empty.

key: 'check2',
      type: 'checkbox',
      // defaultValue: false,
      templateOptions: {
        label: 'check2',
      },
      expressionProperties: {
        'model.check2': 'model.text1 && model.check1 ? true : false'        
              },

**Comment by aitboudad** [comment]
Seems working for me, here is an example https://stackblitz.com/edit/angular-ih6ugw

**Comment by prashantraj16** [comment]
Please can you try this.
This is with || operator.

1. check check1.
2. uncheck check2.
3. type something in text1. check2 should get checked but it is not.


https://stackblitz.com/edit/angular-ih6ugw-tikyzd
