### ISSUE TITLE
ag grid integration example with multi checkbox

### ISSUE THREAD

**Issue by shreeram** [ngx-formly/ngx-formly#3228]
Could you kindly share example of ag-grid integration with multicheckbox or radio type.

A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
Just follow our demo example https://formly.dev/examples/advanced/grid-integration and update `type` of any item of `fields` property to `checkbox`.

```patch
{
  key: 'name',
- type: 'input',
+ type: 'checkbox',
},
```
