### ISSUE TITLE
has-error not removed for fields having ng-touched class when removing validator using clearValidators().

### ISSUE THREAD

**Issue by Agreesh** [ngx-formly/ngx-formly#3231]
[x] - Bug Report.
 
Dependencies used
"@angular/cli": "^11.2.10",
"@ngx-formly/bootstrap": "^5.10.22",
 "@ngx-formly/core": "^5.10.22"
 
 There is an issue with the formly form validation classes when we remove the validator from the already touched field.
 
![image](https://user-images.githubusercontent.com/21072718/158772314-2e44122f-70a4-4d84-926c-7f51ad6a9ea6.png)

I have a formly form with three fields. In the Initial stage, every field is a mandatory field. Password and Public Key fields are related to each other. If there is a value in the Password then the Public Key field needs to be disabled and no need for validators for Public Key and vice versa.

If I touched the Password field and do not add any value in the field will show a validator error. Then adding value in the Public key field will disable the Password Field and * symbol and the Validation message gets removed. But the red-color border remains the same and the form is also invalid in these cases.

I noticed that the is-invalid class name was not removed from the disabled field. Also, there is a has-error class in the parent div of the input field. You can see the class names in the image

![image](https://user-images.githubusercontent.com/21072718/158789496-de30ed3b-4a6d-4ab4-b601-e9877da3508c.png)

I also used expression properties, the same issue also there.

 expressionProperties: {
            'templateOptions.disabled': () => {
              return this.model.sftpPassword != undefined && this.model.sftpPassword != ""
            },
            'templateOptions.required': (model: any, formState: any) => {
              return formState.mainModel.sftpPassword == undefined || formState.mainModel.sftpPassword == "";
            },
 },

**Comment by aitboudad** [comment]
Hi,
could you please test against the latest version of Formly which is `5.11.2` and if the issue still happens I may need provide a reproduction :pray:, here is our `stackblitz` starter example: https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thank you!

**Comment by Agreesh** [comment]
@aitboudad Thanks for your replay.
I will check with latest version.

**Comment by aitboudad** [comment]
Feel free to leave a comment once you've got a reproduction example, thanks!

**Comment by Agreesh** [comment]
> Feel free to leave a comment once you've got a reproduction example, thanks!

Sorry, I was a bit busy with other work. But I have reproduced the same form in the stackblitz you have given. In that reproduction, the form is working as our expectation. But in our project, the forms not working in the way we are expecting.

**Comment by Agreesh** [comment]
@aitboudad  We changed the packages for formly-form into latest version. But the error not fixed. If we only change the validator, then the field become valid. If we try to disable the same field through expression properties, then the field will be invalid.

the has-error class only stay when we make the field disabled after a touch to the field.

Thanks

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
