### ISSUE TITLE
Cascade with Repeat, unable to access value change

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#3232]
**Question**

@aitboudad 

I am looking for some help here.

I am using cascade within repeat where I have two fields "addressCountry" and "addressState".

For some reason within the below code I am not able to listen to "valuechanges" of addressCountry within addressState.

Can I please request your help on telling me what I could be doing wrong?

Thanks

```javascript

    {
      key: 'address',
      type: "repeatdel",
      templateOptions: {
        addText: "New Address",
        // maxItems: 5
      },
      fieldArray: {
        fieldGroupClassName: "row",
        fieldGroup: [
          {
            type: 'nbselect',
            key: "addressCountry",
            className: "col-12 col-md-3",
            templateOptions: {
              label: "Country",
              required: true,
              options: [],
              valueProp: 'id',
              labelProp: 'name'
            },
            hooks: {
              onInit: field => {
                this.userApi.getCountries().subscribe((countries: any) => {
                  field.templateOptions.options = countries;
                });
              }
            }
          },
          {
            type: 'nbselect',
            key: "addressRegion",
            templateOptions: {
              label: "State",
              required: true,
              options: [],
              valueProp: 'id',
              labelProp: 'name',
            },
            hooks: {
               onInit: field => {
                 const stateControl = field.parent.model.get('addressCountry');
                 field.templateOptions.options = stateControl.valueChanges.pipe(
                   tap(() => field.formControl.setValue(null)),
                   startWith(stateControl.value),
                   switchMap(countryId =>  this.userApi.getStates(countryId)
                   ));
               }
            }
          },
        ],
      },
    },
```

**Comment by aitboudad** [comment]
Hi,
The above example is not clear enough to me so could you please provide a reproduction example using `stackblitz`:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by argupta23** [comment]
@aitboudad 
I will try to put something together and send you an update later today.

Thanks

**Comment by aitboudad** [comment]
Feel free to leave a comment once you've got a reproduction example, thanks!

**Comment by argupta23** [comment]
@aitboudad 

Please see attached stackblitz that captures the issue I am running into.

[https://stackblitz.com/edit/angular-ipev6a-kdjs3g](https://stackblitz.com/edit/angular-ipev6a-kdjs3g)

Within the stackblitz if you uncomment lines 24-32 and 89-91 you will notice that the team selection is not populated when the sport selection changes 

Thanks in advance for you help and support.

**Comment by aitboudad** [comment]
replace `this.form` by `field.form`:

```patch
- const sportControl = this.form.get('sport');
+ const sportControl = field.form.get('sport');

...

- const teamControl = this.form.get('team');
+ const teamControl = field.form.get('team');
```

**Comment by argupta23** [comment]
@aitboudad 

Appreciate the prompt response.

While it works in the stackblitz example, for some reason it does not seem to work in my actual code.

for some reason the query for "addressRegion" aka "State" is fired immediately on form initialization with "countryid" value of "null".

Any guidance on how I could debug the issue on my end?

```javascript

              {
                type: 'select', //'ngselect',
                key: "addressCountry",
                className: "col-12 col-md-3",
                templateOptions: {
                  label: "Country",
                  placeholder: "Country",
                  options: [],
                  valueProp: 'id',
                  labelProp: 'name'
                },
                hooks: {
                  onInit: field => {
                    field.templateOptions.options = this.userApi.getCountries();
                  }
                }
              },
              {
                type: 'select',
                key: "addressRegion",
                className: "col-12 col-md-3",
                templateOptions: {
                  label: "State",
                  placeholder: "State",
                  options: [],
                  valueProp: 'id',
                  labelProp: 'name',
                },
                hooks: {
                  onInit: field => {
                    const countryControl = field.form.get('addressCountry');
                    field.templateOptions.options = countryControl.valueChanges.pipe(
                      tap(() => field.formControl.setValue(null)),
                      startWith(countryControl.value),
                      switchMap(countryId =>  this.userApi.getStates(countryId)
                      ));
                  }
                }
              },
```

Thanks in advance.

**Comment by aitboudad** [comment]
You're using an old way of doing cascade select, please check our doc example https://formly.dev/examples/other/cascaded-select which contains the latest version.

**Comment by argupta23** [comment]
@aitboudad 

It is possible that Cascade might not be right approach to what I am trying to achieve.

Essentially what I am looking for is:
1. Initial query gets Countries from backend (name, id)
2. getStates(countryId) to fire when a country is selected by the user. 
   Note: The backend response will only contain states associated with the "countryId" that was requested.

Thanks
