### ISSUE TITLE
"hideExpression" string not working when there are multiple hideExpressions

### ISSUE THREAD

**Issue by tswallen** [ngx-formly/ngx-formly#3234]
**Please see https://stackblitz.com/edit/kaleidoscope?file=src/app/app.component.ts**

**Browser:** Chrome 99.0.4844.51 on Windows 10

**tl;dr:** I have 4 radio-box questions generated by a function. The second and fourth radio boxes require their preceding question to be answered true to be show. Instead what happens is radio box question 2 works as expected but number 4 seems to ignore the hide expression. Am I overlooking something simple?

Code example:

```typescript
labels: string[] = [
  'I feel uninterested in the things I used to enjoy.',
  'I often seem to live through events exactly as they happened before (déjà vu).',
];

fields: FormlyFieldConfig[] = this.labels.flatMap((label, index) => [
  {
    key: `question-${index}`,
    type: 'radio',
    templateOptions: {
      label: `Question ${index} - ${label}`,
      required: true,
      options: [
        { value: 1, label: 'True' },
        { value: 0, label: 'False' },
      ],
    },
  },
  {
    key: `subquestion-${index}`,
    type: 'radio',
    templateOptions: {
      label: `Subquestion ${index} - How much distress did you
      experience?`,
      required: true,
      options: [
        { value: 0, label: 'None' },
        { value: 1, label: 'Mild' },
        { value: 2, label: 'Moderate' },
        { value: 3, label: 'Severe' },
      ],
    },
    hideExpression: `!model.question-${index}`,
  },
]);
```

**Minimal Reproduction**

https://stackblitz.com/edit/kaleidoscope?file=src/app/app.component.ts

**Your Environment**

- Angular version: 12.2.16
- Formly version: 5.11.2

**Comment by aitboudad** [comment]
The syntax is not correct, the key contains `-` which not a valid name for a property in javascript so you need to use brackets:

```ts
hideExpression: `!model['question-${index}']`,
```

**Comment by tswallen** [comment]
Cheers!
