### ISSUE TITLE
Unable to use FormlySelectOptionsPipe programmatically

### ISSUE THREAD

**Issue by smc9** [ngx-formly/ngx-formly#3236]
**Description**
When creating some customized logic in the context of formly and select boxes, it seemed feasible to use the `FormlySelectOptionsPipe` from the code rather than the template. **BUT** that's not working, i.e. it produces an error which seems rather strange

> Error: Module not found: Error: Can't resolve '@ngx-formly/core/select/select-options.pipe' in ...

Note that using it as part of the template works just fine.

Is this intended behavior, am I doing something wrong or is it actually a bug?

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ivy-jxorvc shows the behavior, as it imports and uses the `FormlySelectOptionsPipe` as part of the html template, and has a prepared line of code in `app.component.ts` to force the error (see comment in code).

**Your Environment**

- Angular version: 12 or later
- Formly version: 5.11.2

**Comment by aitboudad** [comment]
Could you please describe the use-case as `FormlySelectOptionsPipe` is designed to be used as a pipe.

**Comment by smc9** [comment]
The pipe encapsulates some useful behavior in the context of selects + formly - if one wants to re-use that but adapt further or apply a different use to the output of the pipe, it would make great sense to be able to use it programmatically. Which for example is possible with the `DatePipe` - I have updated the stackblitz accordingly.

**Comment by aitboudad** [comment]
Ok I see, we'll provide it in the next release.
