### ISSUE TITLE
Missing option to align elements horizontally in repeating section

### ISSUE THREAD

**Issue by elementalPRESS** [ngx-formly/ngx-formly#3238]
Missing option to align elements horizontally in repeating section I'm trying to use the "Repeating Section" from the web page example. This also works very well. However, I miss the possibility of arranging the elements horizontally.

My simplified code looks like this:

	<div class="form-row" *ngFor="let field of field.fieldGroup; let i = index; let last=last">
		<formly-field class="col" [field]="field"></formly-field>
	</div>

The configuration looks like this:

	export const officialsForm: FormlyFieldConfig[] = [
		{
			type: 'stepper',
			templateOptions: {
				currentStep: 0,
				showControls: false,
				enableHeaderClick: false,
			},
			fieldGroup: [
				{
					templateOptions: { label: 'History' },
					fieldGroup: [
						{
							key: 'history',
							type: 'repeat',
							templateOptions: {
								addText: 'Add',
							},
							fieldArray: {
								className: 'col-10 XXX',
								fieldGroup: [
									{
										className: 'col-4',
										type: 'input',
										key: 'investmentName',
										templateOptions: {
											label: 'Name of Investment:',
											required: true,
										},
									},
									...			

Looking at the output in the developer console I find:

	<div _ngcontent-kxn-c267="" class="form-row ng-star-inserted">
		<formly-field _ngcontent-kxn-c267="" class="col-10 XXX" ng-reflect-field="[object Object]">
			
			<formly-group class="ng-star-inserted"> <-- PROBLEM
			
				<formly-field ng-reflect-field="[object Object]" class="col-4 ng-star-inserted">
					<formly-wrapper-form-field class="ng-star-inserted"><div class="form-group">
					...

To arrange the content of a row horizontally I would have to assign a class (in Bootstrap class `row`) to the `formly-group`. And right here is the problem as I don't understand how I could do this. Is there any option or concept I haven't found so far? 
Thx for your help!

**Comment by aitboudad** [comment]
to assign `row` to `formly-group` use `fieldGroupClassName`:

```patch
{
+ fieldGroupClassName: 'row',
  fieldGroup: [...],
}
```
