### ISSUE TITLE
multicheckbox with true false value in array of objects from the model

### ISSUE THREAD

**Issue by Et3rnal** [ngx-formly/ngx-formly#3243]
**Question**

I have a list of questions where the user tick if happened/true.
I'm trying to make it dynamic on both sides, so I thought of returning a list of strings (labels) and a boolean value (true its ticked)

eg:
`questionsList= [
{
	"label": "Blah blah evidence",
	"value": false
},
{
	"label": "is ≤1 year of age xxx",
	"value": true
}
`
However, passing similar **values** to `multicheckbox` will cause all the checkboxes to be ticked once we tick one, I tried to do it differently 

So, I want a way to make the key and the options to be the same, is that possible? I can change the model I just can't find a way to make both drivings by the model so I don't need to do any processing.

Here is the closest I can get, an object instead of an array, options only, I want an array of objects so I can use the model directly

https://ngx-formly-ui-bootstrap-x1dqb2.stackblitz.io

**Comment by Et3rnal** [comment]
The request: One array for both `model` and `options`

If I add `type: 'array'` and use `{ label: 'Option 2', value: true }` 
the model will just have a true/false array, no indicator of which label is that

Plus, all check-boxes with the same value (like false) will be checked together once we check one!

https://ngx-formly-ui-bootstrap-x1dqb2.stackblitz.io

**Comment by aitboudad** [comment]
> can you check the last stackbitz ? is it a bug?

It's an expected behavior, it contains an array of unique values.

> So, I want a way to make the key and the options to be the same

You can customize the option key using `valueProp`:

```patch
  fields: FormlyFieldConfig[] = [
    {
      key: 'checkboxsList',
      type: 'multicheckbox',
      templateOptions: {
        ...
+       valueProp: option => option,
      },
    }
  ];
```

**Comment by Et3rnal** [comment]
@aitboudad 
So it is possible to make `options` and the `key` point at the same array? I have changed the array to have a unique value
`
{
	"availableTypes": [
		{
			"selected": false,
			"text": "B",
			"value": "56"
		},
		{
			"selected": false,
			"text": "V",
			"value": "57"
		},
		{
			"selected": false,
			"text": "Fun",
			"value": "58"
		}
	]
}
`
But can't figure out how to change/stop what `multicheckbox` is adding then change it myself ?

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-x1dqb2

or do I need a custom firmly type to achieve that?

**Comment by aitboudad** [comment]
use https://formly.dev/examples/advanced/repeating-section

**Comment by Et3rnal** [comment]
Thank heaps @aitboudad 
https://stackblitz.com/edit/angular-y3udpd?file=src/app/app.component.ts

Can you tell me if there is a better way to set the label value instead of using `expressionProperties` ?
Have a nice weekend

**Comment by aitboudad** [comment]
`expressionProperties` is the better way, you may pass a string value or an observable instead of function as well:

```
expressionProperties: {
  'templateOptions.label': 'model.text'
}
```

The second solution is to rely on `valueChanges`, https://github.com/ngx-formly/ngx-formly/issues/2747#issuecomment-799430559

**Comment by Et3rnal** [comment]
@aitboudad Any idea if I can I use the same way with `type: 'radio'`?
https://stackblitz.com/edit/angular-y3udpd

**Comment by aitboudad** [comment]
radio type may not work properly for your case, use `valueChanges` and uncheck other fields instead + you could also define a custom validator as well.

```ts
hooks: {
  onInit: (field) => {
    // field.templateOptions.label = field.model.text;

    return field.formControl.valueChanges.pipe(
        // uncheck other fields
        ....
    );
  },
},
```

**Comment by Et3rnal** [comment]
@aitboudad 
Do you mean using `repeat` with `hooks` ? because radio doesn't render under repeat
https://stackblitz.com/edit/angular-y3udpd

If you mean without repeat, how can I stop the radio normal change to the model then apply the change I want only?

**Comment by aitboudad** [comment]
> Do you mean using `repeat` with `hooks` ?

yes, `repeat` with `hooks`.

**Comment by Et3rnal** [comment]
@aitboudad I found why radio doesn't render, I need to pass the values to option, I have used hooks to do that
I can't figure out the uncheck part, where is the selected value kept?
check it out: https://stackblitz.com/edit/angular-y3udpd
