### ISSUE TITLE
Bad selection of the oneOf on load.

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3245]
**Description**
When a oneOf JSONSchema contains an array with a "minItems" property the form is not able to select the right option.

**Minimal Reproduction**

Go to: https://stackblitz.com/edit/angular-yne8as?file=src/assets/json-schema/oneOf.json

The selection option1 is selected instead of option2. Remove the "minItems" property and the option2 is selected.

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.11.2

**Additional context**

**Comment by aitboudad** [comment]
The issue is in default value of listOfObjects:  `"default": [null],`, so either pass name default or an `undefined`  value:

* Solution 1
```json
"listOfObjects": {
  "default": ["name"],
}
```

** Solution 2
```json
"listOfObjects": {
  "default": [undefined],
}
```

**Comment by jma** [comment]
Hello, this is not a good approach as the children can be a complexe structure and thus it is not easy to set the default value of the parent. Moreover I have here a similar problem: https://stackblitz.com/edit/angular-yne8as-1c4dnw?file=src/app/app.component.ts, select the Option2 and add a new element and "boom" the form is back to option 1.

**Comment by aitboudad** [comment]
> this is not a good approach as the children can be a complexe structure and thus it is not easy to set the default value of the parent. 

Agree, so use solution `2`:
```json
"listOfObjects": {
  "default": [undefined],
}
```

> select the Option2 and add a new element and "boom" the form is back to option 1.

related #3246 which I'll provide a fix soon.

**Comment by aitboudad** [comment]
Sorry I've answered on the wrong issue
