### ISSUE TITLE
Unable to apply css to options or break options

### ISSUE THREAD

**Issue by thenm** [ngx-formly/ngx-formly#3247]
https://stackblitz.com/edit/angular-wev3m8?file=src%2Fapp%2Fapp.component.ts

I am trying to break the line if the option label is too long. 

![image](https://user-images.githubusercontent.com/25767032/160659658-8f9a68e3-2ca9-4a50-915a-2f04007d7fb1.png)

how can I achieve that?

**Comment by aitboudad** [comment]
You could pass a custom class to that field through `className`:

```patch
{
  key: 'Select',
  type: 'select',
+ className: 'custom-select'
}
```

Then apply the desired style in your css files, in general native select has a limited styling support in browsers, so in case you want to have a full control of select options I would suggest to use [ng-select](https://github.com/ngx-formly/ngx-formly/issues/3173#issuecomment-1038418608).
