### ISSUE TITLE
formArray's valueChange is not triggered when the length is decreasing

### ISSUE THREAD

**Issue by dc-p8** [ngx-formly/ngx-formly#3250]
**Description**
When you change the length of a fieldArray, the valueChange observable associated to the formArray control is only triggered when the count is increasing but not when the length decrease.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-7mcxsf?file=src/app/app.component.ts

Change the count from 3 to 4, 4 to 5, you will see in the console that the valueChange is triggered accordingly.
But when you set the counter from 5 to 4 and 4 to 3, nothing happens in the console.

**Workaround**
Just after setting the new model, you can put this:
```typescript
setTimeout(() => {
    this.form.get('investments').updateValueAndValidity({ onlySelf: true, emitEvent: true });
    // (<any>this.form)._updateTreeValidity({ emitEvent: true }); // more generic, also works
});
```
The problem is that the valueChange will be triggered 2 times when increasing the count (even when using distinctUntilChanged)

**Your Environment**

- Angular version: 13.3.1
- Formly version: 6.0.0-next.9

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.12.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.12.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
