### ISSUE TITLE
Customizing the material formly UI

### ISSUE THREAD

**Issue by varun-rajareddy** [ngx-formly/ngx-formly#3252]
I am using angular material for the whole project, and also material for formly. But facing difficulties while styling the UI

Actual layout i need :

<img width="240" alt="2022-04-01_10h16_59" src="https://user-images.githubusercontent.com/66180708/161282569-8cc4ec6a-760c-41c8-b6cd-b51d316e25df.png">

Below image is What I am getting displayed when I am passing the JSON to Formly.

<img width="478" alt="image" src="https://user-images.githubusercontent.com/66180708/161288773-f69a4bcb-3d04-487a-aa94-3b5e73426d4e.png">

How I can customize the UI as per the first Image as well as global and inline error messages.

<img width="314" alt="2022-04-01_11h05_27" src="https://user-images.githubusercontent.com/66180708/161290835-5509dd16-3844-4022-9db3-dbd7503edc13.png">

**Comment by derekkite** [comment]
https://stackblitz.com/edit/angular-yxujbq?file=src%2Fapp%2Fapp.formly.css

This is an example of how to style the material inputs.

**Comment by aitboudad** [comment]
You may give a try for some solutions that may not need a full override of existing UI:

- Use css to customize/override the existing style.
- Adjust default options of material [form-field](https://material.angular.io/components/form-field/overview) such as [appearance](https://material.angular.io/components/form-field/overview#form-field-appearance-variants)
- For error messages I think you'll need to override the existing `form-field` wrapper (see below).

Some part are not easy to overrides but for a full control I would suggest to overriding the default [form-field](https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/material/form-field/src/form-field.wrapper.ts) material wrapper, check my answer here https://github.com/ngx-formly/ngx-formly/issues/2511#issuecomment-696120243

Also you may check the source code of our UI which may give you some ideas + doc:
- Create a custom type https://formly.dev/guide/custom-formly-field
- Create a custom wrapper https://formly.dev/guide/custom-formly-wrapper
