### ISSUE TITLE
How do I get ngrx binded to the model

### ISSUE THREAD

**Issue by TYee71384** [ngx-formly/ngx-formly#3253]
**Question**
Hi, I am trying to learn and use formly for a project at work. I am learning ngrx at the same time, and have been struggling to get ngrx and formly to work correctly together.

I can get the data to bind correctly to the form, but when I change one of the fields, it is returning:
Cannot assign to read only property 'transactionType' of object '[object Object]'

my model that I am binding to formly is
`data$ = this.store.select(getRmvData).subscribe(x => this.formModel = x);`

so in the template I am binding via async pipe, but I can't even get it to trigger the modelChange function to try to dispatch an action, before it errors out on read only from the ngrx store

is there any tutorials or examples that clearly explain how to use ngrx with formly?

A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
Can you try with `immutable` mode:

```patch
@NgModule({
  imports: [
    FormlyModule.forRoot({
+     extras: { immutable: true }
    }),
  ],
})
```

**Comment by TYee71384** [comment]
thank you @aitboudad That seems to solve my issue
