### ISSUE TITLE
Translate field formControl value

### ISSUE THREAD

**Issue by kresogalic8** [ngx-formly/ngx-formly#3255]
Hey guys, I want to translate the field value which is read-only in our case. Is there any way to take `field.formControl.value` and use ngx-translate instant method to add a custom string with value, something like `CERTIFICATE.NAME.${field.formControl.value}` and get a translated value back?

**Comment by MaxKless** [comment]
This seems like it would be the job for a custom extension. Check out the [i18n example](https://formly.dev/examples/advanced/i18n-alternative) to see how to translate fields. The example translates the label but it should be the same for field keys .
