### ISSUE TITLE
Multicheckbox and translation

### ISSUE THREAD

**Issue by Garfield-fr** [ngx-formly/ngx-formly#3259]
**Question**

I would like to translate the checkbox labels on multicheckbox tyoe.

I implemented a new extension to try to translate the list of options, but when I pass the stream, I get an object as a label for my checkbox.

What is the best solution for this?

code: https://stackblitz.com/edit/angular-gzgmyz

Thanks

**Comment by aitboudad** [comment]
`label` expect a string value and not an observable, instead collect the list of labels from `options` and pass them to `stream` then convert the list to  options:

```ts
const options = to.options;
const labels = options.map(....);
to.options = this.translate.stream(labels).pipe(
  map(labels => options.map(...)),
);
```
