### ISSUE TITLE
Ionic multi-select does not select multiple options from model

### ISSUE THREAD

**Issue by danbraik** [ngx-formly/ngx-formly#3260]
Hello,

"@ngx-formly/core": "^5.12.0",
"@ngx-formly/ionic": "^5.12.0",

with Ionic wrapper, I created a multiple select
```
{
      key: 'styles',
      type: 'select',
      templateOptions: {
        label: 'Styles',
        placeholder: 'Styles',
        multiple: true,
        options: [
          { value: "ArtStyle.STREET_ART", label: 'Street Art' },
          { value: "ArtStyle.PORTRAIT", label: 'Portrait'  },
          { value: "ArtStyle.PEINTURE_AEROSOL", label: 'Aerosol'  },
          { value: "ArtStyle.AUTRE", label: 'Autre'  },
        ],
      }
    },
```

In the form, it displays the values
![image](https://user-images.githubusercontent.com/5272396/162006581-88d12a2f-8d6a-4e77-9863-da89b4fc2556.png)

but when I click on it, current options are not selected
![image](https://user-images.githubusercontent.com/5272396/162006882-11c4b323-90a7-4909-b94e-357e960d3b00.png)

It worked when I use directly Ionic component :
```
<ion-select  multiple="true" [value]="model.styles">
      <ion-select-option  value="ArtStyle.AUTRE">AUTRE</ion-select-option>
      <ion-select-option  value="ArtStyle.PORTRAIT">PORTRAIT</ion-select-option>
    </ion-select>
```

I think the wrapper for Ionic is missing property " value "
```
<ion-select
        [style.align-self]="to.labelPosition === 'floating' ? 'stretch' : ''"
        [style.max-width.%]="to.labelPosition === 'floating' ? 100 : ''"
        [formControl]="formControl"
        [compareWith]="to.compareWith"
        [ionFormlyAttributes]="field"
        [multiple]="to.multiple"
        [interface]="to.interface"
        [okText]="to.okText"
        [cancelText]="to.cancelText"
      >
```

Thank you

**Comment by aitboudad** [comment]
We use reactive form so the following input `[formControl]="formControl"` is responsible of binding the value, the demo example https://formly.dev/ui/ionic is working as expected so we can't help without a proper reproduction example.

> The bug seems to come from the " [compareWith]="to.compareWith" " property.

see https://github.com/ngx-formly/ngx-formly/blob/v5/src/ionic/src/lib/types/select.ts#L32
