### ISSUE TITLE
Using multiple formly-form stopped working, but other suggested options are problematic too

### ISSUE THREAD

**Issue by MantasJur** [ngx-formly/ngx-formly#3261]
**Description**
Our application has large forms, that are split up into a few logical pages.

The pages themselves have very little logic behind them (they're definetly not a stepper, even the tabs example that you provided to some other similar issues is still too complicated) - my form can have 4 pages, and the user can submit the form on page 1, as long as there are no invalid fields in the rest of the pages.

I used to use multiple formly-form tags to do this, but once I started upgrading versions (the older versions were over a year old), this functionality started to break.

Now, using multiple formly-form tags breaks validation in the previous pages (proper validation only works in the last page that was created, probably due to https://github.com/ngx-formly/ngx-formly/blob/4df05ce846d6c4159d298430bf61489f939e252e/src/core/src/lib/components/formly.form.ts#L87 )

I tried going for the approach that is used in your example (turning the pages into a formly type itself). Everything works fine, except for one form (the form in minimal reproduction is similar to this form that causes me issues): our number of pages varies, depending on a value inside the form. 

In the provided reproduction, the tabsToShow template option controls which pages to show, but when some page is hidden, and it has some required fields, the form is still invalid. 

I COULD use hideExpressions to remove the need of that, but I can't do it, as hideExpressions have other side effects (like deleting model values) which would be bad for me (if switching back from 2 to 3 pages for example, I lose data, which I need).

Any way to make this work currently? Main problem is that I can't use hideExpressions for this, as they're kind of reserved for a different functionality (conditionally removing data, but not always).

**Minimal Reproduction**
https://stackblitz.com/edit/angular-5q2y7x

**Your Environment**

- Angular version: 13.2.5
- Formly version: 5.10.33

**Comment by aitboudad** [comment]
The solution is to use `hideExpressions`, for deleting model values side effects you can control that behavior either globally using `resetFieldOnHide`:

  ```patch
  FormlyModule.forRoot({
  + extras: {
  +   resetFieldOnHide: false,
  + },
  }),
  ```

or for a specific field using `resetOnHide`.

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-5q2y7x-4f7d9f?file=src/app/app.module.ts
