### ISSUE TITLE
How do I get the index of a repeat 

### ISSUE THREAD

**Issue by TYee71384** [ngx-formly/ngx-formly#3262]
I created a custom repeat component from the examples, but how do I extract either the index of the fieldArray or a value from one of the fields

Basically, I have a somewhat complex form that I need to know the value typed in a specific field so I can then attach that to a click event that ngrx will then do a call to my backend

I am trying to figure out how to know which index it is in the array so I can pass that over to my button via templateOptions
this is the base of my fieldArray for my repeat (I created a function to return back the field object just to clean up the code a bit)
but I am trying to see if there is a way to extract the index so I can replace it in the hardcoded 'index' that I have as a templateOption for my button,

  
`    fieldArray: {
              fieldGroupClassName: 'display-flex ',
              fieldGroup: [
                FormlyConfig.createBasicInput('vin', 'input', {
                  label: 'Vin',
                }, 'flex-1', hidePrimaryVehicle ),
                FormlyConfig.createBasicInput('','button',
                    {
                      text: 'Lookup',
                      lookupType: 'tradein',
                      index: 1
                    },
                    'flex-1',
                    hidePrimaryVehicle
                  ),
                FormlyConfig.createBasicInput('plateType', 'input', {
                  label: 'Year',
                }, 'flex-1',hidePrimaryVehicle),
                FormlyConfig.createBasicInput('model', 'input', {
                  label: 'Make',
                }, 'flex-1',hidePrimaryVehicle),
                FormlyConfig.createBasicInput('make', 'input', {
                  label: 'Model',
                }, 'flex-1',hidePrimaryVehicle),
              ],
            },`

**Comment by aitboudad** [comment]
The field `index` is set in the `key` property, you may use `expressionProperties` to assign it to the button field:

```ts
{
  type: 'button',
  expressionProperties: {
    'templateOptions.index': 'field.parent.parent.key',
  }
},
```
