### ISSUE TITLE
How to append an info icon next to a field created using JSON schema.

### ISSUE THREAD

**Issue by Agreesh** [ngx-formly/ngx-formly#3268]
**Question**

I have a form, which is created using formly form Version 5.10.22. The fields are manipulated using JSON schema.
I need to add an info icon near to a filed, a click on the info icon will open a pop-up.
Is there any way to add the info icon without using jQuery and input-addon.

This is the field I have created.
![image](https://user-images.githubusercontent.com/21072718/163102426-802c14a8-ecb5-4ac3-af8b-640ec597e785.png)

This is the required output. This field is created only using HTML.
![image](https://user-images.githubusercontent.com/21072718/163102453-ff04d1d2-4526-46c6-8821-8e455edb6883.png)

I need to add the button next to the form field.

Packages i have using in my project.
"@ngx-formly/bootstrap": "^5.10.22",
"@ngx-formly/core": "^5.10.22",
"@ngx-formly/schematics": "^5.10.22",

**Comment by aitboudad** [comment]
You may need to mix the following solutions:

- https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
- https://formly.dev/examples/bootstrap-specific/input-add-ons

**Comment by Agreesh** [comment]
@aitboudad Thanks for your replay. I have added the info icon by template property. Add some styles, it is working as we expected.
