### ISSUE TITLE
[Question] - Is it possible to breakout formly files across multiple routes.

### ISSUE THREAD

**Issue by dinbtechit** [ngx-formly/ngx-formly#3273]
**Question**

Is possible to break out formly fields across multiple routes? In reactive forms, you can accomplish this using `subforms` by passing in the `ControlContainer`.

### Here is an example: 
As you can see clicking the tabs navigates the user to a different URL route. I would like to accomplish the same using formly. 
https://stackblitz.com/github/janders/angular-tab-router-with-children?file=src%2Fapp%2Fhome%2Fhome-routing.module.ts

![9UlR1GgLGX](https://user-images.githubusercontent.com/17984781/163305852-e5b7e812-503a-48ee-b0f9-2c4738468b52.gif)

**Comment by aitboudad** [comment]
possible but depends on how you would like to handle them, it can be implemented using `formly-form` for each tab where you pass a separated `subforms` or for a simplified solution you may handle all tabs under one form: [Tabs Form](https://formly.dev/examples/advanced/tabs).

**Comment by dinbtechit** [comment]
Appreciate the quick answer! 

I was also planning on using it in conjunction with [ngxs](https://www.ngxs.io/) as a single source for truth (all form(s) output in one json). Sounds like... single form would be ideal for that?

**Comment by aitboudad** [comment]
>  single form would be ideal for that?

yes
