### ISSUE TITLE
Dynamically change the content of a fieldGroup based on another field value

### ISSUE THREAD

**Issue by willyd** [ngx-formly/ngx-formly#3274]
**Question**

I would like to dynamically change the content of a fieldGroup based on the value of a model attribute as set by another field. Is this possible?

**EDIT**:

The idea is that my model can behave polymorphically. In this example below the model could be:
```javascript
let model = {
  type: 'type1',
  parameters: {
    option: 'opt1'
  }
}
```
or
```javascript
let model = {
  type: 'type2',
  parameters: {
    dummy: 'foo'
  }
}
```
In my real use case the `parameters` attribute is an object itself with a more than one attribute and potentially subobjects. But if the above worked, it should be easy to extend to a more complex object.

Please see this example, where the `fieldGroup` expressionProperty does not have the expected behavior.

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-ywehhn?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
You can use one of the following solutions:

1. hideExpression: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-rspefw?file=src/app/app.component.ts
2. manually edit field group using `valueChanges` and `_buildForm`: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-tdq5sf?file=src/app/app.component.ts
