### ISSUE TITLE
Need help write unit test for expression propertires

### ISSUE THREAD

**Issue by albertthinc** [ngx-formly/ngx-formly#3276]
Hi,

I am writing angular jasmine unit test and I am new for it.
Need your help on how write tests for the expression properties functions..

Like
expressionPropertirs : {
  'templateOptions.options : (model) => {
Return refobj
},

'templateOptions.required': { return logicFlg }
}

Thanks in advance

**Comment by aitboudad** [comment]
The doc about testing is not available yet https://github.com/ngx-formly/ngx-formly/issues/2723 so please check our source code as a starting example: https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/components/formly.form.spec.ts#L133-L149
