### ISSUE TITLE
Custom material date time picker control toggle malfunctioning

### ISSUE THREAD

**Issue by alfaproject** [ngx-formly/ngx-formly#3277]
So, I was trying to create a custom control based on the existing formly mat-datepicker because it's basically a copy/paste of the original material datepicker but with a time component and the toggle suffix doesn't seem to be working as expected but I'm not sure why. I don't know if it's my fault and I'm missing something obvious or if there's anything broken:

Reproduction: https://stackblitz.com/edit/angular-pghffr?file=src/app/formly-datetimepicker.component.ts

If you focus on the datetimepicker input, the calendar will show up properly as expected (please ignore the missing styles, I couldn't get them to work in StackBlitz)
BUT if you click the suffix toggle instead to open the calendar then the overlay shows up but without the calendar ):

Any help appreciated

**Comment by aitboudad** [comment]
The difference is the click event in `mat-datetimepicker-toggle` is not emitted, so the solution is to either remove




```
<mat-datetimepicker-toggle
      (click)="detectChanges()"
      [disabled]="to.datetimepickerOptions.disabled"
      [for]="picker"
    >
</mat-datetimepicker-toggle>
```

**Comment by alfaproject** [comment]
I created a fix upstream for the toggle click: https://github.com/kuhnroyal/mat-datetimepicker/pull/299

Once again, thank you @aitboudad for your help!
