### ISSUE TITLE
Specify a value to use when a field is emptied by the user

### ISSUE THREAD

**Issue by Steb95** [ngx-formly/ngx-formly#3283]
**Question**
Hi, I've a request if it's possible. I'm working with JSON schema, I'd like to know if there is a way to specify a value to use to fill a field when the field is emptied by the user (and NOT required, because, of course, if it's required, than it can't be empty).

For example, with this schema:
<pre>
{
    "type": "object",
    "properties": {
        "test": {
            "type": "string",
            "default": "My Default Value"
        }
    }
}</pre>
I'd like to have this behavior (let's suppose the model is `{}`):
- The default value is "My Default Value"
- If a user delete the default value and submit the form with the field `test` empty, than it will be filled with the default value.

Is this possible without manually checking the fields one by one (that can be very difficult when dealing with complex schemas, e.g. with arrays and nested objects)?

**Comment by aitboudad** [comment]
Formly doesn't have a control the value, so the adjustments should be done on your side and if you're looking for a generic way you may define a custom type (https://formly.dev/guide/custom-formly-field) where you can control the submitted value.
