### ISSUE TITLE
What is the best way to map the form results object back to the original templateOptions.label using the key?

### ISSUE THREAD

**Issue by tswallen** [ngx-formly/ngx-formly#3284]
Thinking about writing a function for this but not sure if there's a better solution out there...

I have my form (typeof FormlyFieldConfig[]) which has the question text inside the templateOptions.label (e.g. "How tall are you?") and then I have my results from the form (sent and then retrieved from the server) which look like this: {'a': 120}. What I want to do is loop through all the results and replace the key with the question text.

I know this is a straightforward example but in my case I actually have nested objects inside objects.

Real example:

```
{
    "personal": {},
    "zero": {
        "feedback": {},
        "a": false
    },
    "one": {
        "feedback": {},
        "a": false
    },
    "feedbackConsent": false
}
```

Any easy solution?

**Comment by aitboudad** [comment]
The question is not clear enough, each field has a key (nested key as well) and label which can be linked to the object retrieved from the server without the need to replace key with label.

```ts
{
  key: 'zero.a',
  type: 'input',
  templateOptions: {
    lable: 'How tall are you?'
  }
}
```
