### ISSUE TITLE
SVG in a form -- is it possible to have the SVG code added inline on the page?

### ISSUE THREAD

**Issue by timh770773** [ngx-formly/ngx-formly#3287]
Hi, I'm trying to add an SVG to my form and for styling reasons (ie. setting fill colors for paths) I'd like to have the actual SVG code on the page without creating a separate custom component for the image, if possible.

In this example, the first item works when displaying an SVG from a URL. The second item does not work... the SVG doesn't get added to the DOM. 

 ```
 fields: FormlyFieldConfig[] = [
    {
      key: 'image',
      template: '<img src="image.svg">',
      templateOptions: {},
    },
    {
      key: 'image2',
      template:
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="#fff" d="M8 22h2l5-8.5h5.5c.8 0 1.5-.7 1.5-1.5s-.7-1.5-1.5-1.5H15L10 2H8l2.5 8.5H5L3.5 8H2l1 4-1 4h1.5L5 13.5h5.5L8 22z"/></svg>',
      templateOptions: {},
    },
  ];
```
Live example:
https://stackblitz.com/edit/angular-formly-json-model-ovhyvj?file=src/app/app.component.ts

Maybe this isn't possible but if anyone has any ideas it'd be much appreciated. Thanks!

**Comment by aitboudad** [comment]
to bypass sanitizing template HTML content, you should explicitly set `true` to `safeHtml`:

```ts
templateOptions: {
  safeHtml: true,
},
```

https://stackblitz.com/edit/angular-formly-json-model-gfprqa?file=src/app/app.component.ts

**Comment by timh770773** [comment]
@aitboudad wow, thanks so much! Works great! I really appreciate it.
