### ISSUE TITLE
creating multicheckbox using formly using array binding

### ISSUE THREAD

**Issue by krangampally** [ngx-formly/ngx-formly#3288]
Hi there, I have a label [Valid Values] with one array and value with the array which are checked (true) for multicheckbox, this is how my JSON string looks for my multicheckbox could you kindly let me know how to define and view it in the form. Thank you
 {
            "Name": "Outbound Event Types",
            "CodeName": "Bomgar_Plugin_OutboundEventTypes",
            "Value": [
                "Customer Exit Survey is Completed",
                "Representative Survey is Completed",
                "Someone Joins a Support Session"
            ],
            "Required": false,
            "Description": "",
            "EncryptValue": false,
            "CustomValidators": null,
            "ValidationMessage": null,
            "ValidValues": [
                "Support Session End",
                "Customer Exit Survey is Completed",
                "Representative Survey is Completed",
                "Someone Joins a Support Session"
            ],
            "FieldType": 3
        },
This is how it should look
![image](https://user-images.githubusercontent.com/77158268/166995480-1f192d75-5900-4b40-9e7a-3e1d2509d933.png)

**Comment by aitboudad** [comment]
You may need to convert JSON into Formly format https://stackblitz.com/edit/angular-xhodnp?file=src/app/app.component.ts
