### ISSUE TITLE
ngx-formly derived project

### ISSUE THREAD

**Issue by EdSci** [ngx-formly/ngx-formly#3292]
Dear all,
I would like to create a new project based on ngx-formly.
An easy-to-use form builder, where users could share form templates.
https://www.data-templates.org/
https://app.data-templates.org/#/data-templates/5

I have started to work in an open-source version of the code.  Let me know how you like the idea. 
In a near future, I would appreciate any help I can get. 
Thanks
Ed

**Comment by MaxKless** [comment]
Very cool! Good luck with this project and I will try to help out in the future. Is there a GitHub link yet?

**Comment by cviolbarbosa** [comment]
Not yet. but soon :) Thanks!

**Comment by cviolbarbosa** [comment]
Dear all, 

Finally I have a GitHub link and a npm package for the project:
https://github.com/cviolbarbosa/data-template-form
https://www.npmjs.com/package/dtform

I created also a stackblitz for demonstration:
https://stackblitz.com/edit/datatemplate-form-example?file=src%2Fapp%2Fapp.component.ts

I would appreciate any help to divulge and improve this little project.
Thanks.

**Comment by MaxKless** [comment]
@aitboudad how should issues like this be handled? Keeping it open forever will clutter the issues but it's still interesting. 
Might be a good use case for the discussions feature.
