### ISSUE TITLE
Multi select not working for prime ng

### ISSUE THREAD

**Issue by operta** [ngx-formly/ngx-formly#3293]
**Description**
Multi select dropdown behaving as regular select dropdown.

**Minimal Reproduction**
Can be seen directly on https://formly.dev/ui/primeng when clicking the multi select dropdown

**Your Environment**

- Angular version: 11.2.5
- Formly version: 5.12.1

**Additional context**
I tried different formly/core and formly/primeng versions, the multi select behaviour didn't work.

**Comment by aitboudad** [comment]
PrimeNg select use [Dropdown](https://www.primefaces.org/primeng/dropdown) which doesn't support Multiselect. The solution is to create a custom type `multiselect` that use https://www.primefaces.org/primeng/multiselect component.

For the doc check: https://formly.dev/guide/custom-formly-field

**Comment by MaxKless** [comment]
You're of course very welcome to contribute a primeNg multiselect type.

Maybe we should remove the wrongly labeled "Select multiple" example from the docs @aitboudad?
