### ISSUE TITLE
Material datepicker throws circular ref errors when converted to json

### ISSUE THREAD

**Issue by Absynthesis** [ngx-formly/ngx-formly#3294]
Material datepicker throws circular ref errors when attempting to JSON.stringify() a FormlyFieldConfig containing this control. Easiest way to reproduce is to simply put **<pre>{{fields|json}}</pre>** to output current fields obj. 

 [Error Demo](https://stackblitz.com/edit/ngx-formly-ui-material-qqcqvk?file=src%2Fapp%2Fapp.component.html)

- Angular version: 12.2.2
- Formly version: 5.12.0

ERROR
Error: Converting circular structure to JSON
--> starting at object with constructor 'Object'
| property 'element' -> object with constructor 'Object'
| property 'publicProviders' -> object with constructor 'Object'
| property 'MatFormFieldControl_137' -> object with constructor 'Object'
--- property 'parent' closes the circle

**Comment by MaxKless** [comment]
Can I ask why you're trying to serialize the `fields` object?

In the process of initializing the fields, formly adds many properties to each `FormlyFieldConfig`, including `FormControl`s which are definitely not serializable. So it's expected that your code would throw an error.

If you want to display the config as you pass it into `<formly-form>`, I would reccomend deep copying it and displaying that copy, which should be serializable in most cases.

**Comment by aitboudad** [comment]
> If you want to display the config as you pass it into `<formly-form>`, I would reccomend deep copying it and displaying that copy, which should be serializable in most cases. 

or enable `immutable` mode:

```patch
@NgModule({
  imports: [
    FormlyModule.forRoot({
+     extras: { immutable: true }
    }),
  ],
})
```
