### ISSUE TITLE
Error when trying to implement new ui kit

### ISSUE THREAD

**Issue by dj-fiorex** [ngx-formly/ngx-formly#3296]
Hello guys,
first of all thanks for this amazing library!
I'm trying to implement a new ui kit based on [Nebular](https://akveo.github.io/nebular/), so i started with a new package created by the angular cli, added @ngx-formly/core@next and  then i copied the files from the bootstrap ui, just to start with something that works! Trying to build. i receive some error from the ts compiler:
in checkbox.type.ts line 32:
```
Property 'defaultOptions' in type 'FormlyFieldCheckbox' is not assignable to the same property in base type 'FieldType<FieldTypeConfig>'.
  Type '{ props: { indeterminate: boolean; hideLabel: boolean; formCheck: string; }; }' has no properties in common with type 'Partial<FieldTypeConfig>'
```
and `Property 'props' does not exist on type 'FormlyFieldCheckbox'`

Same two errors in every component. 
I think i made some mistakes, please someone could help me?

Thanks

**Comment by aitboudad** [comment]
`props` is not released yet, instead try to make copy from [v6.0.0-next.9](https://github.com/ngx-formly/ngx-formly/tree/v6.0.0-next.9) branch.
