### ISSUE TITLE
formly.dev search bar

### ISSUE THREAD

**Issue by MaxKless** [ngx-formly/ngx-formly#3297]
**Is your feature request related to a problem? Please describe.**
The formly docs are very example driven. This is nice because you can always find some actual code to show you what to do. However, it can sometimes be hard to find a specific example of a behavior if you don't know exactly what you're looking for.

**Describe the solution you'd like**
I would like to add a search bar at the top of the guides/ui/examples sidebar. You can type in some keyword and it will search in the title, description and actual code to present you a ranked listing across categories. 
Since there's no backend, I would use a client side search lib for this, maybe [Fuse.js](https://github.com/krisk/Fuse) or something similar, I don't really have experience with any lib like this.

**Describe alternatives you've considered**
Maybe some filtering would be useful too or we can just leave it like it is.

**Comment by MaxKless** [comment]
@aitboudad let me know if you have any issues with that or considerations, otherwise I'll just try it out when I find the time.

**Comment by aitboudad** [comment]
Don't waste time on this, I've a tool that generate the API doc for Formly from the source + docusaurus which include the search.
Not sure about examples but we'll see how it can be included when we'll get there.

**Comment by MaxKless** [comment]
Okay, sounds good. I think some fresh docs will be good for formly :) 
Maybe you can create a new issue to collect information and feedback regarding this and the new tool.

I'll go ahead and close this.

**Comment by aitboudad** [comment]
I agree, will focus on that part and provide more details after RC release.

**Comment by aitboudad** [comment]
@MaxKless I've pushed an early version here https://main.formly.dev/ so if you've any remarks, please let me know!

**Comment by MaxKless** [comment]
Looks awesome! Ofc there is still a bunch of stuff missing but it's very nice imo. Especially the search bar is super useful.
Do you have any control over the order of results? I think it would be more useful if the documentation was shown before the API reference because for example the wrapper documentation is more useful than the wrapper api docs.
Also, I didn't see any search results for examples, which could also be useful...

**Comment by aitboudad** [comment]
> Do you have any control over the order of results?

Partially but I'll check further to see how to improve the result
