### ISSUE TITLE
Bind list to Fromly control

### ISSUE THREAD

**Issue by arj060892** [ngx-formly/ngx-formly#3300]
**Question**
I'm trying to add a list to formly form, of which the data is coming from the backed, and while doing a post it should be sent as an array

![image](https://user-images.githubusercontent.com/19621934/169374238-6b586eaa-d1bb-4b03-bf47-3365714cd95c.png)

I created a custom control and have no idea how to bind the value coming from the API to the custom control which contains the list 

Tried something as below 
```
<ul class="list-group" [formControl]="formControl" [formlyAttributes]="field" >
      <li *ngFor="let listGroupItem of to.listGroupItems"
        class="list-group-item">{{listGroupItem.name}}</li>
    </ul>
```

with `to.listGroupItems` it works but that shouldn't be the case as the li property should be mapped from the API response not passed as a templateOption

API response is something like 

```
{
  "name": "",
  "labelPoints": [
    {
      "name": "Label 1"
    },
    {
      "name": "Label 2"
    },
    {
      "name": "Label 3"
    }
  ]
}
```

**Comment by aitboudad** [comment]
To assign value manually use `formControl.setValue()` and Formly will update the model accordingly.
You may check the following example: https://github.com/ngx-formly/ngx-formly/blob/v5/src/bootstrap/src/lib/types/multicheckbox.ts

**Comment by arj060892** [comment]
@aitboudad thank you for the response,
 but at which point in the custom control, we should set the `formControl.setValue()` as on HTML it is an unordered list 
 Then how can I map that response to the model, my current implementation looks like following 
 
```
 {
                    key: 'labelPoints',
                    type: 'list-group',
                    className: 'col-md-6 col-lg-4',
                    templateOptions: {
                      listGroupItems: this.labelPoints,
                      height: this.heightMax
                    }
                  }
```

Currently, I have to do an iteration on the response from API and push the values to `labelPoints` and pass it to the custom control via template options, which is a bit cumbersome way 
 
 I want to create a list directly from the API response which can be mapped to the formly model

**Comment by aitboudad** [comment]
you may use `httpClient` in `listGroupItems`:

```ts
{
  templateOptions: {
    listGroupItems: this.httpClient.get(...).pipe(
      map(v => v.labelPoints)
    )
  }
}
```

and use `async` pipe in `list-group` component:

```html
<ul class="list-group" [formlyAttributes]="field" >
  <li *ngFor="let listGroupItem of to.listGroupItems|async">...</li>
</ul>
```

**Comment by arj060892** [comment]
@aitboudad I have created a [stackblitz ](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-kkqmq1?file=src/app/custom-controls/list-group/list-group.component.ts ) 
as you could see in the code we can map the name & age properties to inputs, similarly, I wish to map the API response to the UI for the list 
using `templateOptions `this is not possible as I have a single endpoint which returns the entire response

**Comment by aitboudad** [comment]
have tried `formControl.value`:

```patch
+ <li *ngFor="let listGroupItem of formControl.value" class="list-group-item">
- <li *ngFor="let listGroupItem of to.listGroupItems" class="list-group-item">
  {{ getLabel(listGroupItem) }}
</li>
```

**Comment by arj060892** [comment]
It worked, thank you so much
Much appreciated :)
