### ISSUE TITLE
Multicheckbox updates dirty state only after the modelChange event has finished firing

### ISSUE THREAD

**Issue by snekku-dev** [ngx-formly/ngx-formly#3302]
**Description**
Bootstrap multicheckbox field updates dirty state only after the modelChange event has fired, unlike other fields

**Minimal Reproduction**
app:
https://angular-ivy-z1eghs.stackblitz.io

editor:
https://stackblitz.com/edit/angular-ivy-z1eghs?file=src/app/app.component.ts

**Your Environment**

- Angular version: 12.1.0
- Formly version: 5.12.0

**Additional context**
I noticed this behavior when trying to capture and filter fields in a dirty state inside a modelChange event, all the fields I am using in my form are already dirty when the event fires, while multicheckbox is still pristine and turns dirty only afterwards keeping me from intercepting it as a dirty control during a modelChange event

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.12.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.12.3) and [v6.0.0-beta.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-beta.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
