### ISSUE TITLE
Change version "beta" to "rc"

### ISSUE THREAD

**Issue by MarlonLuan** [ngx-formly/ngx-formly#3308]
RenovateBot considers that version "6.0.0-next.9" is higher than "6.0.0-beta.1"
and suggests update [ 6.0.0-beta.1 -> 6.0.0-next.9 ],

Angular uses "rc", so I think it would be a good alternative to use it here too

**Comment by aitboudad** [comment]
I thought that was a cache issue, we'll switch to `RC` within 1 or 2 weeks so I think its not a big issue for now.
Thanks for the suggestion :+1:!
