### ISSUE TITLE
load json schema to fields with functions not working

### ISSUE THREAD

**Issue by ip1211** [ngx-formly/ngx-formly#3309]
JSON :
[
{
"key":"eee",
"wrappers":["panel"],
"templateOptions": {
"lable":"!!!table",
"expanded":"this.getexpanded()"
}
}
]
"expanded":"this.getexpanded()" - GETTING STRING NOT FUNCTION

RESAULT:

  constructor(private dataService: DataService) {

    this.dataService.getPromise(config.dataEndpoint + 'waste/schema.json')

      .then((result) => {

        this.fields =result;

      });

  }

  getexpanded(){

 
    return false;

  }

**Comment by aitboudad** [comment]
check our demo example https://formly.dev/examples/other/json-powered, which include how to bind change event using map function .
