### ISSUE TITLE
"display: none" is not set when lazyRender is true

### ISSUE THREAD

**Issue by yinglejia** [ngx-formly/ngx-formly#3313]
**Description**

We set `lazyRender` to `true` in our app and use `hideExpression` to conditionally hide some fields.

The problem we have is that even though the hidden fields are not rendered, the formly wrappers `<formly-field>` are still rendered and they do not have `display: none`. Therefore, they are still part of the visual tree and can break form layout (even though the height is 0).

- When `lazyRender` is `false`, Formly adds `display: none` to `<formly-field>`. https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/components/formly.field.ts#L210
- When `lazyRender` is `true`, Formly does not add `display: none`. It seems it should?

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: 12.2.15
- Formly version: 5.12.0

**Additional context**

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.12.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.12.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by Trophalaxeur** [comment]
> This issue has been fixed and released as part of [v5.12.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.12.3) release.
> 
> Please let us know, in case you are still encountering a similar issue/problem. Thank you!

Hello,
This fix works perfectly with Formly V5 but not with V6.
Is the fix merged on Formly V6 ?

Thanks :) !

**Comment by aitboudad** [comment]
@Trophalaxeur could you please create a separate issue with a reproduction example. Thank you!
