### ISSUE TITLE
Need help on repeat section with chips data.

### ISSUE THREAD

**Issue by ermarkar** [ngx-formly/ngx-formly#3316]
**Question**

Need help on repeat section with chips data. I want to render this type of data

`{ field : [['a','b'], ['c','d']] }`

Details i have mentioned on SO

https://stackoverflow.com/questions/72413744/ngx-formly-repeated-field-with-chips-as-array-of-string-input-angular

**Comment by aitboudad** [comment]
see https://stackoverflow.com/a/72488260/1406096
