### ISSUE TITLE
Need help to display all the digits in the validation message, when it is entered in the min field dynamically

### ISSUE THREAD

**Issue by dimpu46** [ngx-formly/ngx-formly#3317]
**Question**

 In case user provides a 2 digit number as maximum limit and enters a minimum value greater than that, then in validation message only the first digit is seen.

Link to the project
[https://stackblitz.com/edit/angular-ivy-cavryg?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ivy-cavryg?file=src/app/app.component.ts)

Steps:
1) Firstly, enter a value to the max field first (ex: '5'), before entering the value for min field.
2) Once the value is enterd for max field, then enter the value for min field (ex: '6789')
3) Now in the validation message displayed under the max field, only the first digit of min value is shown.

Please guide me as to how the rest of the digits of min field can be updated/displayed dynamically
![Screenshot (327)_LI](https://user-images.githubusercontent.com/43565769/170986273-2e868be9-2e81-453c-9e9a-50ed8ff3654f.jpg)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.12.4](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.12.4) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by dimpu46** [comment]
Thank you for the quick response!
