### ISSUE TITLE
Extension priority field is ignored

### ISSUE THREAD

**Issue by ivanshilo** [ngx-formly/ngx-formly#3318]
⭐ yes, I enjoy using formly

**Description**
Order of extensions in `'providers'` array takes precedence over `'priority'` property inside factory function

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formly-ui-material-vgdjqj?file=src/app/app.module.ts

open console to see the order of called extensions.
first goes options getter, then translator exactly as they registered in providers although priorities define translator to be called first

**Your Environment**
see stackblitz

**Comment by aitboudad** [comment]
`priority` has been introduced in `v6`, so please ensure to test with [v6.0.0-beta.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-beta.2) version
