### ISSUE TITLE
How do I sync a form with its model, if the model was changed via code or another form?

### ISSUE THREAD

**Issue by tzehetner** [ngx-formly/ngx-formly#3319]
I am using Formly together with Material UI.

I have a case where two forms are bound to the same model object. If I change values via one of the forms, the other form does not reflect the changes.

How do I force a form to update its values if the underlying model is changed by some other code (or another form)?

Currently I am using FormlyFormOptions.resetModel(...) to force the update. Is this the correct approach?

Is there a function to tell the form to simply re-read the values from its model?

**Comment by Aman-Jojra** [comment]
If the underlying model is mutable, then formly won't update values automatically for you. Consider making model immutable (deepClone or ngrx state with immutable model).

**Comment by aitboudad** [comment]
Have you tried spread operator in order to let Angular detect changes:

```ts
// Method 1
this.model = { ...this.model }
```

**Comment by tzehetner** [comment]
Thanks to both of you. I could solve my problem with your answers.
