### ISSUE TITLE
Add array element copy into examples

### ISSUE THREAD

**Issue by ivanshilo** [ngx-formly/ngx-formly#3320]
**Is your feature request related to a problem? Please describe.**
Could be nice to new users to help them with array field usage when one has to create a copy of existing element

**Describe the solution you'd like**
Add this code into example https://formly.dev/examples/advanced/json-schema array.type.ts

```
<div class="col-auto text-right">
    <button type="button" mat-icon-button color="primary" (click)="add(i + 1, field.model)">
        <mat-icon>content_copy</mat-icon>
    </button>
</div>
```

**Comment by aitboudad** [comment]
PR welcomed :pray:!
