### ISSUE TITLE
Getter is not updated when values behind changes

### ISSUE THREAD

**Issue by pokke123** [ngx-formly/ngx-formly#3321]
Hi, i enjoy working with formly. but sometimes i run into unexpected behaviour.

Could you please verify, if this behaviour is expected.

On my model i have 3 properties with getters and setters.
where as one of the propertys is a calculated propertie based on the previus two.
the calculated property is displaying the change in html but formly looks like it is ignoring it..
the calculated property is an sum of two fields.

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by pokke123** [comment]
Hi , thanks for the quick reaction.

i updated the stackblitz example below

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-f2nfes?file=src/app/testModel.ts

**Comment by aitboudad** [comment]
Formly doesn't track getter changes instead rely on `valueChanges`:

```ts
    {
      type: 'input',
      templateOptions: { label: 'Sum' },
      hooks: {
        onInit: ({ formControl, form }) => form.valueChanges.pipe(tap(
          () => formControl.setValue(this.model.sum),
        )),
      },
    },
```
