### ISSUE TITLE
How to display validation even when maxLength criteria is met?

### ISSUE THREAD

**Issue by dimpu46** [ngx-formly/ngx-formly#3322]
**Question**

Currently im trying to display the maxLength validation message when user tries to enter characters more than the required maxLength.

As of now, in the formly field when we give maxLength value, user will not be able to enter the value in the input box greater than that of the provided maxLength value, which is good., But it doesn't display maxLength validation message, when the user tries to enter more characters.

Can someone help me with, how to display the validation message, even when maxLength criteria is met.

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by dimpu46** [comment]
Hi,

In the below example, i have given maxLength as 4, so as of now, user can enter only exactly 4 characters, but if he tries to enter any more characters(i.e on keypress > 4), i want to display maximum validation message to user, as to why he is not able input more than 4 characters.
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-k5ke1t?file=src/app/app.component.html

Thank you.

**Comment by aitboudad** [comment]
The main reason of not be able to input more than 4 characters is the use html validation attributes (minlength, maxlength), to remove them use `attributes` property:

```
templateOptions: {
  ...
  attributes: {
    minlength: ''
    maxlength: ''
  }
},
```
