### ISSUE TITLE
Render the Formly form through JSON object instead of FormlyFieldConfig[]

### ISSUE THREAD

**Issue by ezhilking123** [ngx-formly/ngx-formly#3323]
Kindly share the details for render the Formly form through JSON object instead of FormlyFieldConfig[] which is mentioned in component.

1. How to bind the Custom validator form identical JSON object which available from Drive or asset folder.
2. How to bind the API call to load the cascading LOV values from JSON object

Thanks in Advance

**Comment by aitboudad** [comment]
Sorry the question is not clear enough, you may check our doc examples which I think may gives you some hints toward your requests:

- https://formly.dev/examples/other/json-powered
- https://formly.dev/examples/other/cascaded-select-json
- https://formly.dev/examples/advanced/json-schema

To create a custom type you may check https://formly.dev/guide/custom-formly-field

**Comment by ezhilking123** [comment]
Thanks for your reply.. 

I can understand that how can bind or load the option values from component (Object declaration from Typescript).

I need help how can bind the API call or Service call from identical JSON object. Kindly refer the below JSON object.

My expectation is load the "Sub category" option values based on "Category" selection.

Kindly check and help on the same.

[
    {
      "key": "category",
      "type": "select",
      "templateOptions": {
        "label": "Category",
        "placeholder" : "Category",
        
        "required" : true,
        
            "options" : [
              {"value":"1", "label": "Agreement/Scope"},
              {"value":"2", "label":"Approved Product List"}
             
              ]
      
      },
      "validation" : {
        "messages" : {
          "required" : "Category is required"
        }
      }
    } ,

    {
      "key": "subCategory",
      "type": "select",
      "templateOptions": {
        "label": "Sub Category",
        "placeholder": "Sub Category",
        "dependentField" : "category" ,
        "options" : [ ]
        },
     "expressionProperties" : {
      "templateOptions.disabled" : "model.category==='2'",
      "templateOptions.options" : []
       
       
     }
    },

  

    {
      "key": "docType",
      "type": "select",
      "className" : "flex-1",
      "templateOptions": {
        "label": "Document Type",
        "placeholder" : "Document Type",
        "required" : true,
        "options" : [
         
          {"value":"22", "label":"Rodent Escalation Procedure"},
          {"value":"33", "label":"Stored Product Pest Escalation Procedure"}
       
          ]
      },
      "validation":{
        "messages":{
          "required" : "Document type is required"

        }
      }
    },

   

   
    {
      "key": "seqNumber",
      "type": "textarea",
        "templateOptions": {
        "label": "Sequence Number :"
      },
      "expressionProperties": {
      },
      "hideExpression": "model.docType!=='22'"
      
    },


    
    {
      "key": "accNo",
      "type": "input",
        "templateOptions": {
        "label": "Account Number",
        "placeholder" : "ENTER AN ACCOUNT NUMBER",
        "required" : true,
        "minLength": 5,
        "maxLength" : 10
      
      },

      "validation":{
        "message":{
          "required": "Account Number is required",
          "minLength": "Input value 5 is more than 5 letter" 
       
        }
      },

      "validations" : {
        "validation": ["accNumber"]
      },
      
      "hideExpression": "model.docType!=='33'"
      
    }

     
  
  ]
