### ISSUE TITLE
Prevent auto-generation of formly-fields

### ISSUE THREAD

**Issue by stevencherry-uu** [ngx-formly/ngx-formly#3324]
**Question**

I would like to create a component with a more complicated layout in html, but still properly bind my inputs to the 'fields' array. I would like to prevent <formly-form [fields]=fields /> from generating an input for each item in 'fields', so that I can manually create <formly-field> element where I need them to be in my layout. Is this currently possible?

Ultimately, I don't want to use formly json object to describe a highly nested and styled html component which has inputs throughout.

**Comment by aitboudad** [comment]
use inline type as described here https://github.com/ngx-formly/ngx-formly/issues/2086#issuecomment-584847953

**Note**: Available only in `v6`
