### ISSUE TITLE
Error when options for select are not initialized - v6

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#3325]
We set options for selects async.

When options for select are not initilized the following error is shown: 

Error: Cannot read properties of undefined (reading 'forEach')

https://stackblitz.com/edit/angular-vjdhkp?file=src%2Fapp%2Fapp.component.ts

6.0.0-beta.2

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.0-beta.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-beta.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
