### ISSUE TITLE
Validation in Repeating Section works only for the first element

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#3327]
**Description**
When we have an another section using **Repeating Section**, validation of the new section isn't triggered. If we have a required field, the form stay valid even if the field is not filled.

**Minimal Reproduction**
**Add another investment** and click **Submit**, only the first *Name of Investment* has validation triggered.

https://stackblitz.com/edit/angular-zyqdbv?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/32452023/171836503-1fc2afeb-4669-4911-a9fb-ce950fbb9fa2.png)

**Your Environment**

- Angular version: 7.2.16 & 13.3.11
- Formly version: 5.12.3

**Comment by aitboudad** [comment]
That's a regression, you may use `v5.12.1` till we fix the issue.

**Comment by Jukien** [comment]
> That's a regression, you may use `v5.12.1` till we fix the issue.

Thank you it's worked with this version :sunglasses:
