### ISSUE TITLE
Want to display the max validation message, even when user cannot enter more than the maxlength 

### ISSUE THREAD

**Issue by dimpu46** [ngx-formly/ngx-formly#3335]
**Question**

Hi,

I want to display the max validation message, even when user cannot enter more than the maxlength.,
as of now if maxlength value is 4, user cannot enter more than 4 characters, which is good,. but the max validation message is not shown, if he tries to enter more than 4 characters.
So i want to display the max validation message when user tries to enter 5th character. How can it be achieved?
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-k5ke1t?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/3322#issuecomment-1145810285

**Comment by dimpu46** [comment]
Still it isnt working!,..
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-k5ke1t?file=src/app/app.component.ts

**Comment by dimpu46** [comment]
> see [#3322 (comment)](https://github.com/ngx-formly/ngx-formly/issues/3322#issuecomment-1145810285)

Still it isnt working!,..
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-k5ke1t?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
do not remove them, just add extra attributes:

```patch
      templateOptions: {
        minLength: 2,
        maxLength: 4,
+       attributes: {
+         maxlength: '',
+       },
      },
```

**Comment by dimpu46** [comment]
@aitboudad Thank you :)
