### ISSUE TITLE
Autofill/Autocomplete username and password field Issue

### ISSUE THREAD

**Issue by EjazIris** [ngx-formly/ngx-formly#3336]
Hi, @aitboudad 
In my project I am using input type field as my username and password, but as I open the form these fields gets auto-filled with saved credentials on my chrome.
I have tried, 
  attributes: {
    autocomplete: 'off'
  },
 this solution also, but did not work.
 --> If I remove password field from my form then these fields will not get auto-filled.
 --> I also tried to patch the values but its not working for null.
Can you please provide me a solution.

**Comment by aitboudad** [comment]
`autocomplete: 'off'` worked for some users, you may try with `new-password` instead (https://stackoverflow.com/a/51686518/1406096)
```ts
templateOptions: {
  attributes: {
    autocomplete: 'new-password',
  },
}
```
