### ISSUE TITLE
Angular 14 compatibility

### ISSUE THREAD

**Issue by MaxKless** [ngx-formly/ngx-formly#3340]
Hi :) 
With Angular 14 released, it's important to make sure formly works with it. 
Since they made some big changes with regards to form handling, it will probably be some work.
Have you tried a migration yet?
Maybe you can provide some insights or ideas how to contribute towards this, @aitboudad?

Thanks!

**Comment by elnipa** [comment]
any news here? ngx-formly is our only dependency preventing us from upgrading to ng14. Would love to see that fixed.

**Comment by aitboudad** [comment]
@elnipa did you try with https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-beta.3 ?

**Comment by aitboudad** [comment]
> Maybe you can provide some insights or ideas how to contribute towards this?

@MaxKless didn't check the new version yet, but I would say that many features that are implemented in `V6` are complementary to what Angular `v14` bring to the table, the most important one to me is the standalone components which I think we need to check its validity in Formly side. Any enhancements toward typed forms in Formly are also worth some check.

**Comment by elnipa** [comment]
> @elnipa did you try with https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-beta.3 ?

Tried it (together with `@angular/material@14.0.4` and it's giving me the following error when serving the project

```
Error: node_modules/@ngx-formly/material/form-field/form-field.wrapper.d.ts:5:56 - error TS2307: Cannot find module '@angular/material/form-field/form-field' or its corresponding type declarations.

5 import { FloatLabelType, MatFormFieldAppearance } from '@angular/material/form-field/form-field';
```

`    "@ngx-formly/core": "^6.0.0-beta.3",
    "@ngx-formly/material": "^6.0.0-beta.3",`

Any thoughts?

**Comment by aitboudad** [comment]
> Any thoughts?

related to https://github.com/ngx-formly/ngx-formly/pull/3359,  will try to publish a new release this week.

**Comment by yoni333** [comment]
angular 14.0.4 + formly 6.0.3 beta i got the error 
`Error: node_modules/@ngx-formly/core/lib/core.d.ts:6:35 - error TS2307: Cannot find module './services/formly.form.builder' or its corresponding type declarations.`

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.0-rc.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-rc.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by yoni333** [comment]
@aitboudad  it work now with v6.0.0-rc.o . thank you !
another question - "onChanges" hook is design to run only once just after onInit hook?
because i change values in dropdown and "onChanges" event not fired

**Comment by kenisteward** [comment]
I think you are using the incorrect data type

In the error it says it is expecting formlyfieldconfogfielsprops. But you
are passing for field config type instead. Switch that and make sure or
cast it as any

**Comment by yoni333** [comment]
it is not because the type i wrote.i can remove it and still get the same problem - the field.props is optionaly can be undefined. and that the collision with they type
watch this [screenshot](https://1drv.ms/u/s!AiBOP9tamx0ujFxJafN_6x86BqdK)
i understood that the problem is props is defined in the FormlyFieldConfig interface as optional with  ?
in the screenshot see how i solve it in line 66

**Comment by aitboudad** [comment]
> another question - "onChanges" hook is design to run only once just after onInit hook?

`onChanges ` is related to the component lifecycle, triggered when the field input is changed. To subscribe to the field value changes use the following solution:

```ts
{
  ...
  hooks: {
    onInit: (field) => field.formControl.valueChanges.pipe(tap(
      (value) => { ... },
    )),
  },
},
```

**Comment by MaxKless** [comment]
@yoni333 check out [`CONTRIBUTING.MD`](https://github.com/ngx-formly/ngx-formly/blob/main/CONTRIBUTING.md) to see how you can develop locally. You will use `yarn` instead of `npm i`. 
I often have lockfile issues with yarn, so just throw that away when you commit.

**Comment by yoni333** [comment]
i try to make the exampe with the ip custom validator - the problem is that even i insert good ip the error is still there...
can someone tell me where is my mistake ? 
[stackblitz custom validator ip](https://stackblitz.com/edit/angular-ivy-4kad7e?file=src/app/app-routing.module.ts)

**Comment by aitboudad** [comment]
@yoni333 you the value is valid you should return `null` value:

```patch
+ return /(\d{1,3}\.){3}\d{1,3}/.test(control.value) ? null : { ip: false };
- return /(\d{1,3}\.){3}\d{1,3}/.test(control.value) ? { ip: true } : { ip: false };
```

**Comment by yoni333** [comment]
you test it ? my  typescript fail to compile
baecuse angular 14 ValidationErrors type not accect null only key/value
`export declare type ValidationErrors = {
    [key: string]: any;
};
`

**Comment by aitboudad** [comment]
@yoni333 yes, please update the validator declaration as well:

```patch
- IpValidator(control: AbstractControl): ValidationErrors {
+ IpValidator(control: AbstractControl): ValidationErrors | null {
```

**Comment by pjpaparao** [comment]
hi 

<img width="432" alt="image" src="https://user-images.githubusercontent.com/32052006/188303227-6653521c-13a9-483b-913f-127ce28e6b86.png">

i am geting above issue while creating custom ng select for formly forms.
can any help please.

**Comment by aitboudad** [comment]
@pjpaparao see https://github.com/ngx-formly/ngx-formly/issues/2842#issuecomment-1016476706, another solution is to disable strict template in Angular

**Comment by rainerhahnekamp** [comment]
I've created #3446, which might be related to this one.
