### ISSUE TITLE
v6 FieldArrayTypeConfig does not have generic prop value

### ISSUE THREAD

**Issue by dereekb** [ngx-formly/ngx-formly#3341]
**Description**
The FieldArrayTypeConfig type does not allow for a custom props value like FormlyFieldConfig does.

**Minimal Reproduction**
https://github.com/ngx-formly/ngx-formly/blob/a44f2a50a581acdada4bab4803a755a857fa866c/src/core/src/lib/templates/field-array.type.ts#L8

**Your Environment**

- Angular version: 13.3.0
- Formly version: 6.0.0-beta.2

**Additional context**
My guess is this is an oversight, as I don't see why it couldn't be the same as FieldTypeConfig or FieldGroupTypeConfig.

https://github.com/ngx-formly/ngx-formly/blob/a44f2a50a581acdada4bab4803a755a857fa866c/src/core/src/lib/templates/field.type.ts#L5

I'm in the process of updating from 6.0.0-next.9 and taking advantage of the changes, but noticed this type wasn't updated so I have to extend FieldArrayTypeConfig instead like I have been (posted for reference), instead of using props.

https://github.com/dereekb/dbx-components/blob/4b0699c411f04d08982947f981993a87edbe2b46/packages/dbx-form/src/lib/formly/field/value/array/array.field.component.ts#L12

**Comment by aitboudad** [comment]
Could you please send a PR?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.0-beta.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-beta.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by dereekb** [comment]
Thanks!
