### ISSUE TITLE
Validation message for input textbox is not displayed.

### ISSUE THREAD

**Issue by dimpu46** [ngx-formly/ngx-formly#3343]
**Description**
Default value input box accepts characters based on the entered minLength and maxLength.
But when there is already a default value provided in the code, and after that the minLength and maxLength is given which doesn't satisfy the given default value, then the validation message is not shown for default value but on clicking its input box and then clicking outside will display the message.

Stackblitz: https://stackblitz.com/edit/angular-ivy-qfknc6?file=src/app/app.component.ts

Steps:
1) On load, it appears this way(below image), as per the code,
![Screenshot (335)](https://user-images.githubusercontent.com/43565769/172567671-e41a5ed1-0582-4d9f-91be-3649aff5830e.png)

2) Now enter minLength and maxLength as shown in below image, where it should have thrown error for default value input box as it didn't satisfy the minLength condition:
![Screenshot (336)](https://user-images.githubusercontent.com/43565769/172568163-06d58cd3-8e85-4e07-a26a-3a4ffeeb59c3.png)

3) but on clicking inside the default input textbox and then clicking outside will throw an error
![Screenshot (337)](https://user-images.githubusercontent.com/43565769/172568807-099d7411-1003-41bd-a221-3ece3f4c26c5.png)
![Screenshot (338)](https://user-images.githubusercontent.com/43565769/172568819-812de976-b9d0-4baf-a75a-0e95d8c95e39.png)

**Comment by aitboudad** [comment]
Validation is shown when the form is submitted or a field is touched so to change that behavior define a custom `showError` https://github.com/ngx-formly/ngx-formly/issues/3041#issuecomment-978048375 and to force showing message error regardless its state pass `true` to `validation.show` https://formly.dev/examples/validation/force-show-error
