### ISSUE TITLE
Change detection error when focussing a repeatable field

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3344]
**Description**
When a repeatable field has a focus and the initial model contains more than one value the following error appears on the console:

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'ng-untouched: true'. Current value: 'ng-untouched: false'.

**Minimal Reproduction**

1. go to https://stackblitz.com/edit/angular-w6mxpq?file=src%2Fapp%2Fapp.component.ts
1. open the console and see the error.

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.12.4

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.12.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.12.5) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
