### ISSUE TITLE
FieldArrayType different initialisation behavior - v6

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#3345]
I wanted to point out a different behaviour of FieldArrayType between v5 and v6.

Press "Another investment"
Press "Submit"

https://stackblitz.com/edit/angular-aty7mb?file=src%2Fapp%2Fapp.component.ts
v6
{"investments":[{},null]}

Not sure if this makes sense that the object can be null. For me it doesn't as it can incur problems at the backend.
The issue can be fixed by overriding `add(i?: number, initialModel?)` and specifying an initialModel.

FieldArrayType supports an array of single values and objects. Maybe it would make sense to identify which array type is chosen and initialize the added item accordingly.
For an array of single values IMO null or undefined (will be translated to null in JSON) is fine.
Therefor only initializing when it is an array of objects.

https://stackblitz.com/edit/angular-q8e2j3?file=src%2Fapp%2Fapp.component.ts
v5
{"investments":[{},{}]}

A side note: I think it is a pity that the "investment" example got replaced by the "tasklist" example, they should be made availabe both as they address two different use-cases.

**Comment by kenisteward** [comment]
I believe this was done on purpose as a part of the "initialize to undefined " breaking changes. 

Does setting the default value for objects work instead?

**Comment by FritzHerbers** [comment]
The array object gets correctly initialized when `defaultValue: {}` is configured on the `fieldArray` object.

We initialize the array object in our specialized FielArrayType type, as it is easy to forget not setting a defaultValue. Configuration mistakes might not get catched during testing. In our case we didn't had a check for not-null of the array object in our backend and resulted in an exception.

I wanted to point out the different behavior and raise a discussion if there should be made an exception to the "initialize to undefined" for array objects.

**Comment by kenisteward** [comment]
@FritzHerbers it's documented in the changelog / readme for formly v6 here 

https://github.com/ngx-formly/ngx-formly/blob/main/UPGRADE-6.0.md  

> The defaultValue for fieldGroup and fieldArray has been changed to undefined instead of empty object. If you want to rely on the old behavior set the defaultValue:

**Comment by FritzHerbers** [comment]
Yes, it is documented, but you leave out:

>I wanted to point out the different behavior and raise a discussion if there should be made an exception to the "initialize to undefined" for array objects.

Without a defautValue set, formly creates automatically an object as soon as you change the value of an element.
Everything works just fine, until you have an array with non-required elements, and you get a null in your backend. It might be hard to trace back, as you might not have asserted such situation.

We do not configure a defaultValue (as one might be forgotten), we set them explicitly in our specialized array types. Otherwise we would have gone through the configuration and add a defaultValue before handing over to formly.

Put the above question differently, does it make sense (have a use-case) to have uninitialized array objects ?

**Comment by kenisteward** [comment]
It does make sense due to if no data has been added to a non required
object then making it empty actually is incorrect semantics as there was no
action that added data to the non required object ( or internal data )

That being said, the solution for those who would like the old way is
extremely straight forward as you can set the default value at the
framework level not field by field.

FYI this also preps for when angular forms finally makes the default value
of a formcontrol / group / array  undefined instead of null.
https://github.com/angular/angular/issues/42713

With the work that has been done for strictly typed forms I assume that
will be in the pipeline soon as well

**Comment by aitboudad** [comment]
I tend to agree with @kenisteward point view, adding default value is extremely straight forward. We may go with that way in V6 and see how it goes.
