### ISSUE TITLE
Formly custom datepicker with time selection for Angular 13 working on FireFox, Edge and Chrome

### ISSUE THREAD

**Issue by oulusoy** [ngx-formly/ngx-formly#3349]
Hi Formly Team. We upgraded an existing project to Angular 13. After that our custom datepicker with time selection broke. 
Is there any example where you can show us how to make a datepicker with time selection work in all important browsers using Angular13? 

We also already have tried to create the datepicker using templateoptions and the respective type like this `fields: FormlyFieldConfig[] = [
    {
      key: 'example',
      type: 'input',
      templateOptions: {
        label: 'datetime',
        type: 'datetime-local',
      }
    }
  ];` ... it just work in Chrome and NOT in Firefox

But we would prefer to create a custom datepicker. So if you have a solution or an example, it would be great.

**Comment by aitboudad** [comment]
You may check Angular package that provide a datapicker with time and then create a custom type by following our doc https://formly.dev/guide/custom-formly-field
