### ISSUE TITLE
Update fields on dynamic field added to ngx-formly

### ISSUE THREAD

**Issue by svinayaka** [ngx-formly/ngx-formly#3354]
Is there any way we can update formly component when we add a dynamic field to the fields list?

I have a requirement, where users can add and remove field, but field is not referencing form, and throwing error. 

`
export class AppComponent {
  form = new FormGroup({});
  model = {};
  fields: FormlyFieldConfig[] = [
    {
      key: 'name',
      type: 'input',
      templateOptions: {
        label: 'Field 1',
        placeholder: 'Formly is terrific!',
      },
    },
  ];

  fn() {
    debugger;
    this.fields.push({
      key: 'name1',
      type: 'input',
      templateOptions: {
        label: 'Field 1',
        placeholder: 'Formly is terrific!',
      },
    })
  }

  submit(model) {
    console.log(model);
  }
}
`

**Comment by MaxKless** [comment]
No problem :) Which reference has to be updated?
