### ISSUE TITLE
ResetModel event

### ISSUE THREAD

**Issue by ivanshilo** [ngx-formly/ngx-formly#3356]
**Question**

I want to detect changes in every field and change its styling accordingly.
How do I know that form is in Reset mode when I have a notification in changeEvent? It got fired even if old value equals to a new value.

**Comment by aitboudad** [comment]
You should rely on `formControl.valueChanges` and check when the value is `null` or `underfined`:

```ts
{
  ...
  hooks: {
    onInit: (field) => field.formControl.valueChanges.pipe(tap(
      (value) => { ... },
    )),
  },
},
```

Another solution is to use `expressionProperties`.

To apply that for all fields you may consider using a custom extension  https://main.formly.dev/guide/custom-formly-extension

**Comment by ivanshilo** [comment]
It does not work unfortunately if I do
`this.options.resetModel?.(this.lastmodel);`
Every field gets new value through fromControl event, but it is impossible to know if it is a "new default" or just another change during normal mode.
I had to introduce a Subject<void> in form state `this.options.formState!.resetState = new Subject<void>();` and then fire this event when user does "Submit" and listen to this event in every field (thx extensions) so it would know that current value of the field is a "new default".
