### ISSUE TITLE
How to have same validation on two or more fields to show user that at minimum one field need to be filled?

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#3362]
**Question**
How to have same validation on two or more fields to show user that at minimum one field need to be filled?
When one of the fields is filled, the validation will pass for other fields.
Do you think it is possible? I tried to use "Matching Two Fields" mecanisim but with no success.

I did that, but when I fill one field I can't reset other fields validation:
![image](https://user-images.githubusercontent.com/32452023/176229194-4861e966-f217-4c2e-bc10-847658931fc9.png)

**Comment by aitboudad** [comment]
use the following solution instead https://stackblitz.com/edit/angular-g1vdik
