### ISSUE TITLE
when I change the model, form field not changes

### ISSUE THREAD

**Issue by chavilax** [ngx-formly/ngx-formly#3363]
Hi,
when I change the model, form field not changes.

I tried to update a field on change, 
the model is changed and the form field not.
something like this:
 {
                  type: 'input',
                  key: 'sumOfRows',
                  hide:false,
                  templateOptions: {
                    type: 'number',
                     maxlength: 15,
                    minlength: 3,
                    required: true,
                    change: (field, $event) => {
                        console.log('change',field);
                        this.func(field)
                    },
                                      },
func(field:FormlyFieldConfig){
 this.model.Amount=field.parent.model.sumOfRows
}

Thanks

**Comment by kenisteward** [comment]
Would  it be possible for you to setup a stackblitz? 

Also from what you have here I think you want to use expressionProperties : { "model.fieldName" : "changeLogic" } instead

**Comment by aitboudad** [comment]
To trigger the model change you'll need to override the model value in order to let Angular detect changes, try with the following solution and it should work:

```patch
- this.model.Amount=field.parent.model.sumOfRows
+ this.model = {
+   ...this.model,
+   Amount: field.parent.model.sumOfRows
+ }
```

You may also try to use `expressionProperties` as pointed above which will update the field model.

**Comment by chavilax** [comment]
when I do this:

this.model = {
   ...this.model,
   Amount: field.parent.model.sumOfRows
 }
 the model is update , but not the form field.

I did this:
this.form.patchValue(this.model);
and the form was updated also.
Thanks

**Comment by aitboudad** [comment]
> the model is update , but not the form field.

@chavilax working for me https://stackblitz.com/edit/ngx-formly-ui-bootstrap-dxcg44?file=src/app/app.component.ts

**Comment by chavilax** [comment]
for me its not working,
maybe because my model contains some sections,
and I try to change a table in one of them:

 func(field: FormlyFieldConfig) {
      this.model.sectionA['table'] = {
        ... this.model.sectionA['table'][0],
        amount: field.parent.model.sumOfRows
      };
    }

**Comment by aitboudad** [comment]
you should override the the entire `model` value not just `model.sectionA['table']`, another solution you may use is to set the desired field directly using `form.get('sectionA.table.amount').patchValue('***');`

**Comment by chavilax** [comment]
Thanks,
that worked for me:
to change the model:

this.model.sectionA['table'][0]['amount']=field.parent.model.sumOfRows
**and then to override the the entire model-that updated the form:**
  this.model = {
        ...this.model        
      };

when I tried this, it doesn't recognize the fields:
  this.model = {
        ...this.model,
      this.model.sectionA['table'][0]['amount']=field.parent.model.sumOfRows
      };

**Comment by aitboudad** [comment]
> when I tried this, it doesn't recognize the fields:
> this.model = {
> ...this.model,
> this.mod

please check https://stackoverflow.com/a/47103087/1406096
