### ISSUE TITLE
Error on first form submit

### ISSUE THREAD

**Issue by jmendes92** [ngx-formly/ngx-formly#3364]
**Question**

When I submit a form for the first time I keep getting this error. The second time everything works fine.

![Screenshot 2022-06-29 155248](https://user-images.githubusercontent.com/3502753/176455159-bf02e6f8-07b5-4843-9f5c-65bcd8cd93e7.png)

![Screenshot 2022-06-29 155232](https://user-images.githubusercontent.com/3502753/176455187-d0563706-5368-41d4-8e67-94346acff8c5.png)

The project where it happens is pretty complex so a minimal replication is hard to provide. I didn't opened a bug issue because I'm not sure of why this happens. Maybe I did something wrong on my side, but couldn't found it myself so I looking for some advices on what I should check in order to prevent this to happen.

Thanks in advance

**Environment**

Angular: 13.3.11
Formly: 5.12.5

**Comment by aitboudad** [comment]
Hi, 
Sorry but It's hard for us to guess what could be wrong on your project, please feel free to leave a comment once you've a got a reproduction example.
