### ISSUE TITLE
Formly type instantiation - additional constructor/onDestroy 

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#3365]
I am using ng2-daterangepicker and always (v5/v6) had the error message: `Cannot read property 'remove' of undefined`

https://github.com/evansmwendwa/ng2-daterangepicker/issues/32

The above message/behavior is not dramatic.

```
constructor - date.type
constructor - ng2-daterangepicker
ngOnDestroy - ng2-daterangepicker
ng2-daterangepicker.js:77 Cannot read properties of undefined (reading 'remove')
ngOnDestroy - date.type
constructor - date.type
ngOnInit - date.type
```

Searching for the reason I noticed for the instantiation of a field type an additional constructor/onDestroy is called.
https://stackblitz.com/edit/angular-aty7mb-pfuaka?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fsimple.type.ts

After my investigation I remembered some 3 years ago there was a need for this, cannot quickly find in code.

As this might cause side effects, is this still needed, or could it maybe be coded differently?

**Comment by adora-tech** [comment]
Hello all,

I confirm this issue.
I use ng2-daterangepicker and I get the same error message when I create a custom type with it.

Thank you.

**Comment by aitboudad** [comment]
Its an issue in `ng2-daterangepicker`, `ngDestroy`  can be trigger in some case before the view is initialized which is the case in Formly.

There is a plan to change the rendering flow in the next major version that would fix the additional constructor/onDestroy as well.
