### ISSUE TITLE
Material select field - templateOptions' labelProp

### ISSUE THREAD

**Issue by radzk** [ngx-formly/ngx-formly#3366]
Im quite confused about the documentation. It says that templateOptions are dependent on the component itself.  https://formly.dev/guide/properties-options

In here I've found a bootstrap example that uses labelProp, valueProp etc: https://formly.dev/examples/bootstrap-formly/select

I dont know about bootstrap, but I thought it won't work with Material select (API does not have labelProp https://material.angular.io/components/select/api).
Im surprised because it actually works with material select.

How is it then? Is the documentation outdated? What really is the templateOptions prop?

**Comment by aitboudad** [comment]
`templateOptions` are dependent on the component itself but there are some common properties that we use such as `labelProp`, `valueProp` which are provided by 'formlySelectOptions'  pipe.

The documentation of `templateOptions`  is not available yet, we'll able to provide an API doc soon. In `V6` we've added typings for all Formly UI types that you can import in your project.
