### ISSUE TITLE
[Formly Error] [Multiple Form Groups] Maximum call stack size exceeded and wrong required validation field setup

### ISSUE THREAD

**Issue by VladimirUskokovic** [ngx-formly/ngx-formly#3367]
First of all, I want to thank you all for you great contribution in creating very great package that is dealing with forms, I really appreciate it. 🙏 👏 

**Description**
I'm receiving two different types of errors when dealing with multiple form groups:

**First error: maximum call stack size exceeded**

I have formly form with multiple form groups and their respective fields.
Each form group except the first one has hideExpression which depends on the value of the field from first form group.
If the right value is chosen, the respective field group would be shown. 
Problem occurs if respective formGroups have field/s with same key value, the expression properties couldn’t resolve it and it will throw error `ERROR Error: [Formly Error] [Expression "templateOptions.disabled"] Maximum call stack size exceeded`

**Second error: Required property for form field is not set properly**
If given form group is chosen and have field that previous form group has it also with different required field setup, the first group field setup would be applied instead of field setup from visible form group.
NOTE: First comment out expressionProperties from fields in order to test this issue properly

**Minimal Reproduction**
Following fields config code example looks like this:
```
fields: FormlyFieldConfig[] = [
    {
      fieldGroup: [
        {
          key: 'text',
          type: 'select',
          templateOptions: {
            label: 'First group field',
            placeholder: 'Please select',
            required: true,
            options: [
              { label: 'secondGroup', value: 'secondGroup'}, 
              {label: 'thirdGroup', value: 'thirdGroup'}
            ],
          },
        },
      ],
    },
    {
      hideExpression: 'model.text  !== "secondGroup"',
      fieldGroup: [
        {
          key: 'name',
          type: 'input',
          expressionProperties: {
            'templateOptions.disabled': 'model.text  !== "secondGroup"',
          },
          templateOptions: {
            label: 'Second group field!',
            required: true,
          },
        },
        {
          key: 'hasActive',
          type: 'checkbox',
          defaultValue: false,
          templateOptions: {
            label: 'Active!',
          },
        },
      ],
    },
    {
      hideExpression: 'model.text  !== "thirdGroup"',
      fieldGroup: [
        {
          key: 'name',
          type: 'input',
          expressionProperties: {
            'templateOptions.disabled': 'model.text  !== "thirdGroup"',
          },
          templateOptions: {
            label: 'Hey!',
          },
        },
        {
          key: 'haveSomeOtherFunc',
          type: 'checkbox',
          defaultValue: false,
          templateOptions: {
            label: 'Have some func!',
          },
        },
      ],
    },
  ];
```

https://stackblitz.com/edit/ngx-formly-multiple-form-groups-bug?file=src/app/app.component.ts
https://ngx-formly-multiple-form-groups-bug.stackblitz.io/

**Your Environment**

- Angular version: 12.2.5
- Formly version: 5.12.5

**Additional context**

**Comment by aitboudad** [comment]
The passed expression of `name` field was the root cause of the loop, when the `secondGroup` or `thirdGroup` is enabled you're trying to set `true` and `false` to the disabled property which causes an infinite loop, please change the expression into the following solution:

```ts
'templateOptions.disabled': '(model.text !== "secondGroup") && (model.text !== "thirdGroup")',
```

**Comment by FritzHerbers** [comment]
@aitboudad 
https://stackblitz.com/edit/ngx-formly-multiple-form-groups-bug-j5acws?file=src%2Fapp%2Fapp.component.ts
v5
`name` reuses the same `formControl` for `secondGroup` and `thirdGroup`, right?
When using `secondGroup` and entering data in `name`, e.g. 'aaa', is shown with submit.
Moving to `thirdGroup`, `name` is empty, submit shows 'aaa'. Entering data, e.g. 'bbb' and submit, shows 'bbb' for name.
Is this a bug?

https://stackblitz.com/edit/ngx-formly-multiple-form-groups-bug-xjhc6d?file=src%2Fapp%2Fapp.component.ts
v6 (FormlyModule.forRoot/extras/resetFieldOnHide=false) it works.
Noticed that with `thirdGroup` the `name` is required (but that would be OK).
However, the two checkboxes get missing when changing, a bug?

**Comment by aitboudad** [comment]
> `name` reuses the same `formControl` for `secondGroup` and `thirdGroup`, right?

right

> When using `secondGroup` and entering data in `name`, e.g. 'aaa', is shown with submit.
Moving to `thirdGroup`, `name` is empty, submit shows 'aaa'. Entering data, e.g. 'bbb' and submit, shows 'bbb' for name.
Is this a bug?

Moving to `thirdGroup`, `name` is not empty based on my test so not a bug. the diff between v6 and v5 is the flag `resetFieldOnHide` which is set to `true` by default.


>v6 (FormlyModule.forRoot/extras/resetFieldOnHide=false) it works.
>Noticed that with `thirdGroup` the `name` is required (but that would be OK).
>However, the two checkboxes get missing when changing, a bug?

It depends on the use case so let's assume it's an expected/default behavior when `resetFieldOnHide` is set `true`.

**Comment by FritzHerbers** [comment]
@aitboudad 

>Moving to thirdGroup, name is empty
>> Moving to thirdGroup, name is not empty based on my test so not a bug. 

![image](https://user-images.githubusercontent.com/10029682/177027689-2ecff2ce-4959-4991-b6d3-666d4947a38c.png)
![image](https://user-images.githubusercontent.com/10029682/177027725-cfa89063-95ac-4c13-aa3a-f1b8fc670829.png)
`name` is not shown in the form! But the value is in the model.



>>v6 (FormlyModule.forRoot/extras/resetFieldOnHide=`false`) it works.
> It depends on the use case so let's assume it's an expected/default behavior when resetFieldOnHide is set true.

![image](https://user-images.githubusercontent.com/10029682/177028302-27203e04-299b-4174-9a45-002e0e4e32f4.png)
![image](https://user-images.githubusercontent.com/10029682/177027972-8db37b0d-e561-482c-be7c-9b3b58929d80.png)
![image](https://user-images.githubusercontent.com/10029682/177028011-d4d72757-cdd5-41dd-bb8a-37b3874a6dba.png)

The resetFieldOnHide is set to `false`, the `hasActive` checkbox is not in the model anymore, therefor it is not expected!

**Comment by aitboudad** [comment]
> `name` is not shown in the form! But the value is in the model.

still present in the form as `name` = `Second group field!` = `Hey field`

> The resetFieldOnHide is set to `false`, the `hasActive` checkbox is not in the model anymore, therefor it is not expected!

yes, its a bug I think so please create a separate issue for that one.
