### ISSUE TITLE
Model is reset with resetFieldOnHide=false - v6

### ISSUE THREAD

**Issue by FritzHerbers** [ngx-formly/ngx-formly#3368]
Although FormlyModule.forRoot/extras/resetFieldOnHide=`false` the model is reset.

https://stackblitz.com/edit/ngx-formly-multiple-form-groups-bug-xjhc6d?file=src%2Fapp%2Fapp.component.ts
Choose `secondGroup` and set `hasActive`.
Choose `thirdGroup`, press submit, `hasActive` is missing from the model.

![image](https://user-images.githubusercontent.com/10029682/177028302-27203e04-299b-4174-9a45-002e0e4e32f4.png)
![image](https://user-images.githubusercontent.com/10029682/177027972-8db37b0d-e561-482c-be7c-9b3b58929d80.png)
![image](https://user-images.githubusercontent.com/10029682/177028011-d4d72757-cdd5-41dd-bb8a-37b3874a6dba.png)

v6.0.0-beta-3

**Comment by aitboudad** [comment]
The item `hasActive` is still present in the `model` object but not in the form instance which is an expected behavior since its a hidden field and not part of the form anymore.

```patch
submit() {
+  alert(JSON.stringify(this.model));
-  alert(JSON.stringify(this.form.value));
}
```
