### ISSUE TITLE
change not trigger on disable field -formly

### ISSUE THREAD

**Issue by chavilax** [ngx-formly/ngx-formly#3369]
Hi,
I have a disable field,
which changed by a function,
and the change not triggered on this field.

   {
                  type: 'input',
                  key: 'Amount',
                  hide:false,
                   templateOptions: {
                    maxlength: 15,
                    minlength: 3,
                    disabled: true,
                    pattern: /^\d*[.]*\d*$/,

                    change: (field, $event) => {
                      console.log('change',field);
                      this.func(field)
                  },
                  },
                  hooks: {
                    onChanges: (field: FormlyFieldConfig) => {
                        this.func(field)
                    },
                },

**Comment by chavilax** [comment]
my code not recognize valuechanges;
 valueChange: ({ value }) => this.calcTotalPayment(value),

versiov:
Angular CLI: 8.3.29
Angular: 8.2.14

**Comment by chavilax** [comment]
that works:
  hooks: {
                      onInit: (field: FormlyFieldConfig) => {
                     field.formControl.valueChanges
                        .subscribe((e)=>{
                      this.calcTotalPayment(field)
                        }
                      
                        );
                      }
                      },

**Comment by MaxKless** [comment]
Hi @chavilax, please provide a minimal reproduction if you want to get help quickly.
Also, at the very least, make sure your code is properly formatted and readable.

Are you using a version of formly that's compatible with Angular 8?

**Comment by MaxKless** [comment]
Maybe the change in your `FormlyFieldConfig` is not properly registered by formly. Have you tried reassigning the `FormlyFieldConfig` instead of only changing a single property?

Again, there's not much I can do without a minimal reproduction.

**Comment by aitboudad** [comment]
To subscribe to the form value changes use `form.valueChanges`:

```ts
{
  hooks: {
    onInit: ({ formControl, form }) => form.valueChanges.pipe(tap(
      () => formControl.setValue(this.model.sum),
    )),
  },
},
```
