### ISSUE TITLE
Hide columns and header in table

### ISSUE THREAD

**Issue by chavilax** [ngx-formly/ngx-formly#3370]
Hi,
I have a table and I try to hide some columns with the title.
I can hide the column but not the labelHeader, and the space remained.

  {
                    type: 'input',
                    key: 'sewageWaterConcentration',
                    hide: false,
                    templateOptions: {
                      type: 'number',
                      labelHeader: 'sewage Water Concentration',
                      maxlength: 15,
                      minlength: 3,
                      required: true,
                     },
                    hideExpression: (model: any, formState: any, field: FormlyFieldConfig) => {
                      if (this.realModel.section_portal_streamingfees_placedetails_sreamingtype &&
                        this.realModel.section_portal_streamingfees_placedetails_sreamingtype.taxAmountCalculation == 3
                      ) {
                        return true;
                      }
                      return false;
                    },
                  },

**Comment by suifeng110** [comment]
how to get the value if The column ownership of a sub table in a list is hidden ; Thanks...
