### ISSUE TITLE
[Question] Is it possible to use version 5 with Angular 13?

### ISSUE THREAD

**Issue by dsriniv** [ngx-formly/ngx-formly#3371]
**Question**
Is it possible to use Formly-core@5.12.X with Angular 13? It looks like version 6 is not stable yet and has many breaking changes with our application as we just upgraded from Angular 11 to 13.

**Comment by aitboudad** [comment]
Yes `v5`support Angular 13, for version 6 its almost stable you may expect a stable release within 2 weeks (need to check Angular 14 support + some reported issues).
