### ISSUE TITLE
How can I set the value of a repeat section in formly within hooks

### ISSUE THREAD

**Issue by jsofii** [ngx-formly/ngx-formly#3372]
I have this field, it's a repeat section. So the **field.formControl.value** is an Array. I want to set this value with **setValue** but It's not working.    

      {
                key: 'negligenceDefendants',
                type: 'repeat',
                className: 'flex-45',
                hooks: {
                  onInit: (field: FormlyFieldConfig) => {
                    field.parent.parent.form.get('defendants').valueChanges.pipe(
                    ).subscribe(it => {
                      field.formControl.setValue( this.formBuilder.array([{}, {}]));
                    });
                  },
             }

**Comment by aitboudad** [comment]
Can you try the following solution:

```ts
this.model.negligenceDefendants = value;
// change the model to trigger detecting changes
this.model = { ...this.model };
```

**Comment by jsofii** [comment]
I have tried this in my main component, because I use a service to create the fields... But if I do this, It seems like I go into a cicle and the app gets stuck. But then I tried instead {...this.model} => {...this.form.value}. That worked! Not sure if that's the right way to do this but it works now. If you have any feedback let me know.. Really appreciate your support.
```
  onDefendantsChange(): void {
    this.form.get('defendants')?.valueChanges
      .subscribe(it => {
        this.model.negligenceDefendants = [];
        this.model = { ...this.model };
      });
  }
```

**Comment by aitboudad** [comment]
> But if I do this, It seems like I go into a cycle and the app gets stuck.

Assigning a new value should based on some condition else you may end into a loop, use for example try to apply `distinctUntilChanged` pipe.

Note: hooks can handle the subscription if you return an observable
