### ISSUE TITLE
Required property not working properly

### ISSUE THREAD

**Issue by coolankitgupta** [ngx-formly/ngx-formly#3373]
**Description**
I have recently upgraded the application on Angular 13 and formly to 5.12.5 but stuck on an error, where we have required property on form control. It's working fine when we load the form first time, but if we enter any value in input field, and then remove it , required not working. It doesn't show red border on control. 

After investigation, I found that initially we have required property in errors but as soon as we enter the value, form control errors property gets null, and it doesn't retain the errors and form control gets valid. If we have a required field, the form stay valid even if we remove the value from the field.

 This is very critical issue. Pls see both screenshot below:

![image](https://user-images.githubusercontent.com/108867678/177742252-2382c627-ab9a-45c6-b0d6-1fe5eebf840b.png)

![image](https://user-images.githubusercontent.com/108867678/177741624-a1e6e170-b401-4570-a757-8d2788dace89.png)

Package.json
    "@angular/animations": "^13.3.10",
    "@angular/cdk": "^13.3.8",
    "@angular/common": "^13.3.10",
    "@angular/compiler": "^13.3.10",
    "@angular/core": "^13.3.10",
    "@angular/forms": "^13.3.10",
    "@angular/material": "13.3.8",
    "@ngx-formly/core": "^5.12.5",
    "@ngx-formly/material": "^5.12.5",
....

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: 13.3.7
- Formly version: 5.12.5

**Additional context**

**Comment by coolankitgupta** [comment]
Hi,

It's not on Angular 13, do u have any stackblitz starter kit on Angular 13

**Comment by aitboudad** [comment]
> do u have any stackblitz starter kit on Angular 13

https://stackblitz.com/edit/angular-zm3hsg

**Comment by coolankitgupta** [comment]
could you pls upgrade the stackblitz to Angular 13.. its not having Angular13

**Comment by aitboudad** [comment]
> [stackblitz.com/edit/angular-zm3hsg](https://stackblitz.com/edit/angular-zm3hsg)

please check again, Angular 13 is the used version.

**Comment by aitboudad** [comment]
Please feel free to leave a comment once you've a got a reproduction example so we can check it further on our side and provide a fixed if needed.

Thank you!

**Comment by coolankitgupta** [comment]
its very difficult to reproduce it on stackblitz. If you have sometime, we can schedule a call. It was working fine with Angular 7 and formly v 5.4 but when we upgrade the libraries to Angular 13 with formly 5.12.5 , it's start breaking. Please let me know.

**Comment by aitboudad** [comment]
Another solution is to create a private repository where you add a minimal part of the original source that reproduce the issue and send me an invitation so I could investigate on it.

**Comment by coolankitgupta** [comment]
I have reproduced the issue on stackblitz. The issue is when we have formlyform inside loop and passing variable in [fields] input property, then the validation works only first time and when you remove the values then validation stops working. The form stay valid even if we remove the value from the field. 

Please check below url and re-open the bug

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-rr6i2p?file=src%2Fapp%2Fapp.component.html

**Comment by coolankitgupta** [comment]
can we have a fix for this issue, otherwise we need to change a lot. We also having tab structure with Accordion for formGroup, but I have tried using formly-field, it doesn't render anything.

**Comment by aitboudad** [comment]
I did some attempts but without success, right now you've two solutions:
- Downgrade to https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.26
- Or use the new approach which is simple to implement by following these steps:
  
1. Create a custom type `tabs`:
```ts
// tabs.type.ts
import { Component } from '@angular/core';
import { FieldType, FormlyFieldConfig } from '@ngx-formly/core';

@Component({
  selector: 'formly-field-tabs',
  template: `
      <div *ngFor="let tbs of field.fieldGroup;let i =index">
        <ng-container *ngIf="tbs">
          <h3>{{tbs.templateOptions.tabName}}</h3>
          <formly-field [field]="tbs"></formly-field>
        </ng-container>
      </div>
`,
})
export class FormlyFieldTabs extends FieldType {}
```

2. declare `FormlyFieldTabs`in NgModule declaration:
```patch
// app.module.ts
+ import { FormlyFieldTabs } from './tabs.type';

@NgModule({
  imports: [
    FormlyModule.forRoot({
+      types: [
+        { name: 'tabs', component: FormlyFieldTabs },
+      ],
    }),
  ],
})
export class AppModule { }

```

3. Use one `formly-form` tag:
```html
// app.component.html
<form [formGroup]="form" (ngSubmit)="submit()">
  <formly-form [model]="model" [fields]="tabs" [options]="options" [form]="form"></formly-form>
</form>
```

4. Use tabs type in `tabs` property:

```ts
// app.component.ts
tabs = [{
  type: 'tabs',
  fieldGroup: [
    {
      templateOptions: {  tabName: 'Address' },
      fieldGroup: this.fields1,
    },
    {
      templateOptions: {  tabName: 'Personal Detail' },
      fieldGroup: this.fields2,
    },
  ]
}];
```
here is a working example which is based on your stackblitz https://stackblitz.com/edit/ngx-formly-ui-bootstrap-qmln6c
