### ISSUE TITLE
Angular Formly overrides model data on UI for same form fields with different <formly-form> instances

### ISSUE THREAD

**Issue by RiturajKandiyal** [ngx-formly/ngx-formly#3374]
I am making use of 2 <formly-form> tags to render my form on UI which have same fields but model value is different for both. The model value to these tags are coming from indexes of an array. The form renders properly on UI with all the form fields but somehow the values to these form fields are duplicating. The model values seem to somehow override the values in the array while rendering or something else.
Please find below the link to my stackblitz project depicting the same.

https://stackblitz.com/edit/formly-example-ekckzs?file=src/app/app.component.html

Any kind of help is highly appreciated. Also please comment for any clarification on the same.

**Comment by aitboudad** [comment]
Passing the same fields instance may provide an unexpected result, you can use one of the following solution:

- Copy fields: https://stackblitz.com/edit/formly-example-nq3znp?file=src/app/app.component.ts
- use `immutable` mode: https://github.com/ngx-formly/ngx-formly/issues/3294#issuecomment-1126875866
- use custom type https://formly.dev/examples/advanced/multi-step-form
- use repeatable type: https://formly.dev/examples/advanced/repeating-section
