### ISSUE TITLE
pass a templateRef to a custom formly field in ngOnInit lifecycle

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#3375]
I want to pass a template reference to a custom firmly field like that:

app.component.html
```
<form>
  <formly-form [fields]="fields"></formly-field>
  <ng-template #example> some content </ng-template>
</form>
```
I use `@ViewChild` to get a reference to this template
app.component.ts
```
 @ViewChild('example') exampleTemplate: TemplateRef<any>;

ngOnInit(){
  this.fields = [{
    type: 'custom',
    templateOptions:{
      template: exampleTemplate
   }
 }]
}
```

now, I can use this template in the custom firmly field
custom-field.html
```
<ng-container  *ngTemplateOutlet="  to.template; context: {  } "></ng-container>
```

this solution has some drawbacks:
- `@viewChild` only available just before `ngAfterInit` i.e after `ngOnInit`
- if we set `this.fields` in `ngAfterInit` lifecycle, Angular complains about changing the view after it has been checked

I already read [this issue](https://github.com/ngx-formly/ngx-formly/issues/2086) but it seems not the same situation

**Comment by aitboudad** [comment]
Hi, for https://github.com/ngx-formly/ngx-formly/issues/2086#issuecomment-584847953 we rely on `ChangeDetectorRef` to detectChanges so similarly you could use one of the following solutions: inject `ChangeDetectorRef` and and mark the view for check `markForCheck`, use `setTimeout` or `Promise.resolve()`.

**Comment by eng-dibo** [comment]
I already read this comment before opening the issue, you passed the template as a whole field, but in my case I want the template to be injected inside a custom formly field.

also I didn't find anything about the proposal solutions in the mentioned comment
> inject `ChangeDetectorRef` and and mark the view for check `markForCheck`, use `setTimeout` or `Promise.resolve()`.

**Comment by aitboudad** [comment]
> inject `ChangeDetectorRef` and and mark the view for check `markForCheck`, use `setTimeout` or `Promise.resolve()`.

try this for example:

```ts
//  set `this.fields` in `ngAfterInit` lifecycle,
Promise.resolve().then(() => {
  ....
});
```

**Comment by eng-dibo** [comment]
> ```ts
> Promise.resolve().then(() => {
>   ....
> });
> ```

this worked, but what is the philosophy behind `Promise.resolve()` in `ngAfterInit` ?
