### ISSUE TITLE
Ngrx with Angular Formly and Angular Material

### ISSUE THREAD

**Issue by StefaniToto** [ngx-formly/ngx-formly#3384]
Im using a combination of formly ,ngrx and material. There are few issues that managed to fix and some other on doubt.

Demo is below on stackblitz. :

https://stackblitz.com/edit/new-project-3gxwan?file=src%2Fapp%2Fshared%2Fcomponents%2Fformly-table-generic%2Ftable.ts,src%2Fapp%2Fshared%2Fcomponents%2Fformly-table-generic%2Ftable.html

  1.   Im trying to build a filter service and as model have passed an observable. As we filter data of observable change and also model, **BUT** the view doesnt change. I managed to recall the model and its working but it doesnt look like the most efficent way. especially on big data the view freeze till searching completed.

  2.   As on NGRX state is immutable is expected that for every change to be dispatched an action and model to be changed. However the only way to achieve that it was to create my own elements. So in the example if under main.ts comment the following code (my own checkbox element)
    
    ` {
          name: 'checkbox',
          component: FormlyFieldCheckbox,
          wrappers: [],
        }`
In table will be implemented tha material checkbox and when we check it will be displayed the read-only error.

   3.  As elements are custom (checkbox) the only way to pass the values is through hooks. Its any possible way to pass directly the values from the templateoptions as have tried ?
   
   ` templateOptions: {
                checked: this.model.dataTable['allowDownload'],...`

    4.  Sorting through each columns its not working despite the *matColumnField match with the key name.

**Comment by aitboudad** [comment]
> 1. Im trying to build a filter service and as model have passed an observable. As we filter data of observable change and also model, BUT the view doesnt change. I managed to recall the model and its working but it doesnt look like the most efficent way. especially on big data the view freeze till searching completed.

use MatTableDataSource as Observable and rely on `field.formControl.valueChanges` instead `field.fieldGroup`

> 2. As on NGRX state is immutable is expected that for every change to be dispatched an action and model to be changed. However the only way to achieve that it was to create my own elements. So in the example if under main.ts comment the following code (my own checkbox element)

enable `immutable` mode: https://github.com/ngx-formly/ngx-formly/issues/3253#issuecomment-1087860434

> 3. As elements are custom (checkbox) the only way to pass the values is through hooks. Its any possible way to pass directly the values from the templateoptions as have tried ?

The question is not clear enough, if you would like to set an initial value you may use `defaultValue` property.

> 4. Sorting through each columns its not working despite the *matColumnField match with the key name.

You should apply `sort` to the rendered data

**Comment by aitboudad** [comment]
**Note**: to get notified about `model` change use `(modelChange)` output:

```html
<formly-form ... (modelChange)="onModelChange($event)" ...></formly-form>
```

**Comment by StefaniToto** [comment]
> use MatTableDataSource as Observable and rely on `field.formControl.valueChanges` instead `field.fieldGroup`

Can you give a hint please @aitboudad ? The issue is that also this.model = { ...this.model } its not responding to the model change.


>You should apply sort to the rendered data

Sort is already applied but its working only when the key:"key" and not in other cases. For example the column below will work on sorting the elements.

` {
              **key: 'key',**
              type: 'input',
              className: 'flex-1',
              templateOptions: {
                type: 'text',
                name: 'allowDownload',
              },
            },`

**Comment by aitboudad** [comment]
> Can you give a hint please @aitboudad ? The issue is that also this.model = { ...this.model } its not responding to the model change.

```patch
export class MyFormlyArrayTypeComponent implements OnDestroy {
+  onDestroy$ = new Subject<void>();
  ...
  ngOnInit(): void {
    this.field.templateOptions.remove = this.remove.bind(this);
    ...

+   this.formControl.valueChanges.pipe(takeUntil(this.onDestroy$)).subscribe(() => {
+       this.dataSource.data = this.field.fieldGroup;  
+   });
  }

+  ngOnDestroy(): void {
+    this.onDestroy$.next();
+    this.onDestroy$.complete();
+  }
}
```

For `FormFieldOverviewExample`, do not rely on `model` and instead pass `productCategories`:
```
<div *ngIf="productsAndFilters$ | async as productCategories">
  <formly-form
    [form]="form"
    [model]="productCategories"
    [fields]="fields"
    [options]="options"
    (modelChange)="onModelChange($event)"
  ></formly-form>
</div>
```

**Comment by StefaniToto** [comment]
@aitboudad This is not working properly since formcontrol its not detecting all changes. 

Just made all updates as you noticed and despite model and fielgroup are taking the changes the form will not update properly. 

https://stackblitz.com/edit/new-project-dwna1h?file=src%2Fapp%2Fshared%2Fcomponents%2Fformly-table-generic%2Ftable.ts,src%2Fapp%2Fform-field-overview-example.ts

**Comment by aitboudad** [comment]
> Working after adding also this.fields = [...this.fields]; otherwise the fieldgroup wasnt taking all the changes.

it should work without `this.fields = [...this.fields]`, can you try with `delay` operator:

```patch
+   this.formControl.valueChanges.pipe(delay(100), takeUntil(this.onDestroy$)).subscribe(() => {
+       this.dataSource.data = this.field.fieldGroup;  
+   });
```

> Do you have any tip for sorting also please ?

use `sortingDataAccessor`:

```patch
  ngOnInit(): void {
    this.field.templateOptions.remove = this.remove.bind(this);
    this.dataSource.data = this.field.fieldGroup;
+   this.dataSource.sortingDataAccessor = (obj, property) => obj.formControl.get(property).value;
    ...
}
```

**Comment by StefaniToto** [comment]
@aitboudad Thank you veyr very much bro. Working like a charm.
