### ISSUE TITLE
Custom field templateOptions documentation

### ISSUE THREAD

**Issue by jy006** [ngx-formly/ngx-formly#3387]
I've made several custom form fields for my app, some of them require additional options to be passed/supplied, and I added them to `templateOptions`. For example:
```
{
  key: 'production',
  type: 'table-select',
  className: "col-6",
  templateOptions: {
    label: 'Production',
    required: true,
    options: subject,
    labelField: 'id',
    pointer: pointerObservable,
  },
},
```
I added `labelField` and `pointer` for this `table-select` type form. The problem is when another programmer wants to use this custom field for another form, there is no way for this person to know what extra attributes have to be supplied for the field to work properly, e.g. intellisense in vs code cannot show these stuff.

As for now I just have to write basically a text document (in either .md and xwiki format) detailing how these custom component work. Is there a better way to document custom form fields?

**Comment by MaxKless** [comment]
Just chiming in to show you my approach without json schema.
1. [Write a custom ESLint rule](https://github.com/intershop/intershop-pwa/blob/develop/docs/sync-formly-docs.ts) to require all formly artifacts (`types`, `wrappers` & `extensions`) to have JSDoc comments with the used `templateOptions`.
2. [Write a script](https://github.com/intershop/intershop-pwa/blob/develop/docs/sync-formly-docs.ts) that parses the source files and comments to construct a table of all available custom formly types.
3. Add the script to your CI pipeline to make sure that you always have correct, up-to-date information.

I've added links to the code that I wrote, no guarantee that it works for you :D

**Comment by jy006** [comment]
I'm not sure I understand, so I'm gonna be digesting the answers slowly 1 by 1.

> 1. Create an interface in that file that has those fields defined and type the templateoptions ad a union of that type plus base to type.
How do I type the templateOptions? Because currently templateOptions is an attribute of FormlyFieldConfig, so changing the type of templateOptions (to a union of the new type/interface) requires changing FormlyFieldConfig (?).

> define a jsdoc style comment structure ovee the redefinition of template options in the file
Jsdoc make sense, but jsdoc in this case doesn't show up the same way as jsdoc in classes and methods. Unless I misunderstood your answer.

As for JSON Schema I've never used them so I'd have to explore them first, but if you could give an example I'd be very grateful. Thank you @kenisteward.
