### ISSUE TITLE
Change in form state not updated

### ISSUE THREAD

**Issue by erikvdv1** [ngx-formly/ngx-formly#3388]
**Description**
In version 6.x changes in form state are not properly detected. When toggling the state in the example the field disabled state is not updated until you type a character in one of the input fields.

**Minimal Reproduction**
The example is based on the official formly [example](https://main.formly.dev/examples/form-options/form-state) with one extra field.

https://stackblitz.com/edit/angular-elz28t?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 14.0.6
- Formly version: 6.0.0-rc.1

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.0-rc.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.0-rc.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by erikvdv1** [comment]
Thanks, it seems to work now!
