### ISSUE TITLE
Custom field ngOnChanges method is not running on field property reference change.

### ISSUE THREAD

**Issue by GavishiddappaMG** [ngx-formly/ngx-formly#3389]
I've some custom fields. I want run some code inside **ngOnChanges** methods of these custom field components. I tried updating the fields and form group input property references in parent component where formly-form component is rendered. On change of fields data change I want ngOnChanges method to be run. Its not happening now. All the custom fields components have default change detection strategy

```
export class CustomFieldComponent extends FieldType implements OnInit, OnChanges {
  ngOnChanges(changes: SimpleChanges): void {
   // code to run here
  }
}
```
Is there any better way to do it ?

**Comment by aitboudad** [comment]
Try with one of the following methods `prePopulate`, `onPopulate` or `postPopulate`:

```
export class CustomFieldComponent extends FieldType {
  prePopulate(field: FormlyFieldConfig): void {

  }
}
```

**Note**: rely on `field` argument and not  `this.field` on theses methods.
