### ISSUE TITLE
Wrappers break angular material input styles

### ISSUE THREAD

**Issue by GreedyA1** [ngx-formly/ngx-formly#3390]
![image](https://user-images.githubusercontent.com/18186211/180368637-263a6add-9630-4854-83a4-e8539a5371db.png)

**Description**
When applying wrapper to Angular material Inputs they break the styles. 
The styles don't break when applying wrapper and putting the input in fieldGroup. 

```
fields: FormlyFieldConfig[] = [
    {
      key: 'DOESN"TWORK',
      type: 'input',
      wrappers: ['panelll'],
      templateOptions: {
        label: 'DOESN"TWORK',
        placeholder: 'DOESN"TWORK',
        description: 'Description',
        required: true,
      },
    },
    {
      key: 'Address',
      wrappers: ['panelll'],
      fieldGroup: [
        {
          key: 'WORKS',
          type: 'input',
          templateOptions: {
            label: 'WORKS',
            placeholder: 'WORKS',
            description: 'Description',
            required: true,
          },
        },
      ],
    },
  ];
}
```

**Minimal Reproduction**
[stackblitz](https://stackblitz.com/edit/angular-hg2w1p?file=src/app/app.component.ts)

[another reproduction](https://stackblitz.com/edit/ngx-formly-ui-material-2psubv?file=src/app/app.component.ts)

**Your Environment**
![image](https://user-images.githubusercontent.com/18186211/180367502-1c0ecd21-8397-4320-bc7d-b195eab72bc0.png)

**Comment by aitboudad** [comment]
with that config you replaced the default material wrapper (form-field) with panel, instead try one of the following solution:

1. add `form-field` to wrappers: 

```patch
-  wrappers: ['panel'],
+  wrappers: ['panell', 'form-field'],
```

2. use `fieldGroup`, you may check the address field in the following example: https://formly.dev/examples/other/nested-formly-forms
