### ISSUE TITLE
Search in multi-select

### ISSUE THREAD

**Issue by behoyh** [ngx-formly/ngx-formly#3391]
Hi, I was wondering if ngx-formly supported a client-side search of all items in in a multi-select, filtering the results down as you type.
![image](https://user-images.githubusercontent.com/2565745/180581604-d1477426-7060-4bdf-bfdc-6b8ae464ae25.png)

**Comment by aitboudad** [comment]
Not supported, you need to create a custom type with of the following solution:

1. https://github.com/bithost-gmbh/ngx-mat-select-search
2. https://github.com/ngx-formly/ngx-formly/issues/708#issuecomment-364903803
