### ISSUE TITLE
The validators set an object to form errors

### ISSUE THREAD

**Issue by wizardnet972** [ngx-formly/ngx-formly#3393]
**Description**
I get `{ "0": true }` in `form.errors` object.
```
{{ form.errors | json }}
```
this is because I add `validators` in the form level:

```
 fields: FormlyFieldConfig[] = [
    {
      validators: [
        () => {
          console.log('validate in form level..');
          return null;
        },
      ],
      fieldGroup: [
        {
          key: 'text',
....
```

**edit**
I checked this code and `validators` should return `true` is valid or otherwise if invalid. but angular say null is valid otherwise is invalid.

it is a little bit confusing.

**Minimal Reproduction**

[stackblitz](https://stackblitz.com/edit/angular-x95fcw?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html)

**Your Environment**

- Angular version: 14
- Formly version: 6.rc1

**Additional context**

**Comment by aitboudad** [comment]
We expect `validators` to be an object, right now we support two types of format:

- return a boolean value (valid or not):
```ts
validators: {
 email: c => isEmail(c.value) // return boolean
},
```

- Angular validator format through `validators.validation` property:

```ts
validators: {
  validation: [
    () => {
      console.log('validate in form level..');
      return null;
    }
  ],
},
```
