### ISSUE TITLE
Using a shared FormComponent more than twice throws `ExpressionChangedAfterItHasBeenCheckedError`

### ISSUE THREAD

**Issue by sjoulbak** [ngx-formly/ngx-formly#3396]
⭐'ed it 😄 

**Description**
We have a general component (lets call it `FormComponent`) which implements a `form` with a `formly-form`. This component is used to add some `HostListener`s. Back in the days we had to add [FormlyFormBuilder.buildForm](https://github.com/ngx-formly/ngx-formly/blob/v5.10.26/src/core/src/lib/services/formly.form.builder.ts#L16) to the `ngOnInit` of that component to prevent getting the `ExpressionChangedAfterItHasBeenCheckedError` exception (removing this seems not to resolve the new issue and it also brings this previous scenario back). 

We have avoided updating this dependency since we got the same exception after the release of [v5.10.27](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.10.27). It happens when we add our `FormComponent` more than 2 times in the same template, using the same `form` but different fields at least once.

It's been a while and I wanted to keep this dependency up to date as well, so I tried updating it again to the latest version. Unfortunately we still got the same exception.

**Minimal Reproduction**
Can be found at: https://github.com/sjoulbak/formly-bug-multi-form

Run `yarn run test` to see the exception.

**Your Environment**

- Angular version: 14.1.0
- Formly version: 5.12.6

**Comment by aitboudad** [comment]
The issue is caused by `formGroup` input which is used by `FormGroupDirective`, the solution is to use a different name
such as `form` for example:

```patch
- <app-form [formGroup]="form" ...></app-form>
+ <app-form [form]="form" ...></app-form>
```

**Comment by sjoulbak** [comment]
(back from 🌴😄) Thank you for your suggestion @aitboudad! I applied it to the minimal reproduction app (see https://github.com/sjoulbak/formly-bug-multi-form/commit/515d1b0086b81923e6e2b5a90afc391faf92e6d9). Unfortunately it only fixes 2 of the 3 specs, one of them is still throwing the same error. Do you have another suggestion?

**Comment by aitboudad** [comment]
>  Do you have another suggestion?

will check!

**Comment by aitboudad** [comment]
Hi, I think it would be better to test against v6 to see if the issue is still persist.

**Comment by sjoulbak** [comment]
Unfortunately I still get the same error with:
- Angular version: 14.2.10
- Formly version: 6.0.2

**Comment by aitboudad** [comment]
I see, so the root issue is passing the same form instance to multi-component causes an update in the form state during the same cycle:
- first render: form state updated to valid
- second render: form state updated to invalid

What I'd suggest is if possible to use multi `formly-field` instead, to have an idea check the following example https://formly.dev/docs/examples/advanced/tabs/
