### ISSUE TITLE
yarn vs npm

### ISSUE THREAD

**Issue by MaxKless** [ngx-formly/ngx-formly#3397]
Hi,
when you install formly deps using `yarn`, you get this warning:

`warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.`

Also, there's no yarn lockfile which means that by default, one is generated after installing deps.

@aitboudad , can you provide some insight as to why `yarn` is used over `npm` and why there's a `package-lock.json`?

**Comment by aitboudad** [comment]
Right now we rely on `npm` only and it's the recommended tool for Formly. When yarn was introduced its main advantage was speed which is not the case anymore since `npm` fixed that issue also `yarn` present an additional dependencies and `npm` is available by default.

**Comment by MaxKless** [comment]
Okay makes sense, I didn't see the updated `CONTRIBUTING.MD` from [`chore(release): 6.0.0-rc.1`](https://github.com/ngx-formly/ngx-formly/commit/2f7361e01e477b75d29e73a943a619978c9c8330).
