### ISSUE TITLE
Are there any examples of long forms?

### ISSUE THREAD

**Issue by technbuzz** [ngx-formly/ngx-formly#3398]
Usually the official example address a specific problem. Are there any examples that would handle the complex forms? Where there are many level deeply nested fields, including arrayFields and so on?

**Comment by MaxKless** [comment]
For large forms, have a look at this virtual scroll example (from #2762): https://stackblitz.com/edit/angular-rfwvp6

There's a bunch of issues around this topic on here, just search for 'long' or 'large'.
