### ISSUE TITLE
How to handle long forms with formly

### ISSUE THREAD

**Issue by technbuzz** [ngx-formly/ngx-formly#3399]
I have model like below
```
const model = {
  a: {
    a1: '',
    a2: '',
    a3: ''
  },
  b: {
    b1: '',
    b2: '',
    b3: [
      {
        ba: {
          ba1: '',
        }
      }
    ]
  }
}
```
Now I end up writing fields like below
```
const fields = [
  {
    key: 'a',
    fieldGroup:[
      {
        key: 'a1'
      }
      //....
    ]
  },
  {
    key: 'b',
    fieldGroup: [
      {
        key: 'b1'
      },
      // ...
      {
        key: 'b3',
        fieldGroup: [
          {
            key: 'b3a1'
          }
        ]
      }
    ]
  }
]
```
This ends up rendering very bad aligned HTML because of the **nested fieldgroup**. I want the model nested structure to not interfere with fields and it's html representation. What are the options out there that could help me. I see there are wrappers but what else can help me?

**Comment by aitboudad** [comment]
if you don't need fieldGroup, you can use nested key: `a. a1` instead:

```ts
const fields = [
  { key: 'a.a1' },
  ....
];
```

>  I want the model nested structure to not interfere with fields and it's html representation. What are the options out there that could help me.

https://github.com/ngx-formly/ngx-formly/issues/2710#issuecomment-804500185

> For array items

https://main.formly.dev/docs/examples/advanced/repeating-section/
