### ISSUE TITLE
shouldLabelFloat and custom Material control

### ISSUE THREAD

**Issue by tzehetner** [ngx-formly/ngx-formly#3401]
I have a custom Formly field type that contains a matInput textbox which uses a custom ControlValueAccessor directive, similar to matDatepicker. If the entered text value cannot be parsed, the model value is set to null by my ControlValueAccessor implementation, like it's done by matDatepicker. Unfortunately this makes the label move down over the invalid text in the textbox. I guess this happens, because the FieldType.shouldLabelFloat implementation checks only the parsed value from the form model (which is null), but not the actual text of the native input element.

I checked the Formly datepicker field type implementation, which should also have this problem, because the Material datepicker also sets the model value to null, if the date string cannot be parsed. Interestingly the label floats correctly, but I don't understand why.

How can I fix this? How does the Formly datepicker do it?

**Comment by aitboudad** [comment]
A `stackblitz` example is needed so we can check further. Feel free to leave a comment once you've got a reproduction example, Thank you!

**Comment by tzehetner** [comment]
@aitboudad We updated Angular, Material and Formly to the latest versions, which fixed the problem!
