### ISSUE TITLE
top level validators set at creation of `FormGroup` are removed

### ISSUE THREAD

**Issue by gkamperis** [ngx-formly/ngx-formly#3402]
**Description**

Atm when creating a new `form` to pass on the `<formly-form [form]="form" `

Setting top level cross field validation that we want to apply across all fields of the config like so
```
form = new FormGroup({}, { validators: { ... } } )
```

is removed.

I suppose we could add everyting under a "fake" top level field but that should not be the way to go.

At first glance calling `addValidators` vs `setValidators` (in the `ngx-formly/core` code) should allow us to keep our top level validators.

**Your Environment**

- Angular version: 13.3
- Formly version: X5.10.28

**Additional context**

**Comment by aitboudad** [comment]
You can pass the top level validators to the root field definition: https://formly.dev/examples/validation/matching-two-fields

**Comment by gkamperis** [comment]
@aitboudad that wll validate only that field (and sub) though. 
what if I want to validate across multiple of these andtheir subs?

**Comment by aitboudad** [comment]
> that wll validate only that field (and sub) though.

no, it'll be similar to `form = new FormGroup({}, { validators: { ... } } )`, just ensure that the field doesn't have a key.

**Comment by gkamperis** [comment]
@aitboudad tried to add just a field with only `{ validators: { validation: [ () => {}]} }`.
Does not work. 

it gets called once on startup but not on every field change of any of the fields in the form.

As already mentioned in my opening post I could make all the fields be a `fieldGroup` of that top level single key-less field but I do not see why this should be the case.

The `form` object I configured should be respected.

Other workaround was with `setTimeout` calling `addValidators` on the form object and that worked too but it is as ugly if not uglier.

**Comment by aitboudad** [comment]
> it gets called once on startup but not on every field change of any of the fields in the form.

Not true, it gets called on every field change, check the console of the following example https://stackblitz.com/edit/angular-1pwjhe?file=src/app/app.component.ts

**Comment by gkamperis** [comment]
@aitboudad 
> > it gets called once on startup but not on every field change of any of the fields in the form.
> 
> Not true, it gets called on every field change, check the console of the following example https://stackblitz.com/edit/angular-1pwjhe?file=src/app/app.component.ts

You misunderstood my comment. 
I added a separate independent field (next to my other fields) with only `{ validators: { validation: [ () => {}]} }.`

You are wrapping every field inside a top level field with the validation.
I know that this works and I already mentioned in my initial post but this is a workaround not a solution.

**Comment by aitboudad** [comment]
I see, just pass `fieldGroup: []` to make it work: https://stackblitz.com/edit/angular-1pwjhe-o5uj7u?file=src/app/app.component.ts

**Comment by gkamperis** [comment]
@aitboudad confirmed adding an empty `fieldGroup: []` works in a similar way giving access to the top level form control.

Again to me this is a workaround. 
There are no docs for all these "magic" settings and the behaviour.

Also, I can be providing a cofigured `Form` object which is not going to be observed.

**Comment by aitboudad** [comment]
> Again to me this is a workaround.

it's not a workaround, any field with `fieldGroup` that doesn't have key share the `form` instance of the parent.

> There are no docs for all these "magic" settings and the behaviour.

Any help is appreciated to improve the doc 🙏!
