### ISSUE TITLE
Mapping key to a particular array element

### ISSUE THREAD

**Issue by coderdags** [ngx-formly/ngx-formly#3406]
if i have this json data

```
{
	"lastName": [{
		"test": "testingA",
		"type": "a"
	}, {
		"test": "testingB",
		"type": "b"
	}],
	"firstName": "This is a default value",
	"candy": "milky_way"
}
```
how can I set the key of formfield to the last name array element where the type is equal to "b"

I know it's possible to do it by passing the element index like below
```
    {
      key: 'lastName[1].test',
      type: 'input',
      defaultValue: 'This is a default value',
      templateOptions: {
        label: 'Last Name (initialized via the model)',
      },
    },
```
is there any way to use a filter in the key field where i can say the key is an element in lastname array where the type is equal to "b"

here's a sample code 

https://angular-jnmy8n-7ddlpv.stackblitz.io/

**Comment by aitboudad** [comment]
The solution is to find the key first before initializing the fields property:

```ts
fields = [];
...

initFields(model) {
  const key = getTestKey(model);
  this.fields = [...];
}
```
