### ISSUE TITLE
i have a problem when i try to install formly/material

### ISSUE THREAD

**Issue by its0beno** [ngx-formly/ngx-formly#3407]
![image](https://user-images.githubusercontent.com/95960560/182688858-60d001f4-ec81-486c-8bf6-7a0e6c502830.png)
so when i try to download can u help me please it is urgent

**Comment by its0beno** [comment]
![image](https://user-images.githubusercontent.com/95960560/182690663-772f1483-c8aa-493c-a3a3-b4a12a5b8607.png)
this is the full image

**Comment by aitboudad** [comment]
Could you please check  `next` version: https://main.formly.dev/docs/guide/getting-started#1-install-formly-packages
For other alternatives solution you may try with `npm install --force`.
