### ISSUE TITLE
Change placeholder text dynamically

### ISSUE THREAD

**Issue by adora-tech** [ngx-formly/ngx-formly#3408]
Hello all,

I looked for how to do this, but I didn't find anything to help me.

Is there any way to change the placeholder text, dynamically, based on the value of another field?
I tried to use expressions and props.placeholder but I didn't manage to get results.

Thank you!
Iulius

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-29yuk9?file=src/app/app.component.ts

**Comment by adora-tech** [comment]
Hello,

What was wrong, was the fact that I use an extension that translates the placeholders globally.
This rewrites my action to modify the placeholder on a specific field locally.
So, I treat this case as a particular one and I treat it locally, without translating globally.

@aitboudad
Now everything works fine.
Awesome library!

Thank you!
Iulius Ciorica
