### ISSUE TITLE
refresh render of controls in second tab

### ISSUE THREAD

**Issue by coderdags** [ngx-formly/ngx-formly#3409]
I combined the idea from the tabs sample https://formly.dev/examples/advanced/tabs and repeating section sample https://formly.dev/examples/advanced/repeating-section

where I've got two tabs and each tabs uses the same array for the fields. when i'm in the first tab and clicked on the add another investment button it adds a new section to enter some data and the model gets updated with a new object. when i go to the second tab which is the same fieldgroup as in the first tab, it's still have 1 section instead of 2. if i click the add another investment button in the second tab it will display 3 sections. 

here's a sample code https://angular-bz1ogy-dqc1uy.stackblitz.io/

is there anyway to trigger the second tab to update the sections when a new object gets added to the array from the 1st tab.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
