### ISSUE TITLE
JsonSchema: required properties is ignored for array type

### ISSUE THREAD

**Issue by Garfield-fr** [ngx-formly/ngx-formly#3411]
**Description**
Using a jsonschema with required properties on items array type, the input field is not required.

Before version 5.11, the star appears on the required field. After, it disappears and the field is no longer required. If you set a default value, it reappears.

**Minimal Reproduction**
1. Go the stackblitz page.
2. Name should display a start (required).

If you put model value for the name, the star is present.

__Note__: the bug is present since version 5.11.0

https://stackblitz.com/edit/angular-zrnadk-rbp2bp

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.12.6

**Comment by aitboudad** [comment]
The issue has been fixed in `v6` https://stackblitz.com/edit/angular-bvnanb,

For v5 please try with the following workaround:
```patch
  "minItems": 1,
  "title": "Cars",
  "type": "array",
- "default": [null]
+ "default": [{}]
```

It is related of missing type validator (object/array) which is not added in v5 due to the some limitation that we've experienced.
