### ISSUE TITLE
[support] make a field depend on multiple fields

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#3412]
I want to perform an http request to get a field's options, but only when other fields have values, other fields may get theirs options by HTTP requests

example:

```
fields= [
 { key: 'field1', type:'select', templateOptions:{options: http.get('/field1')},
 { key: 'field2', type:'select', templateOptions:{options: http.get('/field2')},
{
 key: 'field3',
 dependencies: ['field1', 'field2'] // <-------------------
}
```

**Comment by aitboudad** [comment]
you may use a shared service where you emit the value of these fields when its resolved and pass it to the field 3:

```ts
  fields: FormlyFieldConfig[] = [
    {
      key: 'field3',
      templateOptions:{
        options: service.get('/field3')
      }
    }
  ];
```

**Comment by eng-dibo** [comment]
do you mean that `service.get('/field3')` is of type Observable or Promise instead of object?
and how would it looks like?

I see it like:
```
get(field:string, dependencies: string[]){
  return new Observable(sub=>{
      /* wait until all dependencies have values */
  })
```

**Comment by aitboudad** [comment]
> do you mean that `service.get('/field3')` is of type Observable or Promise instead of object?

Observable type

> I see it like:
```
get(field:string, dependencies: string[]){
  return new Observable(sub=>{
      /* wait until all dependencies have values */
  })
```

yes something like that.

**Comment by aitboudad** [comment]
Another solution is to rely on `fieldChanges` which emit the field options when they got resolved (https://github.com/ngx-formly/ngx-formly/issues/2350#issuecomment-658158267) but you should declare options in `expressionProperties` instead:

```ts
fields= [
 { key: 'field1', type:'select', expressionProperties:{'templateOptions.options': http.get('/field1')},
 ...
 {
      key: 'field3',
      hooks: {
        onInit: field => {
          field.templateOptions.options = field.options.fieldChanges....
        }
      }
 }
]
```

**Comment by eng-dibo** [comment]
ok, let me try this suggestion and get back to you
