### ISSUE TITLE
Get / Change value in formState instead of model via types?

### ISSUE THREAD

**Issue by afLennart** [ngx-formly/ngx-formly#3413]
Hello,

foremost, this is a great library, and you do a really good job maintaining it. I use this library in a project for more than 2 years now.

I have a case, where I have some values that are calculated from some fields and should not show up in the model, but they should show up as a field (input, select etc.). For example, one of these fields is a total price that is calculated from multiple prices. Also, I want to have change listeners for these values for further calculation. Obviously, one simple way to do this, is to just have the value in the model and ignore the extraneous props in the model. Another way that I tried, was to put these values in the formState, but I struggle with this. I would have to change all my custom types to accept either a key / formControl or a value in the formState. Because I use `checkExpressionOn: 'modelChange'`, I would have to put a BehavourSubject in the formState, to properly detect changes. Furthermore, I think that would break, for example, formly validation, because I ignore the FormControl object created. Do you have any tips on how to solve this easily with formly? I would love to see the option to specify a `formStateKey` instead of `key` for this case, but I could understand if this is too much of an edge case.

**Comment by aitboudad** [comment]
if you're using `expressionProperties`, then you may check `options.fieldChanges` observable.
We emit an event when an expression value is changed, for the emitted object see https://github.com/ngx-formly/ngx-formly/issues/2350#issuecomment-658158267
