### ISSUE TITLE
modelChange event on formly-form tag doesn't fire when I change the model

### ISSUE THREAD

**Issue by jon9090** [ngx-formly/ngx-formly#3415]
**Description**
When I change the model, the `modelChange` event not fire:

```
<formly-form [model]="model" [fields]="fields" [options]="options" [form]="form" (modelChange)="onModelChange()">
...
onModelChange() {
    console.log('in onModelChange');
}
...
<button (click)="changeModel()">change model</button>
..
changeModel() {
    this.model = { text: 'new text' };
 }
...

...

```
**Minimal Reproduction**

https://stackblitz.com/edit/angular-b43wet?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 14.1.2
- Formly version: 6.0.0-rc2

**Comment by aitboudad** [comment]
That's an expected behavior, when you change the model manually we assume that is an initial value and already known from your side.

For a solution to your needs you may just call `onModelChange` manually:
```patch
changeModel() {
   this.model = { text: 'new text' };
+  this.onModelChange...;
}
```
