### ISSUE TITLE
Showing error in array.type.ts file of jsonSchema example

### ISSUE THREAD

**Issue by navnita-170310093** [ngx-formly/ngx-formly#3416]
**Question**
I am creating a local formly app from jsonSchema.
In array.type.ts file, the line `   <div *ngIf="field.templateOptions.removable !== false" class="col-2 text-right">` is showing error.

**Error 1** : 
```
any
Object is possibly 'undefined'.ngtsc(2532)
Property 'removable' comes from an index signature, so it must be accessed with ['removable'].ngtsc(4111)
```

Then I changed the line to `<div *ngIf="field.templateOptions['removable'] !== false" class="col-2 text-right">`
Again it is showing error

**Error 2:**
```
declare,optional (property) FormlyFieldConfig.templateOptions?: FormlyTemplateOptions | undefined
This is reserved for the templates. Any template-specific options go in here. Look at your specific template implementation to know the options required for this.
```

Object is possibly 'undefined'.ngtsc(2532)

**My Local Environment**

Angular version: 13.3.0
Formly version: 5.12.6

I am new to angular and angular formly, please help me to resolve this,
What should write in that line

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2842#issuecomment-1016476706 or check Formly V6 example (https://main.formly.dev/docs/examples/advanced/json-schema) which enable strict template mode by default
