### ISSUE TITLE
input type date validation

### ISSUE THREAD

**Issue by tarektaamali** [ngx-formly/ngx-formly#3418]
Hi ,
I tried to used an input  with type date in templateOptions and a max today date . I found validation not working correctly when insert 
data without chosed from picker 
![image](https://user-images.githubusercontent.com/17914433/185362886-6294a3de-d732-4618-b7c7-e8db62791a1b.png)
validation in picker working correctly
![image](https://user-images.githubusercontent.com/17914433/185362641-c32609ec-099e-4484-bd1f-e03ac2adf049.png)

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
