### ISSUE TITLE
this.model inside FieldWrapper is empty

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#3419]
when you create a custom type and extend FieldWrapper, `this.model` inside this class is empty even if it has value in the host component
```
export class ChainWrapperComponent extends FieldWrapper {
 onClick(){
   console.log(this.model); // {}
   console.log(this.options.formState) // also empty
 }
}
```

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, using is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by eng-dibo** [comment]
**ignore this reply** as it just a side node for me

update [this repo](https://stackblitz.com/edit/ngx-formly-ui-material-b54yiz?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fcustom-field.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html) to refict the issue in entities/models/announcements.js
