### ISSUE TITLE
ExpressionProperties to conditionnally disable one option in a multicheckbox field

### ISSUE THREAD

**Issue by ChloeStevovitch** [ngx-formly/ngx-formly#3420]
Hello! 
I have two multicheckbox fields and I would like to conditionnaly disable options from one to the other according on the selection that is made
![Screenshot from 2022-08-18 14-17-47](https://user-images.githubusercontent.com/26826782/185466156-10878750-ecf1-472e-b2a0-f26b5ec14cd2.png)

For example :  When I select the first option on the first multicheckbox field (Jane), I would like that the first option on the second one get disabled, and reciprocally

I tried expressionProperties in order to achieve this but It seems that even if the option get the new field 'disabled : true' , the form is not getting updated if the modification happen after init

Here is an exemple : 
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-bgvozp?file=src/app/app.component.ts

note : this is working fine if I want to disable conditionnally all the options of the checkbox list but not If I want to disable only one option. Would you know how to make it work?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v5.12.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v5.12.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
