### ISSUE TITLE
Hide step in stepper

### ISSUE THREAD

**Issue by ashnav1msit** [ngx-formly/ngx-formly#3421]
I am trying to find out the solution to hide step in stepper on the basis of user input for other field using hide expression. But when user unhides it looses the control of the route. I wonder if this is supported by formly or if there is any way around this problem?

**Comment by aitboudad** [comment]
Hi,
The question is not clear, could you please provide an example using the following `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
