### ISSUE TITLE
Repeat-section form does not validates the fields until we change any repeated form field value

### ISSUE THREAD

**Issue by nikitagawande65** [ngx-formly/ngx-formly#3422]
When adding the second repeat, the form is still valid, but if you change one of the values, then the form validates and is no longer valid until all the required data is entered.

https://stackblitz.com/edit/angular13-bootstrap-vawnyq?file=src/app/app.component.ts

Enter the fields value, then form validates the field and if it is valid Submit button gets enabled and then click on Add button, you still see submit and add button is enabled and form is valid, until we touch any field it won't validate the form again.

- Formly version: 5.12.6

**Comment by ajjp** [comment]
Based in your example I needed to validate just by one of the repeat fields and did the following:

- Moved the validation to the section where the field that needs to be validated is and added some code:

`validators: {
                                duplicateValidator: {
                                    expression: (control) => {
                                        if (!control.pristine) {
                                            return this.validateDuplicateValue(
                                                control
                                            );
                                        } else {
                                            return true;
                                        }
                                    },
                                    message: 'Duplicate'

                                        )
                                }
                            }
`
- Changed the code in the validator

` validateDuplicateValue(_control): boolean {
        const valueArr = this.model.from.map(function (item) {
            return item.from;
        });
        const isDup = valueArr.includes(_control.value);
        return !isDup;
    }`

Not sure if it's what you're looking for, but here are my 2cts :)

**Comment by aitboudad** [comment]
The issue has been fixed in `v6`.
For `v5` you should rely on `formControl.value` instead of model in order to make work.
