### ISSUE TITLE
Build failing during deploying to server

### ISSUE THREAD

**Issue by StefaniToto** [ngx-formly/ngx-formly#3424]
![image](https://user-images.githubusercontent.com/32243109/186857443-88908abd-7b96-4953-9118-557bc894a1c9.png)

**Comment by aitboudad** [comment]
I think its related to Angular cli, try to increase the value of `max_old_space_size` https://stackoverflow.com/questions/46807355/heap-out-of-memory-in-angular4-while-ng-build-prod
