### ISSUE TITLE
Alternate strategies to make validators optional?

### ISSUE THREAD

**Issue by pimarian** [ngx-formly/ngx-formly#3425]
Hi,

I am trying to find a way to control the applicability of a validator on a specific field, based on the value of another field.
I am aware of the documented implementation where the validator is defined at the top level of the form and receives the whole form control. But given the high complexity of my specific form, it is not a good option for me.
Schematically, I am trying to define the form the following way:
```
  {
    "key": "validate",
    "type": "radio",  // YES/NO
  },
  {
    "hideExpression": "!(model.validate === true)",
     "key": "interestingField",
     "asyncValidators": { "validation": ["fieldValidation"]  }
  },
  {
    "hideExpression": "!(model.validate === false)",
    "key": "interestingField",
     // no validator
  }
```
This implementation does not work and the validator is triggered regardless of the value of the 'validate' field.
Is there a way to use make this work? My main constraint is to keep the single field key 'interestingField' and to be able to disable the validator in some condition.
The real form is a large tree and 'interestingField' appears at different depths.
I have implemented this example at https://stackblitz.com/edit/angular-legwvb

**Comment by aitboudad** [comment]
You may rely on field templateOptions or pass an extra options to make validators optional:
check the following example https://formly.dev/examples/validation/custom-validation-parameters which show how to pass extra parameters to the validators
