### ISSUE TITLE
can we add an html description without custom wrappers?

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#3429]
```
{
  key: "example",
  templateOptions:{
     description: '<b>html is not supported</b>', //<----------------
  }
}
```

I suggest modifying the default wrapper from `<div>{{to.description}}</div>` to `<div innerHTML="to.description"></div>` [like this](https://stackblitz.com/edit/ngx-formly-wrapper-description-top-ka4try?file=src%2Fapp%2Ffield-wrapper.component.ts,src%2Fapp%2Fapp.component.ts)

**Comment by MaxKless** [comment]
It's not a bad idea, would you want to open a PR?

@aitboudad what do you think about this feature?

**Comment by aitboudad** [comment]
Maybe under a flag, we may introduce it but it should not be the default behavior!
Close in favor of https://github.com/ngx-formly/ngx-formly/issues/2226.
