### ISSUE TITLE
Unit Test :: Unable to get Form Control object while writing unit test cases.

### ISSUE THREAD

**Issue by yogesh1991paisode** [ngx-formly/ngx-formly#3430]
Hello All,

I am not getting Form Control object while writing unit test cases when using Formly.

I have created sample StackBlitz for your reference :: [https://stackblitz.com/edit/angular-bn1vyj-exf5qf?file=src%2Fapp%2Fapp.component.spec.ts](https://stackblitz.com/edit/angular-bn1vyj-exf5qf?file=src%2Fapp%2Fapp.component.spec.ts)

**_Note: Sometimes testcases get pass in StackBlitz environment. In that case please restart the browser._**

Also, I have added below code snapshot for your reference:

![html](https://user-images.githubusercontent.com/112938096/188600576-bcfbc55a-223d-4d65-91d3-8aa5a8b030f3.JPG)

![Component](https://user-images.githubusercontent.com/112938096/188600618-3c46c5eb-a395-49aa-8081-44bfab54290b.JPG)

![1](https://user-images.githubusercontent.com/112938096/188612414-99987911-eeaa-4107-bdd6-bd6881c42f2f.JPG)

**_Note: Sometimes testcases get pass in StackBlitz environment. In that case please restart the browser._**

![image](https://user-images.githubusercontent.com/112938096/188613523-927f75f2-b9b3-4a69-b294-41fee7d51ff0.png)

**_Note: Sometimes testcases get pass in StackBlitz environment. In that case please restart the browser._**

I observed that Formly takes fraction of milliseconds to convert fields array object into Form Controls as a result we get [ null ] if try to get form controls.   

I tried with all like, tick, setTimeout, async, awit etc.

Thanks!

**Comment by yogesh1991paisode** [comment]
@aitboudad :: I added ngOnInit in the component to demonstrate the issue. The primary issue I am facing while writing Unit Testing. 
Our application is using Angular 9.1 with Formly v5 hence we can not use new testing features added in v6. We are wondering how we can add Unit Testing w.r.t Formly v5.

Could you please check app.component.spec.ts from Stackblitz: [https://stackblitz.com/edit/angular-bn1vyj-exf5qf?file=src%2Fapp%2Fapp.component.spec.ts](https://stackblitz.com/edit/angular-bn1vyj-exf5qf?file=src%2Fapp%2Fapp.component.spec.ts)

**Comment by aitboudad** [comment]
`TestBed.createComponent` need to be called right after `TestBed.configureTestingModule`:

https://stackblitz.com/edit/angular-bn1vyj-irudif?file=src/app/app.component.spec.ts
