### ISSUE TITLE
Duplicating a control removes required validation from another form control (JSON powered form)

### ISSUE THREAD

**Issue by timhemendinger** [ngx-formly/ngx-formly#3431]
Hi there, I just noticed that in my application one of the controls, which can be set to required, has the required status removed once a different control gets duplicated (a custom component that uses FieldArrayType). So the required field is no longer actually required when one repeats the other control. These two controls, aside from being in the same form, do not interact with one another (at least not in my own code).

Due to security policies I cannot use `expressionProperties` in the JSON to carry out the needed logic to determine if the field should be required. Also, I'm setting `required: true` in the `NgAfterViewInit` lifecycle hook of the component... I know there are other ways to do this but because this particular component in my actual app requires a lot of logic to determine if the component should be required/disabled or not, I'd prefer to leave it there if possible.

I created a much more simplified demo in Stackblitz to demonstrate the issue: https://stackblitz.com/edit/angular-9-starter-dvggab

Repeating component: _formly-guest-information.ts_
Component with the required issue: _signature.component.ts_

![image](https://i.imgur.com/dX0W8fv.gif)

Any ideas would be much appreciated, I haven't been able to figure out why this is happening.

**Comment by aitboudad** [comment]
Right now we rely on `hideExpression` and `expressionProperties` for JSON SCHEMA implementation, the security issue for expressions concern only when passing a string value which is not the case for JSON SCHEMA.

The solution for your case is to disallow passing string for `hideExpression` and `expressionProperties`.
