### ISSUE TITLE
Errors when a repeating field is removed by users - model has a lower field count than the template (JSON powered form)

### ISSUE THREAD

**Issue by timhemendinger** [ngx-formly/ngx-formly#3433]
I've run into an issue and unfortunately I can't think of any way to recreate it in a Stackblitz because the setup is complex, relies on different user roles and server-side storage, etc. However, I'll do my best to clearly explain the issue below.

**The setup of my app:** 

- An **admin** user creates and customizes their form. There is one form field that admins can duplicate (or remove duplicates of).  Any changes they make is saved and stored in the **template's JSON object**. They then send out the form to end users.
- **End users** fill out the form. The field that admins can duplicate in the template can also be duplicated by users, and the users can also remove any number of duplicated fields. The users' form information is stored in the **model** object. Any fields they duplicate or remove will also be reflected in that field's array in the model (I do not want users to be able to affect changes in the original template JSON). Ultimately, the model is the real source of truth, the length of the array for this duplicatable-field should always determine how many instances of the field should display on the form.
- Once a user fills out and submits their form, they can review a read-only version of the form.

**The issue:** because this duplicate-able field is determined both by the template JSON and also the model, there can be a discrepancy between them. Ex. The admin may have created a form with one field, but the user adds another one. So the template could indicate there is one field, but the model has two. Originally, when testing this out, as a user reviewing the submitted form, I was getting errors, because the form had not yet been built when I was trying to parse some of the template JSON in the code (Formly had not yet adjusted the template to have the extra field that existed in the model). However, adding this before doing the parsing fixed the issue:

```
// This must be used in order to ensure that the model and the Formly JSON are synced before carrying out
// logic for setting the form field states.
this.formlyFormBuilder.buildForm(
  this.formTemplate,
  parsedFields,
  this.model,
  this.options
);
```

So, this works if there are _more_ fields in the model compared to the template. The discrepancy gets resolved. However, if there are _fewer_ of the duplicate-able fields in the model vs. the template, I'm getting errors thrown when `buildForm()` is called:

_**Stacktrace: TypeError: Cannot read properties of undefined (reading '_fields')**_

Something I'd done before this was to manually parse the template and ensure the count for this field matches the count for the field in the model. However, this wouldn't be an option now that I'm using `buildForm()` because I rely on `buildForm()` to ensure that the template has the correct number of the duplicatable-fields in the scenario where the number of fields in the model is _greater_ than the template. So I rely on `buildForm()` to fix the issue when there are more fields in the model than the template, but it also blocks me from the only solution I can think of to solve the problem when there are fewer fields in the model vs. the template. 

So I'm looking for any potential solutions to this problem... allowing Formly to resolve the field-count between the model and the template regardless if the model shows a greater number of fields than the template vs. fewer.

Hopefully this all makes sense but let me know if it's not clear. Thanks!

**Comment by MaxKless** [comment]
This is quite a complicated problem and I'm not sure I understand everything that is going on.
Are you sure you can't provide a minimal repro where you play with the amount of fields a bit? It would make it a lot easier to help and maybe you will figure it out while you set it up.

**Comment by aitboudad** [comment]
> Stacktrace: TypeError: Cannot read properties of undefined (reading '_fields')

This could occurs if you push a new element to a field which is in build step. To avoid a such case you should make a copy first, adjust the field then re-assign the field and `buildForm`.


As mentioned above, its quite complicated to understand everything.
