### ISSUE TITLE
Kendo type input duplicate formControl directive

### ISSUE THREAD

**Issue by blemaire** [ngx-formly/ngx-formly#3435]
**Description**
In the kendo input type, the `input` component has the `formControl` directive twice:
![image](https://user-images.githubusercontent.com/7140322/190106536-682de195-da40-4173-9100-0b6564260b3d.png)

https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/kendo/input/src/input.type.ts#L20

This was introduced in #3220 but I could not see any reason why.
Thanks

**Comment by aitboudad** [comment]
Could you please send a PR ?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
