### ISSUE TITLE
[V6] "display: none" is not set when lazyRender is true

### ISSUE THREAD

**Issue by Trophalaxeur** [ngx-formly/ngx-formly#3436]
**Description**
This issue "display: none is not set when lazyRender is true"  was fixed recently in Formly V5.
https://github.com/ngx-formly/ngx-formly/issues/3313

It seems that the fix has not been reported to Formly V6.

**Minimal Reproduction**

In V6, the field has not display:none attribute and break the grid :
(you can switch lazyRender from true to false)
https://stackblitz.com/edit/angular-b43wet-rwq1u5

In V5, the bug is fixed :
https://stackblitz.com/edit/ngx-formly-custom-template-eu1d8k

**Your Environment**

- Angular version: 14.1.2
- Formly version: V6
- 
**Additional context**

**Comment by aitboudad** [comment]
Instead I think `v6` provide a better solution:

```ts
    FormlyModule.forRoot({
      extras: {
        renderFormlyFieldElement: false
      }
    }),
```
Could you please give it a try and let me know if that solve the issue?

**Comment by Trophalaxeur** [comment]
It seems to work perfectly !

Thank you for the tips et thank you for your amazing work ! It's really a great project !

**Comment by Christoph-Majcen** [comment]
Ok thank you. In the meantime I solved it using

```css
formly-field:empty {
  display: none;
}
```

which also works without the additional option.
