### ISSUE TITLE
combine smaller parts of form in formly

### ISSUE THREAD

**Issue by developer-taxblock** [ngx-formly/ngx-formly#3437]
I am creating form using formly and bootstrap related to different components of salary but fields are scattered on page means there are no continue fields, in-between fields there is some different component/template and then few fields and few fields are inside accordion so how can i can keep all fields in same form or is there any other way to achieve it ? please refer below image

![image](https://user-images.githubusercontent.com/111751306/190630332-52d2c667-afff-474a-9bc9-ce6e95ec8bc4.png)

**Comment by MaxKless** [comment]
Check out custom wrappers, they allow you to put any component around a field (like your accordion).
Also look at writing some custom types if you need it.

**Comment by MaxKless** [comment]
Closing this issue.
If there's anything else that I might have missed, please reopen.

**Comment by developer-taxblock** [comment]
Yes I achieved that using custom wrapper but I am not able to pass form data to custom wrapper . for example in above screenshot total salary that is 50000 is on accordion which is in custom wrapper and I nee to sum allowances to get total salary and send it to wrapper to render it on accordion panel and I always want this total salary updated if i change any allowance

**Comment by MaxKless** [comment]
You should have access to form data im your wrapper via `this.field`
