### ISSUE TITLE
Change detection on components won't work for not default initialized props

### ISSUE THREAD

**Issue by Greegko** [ngx-formly/ngx-formly#3444]
**Description**

Creating a bug ticket based on my https://github.com/ngx-formly/ngx-formly/issues/3331#issuecomment-1256092847

Having a component where properties set via observable, and if no default value for that property, it won't fire change detection.

**Minimal Reproduction**

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-pn3yfg

**Your Environment**

- Angular version: 14
- Formly version: 6

**Additional Info**

The observeDeep just hooks on the existing property and that's why it won't pick up any new properties, as the props won't be changes just altered when setting via expressProperties.

**Comment by aitboudad** [comment]
Its a limitation, there is no way to detect change if the property is not mentioned in the initial object for that reason we've mentioned in our upgrade to provide a default value https://github.com/ngx-formly/ngx-formly/blob/main/UPGRADE-6.0.md#solution-1-set-a-default-value

**Comment by aitboudad** [comment]
> The observeDeep just hooks on the existing property and that's why it won't pick up any new properties, as the props won't be changes just altered when setting via expressProperties.

I think we can support a such case, if the property is mentioned in `expressionProperties`.

**Comment by Greegko** [comment]
What about having a base props object which proxied ? Maybe not worth to have this, but this can cause issues as there is no warning or way to see it easier.

**Comment by aitboudad** [comment]
> What about having a base props object which proxied ? 

It could be the solution, we may give it a try and see how it goes.

**Comment by blemaire** [comment]
Hi All
Thanks for having logged this bug. We have a case where we might be having the same issue but the setup is a little complicated so could not create a simple reproduction case for now.
Are there any plans to fix thix in the near future though? it might be causing issues to more people too.
Thanks a lot for your hard work ;)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
