### ISSUE TITLE
Is that possible to run the hook onInit only when we unhide the field?

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#3448]
**Question**

I'm working with cascaded selects and I need to populate the options when previous field is filled. But I don't want to display the field before the previous field is filled.
Currently if the field is hide, the onInit hook is fire but the http request can't work because we need that the user answer to a previous field. It would be great to fire the hook only when the field is unhide. Is that possible?

**Comment by MaxKless** [comment]
Can you not check whether the field is hidden in the hook callback?
You can pass information about the current field in there.

**Comment by Jukien** [comment]
Hi @MaxKless sorry I'm not sure to understand. I give you an example: https://stackblitz.com/edit/angular-u7r9ae?file=src/app/app.component.ts

The onInit is fired from the beginning so the call to the dataservice can't work because I don't have the information at the beginning.

Maybe you can show me in the example ?

**Comment by aitboudad** [comment]
@Jukien can you try with `field.options.fieldChanges` which emit a new value when an expression is changed.

**Comment by Jukien** [comment]
Thank you @aitboudad this is very useful. This give an all new level of possibilities :heart_eyes: Is that new?

Do you know the list of types for which a new event is emit? With my tests I counted `hidden`, `expressionChanges` and `valueChanges`

**Comment by aitboudad** [comment]
> This give an all new level of possibilities heart_eyes Is that new?

no, `expressionChanges` was introduced since `v5.9`. I've sent a new doc PR (https://github.com/ngx-formly/ngx-formly/pull/3450) hope it'll be clear!

> Do you know the list of types for which a new event is emit?

`hidden`, `expressionChanges` and `valueChanges`.

**Comment by Jukien** [comment]
Thank you for your response and the update of the doc ;)
