### ISSUE TITLE
Best practice to reuse in formly field

### ISSUE THREAD

**Issue by tarektaamali** [ngx-formly/ngx-formly#3449]
Hi ,

I have a FormlyFieldConfig object contain many fields some field contain a service lik select . My question is what's best approach to reuse field in formly ? How to inject service in extension field? @aitboudad

**Comment by aitboudad** [comment]
see https://formly.dev/docs/guide/formly-field-presets

**Comment by tarektaamali** [comment]
> see https://formly.dev/docs/guide/formly-field-presets

I'm using version 5 @aitboudad
