### ISSUE TITLE
Non-input elements inside FormlyFieldConfig (text and image)

### ISSUE THREAD

**Issue by ajjp** [ngx-formly/ngx-formly#3451]
Is it possible to include non-input elements inside FormlyFieldConfig and update them based on some input field?

Example: user inputs a product code and, after fetching the database, some info should be displayed inside the form (ex. description and image).

Formly version: 5.12.6

Thanks.

**Comment by aitboudad** [comment]
> Is it possible to include non-input elements inside FormlyFieldConfig and update them based on some input field?

yes possible, and there are multiple ways:

1. template (https://github.com/ngx-formly/ngx-formly/issues/3287#issuecomment-1118815052, https://github.com/ngx-formly/ngx-formly/issues/2057#issuecomment-579724475)
2. inline type (v6 only) https://github.com/ngx-formly/ngx-formly/issues/2086#issuecomment-584847953
3. custom type

**Comment by ajjp** [comment]
Thank you for taking the time to answer, @aitboudad

I created a custom-type and expressionProperties to do it - any comment is welcome.

Custom type - includes a fall back to a "no image" image in case the image doesn't exist in the assets:

`import { Component } from '@angular/core';
import { FieldType } from '@ngx-formly/core';
import { EnvironmentService } from '@services/environment.service';

@Component({
    selector: 'app-formly-image',
    template: `
        <div class="float-right mt-2">
            <img
                class="image-128"
                [src]="field.templateOptions.src"
                (error)="noImage($event)"
            />
        </div>
    `
})
export class ImageTypeComponent extends FieldType {
    constructor(private environmentService: EnvironmentService) {
        super();
    }

    noImage(event: Event) {
        (event.target as HTMLImageElement).src =
            this.environmentService.noImgFile;
    }
}
`

Usage:

`this.fields = [
      {
          key: 'productImage',
          type: 'image',
          className: 'col-12 d-block',
          expressionProperties: {
              'templateOptions.src': (model) =>
                  model.product.length === 8
                      ? `${this.environmentService.productImgFolder}/${model.product}.jpg`
                      : this.environmentService.noImgFile
          }
      },
`
