### ISSUE TITLE
Bug during deploy on server

### ISSUE THREAD

**Issue by StefaniToto** [ngx-formly/ngx-formly#3452]
Im having a bug during deploy process.
Pipeline is giving the below error. 
Have tried to downgrade ts to version 4.7.4 and the same issue.

    "target": "es2020",
    "module": "es2020",
  "lib": ["es2018", "dom"]

![image](https://user-images.githubusercontent.com/32243109/193606597-88755abd-1bac-48f0-a5dc-aa78d14d1647.png)

**Comment by aitboudad** [comment]
> Command failed with exit code 137

The error here seems related build script which run out of memory and not related to Formly.
