### ISSUE TITLE
Formly angular with Bootstrap is finicky.

### ISSUE THREAD

**Issue by parthupadhye** [ngx-formly/ngx-formly#3453]
I have used it before and I absoloutely liked it but I have found installation and use very unpredictable.

However, I find it very unpredictable. Earlier it worked then not.

Today, I initally used the example:
https://formly.dev/docs/guide/getting-started [it worked]
Then went to reproduce the schemas - example. Lots of errors. Rebuilt and served. Errors.
Now even when I go to produce the first example I get a blank screen.

Package.json
"dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/localize": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "@ng-bootstrap/ng-bootstrap": "^12.1.2",
    "@popperjs/core": "^2.10.2",
    "bootstrap": "^5.1.3",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4",
    "@ngx-formly/core": "^6.0.0",
    "@ngx-formly/bootstrap": "^6.0.0"
  },

**Comment by aitboudad** [comment]
Hi, we need more details in order to help. Since it's a starting example, could you please push it in a separate repository so we may check it or show us the error that you're getting to see if we can help.

Thank you!

**Comment by parthupadhye** [comment]
I got my first one to work (it was saved in Github). 
WIll post the schema example (if it doesn't work) or inform otherwise.
Thanks.

**Comment by parthupadhye** [comment]
Here's my repo:
https://github.com/parthupadhye/yedangular
only for the References example of Json Schema.

**Comment by aitboudad** [comment]
Alright, feel free to leave a comment here in case you've any question/remark.
Thank you!
