### ISSUE TITLE
ngx formly - Form fields validations kick in at time of page load

### ISSUE THREAD

**Issue by RiturajKandiyal** [ngx-formly/ngx-formly#3454]
I am using ngx-formly v: 5.9.3 and angular v: 11.2.14. When I run my application, validations for my required form fields kick in at time of page load itself. This was not happening in my previous angular v: 10.2.5. I came across this https://github.com/ngx-formly/ngx-formly/issues/1201#issuecomment-424661978 and did similar in my code, but still to no use. Using the above link example I am adding required properties via my code: -

```
for(var i = 0; i < this.vm.options.formState.modelInfo.fields[0].steps.length; i++) {
      var individualStep = this.vm.options.formState.modelInfo.fields[0].steps[i];
      for(var j = 0; j < individualStep.fields.length; j++) {
        if(individualStep.fields[j].id.indexOf('panel') > -1) {
          for(var k = 0; k < individualStep.fields[j].fieldGroup.length; k++) {
            for(var l = 0; l < individualStep.fields[j].fieldGroup[k].fieldGroup.length; l++) {
              if(individualStep.fields[j].fieldGroup[k].fieldGroup[l].key === 'firstName') {
                individualStep.fields[j].fieldGroup[k].fieldGroup[l]['validation'] = {
                  show: true
                }
                
                  individualStep.fields[j].fieldGroup[k].fieldGroup[l]['expressionProperties'] = {
                    'validation.show': 'false'
                  }
              }
            }
          }
        }
      }
    }
```

and it looks as follow after that: -

![image](https://user-images.githubusercontent.com/108937137/194836104-e9996d6a-ed4b-4744-a3c0-707847cf70e3.png)

But even after adding this, upon running the application my form field looks like: -

![image](https://user-images.githubusercontent.com/108937137/194836187-e62ff6b7-c2c5-4eff-b1b9-0c6b0d3d2da2.png)

**Comment by MaxKless** [comment]
Reassigning such deep nested properties seems like it could definitely cause some errors. In my experience, writing immutable code makes it easier to use and debug formly.

Could you provide a minimal reproduction so we can pinpoint your issue more easily?

**Comment by kenisteward** [comment]
I'm with @MaxKless here as well. Immutable changes I've also found are the easiest to debug and fix and have had no issues with formly or angular in general when sticking to that rule.

**Comment by kenisteward** [comment]
I'd also like to add that true and 'false' evaluate to the same thing when checking for truthiness in JavaScript expressions so as a pre cursor try setting it to false instead.

Like above the stackblitz would be very helpful too!
