### ISSUE TITLE
Is it possible to place mat-label outside of mat-formfield?

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#3458]
**Question**

When using "appearance: outline", I would like to know if it is possible to place "label: xxxxx" to appear above the outline?

Here is how I am currently using it.

```
        {
          key: 'description',
          type: 'input',
          className: "col-12",
          templateOptions: {
            label: 'Description',
            placeholder: "Rule Description",
            tooltip: 'Short description of the rule use case',
            appearance: 'outline',
            required: true,
          },
        },
```

My understanding is that if I do the following using plain angular form, I am able to place / view the label above the outline.

```
   <mat-label>Description</mat-label>
  <mat-form-field appearance="outline">
    <input matInput>
  </mat-form-field>
```

**Comment by MaxKless** [comment]
If the default behavior isnt what you'd like, check out custom wrappers!

**Comment by argupta23** [comment]
@MaxKless 
I was able to address it via CSS.
