### ISSUE TITLE
Using Formly with already existing form (both version 5.* and 6.*)

### ISSUE THREAD

**Issue by neosis** [ngx-formly/ngx-formly#3459]
Hello,

I have a pre-existing project with pre-existing forms and control. For maintenance reasons, I can move existing form to formly.
Can formly be used within pre-existing  for adding new form controls (what to pass as model and fields)? 
If yes, can someone point me to a working example please?

Best
Ashutosh

**Comment by aitboudad** [comment]
Hi, I think it's possible but can't guarantee the result. You may give it a try and let us know if you've encountered any issue.

1. use `FormlyFormBuilder` service to build the form
2. use `formly-field` to render formly elements

Here is an example: https://stackblitz.com/edit/angular-p1msf8

**Comment by neosis** [comment]
Hi, I was not able to use code you shared as I was using 5.x and FormlyBuilder.build({FormlyFieldConfig}) api is not available. But never the less it seems to be working. We are using JSON based configs to had to take care having a copy of all configs and ensure that model is appropriately hydrate as while loading the components. Thanks for your help.
