### ISSUE TITLE
Formly 6 migration -> Form values not patched from observable

### ISSUE THREAD

**Issue by rickvandermey** [ngx-formly/ngx-formly#3461]
After migrating from 5 to 6 i cannot seem to use my 
model data anymore to patch the form data.
I've read the migration and tried different things, but I'm stuck. 
Would love some help

<img width="412" alt="Screenshot 2022-10-17 at 17 21 23" src="https://user-images.githubusercontent.com/10522532/196217335-fbece8d4-e3d5-4543-bb46-e77a43d5143f.png">

example of one form field (added a defaultValue to the field)
```
export const form: FormlyFieldConfig[] = [
	{
		id: 'firstName',
		key: 'firstName',
		hideExpression: "model.salutation == 'family'",
		templateOptions: {
			label: 'global.firstname.label',
			labelExtras: {
				contentWidth: '',
				alignment: 'left-aligned',
				width: '',
			},
			required: true,
			translate: true,
			validation: {
				messages: {
					required: 'global.firstname.required-text',
				},
			},
		},
		type: 'text',
		defaultValue: null,
	},
```

```
<formly-form
  [form]="formGroup"
  [fields]="formFields"
  [model]="model$ | async"
></formly-form>
```

example of the InputComponent (they are all similiar)
```
@Component({
	selector: 'formly-field-input',
	template: `
		<vp-input
			ngDefaultControl
			[formControl]="formControl"
			[icon]="to['icon']"
			[iconPosition]="to['iconPosition']"
			[type]="field.type"
			[inputId]="field.id"
			[name]="field.key"
			[placeholder]="to.placeholder"
			[readonly]="to.readonly"
			[isOptional]="to['optional']"
			[isValid]="formControl.valid"
			[hasError]="showError"
			[maskOptions]="to['maskOptions']"
		></vp-input>
	`,
})
export class InputComponent extends FieldType {}
```

**Comment by aitboudad** [comment]
Hi, do you means model updates (`model$`) aren't applied to the form fields ?

**Comment by rickvandermey** [comment]
Yes, the form stays empty, while the model$ is filled with the correct data

**Comment by aitboudad** [comment]
Seems working on my side https://stackblitz.com/edit/angular-azuvp7, could you please try to edit the stackblitz example in order to reproduce the issue.

Thank you!

**Comment by rickvandermey** [comment]
I think I've fixed it, it seems my formly components weren't passing the initialvalue so the components couldn't be patched correctly.
