### ISSUE TITLE
Is that normal we can't access to the model when using repeating section?

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#3462]
**Question**
Is that normal we can't access to the model when using repeating section?
Maybe I'm using wrong the repeating section but in v5 it worked well.

https://stackblitz.com/edit/angular-vdxzfi?file=src/app/app.component.ts
(check the console. model is null)

**Comment by Jukien** [comment]
Hi @kenisteward thank you for your response.

For the first point I used the tutorial and I haven't see that the model was initialized, sorry.

For the second point, effectively when I add defaultValue to the field the hide function works now for the second field.
But I tried to use the other method to avoid adding defaultValue to every field. And it's doesn't seem to work. The model is still undefined.

```
FormlyModule.forRoot({
  types: [
    {
      extends: 'formly-group',
      defaultOptions: {
        defaultValue: {}
      }
    }
  ],
})
```

Stackblitz updated: https://stackblitz.com/edit/angular-vdxzfi?file=src/app/app.component.ts

**Comment by FritzHerbers** [comment]
It can be done as follow:
```
        {
          name: 'repeat',
          component: RepeatTypeComponent,
          defaultOptions: {
             fieldArray: {
               defaultValue: {}
             },
          }
        },
```

Have a look for the three different ways to set the defaultValue for array-types at https://github.com/ngx-formly/ngx-formly/issues/3345#issuecomment-1165644688

**Comment by Jukien** [comment]
Thank you @kenisteward and @FritzHerbers for your support and examples. It works now :)

**Comment by Jukien** [comment]
Hi @kenisteward and @FritzHerbers, sorry to bother you again with my issue.
I have another form where I use my repeat component but now I want to hide all the field group depending on another field for example.
When I add the hide expression, the default value is not take in count and the model stay null.

Stackblitz updated: https://stackblitz.com/edit/angular-vdxzfi?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
Can you check the following solution instead of default value:

```patch
hide: (field) => {
- return !field.model.task1;
+ return !field.model?.task1;
}
````

**Comment by Jukien** [comment]
Thank you very much @aitboudad it works perfectly :smiley:
