### ISSUE TITLE
model properties not mapped in formly gets deleted

### ISSUE THREAD

**Issue by codercyril** [ngx-formly/ngx-formly#3463]
is there any settings that I can enable so fields that are not in formly will still be in the model after an input change? 

for example i got a model 
{ columna : "a", columnb : "b"}

in formly i only set columna. when i change the value of columna formly then removes the columnb property in the model.

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
