### ISSUE TITLE
Help needed for Dependency Conflict 

### ISSUE THREAD

**Issue by aseem-chhabra** [ngx-formly/ngx-formly#3464]
I tried to install formly using npm install on my application and I am getting this error :

npm install @angular/forms @ngx-formly/core @ngx-formly/bootstrap --save        
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: baseui@0.0.0
npm ERR! Found: @angular/forms@13.1.3
npm ERR! node_modules/@angular/forms
npm ERR!   @angular/forms@"~13.1.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/forms@">=13.2.0" from @ngx-formly/core@6.0.1
npm ERR! node_modules/@ngx-formly/core
npm ERR!   @ngx-formly/core@"^6.0.1" from the root project
npm ERR!   peer @ngx-formly/core@"6.0.1" from @ngx-formly/bootstrap@6.0.1
npm ERR!   node_modules/@ngx-formly/bootstrap
npm ERR!     @ngx-formly/bootstrap@"^6.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\aseemchh\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aseemchh\AppData\Local\npm-cache\_logs\2022-10-25T23_05_01_266Z-debug.log

Can someone help me understand what this issue means and how to resolve it?

**Comment by aitboudad** [comment]
use `npm install` with `--force`, or `--legacy-peer-deps` to fix the issue

**Comment by aseem-chhabra** [comment]
I did and still don't see the changes in the `AppModule`.

I do see `Formly` being added in the `package.json` and `package-lock.json file`

if I add this to the `app.module.ts` file manually, will I be good to go?
![image](https://user-images.githubusercontent.com/32377440/199854832-7acd1f64-04e2-47b1-9f57-e6774b50f150.png)


debug logs:

![image](https://user-images.githubusercontent.com/32377440/199855085-4dd8b9fe-62ae-4a54-b251-dd239dda18df.png)
![image](https://user-images.githubusercontent.com/32377440/199855145-c8cd53c6-5e3d-4a67-b684-4958706d8916.png)

**Comment by aitboudad** [comment]
> if I add this to the app.module.ts file manually, will I be good to go?

yes
