### ISSUE TITLE
Nesting form?

### ISSUE THREAD

**Issue by DanielBerith** [ngx-formly/ngx-formly#3465]
Good day,

 i have been trying to change the styling of some fields in the form 
 i'm not sure on the approach i should use, the fields (data) are coming from the database 

i want the selected inputs on the screenshot to be next to each other

can you advice on a way forward?

thanks

**Comment by aitboudad** [comment]
use `className`, see https://github.com/ngx-formly/ngx-formly/issues/3247#issuecomment-1083169699
