### ISSUE TITLE
custom type as class

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#3467]
we can define custom types and use its name as string
```
{
 type: 'my-custom-type',
 ...otherProps
}
```
this requires us to declare the custom type in the module.

I suggest allowing the custom type class directly in the field
```
{
  type: MyCustomTypeComponent,
 ...otherProps
}

**Comment by eng-dibo** [comment]
the same is going for validations

instead of passing options from the module only, allow it from the field, like this:
```
{
  type: 'input',
   validators: {
        validation: [{validator: myValidator, options: {}}],
              }
```

**Comment by aitboudad** [comment]
passing class to type is available since `v6`, for validators I think its already possible.

**Comment by eng-dibo** [comment]
Ok, I'm going to give a try for both, and then give you a feedback

**Comment by eng-dibo** [comment]
can we change `templateOptions.min` type from `Number` to `Date | Number` or any other type? without using another prop name such as `to.minValue`

**Comment by aitboudad** [comment]
> can we change `templateOptions.min` type from `Number` to `Date | Number` or any other type? without using another prop name such as `to.minValue`

To define or adjust typing check the following example https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/bootstrap/radio/src/radio.type.ts#L5

**Comment by eng-dibo** [comment]
> passing class to type is available since `v6`

this part is confirmed as it exists in v6



> for validators I think its already possible.

I cannot find an example for it in the formly examples page or anywhere in the docs

**Comment by eng-dibo** [comment]
> > can we change `templateOptions.min` type from `Number` to `Date | Number` or any other type? without using another prop name such as `to.minValue`
> 
> To define or adjust typing check the following example https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/bootstrap/radio/src/radio.type.ts#L5

if I understand correct:

in CustomType.component.ts
```
@component({})
export class MyCustomType extends FieldType<FieldTypeConfig>{}
```

in form.component.ts
```
export interface MyCustomFields extends FormlyFieldConfig {
  min: Date | number;
}

this.fields = [{
   type: MyCustomType,
   templateOptions:{
     min: new Date()
}]
```

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/pull/3242

**Comment by aitboudad** [comment]
for usage see this comment: https://github.com/ngx-formly/ngx-formly/pull/3242#discussion_r835774902
