### ISSUE TITLE
PrimeNG Datepicker not working in the stackblitz demo: Unexpected synthetic listener @overlayAnimation.start found

### ISSUE THREAD

**Issue by persdv** [ngx-formly/ngx-formly#3469]
Hi

We are starting working with ngx-formly, but we are facing issues with the datepicker of PrimeNG.

When trying to reproduce our problem in the published samples, we have noticed that a (different) error occurs on the sample page too: https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts (Which is linked from: https://formly.dev/docs/ui/primeng/)

Reproduction steps:

1. Go to https://formly.dev/docs/ui/primeng/
2. In the datapicker section, click in "Edit in StackBlitz" button. It will load https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts
3. Click in the datepicker
4. The expected action does not occur
5. This error appears in console:

```
ERROR
Error: Unexpected synthetic listener @overlayAnimation.start found. Please make sure that:
- Either `BrowserAnimationsModule` or `NoopAnimationsModule` are imported in your application.
- There is corresponding configuration for the animation named `@overlayAnimation.start` defined in the `animations` field of the `@Component` decorator (see https://angular.io/api/core/Component#animations).
- 
```
![image](https://user-images.githubusercontent.com/116909114/198696769-a2890857-46a5-4e20-a156-74d65c81a5b4.png)

**Environment**
@angular 14.2.8
@ngx-formly/core 6.0.1
@ngx-formly/primeng 6.0.1
core-js 3.26.0
primeflex 3.1.0
primeicons 5.0.0
primeng 13.4.1
rxjs 7.5.7
tslib 2.4.0
zone.js 0.11.8

Thanks in advance and congratulations for the amazing documentation available for this project!

**Comment by aitboudad** [comment]
The example is now fixed, thank you for letting us know!

**Comment by persdv** [comment]
Great. Thank you very much!
