### ISSUE TITLE
Formly v6 and ng-select haven't the same behavior than with Formly v5

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#3472]
Since I update my forms to formly v6 and reteste it, I notice that on select field type (powered by ng-select library) when I want to clear an item, I need to click twice.
I don't kwow if the problem comes from ng-select or formly.
But in formly v5 I don't have this issue.

I did some tests to find what cause the issue and I noticed that when options of the select are fed by an HTTP request we have the issue. When options are directly initialize, it works.

I created two projects on my github to show you (sorry I couldn't get them to work on Stackblitz):
- In Formly v5 (5.12.7) where it works : https://github.com/Jukien/angular-bug-select-formly-v5
- In Formly v6 (6.0.1) where it doesn't work : https://github.com/Jukien/angular-bug-select-formly-v6

**Comment by aitboudad** [comment]
Did you checked our upgrade for `v6`: https://formly.dev/docs/guide/migration ?

**Comment by aitboudad** [comment]
I think its due to on push change detection:

- Solution 1: use `formlySelectOptions` pipe

```patch
 <ng-select
-  [items]="props.options"
+  [items]="props.options | formlySelectOptions: field | async"
   [bindLabel]="props.labelProp"
   [multiple]="true"
   [formControl]="formControl" [formlyAttributes]="field">
````

```patch
+ import { FormlySelectModule } from '@ngx-formly/core/select';

@NgModule({
  imports: [
    BrowserModule,
    NgSelectModule,
    FormsModule,
    ReactiveFormsModule,
+   FormlySelectModule,
  ],
})
export class AppModule {}
```


- Solution 2: set a default value for `options` https://formly.dev/docs/guide/migration/#solution-1-set-a-default-value

**Comment by Jukien** [comment]
Thank you @aitboudad, defaultOptions again! It's start to drive me crazy :sweat_smile:

**Comment by Jukien** [comment]
> * Solution 1: use `formlySelectOptions` pipe
> 
> ```diff
>  <ng-select
> -  [items]="props.options"
> +  [items]="props.options | formlySelectOptions: field | async"
>    [bindLabel]="props.labelProp"
>    [multiple]="true"
>    [formControl]="formControl" [formlyAttributes]="field">
> ```
> 
> ```diff
> + import { FormlySelectModule } from '@ngx-formly/core/select';
> 
> @NgModule({
>   imports: [
>     BrowserModule,
>     NgSelectModule,
>     FormsModule,
>     ReactiveFormsModule,
> +   FormlySelectModule,
>   ],
> })
> export class AppModule {}
> ```

I tried the solution 1 but it doesn't work for me I mean now we can click once to clear the item, but we loose display of the options

![image](https://user-images.githubusercontent.com/32452023/198888842-7aea33ee-d0f2-42c6-b598-22ae0625e8d4.png)

I'll go for solution 2 easier :D Thank you very much ;)

By the way if you can check this out: https://github.com/ngx-formly/ngx-formly/issues/3462#issuecomment-1295377814

**Comment by aitboudad** [comment]
> By the way if you can check this out: https://github.com/ngx-formly/ngx-formly/issues/3462#issuecomment-1295377814

see https://github.com/ngx-formly/ngx-formly/issues/3462#issuecomment-1296294796
