### ISSUE TITLE
Using ngx-formly with nested model-data

### ISSUE THREAD

**Issue by FloNeu** [ngx-formly/ngx-formly#3473]
**I have the problem that my flat-api was changed to a nested one. Like from: **
`{
  id: '01',
  districtId: 'district-id-01',
  districtName: 'district-name',
  countryId: 'country-id-01'
  countryName: 'countryname'
}`  to the root containing a field district with id, name, and country-object which
itself contains name and id again.

how can I adapt my form-field configuration to reflect this without additional fieldGroup-wrappers - I saw @aitboudad   
suggesting somewhere as this breaks a wrapper component I use around the structure.

I found some StackOverflow answers referring to 'angular-formly' (outdated angular 1.x project?) which had a syntax
like { key: 'destrict.id' ... { key: district.country.id.

But i found ngx-formly doesn't support that? Any plans for adding this? or is there another workaround to achieve this?

As i found in the tickets: #121 Nested Property Keys should do what i want... But instead the nested model object i am passing has his nested properties deleted

**Comment by FloNeu** [comment]
Example of this problem... 
The FieldConfig:
https://github.com/FloNeu/agrardata/blob/main/Formly_Bug_Fieldconfig.png
and the resulting form with output of the model outside formly and the passed clone
https://github.com/FloNeu/agrardata/blob/main/Formly_Bug_Form.png

Maybe this is a regression - as the feature seems to be implemented for so long?

**Comment by aitboudad** [comment]
You can use nested key using dot notation: `key: 'district.country.id'` which is supported.

**Comment by FloNeu** [comment]
@aitboudad Thanks for looking at this - just wanted to write that i found the problem within my code... (I was somehow overwriting the value later) and my select now receives the id value... still, now my select displays the correct id and the according option...
