### ISSUE TITLE
Hook when form gets submitted

### ISSUE THREAD

**Issue by rickvandermey** [ngx-formly/ngx-formly#3474]
**Question**

Is it possible to have a hook on a field to detect if the form gets submitted?
I need this if i want to use a reusable invisible recaptcha component.

Or is there any docs/example how to use recaptcha V2 (invisible) or V3 in formly (reusable)

**Comment by aitboudad** [comment]
instead use a custom validator with `updateOn='submit'`, check the following examples:

- usage of `updateOn`: https://formly.dev/docs/examples/validation/async-validation-update-on
- define validator at the root level: https://formly.dev/docs/examples/validation/matching-two-fields
