### ISSUE TITLE
How to create custom template from the parent component?

### ISSUE THREAD

**Issue by jon9090** [ngx-formly/ngx-formly#3475]
**Question**

I build `ui-form` component on top of formly component.

And I want to use a custom template from the component HTML

```
  { className: 'legend', type: 'customId' },
 ....
  <ui-form [fields]="fields" [form]="form" [model]="model">
   <ng-template formlyTemplate="customId" let-field>customId!!</ng-template>
 </ui-form>
```

The problem is it not works. but it works only inside `formly` of `ui-form` component:
```
selector: 'ui-form',
  template: `
  <form
    #formRef="ngForm"
    [formGroup]="form"
    (ngSubmit)="onSubmit($event)"
    novalidate
  >
    <formly-form [fields]="fields" [form]="form" [model]="model" [options]="options" (modelChange)="modelChange.emit($event)">
      <ng-template formlyTemplate="customId" let-field>customId!!</ng-template> <------- here
    </formly-form>
  </form>
  `,
```

It is possible to make it works from the ui-form component? Formly can get the parent templates?

The full code:
```
  selector: 'ui-form',
  template: `
  <form
    #formRef="ngForm"
    [formGroup]="form"
    (ngSubmit)="onSubmit($event)"
    novalidate
  >
    <formly-form [fields]="fields" [form]="form" [model]="model" [options]="options" (modelChange)="modelChange.emit($event)">
      <ng-content></ng-content>
      <!-- <ng-template formlyTemplate="customId" let-field>customId!!</ng-template> -->
    </formly-form>
  </form>

....

 selector: 'formly-app-example',
  template: `
  <ui-form [fields]="fields" [form]="form" [model]="model">
   <ng-template formlyTemplate="customId" let-field>customId!!</ng-template>
 </ui-form>
  `,

  `,
```
[stackblitz](https://stackblitz.com/edit/angular-hahctt?file=src%2Fapp%2Fui-form.ts,src%2Fapp%2Fapp.component.ts,src%2Fmain.ts)

**Comment by aitboudad** [comment]
related to https://github.com/angular/angular/issues/16299

**Comment by jon9090** [comment]
@aitboudad is it possible to "register" type from the component in ngOnInit?
maybe something like this or a similar solution?
```
@Input() templates;

formly.register(templates);
```

**Comment by aitboudad** [comment]
If you're looking for a workaround, use `ViewChild` to get `FormlyForm` component instance and set `templates` value manually (https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/components/formly.form.ts#L74-L76).
