### ISSUE TITLE
[regression] options' text does't rendered in formly v6

### ISSUE THREAD

**Issue by eng-dibo** [ngx-formly/ngx-formly#3476]
options' text does't rendered in formly v6
it is a regression

I prepared a [minimal reproduction](https://stackblitz.com/edit/angular-ivy-awetdv?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts,angular.json)

inspecting the source code you will see that `<span class="mat-option-text">` is empty

![image](https://user-images.githubusercontent.com/57308531/199269127-eb45a971-d59e-4eca-9f75-77d1a1887c68.png)

![image](https://user-images.githubusercontent.com/57308531/199269066-62a137ee-cb19-470b-936d-7bb5c2bcbb47.png)

**Comment by eng-dibo** [comment]
@aitboudad

**Comment by aitboudad** [comment]
Seems you're using a deprecated format which has been removed in v6, try the following solution:

```patch
{
  key: 'country',
  type: 'select',
  props: {
    label: 'country',
+   labelProp: 'value',
+   valueProp: 'key',
    options: [
      { key: 'usa', value: 'USA' },
      { key: 'en', value: 'England' },
    ],
    required: true,
  },
},
```

**Comment by aitboudad** [comment]
https://formly.dev/docs/guide/migration#11-select-option-unsuported-format
