### ISSUE TITLE
File Input with FormlyMaterialModel throws error

### ISSUE THREAD

**Issue by SOG-web** [ngx-formly/ngx-formly#3477]
please how do I implement file input with `FormlyMaterialModel`. I followed the example here `https://formly.dev/docs/examples/other/input-file` but it throws this error

```
ERROR TypeError: Cannot read properties of undefined (reading 'controlType')
    at mt.ngAfterContentInit (main.js:1:1336474)
main.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'onContainerClick')
    at main.js:1:1345233

ERROR TypeError: Cannot read properties of undefined (reading 'errorState')
    at hostBindings (main.js:1:1342707)
```

the ui renders without any issue but when i click on the input i get errors

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-material

Thanks!

**Comment by SOG-web** [comment]
Thanks so much I have fixed it, 

Your example later worked, 

Where I got it wrong was not importing the file-accessor directive in the right module
