### ISSUE TITLE
Conditional content inside of a FieldType

### ISSUE THREAD

**Issue by janfaracik** [ngx-formly/ngx-formly#3479]
**Question**

Hey all, great job on the library - it's been great to use. We're developing a form and are trying to implement a list of radiobuttons with conditional content (https://design-system.service.gov.uk/components/radios/#conditionally-revealing-a-related-question)
e.g. the input only shows when the relevant radio is checked.

![](https://files.gitter.im/57048cdf187bb6f0eade11d1/zaB8/image.png)

Doing conditional content is straightforward (e.g. using the hide expression) but how would one use that functionality inside of a custom type and have it do it automatically (e.g. without a developer writing the hide expression each time)? I've got a working mess of code built on layers of form groups that isn't ideal (and doesn't work too well with validation), but I was wondering if anybody knew of an easier way.

Happy to share my current code if needed

**Comment by aitboudad** [comment]
https://formly.dev/docs/guide/formly-field-presets
