### ISSUE TITLE
Angular formly challenge 

### ISSUE THREAD

**Issue by sonalnaiknavare** [ngx-formly/ngx-formly#3483]
Hi,i need some support with ngx formly.i have json response from backend.i am using custom component whose type is coming from backend itself.i have created a custom component for eg. Number control.now i want to set some expression properties to it but the function is not getting called if i try to set the expression properties in my custom component for number control. kindly provide help if there is any solution to this issue.

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
