### ISSUE TITLE
Access nested model value in custom type

### ISSUE THREAD

**Issue by FloNeu** [ngx-formly/ngx-formly#3487]
**Question**
I have a field configuration accessing value of a nested field like:`key: 'nested.field.value'` and have written a custom typeahead component. To be able to select the right initial value i have to access
the models nested value at above path. Does formly expose the internal method to get this value?

**Comment by aitboudad** [comment]
1. use `field.formControl.value`
2. use `getFieldValue`:

related to https://github.com/ngx-formly/ngx-formly/issues/3331:
```ts
import { ɵgetFieldValue as getFieldValue } from '@ngx-formly/core';
// getFieldValue(field);
```

**Comment by FloNeu** [comment]
You are a god among the opensource maintainers
