### ISSUE TITLE
Error message is not display when trigger error using setErrors

### ISSUE THREAD

**Issue by wizardnet972** [ngx-formly/ngx-formly#3490]
**Question**

When you focus on the field, you will get an error. (red color):

https://stackblitz.com/edit/angular-pwjyay?file=src%2Fapp%2Fautocomplete-type.component.ts,src%2Fapp%2Fapp.module.ts

The problem is the error message is not displayed, although it is defined in `validationMessages`:
```
 validationMessages: [
        { name: 'required', message: 'This field is required' },
        { name: 'requiredFoo', message: 'This field is required Foo' }, <----- here
  ],
```
I trigger this error manually in `ngOnInit` using `setTimeout`:
```
setTimeout(() => {
      this.formControl.setErrors([{ requiredFoo: true }]);
});
```
Why? and how can I display this message?

**Comment by wizardnet972** [comment]
@aitboudad I think the bug [at this line](https://github.com/ngx-formly/ngx-formly/blob/4df05ce846/src/core/src/lib/templates/formly.validation-message.ts#L38)

instead of `  for (const error in fieldForm.errors) {` 
should be `  for (const error of fieldForm.errors) {`
because:
```
for (const e of [{ req: true }]) { console.log({ e }); } // e === {req: true } 
vs
for (const e in [{ req: true }]) { console.log({ e }); } // e === '0'
```
`error` is `0` so `message` is `undefined`: `let message = this.config.getValidatorMessage(error);`

So I think it's a bug, not a question. what do you think?

**Comment by aitboudad** [comment]
You should pass an object to `setErrors`:

```ts
this.formControl.setErrors({ requiredFoo: true });
```

**Comment by wizardnet972** [comment]
Thanks :)
