### ISSUE TITLE
hideExperssion with formState not updating

### ISSUE THREAD

**Issue by fb-developer-formly** [ngx-formly/ngx-formly#3491]
**Description**
hideExpression work successfully with formState, but when formState changes, the hideExpression not activated. 
_note_
_when the model changes  the hideExpression activated  and also updates the hideExpression whit formState._

**Minimal Reproduction**

`````````````````````  1
 form = new FormGroup({});
  model: any = {};
  options: FormlyFormOptions = {
    formState: {
      myObj: this.myObj,
    },
  };
myObj={};
``````````````````````` 2
hideExpression: "formState.myObj.show == false'"

````````````````````` 3
this.myObj.show = true


https://stackblitz.com/edit/ngx-formly-ui-primeng-7n9huq?file=src/app/app.component.ts

**Environment**

- Angular version: 13.3.0
- Formly version: 6.0.1
-

**Comment by fb-developer-formly** [comment]
this bug also happened when use 'field' parameter

**Comment by aitboudad** [comment]
To fix the issue ensure to define a default value for `show` property:
```patch
- myObj={};
+ myObj={ show: false };
```

**Comment by fb-developer-formly** [comment]
hi,

thanks for quick answer!


as you can see in the example code
https://stackblitz.com/edit/ngx-formly-ui-primeng-7n9huq?file=src/app/app.component.ts

The 'show' parameter is initialized and first time it's works good,
but when the value changes, the 'evalStringExeption' function not activated

the function activate only when model changes,
 and then, the 'hide Expression' updating also of formState

thanks

  model = {};
  show: boolean = false;
  options: FormlyFormOptions = {
    formState: {
      show: this.show,
    },
  };




‫בתאריך יום א׳, 13 בנוב׳ 2022 ב-14:06 מאת ‪Abdellatif Ait boudad‬‏ <‪
***@***.***‬‏>:‬

**Comment by aitboudad** [comment]
Updating `show` property will not be detected in `options.formState` instead try to update `formState`:

```ts
this.options.formState.show = !this.options.formState.show;
```

For a working example check https://formly.dev/docs/examples/form-options/form-state

**Comment by fb-developer-formly** [comment]
thanks!
can you please see the example code :
https://stackblitz.com/edit/angular-sfza2j?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,package.json,src%2Fapp%2Fshared-model.ts,src%2Fapp%2Fapp.module.ts
firmState referance class
it's can working?

[image: image.png]

‫בתאריך יום א׳, 13 בנוב׳ 2022 ב-20:40 מאת ‪Abdellatif Ait boudad‬‏ <‪
***@***.***‬‏>:‬

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-sfza2j-q2pbrx?file=src/app/app.component.ts

**Comment by fb-developer-formly** [comment]
?
what is the answer?

**Comment by aitboudad** [comment]
sorry I misread you comment, for that case I think the proper solution is to pass an `observable` value to the hide expression https://stackblitz.com/edit/angular-sfza2j-q2pbrx?file=src/app/app.component.ts

**Comment by fb-developer-formly** [comment]
thanks
I'll check it out

**Comment by fb-developer-formly** [comment]
good evening!

i see now, the hide expression use 'this'
and not formState, 
in my project i can't use 'this' becouse , my project have multy components that call the formly mapper.

There is a solution with formState?

thanks

**Comment by fb-developer-formly** [comment]
Hi.
please, can you help me?

thanks

**Comment by aitboudad** [comment]
> There is a solution with formState?

Expressions doesn't support observable through `formState`, you may consider using a custom extension (https://formly.dev/docs/guide/custom-formly-extension) where you can inject `sharedModel` service and pass it to the expression.

**Comment by fb-developer-formly** [comment]
hi.

the formState not have solution
 the formState is not refreshed auto
therefore we reloading the generate field again

thanks!
