### ISSUE TITLE
Formly 5 Custom validator in custom field

### ISSUE THREAD

**Issue by baudev** [ngx-formly/ngx-formly#3493]
Hi!

**Description**
Using custom validator in custom field using Material input gives the following error: 
```
ExpressionChangedAfterItHasBeenCheckedError ...
Previous value: 'ng-valid: true'. Current value: 'ng-valid: false'
```

This is not occurring when using the custom field without formly.  
Do you have any ideas from where it comes?

**Minimal Reproduction**
https://stackblitz.com/edit/formly-custom-field-validation-issue?file=src/app/material-custom-input/material-custom-input.component.ts

**Your Environment**

- Angular version: 12.2.14
- Formly version: 5.12.7

**Additional context**
Thanks for your awesome work!

**Comment by aitboudad** [comment]
Not sure what the right solution because Formly already initialized at that stage so if you're looking for a workaround you may use:

```patch
  ngOnChanges(changes: SimpleChanges) {
    if (changes.authorizedProviders) {
+      Promise.resolve(() => {
+       ...
+   	});
    }
  }
```

Or rely on Formly validation instead: http://localhost:4100/examples/validation/custom-validation
