### ISSUE TITLE
formControl.setValue doesn't remove/add conditional fields in the form

### ISSUE THREAD

**Issue by karthikeyan-arumugam-1558** [ngx-formly/ngx-formly#3495]
**Description**
I want to add/remove some controls based on the value of other controls in the form. In some cases the value has to be set programatically using `setValue` and it doesn't work.

**Minimal Reproduction**
[StackBlitz](https://stackblitz.com/edit/angular-gghwga-sys1my?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fpanel-wrapper.component.ts,src%2Fapp%2Fapp.module.ts,package.json,src%2Fapp%2Fapp.component.html)

**Your Environment**

- Angular version: 13.3.11
- Formly version: 6.0.1

**Additional context**
1. I'm calling `setValue` from a **wrapper**
2. In the above reproduction, it works when I wrap it in a `setTimeout`, but it's not reliable and doesn't help in my actual project ☹️

**Comment by aitboudad** [comment]
just to understand the request, do you means the model value should be updated instantly when calling `setValue`?
or are you looking for an alternative way to get notified when the model is updated?

**Comment by karthikeyan-arumugam-1558** [comment]
Doesn't have to be instant. Just want a way to ensure the model & other controls are updated. I'd have been okay with `setTimeout` if it's reliable, but it sometimes does not work in my case though it works in the example I provided.

**Comment by aitboudad** [comment]
Try this:
```ts
this.options.fieldChanges
  .pipe(
    filter(({ field, type }) => type === 'valueChanges' && this.field === field),
    tap(() => console.warn(this.model)),
  )
```

**Comment by karthikeyan-arumugam-1558** [comment]
Hmm... Works [here](https://stackblitz.com/edit/angular-gghwga-ennt8d?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fpanel-wrapper.component.ts,src%2Fapp%2Fapp.module.ts,package.json,src%2Fapp%2Fapp.component.html), but fieldChanges isn't emitting at all, in my project. Any hunch on what could be wrong?

**Comment by karthikeyan-arumugam-1558** [comment]
Think I found the issue. In my wrapper code, I have the following.
```
<ng-container *ngIf="canShowFields" #fieldComponent></ng-container>
```
`canShowFields` is `false` when when I `setValue`, and becomes `true` later only.

Changing it to the following solved the issue
```
<div [class.d-none]="!canShowFields">
  <ng-container #fieldComponent></ng-container>
</div>
```

Thanks for your prompt response anyway, appreciate it man!
