### ISSUE TITLE
Support other event types

### ISSUE THREAD

**Issue by ChristianKlima** [ngx-formly/ngx-formly#3496]
We want to build a context sensitive help in our application. It's easy to do this with formly, because we can register an event (e.g. click) for every formField in an extension. It works like a charm. 
The only problem is that we noticed that disabled fields don't fire a click event. The focus event also does not work with deactivated fields. Therefore we would like to use the MouseUp event. But only the following events can be used in Formly: ['click', 'keyup', 'keydown', 'keypress', 'focus', 'blur', 'change']. It would be great if you could use other events as well. Maybe the event name could simply be given via the props? Maybe you also have another suggestion how we can get a MouseUp event from each FormField. Many Thanks

**Comment by aitboudad** [comment]
I think that's an expected behavior for disabled field, you may consider using a [custom wrapper](https://formly.dev/docs/guide/custom-formly-wrapper) which will allows to add mouse events.
Here is an example of custom wrapper: https://formly.dev/docs/examples/other/material-prefix-suffix/
