### ISSUE TITLE
Cannot read properties of undefined (reading 'templateOptions')

### ISSUE THREAD

**Issue by 1057189519** [ngx-formly/ngx-formly#3497]
**Description**
`import { FieldType, FieldTypeConfig } from '@ngx-formly/core';`
`export class InputComponent extends FieldType<FieldTypeConfig>`
When I import the configuration as above and use templateOptions, I get an error when executing the **ng test** command: "Cannot read properties of undefined (reading 'templateOptions')". Similarly, when using formControl: "Cannot read properties of undefined (reading 'formControl')"
![image](https://user-images.githubusercontent.com/75262115/203015929-821f58d6-7f0c-4801-8a66-cf6e41e910e6.png)

**Minimal Reproduction**

https://formly.dev/docs/guide/custom-formly-field/
Follow the instructions exactly as introduced and created. The code runs fine, but errors occur when executing **ng test**.
components.ts uses templateOptions in this function，
` 

> valueChange() {

    if ((this.inputComponent as any).el.children[0] === document.activeElement) { 
      if (this.inputComponent !== undefined &&                                                                                                                                              
          this.field.templateOptions !== undefined &&
          this.field.templateOptions.fracStep !== undefined &&           
          this.field.templateOptions.fracStep <= 1) {        
          console.log('The value has changed');       
      }
    }
  }
`
Is this error caused by the function not firing when using **ng test**? But I make the '**if**' decision, I still get it wrong.
**Your Environment**

- Angular version: 14.0.6
- Formly version: 5.12.7

**Additional context**

**Comment by aitboudad** [comment]
The request is not, you may check the following working example https://stackblitz.com/edit/angular-bn1vyj-irudif?file=src/app/app.component.spec.ts

For `v6`  see https://github.com/ngx-formly/ngx-formly/issues/2723#issue-818214519
