### ISSUE TITLE
className has no effect on MatFormField with Angular Material 15

### ISSUE THREAD

**Issue by jmendes92** [ngx-formly/ngx-formly#3499]
**Description**

Using Angular Material 15.0.0 the `className` property has no effect on the element. 
  
Also tried using `props.attributes.class` which added the class to the input but had no effect either.

If I modify the `mat-form-field` element style using the dev tools I obtain the results I was expecting (see Input 1), but couldn't found a solution using formly config.

![image](https://user-images.githubusercontent.com/3502753/203081212-79bc658a-a2f2-4ec3-9678-fb10697fea6d.png)

**Minimal Reproduction**

https://stackblitz.com/edit/angular-xvuzyo-ek6tc2?file=src/app/app.component.ts

**Your Environment**

- Angular version: 15.0.0
- Angular material: 15.0.0
- Formly version: 6.0.2

**Additional context**

Using the config below it works as before but not with Angular Material 15.

- Angular version: 15.0.0
- Angular material: 14.2.7
- Formly version: 6.0.2

**Comment by aitboudad** [comment]
seems working https://stackblitz.com/edit/angular-xvuzyo-m6shke?file=src/styles.scss
