### ISSUE TITLE
Multicheckbox - Angular 9

### ISSUE THREAD

**Issue by tonedeafcoder** [ngx-formly/ngx-formly#3501]
![9H7JE](https://user-images.githubusercontent.com/68946863/203271039-6f8486ef-001d-40b9-96ac-dad72475a608.png)
We are using ngx-formly form in our Angular 9 application. We have some issues with formly multicheckbox implementation. Since the multicheckbox value gets as an Object/ key-value pair. We convert it to a string with JSON.stringify to save it to the DB(pstgres). And while retrieving we parse it and pass it to the model. This is kind of working but some times values are saved in numerics. Need some help figuring out this issue and if anything can be done to make the code look better. Formly version:

"@ngx-formly/bootstrap": "^5.10.14",
"@ngx-formly/core": "^5.10.14",
"@ngx-formly/material": "^5.10.20",
"@ngx-formly/schematics": "^5.10.14"
To stringify Multicheckbox value:

```
 stringifyMuticheckboxValue(model) {
    const values = Object.keys(model);
    values.map((value) => {
      if (Object.prototype.toString.call(model[value]).slice(8, -1) === 'Object') {
        model[value] = JSON.stringify(model[value]);
      }
    });
  }
```
And while retrieving:

```
 export function parseMultiCheckBoxValue(model) {
      if (!!model[formField]
        && isObject(model[formField])) {
        model[formField] = JSON.parse(model[formField]);
      }
    }
![9H7JE](https://user-images.githubusercontent.com/68946863/203270465-d1c075d2-56a0-49b3-a820-ba8451850cfe.png)

```
This may not be the correct implementation for multicheckbox, need some help here, sometimes the value gets saved as below.

**Comment by aitboudad** [comment]
Instead use array value which is supported by Multicheckbox, set `array` to `type` property:

```patch
{
  templateOptions: {
+   type: 'array'
  }
}
```
