### ISSUE TITLE
Object value for Select

### ISSUE THREAD

**Issue by Sash-OK** [ngx-formly/ngx-formly#3502]
Hello,

I have an issue with retrieving an object value in the Select, if I do any manipulation with model on selection change event I lose my selected value.

This is an example - https://stackblitz.com/edit/angular-a2jdqf

Angular 14
ngx-formly 6

I used to use the `compareWith` property from the `templateOptions` in the V5, is there something like that in V6?

**Comment by aitboudad** [comment]
> I used to use the `compareWith` property from the `templateOptions` in the V5, is there something like that in V6?

yes, `compareWith` still exist and its the right solution for your use-case.
