### ISSUE TITLE
FieldExpressionExtension onDestroy hook throwing 'Cannot read properties of null (reading 'unsubscribe')'

### ISSUE THREAD

**Issue by matthias-dev** [ngx-formly/ngx-formly#3505]
**Description**
After upgrade to v6 I'm getting exceptions from the FieldExpressionExtension if a formly form is getting destroyed. I have created 2 Stackblitz examples showing 2 simplified use cases that are causing the same issue. Both are reassigning an observable to a field expression.

The first example is reassigning the observable by button click (it just has to be after OnInit). This new observable is not getting subscribed to within the FieldExpressionExtension onPopulate method because OnInit was already called and this leads to an exception in the onDestroy hook because subscription is null.

In the second example the observable is reassigned by an extension. After a new model is assigned to the form the extension runs again and reassign the observable. Because it's the same instance of the field, evalExpr is triggered for this change but OnInit wont be called for this leaving the subscription field null and causing an exception in the onDestroy hook.

**Minimal Reproduction**
steps: 1. click left button; 2. click right button; 3. see console output
https://stackblitz.com/edit/angular-gqnyiu
https://stackblitz.com/edit/angular-nkcsn9

**Your Environment**

- Angular version: 14.2.12
- Formly version: 6.0.2

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
