### ISSUE TITLE
Change Detection in Custom Type broken

### ISSUE THREAD

**Issue by Kohbrax** [ngx-formly/ngx-formly#3511]
First of all, this is the Stackblitz link: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-ymtcfd?file=src/app/app.component.ts

As you can see, i created a module, which has a setTimeout to replace an object and show the output, which is not working in a custom formly type. Outside of Formly (see the main component) the exact same code works.

What should i do, to prevent this change dectection issue or is it a bug?

**Comment by aitboudad** [comment]
I think its related to OnPush Change detection which is enabled by default since v6, I'll check further.
You may use `this.options.detectChanges(this.field);` to trigger change dectection

**Comment by Kohbrax** [comment]
Thanks!

that snipped worked for me, but it appears to now work as angular default. Thanks for having a look.
