### ISSUE TITLE
NgxFormly with Material UI giving issue for File input (input type file) 

### ISSUE THREAD

**Issue by thanecoder** [ngx-formly/ngx-formly#3512]
Bug Description :
I am trying to render a form using Formly with Material UI using a JSON. 
While trying to add the File type input into the form, we get error - Error: mat-form-field must contain a MatFormFieldControl.

It seems that Formly File input is not compatible with Material UI. I also tested this out on your Material started stackblitz, getting same error there also. Link for the same - https://stackblitz.com/edit/angular-fznjcn?file=src/app/app.component.ts

Please let me know if there is workaround or fix for this. I really need to use the File input using Formly with Material UI in my app.

**Comment by aitboudad** [comment]
import `FieldType` from `@ngx-formly/material` instead:

```patch
- import { FieldType, FieldTypeConfig } from '@ngx-formly/core';
+ import { FieldTypeConfig } from '@ngx-formly/core';
+ import { FieldType } from '@ngx-formly/material';
