### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by manojmula** [ngx-formly/ngx-formly#3513]
While running the angular app , RxJS import error is thrown.

error : ./node_modules/@ngx-formly/core/fesm2020/ngx-formly-core.mjs:2353:28-31 - Error: export 'tap' (imported as 'tap') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

**versions used :**
 - "@ngx-formly/bootstrap": "^6.0.0",
-    "@ngx-formly/core": "^6.0.0",

**complete package.json :** 
   "@angular/animations": "^14.0.5",
    "@angular/cdk": "^12.2.13",
    "@angular/common": "^14.0.5",
    "@angular/compiler": "^14.0.5",
    "@angular/core": "^14.0.5",
    "@angular/fire": "^7.4.1",
    "@angular/forms": "^14.2.0",
    "@angular/material": "^12.2.13",
    "@angular/platform-browser": "^14.0.5",
    "@angular/platform-browser-dynamic": "^14.0.5",
    "@angular/router": "^14.0.5",
    "@ckeditor/ckeditor5-angular": "^2.0.1",
    "@ckeditor/ckeditor5-build-classic": "^26.0.0",
    "@ckeditor/ckeditor5-build-decoupled-document": "^30.0.0",
    "@ckeditor/ckeditor5-source-editing": "^31.1.0",
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@kolkov/angular-editor": "^3.0.0-beta.0",
    "@ngxs/store": "^3.7.5",
    "@types/ckeditor": "^4.9.10",
    "@types/crypto-js": "^4.1.1",
    "ag-grid-angular": "^28.1.1",
    "ag-grid-community": "^28.1.1",
    "angular-datatables": "^11.1.1",
    "angular-ng-autocomplete": "^2.0.5",
    "angular2-text-mask": "^9.0.0",
    "apexcharts": "^3.26.0",
    "bn-ng-idle": "^2.0.4",
    "bootstrap": "^4.6.0",
    "bootstrap-select": "^1.13.18",
    "ckeditor5-document-editor": "^19.1.1",
    "computer-name": "^0.1.0",
    "crypto-js": "^4.1.1",
    "datatables.net": "^1.10.23",
    "datatables.net-autofill-bs4": "^2.3.5",
    "datatables.net-bs4": "^1.10.23",
    "datatables.net-buttons-bs4": "^1.6.5",
    "datatables.net-dt": "^1.10.23",
    "datatables.net-fixedheader-bs4": "^3.1.7",
    "datatables.net-responsive-bs4": "^2.2.7",
    "datatables.net-select-bs4": "^1.3.1",
    "dropzone": "^5.7.2",
    "file-saver": "^2.0.5",
    "firebase": "^9.9.3",
    "getmac": "^5.17.0",
    "jquery": "^3.6.0",
    "jspdf": "^2.5.1",
    "jspdf-autotable": "^3.5.25",
    "jszip": "^3.5.0",
    "jvectormap-next": "^3.1.1",
    "material-design-iconic-font": "^2.2.0",
    "moment": "^2.29.1",
    "morris": "^0.1.4",
    "nativescript-speech-recognition": "^2.0.0",
    "ng-apexcharts": "^1.5.9",
    "ng-select2": "^1.2.5",
    "ng2-ckeditor": "^1.3.7",
    "ng2-datepicker": "^12.0.0",
    "ngx-barcode": "^0.3.0",
    "ngx-chips": "^3.0.0",
    "ngx-device-detector": "^2.0.6",
    "ngx-export-as": "^1.12.0",
    "ngx-loading": "^8.0.0",
    "ngx-pagination": "^5.1.1",
    "ngx-print": "^1.2.0-beta.5",
    "ngx-printer": "^1.0.0",
    "ngx-qrcode2": "^9.0.0",
    "ngx-socket-io": "^4.3.0",
    "ngx-toastr": "^13.2.1",
    "ngx-webcam": "^0.4.1",
    "node-os-utils": "^1.3.5",
    "os": "^0.1.1",
    "pdf-creator-node": "^2.3.4",
    "pdfmake": "^0.1.70",
    "rxjs": "~6.6.0",
    "sass-mixins": "^0.13.0",
    "select2": "^4.1.0-rc.0",
    "sweetalert2": "^10.15.4",
    "url": "^0.11.0",
    "util": "^0.12.4",
    "webcam-easy": "^1.0.5",
    "websocket": "^1.0.34",
    "xlsx": "^0.18.5",
    "zone.js": "~0.11.4"

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.0.4](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.0.4) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
