### ISSUE TITLE
Formly-field should be delete from the DOM when the field is hidden?

### ISSUE THREAD

**Issue by Jukien** [ngx-formly/ngx-formly#3516]
**Question**
When we hide a field, the formly-field object associated isn't delete from the DOM. So in HTML, fields stay vertically whereas fields should be align. Or maybe I miss something?

I have three fields in a fieldGroup and one in the middle is hidden, fields stay vertical in my example:
https://stackblitz.com/edit/angular-c9kz2s?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
use the following solution instead (`styles.scss`):

```scss
formly-field:empty {
  display: none;
}
```

**Comment by Jukien** [comment]
Thank you @aitboudad it works.
But I checked in Formly v5 and this CSS was automatically added to the formly-field element
![image](https://user-images.githubusercontent.com/32452023/205019983-d603e1a0-e658-402d-9f79-85a195c6d3ee.png)

Here the StackBlitz associated: https://stackblitz.com/edit/angular-twad3l?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
Its a different mode compared to v5 (`lazyRender` is set to `false`) but I may see if we can provide it by default.

**Comment by Jukien** [comment]
Ok thank you :)
Just thinking, if the `formly-field` is deleted on hide, it could do the trick like an `*ngIf` no?
