### ISSUE TITLE
File Upload validation

### ISSUE THREAD

**Issue by thanecoder** [ngx-formly/ngx-formly#3517]
Use case - I am using Formly with a form JSON with Material UI. 

For the custom file upload formly component, after adding the validator, the validation message is not displayed on screen. 
If possible could you pls give a look for file upload in this stackblitz link - https://stackblitz.com/edit/angular-fznjcn?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
Seems working to me https://stackblitz.com/edit/angular-fznjcn-6pipec?file=src/app/app.component.html

![Screenshot from 2022-12-18 16-48-33](https://user-images.githubusercontent.com/1753742/208307249-34660083-0526-4c9f-a6cc-f3e054254208.png)
