### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by aseem-chhabra** [ngx-formly/ngx-formly#3521]
tried to install @angular/formly in my current project using:
`npm install @angular/forms @ngx-formly/core@5.x and it has some issues and recommended me to use --force. `

So I did:
`npm install @angular/forms @ngx-formly/core@5.x --force `

but after the installation rest of the modules in my project complains about not able to find @angular/forms with an error message like this:

`TS2307: Cannot find module '@angular/forms' or its corresponding type declarations.
34 import * as i32 from "@angular/forms";`

are they not compatible together in the same project?

I tried to save angular forms again using:
`npm install @angular/forms --save`

**Comment by aitboudad** [comment]
You should specify the angular version that's compatible with `v5` or you may consider using `v6` instead:

```
// https://github.com/ngx-formly/ngx-formly#which-version-to-use
npm install @angular/forms@v13 --save
```
