### ISSUE TITLE
Using Primeng File Upload in Formly Form component, not able to use NG_VALUE_ACCESSOR.

### ISSUE THREAD

**Issue by ManikandanPrabhu** [ngx-formly/ngx-formly#3523]
**Question**
When trying to use primengFile upload with Formly form, unable to use the NG_VALUE_ACCESSOR

where trying to append the formControl throws the error as shown below
![image](https://user-images.githubusercontent.com/16269034/206439444-620a5c77-9cc4-43c9-bbdc-74a7212b146b.png)

I want this to be part of the Form, by including the formControl as shown below
![image](https://user-images.githubusercontent.com/16269034/206439632-256e8e7e-1f8a-47cf-a12b-e6a3dd4211a6.png)

but upon adding that am getting that error. 

 I have the below code but that works only for input type=file
![image](https://user-images.githubusercontent.com/16269034/206440023-dac35e25-a487-4582-bed3-8bde1869e6c2.png)

I want to utilize the capability of primeng file upload as part of formly form.
Please suggest a solution here.

**Comment by aitboudad** [comment]
if `p-fileUpload` doesn't support Angular reactive form, try to write value manually using `formControl.setValue`:

```patch
@Component({
  selector: 'formly-field-file',
  template: ` 
    <p-fileUpload
--     [formControl]="formControl"
      ...
  `,
  
})
export class FormlyFieldFile extends FieldType<FieldTypeConfig> {
+ onChange(file) {
+   this.formControl.setValue(file);
+  }
}
```
