### ISSUE TITLE
Custom Nested form no longer working after upgrading from version 5.12.7 to version 6.0.4

### ISSUE THREAD

**Issue by alex-gon** [ngx-formly/ngx-formly#3524]
**Question**

We have a custom type for that gets two pieces of data that is usable in our formly forms. This custom field type has been working well for us until we updated to the new ngx-formly version 6.0.4. The last version we had that it was working was version 5.12.7.
After updating to version 6.0.4 this field type renders and looks like it is working but it is not passing the inputed value to the model, like the other types.

Other dependency info of packages we are using:
@ngx-formly/core@6.0.4
@ngx-formly/material@6.0.4
@angular/core@13.2.0
@angular/material@13.3.9

I have my issue here in this stackblitz. In the stackblitz I have my custom type and the configuration of it in the module. my form calls it with the name and it shows up in the form along with a basic text input.
When you fill out the form and sumbit it you can see that the model does not have the values for the phone numbers it is only seeing the values for the text input.
[My stackblitz code example](https://stackblitz.com/edit/ngx-formly-ui-material-bak5ts)

I am not sure what I am doing wrong. Any direction would be super helpful

**Comment by aitboudad** [comment]
related to #3455, will make sure to provide fix it in the next minor release.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
