### ISSUE TITLE
JSON Schema - How to apply the form field group class name in JSON schema 

### ISSUE THREAD

**Issue by thanecoder** [ngx-formly/ngx-formly#3526]
Hi , Can you please let me know how to apply the form field group class name in JSON schema. It is giving issue in Angular material 15. I have attached a stackblitz link. I want to apply display-flex class to the Form group.

Stackblitz URL - https://stackblitz.com/edit/ngx-formly-ui-material-sqp6eu

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
