### ISSUE TITLE
change css class is-invalid to ng-invalid

### ISSUE THREAD

**Issue by kgathi2** [ngx-formly/ngx-formly#3528]
**Description**
css class for Angular invalid error needs to be ng-invalid as opposed to is-invalid 

https://github.com/ngx-formly/ngx-formly/blob/c4e611d88933a0e26115736a2840c8f1e0a676bf/src/ui/bootstrap/input/src/input.type.ts#L21

**Comment by aitboudad** [comment]
`is-invalid` is needed for bootstrap, `ng-invalid` is controlled by `[formControl]` directive.

Did you get some unexpected behavior ? if yes please provide a reproduction :pray:!
