### ISSUE TITLE
Problem with valuePrimitive

### ISSUE THREAD

**Issue by Miedziaq** [ngx-formly/ngx-formly#3529]
**Description**
Bug is using formly/kendo newest version 

>     "@ngx-formly/core": "^6.0.4",
>     "@ngx-formly/kendo": "^6.0.4",

The error was 

> grid-context-menu.component.ts:133 ERROR Error: Expected value of primitive type. See http://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/#toc-value-selection
>     at DropDownListComponent.verifySettings (kendo-angular-dropdowns.js:6383:19)
>     at DropDownListComponent.ngAfterContentChecked (kendo-angular-dropdowns.js:5968:14)
> 

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-kendo-nkzbgm?file=src/app/app.component.ts

**Your Environment**

- Angular version: 14.0.0
- Formly version: 		
- "@ngx-formly/core": "^6.0.4",
    "@ngx-formly/kendo": "^6.0.4",

**Additional context**
additionaly, in my project situation is worse because for me even dropdown is not shown. but in my project dwopdown is inside dialog opened by dialogService,.

i cannot make the same example with dialog in stackblitz because of kendo license

whole package.json and angular.json is in stackblitz

difference between stackblitz is 3 errors on it
![image](https://user-images.githubusercontent.com/15612453/207885480-8cb44d16-062c-44b0-9fca-dc1a5ad06de5.png)

on my private its continuously throwing the errors about valuePrimitive and crash browser ( few thousands in a minute )

**Comment by luizfbicalho** [comment]
I don't understand why valuePrimitive is fixed in true and not a prop do configure.
For my forms the ideal is to use valuePrimitive = false and use the object as the value 
How can I configure the whole object as the value?
