### ISSUE TITLE
Values added inside 'Options' property not reflecting on UI

### ISSUE THREAD

**Issue by shankupinku41** [ngx-formly/ngx-formly#3530]
**Question**

Hi,
I am trying to add a validator for one of the input fields using expression. Please find below:

![image](https://user-images.githubusercontent.com/39461223/207638777-051c1834-ff11-45d2-91bb-d99a643c1c37.png)

Inside this, 'message' property is assigned a key for the localised string in a json file(en-us.json). The key' value is as below:

![image](https://user-images.githubusercontent.com/39461223/207639274-a6f5df9c-adf4-42da-88e5-42c5dc7e758e.png)

Now, when te input field is not valid, the localised string is displayed, but the {{options.label}} and {{options.value}} is displayed as it is, without getting resolved. What is the exact way to fix this?

![image](https://user-images.githubusercontent.com/39461223/207641094-2ede6c15-86fc-44ff-8e37-77d41f8061f7.png)

I have tried certain ways :
1. Add options property there and add those properties.('value' and 'label')
2. Add those values inside props.

Please let me know if you need any other details.
Thanks in advance.

**Comment by aitboudad** [comment]
Hi,
could you please replicate a simple example using our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by shankupinku41** [comment]
I am not exactly sure how to replicate this issue here, but I can share some more details, if it helps.

1. This is the formly-config file, where formlyConfigFactory is defined, in which we have defined one custom formly extension .
![image](https://user-images.githubusercontent.com/39461223/207652188-b1435d6a-a246-4b7d-a9b1-ca822495ea17.png)

2. In this extension, we are basically getting the 'key' from 'message' property (shared earlier), and translating it to get the string value from the JSON file.
![image](https://user-images.githubusercontent.com/39461223/207653371-0e0a9d77-b265-4240-a613-4199ef3e4bb4.png)

**Comment by shankupinku41** [comment]
ok, will try to reproduce this somehow, and update. Thanks. (BTW, is it possible to do a screen-sharing sometime? :) )

**Comment by aitboudad** [comment]
![image](https://user-images.githubusercontent.com/39461223/207639274-a6f5df9c-adf4-42da-88e5-42c5dc7e758e.png)

`Note`:  the syntax here for message is not something that Formly support.

for `i18n` you may check the following example https://formly.dev/docs/examples/advanced/i18n-alternative

> is it possible to do a screen-sharing sometime? 

yes, but I a simple reproduction example would be better :)

**Comment by shankupinku41** [comment]
Hi,

I have tried to somehow replicate the issue, but translate extension is throwing some error. Same error is thrown in the Formly doc page as well, when I try to run that code in Stackblitz.

Formly doc :https://formly.dev/docs/examples/advanced/i18n-alternative/

My Stackblitz: https://stackblitz.com/edit/ngx-formly-ui-bootstrap-v8knxe?file=src%2Fapp%2Fapp.component.ts

(More details are shared in the code )

**Comment by aitboudad** [comment]
Please try the following validator format where you can return a dynamic message or retrieve it from the field instance:
![Screenshot from 2022-12-18 16-22-44](https://user-images.githubusercontent.com/1753742/208306445-10466ef4-937a-4f5b-a614-79dd5f659301.png)

**Comment by shankupinku41** [comment]
But won't this solution make the input field invalid under all circumstances ?

**Comment by aitboudad** [comment]
> But won't this solution make the input field invalid under all circumstances ?

It's just an example, you may return `{ input: null }`when the field is valid

**Comment by shankupinku41** [comment]
ok.
Then, my next question would be, now suppose, we have several form fields, and each will have a validation message which contains the user-entered data as well (data might be add at the beginning/middle/end of the static error-message).

How will we be able to localise that type of dynamic validation-message in diff. language. (Since we cannot add dynamic data value in JSON file as you mentioned.)

Possible solution: If we can have some facility, by which we can pass the value to locale JSON file, so that JSON string value can be written something like this(inside the JSON file).

'key' : 'This is the string value, user entered {{ field-value }}. This will be shown in the UI'

**Comment by shankupinku41** [comment]
POKE !!! :)

**Comment by aitboudad** [comment]
for i18n please check our examples in the docs:
- https://formly.dev/docs/examples/advanced/i18n/
- https://formly.dev/docs/examples/advanced/i18n-alternative

**Comment by shankupinku41** [comment]
I am really sorry, if I am getting carried away, but the links are not much useful from my issues' perspective. The examples provided are the cases, when the string (to be translated) is hardcoded (and is not dynamic). 

If the string is dynamic (eg: string contains value from the input field), then it becomes tricky, since the string addition to different json file (for diff. languages) is not possible, since there are dynamic values to be added in that string.

**Comment by Javril** [comment]
Hi 
I am trying to use translation in json powered file. But language translate is undefined.
How do I read multi language with json and formly
Thanks
