### ISSUE TITLE
Hover over text or tooltip for select box options

### ISSUE THREAD

**Issue by dimpu46** [ngx-formly/ngx-formly#3531]
Hi,

How to display on hover over text or tootltip, when options are displayed for select box?
 I want to show hover over text for each options displayed in the select box.

[example](https://stackblitz.com/edit/ngx-formly-select-value-text-1hqub2?file=src%2Fapp%2Fapp.component.ts,node_modules%2F%40ngx-formly%2Fcore%2Flib%2Fcomponents%2Fformly.field.config.d.ts)

in the above example, when select box is clicked, options 1,2,3,4 are shown, i want to display hover over text for those options, how can i achieve that?

**Comment by aitboudad** [comment]
The solution may depends on the use-case:

- Custom type: https://formly.dev/docs/guide/custom-formly-field
- Custom wrapper: https://formly.dev/docs/guide/custom-formly-wrapper
