### ISSUE TITLE
mat-undefined class getting applied on select panel instead of mat-primary

### ISSUE THREAD

**Issue by nehaGI** [ngx-formly/ngx-formly#3532]
panel which gets open for formly-field-mat-select  is having mat-undefined class instead of mat-primary. in earliear version it used to be mat-primary

**Your Environment**

- Angular version: 15.0.0
- Formly version: 6.0.2

**Additional context**
![image](https://user-images.githubusercontent.com/17613530/208023372-b497bdf4-8ae3-4430-8cc8-a4fe5e1c1251.png)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
