### ISSUE TITLE
Faulty layout for textareas using Formly Ionic on iOS

### ISSUE THREAD

**Issue by robbievandam** [ngx-formly/ngx-formly#3534]
**Description**
Faulty layout on iOS using textarea's. Works fine on Android and whilst running in the browser.

**Minimal Reproduction**
No point in creating a Stackblitz as the problem only occurs on actual devices.

**Your Environment**

- Angular version: v14.2.0
- Angular Ionic version: v6.3.8
- Formly version: v6.0.4

**Additional context**
```
fields: FormlyFieldConfig[] = [
    {
      key: 'test',
      type: 'textarea',
      props: {
        label: 'test',
        placeholder: 'test',
        required: true,
        rows: 4,
      }
    },
    ...
]
```

**FYI**
I opened the keyboard on purpose to show where the input is rendered.

![Simulator_Screen_Shot_-_iPhone_14_-_2022-12-19_at_16_15_13](https://user-images.githubusercontent.com/6637635/208460908-87fa14dd-c415-41db-a051-cb336f01b59e.jpg)

![Simulator_Screen_Shot_-_iPhone_14_-_2022-12-19_at_16_14_59](https://user-images.githubusercontent.com/6637635/208460904-e25bed37-0e92-4a56-ba36-2e291430e61f.jpg)

**Comment by aitboudad** [comment]
I think its probably an issue in IONIC, not related to Formly.
