### ISSUE TITLE
Material Datepicker broken CSS in v6

### ISSUE THREAD

**Issue by jmendes92** [ngx-formly/ngx-formly#3535]
**Description**

In v6 the Material Datepicker CSS seems broken based on the one displayed on the [formly documentation page](https://formly.dev/docs/ui/material).

![image](https://user-images.githubusercontent.com/3502753/208882449-b81fa1dd-49f5-41ea-acb7-8f8beb24e501.png)

The style on the [Angular Material datepicker documentation](https://material.angular.io/components/datepicker/overview)

![image](https://user-images.githubusercontent.com/3502753/208882535-08967ee5-96e7-44bb-8fcf-ca1c3af552e8.png)

The v5 version seems Ok.

![image](https://user-images.githubusercontent.com/3502753/208885298-18571c97-da0b-48d3-9869-0bf33cc04b72.png)

The [stackblitz](https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts) version seems Ok as well

![image](https://user-images.githubusercontent.com/3502753/208889279-7bb55192-ef76-42e9-a655-900e4e559f14.png)

**Minimal Reproduction**

Wrong style : https://formly.dev/docs/ui/material
Good style : https://material.angular.io/components/datepicker/examples#date-range-picker-overview

**Your Environment**

The versions below are working.

- Angular version: 14.2.12 (stackblitz) or 15.0.2 (my project)
- Angular Material version: 14.2.7
- Formly version: 6.0.4

Not sure which versions are used in the documentation page though.

**Additional context**

Angular Material 15 introduced a lot of breaking changes so maybe it is the cause.

**Comment by aitboudad** [comment]
fixed.
