### ISSUE TITLE
tailwind with formly

### ISSUE THREAD

**Issue by MussaratAziz** [ngx-formly/ngx-formly#3537]
**Question**
Can tailwind classes be used in className when building forms using formly?

**Comment by kenisteward** [comment]
As long as you are not using shadow Dom nothing special should need to be
done for tailwind.

You will have to inport the entire sheet on the page though as using the
class name property won't allow the tailwind processor to know which
classes you want to use by template to cut the sheet down.

If using shadow Dom you will have to use the class on the template / scss
itself and allow the processor to copy a sheet per component.
