### ISSUE TITLE
Get a DB schema of the FormlyFieldConfig

### ISSUE THREAD

**Issue by zshlomyz** [ngx-formly/ngx-formly#3538]
Hi,
In order to preserve the fields configuration in an external database, I would like to get the schema of the FormlyFieldConfig object.
I can't find it in the docs.
Can you help with that, please?
Thanks

**Comment by aitboudad** [comment]
We don't provide DB schema, you'll need to define your schema instead which could be based on `FormlyFieldConfig` interface.
