### ISSUE TITLE
Cascading selects using observables and hidden fields are broken

### ISSUE THREAD

**Issue by alfaproject** [ngx-formly/ngx-formly#3539]
**Description**
I'm having issues in our project with cascading selects 'inside' hidden blocks and I can't seem to find a solution. In trying to create a small reproduction I found something even more strange which seems connected and very similar to what I'm experiencing.

So, when the options are updated accordingly to some source observable dependent on a hidden field, then the new options emitted are discarded and only the empty array is used. You can actually see that in the reproduction attached by just opening the sports select, picking up anything and notice that there are no teams to pick from, but then if you pick something else, it will work which is basically what I'm experiencing.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-4avvrf?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
Could you please try the following solution:

```patch
- map((sportId) => {
+ map(() => {
+   const sportId = sportControl.value;
    const options = teams.filter((team) => team.sportId === sportId);
    if (!options.find((option) => sportId === option.id)) {
      field.formControl.setValue(null);
    }

  return options;
}),
```

**Comment by alfaproject** [comment]
@aitboudad that worked for this particular example, but I'm confused

**Comment by freon27** [comment]
I had exactly the same problem, and this fixes it (thanks!).

But I would also love to understand why this is necessary?
