### ISSUE TITLE
Slider - Using Formly Slider with Material UI giving console error in Angular 15

### ISSUE THREAD

**Issue by thanecoder** [ngx-formly/ngx-formly#3543]
Formly + Material Slider error in Angular 15 

**Description**
When we add a Slider form element using Formly with Material UI, it gives console error. 

![image](https://user-images.githubusercontent.com/20127101/210133637-5347e3ac-2f1e-4d55-922c-27f22ec9878b.png)

**Minimal Reproduction**
Here is the stackblitz link - https://stackblitz.com/edit/angular-brfkcx?file=src/app/app.component.ts

**Your Environment**

- Angular version: 15.0.4
- Formly version: 6.0.4

**Comment by thanecoder** [comment]
Additionally when we click on the Slider, one more error is shown - ERROR TypeError: this.slider.focus is not a function

**Comment by aitboudad** [comment]
The issue has been already fixed (which is related to #3503), we'll be able to publish a new release by  the next week.

**Comment by thanecoder** [comment]
Hi @aitboudad , so this will be fixed in v6.0.5 ?

**Comment by aitboudad** [comment]
> Hi @aitboudad , so this will be fixed in v6.0.5 ?

`v6.1.0`

**Comment by thanecoder** [comment]
Hi @aitboudad, if possible could you please suggest some work-around for this Slider issue, which we can use till the next version is released.

**Comment by thanecoder** [comment]
Hi @aitboudad  , facing one issue in the new version , the Slider thumbLabel is not coming . Stackblitz link for this issue - https://stackblitz.com/edit/angular-brfkcx?file=src%2Fapp%2Fapp.component.ts. 

I have set the thhumbLabel as true in the props , but still the thumbLabel is not appearing.

**Comment by ngagua** [comment]
Hello @aitboudad 
updated to 6.1.1 version, but got the same error.
![image](https://user-images.githubusercontent.com/75014232/216597845-b0067db3-c0a1-461c-b5ae-f3321181a010.png)

**Comment by aitboudad** [comment]
@ngagua the slider should work just ignore the error for now, its a material issue will try to send a PR when time allows (mentioned here https://github.com/ngx-formly/ngx-formly/issues/3560#issuecomment-1399026098)
