### ISSUE TITLE
Error: Cannot set properties of undefined (setting 'control')

### ISSUE THREAD

**Issue by Vvkg93** [ngx-formly/ngx-formly#3553]
**Description**
We're in the process of upgrading from v5 - v6 and the features looks great so far and I would like to thank you!

When upgrading our project, we came across an issue when using custom wrapper overwriting the **form-field** wrapper (or a new custom wrapper).
![image](https://user-images.githubusercontent.com/61705750/211585804-8ebd9393-2777-45ec-af2b-9a3845d5be1d.png)

I have linked a stackblitz code where you can reproduce the issue. Just run the application and look at the console log.
The error disappear if I don't use the custom wrapper.
If this is an issue or did I miss to update anything in the wrapper component? 

**Minimal Reproduction**
https://stackblitz.com/edit/angular-8dzjjs-wneult?file=src/app/app.component.ts

**Your Environment**

- Angular version: 13.3.12
- Formly version: 6.0.4

**Additional context**
We are making use of kendo components within our project

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by Vvkg93** [comment]
Hi @aitboudad , I tested and it works. Thanks for the fix.
