### ISSUE TITLE
How to Use Custom Directives

### ISSUE THREAD

**Issue by nrbokade** [ngx-formly/ngx-formly#3554]
Hi Team,
I am unable to use custom directive with formly-field.
I have created one custom directive for input box to convert text to upper case, directive as attribute is getting added to textbox but no effect.
PFA.

![image](https://user-images.githubusercontent.com/32088458/211856141-399f77dd-6e47-4901-8d8c-bd4d868e2363.png)
![image](https://user-images.githubusercontent.com/32088458/211857040-db21a73e-397a-4cb2-ad52-ef51b0c14e9e.png)
![image](https://user-images.githubusercontent.com/32088458/211856416-5dfddb9c-5561-48b8-8c9f-7a64f214ec35.png)
![image](https://user-images.githubusercontent.com/32088458/211856647-53f93b00-5e83-45a2-9500-ab6e01e16856.png)

If I use same directive with normal textbox without formly-form then its working fine.

Any help is appreciated,

Thanks!

**Comment by aitboudad** [comment]
No possible, instead define a custom type and pass the directive the field template (https://formly.dev/docs/guide/custom-formly-field)
