### ISSUE TITLE
Inject service into validator (in Angular 14)

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3555]
I am having the below validator:
```
export function dateInThePastValidator(control: AbstractControl) {
  const coreDatetimeService = InjectorInstance.get<CoreDatetimeService>(CoreDatetimeService);
  const controlDate = new Date(control.value);
  const nowDate = coreDatetimeService.getLocalDate();  
  if (controlDate.getTime() < nowDate.getTime()) {
    return { dateInThePast: true };
  }
  return null;
}
```
which is being registered in app module
![image](https://user-images.githubusercontent.com/42749923/212084391-0ad8da22-7cb2-4c1e-83e6-ebb1654748c4.png)

which works fine with the application.

But updating from Angular 13 to v 14, the recommended approach is to use inject (https://codereacter.medium.com/why-angular-14s-new-inject-function-is-so-amazing-ac281e7148d1 or https://dev.to/this-is-angular/always-use-inject-2do4)

if I use inject like below:
```
  const coreDatetimeService = inject(CoreDatetimeService);
```
instead of 
```
  const coreDatetimeService = InjectorInstance.get<CoreDatetimeService>(CoreDatetimeService);
```

I am getting the following error in the console, and the component with the formly form/validation does not work, in the place where the validator is used:

![image](https://user-images.githubusercontent.com/42749923/212084910-01d4dec0-9603-4997-bd81-6a8fb4b2744e.png)

**inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`.** 

Is there still a way to use inject and get a working validator?

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/2551#issuecomment-714727118
