### ISSUE TITLE
Material matPrefix - Space missing in the material matPrefix in Formly 

### ISSUE THREAD

**Issue by thanecoder** [ngx-formly/ngx-formly#3556]
When using Material UI with Formly, the matPrefix appears stuck to the left border of the form field. In normal Material form field, there is some gap between the left border of form field and the matPrefix , that is missing when we add prefix via extension in Formly.
 
Below image for reference :- 
![image](https://user-images.githubusercontent.com/20127101/212231252-e496c31e-ac0e-4d0c-85db-c5337693489b.png)
(Tried to upload on stackblitz, but for some reason stackblitz appears to be some ongoing issue for Angular apps)

Wrapper code :- 

![image](https://user-images.githubusercontent.com/20127101/212231600-d81096dd-7c6c-444f-a584-5cc01eb9df70.png)

Could you please let me know if this is due to Formly adding any additional CSS class for the matPrefix or if it is a Angular material v15 issue

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.1) release.

**Note**: use `textPrefix`/`textSuffix` prop for text content and for icons use `prefix` / `suffix`.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by thanecoder** [comment]
Hi @aitboudad, having one query here, Do we still have to use the addOns wrapper and extensions Or should we directly pass the prefix and suffix in the props?

**Comment by randallmeeker** [comment]
I ended up here with icon issues as well. The example have a `span` tag wrapping the icon and text. I refactored without the span tag. The span tag breaks CSS for use with matIcon. 

For example, mine now looks like this for suffix


```
    <ng-template #matSuffix>
      <ng-container *ngIf="props['addonRight']">
        <mat-icon
          *ngIf="props['addonRight'].icon"
          (click)="addonRightClick($event)"
          [ngStyle]="{
            cursor: props['addonRight'].onClick ? 'pointer' : 'inherit'
          }"
          [matTooltip]="props['addonRight'].tooltip"
          >{{ props['addonRight'].icon }}</mat-icon
        >
        <span *ngIf="props['addonRight'].text">{{
          props['addonRight'].text
        }}</span>
      </ng-container>
    </ng-template>
```
