### ISSUE TITLE
Add subscriptSizing support for Material FormField

### ISSUE THREAD

**Issue by craigsh** [ngx-formly/ngx-formly#3559]
**Is your feature request related to a problem? Please describe.**

Material v15 has a subscriptSizing input on FormField which can be 'fixed' or 'dynamic'.  As Formly provides a default form-field wrapper, it would be good to be able to set this input to dynamic for my project.

**Describe the solution you'd like**
Add a property to the form-field wrapper.

**Comment by dc-p8** [comment]
+1

As a workaround, if you always want fixed or dynamic, you can use the MAT_FORM_FIELD_DEFAULT_OPTIONS injection token to set the default value of subscriptSizing

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
