### ISSUE TITLE
Model not populated correctly for  JsonSchema having oneOf string and array type

### ISSUE THREAD

**Issue by navnita-170310093** [ngx-formly/ngx-formly#3561]
**Description**
In JsonSchema, a property is oneOf string or array of strings. 
In model we are giving string.
But when it is populated in UI it is splitting the string and each character of string is shown as array values.

**Minimal Reproduction**
Editor url
 https://stackblitz.com/edit/angular-a2vvgr-ztafxd?file=src/assets/json-schema/simple.json
Application url
 https://angular-a2vvgr-ztafxd.stackblitz.io/
I am providing the jsonSchema and model here
`{
  "schema": {
    "properties": {
      "Name": {
        "oneOf": [
          { 
            "type": "string"
          },
          {
            "items": {    
              "type": "string"
            },
            "type": "array"
          }
        ]
      }
    }
  },
  "model": {
    "Name":"Navnita"
  }
}`
Using current version. 
I tried the same schema in react jsonSchema form, it is generating correct output

**Additional context**
added image of the ui

![oneof](https://user-images.githubusercontent.com/71219014/212914775-612f14f4-bc5c-428e-abf9-d860b2223e44.PNG)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by navnita-170310093** [comment]
Thanks a lot, now its working fine.
