### ISSUE TITLE
Examples on custom validation messages are not working

### ISSUE THREAD

**Issue by bohndthi** [ngx-formly/ngx-formly#3562]
**Description**
Custom validation messages are not shown. I first noticed it when i tried to use them in my code, but also the official examples are always showing the default message.
I think this might be a regression, though https://v5.formly.dev/examples/validation/custom-validation is also not working as expected.

**Minimal Reproduction**

https://formly.dev/docs/examples/validation/custom-validation

**Your Environment**

- Official Formly Examples, v6 and v5
**Additional context**
-

**Comment by aitboudad** [comment]
The examples work as expected, we may more details so we can check further.
