### ISSUE TITLE
Angular 15 select component issue

### ISSUE THREAD

**Issue by Marcus-Karl** [ngx-formly/ngx-formly#3563]
**Description**
The material select popup is placed incorrectly when using Formly with Angular 15. The popup is placed below the mat-form-field instead of below the mat-select, which leaves a noticeable gap.
![image](https://user-images.githubusercontent.com/37304805/213545616-5457be11-db93-4443-bc03-93d05f7a37ab.png)

**Minimal Reproduction**
This can be seen by using the Formly Material template and updating all to latest.
Template fork with Angular 15: https://stackblitz.com/edit/ngx-formly-ui-material-e3ggrj

**Your Environment**
- Angular version: 15.1.1
- Formly version: 6.1.0

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
