### ISSUE TITLE
Migration v6

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#3568]
**Description**
today I started analyzing to migrate from V5 to V6 and I'm almost giving up.
a lot has changed and I don't see all of that in the migration documentation (https://github.com/ngx-formly/ngx-formly/blob/main/UPGRADE-6.0.md).

Some examples:
this.field.templateOptions - will no longer exist?
this.to - will no longer exist?

error with formGroup.
If I try to access fieldGroup, I get an error that does not exist, for example:
this.field?.fieldArray?.fieldGroup
![Captura de Tela_selecionar área_20230120185757](https://user-images.githubusercontent.com/11314585/213803880-6d3d170a-393f-4737-87c3-764c9bcfbeb4.png)

not to mention that I'm afraid it has a function that I'll realize will stop working only in the tests.

about the fields that no longer exist, if not, I think it's worth making an idea of a helper available, to create these fields for those who have a large application like me and who can't change everything.

**Comment by aitboudad** [comment]
> this.field.templateOptions - will no longer exist?
> this.to - will no longer exist?

All those options still exist in `v6`

> this.field?.fieldArray?.fieldGroup

I think this is related to that part: https://github.com/ngx-formly/ngx-formly/blob/main/UPGRADE-6.0.md#7-add-support-of-strict-template-checking

For `FieldArrayType`:

  ```patch
  - import { FieldType } from '@ngx-formly/core';
  + import { FieldType, FieldArrayTypeConfig } from '@ngx-formly/core';
  @Component({
    template: `<input [formControl]="formControl" />`,
  })
  - export class CustomFieldType extends FieldType {}
  + export class CustomFieldType extends FieldType<FieldArrayTypeConfig> {}
  ```

The issue is raised only when the strict template is enabled so in case you're looking for an easy upgrade disable strictTemplate https://angular.io/guide/template-typecheck#template-type-checking

**Comment by GlauberF** [comment]
when it was of the array type, I used it that way.
`export class VimboFormlyTableTypeComponent extends FieldArrayType{}`

Now does it have to be like this?
`export class VimboFormlyTableTypeComponent extends FieldType<FieldArrayTypeConfig>{}`

now I don't extend FieldArrayType directly, right?
or did I get it wrong.

**Comment by aitboudad** [comment]
if you extend `FieldArrayType`, then you don't have to passe `FieldArrayTypeConfig`.

**Note**: `export class VimboFormlyTableTypeComponent extends FieldArrayType {}` should work without any issue.

**Comment by GlauberF** [comment]
Perfect,
About the `FormlyField` type, in some places I accessed some positions that now in v6 I cannot or I get an error.

example:
- FormlyField?.form?.touched
`error TS2341: Property 'form' is private and only accessible within class 'FormlyField'`

- FormlyField?.model
`Property 'model' does not exist on type 'FormlyField'`

For me to reach the same goal, as I should do now in V6.

**Comment by aitboudad** [comment]
You can get `form` and `model` through the `field` property:

> - FormlyField?.form?.touched

use `FormlyField.field.form`

> - FormlyField?.model

use `FormlyField.field.model`

**Comment by GlauberF** [comment]
Today I got some time to test, and even in disabling tsconfig.json, I get the type errors mentioned at the beginning of this issue and shown in the image.
`tsconfig.json`

```typescript
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./src",
        "outDir": "./dist/out-tsc",
        "forceConsistentCasingInFileNames": true,
        "strict": false,
        //"noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "downlevelIteration": true,
        "sourceMap": true,
        "declaration": false,
        "module": "es2020",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "target": "es2020",
        "typeRoots": ["node_modules/@types"],
        "lib": ["es2018", "dom"],
        "strictNullChecks": false,
        "paths": {
            // core
            "@vimbo": ["@vimbo/"],
            "@vimboConf/*": ["app/vimbo-config/*"],
            "@env/*": ["environments/*"],
            "@guards/*": ["app/guards/*"],
            "@nav/*": ["app/navigation/*"],
            "@layoutComponent/*": ["app/layout/components/*"],
            // default extended
            "@apps/*": ["app/main/apps/*"],
            "@pages/*": ["app/main/pages/*"],
            "@db/*": ["assets/db/*"],
            // Libs
            "moment": ["../node_modules/moment/min/"],
            "lodash": ["./proxies/lodash-es.ts"],
            "crypto-js": ["./proxies/crypto-js.ts"]
        }
    },
    "exclude": ["@schematics/", "**/@schematics/**"],
    "angularCompilerOptions": {
        "fullTemplateTypeCheck": false,
        "strictInjectionParameters": false,
        "strictInputAccessModifiers": false,
        "strictTemplates": false,
        "strictInputTypes": false,
        "strictAttributeTypes": false,
        "strictSafeNavigationTypes": false,
        "strictContextGenerics": false,
        "strictLiteralTypes": false
    }
}
```
