### ISSUE TITLE
Component created multiple times

### ISSUE THREAD

**Issue by roll57** [ngx-formly/ngx-formly#3573]
**Question**
Hello, I notice that when I add a custom type to formly the constructor is called several times, even if there is only one occurrence of the component.

I don't think it is normal, the destroy method is not called, so both instances of the component are live when the app is running. I think it could be a source of problem if logic is done in the constructor.

![image](https://user-images.githubusercontent.com/7392462/214261797-0f7a551b-b27f-4a63-b9fe-edbeb4280c61.png)

Here is the link to reproduce it https://stackblitz.com/edit/formly-example-os3ent?file=src/app/comp.component.ts

**Comment by KakashiOfAnbu** [comment]
https://stackblitz.com/edit/formly-example-ueffub?file=src/app/comp.component.ts here i think is the correct implementation, just remove the constructor and the Comp from boostrap in AppModule

**Comment by KakashiOfAnbu** [comment]
also it is great to add changDetection onPush

**Comment by roll57** [comment]
Hello,
Having onPush detection does not change the fact that component is created twice.
I have added the constructor to show with a console.error that the component was created twice.

**Comment by roll57** [comment]
If i take it deeper with another component. It is created 4 times:
https://stackblitz.com/edit/formly-example-rnkmo9?file=src%2Fapp%2Fcomp2.component.ts
@aitboudad so it is expected behaviour and there is no way to avoid it?

**Comment by aitboudad** [comment]
Its ok for now, the  main advantage of this way is when dealing with a large `form`.

**Comment by roll57** [comment]
If I have an event listener I can see it call several time (3x)
https://stackblitz.com/edit/formly-example-rnkmo9?file=src/app/app.module.ts

**Comment by aitboudad** [comment]
@roll57 that's a good point. you'll need to deal with subscriptions which is true with any components in Angular not only Formly, all subscriptions should be cleaned  in `ngOnDestroy`.

**Comment by roll57** [comment]
hello, of course in a real example I will manage ngOnDestroy, but here it does not seems to be called.
Updating the example I don't see it been called: https://stackblitz.com/edit/formly-example-rnkmo9?file=src%2Fapp%2Fcomp2.component.ts,package.json,src%2Fapp%2Fcomp.component.ts

**Comment by aitboudad** [comment]
@roll57 `this.sub` can be undefined if the `ngOnInit` is not called

**Comment by roll57** [comment]
@aitboudad  you are right, i change it, still clicking the button add 3, which means there are 3 instances of my components.
ngOnDestroy is never called in my example.
