### ISSUE TITLE
Slider | Material - DisplayWith not updating the thumbLabel formatting

### ISSUE THREAD

**Issue by thanecoder** [ngx-formly/ngx-formly#3574]
**Description**
Slider | Material - DisplayWith not updating the Slider Thumb Label formatting
I want to append 'k' to the value on the Slider Thumb Label, Kindly check and please let me know if this is not the correct way for the displayWith.  

Stackblitz Link - 
https://stackblitz.com/edit/angular-brfkcx?file=src%2Fapp%2Fapp.component.ts

**Comment by digoburigo** [comment]
This error is still occurring
```
An error occurred while destroying the Formly component type "slider"
Error: Cannot read properties of undefined (reading 'removeEventListener')
```
Related to #3560

**Comment by thanecoder** [comment]
Hi @aitboudad, Pls check the displayWith property for the MatSlider. Cannot add the Formatting for the value for the thumbLabel.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by digoburigo** [comment]
Updating the dependencies in this example https://stackblitz.com/edit/angular-brfkcx?file=src%2Fapp%2Fapp.component.ts
The error still persists. Can you confirm it?

**Comment by aitboudad** [comment]
@digoburigo I confirm, please check my note https://github.com/ngx-formly/ngx-formly/issues/3560#issuecomment-1399026098

**Comment by aitboudad** [comment]
@digoburigo I've created a PR in material repository, hope it'll be merged soon.

**Comment by digoburigo** [comment]
Oh ok, my bad
