### ISSUE TITLE
Behavior change with formly v6.x in custom field with mat-autocomplete

### ISSUE THREAD

**Issue by larsenqec** [ngx-formly/ngx-formly#3575]
**Description**

We have a custom formly field with autocomplete that displays the mat-autocomplete panel as a mat-table. It works perfectly with ngx-formly 5.x, but when upgrading to 6.x, an extra keystroke is required to trigger the popup. 

**Minimal Reproduction**

Here is the 5.x version: https://stackblitz.com/edit/angular-ivy-yawmsc
In the input field, type 1234 and you will get 2 matches in the auto-complete panel as expected

Here is the 6.x version: https://stackblitz.com/edit/angular-ivy-yazmqy
In the input field, type 1234 and nothing happens. If you type one more character then the popup shows.

The only difference in the two is the formly version.

This seems like a small change but if we were to deploy that to production, it would be disruptive for our users as the extra  keystroke is not at all intuitive. In fact, the use case demonstrated is one where we need exactly 4 digits to search on, no more, no less. so the popup should show once the 4th character is input.

I have been unable to find a workaround.

**Your Environment**

- Angular version: 13.3.12
- Formly version: 6.1.1

**Additional context**
If the samples are re-written to simply use mat-option instead of all the mat-table stuff, then the behavior is as expected in formly 6.x.  I don't know why mat-table is behaving differently.

**Comment by larsenqec** [comment]
I came up with a workaround to manually open the autocomplete panel, but it would be nice if it wasn't required.

https://stackblitz.com/edit/angular-ivy-4bgyum

**Comment by aitboudad** [comment]
Tested on fresh installation and it seems working without the workaround: https://stackblitz.com/edit/angular-4qj9pm?file=src/app/autocomplete-type.component.ts
