### ISSUE TITLE
FieldArrayType.add() fails when using FormlyFormBuilder.buildForm()

### ISSUE THREAD

**Issue by Marcus-Karl** [ngx-formly/ngx-formly#3576]
**Description**
After converting a json schema with an array of objects. If you call FormlyFormBuilder.buildForm you cannot call FieldArrayType.add without getting a console error. Form.valid checks for the form will fail and the form controls will also not render on screen.

![image](https://user-images.githubusercontent.com/37304805/214697036-993cac2a-6b53-47f8-844e-b16f48537aa1.png)

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-aydnff

**Your Environment**
- Angular version: 15.1.2
- Formly version: 6.1.1

**Additional context**
It looks like FormlyFormBuilder.buildForm() changes the FormArray built in the json schema service to a FormControl, which doesn't have the setControl method.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.5) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
