### ISSUE TITLE
form field is null when it is hidden 

### ISSUE THREAD

**Issue by ha-akelius** [ngx-formly/ngx-formly#3577]
**Description**
when the field is hidden => this will make the form field null 
expected behaviour the form field is not null but only hidden (aka display none) 

**Minimal Reproduction**

Please check the sample below
https://stackblitz.com/edit/ngx-formly-ui-material-bnnbmj?file=src/app/app.component.ts

I have 3 dependent drop down list ( in my example country => city => district), 
- first one (country) will hide the second one (city) depends on value (when country is undefined)
- when second one (city) is hidden => the form field (city form field) is null => which will break the Third (district options) dependent drop down list 

**Your Environment**

- Angular version: 14.2.8
- Formly version: 6.0.1

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/3539#issuecomment-1366041802

**Comment by aitboudad** [comment]
> when second one (city) is hidden => the form field (city form field) is null => which will break the Third (district options) dependent drop down list

When the field is hidden, the form control is removed from `form`. If you want to get the form field instance you may use `field.get('city')` instead:

```patch
-- const city = field.form.get('city');
++ const city = field.get('city').formControl;
```

**Comment by ha-akelius** [comment]
thank you @aitboudad for your response 

I fixed it with 

```diff
-- const city = field.get('city').formControl;
++ const city = field.parent.get('city').formControl;
````

and updated the stackblitz
