### ISSUE TITLE
@ngx-formly/material-legacy not getting updates?

### ISSUE THREAD

**Issue by dkimmich-onventis** [ngx-formly/ngx-formly#3579]
I'm using Angular 15 with the Material legacy components, so I am using `@ngx-formly/material-legacy` package. Recently version `6.1.1` of this package was released, but the [`@ngx-formly/material-legacy`](https://www.npmjs.com/package/@ngx-formly/material-legacy?activeTab=versions) package was not updated. When trying to update `@ngx-formly/core` to the latest version, I'm getting a peer dependency error during install:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @ngx-formly/material-legacy@6.1.0
npm ERR! Found: @ngx-formly/core@6.1.1
npm ERR! node_modules/@ngx-formly/core
npm ERR!   @ngx-formly/core@"6.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @ngx-formly/core@"6.1.0" from @ngx-formly/material-legacy@6.1.0
npm ERR! node_modules/@ngx-formly/material-legacy
npm ERR!   @ngx-formly/material-legacy@"6.1.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @ngx-formly/core@6.1.0
npm ERR! node_modules/@ngx-formly/core
npm ERR!   peer @ngx-formly/core@"6.1.0" from @ngx-formly/material-legacy@6.1.0
npm ERR!   node_modules/@ngx-formly/material-legacy
npm ERR!     @ngx-formly/material-legacy@"6.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

What is the state of the `@ngx-formly/material-legacy` package, does it receive updates or not? If not, what about setting the peer dependency `@ngx-formly/core` to a range, like `^6.1.0`, instead of using a specific version?

**Comment by aitboudad** [comment]
fixed, please try with `@ngx-formly/material-legacy` = `v6.1.1`
