### ISSUE TITLE
Enable validation only when field was edited

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3580]
Maybe there is already a solution for what I am looking for.
I want to edit some data in a pre-filled form.
When editing a form field (datepicker) in a formly form, I want the validation to be triggered only after the first changes were introduced.

The validators that I have are 

```
     validators: {
                  validation: ["dateInThePast"],
     },
```

it works just fine, but I want that they are triggered only after the first change.

Actually I found a similar approach, https://github.com/ngx-formly/ngx-formly/issues/2116
but I was not able to correctly re-enable the custom property to re-start the validation (onInit hook was not working for me).
Can you suggest a solution?

**Comment by ottomillrath** [comment]
you can use an expression to change the value of **props.custom1**

```
expressions: {
 'props.custom1': () => !somevar
}
```

**Comment by kenisteward** [comment]
Have you tried overriding showError? The fault one waits for touched
already but you can add more restriction.

If you could throw a stackblitz as well on what's going wrong that would
help too.
