### ISSUE TITLE
CreateComponent undefined Issue in ngx-formly

### ISSUE THREAD

**Issue by malihakhizer** [ngx-formly/ngx-formly#3583]
I have recently upgraded the angular version from 8 to 12. We are using @ngx-formly/core": "4.6.3". Even if i upgrade it to 5.x.x its giving me an error related to the field group validations which is giving me a headache to solve although after upgrading the ngx-formly version does resolve this. With 4.6.3 version I am getting a createComponent undefined error like mentioned below. Can anyone help me diagnose the error and any way to solve this with 4.x.x version?

<img width="646" alt="image" src="https://user-images.githubusercontent.com/47573598/216558004-dd79cc4e-775d-4e9e-8f65-5307f2783c29.png">

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
