### ISSUE TITLE
mat-select with disabled: true disables form

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#3586]
I am using Formly Material 5.12.6 with Angular / Material 13.3

Within my form I have a select that is loaded with some pre-selected values from a service call.

I want to prevent the user from making any changes and have tried to set the field to disabled by adding "disabled: true" to the templateOptions  

When I do that my form "Submit" button gets disabled

``` javascript
                 {
                      type: "select", 
                      key: "devCat",
                      templateOptions: {
                        label: "Dev Category",
                        placeholder: "Select Device Category",
                        required: true,
                        disabled: true,
                        options: [
                          { label: "Acutator", value: "actuator" },
                          { label: "Beacon", value: "beacon" },
                          { label: "Device", value: "device" },
                        ],
                      },
                    },
```

data received from backed call looks like below, I do see the value get populated in the select and the model.

``` javascript
{
 ...
"devCat": "actuator",
}
```

If I remove the "disabled" attribute the "Submit" button is enabled.

Can you please help me understand what I could be doing wrong? Thanks

**Comment by aitboudad** [comment]
Hi,
The question is not clear, please elaborate and provide an example using our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
