### ISSUE TITLE
FormlyField with custom input type:  focus and blur not working

### ISSUE THREAD

**Issue by shananlynch** [ngx-formly/ngx-formly#3587]
**Description**
When using FormlyField with a custom input type the focus and blur does not work.
In the stackblitz you can see that the second field only works because it's using the Kendo TextArea as directive, otherwise it will not focus or blur.

https://stackblitz.com/edit/angular-8dzjjs-ghzrpv?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 13.3.12
- Formly version: 6.1.0

**Comment by aitboudad** [comment]
`formlyAttributes` can handle only the HtmlElement events so for `kendo-textbox` component you'll need to bind those events manually or rely Textarea with `kendoTextArea` directive instead: https://github.com/ngx-formly/ngx-formly/blob/main/src/ui/kendo/textarea/src/textarea.type.ts#L13
