### ISSUE TITLE
Issue with checkbox field

### ISSUE THREAD

**Issue by tomav123-git** [ngx-formly/ngx-formly#3590]
****

**Description**
 I am getting an issue with formly checkbox field. Field Required validation is triggering initially, but if we check and uncheck the checkbox, it is not giving the required validation. So form will be in Valid status. I believe it is an issue with core library, it was working in previous version. Could you please help

**Minimal Reproduction**
https://angular-j7bwy9.stackblitz.io

**Your Environment**

- Angular version: 14.2.12
- Formly version: 6.1.1

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1362#issuecomment-451643594

**Comment by tomav123-git** [comment]
But it was working in v5.0.0 without using requiredTrue.I'm using expressions function to set this required property. Can you please check it again?

**Comment by aitboudad** [comment]
It doesn't work either in `v5.0.0` so I don't think its a regression, https://stackblitz.com/edit/angular-qzrcrn?file=src/app/app.component.ts
