### ISSUE TITLE
Regression: JSON $ref not handled correctly in v6.1.1 

### ISSUE THREAD

**Issue by swesemeyer** [ngx-formly/ngx-formly#3591]
Upgrading from v5.12.7 to v6.1.1 appears to have lost the ability to handle $ref tags in a JSON schema correctly.

The schema I obtain from the backend server contains the following item which references another schema definition in the same file, ie:

      "inputs": {
        "title": "Inputs",
        "type": [
          "array",
          "null"
        ],
        "items": {
          "type": "object",
          "$ref": "#/definitions/ProcessInputSchema", <== works fine in v5 but not in v6
          "title": "Inputs",
          "description": "The inputs to the process."
        },

Previously, in v5.12.7, this $ref was resolved correctly and resulted in the inputs field containing a fieldArray with all the items listed in the ProcessInputSchema. In version 6.1.1, the $ref seems to be ignored or skipped and the inputs field does not contain that fieldArray anymore.

**Your Environment**

- Angular version: 15.1.4
- Formly version: 6.1.1 (not working) & 5.12.7 (working)

**Comment by aitboudad** [comment]
Hi, could you please provide a `stackblitz` reproduction example 🙏
Thanks!

**Comment by aitboudad** [comment]
Seems working here (check references example) https://formly.dev/docs/examples/advanced/json-schema/

Feel free to leave a comment once you've got a reproduction example, thanks!

**Comment by swesemeyer** [comment]
Hi,

Thanks for looking at this....

I finally got round to stripping all the irrelevant bits from the code. 

This is the version that is not working, ie the one with formly 6.1

https://stackblitz.com/edit/angular-6m61yn?file=src%2Fapp%2Fapp.component.ts

The ap just shows a "clickme" link which you should click. 

Observe the console output which logs the content of the generated field item that I am interested in: "inputs". It should contain an array of content (see original report).

The schema can be found in the asset folder.

Unfortunately, stackblitz doesn't want to run with the package-v5-working.json. However, when run locally with that file it does produce the necessary FieldArray.

I have attached 2 screenshots of the behaviour as well.

Cheers,
 Steve

Version 5 working as expected:

![v5-working](https://user-images.githubusercontent.com/6536807/220118820-91d66f3a-fc65-45c7-99b7-5a8d9b5576bd.png)

Version 6 not working as expected:
![v6-notworking](https://user-images.githubusercontent.com/6536807/220119586-041a291e-3d50-4d5f-929d-d24b41afdec2.png)

**Comment by aitboudad** [comment]
`fieldArray` return a function since `v6` which is mentioned in our   [Migration Guide](https://formly.dev/docs/guide/migration). 
Based on your example you can the value of `fieldArray` through the following path: `formlySchema[0].fieldGroup[6].fieldArray`.

```patch
-- const fields = JSON.parse(JSON.stringify(formlySchema));
console.log("inputs contains a FieldArray")
-- console.log(fields[0].fieldGroup[6]);
++ console.log(formlySchema[0].fieldGroup[6])
```

**Comment by aitboudad** [comment]
Here is another example if you want to customize the output of fieldArray https://github.com/ngx-formly/ngx-formly/issues/3351#issuecomment-1179780848

**Comment by swesemeyer** [comment]
@aitboudad 
Great thanks! That works!
I did look at the migration guide in detail but that one didn't jump out to me...
