### ISSUE TITLE
json example is not working in stackblitz

### ISSUE THREAD

**Issue by melaniedupuis** [ngx-formly/ngx-formly#3598]
you json example is not working

https://formly.dev/docs/examples/other/json-powered

in stackblitz

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
Fixed, Thanks!

**Comment by melaniedupuis** [comment]
don't seem fixed when we check the link
https://formly.dev/docs/examples/other/json-powered

only a button is displayed

https://pasteboard.co/k88fIzaCVW13.jpg

**Comment by aitboudad** [comment]
> only a button is displayed
[pasteboard.co/k88fIzaCVW13.jpg](https://pasteboard.co/k88fIzaCVW13.jpg)

You need to fork the example (click on 'Fork' button) in order to make it work.
