### ISSUE TITLE
Documentation: Formly testing

### ISSUE THREAD

**Issue by jljohnson001** [ngx-formly/ngx-formly#3599]
**Question**

Can we please update Formly documentation to include best practices for testing with examples? Additionally, the current Documentation page for testing returns a 404:
https://formly.dev/docs/api/core/testing/
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/66479094/219646355-6ef2647a-a90c-4c5b-974b-709e0521e457.png">

**Comment by aitboudad** [comment]
The doc for testing is not done yet but you may check some examples in the following issue https://github.com/ngx-formly/ngx-formly/issues/2723#issue-818214519
