### ISSUE TITLE
Updating model object

### ISSUE THREAD

**Issue by tomav123-git** [ngx-formly/ngx-formly#3603]
how can we update the model value. Im doing it in version5 with spread operator.but with v6 im getting model is a read only property error. Sample code with v5 as follows:
this.model= {...this.model, email: 'email'}

- Angular version: 14
- Formly version: 6

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, you can use our starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by tomav123-git** [comment]
I have added the example in onsubmit function https://stackblitz.com/edit/ngx-formly-ui-bootstrap-4ugz7j?file=src/app/app.component.ts

**Comment by tomav123-git** [comment]
@aitboudad i created a similar case, could you pplase check the following fork and help?
https://ngx-formly-ui-bootstrap-wwudsq.stackblitz.io 
[fork](https://ngx-formly-ui-bootstrap-wwudsq.stackblitz.io)

**Comment by tomav123-git** [comment]
@aitboudad i'm trying to achieve something like this: https://github.com/ngx-formly/ngx-formly/issues/1116#issuecomment-412297872
Added stackblitz as well, could you please help?

**Comment by aitboudad** [comment]
Duplicate of #3607
