### ISSUE TITLE
Model value update in Custom template

### ISSUE THREAD

**Issue by tomav123-git** [ngx-formly/ngx-formly#3607]
⭐️⭐️⭐️⭐️⭐️

**Description**
I'm trying to update the model value in one of my custom-template. It is doable in v5, but in v6 getting some error like model is a read only property.
https://github.com/ngx-formly/ngx-formly/issues/975#issuecomment-394647380 this is what exactly i'm trying to do.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-wwudsq?file=src/app/formly-field-input.ts

**Your Environment**

- Angular version: 14
- Formly version: 6

**Additional context**

**Comment by aitboudad** [comment]
can you try with `this.formControl.setValue('sdssd')`

**Comment by tomav123-git** [comment]
@aitboudad i tried it, but it is not updating the model object

**Comment by aitboudad** [comment]
Make sure `email` is defined in `fields`:

```
fields = [
   ...,
   { key: 'email' },
]
```

Then to update the model value of email try with:
- Update field outside of current type: `this.form.get('email').setValue('sdssd')` 
- Field of  the current type: `this.formControl.setValue('sdssd')`

**Comment by tomav123-git** [comment]
@aitboudad Field is present in form and if we check the form field value, selected value is there. But when we pass the model it is not present

**Comment by aitboudad** [comment]
A reproduction is needed for further check on our side :pray:!

**Comment by tomav123-git** [comment]
Can you check this https://stackblitz.com/edit/ngx-formly-ui-bootstrap-wwudsq?file=src/app/formly-field-input.ts
Build is failing because of this issue

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-24dtwb?file=src/app/formly-field-input.ts

**Comment by tomav123-git** [comment]
@aitboudad so we cant use the old method of updating model, isn't it?

**Comment by aitboudad** [comment]
still possible but not recommended, do you have a real use-case where the proposed solution is not suitable?

**Comment by tomav123-git** [comment]
@aitboudad thanks for the help. I will create my scenario in stackblitz and share it here

**Comment by aitboudad** [comment]
Please feel free to leave a comment once you've a got a stackblitz example.

Thank you!

**Comment by FritzHerbers** [comment]
The proposed solution generates an error:

```
ERROR Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: 
  Expression has changed after it was checked. Previous value: '{}'. Current value: '{
  "email": "sdssd"
}'
```

As it runs during an Angular Cycle, you might need the following, so that it is run at the next cycle outside of Angular:

```
   setTimeout(() =>  this.form.get('email').setValue('sdssd'));
```
