### ISSUE TITLE
JSON  Schema does not seem to work in Angular 15 standalone

### ISSUE THREAD

**Issue by argupta23** [ngx-formly/ngx-formly#3609]
@aitboudad 
I am trying to migrate to Angular 15 and JSON Schema based approach using Standalone component.

For some reason I am not able to get the thing to work.

Please find attached a stackblitz that captures some of the options I have tried.

[https://stackblitz.com/edit/ngx-formly-ui-bootstrap-zgsvws?file=src/app/dialog/dialog.component.ts](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-zgsvws?file=src/app/dialog/dialog.component.ts)

It is possible that I might be doing something wrong here.

Can I please request your help in looking into the issue?

thanks

I created a simpler version of the above with just the JSON example that is available at this link

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-wx6mdy?file=src/app/app.component.ts

What is interesting is that if you open the first version of the stackblitz and input a character into any of the inputs within the first visible form, the JSON schema form shows up.

**Comment by argupta23** [comment]
just as a side note your JSON Schema example at the following link

https://formly.dev/docs/examples/advanced/json-schema

does not work when opened in stackblitz

**Comment by HaidarZ** [comment]
Try to change anything in the app.component.ts and save, just happened to me.

**Comment by argupta23** [comment]
@HaidarZ,

Thanks for taking a look at the issue.
Are you suggesting that you are seeing the same behavior or how does your comment help resolve the issue?

**Comment by aitboudad** [comment]
standalone support will be added in the next major version, in the meantime you can use the following solution https://github.com/ngx-formly/ngx-formly/issues/3721#issuecomment-1602401526
