### ISSUE TITLE
Validation rules from database

### ISSUE THREAD

**Issue by martinberit** [ngx-formly/ngx-formly#3611]
Hi there,

We would like to maintain Formly validators in a database. We assume that a validator can be represented by a name, a regular expression and an error-message in a number of table rows. A field in the FormlyFieldConfig should point to these names.

How should we implement this, i.e. how do we ensure that our http-request to the database is done and ready before the Formly-model is being build.  Or - would you suggest that we post-process the Formly model after its loaded?
BR from Copenhagen

**Comment by drorm** [comment]
I'm doing a version of this, and I just load the validation data when the page first loads, so that by the time formly is created, all the validation data is already there. It's a bit expensive on startup, but makes sense in my mind for a single page app.

**Comment by aitboudad** [comment]
The implementation depend on the backend side which out of our scope, we've some examples that show how to load JSON form that you may check:

- https://formly.dev/docs/examples/other/json-powered
- https://formly.dev/docs/examples/advanced/json-schema/
