### ISSUE TITLE
How can I set the selected value in select field?

### ISSUE THREAD

**Issue by winsonet** [ngx-formly/ngx-formly#3615]
I am using material ui for build the form, but I don't know how can I set the default selected value with the dropdown select field.

for example, I need to edit a existing record so it also need to show the selected item before

please find the below example codes:
```
public form = new FormGroup({});
public model = {};
public fields: FormlyFieldConfig[] = [];

......

//set the fields in other separate function
public loadFormFields() {
...
 {
      key: 'parentId',
      type: 'select',
      props: {
        label: 'Select',
        placeholder: 'Select Parent',
        required: true,
        options: [
          { label: 'Parent 1', value: '1' },
          { label: 'Parent 2', value: '2' },
          { label: 'Parent 3', value: '3' },
        ],
      },
    },
}
...
}
```
I tried below after call `loadFormfields()`
```
this.form['parentId'].templateOptions.options = data.objectselected;
```
but it will show below error
```
Property 'parentId' does not exist on type 'FormGroup<{}>'. Did you mean 'parent'?
```

Thanks!

**Comment by ottomillrath** [comment]
You can set the value of 'parentId' in the model object
`public model = { parentId: '1' };`

**Comment by aitboudad** [comment]
> You can set the value of 'parentId' in the model object 
> public model = { parentId: '1' };

Or use `defaultValue`:

```patch
 {
      key: 'parentId',
      type: 'select',
+     defaultValue: 1,
}
```

**Comment by winsonet** [comment]
thanks for your reply,  actually, my final solution is to use the `ng-select` for custom field type, and set the default value to `ngModel` in `ng-select` component
