### ISSUE TITLE
Classname has no effect on FormlyFieldType using formly 6 and material 15

### ISSUE THREAD

**Issue by christophglass** [ngx-formly/ngx-formly#3616]
**Description**
Classname has no effect on FormlyFieldType using Angular Material 15

**Expected behaviour**
`<mat-slide-toggle class="mat-mdc-slide-toggle mat-accent ng-pristine ng-valid ng-touched slider-full-width-before"...></mat-slide-toggle>`

**Actual behaviour**
`<mat-slide-toggle class="mat-mdc-slide-toggle mat-accent ng-pristine ng-valid ng-touched "...></mat-slide-toggle>`

**Minimal Reproduction**
```
 {
    key: 'decision',
    type: 'toggle',            
    className: 'slider-full-width-before',
    wrappers: ['form-field', 'togglewrapper'],
    props: {
      labelPosition: 'before',
      label: 'yes or no',
      description: 'make a decision please',
    },
  }
```

Classname doesnt show up in DOM. If I add class in Chrome devtools it works.

**Your Environment**

- Angular version: 15.2.0
- Formly version: 6.1.1
- Material: 15.2.0

**Additional context**
Class 'slider-full-width-before' comes from custom material theme.
Yes I even put a custom wrapper around it hoping I could add the missing class somehow after view init.

**Comment by christophglass** [comment]
**Workaround using wrapper**

```
import { AfterViewInit, Component, ViewChild, ViewContainerRef } from '@angular/core';
import { FieldWrapper } from '@ngx-formly/core';

@Component({
  selector: 'ng-online-calculator-ui-toggle-wrapper',
  templateUrl: './toggle-wrapper.component.html',
  styleUrls: ['./toggle-wrapper.component.css']
})
export class ToggleWrapperComponent extends FieldWrapper implements AfterViewInit {  
  @ViewChild('fieldComponent', { read: ViewContainerRef }) declare fieldComponent: ViewContainerRef;

  ngAfterViewInit(): void {    
    document.getElementById(this.fieldComponent.element.nativeElement.previousElementSibling.firstChild.id)?.classList.add('slider-full-width-before');        
  }
}

```

Dont know if this is a good "solution" but it works at least...

**Comment by aitboudad** [comment]
The `className` is added to `formly-fieled` element which is located at the root of `toggle` field type, to update the style of `mat-slide-toggle` element just use the following selector:

```css
.slider-full-width-before .mat-mdc-slide-toggle {
  ...
}
```
