### ISSUE TITLE
Extension - API Calls via Extensions and Angular Interceptor 

### ISSUE THREAD

**Issue by thanecoder** [ngx-formly/ngx-formly#3623]
**How to make API Calls from within the Extension function such that Angular interceptor intercepts the API calls ?**

So basically I have created an extension in order to make a API call to populate my Select and Autocomplete dropdowns. I have currently used the window.fetch approach. But it causes problems as I am not able to intercept such requests via Angular interceptor and alter the request in order to add headers to these requests.
 
Is it possible to pass a Service instance or HttpClient instance to my FormlyExtension functions or if there is an alternative approach could you please suggest if possible.

**Comment by kenisteward** [comment]
Is there a reason why you are using an extension instead of just trying an
observable directly to the select options? Formly supports this natively.

Also if you are using a custom component instead of the built in once you
can just inherit the formly select implementation to get this.
