### ISSUE TITLE
Is it possible to render questions between another question answer options?

### ISSUE THREAD

**Issue by GreedyA1** [ngx-formly/ngx-formly#3626]
**Is it possible to render questions between another question answer options?**

I want to use expressions to renderer additional question when specific option is selected in the main question.

for example I have question 

    how do you feel? 
          * good
          * very good
          * bad 
          * very bad
      

when clicking option very good
==========================

    how do you feel? 
         * good
         * very good
      
                are you sure? (new question) <-------------------------
                      * yes
                      * no
      
         * bad 
         * very bad

I know I can achieve this:

    how do you feel? 
         * good
         * very good
         * bad 
         * very bad
         
    are you sure? (new question) <-------------------------
          * yes
          * no

**Comment by aitboudad** [comment]
I'd suggest to create a custom type that's the better option I think, also you may check this solution (not sure if its related to your needs or not) https://stackoverflow.com/a/59844495/1406096.
