### ISSUE TITLE
[Expression "props.disabled"] Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by davidoween** [ngx-formly/ngx-formly#3631]
**Description**

'props.disabled': 'model.user' --> fails when expression no return boolean 
'props.disabled': '!!model.user' --> it is works

**Minimal Reproduction**

https://stackblitz.com/edit/angular-qyt5vt?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

**Your Environment**

- Angular version: 13
- Formly version: 6.1.3

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.4](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.4) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
