### ISSUE TITLE
Upgrading from angular 12 to 15 broke all the custom fields in my project

### ISSUE THREAD

**Issue by sranjan-m** [ngx-formly/ngx-formly#3632]
**Description**
Upgraded angular from 12 to 15. And it broke custom controls as mentioned below.

Custom field config code :
```
export interface CustomFieldConfig extends FormlyFieldConfig {
  dbConfig?: any;
}
```

In custom control component :

```
export class CustomFieldType extends FieldType implements OnInit {
  customFieldConfig: CustomFieldConfig;

  ngOnInit(): void {
    this.customFieldConfig = this.field;
  }
}
```
The above code was working perfectly fine in angular v12 and formly v5.

But after the upgrade, getting error `Type 'FormlyFieldConfig<FormlyFieldProps & { [additionalProperties: string]: any; }>' is not assignable to type 'CustomFieldConfig'` at line `this.customFieldConfig = this.field;`

**Your Environment**

- Angular version: 15.0.4
- Formly version: 6.0.0

Could be  just a simple type assignment issue, but it has already taken a lot of my time and not getting any workaround yet.
Please HELP!!!

**Comment by sranjan-m** [comment]
**Update :**

My `CustomFieldConfig` also overrides properties like `fieldGroup` & `fieldArray`.
```
export interface CustomFieldConfig extends FormlyFieldConfig {
  dbConfig?: any;
  fieldGroup?: CustomFieldConfig[];
  fieldArray?: CustomFieldConfig;
}
```

While troubleshooting, I found  `fieldArray?: CustomFieldConfig;` is the one creating the problem. If I remove this overriding property from `CustomFieldConfig` interface, there's no compilation error, not sure about any runtime error though.

Need help about how to override `fieldArray` in my `CustomFieldConfig`

**Comment by kenisteward** [comment]
![Screenshot_20230316-165250.png](https://user-images.githubusercontent.com/12831669/225760715-8cad9097-b9ec-4bcc-a14a-458ba71365df.png)

In the documentation for updating it points to the fact that fieldarray is now a function that returns a fieldconfig instead. If you override yours to that it should be fine.

**Comment by sranjan-m** [comment]
Thanks @kenisteward for your response.
BTW, I had already figured out what am I missing in my overridden property and fixed it. Just came here to close the issue & noticed your reply.

Thanks!
