### ISSUE TITLE
Unbale to access fieldGroup from fieldConfig.fieldArray after upgrading to formly v6

### ISSUE THREAD

**Issue by sranjan-m** [ngx-formly/ngx-formly#3633]
Solution using the array component itself. only downfall doing this is it is specifically programmed to an array of objects only.
https://stackblitz.com/edit/angular-ivy-vxvawr?file=src%2Fapp%2Fcustom-table%2Fcustom-table.type.ts

_Originally posted by @kenisteward in https://github.com/ngx-formly/ngx-formly/issues/2988#issuecomment-926040055_

After upgrading to formly v6, it fails at `<th *ngFor="let tHead of fieldConfig.fieldArray.fieldGroup">`

Unable to access the `fieldGroup` anymore. How to get the `fieldGroup` from `fieldConfig.fieldArray` with the new implementation?

**Comment by robbertvanhoveAtT4T** [comment]
It seems the 'fieldArray' property has changed to a function when I inspected the 'field' object. 
Also this is the new type definition: 
```typescript
    fieldArray?: FormlyFieldConfig | ((field: FormlyFieldConfig) => FormlyFieldConfig);
```
 When further examining I made it work by doing the following:
```
 fieldArray?: FormlyFieldConfig;

  ngOnInit() {
    if (typeof this.field.fieldArray === 'function') {
      this.fieldArray = this.field.fieldArray(this.field);
    } else {
      this.fieldArray = this.field.fieldArray;
    }
  }
```
And in the template replacing it by the following: 
```
<th *ngFor="let headerField of fieldArray.fieldGroup">
```
