### ISSUE TITLE
register types in stand alone components

### ISSUE THREAD

**Issue by its-dibo** [ngx-formly/ngx-formly#3636]
how to register a new type when FormlyModule is used inside a stand alone component

**Comment by aitboudad** [comment]
You can pass the component directly through `type` property without the need to declare it:

```ts
    {
      key: 'text',
      type: CustomComponent,
      props: {
      },
    },
```

**Comment by its-dibo** [comment]
great, but this solution introduces another small issue.

storing the form object in a database is a bit harder. at least it is required to transform the object each time to replace the 'file' type with `fileComponent`
