### ISSUE TITLE
app.module.ts not updated as expected when installing formly

### ISSUE THREAD

**Issue by monsoma** [ngx-formly/ngx-formly#3638]
**Description**
https://formly.dev/docs/guide/getting-started says, executing

    ng add @ngx-formly/schematics --ui-theme=bootstrap
	
would change app.module.ts and automatically import FormlyModule. But it didn't change the file at all. I must did it by hand. And this is the output:

	PS D:\Shared\code\javascript\ang1> ng add @ngx-formly/schematics --ui-theme=bootstrap
	ℹ Using package manager: npm
	✔ Found compatible package version: @ngx-formly/schematics@6.1.3.
	✔ Package information loaded.

	The package @ngx-formly/schematics@6.1.3 will be installed and executed.
	Would you like to proceed? Yes
	✔ Packages successfully installed.
	UPDATE package.json (1254 bytes)
	✔ Packages installed successfully.

Either the generator is broken or the guide.

**Minimal Reproduction**

Follow https://formly.dev/docs/guide/getting-started on a new Angular app.

**Your Environment**

- Angular version: 15.2.4
- Formly version: 6.1.3
- Windows 11

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.5) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
