### ISSUE TITLE
Add description prop support for Ng-Zorro-Antd UI

### ISSUE THREAD

**Issue by jusvit** [ngx-formly/ngx-formly#3639]
Could we please add description prop support for NG-Zorro controls?

Similar to other UI components (such as Bootstrap as shown below):
![image](https://user-images.githubusercontent.com/4002351/227558852-3a4e39c3-46d9-4450-8865-35c7337b1b2a.png)

It would quite helpful for NG-Zorro to support the 'description' prop, as it currently stands, it only accepts 'label' as shown here:
![image](https://user-images.githubusercontent.com/4002351/227559164-491024a5-4df0-428b-8845-8366a01f9ba2.png)

Ng-Zorro-Antd form controls support extra information via nzExtra:
![image](https://user-images.githubusercontent.com/4002351/227560128-9e69beed-3d25-4ee2-92af-71a352c57590.png)
and the code:
![image](https://user-images.githubusercontent.com/4002351/227560271-a1b22553-3c62-4fbc-bd72-7de142806021.png)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.2.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.2.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by zzhimin** [comment]
you can also use this library：https://github.com/zzhimin/ngx-ng-zorro-formly
