### ISSUE TITLE
How to validate a fieldGroup without exporting a function

### ISSUE THREAD

**Issue by ArxClaeyAi** [ngx-formly/ngx-formly#3640]
**How to validate a fieldGroup without exporting a function**

In one of my forms I need to check if 2 fields are identical, currently I do this by using an async validator on the 2nd field but I would like to be able to perform this validation on the fieldGroup so I do not need to call the model or the form from the validator function.

I've seen in the code examples of doing this by referencing the name of an exported validator in the config but I'd like to keep my validator in the same file as my form. I've experimented some but nothing seems to work for me.

Here is the current situation in case this helps:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-fxciyp?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-6ycx9a?file=src%2Fapp%2Fapp.component.ts
