### ISSUE TITLE
The required property does not work with arrays in JSONSchema

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3641]
**Description**
An array subfield is not required anymore when a new item is added.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-uhe3ok?file=src%2Fapp%2Fapp.component.ts

When the page is loaded a star is present on "name". Try to remove the item from the names (minus button) and add again a new item. Now the star is not present anymore on "name".

Note that "Names" should also have a star as the field "Simple".

I tried to reproduce the problem using the version 6 but the stackblitz example provided by the documentation does not work:
https://formly.dev/docs/examples/advanced/json-schema

**Your Environment**

- Angular version: 7.2.16
- Formly version: 5.12.7

**Comment by aitboudad** [comment]
FYI its working as expected in `v6`: https://stackblitz.com/edit/angular-elcjdx

**Comment by jma** [comment]
> FYI its working as expected in `v6`: https://stackblitz.com/edit/angular-elcjdx

Any chance to be fixed on the v5? Thanks.

**Comment by aitboudad** [comment]
I may see if it can be fixed.

**Comment by jma** [comment]
Thanks

**Comment by aitboudad** [comment]
Close since if fixed in `v6`, I recommend upgrading whenever possible :pray:!
