### ISSUE TITLE
Bump ngx formly ionic to ionic 7

### ISSUE THREAD

**Issue by maxcodefaster** [ngx-formly/ngx-formly#3643]

**Comment by bohndthi** [comment]
👍

**Comment by aitboudad** [comment]
PR welcomed!

**Comment by meherhendi** [comment]
It seems that we're unable to upgrade the dependency "@ionic/angular" to version "^7.0.0" due to a **conflicting peer dependency requirement**.

This version of "**@ionic/angular@^7.0.0**" requires **@angular/core@">=14.0.0"**. However, our current Angular version is **"@angular/common" at "^13.3.11"**.

@aitboudad  mentioned in #3675  is no immediate need to upgrade the Angular version, and we probably will have to do that

**Comment by prajput1994** [comment]
@aitboudad  ionic v6 will support till Mar 29, 2024, before that we need to upgrade the version but formly don't support ionic 7, I am getting **"conflicting peer dependency"** 
Can you please let me know when are you planning to update the ionic version. 
Let me know , If you are not planning to update the ionic version then we need to go with some alternative.

**Comment by aitboudad** [comment]
@prajput1994 its on our plan, will make sure to make a new update within 2 up to 3 months from now.

**Comment by serkaneken** [comment]
> @prajput1994 its on our plan, will make sure to make a new update within 2 up to 3 months from now.

Great news, we will be excited to upgrade our application.

**Comment by aitboudad** [comment]
Time flies :), will try to work on it this weekend.

**Comment by prajput1994** [comment]
@aitboudad  still in peer dependency I am getting the old version of ionic 
   "node_modules/@ngx-formly/ionic": {
      "version": "6.2.2",
      "resolved": "https://registry.npmjs.org/@ngx-formly/ionic/-/ionic-6.2.2.tgz",
      "integrity": "sha512-fNrPW5m2XEhcZ7oM3kEZ7p0HM59rOE6wtE5ksosOX7TIabR5zN8M2NbVSEFjcQWN9/hNBobhWKjXWVSxjk6kPA==",
      "dependencies": {
        "tslib": "^2.0.0"
      },
      "peerDependencies": {
        "@ionic/angular": "^6.0.0",
        "@ngx-formly/core": "6.2.2"
      }
    },

**Comment by bohndthi** [comment]
@prajput1994, the changes have not yet been incorporated into a new version - we will probably have to wait for version 6.2.3.

**Comment by prajput1994** [comment]
@aitboudad is there any plan to release new version ?

**Comment by aitboudad** [comment]
> @aitboudad is there any plan to release new version ?

yes, remain some issues to fix and I'll publish a new release probably at the end of this week.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by DeviSriPrasad9999** [comment]
Can you provide the installation steps for installing the latest version. It seems that the same error still persists.


npm install @angular/forms @ngx-formly/core@6 @ngx-formly/ionic --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @angular/core@17.0.4
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"17.0.4" from @angular/common@17.0.4
npm ERR!   node_modules/@angular/common
npm ERR!     peer @angular/common@"17.0.4" from @angular/service-worker@17.0.4
npm ERR!     node_modules/@angular/service-worker
npm ERR!       @angular/service-worker@"^17.0.4" from the root project
npm ERR!   peer @angular/core@"17.0.4" from @angular/service-worker@17.0.4
npm ERR!   node_modules/@angular/service-worker
npm ERR!     @angular/service-worker@"^17.0.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @angular/forms@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@17.1.1
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"17.1.1" from @angular/forms@17.1.1
npm ERR!   node_modules/@angular/forms
npm ERR!     @angular/forms@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!

Formly doesnt have support for angular v17 ?? Or what?

**Comment by aitboudad** [comment]
@DeviSriPrasad9999 normally it should work, try to install with `force` option :  `npm install ...  --force`. if it doesn't work please create a separate ticket so we can further check.
