### ISSUE TITLE
How to implement formly-validation-message in a custom type with two form controls

### ISSUE THREAD

**Issue by atgillette** [ngx-formly/ngx-formly#3645]
**Question**

I want to create a custom type that uses a template for specific layout requirements. Our implementation is similar to this example, [example](https://stackblitz.com/edit/angular-ivy-rabcxg?file=src%2Fapp%2Fcustom.component.ts)  

But I also want to use formly-validation-message in the template. How can I configure formly-validation-message to target the error messages for a specific control?

**Comment by aitboudad** [comment]
To control the validation layout globally just override `form-field` wrapper https://formly.dev/docs/examples/bootstrap-specific/bootstrap-horizontal

But if you want to use it for `FormlyFieldCustomInput` only ensure to not use the default  'form-field' wrapper:
```patch
      types: [
        {
          name: 'custom',
          component: FormlyFieldCustomInput,
-         wrappers: ['form-field'],
+         wrappers: [],
          defaultOptions: {
            fieldGroup: [
              { type: 'input', key: 'name' },
              { type: 'input', key: 'profession' },
            ],
          },
        },
      ],
```
