### ISSUE TITLE
Hidden select option

### ISSUE THREAD

**Issue by snekku-dev** [ngx-formly/ngx-formly#3647]
**Is your feature request related to a problem? Please describe.**
In my application I have a scenario where a select form control has a null default value that should not be selectable by the user and also not visible among the options, but it should act as a placeholder until the user picks a value

**Describe the solution you'd like**
My proposed solution would be to add a "hidden" prop in the select option interface to enable the "hidden" attribute of the option element. I think this should apply to the placeholder too so a "hidePlaceholder" prop should set the hidden attribute to the placeholder option (having the disable attribute on the placeholder would be nice too) so that it won't be visible among the available options

```
// select field props

placeholder: 'I am the placeholder',
hidePlaceholder: true // this won't show the placeholder among the options,
disablePlaceholder: true // with the previous prop set to false, this would prevent the placeholder to be selected although visible as an option
placeholderValue : null // this overrides the placeholder ngValue to null instead of undefined,
options: [{
     label: 'alternative placeholder',
     value: null,
     hidden: true, // still needed as an enchancement
     disabled: true
}]

```

**Describe alternatives you've considered**
As seen in the snippet an alternate way to have a hidden placeholder that works on the "null' value instead of 'undefined' would be to just have the hidden prop for each option along side the disabled one

**Comment by aitboudad** [comment]
I think that a specific use-case which is not something that we're willing to support instead I would suggest to use a custom type.
