### ISSUE TITLE
Custom Step in a mat-stepper

### ISSUE THREAD

**Issue by CDohertyPayescape** [ngx-formly/ngx-formly#3648]
I have encountered an issue when implementing a custom type in the mat-stepper.

It would appear that when the custom type contains a child component hidden by a condition, the child component will not get initialised after the condition has been resolved.

There was no issue with this when previously using 5.12.5 for formly/core and formly/material.

https://stackblitz.com/edit/angular-dkhpnm?file=src/app/app.module.ts

Any guidance on what is going wrong would be greatly appreciated.

**Comment by aitboudad** [comment]
I think its related to onpush change detection, some solutions that you may consider:

1. rely on observable:

```html
<div *ngIf="isFetching$|async">
  <a>Hello Again!</a>
</div>
```

2. rely on field `props`:

```html
<div *ngIf="!props.isFetching">
  <a>Hello Again!</a>
</div>
```

3. use `options.detectChanges`:

```patch
      .subscribe(() => {
        this.isFetching = false;
+       this.options.detectChanges(this.field);
      })
```

4. use `ChangeDetectorRef`:

```patch
      .subscribe(() => {
        this.isFetching = false;
+       this.cdRef.detectChanges();
      })
```

**Comment by CDohertyPayescape** [comment]
Awesome, using the ChangeDetectorRef fixed the issue. Thanks!
