### ISSUE TITLE
Formly datepicker doesn't update the model with selected date from popup when modeloptions is updateon 'blur'

### ISSUE THREAD

**Issue by pavitsrivatsan** [ngx-formly/ngx-formly#3649]
In the datepicker component, we have the options to update model on modeloptions. 
If we choose 'blur' as updateOn modeloptions, the model gets updated with the date value that is entered on input field of the datepicker. 
It doesn't update the model when we select the date from the popup. 
It still retains the old value in the model. 
It updates the input field but it doesn't update the model.

REPRODUCTION:

https://stackblitz.com/...
https://stackblitz.com/edit/angular-vscjvn?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts

- Angular version: 15.1.5
- Formly version: 6.0.0

This issue occurs with integrating primeng calendar too

**Comment by aitboudad** [comment]
seem working/fixed I think https://stackblitz.com/edit/angular-qeeh3y
