### ISSUE TITLE
How to override schema type validation?

### ISSUE THREAD

**Issue by artemxponomarenko** [ngx-formly/ngx-formly#3650]
I have following JSON schema configuration 

```
"dateOfBirth": {
    "type": "string",
    "format": "date",
    "title": "Date of Birth",
    "x-widget": {
      "formlyConfig": {
        "type": "datepicker",
        "props": {
          "appearance": "outline"
        }
      }
    }
  }
```
which triggers type error 
```
{
    "type": {
        "schemaType": [
            "string"
        ]
    }
}
```
when new value is selected.

<img width="484" alt="Screenshot 2023-04-19 at 12 53 28" src="https://user-images.githubusercontent.com/106668892/233038668-ed56dff9-c3c3-42ef-bcf1-9ff866a6395a.png">

I would be grateful if anyone can help me to solve this problem.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
