### ISSUE TITLE
Disabled buttons in repeat section mark my form as pristine

### ISSUE THREAD

**Issue by MathieuGi** [ngx-formly/ngx-formly#3654]
**Question**

Hello ! 

I re-open this issue because the last answer didn't solve the problem but the ticket has been closed.
If it's possible to re-open this ticket : [https://github.com/ngx-formly/ngx-formly/issues/3653](https://github.com/ngx-formly/ngx-formly/issues/3653)

Thank you very much

**Comment by aitboudad** [comment]
I think that's the default behavior of changing the disabled state in Angular, you may try to update the disabled state manually which will give you more control of the form state:

```ts
this.formControl.disable(options)
```
