### ISSUE TITLE
Custom Material RangeDatepicker type TESTING

### ISSUE THREAD

**Issue by valdezcervera** [ngx-formly/ngx-formly#3655]
# Hi everyone
I am currently working on implementing a custon formly type to be able to have  material daterange-picker available in my project.
The implementation was quite straight foreward and its done with very basic features. My problem is that Im having a lot of trouble trying to test my type.componet. So far I have been able to follow how other fieldcomponents are tested in your repo (I am looking at input.type as an example) to test my component, but so far all I can manage to do is to test if the fixture.componentInstance is truthy.
I would like to test the components behaviour, not the view, but the component methods.
How can I access getters in a custom type.component for testing?

This is what I have been able to do so far (not much).

```
const datePickerOpen = new BehaviorSubject(false);

const renderComponent = (field: FormlyFieldConfig) =>
  createFieldComponent(field, {
    imports: [
      FormlyModule.forRoot({
        types: [
          {
            name: "date-picker",
            component: DatepickerTypeComponent,
          },
        ],
      }),
    ],
  });

const { fixture, detectChanges, field, query } = renderComponent({
  key: "date",
  type: "date-picker",
  props: { isOpen: datePickerOpen },
});

describe("Formly Type Component", () => {
  it("should create", () => {
    expect(fixture.componentInstance).toBeTruthy();
  });
});
```

Hope you can give me some guidance.
Thank you in advance!

**Comment by aitboudad** [comment]
You can use query:

```
const datepicker = query('date-picker-component').componentInstance as DatepickerTypeComponent;
```
