### ISSUE TITLE
disabled prop not working without key

### ISSUE THREAD

**Issue by venkateshwarans** [ngx-formly/ngx-formly#3657]
**Question**

`disabled` prop is not working if we don't provide a `key` in the field config. 
What was the idea behind it? 

[Here you can reproduce](https://stackblitz.com/edit/angular-bcgz5f)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.4](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.4) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
