### ISSUE TITLE
bootstrap `form-field` wrapper styling changed in v6 and uses `!important`

### ISSUE THREAD

**Issue by gkamperis** [ngx-formly/ngx-formly#3658]
v6 changes the applied css class

from `form-group`

https://github.com/ngx-formly/ngx-formly/blob/6a546d5c704293c1fb9f6eeab7584c0cec1c0b68/src/bootstrap/src/lib/wrappers/form-field.wrapper.ts#L7

to `mb-3`

https://github.com/ngx-formly/ngx-formly/blob/9b28fc0739a46a549513b3c5d828066ccbecc6d8/src/ui/bootstrap/form-field/src/form-field.wrapper.ts#L20

There are many issues with this: 
* It is a breaking change that is not described anywhere
* no migration steps provided
* `mb-3` uses `!important` and in order to override it we need to also override with `!important` which is a bad practice.

Ideally define a custom css class that allows us to more naturally override the attributes

**Your Environment**

- Formly version: 6.1.3

**Comment by Logic-Bits** [comment]
here wondering that too! this doesnt look very uniform
