### ISSUE TITLE
v6 `select` outside `formly-field-select`

### ISSUE THREAD

**Issue by gkamperis** [ngx-formly/ngx-formly#3659]
**Description**
`select` element is outside `formly-field-select`

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

![image](https://user-images.githubusercontent.com/18055519/234091004-30c90a6b-7efd-4f07-a2ec-d24c260a2bd0.png)

**Comment by aitboudad** [comment]
That's expected behavior, rely on `formly-wrapper-form-field` selector instead (mentioned in https://formly.dev/docs/guide/migration/#ngx-formlybootstrap)

**Comment by gkamperis** [comment]
@aitboudad not sure how the bootstrap changes are related to the fact the the element with v5 was inside the wrapper and now it is not.

At some point I spotted some config that controlled how this rendering is done and the default was for it to be inside - which is not what we see above.

Can you pls be more clear on how I can use a std bootstrap select with the `select` element inside the wrapper?

**Comment by aitboudad** [comment]
The change was made in order to support floating labels (https://github.com/ngx-formly/ngx-formly/pull/3304).

Could you please elaborate about your needs? so we can provide an alternative way or add support of old option.

**Comment by gkamperis** [comment]
@aitboudad as mentioned the requirement would be to support the v5 rendering.

looking at bootstrap floating labels I do not see how rendering inside the wrapper should stop the functionality.

also cannot seem to find that config that controls the rendering behavior... can you confirm if that exists? or maybe it was for something else and I misunderstood...

**Comment by aitboudad** [comment]
> looking at bootstrap floating labels I do not see how rendering inside the wrapper should stop the functionality.

In order for Bootstrap to work properly we should not have an extra `tag` between label and input element:

Before:
```html
	<label>...</label>
	<formly-field-input>
       <input>
	</formly-field-input>
```

After:
```html
	<label>...</label>
    <input>
```
