### ISSUE TITLE
Setting the model of a hidden field using expressions throws error

### ISSUE THREAD

**Issue by dwsesan** [ngx-formly/ngx-formly#3664]
It is possible to set a field's value using `"expressions": { "model.fieldKey": "value" }`. If this field is hidden, there are no errors. But if this field is nested and it's parent field is hidden, formly throws a `target is undefined` error for the expression. 

Please let me know if I'm doing something wrong and this is expected.

https://stackblitz.com/edit/ngx-formly-ui-material-c7uyfk?file=src%2Fapp%2Fapp.component.ts

**Comment by aitboudad** [comment]
I think its a bug, we'll try to provide a fix in the next release.

**Comment by sesan07** [comment]
Thanks for looking into it!

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.5) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by dwsesan** [comment]
The issue has been resolved with the update, thanks!
