### ISSUE TITLE
Material prefix and suffix error

### ISSUE THREAD

**Issue by ngagua** [ngx-formly/ngx-formly#3668]
textPrefix and textSuffix is throwing the error.
Formly : 6.1.3
Angular Material: 15.1.2;

```
 fields: FormlyFieldConfig[] = [
    {
      key: 'key1',
      type: 'input',
      props: {
        textPrefix: 'testPrefix',
        appearance: 'outline',
      },
      wrappers: ['form-field'],
    },
  ];
```
![image](https://user-images.githubusercontent.com/75014232/235616966-76d27e13-360a-4244-b53e-33679129e558.png)

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-49rodg?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
textPrefix should be a templateRef instance and not plain text, please check one of the following example to have an idea of how to pass a valid type:

1. https://formly.dev/docs/examples/other/material-formfield-hint-align/
2. https://formly.dev/docs/examples/other/material-prefix-suffix/
