### ISSUE TITLE
Number input decimal comma instead of point

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3672]
**Question**
We are working on localization together with formly forms.
Is there any possibility for 'number' (numeric) input fields, to use the locale for number formatting (such as decimal comma instead of decimal point).
For example, in nl-NL we have the following number using the local number format pipe
// in component.ts
value = 134.334
// component.html
{{ value | number }}
// shown in the browser
134,334
which is ok.
We want the same thing, but in a formly field, numeric input:
when the model.value is 134.334 to have in the input-box : 
![image](https://user-images.githubusercontent.com/42749923/236211749-0aea8407-ffb3-4473-ac99-d3a80bed885d.png)
but, in a number type input.

**Comment by aitboudad** [comment]
Use custom type https://formly.dev/docs/guide/custom-formly-field instead.

**Comment by aitboudad** [comment]
Another solution is to use `parsers`:
```ts
{
  key: 'text',
  type: 'input',
  parsers: [(value) => ...],
},
```
