### ISSUE TITLE
structure definition migration script.

### ISSUE THREAD

**Issue by GlauberF** [ngx-formly/ngx-formly#3673]
Do you have a script today so we can migrate the definition structure that will be discontinued in the future to the new definition form?
Because I'm here thinking about developing, where I pass the json javascript and replace the name among other details you need.

**Comment by aitboudad** [comment]
@GlauberF Do you means Angular semantics update (`ng update`) ?

**Comment by GlauberF** [comment]
exact, example until then we had for example.
```javascript
...
templateOptions: {
      ...
}
...
```

in a while the structure will only be
```javascript
...
props: {
      ...
}
...
```

This is an example, but the idea at first is to create a CLI, because in my case, for example, the definition of the structure, example mentioned above, is in a database, so `ng update` does not solve for my use case .
I understand that a CLI would help both those who have code locally and people like me who have it in a database.

**Comment by aitboudad** [comment]
We'll provide the migrations guide but for database, we cannot provide a migration script because it depends on you custom implementations.
I would suggest for your case to keep supporting both syntax, the legacy definition will be available through a custom extension in `v7`.

**Comment by aitboudad** [comment]
The old syntax is still allowed, the migrations guide will be provided in `v7`.
