### ISSUE TITLE
Pattern Restrict in Formly Field

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3679]
Is there a simple way, that using the pattern property in the .props field (or any other) to be able to restrict the input values in an 
input field, to a given Regex?
I mean, not only to generate a validation message, but not to permit for the user to enter any character that is not matching the given Regex.

**Comment by aitboudad** [comment]
use `parsers`:

```ts
{
  key: 'text',
  type: 'input',
  parsers: [(value) => 'ddd'],
},
```

**Comment by zoltanhalasz** [comment]
Thanks it works:
```
 parsers: [(value) => {
                if (value && !this.decimalRegex(this.decimalSeparator!, 15).test(value)) {
                  return value.substring(0, value.length - 1);
                }
                return value;
              }
```
