### ISSUE TITLE
Unable to access `model` from nested objects. We are using the `toFieldConfig` method and passing a Schema to it.

### ISSUE THREAD

**Issue by angshumanSarmah** [ngx-formly/ngx-formly#3681]
**Description**
We are using the `toFieldConfig` method and passing a Schema to it. For a requirement we need to use the `hide` or `hideExpression` for conditionally showing/hiding other fields. If the objects are at root level, the `hideExpression` works just fine, but from nested objects we are unable to access `model` and we receive a console error in such cases indicating that the model is undefined. PFA screenshot
<img width="981" alt="image" src="https://github.com/ngx-formly/ngx-formly/assets/45401385/4ada3f46-16b5-4b22-8f04-9a2be7fe11cf">

 
**Minimal Reproduction**

https://stackblitz.com/edit/formly-json-schema-ofdbor?file=src%2Fassets%2Fjson-schema%2FNot-working.json,src%2Fassets%2Fjson-schema%2FWorking.json

**Your Environment**

- Angular version: 13.3.12
- Formly version: 6.1.1
(the fiddler is on Angular version 7.2.16 and Formly 5.10.11)

**Additional context**
Schema structure that we are using for this:
`
{
  "schema": {
    "type": "object",
    "properties": {
      "hostFlag": {
        "type": "boolean",
        "default": false
      },
      "outerObj": {
        "properties": {
          "notes": {
            "widget": {
              "formlyConfig": {
                "type": "textarea",
                "hideExpression": "!model.hostFlag"
              }
            }
          }
        }
      }
    }
  }
}
`

**Comment by aitboudad** [comment]
When the `fieldGroup` has a key the getting model is the current field value. Please try with `parent` with: `!field.parent.model.hostFlag`

**Comment by angshumanSarmah** [comment]
Thanks @aitboudad for the response.

For anyone looking for something similar, need to append `parent` as many times as the nesting level.
For eg: if both the "control" and the "field to be controlled" are at different nested levels, we can access it like below:
```
{
  "schema": {
    "title": "Individual Nesting at both levels",
    "type": "object",
    "properties": {
      "flagObject": {
        "properties": {
          "hostFlag": {
            "title": "Flag",
            "type": "boolean",
            "default": false
          }
        }
      },
      "outerObj": {
        "properties": {
          "nestLevel1": {
            "properties": {
              "inputField": {
                "widget": {
                  "formlyConfig": {
                    "type": "textarea",
                    **"hideExpression": "!field.parent.parent.parent.model.flagObject.hostFlag",**
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```
