### ISSUE TITLE
Is ngx-formly support latest version of Ionic(v7.0.0)

### ISSUE THREAD

**Issue by serkaneken** [ngx-formly/ngx-formly#3682]
**Question**
Is ngx-formly support the latest version of Ionic(v7.0.0)?
- Ionic: https://stackblitz.com/edit/ngx-formly-ui-ionic 
It seems like that ngx-formly gives support till "@ionic/angular": "5.9.3",

**Comment by aitboudad** [comment]
Not supported yet, see #3643

**Comment by serkaneken** [comment]
Thank you for your quick answer, what should we do? Should we find a new alternative? Is the latest version 5.9.3 of ionic for usage?

**Comment by aitboudad** [comment]
https://github.com/ngx-formly/ngx-formly/issues/3643#issuecomment-1527434116
