### ISSUE TITLE
Name Attribute missing in Material Field

### ISSUE THREAD

**Issue by tomav123-git** [ngx-formly/ngx-formly#3684]
**Description**
I recently updated to v6 and found one issue in material. Actually name value is present in formly-field-object, but after rendering it is not present while inspecting.

**Minimal Reproduction**

https://angular-uqxfjt.stackblitz.io
This can be reproduced in material example also after adding name

**Your Environment**

- Angular version: 14
- Formly version: 6

**Additional context**

**Comment by tomav123-git** [comment]
@aitboudad could you please help?

**Comment by aitboudad** [comment]
I'll try provide a fix when time allows :pray:

**Comment by tomav123-git** [comment]
@aitboudad Thanks

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by tomav123-git** [comment]
@aitboudad Thank you so much, i will upgrade and let you know
