### ISSUE TITLE
Action in Custom stepper step.

### ISSUE THREAD

**Issue by ngagua** [ngx-formly/ngx-formly#3685]
Can we perform an action when a custom type component is rendered within a custom stepper step? I attempted to do this in the ngOnInit method, but the component is activated when the stepper is rendered. How can I modify my approach?

https://stackblitz.com/edit/angular-eeo4ub?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
In order to know if the field is rendered within a custom stepper step either pass a custom option to `props` or check the `parent`:

1- pass a custom option to `props`

```patch
{
  key: 'test',
  type: 'customInput',
  props: {
    label: 'test',
    required: true,
+ stepper: true,
  },
},

...
export class CustomInputComponent extends FieldType implements OnInit {
  ngOnInit() {
    if (this.props.stepper) {
      console.log('rendered in step');
    }
  }
}
```

2- check the `parent`:

```
export class CustomInputComponent extends FieldType implements OnInit {
  ngOnInit() {
    // Note: use while loop to check all ancestors
    if (this.field.parent.type === 'stepper') {
      console.log('rendered in step');
    }
  }
}
```
