### ISSUE TITLE
Hide expression clears defaultValue from model

### ISSUE THREAD

**Issue by dwsesan** [ngx-formly/ngx-formly#3686]
**Description**
When hide expression and defaultValue are configured for a field, the field's defaultValue isn't set in the model

``` javascript
{
  key: 'test',
  type: 'input',
  defaultValue: 'Hello!',
  props: {
    label: 'Testing',
  },
  expressions: {
    hide: '!model.test'
  }
}
```
In a field like above, the expectation is that `model.test` will be `Hello!`, therefore the field won't be hidden. It seems like defaultValue doesn't update the model before the hide expression is checked?

**Minimal Reproduction**

https://stackblitz.com/edit/angular-l2ae7y-lqvapj?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 14.2.2
- Formly version: 6.1.6

**Comment by aitboudad** [comment]
see https://formly.dev/docs/guide/migration#6-resetonhide-is-enabled-by-default
