### ISSUE TITLE
ShowError function in app.module

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3687]
When registering in extras the showError function, is there any way to
1. add multiple showError functions
2.  provide some parameters to the showError function
![image](https://github.com/ngx-formly/ngx-formly/assets/42749923/b26dc3e3-8d73-4e5c-bfad-865f7b21b5e4)

```
    FormlyModule.forRoot({
      extras: { showError },
```

**Comment by aitboudad** [comment]
> 1. add multiple showError functions

not clear

> 2. provide some parameters to the showError function

use `FORMLY_CONFIG` provider (https://github.com/ngx-formly/ngx-formly/issues/2551#issuecomment-714727118)
