### ISSUE TITLE
form-field wrapper stays focused after interacting with checkboxes

### ISSUE THREAD

**Issue by dc-p8** [ngx-formly/ngx-formly#3691]
As we all knows, mat-form-field isn't intended to be used with checkboxes. Formly supports this by implementing MatFormFieldControl in it's form-field wrapper, and I think this is a great thing because it adds uniformisation between fields.

But there is a bug when using mdc components : after interacting the checkbox, the form-field stays in it's "focused" state.

We can see it here : https://stackblitz.com/edit/ngx-formly-ui-material?file=src%2Fapp%2Fapp.component.ts where the outline gets the accent color even when bluring the input.

My current workaround is to remove the form-field wrapper in my formly root module : 
```typescript
      types: [
        // remove the "form-field" wrapper
        {
          name: 'checkbox',
          component: FormlyFieldCheckbox,
          wrappers: [],
        },
```

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
