### ISSUE TITLE
Manually trigger  modelChange event

### ISSUE THREAD

**Issue by ngagua** [ngx-formly/ngx-formly#3692]
Is it possible to manually trigger the "modelChange" event in a custom type component? I would like to add a new property to the model and then trigger the "modelChange" event. I do not want to set value with this.formControl.setValue(value)

` 
export class FormlyFieldInput extends FieldType {
  ngOnInit() {
      this.model.someproperty = true;
    //trigger modelChange
  }
}
`

https://stackblitz.com/edit/angular-lcvwuh?file=src/app/app.module.ts

**Comment by aitboudad** [comment]
Try this:

```ts
this.options.fieldChanges.next({ value: true, field: { key: 'someproperty' }, type: 'valueChanges' });
```

**Note**: We recommend to define a field and then set value with `this.form.get('someproperty').setValue`;
