### ISSUE TITLE
fieldArray not updating the form value

### ISSUE THREAD

**Issue by emeryao** [ngx-formly/ngx-formly#3693]
**Description**
fieldArray is omitted after invoking `options.resetModel`

**Minimal Reproduction**

* define a field config with a fieldArray which has a fieldGroup for the array
* render some data by invoking `options.resetModel(data)`
* the UI works fine and shows the fieldArray values
* but when getting the form value by `form.value` there is no value for the fieldArray

> may related with 1dd5c6e52a32553d615427cf340084f60923eb12 since it worked fine on `v6.1.4`

**Your Environment**

- Angular version: 16.0.2
- Formly version: 6.1.6

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, using the following `stackblitz` starter example:
https://stackblitz.com/edit/angular-vc6znj

Thanks!

**Comment by emeryao** [comment]
Thanks for your response
I have made a stackblitz demo for this issue please take a look
https://stackblitz.com/edit/ngx-formly-issue-3693

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.1.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.1.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by enricouniurb** [comment]
I'm getting the same issue with array also at the first loaded model. 

The array is present in the model.
The array is missing from the form.value.

ngx-formly version 6.3.5
angular version 14.3.0
