### ISSUE TITLE
How to set the material input attribute?

### ISSUE THREAD

**Issue by tangqianyu** [ngx-formly/ngx-formly#3702]
Formly : 6.0.0
Angular Material: 16.0.1

I want to use the second one input, but I don't know how to set it.
![image](https://github.com/ngx-formly/ngx-formly/assets/46307662/51b19789-d31a-4fd0-9e3a-f587977484b3)

**Comment by tangqianyu** [comment]
Add:  Is there a way to set global settings?

**Comment by aitboudad** [comment]
> Is there a way to set global settings?

https://material.angular.io/components/form-field/overview#form-field-appearance-variants

> for a specific field

```ts
{
  props: {
    appearance: 'outline'
  }
}
```

**Comment by tangqianyu** [comment]
> > Is there a way to set global settings?
> 
> https://material.angular.io/components/form-field/overview#form-field-appearance-variants
> 
> > for a specific field
> 
> ```ts
> {
>   props: {
>     appearance: 'outline'
>   }
> }
> ```

Thanks!
