### ISSUE TITLE
how to specify a select field config(with angular function ) into postgres db-side?

### ISSUE THREAD

**Issue by ReginaJongs** [ngx-formly/ngx-formly#3707]
I've make my script work well as follows, but I try to keep the FormlyFieldConfig[] into postgres a JSON field and failed...........

export class FormTestComponent {..............
fields: FormlyFieldConfig[] = [
    {
      "type": "tabs",
      "fieldGroup": [
        {
          "props": { "label": "First page" },
          "fieldGroup": [

            {
              key: 'sport1',
              type: 'select',
              props: {
                label: 'Sport',
                options:this.dropdownitem('sport1'), //it's a anfular function with paramater
                valueProp: 'id',
                labelProp: 'name',
              },
            },
            {
              "key": "sport2",
              "type": "select",
              "props": { 
                "label": "Sport2",
                options: this.dropdownitem("sport2"),
                "valueProp": "id",
                "labelProp": "name",
              }........................

  dropdownitem(codetype: string): Observable<any[]> {
    const url = "/api/dropdownitem"; const body = { codetype };//依據類型，取得代碼資料
    let options = {headers: new HttpHeaders({'content-type': 'application/json'})};
    //alert('dropdown from db, type:' + codetype); 
    return this.http.post<{ id: string, name: string}>(url, body, options).pipe(
      map(res => {
        const items = JSON.parse(JSON.stringify(res));
        alert(JSON.stringify(items));
        return items;
      }) //end of map
    );
  }

**Comment by aitboudad** [comment]
see https://formly.dev/docs/examples/other/json-powered
