### ISSUE TITLE
Library is breaking if I don't use ' 'unsafe-inline' in CSP

### ISSUE THREAD

**Issue by rishabh-jain389** [ngx-formly/ngx-formly#3708]
**Description**

**Minimal Reproduction**
Hi Team,

We are using ng-formly to build reactive forms for our customers. Recently we had Penetration testing for the security of the app and the security team found that we are using 'unsafe-eval' CSP which is unsafe for the security. If we remove 'unsafe-eval' then formly library logging error on the console.

**According to the security Team**, script-src 'unsafe-inline' - Inline JavaScript code, commonly used in XSS attacks, is
allowed.

**Remediation they have provided**
• We recommend redefining a more secure content security policy for the
application as part of a defense-in-depth strategy.
• Where possible, depreciate and remove all inline JavaScript code and use of 'data:' URIs.
• Specify both the report-to and report-uri directives (the latter soon to be deprecated) to
ensure violations of CSP are reported.
• Update the application's 'Content-Security-Policy' directives to reflect this change by
removing these values.
• Establish a restrictive 'default-src' using "Content-Security-Policy: default-src 'self'" and then
open it up only where needed using the content-specific directives (e.g. script-src, objectsrc).

Console error - 
![image](https://github.com/ngx-formly/ngx-formly/assets/33519688/93d4e4c0-f401-4b51-8a6c-a78d891638a1)

Library Error -
![image](https://github.com/ngx-formly/ngx-formly/assets/33519688/ed51cfc7-44d3-4613-9304-4369e403f839)

**Environment**

- Angular version: 12.2.16
- Formly version: 5.10.21
- ![image](https://github.com/ngx-formly/ngx-formly/assets/33519688/32ac1dd9-ca87-40c7-8d56-59817b1f5339)

Please provide update if we need to change our code or please update the library.

**Comment by aitboudad** [comment]
Duplicate of #2537
