### ISSUE TITLE
Not able to apply hide Expression for multicheckbox type field , 

### ISSUE THREAD

**Issue by Rishabh-Yadav-12** [ngx-formly/ngx-formly#3712]
Hello ngx-formly team ,
Its request from you to please give me solution for this requirement : 
Q: I want to apply hideExpression for multicheckbox type fields option , But its not working . I am able to achieve the result using hideExpression if the field is radio , select , but not able to do with multicheckbox .

Here is detailed Explanation: 
Question : I want to show the field with labled "show me ", , when user selects option one(1) from multicheckbox , but hideExpression is not working 

My code : **Its NOT working with multicheckbox** _but working with radio_ 

export class AppComponent {
  form = new FormGroup({});
  model = {};
  fields: FormlyFieldConfig[] = [
    {
      key: 'multicheckbox',
      type: 'multicheckbox',
      props: {
        label: 'Multicheckbox',
        required: true,
        options: [
          { label: 'Option 1', value: '1' },
          { label: 'Option 2', value: '2' },
        ],
      },
    },
    {
      key: 'showme',
      type: 'input',
      props: {
        label: 'show me',
        placeholder: 'Input placeholder',
        required: true,
      },
      **hideExpression: "!(model.multicheckbox['1'] ===  true)"**
    },
  ];
}

working code with radio:

fields: FormlyFieldConfig[] = [
    {
      key: 'radio',
      type: 'radio',
      props: {
        label: 'Radio',
        required: true,
        options: [
          { label: 'Option 1', value: '1' },
          { label: 'Option 2', value: '2' },
        ],
      },
    },
    {
      key: 'showme',
      type: 'input',
      props: {
        label: 'show me',
        placeholder: 'Input placeholder',
        required: true,
      },
      **hideExpression: "!(model.radio ===  '1')"**
    },
  ];

**Comment by Rishabh-Yadav-12** [comment]
@aitboudad pls provide solution

**Comment by Rishabh-Yadav-12** [comment]
@kenisteward @beeman pls core team help me

**Comment by Rishabh-Yadav-12** [comment]
sorry by mistake I closed that

**Comment by stormbreakR1** [comment]
@Rishabh-Yadav-12 if u got solution to your issue plz help me as i am also facing similar issue, my id: singhnitin354 @ gmail . com
