### ISSUE TITLE
When can we access ionic(7) support the latest version of ngx-formly ?

### ISSUE THREAD

**Issue by serkaneken** [ngx-formly/ngx-formly#3717]
Hello, 

I already opened this issue( https://github.com/ngx-formly/ngx-formly/issues/3682 ) for support/request.
Could I learn when can we access the support of ionic 7 for ngx-formly ? 
Is there specific work on upgrades ngx-formly ? Actually we are wondering about the estimated date.

Thank you in advance.

**Comment by FBosito** [comment]
Hi, 

also would be interested in this.

Thx
Günter

**Comment by prajput1994** [comment]
Hi,

We are also using @ng/formly and having issue with ionic 7 update. Is there any update for when this issue will resolve for ionic 7.

Thanks

**Comment by mhasansheikdawood** [comment]
Looking forward for the ionic7 support.

Can someone help us with the expected date for the support!!

**Comment by msyler** [comment]
Having exact same issue, Thanks!

**Comment by aitboudad** [comment]
Duplicate of #3643
