### ISSUE TITLE
hideExpression and disable property in json schema

### ISSUE THREAD

**Issue by BhagyashreeCH** [ngx-formly/ngx-formly#3719]
@aitboudad I am having hide expression issue when passing nested object value through json schema, these are the changes I have made here https://stackblitz.com/angular/eyoexxxgvpg?file=src%2Fapp%2Fapp.component.ts in nested.json schema

 "hideExpression": "field.parent.model.title === 'test'" => this also I have tried, Am I missing something, please suggest me **it will resolve my lot of issues related to disable or hide conditionally**

![image](https://github.com/ngx-formly/ngx-formly/assets/54449571/cc019a53-2fc0-4f89-b9ac-77e089e671e5)

**Comment by aitboudad** [comment]
try with:
```json

"widget": {
  "formlyConfig": {
    "hideExpression": "model.title === 'test'"
  }
}
```
