### ISSUE TITLE
how to have more than one input field in the fieldArray(repeating section)

### ISSUE THREAD

**Issue by Virus35** [ngx-formly/ngx-formly#3720]
how can i refer the second fieldGroup's props in this case? im getting undefined if i try to access it, kindly help asap.

{
				key: 'repeating-section',
				type: 'custom-repeat-section',
				fieldArray: {
					fieldGroupClassName: 'd-flex align-items-center gap-2',
					fieldGroup: [
						{
							className: 'w-100',
							key: 'Tenant',
							type: 'custom-dropdown-postpopulated',
							props: {
								label: 'Tenant',
								placeholder: 'Select Tenant',
								searchPlaceholder: 'Search Tenant',
								inputType: 'text',
								disabled: false,
								dropDownCase: 0,
								dropDownIndex: 0,
								selectedId: '',
								insideClick: false,
								searchText: '',
								selectedTenant:'vishal',
								required: true,
								loaderId: 'vishal',
								options:[],
								// onShownFunc: this.dropdownOpen.bind(this),
								// onHiddenFunc: this.dropDownClose.bind(this),
								// scrollEndFunc: this.detectScrollEnd.bind(this),
								onOptionSelect: this.onOptionSelect.bind(this),
								dbModelChange: this.getActiveSubgroups.bind(this),
								getActiveSubGroup: this.getActiveSubgroups.bind(this),
								extraFunc:this.getRoles.bind(this)
							}
						},
						{
							className: 'w-100',
							key: 'Role',
							type: 'custom-dropdown-postpopulated',
							props: {
								placeholder: 'Select Role',
								optionArray:[],
								searchPlaceholder: 'Search Tenant',
								inputType: 'text',
								disabled: false,
								dropDownCase: 0,
								dropDownIndex: 0,
								selectedId: '',
								insideClick: false,
								searchText: '',
								required: true,
								selectedTenant:'',
								loaderId: 'vishalRikhi',
								options:[],
								// onShownFunc: this.dropdownOpen.bind(this),
								// onHiddenFunc: this.dropDownClose.bind(this),
								// scrollEndFunc: this.detectScrollEnd.bind(this),
								onOptionSelect: this.onOptionSelect.bind(this),
								dbModelChange: this.getActiveSubgroups.bind(this),
								getActiveSubGroup: this.getActiveSubgroups.bind(this)
							},
							hooks: {
								onInit: (field: FormlyFieldConfig): void => {
									console.log(field.parent?.fieldGroup?.[1].props?.['selectedTenant']);
								}
							}
						},
					]
				}
			}

**Comment by aitboudad** [comment]
The question is not clear, if you're looking to get the `Tenant` field you may try with: `field.parent?.get('Tenant')`
