### ISSUE TITLE
Hook function type definition is incorrect.

### ISSUE THREAD

**Issue by gkamperis** [ngx-formly/ngx-formly#3722]
According to this the hook functions return `void`

https://github.com/ngx-formly/ngx-formly/blob/bf89337a640749d01dfcf6b1ecc286adc7eb3c79/src/core/src/lib/models/fieldconfig.ts#LL243C55-L243C55

`export type FormlyHookFn = (field: FormlyFieldConfig) => void;`

https://github.com/ngx-formly/ngx-formly/blob/bf89337a640749d01dfcf6b1ecc286adc7eb3c79/src/core/src/lib/models/fieldconfig.ts#L246

However, the below suggest otherwise

https://github.com/ngx-formly/ngx-formly/issues/2238#issuecomment-638762928
https://github.com/ngx-formly/ngx-formly/releases/tag/v5.7.0

https://github.com/ngx-formly/ngx-formly/blob/bf89337a640749d01dfcf6b1ecc286adc7eb3c79/demo/src/app/examples/advanced/repeating-section-input/app.component.ts#L31

So, it looks like the type is incorrect and from the docs it is not clear which hook can return what.
Essentially we do not know if we can return an observable that will be auto unsubscribed or if we cannot return anything.

- Formly version: 6.1.8

**Comment by aitboudad** [comment]
Could you please please send a fix? We support returning an Observable for `onInit` hook.

**Comment by gkamperis** [comment]
@aitboudad I could try but there is not enough info on how the architecture hangs together, what the parts are, etc etc.

Last time I tried to provide a simple solution that had no impact on architecture it was effectively rewritten as I clearly did not have any visibility on how things hang together and what would be alternative preferable approaches.

For something like this that affects public type declarations and changes in the API a lot more is required than just a fix.
How can I know if what I think is appropriate is acceptable?

There is just not enough documentation on the parts of the project so that someone can realistically provide good solutions.

Is there a way we can communicate more interactively? a chat of sorts?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.2.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.2.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
