### ISSUE TITLE
Problem with dependencies primeng v16 which uses Angular 16

### ISSUE THREAD

**Issue by lorenzo0895** [ngx-formly/ngx-formly#3724]
**Description**
The package "@ngx-formly/primeng" has a peer dependency on "primeng" with a version requirement of ">=13.0.0". This can cause issues during installation because when you try to install "@ngx-formly/primeng", npm will attempt to install the latest major version of "primeng" (which is currently 16.0.2). However, this version of "primeng" is built for Angular 16.0.0, leading to conflicts in many cases. As a result, you may need to manually override dependencies in your package.json file.
<img src="https://github.com/ngx-formly/ngx-formly/assets/82187204/37dc5d69-517d-40fe-852b-e36a44fb27d6" width="300px">

**Solution**
Replace ">=13.0.0" with "^13.0.0"

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.12) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
