### ISSUE TITLE
Checkbox Field Appears with MatFormField Input Appearance

### ISSUE THREAD

**Issue by EvanScott542** [ngx-formly/ngx-formly#3727]
**Description**
Appearance of `mat-form-field`, either underline by default or outline, displays around checkbox. Only the checkbox and its label should show. 

**Minimal Reproduction**
This can be seen in the provided starter template. There should be no outline surrounding the checkbox field. 
- Material: https://stackblitz.com/edit/ngx-formly-ui-material

**Your Environment**

- Angular version: 16.0.0
- Formly version: 6.1.4

**Comment by aitboudad** [comment]
Duplicate of #3558
