### ISSUE TITLE
🐞 Disabled forms do not render disabled state

### ISSUE THREAD

**Issue by rustygreen** [ngx-formly/ngx-formly#3731]
**Description**
When passing a form (FormGroup instance) that is already disabled to the formly component, the form will not adhere to the disabled state. The expected result of passing a disabled FormGroup to the formly-form would be that the form is disabled, but that is not what is happening.

**Minimal Reproduction**
1. Create a new form group `const form = new FormGroup({})`
2. Disabled the form group `form.disable()`
3. Create a formly form `<formly-form [form]="form" [fields]="fields"></formly-form>`
4. 🐞 ISSUE: the form does not render with disabled controls (it actually changes the state of some controls)

The issue can be seen in the following Stackblitz:
https://stackblitz.com/edit/angular-qeuysx?file=src%2Fapp%2Fapp.component.ts

Load the stackblitz and notice how the form is editable (it should not be editable on initial load because the form is disabled). If you enable or disable the form after it has already been rendered, then the form behaves correctly.

**Your Environment**

- Angular version: 14+
- Formly version: 6

**Comment by aitboudad** [comment]
`FormGroup` doesn't preserve disable state its delegated to its children controls, you should wait till the form is built in order to take effect. In Formly you can rely on `onInit`:

```ts
{
  hooks: {
    onInit({.form }) {
      form.disable();
    }
  }
}
```
