### ISSUE TITLE
Checkbox: move Data test-id to input

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3734]
**Question**
I have a checkbox in a formly form, using mat checkbox (from MatFormly).
Is there any simple way (without creating a custom formly field type), to move (or show )the data testid from the formly field element (mat-checkbox) to the input?
![image](https://github.com/ngx-formly/ngx-formly/assets/42749923/63f49501-0790-4f8a-9c4b-1514d103ae05)

**Comment by aitboudad** [comment]
The easy way  at the moment is to override the field, an alternative way is to use custom extension https://formly.dev/guide/custom-formly-extension
