### ISSUE TITLE
Form is valid when a field is invalid

### ISSUE THREAD

**Issue by daniela-alves** [ngx-formly/ngx-formly#3742]
**Description**
I have a custom FieldType for text input with the **required** configuration on **props** a true.
After I define in the json the structure with all configurations needed for input text, I display it on the form with a default value.
When I remove the default value, I should see a message error in red, like in version 5, telling me the field is required. 
However, I don't see that and the form is valid. 
I close the form that I display on a modal and I open it again without a default value and the error message in red appears. 

**Minimal Reproduction**
https://stackblitz.com/edit/angular-uswpmx?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

In first tab, the required field is not required anymore. 
This is the structure I have on my side. I use the same formGroup to handle validations when I validate the form for tabs, etc..

**Your Environment**

- Angular version: 13.3.11
- Formly version: 6.1.8

I'm doing the migration of Angular12 to 13 and Formly 5 to 6

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/3520#issuecomment-1351352330
