### ISSUE TITLE
JSON Schema support of ngx-formly 4.x for angular 6

### ISSUE THREAD

**Issue by koushiv777** [ngx-formly/ngx-formly#3743]
JSON Schema support of ngx-formly 4.x for angular 6

A clear and concise description of what the question is.

Does ngx-formly have a version for angular 6 which supports JSON Schema? If No any pointers how to achieve that.

**Comment by aitboudad** [comment]
Formly v4.x is not supported anymore so the only solution for now is to upgrade to at least v5 in order to be able to use JSON Schema.
