### ISSUE TITLE
Documentation doesn't include UI Libraries in source code view

### ISSUE THREAD

**Issue by intellix** [ngx-formly/ngx-formly#3746]
**Description**
If you go to the documentation for a UI Library like "material" and click on source, you'll see that the Material UI Module is never actually imported, but it does exist within the Stackblitz (because otherwise it wouldn't work): https://formly.dev/docs/ui/material/ 

Source:  
<img width="1268" alt="Screenshot 2023-07-18 at 11 40 58" src="https://github.com/ngx-formly/ngx-formly/assets/1162531/180dec8e-2381-4ff0-8d53-3e58392dc8d3">

Stackblitz:  
<img width="658" alt="Screenshot 2023-07-18 at 11 41 06" src="https://github.com/ngx-formly/ngx-formly/assets/1162531/0e322129-0ab0-474f-87cf-771bd4eb6fa8">

**Comment by aitboudad** [comment]
This issue has been fixed. Thank you!
