### ISSUE TITLE
Error when using same attribute names in dependencies for oneOf JSONSchema definition

### ISSUE THREAD

**Issue by vsiguero** [ngx-formly/ngx-formly#3749]
**Question**
I've been struggling with this error, I'll appreciate any help and/or workaround:

I am using JSONSchema and the `.toFieldConfig` method with `oneOf` dependencies as shown in the [example from the website](https://formly.dev/docs/examples/advanced/json-schema).

When I use fields with the same name as alternatives in a oneOf array, they are throwing an error whenever I set them using different types:

An error thrown in the console:
ERROR TypeError: control.registerOnChange is not a function

Example:
```Javascript
this.formlyJsonschema.toFieldConfig({
        title: 'Configurations',
        description: 'These are configurations',
        type: 'object',
        properties: {
          name: {
            type: 'string',
            title: 'Flag type',
            enum: ['type', 'other'],
          },
        },
        required: ['name'],
        dependencies: {
          name: {
            oneOf: [
              {
                title: 'type',
                properties: {
                  name: {
                    enum: ['type'],
                  },
                  value: {
                    title: 'Value',
                    type: 'array',
                    items: {
                      type: 'string',
                      enum: ['value1', 'value2'],
                    },
                  },
                },
              },
              {
                title: 'other',
                description: 'Other property.',
                properties: {
                  name: {
                    enum: ['other'],
                  },
                  value: {
                    title: 'Value',
                    type: 'boolean',
                  },
                },
              },
            ],
          },
        },
      }),
    ]

```

And when we submit the form, the value from `other` field is an empty array [] instead of a boolean.

**Minimal Reproduction**
[https://stackblitz.com/edit/angular-68myfg?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/angular-68myfg?file=src%2Fapp%2Fapp.component.ts)

**Your Environment**

- Angular version: 14
- Formly version: 6

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.2.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.2.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
