### ISSUE TITLE
how can I get current component from ngx-fromly  inner control

### ISSUE THREAD

**Issue by microwin1668** [ngx-formly/ngx-formly#3751]
`@Component({
  selector: 'app-my-form',
  template: `
    <form [formGroup]="form" (ngSubmit)="onSubmit()">
      <formly-form [form]="form" [fields]="fields" [options]="options"></formly-form>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  `,
})
export class MyFormComponent {
  form = new FormGroup({});
  model: any = {};
  }`
  
how can I get current component(MyFormComponent) from ngx-fromly inner control

**Comment by aitboudad** [comment]
The question is not clear, please elaborate.
