### ISSUE TITLE
Ngx-formly oneOf json format field validation.

### ISSUE THREAD

**Issue by kasturiwaleav** [ngx-formly/ngx-formly#3754]
**Can you please a sample example where formly json oneOf is used and can add custom validation. I will just elaborate my requirement i have two fields start date and end date which are inside the oneOf first element I need a custom validation where I can check startDate is less than endDate *

A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/1982#issuecomment-566048527
