### ISSUE TITLE
Question - Server-side validation support

### ISSUE THREAD

**Issue by tomer953** [ngx-formly/ngx-formly#3758]
Hi 👋

We're exploring the use of ngx-formly in our Angular application to dynamically generate forms based on JSON configurations. This solution seems promising for creating customizable form templates that cater to various use cases.

The core use case is quite simple: we need to support a general registration form, with customized templates such as RegisterChildren, RegisterAdults, RegisterCompany, and so on. These templates should be able to be dynamically created from the UI, and we need to validate them on both the UI and server-side.

However, we foresee a challenge when it comes to validating the form data on the server side. We will need to validate the incoming data according to the formly JSON config in our NestJS server to ensure data integrity and security.

We understand that ngx-formly is primarily a client-side library and does not inherently support server-side validation. However, we were wondering if you have any recommended approach for handling this scenario. We are looking for a way to interpret the formly JSON config on the server and apply the same validations as on the client-side.

One approach we've considered is manually mapping the formly field types and templateOptions to corresponding server-side validations. However, this could be prone to errors and discrepancies between client-side and server-side validations.

Additionally, we've also considered using JSON Schema for validations, but we've found it to be a bit limited. For instance, JSON Schema does not support custom types like 'datetime', 'time', and other specific types that we could easily model using ngx-formly.

If you have any guidance on how we could accomplish server-side validation for formly forms, or if there are plans to support this in ngx-formly, we would greatly appreciate your insight.

Thank you for your time and considering ngx-formly for our project.

**Comment by aitboudad** [comment]
At the moment if you would like to unify the validation between client and server, the viable option is JSON Schema.

> Additionally, we've also considered using JSON Schema for validations, but we've found it to be a bit limited. For instance, JSON Schema does not support custom types like 'datetime', 'time', and other specific types that we could easily model using ngx-formly.

Formly right now cover 90% of JSON schema specs and for unsupported part or if you would like customize the JSON Schema output please check https://formly.dev/docs/guide/json-schema#customize-json-schema-output
