### ISSUE TITLE
`getField` function not working for `fieldArray` parameter

### ISSUE THREAD

**Issue by NickSettler** [ngx-formly/ngx-formly#3759]
**Description**
Using `getField` function on fields with fieldArray property not working - fields are not being searched in fieldArray.

**Minimal Reproduction**
not working on stackblitz, but working locally

https://stackblitz.com/edit/stackblitz-starters-umcd1h?file=src%2Fmain.ts

**Your Environment**

- Angular version: 16.1.8
- Formly version: 6.1.8

**Additional context**

**Comment by aitboudad** [comment]
The main purpose of `getField` is to return the constructed fields and not `fieldArray` which is just a base that we rely to create a new fields.

To get the first item in array, you may use: `getField('items.0')`.
