### ISSUE TITLE
CustomField extending FormArrayType setting formControl wrongly

### ISSUE THREAD

**Issue by km4dlpx** [ngx-formly/ngx-formly#3761]
**Description**
There is a custom field extending fieldArray of formly , I am overriding onPopulate method as well where I am adding formlyFields. I am using options.build() to rebuild the form on addition and removal of new fields after which onPopulate gets called but the issue is field.formControl object is empty. 
Earlier the same logic is working fine for version 5.10.32.

 this.field.parent?.parent?.templateOptions?.addGroup(this.index, this.model.fromObject); 

It seems like this.field.parent?.parent?.formcontrol is empty in the latest version.

**Minimal Reproduction**

**Your Environment**

- Angular version: 14
- Formly version: 6.1.8

**Additional context**

**Comment by aitboudad** [comment]
Without a reproduction it hard for us to know the issue, please feel free to leave a comment once you've got a reproduction example, thanks!
