### ISSUE TITLE
JSON Schema's uniqueItems Constraint for Array of Objects Sensitive to Field Entry Order

### ISSUE THREAD

**Issue by PaulG96** [ngx-formly/ngx-formly#3764]
**Description**
The `uniqueItems`' error message does not show for an array of objects when the values entered for the object are entered in different orders for different items within the array.

It appears that the ordering of the properties within an object is determined by the order the fields are entered. Therefore it seems that whatever is performing the unique items validation is sensitive to the ordering of properties within an object.

**Minimal Reproduction**
[Stackblitz](https://stackblitz.com/edit/ngx-formly-ui-material-paxhhb?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fassets%2Fjson-schema%2Fsimple.json)

Steps to reproduce using the above Stackblitz:

1. Add an item to the array.
2. For the "one" field enter a value.
3. For the "two" field enter a value.
4. Add a second item to the array.
5. For the "two" field enter a value that is the same as the first "two" field.
6. For the "one" field enter a value that is the same as the first "one" field.
7. Note that a `uniqueItems` error message has not been shown despite both items having the same values.
8. Clear the value from "two" field for the second item.
9. For the "two field" enter a value.
10. Note the `uniqueItems` error message is now shown.

**Environment**

- Angular version: 16.0.0
- Formly version: 6.1.8

**Additional context**
I currently have a workaround for this by creating a custom validator for unique items which uses the Ajv package to perform the validation.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.2.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.2.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
