### ISSUE TITLE
How to add custom attribute on form field?

### ISSUE THREAD

**Issue by iKrishnaSahu** [ngx-formly/ngx-formly#3766]
How to add custom attribute on `mat-form-field`?

I am using angular with material and creating dynamic forms and I would like to add one special attribute `rufStyle` on form field?

I am currently having JSON input just like what we have in [material stackblitz example](https://stackblitz.com/edit/ngx-formly-ui-material-awfczs?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,node_modules%2F%40ngx-formly%2Fcore%2Flib%2Fmodels%2Ffieldconfig.d.ts).

**Comment by aitboudad** [comment]
You'll need to override the default wrapper `form-field`.
