### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError: Proper way to set value in custom field component onInit

### ISSUE THREAD

**Issue by Steb95** [ngx-formly/ngx-formly#3767]
**Question**

I created a custom field and added it to formlyModule as described in the "custom types" guide (https://formly.dev/docs/guide/custom-formly-field).

I'd like to dynamically set the value of this custom field directly in the component that defines it (e.g. at ngOnInit). I'm using `this.field.formControl.setValue()`, but, if the field is marked as required and doesn't have a default value, when the value is set at onInit, angular throw the following error:

`Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'ng-valid': 'false'. Current value: 'true'. Find more at https://angular.io/errors/NG0100`

I'm missing something? Is there another proper way to set the value of a custom field directly in the component when it's created (so without changing the formSchema/form fields)?

Reproduction: https://stackblitz.com/edit/angular-bhcsq9
I used the stackblitz provided here as starting point: https://formly.dev/docs/examples/advanced/json-schema
I added as an example (it's not my actual custom field, which is more complicated) a `test-checkbox` field (file `check.type.ts`), marked it as required in the form schema and set it's value in component `check.type.ts`'s ngOnInit (https://stackblitz.com/edit/angular-bhcsq9?file=src%2Fapp%2Fcheck.type.ts)

![t](https://github.com/ngx-formly/ngx-formly/assets/47389399/7a1edd92-4cc6-446d-b20d-8314d6a5f645)

**Comment by Steb95** [comment]
Hi, thank you for your answer!

I can't use the first solution since the form is dynamically generated based on user-specified fields, it's not something hardcoded (so I don't have a model until the form is generated by formly).

I suppose I can't use the third solution either, since the value is dynamically generated based on `field.props` value (e.g. in a datepicker, the value -1 in a custom props needs to be parsed in the date corresponding to always "yesterday" etc...). And it seems that in the constructor I can't access `field.props` values. I updated the reproduction to give a better idea: https://stackblitz.com/edit/angular-bhcsq9-k6taom?file=src%2Fapp%2Fcheck.type.ts

```
ngOnInit() {
    const someValue = this.field.props['someValue'];
    if (
      this.field.formControl.value === undefined &&
      someValue &&
      someValue.startsWith('test')
    ) {
      this.field.formControl.setValue(true);
    }
  }
```

The second solution seems a bit hacky to me, but nevertheless it works. So if there isn't some better approach I suppose I can use it, thanks!

**Comment by aitboudad** [comment]
Another solution is to use one of the following methods:   `prePopulate`, `onPopulate` or `postPopulate` instead of `ngOnInit`:

```ts
export class FormlyFieldCustomCheckbox extends FieldType<FieldTypeConfig<CheckboxProps>> implements FormlyExtension {
  onPopulate(field: FormlyFieldConfig) {
     ...
  }
}
```

**Comment by Steb95** [comment]
Hi, thank you for your answer!

I used `prePopulate` to set the default value (instead of setting the field value directly) and it seems to work fine, thanks!
