### ISSUE TITLE
Angular 16 standalone async error

### ISSUE THREAD

**Issue by realtica** [ngx-formly/ngx-formly#3774]
**Description**

This error happening when you try to load the model and the fields: FormlyFieldConfig **_asynchronously_**.
`TypeError: undefined is not an object (evaluating 'value.constructor.name')
`
- Angular version: 16.1.7
- Formly version: 6.1.8

**Additional context**
I tried with the getting-starting example and works well.

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by realtica** [comment]
> Hi, could you please provide a reproduction, here is our `stackblitz` starter example: https://stackblitz.com/edit/ngx-formly-ui-bootstrap
> 
> Thanks!

Hello, this bug happens only for standalone components, please do you have an `stackblitz` starter with standalone component?

**Comment by aitboudad** [comment]
Hi, did you try the following solution https://github.com/ngx-formly/ngx-formly/issues/3721#issuecomment-1602401526
