### ISSUE TITLE
Manipulate repeatable section from outside

### ISSUE THREAD

**Issue by Et3rnal** [ngx-formly/ngx-formly#3775]
**Question**

Is there a way (using a custom repeatable type) to add and remove from within the form, like inside the fields hooks instead of using `Add()` and `Remove()` of `FieldArrayType`

I just can't get the custom type to show the changes (array of objects)

Otherwise is there a way to trigger the `Add()` and `Remove()` or any method inside the created type from the outside?

Reason:
I am trying to keep the form in its own component from the repeat section component

**Comment by Et3rnal** [comment]
I didn't find how to trigger a method inside the custom type, but I was able to manipulate the array simply using
```
this.model.recommend.push(commData.selectedItem);
this.model = {...this.model};
```
I was manipulating the field which was not getting reflected
Also, I couldn't get `setValue()` to do it

**Comment by BeniFreitag** [comment]
I also want to patch the value in a formly repeat/array. Using `form.patchValue()` patches the values for existing repeat-items, but it doesn't add new repeating-items nor remove old repating-items.

Use case: I want to prefill a list of answers based on some user-inputs.

````typescript
form.patchValue({
      tasks: [ { name: 'one' }, { name: 'two' } ]
})
````

Sample:
https://stackblitz.com/edit/angular-formly-repeat-patch?file=src%2Fapp%2Fapp.component.ts

Is it the right approach to update the entire model?

(Related to: [Angular How to patch value in the form array](https://stackoverflow.com/questions/65292461/angular-how-to-patch-value-in-the-form-array))
