### ISSUE TITLE
Angular material 16 issue 

### ISSUE THREAD

**Issue by BakhtadzeSandro** [ngx-formly/ngx-formly#3777]
**Description**
We use formly, angular material and angular animations in the project, but there is an unexpected behavior of input fields. I will provide two versions of the code, one with materials older version and one with the latest. I also increased the duration of animation so its easier to see the bug. If you click the label before the animation ends, the input field moves unexpectedly. This bug occurs in the materials latest version. Below there are two exactly similar codes but with different versions.

Older version which works - https://stackblitz.com/edit/angular-yu7bzv-7ynsjt
Latest version which has the bug described above - https://stackblitz.com/edit/angular-yu7bzv-2taqyk

- Angular version: 16.1.4
- Formly version: 6.1.8

**Additional context**
Bug - 
![image](https://github.com/ngx-formly/ngx-formly/assets/87481392/50865675-ffb1-4fad-961b-6e1b428ffada)

**Comment by aitboudad** [comment]
Hi, could you please try the following workaround https://github.com/ngx-formly/ngx-formly/issues/3515#issuecomment-1334934984

**Comment by BakhtadzeSandro** [comment]
> Hi, could you please try the following workaround [#3515 (comment)](https://github.com/ngx-formly/ngx-formly/issues/3515#issuecomment-1334934984)

Thanks for your answer, I don't think it has any connection with the issue, tried but didn't work

**Comment by BakhtadzeSandro** [comment]
Tried this, but the issue still exists: 
https://stackblitz.com/edit/angular-yu7bzv-2taqyk?file=src%2Fstyles.scss
![image](https://github.com/ngx-formly/ngx-formly/assets/87481392/ff619362-f0a8-44f1-a5fb-d124d6f4aa13)

**Comment by kotekirkitadze** [comment]
@aitboudad Hello, can you help us for this issue?

**Comment by aitboudad** [comment]
Hi @kotekirkitadze, I'm unable to the reproduce the issue on my side, if you can show me how to reproduce it that would be helpful.

**Comment by kotekirkitadze** [comment]
@aitboudad 
Could you refer that link - https://stackblitz.com/edit/angular-yu7bzv-2taqyk?file=src%2Fapp%2Fapp.component.ts
Please click second step and wait, you will see that: 
![image](https://github.com/ngx-formly/ngx-formly/assets/74476606/b7a487ac-7d64-411e-93a5-3cc5ecdeac16)
Also, we can have a small call about this issue and I will show you.

**Comment by aitboudad** [comment]
> Could you refer that link - https://stackblitz.com/edit/angular-yu7bzv-2taqyk?file=src%2Fapp%2Fapp.component.ts

[Screencast from 2023-10-24 11-53-06.webm](https://github.com/ngx-formly/ngx-formly/assets/1753742/90f7afa7-90bb-4be4-bf85-49ab0dfb1fa3)


> Also, we can have a small call about this issue and I will show you.

Sure, but won't be available till the end of week.

**Comment by kotekirkitadze** [comment]
> > Could you refer that link - https://stackblitz.com/edit/angular-yu7bzv-2taqyk?file=src%2Fapp%2Fapp.component.ts
> 
>  Screencast.from.2023-10-24.11-53-06.webm 
> > Also, we can have a small call about this issue and I will show you.
> 
> Sure, but won't be available till the end of week.

Hello, could you help us with this issue?

**Comment by aitboudad** [comment]
Please try the following workarround:

```patch
@Component({
  selector: 'nxe-wrapper-animation',
+  host: {
+   '[id]': "'animation-' + field.id"
+  },
})
....
```
