### ISSUE TITLE
Best Grouping Approach of Several Form Fields - e.g. Login Form

### ISSUE THREAD

**Issue by webia1** [ngx-formly/ngx-formly#3778]
I'm currently working with an **Nx Mono-Repo v16+** containing multiple **Angular 16+** applications. I can use presets across these apps without any issues.

I'm interested in organizing several UI elements into a single reusable group. For example, I'd like to create a **Login Form** with `Username` and `Password` fields that can be easily imported into any Angular app within this Mono-Repo using a predefined group-keyword like `ui-login`.

My current solution involves creating an Angular Login Component with @Input() parameters. This works, but I'm curious to explore if there are more elegant solutions available.

> I found [this solution by Intershop](https://github.com/intershop/intershop-pwa/blob/develop/docs/guides/field-library.md) which is one of the options I'm considering. 

Are there better alternatives? Links to existing documentations are also very welcome.

Thank you very much!

**Comment by aitboudad** [comment]
see https://formly.dev/docs/guide/formly-field-presets
