### ISSUE TITLE
Performance with 150+ fields, 2000 line json config.

### ISSUE THREAD

**Issue by ajjohnson1996** [ngx-formly/ngx-formly#3779]
I'm currently working on a solution for an Angular 15 application that has many large forms (100+ fields in some cases, maybe more) and am looking at formly as a solution. I've noticed that rendering these large pages takes about 5 seconds or more, which violates my requirements.

I'm wondering if I'm using the wrong tool and trying to fit a square peg through a round hole, or if there's something I'm doing wrong on my end. If needed I can try to put together a demo on stack blitz.

Is the performance I'm seeing expected for forms of this size?

**Comment by kenisteward** [comment]
As a developer who has used formly for many large forms I can confirm it
can be used for them. Here are a few thoughts on this subject.

Have you been able to make sure it is the format rendering engine that is
causing a slow down and not the browser draw? Do you have any example or
something you can share that specifies the perf issue with formly?

From our usage of formly we have not found performance issues for
rendering. In general it was an odd usage of conditionals that caused many
recalls on the fields so it was our configurations not formly itself.

We also found performance problems with the css engine for chrome 2-3 years
ago when using flex box with a lot of fields.

There have already been solutions proposed in formly issues to have things
like virtual scroll

https://github.com/ngx-formly/ngx-formly/issues/3398#issuecomment-1197837488

This allows for forms to be large single configurations.

Last note here:
It might be a good idea to split your forms into sections to have better
load performance as well.
