### ISSUE TITLE
multicheckbox touched state

### ISSUE THREAD

**Issue by mgsg** [ngx-formly/ngx-formly#3786]
**Question**

Hi. Thanks for the great work!

This is my first post here even if I've been using Formly for a while now.

I need to submit to the backend all multicheckbox option states, even if the user has not checked/toched them (checkOptionValue: false).

By default, only data for options that have been touched are sent. So a false value is only sent if the user checks a checkbox and then unchecks it.

What is the best way to mark all multicheckbox options as "touched"? Using hooks? Extending the multicheckbox type with a custom type?

I'll try to create a Stackblitz example later today.

Any help/hint would be appreciated.

**Comment by aitboudad** [comment]
you may set default value with all options as false so in that case you'll be able to sent the options state if not touched.

**Comment by mgsg** [comment]
Thanks, that worked!
