### ISSUE TITLE
click changes model value, but expressions don't evaluate unless I click submit, any idea?

### ISSUE THREAD

**Issue by wyxcoder** [ngx-formly/ngx-formly#3787]
**Question**

A clear and concise description of what the question is.

The test code can be accessed here [link](https://stackblitz.com/edit/angular-ntyh6k?file=src%2Fapp%2Fapp.component.ts)
I expect when click between 'one time' and 'monthly' the expressions will be evaluated and the fields below will be hide/unhide.

**Comment by aitboudad** [comment]
The `model` inside custom type is readonly, use `this.field.formControl.setValue(value);` instead.

**Comment by wyxcoder** [comment]
> The `model` inside custom type is readonly, use `this.field.formControl.setValue(value);` instead.

Thanks! That solved the proble.

Another issue on the page. I have total six amount buttons with same key. Each has different value. When you click one, the value will be stored in model and in turn highlight that button. But I found one of the bottom three buttons could be highlighted together with one of the top three buttons. Like screenshot below, any clue? 


![image](https://github.com/ngx-formly/ngx-formly/assets/47443766/80817bfb-0837-4de0-a7a0-1c039a717854)
