### ISSUE TITLE
Field matching -> dynamic Error Path?

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3789]
**Question**

Based on the example https://formly.dev/docs/examples/validation/matching-two-fields/ we can have the errorPath set as below:

![image](https://github.com/ngx-formly/ngx-formly/assets/42749923/75e393ca-4281-4b55-a66e-b56694556655)

This means that I will have the error message in the passwordConfirm field.
But, I need a solution where the matching message appears in the field where I am currently typing/or leaving (for example password field also, if I am editing it and confirmPassword does not match). Is there an example for such solution?

**Comment by aitboudad** [comment]
You can return `errorPath`  inside the `fieldMatchValidator`, to detect the current active field check the focused one.

```patch
export function fieldMatchValidator(control: AbstractControl) {
- return { fieldMatch: { message: 'Password Not Matching' } };
+ return { fieldMatch: { message: 'Password Not Matching', errorPath: 'passwordConfirm' } };
}
```

**Comment by zoltanhalasz** [comment]
Thanks, it is working, just I am not able to get the focused field, is there any way to do this?

**Comment by aitboudad** [comment]
```ts
export function fieldMatchValidator(control: AbstractControl, field: FormlyFieldConfig) {
  const { password, passwordConfirm } = control.value;

  console.log(
    field.get('password')?.focus,
    field.get('passwordConfirm')?.focus,
  );
...
}
```
