### ISSUE TITLE
Error registering controls in onPopulate of FieldArrayType

### ISSUE THREAD

**Issue by markcrowl** [ngx-formly/ngx-formly#3790]
**Description**
Controls not being registered when overriding onPopulate of FieldArrayType in Angular v16.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-jwbggc?file=src%2Fapp%2Fapp.component.ts

Clicking on the add icon or remove icon gives the error:

ERROR TypeError: form.get is not a function
    at registerControl (utils.ts:108:52)
    at FieldFormExtension.addFormControl (field-form.ts:79:5)
    at FieldFormExtension.onPopulate (field-form.ts:38:14)
    at eval (formly.builder.ts:56:37)
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder._build (formly.builder.ts:56:10)
    at eval (formly.builder.ts:57:77)
    at Array.forEach (<anonymous>)
    at FormlyFormBuilder._build (formly.builder.ts:57:59)
    at eval (formly.builder.ts:57:77)

**Your Environment**

- Angular version: 16.2.7
- Formly version: 6.2.0

**Additional context**
This is based on https://stackblitz.com/edit/ngx-formly-ui-material-querybuilder?file=app%2Fapp.component.ts written by Dominic Watson (https://github.com/intellix).  I need to use this in Angular 16+.

**Comment by aitboudad** [comment]
`FieldArrayType` class has `onPopulate` method, so it should be called in order to work properly. Please ensure the method is called and not overrided.

**Comment by markcrowl** [comment]
Hi.  I'm not sure what you mean about calling the onPopulate method.  

Where would I call it?

The example seems to overrides the onPopulate method to read the model information.  Could you give me an example on how to get it working without overriding the onPopulate method please.

**Comment by markcrowl** [comment]
I think my issue is related this one https://github.com/ngx-formly/ngx-formly/issues/3761.  The example is doing something very similar to what they were referring to.

I think the field.formControl is not being set.  Did you get a chance to look at the example script?

Thanks.

**Comment by kenisteward** [comment]
I believe what @aitboudad is saying is the formArray type does a lot of
specific things to make sure that the form controls are setup correctly.

If you want it to work in place in your on populate function you'd have to
call

super.onPopulate() first and then run your logic after

That being said. Out of all the forms I've made I've never had a need to
override the array type on populate.

Is there a specific use case here?

**Comment by markcrowl** [comment]
Hi, I'm trying to use the query builder https://stackblitz.com/edit/ngx-formly-ui-material-querybuilder?file=app%2Fapp.component.ts that was built by Dominic Watson (https://github.com/intellix) in my Angular 16 standalone project.

When I try to call super.onPopulate() first, I get the error: control.setParent is not a function.

Thanks for you reply.

**Comment by markcrowl** [comment]
> Hi, I'm trying to use the query builder https://stackblitz.com/edit/ngx-formly-ui-material-querybuilder?file=app%2Fapp.component.ts that was built by Dominic Watson (https://github.com/intellix) in my Angular 16 standalone project.
> 
> When I try to call super.onPopulate() first, I get the error: control.setParent is not a function.
> 
> Thanks for you reply.

Hi, I'm trying to use the query builder https://stackblitz.com/edit/ngx-formly-ui-material-querybuilder?file=app%2Fapp.component.ts that was built by Dominic Watson (https://github.com/intellix) in my Angular 16 standalone project.

When I try to call super.onPopulate() first, I get the error: control.setParent is not a function.

Thanks for you reply.

**Comment by smile2014** [comment]
@markcrowl    Hello, how can I solve this problem?

**Comment by smile2014** [comment]
@aitboudad  Hi. Could you get the stackblitz example to work?

https://stackblitz.com/edit/ngx-formly-ui-bootstrap-jwbggc?file=src%2Fapp%2Fapp.component.ts

**Comment by FritzHerbers** [comment]
@markcrowl @smile2014 
Have you found a fix?

I am using the same https://stackblitz.com/edit/ngx-formly-ui-material-querybuilder?file=app%2Fapp.component.ts, changed it to bootstrap.

Today I upgraded after a year all libraries.

Initially I had
@angular/core@15.2.0
@ngx-formly/core@6.1.1

Upgraded in two stages:
@angular/core@16.2.12: working
@angular/core@17.0.9: working

Using @angular/core@17.0.9, after the upgrade to
@ngx-formly/core@6.2.2: not working
@ngx-formly/core@6.1.6: not working
@ngx-formly/core@6.1.5: not working: core: delegate FormArray creation to FieldArrayType only (7d02313), closes #3576
@ngx-formly/core@6.1.4: working
@ngx-formly/core@6.1.1: working

I  have a further look next week.

**Comment by FritzHerbers** [comment]
Using prePopulate instead of onPopulate fixed the issue.

Forked @smile2014 stackblitz example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap-xy4mfs?file=src%2Fapp%2Fruleset-rules-type%2Fruleset-rules-type.component.ts,src%2Fapp%2Fapp.component.html

@aitboudad, fyi, can you maybe further explain what caused the issue, and/or what is best-praxis for using prePopulate and onPopulate (for what can they best be used, or shouldn't be used; what is allowed in the methods).

**Comment by smile2014** [comment]
@FritzHerbers  Thank you very much, the issue has been resolved
