### ISSUE TITLE
get file json schema from http get

### ISSUE THREAD

**Issue by marziaa91** [ngx-formly/ngx-formly#3796]
Hello everyone!

I tried to get a json schema file with "http get" as in the example I found on the documentation but it did not work. 

The error is:  "is not valid JSON". The json I have is a schema json so it is normal for it to fail.
All examples I see in the documentation already have the json schema within the frontend.  
Has anyone ever received a server-side json schema?

**Comment by kenisteward** [comment]
What exactly are you doing with the json schema to do an http get inside of it?

Do you mean with $ref? Do you mean with a conditional or validation?

**Comment by marziaantonelli** [comment]
I am using http get to retrieve the json file i saved on s3.

**Comment by kenisteward** [comment]
We would need to know more specifically on how you are setting it up on why
it would fail.
A stackblitz or equivalent would be helpful! Even an example of the schema.

Otherwise the widget keyword is how you change a schema Field's formlyConfig

**Comment by marziaantonelli** [comment]
This is the content of the file: 

`    {
        "label": "Patient info",
        "fields": [
            {
                "fieldGroupClassName": "row",
                "fieldGroup": [
                    {
                        "key": "examId",
                        "className": "col-4",
                        "type": "input",
                        "templateOptions": {
                            "placeholder": "ID",
                            "disabled": true,
                            "label": "ID",
                            "appearance": "outline"
                        },
                        "expressions": {
                            "hide": ({model}) => !model.parentTwo,
                            "props.required": ({model}) => model.parentTwo
                        }
                    },
                    {
                        "key": "indicationToInvestigation",
                        "className": "col-4",
                        "type": "input",
                        "templateOptions": {
                            "placeholder": "Indication to investigation",
                            "label": "Indication to investigation",
                            "required": true,
                            "appearance": "outline"
                        }
                    }
                ]
            }
        ]
    }`

**Comment by kenisteward** [comment]
Yes this is in fact invalid json. If this is a json file and you are trying to load this json file as true json then functions are not allowed of any kind.

You'd have to have a config like this in js or ts

**Comment by marziaa91** [comment]
I didn't understand. Ok it is clear that the content does not respect the json rules but how can I save the file and then receive it in the frontend without changing the content?

**Comment by kenisteward** [comment]
The problem I believe you are running into is json.parse(). This uses the json spec ( which doesn't allow functions ) to parse a json valid string into valid native js data.

If that is a part of the process it just won't work.  

You could instead store it as a js file however and then default export the object from that.

But that begs the question why not just store it in actual code as a variable.

**Comment by marziaa91** [comment]
I don't save the contents of the file directly in the code because the json schema can change completely according to special conditions. I could have many schema json and choose one based on values that the frontend would pass to the backend.
