### ISSUE TITLE
Primeng Dialog Component : `appendTo` property not working

### ISSUE THREAD

**Issue by dai1234cap** [ngx-formly/ngx-formly#3809]
**Description**
I am trying to generate a form inside the [`Dialog`](https://primeng.org/dialog) component from Primeng. **The problem is that when using a Dropdown (select) inside it, the overlay does not work and the dropdown is hidden inside the modal**. The Primeng documentation recommend to use the [`appendTo` propertiy](https://primeng.org/dialog#overlaysinside). 
I have tried to pass the property in my array `FormlyFieldConfig` object in the `props`, but it does not work. Also the there is no concret exemple in the [ngx-formly documentation](https://formly.dev/docs/ui/primeng) and the dropdown exemple suffers the same problem.

_**Is the `appendTo` property from Primeng implemented for ngx-formly ?**_  

Below is the structure of my object as I am trying to pass the `appendTo` property:
`
{
      fieldGroupClassName: 'flex',
      fieldGroup: [
        {
          className: 'field-item',
          key: 'site',
          type: 'select',
          props: {
            appendTo: 'body',
            options: [
              {
                value: '',
                label: '--',
              },
              {
                value: 'site1',
                label: 'Site 1',
              },
              {
                value: 'site2',
                label: 'Site 2',
              },
            ],
          },
        },
      ],
    },
`
Below is a screensht from the ngx-formly documentation which is similar to my issue : 
![image](https://github.com/ngx-formly/ngx-formly/assets/120456666/214fa418-71b2-4899-af83-0b712885e24d)

**Your Environment**

- Angular version: 16.0.4
- Formly version: 6.2.2

Thanks in advance !

**Comment by dai1234cap** [comment]
Hi again. Any feedback ? Maybe can someone tell me if it is a problem form ngx-formly or from Primeng side ? 
I wondering how hard it would be to fix it myself.
Don't hesitate if you need further information on this issue ! Thanks !

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
