### ISSUE TITLE
Support for Angular V17?

### ISSUE THREAD

**Issue by EdenWoo** [ngx-formly/ngx-formly#3811]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by json-derulo** [comment]
I am able to use ngx-formly in my Angular 17 project. What exactly are you missing?

**Comment by madupuis90** [comment]
I just found this issue while googling. 

Angular 17 doesn't come with app.module and @angular/cdk installed by default. 

By following the formly Getting started guide, the first command is to apply a schmatic to you r project, this will fail with a fresh angular 17 project.

**Comment by NateRadebaugh** [comment]
When I think about support for angular 17, I'm considering:
* can I install ngx-formly alongside angular 17 without using "npm install --force" flag?
* can I use standalone components?

It looks like the standalone components support is planned for v7 of ngx-formly whenever that may be released:
https://formly.dev/docs/guide/faq/#formly-standalone-components-support

There is some supported linked, but it's unclear whether this will support proper code splitting for lazy-loading or not:
https://github.com/ngx-formly/ngx-formly/issues/3721

**Comment by ptandler** [comment]
In addition to standalone components, it would be quite cool to add support for signals, see https://github.com/ngx-formly/ngx-formly/issues/3730

**Comment by Alwin-Arokiya-Raj-J** [comment]
how to use ngx formly in angular 17

**Comment by Joe7oo7** [comment]
how to use ngxformly in angular 17+ as standalone ,without module file,is it posible?
