### ISSUE TITLE
Non required properties gets error after typing value and removing it.

### ISSUE THREAD

**Issue by jdreSAG** [ngx-formly/ngx-formly#3813]
**Description**
Issue related to my previous issue https://github.com/ngx-formly/ngx-formly/issues/3757
There is a new issue on 6.2.0 (but is also present in 6.2.2).
I'm creating field config with FormlyJsonschema toFieldConfig method. Form consists of one field- of type number, no validation or required flag. I run the app, type something in the input field, then I remove input value.
Result: control has error
`  "type": {
    "schemaType": [
      "number"
    ]
  }
`
Expected: no errors should exist for empty value
**Minimal Reproduction**
open https://stackblitz.com/edit/angular-a2uvhd-5eh1gw?file=src%2Fapp%2Fapp.component.ts
type anything in the input and remove it all (with backspace). See errors displayed at the bottom of the page.

**Comment by ligajan** [comment]
I had the same problem. Creating a custom field type with the name "number" also caused this error.  I don't know exactly why, but renaming the type to something else helped, so it may be a temporary solution.
A similar error also occurs when converting from jsonSchema and the main object is of type "array".

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
