### ISSUE TITLE
Possible Configuration help ? Need to use regular Angular Material Components instead of MDC components

### ISSUE THREAD

**Issue by tonyquiroga** [ngx-formly/ngx-formly#3814]
**VERSIONS**: 
Angular: 16.2.1
Angular Material: 16.2.1
Formly Core and Formly Material: 6.2.2

**ISSUE**
When rendering basic form fields using Formly, the generated material components are of the MDC version. This causes the styles not to match what the components look like elsewhere in the application because the rest of the application uses the non-MDC versions:
![example](https://github.com/ngx-formly/ngx-formly/assets/74194761/01eae1c4-8c30-499b-9626-0489b2f5eb00)

In the screen shot above, the top form field is generated using Formly and if I inspect the element further, I see all 'mdc' classes being used. The bottom form field is generated without Formly and uses classes that are not the 'mdc' versions. This is the output I would like to see. 

Any help/insight on this matter is greatly appreciated.

**Comment by aitboudad** [comment]
use `@ngx-formly/material-legacy`
