### ISSUE TITLE
Value displayed over label when using an asynchronous filled model

### ISSUE THREAD

**Issue by NevenViguie** [ngx-formly/ngx-formly#3815]
Hello,

I am using ngx-formly with custom field types and I have an issue with some of them. The fields are filled with a model that is updated when the request to the DB is complete. However, for some fields formly doesn't update the interface when the value is received and the it is just displayed on top of the label.

![image](https://github.com/ngx-formly/ngx-formly/assets/75068354/925c6bba-0e62-4e73-b8d9-bb0425a29dbb)

But when you click the component the interface is updated : 

![image](https://github.com/ngx-formly/ngx-formly/assets/75068354/6484cece-1bd1-4e0c-9f2d-8503b0457661)

The only workaround I have found is to call a setValue() on the formControl when the value is received, which is not ideal as opposed to just filling the model. If you have any idea where this might come from, I'm open to suggestions. I think this issue started to appear with Angular 14, not 100% sure though.

Here is the template for one of the fields : 
![image](https://github.com/ngx-formly/ngx-formly/assets/75068354/ac47b204-7ba2-4a15-82de-a3f0a558739a)

And the declaration for the field in the screen above : 
![image](https://github.com/ngx-formly/ngx-formly/assets/75068354/43199c01-8435-496c-b158-716cb8ec7a0b)

Unfortunately I fear this would be hard to replicate on stackblitz as the app is pretty complex :/

**Comment by raiworld81** [comment]
It seems like a detectchanges problem on the material component

**Comment by NevenViguie** [comment]
> It seems like a detectchanges problem on the material component

I have tried to execute ChangeDetectorRef.detectChanges() after the model is updated but it didn't to anything...

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, using our `stackblitz` starter

Thanks!
