### ISSUE TITLE
Sonar analysis: big formly forms

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3816]
**Question**

I am working on a large project, with many formly forms, having the length of hundreds of lines sometimes. Sonar analysis shows repetitive code,  as we have many repeating portions (validations, similar fields) accross the components. Do you have any best practices to reduce the number of duplicate lines/blocks especially for these big forms?

Thanks!

**Comment by aitboudad** [comment]
One of the solution is to use virtual scroll [stackblitz.com/edit/angular-rfwvp6](https://stackblitz.com/edit/angular-rfwvp6)

**Comment by zoltanhalasz** [comment]
Thanks for the suggestion, actually the question was about code analysis done by sonar. The code portion of big formly forms in the .component.ts file is just very big and contains many repetitions that are highlighted by Sonar (code analysis) tool, as code duplications. Is there any best practice to reduce the repetitiveness of formly form fields (this.field= { has many repetitive lines})

**Comment by aitboudad** [comment]
https://formly.dev/docs/guide/formly-field-presets
