### ISSUE TITLE
Formly Angular Datepicker Not found

### ISSUE THREAD

**Issue by DanTurco** [ngx-formly/ngx-formly#3817]
**Description**
datepicker is not found and throws an error for formly angular

**Minimal Reproduction**

https://ngx-formly-ui-material-gtjqug.stackblitz.io

Documentation reflects 'datepicker'

https://v5.formly.dev/ui/material

**Your Environment**

- Angular version: 16.2.0
- Formly version: 6.2.2

**Additional context**
ERROR
Error: [Formly Error] The type "datepicker" could not be found. Please make sure that is registered through the FormlyModule declaration.

**Comment by aitboudad** [comment]
you should import  `FormlyMatDatepickerModule`: https://stackblitz.com/angular/qoakkeqeonv?file=src%2Fapp%2Fapp.module.ts

**Comment by DanTurco** [comment]
Thanks! That was is, you have to force the import, its not detected from the root FormlyMaterialModule

this was the magic piece
```import { FormlyMatDatepickerModule } from '@ngx-formly/material/datepicker';```

**Comment by ansarbachir** [comment]
Hello,
I have issue with type:file
is there any solution?
Thank you
