### ISSUE TITLE
Missing model in array context ?

### ISSUE THREAD

**Issue by Mfron-42** [ngx-formly/ngx-formly#3819]
Sorry, if not, but i guess its a bug ?

```
    {
      key: 'cats',
      type: 'repeat',
      expressionProperties: {
        trolo: (...lul) => console.log(lul),
        repeatCount: 'model', // cant access to model
      }
   }
```
   
   base:
   https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts
   
   I feel like my expressions should be able to access to model, which should be the root representation of my form ?

**Comment by Mfron-42** [comment]
`fields: FormlyFieldConfig[] = [
    {
      key: 'numberOfCats',
      type: 'input',
      templateOptions: {
        type: 'number',
        label: 'How many cats do you have ?',
        min: 1,
        required: true,
      },
      expressionProperties: {
        trolo: (...lul) => console.log(lul),
        "templateOptions.label": 'model.numberOfCats', // correctly set label
      },
    },
    {
      key: 'cats',
      type: 'repeat',
      expressionProperties: {
        trolo: (...lul) => console.log(lul),
        repeatCount: 'model.numberOfCats', // [Expression "repeatCount"] Cannot read properties of undefined (reading 'numberOfCats')
      },
  }`

**Comment by aitboudad** [comment]
I think you would like to get the parent model value, please use the following solution:

```
repeatCount: 'field.parent.model',
```

Related to:

- https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614
- https://formly.dev/docs/guide/faq#how-to-access-to-the-parent-field-model-value

**Comment by Mfron-42** [comment]
Yeah thx, i wrote my own repeat, since i generate my form using AI inspired from your syntax, since its pretty well known by openai models. But i cant write any "workaround", i cannot explain every specificities, and he expect to have access to model on the repeat field.

I also changed the expression service, but please, can you take care to export more symbols, so i can extends of some of your services / access to entities / methods you use. I have to fix a specific version and export needed symbols / copy & past some of your files.

Thanks for your amazing work, also, im trying to modify a bit your library, without writing any js, keeping every functionality (using jsonata instead of js expressions, since its generated, it must be 'safe')

Idk if its the right place for this feedback but thanks anyway for your work again @aitboudad  ˆˆ
