### ISSUE TITLE
Evaluation of arrow functions in expressions in v6

### ISSUE THREAD

**Issue by chris-ace** [ngx-formly/ngx-formly#3820]
**Description**
When working with arrow functions, the new `expressions` in v6 seem to work substantially differently than the previous `expressionProperties` of v5. The problem occurs when a variable is changed by code that does not directly affect the form but should indirectly affect it as an expression would evaluate differently.

This change is a problem to my project as we heavily made use of dynamic expressions using arrow functions.
BehaviourSubjects seem to work fine, but that would mean a lot of refactoring effort. At this state we cannot upgrade to v6.

**Minimal Reproduction**
`'props.disabled': () => this.inputIsDisabled` does not seem to register changes made to the variable from outside the form,
This used to work in v5.

I prepared two stackblitz demos using the expressions examples found for Formly v5 and v6.
Formly v5: https://angular-yhetv7.stackblitz.io
Formly v6 (buggy): https://angular-yobrug-6fniuc.stackblitz.io

Clicking the 'switch' button causes the disabled state to always correctly switch in v5.
In v6 it only always correctly works when using the observable. Using arrow functions it seems to only work once and afterwards only reevaluates when changes are made to the model in another field.

Also, using the in v6 marked as `@deprecated` `expressionProperties` and `templateOptions` produces the same outcome.

**Your Environment**
My project:
- Angular version: ^17.0.0
- Formly version: ^6.2.2

Demo v5:
- Angular version: 7.2.16
- Formly version: 5.12.7

Demo v6:
- Angular version: ^14.0.0
- Formly version: ^6.0.0

**Additional context**
None.

**Comment by aitboudad** [comment]
I think it related to https://formly.dev/docs/guide/migration#4-checkexpressionon-is-set-to-modelchange-by-default , the better option is to pass an observable instead.

**Comment by chris-ace** [comment]
Thank you for the quick response.
Definitely my bad, I failed to notice this in the migration guide!
This fixed it in the provided demos, but in my project, adding a call of **`changeDetectorRef.detectChanges();`** after updating the respective property was also necessary to have the arrow functions working again.

I agree, observables would be the better solution, but the time it takes to refactor legacy code can be too much at some point.
