### ISSUE TITLE
How can i use Materials theme?

### ISSUE THREAD

**Issue by martyandreas** [ngx-formly/ngx-formly#3822]
Hi
I have an app where I currently use reactiveforms with materials. I have completely restyled the materials using a theme (https://material.angular.io/guide/theming).
If I now install ngx-formly with materials, the standard materials theme is used for all the formly form fields. What can I do so that Formly also recognises the Materials theme that I have created?

**Comment by martyandreas** [comment]
I found out that I am missing a custom class on the mat-form-field itself. Is it possible to add a class on the mat-form-field instead of on the formly-field?

**Comment by aitboudad** [comment]
> Is it possible to add a class on the mat-form-field instead of on the formly-field?

no, if you like to control that part you'll to override the `form-field` wrapper.
