### ISSUE TITLE
How can set null or '' value to my type via Expression?

### ISSUE THREAD

**Issue by kingjin53** [ngx-formly/ngx-formly#3823]
**Description**
I have customized a type using Formly, similar to a text input field. Now, I want to clear my custom type when a different value is selected in a dropdown Select box. I've written this logic using the Expression property. However, I've noticed that when I return '', null, or undefined in the expression, the system encounters errors, and sometimes it doesn't update as instructed to be empty or null.

**Minimal Reproduction**

**Your Environment**

- Angular version: 16
- Formly version: 6

**Additional context**
My TS Code as below：
   expressions: {
        'model.C_TENOR_TYPE': (field: FormlyFieldConfig) => {
          if (field.model.C_TENOR_TYPE=== 'A' || field.model.C_TENOR_TYPE=== 'B' || field.model.C_TENOR_TYPE=== 'C') {
            return '';
          }
          return field.model.C_TENOR_TYPE;
        },

**Comment by aitboudad** [comment]
see https://formly.dev/docs/guide/expression-properties#3-get-notified-about-an-expression-changes
