### ISSUE TITLE
get fields by instanceof the type class

### ISSUE THREAD

**Issue by its-dibo** [ngx-formly/ngx-formly#3825]
I want to select the fields of a specific custom type, by the type instance

```
fields = [
  { type: CustomTypeClass, ...}
]
```
then, 

```
this.fields.filter(el => el.type instanceof CustomTypeClass) // 0
```

**Comment by aitboudad** [comment]
Formly support passing the component class to field type since `v6`:

```
fields = [
  { type: FieldTypeClass }
]
```

**Comment by its-dibo** [comment]
yes, but the issue is that the result is always zero
