### ISSUE TITLE
Error CSS form

### ISSUE THREAD

**Issue by Meddevyahoo** [ngx-formly/ngx-formly#3826]
Hello, 
I updated my project from angular 14 to angular 15 but I used a legacy version of angular material , also I have the migration of the component ngx-formly to 6.1.1 and I used ngx-formly/material-legacy, now I have a problem with the alignment of the forms , the theme is good but the alignment is not good, each input in a line but before was two input in each line.

form before migration: 

![image](https://github.com/ngx-formly/ngx-formly/assets/152080160/1097b136-86e4-49b7-9769-6487dbe8166f)

form after migration:

![image](https://github.com/ngx-formly/ngx-formly/assets/152080160/5b76cef8-f05a-4dcb-8942-40d5854ab99f)

so problem as exists in the second image is that each input in a row and that is an impact after migration

css example of code:

`		
 .formly-container {
      display: grid;
      &.formly-container-step2, &.formly-container-step3 {
        grid-template-columns: 100%;
        @media (max-width: 1600px) and (min-width: 1200px) {
          grid-template-columns: 50% 50%; //error here
            grid-gap: 10px;

        }
        grid-row-gap: 5px;
        height: auto;
      }
}
`

where is this solution please

**Comment by 627721565** [comment]
您好，邮件已经收到，查阅后会尽快给您回复！
