### ISSUE TITLE
Upgrading to NG14 and Formly v6 - Errors thrown on field focus

### ISSUE THREAD

**Issue by timhemendinger** [ngx-formly/ngx-formly#3828]
Hi, I'm in the process of investigating what changes would be needed to upgrade Formly from v5 to v6, along with moving up to Angular 14 from 13.

Locally I've been able to upgrade both of them and make some changes to allow the application to work consistently, however there's one issue that I haven't been able to figure out. Whenever I focus in on any of the form inputs I get an error: _"this.props.focus() is not a function"_.

![image](https://github.com/ngx-formly/ngx-formly/assets/4564786/afaa7b7c-d99c-4884-9be2-ee531898e3b3)

Any idea what might be causing this? I've tried removing settings from the module and a number of other potential solutions with no luck. Thanks.

**Comment by timhemendinger** [comment]
Figured this out. I had `focus: false` in all of the fields' `templateOptions` objects in my JSON. Removing them fixed the issue,

**Comment by aitboudad** [comment]
`focus` inside `templateOptions / props` expect a callback value and not a boolean value.
