### ISSUE TITLE
How show/hide element in V6 using a button. 

### ISSUE THREAD

**Issue by pacocsfs** [ngx-formly/ngx-formly#3829]
**Question**

I'm trying to open a modal following this example here -> https://stackblitz.com/edit/angular-formly-modal-egndbr?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fmodal-input.component.ts

However the modal is not showing after clicking the open button. It seems the onClick changes the flag (emailModal) to true but the modal is not showing. I tried using simple input to show/hide, still not working. 

I'm using V6, so I changed hideExpression to expressions: {hide ...}. But still not working. It hides the element when the form loads but doesn't show when clicking in the button. 

My schema is nested. I'm using the stepper, with 4 fieldGroups. The last group is where I need this feature. 

It seems the hideExpression from the field that has the button to open the modal only fires after keydown/keyup event in the the modal-input field. It doesn't fire when emailModal variable changes value.

I'm using:
Angular 16
Formly 6 / Material

Thanks.

**Comment by aitboudad** [comment]
in order to detect `emailModal` property changes, please use one of the following solution:
1. Use observable value
2. Use [formState](https://formly.dev/docs/examples/form-options/form-state/)
3. Manually call detect changes: `this.options.detectChanges` or `this.options.checkExpressions`
