### ISSUE TITLE
Content Security Policy script-src 'self' violation

### ISSUE THREAD

**Issue by anil4kral** [ngx-formly/ngx-formly#3831]
**Description**
I am trying to implement script-src 'self' Content Security Policy. Browser is throwing an error because of a Function call. Can you have a look at this one?
![image](https://github.com/ngx-formly/ngx-formly/assets/13153008/c67b1094-36f0-4a4b-8e55-1e1739a65a9e)
file name: ngx-formly-core.mjs line 1516

![image](https://github.com/ngx-formly/ngx-formly/assets/13153008/15c887a3-7e18-4796-af76-735c3026c10c)

Versions
"@ngx-formly/core": "6.0.4",
"@ngx-formly/kendo": "6.0.4",

**Comment by aitboudad** [comment]
Duplicate of #2537
