### ISSUE TITLE
Input type number on PrimeNG component

### ISSUE THREAD

**Issue by dimosthenis-k** [ngx-formly/ngx-formly#3834]
**Description**
When generating a form through a JSON Schema, the fields generated by declaring a property of type `number` emit a string instead of a floating point number, causing validation to fail.

**Minimal Reproduction**
Cannot reproduce on Stackblitz since loading the default PrimeNG template throws **ENOENT: No such file or directory., '/dev/null'**. 
More on that [here](https://github.com/stackblitz/core/issues/1442).

- Input JSON
`{
  "schema": {
    "id": "http://sample.com/sample-number-form",
    "title": "Number Test Form",
    "properties": {
      "NumberInput": {
        "type": "number",
        "title":"Simple Number Input"
      }
    }
  }
}`

- Generated Form

![image](https://github.com/ngx-formly/ngx-formly/assets/86926621/90593f22-b766-4b10-9237-f3a5cab15199)

**Environment**

- Angular version: 17.0.2
- Formly version: 6.2.2

**Additional context**
It is apparent from the interpolation of `form.value` on the right that the value emitted is a string, as opposed to a number, or more specifically, a floating point number, which is what the `number` type is supposed to represent in the JSON Schema syntax.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
