### ISSUE TITLE
Auto Increment in Array field

### ISSUE THREAD

**Issue by LeoKuenne** [ngx-formly/ngx-formly#3836]
**Question**

We are using formly to generate a list of vlans. The vlan all have to be unique, so the names have be different and the ids have to be different. We are using a JSON as form definition.

To check for the uniquness of the vlans, we already created a validator which checks the hole array.
When adding multiple items at once, the default values get used. This results in an error because the names and ids are the same.

So we want to implement an automatic increment of the vlan id and an automatic generated name like  `VLAN${vlan.id}`.
We already tried it with a extra validator but the `control.value` property seems to be not reactive.

Is there any hint to this how we can accomplish this?

Stackblitz:
[https://stackblitz.com/edit/ngx-formly-ui-bootstrap-lu2t71](https://stackblitz.com/edit/ngx-formly-ui-bootstrap-lu2t71)

**Comment by aitboudad** [comment]
use custom extension https://formly.dev/docs/guide/custom-formly-extension/
