### ISSUE TITLE
Form level validators get overwritten by Formly

### ISSUE THREAD

**Issue by chris-ace** [ngx-formly/ngx-formly#3841]
**Description**
When I call `.addValidators([...]);` on the form I use in the formly-form, the validators seem to get cleared at some point and have to be added at a later time for them to work.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-qzxrj2-168x1g?file=src%2Fapp%2Fapp.component.ts

**Your Environment**
- Angular version: 14
- Formly version: 6

**Comment by aitboudad** [comment]
We do not recommend that approach in Formly please check our doc of how to pass a custom validator:

- https://formly.dev/docs/guide/validation
- https://formly.dev/docs/examples/validation/custom-validation
