### ISSUE TITLE
UniqueItems Error: Maximum call stack size exceeded with json schema

### ISSUE THREAD

**Issue by Steb95** [ngx-formly/ngx-formly#3842]
**Description**
Hi, I'd like to report a possibile bug (I don't know if it has been already reported). Using the json-schema, if there is an array field which items are nested objects (that is, objects in which at least one property is another object), if we set `uniqueItems` to `true` in the array field, an error occurs when typing in the input field.

`ERROR Error: Maximum call stack size exceeded`

I've tried also to use a select with `oneOf` and in this case the error is thrown when changing the select value.

```
{
    type: 'object',
    properties: {
        simpleList: {
            title: 'My list',
            type: 'array',
            uniqueItems: true,
            items: {
                title: 'My Item',
                type: 'object',
                properties: {
                    'item-prop-1': {
                        title: 'My Prop 1',
                        type: 'object',
                        properties: {
                            'sub-prop': {
                                type: 'string',
                                title: 'Sub Prop',
                            },
                        },
                    },
                },
            },
        },
    },
}
```

If we remove the `uniqueItems: true,` prop, the error doesn't show anymore.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-chgmrs

To show the error, add a new item and start typing in the input field.

![formly](https://github.com/ngx-formly/ngx-formly/assets/47389399/c86589cc-a178-4171-9d00-a346c2b1699b)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
