### ISSUE TITLE
FormState disable, hide option is not applied anymore

### ISSUE THREAD

**Issue by N2K02** [ngx-formly/ngx-formly#3843]
Upgraded from 6.0.0-next.9 to 6.2.1, where in a form I have formState: { disabled: true } on the start of the form,
after which i have some logic to hide some fields in a RepeatTypeComponent. Even if the repeated field was set to hide if disable, it still shows the field as disabled instead of hiding it in the UI. 

![image](https://github.com/ngx-formly/ngx-formly/assets/56496952/21408936-3a2f-4a31-a42e-3b9fe9b74278)

- Angular version: 13.2.3
- Formly version: 6.2.1

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by N2K02** [comment]
Hi @aitboudad  

unfortunately I'm not able to reproduce, as the logic is quite complex, with a middleware service generating the json schema, and different subscriptions in the oninit method,

for now we have switch back to the beta4 and everything is working as expected on angular 13, we are not expecting to upgrade soon to newer angular version. if we encounter issues with the hide when we upgrade will report so.

Thanks again.
