### ISSUE TITLE
Uint8Array value is broken

### ISSUE THREAD

**Issue by pct-cclausen** [ngx-formly/ngx-formly#3850]
**Description**
I am trying to manage a small file inside of a formly form.

For this I created a file-form-field which manages its value as a Uint8Array.

Formly somehow breaks this value, the value I get from the model bound to formly seems to be an incorrectly cloned version of the Uint8Array that cannot be cleanly accessed anymore.

**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-zjgnq3?file=src%2Fapp%2Fapp.component.ts

Open the console, click the SET! button.

As you can see the value in this.model.foobar does not have the right prototype.toString result anymore.

the value in this.form.value is unaffected.

Trying to access values like byteLength on the broken Uint8Array causes an error.

**Your Environment**

My own environment is Angular 17.0.1 with formly 6.2.2
The Stackblitz uses Angular 16 with formly 6.1.4, it was based on a link in the bug-template.

**Additional context**
Skimming a bit of formly code, I found this clone() function https://github.com/ngx-formly/ngx-formly/blob/d597c0051d4fe6fa6ba0f9685226ab4ba215891d/src/core/src/lib/utils.ts#L153
It looks like running a Uint8Array through that function may cause this problem, but that is just a guess.
I also don't quite understand how the code may reach it, as the path I looked at needs a config.extra.immutable setting, of which I dont know what it is for or what value it might have.

If that clone function is run a lot for some reason it might also explain why performance quickly degrades for larger file-sizes.
Not that I want to manage huge files, but it's still a bit weird that having loaded a 1mb file into the uint8array field causes typing into an unrelated filed to lag.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
