### ISSUE TITLE
Error install for Ionic UI 

### ISSUE THREAD

**Issue by jeslomo** [ngx-formly/ngx-formly#3851]
**Description**
Error in install for "Ionic UI". 

When install with Angular 17, Ionic 7 (@ionic/angular ^7.0.0) crash with: 

```
npm ERR! Found: @ionic/angular@7.0.0
npm ERR! node_modules/@ionic/angular
npm ERR!   @ionic/angular@"7.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @ionic/angular@"^6.0.0" from @ngx-formly/ionic@6.2.2
npm ERR! node_modules/@ngx-formly/ionic
npm ERR!   @ngx-formly/ionic@"^6.2.2" from the root project
```

**Minimal Reproduction**
On terminal with Node 18 and latest Ionic CLI:

- ionic start 
- --> No use wizard
- --> Framework: Angular
- --> Name: Test
- --> Template: Tabs
- --> NgModules or Standalone Components: NgModules
- npm install @angular/forms @ngx-formly/core @ngx-formly/ionic --save
- --> Crash!

**Your Environment**

- Angular version: ^17.0.0
- Formly version: ^6.2.2
- @Ionic/angular: ^7.0.0

**Additional context**

I thing that this PR (https://github.com/ngx-formly/ngx-formly/pull/3845) add "@ionic/angular": "^6.0.0 || ^7.0.0" in package.json and this not working properly.

<img width="1004" alt="Captura de pantalla 2024-01-22 a las 0 55 54" src="https://github.com/ngx-formly/ngx-formly/assets/5887705/af9c57c2-82f5-4c2b-9bf6-2d3d9e8ff561">

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.0](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.0) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
