### ISSUE TITLE
Formly Reset the Errors on Focus Out for Prime Input Mask

### ISSUE THREAD

**Issue by DSailokesh** [ngx-formly/ngx-formly#3852]
Formly Reset the Errors on Focus Out for Prime Input Mask

https://stackblitz.com/edit/angular-ljcdzn-3r3fwu?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Finput-mask.component.ts,src%2Fapp%2Fapp.component.html

By default, I have set the invalid error to true on model changes to the inputMask field and input field. When we enter the value and focus out, the error bound to the inputMask is vanishing, whereas for the input field, it is retaining the error .

**Comment by DSailokesh** [comment]
@aitboudad  can you help on above issue .

**Comment by aitboudad** [comment]
The issue is not from Formly side, Prime Input Mask clear the existing validation when `unmask` is passed
