### ISSUE TITLE
proposal (json-schema): use relative path in the service within the @ngx-formly/core

### ISSUE THREAD

**Issue by hehoo** [ngx-formly/ngx-formly#3857]
**Question**

In our project, we must ensure the coexistence of two versions(V5 and V6) of ngx-formly. Therefore, we used the npm alias to install version 6 by 
`npm install @ngx-formly/core-v6@npm:@ngx-formly/core@6.2.2 --save`

![image](https://github.com/ngx-formly/ngx-formly/assets/1418392/e1986f43-188d-48a6-8b59-53e084df46ba)

However, we discovered that the json-schema service `formly-json-schema.service.ts` uses these imports
<img width="440" alt="image" src="https://github.com/ngx-formly/ngx-formly/assets/1418392/f207c393-b461-48b4-ac6d-cc6fa9c70f2d">
and
<img width="399" alt="image" src="https://github.com/ngx-formly/ngx-formly/assets/1418392/33fc76c5-fe7e-4d5c-9875-c0c76a572287">

Which causes it to import code from the older version, V5. 

Since the service is bundled in @ngx-formly/core, we are not sure but hope to be able to import these methods and the type using relative paths:
<img width="644" alt="image" src="https://github.com/ngx-formly/ngx-formly/assets/1418392/caec4676-13c9-433b-8c62-9ff66615c18a">

This way, we can resolve the issue of coexisting multiple versions.

**Comment by hehoo** [comment]
@aitboudad How do you think this proposal? If you agree with it, I can create a PR for it. Thanks

**Comment by hehoo** [comment]
@aitboudad Any thought on it?

**Comment by aitboudad** [comment]
@hehoo I suggest to use `patch-package`.
