### ISSUE TITLE
ionic input label missing with `type: 'number'`

### ISSUE THREAD

**Issue by emeryao** [ngx-formly/ngx-formly#3859]
**Description**
```typescript
{
   key: 'someKey',
   type: 'input',
   props: {
    type: 'number',
    label: 'Some Label',
    placeholder: `Please input`,
  },
}
```
field with config above has no label on number type input using `@ngx-formly/ionic@6.3.0`

introduced with #3845 and the number type template was missed [here](https://github.com/ngx-formly/ngx-formly/pull/3845/files#diff-2babb4386ae92e4cb3ad123b089476aeacd6d70074b4118800355265184bd5d2R22)

**Workaround**
add `legacyLable: true` for number type inputs
```typescript
{
   key: 'someKey',
   type: 'input',
   props: {
    type: 'number',
    legacyLabel: true, // 👈
    label: 'Some Label',
    placeholder: `Please input`,
  },
}
```

**Your Environment**

- Ionic version: 7.7.0
- Angular version: 17.1.2
- Formly version: 6.3.0

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.3](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.3) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
