### ISSUE TITLE
Custom Type leads to 'mat-form-field must contain a MatFormFieldControl' with Formly v6

### ISSUE THREAD

**Issue by hiqs-chris** [ngx-formly/ngx-formly#3860]
**Description**
I upgraded Angular to V17 and Formly from Version 5 to 6. After the upgrade my entire Form is rendered hidden on the page and I get the error 'mat-form-field must contain a MatFormFieldControl' in the console so often that the DevTools of Chrome crashes. 

**Minimal Reproduction**
On Stackblitz I was able to figure out that my custom input leads to the error. But the rendering works just fine.

https://stackblitz.com/edit/angular-ivy-15-scss-wch1of

**Your Environment**

- "@angular/core": "^17.0.9",
- "@angular/forms": "^17.0.9",
- "@angular/material": "^17.0.5",
- "@ngx-formly/core": "^6.3.0",
- "@ngx-formly/material": "^6.3.0",
- "@ngx-formly/schematics": "^6.3.0",

**Additional context**
In the real Application the FormConfig comes from an API so replacing the deprecated attributes is currently not an option.

**Comment by hiqs-chris** [comment]
Here is an screenshot from within the actual application. As you can see the DOM-Elements are present but somehow hidden or invisible and therefore unusable. 

![image](https://github.com/ngx-formly/ngx-formly/assets/147066218/e4234928-74e1-4c2a-9203-bc537eb1e823)

**Comment by hiqs-chris** [comment]
Alright, found a Workaround. Switch to ngx-formly/bootstrap and the forms renders again as expected. Not so pretty but at least functional. So the error has to be in ngx-formly/material. With that UI package all my forms fail to render properly. Hope there will be a fix for that.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/3690#issuecomment-1551344508
