### ISSUE TITLE
Custom wrapper, required label not removed until focus control

### ISSUE THREAD

**Issue by bmickoski** [ngx-formly/ngx-formly#3863]
**Description**
I am using custom wrapper. In some scenarios some controls are marked as required depending on use case (manually adding Validations.required). 

**Minimal Reproduction**
https://stackblitz.com/edit/angular-hnhdlf?file=src%2Fapp%2Frepeat-section.type.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fform.extension.ts,src%2Fapp%2Fcustom-wrapper%2Fcustom-wrapper.component.ts,src%2Fapp%2Fcustom-wrapper%2Fcustom-wrapper.component.html

To reproduce:

just check Email radio button (i know it it hidden but Email , Phone and Mail are radio buttons. 
Required label will be shown on right side.. enter some value in email input.. and then select Phone... Email required label is not gone until  i focus email input... 

**Your Environment**

- Angular version: 16.2.1
- Formly version: 6.1.1

**Additional context**

**Comment by aitboudad** [comment]
better rely on `props.required` instead which will detect changes and trigger the view rendering or you may need to call `ChangeDetectorRef.detectChanges()` manually.
