### ISSUE TITLE
error with configuration as json schema & multiselect

### ISSUE THREAD

**Issue by evamueller** [ngx-formly/ngx-formly#3864]
**Description**
If the configuration is read in as a json schema and defined as "select" and "multiple" via the map function, errors appear in the console and the input field does not work.
The problem only exists in connection with array and multi-select

**Minimal Reproduction**
[stackblitz](https://angular-kuxmzz-4fwqr4.stackblitz.io)

**Your Environment**

- Angular version: 16
- Formly version: 6.3.0

**Additional context**

**Comment by aitboudad** [comment]
To enable select for array type, use the following config:

```ts
{
  type: 'object',
  properties: {
    options: {
      title: 'Options',
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "enum": [
          "Option 1",
          "Option 2",
          "Option 3"
        ]
      }
    },
  },
}
```
