### ISSUE TITLE
JSON schema $ref field is removed before `this.formlyJsonschema.toFieldConfig` mapping

### ISSUE THREAD

**Issue by nicholasfinos** [ngx-formly/ngx-formly#3865]
**Question**
I am using JSON schema with Formly and have some custom wrappers and types that I would like to map onto my fields when using `this.formlyJsonschema.toFieldConfig`, specifically to render out my custom definitions consistently throughout my form. 

I thought to use the $ref field to do this since it would keep the rendering consistent with the definition, but apparently the mapper removes it in favour of adding the property types as it reaches my map() function. To get around this I've been using the description field on each of my definitions however I'm not fond of this and would rather use the $ref tag instead.

Here's an example:

![Screenshot 2024-02-07 at 3 50 05 pm](https://github.com/ngx-formly/ngx-formly/assets/87622613/359cc02f-7170-4678-b508-cd28b0d22b69)

![Screenshot 2024-02-07 at 3 59 15 pm](https://github.com/ngx-formly/ngx-formly/assets/87622613/2c8917b7-6c0a-40ec-a06b-a6ffd121925b)

Any chance I'm missing something or could we just keep $ref when mapping inside `this.formlyJsonschema.toFieldConfig`?

For reference, I'm currently on v5.12.7 and are using PrimeNG but I think this is still the same in v6

**Comment by kenisteward** [comment]
If you want to define the wrappers on a particular field with the json
schema config way of doing it you can use the widget property.

https://formly.dev/docs/guide/json-schema/#customize-json-schema-output

This allows specific field config for that exact field. Let me know if I
misunderstood your query.

**Comment by nicholasfinos** [comment]
Sweet that helps a lot. I just noticed that the `FormlyJSONSchema7` exists in `src/core/json-schema/src/formly-json-schema.service.ts` but only seems to apply to the bottom level of the JSONSchema7 type and doesn't go through the rest of the sections in the heirarchy. I was wondering if there were any plans to get this type fixed?
