### ISSUE TITLE
Trigger validation when a nested form changes

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3868]
**Question**
I have a formly form that uses a 2 date pickers and a 2 custom types ( FieldType<FieldTypeConfig>). How can I trigger the validation on the outer form when the value of the custom type (which is a form itself) is changed? 

I tried with hooks, onInit within the customtype, on field level, using valueChanges and it doesn't work...

**Comment by kenisteward** [comment]
A stack blitz would be really helpful to see exactly what issue you are
having .

**Comment by aitboudad** [comment]
Better define validation in the parent control which will trigger validation when one of the field is changed.
