### ISSUE TITLE
Selection multiple with material

### ISSUE THREAD

**Issue by os2be** [ngx-formly/ngx-formly#3874]
I use angular with formly 6.1.1 and material

I search to create an select who allow multiple selection

```
const jobName: FormlyFieldConfig = initMultipleSelect(
     'Job type',
     {
        multiple: true,
        type: InputDataAttribut.InputType.select,
        label: 'Job type',
        options: jobTypeList
    });   


export function initMultipleSelect(key: string, props: FormlyFieldProps): FormlyFieldConfig {
    return {
        className: 'select-selector',
        key: `${key}`,
        type: 'select',
        props: props
    };
  };
```

it's like multiple it's unknow

i checked this api: https://formly.dev/docs/api/ui/material/select/ but it don't realy understand it

**Comment by aitboudad** [comment]
It should work normally, passing `multiple: true,` to material select type will enable multi selection.
