### ISSUE TITLE
Mat-expansion-panel bug in firefox

### ISSUE THREAD

**Issue by ngagua** [ngx-formly/ngx-formly#3875]
**Description**
I am using Angular 17.0.6 with Formly ^6.2.2 on Windows 11. I have an Angular Material expansion panel with drag and drop functionality in a repeating component. In Mozilla Firefox, there is a strange behavior where after sorting the fields, one of the panels is automatically opened. I do not encounter the same issue on other browsers.

**Minimal Reproduction**
https://stackblitz.com/edit/zenyr7?file=src%2Fapp%2Foptions.ts

**Your Environment**
- Angular version: 17.0.6 
- Formly version: ^6.2.2

**Additional context**
Mozila:
![mozila-ezgif com-video-to-gif-converter](https://github.com/ngx-formly/ngx-formly/assets/75014232/b388478f-dd86-4c50-8be0-882d5f44e050)
Google chrome:
![chrome-ezgif com-video-to-gif-converter](https://github.com/ngx-formly/ngx-formly/assets/75014232/5007c044-82a9-4637-a8b9-f3eb79ac6a2c)

**Comment by aitboudad** [comment]
I think you should prevent click propagation on drop (it could be the issue I think but not sure), you may also ensure to update Material to the latest stable version maybe if has been fixed from Material side.
