### ISSUE TITLE
how to get the value if The column ownership of a sub table in a list is hidden ??? Thanks...

### ISSUE THREAD

**Issue by suifeng110** [ngx-formly/ngx-formly#3877]
**Description**

**Minimal Reproduction**

https://stackblitz.com/...

**Your Environment**

- Angular version: X.Y.Z
- Formly version: X.Y.Z

**Additional context**

**Comment by aitboudad** [comment]
If you would like to keep the value of hidden field in the mode, pass `false` to `resetOnHide`.
Another option if want just to check its value, use:
```ts
parentField.get('key_of_hidden_field').formControl.value
```
