### ISSUE TITLE
ResetModel - how to not update default value when doing a resetModel

### ISSUE THREAD

**Issue by jamesvn93** [ngx-formly/ngx-formly#3879]
I am using Angular 16.2.12 and Formly 6.3.0 and recently upgraded from Angular 15 and Formly 5

**Question**

Is it possible to do a resetModel call without updating the default values? We have a form that we can populate using a sample model that we use for testing. But since the upgrade to Formly 6 when trying to clear the form using resetModel(); it does not clear the model anymore it just resets it to the default values set by the populate method. is there any other way to do this other than setting each individual component or by having an "empty" model to reset it to?

I made a quick example of how it currently works here:
https://stackblitz.com/edit/angular-1c4vir?file=src%2Fapp%2Fapp.component.ts

Any assistance would be greatly appreciated.

**Comment by aitboudad** [comment]
use `options.updateInitialValue` to restore default value after calling `resetModel`.
