### ISSUE TITLE
Formly/Material: Easy way to move description text?

### ISSUE THREAD

**Issue by fallenturtle** [ngx-formly/ngx-formly#3880]
I'm new to Angular and I'm working on an Angular 16 project using and Formly 6.1.4 with the Material theme/template. Basically what I want to achieve is moving the hint/description text to between the label and the field itself instead of below it. I saw you can create your own custom templates but it seems like a lot of heavy lifting for a noob like me to go that route just for moving the description field. Doing it with CSS is a non-starter because I need the DOM order to match the visual order for 508 compliance.
Is there a relatively easy way to just extend the Formly/Material form-input component in my project to manipulate the output so that the description/hint renders where I want it to and if so, are there any guides?

**Comment by FloppyNotFound** [comment]
I would try to solve this with a little global CSS instead of changing Formly configs.

Like this:
https://stackblitz.com/edit/angular-xdhnbc?file=src%2Fstyles.scss
