### ISSUE TITLE
wrong type for formState

### ISSUE THREAD

**Issue by its-dibo** [ngx-formly/ngx-formly#3884]
`FormlyFormOptions.formState` is defined as `any`, means it can accept any arbitrary value.
also, the [docs](https://formly.dev/docs/guide/properties-options#formstate)  says
> The formState property is passed to all fields and is a mechanism for communicating between fields (without having to mess with your model).
which also means it holds arbitrary value that doesn't mean anything to firmly

but when you pass `formStatus.disabled=true` it disables the form, which means it has been interpreted by Formly, which is not implied neither by the type definition nor the documentation.

```
export interface FormlyFormOptions {
    updateInitialValue?: (model?: any) => void;
    resetModel?: (model?: any) => void;
    formState?: any;
    fieldChanges?: Subject<FormlyValueChangeEvent>;
    showError?: (field: FieldType) => boolean;
    build?: (field?: FormlyFieldConfig) => FormlyFieldConfig;
    checkExpressions?: (field: FormlyFieldConfig) => void;
    detectChanges?: (field: FormlyFieldConfig) => void;
    parentForm?: FormGroupDirective | null;
}
```

it should be changed to

```
formStats: {
  disabled: boolean 
  // other props that are used by Formly
 [key:string]: any
}

**Comment by aitboudad** [comment]
> but when you pass `formStatus.disabled=true` it disables the form, which means it has been interpreted by Formly, which is not implied neither by the type definition nor the documentation.

Not true, in order to disable the form you should use `formStatus.disabled` inside field expression.
If you think the doc should be adjusted, could you please send a PR 🙏 ?
