### ISSUE TITLE
expressionProperties is not working in formlyPrimeng

### ISSUE THREAD

**Issue by Priyadarsini-techriff** [ngx-formly/ngx-formly#3889]
{
      fieldGroupClassName: 'formgrid grid mt-2',
      fieldGroup: [
        {
          className: 'field col',
          key: 'gender',
          type: 'radio',
          defaultValue: 'Female',
          templateOptions: {
            label: 'Gender :',
            required: true,
            options: [
              { value: 'Male', label: 'Male' },
              { value: 'Female', label: 'Female' },
            ],
          },
        },
        {
          className: 'field col',
          key: 'interest',
          templateOptions: { label: 'Interest :' },

          wrappers: ['form-field'],
          fieldGroup: [
            {
              type: 'checkbox',
              key: 'Movies',
              className: 'ui-g-12',
              templateOptions: { label: 'Movies' },
            },
            {
              type: 'checkbox',
              key: 'Cricket',
              className: 'ui-g-12',
              templateOptions: { label: 'Cricket' },
            },
            {
              type: 'checkbox',
              key: 'Music',
              className: 'ui-g-12',
              templateOptions: { label: 'Music' },
            },
            {
              type: 'checkbox',
              key: 'Book',
              className: 'ui-g-12',
              templateOptions: { label: 'Books' },
            },
          ],
          // Custom expression function
          expressionProperties: {
            'templateOptions.required': (
              model: any,
              field: FormlyFieldConfig
            ) => {
              return field.model?.gender === 'Male'; // Set required to true if gender is Male
            },
          },
        },
      ],
    },

whenever i select male the interest field should be required field.but its not working in my case

**Comment by Sankey1506** [comment]
Facing similar issue in Kendo as well.

**Comment by aitboudad** [comment]
see https://github.com/ngx-formly/ngx-formly/issues/704#issuecomment-364661614
