### ISSUE TITLE
Guideline for AgGrid wrapper without formly-field component, model not properly updated

### ISSUE THREAD

**Issue by alexis-landrieu-avanade** [ngx-formly/ngx-formly#3890]
**Question**

We have a lot of custom CellRenderer and we won't be able to use formly-field component. We have created a custom wrapper for AgGrid (like provided example: https://formly.dev/docs/examples/advanced/grid-integration/) and we are using FieldArrayType to update the model. But the model is not properly updated. May you please provide the right way to update the model properly.

In the provided example, we are using native AgGrid cell renderer, when updating stockIdentifier you can press submit button to see both the model and form value in the console.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-7zyh3v?file=src%2Fapp%2Fgrid.type.ts

**Your Environment**

- Angular version: 14.3.0
- Formly version: 6.3.0

**Comment by aitboudad** [comment]
`formly-field` is required in order to track model changes, here is the missing part is you would like to handle it manually https://github.com/ngx-formly/ngx-formly/blob/main/src/core/src/lib/components/formly.field.ts#L348
