### ISSUE TITLE
Hide expression on repeat component breaks defaultValues of nested fields

### ISSUE THREAD

**Issue by gaetanlgce** [ngx-formly/ngx-formly#3891]
**Description**
When using `expressions.hide` on a custom repeating section to conditionnally display it, `defaultValue` is ignored in fields in the `fieldGroup`. If the `expressions.hide` is not present, default values are applied as expected when adding items.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-e9plpt?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Frepeat-section.type.ts,src%2Fstyles.scss,src%2Fapp%2Fapp.component.html

In this example, the `defaultValue: 'Buy eggs',` is not applied as expected because there is the hide expression line 46.

**Your Environment**

- Angular version: 14.3.0
- Formly version: 6.3.0

**Additional context**
It's maybe related to that issue https://github.com/ngx-formly/ngx-formly/issues/2651

**Comment by uagrawal-evertz** [comment]
I am also facing similar issue

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by aitboudad** [comment]
@uagrawal-evertz please open a new ticket with a reproduction example so we may be able to check it further.
