### ISSUE TITLE
How to resetOnHide and refresh/rebuild form to clear values before i save

### ISSUE THREAD

**Issue by liamsmithaha** [ngx-formly/ngx-formly#3895]
**Question**

As stated in title, before i save a form, im setting the field.resetOnHide = true but the fields are already hidden so i have 3 options, hope either of the first two have an answer.

- i need a way to rebuild to form that take the new resetOnHide value to strip them out,

``` 
 public postPutForm() {
    this.msgSvc.broadcast('clearHiddenInput', '');
    this.fields.forEach((field) => {
      field.resetOnHide = true;
    });
    //trying to deep clone in hopes it will rebuild
    this.fields = JSON.parse(JSON.stringify(this.fields));
```
    
- Im aleady emitting out the fields and fieldGroups that i want to clear hidden values, and I've tried patch value but no luck

``` 
export class TwWrapperBaseComponent extends FieldWrapper implements OnInit {
  constructor(
    public msgSvc: MessageSubjectService,
  )

  ngOnInit(): void {
    this.msgSvc.subscribe('clearHiddenInput', () => {
      this.field.resetOnHide = true;
      if (this.field.hide) {
        this.field.fieldGroup?.forEach((c) => {
          c.formControl?.patchValue(null);
        });
      }
    });
```

```
export class twFieldInputComponent extends FieldType<FieldTypeConfig> implements OnInit {
  constructor(public msgSvc: MessageSubjectService) {
    super();
  }
  ngOnInit(): void {    
    this.msgSvc.subscribe('clearHiddenInput', () => {
      this.field.resetOnHide = true;
      if (this.field.hide) {
        this.field.formControl.patchValue(null);
      }
    });
  }
}
```

   
- if none of the first two are valid options i can recursively search and match model and field hidden values but hope there's a more native way

**Comment by DavWe** [comment]
Try do update the fields like this `this.fields = [...this.fields];` that should rebuild and detect changes (based on https://github.com/ngx-formly/ngx-formly/issues/3827).

**Comment by liamsmithaha** [comment]
@DavWe thanks for the reply, i did try that originally, no luck, then the tried deep clone that you see above, also no luck, I've gone ahead with my third approach for now (recursive search) from what I've read everything i did try should have worked, may of been an issue with needing fresh render cycle to start rather than synchronously (since I'm saving right after) so I'm unsure.
