### ISSUE TITLE
PrimeNg - datepicker without numberOfMonths shows empty picker

### ISSUE THREAD

**Issue by srollinet** [ngx-formly/ngx-formly#3897]
**Description**

When using a PrimeNg datepicker without setting the `numberOfMonths` property, the picker component is empty, so the component is not usable.

It should probably default to 1 when not set, so the component can work correctly

**Minimal Reproduction**

https://stackblitz.com/edit/angular-ckrox7?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 14.3.0
- Formly version: 6.3.0
- PrimeNg version: 13.4.1

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
