### ISSUE TITLE
Formly type for select - > type 3 characters and find the option within the dropdown

### ISSUE THREAD

**Issue by zoltanhalasz** [ngx-formly/ngx-formly#3898]
Let's consider the following formly field in a form:
![image](https://github.com/ngx-formly/ngx-formly/assets/42749923/93d1f233-6663-4307-8143-ff42104a8122)

it is using mat select from material library. What I would like is when typing 3 letters on the screen within the options list, to find the best match beginning with those letters, and jump/select in that position. 

Maybe there is already a solution for this, could you provide the link? :)

**Comment by aitboudad** [comment]
You should use autocomplete component instead, you can check Material autocomplete type for example https://formly.dev/docs/ui/material
