### ISSUE TITLE
ionic v8 support

### ISSUE THREAD

**Issue by emeryao** [ngx-formly/ngx-formly#3902]
Hi Team

ionic v8 is released

https://github.com/ionic-team/ionic-framework/releases/tag/v8.0.0

https://ionicframework.com/docs/updating/8-0

and there seems to be some breaking changes for `@ngx-formly/ionic` when I updated to ionic v8 with `@ngx-formly/ionic@6.3.0`

the `radio` component is broken since the `RadioValueAccessor` is [removed](https://github.com/ionic-team/ionic-framework/pull/28386) by ionic

Can we take a look and support ionic v8 

---

Sorry for my poor English 😅

**Comment by Sirioxstar** [comment]
Hi @emeryao  I have the same problem. How did you solve it?

**Comment by emeryao** [comment]
I just rewrite some custom types and wrapper since there is not too much code to cover 😅

**Comment by wustenveld** [comment]
Why hasn't the team reacted to this post yet?

**Comment by siddhant-dev** [comment]
Hi @emeryao can we connect on discord or somepleace I want to talk about your custom wrapper solution as I have wrapped ionic-radio component to formly by extending its FieldConfig class
