### ISSUE TITLE
[help] access the current field

### ISSUE THREAD

**Issue by its-dibo** [ngx-formly/ngx-formly#3907]
```
fields = [{
 key: "example",
 type: "select",
 props:{
  options: data$.pipe(
   //<------- access "field" here
    tap(res=>{ field.required = res.lengh>0 })
 )
}
}]
```

**other solutions**
I tried other solutions, but all of them are not elegant

- access the field after creating the object
```
fields = [{ ... }]
fields[0].props.options = data$.pipe(
 tap(res=>{ fields[0].required = res.length>0 })
)
```

- use init hook: this makes the code got more complicated, all logic of all props are existing in one function
- use expressions: I want to set the initial state only, not watch for each chnges
- use initializer function; not supported by formly
```
fields=[
 ...
  options: (field, model) => data$.pipe( ... )
]
```

**Comment by aitboudad** [comment]
to have access to the field instance rely on `onInit`, check the following example https://formly.dev/docs/examples/other/cascaded-select
