### ISSUE TITLE
Angular Formly with dynamic custom datetime field is not showing validation message on form submit

### ISSUE THREAD

**Issue by sohaibameenvivup** [ngx-formly/ngx-formly#3908]
`ngOnInit(): void {
    this.setFields();
  }

private setFields() {
    this.fields = [
     {
        key: "dateOfBirth",
        type: "custom-date",
        templateOptions: {
          label: "FamilyPay.CreateHolidayClubOrder.EmployeeBirthDate",
          type: "date",
          minAge: this.model.dateOfBirth ? null : 18,
          maxAge: this.model.dateOfBirth ? null : 80,
          translate: true,
          disabled: !!this.model.dateOfBirth,
          required: true,
        },
      },
 ];
}

<ng-content></ng-content>
<form [formGroup]="form">
  <formly-form [fields]="fields" [form]="form" [model]="model"> </formly-form>
</form>

`

Datetime validation is working with Min and Max range but I want to add another validation which validates the date when no value for datetime is selected so It should show a regular message "Date of birth is required" 

That would be great if somebody can suggest something on it. Thanks

**Comment by aitboudad** [comment]
You'll need to define a custom validation type, please check the doc and examples section:
- https://formly.dev/docs/examples/validation/custom-validation
- https://formly.dev/docs/guide/validation
