### ISSUE TITLE
Item insert in a oneOf does not work

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3910]
**Description**
When an array contains a oneOf, inserting a new item loose some model values.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-bet62l-gnrner?file=src%2Fapp%2Fapp.component.ts

Inserting an item after the first array item loose the last item model value. It seems that inserting an item will hide and show the followers which reset the model. More over the new inserted item has the wrong select value in the oneOf.

Many Thanks in advance.

**Comment by aitboudad** [comment]
Hi, I didn't identify the issue in your example
Could you please provide the steps todo in order to reproduce it with expected vs current result?

Thanks!

**Comment by jma** [comment]
Basically, if you run my example, you will see two value in the first array 1 and 2. If you click on the "plus" button on the first item of the array, which means "instert a new item after" the value model of the last element "2" is lost.

**Comment by aitboudad** [comment]
Got it now, so the expected result is: `:[{"entity":1},null,{"entity":2}],` instead of `:[{"entity":1},null,{}],`

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.1](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.1) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
