### ISSUE TITLE
Name Attribute missing in custom Material Field

### ISSUE THREAD

**Issue by tomav123-git** [ngx-formly/ngx-formly#3912]
⭐

@aitboudad Previously i faced an issue with name attribute missing in fields and as per your suggestion i updated to v6.1.7 it is fixed. Now when i added a custom field, same issue occuring. Name attribute missing in custom elements html

**Your Environment**

- Angular version: 14
- Formly version: 6.1.7

We can refer the previous issue in #3684

**Comment by tomav123-git** [comment]
@aitboudad Could you help please? It is related to  https://github.com/ngx-formly/ngx-formly/issues/3684#issue-1707077451

**Comment by aitboudad** [comment]
For custom field, you need to set name explicitly: `[name]="field.name"`

**Comment by tomav123-git** [comment]
Thankyou so much, it woks.
