### ISSUE TITLE
Expression are not getting executed if value is changed in custom component

### ISSUE THREAD

**Issue by Sankey1506** [ngx-formly/ngx-formly#3915]
I am using Formly with Kendo Components.

I have a custom field called switch. On Switch toggle I have to enable or disable the text field.
It used to work in v5 but not in v6.
Do I have to do any additional changes in if has to work in v6.

Here is my minimal reproduction: https://stackblitz.com/edit/angular-b43wet-djjn2p

**Comment by aitboudad** [comment]
It working fine, the issue is in your custom field type. To update a switch value, please rely on formControl

```patch
  @HostListener('click') toggleSwitch() {
    if (!this.props.disabled) {
+     this.formControl.setValue(!this.isChecked);
-      this.model['' + this.key] = !this.model['' + this.key];
    }
  }
```
