### ISSUE TITLE
Wrong default values in arrays

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3916]
**Description**
A wrong default value is present in the formControl

**Minimal Reproduction**

https://stackblitz.com/edit/angular-kwmyzs-pr8dhu?file=src%2Fassets%2Fjson-schema%2Farrays.json,src%2Fapp%2Farray.type.ts,src%2Fapp%2Fapp.component.html

Several wired behaviors are present:

1. If I modify the value of the first element (val1) and I press the clear button, I should retrieve the default value which is "default"
2. If I insert a new item after the first item (first "+" button), I can see the wrong default value on the top of the page. Moreover if I press the clear button of the new inserted item, I got the wrong default value (val2) instead of "default"
3. If I insert a new item at the end of the array everything is ok.

Thanks in advance.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
