### ISSUE TITLE
[question] is there an offitial formly for React/NextJs

### ISSUE THREAD

**Issue by its-dibo** [ngx-formly/ngx-formly#3917]
I like the idea of passing a plain object to the template and Formly generates the corresponding form fields
so, I really need the same idea for NextJs

I saw some projects, but they are not maintained like this one, such as

[formly-js/react-formly](https://github.com/formly-js/react-formly)
[react-formly](https://www.npmjs.com/package/react-formly)

**Comment by aitboudad** [comment]
Only Angular is supported at the moment.
