### ISSUE TITLE
formfields of FormGroup are not getting disabled if formGroup is disabled using expressions

### ISSUE THREAD

**Issue by Sankey1506** [ngx-formly/ngx-formly#3918]
Description:
formfield inside the formGroup is not getting disabled. Fields has to be disabled explicitly using expression.
This seems to be working v5.

Minimal Reproduction:
https://stackblitz.com/edit/angular-gvuzak-thkuew

Other Details:
I have to disable formgroup and its containing fields using only expressions of formGroup.

**Comment by aitboudad** [comment]
disabled property is only taken when the `fieldGroup` has a key else it'll be ignored.
