### ISSUE TITLE
field.expressions not evaluated on model changes when using zoneless angular 18

### ISSUE THREAD

**Issue by atsjo** [ngx-formly/ngx-formly#3921]
**Description**
field.expressions for hide and "props.disabled" are not evaluated on model changes when using zoneless angular 18. It works fine if using zone change detection in v18.

**Minimal Reproduction**
- use formly with material and angular zoneless via provideExperimentalZonelessChangeDetection()
- add expressions for hide or "props.disabled" and observe that they are not evaluated on model changes

**Your Environment**

- Angular version: 18.0.0
- Formly version: 6.3.1

**Additional context**
Everything works fine in zoneless, also with my usage of formly, except for this bug... I found a workaround for triggering expression evaluation manually by adding the following to my formly component, which builds it's field config from a json schema.

```
function checkExpressions(fields: FormlyFieldConfig[]) {
  for (const field of fields) {
    if (Object.keys(field.expressions ?? {}).length) field.options?.checkExpressions?.(field);
    if (field.fieldGroup) checkExpressions(field.fieldGroup);
  }
}

@Component(...)
class FormlyComponent {
  ...
  constructor(private formlyJson: FormlyJsonschema, zone: NgZone) {
    // HACK: need to force checking expressions in zoneless
    if (zone instanceof ɵNoopNgZone) this.form.valueChanges.pipe(takeUntilDestroyed()).subscribe(() => checkExpressions(this.fields));
  }
}
```

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.2](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.2) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by atsjo** [comment]
thanx for the quick fix... now it works in debug, but not in production... I'm guessing this function doesn't work after minification or something similar

```
export function isNoopNgZone(ngZone: NgZone) {
  return ngZone.constructor.name === 'NoopNgZone';
}
```

**Comment by atsjo** [comment]
I can confirm this is the problem, just tested printing ngZone.constructor.name in prod, and it was minified/changed...

so  changing the isNoopNgZone function to using (zone instanceof ɵNoopNgZone) will fix it...
