### ISSUE TITLE
field.expressions not evaluated on model changes when using zoneless angular 18 production builds

### ISSUE THREAD

**Issue by atsjo** [ngx-formly/ngx-formly#3928]
**Description**
There was a fix for this problem https://github.com/ngx-formly/ngx-formly/issues/3921 in 6.3.2, but it doesn't work in production builds because of minification.

**Your Environment**

- Angular version: 18.0.0
- Formly version: 6.3.2

**Additional context**

Pretty sure this can be fixed by changing

```
export function isNoopNgZone(ngZone: NgZone) {
  return ngZone.constructor.name === 'NoopNgZone';
}
```
 to

```
export function isNoopNgZone(ngZone: NgZone) {
  return zone instanceof ɵNoopNgZone;
}
```

**Comment by aitboudad** [comment]
could you please send a PR?

**Comment by atsjo** [comment]
submitted a PR... build and test works
