### ISSUE TITLE
Last element support in repeat section

### ISSUE THREAD

**Issue by glistolin** [ngx-formly/ngx-formly#3930]
**Question**

I want to display checkbox only in the last element of the repeat section. Didn't manage to implement using _hide_ (checkbox field is being displayed in every row) so I'm trying to achieve this using last part of ***ngFor** but cannot get checkbox control

[Stackblitz](https://stackblitz.com/edit/angular-8kbsyr?file=src%2Fapp%2Frepeat-section.type.ts)

**Comment by FloppyNotFound** [comment]
One way to achieve this would be to simply set a CSS class to hide the checkbox by default, set a CSS class to the last element and set this last control to visible via global CSS like this:

https://stackblitz.com/edit/stackblitz-starters-9hbu7r?file=src%2Fformly-field-custom-input.component.ts

**Comment by aitboudad** [comment]
Or rely on `field.parent` which has the current item key:

```ts
{
  type: 'checkbox',
  expressions: {
    hide: (f: FormlyFieldConfig) => {
      const lastKey = f.parent.parent.model.length - 1;
      return f.parent.key !== `${lastKey}`;
    },
  },
  props: {
    label: 'Checkbox',
    required: true,
  },
}
```
