### ISSUE TITLE
event From Remove item in Repeating Section

### ISSUE THREAD

**Issue by tijanisellami-dev** [ngx-formly/ngx-formly#3935]
Hi, 
How can i detect remove item event in Repeating Section to recalculate sum ?
in repeating section i have
@Output() removeSection = new EventEmitter<number>();
onRemove(i: number) {
    this.removeSection.emit(i);
    super.remove(i);
  }
  
  how can i intersept this event in Formly Parent
  it's like this
  
  props: {
                  label: 'dfdfdfdfdfdfd',
                  heading: 'headingOne',
                  collapse: 'collapseOne',
                  dataBsTarget: '#collapseOne'
                },
                wrappers: ['accordion'],
                fieldGroup: [
                  {
                    fieldGroupClassName: 'row',
                    fieldGroup: [
                      {
                        key: 'OurList',
                        type: 'repeatSection',
                        className: 'deletable',
                        props: {
                          label: 'Add item',
                          change: () => this.addToTotal(),
                        },
                        fieldArray: {
                          fieldGroup: [
                            {
                              fieldGroupClassName: 'row',
                              fieldGroup: [
                                {
                                  key: 'type',
                                  type: 'select',
                                  className: 'col-sm-12 col-md-6',
                                  props: {
                                    label: 'Type',
                                    required: true,
                                    options: [
                                      {label: 'one', value: 15},
                                      {label: two', value: 16},
                                      {label: 'Three', value: 17},
                                    ],
                                  },
                                },
                                .......

**Comment by aitboudad** [comment]
You can define your own events by add two new methods for add/remove or rely on `valueChanges` /`field.options.fieldChanges` observable:

```ts
{
  hooks: {
    onInit: (field) => {
      return field.formControl.valueChanges.pipe(
        tap(e => ....),
      )
    }
  }
},
```

**Comment by tijanisellami-dev** [comment]
Thanks, but i woud  intercept an event not add an event
