### ISSUE TITLE
Migration to Formly 6 - formlyHookConfig related issue

### ISSUE THREAD

**Issue by siari1** [ngx-formly/ngx-formly#3936]
Hi,
We are currently migrating Formly version 5 to 6.
With V5, we were using FormlyHookConfig to capture any view changes using afterViewChecked property.
    
_fields.hooks = {
      afterViewChecked : (field: any) => {_

After migration we are seeing an error on compilation. Below is the error. 

**TS2322: Type '{ afterViewChecked: (field: any) => void; }' is not assignable to type 'FormlyHookConfig'. Object literal may only specify known properties, and 'afterViewChecked' does not exist in type 'FormlyHookConfig'. 

afterViewChecked : (field: any) => {**

I have seen from the release notes of 5.7 version that afterViewChecked is deprecated. So how can we fix this error? Please suggest. 
Thank you.

**Comment by aitboudad** [comment]
It has been removed since v6  the main reason was perf and we suggest avoid relying on it, but in case you still would like to use it in v6. Just create a custom wrapper which emit that event.
