### ISSUE TITLE
Integer field causes errors

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3937]
**Description**
Enter a number in a integer type causes errors.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-ngsqqk-hju9jr?file=src%2Fassets%2Fjson-schema%2Farrays.json

Run the stackblitz example and enter a number in "Number". Console errors occurs and when the form is submitted the model is empty. This bug is new with the 6.3.3 version.

**Your Environment**
- Formly version: 6.3.3

**Comment by tyspice** [comment]
I am also experiencing this issue after upgrading to 6.3.3. Specifically, The problem occurs with both 'number' and 'integer' types that are properties of an object within an array type. I do not see the issue when down versioning to @ngx-formly/core v6.3.2.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.4](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.4) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by tyspice** [comment]
I confirm that the issue seems to be resolved in v6.3.4. Thank you!
