### ISSUE TITLE
Maximum call stack size exeeded while using  PimeNg treeselect in formly with formControl

### ISSUE THREAD

**Issue by ayushhRathor-precisely** [ngx-formly/ngx-formly#3941]
I am trying to create a custom formly type to use primeNg TreeSelect , but getting error on selection

***************************
FormLy Config:
  {
        key: 'treeSelect',
        type: 'formlyTreeSelect',
        props: {
          label: 'Tree test',
          placeholder: 'select',
          options:[ {
            key: '0',
            label: 'Documents',
            data: 'Documents Folder',
            icon: 'pi pi-fw pi-inbox',
            children: [
                {
                    key: '0-0',
                    label: 'Work',
                    data: 'Work Folder',
                    icon: 'pi pi-fw pi-cog',
                    children: [
                        { key: '0-0-0', label: 'Expenses.doc', icon: 'pi pi-fw pi-file', data: 'Expenses Document' },
                        { key: '0-0-1', label: 'Resume.doc', icon: 'pi pi-fw pi-file', data: 'Resume Document' }
                    ]
                },
                {
                    key: '0-1',
                    label: 'Home',
                    data: 'Home Folder',
                    icon: 'pi pi-fw pi-home',
                    children: [{ key: '0-1-0', label: 'Invoices.txt', icon: 'pi pi-fw pi-file', data: 'Invoices for this month' }]
                }
            ]
        }]
      }
      },

***************************
      
    custom type template: 
    
                      <p-treeSelect
                    [formlyAttributes]="field"
                    [options]="getOptions(props)"
                    [placeholder]="props.placeholder"
                    [showClear]="props['showClear']"
                    class="d-flex w-100"
                    [formControl]="formControl"
                  >
                  </p-treeSelect>  

     protected getOptions(props: NonNullable<FieldTypeConfig['props']>): any[] {
    return props.options as any[];
  }
  
********************************
  
Error: Error is produced on selecting any child

ERROR RangeError: Maximum call stack size exceeded
    at ngx-formly-core.mjs:165:36
    at Array.map (<anonymous>)
    at clone (ngx-formly-core.mjs:165:31)
    at ngx-formly-core.mjs:180:28
    at Array.reduce (<anonymous>)
    at clone (ngx-formly-core.mjs:174:31)
    at ngx-formly-core.mjs:165:42
    at Array.map (<anonymous>)
    at clone (ngx-formly-core.mjs:165:31)
    at ngx-formly-core.mjs:180:28
  
  
Please note when I remove the formControl binding, the error goes away.

*******************************

Version used:-
Angular: 16.2.12
"primeng": "~16.3.1",
"@ngx-formly/core": "^6.1.0",
 "@ngx-formly/primeng": "^6.0.0",

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-primeng

Thanks!

**Comment by aitboudad** [comment]
Feel free to leave a comment once you've got a reproduction example, thanks!
