### ISSUE TITLE
Browser crashes when select is used with multiple: true or inside fieldArray/fieldGroup

### ISSUE THREAD

**Issue by johannesjo** [ngx-formly/ngx-formly#3943]
**Description**
I am just in the process of migrating to angular 18 from v 14 (painful ;)) and to formly 6. I ran into an issue where choosing an select option with `multiple: true`  leads to the browser hanging and not accepting any inputs any more.

This is the form config:
https://github.com/johannesjo/super-productivity/blob/upgrade-ng/src/app/features/config/form-cfgs/simple-counter-form.const.ts

**Minimal Reproduction**
1. checkout repo from above. 
2. checkout upgrade-ng branch
3. run npm i
4. run ng serve
5. navigate to setings
6. navigate to "Simple Counter"
7. Click on "Add Simple Counter"
8. BOOOOOOM

**Your Environment**

- Angular version: 18.0.4
- Formly version: 6.3.4

**Additional context**
Might be related to this:
https://github.com/ngx-formly/ngx-formly/issues/3941

**Comment by johannesjo** [comment]
oh seems to be my own fault. Sorry for the inconvenience!

**Comment by aitboudad** [comment]
The `onModelChange` method causes an infinite recursion (I'll check it further later) but for now you may try to use a simple assign:

```patch
onModelChange(changes: SimpleCounterConfig): void {
-  this.editModel = { ...changes };
+  this.editModel = changes;
}
```

https://github.com/johannesjo/super-productivity/blob/upgrade-ng/src/app/features/simple-counter/simple-counter-cfg/simple-counter-cfg.component.ts#L72

**Comment by johannesjo** [comment]
Thank you very much! Just figured it out this second xD

**Comment by aitboudad** [comment]
> Thank you very much! Just figured it out this second and was about to close this xD

Aha, so we worked on the same part Today 😄. Thanks! 

> Not sure why this didn't occur before though.

Not sure, but what I've noticed is probably related to hide expression.
