### ISSUE TITLE
How to highlight a particular field in the form

### ISSUE THREAD

**Issue by dev-kanishk** [ngx-formly/ngx-formly#3945]
Hey, I want to highlight a particular field in the form base on the json path. Is there any method on the root form config that I can use ?

**Comment by aitboudad** [comment]
use `field.get('field_path')` to get the particular field which you can edit or pass a specific property to highlight it.

**Comment by dev-kanishk** [comment]
I tried that but this doesn't work if the form is not rendered.

**Comment by aitboudad** [comment]
You may try to rely on `onInit` or `afterViewInit` hooks for example but it depends on the use-case
