### ISSUE TITLE
How to use web worker in formly

### ISSUE THREAD

**Issue by dev-kanishk** [ngx-formly/ngx-formly#3946]
Hey, my forms are deeply nested and very long. I want to use web worker for the form config generation and updates. I know we can use web worker for initial config generation but how to use web worker when array add operation take place. since it will also be building the the form config for nested structure.

**Comment by aitboudad** [comment]
The same way you did for initial config generation, for FieldArray for example you can override/wrap `add` / `remove` method of the `FieldArray` class.
In case you've tried it and didn't work for you, please share an example of the initial config generation so we can check it.
