### ISSUE TITLE
Any util for converting the json form path to labels path.

### ISSUE THREAD

**Issue by dev-kanishk** [ngx-formly/ngx-formly#3947]
I have a use case where we have server side validations on json data. server provides the json path for the error. I want to show user the fields labels under which the error is present. 

for example in the data:

```
{
 a: {
   b: "someValue";
 }
}
```

incase the "someValue" has the error, server returns the json path: a -> b

I want to show the users the list of errors and the field labels under which error has occurred, example:

```
aLabel -> bLabel value has error
```

I want to show users the label because that what they see in the form fields.

**Comment by kenisteward** [comment]
In formly 6 I thought there was a util that allows you to get form field by
key.

I'm on my phone right now so it's harder to look up the util

**Comment by aitboudad** [comment]
You've two options:

- use `errorPath`: The property `errorPath` allow passing the error from the parent field and Formly will try to map the error with the specified path. Example: `control.setError({.errorPath: 'address.city', message: 'this field is required' })`
- use `get` method: as mentioned by @kenisteward, you can retrive the child field using `get` method. Example: `field.get('address.city')`
