### ISSUE TITLE
Validation is not working with the most recent Angular version

### ISSUE THREAD

**Issue by avalchanin** [ngx-formly/ngx-formly#3948]
**Description**
Form validation does not work with the most recent Angular version [18.1.0-next.3](https://github.com/angular/angular/releases/tag/18.1.0-next.3)

**Minimal Reproduction**
Now formControl status is a getter based on a signal.
[Definition](https://github.com/angular/angular/blob/29ca6d10cc3cd75ebdf64658dafcb3ce579af343/packages/forms/src/model/abstract_model.ts#L594)
[Usecase](https://github.com/angular/angular/blob/29ca6d10cc3cd75ebdf64658dafcb3ce579af343/packages/forms/src/model/abstract_model.ts#L1343)

At the same time ngx_formly redefines formControl status getter and setter.
[Where](https://github.com/ngx-formly/ngx-formly/blob/61d695cfac722994c336e4c23939a75cb0aacf43/src/core/src/lib/components/formly.field.ts#L242)
[How](https://github.com/ngx-formly/ngx-formly/blob/61d695cfac722994c336e4c23939a75cb0aacf43/src/core/src/lib/utils.ts#L293)

As result, when `updateValueAndValidity` is executed, the custom setter is not called anymore, so even if there are any errors, the status remains "VALID".

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.5](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.5) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
