### ISSUE TITLE
timepicker angular matrial

### ISSUE THREAD

**Issue by khalifa005** [ngx-formly/ngx-formly#3949]
**Question**
how to add timepicker while using angular material any hints please

A clear and concise description of what the question is.

**Comment by aitboudad** [comment]
You may check the autocomplete type example : https://stackblitz.com/edit/angular-1icasm-qvvzdd?file=src%2Fapp%2Fapp.module.ts
for doc, please check https://formly.dev/docs/guide/custom-formly-field
