### ISSUE TITLE
Angular 17-Ngx formly -Custom validators not working with 6.3 version

### ISSUE THREAD

**Issue by Swethasri1512** [ngx-formly/ngx-formly#3954]
We have angular 17 application and we are using ngx formly 6.3.x version..Previously with angular 16 and ngx formly 5 version validators are working fine. 

With angular 17 and ngrx formly 6.3 version custom validators are not working. 

@aitboudad 

Please let me know if any workaround

**Comment by kenisteward** [comment]
I'm unaware of custom validators not working. 

Could you please provide a stack blitz showing the problem?

**Comment by aitboudad** [comment]
Feel free to leave a comment once you've got a reproduction example, thanks!
