### ISSUE TITLE
Enum with uniqueItems do not validate the form correctly.

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3958]
**Description**
With a field with "uniqueItems" property, the form is wrongly invalid.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-kwmyzs-bxq82b?file=src%2Fassets%2Fjson-schema%2Farrays.json

Deselecting and reselecting "aut" makes the form invalid, but it should not.

**Your Environment**

- Formly version: 6.3.5

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.6](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.6) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
