### ISSUE TITLE
Inconsistent Form State Due to Missing Return in Expression

### ISSUE THREAD

**Issue by enricouniurb** [ngx-formly/ngx-formly#3962]
I encountered an issue with the form related to the data_pensione field. The expression for hiding the field is currently implemented as follows:

```      
{
          key: 'data_pensione',
          type: 'date',
          className: 'col-md-3',
          templateOptions: {
            translate: true,
            label: 'd1_txt16',
            required: true,
          },
          expressions: {
            hide: (field: any) => {
              if ((field.model.specif_misura_ridotta !== 'D3A' && field.model.specif_misura_ridotta !== 'D3B') || (field.model.flag_misura_ridotta === 0 || field.model.flag_misura_ridotta === false)) {
                return true;
              }              
            },
          'templateOptions.required': (field: FormlyFieldConfig) => {
              return !field.hide;          
            } 
``` 

The expression does not explicitly return a value when the condition is not met, leading to an inconsistent state in the form without any error messages. As shown in the attached figure, there is a field error, but the form is still marked as valid.

![image](https://github.com/user-attachments/assets/394ecf7c-d66b-447e-b1c9-ef967e234b4c)

To resolve this issue, we need to ensure that the function always returns a boolean value. I modified the expression to explicitly return false when the conditions are not met, and it works as expected:

```       
expressions: {
            hide: (field: any) => {
              if ((field.model.specif_misura_ridotta !== 'D3A' && field.model.specif_misura_ridotta !== 'D3B') || (field.model.flag_misura_ridotta === 0 || field.model.flag_misura_ridotta === false)) {
                return true;
              } 
              return false;             
            },
           'templateOptions.required': (field: FormlyFieldConfig) => {
              return !field.hide;          
            }
```

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.8](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.8) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by aitboudad** [comment]
@aghosh-evertz I think its an issue with Typescript somehow, the main goal here is to warn user to return a boolean which does for regular case such as the following example:

![image](https://github.com/user-attachments/assets/1164c4ac-e804-4d0a-b06a-8b56f529da17)

**Comment by aghosh-evertz** [comment]
I believe this error started coming post 6.3.8 release. Prior to that, we didn't have such issues. For now, I had to explicitly provide a default return statement at the end of the 'hide' expression to make it work. 

This might break all the existing hide expressions which has conditional return statements only.

**Comment by aitboudad** [comment]
Return undefined for hide expression may provide an inconsistant result thats why we push that fix in a minor version. Anuway I'll try to revert it in the upcoming release and move the fix to v7
