### ISSUE TITLE
Migration to V6

### ISSUE THREAD

**Issue by siari1** [ngx-formly/ngx-formly#3963]
Hi,

We have a form interface **A** that extends FormlyFormOptions.
Another interface B has an object called **_options_** of the type **A**. We are passing form properties to the _options_, one of them is propsArray.

Though this code is working in V5, it is throwing the following error in V6

            TypeError: Cannot redefine property: propsArray
                at Function.defineProperty (<anonymous>)
                at observe (ngx-formly-core.mjs:234:20)
                at observeDeep (ngx-formly-core.mjs:195:22)
                at ngx-formly-core.mjs:200:32

Any suggestions what I can do about this ?

Thanks.

**Comment by aitboudad** [comment]
Hi,
could you please provide a minimal example to reproduce the issue, you can use the following starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!

**Comment by siari1** [comment]
Hi @aitboudad, we were able to fix it within our code. Thank you.
