### ISSUE TITLE
mat-autocomplete panel is not attached to mat-form-field 

### ISSUE THREAD

**Issue by tHe-AK** [ngx-formly/ngx-formly#3964]
**Description**
When using mat-autocomplete along with mat-chip, the mat-autocomplete list panel is not attached to the form-field container. Instead, it is attached to the mat-input field, whereas it works fine in the material official example.

**Minimal Reproduction**
https://stackblitz.com/edit/ng-material-chips-formly-2uu8sv

**Screenshots**
![image](https://github.com/user-attachments/assets/25b8b3bc-c858-4319-9f9a-13d0427a3f73)
ngx-formly

![image](https://github.com/user-attachments/assets/0c85d58d-1239-4f0f-9353-20736fa985ca)
v17 material example( https://v17.material.angular.io/components/chips/examples#chips-autocomplete )  

**Your Environment**

- Angular version: 17
- Formly version: 6.3.6

**Comment by aitboudad** [comment]
You should assign `formField` to `MatAutocompleteTrigger`, please check https://github.com/ngx-formly/ngx-formly/pull/1391/files
