### ISSUE TITLE
v6 hidden field CSS styling

### ISSUE THREAD

**Issue by siari1** [ngx-formly/ngx-formly#3965]
Hi, 

In our application when a field is hidden, we are modifying CSS styling of that field from _display:none_ to _visibility:hidden_ to retain the column width. This is to avoid any right-side columns moving into left side columns when there are hidden fields.

After V6 upgrade, this CSS styling is not getting applied to the hidden fields. We tried updating hideExpression to hide, passed resetOnHide:false 

Is there something on the Formly end that might be overriding the CSS of hidden fields? Any suggestions are appreciated. 

Thank you

**Comment by aitboudad** [comment]
see https://formly.dev/docs/guide/migration#5-lazy-render-is-enabled-by-default
