### ISSUE TITLE
Validation still not working in Angular 18.1

### ISSUE THREAD

**Issue by create-signal** [ngx-formly/ngx-formly#3972]
**Description**
In the reproduction below, both the email and password field are required. Filling the email field and clicking submit without touching the password field would previously (prior to Angular 18.1) show the validation message on the password field.

Additionally, form.markAllAsTouched() and form.get('password').markAsTouched() have no effect.

Touching the email field again will trigger change detection and finally show the message.

**Minimal Reproduction**

https://stackblitz.com/edit/g3rvwa?file=src%2Fapp%2Fapp.component.ts

**Your Environment**

- Angular version: 18.1.3
- Formly version: 6.3.6

**Comment by leecn9853** [comment]
I also encountered the same problem. Had to roll back to version 17

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.7](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.7) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
