### ISSUE TITLE
primeng props not passed

### ISSUE THREAD

**Issue by its-dibo** [ngx-formly/ngx-formly#3973]
when using `FormlyPrimeNGModule` not all props are passed to the original primeng field

for example the primeNg dropdown accepts the props `optionLabel` and `optionValue`
but formly doesn't pass them to primeNg

```
{
 key:'country',
 type: 'select',
 props:{
   optionLabel: 'title', 
   options: [
       { value: 'usa', title: 'united states' }
 ]
}
```

using optionLabel we don't need to msp all items into `{ label, value }`

**Comment by aitboudad** [comment]
instead you can use `labelProp` and `labelProp`:
```
valueProp: 'id',
labelProp: 'title',
```

**Comment by its-dibo** [comment]
> instead you can use `labelProp` and `labelProp`:
> 
> ```
> valueProp: 'id',
> labelProp: 'title',
> ```

is this a standard prop in Primeng, or it is belongs to formly? I couldn't find a reference to it in formly docs
