### ISSUE TITLE
Nested array ignores default value

### ISSUE THREAD

**Issue by jma** [ngx-formly/ngx-formly#3974]
**Description**
When an array contains an array, the default value is ignored.

**Minimal Reproduction**

In the following example an array at the root level takes the default value into account. The "Nested Array2" don't.
https://stackblitz.com/edit/angular-hb4vkw?file=src%2Fassets%2Fjson-schema%2Farrays.json

**Your Environment**

- Formly version: 6.3.6

Many thanks in advanced.

**Comment by aitboudad** [comment]
Default value is only set when the value is undefined, if pass undefined or empty object `default: [{}]` to `array1` it should work.

**Comment by aitboudad** [comment]
https://stackblitz.com/edit/angular-hb4vkw-qjzp8n?file=src%2Fassets%2Fjson-schema%2Farrays.json
