### ISSUE TITLE
`TypeError: Cannot read properties of undefined (reading '_observers')` when using <formly-field> with a custom FormlyFieldConfig.

### ISSUE THREAD

**Issue by shrezaaa** [ngx-formly/ngx-formly#3977]
**Description**
I am working on an Angular project where I want to manually render a single field using <formly-field> or a group of fields using  for better control over styling and layout.

When attempting to use <formly-field> to render a single field, I encountered the following error:

```javascript
TypeError: Cannot read properties of undefined (reading '_observers')
    at observe (@ngx-formly_core.js:296:10)
    at observeDeep (@ngx-formly_core.js:278:20)
    at FormlyField.fieldChanges (@ngx-formly_core.js:1068:98)
    at FormlyField.triggerHook (@ngx-formly_core.js:982:43)
    at FormlyField.ngOnInit (@ngx-formly_core.js:921:10)
    ...
```

**Your Environment**

- Angular version: 18.0.5
- Formly version: 6

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-bootstrap

Thanks!
