### ISSUE TITLE
NgFormly 6+ not working as expecting after upgrading to angular 16

### ISSUE THREAD

**Issue by raviteja8831** [ngx-formly/ngx-formly#3978]
Recently we upgraded the app from angular 11 to angular 17. As App is working fine with Formly5+ upto angular15, After upgrading to angular16, formly 6 is not working as expecting, not even showing errors. Please let us know any suggestions or any fixes

**Comment by raviteja8831** [comment]
Change detection not happening properly

**Comment by aitboudad** [comment]
A reproduction is needed in order to further check your issue 🙏 , also please ensure to check our migration guide: https://formly.dev/docs/guide/migration
