### ISSUE TITLE
required validation  in multicheckbox, where type='multicheckbox' instead of 'array'

### ISSUE THREAD

**Issue by tonedeafcoder** [ngx-formly/ngx-formly#3979]
**Description**
Require validation works in the first time when no value is added for multicheckbox, on updating it doesn't
We are saving multicheck box value as a JSON string in db like
"{ "a":"true"}", so we cannot use type 'array' at the moment.

https://stackblitz.com/...

**Your Environment**

- Angular version: 9.13
- Formly version: 5.10

@aitboudad can you please help on this

**Comment by aitboudad** [comment]
required only detect if the field has value or not, so instead I do suggest to define a custom validation.
