### ISSUE TITLE
items > anyOf with different primitive types not rendered

### ISSUE THREAD

**Issue by simnado** [ngx-formly/ngx-formly#3980]
**Description**

to validate an array with different primitive types like `[1, 'string']` I need to to define arrays like
```
properties: {
   my_array_fail: {
      title: 'Failing',
      items: {
        anyOf: [
          {
            type: 'number',
          },
          {
            type: 'string',
          },
        ],
      },
      type: 'array',
    },
```

but formly seems to only support item > anyOf with object-like items like:

```
my_array_ok: {
      title: 'Working:',
      items: {
        type: 'object',
        anyOf: [
          {
            properties: {
              num: {
                type: 'number',
              },
            },
          },
          {
            properties: {
              str: {
                type: 'string',
              },
            },
          },
        ],
      },
      type: 'array',
    }
```

which will result in another format like `[{num: 1}, {str: 'string'}]`. Both should be valid json schema.

**Minimal Reproduction**

https://angular-ejt321-njzkzs.stackblitz.io

**Your Environment**

- Angular version: 18+
- Formly version: 6+

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.8](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.8) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
