### ISSUE TITLE
Can you fully create forms only based off a JSON string from a DB request?

### ISSUE THREAD

**Issue by fl4kez** [ngx-formly/ngx-formly#3991]
Can you fully create forms only based off a JSON string from a DB request?

Title. Like I mean full functionality like customValidators etc. Since those are actual code it wouldnt work by passing a string containing the function right?

**Comment by aitboudad** [comment]
Yes, the recommanded approach is to use JSON schema https://formly.dev/docs/guide/json-schema/.
In case you would like to maintain you own format it may require some adjustments which depends on your needs.

- For passing validation as a string you may check `validators.expression` example  https://formly.dev/docs/examples/validation/custom-validation
- https://formly.dev/docs/examples/other/json-powered/
