### ISSUE TITLE
Input label not floating when value is zero

### ISSUE THREAD

**Issue by rothattack** [ngx-formly/ngx-formly#3992]
![image](https://github.com/user-attachments/assets/fd91be65-2333-4fd2-a2fc-06d356552769)
Upgraded to v17 of Angular from v15, and now i see on my text inputs that the material label do not float/shrink
any longer when value is set to zero. Anything i forgot or missed that i need to do? Thank you.

NOTE: only happens when field is untouched

- Angular version: 17x
- Formly version: 6x

**Comment by aitboudad** [comment]
Hi,
could you please provide a reproduction, here is our `stackblitz` starter example:
https://stackblitz.com/edit/ngx-formly-ui-material

Thanks!
