### ISSUE TITLE
Dirty / pristine changes for form arrays don't propagate correctly

### ISSUE THREAD

**Issue by amdor** [ngx-formly/ngx-formly#3996]
**Description**
### Expected
When you have a simple FormControl and change the value for the first time (from UI),  by the time `valueChanges` Observable emits, the form has `pristine` false, as is correct.

### Formly FieldArrayType
When you have a form with repeat elements present by default, then removing one will not count as a UI form interaction, hence `markAsDirty` is required. Formly does call `markAsDirty`, but only _after_ the value has been changed.

### Note
In Angular 18 we have `events` Observable to circumvent this issue, but earlier versions don't have it, they need all sorts of monkey patches for `markAsDirty`, because the only listener there is `valueChanges`, at which point `pristine` is still true.

**Minimal Reproduction**
https://stackblitz.com/edit/stackblitz-starters-yprck4?file=src%2Frepeat-section.type.ts

**Comment by amdor** [comment]
Actually it's both `add` and `remove` [link](https://github.com/ngx-formly/ngx-formly/blob/0a3f2bfa73f290902f19d948a428774e3f3d269e/src/core/src/lib/templates/field-array.type.ts#L44-L65), and the same happens in [select](https://github.com/ngx-formly/ngx-formly/blob/0a3f2bfa73f290902f19d948a428774e3f3d269e/src/ui/material/select/src/select.type.ts#L97-L98)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.8](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.8) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
