### ISSUE TITLE
PrimeNG FormlyFieldSelect doesn't trigger compareWith

### ISSUE THREAD

**Issue by Et3rnal** [ngx-formly/ngx-formly#3997]
**Description**
I tried bootstrap and it works fine, however PrimeNG FormlyFieldSelect doesn't trigger compareWith

**Your Environment**

- Angular version: 15
- Formly version: 6.1.8

**Additional context**
I believe a similar issue found many years ago in one of my cards :D

**Comment by aitboudad** [comment]
We rely on https://primeng.org/dropdown component which doesn't support passing `compareWith` input at the moment If I'm not wrong 🤔

**Comment by Et3rnal** [comment]
Yep, it seems to select an object will need `patchValue(...)` to pass the property defined by `optionValue` on the Dropdown. Can you suggest an ngx workaround? Im thinking of using hooks
