### ISSUE TITLE
label length text under fieldgroup is truncated

### ISSUE THREAD

**Issue by dorianvieira** [ngx-formly/ngx-formly#3998]
Hello,
I've noticed that the text under the 'label' is truncated when the size of the string exceeds a certain number of chars. I'd like the text not to be truncated.
![Screenshot 2024-10-07 11 51 05](https://github.com/user-attachments/assets/8d28fed3-2eeb-46a2-88c5-79141a85a9ee)
![Screenshot 2024-10-07 11 49 29](https://github.com/user-attachments/assets/7c9d013e-c701-4db0-8d7a-228b7ff0b439)
I didn't find any solution or property to edit to avoid this behavior! 
Thanks

**Comment by aitboudad** [comment]
Its not truncated from Formly side at all, you may use CSS to customize it on your end.
