### ISSUE TITLE
reusable component for custom type

### ISSUE THREAD

**Issue by umeshjain1999** [ngx-formly/ngx-formly#4000]
I have a component which is already being used at different places (not with formly). So, I have modified the component to make it compatible with formly which is working perfectly fine but giving problem at places where formly is not used. Is there any practices to follow to modify these components so it should be compatible with or without formly use cases.

**Comment by aitboudad** [comment]
Formly require to extends `FieldType` unless this part is satified I don't see any issue with using it without formly so you may try and see if there is any limitations that needs to be adressed from our side..
