### ISSUE TITLE
Error Property not assegnable fieldconfig.d.ts

### ISSUE THREAD

**Issue by MassimilianoOreto** [ngx-formly/ngx-formly#4001]
**Description**
After update to Formly 6.3.8 with Angular 18.2.8 when i run build, i have this error:

Error: node_modules/.pnpm/@ngx-formly+core@6.3.8_@angular+forms@18.2.8_@angular+common@18.2.8_@angular+core@18.2.8_rxjs_l7h432ghykbabka76egm4kfqla/node_modules/@ngx-formly/core/lib/models/fieldconfig.d.ts:99:9 - error TS2411: Property 'className' of type 'ExpressionType<string> | undefined' is not assignable to 'string' index type 'ExpressionType<any>'.

**Your Environment**

- Angular version: 18.2.2
- Formly version: 6.3.8

**Additional context**
Same error on this interface:

        className?: ExpressionType<string>;
        hide?: ExpressionType<boolean>;
        'props.disabled'?: ExpressionType<boolean>;
        'props.required'?: ExpressionType<boolean>;

**Comment by aitboudad** [comment]
Hi, 
I've tested with the latest Angular version but I'm unable to reproduce it.

Could you please provide us your tsconfig / Typescript version and the field config that raise the issue ?
Thank you!

**Comment by enockkim** [comment]
Im experiencing the same issue, here is my tsconfig

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "module": "ES2022",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "ES2022",
    "typeRoots": ["node_modules/@types"],
    "lib": ["ES2022", "dom"],
    "paths": {
      "@core": ["app/core"],
      "@core/*": ["app/core/*"],
      "@shared": ["app/shared"],
      "@shared/*": ["app/shared/*"],
      "@theme": ["app/theme"],
      "@theme/*": ["app/theme/*"],
      "@testing": ["testing"],
      "@testing/*": ["testing/*"],
      "@env": ["environments"],
      "@env/*": ["environments/*"]
    },
    "useDefineForClassFields": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}


"typescript": "~5.4.2"

**Comment by aitboudad** [comment]
I'm able to reproduce it now, we'll provide a fix soon!

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.9](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.9) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
