### ISSUE TITLE
Complex nested array field structure along with conditionally hidden fields breaks the default field values

### ISSUE THREAD

**Issue by aghosh-evertz** [ngx-formly/ngx-formly#4002]
I thoroughly enjoy using Formly. Thanks for the library @aitboudad and all the other wonderful contributors :)
**Question**

I am unable to see the default values in my formly form which is pretty much nested and is a bit complex with hidden fields and array fields as well.

Created a minimal reproduction of the issue here:
https://stackblitz.com/edit/angular-hc1aib-1vqznu?file=src%2Fapp%2Fapp.component.ts,src%2Fassets%2Fjson-schema%2Fnested.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

Note: In the example, I am somehow unable to hide below field:
1. The 'ENCODER' field group should be hidden and should only be shown when you select 'DVB Teletext Encoder' from the 'Data Services' list. If the 'ENCODER' field is not hidden, it works fine.

Issue:
When you select 'DVB Teletext Encoder', the 'ENCODER' field group will become visible. Inside that, you will find 'Pages' array field. Try adding a 'page' by clicking on '+' button. Mostly all the fields inside the 'page' array are having default value, which are added through schema. But you will find that the default values are not shown in the field. 

Let me know if you need any more information on this.

**Comment by aitboudad** [comment]
> The 'ENCODER' field group should be hidden and should only be shown when you select 'DVB Teletext Encoder' from the 'Data Services' list. If the 'ENCODER' field is not hidden, it works fine.

use `oneOf` https://formly.dev/docs/examples/advanced/json-schema


> But you will find that the default values are not shown in the field.

I'm unable to find the isssue, could you please provide the field that the value is not shown?

**Comment by aghosh-evertz** [comment]
Its the boolean checkbox fields, which doesn't show the default values coming from the schema.

**Comment by aitboudad** [comment]
I see it now, I'll check it further later this week and provide a fix if needed.

**Comment by aghosh-evertz** [comment]
I have updated the code in the link:
https://stackblitz.com/edit/angular-hc1aib-1vqznu?file=src%2Fapp%2Fapp.component.ts,src%2Fassets%2Fjson-schema%2Fnested.json,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html


When you click '+' for PAGES array field, all the fields inside (**'Default Character Set', 'Send Cleardown', 'Double Transmit'**) , are having 'defaultValue' (passed through the schema). But it is not reflected in the form.

**Comment by aghosh-evertz** [comment]
Thanks @aitboudad , I am already using 6.3.7 . Do I need to make any changes in my application ? I still see the issue in the reproduction example .

**Comment by aitboudad** [comment]
@aghosh-evertz The fix will be included in our next release, we'll inform you once done.

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.10](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.10) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by aghosh-evertz** [comment]
Working great now !! Thankyou @aitboudad for the bug fix and release.
