### ISSUE TITLE
TypeError: value.constructor is undefined

### ISSUE THREAD

**Issue by ColinFrick** [ngx-formly/ngx-formly#4008]
**Description**
I'm trying to implement a new custom field type for Tiptap Editor. We are using JSONContent as the model for this field.
When using any nodes like h1, h2, bullet list, etc. formly throws the error `TypeError: value.constructor is undefined`
![CleanShot 2024-10-16 at 12 47 20](https://github.com/user-attachments/assets/05d54672-4826-4c6b-985e-c5c7dc045123)

This is because the nested `attrs` object inside the JSONContent object has no constructor. 
ProseMirror Model uses `Object.create(null)` to create an empty attrs object, which does not add a constructor:
https://github.com/ProseMirror/prosemirror-model/blob/bcc58d66ce1ca6bae64d62fba137fe0eb1a8b3d7/src/node.ts#L8

Caused by:
https://github.com/ngx-formly/ngx-formly/blob/2cc49f41012bba8ff3d1617a42abbec87dad12f3/src/core/src/lib/utils.ts#L159

**Your Environment**

- Angular version: 18.2.7
- Formly version: 6.3.7

**Additional context**

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.10](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.10) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!

**Comment by ColinFrick** [comment]
@aitboudad Thank you so much for the bug fix and release. Works great!
