### ISSUE TITLE
Will unsafe-eval of CSP (Content-Security-Policy) be supported in the future? If so, can you tell me when?

### ISSUE THREAD

**Issue by lelanLi** [ngx-formly/ngx-formly#4010]
nginx:  Content-Security-Policy: script-src 'self' 'unsafe-eval'
![Uploading image.png…]()
src\core\src\lib\extensions\field-expression\utils.ts 的evalStringExpression方法
code:  return Function(...argNames, `return ${expression};`) as any;
error: Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src chrome://resources chrome://webui-test 'self'".

**Comment by lelanLi** [comment]
![image](https://github.com/user-attachments/assets/c4b09f09-ecb3-4b93-82e0-5220bdf9cf34)

**Comment by lelanLi** [comment]
![image](https://github.com/user-attachments/assets/71e60a97-a51b-4101-a35b-3d1d866851b7)

**Comment by lelanLi** [comment]
https://github.com/ngx-formly/ngx-formly/issues/3986
https://github.com/ngx-formly/ngx-formly/issues/2537
I've searched for similar issues, but haven't found a solution.

**Comment by aitboudad** [comment]
Duplicate of #2537
