### ISSUE TITLE
Updates to formState not reflected

### ISSUE THREAD

**Issue by Joxeur2** [ngx-formly/ngx-formly#4012]
**Description**
I'm having trouble disabling the entire form at once. After searching online, I found that I should use formState for this purpose. However, when I followed the example on the website, it didn't work as expected.

While the initial state of formState is correctly applied, any subsequent updates to formState are not reflected.

I saw some bugs about this kind of things, but they where all supposed to be resolved.

**Minimal Reproduction**

Just go to https://formly.dev/docs/examples/form-options/form-state and click toggle.

**Your Environment**

- Angular version: 18.2.1
- Formly version: 6.3.10

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
