### ISSUE TITLE
Change in form state not updated

### ISSUE THREAD

**Issue by DSailokesh** [ngx-formly/ngx-formly#4018]
Description
In version 6.3.0 changes in form state are not properly detected. When toggling the state in the example the field disabled state is not updated until you type a character in one of the input fields.

Minimal Reproduction
The example is based on the official formly [example](https://main.formly.dev/examples/form-options/form-state) with one extra field.

https://stackblitz.com/edit/s3xrak?file=package.json,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

Your Environment

Angular version: 14.0.6
Formly version: 6.3.10

**Comment by DSailokesh** [comment]
@beeman I have observed that there is a recent change in "src/core/src/lib/components/formly.field.ts" on change detection in subscribes  

 **observeDeep(field, ['options', 'formState'], () => field.options.detectChanges(field))**. 

I think it was supposed to be **observeDeep(field.options, ['formState'], () => field.options.detectChanges(field))**.

![Screenshot 2024-11-07 185900](https://github.com/user-attachments/assets/aebb2980-9091-4563-8397-c44cf52b2085)

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
