### ISSUE TITLE
Formly slider throwing error when sliding

### ISSUE THREAD

**Issue by johannesjo** [ngx-formly/ngx-formly#4019]
**Minimal Reproduction**
https://stackblitz.com/edit/ngx-formly-ui-material-wf1q4j?file=package.json

**Your Environment**

- Angular version: 18.Y.Z
- Formly version: 6.3.10

**Additional context**
When using the slider I get the following error:
```
zone.js:159 Uncaught TypeError: Cannot read properties of undefined (reading 'set') at _MatSlider._updateValueIndicatorUI (slider.mjs:892:50) at _MatSlider._onValueChange (slider.mjs:798:10) at MatSliderThumb._fixValue (ngx-formly-material-slider.mjs:432:20) at ngx-formly-material-slider.mjs:413:12 at timer (zone.js:1702:27) at _ZoneDelegate.invokeTask (zone.js:353:171) at _ZoneImpl.runTask (zone.js:156:37) at invokeTask (zone.js:430:26) at ZoneTask.invoke (zone.js:419:38) at data.args.<computed> (zone.js:1684:26)</computed>
```

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.11](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.11) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
