### ISSUE TITLE
createFieldComponent broken in Angular 19

### ISSUE THREAD

**Issue by json-derulo** [ngx-formly/ngx-formly#4020]
**Description**
In Angular 19, [standalone is the new default](https://blog.angular.dev/the-future-is-standalone-475d7edbc706). When using the `createFieldComponent()` function from `@angular/core/testing` in an Angular 19 project, the following error is thrown:

>Error: Unexpected "TestComponent" found in the "declarations" array of the "TestBed.configureTestingModule" call, "TestComponent" is marked as standalone and can't be declared in any NgModule - did you intend to import it instead (by adding it to the "imports" array)?

The reason is that with Angular 19 this component is now standalone. However the tooling expects a non-standalone component, so we need to explicitly mark this component as `standalone: false`.

**Minimal Reproduction**

I can create a minimal reproduction if necessary, but I think the issue is clear.

**Your Environment**

- Angular version: 19.0.0
- Formly version: 6.3.10

**Additional context**
n/a

**Comment by json-derulo** [comment]
I tried to fix the issue with the linked commit, but the tests fail because the workspace is still on Angular 13, which doesn't support the `standalone` component metadata property. The workspace needs to be updated to Angular 14 first, which is probably a breaking change.

**Comment by aitboudad** [comment]
> The workspace needs to be updated to Angular 14 first, which is probably a breaking change.

Yes, I think we need to make a new Major version. I've updated our codebase to Angular 16. Remains some tests to fix before I'll be able to push.
I'll update you once done (mostly at the end of this week. so you'll be able to check this issue.

**Comment by json-derulo** [comment]
Thanks. I create a draft PR #4021. This changes should work in Angular 16.
