### ISSUE TITLE
Async validator extension, form value keeps old not updated value

### ISSUE THREAD

**Issue by bmickoski** [ngx-formly/ngx-formly#4022]
**Description**
When using extension to add async validator i need to get some value from another control. If i get value from field.form.control.get('controlName') it still have old one.  If i get from control.value it is fine (but then again in some scenarios i need to get value from another field.

**Minimal Reproduction**

https://stackblitz.com/edit/angular-wvqt9t

Just click on some radio button. Enter value in input field and in console log we will have previous values for input and radio buttons.

**Your Environment**

- Angular version: 17.1.3
- Formly version: 6.1.1

**Additional context**

**Comment by aitboudad** [comment]
It'll not work properly because when the validation will only be trigged when the field value is changed not other field. The proper solution for a such case can be found in the doc https://formly.dev/docs/examples/validation/matching-two-fields

**Comment by bmickoski** [comment]
Okay so @aitboudad  if i go with that approach:

add validator:
` validators: [
            {
                name: 'existingEntityValidation',
                validation: (
                    control: FormControl,
                    field: FormlyFieldConfig,
                    options: any
                ): Observable<{ existingEntityValidation: { msg: null | string } } | null> => {
                    return validationService.validateExistingEntity(field, control, options);
                },
            },
        ],`
        
 service validation:
 
 ` validateExistingEntity(
        field: FormlyFieldConfig,
        control: AbstractControl<any, any>,
        options: any
    ): Observable<{ existingEntityValidation: { msg: null | string } } | null> {
        if (options.apiPath) {
            let value = control.value[options.fieldValue];
            // Set invalid error true so user won't be able to click
            // save button until api call is finished
            // fieldControl.setErrors({ invalid: true });
            let additionalQuqeryParam = null;
            // const propertyKey = field.props?.['existingEntityValidationPropName'] || null;
            if (options.existingEntityValidationAdditionalParamControlValue) {
                const additionalPropValue = options.existingEntityValidationAdditionalParamControlValue;
                const additionalPropKey = options.existingEntityValidationAdditionalParamControlKey;
                value = control.value[additionalPropValue];
                additionalQuqeryParam = {
                    [additionalPropKey]: value,
                };
            }
            return this.checkForExistingEntityByIdentifier(options.apiPath, value, null, additionalQuqeryParam).pipe(
                map((res) => {
                    // Remove invalid: true error used for disabling button
                    // until api call is finished
                    if (res.exists) {
                        // fieldControl.setErrors({
                        //     existingEntityValidation: { msg: res.messageCode },
                        // });
                        return { existingEntityValidation: { msg: res.messageCode } };
                    } else {
                        // fieldControl.setErrors(null);
                        return null;
                    }
                })
            );
        } else {
            return of(null);
        }
    }`       
    
    and just add validator at root 
    
    `
    "fields": [
        {
            "validators": {
                "validation": [
                    {
                        "name": "existingEntityValidation",
                        "options": {
                            "errorPath": "insuranceCarrierId",
                            "apiPath": "insuranceCarriers",
                            "existingEntityValidationAdditionalParamControlValue": "idType",
                            "existingEntityValidationAdditionalParamControlKey": "identifierType",
                            "fieldValue": "insuranceCarrierId"
                        }
                    }
                ]
            }....
    `
    
    how can i set this to be async validator to be invoked? Right now with this approach is not async.

**Comment by aitboudad** [comment]
@bmickoski did you try to pass it to `asyncValidators`:

```json
"fields": [
    {
        "asyncValidators": {
            "validation": [...]
        }
   }
]
```

**Comment by bmickoski** [comment]
@aitboudad  yeah.. i add 

```
 "asyncValidators": {
                "validation": [
                    {
                        "name": "existingEntityValidation",
                        "options": {
                            "errorPath": "insuranceCarrierId",
                            "apiPath": "insuranceCarriers",
                            "existingEntityValidationAdditionalParamControlValue": "idType",
                            "existingEntityValidationAdditionalParamControlKey": "identifierType",
                            "fieldValue": "insuranceCarrierId"
                        }
                    }
                ]
            },
```

but validator it not executing at all in this way.

**Comment by bmickoski** [comment]
@aitboudad yeah i added and seems to work. But thing is.. i have other required/custom validators fields.. and i want this  async validator to be invoked whenever user change any of this two fields. 

I updated stackblitz example:

https://stackblitz.com/edit/angular-wvqt9t

Added one more field3 which is required. So if we choose only option from radio button and enter value in field 2, validator won't be invoked until user also select field 3...  I know that async validators are invoked only when form state (invalid -> valid) is changed.. but do you have some suggestion how i can achieve this for my use case?
