### ISSUE TITLE
Validate custom file upload control on form submit.

### ISSUE THREAD

**Issue by tHe-AK** [ngx-formly/ngx-formly#4026]
I've developed a custom form control for file uploads, and while the validations function correctly when a file is uploaded or removed, they fail to trigger upon form submission. I have prepared a Stackblitz to demonstrate my current approach. Could you please help identify what I might be doing wrong? 

Additionally, I would appreciate any suggestions for improving the existing setup. Thank you!

Stackblitz: 
https://stackblitz.com/edit/ngx-formly-ui-material-guaenq

**Comment by bmickoski** [comment]
@tHe-AK  If you want validations to be shown like required lets say you need to add wrapper to your custom type:

```
  types: [
        {
          name: 'fileupload',
          component: FormlyFileupload,
          wrappers: ['form-field'],
        },
      ],
```

There are prebuild wrappers https://formly.dev/docs/guide/custom-formly-wrapper but you can also create custom one. 

` <formly-validation-message [field]="field"></formly-validation-message>`

this component handles showing this validation messages.

**Comment by tHe-AK** [comment]
Hi @bmickoski, I have explored `formly-validation-message` already and we are using it for other fields. I cannot use it for file upload as its design has errors at multiple levels (file level error[file size, file type], file category error[max, min files count], whole control level error[totalFilesSize]), which are to be displayed in different places.

**Comment by bmickoski** [comment]
So @tHe-AK i don't follow then... what is main problem? That you don't see required msg for example when you try to submit without uploaded file or i misunderstood you?

**Comment by bmickoski** [comment]
Oh i see.. you say that validations only works if you choose file otherwise they are not triggered when submitting.

**Comment by aitboudad** [comment]
You should use `form-field` wrapper, alos ensure to import `FieldType` from `@ngx-formly/material`.
You may check the following example https://stackblitz.com/edit/ngx-formly-ui-material-b9ahsaez
