### ISSUE TITLE
Validation doesn't work on Angular v19 (standalone=false)

### ISSUE THREAD

**Issue by zulis** [ngx-formly/ngx-formly#4027]
**Description**
Validation doesn't work on Angular v19 (standalone=false). Error message triggers when field is unfocused but not on form submit.

**Minimal Reproduction**
https://stackblitz.com/edit/stackblitz-starters-typhqj

**Environment**
- Angular version: 19.0.1
- Formly version: 6.3.11

**Additional context**
Here https://github.com/ngx-formly/ngx-formly/issues/3948 looks like was fixed for v18.1 but got broken again?

**Comment by aitboudad** [comment]
This issue has been fixed and released as part of [v6.3.12](https://github.com/ngx-formly/ngx-formly/releases/tag/v6.3.12) release.

Please let us know, in case you are still encountering a similar issue/problem.
Thank you!
