### ISSUE TITLE
Repeat section | Material UI | For Custom field within the Repeat section, the NgOnInit of the Custom Field is not getting called

### ISSUE THREAD

**Issue by thanecoder** [ngx-formly/ngx-formly#4029]
**For Custom field within the Repeat section, the NgOnInit of the Custom Field is not getting called**

- I have created a Repeat section custom type and an Autocomplete custom type. 
- Autocomplete custom type has a NgOnInit where a API call fetches the dropdown options. 
- Within the Repeat section, I have added one autocomplete type and other are normal inputs. 
- When I click on the Add button on Repeat section, all my form fields are rendered. But the options for the autocomplete type are not fetched.  
- Is there any way to trigger the NgOnInit of the fields in FieldArray of Repeat section ?

**Environment**

- Angular version: 15.0.0
- Formly version: 6.1.3

**Comment by aitboudad** [comment]
Please provide a reproduction, the ngOnInit is getting called https://stackblitz.com/edit/angular-ausquswe
For Autocomplete type example, please check: https://formly.dev/docs/ui/material
