### ISSUE TITLE
Required validation is not working as expected after migrating v5 to v6

### ISSUE THREAD

**Issue by vijhhh2** [ngx-formly/ngx-formly#4035]
**Description**
This is a bug which happens with multiple tabs.
Suppose if a field has required set to true in props, Initially required validation works and form is invalid.
Then you add some value to a required field. Now the form is valid.
Now if you remove the value in the required field the form is still valid.
It should be invalid.

**Minimal Reproduction**
https://stackblitz.com/edit/angular-wymqjb2u?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts

**Your Environment**

- Angular version: 18
- Formly version: 6.3.12

**Comment by aitboudad** [comment]
see https://formly.dev/docs/examples/advanced/tabs/
