### ISSUE TITLE
Problem with passing model in hideExpression when have fieldGroup

### ISSUE THREAD

**Issue by GetTaxSolutions** [ngx-formly/ngx-formly#704]
I have follow field definition:

```
    field1,
     field2, .....
{
      fieldGroupClassName: 'row',
      wrappers: ['panel'],
      key: 'Address',
      hideExpression: function (model: any, formState: any) {
        console.log('=================Start====================');
        console.log(model);
        console.log('=================End====================');
        if (model && model.DocumentCountryId) {
          return model.DocumentCountryId === "84865a19-c589-4af7-8972-982c8ac16e90"
        }
        return true;
      },
      templateOptions: {
        label: 'What is your home address?'
      },
      fieldGroup: [{
        className: "col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4",
        type: 'sInput',
        key: 'Street1',
        templateOptions: {
          placeholder: 'Street 1',
          label: 'Street 1'
        }
      },
      .....]
```

The problem here is that when I have fieldGroup with fields, the model in hideExpression callback is empty object and have no access to the model. Result in console:

> =================Start====================
>{}
>=================End====================

**Comment by aitboudad** [comment]
when `fieldGroup` is set and the `key` is present the passed model is `parentModel.key`, in your example it's `model.Address`.
in your case to access into the main model you have to use `formState` or use the `this.model` defined on your main component, see https://stackblitz.com/edit/angular-formly-6nvp4q

**Comment by GetTaxSolutions** [comment]
Thank you. I catch the idea. I had the same logic in formly for Angular 1.x and the context there was to main model. Here is changed. Thank you for resolving the issue.

**Comment by GetTaxSolutions** [comment]
Thank you for the info.

**Comment by jashanbhullar** [comment]
The above mentioned didn't work for me,  don't know why, 
But somehow I got this working by using:
```
hideExpression: () => {
   return this.editing;
}
```
where `editing` is variable set true when editing a form.

**Comment by juristr** [comment]
Hey,

the hideExpression has a parameter containing the model, so you can use
that one.

```
hideExpression: (model: any) => ...
```
-- 
Juri Strumpflohner
Google Developer Expert in Web Tech • https://juristr.com • @juristr on
Twitter

**Comment by intellix** [comment]
Having issues with this for my Expression QueryBuilder when trying to swap out the field containing an array. What I have looks like this:

```ts
export function createFormlyCondition(): FormlyFieldConfig[] {
  return [
    {
      key: 'condition',
      type: 'condition',
      fieldGroup: [
        {
          key: 'type',
          type: 'radio',
          defaultValue: ConditionType.USER_DATA,
          templateOptions: {
            required: true,
            placeholder: 'Condition',
            options: [
              { value: ConditionType.LOGICAL_OPERATOR, label: 'Logical Operator' },
              { value: ConditionType.NEGATE, label: 'Negate' },
            ],
          },
        },
        {
          key: 'fields',
          type: 'condition-fields', // change this to 'input' and the model is different
          hideExpression: model => model.type !== 'LOGICAL_OPERATOR',
          fieldArray: {
            fieldGroup: [],
          },
        },
      ],
    },
  ];
}
```

This gets called in multiple places and there's also nesting. I don't really have access to `this.model` because of those things.

Judging by the amount of linked issues it seems quite a common problem. Maybe the solution would be to pass a third parameter to hideExpression like:

```
hideExpression: (model, formState, key) => {}
```

If it contains a formArray then you also have the key passed, but the model would be the same regardless of type

**Comment by aitboudad** [comment]
`fieldArray` has the same behavior of `fieldGroup` (internally rely on fieldGroup), for now, you can pass the main model to the `formState`.

Passing the `field` as a third argument would be another solution which I would consider adding to the `V5.1`

**Comment by FritzHerbers** [comment]
> Passing the `field` as a third argument would be another solution which I would consider adding to the `V5.1`

Needed that today and used this.field in the expression. Is there something wrong when using it this way?

**Comment by aitboudad** [comment]
@FritzHerbers nop but it works only when passing a `string` expression, in case of a `function` expression there is no way to get the `field` instance. My plan is to deprecate `this.field` in favor of `field`.

**Comment by ssergdev** [comment]
Hi, does it possible to use string-expression related to parent model property, within `fieldGroup` / `fieldArray` ?
